Content-type: text/asciidoc
Abstract: Amikor egy sebezhetőséget jelentenek, ezeket az irányelveket
 követjük a sebezhetőség felmérésére, egy javítás elkészítésére és
 átnézésére, valamint az embargó alatti biztonsági kiadások koordinálására.

Hogyan koordináljuk az embargó alatti kiadásokat
------------------------------------------------

Hogy megvédjük a Git felhasználóit a kritikus sebezhetőségektől, nem csak
kiadunk javított verziókat, mint a szokásos maintenance release-eknél. Ehelyett
a csomagolókkal koordináljuk a kiadásokat, a javításokat a kiadás dátumáig
embargó alatt tartva. Így a felhasználóknak lesz esélyük frissíteni azon a
napon, függetlenül attól, milyen operációs rendszert vagy disztribúciót
futtatnak.

A `git-security` levelezőlista
------------------------------

A sebezhetőségek felelős közzététele, az elemzés, a javasolt javítások,
valamint a koordinált embargós kiadások megszervezése mind a `git-security`
levelezőlistán történik, a <git-security@googlegroups.com> címen.

Ebben a szövegkörnyezetben az "embargó" kifejezés arra az időszakra utal,
amíg egy sebezhetőségről szóló információt titokban tartanak, és csak a
szükséges ismeret elve alapján osztanak meg. Erre azért van szükség, hogy
megvédjük a Git felhasználóit a rosszindulatú szereplőktől, akik egyébként
tudomást szereznének a kihasználható támadási vektorokról. Az "embargó
feloldása" a sebezhetőségeket javító verzió közzétételére utal.

A `git-security` levelezőlista közönsége
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bárki felveheti a kapcsolatot a `git-security` levelezőlistával úgy, hogy
e-mailt küld a <git-security@googlegroups.com> címre, bár az archívum zárt a
nyilvánosság előtt, és csak a feliratkozott tagok számára elérhető.

Néhány tucat feliratkozott tag van: core Git fejlesztők, akiket megbíznak a
sebezhetőségek kezelésével, és érdekeltek (azaz olyan termékek tulajdonosai,
amelyeket a Git biztonsági sebezhetőségei érintenek).

A viták többsége a jelentett probléma súlyosságának felmérése körül forog
(beleértve azt a döntést, hogy a jelentés biztonsági szempontból releváns-e,
vagy átirányítható a nyilvános levelezőlistára), hogyan orvosolják a
problémát, a közzététel ütemtervének meghatározása, valamint a prioritások és
a követelmények összehangolása.

Kommunikáció
~~~~~~~~~~~~

Ha érdekelt vagy, jó ötlet szorosan figyelni a vitákat, mivel a lényeges
információ egy élénk beszélgetés közepén lehet elrejtve, amely nem tűnik a
te érdekeid szempontjából relevánsnak. Például az ideiglenes ütemtervben úgy
állapodhatnak meg, hogy közben az egyik patch kódkommentjeinek formázásáról
vitáznak, és arról, hogy több különálló sebezhetőség javításait egyetlen
embargós kiadásba vonják-e össze. A legtöbb levélszál általában nincs
kifejezetten úgy strukturálva, hogy megállapodásokat, felméréseket vagy
ütemterveket közöljön.

Tipikus ütemterv
----------------

- Egy lehetséges sebezhetőséget jelentenek a `git-security` levelezőlistának.

- A git-security lista tagjai vitát indítanak, hogy kezdeti felmérést adjanak
  a jelentett lehetséges sebezhetőség súlyosságáról.
  Erre néhány napon belül törekszünk.

- A vita után, ha konszenzus születik arról, hogy nem elég kritikus ahhoz,
  hogy bármilyen embargót indokoljon, a bejelentőt átirányítják a nyilvános
  Git levelezőlistára. Ezzel véget ér a bejelentő interakciója a
  `git-security` listával.

- Ha elég kritikusnak ítélik egy embargóhoz, ötleteket mutatnak be arról,
  hogyan kezeljék a sebezhetőséget.

- Általában e körül a Git maintainer vagy a megbízottjai megnyitnak egy
  security advisory vázlatot a GitHubon lévő `git/git` repository-ban (lásd
  lent a további részleteket).

- A kódátnézés a szövegkörnyezettől függően különféle helyeken zajlhat.
  Ezek: a git-security listán inline küldött patchek, a security advisory
  vázlatához társított privát GitHub-fork, vagy a git/cabal repository.

- A javításon dolgozó contributoroknak érdemes megfontolniuk, hogy a
  patchek a git-security listára küldésével kezdjenek (az eredeti szállal
  inline), mivel azok minden feliratkozó számára elérhetők, az eredeti
  bejelentővel együtt.

- Miután az átnézés letisztázódott, és mindenki, aki részt vett az
  átnézésben, egyetért abban, hogy a patchek közelítenek a célegyeneshez, a Git
  maintainer és mások meghatározzák a kiadás dátumát, valamint a kiszolgált
  kiadási vonalakat. Az arról szóló döntés, hogy mely verziókhoz kell
  visszaportolt javítás, a bejelentőtől, a patcheken dolgozó contributortól és
  az érdekeltektől érkező inputon alapul. Például a hosztoló oldalak
  üzemeltetői, akik elemezni szeretnék, hogy az adott problémát kihasználják-e
  az általuk hosztolt repository-k valamelyikén keresztül, és a bináris
  csomagolók, akik biztosak akarnak lenni abban, hogy a termékük megfelelően
  javítva lesz a sebezhetőség ellen, ebben a szakaszban adhatják meg az
  inputjukat.

- Bár a Git közösség mindent megtesz, hogy alkalmazkodjon a különböző bináris
  csomagolók konkrét ütemterv-kéréseihez, a probléma természete kizárhat egy
  elnyújtott kiadási ütemtervet. A sürgősnek ítélt javítások esetén a Git
  felhasználói közösségének az lehet a legjobb érdeke, hogy lerövidítsék a
  közzétételi és kiadási ütemtervet, és a csomagolóknak ennek megfelelően kell
  alkalmazkodniuk.

- Ezt követően a javításokat tartalmazó brancheket push-olják a git/cabal repository-ba.

- A tageket a Git maintainer hozza létre, és ugyanabba a repository-ba push-olja.

- A Git for Windows, a Git for macOS, a BSD, a Debian stb. maintainerei
  elkészítik a megfelelő kiadási artefaktumokat a Git maintainer által
  előkészített, létrehozott tagek alapján.

- A különböző bináris csomagolók által előkészített kiadási artefaktumok
  embargó alatt elérhetővé tehetők az érdekeltek számára a `git-security`
  listára küldött levéllel.

- Kevesebb mint egy héttel a kiadás előtt egy levelet küldenek a releváns
  információval a <distros@vs.openwall.org> címre (lásd lent), ez egy lista,
  amelyet a nyílt forráskódú projektek embargós kiadásainak előzetes
  bejelentésére használnak a Linux összes főbb disztribúciójának, valamint
  más operációs rendszereknek az érdekeltjei felé.

- Ezután a nyilvános kommunikációt a kiadás dátuma előtt előkészítik. Ez
  magában foglalja a blogbejegyzéseket és a Git és a Git for Windows
  levelezőlistákra küldött leveleket.

- A kiadás napján, körülbelül csendes-óceáni idő szerint reggel 10-kor, a Git
  maintainer push-olja a taget és a `master` branchet a nyilvános
  repository-ba, majd kiküld egy bejelentő levelet.

- Miután a taget push-olták, a Git for Windows maintainer közzéteszi a
  megfelelő taget, és létrehoz egy GitHub Release-t a hozzá tartozó kiadási
  artefaktumokkal (Git for Windows telepítő, Portable Git, MinGit stb.).

- A Git for Windows kiadást ezután bejelentik a nyilvános Git és Git for
  Windows levelezőlistákra küldött levéllel, valamint egy tweettel.

- Ugyanez a Linux és más platformok disztribúció-csomagolóira: a kiadásaikat
  az általuk preferált csatornákon jelentik be.

- Egy levelet küldenek a <oss-security@lists.openwall.org> címre (lásd lent a
  részleteket) a <distros@vs.openwall.org> címre küldött levél folytatásaként,
  amely részletesen leírja a sebezhetőséget, gyakran egy exploit proof of
  conceptjével együtt.

Megjegyzés: A Git projekt nem ad garanciát az ütemtervekre, de arra törekszik,
hogy az embargókat ésszerűen röviden tartsa a Git felhasználóinak biztonsága
érdekében.

Egy security advisory vázlat megnyitása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Az első lépés, hogy https://github.com/git/git/security/advisories/new[megnyitsz
egy advisory-t]. Technikailag ez nem szükséges. Mégis ez a legkényelmesebb mód a
CVE-szám megszerzésére, és ad hozzá egy társított privát repository-t, amely egy
javításon való együttműködésre használható.

A Linux disztribúciók értesítése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Legfeljebb két héttel a kiadás dátuma előtt értesítést kell küldenünk a
<distros@vs.openwall.org> címre, lehetőleg kevesebb mint 7 nappal a kiadás
dátuma előtt. Ez a legtöbb (az összes?) Linux disztribúciót eléri. Lásd lent
egy példát, és ennek a levelezőlistának az irányelveit
https://oss-security.openwall.org/wiki/mailing-lists/distros#how-to-use-the-lists[itt].

Miután a verzió megjelent, erről egy jegyzetet küldünk az oss-security-nek.
Példaként lásd a https://www.openwall.com/lists/oss-security/2019/12/13/1[v2.24.1
levelet];
https://oss-security.openwall.org/wiki/mailing-lists/oss-security[itt] vannak
az irányelveik.

Az oss-security-nek küldött levélnek le kell írnia az exploitot is, és
elismerést kell adnia a bejelentő(k)nek: a biztonsági kutatók még mindig túl
kevés elismerést kapnak a felbecsülhetetlen szolgáltatásért, amelyet
nyújtanak, és a nyilvános elismerés sokat segít abban, hogy a szervezeteik
továbbra is fizessék őket.

Technikailag bármely exploit leírása legfeljebb 7 nappal elhalasztható, de
ezt általában nem tesszük, hanem rögtön belefoglaljuk.

Előzékenységből jellemzően csatolunk egy Git bundle-t (`.tar.xz`-ként, mert a
lista eldobja a `.bundle` csatolmányokat) a distros@ címre küldött levélben,
hogy az érintett felek gondoskodhassanak az integrálásukról/visszaportolásukról.
Ezt a bundle-t jellemzően egy ilyen paranccsal hozzuk létre:

	git bundle create cve-xxx.bundle ^origin/master vA.B.C vD.E.F
	tar cJvf cve-xxx.bundle.tar.xz cve-xxx.bundle

Példa levél a distros@vs.openwall.org címre
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

....
To: distros@vs.openwall.org
Cc: git-security@googlegroups.com, <other people involved in the report/fix>
Subject: [vs] Upcoming Git security fix release

Team,

The Git project will release new versions on <date> at 10am Pacific Time or
soon thereafter. I have attached a Git bundle (embedded in a `.tar.xz` to avoid
it being dropped) which you can fetch into a clone of
https://github.com/git/git via `git fetch --tags /path/to/cve-xxx.bundle`,
containing the tags for versions <versions>.

You can verify with `git tag -v <tag>` that the versions were signed by
the Git maintainer, using the same GPG key as e.g. v2.24.0.

Please use these tags to prepare `git` packages for your various
distributions, using the appropriate tagged versions. The added test cases
help verify the correctness.

The addressed issues are:

<list of CVEs with a short description, typically copy/pasted from Git's
release notes, usually demo exploit(s), too>

Credit for finding the vulnerability goes to <reporter>, credit for fixing
it goes to <developer>.

Thanks,
<name>

....

Példa levél az oss-security@lists.openwall.com címre
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

....
To: oss-security@lists.openwall.com
Cc: git-security@googlegroups.com, <other people involved in the report/fix>
Subject: git: <copy from security advisory>

Team,

The Git project released new versions on <date>, addressing <CVE>.

All supported platforms are affected in one way or another, and all Git
versions all the way back to <version> are affected. The fixed versions are:
<versions>.

Link to the announcement: <link to lore.kernel.org/git>

We highly recommend to upgrade.

The addressed issues are:
* <list of CVEs and their explanations, along with demo exploits>

Credit for finding the vulnerability goes to <reporter>, credit for fixing
it goes to <developer>.

Thanks,
<name>
....