From: Junio C Hamano <gitster@pobox.com>
Date: Wed, 07 May 2014 13:15:39 -0700
Subject: Beginner question on "Pull is mostly evil"
Abstract: Ez a how-to egy módszert ismertet arra, hogyan tartható helyesen
 egy projekt előzménye a git pull használatakor.
Content-type: text/asciidoc

Tartsd helyesen a mérvadó kanonikus előzményt a git pull-lal
============================================================

Néha egy új projektintegrátor olyan projektelőzménnyel végzi, amely
"visszafelé fordítottnak" tűnik ahhoz képest, amit a projekt többi fejlesztője
elvár. Ez a howto egy javasolt integrációs munkafolyamatot mutat be egy
központi repository karbantartásához.

Tegyük fel, hogy a központi repository előzménye ez:

------------
    ---o---o---A
------------

amely az `A` commitnál végződik (az idő balról jobbra folyik, a gráf minden
csomópontja egy commit, a köztük lévő vonalak a szülő-gyermek kapcsolatot
jelzik).

Aztán klónozod, és a saját commitjaidon dolgozol, aminek eredményeként ez az
előzmény lesz a *te* repository-dban:

------------
    ---o---o---A---B---C
------------

Képzeld el, hogy a munkatársad ugyanezt tette, és közben az `A` tetejére
épített a *saját* repository-jában, majd push-olta a
központi repository-ba:

------------
    ---o---o---A---X---Y---Z
------------

Namost, ha ezen a ponton `git push`-t adsz ki, mivel a `C`-hez vezető
előzményedből hiányzik az `X`, az `Y` és a `Z`, ez sikertelen lesz.  Valahogy
a `Z` leszármazottjává kell tenned az előzményed csúcsát.

A probléma megoldásának egyik javasolt módja a "fetch, majd merge", más néven
`git pull`. Amikor fetch-elsz, a repository-d előzménye ilyen lesz:

------------
    ---o---o---A---B---C
		\
		 X---Y---Z
------------

Ha ezután lefuttatod a merge-t, még mindig a *te* branchened, azaz a `C`-n
állva, létrehozol egy `M` merge-t, és az előzményt ilyenné teszed:

------------
    ---o---o---A---B---C---M
		\         /
		 X---Y---Z
------------

Az `M` a `Z` leszármazottja, így push-olhatsz a központi repository
frissítéséhez.  Egy ilyen `M` merge egyik előzményben sem veszít el commitot,
így ebben az értelemben nem feltétlenül hibás, de amikor az emberek
"a projekt résztvevői között megosztott, mérvadó kanonikus előzményről", azaz
a "trunk"-ról akarnak beszélni, gyakran úgy tekintenek rá, mint "azokra a
commitokra, amelyeket az first-parent láncot követve látsz", és ezzel a
paranccsal nézik meg:

------------
    $ git log --first-parent
------------

Mindenki más számára, aki azután figyelte a központi repository-t, hogy a
munkatársad push-olta a `Z`-t, de mielőtt te push-oltad az `M`-et, a trunkon
lévő commitok az `o-o-A-X-Y-Z` voltak.  De mivel az `M`-et akkor csináltad,
amikor a `C`-n voltál, az `M` first parentje a `C`, így azzal, hogy az `M`-et
push-olva előrevitted a központi repository-t, az `X-Y-Z`-t oldalági branchré
tetted, nem a trunkra.

Inkább egy ilyen alakú előzményt szeretnél:

------------
    ---o---o---A---X---Y---Z---M'
		\             /
		 B-----------C
------------

hogy az first-parent láncban világos legyen: a projekt először az `X`-et,
aztán az `Y`-t, aztán a `Z`-t csinálta, majd merge-elt egy változtatást, amely
két commitból, a `B`-ből és a `C`-ből áll, és egyetlen célt ér el.  Lehet,
hogy a #12345 hiba javításán dolgoztál ezt a két patchet használva, és a
felcserélt szülőkkel rendelkező `M'` merge azt írhatja a napló-üzenetében,
hogy "Merge fix-bug-12345". Egy mód arra, hogy megmondd a `git pull`-nak, hogy
hozzon létre egy merge-t, de fordított sorrendben rögzítse a szülőket, lehet
erre a megoldás.

Vedd észre, hogy fent azt mondtam, "egyetlen célt ér el", mert ez fontos.
A "merge-sorrend felcserélése" csak egy speciális esetet fed le, amikor a
projektet nem nagyon érdekli, hogy egyetlen merge-en összefüggéstelen dolgok
készüljenek, de nagyon fontos neki az first-parent lánc.

A "trunk" kezeléséről többféle iskola létezik.

 1. Egyes projektek teljesen lineáris előzményt akarnak tartani mindenféle
    merge nélkül.  Nyilvánvalóan a merge-sorrend felcserélése nem felelne meg
    az ízlésüknek.  Ehelyett laposítanod kellene az előzményedet a frissített
    upstream tetejére, hogy ilyen alakú előzményt kapj:
+
------------
    ---o---o---A---X---Y---Z---B---C
------------
+
`git pull --rebase`-szel vagy valami hasonlóval.

 2. Egyes projektek tolerálják a merge-eket az előzményükben, de nem
    aggódnak túlságosan a first-parent sorrend miatt, és megengedik a
    fast-forward merge-eket.  Nekik a merge-sorrend felcserélése nem árt, de
    szükségtelen.

 3. Egyes projektek azt akarják, hogy a "trunk" minden egyes commitja egyetlen
    dolgot csináljon.  A `git log --first-parent` kimenete egy ilyen
    projektben vagy egy oldalági branch merge-ét mutatná, amely egyetlen témát
    zár le, vagy egyetlen commitot, amely önmagában zár le egyetlen témát.
    Ha a két commitod, a `B` és a `C` (vagy akár lehetnek két commitcsoport is)
    két független issue-t oldott meg, akkor az `M'` merge, amelyet a korábbi
    példában a merge-sorrend felcserélésével csináltunk, még mindig nem üti meg
    a projekt mércéjét.  Egyszerre merge-el két összefüggéstelen
    erőfeszítést, a `B`-t és a `C`-t.

Az utolsó kategóriába tartozó projekteknél (a Git maga is egy közülük) az
egyéni fejlesztők inkább egy ilyesféle előzményt szeretnének előkészíteni:

------------
		 C0--C1--C2     topic-c
		/
    ---o---o---A                master
		\
		 B0--B1--B2     topic-b
------------

Vagyis külön topicokat külön brancheken tartva, esetleg így:

------------
    $ git clone $URL work && cd work
    $ git checkout -b topic-b master
    $ ... work to create B0, B1 and B2 to complete one theme
    $ git checkout -b topic-c master
    $ ... same for the theme of topic-c
------------

És aztán

------------
    $ git checkout master
    $ git pull --ff-only
------------

megragadná az `X`-et, az `Y`-t és a `Z`-t az upstreamből, és előrevinné a
master branchedet:

------------
		 C0--C1--C2     topic-c
		/
    ---o---o---A---X---Y---Z    master
		\
		 B0--B1--B2     topic-b
------------

És aztán külön-külön merge-elnéd ezt a két branchet:

------------
    $ git merge topic-b
    $ git merge topic-c
------------

aminek eredménye:

------------
		 C0--C1---------C2
		/                 \
    ---o---o---A---X---Y---Z---M---N
		\             /
		 B0--B1-----B2
------------

és push-olnád vissza a központi repository-ba.

Nagyon is lehetséges, hogy amíg a topic-b-t és a topic-c-t merge-eled, valaki
megint előrevitte az előzményt a központi repository-ban, `W`-t téve a `Z`
tetejére, és sikertelenné téve a `git push`-odat.

Ilyen esetben visszatekernél, hogy eldobd az `M`-et és az `N`-et, újra
frissítenéd a 'master'-ed csúcsát, és megismételnéd a két merge-t:

------------
    $ git reset --hard origin/master
    $ git pull --ff-only
    $ git merge topic-b
    $ git merge topic-c
------------

Az eljárás eredménye egy ilyen előzmény lesz:

------------
		 C0--C1--------------C2
		/                     \
    ---o---o---A---X---Y---Z---W---M'--N'
		\                 /
		 B0--B1---------B2
------------

Lásd még https://git-blame.blogspot.com/2013/09/fun-with-first-parent-history.html
