From: Junio C Hamano <gitster@pobox.com>
Date: Wed, 21 Nov 2007 16:32:55 -0800
Subject: Addendum to "MaintNotes"
Abstract: Képzeld el, hogy a Git fejlesztése a szokásos módon száguld, amikor
 kedves, szomszédos maintainerünket elüti egy kósza busz. A balekok (hűséges
 fejlesztők) hordáiból téged csaptak be (választottak ki), hogy beállj új
 maintainernek. Ez a howto megmutatja neked, "hogyan" csináld.
Content-type: text/asciidoc

Hogyan tartsd karban a Gitet
============================

Tevékenységek
-------------

A maintainer Git-idejét három tevékenységre fordítja.

 - Kommunikáció (45%)

   Levelezőlistás viták az általános tervezésről, felhasználói kérdések
   megválaszolása, hibajelentések diagnosztizálása; patchek átnézése,
   kommentálása, alternatívák javaslása hozzájuk, és elutasításuk.

 - Integráció (50%)

   Új patchek alkalmazása a contributoroktól, miközben apró hibákat
   észreveszünk és javítunk, az integrációs és tesztelő branchek
   rendezgetése, az eredmények kipush-olása, a kiadások elkészítése és a
   bejelentések megtétele.

 - Saját fejlesztés (5%)

   A saját problémáim vakarászása és a javasolt patchsorozatok kiküldése.

Az irányelv
-----------

Az integrációra vonatkozó irányelvet informálisan az "A Note from the
maintainer" üzenet említi, amelyet minden feature release elkészülte után
időnként kiküldenek a levelezőlistára:

 - A feature release-ek számozása vX.Y.0, és bármely területen tartalmazhatnak
   bugfixeket és fejlesztéseket, beleértve a funkcionalitást, a
   teljesítményt és a használhatóságot, regresszió nélkül.

 - A maintenance release-ek számozása vX.Y.Z (0 < Z), és csak a megfelelő
   vX.Y.0 feature release-hez és a korábbi vX.Y.W (W < Z) maintenance
   release-ekhez tartozó bugfixeket tartalmazhatnak.

 - A 'master' branch a következő feature release előkészítésére szolgál.
   Másképp: valamikor a 'master' branch csúcsát vX.(Y+1).0-ként tagelik, amikor
   a vX.Y.0 a legutóbbi feature release.

 - A 'maint' branch a következő maintenance release előkészítésére szolgál.
   Miután a vX.Y.0 feature release elkészül, a 'maint' branch csúcsát arra a
   kiadásra állítják, és a bugfixek felhalmozódnak a branchen, majd valamikor
   a branch csúcsát vX.Y.1, vX.Y.2 és így tovább taggel jelölik.

 - A 'next' branch olyan változtatások (fejlesztések és javítások egyaránt)
   közzétételére szolgál, amelyeknek (1) érdemleges célja van, (2) elég jó
   állapotban vannak a mindennapi használathoz, (3) de még nem bizonyultak
   regressziómentesnek.  A contributorok levelezőlistás átnézései segítenek a
   döntésben.  Miután egy topicot merge-elnek a 'next'-be, legalább 7 naptári
   napig tesztelik, mielőtt merge-elnék a 'master'-be.

 - A 'seen' branch olyan más javasolt változtatások közzétételére szolgál,
   amelyek még nem felelnek meg a 'next'-re megállapított kritériumoknak (lásd
   fent), de nincs ígéret arra, hogy a 'seen' mindent tartalmazni fog.  Egy
   topicot, amelyre nem volt átnézői reakció, lehet, hogy nem vesznek fel.

   - Egy új topicot először a 'seen'-be merge-elnek, hacsak nem triviálisan
     helyes és egyértelműen sürgős, amely esetben közvetlenül a 'next'-be vagy
     akár a 'master'-be is merge-elhető.

   - Ha egy topic, amelyet felvettek a 'seen'-be, 3 naptári hétre inaktívvá
     válik és az is marad anélkül, hogy egyértelmű konszenzus alakult volna ki
     arról, hogy elég jó a 'next'-be helyezéshez, a topicot el lehet dobni a
     'seen'-ből.  Az érdekeltek szabadon újraéleszthetik a topicot.  Ezen
     irányelv szempontjából az "inaktív" meghatározása az, hogy senki sem
     beszélt a topicról, nem tettek közzé új iterációt belőle, és nem adtak
     választ az átnézési kommentekre.

 - A 'master' és a 'maint' branch csúcsát nem tekerik vissza, hogy az emberek
   a tetejükre építhessék a saját testreszabásaikat.  Egy új fejlesztési
   ciklus elején a 'next'-et egyszer visszatekerik a 'master' csúcsához, de
   egyébként a ciklus végéig nem tekerik vissza.

 - A 'master' általában a 'maint' egészét tartalmazza, a 'next' pedig a
   'master' egészét.  A 'seen' a 'next'-be merge-elt összes topicot
   tartalmazza, de közvetlenül a 'master'-re épül újra.

 - A 'master' csúcsa a szándék szerint stabilabb, mint bármely taggel jelölt
   kiadás, és a felhasználókat arra biztatják, hogy kövessék.

 - A 'next' branchen zajlik az új tevékenység, és a felhasználókat arra
   biztatják, hogy teszteljék, hogy a regressziók és a bugok még azelőtt
   előkerüljenek, hogy új topicokat merge-elnének a 'master'-be.

 - Amikor problémát találnak egy topicban a 'next'-en, a topicot megjelölik,
   hogy ne merge-elődjön a 'master'-be.  A követő patcheket a levelezőlistán
   megvitatják, és átnézés után alkalmazzák a topicra, majd a topicot (újra)
   merge-elik a 'next'-be.  Miután átment a szokásos tesztelésen a 'next'-en,
   a teljes (javított) topicot merge-elik a 'master'-be.

 - Egy feature release kiadási ciklusa várhatóan nyolc-tíz hétig tart.  A
   végleges kiadás előtt néhány "release candidate" kiadást várhatóan
   körülbelül egy hét eltéréssel tagelnek, egy "preview" kiadást pedig
   körülbelül egy héttel az első release candidate tagelése előtt tagelnek.

 - A preview kiadás tagelése után a jól átnézett topicok merge-elhetők a
   'master'-be, mielőtt eltöltenék a szokásos 7 naptári napot a 'next'-en,
   azzal a várakozással, hogy a bennük lévő bugok elkaphatók és javíthatók a
   release candidate-ekben a végleges kiadás előtt.

 - Az első release candidate tagelése után a contributorokat erősen arra
   biztatják, hogy a régi bugok és bármilyen új funkció kezelése helyett a
   ciklus során bevezetett új regressziók megtalálására és javítására
   összpontosítsanak.  A topicok merge-elése a 'next'-ből a 'master'-be leáll,
   és az új topicok merge-elése a 'next'-be leáll. Hacsak nem a ciklusban
   keletkezett új regressziók javításai, persze.

 - Nem sokkal egy feature release elkészülte után a 'maint' csúcsát
   fast-forwardolják, hogy a kiadásra mutasson.  A 'next'-ben tartott
   topicokat lemerge-elik a 'master'-be, és új fejlesztési ciklus kezdődik.


Vedd észre, hogy a v1.9.0 kiadás előtt a verziószámok felépítése kissé
másképp nézett ki.  A vX.Y.Z feature release-ek voltak, míg a vX.Y.Z.W a
vX.Y.Z-hez tartozó maintenance release-ek.

Mivel a Gitben a kódsorok többségét egyéni contributorok írják, és a
hozzájárulások a levelezőlistán közzétett, e-mailben küldött patchek
formájában érkeznek, a projekt fenntart egy leképezést az egyes commitoktól
annak az e-mailnek a Message-Id-jéig, amelyből a commit lett, hogy segítse a
változtatások eredetének nyomon követését. Az "refs/notes/amlog"-ban lévő
notes-okat használják erre a célra, és a maintainer repository-jába a
különbontott branchekkel együtt teszik közzé.

Egy tipikus Git-nap
-------------------

A maintainer tipikus Git-napja a fenti irányelvet a következők
elvégzésével valósítja meg:

 - A levelezőlista átfutása.  Válasz átnézési kommentekkel, javaslatokkal
   stb.  Kibicelés.  A potenciálisan használható patchek összegyűjtése a
   levelezőlistáról.  Az egyetlen topicról szóló patchek egy mailboxba kerülnek
   (a leveleimet Gnusban olvasom, és \C-o-t ütök, hogy mbox formátumú
   fájlokba mentsem/fűzzem az üzeneteket).

 - Saját patchek írása a listán felvetett, de senki által megoldani nem
   vállalt problémák kezelésére.  Kiküldés úgy, ahogy a többi contributor
   teszi, és felvétel úgy, ahogy a többi contributortól érkező patcheket (lásd
   fent).

 - Az elmentett mailboxokban lévő patchek átnézése.  A javasolt napló-üzenet
   szerkesztése elgépelés-javítások és pontosítások céljából, és a listáról
   összegyűjtött Ack-ek hozzáadása.  A patch szerkesztése, hogy beépüljenek a
   vitából származó "Hoppá, ennek így kellett volna lennie" javítások.

 - Az összegyűjtött patchek osztályozása és a 'master' és a 'maint'
   frissítéseinek kezelése:

   - A 'maint' csúcsát érintő, nyilvánvalóan helyes javítások közvetlenül a
     'maint'-re kerülnek alkalmazásra.

   - A 'master' csúcsát érintő, nyilvánvalóan helyes javítások közvetlenül a
     'master'-re kerülnek alkalmazásra.

   - A többi topicot ez a lépés nem kezeli.

   Ez a lépés a "git am"-mel történik.

     $ git checkout master    ;# or "git checkout maint"
     $ git am -sc3 mailbox
     $ make test

   A gyakorlatban szinte egyetlen patch sem megy közvetlenül a 'master'-be
   vagy a 'maint'-be.

   Az e-mailben küldött patchek "git am"-mel való alkalmazása automatikusan
   rögzíti a 'Message-Id'-tól az alkalmazott commitig tartó leképezéseket az
   "amlog" notes-ban. Időnként ellenőrizd, hogy ez működik, a "git show -s
   --notes=amlog $commit"-tal.

   Ezt a leképezést a 'todo' branchen található "post-applypatch" hook
   segítségével tartják karban. Azt a hookot a patchek alkalmazása előtt kell
   telepíteni. Az is hasznos, ha a releváns amlog-bejegyzéseket rebase-eléskor
   továbbvisszük, ezért a következő config hasznos lehet:

      [notes]
	rewriteRef = refs/notes/amlog

   Kerüld a "cherry-pick"-et, mivel az tervezetten nem propagálja a
   notes-okat. Használd a "git commit --amend"-et vagy a "git rebase"-t egy
   meglévő commit javításához, akár egyetlen patches topicnál is.

   Bizonyosodj meg róla, hogy egy 'refs/notes/amlog'-hoz tartozó push
   refspec szerepel a publikáló repository-k remote-konfigurációjában. Néhány
   mintakonfiguráció így néz ki:

      [remote "github"]
	url = https://github.com/gitster/git
	pushurl = github.com:gitster/git.git
	mirror

      [remote "github2"]
	url = https://github.com/git/git
	fetch = +refs/heads/*:refs/remotes/github2/*
	pushurl = github.com:git/git.git
	push = refs/heads/maint:refs/heads/maint
	push = refs/heads/master:refs/heads/master
	push = refs/heads/next:refs/heads/next
	push = +refs/heads/seen:refs/heads/seen
	push = +refs/notes/amlog

 - A "What's cooking" üzenet legutóbbi számának átnézése, a merge-elésre kész
   topicok átnézése (topic->master és topic->maint).  Használd a "Meta/cook -w"
   szkriptet (ahol a Meta/ a 'todo' branch egy checkoutját tartalmazza) ennek a
   lépésnek a segítéséhez.

   És végezd el a merge-t.  Használd a "Meta/Reintegrate -e" szkriptet (lásd
   később) ennek a lépésnek a segítéséhez.

     $ Meta/cook -w last-issue-of-whats-cooking.mbox

     $ git checkout master    ;# or "git checkout maint"
     $ echo ai/topic | Meta/Reintegrate -e ;# "git merge ai/topic"
     $ git log -p ORIG_HEAD.. ;# final review
     $ git diff ORIG_HEAD..   ;# final review
     $ make test              ;# final review

   Ha a 'master' csúcsa frissül, generáld le az előformázott dokumentációt
   is, és push-old ki az eredményt a git-htmldocs és a git-manpages
   repository-kba.

 - A maradék patchek kezelése:

   - Minden nem nyilvánvaló dolog, amely a 'master'-re alkalmazható (másképp:
     nem függ semmi olyantól, ami még a 'next'-ben van, és nincs a
     'master'-ben), egy új topic branchre kerül alkalmazásra, amely a 'master'
     csúcsáról (vagy a legutóbbi feature release-ről, amely kicsit régebbi,
     mint a 'master') van forkolva.  Ez magában foglalja a 'master' bővítéseit
     és nem nyilvánvaló javításait is.  Egy topic branch neve ai/topic
     alakú, ahol az "ai" egy kétbetűs karakterlánc a szerző kezdőbetűi alapján,
     a "topic" pedig a topic leíró neve (másképp: "miről szól a sorozat").

   - A 'maint'-nek szánt nem nyilvánvaló javítás egy új topic branchre kerül
     alkalmazásra, amely a 'maint' csúcsáról (vagy a legrégebbi, még releváns
     maintenance branchről) van forkolva.  A topic elnevezhető
     ai/maint-topic alakúra.

   - Egy meglévő topicot érintő változtatások a branchre kerülnek
     alkalmazásra, de:

     - a nyilvánvalóan helyeseket alkalmazzuk először;

     - a kétségeseket eldobjuk, vagy a csúcs közelébe alkalmazzuk;

   - Egy meglévő topichoz tartozó helyettesítő patcheket csak a 'next'-ben
     nem lévő commitokra fogadunk el.

   A kezdeti kör ezzel történik:

     $ git checkout ai/topic ;# or "git checkout -b ai/topic master"
     $ git am -sc3 --whitespace=warn mailbox

   egy meglévő topic lecserélése egy következő körrel pedig ezzel történik:

     $ git checkout master...ai/topic ;# try to reapply to the same base
     $ git am -sc3 --whitespace=warn mailbox

   hogy az új kört egy leválasztott HEAD-en készítsd elő, majd

     $ git range-diff @{-1}...
     $ git diff @{-1}

   hogy duplán ellenőrizd, mi változott a legutóbbi kör óta, és végül

     $ git checkout -B @{-1}

   a lezáráshoz (az utolsó lépés az oka annak, amiért egy már a 'next'-ben
   lévő topicot nem lecserélünk, hanem inkrementálisan frissítünk).

   Akár a kezdeti kör, akár egy következő kör, a topic lehet, hogy még
   önmagában sem buildel, vagy bugok miatt eltörheti a buildet, amikor
   integrációs branchekbe merge-elik.  Lehet, hogy már vannak nyilvánvaló és
   triviális javítási javaslatok a listán.  A maintainer gyakran hozzáad egy
   extra commitot, a címében "SQUASH???"-sel, hogy rendbe tegye a dolgokat,
   mielőtt közzétenné az integrációs brancheket, hogy más fejlesztők
   használhassák tesztelésre.  Ezek a változtatások azok, amelyek mellett a
   maintainer nem 100%-ig elkötelezett (a triviális elgépelés-javításokat stb.
   gyakran közvetlenül a javítást igénylő patchekbe squashelik, anélkül hogy
   külön "SQUASH???" commitként alkalmaznák), hogy szükség szerint könnyen
   eltávolíthatók legyenek.  A várakozás az, hogy az eredeti szerző az
   újragöngyölésben elvégzi a javításokat.

 - Mostanra új topic branchek jöttek létre, és a meglévő topic brancheket
   frissítették.  Az integrációs brancheket, a 'next'-et, a 'jch'-t és a
   'seen'-t frissíteni kell, hogy tartalmazzák őket.

 - Ha vannak olyan topicok, amelyeket merge-eltek a 'master'-be, és a
   'maint'-be kellene merge-elni, merge-eld őket a 'maint'-be, és frissítsd a
   release notes-ot a következő maintenance release-hez.

 - Nézd át újra a "What's cooking" legutóbbi számát.  A 'next'-ben elég régóta
   lévő topicok készen állnak a 'master'-be merge-elésre?  A korábban látott,
   'seen'-ben lévő topicok most kaptak-e pozitív átnézéseket, és készen
   állnak-e a 'next'-be merge-elésre?

 - Ha vannak olyan topicok, amelyek elég régóta főnek a 'next'-ben, és a
   'master'-be kellene merge-elni, merge-eld őket a 'master'-be, és frissítsd a
   release notes-ot a következő feature release-hez.

 - Ha voltak közvetlenül a 'maint'-en készült patchek, merge-eld a 'maint'-et
   a 'master'-be; bizonyosodj meg róla, hogy az eredmény az, amit szeretnél.

     $ git checkout master
     $ git merge -m "Sync with 'maint'" --no-log maint
     $ git log -p --first-parent ORIG_HEAD..
     $ make test

 - Készülj fel a 'jch' branch frissítésére, amely a 'master' és a 'seen'
   közötti valamit reprezentál, és gyakran kicsit a 'next' előtt jár, valamint
   a 'seen' branch frissítésére, amely a maradékot tartja.

     $ Meta/Reintegrate master..jch >Meta/redo-jch.sh

   Az eredmény egy szkript, amely felsorolja a merge-elendő topicokat a
   jelenlegi 'jch' újraépítéséhez.  Tedd ugyanezt a 'seen'-nel.

 - Nézd át a Meta/redo-jch.sh és a Meta/redo-seen.sh szkripteket.  Az
   előbbiben kell lennie egy '### match next' sornak---az ötlet az, hogy a
   sor előtt felsorolt topicok 'master' tetejére merge-elése a 'next'-ével
   azonos fát kell hogy eredményezzen.

 - Mivel az újonnan létrehozott topicokat általában a 'seen' csúcsa közelébe
   merge-elik, add őket a Meta/redo-seen.sh szkript végéhez.  A 'seen'-ben lévő
   topicok között lehetnek olyanok, amelyek még nem egészen készek a 'next'-re,
   de közelítenek hozzá.  Mozgasd őket a Meta/redo-seen.sh-ból a
   Meta/redo-jch.sh végére.  A várakozás az, hogy a 'jch'-t használod
   mindennapi meghajtóként, első kísérleti nyúlként, ezért óvatosan kell
   választanod.

 - Most készen állunk a 'jch' újraépítésének megkezdésére és a topicok
   'next'-be merge-elésére.  Minden olyan branchnél, amelynek csúcsa nincs a
   'next'-be merge-elve, három dolog egyike történhet:

   - A commitok mind 'next'-re érdemesek; merge-eld a topicot a next-be;
   - Az új részek vegyes minőségűek, de a korábbiak 'next'-re érdemesek;
     merge-eld a korai részeket a next-be;
   - Semmi sem 'next'-re érdemes; ne csinálj semmit.

   Ezt a lépést a korábban létrehozott Meta/redo-jch.sh szkript segíti.  Ha
   egy már a 'next'-ben lévő topic kapott egy patchet, a szkript
   "ai/topic~1"-ként sorolná fel.  Ahhoz, hogy az új patch bekerüljön a
   frissített 'next'-be, dobd el a "~1" részt; ahhoz, hogy kizárva maradjon,
   ne nyúlj a sorhoz.

   Ha egy topicot, amely nem volt a 'next'-ben, a 'next'-be kellene
   merge-elni, add hozzá a '### match next' sor elé.  Aztán:

     $ git checkout --detach master
     $ sh Meta/redo-jch.sh -c1

   hogy a nulláról építsd újra a 'jch' branchet.  A "-c1" azt mondja a
   szkriptnek, hogy álljon meg a merge-eléssel az első '###'-kal kezdődő
   sornál (azaz a "### match next" sornál, amelyet korábban hozzáadtál).

   Ezen a ponton buildeld-teszteld az eredményt.  Felfedhet szemantikai
   konfliktusokat (pl. egy topic átnevezett egy változót, egy másik új
   hivatkozást adott a változóra a régi nevén), amely esetben előbb készíts
   egy megfelelő merge-fixet (lásd a függeléket), és a nulláról építsd újra a
   'jch' branchet, a 'master' csúcsáról indulva, ezúttal "-c1" nélkül, hogy az
   összes topicot merge-eld.

   Aztán tedd ugyanezt a 'next'-tel.

     $ git checkout next
     $ sh Meta/redo-jch.sh -c1 -e

   A "-e" opció lehetővé teszi a merge-üzenet szerkesztését, amely a topic
   előzményéből és a "What's cooking"-ban lévő kommentekből származik.  Az
   eredményül kapott fának egyeznie kell a 'jch^{/^### match next'}'-tal, mivel
   ugyanazt a topichalmazt merge-elik a 'master'-en; egyébként hibás merge
   történt. Vizsgáld ki, miért, és ne folytasd, amíg a hibás merge-t meg nem
   találtad és ki nem javítottad.

   Ha a 'master' frissült, mielőtt elkezdted volna újracsinálni a 'next'-et, akkor

     $ git diff 'jch^{/^### match next}' next

   megmutatná a 'master'-be került különbségeket (amelyek megvannak a
   'jch'-ban, de a 'next'-ben még nincsenek---gyakran ezek a release notes
   frissítései).  Merge-eld vissza a 'master'-t a 'next'-be, ha ez a helyzet.

     $ git merge -m "Sync with 'master'" --no-log master

   Ha minden rendben van, tisztítsd meg a redo-jch.sh szkriptet ezzel

     $ sh Meta/redo-jch.sh -u

   Ez eltávolítja a szkriptben felsorolt, már a 'master'-be merge-elt
   topicokat.  Ez elveszítheti a '### match next' jelölőt; add hozzá újra a
   megfelelő helyre, amikor ez történik.

 - Építsd újra a 'seen'-t a 'jch' tetején.

     $ git checkout -B seen jch
     $ sh Meta/redo-seen.sh

   Ha minden rendben van, tisztítsd meg a redo-seen.sh szkriptet ezzel

     $ sh Meta/redo-seen.sh -u

   Duplán ellenőrizd ezzel

     $ git branch --no-merged seen '??/*'

   hogy lásd, nincsenek váratlanul ottmaradt topicok.

   Ezen a ponton buildeld-teszteld az eredményt szemantikai konfliktusokért,
   és ha vannak, előbb készíts egy megfelelő merge-fixet (lásd a függeléket),
   és a nulláról építsd újra a 'seen' branchet, a 'jch' csúcsáról indulva.

 - Frissítsd a "What's cooking" üzenetet, hogy átnézd a meglévő topicok
   frissítéseit, az újonnan hozzáadott topicokat és a végzett topicokat.

   Ezt a lépést a Meta/cook szkript segíti.

     $ Meta/cook

   Ez a szkript megvizsgálja a master..seen közötti előzményt, megtalálja a
   topic branchek csúcsait, összehasonlítja, amit talált, a
   Meta/whats-cooking.txt jelenlegi tartalmával, és frissíti azt a fájlt.  A
   fájlban nem szereplő, de a master..seen-ben megtalált topicok az "New
   topics" szakaszba kerülnek, a fájlban felsorolt, de a master..seen-ben már
   nem található topicok a "Graduated to master" szakaszba kerülnek, a topicok
   pedig, amelyek commitjai megváltoztatták az állapotukat (pl. korábban csak
   a 'seen'-ben voltak, most a 'next'-be merge-elve), a "<<" és ">>" változás-
   jelölőkkel frissülnek.

   Keresd a "<<" és ">>" közé zárt sorokat; ezek a régi fájl tartalmát
   tartják, amelyet ez az integrációs kör lecserél.  Miután ellenőrizted őket,
   távolítsd el a régi részt.  Nézd át az egyes topicok leírását, és frissítsd
   a készültségét és a tervét szükség szerint.  A frissített terv átnézéséhez
   futtasd

     $ Meta/cook -w

   amely felveszi a topicokhoz adott kommenteket, például "Will merge to
   'next'", stb. (lásd a Meta/cook szkriptet, hogy megtudd, milyen kifejezések
   támogatottak).

 - Fordítsd le, teszteld és telepítsd mind a négy (öt) integrációs branchet;
   a Meta/Dothem szkript segítheti ezt a lépést.

 - Formázd a dokumentációt, ha a 'master' branch frissült; a Meta/dodoc.sh
   szkript segítheti ezt a lépést.

 - Push-old ki az integrációs brancheket nyilvános helyekre; a Meta/pushall
   szkript segítheti ezt a lépést.

Megfigyelések
-------------

Néhány megfigyelés.

 * Minden topicot egyénileg tesztelnek, és a többi, előbb a 'seen'-ben, majd a
   'jch'-ban, majd a 'next'-ben főző topickal együtt is.  Amíg meg nem érik,
   egyetlen része sem kerül merge-elésre a 'master'-be.

 * Egy már a 'next'-ben lévő topic kaphat javításokat, még mindig a
   'next'-ben.  Egy ilyen topicnak sok merge-e lesz a 'next'-be (másképp: a
   "git log --first-parent next" sok "Merge branch 'ai/topic' to next"-et fog
   mutatni ugyanahhoz a topichoz.

 * Egy 'maint'-nek szánt nem nyilvánvaló javítást a 'next'-ben főznek, majd a
   'master'-be merge-elnek, hogy extra biztosak legyenek benne, hogy rendben
   van, majd a 'maint'-be merge-elnek.

 * Még amikor a 'next' üressé válik (másképp: minden topic stabilnak bizonyul
   és merge-elődik a 'master'-be, és a "git diff master next" üreset mutat),
   akkor is rengeteg merge commitja van, amelyek sosem lesznek a 'master'-ben.

 * Elvben a "git log --first-parent master..next" csak merge-eket kellene
   hogy mutasson (a gyakorlatban vannak fixup commitok és revertek, amelyek
   nem merge-ek).

 * Egy topic branch csúcsa közelében lévő commitok, amelyek nincsenek a
   'next'-ben, szabad prédái az eldobásnak, lecserélésnek vagy átírásnak.  A
   már a 'next'-be merge-elt commitok nem.

 * Az, hogy egy topic a 'next' branchen van, nem garancia arra, hogy bekerül
   a következő feature release-be.  Az, hogy a 'master' branchen van,
   jellemzően igen.

 * A "SQUASH???" javítások természete miatt, ha az eredeti szerző egyetért a
   javasolt változtatásokkal, rendben van a megfelelő patchekbe squashelni
   őket a következő körben (amikor a javasolt változtatás elég kicsi, a
   szerzőnek a "Helped-by"-jal sem kell foglalkoznia).  Az is rendben van, ha
   a következő körből eldobjuk őket, amikor az eredeti szerző nem ért egyet a
   javaslattal, de a szerzőtől elvárt, hogy valahol a vitában elmondja, miért.


Függelék
--------

Egy "merge-fix" előkészítése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Két topic merge-e lehet, hogy szövegesen nem ütközik, de szemantikai
szinten mégis konfliktusa van. Klasszikus példa, hogy az egyik topic
átnevez egy változót és annak minden használatát, míg egy másik topic új
használatot ad a változóhoz a régi nevén. Amikor ezt a két topicot
összemerge-elik, az utóbbi topic által újonnan hozzáadott hivatkozás a
változóra az eredményben továbbra is a régi nevet fogja használni.

A Meta/Reintegrate szkript, amelyet a redo-jch és a redo-seen szkriptek
használnak, egy nyers, de használható módot valósít meg ennek a problémának a
megkerülésére.  Amikor a szkript merge-eli a $X branchet, ellenőrzi, hogy
létezik-e a "refs/merge-fix/$X", és ha igen, annak a hatását beszkashelik a
mechanikus merge eredményébe.  Másképp:

     $ echo $X | Meta/Reintegrate

nagyjából egyenértékű ezzel a sorozattal:

     $ git merge --rerere-autoupdate $X
     $ git commit
     $ git cherry-pick -n refs/merge-fix/$X
     $ git commit --amend

Ennek a ""merge-fix előkészítése"" lépésnek a célja, hogy előálljon egy
commit, amely beszkashelhető egy mechanikus merge eredményébe a szemantikai
konfliktusok javítására.

Miután rájöttél, hogy az "ai/topic" branch egy integrációs branchbe való
merge-elésének eredményében ilyen szemantikai konfliktus volt, mondjuk a
seen~4-ben, checkoutold a problémás merge-t egy leválasztott HEAD-en,
szerkeszd a working tree-t a szemantikai konfliktus javításához, és készíts
egy külön commitot a javítás rögzítéséhez:

     $ git checkout seen~4
     $ git show -s --pretty=%s ;# double check
     Merge branch 'ai/topic' to seen
     $ edit
     $ git commit -m 'merge-fix/ai/topic' -a

Aztán készíts egy "refs/merge-fix/ai/topic" referenciát, hogy erre az
eredményre mutasson:

     $ git update-ref refs/merge-fix/ai/topic HEAD

Aztán duplán ellenőrizd az eredményt úgy, hogy megkéred a Meta/Reintegrate-et
a merge újbóli elvégzésére:

     $ git checkout seen~5 ;# the parent of the problem merge
     $ echo ai/topic | Meta/Reintegrate
     $ git diff seen~4

Ezúttal, mivel előkészítetted a refs/merge-fix/ai/topic-ot, az eredményül
kapott merge-t módosítani kellett, hogy tartalmazza a szemantikai konfliktus
javítását.

Vedd észre, hogy ez feltételezi, hogy az ütköző branchek merge-elésének
sorrendje nem változik.  Ha az ok, amiért az ai/topic branch merge-elésének
szüksége van erre a merge-fixre, az, hogy egy másik branch, amelyet korábban
merge-eltek az integrációs branchbe, megváltoztatta azt az alapfeltételezést,
amit az ai/topic branch tett (pl. az ai/topic branch hozzáadott egy helyet,
ahol egy változóra hivatkozik, míg a másik branch átnevezte azt a változót,
és igazította a meglévő használati helyeket), és ha megváltoztattad a
redo-jch (vagy redo-seen) szkriptet, hogy az ai/topic branchet a másik branch
előtt merge-elje, akkor a fenti merge-fixet nem az ai/topic merge-elésekor
kell alkalmazni, hanem a másik branch merge-elésekor.  Át kellene helyezned a
javítást, hogy a másik branchre vonatkozzon, talán így:

      $ mf=refs/merge-fix
      $ git update-ref $mf/$the_other_branch $mf/ai/topic
      $ git update-ref -d $mf/ai/topic
