From: Eric S. Raymond <esr@thyrsus.com>
Abstract: Ez how-to dokumentáció azoknak, akik bővítményparancsokat szeretnének
 hozzáadni a Githez.  A builtin.h mellett érdemes olvasni.
Content-type: text/asciidoc

Hogyan integrálj új alparancsokat
=================================

Ez how-to dokumentáció azoknak, akik bővítményparancsokat szeretnének
hozzáadni a Githez.  A builtin.h mellett érdemes olvasni.

Futásidejű környezet
--------------------

A Git alparancsai önálló futtatható programok, amelyek a Git exec elérési
útján helyezkednek el, ez általában a /usr/lib/git-core.  Maga a git futtatható
program egy vékony burkoló, amely tudja, hol vannak az alparancsok, és úgy
futtatja őket, hogy átadja nekik a parancssori argumentumokat.

(Ha a "git foo" nem található a Git exec elérési útján, a burkoló a $PATH
többi részében keresi.  Így lehetséges olyan helyi Git-bővítményeket írni,
amelyek nem rendszerszintű helyen laknak.)

Megvalósítási nyelvek
---------------------

A legtöbb alparancs C-ben vagy shellben íródott.  Néhányat Perlben
írtak.

Bár a hordozhatóság kedvéért erősen javasoljuk a hordozható C-ben való
kódolást, ezek a konkrét szkriptnyelvek is elfogadhatók.  Többet nem fogadunk
el nagyon erős technikai indok nélkül, mivel nem akarjuk kiszélesíteni a Git
csomag kötelező függőségeit.  Az importáló segédprogramok, sebészeti eszközök,
remote helperek és a Git csomag peremén lévő egyéb kód esetében
elnézőbbek vagyunk, és megengedjük a Pythont (sőt a Tcl/tk-t is), de ezeket
nem szabad alapfunkciókhoz használni.

Ez a jövőben változhat.  Különösen a Python nem engedélyezett a magban, mert
jobb Python-integrációra van szükségünk a Git Windows-telepítőjében, mielőtt
biztosak lehetnénk benne, hogy az adott környezetben lévők nem szenvednek el
elfogadhatatlanul nagy képességveszteséget.

A C-parancsok általában egyetlen modulként íródnak, a parancsról elnevezve,
amelyek egy libgit nevű függvénygyűjteményt linkelnek.  Így a 'git-foo'
parancsod általában egyetlen "git-foo.c"-ként valósulna meg (vagy
"builtin/foo.c"-ként, ha a fő binárishoz kell linkelni); ez a szervezés
megkönnyíti a kódot olvasók dolgát a dolgok megtalálásában.

A CodingGuidelines dokumentumban további útmutatást találsz arról, mit
tartunk jó gyakorlatnak C-ben és shellben, a builtin.h-ban pedig a C-ben írt
beépített parancsok számára elérhető segédfüggvényeket.

Mire van szüksége minden bővítményparancsnak
--------------------------------------------

Kell lennie egy man page-ednek, asciidocban megírva (ezt jeleníti meg a Git
help az alparancsod nevével együtt).  Ne feledd, hogy van egy helyi asciidoc-
konfiguráció és makrókészlet, amit használnod kell.  Gyakran hasznos egy
meglévő oldal klónozásával kezdeni, és a szöveges tartalmat lecserélni.

Kell lennie egy tesztednek, amely TAP (Test Anything Protocol) formátumban
jelent.  A tesztek futtatható programok (általában shell szkriptek), amelyek a
fa 't' alkönyvtárában találhatók.  Minden teszt neve egy 't' betűvel és egy
sorszámmal kezdődik, amely szabályozza, hol fut le a tesztsorozatban;
hagyományosan a névtörzs többi része a tesztelt parancs neve.

Olvasd el a t/README fájlt, hogy többet megtudj a tesztek írásakor
követendő konvenciókról és a teszttámogató könyvtárról.

Egy parancs integrálása
-----------------------

Íme a teendők, amikor egy új alparancsot szeretnél merge-elni a Git
fájába.

1. Ne felejtsd el sign-offolni a patchedet!

2. Fűzd hozzá a parancsod nevét a BUILTIN_OBJS, EXTRA_PROGRAMS, SCRIPT_SH,
SCRIPT_PERL vagy SCRIPT_PYTHON változók egyikéhez.

3. Tedd be a tesztjét a t könyvtárba.

4. Ha a parancsod egy p-kód köztes formával rendelkező értelmezett nyelven
van megvalósítva, gondoskodj róla, hogy a fő könyvtárban lévő .gitignore
tartalmazzon egy mintabejegyzést, amely az ilyen fájlokat kizárja.  A Python
.pyc és .pyo fájljaira ez már ki van terjesztve.

5. Ha a parancsod egy adott nyelvi verziótól függ, dokumentáld az INSTALL
fájlban.

6. A disztribúció fő könyvtárában van egy command-list.txt fájl, amely típus
szerint kategorizálja a parancsokat, hogy a dokumentáció összefoglaló
parancslistájában a megfelelő alszakaszokban felsorolhatók legyenek.  Adj hozzá
egy bejegyzést a sajátodhoz.  A kategóriák megértéséhez nézd meg a fő
könyvtárban lévő command-list.txt-t.  Ha az új parancs a tipikus Git
munkafolyamat része, és úgy gondolod, hogy elég gyakori ahhoz, hogy a
'git help' megemlítse, rendeld ezt a parancsot egy közös csoporthoz a
[common] oszlopban.

7. Adj a maintainernek egy bekezdést, amit beilleszthet a RelNotes fájlba az
új funkció leírásához; erre jó hely a kísérőlevél [PATCH 0/n].

Ennyi az egész.
