From:	Junio C Hamano <gitster@pobox.com>
To:	git@vger.kernel.org
Cc:	Petr Baudis <pasky@suse.cz>, Linus Torvalds <torvalds@osdl.org>
Subject: Re: sending changesets from the middle of a git tree
Date:	Sun, 14 Aug 2005 18:37:39 -0700
Abstract: Ebben a cikkben JC arról beszél, hogyan rebase-eli a nyilvános
 "seen" branchet az alapvető Git eszközökkel, amikor frissíti a "master"
 branchet, és hogyan működik a "rebase".  Szó esik arról is, hogyan
 vonatkozik ez azokra az egyéni fejlesztőkre, akik patcheket küldenek
 upstreamnek.
Content-type: text/asciidoc

Hogyan rebase-elj egy belső branchből
=====================================

--------------------------------------
Petr Baudis <pasky@suse.cz> writes:

> Dear diary, on Sun, Aug 14, 2005 at 09:57:13AM CEST, I got a letter
> where Junio C Hamano <junkio@cox.net> told me that...
>> Linus Torvalds <torvalds@osdl.org> writes:
>>
>> > Junio, maybe you want to talk about how you move patches from your
>> > "seen" branch to the real branches.
>>
> Actually, wouldn't this be also precisely for what StGIT is intended to?
--------------------------------------

Pontosan ezt érzem én is.  Valahogy arra vártam, hogy Catalin szólaljon
meg.  Mivel a filozófiai gyökereit a quiltre alapozza, ez pont az a fajta
feladat, amelyre az StGIT-et tervezték.

Én most egy egyszerűbbet csináltam, ezúttal csak az alapvető Git
eszközöket használva.

Volt egy maroknyi commitom a 'seen'-ben, amelyek a master előtt jártak, és
szerettem volna hozzáadni némi dokumentációt, megkerülve a szokásomat, hogy
az új dolgokat előbb a 'seen'-be teszem.  Az elején a commitok
származási gráfja így nézett ki:

			     *"seen" head
    master --> #1 --> #2 --> #3

Így a masterből indultam ki, csináltam egy csomó szerkesztést, és commitoltam:

    $ git checkout master
    $ cd Documentation; ed git.txt ...
    $ cd ..; git add Documentation/*.txt
    $ git commit -s

A commit után a származási gráf így nézne ki:

			      *"seen" head
    master^ --> #1 --> #2 --> #3
          \
            \---> master

A régi master most már master^ (a master első szülője).
Az új master commit tartalmazza a dokumentációs frissítéseimet.

Most a "seen" branchet kell kezelnem.

Ez az a fajta helyzet, amely folyton előfordult velem, amikor Linus volt a
maintainer, én pedig contributor, ha úgy tekintünk a "master" branchre, mint a
"maintainer" branchre, a "seen" branchre pedig mint a "contributor" branchre.
A munkád valamikor a "maintainer" branch csúcsán indult, közben sokat
haladtál, és most a maintainer branchen van néhány olyan commit, amely
neked még nincs meg.  A "git rebase" pedig kifejezetten azzal a céllal
íródott, hogy segítsen az olyan branchek karbantartásában, mint a "seen".
_Merge-elhetnéd_ a mastert a 'seen'-be, és mehetnél tovább, de ha végül
cherry-pickelni akarsz, és néhány — de nem feltétlenül az összes —
változtatást vissza akarsz merge-elni a master branchbe, gyakran könnyebbé
teszi a későbbi műveleteket _neked_, ha a "seen"-t rebase-eled (azaz
továbbviszed a változtatásaidat), ahelyett hogy merge-elnéd.  Így lefuttattam
a "git rebase"-t:

    $ git checkout seen
    $ git rebase master seen

Ez annyit tesz, hogy kiválasztja az összes commitot azóta, hogy az aktuális
branch (figyeld meg, hogy most a "seen" branchen vagyok) leágazott a master
branchről, és előre portolja ezeket a változtatásokat.

    master^ --> #1 --> #2 --> #3
	  \                                  *"seen" head
            \---> master --> #1' --> #2' --> #3'

A master^ és a #1 közötti diff a masterre kerül alkalmazásra, és
commitolódik, létrehozva a #1' commitot, a commit-információval (napló,
szerző és dátum) a #1 commitból véve.  Efölé a #2' és a #3' commit
készül el hasonlóan a #2 és a #3 commitból.

A régi #3 már egyik .git/refs/heads/ fájlban sincs rögzítve, így ennek
elvégzése után dangling commitod lesz, ha lefuttattad az fsck-cache-t, ami
normális.  A "seen" tesztelése után lefuttathatod a "git prune"-t, hogy
megszabadulj attól az eredeti három committól.

Amíg a "git rebase"-ről beszélek, beszélnem kellene arról is, hogyan lehet
cherry-pickelni kizárólag az alapvető Git eszközökkel.

Térjünk vissza a korábbi ábrához, más címkékkel.

Te, egyéni fejlesztőként, klónoztad az upstream repository-t, és csináltál
rá néhány commitot.

                              *your "master" head
   upstream --> #1 --> #2 --> #3

Szeretnéd, ha a #2 és a #3 változtatás bekerülne az upstreambe, miközben úgy
érzed, hogy a #1 további finomításokat igényelhet.  Ezért előkészíted a #2-t
és a #3-t e-mailben való beküldésre.

    $ git format-patch master^^ master

Ez két fájlt hoz létre, a 0001-XXXX.patch-et és a 0002-XXXX.patch-et.  Küldd
el őket a projekted maintainerének "To: "-ként, és a levelezőlistádnak
"Cc: "-ként.  Használhatnád a hozzájárult git-send-email szkriptet, ha a
hosztodon megvannak hozzá a szükséges perl modulok, de a szokásos MUA-d is
megteszi, amíg nem rontja el a whitespace-eket a
patchben.

Aztán várnál, és rájönnél, hogy az upstream átvette a változtatásaidat, más
változtatásokkal együtt.

   where                      *your "master" head
  upstream --> #1 --> #2 --> #3
    used   \
   to be     \--> #A --> #2' --> #3' --> #B --> #C
                                                *upstream head

A fenti ábrán a #2' és a #3' commit ugyanazokat a változtatásokat rögzíti,
amelyeket a #2-höz és a #3-hoz tartozó e-mailes beküldésed tartalmazott, de
valószínűleg az upstream maintainer által hozzáadott új sign-off sorral, és
mindenképpen más committer- és származási információval — ezek a #2 és a #3
committól különböző objektumok.

Fetch-elsz az upstreamből, de nem merge-elsz.

    $ git fetch upstream

Ez a frissített upstream headet a .git/FETCH_HEAD-ben hagyja, de nem
nyúl a .git/HEAD-hez vagy a .git/refs/heads/master-hez.
Most lefuttatod a "git rebase"-t.

    $ git rebase FETCH_HEAD master

Korábban azt mondtam, hogy a rebase a branchedről az összes commitot az
upstream head tetejére alkalmazza.  Nos, hazudtam.  A "git rebase" ennél egy
kicsit okosabb, és észreveszi, hogy a #2-t és a #3-t nem kell alkalmazni, így
csak a #1-et alkalmazza.  A commitok származási gráfja valahogy így alakul:

   where                     *your old "master" head
  upstream --> #1 --> #2 --> #3
    used   \                      your new "master" head*
   to be     \--> #A --> #2' --> #3' --> #B --> #C --> #1'
                                                *upstream
                                                head

Ismét: a "git prune" eldobná a használaton kívüli #1–#3 commitokat, és az új
"master" headből indulva folytatod, amely a #1' commit.

-jc
