Subject: [HOWTO] Using post-update hook
Message-ID: <7vy86o6usx.fsf@assigned-by-dhcp.cox.net>
From: Junio C Hamano <gitster@pobox.com>
Date: Fri, 26 Aug 2005 18:19:10 -0700
Abstract: Ebben a how-to cikkben JC arról beszél, hogyan használja a
 post-update hookot a https://www.kernel.org/pub/software/scm/git/docs/
 címen megjelenő Git dokumentációs oldal automatikus frissítésére.
Content-type: text/asciidoc

Hogyan építs újra az update hookból
===================================

A https://www.kernel.org/pub/software/scm/git/docs/ alatti oldalak a git.git
projekt Documentation/ könyvtárából épülnek, és naprakészen kell tartani
őket.  A www.kernel.org/ szerverek tükrözöttek, és úgy tudom, hogy a tükör
eredete a $some.kernel.org gépen van, amelyen kaptam egy hozzáférést, amikor
átvettem a Git maintainerséget Linustól.

A how-to szempontjából releváns könyvtárak ez a kettő:

    /pub/scm/git/git.git/	The public Git repository.
    /pub/software/scm/git/docs/	The HTML documentation page.

Így az ottani home könyvtáram alatt létrehoztam egy repository-t a
dokumentáció előállításához.

    $ cd
    $ mkdir doc-git && cd doc-git
    $ git clone /pub/scm/git/git.git/ docgen

Ami szükséges: frissíteni a $HOME/doc-git/docgen/ working tree-t, ott
felépíteni a HTML doksit, és a végeredményt telepíteni a
/pub/software/scm/git/docs/ könyvtárba.  Ezért írtam egy kis
szkriptet:

    $ cat >dododoc.sh <<\EOF
    #!/bin/sh
    cd $HOME/doc-git/docgen || exit

    unset GIT_DIR

    git pull /pub/scm/git/git.git/ master &&
    cd Documentation &&
    make install-webdoc
    EOF

Kezdetben kézzel futtattam ezt, valahányszor push-oltam a nyilvános Git
repository-ba.  Aztán csináltam egy cron jobot, ami naponta kétszer futott.
A mostani megközelítés a post-update hook mechanizmust használja, így:

    $ cat >/pub/scm/git/git.git/hooks/post-update <<\EOF
    #!/bin/sh
    #
    # An example hook script to prepare a packed repository for use over
    # dumb transports.
    #
    # To enable this hook, make this file executable by "chmod +x post-update".

    case " $* " in
    *' refs/heads/master '*)
            echo $HOME/doc-git/dododoc.sh | at now
            ;;
    esac
    exec git-update-server-info
    EOF
    $ chmod +x /pub/scm/git/git.git/hooks/post-update

Négy dolgot érdemes megemlíteni:

 - Az update-hook azután fut, hogy a repository elfogad egy "git push"-t, az
   én felhasználói jogosultságommal.  Argumentumként megkapja a frissült refek
   teljes nevét.  Az én post-update-em csak akkor futtatja a dododoc.sh
   szkriptet, amikor a master head frissül.

 - Amikor az update-hook fut, a GIT_DIR-t a hívó receive-pack '.'-ra állítja.
   Ezt örökli az "at" paranccsal futtatott dododoc.sh, és ki kell törölni;
   különben a "git pull", amit a $HOME/doc-git/docgen/ repository-ba végez, nem
   működne helyesen.

 - Az update hook szkript stdoutja nincs a git push-hoz kötve; a parancs
   nehéz részét az "at"-en belül futtatom, hogy a végrehajtási jelentést
   e-mailben kapjam meg.

 - Ez még kezdetleges, és nem véd az egyidejű make-hívások egymásra taposása
   ellen.  Ehhez valamilyen zárolási mechanizmust kellene hozzáadnom.
