Date: Fri, 9 Nov 2007 08:28:38 -0800 (PST)
From: Linus Torvalds <torvalds@linux-foundation.org>
Subject: corrupt object on git-gc
Abstract: Néhány trükk blob-objektumok rekonstruálásához egy sérült
 repository megjavítása érdekében.
Content-type: text/asciidoc

Hogyan állíts helyre egy sérült blob-objektumot
===============================================

-----------------------------------------------------------
On Fri, 9 Nov 2007, Yossi Leybovich wrote:
>
> Did not help still the repository look for this object?
> Any one know how can I track this object and understand which file is it
-----------------------------------------------------------

Pontosan *azért*, mert a SHA-1 hash kriptográfiailag biztonságos, maga a hash
valójában semmit sem árul el; egy sérült objektum megjavításához alapvetően
meg kell találnod hozzá az "eredeti forrást".

Ennek a legegyszerűbb módja szinte mindig az, ha van biztonsági mentésed, és
ugyanazt az objektumot megtalálod máshol. A biztonsági mentés tényleg jó
ötlet, és a Git elég egyszerűvé teszi (ha más nem, csak klónozd a repository-t
máshová, és ügyelj rá, hogy *ne* hard-linkelt klónt használj, és lehetőleg ne
ugyanazt a lemezt/gépet).

De mivel úgy tűnik, most nincs biztonsági mentésed, a jó hír az, hogy
különösen egyetlen sérült blob esetén ezek a dolgok *tényleg* valamennyire
hibakereshetők.

Először is helyezd el máshová a sérült objektumot, és *mentsd el*. A sérülés
eddigi leggyakoribb oka a memóriasérülés volt, de még így is vannak, akiket
érdekelne a sérülés megtekintése - viszont a sérülést alapvetően lehetetlen
megítélni, amíg az eredeti objektumot is nem látjuk, így most a sérült
objektum haszontalan, de a jövő szempontjából nagyon érdekes, abban a
reményben, hogy újra tudsz alkotni egy nem sérült verziót.

-----------------------------------------------------------
So:

> ib]$ mv .git/objects/4b/9458b3786228369c63936db65827de3cc06200 ../
-----------------------------------------------------------

Ez a helyes teendő, bár általában a legjobb a teljes SHA-1 nevén elmenteni
(az eredményből épp most hagytad le a "4b"-t ;).

Nézzük, mit árul ez el nekünk:

-----------------------------------------------------------
> ib]$ git-fsck --full
> broken link from    tree 2d9263c6d23595e7cb2a21e5ebbb53655278dff8
>              to    blob 4b9458b3786228369c63936db65827de3cc06200
> missing blob 4b9458b3786228369c63936db65827de3cc06200
-----------------------------------------------------------

Oké, eltávolítottam a "dangling commit" üzeneteket, mert azok csak arról
szólnak, hogy valószínűleg rebase-eltél stb., így egyáltalán nem érdekesek.
De ami marad, az még mindig nagyon hasznos. Konkrétan: most már tudjuk, melyik
tree mutat rá!

Most a következőt teheted

	git ls-tree 2d9263c6d23595e7cb2a21e5ebbb53655278dff8

amely valami ilyesmit fog mutatni

	100644 blob 8d14531846b95bfa3564b58ccfb7913a034323b8    .gitignore
	100644 blob ebf9bf84da0aab5ed944264a5db2a65fe3a3e883    .mailmap
	100644 blob ca442d313d86dc67e0a2e5d584b465bd382cbf5c    COPYING
	100644 blob ee909f2cc49e54f0799a4739d24c4cb9151ae453    CREDITS
	040000 tree 0f5f709c17ad89e72bdbbef6ea221c69807009f6    Documentation
	100644 blob 1570d248ad9237e4fa6e4d079336b9da62d9ba32    Kbuild
	100644 blob 1c7c229a092665b11cd46a25dbd40feeb31661d9    MAINTAINERS
	...

és most kell lennie egy ilyen sornak

	10064 blob 4b9458b3786228369c63936db65827de3cc06200	my-magic-file

a kimenetben. Ez már *sokat* elárul: megmondja, melyik fájlból származott a
sérült blob!

Persze ez nem árul el egészen eleget: nem mondja meg, a fájl melyik
*verziója* nem íródott ki helyesen! Lehet, hogy nagyon szerencsés vagy, és ez
az a verzió, amely már ki van checkoutolva a working tree-dben, amely esetben
ennek a problémának a megoldása tényleg egyszerű, csak futtasd

	git hash-object -w my-magic-file

újra, és ha kiírja a hiányzó SHA-1-et (4b945..), akkor készen is vagy!

De ez a nagyon szerencsés eset, úgyhogy tegyük fel, hogy valamelyik régebbi
verzió sérült meg. Hogyan állapítod meg, melyik verzió volt az?

A legegyszerűbb módja, ha ezt futtatod

	git log --raw --all --full-history -- subdirectory/my-magic-file

és ez megmutatja az adott fájl teljes naplóját (vedd figyelembe, hogy a tree,
amid volt, nem feltétlenül a legfelső szintű tree, így magadnak kell
kitalálnod, melyik alkönyvtárban volt), és mivel raw kimenetet kérsz, most
valami ilyesmit kapsz

	commit abc
	Author:
	Date:
	  ..
	:100644 100644 4b9458b... newsha... M  somedirectory/my-magic-file


	commit xyz
	Author:
	Date:

	  ..
	:100644 100644 oldsha... 4b9458b... M	somedirectory/my-magic-file

és ez valójában megmondja, mi volt az adott fájl *előző* és *következő*
verziója! Így most megnézheted ezeket ("oldsha", illetve "newsha"), és
remélhetőleg gyakran commitoltál, és a régebbi és újabb verziók
megnézésével újra tudod alkotni a hiányzó my-magic-file verziót!

Ha ezt meg tudod tenni, most újra tudod alkotni a hiányzó objektumot ezzel

	git hash-object -w <recreated-file>

és a repository-d újra rendben van!

(Egyébként figyelmen kívül hagyhattad volna az fsck-t, és kezdhetted volna egy

	git log --raw --all

futtatásával, majd egyszerűen megkereshetted volna a hiányzó objektum
sha-ját (4b9458b..) az egészben. Rajtad múlik - a Gitnek *van* rengeteg
információja, csak egyetlen konkrét blob-verzió hiányzik.

A tree-k és különösen a commitok újraalkotásának megkísérlése *sokkal*
nehezebb. Szóval szerencséd volt, hogy ez egy blob. Egészen valószínű, hogy
újra tudod alkotni a dolgot.

			Linus
