Date: Wed, 16 Oct 2013 04:34:01 -0400
From: Jeff King <peff@peff.net>
Subject: pack corruption post-mortem
Abstract: Egy sérült objektum helyreállítása, amikor nincs elérhető jó másolat.
Content-type: text/asciidoc

Hogyan állíts helyre egy objektumot a nulláról
==============================================

Nemrég elém került egy repository sérült packfile-lal, és megkérdezték, hogy
az adat helyreállítható-e. Ez a post-mortem leírja azokat a lépéseket,
amelyeket a probléma kivizsgálásához és javításához tettem. Gondoltam, mások
érdekesnek találhatják a folyamatot, és segíthet valakinek ugyanebben a
helyzetben.

********************************
Megjegyzés: Ebben az esetben nem volt elérhető jó másolata a repository-nak. A
sokkal egyszerűbb esethez, amikor a sérült objektumot máshonnan meg tudod
szerezni, lásd link:recover-corrupted-blob-object.html[ezt a howtót].
********************************

Egy fsck-val kezdtem, amely pontosan egy objektummal talált problémát (lent
a $pack és a $obj jelölést használtam, hogy a kimenet olvasható maradjon, és
azért is, mert később hivatkozni fogok rájuk):

-----------
    $ git fsck
    error: $pack SHA1 checksum mismatch
    error: index CRC mismatch for object $obj from $pack at offset 51653873
    error: inflate: data stream error (incorrect data check)
    error: cannot unpack $obj from $pack at offset 51653873
-----------

A pack ellenőrzőösszegének hibája azt jelenti, hogy valahol egy bájt
elromlott, és ez feltehetően az említett objektumban van (mivel az index
ellenőrzőösszege és a zlib is hibázott).

A zlib forráskódját olvasva rájöttem, hogy az "incorrect data check" azt
jelenti, hogy a zlib adat végén lévő adler-32 ellenőrzőösszeg nem egyezett a
kibontott adattal. Így az adat zlib-en való átléptetése nem segítene, mivel
egészen a legvégéig nem hibázott, amikor rájövünk, hogy a CRC nem egyezik.
A problémás bájtok bárhol lehetnek az objektum adatában.

Az első dolog, amit tettem, hogy kiszedtem a hibás adatot a packfile-ból.
Tudnom kellett, mekkora az objektum, amit ezzel derítettem ki:

------------
    $ git show-index <$idx | cut -d' ' -f1 | sort -n | grep -A1 51653873
    51653873
    51664736
------------

A show-index megadja az objektumok listáját és az offsetjeiket. Az offseteken
kívül mindent eldobunk, majd rendezzük őket, hogy az érdekes offsetünket
(amelyet a fenti fsck kimenetből kaptunk) közvetlenül a következő objektum
offsetje kövesse. Most már tudjuk, hogy az objektum adata 10863 bájt hosszú,
és megszerezhetjük ezzel:

------------
  dd if=$pack of=object bs=1 skip=51653873 count=10863
------------

Megvizsgáltam az adat hexdumpját, bármilyen nyilvánvaló képtelenséget keresve
(pl. egy 4K-nyi nulla-sorozat a fájlrendszer sérülésének jó jele lenne). De
minden elég ésszerűnek tűnt.

Vedd észre, hogy az "object" fájl nem alkalmas arra, hogy közvetlenül a
zlib-nek adjuk; van rajta a git csomagolt objektum fejléce, amely változó
hosszúságú. Ezt le akarjuk vágni, hogy közvetlenül elkezdhessünk játszani a
zlib adattal. Vagy manuálisan végigdolgozhatod magad rajta (a formátumot a
linkgit:gitformat-pack[5] írja le),
vagy végigléptethetsz rajta egy debuggerben. Én az utóbbit tettem, egy
érvényes packet létrehozva így:

------------
    # pack magic and version
    printf 'PACK\0\0\0\2' >tmp.pack
    # pack has one object
    printf '\0\0\0\1' >>tmp.pack
    # now add our object data
    cat object >>tmp.pack
    # and then append the pack trailer
    /path/to/git.git/t/helper/test-tool sha1 -b <tmp.pack >trailer
    cat trailer >>tmp.pack
------------

majd a "git index-pack tmp.pack" futtatásával a debuggerben (megállva az
unpack_raw_entry-nél). Ezt megtéve rájöttem, hogy 3 bájtnyi fejléc volt
(és magának a fejlécnek ép típusa és mérete volt). Így ezeket levágtam
ezzel:

------------
    dd if=object of=zlib bs=1 skip=3
------------

Az eredményt átfuttattam a zlib inflate-jén egy egyedi C program
segítségével. És bár jelentette a hibát, a helyes számú kimeneti bájtot
megkaptam (azaz egyezett a git méret-fejlécével, amelyet fent dekódoltunk). De
az eredményt visszaadva a "git hash-object"-nek nem ugyanazt a sha1-et
állította elő. Tehát volt néhány rossz bájt, de nem tudtam, melyek. A fájl
történetesen C forráskód volt, így reméltem, hogy észreveszek benne valami
nyilvánvalóan hibásat, de nem sikerült. Még le is fordítottam!

Megpróbáltam összehasonlítani ugyanannak az útvonalnak a repository-ban lévő
más verzióival is, remélve, hogy lesz a diffnek valamilyen része, amelynek
nincs értelme. Sajnos ez történetesen ennek a bizonyos fájlnak az egyetlen
revíziója volt a repository-ban, így nem volt mihez hasonlítanom.

Így más megközelítést választottam. Azzal a feltételezéssel dolgozva, hogy a
sérülés egyetlen bájtra korlátozódik, írtam egy programot, amely minden bájtot
egyenként elront, és megpróbálja kibontani az eredményt. Mivel az objektum
tömörítve csak 10K volt, ez körülbelül 2,5M próbálkozást jelentett, ami néhány
percig tartott.

A program, amelyet használtam, itt van:

----------------------------------------------
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <signal.h>
#include <zlib.h>

static int try_zlib(unsigned char *buf, int len)
{
	/* make this absurdly large so we don't have to loop */
	static unsigned char out[1024*1024];
	struct z_stream_s z;
	int ret;

	memset(&z, 0, sizeof(z));
	inflateInit(&z);

	z.next_in = buf;
	z.avail_in = len;
	z.next_out = out;
	z.avail_out = sizeof(out);

	ret = inflate(&z, 0);
	inflateEnd(&z);
	return ret >= 0;
}

/* eye candy */
static int counter = 0;
static void progress(int sig)
{
	fprintf(stderr, "\r%d", counter);
	alarm(1);
}

int main(void)
{
	/* oversized so we can read the whole buffer in */
	unsigned char buf[1024*1024];
	int len;
	unsigned i, j;

	signal(SIGALRM, progress);
	alarm(1);

	len = read(0, buf, sizeof(buf));
	for (i = 0; i < len; i++) {
		unsigned char c = buf[i];
		for (j = 0; j <= 0xff; j++) {
			buf[i] = j;

			counter++;
			if (try_zlib(buf, len))
				printf("i=%d, j=%x\n", i, j);
		}
		buf[i] = c;
	}

	alarm(0);
	fprintf(stderr, "\n");
	return 0;
}
----------------------------------------------

Lefordítottam és futtattam ezzel:

-------
  gcc -Wall -Werror -O3 munge.c -o munge -lz
  ./munge <zlib
-------


Volt néhány hamis pozitív az elején (ha "no data"-t írsz a zlib fejlécbe, a
zlib szerint minden rendben :) ). De körülbelül félúton kaptam egy találatot:

-------
  i=5642, j=c7
-------

Hagytam végigfutni, és a végén kaptam még néhány találatot (ahol a CRC-t
rontotta el, hogy egyezzen a hibás adatunkkal). Így jó esély volt rá, hogy ez
a középső találat a probléma forrása.

Megerősítettem úgy, hogy módosítottam a bájtot egy hexszerkesztőben,
kibontottam az eredményt a zlib-bel (nincs hiba!), majd a kimenetet
átirányítottam a "git hash-object"-be, amely a hibás objektum sha1-ét
jelentette. Siker!

Magát a packfile-t ezzel javítottam meg:

-------
  chmod +w $pack
  printf '\xc7' | dd of=$pack bs=1 seek=51659518 conv=notrunc
  chmod -w $pack
-------

A `\xc7` a "munge" programunk által talált helyettesítő bájtból származik.
Az 51659518 offsetet úgy kapjuk, hogy vesszük az eredeti objektum-offsetet
(51653873), hozzáadjuk a "munge" által talált helyettesítési offsetet (5642),
majd visszaadjuk a levágott 3 bájtnyi git fejlécet.

Ezután a "git fsck" tisztán lefutott.

Ami magát a sérülést illeti, szerencsém volt, hogy tényleg egyetlen bájt
volt. Valójában kiderült, hogy egyetlen bit. A 0xc7 bájt 0xc5-re sérült. Így
feltehetően hibás hardver okozta, vagy egy kozmikus sugár.

És a félbehagyott kísérlet, hogy megnézzem a kibontott kimenetet, hátha látom,
mi a baj? Örökké nézhettem volna, sosem találom meg. Íme a diff aközött, amivé
a sérült adat kibomlik, és a valódi adat között:

--------------
  -       cp = strtok (arg, "+");
  +       cp = strtok (arg, ".");
--------------

Egyetlen bájtot módosított, és mégis érvényes, olvasható C lett belőle, amely
történetesen valami teljesen mást csinált! Az egyik tanulság, hogy egy
kevésbé peches napon a zlib kimenetének megnézése valójában hasznos lehetett
volna, mivel a legtöbb véletlenszerű változtatás ténylegesen eltörné a C
kódot.

De ami fontosabb, a git hashelése és ellenőrzőösszeg-számítása észrevett egy
problémát, amely egy másik rendszerben könnyen észrevétlen maradhatott volna.
Az eredmény még lefordult, de egy érdekes bugot okozott volna (amit valami
véletlenszerű commitra fogtak volna).


A kaland folytatódik...
-----------------------

Végül újra megcsináltam ezt! Ugyanaz az entitás, új hardver. A feltételezés
ezen a ponton az, hogy a régi lemez rontotta el a packfile-t, majd a sérülés
átvándorolt az új hardverre (mert rsync-kel vagy hasonlóval történt, és a
migráció idején nem végeztek fsck-t).

Ezúttal az érintett blob több mint 20 megabájt volt, ami túl nagy volt ahhoz,
hogy brute-force-oljam. Követtem a fenti utasításokat a `zlib` fájl
létrehozásához. Aztán az alábbi `inflate` programmal szedtem ki belőle a
sérült adatot. Ennek a kimenetnek a vizsgálata adott egy utalást arról, hol
volt a sérülés a fájlban. De most magával a fájllal dolgoztam, nem a zlib
tartalmával. Így az objektum sha1-ét és a sérülés hozzávetőleges területét
ismerve az alábbi `sha1-munge` programmal brute-force-oltam ki a helyes
bájtot.

Íme az inflate program (lényegében `gunzip`, de a `.gz` fejléc feldolgozása
nélkül):

--------------------------
#include <stdio.h>
#include <string.h>
#include <zlib.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
	/*
	 * oversized so we can read the whole buffer in;
	 * this could actually be switched to streaming
	 * to avoid any memory limitations
	 */
	static unsigned char buf[25 * 1024 * 1024];
	static unsigned char out[25 * 1024 * 1024];
	int len;
	struct z_stream_s z;
	int ret;

	len = read(0, buf, sizeof(buf));
	memset(&z, 0, sizeof(z));
	inflateInit(&z);

	z.next_in = buf;
	z.avail_in = len;
	z.next_out = out;
	z.avail_out = sizeof(out);

	ret = inflate(&z, 0);
	if (ret != Z_OK && ret != Z_STREAM_END)
		fprintf(stderr, "initial inflate failed (%d)\n", ret);

	fprintf(stderr, "outputting %lu bytes", z.total_out);
	fwrite(out, 1, z.total_out, stdout);
	return 0;
}
--------------------------

És íme a `sha1-munge` program:

--------------------------
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <signal.h>
#include <openssl/sha.h>
#include <stdlib.h>

/* eye candy */
static int counter = 0;
static void progress(int sig)
{
	fprintf(stderr, "\r%d", counter);
	alarm(1);
}

static const signed char hexval_table[256] = {
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 00-07 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 08-0f */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 10-17 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 18-1f */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 20-27 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 28-2f */
	  0,  1,  2,  3,  4,  5,  6,  7,		/* 30-37 */
	  8,  9, -1, -1, -1, -1, -1, -1,		/* 38-3f */
	 -1, 10, 11, 12, 13, 14, 15, -1,		/* 40-47 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 48-4f */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 50-57 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 58-5f */
	 -1, 10, 11, 12, 13, 14, 15, -1,		/* 60-67 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 68-67 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 70-77 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 78-7f */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 80-87 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 88-8f */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 90-97 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* 98-9f */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* a0-a7 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* a8-af */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* b0-b7 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* b8-bf */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* c0-c7 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* c8-cf */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* d0-d7 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* d8-df */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* e0-e7 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* e8-ef */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* f0-f7 */
	 -1, -1, -1, -1, -1, -1, -1, -1,		/* f8-ff */
};

static inline unsigned int hexval(unsigned char c)
{
return hexval_table[c];
}

static int get_sha1_hex(const char *hex, unsigned char *sha1)
{
	int i;
	for (i = 0; i < 20; i++) {
		unsigned int val;
		/*
		 * hex[1]=='\0' is caught when val is checked below,
		 * but if hex[0] is NUL we have to avoid reading
		 * past the end of the string:
		 */
		if (!hex[0])
			return -1;
		val = (hexval(hex[0]) << 4) | hexval(hex[1]);
		if (val & ~0xff)
			return -1;
		*sha1++ = val;
		hex += 2;
	}
	return 0;
}

int main(int argc, char **argv)
{
	/* oversized so we can read the whole buffer in */
	static unsigned char buf[25 * 1024 * 1024];
	char header[32];
	int header_len;
	unsigned char have[20], want[20];
	int start, len;
	SHA_CTX orig;
	unsigned i, j;

	if (!argv[1] || get_sha1_hex(argv[1], want)) {
		fprintf(stderr, "usage: sha1-munge <sha1> [start] <file.in\n");
		return 1;
	}

	if (argv[2])
		start = atoi(argv[2]);
	else
		start = 0;

	len = read(0, buf, sizeof(buf));
	header_len = sprintf(header, "blob %d", len) + 1;
	fprintf(stderr, "using header: %s\n", header);

	/*
	 * We keep a running sha1 so that if you are munging
	 * near the end of the file, we do not have to re-sha1
	 * the unchanged earlier bytes
	 */
	SHA1_Init(&orig);
	SHA1_Update(&orig, header, header_len);
	if (start)
		SHA1_Update(&orig, buf, start);

	signal(SIGALRM, progress);
	alarm(1);

	for (i = start; i < len; i++) {
		unsigned char c;
		SHA_CTX x;

#if 0
		/*
		 * deletion -- this would not actually work in practice,
		 * I think, because we've already committed to a
		 * particular size in the header. Ditto for addition
		 * below. In those cases, you'd have to do the whole
		 * sha1 from scratch, or possibly keep three running
		 * "orig" sha1 computations going.
		 */
		memcpy(&x, &orig, sizeof(x));
		SHA1_Update(&x, buf + i + 1, len - i - 1);
		SHA1_Final(have, &x);
		if (!memcmp(have, want, 20))
			printf("i=%d, deletion\n", i);
#endif

		/*
		 * replacement -- note that this tries each of the 256
		 * possible bytes. If you suspect a single-bit flip,
		 * it would be much shorter to just try the 8
		 * bit-flipped variants.
		 */
		c = buf[i];
		for (j = 0; j <= 0xff; j++) {
			buf[i] = j;

			memcpy(&x, &orig, sizeof(x));
			SHA1_Update(&x, buf + i, len - i);
			SHA1_Final(have, &x);
			if (!memcmp(have, want, 20))
				printf("i=%d, j=%02x\n", i, j);
		}
		buf[i] = c;

#if 0
		/* addition */
		for (j = 0; j <= 0xff; j++) {
			unsigned char extra = j;
			memcpy(&x, &orig, sizeof(x));
			SHA1_Update(&x, &extra, 1);
			SHA1_Update(&x, buf + i, len - i);
			SHA1_Final(have, &x);
			if (!memcmp(have, want, 20))
				printf("i=%d, addition=%02x", i, j);
		}
#endif

		SHA1_Update(&orig, buf + i, 1);
		counter++;
	}

	alarm(0);
	fprintf(stderr, "\r%d\n", counter);
	return 0;
}
--------------------------
