From: Junio C Hamano <gitster@pobox.com>
To: git@vger.kernel.org
Subject: [HOWTO] Reverting an existing commit
Abstract: Ebben a cikkben JC egy kis, életből vett példát mutat a 'git revert'
 parancs használatára, valamint egy ideiglenes branch és tag használatára a
 biztonság és az egyszerűbb helyesség-ellenőrzés kedvéért.
Date: Mon, 29 Aug 2005 21:39:02 -0700
Content-type: text/asciidoc
Message-ID: <7voe7g3uop.fsf@assigned-by-dhcp.cox.net>

Hogyan revertelj egy meglévő commitot
=====================================

Az egyik változtatás, amelyet a 'master' branchbe pull-oltam, kiderült, hogy
eltöri a Git buildelését GCC 2.95-tel.  Bár jó szándékú hordozhatósági
javítások voltak, az is fontos volt, hogy a dolgok működjenek gcc-2.95-tel.
Íme, mit tettem, hogy visszavonjam a változtatást a 'master' branchen, és
igazítsam a 'seen' branchet, az alapvető Git eszközöket és csupasz
Porcelaint használva.

Először készíts egy eldobható branchet arra az esetre, ha elrontanám a dolgokat.

------------------------------------------------
$ git checkout -b revert-c99 master
------------------------------------------------

Most a 'revert-c99' branchen vagyok.  Találjuk ki, melyik commitot kell
visszavonni.  Történetesen tudom, hogy a 'master' branch teteje egy merge, és
a második szülője (azaz az idegen commit, amelyből merge-eltem) tartalmazza
a változtatást, amelyet vissza szeretnék vonni.  Továbbá történetesen tudom,
hogy az a merge 5 vagy annyi commitot hozott be:

------------------------------------------------
$ git show-branch --more=4 master master^2 | head
* [master] Merge refs/heads/portable from http://www.cs.berkeley....
 ! [master^2] Replace C99 array initializers with code.
--
-  [master] Merge refs/heads/portable from http://www.cs.berkeley....
*+ [master^2] Replace C99 array initializers with code.
*+ [master^2~1] Replace unsetenv() and setenv() with older putenv().
*+ [master^2~2] Include sys/time.h in daemon.c.
*+ [master^2~3] Fix ?: statements.
*+ [master^2~4] Replace zero-length array decls with [].
*  [master~1] tutorial note about git branch
------------------------------------------------

A fenti '--more=4' azt jelenti: "miután elérjük a refek merge-alapját,
mutass, amíg négy további közös commitot meg nem jelenítünk".  Az az utolsó
commit ott lett volna, ahol a "portable" branch leágazott a fő git.git
repository-ról, így ez mindent megmutatna mindkét branchen azóta.  A kimenetet
csak az első maroknyira korlátoztam a 'head' segítségével.

Most már tudom, hogy a 'master^2~4' (ejtsd: "keresd meg a 'master' második
szülőjét, majd menj vissza négy generációt az első szülőt követve") az, amit
vissza szeretnék vonni.  Mivel azt is el akarom mondani, miért vonom vissza,
a '-n' kapcsolót adom a 'git revert'-nek.  Ez megakadályozza, hogy ténylegesen
commitot készítsen, helyette a 'git revert' a '.msg' fájlban hagyja a
commit napló-üzenetet, amelyet használni akart:

------------------------------------------------
$ git revert -n master^2~4
$ cat .msg
Revert "Replace zero-length array decls with []."

This reverts 6c5f9baa3bc0d63e141e0afc23110205379905a4 commit.
$ git diff HEAD ;# to make sure what we are reverting makes sense.
$ make CC=gcc-2.95 clean test ;# make sure it fixed the breakage.
$ make clean test ;# make sure it did not cause other breakage.
------------------------------------------------

A visszavont változtatásnak van értelme (a 'diff' kimenetének elolvasásából),
tényleg megoldja a problémát (a 'make CC=gcc-2.95' tesztből), és nem okoz új
törést (az utolsó 'make test'-ből).  Készen állok a commitolásra:

------------------------------------------------
$ git commit -a -s ;# read .msg into the log,
                    # and explain why I am reverting.
------------------------------------------------

Bármelyik fenti lépésnél elronthattam volna, de a legrosszabb esetben csak
lefuttathattam volna a 'git checkout master'-t, hogy elölről kezdjem.
Szerencsére nem kellett; amim az aktuális 'revert-c99' branchen van, az az,
amit akarok.  Úgyhogy merge-eljük ezt vissza a 'master'-be:

------------------------------------------------
$ git checkout master
$ git merge revert-c99 ;# this should be a fast-forward
Updating from 10d781b9caa4f71495c7b34963bef137216f86a8 to e3a693c...
 cache.h        |    8 ++++----
 commit.c       |    2 +-
 ls-files.c     |    2 +-
 receive-pack.c |    2 +-
 server-info.c  |    2 +-
 5 files changed, 8 insertions(+), 8 deletions(-)
------------------------------------------------

Ezen a ponton nincs szükség a teszt megismétlésére.  Fast-forwardoltunk, és
tudjuk, hogy a 'master' pontosan megegyezik a 'revert-c99'-cel.  Sőt:

------------------------------------------------
$ git diff master..revert-c99
------------------------------------------------

nem mond semmit.

Aztán a szokásos módon rebase-eljük a 'seen' branchet.

------------------------------------------------
$ git checkout seen
$ git tag seen-anchor seen
$ git rebase master
* Applying: Redo "revert" using three-way merge machinery.
First trying simple merge strategy to cherry-pick.
* Applying: Remove git-apply-patch-script.
First trying simple merge strategy to cherry-pick.
Simple cherry-pick fails; trying Automatic cherry-pick.
Removing Documentation/git-apply-patch-script.txt
Removing git-apply-patch-script
* Applying: Document "git cherry-pick" and "git revert"
First trying simple merge strategy to cherry-pick.
* Applying: mailinfo and applymbox updates
First trying simple merge strategy to cherry-pick.
* Applying: Show commits in topo order and name all commits.
First trying simple merge strategy to cherry-pick.
* Applying: More documentation updates.
First trying simple merge strategy to cherry-pick.
------------------------------------------------

A 'seen-anchor' ideiglenes tag csak az én óvatosságom, arra az esetre, ha a
'git rebase' elrontaná.  Ezután ezeket futtathatom helyesség-ellenőrzésre:

------------------------------------------------
$ git diff seen-anchor..seen ;# make sure we got the master fix.
$ make CC=gcc-2.95 clean test ;# make sure it fixed the breakage.
$ make clean test ;# make sure it did not cause other breakage.
------------------------------------------------

Minden rendben van.  Már nincs szükségem az ideiglenes branchre vagy tagre,
úgyhogy távolítsuk el őket:

------------------------------------------------
$ rm -f .git/refs/tags/seen-anchor
$ git branch -d revert-c99
------------------------------------------------

Vészhelyzeti javítás volt, úgyhogy akár merge-elhetjük is a
'release candidate' branchbe, bár arra számítok, hogy a következő kiadás még
néhány nap:

------------------------------------------------
$ git checkout rc
$ git pull . master
Packing 0 objects
Unpacking 0 objects

* commit-ish: e3a693c...	refs/heads/master from .
Trying to merge e3a693c... into 8c1f5f0... using 10d781b...
Committed merge 7fb9b7262a1d1e0a47bbfdcbbcf50ce0635d3f8f
 cache.h        |    8 ++++----
 commit.c       |    2 +-
 ls-files.c     |    2 +-
 receive-pack.c |    2 +-
 server-info.c  |    2 +-
 5 files changed, 8 insertions(+), 8 deletions(-)
------------------------------------------------

A végső repository-státusz pedig így néz ki:

------------------------------------------------
$ git show-branch --more=1 master seen rc
! [master] Revert "Replace zero-length array decls with []."
 ! [seen] git-repack: Add option to repack all objects.
  * [rc] Merge refs/heads/master from .
---
 +  [seen] git-repack: Add option to repack all objects.
 +  [seen~1] More documentation updates.
 +  [seen~2] Show commits in topo order and name all commits.
 +  [seen~3] mailinfo and applymbox updates
 +  [seen~4] Document "git cherry-pick" and "git revert"
 +  [seen~5] Remove git-apply-patch-script.
 +  [seen~6] Redo "revert" using three-way merge machinery.
  - [rc] Merge refs/heads/master from .
++* [master] Revert "Replace zero-length array decls with []."
  - [rc~1] Merge refs/heads/master from .
... [master~1] Merge refs/heads/portable from http://www.cs.berkeley....
------------------------------------------------
