Date: Fri, 19 Dec 2008 00:45:19 -0800
From: Linus Torvalds <torvalds@linux-foundation.org>, Junio C Hamano <gitster@pobox.com>
Subject: Re: Odd merge behaviour involving reverts
Abstract: Néha egy branchről, amelyet már merge-eltek a mainline-ba, később
 kiderül, hogy hibás.  Linus és Junio útmutatást ad az ilyen elhamarkodott
 merge utáni helyreállításhoz és a fejlesztés folytatásához, miután a hibás
 branch javításra került.
Message-ID: <7vocz8a6zk.fsf@gitster.siamese.dyndns.org>
References: <alpine.LFD.2.00.0812181949450.14014@localhost.localdomain>
Content-type: text/asciidoc

Hogyan revertelj egy hibás merge-t
==================================

Alan <alan@clueserver.org> ezt mondta:

    I have a master branch.  We have a branch off of that that some
    developers are doing work on.  They claim it is ready. We merge it
    into the master branch.  It breaks something so we revert the merge.
    They make changes to the code.  they get it to a point where they say
    it is ok and we merge again.

    When examined, we find that code changes made before the revert are
    not in the master branch, but code changes after are in the master
    branch.

és segítséget kért, hogyan álljon helyre ebből a helyzetből.

A "merge visszavonása" utáni előzmény közvetlenül így nézne ki:

 ---o---o---o---M---x---x---W
               /
       ---A---B

ahol az A és a B a nem túl jól sikerült oldalági fejlesztésen van, az M az a
merge, amely ezeket az elhamarkodott változtatásokat behozza a mainline-ba, az
x-ek olyan változtatások, amelyek nem kapcsolódnak ahhoz, amit az oldalági
branch csinált, és már a mainline-on készültek, a W pedig az "M merge
visszavonása" (nem úgy néz ki a W, mint a fejjel lefelé fordított M?).
Más szóval: a `"diff W^..W"` hasonló a `"diff -R M^..M"`-hez.

Egy merge ilyen "visszavonása" a következővel végezhető el:

    $ git revert -m 1 M

Miután az oldalági branch fejlesztői kijavítják a hibáikat, az előzmény így
nézhet ki:

 ---o---o---o---M---x---x---W---x
               /
       ---A---B-------------------C---D

ahol a C és a D azt javítja, ami az A-ban és a B-ben elromlott, és lehet, hogy
a W után már van néhány más változtatásod a mainline-on.

Ha merge-eled a frissített oldalági branchet (a csúcsán a D-vel), az A-ban
vagy a B-ben végzett változtatások egyike sem lesz benne az eredményben, mert
azokat a W visszavonta.  Ezt látta Alan.

Linus elmagyarázza a helyzetet:

    Reverting a regular commit just effectively undoes what that commit
    did, and is fairly straightforward. But reverting a merge commit also
    undoes the _data_ that the commit changed, but it does absolutely
    nothing to the effects on _history_ that the merge had.

    So the merge will still exist, and it will still be seen as joining
    the two branches together, and future merges will see that merge as
    the last shared state - and the revert that reverted the merge brought
    in will not affect that at all.

    So a "revert" undoes the data changes, but it's very much _not_ an
    "undo" in the sense that it doesn't undo the effects of a commit on
    the repository history.

    So if you think of "revert" as "undo", then you're going to always
    miss this part of reverts. Yes, it undoes the data, but no, it doesn't
    undo history.

Ilyen helyzetben először vissza akarnád vonni az előző visszavonást, ami így
alakítaná az előzményt:

 ---o---o---o---M---x---x---W---x---Y
               /
       ---A---B-------------------C---D

ahol az Y a W visszavonása.  Egy ilyen "visszavonás visszavonása" a
következővel végezhető el:

    $ git revert W

Ez az előzmény (figyelmen kívül hagyva a lehetséges konfliktusokat aközött,
amit a W és a W..Y megváltoztatott) egyenértékű lenne azzal, mintha a W vagy az
Y egyáltalán nem lenne az előzményben:

 ---o---o---o---M---x---x-------x----
               /
       ---A---B-------------------C---D

és az oldalági branch újbóli merge-elésénél nem lesz olyan konfliktus, amely
egy korábbi visszavonásból és a visszavonás visszavonásából ered.

 ---o---o---o---M---x---x-------x-------*
               /                       /
       ---A---B-------------------C---D

Persze a C-ben és a D-ben végzett változtatások továbbra is ütközhetnek
azzal, amit bármelyik x csinált, de ez csak egy normál merge-konfliktus.

Másrészt, ha az oldalági branch fejlesztői eldobták a hibás A-t és B-t, és a
visszavonás után újra elvégezték a változtatásokat a frissített mainline
tetején, az előzmény így nézett volna ki:

 ---o---o---o---M---x---x---W---x---x
               /                 \
       ---A---B                   A'--B'--C'

Ha ilyen esetben visszavonnád a visszavonást, mint az előző példában:

 ---o---o---o---M---x---x---W---x---x---Y---*
               /                 \         /
       ---A---B                   A'--B'--C'

ahol az Y a W visszavonása, az A' és a B' az újragöngyölt A és B, és lehet,
hogy van még egy további C' javítás is az oldalági branchen.  A `"diff Y^..Y"`
hasonló a `"diff -R W^..W"`-hez (ami viszont azt jelenti, hogy hasonló a
`"diff M^..M"`-hez), az `"diff A'^..C'"` pedig definíció szerint ehhez hasonló
lenne, de attól eltérő, mert ez a korábbi változtatás újragöngyölt sorozata.
Sok egymást átfedő változtatás lesz, amelyek konfliktusokhoz vezetnek.  Ezért
ne végezz "visszavonás-visszavonást" vakon, gondolkodás nélkül..

 ---o---o---o---M---x---x---W---x---x
               /                 \
       ---A---B                   A'--B'--C'

A rebase-elt oldalági branchet tartalmazó előzményben a W (és az M) a
frissített branch merge-alapja és a mainline csúcsa mögött van, és
merge-elődniük kellene anélkül, hogy a múltbeli hibás merge és annak
visszavonása útban lenne.

Összefoglalva: ez két nagyon különböző forgatókönyv, és két nagyon különböző
feloldási stratégiát igényelnek:

 - Ha a hibás oldalági branchet a tetejére adott javításokkal javították ki,
   akkor az előző visszavonás visszavonása lenne a helyes teendő.

 - Ha a hibás oldalági branchet, amelynek hatásait egy korábbi
   merge-visszavonás eldobta, a nulláról építették újra (azaz rebase-elés és
   javítás, ahogy te értelmezni látszol), akkor az eredmény újbóli
   merge-elése bármi más trükközés nélkül lenne a helyes teendő.
   (Lásd az alábbi ADDENDUM-ot arról, hogyan építs újra egy branchet a
   nulláról az eredeti leágazási pontjának megváltoztatása nélkül.)

Van azonban néhány dolog, amit szem előtt kell tartani egy merge
visszavonásakor (és egy ilyen visszavonás visszavonásakor).

Például gondolj arra, mit tesz egy merge visszavonása (majd a visszavonás
visszavonása) a bisectelhetőséggel. Hagyd figyelmen kívül azt a tényt, hogy a
visszavonás visszavonása visszacsinálja azt - csak gondolj rá úgy, mint "egy
commitra, amely sok mindent csinál". Mert pontosan ezt teszi.

Amikor van egy problémád, amelyet üldözöl, és belefutsz egy "vond vissza ezt
a merge-t"-be, akkor lényegében egy olyan commitba futsz bele, amely az összes
merge-elt commit összes változtatását tartalmazza (de nyilván fordítva). Így
ez hibakeresési pokol, mert most nincs sok apró változtatásod, amellyel
megpróbálhatnád pontosan behatárolni, melyik _részük_ változtat valamin.

De működik egyáltalán? Persze, hogy működik. Visszavonhatsz egy merge-t, és
tisztán technikai szemszögből a Git nagyon természetesen csinálta, és nem volt
vele igazi gond. Egyszerűen egy változtatásnak tekintette a "merge előtti
állapotból" a "merge utáni állapotba", és ennyi. Semmi bonyolult, semmi
furcsa, semmi igazán veszélyes. A Git gondolkodás nélkül elvégzi.

Tehát technikai szemszögből nincs semmi baj egy merge visszavonásával, de
munkafolyamat-szemszögből ez olyasmi, amit általában érdemes kerülni.

Ha egyáltalán lehetséges, például ha találsz egy problémát, amely bekerült a
fő fába, ahelyett hogy visszavonnád a merge-t, próbáld _nagyon_ erősen
lebisectelni a problémát a merge-elt branchbe, és egyszerűen javítsd ki, vagy
próbáld meg visszavonni azt az egyedi commitot, amely okozta.

Igen, bonyolultabb, és nem, nem mindig fog működni (néha a válasz az: "hoppá,
tényleg nem lett volna szabad merge-elnem, mert még nem volt kész, és tényleg
vissza kell csinálnom az _egész_ merge-t"). Szóval akkor tényleg vissza
kellene vonnod a merge-t, de amikor újra el akarod végezni a merge-t, azt most
a visszavonás visszavonásával kell megtenned.

ADDENDUM

Néha át kell írnod egy topic branch valamelyik commitját, *és* nem tudod
megváltoztatni a topic leágazási pontját.  Vedd fontolóra a következő
helyzetet:

 P---o---o---M---x---x---W---x
  \         /
   A---B---C

ahol a W commit visszavonta az M commitot, mert kiderült, hogy a B commit
hibás volt, és át kell írni, de arra van szükséged, hogy az átírt topic
továbbra is a P commitból ágazzon le (talán a P egy másik branch leágazási
pontja is, és mindkét branchbe merge-elni akarod tudni a topicot).

Ebben az esetben a természetes teendő az, hogy checkoutolod az A-B-C branchet,
és a "rebase -i P"-vel megváltoztatod a B commitot.  Ez azonban nem írja át az
A commitot, mert a "rebase -i" alapból fast-forwardol a "pick" paranccsal
kiválasztott bármely kezdeti commiton.  Így ez lesz a végeredmény:

 P---o---o---M---x---x---W---x
  \         /
   A---B---C   <-- old branch
    \
     B'---C'   <-- naively rewritten branch

Ahhoz, hogy az A-B'-C'-t a mainline branchbe merge-eld, továbbra is először
vissza kellene vonnod a W commitot, hogy felvedd az A-ban lévő változtatásokat,
de akkor valószínű, hogy a B'-ben lévő változtatások ütközni fognak a W
visszavonása által újra bevezetett eredeti B változtatásokkal.

Ezeket a problémákat azonban elkerülheted, ha újra létrehozod az egész
branchet, beleértve az A commitot is:

   A'---B'---C'  <-- completely rewritten branch
  /
 P---o---o---M---x---x---W---x
  \         /
   A---B---C

Az A'-B'-C'-t merge-elheted a mainline branchbe anélkül, hogy aggódnod
kellene a W előzetes visszavonása miatt.  A mainline előzménye így nézne ki:

   A'---B'---C'------------------
  /                              \
 P---o---o---M---x---x---W---x---M2
  \         /
   A---B---C

De ha valójában nem kell megváltoztatnod az A commitot, akkor kell valamilyen
mód, hogy újra létrehozd új commitként, ugyanazokkal a változtatásokkal benne.
A rebase parancs --no-ff opciója erre ad módot:

    $ git rebase [-i] --no-ff P

A --no-ff opció egy új A'-B'-C' branchet hoz létre teljesen új commitokkal
(az összes SHA ID más lesz), még akkor is, ha az interaktív esetben valójában
csak a B commitot módosítod.  Ezután ezt az új branchet közvetlenül a mainline
branchbe merge-elheted, és biztos lehetsz benne, hogy megkapod a branch összes
változtatását.

A --no-ff-et olyan esetekben is használhatod, amikor csak extra commitokat
adsz a topichoz, hogy kijavítsd.  Térjünk vissza a howto elején tárgyalt
helyzethez:

 P---o---o---M---x---x---W---x
  \         /
   A---B---C----------------D---E   <-- fixed-up topic branch

Ezen a ponton a --no-ff-fel újra létrehozhatod a topic branchet:

    $ git checkout E
    $ git rebase --no-ff P

ami ezt adja

   A'---B'---C'------------D'---E'  <-- recreated topic branch
  /
 P---o---o---M---x---x---W---x
  \         /
   A---B---C----------------D---E

Az újra létrehozott branchet a W commit visszavonása nélkül merge-elheted a
mainline-ba, és a mainline előzménye így fog kinézni:

   A'---B'---C'------------D'---E'
  /                              \
 P---o---o---M---x---x---W---x---M2
  \         /
   A---B---C
