From: Junio C Hamano <gitster@pobox.com>
Subject: Separating topic branches
Abstract: Ebben a cikkben JC leírja, hogyan választhatók szét a topic branchek.
Content-type: text/asciidoc

Hogyan válaszd szét a topic brancheket
======================================

Ez a szöveg eredetileg lábjegyzet volt egy vitához, amely a git diff parancsok
viselkedéséről szólt.

Gyakran kapom magam azon, hogy ezt csinálom [a diffet nem a HEAD-hez
futtatom], miközben kusza fejlesztési előzményeket írok át.  Például
elkezdek dolgozni valamin anélkül, hogy pontosan tudnám, hová vezet, és a
végén egy ilyen előzménnyel maradok:

            "master"
        o---o
             \                    "topic"
              o---o---o---o---o---o

Ezen a ponton a "topic" tartalmaz valamit, amiről tudom, hogy kell, de két
olyan koncepciót is tartalmaz, amelyek teljesen függetlennek bizonyultak.
És gyakran az egyik topic-komponens nagyobb, mint a másik.  Kettőnél több
topicot is tartalmazhat.

Hogy ezt a zűrzavart kezelhetőbbre írjam át, először egy "diff master..topic"-ot
csinálnék, hogy a változtatásokat egyetlen patchbe emeljem ki, aztán elkezdek
darabokat kiszedni belőle, hogy logikailag önálló egységeket kapjak, és
elkezdek építkezni a "master" tetejére:

        $ git diff master..topic >P.diff
        $ git checkout -b topicA master
        ... pick and apply pieces from P.diff to build
        ... commits on topicA branch.

              o---o---o
             /        "topicA"
        o---o"master"
             \                    "topic"
              o---o---o---o---o---o

Mielőtt a "topicA" HEAD-en minden egyes commitot elvégeznék, lefuttatom a
"diff HEAD"-et az érintett útvonalak update-index-elése előtt, vagy a
"diff --cached HEAD"-et utána.  Lefuttatnám a "diff --cached master"-t is, hogy
megbizonyosodjak róla, hogy a változtatások csak a "topicA"-hoz kapcsolódók.
Általában előbb a kisebb topicokra csinálom ezt.

Ezután megcsinálnám az eredeti "topic" maradékát, de ahhoz nem a kezdetben
használt, a "master" és a "topic" összehasonlításával kiemelt patchfájlból
indulok ki.  Még mindig a "topicA"-n állva kiemelem a "diff topic"-ot, és
azzal építem újra a másik topicot:

        $ git diff -R topic >P.diff ;# --cached also would work fine
        $ git checkout -b topicB master
        ... pick and apply pieces from P.diff to build
        ... commits on topicB branch.

                                "topicB"
               o---o---o---o---o
              /
             /o---o---o
            |/        "topicA"
        o---o"master"
             \                    "topic"
              o---o---o---o---o---o

Miután végeztem, kipróbálnék egy színlelt merge-t a "topicA" és a "topicB"
között, hogy megbizonyosodjak róla, hogy semmit sem hagytam ki:

        $ git pull . topicA ;# merge it into current "topicB"
        $ git diff topic
                                "topicB"
               o---o---o---o---o---* (pretend merge)
              /                   /
             /o---o---o----------'
            |/        "topicA"
        o---o"master"
             \                    "topic"
              o---o---o---o---o---o

Az utolsó diff jobb, ha nem mutat mást, csak a limlom eltakarítását.  Aztán
végre rendet rakhatok:

        $ git branch -D topic
        $ git reset --hard HEAD^ ;# nuke pretend merge

                                "topicB"
               o---o---o---o---o
              /
             /o---o---o
            |/        "topicA"
        o---o"master"
