From: Rutger Nijlunsing <rutger@nospam.com>
Subject: Setting up a Git repository which can be pushed into and pulled from over HTTP(S).
Date: Thu, 10 Aug 2006 22:00:26 +0200
Content-type: text/asciidoc

Hogyan állíts fel Git szervert http-n keresztül
===============================================

NOTE: Ez a dokumentum 2006-ból származik.  Azóta sok minden történt, és ez a
dokumentum most főként akkor releváns, ha a webhosztod nem CGI-képes.
Szinte mindenki másnak a linkgit:git-http-backend[1]-et kellene inkább néznie.

Mivel az Apache egyike azoknak a csomagoknak, amelyeket az emberek szeretnek
maguk lefordítani, míg mások a bürokraták álmát, a Debiant részesítik előnyben,
lehetetlen mindenkinek működő útmutatót adni. Csak küldj némi visszajelzést a
git@vger.kernel.org levelezőlistára, hogy ez a dokumentum a kedvenc distród
szerint alakuljon.


Mi kell hozzá:

- Legyen egy Apache webszervered

  On Debian:
    $ apt-get install apache2
    To get apache2 by default started,
    edit /etc/default/apache2 and set NO_START=0

- tudd szerkeszteni a konfigurációját.

  This could be found under /etc/httpd, or refer to your Apache documentation.

  On Debian: this means being able to edit files under /etc/apache2

- tudd újraindítani.

  'apachectl --graceful' might do. If it doesn't, just stop and
  restart apache. Be warning that active connections to your server
  might be aborted by this.

  On Debian:
    $ /etc/init.d/apache2 restart
  or
    $ /etc/init.d/apache2 force-reload
    (which seems to do the same)
  This adds symlinks from the /etc/apache2/mods-enabled to
  /etc/apache2/mods-available.

- legyen jogosultságod egy könyvtár chownolására

- legyen Git telepítve a kliensen, és

- vagy legyen Git telepítve a szerveren, vagy legyen egy webdav kliens a
  kliensen.

Ez gyakorlatilag azt jelenti, hogy root leszel, vagy hogy egy előre
konfigurált WebDAV szervert használsz.


1. lépés: bare Git repository felállítása
-----------------------------------------

E sorok írásakor a git-http-push nem tud távolról Git repository-t létrehozni.
Ezért ezt a szerveroldalon kell megtennünk a Gittel. Egy másik lehetőség, hogy
a kliensen generálunk egy üres bare repository-t, és egy WebDAV klienssel
átmásoljuk a szerverre (ami az egyetlen lehetőség, ha a szerveren nincs Git
telepítve).

Hozd létre a könyvtárat az Apache által kiszolgált könyvtárak DocumentRootja
alatt. Példaként a /usr/local/apache2-t vesszük, de próbáld ki a "grep
DocumentRoot /where/ever/httpd.conf"-ot a gyökered megtalálásához:

    $ cd /usr/local/apache/htdocs
    $ mkdir my-new-repo.git

  On Debian:

    $ cd /var/www
    $ mkdir my-new-repo.git


Inicializálj egy bare repository-t

    $ cd my-new-repo.git
    $ git --bare init


Változtasd meg a tulajdonjogot a webszervered hitelesítő adataira. A `"grep ^User
httpd.conf"` és a `"grep ^Group httpd.conf"` paranccsal derítheted ki:

    $ chown -R www.www .

  On Debian:

    $ chown -R www-data.www-data .


Ha nem tudod, melyik felhasználóként fut az Apache, alternatívaként
kiadhatsz egy "chmod -R a+w ."-t, megnézheted a később létrejövő fájlokat, és
megfelelően beállíthatod a jogosultságokat.

Indítsd újra az apache2-t, és ellenőrizd, hogy a http://server/my-new-repo.git
ad-e könyvtárlistázást. Ha nem, ellenőrizd, hogy az apache sikeresen
elindult-e.


2. lépés: a DAV engedélyezése ezen a repository-n
-------------------------------------------------

Először bizonyosodj meg róla, hogy a dav_module be van töltve. Ehhez illeszd be a httpd.conf-ba:

    LoadModule dav_module libexec/httpd/libdav.so
    AddModule mod_dav.c

Bizonyosodj meg arról is, hogy létezik ez a sor, amely a DAV-műveletek
zárolásához használt fájl:

  DAVLockDB "/usr/local/apache2/temp/DAV.lock"

  On Debian these steps can be performed with:

    Enable the dav and dav_fs modules of apache:
    $ a2enmod dav_fs
    (just to be sure. dav_fs might be unneeded, I don't know)
    $ a2enmod dav
    The DAV lock is located in /etc/apache2/mods-available/dav_fs.conf:
      DAVLockDB /var/lock/apache2/DAVLock

Persze mutathat máshová is, de a karakterlánc egyes Apache-konfigurációkban
valójában csak egy előtag, ezért a _könyvtárnak_ írhatónak kell lennie az
Apache futtató felhasználója számára.

Ezután adj valami ilyesmit a httpd.conf-odhoz

  <Location /my-new-repo.git>
     DAV on
     AuthType Basic
     AuthName "Git"
     AuthUserFile /usr/local/apache2/conf/passwd.git
     Require valid-user
  </Location>

  On Debian:
    Create (or add to) /etc/apache2/conf.d/git.conf :

    <Location /my-new-repo.git>
       DAV on
       AuthType Basic
       AuthName "Git"
       AuthUserFile /etc/apache2/passwd.git
       Require valid-user
    </Location>

    Debian automatically reads all files under /etc/apache2/conf.d.

A jelszófájl lehet máshol is, de az Apache-nak olvashatónak kell lennie, és
lehetőleg ne legyen mindenki számára olvasható.

Hozd létre ezt a fájlt ezzel
    $ htpasswd -c /usr/local/apache2/conf/passwd.git <user>

    On Debian:
      $ htpasswd -c /etc/apache2/passwd.git <user>

A rendszer jelszót fog kérni, és a fájl létrejön. A htpasswd további
hívásaiból hagyd ki a '-c' opciót, mivel a meglévő fájlhoz akarsz hozzáfűzni.

Újra kell indítanod az Apache-ot.

Most menj a http://<username>@<servername>/my-new-repo.git címre a
böngésződben, hogy ellenőrizd, kér-e jelszót, és elfogadja-e a helyes
jelszót.

Debianon:

   To test the WebDAV part, do:

   $ apt-get install litmus
   $ litmus http://<servername>/my-new-repo.git <username> <password>

   Most tests should pass.

Egy parancssori eszköz a WebDAV teszteléséhez a cadaver. Ha a grafikus
felületeket kedveled, például a konqueror meg tudja nyitni a WebDAV URL-eket
"webdav://..." vagy "webdavs://..." alakban.

Ha a Windowst szereted, az XP-től kezdve az Internet Explorer támogatja a
WebDAV-ot. Ehhez tedd a következőt: Internet Explorer -> Open Location ->
http://<servername>/my-new-repo.git [x] Open as webfolder -> login .


3. lépés: a kliens felállítása
------------------------------

Bizonyosodj meg róla, hogy van HTTP-támogatásod, azaz a Gitedet libcurllel
építették (7.10-nél újabb verzióval). A 'git http-push' parancsnak argumentum
nélkül egy használati üzenetet kell megjelenítenie.

Ezután add a következőt a $HOME/.netrc-edhez (megvagy nélküle is, de _rengetegszer_
kérni fogja a jelszavad beírását):

    machine <servername>
    login <username>
    password <password>

...és állítsd be a jogosultságokat:
     chmod 600 ~/.netrc

Ha a webszervert az IP-címén akarod elérni, azt kell beírnod a szervernév
helyett.

Annak ellenőrzésére, hogy minden rendben van-e, futtasd:

   curl --netrc --location -v http://<username>@<servername>/my-new-repo.git/HEAD

...ennek valami ilyesmit kell adnia: 'ref: refs/heads/master', ami a szerveren
lévő HEAD fájl tartalma.

Most add hozzá a remote-ot a meglévő repository-dban, amely az exportálni
kívánt projektet tartalmazza:

   $ git-config remote.upload.url \
       http://<username>@<servername>/my-new-repo.git/

Fontos kitenni az utolsó '/'-t; Nélküle a szerver egy átirányítást küld,
amelyet a git-http-push (még) nem ért, és a git-http-push a végtelenségig
ismételni fogja a kérést.


4. lépés: a kezdeti push végrehajtása
-------------------------------------

A kliens repository-dból futtasd

   $ git push upload master

Ez a 'master' branchet (amelyről feltételezzük, hogy az exportálni kívánt
branch) az 'upload' nevű repository-ba push-olja, amelyet korábban a
git-config-gal definiáltunk.


Proxy használata:
-----------------

Ha a WebDAV szervert egy HTTP(S) proxy mögül kell elérned, állítsd az
'all_proxy' változót erre: `http://proxy-host.com:port`, vagy
`http://login-on-proxy:passwd-on-proxy@proxy-host.com:port`. A részletekért
lásd a 'man curl'-t.


Hibaelhárítás:
--------------

Ha a git-http-push ezt írja

   Error: no DAV locking support on remote repo http://...

akkor az azt jelenti, hogy a webszerver nem fogadta el a hitelesítésedet.
Bizonyosodj meg róla, hogy a felhasználónév és a jelszó egyezik a
httpd.conf-ban, a .netrc-ben és abban az URL-ben, amelyre feltöltesz.

Ha a git-http-push egy (22/502) hibát mutat, amikor egy blobot próbál
MOVE-olni, az azt jelenti, hogy a webszervered valamiért nem ismeri fel a saját
nevét a kérésben; Ez akkor fordulhat elő, ha elindítod az Apache-ot, de aztán
letiltod a hálózati interfészt. Az Apache egyszerű újraindítása segít.

A (22/502)-höz hasonló hibák formátuma (curl hibakód/http hibakód). Tehát a
(22/404) valami olyasmit jelent, hogy 'not found' a szerveren.

A /usr/local/apache2/logs/error_log olvasása gyakran segít.

  On Debian: Read /var/log/apache2/error.log instead.

Ha HTTPS helyeket érsz el, a Git elbukhat az SSL-tanúsítvány ellenőrzésén (ez
a 60-as visszatérési kód). A http.sslVerify=false beállítása segíthet a
probléma diagnosztizálásában, de eltávolítja a biztonsági ellenőrzéseket.


Debian-hivatkozások: http://www.debian-administration.org/articles/285

Szerzők
  Johannes Schindelin <Johannes.Schindelin@gmx.de>
  Rutger Nijlunsing <git@wingding.demon.nl>
  Matthieu Moy <Matthieu.Moy@imag.fr>
