Content-type: text/asciidoc

Hogyan használd a git-daemont
=============================

A Git futtatható inetd módban és önálló (stand alone) módban is. De neked
csak annyi kell, hogy egy munkatársad pull-olhasson tőled, ezért gyorsan fel
kell állítanod egy Git-szervert, igaz?

Ne feledd, hogy a git-daemon jelenleg nem túl bőbeszédű, különösen akkor,
ha valami nem a terv szerint alakul (pl. egy socketet nem sikerült bekötni).

Még egy figyelmeztetés: ha ezt futtatod

	$ git ls-remote git://127.0.0.1/rule-the-world.git

és egy ilyen üzenetet látsz

	fatal: The remote end hung up unexpectedly

az csak annyit jelent, hogy _valami_ elromlott. Hogy megtudd, _mi_ romlott el,
a szervert kell megkérdezned. (A Git kizárólag a te biztonságod érdekében
tagadja meg a pontosabb tájékoztatást. Vedd le a cipődet. Van aprópénz a
zsebedben? Sajnálom, az nem megengedett -- ki tudja, mit terveztél vele?)

E két figyelmeztetés után lássunk egy példát:

	$ git daemon --reuseaddr --verbose --base-path=/home/gitte/git \
	  --export-all -- /home/gitte/git/rule-the-world.git

(Persze hacsak nem `gitte` a felhasználóneved _és_ a repository-d nem a
~/rule-the-world.git alatt van, ki kell igazítanod az útvonalakat. Ha a
repository-d nem bare, ne feledd, hogy a .git könyvtár útvonalát kell begépelned!)

Ez a hívás megpróbálja újrahasználni a címet, ha az már foglalt (ez
megspórolhat némi hibakeresést, mert különben a git-daemon leállítása és
újraindítása némán, hibajelzés nélkül is elbukhat egy socket bekötésekor).

Emellett (viszonylag) bőbeszédű, amikor valaki ténylegesen csatlakozik hozzá.
Beállítja továbbá az alap útvonalat, ami azt jelenti, hogy minden projektnek,
amely ezen a daemonon keresztül elérhető, ezen az útvonalon vagy alatta kell lennie.

A `--export-all` opció csak annyit jelent, hogy _nem_ kell létrehoznod egy
`git-daemon-export-ok` nevű fájlt minden exportált repository-ban. (Különben a
git-daemon hangosan panaszkodna, és megtagadná az együttműködést.)

Végül meg van adva az exportálandó repository. Jó gyakorlat az útvonalakat egy
"--" elválasztó után írni.

Most teszteld a daemonodat ezzel

	$ git ls-remote git://127.0.0.1/rule-the-world.git

Ha ez nem működik, derítsd ki, miért, és küldj be egy patchet ehhez a dokumentumhoz.
