From: Junio C Hamano <gitster@pobox.com>
Date: Tue, 17 Jan 2011 13:00:00 -0800
Subject: Using signed tag in pull requests
Abstract: A v1.7.9-től kezdve egy contributor push-olhat egy aláírt taget a
 publikáló repository-jába, és megkérheti az integrátorát, hogy pull-olja. Ez
 biztosítja az integrátort arról, hogy a pull-olt előzmény hiteles, és lehetővé
 teszi, hogy mások később validálják.
Content-type: text/asciidoc

Hogyan használj aláírt taget pull requestekben
==============================================

Egy tipikus, Gitet használó elosztott munkafolyamat az, hogy egy contributor
forkol egy projektet, épít rá, publikálja az eredményt a saját nyilvános
repository-jába, és megkéri az "upstream" személyt (gyakran annak a projektnek
a tulajdonosát, amelyből forkolt), hogy pull-oljon a nyilvános
repository-jából. Az ilyen "pull" kérését a `git request-pull` parancs teszi
egyszerűvé.

Korábban egy tipikus pull request így kezdődhetett:

------------
 The following changes since commit 406da78032179...:

   Froboz 3.2 (2011-09-30 14:20:57 -0700)

 are available in the Git repository at:

   example.com:/git/froboz.git for-xyzzy
------------

amit a változtatások shortlogja és egy diffstat követ.

A kérés egy branchnévre (pl. `for-xyzzy`) vonatkozott a contributor nyilvános
repository-jában, és bár megmondta, honnan forkolta a contributor a munkáját,
az üzenet nem mondott semmit arról, milyen commitot várjunk a for-xyzzy branch
csúcsán. Ha a contributor nyilvános repository-ját hosztoló oldalban nem lehet
teljesen megbízni, szükségtelenül nehéz volt megbizonyosodni arról, hogy amit
az integrátor pull-olt, valóban az, amit a contributor a projektnek
előállított. Ráadásul nem volt egyszerű módja annak, hogy külső auditorok
később ellenőrizzék az eredményül kapott előzményt.

A Git v1.7.9 kiadástól kezdve egy contributor aláírt taget adhat az előzmény
csúcsán lévő commithoz, és megkérheti az integrátort, hogy azt az aláírt taget
pull-olja. Amikor az integrátor lefuttatja a `git pull`-t, az aláírt tag
automatikusan ellenőrzésre kerül, hogy biztos legyen, az előzményt nem
babrálták meg. Ráadásul az eredményül kapott merge commit rögzíti az aláírt
tag tartalmát, így mások ellenőrizhetik, hogy az integrátor által merge-elt
branchet a contributor írta alá, anélkül hogy külön letöltenék a pull request
validálásához használt aláírt taget, és a refs névtérben tartanák.

Ez a dokumentum a contributor és az integrátor közötti munkafolyamatot írja
le, Git v1.7.9 vagy újabb használatával.


Egy contributor vagy egy lieutenant
-----------------------------------

Miután előkészítette a munkáját pull-olásra, a contributor a `git tag -s`-t
használja egy aláírt tag létrehozásához:

------------
 $ git checkout work
 $ ... "git pull" from sublieutenants, "git commit" your own work ...
 $ git tag -s -m "Completed frotz feature" frotz-for-xyzzy work
------------

Vedd észre, hogy ez a példa a `-m` opciót használja egy aláírt tag
létrehozásához, mindössze egysoros üzenettel, de ez csak szemléltetés céljából
van így. Ajánlott jól megírt magyarázatot fogalmazni arról, mit csinál a
topic, hogy indokold, miért éri meg az integrátornak pull-olnia, mivel ez az
üzenet végül a végleges előzmény része lesz, miután az integrátor válaszol a
pull requestre (ahogy később látni fogjuk).

Ezután push-olja a taget a nyilvános repository-jába:

------------
 $ git push example.com:/git/froboz.git/ +frotz-for-xyzzy
------------

Nincs szükség a `work` branch vagy bármi más push-olására.

Vedd észre, hogy a fenti parancssor egy plusz jelet használt a
`+frotz-for-xyzzy` elején, hogy engedélyezze egy tag frissítésének
kikényszerítését, mivel ugyanaz a contributor újra akarhat használni egy
azonos nevű aláírt taget, miután az előző pull requestre már válaszoltak.

A contributor ezután összeállít egy üzenetet, hogy "pull"-t kérjen:

------------
 $ git request-pull v3.2 example.com:/git/froboz.git/ frotz-for-xyzzy >msg.txt
------------

Az argumentumok:

. az integrátor azon commitjának verziója, amelyre a contributor alapozta a munkáját;
. a repository URL-je, amelybe a contributor feltolta azt, amit pull-oltatni
  szeretne; és
. a tag neve, amelyet a contributor pull-oltatni szeretne (korábban ide csak
  branchnevet írhatott).

Az eredményül kapott msg.txt fájl így kezdődik:

------------
 The following changes since commit 406da78032179...:

   Froboz 3.2 (2011-09-30 14:20:57 -0700)

 are available in the Git repository at:

   example.com:/git/froboz.git tags/frotz-for-xyzzy

 for you to fetch changes up to 703f05ad5835c...:

   Add tests and documentation for frotz (2011-12-02 10:02:52 -0800)

 -----------------------------------------------
 Completed frotz feature
 -----------------------------------------------
------------

amit a változtatások shortlogja és egy diffstat követ.  Ha ezt összevetjük a
hagyományos `git request-pull` parancs kimenetének korábbi szemléltetésével,
az olvasónak észre kell vennie, hogy:

. a várt csúcscommit meg van jelenítve az integrátornak; és
. az aláírt tag üzenete jól láthatóan meg van jelenítve a szaggatott vonalak
  között, a shortlog előtt.

Az utóbbi az oka annak, amiért a contributor indokolni szeretné, miért éri meg
pull-olni a munkáját, amikor létrehozza az aláírt taget.  A contributor ezután
megnyitja a kedvenc MUA-ját, elolvassa a msg.txt-t, szerkeszti, és elküldi az
upstream integrátorának.


Integrátor
----------

Miután megkapott egy ilyen pull request üzenetet, az integrátor fetch-eli és
integrálja a kérésben megnevezett taget, ezzel:

------------
 $ git pull example.com:/git/froboz.git/ tags/frotz-for-xyzzy
------------

Ez a művelet mindig megnyit egy szerkesztőt, hogy az integrátor
finomhangolhassa a commit napló-üzenetét egy aláírt tag merge-elésekor.
Emellett egy aláírt tag pull-olása mindig létrehoz egy merge commitot, még
akkor is, ha az integrátornak nincs új commitja azóta, hogy a contributor
munkája leágazott (azaz 'fast forward'), hogy az integrátor rendesen
elmagyarázhassa, miről szól a merge, és miért készült.

A szerkesztőben az integrátor valami ilyesmit fog látni:

------------
 Merge tag 'frotz-for-xyzzy' of example.com:/git/froboz.git/

 Completed frotz feature
 # gpg: Signature made Fri 02 Dec 2011 10:03:01 AM PST using RSA key ID 96AFE6CB
 # gpg: Good signature from "Con Tributor <nitfol@example.com>"
------------

Vedd észre, hogy az aláírt tagben rögzített üzenet, a "Completed frotz
feature" itt megjelenik, és ez megint csak azért fontos, hogy a contributor
jól magyarázza el a munkáját az aláírt tag létrehozásakor.

Szokás szerint a `#`-tel kommentelt sorok eltávolításra kerülnek. Az
eredményül kapott commit egy rejtett mezőben rögzíti az ehhez a validáláshoz
használt aláírt taget, hogy később mások felhasználhassák az előzmény
auditálásához. Az integrátornak nincs szüksége arra, hogy külön másolatot
tartson a tagből a repository-jában (azaz a `git tag -l` nem sorolja fel a
`frotz-for-xyzzy` taget a fenti példában), és a taget a nyilvános
repository-jába sem kell publikálnia.

Miután az integrátor válaszol a pull requestre, és a munkája a végleges
előzmény része lesz, a contributor eltávolíthatja a taget a nyilvános
repository-jából, ha úgy dönt, hogy tisztán tartsa a nyilvános
repository-ja tag-névterét, ezzel:

------------
 $ git push example.com:/git/froboz.git :frotz-for-xyzzy
------------


Auditorok
---------

A `--show-signature` opció megadható a `git log`-nak vagy a `git show`-nak, és
megmutatja a beágyazott aláírt tag ellenőrzési állapotát azokban a merge
commitokban, amelyek akkor jöttek létre, amikor az integrátor válaszolt egy
aláírt tag pull requestjére.

A `git show --show-signature` tipikus kimenete így nézhet ki:

------------
 $ git show --show-signature
 commit 02306ef6a3498a39118aef9df7975bdb50091585
 merged tag 'frotz-for-xyzzy'
 gpg: Signature made Fri 06 Jan 2012 12:41:49 PM PST using RSA key ID 96AFE6CB
 gpg: Good signature from "Con Tributor <nitfol@example.com>"
 Merge: 406da78 703f05a
 Author: Inte Grator <xyzzy@example.com>
 Date:   Tue Jan 17 13:49:41 2012 -0800

     Merge tag 'frotz-for-xyzzy' of example.com:/git/froboz.git/

     Completed frotz feature

     * tag 'frotz-for-xyzzy' (100 commits)
       Add tests and documentation for frotz
       ...
------------

Az auditornak nem kell explicit módon letöltenie a contributor aláírását, sőt
azt sem kell tudnia, milyen taget/tageket használt a contributor és az
integrátor az aláírás közlésére.  Minden szükséges információ a merge commit
részeként van rögzítve.
