Date: Sat, 5 Jan 2008 20:17:40 -0500
From: Sean <seanlkml@sympatico.ca>
To: Miklos Vajna <vmiklos@frugalware.org>
Cc: git@vger.kernel.org
Subject: how to use git merge -s subtree?
Abstract: Ebben a cikkben Sean bemutatja, hogyan használható a subtree
 merge-stratégia.
Content-type: text/asciidoc
Message-ID: <BAYC1-PASMTP12374B54BA370A1E1C6E78AE4E0@CEZ.ICE>

Hogyan használd a subtree merge-stratégiát
==========================================

Vannak helyzetek, amikor egy önállóan fejlesztett projektből szeretnél
tartalmat beépíteni a saját projektedbe. Egyszerűen pull-olhatsz a másik
projektből, amíg nincsenek ütköző útvonalak.

A problémás eset az, amikor vannak ütköző fájlok. Lehetséges jelöltek a
Makefile-ok és más szokásos fájlnevek. Ezeket a fájlokat merge-elhetnéd, de
valószínűleg nem akarod.  Erre a problémára jobb megoldás lehet a projektet a
saját alkönyvtáraként merge-elni. Ezt a 'recursive' merge-stratégia nem
támogatja, így a puszta pull-olás nem működik.

Amire szükséged van, az a 'subtree' merge-stratégia, amely segít az ilyen
helyzetekben.

Ebben a példában tegyük fel, hogy a repository a `/path/to/B` alatt van (de
igény szerint lehet URL is). Ennek a repository-nak a 'master' branchét
szeretnéd a `dir-B` alkönyvtárba merge-elni az aktuális
branchedben.

Íme a parancssorozat, amire szükséged van:

----------------
$ git remote add -f Bproject /path/to/B <1>
$ git merge -s ours --no-commit --allow-unrelated-histories Bproject/master <2>
$ git read-tree --prefix=dir-B/ -u Bproject/master <3>
$ git commit -m "Merge B project as our subdirectory" <4>

$ git pull -s subtree Bproject master <5>
----------------
<1> nevezd el a másik projektet "Bproject"-nek, és fetch-elj.
<2> készülj fel arra, hogy egy későbbi lépés az eredményt merge-ként rögzítse.
<3> olvasd be a Bproject "master" branchét a "dir-B" alkönyvtárba.
<4> rögzítsd a merge eredményét.
<5> tartsd karban az eredményt a további merge-ekkel a "subtree" használatával

Az első négy parancs a kezdeti merge-hez való, míg az utolsó a 'B project'
frissítéseinek merge-eléséhez.

A 'subtree' merge összehasonlítása a submodule-okkal
----------------------------------------------------

- A subtree merge használatának előnye, hogy kevesebb adminisztratív terhet
  ró a repository-d felhasználóira. Régebbi (Git v1.5.2 előtti) kliensekkel is
  működik, és a kód rögtön a clone után a kezedben van.

- Ha viszont submodule-okat használsz, akkor dönthetsz úgy, hogy nem viszed át
  a submodule-objektumokat. Ez a subtree merge-nél problémát jelenthet.

- Továbbá, ha módosításokat végzel a másik projekten, egyszerűbb beküldeni a
  változtatásokat, ha submodule-okat használsz.

További tippek
--------------

- Ha a másik projekten módosítottál a saját repository-dban, előfordulhat, hogy
  a te projektedből akarnak merge-elni. Ez a subtree-vel lehetséges -- feljebb
  tudja tolni az útvonalakat a fádban, és így ők csak a fád releváns részeit
  merge-elhetik.

- Ne feledd, hogy ha a másik projekt tőled merge-el, akkor összekapcsolja a
  saját előzményeit a tiéddel, amit lehet, hogy nem szeretnének.
