Hibajelentés a gitben
=====================

A `BUG`, `bug`, `die`, `usage`, `error` és `warning` különféle hibákat
jelentenek.

- A `BUG` olyan sikertelen belső ellenőrzésekhez (assertion) való, amelyek
  soha nem fordulhatnának elő, azaz magának a gitnek a hibái.

- A `bug` (kisbetűs, nem `BUG`) a `BUG`-hoz hasonlóan használandó, de
  "BUG" üzenetet ír ki `abort()` hívása helyett.
+
A `bug()` hívása ezután a `BUG()` függvény "valódi" hívását eredményezi,
vagy explicit módon a `BUG_if_bug()` meghívásával a `bug()` hívása(i)
után, vagy implicit módon `exit()` idején, amikor ellenőrizzük, hogy
maradt-e elintézetlen `bug()` hívás.
+
Ha a `BUG_if_bug()` meghívása előtt nem volt korábbi `bug()` hívás,
akkor az utóbbi egy NOOP. A `BUG_if_bug()` függvény ugyanazokat az
argumentumokat veszi át, mint maga a `BUG()`. A `BUG_if_bug()` explicit
hívása nem szükséges, de biztosítja, hogy a lehető leghamarabb leálljunk.
+
Ha tudod, hogy voltak korábbi `bug()` hívások, akkor magának a `BUG()`-nak
a hívása egyenértékű a `BUG_if_bug()` hívásával; az utóbbi egy olyan
burkoló, amely meghívja a `BUG()`-ot, ha be van állítva egy jelző, amely
azt jelzi, hogy meghívtuk a `bug()`-ot.
+
Ez azon API-k kényelmét szolgálja, amelyek esetleg egynél több "bug"-ot
szeretnének jelenteni, mint például a parse-options.c-beli optbug()
ellenőrzés.

- A `die` végzetes alkalmazáshibákhoz való. Üzenetet ír ki a
  felhasználónak, és 128-as státusszal lép ki.

- A `usage` a parancssori használat hibáihoz való. Az üzenetének kiírása
  után 129-es státusszal lép ki. (Lásd még a `usage_with_options`-t a
  link:api-parse-options.html[parse-options API]-ban.)

- Az `error` nem végzetes könyvtárhibákhoz való. Üzenetet ír ki a
  felhasználónak, és -1-et ad vissza, hogy kényelmesen jelezze a hibát
  a hívónak.

- A `warning` olyan helyzetek jelentésére való, amelyek valószínűleg nem
  fordulhatnának elő, de amelyeket a felhasználó (és a Git) túl sok
  probléma nélkül meg tud kerülni a munka folytatásához. Az `error`-hoz
  hasonlóan -1-et ad vissza, miután jelentette a helyzetet a hívónak.

Ezeket a jelentéseket a trace2 szolgáltatás naplózza. Lásd az "error"
eseményt a link:api-trace2.html[trace2 API]-ban.

[[_customizable_error_handlers]]
Testreszabható hibakezelők
--------------------------

A `die` és az `error` alapértelmezett viselkedése, hogy üzenetet ír a
stderr-re, majd a helyzetnek megfelelően kilép vagy visszatér. Ez a
viselkedés felülírható a `set_die_routine` és a `set_error_routine`
segítségével. Például a "git daemon" a set_die_routine-t használja arra,
hogy kilépés előtt a syslog-ba írja a `die` hívásának okát.

[[_library_errors]]
Könyvtárhibák
-------------

A függvények hiba esetén negatív egész számot adnak vissza. Az ezen
túli részletek függvényről függvényre változnak:

- Egyes függvények minden hibára -1-et adnak vissza. Mások konkrétabb
  értéket adnak vissza attól függően, hogy a hívó hogyan szeretne
  reagálni a hibára.

- Egyes függvények az `error`-ral jelentik a hibát a stderr-re, míg
  mások ezt a hívóra hagyják.

- Az errno a legtöbb függvényből visszatérve nem értelmes (kivéve a
  rendszerhívások vékony burkolóit).

A biztonság kedvéért nézd meg a függvény API-dokumentációját.

[[_caller_handled_errors]]
A hívó által kezelt hibák
-------------------------

Egyre több függvény vesz át egy 'struct strbuf *err' paramétert. Hiba
esetén az ilyen függvények egy üzenetet fűznek az 'err' strbufhoz arról,
mi ment rosszul. Az üzenetnek elég teljesnek kell lennie, hogy
változatlanul átadható legyen a `die`-nak vagy az `error`-nak. Például:

	if (ref_transaction_commit(transaction, &err))
		die("%s", err.buf);

Az 'err' paraméter érintetlen marad, ha nem történt hiba, így több
függvényhívás láncba fűzhető:

	t = ref_transaction_begin(&err);
	if (!t ||
	    ref_transaction_update(t, "HEAD", ..., &err) ||
	    ret_transaction_commit(t, &err))
		die("%s", err.buf);

Az 'err' paraméternek érvényes strbufra mutató mutatónak kell lennie. Egy
üzenet elnémításához adj át egy explicit módon figyelmen kívül hagyott strbufot:

	if (thing_that_can_fail_in_an_ignorable_way(..., &err))
		/* This failure is okay. */
		strbuf_reset(&err);
