parse-options API
=================

A parse-options API az opciók Gitben való feldolgozására és átalakítására,
valamint konzisztens megjelenésű használati súgó nyújtására szolgál.

[[_basics]]
Alapok
------

Az `argv[]` argumentumvektor általában kötelező vagy opcionális
'nem-opció argumentumokat' (pl. egy fájlnevet vagy egy branchet),
'opciókat' és 'alparancsokat' tartalmazhat.
Az opciók olyan opcionális argumentumok, amelyek kötőjellel kezdődnek,
és lehetővé teszik egy parancs viselkedésének megváltoztatását.

* Alapvetően háromféle opció létezik:
  'logikai' opciók,
  (kötelező) 'argumentumot' váró opciók, és
  'opcionális argumentumot' váró opciók
  (azaz olyan logikai opció, amely finomítható).

* Alapvetően kétféle alakja van az opcióknak:
  A 'rövid opciók' egy kötőjelből (`-`) és egy alfanumerikus
  karakterből állnak.
  A 'hosszú opciók' két kötőjellel (`--`) és néhány alfanumerikus
  karakterrel kezdődnek.

* Az opciók megkülönböztetik a kis- és nagybetűket.
  Kérjük, csak 'kisbetűs hosszú opciókat' definiálj.

A parse-options API a következőket teszi lehetővé:

* Argumentumot váró opciók 'tapadó' és 'különálló alakja'.
  A `-oArg` tapadó, a `-o Arg` különálló alak.
  A `--option=Arg` tapadó, a `--option Arg` különálló alak.

* A hosszú opciók 'rövidíthetők', amennyiben a rövidítés
  egyértelmű.

* A rövid opciók összevonhatók, pl. a `-a -b` megadható `-ab` alakban.

* A logikai hosszú opciók 'negálhatók' (vagy 'kikapcsolhatók') a `no-`
  elé illesztésével, pl. `--no-abbrev` a `--abbrev` helyett. Fordítva,
  a `no-` kezdetű opciók a `no-` eltávolításával 'negálhatók'. Más
  hosszú opciók kikapcsolhatók (pl. a sztring NULL-ra, az egész szám
  0-ra állítása) a `no-` elé illesztésével.

* Az opciók és a nem-opció argumentumok egyértelműen elválaszthatók a `--`
  opcióval, pl. a `-a -b --option -- --this-is-a-file` azt jelzi, hogy
  a `--this-is-a-file` nem dolgozható fel opcióként.

Az alparancsok több szempontból is különlegesek:

* Az alparancsoknak csak hosszú alakja van, nincs dupla kötőjeles előtagjuk,
  nincs negált alakjuk, és nincs leírásuk, nem vesznek át argumentumot, és
  nem rövidíthetők.

* Pontosan egy alparancsnak kell lennie az argumentumok között, vagy nullának,
  ha a parancsnak van alapértelmezett működési módja.

* Az alparancsot követő összes argumentum az alparancs argumentumának
  számít, és fordítva, az alparancsnak szánt argumentumok nem előzhetik
  meg az alparancsot.

Ezért ha az opciótömb legalább egy alparancsot tartalmaz, és a
`parse_options()` az első kötőjel nélküli argumentumhoz ér, akkor vagy:

* megáll és visszatér, ha az a kötőjel nélküli argumentum ismert alparancs,
  a `value`-t az adott alparancshoz társított függvénymutatóra állítja,
  az alparancs nevét az argv[0]-ban tárolja, a többi argumentumot pedig
  feldolgozatlanul hagyja, vagy

* megáll és visszatér, ha a `PARSE_OPT_SUBCOMMAND_OPTIONAL` jelzővel hívták
  meg, és az a kötőjel nélküli argumentum egyetlen alparancsra sem illeszkedik,
  a `value`-t változatlanul, a többi argumentumot pedig feldolgozatlanul
  hagyja, vagy

* hibát és használatot jelenít meg, és megszakítja a végrehajtást.

[[_steps_to_parse_options]]
Az opciók feldolgozásának lépései
---------------------------------

. `#include "parse-options.h"`

. definiálj egy NULL-lal lezárt
  `static const char * const builtin_foo_usage[]` tömböt,
  amely alternatív használati sztringeket tartalmaz

. definiáld a `builtin_foo_options` tömböt az alábbi
  'Adatszerkezet' szakaszban leírtak szerint.

. a `cmd_foo(int argc, const char **argv, const char *prefix)`-ban
  hívd meg

	argc = parse_options(argc, argv, prefix, builtin_foo_options, builtin_foo_usage, flags);
+
A `parse_options()` kiszűri az `argv[]` feldolgozott opcióit, és a nem-opció
argumentumokat az `argv[]`-ben hagyja.
Az `argc` az értékadás miatt megfelelően frissül.
+
A parse_options() ötödik paramétereként NULL-t is átadhatsz használati tömb
helyett, hogy elkerüld a használati információt és opciólistát megjelenítő
súgóképernyőt. Ezt csak szükség esetén szabad, pl. egy korlátozott
feldolgozó megvalósításához, amely csak az opciók egy részhalmazához való,
és a teljes feldolgozó előtt kell futnia, amely viszont a teljes súgóüzenetet mutatja.
+
A jelzők a következők bitenkénti VAGY-a:

`PARSE_OPT_KEEP_DASHDASH`::
	Megtartja a `--`-t, amely általában elválasztja az opciókat a
	nem-opció argumentumoktól.

`PARSE_OPT_STOP_AT_NON_OPTION`::
	Általában az egész argumentumvektor átalakításra és átrendezésre kerül.
	Ezzel a jelzővel a feldolgozás az első nem-opció argumentumnál
	leáll.

`PARSE_OPT_KEEP_ARGV0`::
	Megtartja az első argumentumot, amely a program nevét tartalmazza.
	Alapértelmezés szerint eltávolításra kerül az argv[]-ből.

`PARSE_OPT_KEEP_UNKNOWN_OPT`::
	Megtartja az ismeretlen opciókat ahelyett, hogy hibával leállna. Ez
	nem működik az argumentumok minden kombinációjára úgy, ahogy a
	felhasználók várnák. Pl. ha a `--unknown --known` első argumentuma
	értéket vár (amit nem tudhatunk), a másodikat tévesen ismert
	opcióként értelmezi. Hasonlóképpen, ha a
	`PARSE_OPT_STOP_AT_NON_OPTION` be van állítva, a `--unknown value`
	második argumentumát tévesen nem-opcióként értelmezi, nem pedig az
	ismeretlen opcióhoz tartozó értékként. Ezért a parse_options()
	hibával leáll, ha mindkét opció be van állítva.
	Vedd figyelembe, hogy a nem-opció argumentumok mindig megmaradnak,
	e jelző nélkül is.

`PARSE_OPT_NO_INTERNAL_HELP`::
	Alapértelmezés szerint a parse_options() a `-h`, `--help` és
	`--help-all` opciókat belsőleg kezeli, egy súgóképernyő
	megjelenítésével. Ez az opció kikapcsolja ezt, és lehetővé teszi
	egyéni kezelők hozzáadását ezekhez az opciókhoz, vagy egyszerűen
	ismeretlenként hagyásukat.

`PARSE_OPT_SUBCOMMAND_OPTIONAL`::
	Ne álljon le hibával, ha nincs alparancs megadva.

Vedd figyelembe, hogy a `PARSE_OPT_STOP_AT_NON_OPTION` nem kompatibilis az
alparancsokkal; míg a `PARSE_OPT_KEEP_DASHDASH` és a `PARSE_OPT_KEEP_UNKNOWN_OPT`
alparancsokkal csak akkor használható, ha a `PARSE_OPT_SUBCOMMAND_OPTIONAL`-lal
kombinálják.

[[_data_structure]]
Adatszerkezet
-------------

A fő adatszerkezet az `option` struct tömbje, mondjuk
`static struct option builtin_add_options[]`.

[[_option_flags]]
Opciójelzők
~~~~~~~~~~~

Minden opció hordozhat jelzőket az `option` structjának `flags` mezőjében.
Ezek opciónkénti jelzők, és különböznek a fent leírt `parse_options()`
jelzőktől; általában az `OPT_*_F()` makróváltozatokon keresztül (lásd
lentebb) állítják be őket, nem kézzel. A következők bitenkénti VAGY-a:

`PARSE_OPT_OPTARG`::
	Az opció argumentuma opcionális, azaz a `--option` és a
	`--option=<value>` is elfogadott.

`PARSE_OPT_NOARG`::
	Az opció egyáltalán nem vesz át argumentumot. A `--option=<value>`
	használata elutasításra kerül.

`PARSE_OPT_NONEG`::
	Letiltja az automatikusan generált negált `--no-option`
	alakot.

`PARSE_OPT_HIDDEN`::
	Elrejti az opciót: kimarad a `git <cmd> -h` által mutatott
	használatból, de a `git <cmd> --help-all` továbbra is mutatja.
	Az opció mindkét esetben a szokásos módon kerül feldolgozásra. Ez
	elavult, haladó vagy egyébként nem gyakori opciókhoz való.

`PARSE_OPT_LASTARG_DEFAULT`::
	Az argumentum nélküli alak csak akkor elfogadott, ha az opció az
	utolsó token a parancssorban; korábban használva továbbra is
	argumentumot igényel. Nem kombinálandó a
	`PARSE_OPT_OPTARG`-gal.

`PARSE_OPT_NODASH`::
	Az opció egyetlen karakter kezdő kötőjel nélkül, mint például a
	`+`, amelyet néhány parancs használ.

`PARSE_OPT_LITERAL_ARGHELP`::
	Az argumentum súgósztringjét (`argh`) szó szerint használja a
	használati kimenetben ahelyett, hogy `<>` vagy `[]` jelekkel venné
	körül. Hasznos, ha az `argh` már kézzel formázott leírást tartalmaz.

`PARSE_OPT_FROM_ALIAS`::
	Belső jelző, amely a konfigurált aliasból kibontott opciókon van
	beállítva. A hívók ne állítsák be.

`PARSE_OPT_NOCOMPLETE`::
	Ne ajánlja fel ezt az opciót kiegészítéshez.

`PARSE_OPT_COMP_ARG`::
	Az opció argumentumát kell kiegészíteni, nem magát az opciót.

`PARSE_OPT_CMDMODE`::
	Az opció egyike több, egymást kölcsönösen kizáró "parancsmód"
	opciónak, amelyek ugyanazon a változón osztoznak. Egyszerre több
	használata elutasításra kerül.

[[_macros]]
Makrók
~~~~~~

Van néhány makró az opciók egyszerű definiálásához:

Az alábbi makrók közül soknak van `_F` változata (például `OPT_BOOL_F`,
`OPT_STRING_F`, `OPT_INTEGER_F`, `OPT_SET_INT_F`, `OPT_BIT_F` és
`OPT_CALLBACK_F`), amely egy további, záró `flags` argumentumot vesz át.
Ez az argumentum a fenti "Opciójelzők" szakaszban leírt opciónkénti
jelzők bitenkénti VAGY-a; a nem `_F` makrók egyszerűen `0`-ra állított
`flags`-szel vannak definiálva.

`OPT__ABBREV(&int_var)`::
	Hozzáadja a `--abbrev[=<n>]`-t.

`OPT__COLOR(&int_var, description)`::
	Hozzáadja a `--color[=<when>]`-t és a `--no-color`-t.

`OPT__DRY_RUN(&int_var, description)`::
	Hozzáadja a `-n, --dry-run`-t.

`OPT__FORCE(&int_var, description)`::
	Hozzáadja a `-f, --force`-t.

`OPT__QUIET(&int_var, description)`::
	Hozzáadja a `-q, --quiet`-et.

`OPT__VERBOSE(&int_var, description)`::
	Hozzáadja a `-v, --verbose`-t.

`OPT_GROUP(description)`::
	Elkezd egy opciócsoportot. A `description` egy rövid sztring, amely
	leírja a csoportot, vagy egy üres sztring.
	A leírást nagybetűvel kezdd.

`OPT_HIDDEN_GROUP(description)`::
	Mint az `OPT_GROUP()`, de a csoport fejléce `PARSE_OPT_HIDDEN`-t
	hordoz, így csak a `--help-all` mutatja, a `-h` nem. Használd olyan
	csoport címkézésére, amely csak rejtett opciókat tartalmaz, és amely
	egyébként üres fejlécet mutatna a `-h` alatt.

`OPT_BOOL(short, long, &int_var, description)`::
	Bevezet egy logikai opciót. Az `int_var` egyre áll a `--option`
	hatására, és nullára a `--no-option` hatására.

`OPT_HIDDEN_BOOL(short, long, &int_var, description)`::
	Mint az `OPT_BOOL()`, de az opció `PARSE_OPT_HIDDEN`-t hordoz,
	így rejtve van a `-h` elől, miközben a `--help-all` továbbra is
	mutatja.

`OPT_COUNTUP(short, long, &int_var, description)`::
	Bevezet egy felfelé számláló opciót.
	A `--option` minden használata növeli az `int_var`-t, nullától
	indulva (még ha kezdetben negatív is), a `--no-option` pedig
	nullára állítja vissza. Annak megállapításához, hogy egyáltalán
	előfordult-e `--option` vagy `--no-option`, inicializáld az
	`int_var`-t negatív értékre, és ha a parse_options() után még mindig
	negatív, akkor sem `--option`, sem `--no-option` nem szerepelt.

`OPT_BIT(short, long, &int_var, description, mask)`::
	Bevezet egy logikai opciót.
	Ha használják, az `int_var` bitenkénti VAGY-ba kerül a `mask`-kal.

`OPT_NEGBIT(short, long, &int_var, description, mask)`::
	Bevezet egy logikai opciót.
	Ha használják, az `int_var` bitenkénti ÉS-be kerül az invertált `mask`-kal.

`OPT_SET_INT(short, long, &int_var, description, integer)`::
	Bevezet egy egész szám opciót.
	Az `int_var` az `integer`-re áll a `--option` hatására, és
	nullára áll vissza a `--no-option` hatására.

`OPT_STRING(short, long, &str_var, arg_str, description)`::
	Bevezet egy sztring argumentumú opciót.
	A sztring argumentum a `str_var`-ba kerül.

`OPT_STRING_LIST(short, long, &struct string_list, arg_str, description)`::
	Bevezet egy sztring argumentumú opciót.
	A sztring argumentum a `string_list` egy elemeként tárolódik.
	A `--no-option` használata törli a megelőző értékek listáját.

`OPT_INTEGER(short, long, &int_var, description)`::
	Bevezet egy egész szám argumentumú opciót. Az argumentumnak egész
	számnak kell lennie, és tartalmazhat 'k', 'm' vagy 'g' utótagot, amely
	a megadott értéket 1024-gyel, 1024^2-nel, illetve 1024^3-nal skálázza.
	A skálázott érték az `int_var`-ba kerül.

`OPT_UNSIGNED(short, long, &unsigned_long_var, description)`::
	Bevezet egy előjel nélküli egész szám argumentumú opciót. Az argumentumnak
	nemnegatív egész számnak kell lennie, és tartalmazhat 'k', 'm' vagy 'g'
	utótagot, amely a megadott értéket 1024-gyel, 1024^2-nel, illetve 1024^3-nal
	skálázza. A skálázott érték az `unsigned_long_var`-ba kerül.

`OPT_EXPIRY_DATE(short, long, &timestamp_t_var, description)`::
	Bevezet egy lejárati dátum argumentumú opciót, lásd `parse_expiry_date()`.
	Az időbélyeg a `timestamp_t_var`-ba kerül.

`OPT_CALLBACK(short, long, &var, arg_str, description, func_ptr)`::
	Bevezet egy argumentumú opciót.
	Az argumentum a `func_ptr` által megadott függvénybe kerül,
	az eredmény pedig a `var`-ba.
	Részletesebb leírásért lásd az alábbi 'Opció-visszahívások' részt.

`OPT_FILENAME(short, long, &var, description)`::
	Bevezet egy fájlnév argumentumú opciót.
	A fájlnév előtaggal lesz ellátva úgy, hogy a fájlnevet a
	`parse_options()` prefix argumentumával együtt átadja a `prefix_filename()`-nek.

`OPT_NUMBER_CALLBACK(&var, description, func_ptr)`::
	Felismeri a -123-hoz hasonló numerikus opciókat, és úgy adja át az
	egész számot, mintha a `func_ptr` által megadott függvény argumentuma
	lenne. Az eredmény a `var`-ba kerül. Csak egy ilyen opciódefiníció
	lehet. Nem negálható, és nem vesz át argumentumot. A véletlenül
	számjegyekből álló rövid opciók elsőbbséget élveznek vele szemben.

`OPT_COLOR_FLAG(short, long, &int_var, description)`::
	Bevezet egy opciót, amely opcionális argumentumot vesz át, amelynek
	három érték egyike lehet: "always", "never" vagy "auto". Ha az
	argumentum nincs megadva, az alapértelmezés "always". A `--no-` alak
	úgy működik, mint a `--long=never`; nem vehet át argumentumot. Ha
	"always", állítsd az `int_var`-t 1-re; ha "never", 0-ra; ha "auto",
	1-re, ha a stdout tty vagy pager, egyébként 0-ra.

`OPT_NOOP_NOARG(short, long)`::
	Bevezet egy opciót, amelynek nincs hatása, és nem vesz át argumentumot.
	Használd olyan elavult opciók elrejtésére, amelyeket még fel kell
	ismerni, és csendben figyelmen kívül kell hagyni.

`OPT_PASSTHRU(short, long, &char_var, arg_str, description, flags)`::
	Bevezet egy opciót, amelyet egy char* sztringgé építenek újra,
	amelyet NULL-ra kell inicializálni. Ez hasznos, ha a parancssori
	opciót át kell adnod egy másik parancsnak. Minden korábbi érték
	felülíródik, ezért ezt csak olyan opciókhoz szabad használni, ahol
	a parancssorban utoljára megadott nyer.

`OPT_PASSTHRU_ARGV(short, long, &strvec_var, arg_str, description, flags)`::
	Bevezet egy opciót, amelynek a parancssoron lévő összes példányát
	egy strvec-cé építik újra. Ez hasznos, ha egy olyan parancssori
	opciót, amely többször is megadható, át kell adnod egy másik
	parancsnak.

`OPT_CMDMODE(short, long, &int_var, description, enum_val)`::
	Definiál egy "működési mód" opciót, amelyből ugyanabban a
	"működési mód" opciócsoportban, amely ugyanazon az `int_var`-on
	osztozik, a felhasználó csak egyet adhat meg. Az `int_var` az
	`enum_val`-ra áll, amikor az opciót használják, de hibát jelez, ha
	más "működési mód" opció már ugyanarra az `int_var`-ra állította az
	értékét. Új parancsokban fontold meg inkább az alparancsok használatát.

`OPT_SUBCOMMAND(long, &fn_ptr, subcommand_fn)`::
	Definiál egy alparancsot. A `subcommand_fn` a `fn_ptr`-ba kerül,
	amikor ezt az alparancsot használják.

A tömb utolsó elemének `OPT_END()`-nek kell lennie.

Ha másképp nincs jelezve, az argumentumokat a következőképpen értelmezd:

* a `short` a rövid opcióhoz tartozó karakter
  (pl. `'e'` a `-e`-hez, `0` az elhagyáshoz),

* a `long` a hosszú opcióhoz tartozó sztring
  (pl. `"example"` a `--example`-höz, `NULL` az elhagyáshoz),

* az `int_var` egy egész szám változó,

* a `str_var` egy sztring változó (`char *`),

* az `arg_str` az a sztring, amely argumentumként jelenik meg
  (pl. a `"branch"` `<branch>`-et eredményez).
  Ha `NULL`-ra van állítva, három pont (`...`) jelenik meg.

* a `description` egy rövid sztring, amely leírja az opció hatását.
  Kisbetűvel kell kezdődnie, és a végéről el kell hagyni a pontot (`.`).

[[_option_callbacks]]
Opció-visszahívások
-------------------

A függvényt a következő alakban kell definiálni:

	int func(const struct option *opt, const char *arg, int unset)

A visszahívási mechanizmus a következő:

* A `func`-on belül az `opt` által megadott struktúra egyetlen
  érdekes tagja a `opt->value` void mutató.
  A `*opt->value` lesz az az érték, amely a `var`-ba mentődik, ha
  az `OPT_CALLBACK()`-et használod.
  Például az `*(unsigned long *)opt->value = 42;` beállítja a 42-t
  egy `unsigned long` változóba.

* A `0` visszatérési érték sikert jelez, a nem nulla visszatérési
  érték pedig meghívja a `usage_with_options()`-t, és így leáll.

* Ha a felhasználó negálja az opciót, az `arg` `NULL`, az `unset` pedig 1.

[[_sophisticated_option_parsing]]
Kifinomult opció-feldolgozás
----------------------------

Ha például opcionális argumentumú vagy egyáltalán argumentum nélküli
opció-visszahívásokra van szükséged, vagy ha más, a fenti makrók által
nem kezelt speciális esetekre van szükséged, akkor az `option` struktúra
tagjait kézzel kell megadnod.

Ezt ez a dokumentum nem tárgyalja, de maga a `parse-options.h`
jól dokumentálja.

[[_examples]]
Példák
------

Valós példákért lásd a `test-parse-options.c`-t és a
`builtin/add.c`,
`builtin/clone.c`,
`builtin/commit.c`,
`builtin/fetch.c`,
`builtin/fsck.c`,
`builtin/rm.c`
fájlokat.
