= Trace2 API

A Trace2 API hibakeresési, teljesítmény- és telemetriai információk
stderr-re vagy fájlba írására használható. A Trace2 funkció inaktív, hacsak
nem engedélyezik kifejezetten egy vagy több Trace2 cél engedélyezésével.

A Trace2 API célja a meglévő (Trace1) `printf()`-stílusú nyomkövetés
lecserélése, amelyet a meglévő `GIT_TRACE` és `GIT_TRACE_PERFORMANCE`
szolgáltatások nyújtanak. A kezdeti megvalósítás során a Trace2 és a
Trace1 párhuzamosan működhet.

A Trace2 API magas szintű üzenetek halmazát definiálja ismert mezőkkel,
mint például (`start`: `argv`) és (`exit`: {`exit-code`, `elapsed-time`}).

A Git kódbázisában elhelyezett Trace2 műszerezés Trace2 üzeneteket küld az
engedélyezett Trace2 céloknak. A célok ezen üzenetek tartalmát célspecifikus
formátumokká alakítják, és eseményeket írnak az adatfolyamaikba. Ily módon
a Trace2 API sokféle elemzést tud kiszolgálni.

A célokat egy VTable segítségével definiálják, amely lehetővé teszi a
jövőben más formátumokra való egyszerű kiterjesztést. Ezt például egy
bináris formátum definiálására lehetne használni.

A Trace2-t a rendszer- és globális konfigurációs fájlokban lévő `trace2.*`
konfigurációs értékekkel és a `GIT_TRACE2*` környezeti változókkal
vezérlik. A Trace2 nem olvas a repó-lokális vagy working tree konfigurációs
fájlokból, és nem veszi figyelembe a `-c` parancssori konfigurációs
beállításokat sem.

[[_trace2_targets]]
== Trace2 célok

A Trace2 a Trace2 célok következő halmazát definiálja.
A formátum részleteit egy későbbi szakasz tartalmazza.

[[_the_normal_format_target]]
=== A normál formátumú cél

A normál formátumú cél egy hagyományos `printf()` formátum, és hasonló a
`GIT_TRACE` formátumhoz. Ezt a formátumot a `GIT_TRACE2` környezeti
változóval vagy a `trace2.normalTarget` rendszer- vagy globális
konfigurációs beállítással engedélyezik.

Például

------------
$ export GIT_TRACE2=~/log.normal
$ git version
git version 2.20.1.155.g426c96fcdb
------------

vagy

------------
$ git config --global trace2.normalTarget ~/log.normal
$ git version
git version 2.20.1.155.g426c96fcdb
------------

ez az eredménye:

------------
$ cat ~/log.normal
12:28:42.620009 common-main.c:38                  version 2.20.1.155.g426c96fcdb
12:28:42.620989 common-main.c:39                  start git version
12:28:42.621101 git.c:432                         cmd_name version (version)
12:28:42.621215 git.c:662                         exit elapsed:0.001227 code:0
12:28:42.621250 trace2/tr2_tgt_normal.c:124       atexit elapsed:0.001265 code:0
------------

[[_the_performance_format_target]]
=== A teljesítmény formátumú cél

A teljesítmény formátumú cél (PERF) egy oszlopalapú formátum a
`GIT_TRACE_PERFORMANCE` lecserélésére, és fejlesztéshez, valamint
teszteléshez alkalmas, esetleg olyan eszközök kiegészítésére, mint a
`gprof`. Ezt a formátumot a `GIT_TRACE2_PERF` környezeti változóval vagy a
`trace2.perfTarget` rendszer- vagy globális konfigurációs beállítással
engedélyezik.

Például

------------
$ export GIT_TRACE2_PERF=~/log.perf
$ git version
git version 2.20.1.155.g426c96fcdb
------------

vagy

------------
$ git config --global trace2.perfTarget ~/log.perf
$ git version
git version 2.20.1.155.g426c96fcdb
------------

ez az eredménye:

------------
$ cat ~/log.perf
12:28:42.620675 common-main.c:38                  | d0 | main                     | version      |     |           |           |            | 2.20.1.155.g426c96fcdb
12:28:42.621001 common-main.c:39                  | d0 | main                     | start        |     |  0.001173 |           |            | git version
12:28:42.621111 git.c:432                         | d0 | main                     | cmd_name     |     |           |           |            | version (version)
12:28:42.621225 git.c:662                         | d0 | main                     | exit         |     |  0.001227 |           |            | code:0
12:28:42.621259 trace2/tr2_tgt_perf.c:211         | d0 | main                     | atexit       |     |  0.001265 |           |            | code:0
------------

[[_the_event_format_target]]
=== Az esemény formátumú cél

Az esemény formátumú cél az eseményadatok JSON-alapú formátuma, amely
telemetriai elemzéshez alkalmas. Ezt a formátumot a `GIT_TRACE2_EVENT`
környezeti változóval vagy a `trace2.eventTarget` rendszer- vagy globális
konfigurációs beállítással engedélyezik.

Például

------------
$ export GIT_TRACE2_EVENT=~/log.event
$ git version
git version 2.20.1.155.g426c96fcdb
------------

vagy

------------
$ git config --global trace2.eventTarget ~/log.event
$ git version
git version 2.20.1.155.g426c96fcdb
------------

ez az eredménye:

------------
$ cat ~/log.event
{"event":"version","sid":"20190408T191610.507018Z-H9b68c35f-P000059a8","thread":"main","time":"2019-01-16T17:28:42.620713Z","file":"common-main.c","line":38,"evt":"4","exe":"2.20.1.155.g426c96fcdb"}
{"event":"start","sid":"20190408T191610.507018Z-H9b68c35f-P000059a8","thread":"main","time":"2019-01-16T17:28:42.621027Z","file":"common-main.c","line":39,"t_abs":0.001173,"argv":["git","version"]}
{"event":"cmd_name","sid":"20190408T191610.507018Z-H9b68c35f-P000059a8","thread":"main","time":"2019-01-16T17:28:42.621122Z","file":"git.c","line":432,"name":"version","hierarchy":"version"}
{"event":"exit","sid":"20190408T191610.507018Z-H9b68c35f-P000059a8","thread":"main","time":"2019-01-16T17:28:42.621236Z","file":"git.c","line":662,"t_abs":0.001227,"code":0}
{"event":"atexit","sid":"20190408T191610.507018Z-H9b68c35f-P000059a8","thread":"main","time":"2019-01-16T17:28:42.621268Z","file":"trace2/tr2_tgt_event.c","line":163,"t_abs":0.001265,"code":0}
------------

[[_enabling_a_target]]
=== Egy cél engedélyezése

Egy cél engedélyezéséhez állítsd a megfelelő környezeti változót vagy
rendszer- vagy globális konfigurációs értéket a következők egyikére:

include::../trace2-target-values.adoc[]

Amikor a nyomkövetési fájlokat egy célkönyvtárba írják, a SID utolsó
komponense szerint kapnak nevet (opcionálisan egy számlálóval kiegészítve
a fájlnév-ütközések elkerülésére).

[[_trace2_api]]
== Trace2 API

A Trace2 publikus API-ját a `trace2.h` definiálja és dokumentálja; további
információért nézd meg azt. Minden publikus függvény és makró `trace2_`
előtaggal rendelkezik, és a `trace2.c`-ben van megvalósítva.

Nincsenek publikus Trace2 adatszerkezetek.

A Trace2 kód privát függvények és adattípusok halmazát is definiálja a
`trace2/` könyvtárban. Ezek a szimbólumok `tr2_` előtaggal rendelkeznek,
és csak a `trace2.c`-beli függvények (vagy más, `trace2/`-beli privát
forrásfájlok) használhatják őket.

[[_conventions_for_public_functions_and_macros]]
=== Konvenciók a publikus függvényekhez és makrókhoz

Egyes függvények `_fl()` utótaggal rendelkeznek, jelezve, hogy `file` és
`line-number` argumentumokat vesznek át.

Egyes függvények `_va_fl()` utótaggal rendelkeznek, jelezve, hogy egy
`va_list` argumentumot is átvesznek.

Egyes függvények `_printf_fl()` utótaggal rendelkeznek, jelezve, hogy egy
`printf()` stílusú, változó számú argumentumú formátumot is átvesznek.

CPP burkoló makrók vannak definiálva, hogy elrejtsék e részletek nagy részét.

[[_trace2_target_formats]]
== Trace2 célformátumok

[[_normal_format]]
=== NORMAL formátum

Az események a következő alakú sorokként íródnak:

------------
[<time> SP <filename>:<line> SP+] <event-name> [[SP] <event-message>] LF
------------

`<event-name>`::

	az esemény neve.

`<event-message>`::
	egy szabad formátumú `printf()` üzenet, amelyet emberi fogyasztásra
	szánnak.
+
Vedd figyelembe, hogy ez tartalmazhat beágyazott LF vagy CRLF
karaktereket, amelyek nincsenek escape-elve, így az esemény több sorra
is kiterjedhet.

Ha a `GIT_TRACE2_BRIEF` vagy a `trace2.normalBrief` igaz, a `time`,
`filename` és `line` mezők kimaradnak.

Ez a cél inkább összefoglaló jellegű (mint a GIT_TRACE), és kevésbé
részletes, mint a többi cél. Például figyelmen kívül hagyja a szál-,
régió- és adatüzeneteket.

[[_perf_format]]
=== PERF formátum

Az események a következő alakú sorokként íródnak:

------------
[<time> SP <filename>:<line> SP+
    BAR SP] d<depth> SP
    BAR SP <thread-name> SP+
    BAR SP <event-name> SP+
    BAR SP [r<repo-id>] SP+
    BAR SP [<t_abs>] SP+
    BAR SP [<t_rel>] SP+
    BAR SP [<category>] SP+
    BAR SP DOTS* <perf-event-message>
    LF
------------

`<depth>`::
	a git folyamat mélysége. Ez a szülő git folyamatok száma. Egy
	legfelső szintű git parancs mélységértéke "d0". Egy gyermekének
	mélységértéke "d1". Egy második szintű gyermeknek "d2" a
	mélységértéke, és így tovább.

`<thread-name>`::
	a szál egyedi neve. Az elsődleges szál neve "main". A többi szál
	neve "th%d:%s" alakú, és egy egyedi számot, valamint a thread-proc
	nevét tartalmazza.

`<event-name>`::
	az esemény neve.

`<repo-id>`::
	ha jelen van, egy szám, amely a használatban lévő repository-t
	jelzi. Egy `def_repo` esemény kerül kibocsátásra, amikor egy
	repository-t megnyitnak. Ez definiálja a repo-id-t és a hozzá
	tartozó working tree-t. A későbbi repository-specifikus események
	erre a repo-id-ra fognak hivatkozni.
+
Jelenleg ez mindig "r1" a fő repository esetén.
Ez a mező a jövőbeli, folyamaton belüli submodule-ok előrejelzése.

`<t_abs>`::
	ha jelen van, a program indulása óta eltelt abszolút idő
	másodpercben.

`<t_rel>`::
	ha jelen van, az aktuális régió kezdetéhez viszonyított idő
	másodpercben. Egy thread-exit esemény esetén ez a szál eltelt
	ideje.

`<category>`::
	a régió- és adateseményeken jelenik meg, és egy tág kategória
	jelzésére szolgál, mint például "index" vagy "status".

`<perf-event-message>`::
	egy szabad formátumú `printf()` üzenet, amelyet emberi fogyasztásra
	szánnak.

------------
15:33:33.532712 wt-status.c:2310                  | d0 | main                     | region_enter | r1  |  0.126064 |           | status     | label:print
15:33:33.532712 wt-status.c:2331                  | d0 | main                     | region_leave | r1  |  0.127568 |  0.001504 | status     | label:print
------------

Ha a `GIT_TRACE2_PERF_BRIEF` vagy a `trace2.perfBrief` igaz, a `time`,
`file` és `line` mezők kimaradnak.

------------
d0 | main                     | region_leave | r1  |  0.011717 |  0.009122 | index      | label:preload
------------

A PERF cél fejlesztés közbeni interaktív teljesítményelemzéshez való, és
meglehetősen zajos.

[[_event_format]]
=== EVENT formátum

Minden esemény egy JSON-objektum, amely több kulcs/érték párt tartalmaz,
egyetlen sorba írva, amelyet egy LF követ.

------------
'{' <key> ':' <value> [',' <key> ':' <value>]* '}' LF
------------

Egyes kulcs/érték párok minden eseményre közösek, mások
eseményspecifikusak.

[[_common_key_value_pairs]]
==== Közös kulcs/érték párok

A következő kulcs/érték párok minden eseményre közösek:

------------
{
	"event":"version",
	"sid":"20190408T191827.272759Z-H9b68c35f-P00003510",
	"thread":"main",
	"time":"2019-04-08T19:18:27.282761Z",
	"file":"common-main.c",
	"line":42,
	...
}
------------

`"event":<event>`::
	az esemény neve.

`"sid":<sid>`::
	a session-id. Ez egy egyedi sztring a folyamatpéldány
	azonosítására, amely lehetővé teszi egy folyamat által kibocsátott
	összes esemény azonosítását. Session-id-t használunk PID helyett,
	mert a PID-eket az operációs rendszer újrahasznosítja. Gyermek git
	folyamatok esetén a session-id elé kerül a szülő git folyamat
	session-id-ja, hogy a szülő-gyermek kapcsolatok azonosíthatók
	legyenek az utófeldolgozás során.

`"thread":<thread>`::
	a szál neve.

`"time":<time>`::
	az esemény UTC-ideje.

`"file":<filename>`::
	az eseményt generáló forrásfájl.

`"line":<line-number>`::
	az eseményt generáló egész számú forrássor száma.

`"repo":<repo-id>`::
	ha jelen van, a korábban leírt egész számú repo-id.

Ha a `GIT_TRACE2_EVENT_BRIEF` vagy a `trace2.eventBrief` igaz, a `file` és
`line` mezők minden eseményből kimaradnak, a `time` mező pedig csak a
"start" és az "atexit" eseményeken van jelen.

[[_event_specific_key_value_pairs]]
==== Eseményspecifikus kulcs/érték párok

`"version"`::
	Ez az esemény megadja a futtatható állomány és az EVENT formátum
	verzióját. Mindig ez legyen az első esemény egy nyomkövetési
	munkamenetben. Az EVENT formátum verziója növekszik, ha új
	eseménytípusokat adnak hozzá, ha meglévő mezőket távolítanak el, vagy
	ha jelentős változás történik a meglévő események vagy mezők
	értelmezésében. A kisebb változások, mint egy új mező hozzáadása egy
	meglévő eseményhez, nem igénylik az EVENT formátum verziójának
	növelését.
+
------------
{
	"event":"version",
	...
	"evt":"4",		       # EVENT format version
	"exe":"2.20.1.155.g426c96fcdb" # git version
}
------------

`"too_many_files"`::
	Ez az esemény a git-trace2-discard őrszemfájlba íródik, ha túl sok
	fájl van a cél nyomkövetési könyvtárban (lásd a trace2.maxFiles
	konfigurációs opciót).
+
------------
{
	"event":"too_many_files",
	...
}
------------

`"start"`::
	Ez az esemény a main() által kapott teljes argv-t tartalmazza.
+
------------
{
	"event":"start",
	...
	"t_abs":0.001227, # elapsed time in seconds
	"argv":["git","version"]
}
------------

`"exit"`::
	Ez az esemény akkor kerül kibocsátásra, amikor a git meghívja az
	`exit()`-et.
+
------------
{
	"event":"exit",
	...
	"t_abs":0.001227, # elapsed time in seconds
	"code":0	  # exit code
}
------------

`"atexit"`::
	Ezt az eseményt a Trace2 `atexit` rutin bocsátja ki a végső leállítás
	során. Ez legyen az utolsó esemény, amelyet a folyamat kibocsát.
+
(Az itt jelentett eltelt idő nagyobb, mint az "exit" eseményben jelentett
idő, mert az összes többi atexit feladat befejezése után fut.)
+
------------
{
	"event":"atexit",
	...
	"t_abs":0.001227, # elapsed time in seconds
	"code":0          # exit code
}
------------

`"signal"`::
	Ez az esemény akkor kerül kibocsátásra, amikor a programot egy
	felhasználói szignál leállítja. A platformtól függően a szignálesemény
	megakadályozhatja az "atexit" esemény generálását.
+
------------
{
	"event":"signal",
	...
	"t_abs":0.001227,  # elapsed time in seconds
	"signo":13         # SIGTERM, SIGINT, etc.
}
------------

`"error"`::
	Ez az esemény akkor kerül kibocsátásra, amikor a `BUG()`, `bug()`,
	`error()`, `die()`, `warning()` vagy `usage()` függvények egyikét
	meghívják.
+
------------
{
	"event":"error",
	...
	"msg":"invalid option: --cahced", # formatted error message
	"fmt":"invalid option: %s"	  # error format string
}
------------
+
Az error esemény többször is kibocsátásra kerülhet. A formátumsztring
lehetővé teszi az utófeldolgozók számára, hogy típus szerint csoportosítsák
a hibákat anélkül, hogy a konkrét hibaargumentumokkal foglalkoznának.

`"cmd_path"`::
	Ez az esemény a git futtatható állomány felfedezett teljes elérési
	útját tartalmazza (azokon a platformokon, amelyek úgy vannak
	konfigurálva, hogy feloldják).
+
------------
{
	"event":"cmd_path",
	...
	"path":"C:/work/gfw/git.exe"
}
------------

`"cmd_ancestry"`::
	Ez az esemény az aktuális folyamat szülőjének (és a szülők korábbi
	generációinak) szöveges parancsnevét tartalmazza, egy tömbben, a
	legközelebbi szülőtől a legtávolabbi dédszülőig rendezve. Lehet, hogy
	nem minden platformon van megvalósítva.
+
------------
{
	"event":"cmd_ancestry",
	...
	"ancestry":["bash","tmux: server","systemd"]
}
------------

`"cmd_name"`::
	Ez az esemény ennek a git folyamatnak a parancsnevét, valamint a
	szülő git folyamatoktól származó parancsok hierarchiáját tartalmazza.
+
------------
{
	"event":"cmd_name",
	...
	"name":"pack-objects",
	"hierarchy":"push/pack-objects"
}
------------
+
Általában a "name" mező a parancs kanonikus nevét tartalmazza. Amikor
nincs elérhető kanonikus név, ezen speciális értékek egyikét használjuk:
+
------------
"_query_"            # "git --html-path"
"_run_dashed_"       # when "git foo" tries to run "git-foo"
"_run_shell_alias_"  # alias expansion to a shell command
"_run_git_alias_"    # alias expansion to a git command
"_usage_"            # usage error
------------

`"cmd_mode"`::
	Ez az esemény, ha jelen van, a parancs változatát írja le. Ez az
	esemény többször is kibocsátásra kerülhet.
+
------------
{
	"event":"cmd_mode",
	...
	"name":"branch"
}
------------
+
A "name" mező egy tetszőleges sztring a parancsmód leírására. Például a
checkout ki tud checkoutolni egy branchet vagy egy egyedi fájlt. Ezeknek
a változatoknak jellemzően eltérő, nem összehasonlítható
teljesítményjellemzőik vannak.

`"alias"`::
	Ez az esemény akkor van jelen, amikor egy aliast kibontanak.
+
------------
{
	"event":"alias",
	...
	"alias":"l",		 # registered alias
	"argv":["log","--graph"] # alias expansion
}
------------

`"child_start"`::
	Ez az esemény egy gyermekfolyamatot ír le, amelyet éppen létre fognak
	hozni.
+
------------
{
	"event":"child_start",
	...
	"child_id":2,
	"child_class":"?",
	"use_shell":false,
	"argv":["git","rev-list","--objects","--stdin","--not","--all","--quiet"]

	"hook_name":"<hook_name>"  # present when child_class is "hook"
	"cd":"<path>"		   # present when cd is required
}
------------
+
A "child_id" mező használható ennek a child_start-nak a megfelelő
child_exit eseménnyel való párosítására.
+
A "child_class" mező egy durva besorolás, mint például "editor", "pager",
"transport/*" és "hook". A besorolatlan gyermekeket "?" jelöli.

`"child_exit"`::
	Ez az esemény azután generálódik, hogy az aktuális folyamat
	visszatért a `waitpid()`-ből, és összegyűjtötte a gyermek kilépési
	információit.
+
------------
{
	"event":"child_exit",
	...
	"child_id":2,
	"pid":14708,	 # child PID
	"code":0,	 # child exit-code
	"t_rel":0.110605 # observed run-time of child process
}
------------
+
Vedd figyelembe, hogy a gyermekfolyamat session-id-ja nem elérhető az
aktuális/létrehozó folyamat számára, ezért a gyermek PID-jét jelentjük itt
az utófeldolgozás segítéséhez. (De ez csak egy támpont, mert a
gyermekfolyamat lehet egy shell szkript, amelynek nincs session-id-ja.)
+
Vedd figyelembe, hogy a `t_rel` mező a gyermekfolyamat megfigyelt
futásidejét tartalmazza másodpercben (a fork/exec/spawn előtt indulva és a
`waitpid()` után megállva, és tartalmazza az OS folyamatlétrehozási
többletköltségét). Így ez az idő valamivel nagyobb lesz, mint a
gyermekfolyamat által jelentett atexit idő.

`"child_ready"`::
	Ez az esemény azután generálódik, hogy az aktuális folyamat elindított
	egy háttérfolyamatot, és felszabadította az összes rá mutató
	leírót.
+
------------
{
	"event":"child_ready",
	...
	"child_id":2,
	"pid":14708,	 # child PID
	"ready":"ready", # child ready state
	"t_rel":0.110605 # observed run-time of child process
}
------------
+
Vedd figyelembe, hogy a gyermekfolyamat session-id-ja nem elérhető az
aktuális/létrehozó folyamat számára, ezért a gyermek PID-jét jelentjük itt
az utófeldolgozás segítéséhez. (De ez csak egy támpont, mert a
gyermekfolyamat lehet egy shell szkript, amelynek nincs session-id-ja.)
+
Ez az esemény azután generálódik, hogy a gyermeket a háttérben elindították,
és egy kevés időt kapott a felállásra és a munka megkezdésére. Ha a gyermek
normálisan elindul, miközben a szülő még vár, a "ready" mező értéke "ready"
lesz.
Ha a gyermek túl lassan indul, és a szülő túllépi az időkorlátot, a mező
értéke "timeout" lesz.
Ha a gyermek elindul, de a szülő nem tudja megvizsgálni, a mező értéke
"error" lesz.
+
Miután a szülőfolyamat kibocsátja ezt az eseményt, felszabadítja az összes
gyermekfolyamatra mutató leíróját, és a gyermeket háttér-daemonként kezeli.
Így még ha a gyermek végül be is fejezi a felállást, a szülő nem bocsát ki
frissített eseményt.
+
Vedd figyelembe, hogy a `t_rel` mező azt a megfigyelt futásidőt tartalmazza
másodpercben, amikor a szülő a háttérbe engedte a gyermekfolyamatot.
A gyermekről feltételezzük, hogy hosszú életű daemon folyamat, és túlélheti
a szülőfolyamatot. Ezért a szülő gyermekeseményeinek idejét nem szabad
összehasonlítani a gyermek atexit idejével.

`"exec"`::
	Ez az esemény azelőtt generálódik, hogy a git megkísérelné egy másik
	parancs `exec()`-elését, ahelyett, hogy gyermekfolyamatot indítana.
+
------------
{
	"event":"exec",
	...
	"exec_id":0,
	"exe":"git",
	"argv":["foo", "bar"]
}
------------
+
Az "exec_id" mező egy parancsonként egyedi azonosító, és csak akkor
hasznos, ha az `exec()` sikertelen, és egy megfelelő exec_result esemény
generálódik.

`"exec_result"`::
	Ez az esemény akkor generálódik, ha az `exec()` sikertelen, és a
	vezérlés visszatér az aktuális git parancshoz.
+
------------
{
	"event":"exec_result",
	...
	"exec_id":0,
	"code":1      # error code (errno) from exec()
}
------------

`"thread_start"`::
	Ez az esemény akkor generálódik, amikor egy szál elindul. Az új szál
	thread-procján *belül* generálódik (mert hozzá kell férnie a szál
	szál-lokális tárolójában lévő adatokhoz).
+
------------
{
	"event":"thread_start",
	...
	"thread":"th02:preload_thread" # thread name
}
------------

`"thread_exit"`::
	Ez az esemény akkor generálódik, amikor egy szál kilép. A szál
	thread-procján *belül* generálódik.
+
------------
{
	"event":"thread_exit",
	...
	"thread":"th02:preload_thread", # thread name
	"t_rel":0.007328                # thread elapsed time
}
------------

`"def_param"`::
	Ez az esemény egy globális paraméter naplózására generálódik, mint
	például egy konfigurációs beállítás, parancssori jelző vagy környezeti
	változó.
+
------------
{
	"event":"def_param",
	...
	"scope":"global",
	"param":"core.abbrev",
	"value":"7"
}
------------

`"def_repo"`::
	Ez az esemény definiál egy repo-id-t, és a working tree gyökeréhez
	társítja.
+
------------
{
	"event":"def_repo",
	...
	"repo":1,
	"worktree":"/Users/jeffhost/work/gfw"
}
------------
+
Ahogy korábban említettük, a repo-id jelenleg mindig 1, így csak egy
def_repo esemény lesz. Később, ha a folyamaton belüli submodule-ok
támogatottak lesznek, minden meglátogatott submodule-hoz egy def_repo
eseményt kell kibocsátani.

`"region_enter"`::
	Ez az esemény egy régióba való belépéskor generálódik.
+
------------
{
	"event":"region_enter",
	...
	"repo":1,                # optional
	"nesting":1,             # current region stack depth
	"category":"index",      # optional
	"label":"do_read_index", # optional
	"msg":".git/index"       # optional
}
------------
+
A `category` mező egy jövőbeli fejlesztésben kategóriaalapú szűrésre
használható.
+
A `GIT_TRACE2_EVENT_NESTING` vagy a `trace2.eventNesting` a mélyen
egymásba ágyazott régiók és adatesemények szűrésére használható. Az
alapértéke "2".

`"region_leave"`::
	Ez az esemény egy régióból való kilépéskor generálódik.
+
------------
{
	"event":"region_leave",
	...
	"repo":1,                # optional
	"t_rel":0.002876,        # time spent in region in seconds
	"nesting":1,             # region stack depth
	"category":"index",      # optional
	"label":"do_read_index", # optional
	"msg":".git/index"       # optional
}
------------

`"data"`::
	Ez az esemény egy szál- és régió-lokális kulcs/érték pár naplózására
	generálódik.
+
------------
{
	"event":"data",
	...
	"repo":1,              # optional
	"t_abs":0.024107,      # absolute elapsed time
	"t_rel":0.001031,      # elapsed time in region/thread
	"nesting":2,           # region stack depth
	"category":"index",
	"key":"read/cache_nr",
	"value":"3552"
}
------------
+
A "value" mező lehet egész szám vagy sztring.

`"data-json"`::
	Ez az esemény egy előre formázott, strukturált adatokat tartalmazó
	JSON-sztring naplózására generálódik.
+
------------
{
	"event":"data_json",
	...
	"repo":1,              # optional
	"t_abs":0.015905,
	"t_rel":0.015905,
	"nesting":1,
	"category":"process",
	"key":"windows/ancestry",
	"value":["bash.exe","bash.exe"]
}
------------

`"th_timer"`::
	Ez az esemény azt az időmennyiséget naplózza, ameddig egy stopper
	időzítő futott a szálban. Ez az esemény akkor generálódik, amikor egy
	szál kilép, azon időzítők esetében, amelyek szálankénti eseményeket
	kértek.
+
------------
{
	"event":"th_timer",
	...
	"category":"my_category",
	"name":"my_timer",
	"intervals":5,         # number of time it was started/stopped
	"t_total":0.052741,    # total time in seconds it was running
	"t_min":0.010061,      # shortest interval
	"t_max":0.011648       # longest interval
}
------------

`"timer"`::
	Ez az esemény azt az időmennyiséget naplózza, ameddig egy stopper
	időzítő futott, az összes szálon összesítve. Ez az esemény a folyamat
	kilépésekor generálódik.
+
------------
{
	"event":"timer",
	...
	"category":"my_category",
	"name":"my_timer",
	"intervals":5,         # number of time it was started/stopped
	"t_total":0.052741,    # total time in seconds it was running
	"t_min":0.010061,      # shortest interval
	"t_max":0.011648       # longest interval
}
------------

`"th_counter"`::
	Ez az esemény egy számlálóváltozó értékét naplózza egy szálban. Ez az
	esemény akkor generálódik, amikor egy szál kilép, azon számlálók
	esetében, amelyek szálankénti eseményeket kértek.
+
------------
{
	"event":"th_counter",
	...
	"category":"my_category",
	"name":"my_counter",
	"count":23
}
------------

`"counter"`::
	Ez az esemény egy számlálóváltozó értékét naplózza az összes szálon.
	Ez az esemény a folyamat kilépésekor generálódik. Az itt jelentett
	teljes érték az összes szálon vett összeg.
+
------------
{
	"event":"counter",
	...
	"category":"my_category",
	"name":"my_counter",
	"count":23
}
------------

`"printf"`::
	Ez az esemény egy ember által olvasható üzenetet naplóz, konkrét
	formázási irányelvek nélkül.
+
------------
{
	"event":"printf",
	...
	"t_abs":0.015905,      # elapsed time in seconds
	"msg":"Hello world"    # optional
}
------------


[[_example_trace2_api_usage]]
== Példa a Trace2 API használatára

Íme a Trace2 API egy hipotetikus használata, amely a szándékolt
használatot mutatja (a tényleges Git-részletekkel való törődés nélkül).

Inicializálás::

	Az inicializálás a `main()`-ben történik. A háttérben egy `atexit`
	és egy `signal` kezelő kerül regisztrálásra.
+
----------------
int main(int argc, const char **argv)
{
	int exit_code;

	trace2_initialize();
	trace2_cmd_start(argv);

	exit_code = cmd_main(argc, argv);

	trace2_cmd_exit(exit_code);

	return exit_code;
}
----------------

Parancsrészletek::

	Miután az alapok megvannak, további parancsinformáció küldhető a
	Trace2-nek, ahogy azt felfedezik.
+
----------------
int cmd_checkout(int argc, const char **argv)
{
	trace2_cmd_name("checkout");
	trace2_cmd_mode("branch");
	trace2_def_repo(the_repository);

	// emit "def_param" messages for "interesting" config settings.
	trace2_cmd_list_config();

	if (do_something())
	    trace2_cmd_error("Path '%s': cannot do something", path);

	return 0;
}
----------------

Gyermekfolyamatok::

	Csomagold be a gyermekfolyamatokat létrehozó kódot.
+
----------------
void run_child(...)
{
	int child_exit_code;
	struct child_process cmd = CHILD_PROCESS_INIT;
	...
	cmd.trace2_child_class = "editor";

	trace2_child_start(&cmd);
	child_exit_code = spawn_child_and_wait_for_it();
	trace2_child_exit(&cmd, child_exit_code);
}
----------------
+
Például a következő fetch parancs elindította az ssh, index-pack,
rev-list és gc folyamatokat. Ez a példa azt is mutatja, hogy a fetch
5,199 másodpercig tartott, és ebből 4,932 az ssh-ban telt.
+
----------------
$ export GIT_TRACE2_BRIEF=1
$ export GIT_TRACE2=~/log.normal
$ git fetch origin
...
----------------
+
----------------
$ cat ~/log.normal
version 2.20.1.vfs.1.1.47.g534dbe1ad1
start git fetch origin
worktree /Users/jeffhost/work/gfw
cmd_name fetch (fetch)
child_start[0] ssh git@github.com ...
child_start[1] git index-pack ...
... (Trace2 events from child processes omitted)
child_exit[1] pid:14707 code:0 elapsed:0.076353
child_exit[0] pid:14706 code:0 elapsed:4.931869
child_start[2] git rev-list ...
... (Trace2 events from child process omitted)
child_exit[2] pid:14708 code:0 elapsed:0.110605
child_start[3] git gc --auto
... (Trace2 events from child process omitted)
child_exit[3] pid:14709 code:0 elapsed:0.006240
exit elapsed:5.198503 code:0
atexit elapsed:5.198541 code:0
----------------
+
Amikor egy git folyamat egy másik git folyamat (közvetlen vagy közvetett)
gyermeke, örökli a Trace2 kontextusinformációkat. Ez lehetővé teszi a
gyermek számára a parancshierarchia kiírását. Ez a példa a gc-t a fetch
child[3]-jaként mutatja. Amikor a gc folyamat a nevét "gc"-ként jelenti,
a hierarchiát "fetch/gc"-ként is jelenti. (Ebben a példában a
gyermekfolyamat trace2 üzenetei az áttekinthetőség kedvéért be vannak
húzva.)
+
----------------
$ export GIT_TRACE2_BRIEF=1
$ export GIT_TRACE2=~/log.normal
$ git fetch origin
...
----------------
+
----------------
$ cat ~/log.normal
version 2.20.1.160.g5676107ecd.dirty
start git fetch official
worktree /Users/jeffhost/work/gfw
cmd_name fetch (fetch)
...
child_start[3] git gc --auto
    version 2.20.1.160.g5676107ecd.dirty
    start /Users/jeffhost/work/gfw/git gc --auto
    worktree /Users/jeffhost/work/gfw
    cmd_name gc (fetch/gc)
    exit elapsed:0.001959 code:0
    atexit elapsed:0.001997 code:0
child_exit[3] pid:20303 code:0 elapsed:0.007564
exit elapsed:3.868938 code:0
atexit elapsed:3.868970 code:0
----------------

Régiók::

	A régiók a kód egy érdekes szakaszának időzítésére használhatók.
+
----------------
void wt_status_collect(struct wt_status *s)
{
	trace2_region_enter("status", "worktrees", s->repo);
	wt_status_collect_changes_worktree(s);
	trace2_region_leave("status", "worktrees", s->repo);

	trace2_region_enter("status", "index", s->repo);
	wt_status_collect_changes_index(s);
	trace2_region_leave("status", "index", s->repo);

	trace2_region_enter("status", "untracked", s->repo);
	wt_status_collect_untracked(s);
	trace2_region_leave("status", "untracked", s->repo);
}

void wt_status_print(struct wt_status *s)
{
	trace2_region_enter("status", "print", s->repo);
	switch (s->status_format) {
	    ...
	}
	trace2_region_leave("status", "print", s->repo);
}
----------------
+
Ebben a példában a nem követett fájlok keresése +0.012568-tól +0.027149-ig
tartott (a folyamat indulása óta), és 0,014581 másodpercig tartott.
+
----------------
$ export GIT_TRACE2_PERF_BRIEF=1
$ export GIT_TRACE2_PERF=~/log.perf
$ git status
...

$ cat ~/log.perf
d0 | main                     | version      |     |           |           |            | 2.20.1.160.g5676107ecd.dirty
d0 | main                     | start        |     |  0.001173 |           |            | git status
d0 | main                     | def_repo     | r1  |           |           |            | worktree:/Users/jeffhost/work/gfw
d0 | main                     | cmd_name     |     |           |           |            | status (status)
...
d0 | main                     | region_enter | r1  |  0.010988 |           | status     | label:worktrees
d0 | main                     | region_leave | r1  |  0.011236 |  0.000248 | status     | label:worktrees
d0 | main                     | region_enter | r1  |  0.011260 |           | status     | label:index
d0 | main                     | region_leave | r1  |  0.012542 |  0.001282 | status     | label:index
d0 | main                     | region_enter | r1  |  0.012568 |           | status     | label:untracked
d0 | main                     | region_leave | r1  |  0.027149 |  0.014581 | status     | label:untracked
d0 | main                     | region_enter | r1  |  0.027411 |           | status     | label:print
d0 | main                     | region_leave | r1  |  0.028741 |  0.001330 | status     | label:print
d0 | main                     | exit         |     |  0.028778 |           |            | code:0
d0 | main                     | atexit       |     |  0.028809 |           |            | code:0
----------------
+
A régiók egymásba ágyazhatók. Ez például azt okozza, hogy az üzenetek be
lesznek húzva a PERF célban.
Az eltelt idők a várakozásnak megfelelően a megfelelő beágyazási szint
kezdetéhez viszonyítottak. Például ha régióüzenetet adunk ehhez:
+
----------------
static enum path_treatment read_directory_recursive(struct dir_struct *dir,
	struct index_state *istate, const char *base, int baselen,
	struct untracked_cache_dir *untracked, int check_only,
	int stop_at_first_file, const struct pathspec *pathspec)
{
	enum path_treatment state, subdir_state, dir_state = path_none;

	trace2_region_enter_printf("dir", "read_recursive", NULL, "%.*s", baselen, base);
	...
	trace2_region_leave_printf("dir", "read_recursive", NULL, "%.*s", baselen, base);
	return dir_state;
}
----------------
+
Tovább vizsgálhatjuk a nem követett fájlok keresésével töltött időt.
+
----------------
$ export GIT_TRACE2_PERF_BRIEF=1
$ export GIT_TRACE2_PERF=~/log.perf
$ git status
...
$ cat ~/log.perf
d0 | main                     | version      |     |           |           |            | 2.20.1.162.gb4ccea44db.dirty
d0 | main                     | start        |     |  0.001173 |           |            | git status
d0 | main                     | def_repo     | r1  |           |           |            | worktree:/Users/jeffhost/work/gfw
d0 | main                     | cmd_name     |     |           |           |            | status (status)
...
d0 | main                     | region_enter | r1  |  0.015047 |           | status     | label:untracked
d0 | main                     | region_enter |     |  0.015132 |           | dir        | ..label:read_recursive
d0 | main                     | region_enter |     |  0.016341 |           | dir        | ....label:read_recursive vcs-svn/
d0 | main                     | region_leave |     |  0.016422 |  0.000081 | dir        | ....label:read_recursive vcs-svn/
d0 | main                     | region_enter |     |  0.016446 |           | dir        | ....label:read_recursive xdiff/
d0 | main                     | region_leave |     |  0.016522 |  0.000076 | dir        | ....label:read_recursive xdiff/
d0 | main                     | region_enter |     |  0.016612 |           | dir        | ....label:read_recursive git-gui/
d0 | main                     | region_enter |     |  0.016698 |           | dir        | ......label:read_recursive git-gui/po/
d0 | main                     | region_enter |     |  0.016810 |           | dir        | ........label:read_recursive git-gui/po/glossary/
d0 | main                     | region_leave |     |  0.016863 |  0.000053 | dir        | ........label:read_recursive git-gui/po/glossary/
...
d0 | main                     | region_enter |     |  0.031876 |           | dir        | ....label:read_recursive builtin/
d0 | main                     | region_leave |     |  0.032270 |  0.000394 | dir        | ....label:read_recursive builtin/
d0 | main                     | region_leave |     |  0.032414 |  0.017282 | dir        | ..label:read_recursive
d0 | main                     | region_leave | r1  |  0.032454 |  0.017407 | status     | label:untracked
...
d0 | main                     | exit         |     |  0.034279 |           |            | code:0
d0 | main                     | atexit       |     |  0.034322 |           |            | code:0
----------------
+
A Trace2 régiók hasonlók a meglévő trace_performance_enter() és
trace_performance_leave() rutinokhoz, de szálbiztosak, és szálankénti
időzítő-vermeket tartanak fenn.

Adatüzenetek::

	Egy régióhoz hozzáadott adatüzenetek.
+
----------------
int read_index_from(struct index_state *istate, const char *path,
	const char *gitdir)
{
	trace2_region_enter_printf("index", "do_read_index", the_repository, "%s", path);

	...

	trace2_data_intmax("index", the_repository, "read/version", istate->version);
	trace2_data_intmax("index", the_repository, "read/cache_nr", istate->cache_nr);

	trace2_region_leave_printf("index", "do_read_index", the_repository, "%s", path);
}
----------------
+
Ez a példa azt mutatja, hogy az index 3552 bejegyzést tartalmazott.
+
----------------
$ export GIT_TRACE2_PERF_BRIEF=1
$ export GIT_TRACE2_PERF=~/log.perf
$ git status
...
$ cat ~/log.perf
d0 | main                     | version      |     |           |           |            | 2.20.1.156.gf9916ae094.dirty
d0 | main                     | start        |     |  0.001173 |           |            | git status
d0 | main                     | def_repo     | r1  |           |           |            | worktree:/Users/jeffhost/work/gfw
d0 | main                     | cmd_name     |     |           |           |            | status (status)
d0 | main                     | region_enter | r1  |  0.001791 |           | index      | label:do_read_index .git/index
d0 | main                     | data         | r1  |  0.002494 |  0.000703 | index      | ..read/version:2
d0 | main                     | data         | r1  |  0.002520 |  0.000729 | index      | ..read/cache_nr:3552
d0 | main                     | region_leave | r1  |  0.002539 |  0.000748 | index      | label:do_read_index .git/index
...
----------------

Szálesemények::

	Egy thread-prochoz hozzáadott szálüzenetek.
+
Például a többszálú preload-index kód műszerezhető egy régióval a
szálkészlet körül, majd szálankénti indulási és kilépési eseményekkel a
thread-procon belül.
+
----------------
static void *preload_thread(void *_data)
{
	// start the per-thread clock and emit a message.
	trace2_thread_start("preload_thread");

	// report which chunk of the array this thread was assigned.
	trace2_data_intmax("index", the_repository, "offset", p->offset);
	trace2_data_intmax("index", the_repository, "count", nr);

	do {
	    ...
	} while (--nr > 0);
	...

	// report elapsed time taken by this thread.
	trace2_thread_exit();
	return NULL;
}

void preload_index(struct index_state *index,
	const struct pathspec *pathspec,
	unsigned int refresh_flags)
{
	trace2_region_enter("index", "preload", the_repository);

	for (i = 0; i < threads; i++) {
	    ... /* create thread */
	}

	for (i = 0; i < threads; i++) {
	    ... /* join thread */
	}

	trace2_region_leave("index", "preload", the_repository);
}
----------------
+
Ebben a példában a preload_index()-et a `main` szál hajtotta végre, és
elindította a `preload` régiót. Hét szál indult el, `th01:preload_thread`-től
`th07:preload_thread`-ig. Az egyes szálak eseményei atomi módon fűződnek a
közös célfolyamhoz, ahogy bekövetkeznek, így a többi szálhoz képest
véletlenszerű sorrendben jelenhetnek meg. Végül a fő szál megvárja, míg a
szálak befejeződnek, és elhagyja a régiót.
+
Az adateseményeket az aktív szál nevével címkézzük. A szálankénti
paraméterek jelentésére szolgálnak.
+
----------------
$ export GIT_TRACE2_PERF_BRIEF=1
$ export GIT_TRACE2_PERF=~/log.perf
$ git status
...
$ cat ~/log.perf
...
d0 | main                     | region_enter | r1  |  0.002595 |           | index      | label:preload
d0 | th01:preload_thread      | thread_start |     |  0.002699 |           |            |
d0 | th02:preload_thread      | thread_start |     |  0.002721 |           |            |
d0 | th01:preload_thread      | data         | r1  |  0.002736 |  0.000037 | index      | offset:0
d0 | th02:preload_thread      | data         | r1  |  0.002751 |  0.000030 | index      | offset:2032
d0 | th03:preload_thread      | thread_start |     |  0.002711 |           |            |
d0 | th06:preload_thread      | thread_start |     |  0.002739 |           |            |
d0 | th01:preload_thread      | data         | r1  |  0.002766 |  0.000067 | index      | count:508
d0 | th06:preload_thread      | data         | r1  |  0.002856 |  0.000117 | index      | offset:2540
d0 | th03:preload_thread      | data         | r1  |  0.002824 |  0.000113 | index      | offset:1016
d0 | th04:preload_thread      | thread_start |     |  0.002710 |           |            |
d0 | th02:preload_thread      | data         | r1  |  0.002779 |  0.000058 | index      | count:508
d0 | th06:preload_thread      | data         | r1  |  0.002966 |  0.000227 | index      | count:508
d0 | th07:preload_thread      | thread_start |     |  0.002741 |           |            |
d0 | th07:preload_thread      | data         | r1  |  0.003017 |  0.000276 | index      | offset:3048
d0 | th05:preload_thread      | thread_start |     |  0.002712 |           |            |
d0 | th05:preload_thread      | data         | r1  |  0.003067 |  0.000355 | index      | offset:1524
d0 | th05:preload_thread      | data         | r1  |  0.003090 |  0.000378 | index      | count:508
d0 | th07:preload_thread      | data         | r1  |  0.003037 |  0.000296 | index      | count:504
d0 | th03:preload_thread      | data         | r1  |  0.002971 |  0.000260 | index      | count:508
d0 | th04:preload_thread      | data         | r1  |  0.002983 |  0.000273 | index      | offset:508
d0 | th04:preload_thread      | data         | r1  |  0.007311 |  0.004601 | index      | count:508
d0 | th05:preload_thread      | thread_exit  |     |  0.008781 |  0.006069 |            |
d0 | th01:preload_thread      | thread_exit  |     |  0.009561 |  0.006862 |            |
d0 | th03:preload_thread      | thread_exit  |     |  0.009742 |  0.007031 |            |
d0 | th06:preload_thread      | thread_exit  |     |  0.009820 |  0.007081 |            |
d0 | th02:preload_thread      | thread_exit  |     |  0.010274 |  0.007553 |            |
d0 | th07:preload_thread      | thread_exit  |     |  0.010477 |  0.007736 |            |
d0 | th04:preload_thread      | thread_exit  |     |  0.011657 |  0.008947 |            |
d0 | main                     | region_leave | r1  |  0.011717 |  0.009122 | index      | label:preload
...
d0 | main                     | exit         |     |  0.029996 |           |            | code:0
d0 | main                     | atexit       |     |  0.030027 |           |            | code:0
----------------
+
Ebben a példában a preload régió 0,009122 másodpercig tartott. A 7 szálnak
0,006069 és 0,008947 másodperc közötti időbe telt feldolgozni az index rá
eső részét. A "th01" szál 508 elemet dolgozott fel a 0-s eltolásnál. A
"th02" szál 508 elemet a 2032-es eltolásnál. A "th04" szál 508 elemet az
508-as eltolásnál.
+
Ez a példa azt is mutatja, hogy a szálneveket versenyhelyzetes módon
osztják ki az egyes szálak indulásakor.

Konfigurációs (def param) események::

	  "Érdekes" konfigurációs értékek kiírása a trace2 naplóba.
+
Opcionálisan kibocsáthatunk konfigurációs eseményeket, lásd a
`trace2.configparams`-t a linkgit:git-config[1]-ben az engedélyezés
módjáról.
+
----------------
$ git config --system color.ui never
$ git config --global color.ui always
$ git config --local color.ui auto
$ git config list --show-scope | grep 'color.ui'
system  color.ui=never
global  color.ui=always
local   color.ui=auto
----------------
+
Ezután jelöld meg a `color.ui` konfigurációt "érdekes" konfigurációként a
`GIT_TRACE2_CONFIG_PARAMS`-szal:
+
----------------
$ export GIT_TRACE2_PERF_BRIEF=1
$ export GIT_TRACE2_PERF=~/log.perf
$ export GIT_TRACE2_CONFIG_PARAMS=color.ui
$ git version
...
$ cat ~/log.perf
d0 | main                     | version      |     |           |           |              | ...
d0 | main                     | start        |     |  0.001642 |           |              | /usr/local/bin/git version
d0 | main                     | cmd_name     |     |           |           |              | version (version)
d0 | main                     | def_param    |     |           |           | scope:system | color.ui:never
d0 | main                     | def_param    |     |           |           | scope:global | color.ui:always
d0 | main                     | def_param    |     |           |           | scope:local  | color.ui:auto
d0 | main                     | data         | r0  |  0.002100 |  0.002100 | fsync        | fsync/writeout-only:0
d0 | main                     | data         | r0  |  0.002126 |  0.002126 | fsync        | fsync/hardware-flush:0
d0 | main                     | exit         |     |  0.000470 |           |              | code:0
d0 | main                     | atexit       |     |  0.000477 |           |              | code:0
----------------

Stopper-időzítő események::

	Egy függvényhívásban vagy egy kódszakaszban töltött idő mérése,
	amelyet a kód sok helyéről meghívhatnak a folyamat élettartama
	során.
+
----------------
static void expensive_function(void)
{
	trace2_timer_start(TRACE2_TIMER_ID_TEST1);
	...
	sleep_millisec(1000); // Do something expensive
	...
	trace2_timer_stop(TRACE2_TIMER_ID_TEST1);
}

static int ut_100timer(int argc, const char **argv)
{
	...

	expensive_function();

	// Do something else 1...

	expensive_function();

	// Do something else 2...

	expensive_function();

	return 0;
}
----------------
+
Ebben a példában az `expensive_function()`-ben töltött teljes időt mérjük,
függetlenül attól, hogy mikor hívják meg a program általános folyamatában.
+
----------------
$ export GIT_TRACE2_PERF_BRIEF=1
$ export GIT_TRACE2_PERF=~/log.perf
$ t/helper/test-tool trace2 100timer 3 1000
...
$ cat ~/log.perf
d0 | main                     | version      |     |           |           |              | ...
d0 | main                     | start        |     |  0.001453 |           |              | t/helper/test-tool trace2 100timer 3 1000
d0 | main                     | cmd_name     |     |           |           |              | trace2 (trace2)
d0 | main                     | exit         |     |  3.003667 |           |              | code:0
d0 | main                     | timer        |     |           |           | test         | name:test1 intervals:3 total:3.001686 min:1.000254 max:1.000929
d0 | main                     | atexit       |     |  3.003796 |           |              | code:0
----------------


[[_future_work]]
== Jövőbeli munka

[[_relationship_to_the_existing_trace_api_api_trace_txt]]
=== Kapcsolat a meglévő Trace API-val (api-trace.txt)

Néhány kérdést meg kell oldani, mielőtt teljesen átállhatunk a Trace2-re.

* A `GIT_TRACE` formátumú üzeneteket feltételező meglévő tesztek
frissítése.

* Hogyan kezeljük legjobban az egyéni `GIT_TRACE_<key>` üzeneteket?

** A `GIT_TRACE_<key>` mechanizmus lehetővé teszi, hogy minden <key> egy
másik fájlba írjon (a puszta stderr-en felül).

** Fenn akarjuk-e tartani ezt a képességet, vagy egyszerűen a meglévő
Trace2 célokba írjunk (és alakítsuk át a <key>-t "category"-vé).
