merge API
=========

A merge API segít egy programnak összeegyeztetni bizonyos fájlok
javításainak két, egymással versengő halmazát (pl. a working tree nem
regisztrált változásait szemben egy új branchre váltással járó
változásokkal), és jelenti a talált konfliktusokat. Az ezen az API-n
keresztül hívott könyvtár néhány dologért felelős.

 * annak meghatározása, hogy mely fákat kell merge-elni (rekurzív ősök
   összevonása);

 * a merge-elendő fákban a megfelelő fájlok egymáshoz igazítása
   (átnevezés-észlelés, részfa-eltolás), és a felhasználónak jelenti az
   olyan határeseteket, mint az add/add és a rename/rename konfliktusok;

 * a megfelelő fájlok háromutas merge-elésének elvégzése, figyelembe
   véve az útvonalspecifikus merge drivereket (amelyeket a
   `.gitattributes` határoz meg).

[[_data_structures]]
Adatszerkezetek
---------------

* `mmbuffer_t`, `mmfile_t`

Ezek olyan adatokat tárolnak, amelyeket az xdiff backend használhat,
írásra, illetve olvasásra. A definíciókat lásd az `xdiff/xdiff.h`-ban,
a példákat a `diff.c`-ben.

* `struct ll_merge_options`

A részletekért nézd meg a merge-ll.h-t.

[[_low_level_single_file_merge]]
Alacsonyszintű (egyetlen fájl) merge
------------------------------------

A részletekért nézd meg a merge-ll.h-t.
