GIT bitmap v1 formátum
======================

[[_pack_and_multi_pack_bitmaps]]
== Pack és multi-pack bitmapek

A bitmapek elérhetőségi információt tárolnak egy packfile-ban, vagy egy
multi-pack indexben (MIDX) lévő objektumok halmazáról. Az előbbi
kézenfekvően definiált, az utóbbi pedig a MIDX-ben található packekben lévő
objektumok uniójaként.

Egy bitmap tartozhat egy packhez, vagy a repository multi-pack indexéhez
(ha az létezik). Egy repository-nak legfeljebb egy bitmapje lehet.

Egy objektumot egyértelműen leír a bitmapen belüli bitpozíciója:

	- Ha a bitmap egy packfile-hoz tartozik, az __n__. bit a pack
	sorrendben lévő __n__. objektumnak felel meg. Egy `offset` függvényre,
	amely az objektumokat a packen belüli bájteltolásukhoz rendeli, a pack
	sorrend a következőképpen definiált:

		o1 <= o2 <==> offset(o1) <= offset(o2)

	- Ha a bitmap egy MIDX-hez tartozik, az __n__. bit a MIDX sorrendben
	lévő __n__. objektumnak felel meg. Egy további `pack` függvénnyel,
	amely az objektumokat ahhoz a packhez rendeli, amelyből a MIDX
	kiválasztotta őket, a MIDX sorrend a következőképpen definiált:

		o1 <= o2 <==> pack(o1) <= pack(o2) /\ offset(o1) <= offset(o2)
+
A packek közötti sorrendezés a MIDX .rev fájlja szerint történik.
Nevezetesen, a preferált pack minden más pack elé kerül a rendezésben.

Egy bitmap lemezen tárolt reprezentációja (lásd lentebb) ugyanaz,
függetlenül attól, hogy az a bitmap egy packfile-hoz vagy egy MIDX-hez
tartozik-e. Az egyetlen különbség a bitek értelmezése, amelyet fentebb
ismertettünk.

Bizonyos bitmap-kiterjesztések támogatottak (lásd: B. függelék). A
packfile-oknak megfelelő bitmapekhez nem szükségesek kiterjesztések. A
MIDX-eknek megfelelő bitmapekhez a bit-cache és a rev-cache kiterjesztés is
szükséges.

[[_on_disk_format]]
== Lemezen tárolt formátum

    * A fejléc a legelején jelenik meg:

	4 bájtos szignatúra: :: {'B', 'I', 'T', 'M'}

	2 bájtos verziószám (hálózati bájtsorrend): ::

	    A jelenlegi megvalósítás csak a bitmap-index 1-es verzióját
	    támogatja (ugyanazt, mint a JGit).

	2 bájtos jelzők (hálózati bájtsorrend): ::

	    A következő jelzők támogatottak:

	    ** {empty}
	    BITMAP_OPT_FULL_DAG (0x1) REQUIRED: :::

	    Ennek a jelzőnek mindig jelen kell lennie. Azt jelenti, hogy a
	    bitmap-index teljes lezárással rendelkező packfile-hoz vagy
	    multi-pack indexhez (MIDX) készült (azaz ahol a packfile/MIDX
	    minden egyes objektuma megtalálja a szülőláncait ugyanazon a
	    packfile-on/MIDX-en belül). Ez a bitmap-index formátum
	    követelménye, amely a JGitben is jelen van, és nagyban csökkenti
	    a megvalósítás összetettségét.

	    ** {empty}
	    BITMAP_OPT_HASH_CACHE (0x4): :::

	    Ha jelen van, a bitmap-fájl vége `N` darab 32 bites name-hash
	    értéket tartalmaz, egyet minden objektumhoz a pack/MIDX-ben. A
	    name-hash formátumát és jelentését lentebb ismertetjük.

		** {empty}
		BITMAP_OPT_LOOKUP_TABLE (0x10): :::
		Ha jelen van, a bitmap-fájl vége egy táblázatot tartalmaz,
		amelyben `N` darab <commit_pos, offset, xor_row> hármas
		listája található. A táblázat formátumát és jelentését lentebb
		ismertetjük.
+
NOTE: Az egyedi bitmap tömörítésére használt xor_offsettel ellentétben az
`xor_row` egy *abszolút* indexet tárol a kikeresési táblába, nem pedig az
aktuális bejegyzéshez viszonyított helyet.

	4 bájtos bejegyzésszám (hálózati bájtsorrend): ::
	    A bejegyzések (bitmapelt commitok) teljes száma ebben a bitmap-indexben.

	20 bájtos ellenőrzőösszeg: ::
	    Annak a pack/MIDX-nek a SHA1 ellenőrzőösszege, amelyhez ez a
	    bitmap-index tartozik.

    * 4 EWAH bitmap, amelyek típusindexként működnek
+
A típusindexek a hash-gyorsítótár után kerülnek szerializálásra négy,
egymás után tárolt EWAH bitmap alakjában (az EWAH bitmap szerializálási
formátumát lásd az A. függelékben).
+
Minden Git objektumtípushoz van egy bitmap, a következő sorrendben
tárolva:
+
    - Commits
    - Trees
    - Blobs
    - Tags

+
Minden bitmapben az `n`. bit igazra van állítva, ha a packfile-ban vagy
multi-pack indexben lévő `n`. objektum ilyen típusú.
+
A kézenfekvő következmény, hogy mind a 4 bitmap VAGY-a teljes halmazt
eredményez (minden bit beállítva), mind a 4 bitmap ÉS-e pedig üres
bitmapet eredményez (egy bit sincs beállítva).

    * N bejegyzés tömörített bitmapekkel, egy minden indexelt commithoz
+
Ahol `N` a bejegyzések teljes száma ebben a bitmap-indexben.
Minden bejegyzés a következőket tartalmazza:

	** {empty}
	4 bájtos objektumpozíció (hálózati bájtsorrend): ::
	    A pozíció **a packfile vagy multi-pack index indexében**, ahol az
	    ehhez a commithoz tartozó bitmap található.

	** {empty}
	1 bájtos XOR-eltolás: ::
	    Az ennek a bitmapnek a tömörítésére használt xor-eltolás. Egy `x`
	    pozícióban lévő bejegyzés esetén az `y` XOR-eltolás azt jelenti,
	    hogy az ezt a commitot reprezentáló tényleges bitmap úgy áll elő,
	    hogy ennek a bejegyzésnek a bitmapjét XOR-oljuk az `x-y`
	    bejegyzésben lévő bitmappel (azaz az ezt megelőző `y`. bitmappel).
+
NOTE: Ez a tömörítés rekurzív lehet. Ahhoz, hogy ezt a bejegyzést egy
korábbival XOR-oljuk, előbb a korábbi bejegyzést kell kitömöríteni, és így
tovább.
+
Ennek az eltolásnak a kemény korlátja 160 (egy bejegyzést csak az őt
megelőző 160 bejegyzés egyikével lehet XOR-olni). Ez a szám mindig pozitív,
így a bejegyzéseket mindig **korábbi** bitmapekkel XOR-oljuk, nem olyan
bitmapekkel, amelyek később jönnek az indexben.

	** {empty}
	1 bájtos jelzők ehhez a bitmaphez: ::
	    Jelenleg az egyetlen elérhető jelző a `0x1`, amely arra utal, hogy
	    ez a bitmap újrafelhasználható a repository bitmap-indexeinek
	    újraépítésekor.

	** Maga a tömörített bitmap, lásd az A. függeléket.

	* {empty}
	TRAILER: ::
		A megelőző tartalom lezáró ellenőrzőösszege.

[[_appendix_a_serialization_format_for_an_ewah_bitmap]]
== A. függelék: Egy EWAH bitmap szerializálási formátuma

Az Ewah bitmapek ugyanazzal a protokollal kerülnek szerializálásra, mint a
JAVAEWAH könyvtár, így visszafelé kompatibilisek a JGit
megvalósítással:

	- Az eredményül kapott TÖMÖRÍTETLEN bitmap bitjeinek 4 bájtos száma

	- A TÖMÖRÍTETT bitmap szavainak 4 bájtos száma, tároláskor

	- N x 8 bájtos szó, az előző mező által megadottak szerint
+
Ez a tömörített bitmap tényleges tartalma.

	- A tömörített bitmaphez tartozó aktuális RLW 4 bájtos
		pozíciója

Minden szó hálózati bájtsorrendben van tárolva a megfelelő
méretéhez.

A tömörített bitmap futáshossz-kódolás formájában van tárolva, a
következőképpen. Tetszőleges számú darab összefűzéséből áll. Minden darab
egy vagy több 64 bites szóból áll

     H  L_1  L_2  L_3 .... L_M

A H neve RLW (run length word). A következőkből áll (az alacsonyabb
helyiértékű bitektől a magasabbak felé):

     - 1 bit: the repeated bit B

     - 32 bits: repetition count K (unsigned)

     - 31 bits: literal word count M (unsigned)

A fenti darab által reprezentált bitfolyam ekkor:

     - K repetitions of B

     - The bits stored in `L_1` through `L_M`.  Within a word, bits at
       lower order come earlier in the stream than those at higher
       order.

Az `L_M` utáni következő szónak (ha van) ismét RLW-nek kell lennie, a
következő darabhoz. A bitfolyamhoz való hatékony hozzáfűzéshez az EWAH egy
mutatót tárol a folyam utolsó RLW-jére.


[[_appendix_b_optional_bitmap_sections]]
== B. függelék: Opcionális bitmap-szakaszok

Ezek a szakaszok jelen lehetnek vagy sem a `.bitmap` fájlban; a jelenlétüket
a fentebb ismertetett fejlécjelzők szakasza jelzi.

[[_name_hash_cache]]
Név-hash gyorsítótár
--------------------

Ha a BITMAP_OPT_HASH_CACHE jelző be van állítva, a bitmap vége 32 bites
értékek gyorsítótárát tartalmazza, egyet minden objektumhoz a pack/MIDX-ben.
Az `i` pozíción lévő érték annak az útvonalnak a hashe, amelyen a pack/MIDX
`i`. objektuma (index- vagy multi-pack index-sorrendben számolva) megtalálható.
Ez betáplálható a delta-heurisztikákba a hasonló útvonalú objektumok
összehasonlításához.

A használt hash-algoritmus:

    hash = 0;
    while ((c = *name++))
	    if (!isspace(c))
		    hash = (hash >> 2) + (c << 24);

Vedd figyelembe, hogy ez a hashelési séma a BITMAP_OPT_HASH_CACHE jelzőhöz
van kötve. Ha a megvalósítások más hashelési sémát szeretnének választani,
szabadon megtehetik, de KÖTELESEK új fejlécjelzőt lefoglalni (mert két
különböző séma szerint készített hashek összehasonlítása értelmetlen lenne).

[[_commit_lookup_table]]
Commit-kikeresési tábla
-----------------------

Ha a BITMAP_OPT_LOOKUP_TABLE jelző be van állítva, a `.bitmap` fájl utolsó
`N * (4 + 8 + 4)` bájtja (a name-hash gyorsítótár és a lezáró hash előtt)
egy kikeresési táblát tartalmaz, amely megadja a kívánt bitmap
bejegyzésekből való megszerzéséhez szükséges információt, a korábbi
szükségtelen bitmapek feldolgozása nélkül.

Egy `nr_entries` elérhetőségi bitmapet tartalmazó `.bitmap` esetén a
táblázat `nr_entries` darab <commit_pos, offset, xor_row> hármas listáját
tartalmazza (a `commit_pos` növekvő sorrendjébe rendezve). Az i. hármas
tartalma -

	* {empty}
	commit_pos (4 bájtos egész szám, hálózati bájtsorrend): ::
	Egy commit objektumpozícióját tárolja (a midx- vagy pack-indexben).

	* {empty}
	offset (8 bájtos egész szám, hálózati bájtsorrend): ::
	Az az eltolás, amelytől az adott commit bitmapje olvasható.

	* {empty}
	xor_row (4 bájtos egész szám, hálózati bájtsorrend): ::
	Annak a hármasnak a pozíciója, amelynek a bitmapjét ennek a
	tömörítésére használják, vagy `0xffffffff`, ha nincs ilyen bitmap.

[[_pseudo_merge_bitmaps]]
Pseudo-merge bitmapek
---------------------

Ha a `BITMAP_OPT_PSEUDO_MERGES` jelző be van állítva, a `.bitmap` fájl
változó számú bájtja (a name-hash gyorsítótár, a commit-kikeresési tábla és
a lezáró ellenőrzőösszeg előtt) pseudo-merge bitmapek tárolására szolgál.

Arról, hogy mik a pseudo-merge-ek, miért hasznosak, és hogyan lehet őket
konfigurálni, lásd a linkgit:gitpacking[7] információit.

[[_file_format]]
=== Fájlformátum

Ha engedélyezve van, a pseudo-merge bitmapek egy `.bitmap` fájl végén lévő
opcionális szakaszban tárolódnak. A formátum a következő:

....
+-------------------------------------------+
|               .bitmap File                |
+-------------------------------------------+
|                                           |
|  Pseudo-merge bitmaps (Variable Length)   |
|  +---------------------------+            |
|  | commits_bitmap (EWAH)     |            |
|  +---------------------------+            |
|  | merge_bitmap (EWAH)       |            |
|  +---------------------------+            |
|                                           |
+-------------------------------------------+
|                                           |
|  Lookup Table                             |
|  +---------------------------+            |
|  | commit_pos (4 bytes)      |            |
|  +---------------------------+            |
|  | offset (8 bytes)          |            |
|  +------------+--------------+            |
|                                           |
|  Offset Cases:                            |
|  -------------                            |
|                                           |
|  1. MSB Unset: single pseudo-merge bitmap |
|     + offset to pseudo-merge bitmap       |
|                                           |
|  2. MSB Set: multiple pseudo-merges       |
|     + offset to extended lookup table     |
|                                           |
+-------------------------------------------+
|                                           |
|  Extended Lookup Table (Optional)         |
|  +----+----------+----------+----------+  |
|  | N  | Offset 1 |   ....   | Offset N |  |
|  +----+----------+----------+----------+  |
|  |    |  8 bytes |   ....   |  8 bytes |  |
|  +----+----------+----------+----------+  |
|                                           |
+-------------------------------------------+
|                                           |
|  Pseudo-merge position table              |
|  +----+----------+----------+----------+  |
|  | N  | Offset 1 |   ....   | Offset N |  |
|  +----+----------+----------+----------+  |
|  |    |  8 bytes |   ....   |  8 bytes |  |
|  +----+----------+----------+----------+  |
|                                           |
+-------------------------------------------+
|                                           |
|  Pseudo-merge Metadata                    |
|  +-----------------------------------+    |
|  | # pseudo-merges (4 bytes)         |    |
|  +-----------------------------------+    |
|  | # commits (4 bytes)               |    |
|  +-----------------------------------+    |
|  | Lookup offset (8 bytes)           |    |
|  +-----------------------------------+    |
|  | Extension size (8 bytes)          |    |
|  +-----------------------------------+    |
|                                           |
+-------------------------------------------+
....

* Egy vagy több pseudo-merge bitmap, mindegyik a következőket tartalmazza:

  ** `commits_bitmap`, egy EWAH-tömörített bitmap, amely leírja az ebbe a
     pseudo-merge-be tartozó commitok halmazát.

  ** `merge_bitmap`, egy EWAH-tömörített bitmap, amely leírja a
     `commits_bitmap`-ben felsorolt összes commitból elérhető objektumok
     halmazának unióját.

* Egy kikeresési tábla, amely a pseudo-merge-elt commitokat az őket
  tartalmazó pseudo-merge-ekhez rendeli. A bejegyzések az egyes commitok
  bitpozíciójának növekvő sorrendjében jelennek meg. Minden bejegyzés 12
  bájt széles, és a következőkből áll:

  ** `commit_pos`, egy 4 bájtos előjel nélküli érték (hálózati
     bájtsorrendben), amely ennek a commitnak a bitpozícióját tartalmazza.

  ** `offset`, egy 8 bájtos előjel nélküli érték (szintén hálózati
  bájtsorrendben), amely két lehetséges eltolás egyikét tartalmazza, attól
  függően, hogy a legmagasabb helyiértékű bit be van-e állítva.

    *** Ha nincs beállítva (azaz `offset & ((uint64_t)1<<63) == 0`), az az
	eltolás (a `.bitmap` fájl elejéhez viszonyítva), amelyen az ehhez a
	commithoz tartozó pseudo-merge bitmap olvasható. Ez azt jelzi, hogy
	csak egyetlen pseudo-merge bitmap tartalmazza ezt a commitot.

    *** Ha be van állítva (azaz `offset & ((uint64_t)1<<63) != 0`), az az
	eltolás (ismét a `.bitmap` fájl elejéhez viszonyítva), amelyen a
	kiterjesztett eltolástábla található, amely leírja az ezt a commitot
	tartalmazó pseudo-merge bitmapek halmazát. Ez azt jelzi, hogy több
	pseudo-merge bitmap tartalmazza ezt a commitot.

* Egy (opcionális) kiterjesztett kikeresési tábla (akkor és csak akkor
  íródik ki, ha van legalább egy commit, amely egynél több pseudo-merge-ben
  megjelenik). Annyi bejegyzés van, ahány commit több pseudo-merge-ben
  megjelenik. Minden bejegyzés a következőket tartalmazza:

  ** `N`, egy 4 bájtos előjel nélküli érték, amely megegyezik az adott
     commitot tartalmazó pseudo-merge-ek számával.

  ** `N` darab 8 bájtos előjel nélküli érték tömbje, amelyek mindegyike
     eltolásként értelmezendő (a `.bitmap` fájl elejéhez viszonyítva),
     amelyen az ehhez a commithoz tartozó pseudo-merge bitmap olvasható.
     Ezek az értékek nincsenek meghatározott sorrendben.

* Az összes pseudo-merge pozíciója, mindegyik egy 8 bájtos előjel nélküli
  értékként tárolva (hálózati bájtsorrendben), amely az egyes egymást
  követő pseudo-merge-ek eltolását (a `.bitmap` fájl elejéhez viszonyítva)
  tartalmazza.

* Egy 4 bájtos előjel nélküli érték (hálózati bájtsorrendben), amely
  megegyezik a pseudo-merge-ek számával.

* Egy 4 bájtos előjel nélküli érték (hálózati bájtsorrendben), amely
  megegyezik a bármely pseudo-merge-ben megjelenő egyedi commitok számával.

* Egy 8 bájtos előjel nélküli érték (hálózati bájtsorrendben), amely
  megegyezik a pseudo-merge szakasz kezdete és a kikeresési tábla kezdete
  közötti bájtok számával.

* Egy 8 bájtos előjel nélküli érték (hálózati bájtsorrendben), amely
  megegyezik a pseudo-merge szakasz bájtjainak számával (beleértve ezt a
  mezőt is).
