= Build rendszerek

A build rendszer az elsődleges módja annak, hogy a fejlesztők és a
rendszerintegrátorok is együttműködjenek a Git projekttel. Ezért az, hogy
könnyen használható és bővíthető legyen azok számára, akik nem közvetlenül
magát a Gitet fejlesztik, ugyanolyan fontos, mint a bármely lehetséges build
rendszerrel szemben támasztott többi követelményünk.

Ez a dokumentum felvázolja a build rendszerrel szemben támasztott különböző
követelményeinket, majd ezen kritériumok alapján összehasonlítja az elérhető
build rendszereket.

[[_requirements]]
== Követelmények

A következő alszakaszok bemutatják a bármely lehetséges build rendszerrel
szemben támasztott követelmények listáját. A szakaszok csökkenő prioritás
szerint rendezve.

[[_platform_support]]
=== Platformtámogatás

A build rendszernek támogatnia kell az összes olyan platformunkat, amelyekkel
szemben folyamatosan tesztelünk, ahogy azt a platformtámogatási
szabályzatunk körvonalazza. Ezek a platformok:

  - Linux
  - Windows
  - macOS

Továbbá a build rendszernek támogatnia kell a következő platformokat,
amelyekhez általában valaki rendszeresen futtat tesztfolyamatokat:

  - AIX
  - FreeBSD
  - NetBSD
  - NonStop
  - OpenBSD

Az eszköz által kötelezően támogatott platformoknak összhangban kell lenniük
a platformtámogatási szabályzatunkkal (lásd platform-support.adoc).
// once we lose AsciiDoc compatibility, we can start writing the above as:
// xref:platform-support.adoc#platform-support-policy[platform support policy]
// or something like that, but until then....

[[_auto_detection_of_supported_features]]
=== A támogatott funkciók automatikus felismerése

A build rendszernek támogatnia kell azon funkciók automatikus felismerését,
amelyek az aktuális platformon elérhetők vagy sem. A platform-maintainerektől
nem szabad megkövetelni a teljes build kézi konfigurálását.

A következő elemek automatikus felismerése fontosnak számít:

  - Fejlécek meglétének ellenőrzése.
  - Könyvtárak meglétének ellenőrzése.
  - Futtatható állományok meglétének ellenőrzése.
  - Bizonyos függvények futásidejű viselkedésének ellenőrzése.
  - Bizonyos linkelési sorrend-követelmények ellenőrzése, amikor több
    könyvtár érintett.

[[_ease_of_use]]
=== Egyszerű használat

A build rendszernek egyszerűen használhatónak és egyszerűen bővíthetőnek is
kell lennie. Bár ez természetesen szubjektív mérőszám, valószínűleg nem
vitatható, hogy egyes build rendszerek jelentősen nehezebben használhatók,
mint mások.

[[_ide_support]]
=== IDE-támogatás

A build rendszernek integrálódnia kell a jól ismert IDE-kkel. A jól ismert
IDE-k közé tartozik:

  - Microsoft Visual Studio
  - Visual Studio Code
  - Xcode

A támogatásnak négy szintje van:

  - Natív integráció az IDE-be.
  - Integráció az IDE-be egy bővítményen keresztül.
  - Integráció az IDE-be úgy, hogy a build rendszerrel projektleírást
    generálunk.
  - Nincs integráció.

A natív integráció előnyösebb, de a bővítményen keresztüli integráció vagy a
build rendszerrel generált projektleírás is elfogadható alternatívának
számít.

Egy másik fontos megkülönböztetés az integráció szintje. Két olyan funkció
van, amelyet az ember általában szeretne:

  - A build-célok integrációja.
  - Az olyan funkciók automatikus beállítása, mint a kódkiegészítés a
    felismert build-függőségekkel.

Az első pont a legszükségesebb minimum, de nem elegendő ahhoz, hogy megfelelő
integrációnak számítson.

[[_out_of_tree_builds]]
=== Fán kívüli buildek

A build rendszernek támogatnia kell a fán kívüli buildeket. A fán kívüli
buildek lehetővé teszik a fejlesztő számára, hogy több különböző
build-könyvtárat konfiguráljon eltérő konfigurációval, pl. egy "debug" és egy
"release" buildet.

[[_cross_platform_builds]]
=== Platformfüggetlen buildek

A build rendszernek támogatnia kell a platformfüggetlen buildeket, pl. arm-ra
való buildelést egy x86-64 hoszton.

[[_language_support]]
=== Nyelvi támogatás

A következő nyelvek és eszközláncok relevánsak, és a build rendszernek
támogatnia kell őket:

  - C: a Git által használt elsődleges fordított nyelv, kötelezően
    támogatandó. A releváns eszközláncok a GCC, a Clang és az MSVC.
  - Rust: jelölt második fordított nyelvként, támogatandó. A releváns
    eszközlánc az LLVM-alapú rustc.

A szóban forgó nyelvek beépített támogatása előnyösebb a kézzel bekötendő
támogatásnál, hogy elkerüljük a felesleges bonyolultságot. A natív támogatás
a következő funkciókat tartalmazza:

  - Objektumok fordítása.
  - Függőségkövetés.
  - Elérhető funkciók felismerése.
  - Releváns eszközláncok felderítése.
  - Könyvtárak és futtatható állományok linkelése.
  - Helyőrzők sablonozása a szkriptekben.

[[_test_integration]]
=== Tesztintegráció

Lehetővé kell tenni a tesztek integrálását a build rendszerbe úgy, hogy a Git
buildelése és tesztelése a build rendszeren belül lehetséges legyen. Jó lenne,
ha meglennének a következő funkciók:

  - Az egyes tesztek build-idejű függőségeinek követése. Az egységteszteknek
    más követelményeik vannak, mint az integrációs teszteknek.
  - A futtatandó tesztek szűrésének lehetővé tétele.
  - A tesztek olyan futtatásának lehetővé tétele, hogy az olyan segédeszközök,
    mint a `test_pause` vagy a `debug`, működjenek.

[[_comparison]]
== Összehasonlítás

A build rendszerek következő listáját vesszük figyelembe:

- GNU Make
- autoconf
- CMake
- Meson

[[_gnu_make]]
=== GNU Make

- Platformtámogatás: mindenütt jelen van minden platformon, de Windowsba nincs
  jól integrálva.
- Automatikus felismerés: nincs beépített támogatás a funkciók automatikus
  felismeréséhez.
- Egyszerű használat: könnyen használható, de az elérhető opciók felfedezése
  nehéz. A Makefile-szabályok gyorsan elszabadulhatnak, ha egy bizonyos
  méretet elérnek.
- IDE-támogatás: a Makefile-célok végrehajtását sok IDE támogatja
- Fán kívüli buildek: elméletben támogatott, a gyakorlatban nincs bekötve.
- Platformfüggetlen buildek: elméletben támogatott, a gyakorlatban nincs
  bekötve.
- Nyelvi támogatás:
  - C: korlátozott beépített támogatás, sok részt kézzel kell bekötni.
  - Rust: nincs beépített támogatás, kézzel kell bekötni.
- Tesztintegráció: részben támogatott, sok részt kézzel kell
  bekötni.

[[_autoconf]]
=== autoconf

- Platformtámogatás: mindenütt jelen van minden platformon, de Windowsba nincs
  jól integrálva.
- Automatikus felismerés: támogatott.
- Egyszerű használat: könnyen használható, az elérhető opciók felfedezése
  viszonylag egyszerű. Az autoconf szintaxisa azonban a bonyolultan
  egymásra ható fájlok halmaza és a nehezen érthető M4 nyelv miatt
  megengedhetetlenül nehezen bővíthető.
- IDE-támogatás: generáláskor nincs integráció az IDE-kbe. A generált
  Makefile-ok ugyanolyan szintű támogatással rendelkeznek, mint a GNU Make.
- Fán kívüli buildek: elméletben támogatott, a gyakorlatban nincs bekötve.
- Platformfüggetlen buildek: támogatott.
- Nyelvi támogatás:
  - C: korlátozott beépített támogatás, sok részt kézzel kell bekötni.
  - Rust: nincs beépített támogatás, kézzel kell bekötni.
- Tesztintegráció: részben támogatott, sok részt kézzel kell
  bekötni.

[[_cmake]]
=== CMake

- Platformtámogatás: nem olyan kiterjedt, mint a GNU Make vagy az autoconf, de
  minden fő platform támogatott.
  - AIX
  - Cygwin
  - FreeBSD
  - Linux
  - OpenBSD
  - Solaris
  - Windows
  - macOS
- Egyszerű használat: könnyen használható, az elérhető opciók felfedezése nem
  mindig triviális. A CMake által használt szkriptnyelv kissé nehézkesen
  használható, de a CMake build-utasítások bővítése megoldható.
- IDE-támogatás: natívan integrálva a Microsoft Visual Studióba. Xcode-hoz
  tud projektleírásokat generálni. A Visual Studio Code-hoz elérhető egy
  bővítmény. Sok más IDE-hez van CMake-bővítmény.
- Fán kívüli buildek: támogatott.
- Platformfüggetlen buildek: támogatott.
- Nyelvi támogatás:
  - C: támogatott GCC-hez, Clang-hez, MSVC-hez és más eszközláncokhoz.
  - Rust: nincs beépített támogatás, kézzel kell bekötni.
- Tesztintegráció: támogatott, bár a tesztfüggőségek kissé nehézkesen
  használhatók a "test fixtures"-ökön keresztül. Az interaktív tesztfuttatás
  nem támogatott.

[[_meson]]
=== Meson

- Platform: nem olyan kiterjedt, mint a GNU Make vagy az autoconf, de minden
  fő platform és néhány kisebb is támogatott.
  - AIX
  - Cygwin
  - DragonflyBSD
  - FreeBSD
  - Haiku
  - Linux
  - NetBSD
  - OpenBSD
  - Solaris
  - Windows
  - macOS
- Egyszerű használat: könnyen használható, az elérhető opciók felfedezése
  egyszerű. A szkriptnyelv egyértelműen használható.
- IDE-támogatás: támogatja a build-utasítások generálását Xcode-hoz és
  Microsoft Visual Studióhoz, a Visual Studio Code-hoz létezik bővítmény.
- Fán kívüli buildek: támogatott.
- Platformfüggetlen buildek: támogatott.
- Nyelvi támogatás:
  - C: támogatott GCC-hez, Clang-hez, MSVC-hez és más eszközláncokhoz.
  - Rust: támogatott rustc-hez.
- Tesztintegráció: támogatott. Az interaktív tesztek a Meson 1.5.0-tól
  támogatottak a `--interactive` jelzőn keresztül.
