Bundle URI-k
============

A Git bundle-ök olyan fájlok, amelyek egy pack-file-t tárolnak némi extra
metaadattal együtt, beleértve egy refkészletet és a szükséges commitok egy
(esetleg üres) készletét. További információért lásd a linkgit:git-bundle[1]
és a linkgit:gitformat-bundle[5] oldalt.

A bundle URI-k olyan helyek, ahonnan a Git egy vagy több bundle-t tud
letölteni, hogy előkészítse (bootstrap) az objektumadatbázist, mielőtt a
maradék objektumokat lekérné egy remote-ról.

Az egyik cél a klónozások és fetchek felgyorsítása azon felhasználók
számára, akiknek gyenge a hálózati kapcsolatuk az origin szerverhez. Egy
másik előny, hogy lehetővé teszi a nagy felhasználóknak, mint a CI
build-farmoknak, hogy a Git-adatok többségéhez helyi erőforrásokat
használjanak, és ezzel csökkentsék az origin szerver terhelését.

A bundle URI funkció engedélyezéséhez a felhasználók megadhatnak egy bundle
URI-t parancssori opciókkal, vagy az origin szerver hirdethet egy vagy több
URI-t egy protocol v2 képességen keresztül.

[[_design_goals]]
Tervezési célok
---------------

A bundle URI szabvány célja, hogy elég rugalmas legyen több munkaterhelés
kiszolgálásához. A bundle-szolgáltatónak és a Git kliensnek több választása
is van abban, hogyan hozzák létre és fogyasztják a bundle URI-kat.

* A bundle-ök bármilyen nevet kaphatnak, amilyet a szerver kíván. Ez a név
  hivatkozhat változatlan adatra a bundle tartalmának hashével. Ez azonban
  azt jelenti, hogy a tartalom minden frissítése után új URI-ra lesz
  szükség. Ez elfogadható lehet, ha a szerver hirdeti az URI-t (és a szerver
  tud az új bundle-ök generálásáról), de nem lenne ergonomikus a parancssori
  opciót használó felhasználók számára.

* A bundle-ök szervezhetők kifejezetten a teljes klónok előkészítéséhez, de
  szervezhetők az inkrementális fetchek előkészítésének szándékával is. A
  bundle-szolgáltatónak több szervezési séma közül kell választania, hogy
  minimalizálja a kliensletöltéseket az inkrementális fetchek során, de a
  Git kliens is választhat, hogy használ-e bundle-öket bármelyik művelethez.

* A bundle-szolgáltató választhat, hogy támogatja a teljes klónokat, a
  részleges klónokat, vagy mindkettőt. A kliens fel tudja ismerni, hogy mely
  bundle-ök felelnek meg a repository részleges klón szűrőjének, ha van
  ilyen.

* A bundle-szolgáltató használhat egyetlen bundle-t (csak klónokhoz), vagy
  bundle-ök listáját. Bundle-lista használatakor a szolgáltató megadhatja,
  hogy a kliensnek _minden_ bundle URI-ra szüksége van-e egy teljes
  klónhoz, vagy elég _bármelyik_ bundle URI. Ez lehetővé teszi a
  bundle-szolgáltató számára, hogy különböző URI-kat használjon a különböző
  földrajzi régiókhoz.

* A bundle-szolgáltató heurisztikákkal szervezheti a bundle-öket, mint
  például a létrehozási tokenekkel, hogy segítsen a kliensnek elkerülni a
  nem szükséges bundle-ök letöltését. Ha a bundle-szolgáltató nem nyújt
  ilyen heurisztikákat, a kliens optimalizációkat használhat, hogy
  minimalizálja a letöltött adatmennyiséget.

* A bundle-szolgáltatónak nem kell a Git szerverhez kötődnie. A kliens
  választhatja a bundle-szolgáltató használatát anélkül, hogy azt a Git
  szerver hirdetné.

* A kliens választhatja a Git szerver által hirdetett bundle-szolgáltatók
  felderítését. Ez történhet `git clone` során, `git fetch` során,
  mindkettő során, vagy egyik során sem. A felhasználó választhatja meg,
  melyik kombináció működik számára a legjobban.

* A kliens bármikor választhatja egy bundle-szolgáltató kézi konfigurálását.
  A kliens azt is választhatja, hogy egy bundle-szolgáltatót kézzel ad meg a
  `git clone` parancssori opciójaként.

Minden repository más, és minden Git szervernek más igényei vannak.
Remélhetőleg a bundle URI funkció elég rugalmas ahhoz, hogy minden igényt
kielégítsen. Ha nem, akkor a funkció kiterjeszthető a verziókezelési
mechanizmusán keresztül.

[[_server_requirements]]
Szerverkövetelmények
--------------------

A bundle-szerverek szerveroldali megvalósításához a Git protokoll semmilyen
más része nem szükséges. Ez lehetővé teszi a szerver-maintainerek számára,
hogy statikus tartalommegoldásokat, például CDN-eket használjanak a
bundle-fájlok kiszolgálására.

A bundle URI funkció jelenlegi hatókörében minden URI HTTP(S) URL kell
legyen, ahol a tartalmat egy helyi fájlba töltik le az adott URL-hez
intézett `GET` kéréssel. A szerver hitelesítési követelményeket is
tartalmazhat ezekhez a kérésekhez azzal a céllal, hogy a biztonságos
hozzáféréshez elindítsa a konfigurált credential helpert. (A jövőbeli
kiterjesztések használhatnának "file://" URI-kat vagy SSH URI-kat.)

Feltételezve a szervertől kapott `200 OK` választ, a Git megvizsgálja az
URL-en lévő tartalmat. Először a Git megpróbálja a fájlt 2-es vagy magasabb
verziójú bundle-fájlként feldolgozni. Ha a fájl nem bundle, akkor a fájlt
egyszerű szöveges fájlként dolgozza fel a Git config feldolgozójával. Az
ebben a config fájlban lévő kulcs-érték pároktól elvárt, hogy egy bundle
URI-lista leírását adják. Ha egyik feldolgozási kísérlet sem jár sikerrel,
akkor a Git hibát jelez a felhasználónak, hogy a bundle URI hibás adatot
szolgáltatott.

A szerver által szolgáltatott bármely más adat hibásnak számít.

[[_bundle_lists]]
Bundle-listák
-------------

A Git szerver `key=value` párok halmazával hirdethet bundle URI-kat. Egy
bundle URI kiszolgálhat egy egyszerű szöveges fájlt is a Git config
formátumban, amely ugyanezeket a `key=value` párokat tartalmazza. Mindkét
esetben ezt _bundle-listának_ tekintjük. A párok információt adnak meg a
bundle-ökről, amelyeket a kliens felhasználhat annak eldöntésére, hogy mely
bundle-öket töltse le, és melyeket hagyja figyelmen kívül.

Néhány kulcs magának a listának a tulajdonságaira összpontosít.

bundle.version::
	(Kötelező) Ez az érték egy verziószámot ad meg a bundle-listához.
	Ha egy jövőbeli Git-változtatás olyan funkciót engedélyez, amelyhez
	a Git kliensnek reagálnia kell egy új kulcsra a bundle-lista
	fájlban, akkor ez a verzió növekszik. Az egyetlen jelenlegi
	verziószám az 1, és ha bármilyen más értéket adnak meg, akkor a Git
	nem fogja tudni használni ezt a fájlt.

bundle.mode::
	(Kötelező) Ennek az értéknek két értéke egyike lehet: `all` és
	`any`. Ha `all` van megadva, akkor a kliensnek arra kell
	számítania, hogy szüksége lesz az összes felsorolt bundle URI-ra,
	amely megfelel a repository-ja követelményeinek. Ha `any` van
	megadva, akkor a kliensnek arra kell számítania, hogy a repository-ja
	követelményeinek megfelelő bundle URI-k bármelyike elegendő lesz.
	Jellemzően az `any` opciót arra használják, hogy különböző földrajzi
	régiókban elhelyezkedő, több különböző bundle-szervert soroljanak fel.

bundle.heuristic::
	Ha ez a sztringértékű kulcs létezik, akkor a bundle-lista úgy van
	tervezve, hogy jól működjön az inkrementális `git fetch`
	parancsokkal. A heurisztika azt jelzi, hogy minden bundle-höz
	elérhetők további kulcsok, amelyek segítenek meghatározni, hogy a
	kliensnek a bundle-ök mely részhalmazát kell letöltenie. Az egyetlen
	jelenleg tervezett heurisztika a `creationToken`.

A többi kulcs tartalmaz egy `<id>` szegmenst, amely minden elérhető
bundle-höz egy szerver által kijelölt név. Az `<id>` csak alfanumerikus és
`-` karaktereket tartalmazhat.

bundle.<id>.uri::
	(Kötelező) Ez a sztringérték az `<id>` bundle letöltésének URI-ja.
	Ha az URI protokollal kezdődik (`http://` vagy `https://`), akkor az
	URI abszolút. Egyébként az URI a bundle-listához használt URI-hoz
	viszonyítva értelmezendő. Ha az URI `/`-rel kezdődik, akkor az a
	relatív útvonal a bundle-listához használt domainnévhez viszonyított.
	(A relatív útvonalak ezen használatának célja, hogy megkönnyítse egy
	bundle-készlet elosztását nagyszámú, eltérő domainnevű szerver vagy
	CDN között.)

bundle.<id>.filter::
	Ez a sztringérték egy objektumszűrőt jelöl, amelynek ennek a
	bundle-nek a fejlécében is meg kell jelennie. A szerver ezt az
	értéket használja a különböző fajta bundle-ök megkülönböztetésére,
	amelyek közül a kliens kiválaszthatja azokat, amelyek megfelelnek az
	objektumszűrőinek.

bundle.<id>.creationToken::
	Ez az érték egy nemnegatív 64 bites egész szám, amelyet a
	bundle-lista rendezésére használnak. Ezt a bundle-ök egy
	részhalmazának letöltésére használják egy fetch során, amikor
	`bundle.heuristic=creationToken`.

bundle.<id>.location::
	Ez a sztringérték egy valós helyet hirdet, ahonnan a bundle URI-t
	kiszolgálják. Ez felhasználható arra, hogy a felhasználónak
	választási lehetőséget kínáljon arról, melyik bundle URI-t használja,
	vagy egyszerűen informatív jelzésként arról, melyik bundle URI-t
	választotta a Git. Ez csak akkor értékes, ha a `bundle.mode` értéke
	`any`.

Íme egy példa bundle-lista a Git config formátumban:

	[bundle]
		version = 1
		mode = all
		heuristic = creationToken

	[bundle "2022-02-09-1644442601-daily"]
		uri = https://bundles.example.com/git/git/2022-02-09-1644442601-daily.bundle
		creationToken = 1644442601

	[bundle "2022-02-02-1643842562"]
		uri = https://bundles.example.com/git/git/2022-02-02-1643842562.bundle
		creationToken = 1643842562

	[bundle "2022-02-09-1644442631-daily-blobless"]
		uri = 2022-02-09-1644442631-daily-blobless.bundle
		creationToken = 1644442631
		filter = blob:none

	[bundle "2022-02-02-1643842568-blobless"]
		uri = /git/git/2022-02-02-1643842568-blobless.bundle
		creationToken = 1643842568
		filter = blob:none

Ez a példa a `bundle.mode=all`-t használja, csakúgy, mint a
`bundle.<id>.creationToken` heurisztikát. A `bundle.<id>.filter` opciókat is
használja arra, hogy két párhuzamos bundle-készletet mutasson be: egyet a
teljes klónokhoz, egy másikat a blob nélküli részleges klónokhoz.

Tegyük fel, hogy ez a bundle-lista a
`https://bundles.example.com/git/git/` URI-n volt megtalálható, így a két
blob nélküli bundle a következő, teljesen kifejtett URI-kkal rendelkezik:

* `https://bundles.example.com/git/git/2022-02-09-1644442631-daily-blobless.bundle`
* `https://bundles.example.com/git/git/2022-02-02-1643842568-blobless.bundle`

[[_advertising_bundle_uris]]
Bundle URI-k hirdetése
----------------------

Ha egy felhasználó ismer egy bundle URI-t a repository-hoz, amelyet klónoz,
akkor kézzel megadhatja azt az URI-t egy parancssori opción keresztül. Egy
Git-tárhely azonban hirdethet bundle URI-kat a klónozási művelet során,
segítve a funkciót nem ismerő felhasználókat.

Az egyetlen dolog, ami ehhez a funkcióhoz szükséges, hogy a szerver
hirdethessen egy vagy több bundle URI-t. Ez a hirdetés egy új, kifejezetten
a bundle URI-k felderítésére szolgáló protocol v2 képesség formáját ölti.

A kliens választhat egy tetszőleges bundle URI-t opcióként, _vagy_
kiválaszthatja a legjobb teljesítményű URI-t néhány felderítő ellenőrzéssel.
A bundle-szolgáltatóra van bízva annak eldöntése, hogy több URI előnyösebb-e
egyetlen URI-nál, amelyet szerveroldali infrastruktúrán keresztül
geodisztribuálnak.

[[_cloning_with_bundle_uris]]
Klónozás bundle URI-kkal
------------------------

A bundle URI-k elsődleges célja a klónozások felgyorsítása. A Git kliens a
következő folyamat szerint lép kapcsolatba a bundle URI-kkal:

1. A felhasználó megad egy bundle URI-t a `--bundle-uri` parancssori
   opcióval, _vagy_ a kliens felderít egy, a Git szerver által hirdetett
   bundle-listát.

2. Ha egy bundle URI-ról letöltött adat egy bundle, akkor a kliens
   megvizsgálja a bundle fejléceit, hogy ellenőrizze, az előfeltétel
   commit-OID-k jelen vannak-e a kliens repository-jában. Ha néhány
   hiányzik, akkor a kliens elhalasztja a kicsomagolást, amíg más
   bundle-öket ki nem csomagolt, jelenlévővé téve azokat az OID-kat. Amikor
   az összes szükséges OID jelen van, a kliens kicsomagolja azt az adatot
   egy refspec használatával. A használt refspec a
   `+refs/*:refs/bundles/*`. Ezeket a refeket eltárolja, hogy a későbbi
   `git fetch` egyeztetések minden bundle-ből származó refet `have`-ként
   közölhessenek, csökkentve a fetch méretét a Git protokollon keresztül.
   Hogy a refek metszése ebből a ref-névtérből lehetséges legyen, a Git
   bevezethet egy számozott névteret (mint a `refs/bundles/<i>/*`), hogy az
   elavult bundle-refek törölhetők legyenek.

3. Ha a fájl ehelyett egy bundle-lista, akkor a kliens megvizsgálja a
   `bundle.mode`-ot, hogy lássa, a lista az `all` vagy az `any` formájú-e.

   a. Ha `bundle.mode=all`, akkor a kliens az összes bundle URI-t
      figyelembe veszi. A lista lecsökken a kliens repository részleges
      klón szűrőjének megfelelő `bundle.<id>.filter` opciók alapján. Ezután
      az összes bundle URI-t lekéri. Ha a `bundle.<id>.creationToken`
      heurisztika meg van adva, akkor a bundle-öket a létrehozási token
      szerint csökkenő sorrendben tölti le, megállva, amikor egy bundle-nek
      megvan az összes szükséges OID-je. A bundle-ök ezután növekvő
      létrehozásitoken-sorrendben csomagolhatók ki. A kliens eltárolja a
      legutóbbi létrehozási tokent heurisztikaként, hogy elkerülje a
      jövőbeli letöltéseket, ha a bundle-lista nem hirdet nagyobb
      létrehozási tokennel rendelkező bundle-öket.

   b. Ha `bundle.mode=any`, akkor a kliens a bundle URI-k bármelyikét
      választhatja megvizsgálásra. A kliens sokféle módon választhat ezen
      URI-k közül. A kliens vissza is válthat egy másik URI-ra, ha a
      kezdeti választás nem ad eredményt.

Vedd figyelembe, hogy egy klónozás során arra számítunk, hogy az összes
bundle-re szükség lesz, és az olyan heurisztikák, mint a
`bundle.<uri>.creationToken`, használhatók a bundle-ök kronológiai
sorrendben vagy párhuzamosan való letöltésére.

Ha egy adott bundle URI egy `bundle.heuristic` értékkel rendelkező
bundle-lista, akkor a kliens választhatja, hogy azt az URI-t elmenti a
kiválasztott bundle URI-jaként. A kliens ezután a későbbi `git fetch`
hívások során közvetlenül arra az URI-ra navigálhat.

Bundle URI-k letöltésekor a kliens választhatja a kezdeti tartalom
megvizsgálását, mielőtt elkötelezné magát a teljes tartalom letöltése
mellett. Ez elég információt nyújthat annak megállapításához, hogy az URI
bundle-lista-e vagy bundle. Bundle esetén a kliens megvizsgálhatja a bundle
fejlécét annak megállapításához, hogy az összes hirdetett csúcs már jelen
van a kliens repository-jában, és megszakíthatja a hátralévő letöltést.

[[_fetching_with_bundle_uris]]
Fetchelés bundle URI-kkal
-------------------------

Amikor a kliens új adatot fetchel, dönthet úgy, hogy a bundle-szerverekről
fetchel, mielőtt az origin remote-ról fetchelne. Ez megtehető egy
parancssori opcióval, de valószínűleg hasznosabb egy config-értéket
használni, mint amilyet a klónozás során megadtak.

A fetch művelet ugyanazt az eljárást követi a bundle-ök bundle-listáról való
letöltéséhez (bár itt _nem_ akarunk párhuzamos letöltéseket használni).
Arra számítunk, hogy a folyamat akkor ér véget, amikor egy thin bundle-ben
lévő összes előfeltétel commit-OID már az objektumadatbázisban van.

A `creationToken` heurisztika használatakor a kliens elkerülheti bármely
bundle letöltését, ha a létrehozási tokenjeik nem nagyobbak a tárolt
létrehozási tokennél. Új bundle-ök fetchelése után a Git frissíti ezt a
helyi létrehozási tokent.

Ha a bundle-szolgáltató nem nyújt heurisztikát, akkor a kliensnek meg
kellene próbálnia megvizsgálni a bundle fejléceit, mielőtt letöltené a
teljes bundle-adatot, arra az esetre, ha a bundle csúcsai már léteznek a
kliens repository-jában.

[[_error_conditions]]
Hibafeltételek
--------------

Ha a Git kliens valami váratlant fedez fel, miközben egy bundle URI vagy az
azon a helyen található bundle-lista szerint tölt le információt, akkor a
Git figyelmen kívül hagyhatja azt az adatot, és folytathatja, mintha nem
kapott volna bundle URI-t. A távoli Git szerver a végső igazságforrás, nem
a bundle URI.

Íme néhány példa hibafeltételre:

* A kliensnek nem sikerül kapcsolódnia egy szerverhez az adott URI-n, vagy
  egy kapcsolat elveszik minden helyreállítási esély nélkül.

* A kliens 400-as szintű választ kap (mint a `404 Not Found` vagy a
  `401 Not Authorized`). A kliensnek a credential helpert kellene
  használnia, hogy megtaláljon és megadjon egy credentialt az URI-hoz, de
  a konkrét 400-as szintű hibák kezelésében kövesse a Git többi
  HTTP-protokolljának szemantikáját.

* A szerver bármilyen más hibaválaszt jelent.

* A kliens olyan adatot kap, amely nem dolgozható fel bundle-ként vagy
  bundle-listaként.

* Egy bundle olyan szűrőt tartalmaz, amely nem felel meg az elvárásoknak.

* A kliens nem tudja kicsomagolni a bundle-öket, mert az előfeltétel
  commit-OID-k nincsenek az objektumadatbázisban, és nincs több letölthető
  bundle.

Vannak olyan helyzetek is, amelyek pazarlónak tűnhetnek, de nem
hibafeltételek:

* A letöltött bundle-ök több információt tartalmaznak, mint amennyit a klón-
  vagy fetch-kérés kér. Egy elsődleges példa, ha a felhasználó
  `--single-branch`-csel kér klónozást, de olyan bundle-öket tölt le,
  amelyek minden elérhető commitot tárolnak az összes `refs/heads/*`
  referenciából. Ez kezdetben pazarló lehet, de talán ezek az objektumok
  elérhetővé válnak egy későbbi ref-frissítéssel, amely érdekli a klienst.

* Egy bundle letöltése egy `git fetch` során olyan objektumokat tartalmaz,
  amelyek már az objektumadatbázisban vannak. Ez valószínűleg
  elkerülhetetlen, ha bundle-öket használunk a fetchekhez, mivel a kliens
  szinte mindig kicsit a bundle-szerverek előtt jár, miután elvégezte a
  „behozó" fetchét a távoli szerverhez. Ez az extra munka akkor a
  legpazarlóbb, amikor a kliens sokkal gyakrabban fetchel, mint ahogy a
  szerver bundle-öket számít ki, például ha a kliens óránkénti
  előfetcheléseket használ háttérkarbantartással, de a szerver hetente
  számít ki bundle-öket. Ezért a kliensnek nem szabadna bundle URI-kat
  használnia fetcheléshez, hacsak a szerver kifejezetten nem ajánlotta egy
  `bundle.heuristic` értéken keresztül.

[[_example_bundle_provider_organization]]
Példa bundle-szolgáltatói szervezésre
-------------------------------------

A bundle URI funkciót szándékosan úgy tervezték, hogy rugalmas legyen a
különböző módokhoz, ahogyan egy bundle-szolgáltató szervezni akarja az
objektumadatokat. Hasznos lehet azonban, ha van itt egy teljes szervezési
modell leírva, hogy a szolgáltatók abból az alapból indulhassanak ki.

Ez a példa-szervezés egy egyszerűsített modellje annak, amit a GVFS Cache
Serverek használnak (lásd a szakaszt a dokumentum vége felé), amelyek
hasznosnak bizonyultak a klónozások és fetchek felgyorsításában nagyon nagy
repository-k esetén, bár a Giten kívüli extra szoftvert használnak.

A bundle-szolgáltató több földrajzi régióban telepít szervereket. Minden
szerver a saját bundle-készletét kezeli. A szerver számos Git repository-t
követhet, de mindegyikhez egy minta alapján ad bundle-listát. Például egy
`https://<domain>/<org>/<repo>` címen lévő repository tükrözésekor a
bundle-szerver bundle-listája a
`https://<server-url>/<domain>/<org>/<repo>` címen lehet elérhető. Az origin
Git szerver az összes ilyen szervert felsorolhatja az „any" módban:

	[bundle]
		version = 1
		mode = any

	[bundle "eastus"]
		uri = https://eastus.example.com/<domain>/<org>/<repo>

	[bundle "europe"]
		uri = https://europe.example.com/<domain>/<org>/<repo>

	[bundle "apac"]
		uri = https://apac.example.com/<domain>/<org>/<repo>

Ez a „listák listája" statikus, és csak akkor változik, ha egy
bundle-szervert hozzáadnak vagy eltávolítanak.

Minden bundle-szerver a saját bundle-készletét kezeli. A kezdeti
bundle-lista csak egyetlen bundle-t tartalmaz, amelyben az összes objektum
benne van, amelyet a repository origin szerverről való klónozásából kaptak.
A lista a `creationToken` heurisztikát használja, és a bundle-höz a szerver
időbélyege alapján készül egy `creationToken`.

A bundle-szerver rendszeresen ütemezett frissítéseket futtat a
bundle-listához, például naponta egyszer. E feladat során a szerver
lekéri a legfrissebb tartalmat az origin szerverről, és generál egy
bundle-t, amely a legfrissebb origin refekből elérhető objektumokat
tartalmazza, de amelyek nincsenek benne egy korábban kiszámított
bundle-ben. Ez a bundle bekerül a listába, ügyelve arra, hogy a
`creationToken` szigorúan nagyobb legyen a korábbi maximális
`creationToken`-nél.

Amikor a bundle-lista túl nagyra nő, mondjuk 30 bundle-nél többre, akkor a
legrégebbi „_N_ mínusz 30" bundle-t egyetlen bundle-be vonják össze. Ennek
a bundle-nek a `creationToken`-je egyenlő az összevont bundle-ök közötti
maximális `creationToken`-nel.

Íme egy példa bundle-lista, bár csak két napi bundle-je van, nem egy teljes,
30 elemű lista:

	[bundle]
		version = 1
		mode = all
		heuristic = creationToken

	[bundle "2022-02-13-1644770820-daily"]
		uri = https://eastus.example.com/<domain>/<org>/<repo>/2022-02-09-1644770820-daily.bundle
		creationToken = 1644770820

	[bundle "2022-02-09-1644442601-daily"]
		uri = https://eastus.example.com/<domain>/<org>/<repo>/2022-02-09-1644442601-daily.bundle
		creationToken = 1644442601

	[bundle "2022-02-02-1643842562"]
		uri = https://eastus.example.com/<domain>/<org>/<repo>/2022-02-02-1643842562.bundle
		creationToken = 1643842562

Hogy elkerülje az objektumadatok örökös tárolását és kiszolgálását annak
ellenére, hogy az origin szerveren elérhetetlenné válnak, ez a
bundle-összevonás körültekintőbb lehet. Ahelyett, hogy a régi bundle-ök
abszolút unióját venné, a bundle úgy is létrehozható, hogy megnézzük az
újabb bundle-öket, és biztosítjuk, hogy a szükséges commitjaik mind
elérhetők ebben az összevont bundle-ben (vagy az újabb bundle-ök egy
másikában). Ez lehetővé teszi az olyan objektumadatok „lejáratását",
amelyeket nem használnak új commitok ebben az időablakban. Azt az adatot
egy későbbi push újra bevezetheti.

Ennek az adatszervezésnek a szándéka két fő célt szolgál. Először: a
repository kezdeti klónjai gyorsabbá válnak azzal, hogy előre kiszámított
objektumadatokat töltenek le egy közelebbi forrásból. Másodszor: a
`git fetch` parancsok gyorsabbak lehetnek, különösen ha a kliens néhány
napja nem fetchelt. Ha azonban egy kliens 30 napig nem fetchel, akkor a
bundle-lista szervezése nagy mennyiségű objektumadat újraletöltését okozná.

Az egyik mód, hogy ez a szervezés hasznosabb legyen a gyakran fetchelő
felhasználók számára, a gyakoribb bundle-létrehozás. Például bundle-ök
készülhetnének óránként, majd naponta egyszer ezeket az „óránkénti"
bundle-öket egy „napi" bundle-be lehetne összevonni. A napi bundle-öket 30
nap után a legrégebbi bundle-be vonják össze.

Ajánlott, hogy ezt a bundle-stratégiát megismételjék a `blob:none`
szűrővel, ha ennek a repository-nak a kliensei blob nélküli részleges
klónokat várnak használni. Ez a blob nélküli bundle-ök listája ugyanabban a
listában marad, mint a teljes bundle-ök, de a `bundle.<id>.filter` kulcsot
használja a két csoport elkülönítésére. Nagyon nagy repository-k esetén a
bundle-szolgáltató választhatja, hogy _csak_ blob nélküli bundle-öket
nyújt.

[[_implementation_plan]]
Megvalósítási terv
------------------

Ezt a tervdokumentumot önmagában, aspirációs dokumentumként nyújtjuk be,
azzal a céllal, hogy az összes említett kliensfunkciót több patch-sorozat
folyamán megvalósítsuk. Íme egy lehetséges vázlat ezeknek a funkcióknak a
beküldésére:

1. A bundle URI-k integrálása a `git clone`-ba egy `--bundle-uri` opcióval.
   Ez tartalmazni fog egy új `git fetch --bundle-uri` módot, amelyet a
   `git clone` alatti megvalósításként használunk. A kezdeti verzió itt egy
   egyetlen bundle-t vár az adott URI-n.

2. A bundle-lista bundle URI-ból való feldolgozásának megvalósítása, és a
   `git fetch --bundle-uri` logika frissítése, hogy megfelelően
   megkülönböztesse a `bundle.mode` opciókat. A funkciót kifejezetten úgy
   tervezd meg, hogy a config-formátum feldolgozása kulcs-érték párok
   listáját táplálja a bundle-lista logikába.

3. A `bundle-uri` protocol v2 parancs létrehozása, hogy a Git szerverek
   hirdethessenek bundle URI-kat a kulcs-érték párok használatával.
   Csatlakoztasd a meglévő kulcs-érték bemenethez a bundle-lista logikában.
   Tedd lehetővé, hogy a `git clone` felderítse ezeket a bundle URI-kat, és
   előkészítse a kliens repository-t a bundle-adatokból. (Ez a választás
   opcionális egy config-opción és egy parancssori opción keresztül.)

4. Tedd lehetővé, hogy a kliens megértse a `bundle.heuristic` konfigurációs
   kulcsot és a `bundle.<id>.creationToken` heurisztikát. Amikor a
   `git clone` felderít egy `bundle.heuristic`-kal rendelkező bundle URI-t,
   úgy konfigurálja a kliens repository-t, hogy ellenőrizze azt a bundle
   URI-t a későbbi `git fetch <remote>` parancsok során.

5. Tedd lehetővé, hogy a kliensek felderítsenek bundle URI-kat egy
   `git fetch` során, és konfiguráljanak egy bundle URI-t a későbbi
   fetchekhez, ha a `bundle.heuristic` be van állítva.

6. A „fejlécek megvizsgálása" heurisztika megvalósítása az adatletöltések
   csökkentésére, amikor a `bundle.<id>.creationToken` heurisztika nem
   elérhető.

Ahogy ezeket a funkciókat áttekintik, ez a terv frissülhet. Arra is
számítunk, hogy új terveket fedezünk fel és valósítunk meg, ahogy ez a
funkció beérik, és valós forgatókönyvekben használják.

[[_related_work_packfile_uris]]
Kapcsolódó munka: Packfile URI-k
--------------------------------

A Git protokollnak már van egy képessége, amellyel a Git szerver egy kliens
kérésének kiszolgálásakor felsorolhat egy URL-készletet a packfile-válasz
mellett. Ekkor a kliensnek le kell töltenie a packfile-okat azokról a
helyekről, hogy teljes képet kapjon a válaszról.

Ezt a mechanizmust a Gerrit szerver használja (JGittel megvalósítva), és
hatékonynak bizonyult a CPU-terhelés csökkentésében és a felhasználói
teljesítmény javításában a klónozásoknál.

E mechanizmus egy fő hátránya, hogy az origin szervernek _pontosan_ tudnia
kell, mi van azokban a packfile-okban, és a packfile-oknak elérhetőnek kell
lenniük a felhasználó számára egy ideig azután, hogy a szerver válaszolt. Ez
a csatolás az origin és a packfile-adat között nehezen kezelhető.

Továbbá ezt a megvalósítást rendkívül nehéz működésre bírni fetchekkel.

[[_related_work_gvfs_cache_servers]]
Kapcsolódó munka: GVFS Cache Serverek
-------------------------------------

A GVFS Protocol [2] HTTP-végpontok halmaza, amelyet a Git projekttől
függetlenül terveztek, mielőtt a Git partial clone-ja létrejött volna. E
protokoll egyik funkciója a „cache server" ötlete, amely a build-gépekkel
vagy fejlesztői irodákkal egy helyre telepíthető, hogy Git-adatokat vigyen
át a központi szerver túlterhelése nélkül.

A végpont, amelyről a VFS for Git híres, a `GET /gvfs/objects/{oid}`
végpont, amely lehetővé teszi egy objektum igény szerinti letöltését. Ez a
termék fájlrendszer-virtualizációjának kritikus darabja.

Egy finomabb szükséglet azonban a `GET /gvfs/prefetch?lastPackTimestamp=<t>`
végpont. Egy opcionális időbélyeget megadva a cache server olyan, előre
kiszámított packfile-ok listájával válaszol, amelyek az azokban az
időintervallumokban bevezetett commitokat és tree-ket tartalmazzák.

A cache server ezeket az „előfetch" packfile-okat a következő stratégiával
számítja ki:

1. Óránként egy „óránkénti" packet generál egy adott időbélyeggel.
2. Éjszakánként az előző 24 óránkénti packet egy „napi" packbe vonja össze.
3. Éjszakánként az összes, 30 napnál régebbi előfetch packet egy packbe
   vonja össze.

Amikor egy felhasználó `gvfs clone`-t vagy `scalar clone`-t futtat egy
cache serverekkel rendelkező repóval szemben, a kliens az összes előfetch
packfile-t lekéri, ami legfeljebb `24 + 30 + 1` packfile, csak commitokat és
tree-ket letöltve. A kliens ezután egy kéréssel fordul az origin szerverhez
a referenciákért, és megpróbálja checkoutolni azt a csúcsreferenciát. (Van
egy extra végpont, amely segít az összes elérhető tree megszerzésében egy
adott commitból, arra az esetre, ha az a commit nem volt már benne egy
előfetch packfile-ban.)

Egy `git fetch` során egy hook lekéri az előfetch végpontot egy korábban
letöltött előfetch packfile legfrissebb időbélyegét használva. Csak a
későbbi időbélyegű packfile-ok listáját tölti le. A legtöbb felhasználó
óránként fetchel, így legfeljebb egy óránkénti előfetch packet kap. Azok a
felhasználók, akiknek a gépe ki volt kapcsolva, vagy egyébként 30 napnál
tovább nem fetcheltek, esetleg újraletölthetik az összes előfetch
packfile-t. Ez ritka.

Fontos megjegyezni, hogy a kliensek mindig kapcsolatba lépnek az origin
szerverrel a refhirdetésért, így a refek gyakran a lehívott
pack-adat „előtt" járnak. A hiányzó objektumokat igény szerint töltik le a
`GET gvfs/objects/{oid}` kérésekkel, amikor egy olyan parancsnak van rá
szüksége, mint a
`git checkout` vagy a `git log`. Néhány Git-optimalizáció letilt olyan
ellenőrzéseket, amelyek túl agresszívvá tennék ezeket az igény szerinti
letöltéseket.

[[_see_also]]
See Also
--------

[1] https://lore.kernel.org/git/RFC-cover-00.13-0000000000-20210805T150534Z-avarab@gmail.com/
    Egy korábbi RFC a bundle URI funkcióhoz.

[2] https://github.com/microsoft/VFSForGit/blob/master/Protocol.md
    A GVFS Protocol
