A Git commit-graph tervezési jegyzetei
======================================

A Git sok okból bejárja a commit gráfot, többek között:

1. A commit-előzmények listázása és szűrése.
2. Merge-alapok kiszámítása.

Ezek a műveletek lassúvá válhatnak, ahogy a commitok száma nő. A merge-alap
kiszámítása sok felhasználó felé néző parancsban felbukkan, például a 'merge-base'
vagy a 'status' parancsban, és az előzmények alakjától függően percekig is eltarthat.

Itt két fő költség van:

1. A commitok kicsomagolása és elemzése.
2. A teljes gráf bejárása a topologikus sorrendi megkötések teljesítéséhez.

A commit-graph fájl egy kiegészítő adatszerkezet, amely felgyorsítja a
commit gráf bejárásait. Ha egy felhasználó visszavált egy régebbi verzióra, vagy kikapcsolja a 'core.commitGraph'
konfigurációs beállítást, akkor a meglévő objektumadatbázis elegendő. A fájl "commit-graph"
néven van tárolva vagy a .git/objects/info könyvtárban, vagy egy alternate info
könyvtárában.

A commit-graph fájl a commit gráf szerkezetét tárolja némi
extra metaadattal együtt, hogy felgyorsítsa a gráfbejárásokat. Azzal, hogy a commit-OID-kat
lexikografikus sorrendben soroljuk fel, minden committhoz azonosítani tudunk egy egész számú pozíciót,
és egy commit szülőire ezekkel az egész számú pozíciókkal hivatkozhatunk. A
kezdeti commitok megkereséséhez bináris keresést használunk, majd a bejárás során az egész számú
pozíciókkal végzünk gyors kereséseket.

Egy fogyasztó a következő információkat töltheti be a gráfból egy committhoz:

1. A commit OID-ja.
2. A szülők listája az egész számú pozíciójukkal együtt.
3. A commit dátuma.
4. A gyökér tree OID-ja.
5. A generációs szám (lásd a definíciót lentebb).

Az 1-4. értékek kielégítik a parse_commit_gently() követelményeit.

A generációs számnak két definíciója van:

1. Korrigált committer dátumok (generációs szám v2)
2. Topologikus szintek (generációs szám v1)

Egy commit „korrigált committer dátumát" rekurzívan a következőképpen definiáljuk:

 * Egy szülő nélküli commit (gyökércommit) korrigált committer dátuma
    megegyezik a committer dátumával.

 * Egy legalább egy szülővel rendelkező commit korrigált committer dátuma
    a committer dátumának és a szülői közötti legnagyobb korrigált
    committer dátumnál eggyel nagyobb értéknek a maximuma.

 * Speciális esetként a nulla időbélyegű gyökércommit korrigált commit-
    dátuma 1, hogy megkülönböztethető legyen a GENERATION_NUMBER_ZERO
    értéktől (vagyis egy ki nem számított korrigált commit-dátumtól).

Egy commit „topologikus szintjét" rekurzívan a következőképpen definiáljuk:

 * Egy szülő nélküli commit (gyökércommit) topologikus szintje egy.

 * Egy legalább egy szülővel rendelkező commit topologikus szintje eggyel nagyobb,
   mint a szülői közötti legnagyobb topologikus szint.

Ezzel egyenértékűen egy A commit topologikus szintje eggyel nagyobb, mint az
A committól egy gyökércommithoz vezető leghosszabb út hossza. A rekurzív definíció
egyszerűbben használható a számításhoz és a következő tulajdonság megfigyeléséhez:

    Ha A és B olyan commitok, amelyek generációs száma rendre N és M,
    és N <= M, akkor A nem éri el B-t. Vagyis keresés nélkül tudjuk,
    hogy B nem felmenője A-nak, mert messzebb van egy gyökércommittól,
    mint A.

    Fordítva, amikor azt ellenőrizzük, hogy A felmenője-e B-nek, csak
    addig kell bejárnunk a commitokat, amíg a bejárás határán lévő összes commit
    generációs száma legfeljebb N. Ha a commitokat generációs számokkal
    beültetett prioritási sorral járjuk be, akkor mindig a legmagasabb generációs
    számú határcommitot bővítjük, és könnyen felismerjük a megállási feltételt.

A tulajdonság a generációs szám mindkét változatára érvényes, vagyis a
korrigált committer dátumokra és a topologikus szintekre is.

Ezzel a tulajdonsággal jelentősen csökkenthető a commitok bejárásához és a
topologikus kapcsolatok meghatározásához szükséges idő. Generációs számok
nélkül az általános heurisztika a következő:

    Ha A és B olyan commitok, amelyek commit-ideje rendre X és Y, és
    X < Y, akkor A _valószínűleg_ nem éri el B-t.

Korrigált commit-dátumok hiányában (például régi Git-verziók vagy
vegyes generációjú gráfláncok esetén)
ezt a heurisztikát jelenleg mindig használjuk, amikor a számítás
óracsúszás miatt megsértheti a topologikus kapcsolatokat (például az alapértelmezett
sorrendű "git log" esetén), de nem használjuk, amikor a topologikus sorrend
kötelező (például merge-alap-számításoknál, "git log --graph" esetén).

A gyakorlatban arra számítunk, hogy néhány commit nemrég jött létre, és nincs
eltárolva a commit-graphban. Ezeket a commitokat „végtelen" generációs számúaknak
tekinthetjük, és addig járunk be, amíg ismert generációs számú commitokhoz nem
érünk.

A commit-graph fájlban nem szereplő commitok jelölésére a
GENERATION_NUMBER_INFINITY makrót használjuk. Ha egy commit-graph fájlt a Git olyan
verziója írt, amely nem számított generációs számokat, akkor azok a commitok
generációs számát a GENERATION_NUMBER_ZERO = 0 makró képviseli.

Mivel a commit-graph fájl elérhetőségre nézve zárt, minden commitra garantálhatjuk
a következő gyengébb feltételt:

    Ha A és B olyan commitok, amelyek generációs száma rendre N és M,
    és N < M, akkor A nem éri el B-t.

Vedd észre, mennyiben tér el a szigorú egyenlőtlenség attól az egyenlőtlenségtől, amikor
teljesen kiszámított generációs számaink vannak. A szigorú egyenlőtlenség használata
néhány extra commit bejárását eredményezheti, de a *_INFINITY vagy *_ZERO generációs
számú commitok kezelésének egyszerűsége értékes.

A GENERATION_NUMBER_V1_MAX = 0x3FFFFFFF makrót azokra a commitokra használjuk, amelyek
topologikus szintje (generációs szám v1) legalább ekkorára van kiszámítva.
Ennél az értéknél korlátozunk, mivel ez a legnagyobb érték, amely a
commit-graph fájlban a topologikus szintekre rendelkezésre álló 30 biten
tárolható. Ez egy újabb eset, amikor egy commit generációs száma megegyezhet
egy szülőjének generációs számával.

[[_design_details]]
Tervezési részletek
-------------------

- A commit-graph fájl a .git/objects/info könyvtárban egy 'commit-graph' nevű
  fájlban van tárolva. Ez egy alternate info könyvtárában is
  tárolható.

- A gráffájlok felhasználásához a core.commitGraph konfigurációs beállításnak be kell kapcsolva lennie.

- A fájlformátum tartalmazza az objektumazonosító-hashfüggvény paramétereit,
  így a hash-algoritmus jövőbeli megváltoztatása nem igényel formátumváltoztatást.

- A commit graftok és a replace objektumok megváltoztathatják a commit-előzmények
  alakját. Az utóbbi menet közben is be- és kikapcsolható a
  `--no-replace-objects` kapcsolóval. Ez megnehezíti egy commit-azonosító
  mindkét lehetséges értelmezésének tárolását, különösen a generációs számok
  kiszámításakor. A commit-graphot nem olvassuk és nem írjuk, ha
  replace-objektumok vagy graftok vannak jelen.

- A sekély klónok a szüleik eldobásával commit-graftokat hoznak létre. Ez azt
  eredményezi, hogy a commit-graph 1-es generációs számúnak hiszi ezeket a commitokat.
  Ha és amikor ezeket a commitokat nem sekéllyé teszik, ezek a generációs számok
  érvénytelenné válnak. Mivel a sekély klónok célja, hogy a commit-előzményeket egy
  nagyon kis committhalmazra korlátozzák, a commit-graph funkció amúgy is kevésbé
  hasznos ezeknél a klónoknál. A commit-graphot nem olvassuk és nem
  írjuk, ha sekély commitok vannak jelen.

[[_commit_graphs_chains]]
Commit-graph láncok
-------------------

A repók jellemzően közel állandó sebességgel nőnek (commit/nap). Idővel egy
fetch művelet által hozzáadott commitok száma sokkal kisebb, mint a
teljes előzmény commitjainak száma. Ha a commit-graphokból „láncot" hozunk létre,
lehetővé válik az új commit-adatok gyors írása a teljes commit-előzmény
újraírása nélkül -- legalábbis az esetek többségében.

[[_file_layout]]
Fájlelrendezés
~~~~~~~~~~~~~~

Egy commit-graph lánc több fájlt használ, és a fájlok rendszerezéséhez rögzített
elnevezési konvenciót alkalmazunk. Minden commit-graph fájl neve
`$OBJDIR/info/commit-graphs/graph-{hash}.graph`, ahol a `{hash}` az adott fájl
láblécében tárolt hexadecimális értékű hash (amely a fájl tartalmának hash-e a
hash előtti részig). Commit-graph fájlok láncához a
`$OBJDIR/info/commit-graphs/commit-graph-chain` helyen lévő egyszerű szöveges
fájl tartalmazza a fájlok hash-eit a „legalacsonyabbtól" a „legmagasabbig" sorrendben.

Például, ha a `commit-graph-chain` fájl a következő sorokat tartalmazza

----
	{hash0}
	{hash1}
	{hash2}
----

akkor a commit-graph lánc a következő ábrához hasonlóan néz ki:

 +-----------------------+
 |  graph-{hash2}.graph  |
 +-----------------------+
	  |
 +-----------------------+
 |                       |
 |  graph-{hash1}.graph  |
 |                       |
 +-----------------------+
	  |
 +-----------------------+
 |                       |
 |                       |
 |                       |
 |  graph-{hash0}.graph  |
 |                       |
 |                       |
 |                       |
 +-----------------------+

Legyen X0 a `graph-{hash0}.graph` commitjainak száma, X1 a
`graph-{hash1}.graph` commitjainak száma, X2 pedig a
`graph-{hash2}.graph` commitjainak száma. Ha egy commit az i. pozícióban jelenik meg a `graph-{hash2}.graph`-ban,
akkor ezt úgy értelmezzük, hogy ez a commit az (X0 + X1 + i) pozícióban van, és ezt
használjuk a „gráfpozíciójaként". A `graph-{hash2}.graph` commitjai ezekkel a
pozíciókkal hivatkoznak a szüleikre, amelyek a `graph-{hash1}.graph`-ban vagy a
`graph-{hash0}.graph`-ban lehetnek. Egy tetszőleges, j pozícióban lévő committhoz úgy navigálhatunk, hogy ellenőrizzük,
benne van-e a [0, X0), [X0, X0 + X1), [X0 + X1, X0 + X1 +
X2) intervallumokban.

Minden commit-graph fájl (kivéve az alapot, a `graph-{hash0}.graph`-ot) olyan adatokat tartalmaz,
amelyek megadják az alsóbb rétegek összes fájljának hash-eit. A fenti példában
a `graph-{hash1}.graph` a `{hash0}`-t tartalmazza, míg a `graph-{hash2}.graph` a
`{hash0}`-t és a `{hash1}`-et.

[[_merging_commit_graph_files]]
Commit-graph fájlok merge-elése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ha minden íráskor csak egy új commit-graph fájlt adnánk hozzá, sok commit-graph
fájlon átívelő lineáris keresési problémába ütköznénk.  Ehelyett merge-stratégiát
használunk annak eldöntésére, hogy a verem mikor csukjon össze néhány szintet.

Az alábbi ábra egy ilyen összecsukást mutat. Ahogy új commitok halmaza kerül hozzáadásra,
a merge-stratégia úgy dönt, hogy a fájloknak a `graph-{hash1}`-be kell
összecsukódniuk. Így az új commitokat, a `graph-{hash2}` commitjait és
a `graph-{hash1}` commitjait egy új `graph-{hash3}`
fájlba kell egyesíteni.

....
			    +---------------------+
			    |                     |
			    |    (new commits)    |
			    |                     |
			    +---------------------+
			    |                     |
 +-----------------------+  +---------------------+
 |  graph-{hash2}        |->|                     |
 +-----------------------+  +---------------------+
	  |                 |                     |
 +-----------------------+  +---------------------+
 |                       |  |                     |
 |  graph-{hash1}        |->|                     |
 |                       |  |                     |
 +-----------------------+  +---------------------+
	  |                  tmp_graphXXX
 +-----------------------+
 |                       |
 |                       |
 |                       |
 |  graph-{hash0}        |
 |                       |
 |                       |
 |                       |
 +-----------------------+
....

Ennek a folyamatnak a során az írandó commitokat egyesítjük, rendezzük, és a
tartalmat egy ideiglenes fájlba írjuk, mindezt egy `commit-graph-chain.lock`
zárolófájl birtoklása közben.  Amikor a fájl kiürül, a kiszámított `{hash3}`
szerint `graph-{hash3}`-ra nevezzük át. Végül az új láncadatokat a
`commit-graph-chain.lock` fájlba írjuk:

----
	{hash3}
	{hash0}
----

Ezután lezárjuk a zárolófájlt.

[[_merge_strategy]]
Merge-stratégia
~~~~~~~~~~~~~~~

Amikor olyan committhalmazt írunk, amely nem szerepel az N magasságú commit-graph
veremben, alapértelmezés szerint egy új fájlt hozunk létre az N + 1. szinten. Ezután úgy döntünk, hogy
merge-elünk az N. szinttel, ha a két feltétel egyike teljesül:

  1. Meg van adva a `--size-multiple=<X>`, vagy X = 2, és az N. szint commitjainak
     száma kevesebb, mint az N + 1. szint commitjai számának X-szerese.

  2. Meg van adva a `--max-commits=<C>` nem nulla C értékkel, és az N + 1. szint
     commitjainak száma több, mint C commit.

Ez a döntés lefelé kaszkádol a szinteken: amikor merge-elünk egy szintet, egy új
committhalmazt hozunk létre, amely aztán a következő szinttel hasonlítódik össze.

Az első feltétel a szintek számát a commitok teljes számában logaritmikusra
korlátozza.  A második feltétel korlátozza azoknak a commitoknak a teljes számát, amelyek egy
`graph-{hashN}` fájlban vannak, de nincsenek a `commit-graph` fájlban, megelőzve a
jelentős teljesítményproblémákat, amikor a verem merge-elődik, és egy másik folyamat csak
részben olvassa be az előző vermet.

A merge-stratégia értékei (2 a méretszorzóra, 64 000 a commitok maximális
számára) a teljes rugalmasság érdekében konfigurációs beállításokba lennének
kiszervezhetők.

[[_handling_mixed_generation_number_chains]]
Vegyes generációsszám-láncok kezelése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A v2-es generációs szám és a generációsadat-darab bevezetésével a
következő forgatókönyv lehetséges:

1. Az „új" Git korrigált commit-dátumokkal ír egy commit-graphot.
2. A „régi" Git korrigált commit-dátumok nélkül ír egy felosztott commit-graphot a tetejére.

Egy naiv megközelítés, amely minden rétegből a legújabb rendelkezésre álló
generációs számot használná, megsértené az elvárásokat: az alsó réteg
korrigált commit-dátumokat használna, amelyek sokkal nagyobbak, mint a felső
réteg topologikus szintjei. Ezért a Git megvizsgálja a legfelső
réteget, hogy hiányoznak-e belőle a korrigált commit-dátumok. Ilyen esetben
a Git csak a topologikus szintet használja generációs számként.

Amikor egy felosztott commit-graphban új réteget írunk, korrigált commit-
dátumokat írunk, ha a legfelső rétegben vannak korrigált commit-dátumok. Ez
garantálja, hogy ha egy rétegben vannak korrigált commit-dátumok, akkor minden alsóbb
rétegben is kell lenniük korrigált commit-dátumoknak.

Rétegek merge-elésekor nem vesszük figyelembe, hogy a merge-elt rétegekben voltak-e korrigált
commit-dátumok. Ehelyett az új rétegben akkor lesznek korrigált commit-dátumok, ha az
új réteg alatti rétegben vannak korrigált commit-dátumok.

Rétegek írása vagy merge-elése közben, ha az új réteg az egyetlen réteg, akkor
lesznek benne korrigált commit-dátumok, ha a Git kompatibilis verziója írja. Így
egy felosztott commit-graph egyetlen fájlként való újraírása (`--split=replace`)
egyetlen réteget hoz létre korrigált commit-dátumokkal.

[[_deleting_graph_hash_files]]
A graph-\{hash\} fájlok törlése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Miután egy új csúcsfájl megíródik, néhány `graph-{hash}` fájl esetleg már nem
része egy láncnak. Fontos, hogy ezeket a fájlokat előbb-utóbb eltávolítsuk a lemezről.
Az eltávolítás késleltetésének fő oka az, hogy egy másik folyamat még az újraírása
előtt beolvashatja a `commit-graph-chain` fájlt, de aztán a `graph-{hash}` fájlokat
a törlésük után keresi.

Hogy a régi felosztott commit-graphokat egy ideig meg lehessen tartani, miután
hivatkozatlanná válnak, frissítjük a fájlok módosítási idejét, amikor hivatkozatlanná
válnak. Ezután átvizsgáljuk a `$OBJDIR/info/commit-graphs/` könyvtárat olyan
`graph-{hash}` fájlok után, amelyek módosítási ideje régebbi egy adott lejárati
ablaknál. Ez az ablak alapértelmezés szerint nulla, de parancssori argumentumokkal vagy
konfigurációs beállítással megváltoztatható.

[[_chains_across_multiple_object_directories]]
Láncok több objektumkönyvtáron át
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Alternate-ekkel rendelkező repóban a `commit-graph-chain` fájlt a helyi
objektumkönyvtárban, majd az egyes alternate-ekben keressük. Az első létező
fájl határozza meg a láncunkat. Ahogy a láncfájlban lévő minden `{hash}`-hez
keressük a `graph-{hash}` fájlokat, ugyanezt a mintát követjük a
gazdakönyvtáraknál.

Ez lehetővé teszi, hogy a commit-graphok több forkra legyenek felosztva egy fork-hálózatban.
A tipikus eset egy nagy „alap" repó sok kisebb forkkal.

Ahogy az alap repó halad előre, valószínűleg gyakrabban frissíti és merge-eli a
commit-graph láncát, mint a forkok. Ha egy fork az alap repó után frissíti a
commit-graphját, akkor „át kell szüleznie" a commit-graph láncot az alap repó új
láncára. Amikor minden `graph-{hash}` fájlt beolvasunk, nyomon követjük az azt
tartalmazó objektumkönyvtárt. Egy új commit-graph fájl írása során ellenőrizzük,
hogy vannak-e változások a forrás objektumkönyvtárban, beolvassuk annak a
forrásnak a `commit-graph-chain` fájlját, és ezekre a fájlokra alapozva új fájlt
hozunk létre. Ennek az „átszülezés" műveletnek a során szükségszerűen össze kell
csuknunk a fork összes szintjét, mivel az összes fájl érvénytelen az új alapfájllal szemben.

Ebben a forgatókönyvben döntő fontosságú az óvatosság a „hivatkozatlan" `graph-{hash}.graph`
fájlok takarításakor. A felhasználóra hárul, hogy meghatározza az egyedi
környezetének megfelelő beállításokat:

 1. Amikor az alap repóban szinteket merge-elünk, a hivatkozatlan fájlokra még
    hivatkozhatnak fork repók láncai.

 2. A lejárati időt olyan hosszúra kell állítani, hogy minden forknak legyen ideje
    újraszámítani a commit-graph láncát, hogy „átszülezze" az új alap-
    fájl(ok)ra.

 3. Ha az alapban frissül a commit-graph lánc, a fork nem fér hozzá az új
    lánchoz, amíg a lánca nem frissül, hogy hivatkozzon ezekre a fájlokra.
    (Ez a jövőben megváltozhat [5].)

[[_related_links]]
Kapcsolódó hivatkozások
-----------------------
[0] https://bugs.chromium.org/p/git/issues/detail?id=8
    Chromium munkaelem ehhez: Serialized Commit Graph

[1] https://lore.kernel.org/git/20110713070517.GC18566@sigill.intra.peff.net/
    Egy elhagyott patch, amely bevezette a generációs számokat.

[2] https://lore.kernel.org/git/20170908033403.q7e6dj7benasrjes@sigill.intra.peff.net/
    Vita a commitok generációs számairól és arról, hogyan lépnek kölcsönhatásba
    az fsck-val.

[3] https://lore.kernel.org/git/20170908034739.4op3w4f2ma5s65ku@sigill.intra.peff.net/
    További vita a generációs számokról és arról, hogy ne tároljuk őket a
    commit-objektumokon belül. Egy értékes idézet:

    "I think we should be moving more in the direction of keeping
     repo-local caches for optimizations. Reachability bitmaps have been
     a big performance win. I think we should be doing the same with our
     properties of commits. Not just generation numbers, but making it
     cheap to access the graph structure without zlib-inflating whole
     commit objects (i.e., packv4 or something like the "metapacks" I
     proposed a few years ago)."

[4] https://lore.kernel.org/git/20180108154822.54829-1-git@jeffhostetler.com/T/#u
    Egy patch, amely eltávolítja az ahead-behind számítást a 'status' parancsból.

[5] https://lore.kernel.org/git/f27db281-abad-5043-6d71-cbb083b1c877@gmail.com/
    Vita egy „kétdimenziós gráfpozícióról", amely lehetővé teheti több
    commit-graph lánc egyidejű olvasását.
