Könyvtár-átnevezés felismerése
==============================

A diffcore-rename átnevezés-felismerő logikája, amely az egyes fájlok
átnevezéseit ellenőrzi, szintén ott aggregálódik, majd a merge-ort vagy a
merge-recursive elemzi azokban az esetekben, amikor az átnevezések kombinációi
arra utalnak, hogy egy teljes könyvtár átnevezésre került.

[[_scope_of_abilities]]
A képességek hatóköre
---------------------

Talán a legegyszerűbb egy példával kezdeni:

  * Ha x/a, x/b és x/c mind átkerült z/a, z/b és z/c helyére, valószínű,
    hogy a közben hozzáadott x/d is z/d-be szeretne kerülni, felismerve a
    jelet, hogy a teljes 'x' könyvtár átkerült 'z'-be.

Léteznek azonban érdekesebb lehetőségek is, például:

  * az előzmények egyik oldala átnevezi x -> z-t, a másik pedig valamely fájlt
    x/e-re nevez át, ezért a merge-nek tranzitív átnevezést kell végeznie, hogy
    az átnevezés végül z/e-nél kössön ki.

  * az előzmények egyik oldala átnevezi x -> z-t, de az x-en belüli összes fájlt is átnevezi.
    Például x/a -> z/alpha, x/b -> z/bravo stb.

  * 'x' és 'y' egyaránt egyetlen 'z' könyvtárba merge-elődik, és
    x->z-re és y->z-re is könyvtár-átnevezés kerül felismerésre.

  * egy könyvtár nem összes fájlja kerül ugyanarra a helyre átnevezésre;
    vagyis lehet, hogy az 'x'-ben lévő fájlok többsége most 'z' alatt található, de néhány
    'w' alatt van.

  * egy könyvtár átnevezésre kerül, amely egy alkönyvtárt is tartalmazott, amelyet
    egy teljesen más helyre neveztek át.  (És talán maga a belső könyvtár is
    tartalmazott belső könyvtárakat, amelyeket megint más helyekre
    neveztek át).

  * a fentiek kombinációi; különféle érdekes esetekért lásd a
    t/t6423-merge-rename-directories.sh fájlt.

[[_limitations_applicability_of_directory_renames]]
Korlátozások -- a könyvtár-átnevezések alkalmazhatósága
-------------------------------------------------------

Annak megelőzésére, hogy szélső- és sarokesetek olyan konfliktusokhoz vezessenek,
amelyek nem ábrázolhatók az indexben, vagy amelyek túl bonyolultak lehetnek ahhoz,
hogy a felhasználók megpróbálják megérteni és feloldani őket, néhány alapszabály
korlátozza, hogy mikor alkalmazandó a könyvtár-átnevezés felismerése:

  1) Ha egy adott könyvtár a merge mindkét oldalán továbbra is létezik, akkor
     nem tekintjük átnevezettnek.

  2) Ha az átnevezendő fájlok egy részhalmazának egy fájl vagy könyvtár útban van
     (vagy egymásnak lennének útban), akkor „kapcsold ki" a könyvtár-átnevezést
     azokra a konkrét alútvonalakra, és jelentsd a konfliktust a
     felhasználónak.

  3) Ha az előzmények másik oldala olyan útvonalra végzett könyvtár-átnevezést,
     amelyet a te előzményoldalad elnevezett onnan, akkor hagyd figyelmen kívül
     az előzmények másik oldaláról származó azt a konkrét átnevezést minden implicit
     könyvtár-átnevezésnél (de figyelmeztesd a felhasználót).

[[_limitations_detailed_rules_and_testcases]]
Korlátozások -- részletes szabályok és tesztesetek
--------------------------------------------------

A t/t6423-merge-rename-directories.sh kiterjedt teszteket és magyarázatokat tartalmaz,
amelyek a fent felsorolt szabályokat generálják és tárják fel.  Néhány további
szabályt is felsorol:

  a) Ha az átnevezések egy könyvtárt két vagy több másikra osztanak, a legtöbb
     átnevezéssel bíró könyvtár „nyer".

  b) Az implicit könyvtár-átnevezéseket csak akkor alkalmazd a könyvtárakra, ha
     az előzmények másik oldala végzi az átnevezést.

  c) Ne végezz könyvtár-átnevezés-felismerést olyan könyvtárakra, amelyekhez nem
     adtak hozzá új útvonalat.

[[_limitations_support_in_different_commands]]
Korlátozások -- támogatás a különböző parancsokban
--------------------------------------------------

A könyvtár-átnevezés felismerését a 'merge' és a 'cherry-pick' támogatja.
Más git parancsok, amelyeknél a felhasználók meglepődhetnek, hogy korlátozott vagy
egyáltalán nincs könyvtár-átnevezés-felismerési támogatás:

  * diff

    A múltban felmerült az igény, hogy a `git diff` ismerje fel a könyvtár-
    átnevezéseket, és valamilyen módon egyszerűsítse a kimenetét.  Nem világos, hogy ez
    kívánatos volna-e, vagy hogyan kellene egyszerűsíteni a kimenetet, ezért ezt
    egyszerűen nem valósították meg.  Ráadásul, bár a diffcore-rename tartalmazza a
    könyvtár-átnevezések felismerésének logikájának nagy részét, a logika egy része
    még mindig a merge-ort és a merge-recursive kódjában található.  A könyvtár-
    átnevezés felismerésének teljes támogatásához a diffekben a fennmaradó
    logikarészeket át kellene másolni vagy mozgatni a diff gépezetébe.

  * am

    A git-am megpróbálja elkerülni a teljes háromutas merge-et, helyette a
    git-apply-t hívja.  Ez teljesen megakadályozza az átnevezések felismerését, ami
    meghiúsíthatja a könyvtár-átnevezés felismerését.  Van azonban egy tartalék megoldás; ha
    a kezdeti git-apply sikertelen, és a felhasználó megadta a -3 opciót,
    a git-am visszavált háromutas merge-re.  A git-am azonban nem rendelkezik a
    „valódi" háromutas merge-hez szükséges információval.  Ehelyett a
    build_fake_ancestor() függvényt kell használnia, hogy olyan merge-alapot kapjon, amelyből hiányoznak azok a fájlok,
    amelyek átnevezésének felismerése fontos lehetett volna a könyvtár-átnevezés
    felismerésének működéséhez.

  * rebase

    Mivel az am-alapú rebase-ek úgy működnek, hogy előbb egy csomó patchet generálnak
    (amelyek már nem rögzítik, hogy mik voltak az eredeti commitok, így nem
    tartalmazzák a szükséges információt, amelyből valódi merge-alapot találhatnánk),
    majd meghívják a git-am-et, ez azt jelenti, hogy az am-alapú rebase-ek sem mindig
    ismerik fel sikeresen a könyvtár-átnevezéseket (lásd a fenti 'am' szakaszt).
    A merge-alapú rebase-eket (rebase -m) és a cherry-pick-alapú rebase-eket
    (rebase -i) nem érinti ez a hiányosság, és teljes mértékben támogatják a
    könyvtár-átnevezés felismerését.
