A Git hashfüggvény-átállása
===========================

[[_objective]]
Cél
---
A Git átállítása SHA-1-ről egy erősebb hashfüggvényre.

[[_background]]
Háttér
------
Alapjában véve a Git verziókövető rendszer egy tartalomcímzett
fájlrendszer. A SHA-1 hashfüggvényt használja a tartalom elnevezésére.
Például a fájlokra, könyvtárakra és revíziókra hashértékekkel hivatkozik,
szemben más hagyományos verziókövető rendszerekkel, ahol a fájlokra
vagy verziókra sorszámokkal hivatkoznak. A tartalom címzésére szolgáló hash-
függvény használata néhány előnnyel jár:

* Az integritásellenőrzés egyszerű. A bitfordulások például könnyen
  észlelhetők, mivel a sérült tartalom hash-e nem egyezik a nevével.
* Az objektumok keresése gyors.

Egy kriptográfiailag biztonságos hashfüggvény használata további
előnyökkel jár:

* Az objektumnevek aláírhatók, és harmadik felek megbízhatnak abban, hogy a
  hash az aláírt objektumot és az általa hivatkozott összes objektumot címzi.
* A Git protokollt használó kommunikáció és a sávon kívüli kommunikációs
  módszerek rövid, megbízható karakterlánccal rendelkeznek, amely a tárolt
  tartalom megbízható címzésére használható.

Idővel a biztonsági kutatók néhány hibát fedeztek fel a SHA-1-ben. 2017.
február 23-án a SHAttered támadás
(https://shattered.io) gyakorlati SHA-1 hash-ütközést mutatott be.

A Git v2.13.0 és későbbi verziói ezt követően alapértelmezés szerint egy
megerősített SHA-1 implementációra tértek át, amely nem sebezhető a SHAttered
támadással szemben, de a SHA-1 továbbra is gyenge.

Ezért körültekintőnek tekinthető, hogy a SHA-1 bármely változatán túllépve egy
új hashre váltsunk. Nincs garancia arra, hogy a jövőben nem publikálnak további
SHA-1 elleni támadásokat, és ezeknek a támadásoknak esetleg nincs életképes
kivédési módja.

Ha a SHA-1 és változatai valóban feltörnének, a Git hashfüggvénye többé nem
lenne kriptográfiailag biztonságosnak tekinthető. Ez hatással lenne a
hashértékek kommunikációjára, mert nem bízhatnánk abban, hogy egy adott
hashérték a tartalom ismerten jó verzióját képviseli, amelyet a beszélő
szándékozott.

A SHA-1 továbbra is rendelkezik a többi tulajdonsággal, például a gyors
objektumkereséssel és a biztonságos hibaellenőrzéssel, de más hashfüggvények
ugyanúgy megfelelnek, amelyekről feltételezik, hogy kriptográfiailag biztonságosak.

[[_choice_of_hash]]
A hash megválasztása
--------------------
A megerősített SHA-1-et leváltó hashnek erősebbnek kell lennie, mint amilyen a
SHA-1 volt: azt szeretnénk, hogy megbízható és a gyakorlatban hasznos legyen
legalább 10 évig.

Néhány további releváns tulajdonság:

1. 256 bites hash (elég hosszú ahhoz, hogy megfeleljen az általános biztonsági
   gyakorlatnak; nem túl hosszú, hogy rontsa a teljesítményt és a lemezhasználatot).

2. Kiváló minőségű implementációknak széles körben elérhetőnek kell lenniük (pl.
   az OpenSSL-ben és az Apple CommonCryptóban).

3. A hashfüggvény tulajdonságainak meg kell felelniük a Git igényeinek (pl. a Git
   ütközés- és második őskép-ellenállást igényel, és nem igényel
   hosszkiterjesztés-ellenállást).

4. Döntetlen esetén a hashnek gyorsan kiszámíthatónak kell lennie (szerencsére
   sok jelölt gyorsabb a SHA-1-nél).

Több jelölt is volt a SHA-1 utódhashére, köztük a
SHA-256, a SHA-512/256, a SHA-256x16, a K12 és a BLAKE2bp-256.

2018 végén a projekt a SHA-256-ot választotta utódhashének.

További információért lásd a 0ed8d8da374 (doc hash-function-transition: pick SHA-256 as
NewHash, 2018-08-04) committot és az akkori számos levelezőlistás szálat,
különösen az itt kezdődőt:
https://lore.kernel.org/git/20180609224913.GC38834@genre.crustytoothpaste.net/

[[_goals]]
Célok
-----
1. A SHA-256-ra való átállás egyszerre egy helyi repositoryn végezhető el.
   a. Nem igényel semmilyen műveletet más féltől.
   b. Egy SHA-256 repository tud kommunikálni SHA-1-es Git-szerverekkel
      (push/fetch).
   c. A felhasználók felcserélhetően használhatnak SHA-1 és SHA-256
      objektumazonosítókat (lásd lentebb az „Objektumnevek a parancssorban" szakaszt).
   d. Az új aláírt objektumok a SHA-1-nél erősebb hashfüggvényt használnak a
      biztonsági garanciáikhoz.
2. Lehetővé tenni a SHA-1-től való teljes elszakadást.
   a. A SHA-1 kompatibilitáshoz szükséges helyi metaadatok eltávolíthatók egy
      repositoryból, ha a SHA-1 kompatibilitásra már nincs szükség.
3. Karbantarthatóság a folyamat során végig.
   a. Az objektumformátum egyszerű és konzisztens marad.
   b. Egy általánosított repository-konverziós eszköz létrehozása.

[[_non_goals]]
Nem célok
---------
1. SHA-256 támogatás hozzáadása a Git protokollhoz. Ez értékes és a
   logikus következő lépés, de kívül esik ennek a kezdeti tervnek a hatókörén.
2. A meglévő SHA-1-gyel aláírt objektumok biztonságának átlátszó
   javítása.
3. Több hashfüggvényt használó objektumok keverése egyetlen
   repositoryn belül.
4. Az alkalom megragadása a Git formátumainak és protokolljainak egyéb
   hibái kijavítására.
5. Sekély klónok és fetchek egy SHA-256 repositoryba. (Ez meg fog
   változni, amikor SHA-256 támogatást adunk a Git protokollhoz.)
6. Egy projekt bizonyos submodule-jainak kihagyása egy SHA-256
   repositoryba történő fetch során. (Ez szintén a Git protokoll SHA-256
   támogatásától függ.)

[[_overview]]
Áttekintés
----------
Bevezetünk egy új repository-formátum-kiterjesztést. Az ezt a kiterjesztést
engedélyező repository-k SHA-1 helyett SHA-256-ot használnak az objektumaik
elnevezésére. Ez az objektumneveket és az objektumtartalmat is érinti -- az
objektumok nevei és az egy objektumon belüli, más objektumokra mutató összes
hivatkozás is átvált az új hashfüggvényre.

A SHA-256 repository-kat a Git régebbi verziói nem tudják olvasni.

A packfile mellett egy SHA-256 repository kétirányú leképezést tárol a
SHA-256 és a SHA-1 objektumnevek között. A leképezés helyben jön létre, és a
"git fsck" paranccsal ellenőrizhető. Az objektumkeresések ezt a leképezést
használják, hogy az objektumok felcserélhetően legyenek elnevezhetők a SHA-1 és
a SHA-256 nevükkel is.

A "git cat-file" és a "git hash-object" opciókat kap egy objektum SHA-1
alakban való megjelenítésére és egy objektum SHA-1 alakja alapján történő
kiírására. Ehhez az adott objektum által hivatkozott összes objektumnak jelen
kell lennie az objektumadatbázisban, hogy a megfelelő névvel legyenek
elnevezhetők (a kétirányú hash-leképezéssel).

Egy SHA-1 alapú szerverről történő fetchek a lekért objektumokat SHA-256
alakra konvertálják, és rögzítik a leképezést a kétirányú leképezőtáblában
(részletekért lásd lentebb). Egy SHA-1 alapú szerverre történő pushok a
pusholt objektumokat SHA-1 alakra konvertálják, így a szervernek nem kell
tudnia, milyen hashfüggvényt használ a kliens.

[[_detailed_design]]
Részletes terv
--------------
[[_repository_format_extension]]
Repository-formátum-kiterjesztés
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Egy SHA-256 repository az `1`-es repository-formátumverziót használja (lásd:
linkgit:gitrepository-layout[5]), ahol az `extensions.objectFormat` és az
`extensions.compatObjectFormat` (lásd: linkgit:git-config[1]) a következőre van állítva:

	[core]
		repositoryFormatVersion = 1
	[extensions]
		objectFormat = sha256
		compatObjectFormat = sha1

A `core.repositoryFormatVersion=1` beállítása és az `extensions.*` kitöltése
együtt biztosítja, hogy a Git minden `v0.99.9l`-nél újabb verziója kilépjen
ahelyett, hogy megpróbálna a SHA-256 repositoryn dolgozni, és helyette
hibaüzenetet ad.

	# Between v0.99.9l and v2.7.0
	$ git status
	fatal: Expected git repo version <= 0, found 1
	# After v2.7.0
	$ git status
	fatal: unknown repository extensions found:
		objectformat
		compatobjectformat

Ezekről a repository-kiterjesztésekről bővebben lásd lentebb az „Átállási terv"
szakaszt.

[[_object_names]]
Objektumnevek
~~~~~~~~~~~~~
Az objektumok elnevezhetők a 40 hexadecimális számjegyű SHA-1 nevükkel vagy a 64
hexadecimális számjegyű SHA-256 nevükkel, valamint az ezekből származtatott
nevekkel (lásd: gitrevisions(7)).

Egy objektum SHA-1 neve a típusának, a hosszának, egy nul bájtnak és az
objektum SHA-1 tartalmának az összefűzéséből képzett SHA-1. Ez a Git-ben az
objektumok elnevezésére használt hagyományos <sha1>.

Egy objektum SHA-256 neve a típusának, a hosszának, egy nul bájtnak és az
objektum SHA-256 tartalmának az összefűzéséből képzett SHA-256.

[[_object_format]]
Objektumformátum
~~~~~~~~~~~~~~~~
Egy SHA-1-gyel és egy SHA-256-tal elnevezett tag-, commit- vagy tree-objektum
bájtsorozatként vett tartalma eltér, mert egy SHA-256 névvel elnevezett objektum
más objektumokra a SHA-256 nevükkel hivatkozik, egy SHA-1 névvel elnevezett
objektum pedig más objektumokra a SHA-1 nevükkel hivatkozik.

Egy objektum SHA-256 tartalma megegyezik a SHA-1 tartalmával, azzal a
kivétellel, hogy az objektum által hivatkozott objektumok a SHA-256 nevükkel
vannak elnevezve a SHA-1 nevük helyett. Mivel egy blob-objektum nem hivatkozik
más objektumra, a SHA-1 tartalma és a SHA-256 tartalma azonos.

A formátum lehetővé teszi az oda-vissza konverziót a SHA-256 tartalom és a
SHA-1 tartalom között.

[[_object_storage]]
Objektumtárolás
~~~~~~~~~~~~~~~
A laza objektumok zlib tömörítést használnak, a csomagolt objektumok pedig a
linkgit:gitformat-pack[5] dokumentumban leírt csomagolt formátumot, akárcsak
ma. A tömörített és tárolt tartalom SHA-256 tartalmat használ SHA-1 tartalom
helyett.

[[_pack_index]]
Pack-index
~~~~~~~~~~
A pack-index (.idx) fájlok egy új v3 formátumot használnak, amely több
hashfüggvényt támogat. A következő formátumuk van (minden egész szám
hálózati bájtsorrendben):

- Az elején egy fejléc szerepel, amely a következőkből áll:
  * A 4 bájtos pack-index-aláírás: '\377t0c'
  * 4 bájtos verziószám: 3
  * A fejlécszakasz 4 bájtos hossza, az aláírással és a
    verziószámmal együtt
  * A packben lévő objektumok 4 bájtos száma
  * Az ebben a pack-indexben lévő objektumformátumok 4 bájtos száma: 2
  * Minden objektumformátumhoz:
    ** 4 bájtos formátumazonosító (pl. 'sha1' a SHA-1-hez)
    ** A rövidített objektumnevek 4 bájtos hossza bájtban. Ez a
      lehető legrövidebb hossz, amely ahhoz szükséges, hogy a rövidített
      objektumnév-táblában lévő nevek egyértelműek legyenek.
    ** 8 bájtos egész szám, amely rögzíti, hol tárolódnak az ehhez a formátumhoz
      tartozó táblák ebben az indexfájlban, az elejétől számított eltolásként.
  * 8 bájtos eltolás a fájl elejétől a záró részhez.
  * Nulla vagy több további kulcs/érték pár (4 bájtos kulcs, 4 bájtos
    érték). Csak egy kulcs támogatott: 'PSRC'. A támogatott értékekért és
    ennek használatáért lásd a „Laza objektumok és elérhetetlen objektumok"
    szakaszt.  Minden más kulcs fenntartott. Az olvasóknak figyelmen kívül kell
    hagyniuk a fel nem ismert kulcsokat.
- Nulla vagy több NUL bájt. Ez opcionálisan az alábbi teljes objektumnév-tábla
  igazításának javítására használható.
- Táblák az első objektumformátumhoz:
  * A rövidített objektumnevek rendezett táblája.  Ezek az ebben a pack fájlban
    lévő összes objektum nevének előtagjai, eltolásértékek nélkül összecsomagolva,
    hogy csökkentsék egy adott objektumnév bináris keresésének
    gyorsítótár-lábnyomát.

  * A teljes objektumnevek táblája pack sorrendben. Ez lehetővé teszi, hogy „a
    pack fájl n. objektumára" mutató hivatkozást (egy elérhetőségi bittérképből
    vagy egy másik objektumformátum következő táblájából) feloldjunk az
    objektumnevére.

  * 4 bájtos értékek táblája, amely az objektumnév-sorrendet a pack sorrendre
    képezi le. Egy objektumhoz a rendezett rövidített objektumnevek táblájában a
    megfelelő indexen lévő érték ebben a táblában az előző táblában
    ugyanahhoz az objektumhoz tartozó index.
    Ez az objektum elérhetőségi bittérképekben való kereséséhez vagy a nevének
    egy másik objektumformátumban való kereséséhez használható.

  * A csomagolt objektumadatok 4 bájtos CRC32-értékeinek táblája abban a
    sorrendben, ahogy az objektumok a pack fájlban megjelennek. Ez lehetővé teszi,
    hogy a tömörített adatokat újracsomagolás során közvetlenül packből packbe
    másoljuk észrevétlen adatsérülés nélkül.

  * 4 bájtos eltolásértékek táblája. Ennek a táblának az indexe pack sorrendben
    jelzi, hol található az adott objektum a pack fájlban. Ezek
    általában 31 bites pack fájl eltolások, de a nagy eltolások a
    következő táblába mutató indexként vannak kódolva, a legmagasabb helyi értékű bit beállításával.

  * 8 bájtos eltolásbejegyzések táblája (üres a 2 GiB-nál kisebb pack
    fájloknál). A pack fájlok úgy vannak rendezve, hogy a sokat használt objektumok
    az elejére kerüljenek, így a legtöbb objektumhivatkozásnak nem kellene erre a
    táblára hivatkoznia.
- Nulla vagy több NUL bájt.
- Táblák a második objektumformátumhoz, a fentivel azonos elrendezéssel,
  a CRC32-értékek tábláját nem beleértve.
- Nulla vagy több NUL bájt.
- A záró rész a következőkből áll:
  * A megfelelő packfile végén lévő teljes fő hash ellenőrzőösszegének
    másolata.

  * A fentiek mindegyikének teljes fő hash ellenőrzőösszege.

A „teljes fő hash" a repositoryban lévő fő (nem kompatibilitási) algoritmus
teljes hosszúságú hash-e.  Így ha a fő algoritmus a SHA-256, ez egy
32 bájtos SHA-256 hash, a SHA-1 esetén pedig egy 20 bájtos SHA-1 hash.

[[_loose_object_index]]
Laza objektum index
~~~~~~~~~~~~~~~~~~~
Egy új $GIT_OBJECT_DIR/loose-object-idx fájl minden laza objektumról
információt tartalmaz. A formátuma:

  # loose-object-idx
  (sha256-name SP sha1-name LF)*

ahol az objektumnevek hexadecimális formátumúak. A fájl nincs
rendezve.

A laza objektum indexet egy $GIT_OBJECT_DIR/loose-object-idx.lock
zárolófájl védi az egyidejű írásoktól. Egy új laza objektum
hozzáadásához:

1. Írd a laza objektumot egy ideiglenes fájlba, akárcsak ma.
2. Nyisd meg a loose-object-idx.lock-ot O_CREAT | O_EXCL-lel a zár megszerzéséhez.
3. Nevezd át a laza objektumot a helyére.
4. Nyisd meg a loose-object-idx-et O_APPEND-del, és írd bele az új objektumot
5. Töröld (unlink) a loose-object-idx.lock-ot a zár feloldásához.

Bejegyzések eltávolításához (pl. a "git pack-refs"-ben vagy a "git-prune"-ban):

1. Nyisd meg a loose-object-idx.lock-ot O_CREAT | O_EXCL-lel a zár
   megszerzéséhez.
2. Írd az új tartalmat a loose-object-idx.lock-ba.
3. Töröld (unlink) az eltávolítandó laza objektumokat.
4. Nevezd át, hogy leváltsd a loose-object-idx-et, feloldva a zárat.

[[_translation_table]]
Fordítótábla
~~~~~~~~~~~~
Az indexfájlok kétirányú leképezést támogatnak a SHA-1 nevek és a
SHA-256 nevek között. A keresés a szokásos objektumkeresésekhez
hasonlóan zajlik. Például egy SHA-1 név SHA-256 névre alakításához:

 1. Keresd meg az objektumot az idx fájlokban. Ha van egyezés az idx
    csonkolt SHA-1 neveinek rendezett listájában, akkor:
    a. Olvasd be a megfelelő bejegyzést a SHA-1 névsorrend → pack
       névsorrend leképezésben.
    b. Olvasd be a megfelelő bejegyzést a teljes SHA-1 névtáblában, hogy
       ellenőrizd, a megfelelő objektumot találtuk-e meg. Ha igen, akkor
    c. Olvasd be a megfelelő bejegyzést a teljes SHA-256 névtáblában.
       Ez az objektum SHA-256 neve.
 2. Ellenőrizd, van-e laza objektum. Olvass sorokat a loose-object-idx-ből,
    amíg egyezést nem találsz.

Az (1) lépés ugyanannyi ideig tart, mint egy szokásos objektumkeresés:
O(packek száma * log(objektumok packenként)). A (2) lépés O(laza objektumok
száma) ideig tart. A jó teljesítmény fenntartásához szükséges lesz
alacsonyan tartani a laza objektumok számát. Bővebben lásd lentebb a „Laza
objektumok és elérhetetlen objektumok" szakaszt.

Mivel minden új objektumot létrehozó művelet (pl. "git commit") hozzáadja az
új objektumokat a megfelelő indexhez, ez a leképezés az objektumtár minden
objektumára lehetséges.

[[_reading_an_object_s_sha_1_content]]
Egy objektum SHA-1 tartalmának olvasása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Egy objektum SHA-1 tartalma úgy olvasható be, hogy a SHA-256 tartalma
hivatkozásainak összes SHA-256 nevét SHA-1 nevekre alakítjuk a fordítótáblával.

[[_fetch]]
Fetch
~~~~~
Egy SHA-1 alapú szerverről történő fetchhez menet közben kell fordítani a
SHA-1 és a SHA-256 alapú reprezentációk között.

A ref-hirdetésben megnevezett, a kliensen jelen lévő SHA-1-ek SHA-256-ra
fordíthatók, és helyi objektumként kereshetők ki a
fordítótáblával.

Az egyeztetés a mai módon zajlik. A helyben generált "have"-ek
SHA-1-re konvertálódnak, mielőtt a szerverre küldenék őket, a szerver által
említett SHA-1-ek pedig SHA-256-ra konvertálódnak, amikor helyben keresik
ki őket.

Az egyeztetés után a szerver egy packfile-t küld, amely a kért
objektumokat tartalmazza. A packfile-t a következő lépésekkel konvertáljuk
SHA-256 formátumra:

1. index-pack: fújd ki (inflate) a packfile minden objektumát, és számítsd ki a
   SHA-1-ét. Az objektumok tartalmazhatnak deltákat OBJ_REF_DELTA formátumban
   olyan objektumokhoz képest, amelyek a kliensen helyben megvannak. Ezek az
   objektumok kikereshetők a fordítótáblával, és a SHA-1 tartalmuk a fent leírt
   módon olvasható be a delták feloldásához.
2. topologikus rendezés: az egyeztetési fázis "want"-jaiból kiindulva járd be a
   pack objektumait, és bocsáss ki róluk egy listát, a blobokat kizárva,
   fordított topologikusan rendezett sorrendben, ahol minden objektum később
   kerül a listába, mint az összes általa hivatkozott objektum.
   (Ez a lista csak a "wants"-ból elérhető objektumokat tartalmazza. Ha a
   szervertől kapott pack további felesleges objektumokat tartalmazott, akkor
   azokat eldobjuk.)
3. konvertálás SHA-256-ra: nyiss egy új SHA-256 packfile-t. Olvasd be az imént
   generált topologikusan rendezett listát. Minden objektumhoz fújd ki a
   SHA-1 tartalmát, konvertáld SHA-256 tartalommá, és írd bele a SHA-256
   packbe. Rögzítsd az új SHA-1<-->SHA-256 leképezésbejegyzést az idx-ben való felhasználáshoz.
4. rendezés: rendezd át az új pack bejegyzéseit, hogy megfeleljenek az
   objektumok sorrendjének abban a packben, amelyet a szerver generált, és vedd
   bele a blobokat. Írj egy SHA-256 idx fájlt
5. takarítás: távolítsd el a SHA-1 alapú pack fájlt, indexet és a szervertől az
   1. és 2. lépésben kapott topologikusan rendezett listát.

A 3. lépéshez az kell, hogy az új objektum által hivatkozott minden objektum
benne legyen a fordítótáblában. Ezért van szükség a topologikus rendezési lépésre.

Optimalizációként az 1. lépés írhatna egy fájlt, amely leírja, hogy a
packfile-ból kifújt minden objektum milyen nem blob objektumokra hivatkozik. Ez
lehetővé teszi a 2. lépésbeli topologikus rendezést anélkül, hogy a
packfile objektumait másodszor is ki kellene fújni. A 3. lépésben az objektumokat
újra ki kell fújni, így összesen két kifújás történik.

A 4. lépés valószínűleg szükséges a jó olvasásidejű teljesítményhez. A szerveren
a "git pack-objects" a pack fájlt jó adatlokalitásra optimalizálja
(lásd: Documentation/technical/pack-heuristics.adoc).

Ennek a folyamatnak a részletei valószínűleg változni fognak. Némi
kísérletezésbe fog telni, hogy ez jól teljesítsen.

[[_push]]
Push
~~~~
A push egyszerűbb, mint a fetch, mert a pusholt objektumok által hivatkozott
objektumok már benne vannak a fordítótáblában. Minden pusholt objektum SHA-1
tartalma az „Egy objektum SHA-1 tartalmának olvasása" szakaszban leírt módon
olvasható be, hogy létrejöjjön a git send-pack által írt pack.

[[_signed_commits]]
Aláírt commitok
~~~~~~~~~~~~~~~
Egy új "gpgsig-sha256" mezőt adunk a commit-objektum formátumához, hogy a
commitok a SHA-1-re támaszkodás nélkül legyenek aláírhatók. Hasonló a
meglévő "gpgsig" mezőhöz. Az aláírt payloadja a commit-objektum SHA-256
tartalma, minden "gpgsig" és "gpgsig-sha256" mezőt eltávolítva belőle.

Ez azt jelenti, hogy a commitok aláírhatók

1. csak SHA-1-gyel, mint a meglévő aláírt commit-objektumokban
2. SHA-1-gyel és SHA-256-tal is, a gpgsig-sha256 és a gpgsig mező
   együttes használatával.
3. csak SHA-256-tal, csak a gpgsig-sha256 mező használatával.

A "git verify-commit" régi verziói módosítás nélkül tudják ellenőrizni a
gpgsig aláírást az (1) és a (2) esetben, a (3) esetet pedig
közönséges, alá nem írt commitnak látják.

[[_signed_tags]]
Aláírt tagek
~~~~~~~~~~~~
Új "gpgsig" és "gpgsig-sha256" mezőket adunk a tag-objektum formátumához, hogy a
tagek mindkét formátumban aláírhatók legyenek.  A törzsön belüli aláírás a
jelenlegi hash-algoritmusbeli aláíráshoz használatos, a fejléc pedig a másik
algoritmusbeli aláíráshoz.  Így egy kétaláírásos tag tartalmazni fog egy
törzsön belüli aláírást és egy gpgsig-sha256 fejlécet egy objektum SHA-1
formátumához, vagy egy törzsön belüli aláírást és egy gpgsig fejlécet egy
objektum SHA-256 formátumához.

A tag aláírt payloadja a tag jelenlegi algoritmusbeli tartalma, mind a
gpgsig, mind a gpgsig-sha256 mezőjét, valamint a
"-----BEGIN PGP SIGNATURE-----" által határolt törzsön belüli aláírást eltávolítva.

Ez azt jelenti, hogy a tagek egy vagy mindkét algoritmussal aláírhatók.

[[_mergetag_embedding]]
Mergetag-beágyazás
~~~~~~~~~~~~~~~~~~
Egy commit SHA-1 tartalmában lévő mergetag mező egy olyan tag SHA-1
tartalmát tartalmazza, amelyet az a commit merge-elt.

Ugyanannak a commitnak a SHA-256 tartalmában lévő mergetag mező ugyanannak a
tagnek a SHA-256 tartalmát tartalmazza.

[[_submodules]]
Submodule-ok
~~~~~~~~~~~~
A rögzített submodule-mutatók konvertálásához a helyén kell lennie a konvertált
submodule repositorynak. A submodule fordítótáblája használható az új
hash kikereséséhez.

[[_loose_objects_and_unreachable_objects]]
Laza objektumok és elérhetetlen objektumok
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A loose-object-idx-ben végzett gyors keresésekhez az kell, hogy a laza
objektumok száma ne nőjön túl nagyra.

A "git gc --auto" jelenleg megvárja, hogy 6700 laza objektum legyen
jelen, mielőtt egy packfile-ba vonná össze őket. Mérnünk kell majd, hogy
megfelelőbb küszöböt találjunk a számára.

A "git gc --auto" jelenleg megvárja, hogy 50 pack legyen jelen,
mielőtt egyesítené a packfile-okat. A laza objektumok agresszívabb
csomagolása azt okozhatja, hogy a pack fájlok száma túl gyorsan nő. Ez
enyhíthető egy olyan stratégiával, amely Martin Fick exponenciális
gördülő szemétgyűjtő szkriptjéhez hasonló:
https://gerrit-review.googlesource.com/c/gerrit/+/35215

A "git gc" jelenleg minden általa a pack fájlokban talált elérhetetlen
objektumot laza objektumként kilök, hogy megelőzzön egy versenyhelyzetet
a törlésükkor (arra az esetre, ha egy másik folyamat egyidejűleg egy új,
a törlés előtt álló objektumra hivatkozó objektumot ír). Ez a jelen lévő laza
objektumok számának és a lemezterület-használatnak a robbanásához vezet, mivel
a delta formában lévő objektumok önálló laza objektumokkal helyettesítődnek.
Ami rosszabb, a versenyhelyzet a laza objektumoknál továbbra is fennáll.

Ehelyett a "git gc"-nek az elérhetetlen objektumokat egy új, UNREACHABLE_GARBAGE-
ként megjelölt packfile-ba kell mozgatnia (a PSRC mezővel; lásd
lentebb). Hogy elkerüljük a versenyhelyzetet, amikor egy törlés előtt álló
objektumra hivatkozó új objektumokat írunk, az új objektumokat író
kódútvonalaknak át kell másolniuk minden olyan objektumot az UNREACHABLE_GARBAGE
packekből, amelyekre új, nem UNREACHABLE_GARBAGE packek (vagy laza objektumok)
hivatkoznak. Az UNREACHABLE_GARBAGE ezután biztonságosan törölhető, ha a
létrehozási idejük (amelyet a fájl mtime-ja jelez) elég régen volt.

Az UNREACHABLE_GARBAGE packek elszaporodásának elkerülésére bizonyos
körülmények között összevonhatók. Ha a "gc.garbageTtl" egy napnál nagyobbra van
állítva, akkor az egyetlen UTC naptári napon belül létrehozott packek
összeolvaszthatók. A keletkező packfile mtime-ja aznap éjfél előtti volna, így
ez az effektív maximális ttl-t garbageTtl + 1 nappá teszi. Ha a "gc.garbageTtl"
egy napnál kevesebb, akkor a naptári napot ennek a ttl-nek a harmadával
megegyező hosszúságú intervallumokra osztjuk. Az ugyanazon az intervallumon
belül létrehozott packek összeolvaszthatók. A keletkező packfile mtime-ja az
intervallum vége előtti volna, így ez az effektív maximális ttl-t
garbageTtl * 4/3-dá teszi.

Ez a szabály Thirumala Reddy Mutchukota JGit-változtatásából származik:
https://git.eclipse.org/r/90465.

Az UNREACHABLE_GARBAGE beállítás a pack-index PSRC mezőjébe kerül.
Általánosabban ez a mező jelzi, honnan származik egy pack:

 - 1 (PACK_SOURCE_RECEIVE) a hálózaton keresztül kapott packhez
 - 2 (PACK_SOURCE_AUTO) egy könnyűsúlyú "gc --auto" művelet által létrehozott
   packhez
 - 3 (PACK_SOURCE_GC) egy teljes gc által létrehozott packhez
 - 4 (PACK_SOURCE_UNREACHABLE_GARBAGE) a gc által felfedezett lehetséges
   szeméthez
 - 5 (PACK_SOURCE_INSERT) a helyben létrehozott objektumokhoz, amelyeket
   közvetlenül egy pack fájlba írtak, pl. a "git add ."-ból

Ez az információ hasznos lehet a hibakereséshez és ahhoz, hogy a "gc --auto"
megfelelő döntéseket hozzon arról, mely packeket vonja össze.

[[_caveats]]
Figyelmeztetések
----------------
[[_invalid_objects]]
Érvénytelen objektumok
~~~~~~~~~~~~~~~~~~~~~~
A SHA-1 tartalomról SHA-256 tartalomra való konverzió megtart minden
sérülést az eredeti objektumban (pl. a bevezető 0-val kódolt tree-bejegyzés-
módokat, a helytelenül rendezett útvonalú tree-objektumokat és a szerző vagy
committer nélküli commit-objektumokat). Ez a terv szándékos jellemzője, hogy a
konverzió oda-vissza járható legyen.

A mélyebben sérült objektumok (pl. egy csonkolt "tree" fejlécsorú commit) nem
konvertálhatók, de amúgy sem voltak használhatók a jelenlegi Git
számára.

[[_shallow_clone_and_submodules]]
Sekély klón és submodule-ok
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Mivel megköveteli, hogy minden hivatkozott objektum elérhető legyen a helyben
generált fordítótáblában, ez a terv nem támogatja a sekély klónt vagy a le nem
kért submodule-okat. Protokollfejlesztések esetleg lehetővé tehetik ennek a
korlátozásnak a feloldását.

[[_alternates]]
Alternate-ek
~~~~~~~~~~~~
Ugyanezen okból egy SHA-256 repository nem kölcsönözhet objektumokat egy
SHA-1 repositoryból az objects/info/alternates vagy a
$GIT_ALTERNATE_OBJECT_DIRECTORIES használatával.

[[_git_notes]]
git notes
~~~~~~~~~
A "git notes" eszköz az objektumokat a SHA-1 nevükkel mint kulccsal annotálja.
Ez a terv nem ír le módot a notes-fák SHA-256 nevekre való migrálására.
Az a migráció várhatóan külön fog megtörténni (például a notes-fa gyökerében
lévő fájllal, amely leírja, melyik hasht használja).

[[_server_side_cost]]
Szerveroldali költség
~~~~~~~~~~~~~~~~~~~~~
Amíg a Git protokoll nem kap SHA-256 támogatást, a nyilvánosan elérhető
Git-szervereken erősen ellenjavallt a SHA-256 alapú tárolás használata. Amint a
Git protokoll SHA-256 támogatást kap, a SHA-256 alapú szerverek valószínűleg
nem fogják támogatni a SHA-1 kompatibilitást, hogy elkerüljék a klónozás során
esetleg nagyon költséges hash-újrakódolást, és hogy a partnereket
modernizálásra ösztönözzék.

Az itt leírt terv lehetővé teszi, hogy SHA-1-es kliensek fetcheljenek egy
személyes SHA-256 repositoryból, mert ez nem sokkal nehezebb, mint az adott
repositoryból történő push engedélyezése. Ezt a támogatást egy konfigurációs
opcióval kell védeni -- a git.kernel.orghoz hasonló szerverektől, amelyek nagy
számú klienst szolgálnak ki, nem várható el, hogy viseljék ezt a költséget.

[[_meaning_of_signatures]]
Az aláírások jelentése
~~~~~~~~~~~~~~~~~~~~~~
Az aláírt commitok és tagek aláírt payloadja nem nevezi meg kifejezetten az
objektumok azonosítására használt hasht. Ha egy nap a Git a jelenlegi SHA-1
(40 hexadecimális számjegy) vagy SHA-256 (64 hexadecimális számjegy)
objektumokkal azonos hosszúságú új hashfüggvényt vezet be, akkor egy
objektumaláírásban a PGP-vel aláírt payload mögötti szándék
tisztázatlan:

	object e7e07d5a4fcc2a203d9873968ad3e6bd4d7419d7
	type commit
	tag v2.12.0
	tagger Junio C Hamano <gitster@pobox.com> 1487962205 -0800

	Git 2.12

Azt jelenti-e ez, hogy a Git v2.12.0 az e7e07d5a4fcc2a203d9873968ad3e6bd4d7419d7
SHA-1 nevű commit, vagy az e7e07d5a4fcc2a203d9873968ad3e6bd4d7419d7
új-40-számjegyű-hashnevű commit?

Szerencsére a SHA-256 és a SHA-1 hossza eltér. Ha a Git egy másik, azonos
hosszúságú hasht kezd használni az objektumok elnevezésére, akkor meg kell
változtatnia az azt a hasht használó aláírt payloadok formátumát, hogy
kezelje ezt a problémát.

[[_object_names_on_the_command_line]]
Objektumnevek a parancssorban
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Az átállás támogatására (lásd lentebb az Átállási tervet) ez a terv négy
különböző működési módot támogat:

 1. („dark launch") A felhasználó által bevitt objektumneveket SHA-1-ként kezeli,
    és a kimenetre írt minden objektumnevet SHA-1-re konvertál, de az
    objektumokat SHA-256-tal tárolja.  Ez lehetővé teszi, hogy a felhasználók a
    kódot a teljesítményen kívül semmilyen látható viselkedésváltozás nélkül
    teszteljék.  Ez lehetővé teszi, hogy még a SHA-1 hashfüggvényt feltételező
    teszteket is lefuttassuk, hogy leellenőrizzük az új mód viselkedését.

 2. („early transition") Engedélyezi a SHA-1 és a SHA-256 objektumneveket is a
    bemeneten. A kimenetre írt minden objektumnév SHA-1-et használ. Ez lehetővé
    teszi, hogy a felhasználók továbbra is használják a SHA-1-et olyan partnerekkel
    (pl. e-mailben) való kommunikációhoz, akik még nem álltak át, és felkészít a 3. módra.

 3. („late transition") Engedélyezi a SHA-1 és a SHA-256 objektumneveket is a
    bemeneten. A kimenetre írt minden objektumnév SHA-256-ot használ. Ebben a
    módban a felhasználók alapértelmezés szerint biztonságosabb objektumelnevezési
    módszert használnak.  A fennakadás minimális, amíg a partnereik többsége
    a 2. vagy a 3. módban van.

 4. („post-transition") A felhasználó által bevitt objektumneveket SHA-256-ként
    kezeli, és a kimenetet SHA-256-tal írja. Ez biztonságosabb a 3. módnál,
    mert kisebb a kockázata, hogy a bemenetet helytelenül, a rossz
    hashfüggvénnyel értelmezzük.

A módot a konfigurációban adjuk meg.

A felhasználó explicit módon is megadhatja, melyik formátumot használja egy
adott revíziómegadóhoz és a kimenethez, felülbírálva a módot. Például:

    git --output-format=sha1 log abac87a^{sha1}..f787cac^{sha256}

[[_transition_plan]]
Átállási terv
-------------
Néhány kezdeti lépés egymástól függetlenül megvalósítható:

- egy hashfüggvény-API (vtable) hozzáadása
- az fsck megtanítása, hogy tolerálja a gpgsig-sha256 mezőt
- a gpgsig-* kizárása a "git commit --amend" által másolt mezők közül
- a SHA-1 értékektől függő tesztek megjelölése SHA1 teszt-
  előfeltétellel
- a "struct object_id", a GIT_MAX_RAWSZ és a GIT_MAX_HEXSZ
  következetes használata az "unsigned char *" és a beégetett
  20-as és 40-es konstansok helyett.
- az index v3 bevezetése
- a PSRC mező és a biztonságosabb objektumtörlés támogatásának hozzáadása

Az első felhasználó által látható változás az objectFormat kiterjesztés
bevezetése (compatObjectFormat nélkül). Ehhez kell:

- az fsck megtanítása erre a működési módra
- a hashfüggvény-API (vtable) használata az objektumnevek kiszámításakor
- objektumok aláírása és aláírások ellenőrzése
- a nem kompatibilis repositoryból történő fetch vagy oda történő push
  kísérleteinek elutasítása

Ezután jön a compatObjectFormat bevezetése:

- a loose-object-idx megvalósítása
- objektumnevek fordítása objektumformátumok között
- objektumtartalom fordítása objektumformátumok között
- aláírások generálása és ellenőrzése a kompat formátumban
- megfelelő indexbejegyzések hozzáadása, amikor új objektumot adunk az
  objektumtárhoz
- --output-format opció
- a ^{sha1} és a ^{sha256} revíziójelölés
- konfiguráció az alapértelmezett bemeneti és kimeneti formátum megadására (lásd
  fentebb az „Objektumnevek a parancssorban" szakaszt)

A következő lépés a SHA-1 repository-kból történő fetch és az oda történő push támogatása:

- a kompat formátumot használó repositoryba történő pushok engedélyezése
- a lekért objektumok SHA-1 neveiből topologikusan rendezett lista
  generálása
- a lekért packfile SHA-256 formátumra konvertálása és egy idx fájl
  generálása
- újrarendezés, hogy megfeleljen az objektumok sorrendjének a lekért packfile-ban

A fetchet támogató infrastruktúra egy meglévő repository konvertálását is
lehetővé teszi. A konvertált repository-kban és az új klónokban a végfelhasználók
a viselkedés bármilyen látható változása nélkül kaphatnak támogatást az új
hashfüggvényhez (lásd a „dark launch"-ot az „Objektumnevek a parancssorban"
szakaszban). Ez különösen lehetővé teszi, hogy a felhasználók ellenőrizzék a
repositoryban lévő objektumok SHA-256 aláírásait, és biztosítania kell, hogy az
átállási kód stabil legyen éles környezetben, felkészülve a szélesebb körű használatra.

Idővel a projektek arra ösztönöznék a felhasználóikat, hogy az „early transition",
majd a „late transition" módot vegyék fel, hogy kihasználják az új, jobban
jövőállóbb SHA-256 objektumneveket.

Amikor az objectFormat és a compatObjectFormat is be van állítva, az aláírásokat
generáló parancsok alapértelmezés szerint SHA-1 és SHA-256 aláírásokat is
generálnának, hogy támogassák az új és a régi felhasználókat is.

A SHA-256-ot sokat használó projektekben a felhasználókat arra lehetne
ösztönözni, hogy a „post-transition" módot vegyék fel, hogy elkerüljék a SHA-1
objektumnevek véletlen implicit használatát.

Amint a felhasználók kritikus tömege frissített a Git olyan verziójára, amely
tudja ellenőrizni a SHA-256 aláírásokat, és konvertálta a meglévő
repository-jait, hogy támogassa az ellenőrzésüket, hozzáadhatunk támogatást egy
olyan beállításhoz, amely csak SHA-256 aláírásokat generál. Ez várhatóan legalább
egy évvel később lesz.

Ez egyben jó pillanat annak meghirdetésére, hogy a repository-k átalakíthatók
csak SHA-256 használatára, minden SHA-1-hez kapcsolódó metaadatot kigyomlálva.
Ez javítja a teljesítményt a fordítási többletköltség kiküszöbölésével, és a
biztonságot azzal, hogy elkerüli a SHA-1 biztonságosságára való véletlen
támaszkodás lehetőségét.

A Git protokolljainak frissítése, hogy egy szerver megadhassa, mely
hashfüggvényeket támogatja, szintén fontos része ennek az átállásnak. Ezt a
dokumentum nem tárgyalja részletesen, de ez az átállási terv feltételezi, hogy
megtörténik. :)

[[_alternatives_considered]]
Megfontolt alternatívák
-----------------------
[[_upgrading_everyone_working_on_a_particular_project_on_a_flag_day]]
Egy adott projekten dolgozók egyszerre, egy kijelölt napon való átállítása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Az olyan projektek, mint a Linux kernel, elég nagyok és összetettek ahhoz, hogy
a repositoryn alapuló összes projektnél egyszerre átkapcsolni
kivitelezhetetlen.

Nemcsak minden fejlesztőnek és a fejlesztőket kiszolgáló szerverüzemeltetőnek
kellene ugyanazon a kijelölt napon átváltania, hanem a támogató eszközkészletet
(folyamatos integráció, kódfelülvizsgálat, hibakövetők stb.) is át kellene
alakítani. Ez azt is megnehezíti, hogy korai visszajelzést kapjunk néhány
tesztelő projektrésztvevőtől, mielőtt eljön a tömeges bevezetés ideje.

[[_using_hash_functions_in_parallel]]
Hashfüggvények párhuzamos használata
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(pl. https://lore.kernel.org/git/22708.8913.864049.452252@chiark.greenend.org.uk/ )
Az újonnan létrehozott objektumokat az új hash címezné, de egy ilyen
objektumon belül (pl. commit) továbbra is lehetséges volna az objektumokat a
régi hashfüggvénnyel címezni.

* Az előzményeiben (amely a bisectelhetőséghez szükséges) a jövőben nem
  bízhatsz további munka nélkül
* Karbantartási teher, ahogy a támogatott hashfüggvények száma nő
  (soha nem tűnnek el, így felhalmozódnak). Ebben a javaslatban ezzel
  szemben a konvertált objektumok minden SHA-1-re mutató hivatkozásukat elveszítik.

[[_signed_objects_with_multiple_hashes]]
Több hasht tartalmazó aláírt objektumok
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ahelyett, hogy a SHA-256 tartalom alapú aláírásokhoz bevezette volna a
gpgsig-sha256 mezőt a commit- és tag-objektumokban, ennek a tervnek egy korábbi
verziója "hash sha256 <SHA-256 név>" mezőket adott hozzá a meglévő SHA-1
tartalom alapú aláírások megerősítésére.

Más szóval egyetlen aláírást használtak arra, hogy mindkét hashfüggvénnyel
tanúsítsák az objektum tartalmát. Ennek voltak előnyei:

* Kettő helyett egy aláírás használata felgyorsítja az aláírási folyamatot.
* Egyetlen, mindkét hasht tartalmazó aláírt payload lehetővé teszi az aláírónak,
  hogy tanúsítsa, hogy a SHA-1 név és a SHA-256 név ugyanarra az objektumra mutat.
* Minden felhasználó ugyanazt az aláírást fogyasztja. A sérült aláírások
  valószínűleg gyorsan felfedeződnek a git jelenlegi verzióival.

Voltak azonban hátrányai is:

* Egy aláírt objektum ellenőrzéséhez hozzáférés kell az általa hivatkozott
  összes objektum SHA-1 nevéhez, még azután is, hogy az átállás befejeződött, és a
  fordítótáblára már semmi máshoz nincs szükség. Ennek támogatására a terv olyan
  mezőket adott hozzá, mint a "hash sha1 tree <SHA-1 név>" és a
  "hash sha1 parent <SHA-1 név>" egy aláírt commit SHA-256 tartalmához, ami
  bonyolította a konverziós folyamatot.
* Az SHA-1 nélküli aláírt objektumok engedélyezése (az átállás befejezése
  utáni időre) tovább bonyolította a tervet, és szükségessé tett egy "nohash sha1"
  mezőt a "hash sha1" mezők SHA-256 tartalomba és aláírt payloadba való
  belefoglalásának elnyomására.

[[_lazily_populated_translation_table]]
Lustán feltöltött fordítótábla
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A fordítótábla felépítésének egy része elhalasztható volna push időre, de ez
jelentősen bonyolítaná és lassítaná a pushokat.
A SHA-1 név kiszámítása az objektum létrehozásakor, azzal egy időben, hogy a
lemezre streamelik, és a SHA-256 nevének kiszámítása elfogadható költség
volna.

[[_document_history]]
Dokumentumtörténet
------------------

2017-03-03
bmwill@google.com, jonathantanmy@google.com, jrnieder@gmail.com,
sbeller@google.com

* Initial version sent to https://lore.kernel.org/git/20170304011251.GA26789@aiede.mtv.corp.google.com

2017-03-03 jrnieder@gmail.com
Incorporated suggestions from jonathantanmy and sbeller:

* Describe purpose of signed objects with each hash type
* Redefine signed object verification using object content under the
  first hash function

2017-03-06 jrnieder@gmail.com

* Use SHA3-256 instead of SHA2 (thanks, Linus and brian m. carlson).[1][2]
* Make SHA3-based signatures a separate field, avoiding the need for
  "hash" and "nohash" fields (thanks to peff[3]).
* Add a sorting phase to fetch (thanks to Junio for noticing the need
  for this).
* Omit blobs from the topological sort during fetch (thanks to peff).
* Discuss alternates, git notes, and git servers in the caveats
  section (thanks to Junio Hamano, brian m. carlson[4], and Shawn
  Pearce).
* Clarify language throughout (thanks to various commenters,
  especially Junio).

2017-09-27 jrnieder@gmail.com, sbeller@google.com

* Use placeholder NewHash instead of SHA3-256
* Describe criteria for picking a hash function.
* Include a transition plan (thanks especially to Brandon Williams
  for fleshing these ideas out)
* Define the translation table (thanks, Shawn Pearce[5], Jonathan
  Tan, and Masaya Suzuki)
* Avoid loose object overhead by packing more aggressively in
  "git gc --auto"

Later history:

* See the history of this file in git.git for the history of subsequent
  edits. This document history is no longer being maintained as it
  would now be superfluous to the commit log

References:

 [1] https://lore.kernel.org/git/CA+55aFzJtejiCjV0e43+9oR3QuJK2PiFiLQemytoLpyJWe6P9w@mail.gmail.com/
 [2] https://lore.kernel.org/git/CA+55aFz+gkAsDZ24zmePQuEs1XPS9BP_s8O7Q4wQ7LV7X5-oDA@mail.gmail.com/
 [3] https://lore.kernel.org/git/20170306084353.nrns455dvkdsfgo5@sigill.intra.peff.net/
 [4] https://lore.kernel.org/git/20170304224936.rqqtkdvfjgyezsht@genre.crustytoothpaste.net
 [5] https://lore.kernel.org/git/CAJo=hJtoX9=AyLHHpUJS7fueV9ciZ_MNpnEPHUz8Whui6g9F0A@mail.gmail.com/
