Large Object Promisors
======================

Amióta a Git létezik, a felhasználók folyamatosan panaszkodnak a nagy
fájlok Gitben való tárolásával kapcsolatos problémákra. Néhány megoldás
készült a segítségükre, de ezek nem sokat segítettek bizonyos gondokon.

A Git jelenleg támogatja a több promisor remote használatát, ami segíthetne
néhány megmaradt probléma megoldásában, de nagyon nehéz őket erre használni,
mert több fontos funkció is hiányzik.

Az ebben a dokumentumban leírt munka célja ezeknek a fontos funkcióknak a
hozzáadása.

„Large Object Promisor"-nak, röviden „LOP"-nak nevezünk egy olyan promisor
remote-ot, amelyet kizárólag nagy blobok tárolására használnak, és amely
külön van attól a fő remote-tól, amelynek a többi Git-objektumot és a repók
maradékát kellene tárolnia.

Kiterjesztve „Large Object Promisor"-nak, azaz LOP-nak nevezzük magát az
ebben a dokumentumban leírt munkát is, amely egy sor funkció hozzáadását
célozza, hogy a nagy blobok/fájlok kezelése a Gitben egyszerűbb legyen a
LOP-ok használatával.

Ez a munka különösen a szerveroldalon próbál javítani a helyzeten, és
különösen az olyan nagy blobok esetében, amelyek már bináris formátumban
tömörítve vannak.

Ez a munka egy alternatívát kíván nyújtani a Git LFS-hez
(https://git-lfs.com/) és a hasonló eszközökhöz, mint a git-annex
(https://git-annex.branchable.com/), a nagy fájlok kezelésére, még akkor is,
ha egy teljes értékű alternatíva nagyon valószínűen további munkát igényelne,
különösen a kliensoldalon, ahol valószínűleg segítene egy új objektum-
ábrázolás bevezetése a nagy blobokhoz, ahogyan itt szó esik róla:

https://lore.kernel.org/git/xmqqbkdometi.fsf@gitster.g/

[[_non_goals]]
Nem célok
---------

- Ezeket a kliensoldali fejlesztéseket itt nem tárgyaljuk, mivel a Git más
  részeiben igényelnének módosításokat, mint ez a munka.
+
Így nem állítjuk, hogy a Git LFS-t teljesen leváltjuk pusztán ezzel a
munkával, de mindazonáltal úgy hisszük, hogy jelentősen javíthat a jelenlegi
helyzeten a szerveroldalon, és hogy más, különálló munkák a kliensoldalon is
javíthatnának a helyzeten.

- Ugyanígy nem fogjuk végigvenni az összes lehetséges módot arra, hogyan
  valósítható meg egy LOP vagy annak alapját képező objektumtárolás, illetve
  hogyan optimalizálható a LOP működése.
+
A véleményünk szerint egyelőre a legegyszerűbb megoldás az, ha a LOP-ok egy
remote helperen keresztül (lásd a lenti II.2. szakaszt a részletekért)
használnak objektumtárolást az objektumaik tárolására. Ezért ezt tekintjük
az alapértelmezett megvalósításnak. Ha ezen felül vannak fejlesztések, az
nagyszerű, de a véleményünk szerint az ilyen fejlesztések nem szükségesek
ahhoz, hogy a LOP-ok már így is hasznosak legyenek. Az ilyen fejlesztések
valószínűleg más technikai téma, és külön is kezelhetők amúgy is.

- Így különösen nem fogunk cserélhető ODB-kről vagy más
  objektumadatbázis-backendekről beszélni, amelyek darabolhatnák a nagy
  blobokat, dedupolhatnák a darabokat és hatékonyan tárolhatnák őket. Igaz,
  ez szép javítás lenne a nagy blobok szerveroldali tárolására, de úgy
  hisszük, ez lehet egy különálló munka is, mivel technikailag sem nagyon
  kapcsolódik ehhez a munkához.
+
Az adatátviteli fejlesztéseket sem fogjuk tárgyalni a LOP-ok és a kliensek
vagy szerverek között. Igaz, lehetnek ott egyszerű és nagyon hatékony
optimalizációk (mivel tudjuk, hogy a LOP-okon lévő objektumok nagyon
valószínűen tömöríthetetlenek és rosszul deltásíthatók), de ez külön, egy
különálló munkában kezelhető.

Más szóval ennek a dokumentumnak a célja nem az, hogy az összes lehetséges
módról beszéljen, ahogyan a Git kezelhetné a nagy blobokat, hanem az, hogy
leírja, hogyan működhet már most is jól egy LOP-alapú megoldás, és hogyan
enyhítheti a jelenlegi problémák egy részét abban a kontextusban, ahol a Git
kliensei és szerverei Git-objektumokat osztanak meg egymással.

Még ha a LOP-okat nem is túl hatékonyan használják, bizonyos esetekben akkor
is hasznosak és érdemes használni őket, ahogyan a dokumentum későbbi
részében részletesebben látni fogjuk:

  - egyszerűbbé tehetik a kliensek számára a promisor remote-ok használatát,
    és így elkerülhető, hogy sok olyan nagy blobot fetcheljenek, amelyre
    lehet, hogy helyben nincs is szükségük,

  - jelentősen olcsóbbá vagy egyszerűbbé tehetik a szerverek számára a
    jelenlegi repository-tartalom jelentős részének kiszolgálását, sőt még
    inkább a nagyobb blobokat vagy több nagy blobot tartalmazó tartalom
    kiszolgálását, mint jelenleg.

[[_i_issues_with_the_current_situation]]
I A jelenlegi helyzet problémái
-------------------------------

- A GitLab-repókon készített statisztikák azt mutatták, hogy a lemezterület
  több mint 75%-át olyan blobok használják, amelyek 1MB-nál nagyobbak, és
  gyakran bináris formátumúak.

- Így még ha a felhasználók használhatnák is a Git LFS-t vagy hasonló
  eszközöket sok nagy blob repón kívüli tárolására, tény, hogy a gyakorlatban
  ezt nem teszik meg olyan mértékben, mint valószínűleg kellene.

- A szerveroldalon ideális esetben a szervernek magának kellene tudnia
  eldönteni, hogyan tárolja a dolgokat. Nem szabadna attól függnie, hogy a
  felhasználók úgy döntenek-e, hogy egyes blobokon használnak-e olyan
  eszközöket, mint a Git LFS, vagy sem.

- Sokkal drágább a rendszeres, gyors elérésű meghajtókon (mint az SSD-k)
  tárolni olyan nagy blobokat, amelyek nem delta-tömöríthetők jól, mint az
  objektumtárolón (mint az Amazon S3 vagy a GCP Buckets). A gyors meghajtók
  használata a rendszeres Git-repókhoz viszont észszerű, mivel a rendszeres
  Git-tartalom (szöveget vagy kódot tartalmazó blobok) kiszolgálásához olyan
  meghajtók kellenek, ahol a keresés gyors, de a tartalom viszonylag kicsi.
  Másrészről az objektumtárolás a Git LFS blobokhoz észszerű, mivel a
  keresési sebesség nem annyira fontos nagy fájlok kezelésekor, míg a
  költségek fontosabbak. Így az a tény, hogy a felhasználók nem használják a
  Git LFS-t vagy hasonló eszközöket jelentős számú nagy blobhoz, valószínűleg
  néhány rossz következménnyel jár a legtöbb Git-tárhelyplatform
  repository-tárolási költségeire nézve.

- Ha a nagy blobokat ugyanúgy kezeljük, mint a többi blobot és Git-objektumot
  a Git-repókban, ahelyett, hogy objektumtárolón lennének, annak a
  packfile-ok létrehozásakor megnövekedett memória- és CPU-használatban,
  és így csökkent teljesítményben is ára van. (Ez azért van, mert a Git
  megpróbál delta-tömörítést vagy zlib-tömörítést használni, ami valószínűen
  nem működik jól a már tömörített bináris tartalmon.) Így ez nem csupán a
  tárolási költség növekedése.

- Ha egy nagy blobot már commitoltak egy repóba, előfordulhat, hogy ezt a
  blobot nem lehet eltávolítani a repóból az előzmények átírása nélkül, még
  akkor sem, ha a felhasználó ezután úgy dönt, hogy a Git LFS-t vagy hasonló
  eszközt használ a kezeléséhez.

- Valójában a Git LFS és a hasonló eszközök nem túl rugalmasak abban, hogy a
  felhasználók meggondolhassák magukat azzal kapcsolatban, mely blobokat
  kellene kezelniük, és melyeket nem.

- Még amikor a felhasználók a Git LFS-t vagy hasonló eszközöket használnak,
  gyakran panaszkodnak, hogy ezek az eszközök jelentős erőfeszítést
  igényelnek a helyes beállításhoz, megtanuláshoz és használathoz.

[[_ii_main_features_of_the_large_object_promisors_solution]]
II A „Large Object Promisors" megoldás fő funkciói
--------------------------------------------------

Az alábbi fő funkcióknak nagyjából áttekintést kell adniuk arról, hogyan
működhet a megoldás. A szükséges elemek részleteit a következő szakaszokban
találod.

Bár az alábbi minden funkció nagyon hasznos a teljes megoldáshoz, nagyon
valószínű, hogy önmagában is hasznos bizonyos esetekben, amikor a teljes
megoldásra nincs szükség. Itt azonban elsősorban a nagy képre koncentrálunk.

Továbbá minden funkciót nem kell teljes egészében magában a Gitben
megvalósítani. Néhány lehet szkript, hook vagy helper, amely nem része a Git
repónak. Hasznos lenne viszont, ha ezeket meg lehetne osztani és
együttműködésben javítani. Ezért szeretnénk bátorítani a megosztásukat.

[[_1_large_blobs_are_stored_on_lops]]
1) A nagy blobokat LOP-okon tárolják
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A nagy blobokat speciális promisor remote-okon kellene tárolni, amelyeket
„Large Object Promisors"-nak vagy LOP-oknak fogunk nevezni. Ezeknek a
LOP-oknak további remote-oknak kellene lenniük, amelyek a nagy blobok,
különösen a bináris formátumúak tárolására szolgálnak. Olyan fő remote-okkal
együtt kellene őket használni, amelyek a többi objektumot tartalmazzák.

Note 1
^^^^^^

Pontosításképpen: egy LOP egy normál promisor remote, kivéve hogy:

- kizárólag nagy blobokat kellene tárolnia,

- külön kellene lennie a fő remote-tól, hogy a fő remote a többi objektum és
  a repók maradékának kiszolgálására koncentrálhasson (lásd lent a 4)
  funkciót), és magához a fő remote-hoz is használhassa a LOP-ot promisor
  remote-ként.

Note 2
^^^^^^

A Git már most is lehetővé teszi, hogy egy fő remote egyben promisor remote
is legyen, amely rendszeres objektumokat és nagy blobokat is tárol egy olyan
kliens számára, amely blobméret-szűrővel klónoz róla. De itt kifejezetten el
akarjuk kerülni ezt.

Rationale
^^^^^^^^^

A LOP-ok célja, hogy jók legyenek a nagy blobok kezelésében, míg a fő
remote-ok már jók a többi objektum kezelésében.

Implementation
^^^^^^^^^^^^^^

A Git már most is támogatja a több promisor remote-ot, lásd
link:partial-clone.html#using-many-promisor-remotes[a partial clone
dokumentációját].

Továbbá a Git már most is támogatja a partial clone-t a blobok méretére
alkalmazott szűrővel (a `git clone --filter=blob:limit=<size>` paranccsal).
Az alábbi többi fő funkció nagy része ezekre a meglévő funkciókra épül, és
arról szól, hogy egyszerűvé és hatékonnyá tegye a használatukat a nagy blobok
jobb kezelésének céljából.

[[_2_lops_can_use_object_storage]]
2) A LOP-ok használhatnak objektumtárolást
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A LOP-ok objektumtárolással valósíthatók meg, mint egy Amazon S3 vagy GCP
Bucket vagy MinIO (amely nyílt forráskódú a GNU AGPLv3 licenc alatt), a nagy
blobok tényleges tárolására, és egy Git remote helperen keresztül érhetők el
(lásd linkgit:gitremote-helpers[7]), amely az alapját képező
objektumtárolást remote-ként jeleníti meg a Git felé.

Note
^^^^

Egy LOP lehet promisor remote, amelyet remote helperen keresztül ér el
egyes kliensek és a fő remote is.

Rationale
^^^^^^^^^

Ez tűnik a legegyszerűbb módnak olyan LOP-ok létrehozására, amelyek olcsón
kezelhetnek sok nagy blobot.

Implementation
^^^^^^^^^^^^^^

A remote helpereket elég egyszerű shellszkriptként megírni, de hatékonyabb
és karbantarthatóbb lehet más nyelveken, például Go-ban megírni őket.

Néhány már létezik nyílt forráskódú licencek alatt, például:

  - https://github.com/awslabs/git-remote-s3
  - https://gitlab.com/eric.p.ju/git-remote-gs

A LOP-ok megvalósításának más módjai bizonyosan lehetségesek, de ennek a
dokumentumnak nem célja megvitatni, hogyan valósítható meg legjobban egy LOP
vagy az alapját képező objektumtárolás (lásd a fenti „0) Nem célok"
szakaszt).

[[_3_lop_object_storage_can_be_git_lfs_storage]]
3) A LOP objektumtárolása lehet Git LFS-tárolás
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Az alapját képező objektumtárolás, amelyet egy LOP használ, a Git LFS által
kezelt nagy fájlok tárolójaként is szolgálhatna.

Rationale
^^^^^^^^^

Ez egyszerűsítené a szerveroldalt, ha az egyszerre akar LOP-ot használni és
Git LFS-szerverként működni.

[[_4_a_main_remote_can_offload_to_a_lop_with_a_configurable_threshold]]
4) Egy fő remote konfigurálható küszöbértékkel kihelyezhet egy LOP-ra
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A szerveroldalon egy fő remote-nak kellene, hogy legyen módja arra, hogy egy
LOP-ra kihelyezze az összes olyan blobját, amelynek a mérete egy
konfigurálható küszöbérték felett van.

Rationale
^^^^^^^^^

Ez egyszerűvé teszi a dolgok beállítását és megtisztítását. Például egy admin
ezt használhatná egy LOP-ot nem használó repó kézzel történő átalakítására
LOP-ot használó repóvá. Egy olyan repón, amely már használ LOP-ot, de ahol
egyes felhasználók néha nagy blobokat pusholnak, egy cron job ezt
használhatná annak rendszeres biztosítására, hogy a nagy blobok átkerüljenek
a LOP-ra.

Implementation
^^^^^^^^^^^^^^

Valami olyasmi használata, ami a `git repack --filter=...`-ra épül, hogy
elkülönítse a kihelyezni kívánt blobokat a többi Git-objektumtól, jó ötlet
lehet. A hiányzó rész az, hogy csatlakozzon a LOP-hoz, ellenőrizze, hogy a
kihelyezni kívánt blobok már ott vannak-e, és ha nem, elküldje őket.

[[_5_a_main_remote_should_try_to_remain_clean_from_large_blobs]]
5) Egy fő remote-nak igyekeznie kell nagy bloboktól mentesnek maradni
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Egy fő remote-nak igyekeznie kell elkerülni, hogy sok túlméretes blobot
tartalmazzon. Ebből a célból szükség szerint kihelyez egy LOP-ra, és
rendelkeznie kell módokkal a túlméretes blobok fetchelésének, és talán
pusholásának a megakadályozására is.

Rationale
^^^^^^^^^

Egy sok túlméretes blobot tartalmazó fő remote meghiúsítaná a LOP-ok
célját.

Implementation
^^^^^^^^^^^^^^

A fenti 4)-ben tárgyalt, LOP-ra való kihelyezés módja használható a
túlméretes blobok rendszeres kihelyezésére. A túlméretes blobok repóba
fetchelésének megakadályozásáról lásd lent a 6)-ot. A túlméretes blobok
pusholásának megakadályozásáról: egy pre-receive hook használható lenne.

Vannak továbbá különböző forgatókönyvek, amelyekben nagy blobok kerülhetnek
be fetcheléssel a fő remote-ba, például:

- Egy kliens, amely nem valósítja meg a „promisor-remote" protokollt (leírva
  a lenti 6)-ban), klónoz a fő remote-ról.

- A fő remote kérést kap egy nagy blobbal kapcsolatos információért, és nem
  tudja megszerezni azt az információt anélkül, hogy a blobot fetchelné a
  LOP-ról.

Lehet, hogy nem lehet teljesen megakadályozni, hogy ezek a forgatókönyvek
bekövetkezzenek. Ezért itt a cél az kellene legyen, hogy olyan funkciókat
valósítsunk meg, amelyek kevésbé valószínűvé teszik a nagy blobok
fetchelését. Például egy `remote-object-info` parancs hozzáadása a
`git cat-file --batch` protokollhoz és annak változataihoz lehetővé tehetné,
hogy egy fő repó néhány nagy blobbal kapcsolatos kérésre válaszoljon anélkül,
hogy fetchelné őket.

[[_6_a_protocol_negotiation_should_happen_when_a_client_clones]]
6) Protokollegyeztetésnek kell történnie, amikor egy kliens klónoz
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Amikor egy kliens klónoz egy fő repóról, protokollegyeztetésnek kell
történnie, hogy a szerver hirdethessen egy vagy több LOP-ot, és hogy a
kliens és a szerver megvitathassa, használhatná-e a kliens közvetlenül a
szerver által hirdetett LOP-ot. Ha a kliens és a szerver meg tud egyezni
ebben, akkor a kliens képes lenne a nagy blobokat közvetlenül a LOP-ról
megszerezni, és a szervernek nem kellene ezeket a blobokat a LOP-ról
fetchelnie ahhoz, hogy kiszolgálja a klienst.

Note
^^^^

Fetchek esetén, klónozás helyett, nem mindig történik feltétlenül
protokollegyeztetés, lásd lent a „Mi a helyzet a fetchekkel?" GYIK-bejegyzést
a részletekért.

Rationale
^^^^^^^^^

A dolgok beállításának biztonsága, konfigurálhatósága és hatékonysága.

Implementation
^^^^^^^^^^^^^^

Egy „promisor-remote" protocol v2 képesség jó módnak tűnik ennek
megvalósítására. Azt, ahogyan a kliens és a szerver ezt a képességet
használja, konfigurációs változók vezérelhetnék.

Az információ, amelyet a szerver a kliensnek ezen a protokollon keresztül
küldhetne, olyasmi lehetne, mint: LOP neve, LOP URL-je, filter-spec (például
`blob:limit=<size>`) vagy csak méretkorlát, amelyet szűrőként kell használni
klónozáskor, a LOP-pal használandó token stb.

[[_7_a_client_can_offload_to_a_lop]]
7) Egy kliens kihelyezhet egy LOP-ra
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Amikor egy kliens olyan LOP-ot használ, amely a fő remote-jának is LOP-ja, a
kliensnek képesnek kellene lennie néhány olyan nagy blob kihelyezésére a
LOP-ra, amelyet fetchelt, de esetleg már nincs rá szüksége.

Note
^^^^

Kontextusfüggő lehet, hogy rendben van-e vagy sem, hogy a kliensek az általuk
létrehozott – nem pedig fetchelt – nagy blobokat közvetlenül a LOP-ra
helyezzék ki anélkül, hogy a fő remote valamilyen módon (esetleg hookok vagy
más eszközök használatával) ellenőrizné őket.

Ezt meg kell vitatni és pontosítani kell, amikor közelebb kerülünk ennek a
funkciónak a megvalósításához.

Rationale
^^^^^^^^^

A kliensen a felesleges nagy blobok kezelésének legegyszerűbb módja a
kihelyezésük.

Implementation
^^^^^^^^^^^^^^

Ez nagyon hasonló ahhoz, amiről a fenti 4) szól, csak a kliensoldalon a
szerveroldal helyett. Így a 4)-re adott jó megoldás valószínűleg
átalakítható lenne, hogy a kliensoldalon is működjön.

Lehetnek itt biztonsági problémák, mivel nincs egyeztetés, de ezek
enyhíthetők, ha a kliens újra felhasználhat egy tokent, amelyet klónozáskor
kapott (lásd a fenti 6)-ot). Továbbá, ha a nagy blobokat egy LOP-ról
fetchelték, valószínű, és könnyen megerősíthető, hogy a LOP-nak még mindig
megvannak, így egyszerűen eltávolíthatók a kliensről.

[[_iii_benefits_of_using_lops]]
III A LOP-ok használatának előnyei
----------------------------------

Sok előny kapcsolódik a fenti „I) A jelenlegi helyzet problémái" részben
tárgyalt problémákhoz:

- Nem kell átírni az előzményeket, amikor eldöntjük, mely blobokat érdemes a
  többi objektumtól elkülönítve kezelni, illetve amikor a küszöbértéket
  áthelyezzük vagy eltávolítjuk.

- Ha a kliens és a szerver közötti protokoll eléggé kidolgozott és biztonságos,
  akkor sok részletet csak a szerveroldalon lehetne beállítani, és az összes
  kliens könnyen megszerezhetné az összes konfigurációs információt, és
  felhasználhatná arra, hogy nagyrészt automatikusan beállítsa magát.

- Tárolási költségbeli előnyök a szerveroldalon.

- Csökkentett memória- és CPU-igény a szerveroldali fő remote-okon.

- Csökkentett tárolási igény a kliensoldalon.

[[_iv_faq]]
IV GYIK
-------

Mi a helyzet több LOP használatával a szerver- és a kliensoldalon?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ez talán hasznos lehetne bizonyos esetekben, de egyelőre valószínűbb, hogy a
legtöbb esetben egyetlen LOP-ot fog hirdetni a szerver, és azt kellene
használnia a kliensnek.

Egy olyan eset, ahol hasznos lehetne, hogy egy szerver több LOP-ot hirdessen,
az, ha egy LOP jobb egyes felhasználóknak, míg egy másik LOP jobb más
felhasználóknak. Például egyes kliensek jobb kapcsolattal rendelkezhetnek egy
LOP-hoz, mint mások.

Ezekben az esetekben a szerver felelőssége, hogy legyen valamennyi
dokumentációja a kliensek segítésére. Mondhatná például valami olyasmit, hogy
„A világ ezen részén lévő felhasználók talán csak a LOP A-t akarják
választani, mivel valószínűleg jobb kapcsolatuk van vele, míg a világ más
részein lévő felhasználók ugyanezért csak a LOP B-t válasszák."

Mikor bízzunk meg és mikor ne a szerver által hirdetett LOP-okban?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bizonyos kontextusokban, például egy vállalati környezetben, ahol a szerver
és az összes kliens egy cég belső hálózatának része, ahol az adminoknak
minden joguk megvan minden rendszerhez, rendben van, sőt talán jó dolog, ha
a kliensek teljesen megbíznak a szerverben, mivel ez segíthet biztosítani,
hogy az összes kliens azonos állapotban legyen.

Vannak olyan kontextusok is, amelyekben a kliensek megbíznak egy
kódtárhely-platformban, amely néhány repót szolgál ki nekik, de esetleg nem
bíznak meg teljesen más felhasználókban, akik ezen repók egy részét kezelik
vagy hozzájárulnak hozzájuk. Például a kódtárhely-platformon lehetnének
hookok, amelyek ellenőrzik, hogy egyetlen általa kapott objektum sem
tartalmaz malware-t vagy egyéb rossz tartalmat. Ebben az esetben rendben
lehet, hogy a kliens egy fő remote-ot és annak LOP-ját használja, ha mindkettőt
a kódtárhely-platform üzemelteti, de nem, ha a LOP-ot máshol üzemeltetik
(ahol a tartalmat nem ellenőrzik).

Más kontextusokban egy kliensnek egyszerűen nem szabadna megbíznia egy
szerverben.

Ezért kellene, hogy különböző módok legyenek annak beállítására, hogyan
viselkedjen a kliens, amikor egy szerver LOP-ot hirdet neki klónozáskor.

Mivel az alapvető elemek, amelyeket egy szerver hirdethet egy LOP-ról, egy
LOP-név és egy LOP-URL, a kliensnek ezekre az elemekre kellene alapoznia a
LOP elfogadásáról szóló döntését.

Egy egyszerű mód arra, hogy nagyon szigorú legyen abban, mely LOP-ot fogadja
el, például az, hogy a kliens ellenőrzi, hogy a LOP már ugyanazzal a névvel
és URL-lel van-e konfigurálva a kliensen, mint amit a szerver hirdet.

Általánosságban az alapértelmezett és „biztonságos" beállításoknak meg
kellene követelniük, hogy a LOP-ok a kliensen a „promisor-remote"
protokolltól elkülönítve legyenek konfigurálva, és hogy a kliens csak akkor
fogadjon el egy LOP-ot, amikor a protokollból származó információ egyezik
azzal, amit korábban külön konfiguráltak.

Mi a helyzet a LOP-nevekkel?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bizonyos kontextusokban, például ha a kliensek néha egymástól fetchelnek, jó
ötlet lehet, hogy az összes kliens ugyanazokat a neveket használja az összes
általuk használt remote-hoz, beleértve a LOP-okat is.

Más kontextusokban minden kliens talán olyan nevet szeretne adni minden
remote-nak, beleértve minden LOP-ot, amellyel kapcsolatba lép.

Ezért kellene, hogy különböző módok legyenek annak beállítására, hogyan
fogadja el vagy sem a kliens a szerver által hirdetett LOP-nevet.

Ha alapértelmezett vagy „biztonságos" beállítást használnak, akkor mivel egy
ilyen beállításnak meg kellene követelnie, hogy a LOP külön legyen
konfigurálva, a név külön lenne konfigurálva, és nincs kockázata annak, hogy
a szerver nevet diktálhatna egy kliensnek.

Elárasztódhatna a fő remote régi vagy paranoiás kliensektől?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Igen, megtörténhetne, ha túl sok olyan kliens van, amely vagy nem hajlandó
megbízni a fő remote-ban, vagy egyszerűen nem valósítja meg a
„promisor-remote" protokollt, mert túl régi vagy nem teljesen kompatibilis a
'git' klienssel.

Egy ilyen kliens kiszolgálásakor a fő remote-nak nincs más választása, mint
hogy először a LOP-járól fetcheljen, hogy aztán mindent biztosítani tudjon a
kliensnek, amit kért. Így a fő remote, még ha vannak is takarítási
mechanizmusai (lásd a fenti II.4. szakaszt), legalább átmenetileg
megterhelődne azokkal a nagy blobokkal, amelyeket a LOP-járól kellett
fetchelnie.

Ha nem így viselkedne, az megtörné a visszafelé kompatibilitást, és a
kliensek szegregálásának lehetne tekinteni. Például lehetne megvalósítani egy
speciális módot, amely lehetővé teszi a szervernek, hogy egyszerűen
elutasítsa azokat a klienseket, amelyek nem valósítják meg a „promisor-remote"
protokollt, vagy nem hajlandók megbízni a fő remote-ban. Ez a mód hasznos
lehet egy speciális kontextusban, mint egy vállalati környezet. Nincs
azonban terv egy ilyen mód megvalósítására, és ezt amúgy is külön kellene
megvitatni később.

Egy jobb módszer valószínűleg az, ha a fő remote üzenetet jelenít meg,
amely elmondja a protokollt nem megvalósító vagy a hirdetett LOP-(ok)at
elfogadni nem hajlandó klienseknek, hogy gyorsabb klónozást és fetcheket
kapnának, ha frissítenék a kliensszoftvert, vagy megfelelően beállítanák
őket a LOP-(ok) elfogadására.

A kliensek frissítésére való várakozás, ezeknek a frissítéseknek a
figyelése, és a LOP-ok használatának korlátozása a nem túl gyakran elért
repókra más jó módok lehetnek annak biztosítására, hogy még mindig legyen
valamennyi haszon a LOP-okból. Idővel, ahogy egyre több kliens frissül és
profitál a LOP-okból, egyre gyakrabban elért repókban is megéri majd
használni őket.

A vállalati környezetek, ahol talán könnyebb biztosítani, hogy az összes
kliens naprakész és megfelelően konfigurált legyen, remélhetőleg többet és
korábban profitálhatnának a LOP-ok használatából.

Mi a helyzet a fetchekkel?
~~~~~~~~~~~~~~~~~~~~~~~~~~

Különböző fajta fetchek vannak. Egy rendszeres fetch akkor történik, amikor
néhány refet frissítettek a szerveren, és a kliens szeretné a
ref-frissítéseket és esetleg a velük hozzáadott új objektumokat. Egy
„backfill" vagy „lazy" fetch ezzel szemben akkor történik, amikor a
kliensnek olyan objektumokat kell használnia, amelyekről már tud, de nincsenek
meg neki, mert egy promisor remote-on vannak.

Rendszeres fetch
^^^^^^^^^^^^^^^^

Egy rendszeres fetchnél a kliens kapcsolatba lép a fő remote-tal, és
protokollegyeztetés történik közöttük. Jó dolog, hogy minden alkalommal
történik protokollegyeztetés, mivel a kliensen vagy a fő remote-on a
konfiguráció megváltozhatott az előző protokollegyeztetés óta. Ebben az
esetben az új protokollegyeztetésnek biztosítania kellene, hogy az új fetch
olyan módon történjen, amely kielégíti a kliens és a szerver új
konfigurációját is.

A legtöbb esetben azonban a kliensen és a fő remote-on lévő konfiguráció nem
változott meg 2 fetch között, vagy a kezdeti klónozás és egy későbbi fetch
között. Ez azt jelenti, hogy egy új protokollegyeztetés eredménye ugyanaz
lesz, mint az előző eredmény, így az új fetch ugyanúgy fog történni, mint az
előző klónozás vagy fetch, ugyanazt a LOP-(ot)at használva vagy nem
használva, mint legutóbb.

„Backfill" vagy „lazy" fetch
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Amikor backfill fetch van, a kliens nem feltétlenül lép először kapcsolatba a
fő remote-tal. Megpróbál a promisor remote-jairól fetchelni abban a
sorrendben, ahogyan a konfigurációs fájlban megjelennek, kivéve hogy egy
`extensions.partialClone` konfigurációs változóval konfigurált remote-ot
próbál utoljára. Lásd
link:partial-clone.html#using-many-promisor-remotes[a partial clone
dokumentációját].

Ez nem újdonság ezzel a munkával. Valójában így működik a több remote már
körülbelül 5 éve.

LOP-ok használatakor észszerű, ha a fő remote `extensions.partialClone`-nal
van konfigurálva, hogy utoljára próbálódjon, mivel a hiányzó objektumok csak
LOP-okon lévő nagy blobok lehetnek.

Ez azt jelenti, hogy valószínűleg nem történik protokollegyeztetés, mivel a
hiányzó objektumokat a LOP-okról fogják fetchelni, és akkor nem marad semmi,
amit a fő remote-ról kellene fetchelni.

Ennek biztosítására jó ötlet lehetne, ha a LOP-ok tokent követelnének meg a
klienstől, amikor tőlük fetchel. A kliens megkaphatná a tokent, amikor
protokollegyeztetést végez a fő remote-tal (lásd a fenti II.6. szakaszt).

[[_v_future_improvements]]
V Jövőbeli fejlesztések
-----------------------

Várható, hogy az elején a LOP-ok használata leginkább vagy egy vállalati
kontextusban éri majd meg, ahol a kliensek által használt Git-verzió
könnyen szabályozható, vagy a ritkán elért repókon. (Lásd az „Elárasztódhatna
a fő remote régi vagy paranoiás kliensektől?" szakaszt a fenti GYIK-ban.)

Idővel, ahogy egyre több kliens frissül olyan verzióra, amely megvalósítja a
fent, a II.6) szakaszban leírt „promisor-remote" protocol v2 képességet,
megéri majd szélesebb körben használni a LOP-okat.

Sok fejlesztés is segíthet a LOP-ok szélesebb körű használatában. Ezeknek a
fejlesztéseknek egy része ennek a dokumentumnak a hatókörébe tartozik, mint a
következők:

  - Egy „remote-object-info" parancs megvalósítása a
    `git cat-file --batch` protokollban és annak változataiban, hogy a fő
    remote-ok válaszolni tudjanak a nagy blobokkal kapcsolatos kérésekre
    anélkül, hogy fetchelnék őket. (Eric Ju elkezdett ezen dolgozni Calvin
    Wan korábbi munkája alapján.)

  - Jobb takarítási és kihelyezési mechanizmusok létrehozása a fő remote-ok
    és a kliensek számára, hogy megelőzzék a nagy blobok felhalmozódását.

  - Kifinomultabb protokollegyeztetési képességek kifejlesztése a kliensek és
    a szerverek között a LOP-ok kezelésére, például egy filter-spec (pl.
    blob:limit=<size>) vagy méretkorlát hozzáadása a klónozáskori szűréshez,
    vagy egy token hozzáadása a LOP-hitelesítéshez.

  - A LOP-eléréshez tartozó biztonsági intézkedések javítása, különösen a
    tokenkezelés és a hitelesítés körül.

  - Szabványosított módok kifejlesztése több LOP konfigurálására és
    kezelésére különböző környezetekben. Különösen abban az esetben, amikor
    különböző LOP-ok ugyanazt a tartalmat szolgálják ki klienseknek különböző
    földrajzi helyeken, szükség van a LOP-ok közötti replikációra vagy
    szinkronizációra.

Néhány fejlesztés, beleértve néhányat, amelyet a dokumentum „0) Nem célok"
szakaszában említettünk, ennek a dokumentumnak a hatókörén kívül esik:

  - Egy új objektumábrázolás megvalósítása a nagy blobokhoz a kliensoldalon.

  - Cserélhető ODB-k vagy más objektumadatbázis-backendek kifejlesztése,
    amelyek darabolhatnák a nagy blobokat, dedupolhatnák a darabokat és
    hatékonyan tárolhatnák őket.

  - Az adatátvitel optimalizálása a LOP-ok és a kliensek/szerverek között,
    különösen a tömöríthetetlen és nem deltásítható tartalom esetében.

  - Jobb kliensoldali eszközök létrehozása a nagy objektumok hatékonyabb
    kezelésére, például eszközök a Git LFS-ről vagy a git-annexről való
    átálláshoz, vagy eszközök annak megállapítására, mely objektumokat
    lehetne kihelyezni, és mennyi lemezterület nyerhető vissza a
    kihelyezésükkel.

Néhány fejlesztés a dokumentum hatókörének részének tekinthető, de esetleg
már saját, a Git-projekttől különálló projektjük van, mint:

  - Meglévő remote helperek javítása az objektumtárolás eléréséhez, vagy
    újak kifejlesztése.

  - Meglévő objektumtárolási megoldások javítása, vagy újak kifejlesztése.

Bár az összes fenti fejlesztés segíthet, ennek a dokumentumnak és a LOP-
munkának legalább először egy viszonylag kis számú fejlesztésre kellene
próbálnia koncentrálni, leginkább azokra, amelyek a jelenlegi hatókörébe
tartoznak.

Például a cserélhető ODB-k és egy új objektumadatbázis-backend bevezetése
valószínűleg önmagában is több éves munka, amely külön, párhuzamosan
történhet. Más technikai követelményei vannak, a Git kódbázis más részét
érinti, és saját tervdokumentum(ok)nak kellene lennie hozzá.
