Hosszú életű folyamatok protokollja
===================================

Ezt a protokollt akkor használja a Git, amikor egyetlen Git-parancs teljes
élettartama alatt egy külső folyamattal kell kommunikálnia. A teljes
kommunikáció pkt-line formátumban zajlik (lásd: linkgit:gitprotocol-common[5])
a szabványos bemeneten és a szabványos kimeneten keresztül.

[[_handshake]]
Kézfogás
--------

A Git egy üdvözlőüzenet elküldésével kezd (például
"git-filter-client"), majd elküldi a támogatott protokollverzió-számok listáját és
egy flush csomagot. A Git azt várja, hogy az üdvözlőüzenetben "client"
helyett "server" szerepeljen (például "git-filter-server"), pontosan egy
protokollverzió-szám a korábban elküldött listából, valamint egy flush
csomag. Minden további kommunikáció a kiválasztott verzión alapul.
Az alábbi protokollleírás hátralévő része a "version=2" változatot dokumentálja. Vedd
figyelembe, hogy az alábbi példában szereplő "version=42" nem létezik, csak
azt hivatott illusztrálni, hogyan nézne ki a protokoll egynél több
verzió esetén.

A verzióegyeztetés után a Git elküldi az összes általa támogatott
képesség listáját és egy flush csomagot. A Git azt várja, hogy válaszul
beolvashassa a kívánt képességek listáját, amelynek a támogatott képességek
listájának részhalmazát kell alkotnia, és egy flush csomagot:

------------------------
packet:          git> git-filter-client
packet:          git> version=2
packet:          git> version=42
packet:          git> 0000
packet:          git< git-filter-server
packet:          git< version=2
packet:          git< 0000
packet:          git> capability=clean
packet:          git> capability=smudge
packet:          git> capability=not-yet-invented
packet:          git> 0000
packet:          git< capability=clean
packet:          git< capability=smudge
packet:          git< 0000
------------------------

[[_shutdown]]
Leállítás
---------

A Git kilépéskor lezárja
a parancscsövet. A szűrőtől azt várjuk, hogy érzékelje az EOF-ot,
és magától, rendben lépjen ki. A Git megvárja, amíg a szűrő
folyamat leáll.
