A multi-pack-index (MIDX) tervezési jegyzetei
=============================================

A Git objektumkönyvtár tartalmaz egy 'pack' könyvtárat, amely
packfile-okat (".pack" utótaggal) és pack-indexeket (".idx"
utótaggal) tartalmaz. A pack-indexek módot adnak az objektumok
keresésére és a packen belüli eltolásukhoz való navigálásra, de ezeknek
párban kell lenniük a packfile-okkal. Ez a párosítás a fájlneveken
múlik, mivel a pack-index csak az utótagjában különbözik a pack-
fájljától. Bár a pack-indexek packfile-onként gyors keresést biztosítanak,
ez a teljesítmény romlik, ahogy a packfile-ok száma nő,
mert a rövidítéseknek minden packfile-t meg kell vizsgálniuk, és
nagyobb az esély a találat hiányára a legutóbb használt packfile-unkban.
Néhány nagy repository esetén az egyetlen packfile-ba történő újracsomagolás
nem kivitelezhető a tárhely vagy a túlzott újracsomagolási idők miatt.

A multi-pack-index (röviden MIDX) az objektumok listáját és a
több packfile-on belüli eltolásaikat tárolja. A következőket tartalmazza:

* A packfile-nevek listája.
* Az objektumazonosítók rendezett listája.
* Metaadatok listája az i. objektumazonosítóhoz, ideértve:
** Egy j értéket, amely a j. packfile-ra hivatkozik.
** Az objektum eltolását a j. packfile-on belül.
* Ha nagy eltolásokra van szükség, egy másik listát használunk a nagy
  eltolásokhoz, hasonlóan a 2-es verziójú pack-indexekhez.
- Az objektumok opcionális listája pszeudo-pack sorrendben (MIDX-bittérképekkel használva).

Így bármennyi packfile esetén O(log N) keresési időt tudunk
biztosítani.

[[_design_details]]
Tervezési részletek
-------------------

- A MIDX a .git/objects/pack könyvtárban egy 'multi-pack-index' nevű
  fájlban van tárolva. Ez egy alternate pack könyvtárában is
  tárolható. Csak az ugyanabban a könyvtárban lévő packfile-okra
  hivatkozik.

- A MIDX-fájlok felhasználásához a core.multiPackIndex konfigurációs
  beállításnak be kell kapcsolva lennie (ami az alapértelmezett).  Ha `false`
  értékre állítjuk, az megakadályozza, hogy a Git beolvasson egy MIDX-fájlt, még ha létezik is.

- A fájlformátum tartalmazza az objektumazonosító-hashfüggvény
  paramétereit, így a hash-algoritmus jövőbeli megváltoztatása nem igényel
  formátumváltoztatást.

- A MIDX objektumazonosítónként csak egy rekordot tart nyilván. Ha egy objektum
  több packfile-ban is megjelenik, akkor a MIDX a preferált packfile-ban lévő
  példányt választja, egyébként a legutóbb módosított packfile-ból
  választ.

- Ha a pack könyvtárban vannak olyan packfile-ok, amelyek nincsenek
  regisztrálva a MIDX-ben, akkor azok a packfile-ok betöltődnek a `packed_git`
  listába és a `packed_git_mru` gyorsítótárba.

- A pack-indexek (.idx fájlok) a pack könyvtárban maradnak, így törölhetjük a
  MIDX-fájlt, a core.midx értékét false-ra állíthatjuk, vagy visszaválthatunk egy
  régebbi verzióra bármilyen információvesztés nélkül.

- A MIDX-fájlformátum darab-alapú (chunk) megközelítést használ (hasonlóan a
  commit-graph fájlhoz), amely lehetővé teszi opcionális adatok hozzáadását.

[[_incremental_multi_pack_indexes]]
Inkrementális multi-pack indexek
--------------------------------

Ahogy a repository-k mérete nő, egyre költségesebbé válik olyan
multi-pack indexet (MIDX) írni, amely az összes packfile-t tartalmazza. Ennek
kezelésére az „inkrementális multi-pack indexek" funkció lehetővé teszi multi-pack
indexek „láncának" kombinálását.

A lánc minden egyes komponensének csak kevés packfile-t kell tartalmaznia.
A lánchoz való hozzáfűzés nem érvényteleníti a lánc korábbi részeit,
így a repository-k szabályozhatják, mennyi időt fordítanak a MIDX-lánc
frissítésére azzal, hogy meghatározzák a MIDX-lánc egyes rétegeiben lévő
packek számát.

[[_design_state]]
=== Tervezési állapot

Jelenleg az inkrementális multi-pack indexek funkcióból két
fontos komponens hiányzik:

  - Annak lehetősége, hogy a MIDX-lánc korábbi részeit újraírjuk (vagyis
    hogy egymással szomszédos MIDX-rétegek egy gyűjteményét egyetlen MIDX-be
    „tömörítsük"). Jelenleg a MIDX-lánc zsugorításának egyetlen támogatott
    módja az, hogy a teljes láncot a nulláról újraírjuk a `--split`
    kapcsoló nélkül.
+
Nincsenek alapvető korlátok, amelyek megakadályoznák ennek a funkciónak a
megvalósítását. A kezdeti implementációból a bonyolultság csökkentése
érdekében marad ki, de később hozzáadásra kerül.

  - Az elérhetőségi bittérképek támogatása. A klasszikus, egyetlen MIDX-es
    implementáció támogatja az elérhetőségi bittérképeket (részletekért lásd a
    "multi-pack-index reverse indexes" című szakaszt a
    linkgit:gitformat-pack[5] dokumentumban).
+
Mint fentebb, itt sincsenek alapvető korlátok, amelyek megakadályoznák, hogy az
inkrementális MIDX-formátumot kiterjesszük az elérhetőségi bittérképek támogatására.
Az alábbi terv kifejezetten figyelembe veszi ezt, és az elérhetőségi
bittérképek támogatása egy jövőbeli patchsorozatban kerül hozzáadásra. A
jelenlegi implementációból a fentivel azonos okból marad ki.
+
Röviden, ahhoz, hogy az inkrementális MIDX funkcióval támogassuk az
elérhetőségi bittérképeket, a pszeudo-pack sorrend fogalma az
inkrementális MIDX-lánc minden rétegére kiterjesztésre kerül, hogy
összefűzött pszeudo-pack sorrendet alkosson. Ez az összefűzés ugyanabban
a sorrendben történik, mint maga a lánc (más szóval a `{$H1, $H2, $H3}`
lánc összefűzött pszeudo-pack sorrendje a `$H1` pszeudo-pack sorrendje,
amelyet a `$H2` pszeudo-pack sorrendje követ, majd a `$H3` pszeudo-pack
sorrendje).
+
Ezután az elrendezés kiterjesztésre kerül, hogy az inkrementális MIDX-lánc minden
rétege írhasson egy `*.bitmap`-et. Az egyes rétegek bittérképében lévő objektumokat
a lánc korábbi rétegeiben lévő objektumok száma tolja el.

[[_file_layout]]
=== Fájlelrendezés

Ahelyett, hogy egyetlen `multi-pack-index` fájlt tárolnánk (opcionális `.rev` és
`.bitmap` kiterjesztéssel) a `$GIT_DIR/objects/pack` helyen, az inkrementális
MIDX-ek a következő elrendezésben tárolódnak:

----
$GIT_DIR/objects/pack/multi-pack-index.d/
$GIT_DIR/objects/pack/multi-pack-index.d/multi-pack-index-chain
$GIT_DIR/objects/pack/multi-pack-index.d/multi-pack-index-$H1.midx
$GIT_DIR/objects/pack/multi-pack-index.d/multi-pack-index-$H2.midx
$GIT_DIR/objects/pack/multi-pack-index.d/multi-pack-index-$H3.midx
----

A `multi-pack-index-chain` fájl a lánc inkrementális MIDX-fájljainak
sorrendbe rendezett listáját tartalmazza. A fenti példa egy olyan láncot mutat, amelynek
`multi-pack-index-chain` fájlja a következő sorokat tartalmazná:

----
$H1
$H2
$H3
----

A `multi-pack-index-$H1.midx` fájl a multi-pack-index lánc első rétegét
tartalmazza. A `multi-pack-index-$H2.midx` fájl a lánc második rétegét
tartalmazza, és így tovább.

Amikor egy inkrementális és egy nem inkrementális MIDX is jelen van, a
nem inkrementális MIDX-et mindig előbb olvassuk be.

[[_object_positions_for_incremental_midxs]]
=== Objektumpozíciók inkrementális MIDX-ekhez

Az eredeti multi-pack-index tervben az objektumokra a repository egyetlen
multi-pack-indexén belüli lexikografikus pozíciójuk (objektumazonosítók
szerint) alapján hivatkozunk. Az inkrementális multi-pack-index tervben az
objektumokra a MIDX-lánc egyes komponenseinek összefűzött lexikografikus
rendezésébe mutató indexük alapján hivatkozunk.

Ha az `objects_nr()` egy olyan függvény, amely egy adott MIDX-réteg
objektumainak számát adja vissza, akkor egy `i` lexikografikus pozícióban
lévő objektum indexe mondjuk a $H3-ban a következőképpen definiált:

----
objects_nr($H2) + objects_nr($H1) + i
----

(a C implementációban ezt gyakran `i +
m->num_objects_in_base` alakban számítjuk ki).

[[_pseudo_pack_order_for_incremental_midxs]]
=== Pszeudo-pack sorrend inkrementális MIDX-ekhez

A multi-pack elérhetőségi bittérképek eredeti implementációja a pszeudo-pack
sorrendet a linkgit:gitformat-pack[5] dokumentumban (lásd a "multi-pack-index
reverse indexes" című szakaszt) nagyjából a következőképpen definiálta:

____
Röviden, egy MIDX pszeudo-packje a MIDX által tárolt packekben lévő objektumok
deduplikált összefűzése, pack sorrendben elrendezve, a packek pedig MIDX-sorrendbe
rendezve (a preferált pack kerül előre).
____

Az inkrementális MIDX tervben ezt a definíciót kiterjesztjük, hogy több MIDX-lánc-
réteg objektumait is tartalmazza. Az inkrementális MIDX-ek pszeudo-pack sorrendjét
úgy határozzuk meg, hogy a MIDX-lánc egyes rétegeinek pszeudo-pack rendezését
sorrendben összefűzzük. Formálisan két `o1` és `o2` objektumot a következőképpen
hasonlítunk össze:

1. Ha `o1` a MIDX-lánc egy korábbi rétegében jelenik meg, mint `o2`, akkor
  `o1` `o2` elé sorolódik.

2. Egyébként, ha `o1` és `o2` ugyanabban a MIDX-rétegben jelenik meg, és annak a
   MIDX-rétegnek nincs alapja, akkor ha a `pack(o1)` és a `pack(o2)` egyike
   preferált, a másik pedig nem, akkor a preferált sorolódik a
   nem preferált elé. Ha van alapréteg (vagyis a MIDX-réteg nem a lánc első
   rétege), akkor ha a `pack(o1)` korábban jelenik meg abban a MIDX-rétegben a
   pack sorrendjében, akkor `o1` sorolódik `o2` elé. Hasonlóképpen, ha a
   `pack(o2)` jelenik meg korábban, akkor ennek az ellenkezője
   igaz.

3. Egyébként `o1` és `o2` ugyanabban a packben, és így ugyanabban a MIDX-rétegben
   jelenik meg. Rendezd `o1`-et és `o2`-t az őket tartalmazó packfile-on belüli
   eltolásuk szerint.

Vedd figyelembe, hogy a preferált pack a MIDX-lánc, nem pedig az egyes rétegek
tulajdonsága. Alapvetően bevezethetnénk rétegenkénti preferált packet, de ez
kevésbé releváns most, hogy egy MIDX packjeinek halmazán át multi-pack újrafelhasználást
tudunk végezni.

[[_reachability_bitmaps_and_incremental_midxs]]
=== Elérhetőségi bittérképek és inkrementális MIDX-ek

Egy inkrementális MIDX-lánc minden rétege ábrázolhatja a saját objektumait (és az
ugyanabban a MIDX-láncban lévő bármely korábbi réteg objektumait) a saját
`*.bitmap` fájljában.

Egy inkrementális MIDX-lánchoz tartozó `*.bitmap` fájl szerkezete azonos egy
nem inkrementális MIDX-bittérképével vagy egy klasszikus, egyetlen packes
bittérképével. Mivel az objektumok az inkrementális MIDX pszeudo-pack
sorrendjének végére kerülnek (lásd fentebb), egy bittérkép kiterjeszthető,
amikor a MIDX-lánc végéhez fűzünk hozzá.

(Megjegyzés: hasonlóképpen lehetséges egy összefüggő MIDX-inkrementális-réteg-sorozatot
és azok `*.bitmap` fájljait egyetlen réteggé és `*.bitmap`-pé tömöríteni, de ez még
nincs megvalósítva.)

A használt objektumpozíciók globálisak a pszeudo-pack sorrenden belül, így a
későbbi rétegekben például `m->num_objects_in_base` darab `0` bit lesz a
négy típus-bittérképük mindegyikében. Ez abból következik,
hogy csak a bittérképnek közvetlenül megfelelő rétegben jelen lévő objektumokhoz
írunk típus-bittérkép-bejegyzéseket).

Vedd figyelembe azt is, hogy egy inkrementális MIDX-láncban csak a legutóbbi réteghez
tartozó bittérképet használjuk arra, hogy elérhetőségi információt tároljunk egy
elérhetőségi lekérdezés érdekes és nem érdekes objektumairól.
A korábbi bittérkép-rétegeket csak arra használjuk, hogy commit- és pszeudo-merge-
bittérképeket keressünk ki abból a rétegből, valamint az adott réteg objektumainak
típusszintű bittérképeit.

Az implementáció egyszerűsítése érdekében a típusszintű bittérképeket egyszerre
iteráljuk, és az eredményeiket VAGY-oljuk össze, hogy elkerüljük a belső
bittérkép-függvények rekurzív hívását.

[[_future_work]]
Jövőbeli munka
--------------

- Ha a multi-pack-indexet kiterjesztik egy „stabil objektumsorrend"
  tárolására (egy Order(hash) = egész szám függvény, amely egy adott hashre
  állandó, még a multi-pack-index frissítésekor is), akkor a MIDX-bittérképek
  a MIDX-től függetlenül frissíthetők lennének.

- A packfile-ok „speciálisnak" jelölhetők üres fájlokkal, amelyek a kezdeti
  névben osztoznak, de a ".pack"-et ".keep"-re vagy ".promisor"-ra cserélik.
  Hozzáadhatunk egy opcionális adatdarabot a multi-pack-indexhez, amely
  a packfile-okról szóló információk jelzőit rögzíti. Ez új
  állapotokat tesz lehetővé, például 'repacked' vagy 'redeltified', amelyek segíthetnek a
  pack-karbantartásban multi-pack környezetben. Hasznos lehet a
  packfile-okat objektumtípus szerint (commit, tree, blob
  stb.) rendszerezni, és ezt a metaadatot a karbantartás segítésére használni.

[[_related_links]]
Kapcsolódó hivatkozások
-----------------------
[0] https://bugs.chromium.org/p/git/issues/detail?id=6
    Chromium munkaelem ehhez: Multi-Pack Index (MIDX)

[1] https://lore.kernel.org/git/20180107181459.222909-1-dstolee@microsoft.com/
    Egy korábbi RFC a multi-pack-index funkcióhoz

[2] https://lore.kernel.org/git/alpine.DEB.2.20.1803091557510.23109@alexmv-linux/
    A 2018-as Git Merge közreműködői csúcstalálkozójának jegyzetei (tartalmaz MIDX-vitát is)
