A Git csomagolási heurisztikáiról
=================================

        Oh, here's a really stupid question:

                  Where do I go
               to learn the details
	    of Git's packing heuristics?

Vigyázz, mit kérdezel!

A Git hívei, nyissátok meg a Git IRC-naplóját, és lapozzatok
2006. február 10-éhez.

Ritka alkalom ez: csatlakozik hozzánk maga a Git Királya,
Linus Torvalds (linus).  Nathaniel Smith (njs`) kapja a szót,
és megvilágosodásra vágyik.  Mások is jelen vannak, de hallgatnak.

Hallgassunk bele!

    <njs`> Oh, here's a really stupid question -- where do I go to
	learn the details of Git's packing heuristics?  google avails
        me not, reading the source didn't help a lot, and wading
        through the whole mailing list seems less efficient than any
        of that.

Merész kezdés!  Segélykérés, egyszersmind háromfelől indított
támadás a megvilágosodás keresésének néhány jól bevált támpontja
ellen.  Pimasz vádaskodás, hogy a google haszontalan. Micsoda gőg!
A forrás rágalmazása.  Eretnekség!  A levelezőlista-archívumok lenézése.
Ó, jaj.

    <pasky> yes, the packing-related delta stuff is somewhat
        mysterious even for me ;)

Á!  Mégiscsak van benne szerénység.

    <linus> njs, I don't think the docs exist. That's something where
	 I don't think anybody else than me even really got involved.
	 Most of the rest of Git others have been busy with (especially
	 Junio), but packing nobody touched after I did it.

Rejtélyes, mégis homályos.  Egészen linusi stílus.  A bölcsek
ezt bocsánatkérésnek értelmezik.  Néhányan azzal érvelnek, hogy
pusztán ténymegállapítás.

    <njs`> I guess the next step is "read the source again", but I
        have to build up a certain level of gumption first :-)

Valóban!  Mindkét ponton.

    <linus> The packing heuristic is actually really really simple.

Csali...

    <linus> But strange.

És csere.  Ez így már működik!

    <linus> Remember: Git really doesn't follow files. So what it does is
        - generate a list of all objects
        - sort the list according to magic heuristics
        - walk the list, using a sliding window, seeing if an object
          can be diffed against another object in the window
        - write out the list in recency order

A hagyományos alábecslés:

    <njs`> I suspect that what I'm missing is the precise definition of
        the word "magic"

A hagyományos éleslátás:

    <pasky> yes

És bábeli zűrzavar áradt szét.

    <njs`> oh, hmm, and I'm not sure what this sliding window means either

    <pasky> iirc, it appeared to me to be just the sha1 of the object
        when reading the code casually ...

        ... which simply doesn't sound as a very good heuristics, though ;)

    <njs`> .....and recency order.  okay, I think it's clear I didn't
       even realize how much I wasn't realizing :-)

Á, ifjú tanítvány!  És így kezdődik újra a megvilágosodás.

    <linus> The "magic" is actually in theory totally arbitrary.
        ANY order will give you a working pack, but no, it's not
	ordered by SHA-1.

        Before talking about the ordering for the sliding delta
        window, let's talk about the recency order. That's more
        important in one way.

    <njs`> Right, but if all you want is a working way to pack things
        together, you could just use cat and save yourself some
        trouble...

Váááárj egy kicsit....

    <linus> The recency ordering (which is basically: put objects
        _physically_ into the pack in the order that they are
        "reachable" from the head) is important.

    <njs`> okay

    <linus> It's important because that's the thing that gives packs
        good locality. It keeps the objects close to the head (whether
        they are old or new, but they are _reachable_ from the head)
        at the head of the pack. So packs actually have absolutely
        _wonderful_ IO patterns.

Olvasd el ezt még egyszer, mert fontos.

    <linus> But recency ordering is totally useless for deciding how
        to actually generate the deltas, so the delta ordering is
        something else.

        The delta ordering is (wait for it):
        - first sort by the "basename" of the object, as defined by
          the name the object was _first_ reached through when
          generating the object list
        - within the same basename, sort by size of the object
        - but always sort different types separately (commits first).

        That's not exactly it, but it's very close.

    <njs`> The "_first_ reached" thing is not too important, just you
        need some way to break ties since the same objects may be
        reachable many ways, yes?

És mintegy pontosításképpen:

    <linus> The point is that it's all really just any random
        heuristic, and the ordering is totally unimportant for
        correctness, but it helps a lot if the heuristic gives
        "clumping" for things that are likely to delta well against
        each other.

Fontos pont ez, úgyhogy titokban elvégeztem a saját kutatásomat, és az
eredményeimet alább mellékeltem.  Az igazság kedvéért: idővel valamennyit
változott.  És a Revizionista Történelem varázsa révén a Git IRC-naplóinak
ebből a bejegyzéséből merítek, apám születésnapján, március 1-jén:

    <gitster> The quote from the above linus should be rewritten a
        bit (wait for it):
        - first sort by type.  Different objects never delta with
	  each other.
        - then sort by filename/dirname.  hash of the basename
          occupies the top BITS_PER_INT-DIR_BITS bits, and bottom
          DIR_BITS are for the hash of leading path elements.
        - then if we are doing "thin" pack, the objects we are _not_
          going to pack but we know about are sorted earlier than
          other objects.
        - and finally sort by size, larger to smaller.

Egyetlen zavaros csapással pontosítás és homályosítás!  Mindazonáltal
mérvadó.  Rejtélyes, mégis tömör.  Még A Forráskódból vett idézetek
gondolatát is felkelti.  Nyilvánvaló, hogy több tanulmányozás kell.

    <gitster> That's the sort order.  What this means is:
        - we do not delta different object types.
	- we prefer to delta the objects with the same full path, but
          allow files with the same name from different directories.
	- we always prefer to delta against objects we are not going
          to send, if there are some.
	- we prefer to delta against larger objects, so that we have
          lots of removals.

        The penultimate rule is for "thin" packs.  It is used when
        the other side is known to have such objects.

Már megint itt van. "Thin" (vékony) packek.  Elgondolkodom: „Mi az a
'thin' pack?"  Úgyhogy megkérdezem:

    <jdl> What is a "thin" pack?

    <gitster> Use of --objects-edge to rev-list as the upstream of
        pack-objects.  The pack transfer protocol negotiates that.

Hurrá!  Ez aztán _tisztázta_ a dolgot!

    <gitster> There are two directions - push and fetch.

Ott!  Láttad?  Nem az van, hogy '"push" és "pull"'!  Milyen gyakran
kezdődött itt a félreértés.  És milyen csak úgy mellékesen ejtve!

    <gitster> For push, git-send-pack invokes git-receive-pack on the
        other end.  The receive-pack says "I have up to these commits".
        send-pack looks at them, and computes what are missing from
        the other end.  So "thin" could be the default there.

        In the other direction, fetch, git-fetch-pack and
        git-clone-pack invokes git-upload-pack on the other end
	(via ssh or by talking to the daemon).

	There are two cases: fetch-pack with -k and clone-pack is one,
        fetch-pack without -k is the other.  clone-pack and fetch-pack
        with -k will keep the downloaded packfile without expanded, so
        we do not use thin pack transfer.  Otherwise, the generated
        pack will have delta without base object in the same pack.

        But fetch-pack without -k will explode the received pack into
        individual objects, so we automatically ask upload-pack to
        give us a thin pack if upload-pack supports it.

Nos, rendben.

Ööö.

Térjünk vissza az előző, még folyamatban lévő beszélgetéshez.

    <njs`> and "basename" means something like "the tail of end of
        path of file objects and dir objects, as per basename(3), and
        we just declare all commit and tag objects to have the same
        basename" or something?

Szerencsére ezt a pontot is tisztázta nekünk gitster!

Ha hozzátehetem, a trükk az, hogy az _esetleg_ hasonló fájlok a
fájlneveik alapján egymáshoz közeli hash-kosarakba kerüljenek.  Régen
a "foo/Makefile", a "bar/baz/quux/Makefile" és a "Makefile" mind
ugyanabba a kosárba került a közös basename-jük, a "Makefile" miatt.
Most viszont "közeli" kosarakba kerülnek.

Az algoritmus nem csak az _ugyanolyan_ kosarat, hanem a _közeli_
kosarakat is delta-jelöltnek tekinti.  Az indoklás lényegében az, hogy
a fájlok, mint a Makefile-ok, gyakran nagyon hasonló tartalmúak,
függetlenül attól, melyik könyvtárban laknak.

    <linus> I played around with different delta algorithms, and with
        making the "delta window" bigger, but having too big of a
        sliding window makes it very expensive to generate the pack:
        you need to compare every object with a _ton_ of other objects.

        There are a number of other trivial heuristics too, which
        basically boil down to "don't bother even trying to delta this
        pair" if we can tell before-hand that the delta isn't worth it
        (due to size differences, where we can take a previous delta
        result into account to decide that "ok, no point in trying
        that one, it will be worse").

        End result: packing is actually very size efficient. It's
        somewhat CPU-wasteful, but on the other hand, since you're
        really only supposed to do it maybe once a month (and you can
        do it during the night), nobody really seems to care.

Szép mérnöki fogás ez.  Megtalálod, mikor nem számít, és kikiáltod
lényegtelennek.  Jó stílus is!

    <njs`> So, just to repeat to see if I'm following, we start by
        getting a list of the objects we want to pack, we sort it by
        this heuristic (basically lexicographically on the tuple
        (type, basename, size)).

        Then we walk through this list, and calculate a delta of
        each object against the last n (tunable parameter) objects,
        and pick the smallest of these deltas.

Erősen leegyszerűsítve, de a lényeg megvan!

    <linus> Correct.

    <njs`> And then once we have picked a delta or fulltext to
        represent each object, we re-sort by recency, and write them
        out in that order.

    <linus> Yup. Some other small details:

És persze ott van a „mikor esik le a tantusz" tényező is.

    <linus> - We limit the delta depth to another magic value (right
        now both the window and delta depth magic values are just "10")

    <njs`> Hrm, my intuition is that you'd end up with really _bad_ IO
        patterns, because the things you want are near by, but to
        actually reconstruct them you may have to jump all over in
        random ways.

    <linus> - When we write out a delta, and we haven't yet written
        out the object it is a delta against, we write out the base
        object first.  And no, when we reconstruct them, we actually
        get nice IO patterns, because:
        - larger objects tend to be "more recent" (Linus' law: files grow)
        - we actively try to generate deltas from a larger object to a
          smaller one
        - this means that the top-of-tree very seldom has deltas
          (i.e. deltas in _practice_ are "backwards deltas")

Megint érdemes újraolvasni ezt az egész bekezdést.  Nem csak azért,
mert Linus becsempészte oda nekünk Linus törvényét, hanem azért, mert
fontos.  Tisztázzunk itt néhány pontot:

    <njs`> So the point is just that in practice, delta order and
        recency order match each other quite well.

    <linus> Yes. There's another nice side to this (and yes, it was
	designed that way ;):
        - the reason we generate deltas against the larger object is
	  actually a big space saver too!

    <njs`> Hmm, but your last comment (if "we haven't yet written out
        the object it is a delta against, we write out the base object
        first"), seems like it would make these facts mostly
        irrelevant because even if in practice you would not have to
        wander around much, in fact you just brute-force say that in
        the cases where you might have to wander, don't do that :-)

    <linus> Yes and no. Notice the rule: we only write out the base
        object first if the delta against it was more recent.  That
        means that you can actually have deltas that refer to a base
        object that is _not_ close to the delta object, but that only
        happens when the delta is needed to generate an _old_ object.

    <linus> See?

Hát, nem.  Én is lemaradtam róla az első két-három olvasásra.

    <linus> This keeps the front of the pack dense. The front of the
        pack never contains data that isn't relevant to a "recent"
        object.  The size optimization comes from our use of xdelta
        (but is true for many other delta algorithms): removing data
        is cheaper (in size) than adding data.

        When you remove data, you only need to say "copy bytes n--m".
	In contrast, in a delta that _adds_ data, you have to say "add
        these bytes: 'actual data goes here'"

    *** njs` has quit: Read error: 104 (Connection reset by peer)

    <linus> Uhhuh. I hope I didn't blow njs` mind.

    *** njs` has joined channel #git

    <pasky> :)

A csendes megfigyelők jól szórakoznak.  Persze.

És mintha njs`-től elvárnák, hogy mindentudó legyen:

    <linus> njs - did you miss anything?

Jó, kimondom.  Ez geekhumor.  Ha njs` egy kis időre tényleg nem volt
kapcsolatban, honnan tudná, hogy lemaradt-e bármiről, amíg le volt
csatlakozva?  Jóindulatú diktátor, humorérzékkel!  Jól megjegyezve!

    <njs`> Stupid router.  Or gremlins, or whatever.

Olcsó beszólás a Ciscónak.  Élj vele, amikor tudsz.

    <njs`> Yes and no. Notice the rule: we only write out the base
        object first if the delta against it was more recent.

        I'm getting lost in all these orders, let me re-read :-)
	So the write-out order is from most recent to least recent?
        (Conceivably it could be the opposite way too, I'm not sure if
        we've said) though my connection back at home is logging, so I
        can just read what you said there :-)

És azoknak, akik figyeltek: a Mindentudó Trükköt épp az imént
részletezték!

    <linus> Yes, we always write out most recent first

    <njs`> And, yeah, I got the part about deeper-in-history stuff
        having worse IO characteristics, one sort of doesn't care.

    <linus> With the caveat that if the "most recent" needs an older
        object to delta against (hey, shrinking sometimes does
        happen), we write out the old object with the delta.

    <njs`> (if only it happened more...)

    <linus> Anyway, the pack-file could easily be denser still, but
	because it's used both for streaming (the Git protocol) and
        for on-disk, it has a few pessimizations.

Valójában ez egy kitalált szó. De egy olyan kitalált szó, amelyet egy
későbbi optimalizáció felvezetéseként használnak – az pedig valódi szó:

    <linus> In particular, while the pack-file is then compressed,
        it's compressed just one object at a time, so the actual
        compression factor is less than it could be in theory. But it
        means that it's all nice random-access with a simple index to
        do "object name->location in packfile" translation.

    <njs`> I'm assuming the real win for delta-ing large->small is
        more homogeneous statistics for gzip to run over?

        (You have to put the bytes in one place or another, but
        putting them in a larger blob wins on compression)

        Actually, what is the compression strategy -- each delta
        individually gzipped, the whole file gzipped, somewhere in
        between, no compression at all, ....?

        Right.

Beköszönt az IRC-valóság.  Például:

    <pasky> I'll read the rest in the morning, I really have to go
        sleep or there's no hope whatsoever for me at the today's
        exam... g'nite all.

Hehe.

    <linus> pasky: g'nite

    <njs`> pasky: 'luck

    <linus> Right: large->small matters exactly because of compression
        behaviour. If it was non-compressed, it probably wouldn't make
        any difference.

    <njs`> yeah

    <linus> Anyway: I'm not even trying to claim that the pack-files
        are perfect, but they do tend to have a nice balance of
        density vs ease-of use.

Hű!  Rendben, megúsztuk.  Ez tisztességes mérnöki kompromisszum.
Épphogy!  Linus voltaképp elmélkedik néhány alapvető mérnöki
alapelven, tervezési lehetőségeken és hasonlókon.

    <linus> More importantly, they allow Git to still _conceptually_
        never deal with deltas at all, and be a "whole object" store.

        Which has some problems (we discussed bad huge-file
	behaviour on the Git lists the other day), but it does mean
	that the basic Git concepts are really really simple and
        straightforward.

        It's all been quite stable.

        Which I think is very much a result of having very simple
        basic ideas, so that there's never any confusion about what's
        going on.

        Bugs happen, but they are "simple" bugs. And bugs that
        actually get some object store detail wrong are almost always
        so obvious that they never go anywhere.

    <njs`> Yeah.

Ennyi elég is.

    <linus> Anyway.  I'm off for bed. It's not 6AM here, but I've got
	 three kids, and have to get up early in the morning to send
	 them off. I need my beauty sleep.

    <njs`> :-)

    <njs`> appreciate the infodump, I really was failing to find the
	details on Git packs :-)

És most már ismered a történet többi részét is.
