Packfile URI-k
==============

Ez a funkció lehetővé teszi, hogy a szerverek a packfile-válaszuk egy részét URI-ként szolgálják ki.
Ezzel olyan szerverkialakítások válnak lehetővé, amelyek javítják a sávszélesség és a CPU-használat skálázhatóságát
(például úgy, hogy egyes adatokat egy CDN-en keresztül szolgálnak ki), és (a jövőben) bizonyos mértékű
folytathatóságot biztosítanak a klienseknek.

Ez a funkció csak a 2-es protokollverzióban érhető el.

[[_protocol]]
Protokoll
---------

A szerver meghirdeti a `packfile-uris` képességet.

Ha ezután a kliens egy `packfile-uris` argumentummal közli, hogy mely protokollokat
(HTTPS stb.) támogatja, a szerver KÜLDHET egy `packfile-uris` szakaszt
közvetlenül a `packfile` szakasz előtt (a `wanted-refs` után, ha az elküldésre
kerül), amely a megadott protokollok bármelyikéhez tartozó URI-kat tartalmaz. Az URI-k olyan
packfile-okra mutatnak, amelyek csak a kliens által deklaráltan támogatott funkciókat használják
(pl. ofs-delta és thin-pack). E szakasz dokumentációját lásd: linkgit:gitprotocol-v2[5].

A klienseknek ezután le kell tölteniük és indexelniük az összes megadott URI-t (a válasz
`packfile` szakaszában megadott packfile letöltésén és indexelésén felül),
mielőtt elvégeznék a kapcsolódási ellenőrzést.

[[_server_design]]
A szerver kialakítása
---------------------

A szerver triviálisan kompatibilissé tehető a javasolt protokollal úgy, hogy
meghirdeti a `packfile-uris` képességet, eltűri, ha a kliens `packfile-uris`-t
küld, és soha nem küld `packfile-uris` szakaszt. De érdemes valamilyen
nem triviális implementációt is beletenni a Minimum Viable Productba,
legalább azért, hogy tesztelni tudjuk a klienst.

Az implementáció a következő: egy kísérletinek jelölt funkció, amely lehetővé teszi, hogy a
szervert egy vagy több `uploadpack.blobPackfileUri=
<object-hash> <pack-hash> <uri>` bejegyzéssel konfiguráljuk. Valahányszor összeáll az elküldendő
objektumok listája, minden ilyen blob kimarad, és URI-k lépnek a helyükre. Ahogy
az alábbi „Jövőbeli munka" szakaszban szerepel, a szerver a jövőben továbbfejleszthető úgy, hogy más
objektumok kizárását is támogassa (vagy készíthetők más szerverimplementációk,
amelyek más objektumok kizárását támogatják) protokollváltoztatás nélkül, ezért
a klienseknek nem szabad arra számítaniuk, hogy az így letöltött packfile-ok csak
egyetlen blobot tartalmaznak.

[[_client_design]]
A kliens kialakítása
--------------------

A kliens egy `fetch.uriprotocols` konfigurációs változóval rendelkezik, amely meghatározza, hogy
a végfelhasználó mely protokollokat hajlandó használni. Alapértelmezés szerint ez üres.

Amikor a kliens letölti a megadott URI-kat, „keep" fájlokkal kell tárolnia őket,
ugyanúgy, ahogy a `packfile` szakaszban lévő packfile-lal teszi. Ezek a
további „keep" fájlok csak a refek frissítése után távolíthatók el -
ugyanúgy, mint a `packfile` szakaszban lévő packfile „keep" fájlja.

A munka felosztása (kezdeti fetch + további URI-k) kényelmes pontokat kínál
egy megszakadt klónozás folytatásához - az ilyen folytatás a
Minimum Viable Product után valósítható meg (lásd: „Jövőbeli munka").

[[_future_work]]
Jövőbeli munka
--------------

A protokoll kialakítása lehetővé tesz némi továbbfejlesztést a szerver és a kliens oldalán
protokollváltoztatás nélkül, ezért itt csak egy szűk hatókörű terv szerepel, amely
az MVP-t alkotja. Például a következők tehetők meg:

 * A szerveren kifinomultabb módszerek az objektumok kizárására (pl. egy commit
   megadásával, amely magát a commitot és az összes általa hivatkozott
   objektumot képviseli).
 * A kliensen a klónozás folytatása. Ha egy klónozás megszakad, információ
   rögzíthető a repository konfigurációjában, és egy „clone-resume" parancs
   folytathatja a folyamatban lévő klónozást. (A későbbi fetchek folytatása
   nehezebb, mert azzal is számolni kell, hogy a felhasználó akkor is használni
   akarja a repository-t, ha a fetch megszakadt.)

Van néhány lehetséges funkció, amely protokollváltoztatást igényel:

 * További HTTP-fejlécek (pl. hitelesítés)
 * Bájttartomány-támogatás
 * Az URI-k által hivatkozott eltérő fájlformátumok (pl. nyers objektum)
