A párhuzamos checkout tervezési jegyzetei
=========================================

A „párhuzamos checkout" funkció több folyamatot próbál használni, hogy egy
checkout művelet során párhuzamosítsa a blobok kicsomagolásának, a magon belüli
szűrők alkalmazásának és a keletkező tartalmak working tree-be írásának
munkáját. Minden checkout-jellegű parancs használhatja, például a
`clone`, a `checkout`, a `reset`, a `sparse-checkout` és mások.

Ezek a parancsok a következő alapstruktúrán osztoznak:

* 1. lépés: A jelenlegi indexfájl beolvasása a memóriába.

* 2. lépés: A memóriában lévő index módosítása a parancs alapján, és
  minden frissítendő cache-bejegyzés ideiglenes megjelölése.

* 3. lépés: A working tree feltöltése az új jelölt indexnek megfelelően.
  Ez magában foglalja az összes frissítendő cache-bejegyzésen való végigiterálást,
  valamint a hozzájuk tartozó fájlok törlését, létrehozását vagy felülírását a
  working tree-ben.

* 4. lépés: Az új index lemezre írása.

Az itt leírt „párhuzamos checkout" erőfeszítés a 3. lépésre összpontosít.

[[_sequential_implementation]]
Szekvenciális implementáció
---------------------------

Az itteni tárgyalás céljából a 3. lépés jelenlegi szekvenciális
implementációja 3 részre oszlik, amelyek mindegyike a saját
függvényében van megvalósítva:

* 3a lépés: az `unpack-trees.c:check_updates()` szekvenciális ciklusok
  sorozatát tartalmazza, amelyek a `cache_entry`-k tömbjén iterálnak végig. A
  függvény fő ciklusa minden frissítendő bejegyzéshez meghívja a 3b lépés
  függvényét.

* 3b lépés: az `entry.c:checkout_entry()` megvizsgálja a meglévő working tree-t
  fájlkonfliktusok, ütközések és el nem mentett változtatások szempontjából. Szükség
  szerint eltávolít fájlokat és létrehozza a vezető könyvtárakat. Minden írandó
  bejegyzéshez meghívja a 3c lépés függvényét.

* 3c lépés: az `entry.c:write_entry()` betölti a blobot a memóriába, szükség
  esetén smudge-eli, létrehozza a fájlt a working tree-ben, kiírja a
  smudge-elt tartalmat, meghívja az `fstat()`-ot vagy az `lstat()`-ot, és
  frissíti a hozzá tartozó `cache_entry` structot az összegyűjtött stat-információval.

Nem lenne biztonságos a 3b lépést párhuzamosan végezni, mivel versenyhelyzetek
lehetnének a fájllétrehozások és -eltávolítások között. Ehelyett a
párhuzamos checkout keretrendszer a szekvenciális kódra bízza a 3b lépést,
és párhuzamos workereket használ a 3c lépés szekvenciális
`entry.c:write_entry()` hívásainak leváltására.

[[_rejected_multi_threaded_solution]]
Az elvetett többszálú megoldás
------------------------------

A leg„kézenfekvőbb" implementáció az lenne, hogy a frissítendő
cache-bejegyzések halmazát több szál között osztjuk el. De az objektumadatbázis
kódjában lévő nem szálbiztos függvények miatt zárolásokat kellene használnunk a
párhuzamos működés összehangolásához. Ennek a megoldásnak egy korai prototípusa
azt mutatta, hogy a többszálú checkout teljesítménybeli javulást hozna a
szekvenciális kódhoz képest, de még mindig túl sok volt a zárolási
versengés. Egy `perf` profilozás azt jelezte, hogy egy helyi Linux-klón (SSD-n)
futásidejének mintegy 20%-át zárolási függvényekben töltötte.
Ezért ezt a megközelítést elvetettük több gyermekfolyamat használata
javára, ami jobb teljesítményhez vezetett.

[[_multi_process_solution]]
A többfolyamatos megoldás
-------------------------

A párhuzamos checkout a fent említett 3. lépést úgy módosítja, hogy több
`checkout--worker` háttérfolyamatot használjon a munka elosztására. A
hosszú életű worker folyamatokat az előtérben futó Git-parancs vezérli a
meglévő run-command API-val.

[[_overview]]
Áttekintés
~~~~~~~~~~

A 3b lépés csak kis mértékben módosul; minden checkoutolandó bejegyzéshez a
fő folyamat a következő lépéseket hajtja végre:

* M1: Ellenőrzi, van-e a working tree-ben olyan nem követett vagy nem tiszta
  fájl, amelyet ez a bejegyzés felülírna, és eldönti, hogy folytassa-e
  (eltávolítva a fájl(oka)t) vagy sem.

* M2: Létrehozza a vezető könyvtárakat.

* M3: Betölti a bejegyzés útvonalához tartozó konverziós attribútumokat.

* M4: A bejegyzés típusa és konverziós attribútumai alapján ellenőrzi,
  hogy a bejegyzés alkalmas-e párhuzamos checkoutra (erről később
  bővebben). Ha alkalmas, sorba állítja a bejegyzést és a betöltött
  attribútumokat, hogy később párhuzamosan írja ki a bejegyzést. Ha nem, azonnal
  kiírja a bejegyzést az alapértelmezett szekvenciális kóddal.

Megjegyzés: az egyes bejegyzésekhez tartozó konverziós attribútumokat elmentjük,
mert a workerek nem férnek hozzá a fő folyamat indexállapotához,
így nem tudják maguk betölteni az attribútumokat (az attribútumok pedig
szükségesek a bejegyzés helyes smudge-eléséhez). Ezenkívül ez pozitívan
hat a teljesítményre, mivel (1) nem kell kétszer betölteni az attribútumokat,
és (2) az attribútum-gépezet arra van optimalizálva, hogy az útvonalakat
szekvenciális sorrendben kezelje.

Miután minden bejegyzés átment a fenti lépéseken, a fő folyamat
ellenőrzi, hogy a sorba állított bejegyzések száma elegendő-e a workerek közötti
elosztáshoz. Ha nem, egyszerűen szekvenciálisan írja ki őket. Egyébként
elindítja a workereket, és a sorba állított bejegyzéseket egyenletesen, folytonos
darabokban osztja el. Ez azt hivatott minimalizálni, hogy két worker egyszerre
írjon ugyanabba a könyvtárba, ami növelhetné a zárolási
versengést a kernelben.

Ezután minden hozzárendelt elemhez minden worker:

* W1: Ellenőrzi, van-e nem könyvtár típusú fájl a bejegyzés útvonalának vezető
  részében, vagy létezik-e már fájl a bejegyzés útvonalán.
  Ha igen, megjelöli a bejegyzést `PC_ITEM_COLLIDED`-dal, és kihagyja (erről
  később bővebben).

* W2: Létrehozza a fájlt (O_CREAT-tal és O_EXCL-lel).

* W3: Betölti a blobot a memóriába (kifújva és a deltát rekonstruálva
  belőle).

* W4: Alkalmaz minden szükséges folyamaton belüli szűrőt, például a sorvég-
  konverziót és az újrakódolást.

* W5: A W2-nél megnyitott fájlleíróba írja az eredményt.

* W6: Meghívja az `fstat()`-ot vagy az `lstat()`-ot a most kiírt útvonalon, és
  visszaküldi az eredményt a fő folyamatnak a művelet végállapotával és az
  elem azonosítószámával együtt.

Vedd figyelembe, hogy amikor lehetséges, a W3-tól W5-ig terjedő lépéseket a
streamelő gépezetre delegáljuk, így nem kell a teljes blobot a memóriában tartani.

Ha a workernek nem sikerül beolvasnia a blobot, vagy kiírnia a working tree-be,
eltávolítja a létrehozott fájlt, hogy ne hagyjon maga után üres fájlokat. Ez az
*egyetlen* alkalom, amikor egy worker fájlt távolíthat el.

Ahogy korábban említettük, a fő folyamat felelőssége, hogy eltávolítson minden
olyan fájlt, amely blokkolja a checkout műveletet (vagy megszakítsa a folyamatot, ha
az eltávolítás(ok) adatvesztést okoznának, és a felhasználó nem kérte a `--force`-ot).
Ez döntő fontosságú a versenyhelyzetek elkerüléséhez, valamint az
útvonalütközések helyes felismeréséhez a W1 lépésnél.

Miután a workerek befejezik az elemek kiírását és a szükséges információ
visszaküldését, a fő folyamat két lépésben kezeli az eredményeket:

- Először frissíti a memóriában lévő indexet a workerek által küldött `lstat()`
  információval. (Ezt kell először elvégezni, mivel erre az információra
  szükség lehet a következő lépésben.)

- Ezután kiírja azokat az elemeket, amelyek a lemezen ütköztek (vagyis a
  `PC_ITEM_COLLIDED`-dal megjelölt elemeket). Erről bővebben lentebb.

[[_path_collisions]]
Útvonalütközések
----------------

Útvonalütközések akkor fordulnak elő, amikor két különböző útvonal ugyanahhoz a
fájlrendszerbeli bejegyzéshez tartozik. Pl. az 'a' és az 'A' útvonal ütközne egy
kis- és nagybetűt nem megkülönböztető fájlrendszerben.

A szekvenciális checkout ugyanúgy kezeli az ütközéseket, ahogy azokat a
fájlokat kezeli, amelyek a checkout előtt már jelen voltak a working
tree-ben. Alapvetően ellenőrzi, hogy az az útvonal, amelyre írni akar,
már létezik-e a lemezen, meggyőződik róla, hogy a meglévő fájlban nincs el nem
mentett adat, majd felülírja. (Pedánsabban: törli a
meglévő fájlt, és létrehozza az újat.) Tehát ha több ütköző fájlt kell
checkoutolni, a szekvenciális kód mindegyiket kiírja, de valójában csak az
utolsó marad meg a lemezen.

A párhuzamos checkout ugyanezt a viselkedést igyekszik reprodukálni. Nem
engedhetjük azonban, hogy a workerek versengve ugyanabba a lemezen lévő fájlba
írjanak. Ehelyett a workerek felismerik, amikor a checkoutolandó bejegyzés
ütközne egy meglévő fájllal, és megjelölik `PC_ITEM_COLLIDED`-dal.
Később a fő folyamat versenyhelyzet kockázata nélkül, szekvenciálisan
adhatja vissza ezeket a bejegyzéseket a `checkout_entry()`-nek. Klónozáskor ez
azzal a hatással is jár, hogy megjelöli az ütköző bejegyzéseket, hogy később
figyelmeztetést adjon a felhasználónak, ahogy a klasszikus szekvenciális checkout teszi.

A workerek fel tudják ismerni mind az egyidejűleg írt bejegyzések közötti
ütközéseket, mind a párhuzamosra alkalmas és a nem alkalmas bejegyzés közötti
ütközéseket. Az ütközésfelismerés általános ötlete elég egyszerű: minden
párhuzamosra alkalmas bejegyzéshez a fő folyamatnak (a sorba állítás előtt) el
kell távolítania minden fájlt, amely megakadályozza a bejegyzés kiírását.
Ide tartozik minden nem könyvtár típusú fájl a bejegyzés vezető útvonalában.
Később, amikor egy worker megkapja a bejegyzést, újra megnézi a nem könyvtár
típusú fájlokat és a bejegyzés útvonalán már létező fájlt. Ha ezen
ellenőrzések bármelyike talál valamit, a worker tudja, hogy útvonalütközés történt.

Mivel a párhuzamos checkout meg tudja különböztetni az útvonalütközéseket attól az
esettől, amikor a fájl a checkout előtt már jelen volt a working tree-ben,
alternatívaként dönthetnénk úgy is, hogy kihagyjuk az ütköző bejegyzések checkoutját.
Azonban minden ki nem írt bejegyzésnek NULL `lstat()`-mezői lennének az indexben.
Ez teljesítménybeli hátrányt okozhatna a
későbbi parancsoknak, amelyeknek frissíteniük kell az indexet, mivel a
fájlrendszerhez kellene fordulniuk, hogy megnézzék, piszkos-e a bejegyzés. Tehát ha
egy ütköző csoportban N bejegyzésünk van, és úgy döntünk, hogy csak egyiküket
írjuk ki és `lstat()`-oljuk, minden későbbi `git-status`-nak N - 1-szer kell
beolvasnia, konvertálnia és hash-elnie a kiírt fájlt. Azzal, hogy minden ütköző
bejegyzést checkoutolunk (ahogy a szekvenciális kód teszi), a többletköltséget
csak egyszer fizetjük meg, a checkout során.

[[_eligible_entries_for_parallel_checkout]]
A párhuzamos checkoutra alkalmas bejegyzések
--------------------------------------------

Ahogy korábban említettük, nem minden `checkout_entry()`-nek átadott bejegyzés
minősül párhuzamos checkoutra alkalmasnak. Pontosabban a következőket
zárjuk ki:

- Szimbolikus linkek; hogy elkerüljük azokat a versenyhelyzeteket, amelyek
  útvonalütközésekkel kombinálva arra késztethetnék a workereket, hogy rossz
  helyre írjanak fájlokat. Például ha egyidejűleg checkoutolnánk egy 'a' -> 'b'
  szimlinket és egy 'A/f' közönséges fájlt egy kis- és nagybetűt nem megkülönböztető
  fájlrendszerben, akár az történhetne, hogy az 'A/f' fájlt az 'a/f' helyre írjuk egy
  versenyhelyzet miatt.

- Közönséges fájlok, amelyek külső szűrőket igényelnek (akár „one shot" szűrők,
  akár hosszú életű folyamatszűrők). Ezek a szűrők fekete dobozok a Git számára,
  és lehet, hogy saját belső zárolásuk vagy nem konkurens feltételezéseik vannak.
  Ezért nem biztos, hogy biztonságos több példányt párhuzamosan futtatni.
+
Ezenkívül a hosszú életű szűrők használhatják a késleltetett checkout funkciót,
hogy elhalasszák néhány szűrt blob visszaadását. A késleltetett checkout sor
és a párhuzamos checkout sor nem kompatibilis, és külön kell
maradniuk.
+
Megjegyzés: azok a közönséges fájlok, amelyek csak belső szűrőket igényelnek, mint a
sorvég-konverzió és az újrakódolás, alkalmasak párhuzamos checkoutra.

A nem alkalmas bejegyzéseket a klasszikus szekvenciális kódútvonal checkoutolja
a workerek elindítása *előtt*.

Megjegyzés: a submodule-ok fájljai is alkalmasak párhuzamos checkoutra (amíg
nem esnek a fent említett kizáró kategóriák egyikébe sem).
De mivel minden submodule a saját gyermekfolyamatában van checkoutolva,
nem keverjük a szuperprojekt és a submodule-ok fájljait ugyanabba a
párhuzamos checkout folyamatba vagy sorba.

[[_the_api]]
Az API
------

A párhuzamos checkout API-t azzal a céllal terveztük, hogy minimalizáljuk a
checkout gépezet jelenlegi felhasználóin szükséges változtatásokat. Ez azt jelenti, hogy
nem kell más függvényt hívniuk szekvenciális vagy párhuzamos
checkouthoz. Ahogy már említettük, a `checkout_entry()` automatikusan
beszúrja az adott bejegyzést a párhuzamos checkout sorba, amikor ez a funkció
engedélyezve van, és a bejegyzés alkalmas; egyébként egyszerűen azonnal kiírja a
bejegyzést a szekvenciális kóddal. Általánosságban a párhuzamos
checkout API hívói ehhez hasonlóan néznek ki:

----------------------------------------------
int pc_workers, pc_threshold, err = 0;
struct checkout state;

get_parallel_checkout_configs(&pc_workers, &pc_threshold);

/*
 * This check is not strictly required, but it
 * should save some time in sequential mode.
 */
if (pc_workers > 1)
	init_parallel_checkout();

for (each cache_entry ce to-be-updated)
	err |= checkout_entry(ce, &state, NULL, NULL);

err |= run_parallel_checkout(&state, pc_workers, pc_threshold, NULL, NULL);
----------------------------------------------
