[[_partial_clone_design_notes]]
Partial Clone – tervezési jegyzetek
===================================

A „Partial Clone" funkció a Git egy teljesítmény-optimalizációja, amely
lehetővé teszi, hogy a Git a repository teljes másolata nélkül is
működjön.  E munka célja, hogy a Git jobban tudja kezelni a rendkívül
nagy repository-kat.

A klónozási és fetch műveletek során a Git letölti a repository teljes
tartalmát és előzményét.  Ez magában foglalja az összes commitot,
tree-t és blobot a repository teljes élettartamára.  Rendkívül nagy
repository-knál a klónozás órákig (vagy napokig) tarthat, és 100+ GiB
lemezterületet fogyaszthat.

Ezekben a repository-kban gyakran van sok olyan blob és tree, amelyre a
felhasználónak nincs szüksége, például:

  1. a felhasználó munkaterületén kívüli fájlok a tree-ben.  Például egy
     olyan repository-ban, amelyben minden commit 500 ezer könyvtárat és
     3,5 millió fájlt tartalmaz, sok objektum letöltését elkerülhetjük,
     ha a felhasználónak csak a forrásfa egy szűk „kúpjára" van szüksége.

  2. nagy bináris eszközök.  Például egy olyan repository-ban, ahol nagy
     build-artefaktumokat commitolnak a tree-be, elkerülhetjük az ezen
     nem merge-elhető bináris eszközök összes korábbi verziójának
     letöltését, és csak a ténylegesen hivatkozott verziókat töltjük le.

A partial clone lehetővé teszi, hogy az ilyen szükségtelen objektumok
letöltését *előre* elkerüljük a klónozási és fetch műveletek során, és
ezáltal csökkentsük a letöltési időket és a lemezhasználatot.  A
hiányzó objektumok később „igény szerint letölthetők", ha/amikor
szükség van rájuk.

Az a remote, amely később biztosítani tudja a hiányzó objektumokat,
promisor remote-nak nevezzük, mivel megígéri, hogy elküldi az
objektumokat, amikor kérik. Kezdetben a Git csak egyetlen promisor
remote-ot támogatott, azt az origin remote-ot, amelyről a felhasználó
klónozott, és amelyet az „extensions.partialClone" config opció
állított be. Később megvalósult az egynél több promisor remote
támogatása.

A partial clone használatához az kell, hogy a felhasználó online
legyen, és az origin remote vagy más promisor remote-ok elérhetők
legyenek a hiányzó objektumok igény szerinti fetcheléséhez.  Ez a
felhasználónak lehet problémás, de lehet, hogy nem.  Ha például a
felhasználó a forrásfa előre kiválasztott részhalmazán belül tud
maradni, lehet, hogy egyetlen hiányzó objektummal sem találkozik.
Vagy a felhasználó megpróbálhat előre lefetchelni különféle
objektumokat, ha tudja, hogy offline lesz.


[[_non_goals]]
Nem célok
---------

A partial clone egy olyan mechanizmus, amely a commitok egy adott
tartományán *belül* letöltött blobok és tree-k számát korlátozza – és
ezért független a kért commitok halmazát korlátozó, meglévő DAG-szintű
mechanizmusoktól (azaz a shallow clone-tól, a single branchtől vagy a
fetch '<refspec>'-től), és nem szándéka ütközni velük.


[[_design_overview]]
A tervezés áttekintése
----------------------

A partial clone logikailag a következő részekből áll:

- Egy mechanizmus, amellyel a kliens leírja a szervernek a szükségtelen
  vagy nem kívánt objektumokat.

- Egy mechanizmus, amellyel a szerver kihagyja az ilyen nem kívánt
  objektumokat a kliensnek küldött packfile-okból.

- Egy mechanizmus, amellyel a kliens elegánsan kezeli a hiányzó
  objektumokat (amelyeket korábban a szerver kihagyott).

- Egy mechanizmus, amellyel a kliens szükség szerint pótolja a hiányzó
  objektumokat.


[[_design_details]]
Tervezési részletek
-------------------

- Egy új „filter" pack-protokoll képesség kerül hozzáadásra a
  fetch-pack és upload-pack egyeztetéshez.
+
Ez a meglévő képesség-felfedező mechanizmust használja.
Lásd a „filter"-t a linkgit:gitprotocol-pack[5]-ben.

- A kliensek egy „filter-spec"-et adnak át a clone-nak és a fetchnek,
  amelyet átadnak a szervernek, hogy szűrést kérjenek a packfile
  felépítése során.
+
Különféle filterek állnak rendelkezésre a különböző helyzetek
kezelésére.  Lásd a „--filter=<filter-spec>"-et a
Documentation/rev-list-options.adoc fájlban.

- A szerveren a pack-objects alkalmazza a kért filter-spec-et, miközben
  „szűrt" packfile-okat hoz létre a kliens számára.
+
Ezek a szűrt packfile-ok a hagyományos értelemben *nem teljesek*, mert
tartalmazhatnak olyan objektumokat, amelyek a packfile-ban nem szereplő,
és a kliensnél még nem meglévő objektumokra hivatkoznak.  Például a
szűrt packfile tartalmazhat hiányzó blobokra hivatkozó tree-ket vagy
tageket, vagy hiányzó tree-kre hivatkozó commitokat.

- A kliensen ezeket a nem teljes packfile-okat „promisor packfile"-ként
  jelöljük meg, és a különböző parancsok másképp kezelik őket.

- A kliensen egy repository-kiterjesztés kerül a helyi configba, hogy
  megakadályozza, hogy a git régebbi verziói művelet közben elhasaljanak
  az általuk nem kezelhető hiányzó objektumok miatt.
  Lásd az `extensions.partialClone`-t a linkgit:git-config[1]-ben.


[[_handling_missing_objects]]
A hiányzó objektumok kezelése
-----------------------------

- Egy objektum hiányozhat partial clone vagy fetch miatt, vagy
  hiányozhat a repository sérülése miatt.  E két eset
  megkülönböztetésére a helyi repository az ilyen, promisor remote-októl
  kapott szűrt packfile-okat kifejezetten „promisor packfile"-ként
  jelzi.
+
Ezek a promisor packfile-ok egy tetszőleges tartalmú „<name>.promisor"
fájlból állnak (a „<name>.keep" fájlokhoz hasonlóan), a „<name>.pack" és
„<name>.idx" fájljaikon felül.

- A helyi repository „promisor objektumnak" tekint egy olyan objektumot,
  amelyről (legjobb tudása szerint) tudja, hogy a promisor remote-ok
  megígérték, hogy náluk megvan, akár azért, mert a helyi repository-nak
  megvan az az objektum valamelyik promisor packfile-jában, akár azért,
  mert egy másik promisor objektum hivatkozik rá.
+
Amikor a Git hiányzó objektummal találkozik, meg tudja nézni, hogy az
promisor objektum-e, és megfelelően kezelheti.  Ha nem, a Git sérülést
jelezhet.
+
Ez azt jelenti, hogy a kliensnek nem kell explicit módon karbantartania
a hiányzó objektumok nehezen módosítható listáját.[a]

- Mivel jelenleg szinte az összes Git-kód elvárja, hogy bármely
  hivatkozott objektum helyben jelen legyen, és mivel nem akarjuk minden
  parancsot arra kényszeríteni, hogy először száraz futtatást végezzen,
  egy tartalék mechanizmus kerül hozzáadásra, amely lehetővé teszi, hogy
  a Git megpróbálja dinamikusan lefetchelni a hiányzó objektumokat a
  promisor remote-októl.
+
Amikor a normál objektumkeresés nem talál meg egy objektumot, a Git
meghívja a promisor_remote_get_direct()-et, hogy megpróbálja megszerezni
az objektumot egy promisor remote-tól, majd újrapróbálja az
objektumkeresést.  Ez lehetővé teszi, hogy az objektumok bonyolult
előrejelző algoritmusok nélkül „beessenek".
+
Hatékonysági okokból nem történik ellenőrzés arra nézve, hogy a hiányzó
objektum valóban promisor objektum-e.
+
A dinamikus objektum-fetchelés általában lassú, mivel az objektumokat
egyesével fetcheljük.

- A `checkout` (és bármely más, `unpack-trees`-t használó parancs) meg
  lett tanítva arra, hogy egyetlen kötegben tömegesen előre lefetchelje
  az összes szükséges hiányzó blobot.

- A `rev-list` meg lett tanítva a hiányzó objektumok kiírására.
+
Ezt más parancsok az objektumok tömeges előzetes fetchelésére
használhatják.  Például egy „git log -p A..B" belsőleg először valami
olyasmit akarhat tenni, mint „git rev-list --objects --quiet
--missing=print A..B", és tömegesen előre lefetchelni azokat az
objektumokat.

- Az `fsck` frissítve lett, hogy teljesen tisztában legyen a promisor
  objektumokkal.

- A `repack` a GC-ben frissítve lett, hogy egyáltalán ne nyúljon a
  promisor packfile-okhoz, és csak a többi objektumot csomagolja újra.

- A repository-nkénti „fetch_if_missing" flag azt szabályozza, hogy egy
  objektumkeresés megpróbál-e dinamikusan lefetchelni egy hiányzó
  objektumot, vagy hibát jelez.
+
Nem vagyunk elégedettek ezzel a globális változóval, és szeretnénk
eltávolítani, de ehhez az objektumkód jelentős refaktorálása kell egy
további flag átadásához.


[[_fetching_missing_objects]]
A hiányzó objektumok fetchelése
-------------------------------

- Az objektumok fetchelése egy „git fetch" alfolyamat meghívásával
  történik.

- A helyi repository egy kérést küld az összes kért objektum hashével,
  és nem végez packfile-egyeztetést.  Ezután kap egy packfile-t.

- Mivel a meglévő fetch mechanizmust használjuk újra, a fetchelés
  jelenleg minden, a kért objektumok által hivatkozott objektumot
  lefetchel, még ha nem is szükségesek.

- A `--refetch`-csel való fetchelés egy teljesen új szűrt packfile-t
  kér a remote-tól, ami arra használható, hogy megváltoztassunk egy
  filtert anélkül, hogy dinamikusan le kellene fetchelni a hiányzó
  objektumokat.

[[_using_many_promisor_remotes]]
Sok promisor remote használata
------------------------------

Sok promisor remote konfigurálható és használható.

Ez lehetővé teszi például, hogy egy felhasználónak több
földrajzilag közeli cache szervere legyen a hiányzó blobok
fetcheléséhez, miközben továbbra is szűrt `git-fetch` parancsokat futtat
a központi szerverről.

Objektumok fetchelésekor a promisor remote-okat egymás után próbáljuk,
amíg az összes objektum le nem töltődött.

Azok a remote-ok számítanak „promisor" remote-nak, amelyeket a
következő konfigurációs változók adnak meg:

- `extensions.partialClone = <name>`

- `remote.<name>.promisor = true`

- `remote.<name>.partialCloneFilter = ...`

Az `extensions.partialClone` config változóval csak egyetlen promisor
remote konfigurálható. Ez a promisor remote lesz az utolsó, amelyet
objektumok fetchelésekor kipróbálunk.

Úgy döntöttünk, hogy ezt próbáljuk utoljára, mert valószínű, hogy aki
sok promisor remote-ot használ, azért teszi, mert a többi promisor
remote valamiért jobb (talán közelebb vannak, vagy gyorsabbak valamely
objektumfajtánál), mint az origin, és az origin valószínűleg az a
remote, amelyet az extensions.partialClone ad meg.

Ez az indoklás nem túl erős, de valamilyen döntést meg kellett hozni,
és a hosszú távú terv amúgy is az kell legyen, hogy a sorrend valahogy
teljesen konfigurálható legyen.

Egyelőre azonban a többi promisor remote-ot abban a sorrendben
próbáljuk, ahogy a config fájlban megjelennek.

[[_current_limitations]]
Jelenlegi korlátozások
----------------------

- Nem lehet megadni a promisor remote-ok kipróbálásának sorrendjét más
  módon, mint azzal a sorrenddel, ahogy a config fájlban megjelennek.
+
Azt sem lehet megadni, hogy egy adott remote-ról való fetcheléskor egy
sorrendet, egy másik remote-ról való fetcheléskor pedig egy másik
sorrendet használjunk.

- Nem lehet csak bizonyos objektumokat pusholni egy promisor remote-ra.
+
Nem lehet egyszerre több promisor remote-ra pusholni egy adott
sorrendben.

- A dinamikus objektum-fetchelés csak a promisor remote-októl kér
  hiányzó objektumokat.  Feltételezzük, hogy a promisor remote-oknak
  teljes rálátásuk van a repository-ra, és minden ilyen kérést ki tudnak
  szolgálni.

- A repack lényegében 2 különálló partícióként kezeli a promisor és a
  nem promisor packfile-okat, és nem keveri őket.

- A dinamikus objektum-fetchelés *elemenként egyszer* hívja meg a
  fetch-pack-et, mert a legtöbb algoritmus egy hiányzó objektumba
  botlik, és fel kell oldania, mielőtt folytatná a munkáját.  Ez
  jelentős többletköltséget – és több hitelesítési kérést – okozhat, ha
  sok objektumra van szükség.

- A dinamikus objektum-fetchelés jelenleg a meglévő V0 pack protokollt
  használja, ami azt jelenti, hogy minden objektumot a fetch-pack-en
  keresztül kérünk.  A szerver a kapcsolat felépítésekor egy teljes
  info/refs halmazt küld.  Ha nagyszámú ref van, ez jelentős
  többletköltséget okozhat.


[[_future_work]]
Jövőbeli munka
--------------

- A promisor remote-ok kipróbálási sorrendjének megadási módját
  javítani.
+
Ez például lehetővé tehetné, hogy explicit módon megadjunk valami
olyasmit: „Amikor erről a remote-ról fetchelek, ezeket a promisor
remote-okat akarom használni ebben a sorrendben, viszont amikor arra a
remote-ra pusholok vagy fetchelek, azokat a promisor remote-okat akarom
használni abban a sorrendben."

- Lehetővé tenni a promisor remote-okra való pusholást.
+
A felhasználó dolgozhat háromszög alakú munkafolyamatban több promisor
remote-tal, amelyek mindegyikének nem teljes rálátása van a
repository-ra.

- Lehetővé tenni, hogy a nem útvonalnév-alapú filterek is kihasználják a
  packfile bitmapeket (ha vannak).  Ez csak egy mulasztás volt a kezdeti
  megvalósítás során.

- Megvizsgálni egy hosszan futó folyamat használatát egy objektumsorozat
  dinamikus fetcheléséhez, ahogy az [5,6]-ban javasolt, a
  folyamatindítási és többletköltségek csökkentésére.
+
Jó lenne, ha a V2 pack protokoll lehetővé tenné, hogy az a hosszan futó
folyamat egy sor kérést tegyen egyetlen hosszan futó kapcsolaton
keresztül.

- Megvizsgálni a V2 pack protokollt, hogy elkerüljük az info/refs
  broadcastot minden egyes, a szerverrel való kapcsolatnál a hiányzó
  objektumok dinamikus fetcheléséhez.

- Megvizsgálni, hogy szükség van-e a laza promisor objektumok kezelésére.
+
A promisor packfile-okban lévő objektumok hivatkozhatnak olyan hiányzó
objektumokra, amelyek dinamikusan lefetchelhetők a szerverről.  Az a
feltételezés született, hogy a laza objektumokat csak helyben hozzák
létre, ezért nem szabad hiányzó objektumra hivatkozniuk.  Lehet, hogy
újra kell gondolnunk ezt a feltételezést, ha például dinamikusan
lefetchelünk egy hiányzó tree-t, és laza objektumként tároljuk, nem
pedig egyetlen objektumot tartalmazó packfile-ként.
+
Ez nem feltétlenül jelenti azt, hogy a laza objektumokat promisorként
kell megjelölnünk; elég lehet lazítani az objektumkereső vagy az
is-promisor függvényeken.


[[_non_tasks]]
Nem feladatok
-------------

- Valahányszor előkerül a „blobok igény szerinti betöltésének" témája,
  úgy tűnik, valaki felveti, hogy a szerver „találgathasson", és küldjön
  további objektumokat, amelyek a kért objektumokhoz kapcsolódhatnak.
+
Ennek tényleges megvalósításába nem fektettünk munkát; csak
dokumentáljuk, hogy ez egy gyakori javaslat.  Nem vagyunk biztosak
benne, hogyan működne, és nincs tervünk arra, hogy dolgozzunk rajta.
+
Érvényes, ha a szerver a kértnél több objektumot küld (még egy dinamikus
objektum-fetchelésnél is), de nem erre építünk.


[[_footnotes]]
Lábjegyzetek
------------

[a] a hiányzó objektumok nehezen módosítható listája:  Korábban a
    partial clone tervezésekor megbeszéltük, hogy szükség van a hiányzó
    objektumok egyetlen listájára.  Ez lényegében azon OID-k rendezett
    lineáris listája lenne, amelyeket a szerver egy klónozás vagy
    későbbi fetchek során kihagyott.

Ezt a fájlt minden objektumkeresésnél be kellene tölteni a memóriába.
Minden explicit „git fetch" parancsnál *és* minden dinamikus
objektum-fetchelésnél be kellene olvasni, frissíteni és újraírni (mint a
.git/index).

E fájl beolvasásának, frissítésének és írásának költsége jelentős
többletköltséget adhatna minden parancshoz, ha sok hiányzó objektum van.
Például, ha 100 millió hiányzó blob van, ez a fájl legalább 2 GiB lenne
a lemezen.

A „promisor" koncepcióval egy hiányzó objektumot az őt hivatkozó
packfile típusa alapján *következtetünk ki*.


[[_related_links]]
Kapcsolódó hivatkozások
-----------------------
[0] https://crbug.com/git/2
    Bug#2: Partial Clone

[1] https://lore.kernel.org/git/20170113155253.1644-1-benpeart@microsoft.com/ +
    Subject: [RFC] Add support for downloading blobs on demand +
    Date: Fri, 13 Jan 2017 10:52:53 -0500

[2] https://lore.kernel.org/git/cover.1506714999.git.jonathantanmy@google.com/ +
    Subject: [PATCH 00/18] Partial clone (from clone to lazy fetch in 18 patches) +
    Date: Fri, 29 Sep 2017 13:11:36 -0700

[3] https://lore.kernel.org/git/20170426221346.25337-1-jonathantanmy@google.com/ +
    Subject: Proposal for missing blob support in Git repos +
    Date: Wed, 26 Apr 2017 15:13:46 -0700

[4] https://lore.kernel.org/git/1488999039-37631-1-git-send-email-git@jeffhostetler.com/ +
    Subject: [PATCH 00/10] RFC Partial Clone and Fetch +
    Date: Wed,  8 Mar 2017 18:50:29 +0000

[5] https://lore.kernel.org/git/20170505152802.6724-1-benpeart@microsoft.com/ +
    Subject: [PATCH v7 00/10] refactor the filter process code into a reusable module +
    Date: Fri,  5 May 2017 11:27:52 -0400

[6] https://lore.kernel.org/git/20170714132651.170708-1-benpeart@microsoft.com/ +
    Subject: [RFC/PATCH v2 0/1] Add support for downloading blobs on demand +
    Date: Fri, 14 Jul 2017 09:26:50 -0400
