[[platform-support-policy]]
[[_platform_support_policy]]
Platformtámogatási szabályzat
=============================

A Gitnek van egy múltja, amelyben széles körű „támogatást" nyújtott
egzotikus és régebbi platformoknak, explicit elköteleződés nélkül. Ezen
platformok érdekelt felei kiszámíthatóbb támogatási elköteleződést
szeretnének. Ez csak akkor lehetséges, ha a platform érdekelt felei
megfelelő eszközkészletet biztosítanak a Git fejlesztőinek, hogy magunk
tudjunk kompatibilitást tesztelni vagy kerülőmegoldásokat fejleszteni a
platform-specifikus furcsaságokra. A platform-specifikus eszközkészlet
különböző szintjei lehetővé teszik, hogy szilárdabb elköteleződéseket
tegyünk a Git adott platformmal való kompatibilitása körül.

Vedd figyelembe, hogy ez a dokumentum egy olyan platform meglévő
támogatásának fenntartásáról szól, amely a múltban általában működött;
egy olyan platform támogatásának hozzáadásához, amely a Gittel általában
nem működik, az adott platform érdekelt feleitől azt várjuk, hogy a
munka nagy részét maguk végezzék el. Az ilyen patcheket megfontoljuk, ha
nem nehezítik meg más támogatott platformok vagy a Git közreműködőinek
életét. Néhány közreműködő önként segíthet a kezdeti vagy folyamatos
támogatásban, de ez nem garantált. A túl tolakodó vagy a projekt számára
túl nehezen karbantartható támogatási munkát ettől még nem biztos, hogy
elfogadjuk.

[[_minimum_requirements]]
Minimális követelmények
-----------------------

E dokumentum további része azokat a legjobb gyakorlatokat írja le,
amelyekkel a platformok könnyen támogathatóvá tehetik magukat. Mielőtt
azonban egyáltalán szóba jönne a támogatás, a platformoknak meg kell
felelniük a következő minimális követelményeknek:

* Van C99 vagy C11

* Olyan verziójú függőségeket használ, amelyek általánosan elfogadottan
  stabilak és támogathatók, pl. összhangban az egyéb hosszú távú
  támogatású (long-term-support) disztribúciók által használt verzióval

* Aktív biztonsági támogatással rendelkezik (átveszi a függőségek
  biztonsági kiadásait stb.)

Ezek a követelmények kiindulópontok, és önmagukban nem elegendők ahhoz,
hogy a Git közösség lelkesedjen a platformod támogatásáért. Az e
követelményeknek megfelelő platformok maintainerei az alábbi lépéseket
követhetik, hogy valószínűbbé tegyék: a Git frissítései tiszteletben
tartják a platform igényeit.

[[_compatible_by_next_release]]
Kompatibilis a következő kiadásra
---------------------------------

Annak valószínűségét növelendő, hogy egy kiadásban bevezetett
kompatibilitási problémák egy későbbi kiadásban javításra kerülnek:

* Hibajelentést kell küldened, amint észreveszed a törést a
  platformodon. Minél hamarabb veszed észre, annál jobb; a `seen`
  figyelése azt jelenti, hogy a problémákat még azelőtt észreveheted,
  hogy „a review-val kész" állapotba kerülnének; míg a `master` figyelése
  azt jelenti, hogy a stabil branch eltörhet a platformodon, de tisztes
  esélyed van elkerülni, hogy egy tagelt kiadás eltörjön nálad. Lásd „The
  Policy" a link:../howto/maintain-git.html["Hogyan tartsuk karban a
  Gitet"] alatt, amely áttekintést ad arról, hogy a Git projekt mely
  brancheket használja, és hogyan.

* A hibajelentésnek tartalmaznia kell információt arról, hogy milyen
  platformot használsz.

* Használd a linkgit:git-bisect[1]-et is, és határozd meg, melyik commit
  vezette be a törést.

* Kérjük, csatolj minden információt, ami a törés természetéről a
  rendelkezésedre áll: memóriaigazítási probléma? Hiányzik vagy hibás egy
  alsóbb szintű könyvtár a platformodon? Van valami furcsaság a
  platformoddal kapcsolatban, ami miatt a tipikus gyakorlatok (mint a
  malloc) furcsán viselkednek?

* Ha lehetséges, buildeld a Gitet pontosan ugyanabból a forrásból a
  platformodra és egy fősodorbeli platformra is, hogy lásd, a probléma,
  amit észrevettél, csak a platformodon jelentkezik-e. Ha a probléma
  mindkettőn megjelenik, akkor nem kompatibilitási probléma, de
  természetesen szívesen hallunk róla egy hibajelentésben így is, minden
  platform felhasználóinak javára. Ha csak a platformodon jelentkezik,
  a jelentésedben egyértelműen említsd meg, hogy kompatibilitási
  problémáról van szó.

* Amint elkezdjük a probléma javítását, kérjük, működj szorosan együtt
  az azon dolgozó közreműködővel, hogy a javasolt javítást a platformodon
  is teszteljétek.

Példa: a NonStop
https://lore.kernel.org/git/01bd01da681a$b8d70a70$2a851f50$@nexbridge.com/[jelenti
a problémákat], amikor észreveszik őket.

[[_compatible_on_master_and_releases]]
Kompatibilis a `master`-en és a kiadásokban
-------------------------------------------

Hogy biztosan minden stabil build és rendszeres kiadás elsőre működjön a
platformodon, segíts elkerülnünk, hogy eltörjük a `master`-t a
platformodon:

* Rendszeres teszteket kell futtatnod a `next` branch ellen, és a
  törésjelentéseket azonnal közzé kell tenned a levelezőlistán, amikor
  megtörténnek.

** Ideális esetben ezeket a teszteket naponta kellene futtatni. Hetinél
   gyakrabban kell futniuk, mivel a témák általában legalább 7 napot
   töltenek a `next`-ben, mielőtt átkerülnének a `master`-be, és időbe
   telik lefékezni egy patchet, amint az bekerül a `next`-be.

** Érdemes lehet kérned a mailto:git-security@googlegroups.com[biztonsági
   levelezőlistára] való felvételedet is, hogy az ott javasolt javítások
   ellen is futtathass teszteket.

* Ezek automatizálása értelmes lehet; ha megteszed, ügyelj rá, hogy ne
  legyenek zajosak (nem kell jelentést küldened, amikor minden működik,
  csak amikor valami eltörik; nem kell ugyanarról a törésről ismételt
  jelentéseket küldened éjszakáról éjszakára).

* A törésjelentéseknek cselekvésre alkalmasnak kell lenniük – tartalmazz
  világos hibaüzeneteket, amelyek segíthetnek azoknak a fejlesztőknek,
  akiknek esetleg nincs hozzáférésük, hogy közvetlenül a platformodon
  teszteljenek.

* Használd a git-bisectet, és határozd meg, melyik commit vezette be a
  törést; ha ezt nem tudod automatizálással megtenni, magadnak kézzel
  kell megtenned, amint észreveszed, hogy törésjelentést küldtek.

* Vagy:

** Igény szerinti hozzáférést biztosítasz a platformodhoz egy megbízható,
   a probléma javításán dolgozó fejlesztőnek, hogy tesztelhesse a
   javítását, VAGY

** Szorosan együttműködsz a problémát javító fejlesztővel; annak
   ellenőrzése, hogy a javasolt javítása működik-e a platformodon,
   elég gyors kell legyen ahhoz, hogy ne akadályozza a javításon dolgozó
   fejlesztőt. A lassú tesztelési átfutás miatt a javítás lemaradhat a
   következő kiadásról, vagy a fejlesztő teljesen elveszítheti az
   érdeklődését a javításon való munka iránt.

Példa:
https://lore.kernel.org/git/CAHd-oW6X4cwD_yLNFONPnXXUAFPxgDoccv2SOdpeLrqmHCJB4Q@mail.gmail.com/[az
AIX] biztosít egy build farmot, és teszteket futtat a kiadásjelöltek
ellen.

[[_compatible_on_next]]
Kompatibilis a `next`-en
------------------------

Hogy elkerüld a reaktív hibakeresést és javítást, amikor a változtatások
egy kiadásba vagy a stabilba kerülnek, arra törekedhetsz, hogy a `next`
mindig működjön a platformodon. (Lásd „The Policy" a
link:../howto/maintain-git.html["Hogyan tartsuk karban a Gitet"] alatt,
amely áttekintést ad arról, hogyan használják a `next`-et a Git
projektben.) Ehhez:

* Adj hozzá egy runnert a platformodhoz a GitHub Actions vagy a GitLab CI
  készlethez.  Ez a készlet akkor fut, amikor bármely Git-fejlesztő új
  patchet javasol, és ha van runner a platformodhoz/konfigurációdhoz, az
  azt jelenti, hogy minden fejlesztő azonnal megtudja, ha eltör téged.

** Ha egy meglévő CI-készlethez való hozzáadása nem kivitelezhető
   (architekturális korlátok vagy teljesítmény-okok miatt), bármely más
   módszer, amely a lehető legautomatikusabban és leggyorsabban fut,
   szintén megfelel. Például egy szolgáltatás, amely figyeli a
   levelezőlistát, és automatikusan teszteket futtat az új [PATCH]
   e-maileken, majd az eredményekkel válaszol a szerzőnek, szintén e
   követelmény szellemében lenne.

* Ha arra hagyatkozol, hogy a Git elkerül egy bizonyos mintát, amely a
  platformoddal nem működik jól (mint egy bizonyos malloc-minta), vesd fel
  a levelezőlistán.  Esetről esetre dolgozunk azon, hogy olyan megoldást
  keressünk, amely nem korlátozza feleslegesen a többi platformot a
  tieddel való kompatibilitás megőrzése érdekében.

* Ha valamely konfigurációra vagy viselkedésre hagyatkozol, adj hozzá
  tesztet. A teszteletlen viselkedés bármikor eltörhet.

** Egyértelműen jelöld meg ezeket a teszteket a
   platformkompatibilitáshoz szükségesként. Add őket egy elkülönített,
   kompatibilitással kapcsolatos tesztkészlethez, mint egy új t* fájl
   vagy unit-tesztkészlet, hogy könnyen eltávolíthatók legyenek, amikor a
   kompatibilitásra már nincs szükség.  Ha az adott kompatibilitási
   igényt egy másik projekt problémája feltételezi, hivatkozz az adott
   probléma dokumentációjára (mint egy bug vagy e-mail-szál), hogy
   könnyebb legyen megállapítani, mikor szűnik meg ez a kompatibilitási
   igény.

** Csatolj egy kommentet e tesztekhez egy lejárati dátummal, amely
   legfeljebb 1 évre van mostantól. A lejárati dátumot frissítheted, ha a
   platformodnak később is szüksége van erre a biztosítékra, de tudnunk
   kell, hogy továbbra is fontos neked ez a kompatibilitási eset, és
   dolgozol azon, hogy feleslegessé tedd.

Példa: A
https://git.kernel.org/pub/scm/git/git.git/tree/.github/workflows/main.yml[CI-
készletünket] Windowson, Ubuntun, Macen és másokon futtatjuk.

[[_getting_help_writing_platform_support_patches]]
Segítségkérés platformtámogatási patchek írásához
-------------------------------------------------

Általánosságban, amikor platformtámogatási problémákat javító patcheket
küldesz, kövesd ezeket az irányelveket, hogy a patch a megfelelő szintű
sürgősséggel kerüljön review-ra:

* A commit-üzenetben egyértelműen jelezd, hogy egy platformtörést
  javítasz, és hogy melyik platformon.

* Használd a CI-t és a tesztkészletet annak biztosítására, hogy a
  platformodhoz készült javítás ne törjön el más platformokat.

* Ha lehetséges, adj hozzá egy tesztet, amely biztosítja, hogy ez a
  regresszió ne forduljon elő újra. Ha nem lehet tesztet hozzáadni,
  magyarázd el, miért, a commit-üzenetben.

[[_platform_maintainers]]
Platform-maintainerek
---------------------

Ha karbantartasz egy platformot, vagy a Gitet arra a platformra, és
szándékodban áll a Git projekttel együttműködni a kompatibilitás
biztosításáért, kérjük, küldj egy patchet, amellyel felveszed magad erre
a listára.

NonStop: Randall S. Becker <rsbecker@nexbridge.com>
