[[_use_of_index_and_racy_git_problem]]
Az index használata és a racy Git probléma
==========================================

[[_background]]
Háttér
------

Az index a Git egyik legfontosabb adatszerkezete.  Egy virtuális
working tree állapotot reprezentál azzal, hogy rögzíti az útvonalak és
azok objektumneveinek listáját, és staging area-ként szolgál a
következő, commitolandó tree objektum kiírásához.  Az állapot abban az
értelemben „virtuális", hogy nem feltétlenül kell egyeznie – és gyakran
nem is egyezik – a working tree fájljaival.

Vannak esetek, amikor a Gitnek meg kell vizsgálnia az indexben lévő
virtuális working tree állapot és a working tree fájljai közötti
különbségeket.  A legnyilvánvalóbb eset az, amikor a felhasználó `git
diff`-et kér (vagy annak alacsonyszintű implementációját, a `git
diff-files`-t), vagy `git-ls-files --modified`-ot.  Ezenkívül a Git
belsőleg is ellenőrzi, hogy a working tree fájljai eltérnek-e az
indexben rögzítettektől, hogy elkerülje a bennük lévő helyi
változtatások eltaposását patch alkalmazása, branchváltás és merge-elés
közben.

A working tree fájljai és az index-bejegyzések közötti
összehasonlítás felgyorsítása érdekében az index-bejegyzések
rögzítik azt az információt, amit a fájlrendszerből az `lstat(2)`
rendszerhívással kaptak, amikor utoljára frissítették őket.  Amikor
ellenőrzi, hogy különböznek-e, a Git először lefuttatja az `lstat(2)`-t
a fájlokon, és összehasonlítja az eredményt ezzel az információval
(ezt eredetileg a `ce_match_stat()` függvény végezte, de a jelenlegi
kód a `ce_match_stat_basic()` függvényben teszi).  Ha ezek közül a
„gyorsítótárazott stat-információ" mezők közül némelyik nem egyezik, a
Git a tartalmuk megnézése nélkül is meg tudja állapítani, hogy a
fájlok módosultak.

Megjegyzés: az `lstat(2)`-vel megszerzett `struct stat` nem minden tagját
használjuk ehhez az összehasonlításhoz.  Például az `st_atime`
nyilvánvalóan nem hasznos.  Jelenleg a Git az `st_mode` tagból a
fájltípust (reguláris fájlok vs szimbolikus linkek) és a
végrehajthatósági biteket (csak reguláris fájloknál), az `st_mtime` és
`st_ctime` időbélyegeket, valamint az `st_uid`, `st_gid`, `st_ino` és
`st_size` tagokat hasonlítja össze.  A `USE_STDEV` fordítási idejű
opcióval az `st_dev` is összehasonlításra kerül, de ez alapértelmezés
szerint nincs engedélyezve, mert ez a tag hálózati fájlrendszereken nem
stabil.  A `USE_NSEC` fordítási idejű opcióval az `st_mtim.tv_nsec` és
`st_ctim.tv_nsec` tagok is összehasonlításra kerülnek. Linuxon ez
alapértelmezés szerint nincs engedélyezve, mert a memóriabeli
időbélyegek finomabb felbontásúak lehetnek, mint a lemezen tárolt
időbélyegek, ami értelmetlen változásokat eredményez, amikor egy inode
kikerül az inode-gyorsítótárból.  Lásd a 8ce13b0 committ a
git://git.kernel.org/pub/scm/linux/kernel/git/tglx/history.git alatt
([PATCH] Sync in core time granularity with filesystems,
2005-01-04). Ez a patch benne van a 2.6.11-es és újabb kernelekben, de
csak a pontosan 1 ns vagy 1 s felbontású fájlrendszereknél oldja meg a
problémát. Más fájlrendszerek a jelenlegi Linux-kernelekben továbbra is
hibásak (pl. CEPH, CIFS, NTFS, UDF), lásd
https://lore.kernel.org/lkml/5577240D.7020309@gmail.com/

[[_racy_git]]
Racy Git
--------

Van egy apró probléma a gyorsítótárazott stat-információn alapuló
optimalizációval.  Vedd fontolóra ezt a sorozatot:

  : modify 'foo'
  $ git update-index 'foo'
  : modify 'foo' again, in-place, without changing its size

Az első `update-index` kiszámítja a `foo` fájl tartalmának
objektumnevét, és a `struct stat` információval együtt frissíti a `foo`
index-bejegyzését.  Ha az ezt követő módosítás nagyon gyorsan
történik, így a fájl `st_mtime` időbélyege nem változik, akkor e
sorozat után az index-bejegyzésben rögzített gyorsítótárazott
stat-információ még mindig pontosan egyezik azzal, amit a
fájlrendszerben látnál, még akkor is, ha a `foo` fájl most már
különböző.
Így a Git tévesen gondolhatja azt, hogy a working tree fájljai
módosítatlanok, holott valójában módosultak.  Ezt nevezzük a „racy
Git" problémának (Pasky fedezte fel), és azokat a bejegyzéseket,
amelyek e probléma miatt tisztának tűnnek, holott lehet, hogy nem
azok, „racily clean" bejegyzéseknek hívjuk.

E probléma elkerülésére a Git két dolgot tesz:

. Amikor a gyorsítótárazott stat-információ szerint a fájl nem
  módosult, és az `st_mtime` ugyanaz (vagy újabb), mint magának az
  indexfájlnak az időbélyege (ami a fenti példában az az időpont, amikor
  a `git update-index foo` befejezte a futást), akkor a tartalmat is
  összehasonlítja az index-bejegyzésben regisztrált objektummal, hogy
  megbizonyosodjon az egyezésről.

. Amikor egy racily clean bejegyzéseket tartalmazó indexfájlt
  frissítenek, a gyorsítótárazott `st_size` információ nullára csonkul
  az indexfájl új verziójának kiírása előtt.

Mivel magát az indexfájlt a frissített útvonalak összes
stat-információjának összegyűjtése után írjuk ki, annak `st_mtime`
időbélyege általában ugyanaz vagy újabb, mint az index bármely
útvonaláé.  És bármilyen gyorsan is fejeződik be a `git update-index
foo`-t követő módosítás, a `foo` eredményül kapott `st_mtime`
időbélyege nem kaphat az indexfájlénál korábbi értéket.  Ezért a
racily clean bejegyzések azokra korlátozódnak, amelyeknek ugyanaz az
időbélyegük, mint magának az indexfájlnak.

Azok a hívók, amelyek ellenőrizni akarják, hogy egy index-bejegyzés
egyezik-e a working tree megfelelő fájljával, továbbra is a
`ce_match_stat()`-et hívják, de ezzel a változtatással a
`ce_match_stat()` a `ce_modified_check_fs()`-t használja annak
megállapítására, hogy a racily clean bejegyzések valóban tiszták-e,
miután a `ce_match_stat_basic()`-kel összehasonlította a
gyorsítótárazott stat-információt.

A probléma, amit az utóbbi megold, ez a sorozat:

  $ git update-index 'foo'
  : modify 'foo' in-place without changing its size
  : wait for enough time
  $ git update-index 'bar'

Az utóbbi nélkül az indexfájl időbélyege újabb értéket kap, és a
tévesen tisztának hitt `foo` bejegyzést a korábbi logika által végzett
időbélyeg-összehasonlító ellenőrzés többé nem kapná el.  Az utóbbi
gondoskodik arról, hogy a `foo` gyorsítótárazott stat-információja soha
ne egyezzen a working tree-ben lévő fájllal, így a `ce_match_stat_basic()`
későbbi ellenőrzései azt jelentenék, hogy az index-bejegyzés nem egyezik
a fájllal, és a Gitnek nem kell a drágább `ce_modified_check_fs()`-hez
folyamodnia.


[[_runtime_penalty]]
Futásidejű büntetés
-------------------

A `ce_match_stat()`-ből a `ce_modified_check_fs()`-hez való
folyamodás futásidejű büntetése nagyon költséges lehet, ha sok racily
clean bejegyzés van.  Ezt a helyzetet mesterségesen létrehozni
kézenfekvő módon úgy lehet, hogy egy nagy projektben a working tree
összes fájljának ugyanazt az időbélyeget adjuk, lefuttatjuk rajtuk a
`git update-index`-et, és az indexfájlnak is ugyanazt az időbélyeget
adjuk:

  $ date >.datestamp
  $ git ls-files | xargs touch -r .datestamp
  $ git ls-files | git update-index --stdin
  $ touch -r .datestamp .git/index

Ez minden index-bejegyzést racily clean-né tesz.  A linux projektben
például több mint 20 000 fájl van a working tree-ben.  Az én Athlon 64
X2 3800+-omon a fentiek után:

  $ /usr/bin/time git diff-files
  1.68user 0.54system 0:02.22elapsed 100%CPU (0avgtext+0avgdata 0maxresident)k
  0inputs+0outputs (0major+67111minor)pagefaults 0swaps
  $ git update-index MAINTAINERS
  $ /usr/bin/time git diff-files
  0.02user 0.12system 0:00.14elapsed 100%CPU (0avgtext+0avgdata 0maxresident)k
  0inputs+0outputs (0major+935minor)pagefaults 0swaps

A `git update-index` közben történő futtatása ellenőrizte a racily
clean bejegyzéseket, és minden útvonal gyorsítótárazott `st_mtime`-ját
érintetlenül hagyta, mert valójában tiszták voltak (így ez a lépés
nagyjából ugyanannyi ideig tartott, mint az első `git diff-files`).
Ezután már nem racily clean-ek, hanem valóban tiszták, így a `git
diff-files` második meghívása teljesen kihasználta a gyorsítótárazott
stat-információt.


[[_avoiding_runtime_penalty]]
A futásidejű büntetés elkerülése
--------------------------------

A fenti futásidejű büntetés elkerülésére az 1.4.2 utáni Git
korábban tartalmazott egy kódot, amely gondoskodott arról, hogy az
indexfájl az index legfrissebb fájljainál újabb időbélyeget kapjon,
amikor sok friss fájl volt olyan időbélyeggel, mint amilyet az
eredményül kapott indexfájl egyébként kapna – oly módon, hogy várt az
indexfájl kiírásának befejezése előtt.

Gyanítottam, hogy a gyakorlatban az a helyzet, amikor az indexben sok
útvonal mind racily clean, meglehetősen ritka.  Az egyetlen olyan
kódútvonal, amely nagyszámú útvonalhoz rögzíthet friss időbélyeget:

. Egy nagy projekt kezdeti `git add .`-ja.

. Egy nagy projekt `git checkout`-ja üres indexből egy feltöltetlen
  working tree-be.

Megjegyzés: a branchek közötti váltás a `git checkout`-tal megtartja azon
meglévő working tree fájlok gyorsítótárazott stat-információját,
amelyek a jelenlegi branch és az új branch között azonosak, amelyek
mind régebbiek, mint az eredményül kapott indexfájl, és nem lesznek
racily clean-ek.  Csak azok a fájlok válhatnak racily clean-né,
amelyeket ténylegesen kicheckoutolnak.

Egy nagy projektben viszont, ahol a raciness elkerülésének költsége
valóban számít, az index összes objektumnevének kezdeti kiszámítása
több mint egy másodpercig tart, és az indexfájlt mindezek megtörténte
után írjuk ki.  Ezért az indexfájl időbélyege több mint egy
másodperccel későbbi lesz, mint a working tree legfrissebb fájljáé.
Ez azt jelenti, hogy ezekben az esetekben valójában nem lesz egyetlen
racily clean bejegyzés sem az eredményül kapott indexben.

E megbeszélés alapján a jelenlegi kód nem használja a „kerülőmegoldást"
a gyakorlatban már nem létező futásidejű büntetés elkerülésére.  Ezt a
0fc82cff committal tettük meg 2006. augusztus 15-én.
