reftable
--------

Áttekintés
~~~~~~~~~~

Problémafelvetés
^^^^^^^^^^^^^^^^

Néhány repository sok referenciát tartalmaz (pl. az android 866 ezret, a
rails 31 ezret). A meglévő packed-refs formátum sok helyet foglal (pl.
62 M), és nem skálázódik a további referenciákkal. Egyetlen referencia
kikeresése a fájl lineáris végigpásztázását igényli.

A több referenciát módosító atomi pushok az egész packed-refs fájl
másolását igénylik, ami tetemes mennyiségű mozgatott adat lehet (pl.
62 M be, 62 M ki) még kis tranzakcióknál is (2 ref módosítva).

A sok laza referenciával rendelkező repository-k nagyszámú lemezblokkot
foglalnak a helyi fájlrendszerből, mivel minden referencia egy önálló
fájl, amely 41 bájtot tárol (és még egy fájl a hozzá tartozó
refloghoz). Ez negatívan érinti az elérhető inode-ok számát, amikor sok
repository van ugyanazon a fájlrendszeren tárolva. Az olvasók
büntetést kaphatnak a `$GIT_DIR/refs` könyvtár bejárásához és
olvasásához szükséges nagyobb számú rendszerhívás miatt.


Célok
^^^^^

* Közel állandó idejű kikeresés bármely egyetlen referenciára, még
akkor is, ha a repository hideg, és nincs a folyamat vagy a kernel
gyorsítótárában.
* Közel állandó idejű ellenőrzés arra, hogy egy objektumnévre legalább
egy referencia hivatkozik-e (az allow-tip-sha1-in-want-hoz).
* Egy egész névtér, például a `refs/tags/` hatékony felsorolása.
* Atomi push támogatása `O(size_of_update)` művelettel.
* A reflog-tárolás összevonása a reftárolással a kis tranzakciókhoz.
* Külön reflog-tárolás az alap refekhez és a történeti logokhoz.

Leírás
^^^^^^

A reftable fájl egy hordozható bináris fájlformátum, amelyet
referenciatárolásra szabtak. A referenciák rendezettek, ami lehetővé
teszi a lineáris pásztázást, a bináris keresést és a
tartománypásztázást.

A fájlban a tárolás változó méretű blokkokba van szervezve. Egyetlen
blokkon belül előtag-tömörítést használunk a lemezterület
csökkentésére. A blokkméret és -igazítás az író által hangolható.

Teljesítmény
^^^^^^^^^^^^

Felhasznált hely, packed-refs vs. reftable:

[cols=",>,>,>,>,>",options="header",]
|===============================================================
|repository |packed-refs |reftable |% eredeti |átl. ref |átl. obj
|android |62.2 M |36.1 M |58.0% |33 bytes |5 bytes
|rails |1.8 M |1.1 M |57.7% |29 bytes |4 bytes
|git |78.7 K |48.1 K |61.0% |50 bytes |4 bytes
|git (heads) |332 b |269 b |81.0% |33 bytes |0 bytes
|===============================================================

Pásztázás (866 ezer ref olvasása), referencianév szerinti kikeresés (egy
ref a 866 ezerből), és SHA-1 szerinti kikeresés (az adott SHA-1-gyel
rendelkező refek, a 866 ezerből):

[cols=",>,>,>,>",options="header",]
|=========================================================
|formátum |gyorsítótár |pásztázás |név szerint |SHA-1 szerint
|packed-refs |cold |402 ms |409,660.1 usec |412,535.8 usec
|packed-refs |hot | |6,844.6 usec |20,110.1 usec
|reftable |cold |112 ms |33.9 usec |323.2 usec
|reftable |hot | |20.2 usec |320.8 usec
|=========================================================

43 061 ref 149 932 log-bejegyzéséhez felhasznált hely, reflog vs.
reftable:

[cols=",>,>",options="header",]
|================================
|formátum |méret |átl. bejegyzés
|$GIT_DIR/logs |173 M |1209 bytes
|reftable |5 M |37 bytes
|================================

Részletek
~~~~~~~~~

Lefejtés
^^^^^^^^

A reftable-ben tárolt referenciák le vannak fejtve: egy annotált (vagy
aláírt) taghez tartozó rekord rögzíti mind a tagobjektumot, mind azt az
objektumot, amelyre hivatkozik. Ez analóg a packed-refs formátumban való
tárolással.

Referencianév-kódolás
^^^^^^^^^^^^^^^^^^^^^

A referencianevek bájtok értelmezetlen sorozatai, amelyeknek érvényes
referencianévként át kell menniük a linkgit:git-check-ref-format[1]-en.

Kulcsegyediség
^^^^^^^^^^^^^^

Minden bejegyzésnek egyedi kulccsal kell rendelkeznie; az ismétlődő
kulcsok nem megengedettek.

Hálózati bájtsorrend
^^^^^^^^^^^^^^^^^^^^

Minden többbájtos, fix szélességű mező hálózati bájtsorrendben van.

Varint kódolás
^^^^^^^^^^^^^^

A varint kódolás azonos a pack fájlokon belül használt ofs-delta
kódolási módszerrel.

A dekódoló a következőképpen működik:

....
val = buf[ptr] & 0x7f
while (buf[ptr] & 0x80) {
  ptr++
  val = ((val + 1) << 7) | (buf[ptr] & 0x7f)
}
....

Rendezés
^^^^^^^^

A blokkok lexikografikusan rendezettek az első referenciájuk szerint.

Könyvtár/fájl konfliktusok
^^^^^^^^^^^^^^^^^^^^^^^^^^

A reftable formátum a `refs/heads/foo`-t és a `refs/heads/foo/bar`-t is
külön referenciaként fogadja el.

Ez a tulajdonság hasznos a log-rekordok reftable-ben való megőrzéséhez,
de megzavarhatja a Git azon verzióit, amelyek a `$GIT_DIR/refs`
könyvtárfát használják a referenciák karbantartásához. A reftable
felhasználói dönthetnek úgy, hogy továbbra is elutasítják a `foo` és
`foo/bar` típusú konfliktusokat, hogy elkerüljék a problémákat a
társaknál.

Fájlformátum
~~~~~~~~~~~~

Szerkezet
^^^^^^^^^

Egy reftable fájl a következő magas szintű szerkezettel rendelkezik:

....
first_block {
  header
  first_ref_block
}
ref_block*
ref_index*
obj_block*
obj_index*
log_block*
log_index*
footer
....

A csak logot tartalmazó fájl kihagyja a `ref_block`, `ref_index`,
`obj_block` és `obj_index` szakaszokat, csak a fájlfejlécet és a
log-blokkot tartalmazza:

....
first_block {
  header
}
log_block*
log_index*
footer
....

Egy csak logot tartalmazó fájlban az első log-blokk közvetlenül a
fájlfejléc után következik, a blokkigazításhoz szükséges kitöltés nélkül.

Blokkméret
^^^^^^^^^^

A fájl blokkméretét az író tetszőlegesen határozza meg, és nem kell
kettőhatványnak lennie. A blokkméretnek nagyobbnak kell lennie, mint a
repository-ban használt leghosszabb referencianév vagy log-bejegyzés,
mivel a referenciák nem terjedhetnek át blokkokon.

A virtuális memóriarendszerhez vagy a fájlrendszerhez barátságos
kettőhatványok (mint a 4k vagy a 8k) ajánlottak. A nagyobb méretek (64k)
jobb tömörítést eredményezhetnek, de esetleg megnövelt költséggel járnak
az olvasók számára hozzáférés közben.

A legnagyobb blokkméret `16777215` bájt (15,99 MiB).

Blokkigazítás
^^^^^^^^^^^^^

Az írók dönthetnek úgy, hogy a blokkokat a blokkméret többszöröseire
igazítják úgy, hogy a blokk végére NUL bájtokkal feltöltött `padding`-et
tesznek, hogy kikerekítsenek a választott igazításra. Amikor igazítást
használunk, az íróknak meg kell adniuk az igazítást a fájlfejléc
`block_size` mezőjével.

A blokkigazítást a fájlformátum nem követeli meg. Az igazítatlan
fájloknak `block_size = 0`-t kell beállítaniuk a fájlfejlécben, és ki
kell hagyniuk a `padding`-et. Az egynél több ref blokkot tartalmazó
igazítatlan fájloknak tartalmazniuk kell a link:#Ref-index[ref-indexet] a
gyors kikeresés támogatásához. Az olvasóknak képesnek kell lenniük mind
az igazított, mind a nem igazított fájlok olvasására.

A nagyon kis fájlok (pl. egyetlen ref blokk) kihagyhatják a `padding`-et
és a ref-indexet a teljes fájlméret csökkentésére.

Fejléc (1-es verzió)
^^^^^^^^^^^^^^^^^^^^

A fájl elején egy 24 bájtos fejléc jelenik meg:

....
'REFT'
uint8( version_number = 1 )
uint24( block_size )
uint64( min_update_index )
uint64( max_update_index )
....

Az igazított fájloknak meg kell adniuk a `block_size`-t, hogy
beállítsák az olvasók számára a várt blokkigazítást. Az igazítatlan
fájloknak `block_size = 0`-t kell beállítaniuk.

A `min_update_index` és a `max_update_index` a fájl összes
log-rekordjának `update_index` mezőjére vonatkozó határokat írja le.
Amikor a reftable-öket egy veremben
link:#Update-transactions[tranzakciókhoz] használják, ezek a mezők úgy
rendezhetik a fájlokat, hogy az előző fájl `max_update_index + 1`-je a
következő fájl `min_update_index`-e.

Fejléc (2-es verzió)
^^^^^^^^^^^^^^^^^^^^

A fájl elején egy 28 bájtos fejléc jelenik meg:

....
'REFT'
uint8( version_number = 2 )
uint24( block_size )
uint64( min_update_index )
uint64( max_update_index )
uint32( hash_id )
....

A fejléc azonos a `version_number=1`-gyel, azzal, hogy a fejléchez
hozzá van fűzve a 4 bájtos hash ID ("sha1" a SHA1-hez és "s256" a
SHA-256-hoz).

A maximális visszafelé kompatibilitás érdekében ajánlott az 1-es
verziót használni SHA1 reftable-ök írásakor.

Első ref blokk
^^^^^^^^^^^^^^

Az első ref blokk ugyanazt a blokkot osztja meg a fájlfejléccel, és 24
bájttal kisebb, mint a fájl összes többi blokkja. Az első blokk
közvetlenül a fájlfejléc után kezdődik, a 24-es pozíción.

Ha az első blokk egy log-blokk (egy csak logot tartalmazó fájl), akkor
a blokkfejléce közvetlenül a 24-es pozíción kezdődik.

Ref blokk formátuma
^^^^^^^^^^^^^^^^^^^

Egy ref blokk így íródik:

....
'r'
uint24( block_len )
ref_record+
uint24( restart_offset )+
uint16( restart_count )

padding?
....

A blokkok `block_type = 'r'`-rel és egy 3 bájtos `block_len`-nel
kezdődnek, amely a blokkban lévő bájtok számát kódolja az opcionális
`padding`-ig, de azt nem beleértve. Ez mindig kisebb vagy egyenlő, mint
a fájl blokkmérete. Az első ref blokkban a `block_len` 24 bájtot
tartalmaz a fájlfejléchez.

A 2 bájtos `restart_count` a `restart_offset` lista bejegyzéseinek számát
tárolja, amely nem lehet üres. Az olvasók a `restart_count`-tal bináris
keresést végezhetnek az újraindítási pontok között, mielőtt lineáris
pásztázásba kezdenének.

Pontosan `restart_count` darab 3 bájtos `restart_offset` érték előzi meg
a `restart_count`-ot. Az eltolások a blokk kezdetéhez viszonyítottak, és
bármely olyan `ref_record` első bájtjára hivatkoznak, amelynek a neve
nem lett előtag-tömörítve. A `restart_offset` lista bejegyzéseinek
rendezettnek kell lenniük, növekvő sorrendben. Az olvasók e rekordok
bármelyikéből elkezdhetik a lineáris pásztázást.

Változó számú `ref_record` tölti ki a blokk közepét, amelyek a
referencianeveket és -értékeket írják le. A formátumot lentebb írjuk le.

Mivel az első ref blokk az első fájlblokkot a fájlfejléccel osztja meg,
az első blokkban minden `restart_offset` a fájl kezdetéhez (0-s pozíció)
viszonyított, és tartalmazza a fájlfejlécet. Ez arra kényszeríti az első
`restart_offset`-et, hogy `28` legyen.

ref rekord
++++++++++

Egy `ref_record` egyetlen referenciát ír le, tárolva mind a nevet, mind
az értékét/értékeit. A rekordok formátuma:

....
varint( prefix_length )
varint( (suffix_length << 3) | value_type )
suffix
varint( update_index_delta )
value?
....

A `prefix_length` mező azt adja meg, hogy az előző referenciarekord
nevének hány kezdő bájtját kell átmásolni e referencia nevének
megszerzéséhez. Ennek 0-nak kell lennie bármely blokk első referenciája
esetén, és 0-nak kell lennie bármely olyan `ref_record` esetén is,
amelynek az eltolása szerepel a blokk végén lévő `restart_offset`
táblában.

Egy referencianév visszaállítása bármely `ref_record`-ból egy egyszerű
összefűzés:

....
this_name = prior_name[0..prefix_length] + suffix
....

A `suffix_length` érték megadja a `suffix`-ban rendelkezésre álló bájtok
számát, amelyeket a `suffix`-ból át kell másolni a referencianév
kiegészítéséhez.

A referenciát utoljára módosító `update_index` úgy szerezhető meg, hogy
az `update_index_delta`-t hozzáadjuk a fájlfejlécbeli
`min_update_index`-hez: `min_update_index + update_index_delta`.

Ezután következik a `value`. Formátumát a `value_type` határozza meg, a
következők egyike:

* `0x0`: törlés; nincs értékadat (lásd a tranzakciókat lentebb)
* `0x1`: egy objektumnév; a ref értéke
* `0x2`: két objektumnév; a ref értéke, a lefejtett cél
* `0x3`: szimbolikus referencia: `varint( target_len ) target`

A szimbolikus referenciák `0x3`-at használnak, amelyet a referencia
céljának teljes neve követ. A célnévre nem alkalmazunk tömörítést.

A `0x4..0x7` típusok jövőbeli használatra vannak fenntartva.

[[Ref-index]]
Ref-index
^^^^^^^^^

A ref-index a fájl minden ref blokkjából eltárolja az utolsó referencia
nevét, ami lehetővé teszi a kikeresésekhez szükséges lemezelérések
csökkentését. Bármely referencia megtalálható az index átkeresésével, a
tartalmazó blokk azonosításával, majd az adott blokkon belüli
kereséssel.

Az index szervezhető többszintű indexbe, ahol az 1. szintű indexblokk
további ref-indexblokkokra (2. szint) mutat, amelyek viszont
mutathatnak vagy további indexblokkokra (pl. 3. szint), vagy ref
blokkokra (levélszint). Egy ref eléréséhez szükséges lemezolvasások
száma nő a magasabb indexszintekkel. Többszintű indexekre lehet szükség
annak biztosítására, hogy egyetlen indexblokk se lépje túl a
fájlformátum `16777215` bájtos (15,99 MiB) maximális blokkméretét. Az
állandó O(1) lemezelérés eléréséhez a kikeresésekhez az indexnek
egyszintűnek kell lennie, ami túllépheti a fájl beállított blokkméretét,
de a formátum 15,99 MiB-os maximális blokkméretét nem.

Ha jelen van, a ref-indexblokk(ok) az utolsó ref blokk után jelenik meg.

Ha legalább 4 ref blokk van, ref-indexblokkot kell írni a kikeresési
idők javítására. Az index használatával végzett hideg olvasások 2
lemezolvasást igényelnek (index olvasása, blokk olvasása), és < 4 blokk
bináris keresése szintén <= 2 olvasást igényel. Az indexblokk kihagyása
a kisebb fájlokból helyet takarít meg.

Ha a fájl igazítatlan, és egynél több ref blokkot tartalmaz, a
ref-indexet meg kell írni.

Indexblokk formátuma:

....
'i'
uint24( block_len )
index_record+
uint24( restart_offset )+
uint16( restart_count )

padding?
....

Az indexblokkok `block_type = 'i'`-vel és egy 3 bájtos `block_len`-nel
kezdődnek, amely a blokkban lévő bájtok számát kódolja az opcionális
`padding`-ig, de azt nem beleértve.

A `restart_offset` és a `restart_count` mező formátumában, jelentésében
és használatában azonos a ref blokkokéval.

A nagyon nagy fájlokban a véletlen hozzáféréshez szükséges olvasások
számának csökkentésére az indexblokk nagyobb lehet a többi blokknál. Az
olvasóknak azonban a teljes indexet a memóriában kell tartaniuk, hogy
ebből hasznot húzzanak, tehát ez egy idő-hely kompromisszum mind a
fájlméret, mind az olvasó memóriája tekintetében.

A fájl blokkméretének növelése csökkenti az index méretét. Alternatívaként
többszintű index használható, amely az indexblokkokat a fájl blokkméretén
belül tartja, de növeli az elérendő blokkok számát.

index rekord
++++++++++++

Egy index rekord egy másik blokk utolsó bejegyzését írja le. Az index
rekordok így íródnak:

....
varint( prefix_length )
varint( (suffix_length << 3) | 0 )
suffix
varint( block_position )
....

Az index rekordok pontosan úgy használnak előtag-tömörítést, mint a
`ref_record`.

Az index rekordok a suffix után tárolják a `block_position`-t, amely
bájtban (a fájl kezdetétől) megadja annak a blokknak az abszolút
pozícióját, amely ezzel a referenciával végződik. Az olvasók a
`block_position`-re pozicionálhatnak, hogy elkezdjék a blokkfejléc
olvasását.

Az olvasóknak meg kell vizsgálniuk a `block_position`-nél lévő
blokkfejlécet, hogy meghatározzák, a következő blokk egy másik szintű
indexblokk-e, vagy a levélszintű ref blokk.

Az index olvasása
+++++++++++++++++

A ref-indexet betöltő olvasóknak először el kell olvasniuk a láblécet
(lentebb), hogy megszerezzék a `ref_index_position`-t. Ha nincs jelen, a
pozíció 0 lesz. A `ref_index_position` a ref-index 1. szintű gyökeréé.

Obj blokk formátuma
^^^^^^^^^^^^^^^^^^^

Az objektumblokkok opcionálisak. Az írók dönthetnek úgy, hogy kihagyják
az objektumblokkokat, különösen ha az olvasók nem használják az
objektumnév–ref leképezést.

Az objektumblokkok egyedi, rövidített 2–31 bájtos objektumnév-kulcsokat
használnak, amelyek olyan ref blokkokra képeznek le, amelyek az adott
objektumra közvetlenül, vagy egy annotált tag lefejtett értékeként
mutató referenciákat tartalmaznak. A ref blokkokhoz hasonlóan az
objektumblokkok a fájl standard blokkméretét használják. A rövidítés
hossza a láblécben `obj_id_len`-ként érhető el.

A kis fájlokban való helymegtakarítás érdekében az objektumblokkok
kihagyhatók, ha a ref-index nincs jelen, mivel a nyers erővel végzett
keresésnek csak néhány ref blokkot kell olvasnia. Ha hiányzik, az
olvasóknak nyers erővel, az összes referencia lineáris átkeresésével
kell kikeresniük objektumnév szerint.

Egy objektumblokk így íródik:

....
'o'
uint24( block_len )
obj_record+
uint24( restart_offset )+
uint16( restart_count )

padding?
....

A mezők azonosak a ref blokkéval. Az újraindítási táblát használó
bináris keresés ugyanúgy működik, mint a referenciablokkokban.

Mivel az objektumneveket az írók a reftable-ön belüli legrövidebb egyedi
rövidítésre rövidítik, az obj kulcsok hossza változó. A hosszuknak
legalább 2 bájtnak kell lennie. Az olvasóknak csak közös előtag-egyezésre
kell összehasonlítaniuk egy obj blokkon vagy obj-indexen belül.

obj rekord
++++++++++

Egy `obj_record` egyetlen objektumrövidítést ír le, valamint azokat a
blokkokat, amelyek ezt az egyedi rövidítést használó referenciákat
tartalmaznak:

....
varint( prefix_length )
varint( (suffix_length << 3) | cnt_3 )
suffix
varint( cnt_large )?
varint( position_delta )*
....

A referenciablokkokhoz hasonlóan a rövidítések előtag-tömörítettek egy
obj blokkon belül. Sok egyedi objektummal rendelkező nagy reftable-ökön,
magasabb blokkméretekkel (64k) és magasabb újraindítási intervallummal
(128) a 2-es vagy 3-as `prefix_length` és a 3-as `suffix_length` gyakori
lehet az obj rekordokban (5–6 nyers bájtos, 10–12 hexadecimális
számjegyű egyedi rövidítés).

Minden rekord `position_count` számú pozíciót tartalmaz az egyező ref
blokkokhoz. 1–7 pozíció esetén a szám a `cnt_3`-ban van tárolva. Amikor
`cnt_3 = 0`, a tényleges szám egy varintben követi, `cnt_large`.

A `cnt_3` használata arra fogad, hogy a legtöbb objektumra csak egyetlen
referencia mutat, néhányra mutathat egy-két referencia, és nagyon
kevésre (ha egyáltalán) mutat 7-nél több referencia.

Egy speciális eset létezik, amikor `cnt_3 = 0` és `cnt_large = 0`: nincs
`position_delta`, de legalább egy referencia ezzel a rövidítéssel
kezdődik. Egy olyan olvasónak, amelynek pontos referencianevekre van
szüksége, át kell pásztáznia az összes referenciát, hogy megtalálja,
mely konkrét referenciák tartalmazzák a kívánt objektumot. Az íróknak
ezt a formátumot kell használniuk, ha a `position_delta` lista túlcsordult
volna a fájl blokkméretén az ugyanarra az objektumra mutató referenciák
nagy száma miatt.

Az első `position_delta` a fájl kezdetétől számított pozíció. A további
`position_delta` bejegyzések növekvő sorrendben rendezettek, és az előző
bejegyzéshez viszonyítottak, pl. egy olvasó a következőt végezné el:

....
pos = position_delta[0]
prior = pos
for (j = 1; j < position_count; j++) {
  pos = prior + position_delta[j]
  prior = pos
}
....

Egy pozíció birtokában az olvasónak lineárisan át kell pásztáznia a ref
blokkot, az első `ref_record`-tól kezdve, tesztelve minden referencia
objektumneveit (`value_type = 0x1` vagy `0x2` esetén) teljes egyezésre. Az
objektumnév szerinti gyorsabb keresést egyetlen ref blokkon belül a
reftable formátum nem támogatja. A kisebb blokkméretek csökkentik a
jelöltek számát, amelyeket ennek a lépésnek meg kell fontolnia.

Obj-index
^^^^^^^^^

Az obj-index a fájl minden obj blokkjának utolsó bejegyzéséből eltárolja
a rövidítést, ami lehetővé teszi a csökkentett lemezelérést minden
kikereséshez. Pontosan ugyanúgy van formázva, mint a ref-index, de obj
blokkokra hivatkozik.

Az obj-indexnek jelen kell lennie, ha obj blokkok jelen vannak, mivel obj
blokkokat csak nagyobb fájlokba szabad írni.

Az obj-indexet betöltő olvasóknak először el kell olvasniuk a láblécet
(lentebb), hogy megszerezzék az `obj_index_position`-t. Ha nincs jelen, a
pozíció 0 lesz.

Log blokk formátuma
^^^^^^^^^^^^^^^^^^^

A ref és obj blokkokkal ellentétben a log-blokkok mindig igazítatlanok.

A log-blokkok mérete változó, és nem egyezik a fájlfejlécben vagy
láblécben megadott `block_size`-zal. Az íróknak megfelelő pufferméretet
kell választaniuk a log-blokk deflálásra való előkészítéséhez, mint pl.
`2 * block_size`.

Egy log-blokk így íródik:

....
'g'
uint24( block_len )
zlib_deflate {
  log_record+
  uint24( restart_offset )+
  uint16( restart_count )
}
....

A log-blokkok hasonlítanak a ref blokkokra, azzal a kivétellel, hogy
`block_type = 'g'`.

A 4 bájtos blokkfejlécet a zlib deflate-tel deflált blokktartalom
követi. A fejlécben lévő `block_len` az inflált méret (a 4 bájtos
blokkfejlécet is beleértve), és az olvasóknak arra kell használniuk,
hogy előre lefoglalják az inflálás kimeneti pufferét. Egy log-blokk
`block_len`-je túllépheti a fájl blokkméretét.

A log-blokkon belüli eltolások (pl. `restart_offset`) továbbra is
tartalmazzák a 4 bájtos fejlécet. Az olvasók előnyben részesíthetik, hogy
az inflálás kimeneti pufferét a 4 bájtos fejléccel előtagozzák.

A deflate konténeren belül változó számú `log_record` írja le a
referenciaváltozásokat. A log-rekord formátumát lentebb írjuk le. A
`restart_offset` és a `restart_count` leírásáért lásd a ref blokk
formátumát (fentebb).

Mivel a log-blokkok között nincs igazítás vagy kitöltés, az olvasóknak
nyomon kell követniük az infláló által elfogyasztott bájtokat, hogy
tudják, hol kezdődik a következő log-blokk.

log rekord
++++++++++

A log-rekord kulcsok szerkezete:

....
ref_name '\0' reverse_int64( update_index )
....

ahol az `update_index` az egyedi tranzakcióazonosító. Az `update_index`
mezőnek egyedinek kell lennie egy `ref_name` hatókörén belül. További
részletekért lásd a frissítési tranzakciók szakaszt lentebb.

A `reverse_int64` függvény megfordítja az értéket, így a hálózati
bájtsorrend-kódolás lexikografikus rendezése a frissebb rekordokat, a
magasabb `update_index` értékekkel, előre sorolja:

....
reverse_int64(int64 t) {
  return 0xffffffffffffffff - t;
}
....

A log-rekordok kezdő szerkezete hasonló a ref és index rekordokéhoz, a
fent leírt log-rekord kulcsra alkalmazott ugyanazon előtag-tömörítési
sémát használva.

....
    varint( prefix_length )
    varint( (suffix_length << 3) | log_type )
    suffix
    log_data {
      old_id
      new_id
      varint( name_length    )  name
      varint( email_length   )  email
      varint( time_seconds )
      sint16( tz_offset )
      varint( message_length )  message
    }?
....

A log-rekord bejegyzések a `log_type`-ot használják annak jelzésére, hogy
mi következik:

* `0x0`: törlés; nincs log-adat.
* `0x1`: standard git reflog-adat a fenti `log_data` használatával.

A `log_type = 0x0` leginkább a `git stash drop`-hoz hasznos, amely egy
bejegyzést távolít el a `refs/stash` reflogjából egy tranzakciós fájlban
(lentebb), anélkül, hogy nagyobb fájlokat kellene újraírni. A reflogok
egy vermét olvasó olvasóknak ezt törlésként kell kezelniük.

`log_type = 0x1` esetén a `log_data` szakasz a linkgit:git-update-ref[1]
naplózását követi, és tartalmazza:

* két objektumnév (régi id, új id)
* a commitoló nevének varint sztringje
* a commitoló e-mailjének varint sztringje
* varint idő másodpercben az epoch (1970. jan. 1.) óta
* 2 bájtos időzóna-eltolás percben (előjeles)
* az üzenet varint sztringje

A `tz_offset` a GMT-től számított percek abszolút száma, ahol a commitoló
a frissítés időpontjában volt. Például a `GMT-0800` a reftable-ben
`sint16(-480)`-ként van kódolva, a `GMT+0230` pedig `sint16(150)`.

A commitoló e-mailje nem tartalmaz `<` vagy `>` karaktert, ez az az
érték, amely normál esetben a `<>` között található egy git commit
objektum fejlécében.

A `message_length` lehet 0, amely esetben nem adtak meg üzenetet a
frissítéshez.

A hagyományos refloggal (amely egy fájl) ellentétben az átnevezések ref
törlés és ref létrehozás kombinációjaként vannak kódolva.  A törlés egy
nulla new_id-jú log-rekord, a létrehozás pedig egy nulla old_id-jú
log-rekord.

A log olvasása
+++++++++++++++

A logot elérő olvasóknak először el kell olvasniuk a láblécet (lentebb),
hogy meghatározzák a `log_position`-t. A log első blokkja a fájl
kezdetétől számított `log_position` bájtnál kezdődik. A `log_position`
nem blokkigazított.

Logok importálása
++++++++++++++

A `$GIT_DIR/logs`-ból való importáláskor az íróknak globálisan,
nagyjából időbélyeg szerint kell rendezniük az összes log-rekordot,
megőrizve a fájlsorrendet, és minden log-sorhoz egyedi, növekvő
`update_index` értékeket kell rendelniük. Az újabb log-rekordok magasabb
`update_index` értékeket kapnak.

Bár egy import csak egyetlen reftable fájlt írhat, a reftable fájlnak
sok egyedi `update_index`-en kell átívelnie, mivel minden log-sornak a
saját `update_index`-e kell legyen a szemantika megőrzéséhez.

Log-index
^^^^^^^^^

A log-index a fájl minden log-blokkjának utolsó log-rekordjához eltárolja
a log-kulcsot (`refname \0 reverse_int64(update_index)`), ami korlátos
idejű kikeresést támogat.

Log-indexblokkot kell írni, ha 2 vagy több log-blokkot írnak a fájlba.
Ha jelen van, a log-index az utolsó log-blokk után jelenik meg. Nincs
kitöltés a log-index blokkigazításhoz való igazítására.

A log-index formátuma azonos a ref-indexével, azzal a kivétellel, hogy a
kulcsok 9 bájttal hosszabbak, hogy tartalmazzák a `'\0'`-t és a 8 bájtos
`reverse_int64(update_index)`-et. A rekordok a `block_position`-t
használják egy log-blokk kezdetére való hivatkozásra.

Az index olvasása
+++++++++++++++++

A log-indexet betöltő olvasóknak először el kell olvasniuk a láblécet
(lentebb), hogy megszerezzék a `log_index_position`-t. Ha nincs jelen, a
pozíció 0 lesz.

Lábléc
^^^^^^

A fájl utolsó blokkja után egy fájlláblécet írunk. Úgy kezdődik, mint a
fájlfejléc, de további adatokkal van kiegészítve.

....
    HEADER

    uint64( ref_index_position )
    uint64( (obj_position << 5) | obj_id_len )
    uint64( obj_index_position )

    uint64( log_position )
    uint64( log_index_position )

    uint32( CRC-32 of above )
....

If a section is missing (e.g. ref index) the corresponding position
field (e.g. `ref_index_position`) will be 0.

* `obj_position`: byte position for the first obj block.
* `obj_id_len`: number of bytes used to abbreviate object names in
obj blocks.
* `log_position`: byte position for the first log block.
* `ref_index_position`: byte position for the start of the ref index.
* `obj_index_position`: byte position for the start of the obj index.
* `log_index_position`: byte position for the start of the log index.

The size of the footer is 68 bytes for version 1, and 72 bytes for
version 2.

Reading the footer
++++++++++++++++++

Readers must first read the file start to determine the version
number. Then they seek to `file_length - FOOTER_LENGTH` to access the
footer. A trusted external source (such as `stat(2)`) is necessary to
obtain `file_length`. When reading the footer, readers must verify:

* 4-byte magic is correct
* 1-byte version number is recognized
* 4-byte CRC-32 matches the other 64 bytes (including magic, and
version)

Once verified, the other fields of the footer can be accessed.

Empty tables
++++++++++++

A reftable may be empty. In this case, the file starts with a header
and is immediately followed by a footer.

Binary search
^^^^^^^^^^^^^

Binary search within a block is supported by the `restart_offset` fields
at the end of the block. Readers can binary search through the restart
table to locate between which two restart points the sought reference or
key should appear.

Each record identified by a `restart_offset` stores the complete key in
the `suffix` field of the record, making the compare operation during
binary search straightforward.

Once a restart point lexicographically before the sought reference has
been identified, readers can linearly scan through the following record
entries to locate the sought record, terminating if the current record
sorts after (and therefore the sought key is not present).

Restart point selection
+++++++++++++++++++++++

Writers determine the restart points at file creation. The process is
arbitrary, but every 16 or 64 records is recommended. Every 16 may be
more suitable for smaller block sizes (4k or 8k), every 64 for larger
block sizes (64k).

More frequent restart points reduces prefix compression and increases
space consumed by the restart table, both of which increase file size.

Less frequent restart points makes prefix compression more effective,
decreasing overall file size, with increased penalties for readers
walking through more records after the binary search step.

A maximum of `65535` restart points per block is supported.

Considerations
~~~~~~~~~~~~~~

Lightweight refs dominate
^^^^^^^^^^^^^^^^^^^^^^^^^

The reftable format assumes the vast majority of references are single
object names valued with common prefixes, such as Gerrit Code Review's
`refs/changes/` namespace, GitHub's `refs/pulls/` namespace, or many
lightweight tags in the `refs/tags/` namespace.

Annotated tags storing the peeled object cost an additional object name per
reference.

Low overhead
^^^^^^^^^^^^

A reftable with very few references (e.g. git.git with 5 heads) is 269
bytes for reftable, vs. 332 bytes for packed-refs. This supports
reftable scaling down for transaction logs (below).

Block size
^^^^^^^^^^

For a Gerrit Code Review type repository with many change refs, larger
block sizes (64 KiB) and less frequent restart points (every 64) yield
better compression due to more references within the block compressing
against the prior reference.

Larger block sizes reduce the index size, as the reftable will require
fewer blocks to store the same number of references.

Minimal disk seeks
^^^^^^^^^^^^^^^^^^

Assuming the index block has been loaded into memory, binary searching
for any single reference requires exactly 1 disk seek to load the
containing block.

Scans and lookups dominate
^^^^^^^^^^^^^^^^^^^^^^^^^^

Scanning all references and lookup by name (or namespace such as
`refs/heads/`) are the most common activities performed on repositories.
Object names are stored directly with references to optimize this use case.

Logs are infrequently read
^^^^^^^^^^^^^^^^^^^^^^^^^^

Logs are infrequently accessed, but can be large. Deflating log blocks
saves disk space, with some increased penalty at read time.

Logs are stored in an isolated section from refs, reducing the burden on
reference readers that want to ignore logs. Further, historical logs can
be isolated into log-only files.

Logs are read backwards
^^^^^^^^^^^^^^^^^^^^^^^

Logs are frequently accessed backwards (most recent N records for master
to answer `master@{4}`), so log records are grouped by reference, and
sorted descending by update index.

Repository format
~~~~~~~~~~~~~~~~~

Version 1
^^^^^^^^^

A repository must set its `$GIT_DIR/config` to configure reftable:

....
[core]
    repositoryformatversion = 1
[extensions]
    refStorage = reftable
....

Layout
^^^^^^

A collection of reftable files are stored in the `$GIT_DIR/reftable/` directory.
Their names should have a random element, such that each filename is globally
unique; this helps avoid spurious failures on Windows, where open files cannot
be removed or overwritten. It suggested to use
`${min_update_index}-${max_update_index}-${random}.ref` as a naming convention.

Log-only files use the `.log` extension, while ref-only and mixed ref
and log files use `.ref`. extension.

The stack ordering file is `$GIT_DIR/reftable/tables.list` and lists the
current files, one per line, in order, from oldest (base) to newest
(most recent):

....
$ cat .git/reftable/tables.list
00000001-00000001-RANDOM1.log
00000002-00000002-RANDOM2.ref
00000003-00000003-RANDOM3.ref
....

Readers must read `$GIT_DIR/reftable/tables.list` to determine which
files are relevant right now, and search through the stack in reverse
order (last reftable is examined first).

Reftable files not listed in `tables.list` may be new (and about to be
added to the stack by the active writer), or ancient and ready to be
pruned.

Backward compatibility
^^^^^^^^^^^^^^^^^^^^^^

Older clients should continue to recognize the directory as a git
repository so they don't look for an enclosing repository in parent
directories. To this end, a reftable-enabled repository must contain the
following dummy files

* `.git/HEAD`, a regular file containing `ref: refs/heads/.invalid`.
* `.git/refs/`, a directory
* `.git/refs/heads`, a regular file

Readers
^^^^^^^

Readers can obtain a consistent snapshot of the reference space by
following:

1.  Open and read the `tables.list` file.
2.  Open each of the reftable files that it mentions.
3.  If any of the files is missing, goto 1.
4.  Read from the now-open files as long as necessary.

Update transactions
^^^^^^^^^^^^^^^^^^^

Although reftables are immutable, mutations are supported by writing a
new reftable and atomically appending it to the stack:

1.  Acquire `tables.list.lock`.
2.  Read `tables.list` to determine current reftables.
3.  Select `update_index` to be most recent file's
`max_update_index + 1`.
4.  Prepare temp reftable `tmp_XXXXXX`, including log entries.
5.  Rename `tmp_XXXXXX` to `${update_index}-${update_index}-${random}.ref`.
6.  Copy `tables.list` to `tables.list.lock`, appending file from (5).
7.  Rename `tables.list.lock` to `tables.list`.

During step 4 the new file's `min_update_index` and `max_update_index`
are both set to the `update_index` selected by step 3. All log records
for the transaction use the same `update_index` in their keys. This
enables later correlation of which references were updated by the same
transaction.

Because a single `tables.list.lock` file is used to manage locking, the
repository is single-threaded for writers. Writers may have to busy-spin
(with backoff) around creating `tables.list.lock`, for up to an
acceptable wait period, aborting if the repository is too busy to
mutate. Application servers wrapped around repositories (e.g. Gerrit
Code Review) can layer their own lock/wait queue to improve fairness to
writers.

Reference deletions
^^^^^^^^^^^^^^^^^^^

Deletion of any reference can be explicitly stored by setting the `type`
to `0x0` and omitting the `value` field of the `ref_record`. This serves
as a tombstone, overriding any assertions about the existence of the
reference from earlier files in the stack.

Compaction
^^^^^^^^^^

A partial stack of reftables can be compacted by merging references
using a straightforward merge join across reftables, selecting the most
recent value for output, and omitting deleted references that do not
appear in remaining, lower reftables.

A compacted reftable should set its `min_update_index` to the smallest
of the input files' `min_update_index`, and its `max_update_index`
likewise to the largest input `max_update_index`.

For sake of illustration, assume the stack currently consists of
reftable files (from oldest to newest): A, B, C, and D. The compactor is
going to compact B and C, leaving A and D alone.

1.  Obtain lock `tables.list.lock` and read the `tables.list` file.
2.  Obtain locks `B.lock` and `C.lock`. Ownership of these locks
prevents other processes from trying to compact these files.
3.  Release `tables.list.lock`.
4.  Compact `B` and `C` into a temp file
`${min_update_index}-${max_update_index}_XXXXXX`.
5.  Reacquire lock `tables.list.lock`.
6.  Verify that `B` and `C` are still in the stack, in that order. This
should always be the case, assuming that other processes are adhering to
the locking protocol.
7.  Rename `${min_update_index}-${max_update_index}_XXXXXX` to
`${min_update_index}-${max_update_index}-${random}.ref`.
8.  Write the new stack to `tables.list.lock`, replacing `B` and `C`
with the file from (4).
9.  Rename `tables.list.lock` to `tables.list`.
10. Delete `B` and `C`, perhaps after a short sleep to avoid forcing
readers to backtrack.

This strategy permits compactions to proceed independently of updates.

Each reftable (compacted or not) is uniquely identified by its name, so
open reftables can be cached by their name.

Windows
^^^^^^^

On windows, and other systems that do not allow deleting or renaming to open
files, compaction may succeed, but other readers may prevent obsolete tables
from being deleted.

On these platforms, the following strategy can be followed: on closing a
reftable stack, reload `tables.list`, and delete any tables no longer mentioned
in `tables.list`.

Irregular program exit may still leave about unused files. In this case, a
cleanup operation should proceed as follows:

* take a lock `tables.list.lock` to prevent concurrent modifications
* refresh the reftable stack, by reading `tables.list`
* for each `*.ref` file, remove it if
** it is not mentioned in `tables.list`, and
** its max update_index is not beyond the max update_index of the stack


Alternatives considered
~~~~~~~~~~~~~~~~~~~~~~~

bzip packed-refs
^^^^^^^^^^^^^^^^

`bzip2` can significantly shrink a large packed-refs file (e.g. 62 MiB
compresses to 23 MiB, 37%). However the bzip format does not support
random access to a single reference. Readers must inflate and discard
while performing a linear scan.

Breaking packed-refs into chunks (individually compressing each chunk)
would reduce the amount of data a reader must inflate, but still leaves
the problem of indexing chunks to support readers efficiently locating
the correct chunk.

Given the compression achieved by reftable's encoding, it does not seem
necessary to add the complexity of bzip/gzip/zlib.

Michael Haggerty's alternate format
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Michael Haggerty proposed
link:https://lore.kernel.org/git/CAMy9T_HCnyc1g8XWOOWhe7nN0aEFyyBskV2aOMb_fe%2BwGvEJ7A%40mail.gmail.com/[an
alternate] format to reftable on the Git mailing list. This format uses
smaller chunks, without the restart table, and avoids block alignment
with padding. Reflog entries immediately follow each ref, and are thus
interleaved between refs.

Performance testing indicates reftable is faster for lookups (51%
faster, 11.2 usec vs. 5.4 usec), although reftable produces a slightly
larger file (+ ~3.2%, 28.3M vs 29.2M):

[cols=">,>,>,>",options="header",]
|=====================================
|format |size |seek cold |seek hot
|mh-alt |28.3 M |23.4 usec |11.2 usec
|reftable |29.2 M |19.9 usec |5.4 usec
|=====================================

JGit Ketch RefTree
^^^^^^^^^^^^^^^^^^

https://dev.eclipse.org/mhonarc/lists/jgit-dev/msg03073.html[JGit Ketch]
proposed
link:https://lore.kernel.org/git/CAJo%3DhJvnAPNAdDcAAwAvU9C4RVeQdoS3Ev9WTguHx4fD0V_nOg%40mail.gmail.com/[RefTree],
an encoding of references inside Git tree objects stored as part of the
repository's object database.

The RefTree format adds additional load on the object database storage
layer (more loose objects, more objects in packs), and relies heavily on
the packer's delta compression to save space. Namespaces which are flat
(e.g. thousands of tags in refs/tags) initially create very large loose
objects, and so RefTree does not address the problem of copying many
references to modify a handful.

Flat namespaces are not efficiently searchable in RefTree, as tree
objects in canonical formatting cannot be binary searched. This fails
the need to handle a large number of references in a single namespace,
such as GitHub's `refs/pulls`, or a project with many tags.

LMDB
^^^^

David Turner proposed
https://lore.kernel.org/git/1455772670-21142-26-git-send-email-dturner@twopensource.com/[using
LMDB], as LMDB is lightweight (64k of runtime code) and GPL-compatible
license.

A downside of LMDB is its reliance on a single C implementation. This
makes embedding inside JGit (a popular reimplementation of Git)
difficult, and hoisting onto virtual storage (for JGit DFS) virtually
impossible.

A common format that can be supported by all major Git implementations
(git-core, JGit, libgit2) is strongly preferred.
