A rebase-ek és a cherry-pickek merge-ek egy sorozatával járnak, amelyek
eredményét új, egyszülős commitokként rögzítjük.  Ezeknek a merge-eknek
az első szülő oldala az „upstream" oldalt jelöli, és gyakran sokkal
nagyobb változtatáshalmazt tartalmaz, mint a második szülő oldala.
Hagyományosan az e merge-sorozat első-szülő oldalán lévő átnevezéseket
minden merge-nél újra és újra felismertük.  Ez a fájl elmagyarázza, hogy
miért biztonságos és hatékony a rebase-ek és cherry-pickek során
optimalizációként megjegyezni az átnevezéseket az előzmény upstream
oldalán, feltéve, hogy minden merge automatikus és tiszta (azaz nincsenek
konfliktusok, és nem szakad meg felhasználói bevitel vagy szerkesztés
miatt).

Vázlat:

  1. Feltételezések

  2. Hogyan működik a rebase-elés és a cherry-pickelés

  3. Miért *mindig* szuperhalmaza egy adott pick MERGE_SIDE1-en lévő
     átnevezéseinek a következő pick MERGE_SIDE1-en lévő átnevezései.

  4. Miért _majdnem_ mindig átnevezés a következő pick MERGE_SIDE1-én is
     egy adott pick MERGE_SIDE1-én lévő bármely átnevezés

  5. A #4-hez tartozó ellenpéldák részletes leírása.

  6. Miért teljesen ésszerű mégis a #5-beli speciális esetek használata
     fájlok párosítására a merge-gépezetben végzett háromutas tartalmi
     merge-hez, és miért nem befolyásolják a merge helyességét.

  7. Kölcsönhatás az „irreleváns" átnevezések kihagyásával

  8. További elemek, amelyeket gyorsítótárazni kell

  9. Hogyan lép kölcsönhatásba a könyvtár-átnevezés felismerése a
     fentiekkel, és miért biztonságos még mindig ez az optimalizáció akkor
     is, ha a merge.directoryRenames „true"-ra van állítva.


[[_1_assumptions]]
== 1. Feltételezések ==

Van két feltételezés, amely e dokumentumon végig érvényes lesz:

  * Az upstream oldalt, ahová a commitokat átültetjük, első szülő
    oldalként kezeljük, amikor a rebase/cherry-pick meghívja a
    merge-gépezetet

  * Minden merge teljesen automatikus

és egy harmadik, amely a 3–6. szakaszokban lesz érvényes az egyszerűség
kedvéért, és amelyet később a 9. szakaszban tárgyalok:

  * Nem történik könyvtárátnevezés


Hadd magyarázzam el bővebben mindegyik feltételezést, és hogy miért
veszem be:


Az első feltételezés pusztán azt a célt szolgálja, hogy e dokumentum
érthetőbb legyen; az optimalizáció implementációja valójában nem függ
tőle.  A feltételezés azonban minden esetben érvényes, mert azt tükrözi,
ahogyan a rebase-t és a cherry-picket is implementálták; és a cherry-pick
és a rebase implementációja visszafelé kompatibilitási okokból nem
változtatható meg könnyen (lásd például a `git checkout` dokumentációjában
a --ours és --theirs kapcsoló tárgyalását, különösen a megjegyzéseket
arról, hogyan viselkednek rebase-szel).  Az optimalizáció mindazonáltal
elkerüli az első-szülőség ellenőrzését.  Ehelyett azokat a feltételeket
ellenőrzi, amelyek az optimalizációt érvényessé teszik, így akkor is
tovább működne, ha valaki megváltoztatná a szülősorrendet, amelyet a
cherry-pick és a rebase használ.  De e feltételezés megtétele sokkal
érthetőbbé teszi ezt a dokumentumot, és megkímél attól, hogy minden
példát kétszer kelljen megismételnem.

Ha a második feltételezés sérül, akkor az optimalizáció egyszerűen ki van
kapcsolva, és így nem releváns megfontolni.  A második feltételezés úgy is
megfogalmazható, hogy „nincs megszakítás azért, hogy a felhasználó
konfliktusokat oldjon fel, vagy hogy csak tovább szerkesszen vagy
finomhangoljon fájlokat".  Bár a valódi rebase-eket és cherry-pickeket
gyakran megszakítják (akár azért, mert interaktív rebase-ről van szó, ahol
a felhasználó megállást és szerkesztést kért, akár azért, mert voltak
konfliktusok, amelyeket a felhasználónak fel kell oldania), az
átnevezések gyorsítótárát nem tároljuk lemezen, és így eldobjuk, amint a
rebase vagy cherry-pick megáll, hogy a felhasználó feloldja a műveletet.

A harmadik feltételezés egyszerűbbé teszi a 3–6. szakaszt, és lehetővé
teszi, hogy megértsük az alapjait annak, miért biztonságos és hatékony ez
az optimalizáció, és utána visszatérhetek a részletekre a 9. szakaszban.
Valószínűleg azt is érdemes megjegyezni, hogy ha könyvtárátnevezések
történnek, akkor az, hogy a merge.directoryRenames alapértelmezés szerint
„conflict"-ra van állítva, azt jelenti, hogy a művelet megáll, hogy a
felhasználók feloldják a konfliktusokat, és a gyorsítótárat eldobjuk, így
nem lesz optimalizáció, amit alkalmazni lehetne.  Tehát az egyetlen ok,
amiért a könyvtárátnevezésekkel kifejezetten foglalkoznunk kell, az, hogy
néhány felhasználó „true"-ra állítja a merge.directoryRenames-t, hogy a
merge-ek automatikusan tudjanak tovább haladni.  Az optimalizáció ezzel a
config-beállítással is biztonságos, de meg kell beszélnünk még néhány
esetet, hogy megmutassuk, miért; ezt a tárgyalást a 9. szakaszra
halasztjuk.


[[_2_how_rebasing_and_cherry_picking_work]]
== 2. Hogyan működik a rebase-elés és a cherry-pickelés ==

Vedd fontolóra a következő felállást (a git-rebase manpage-ből):

------------
		     A---B---C topic
		    /
	       D---E---F---G main
------------

Miután a topicot rebase-eltük vagy cherry-pickeltük a main tetejére, ez
így fog megjelenni:

------------
			     A'--B'--C' topic
			    /
	       D---E---F---G main
------------

Az A', B' és C' commitok merge-ek egy sorozatán keresztül jönnek létre,
ahol a rebase vagy a cherry-pick egymás után használja a három A-B-C
commit mindegyikét egy speciális merge-műveletben.  Címkézzük a
merge-művelet három commitját MERGE_BASE-ként, MERGE_SIDE1-ként és
MERGE_SIDE2-ként.  Ehhez a képhez a három merge mindegyikének a három
commitja a következő lenne:

....
To create A':
   MERGE_BASE:   E
   MERGE_SIDE1:  G
   MERGE_SIDE2:  A

To create B':
   MERGE_BASE:   A
   MERGE_SIDE1:  A'
   MERGE_SIDE2:  B

To create C':
   MERGE_BASE:   B
   MERGE_SIDE1:  B'
   MERGE_SIDE2:  C
....

Az embereket néha meglepi, hogy ezek a háromutas merge-ek megtörténnek.
E háromutas merge-ek megértésében hasznos lehet, ha kissé más
megvilágításban nézzük őket.  Például C' létrehozását nézheted így is:

  * Alkalmazd a B és C közötti változtatásokat B'-re
  * Alkalmazd a B és B' közötti változtatásokat C-re

Fogalmilag a fenti két állítás ugyanaz, mint B, B' és C háromutas
merge-e, legalábbis azok a részek, mielőtt eldöntenéd, hogy commitot
rögzítesz.


[[_3_why_the_renames_on_merge_side1_in_any_given_pick_are_always_a_superset_of_the_renames_on_merge_side1_for_the_next_pick]]
== 3. Miért mindig szuperhalmaza egy adott pick MERGE_SIDE1-en lévő átnevezéseinek a következő pick MERGE_SIDE1-en lévő átnevezései. ==

A merge-gépezet azokat a fájlneveket használja, amelyeket a MERGE_BASE-
ből, a MERGE_SIDE1-ből és a MERGE_SIDE2-ből kap.  Csak három feltétel
egyike mellett mozgat tartalmat másik fájlnévre:

  * Hogy egy konfliktus mindkét darabja elérhető legyen a felhasználó
    számára a konfliktusfeloldás során (példák: könyvtár/fájl konfliktus,
    add/add típusú konfliktus, mint symlink vs. reguláris fájl)

  * Amikor a MERGE_SIDE1 átnevezi a fájlt.

  * Amikor a MERGE_SIDE2 átnevezi a fájlt.

Először is emlékezzünk arra, mely commitok érintettek a cherry-pick vagy
rebase sorozat első és második pickjében:

....
To create A':
   MERGE_BASE:   E
   MERGE_SIDE1:  G
   MERGE_SIDE2:  A

To create B':
   MERGE_BASE:   A
   MERGE_SIDE1:  A'
   MERGE_SIDE2:  B
....

Tehát konkrétan azt kell megmutatnunk, hogy az E és G közötti átnevezések
szuperhalmaza az A és A' közöttieknek.

A'-t az első merge hozza létre.  A'-ben csak a fent felsorolt három ok
egyike miatt lesznek átnevezések.  Az első eset, egy konfliktus, olyan
helyzetet eredményez, ahol a gyorsítótárat eldobjuk, és így ez az
optimalizáció nem lép életbe, tehát ezt az esetet nem kell megfontolnunk.
A harmadik eset, egy MERGE_SIDE2-n lévő átnevezés (azaz G-ből A-ba),
megjelenik A'-ben, de megjelenik A-ban is – ezért A és A' diffelésekor az
az útvonal nem jelenik meg átnevezésként.  Az egyetlen fennmaradó mód
arra, hogy átnevezések jelenjenek meg A'-ben, az, hogy az átnevezés a
MERGE_SIDE1-ből jön.  Ezért az A és A' közötti minden átnevezés részhalmaza
az E és G közöttieknek.  Ezzel egyenértékűen, az E és G közötti minden
átnevezés szuperhalmaza az A és A' közöttieknek.


[[_4_why_any_rename_on_merge_side1_in_any_given_pick_is_almost_always_also_a_rename_on_merge_side1_for_the_next_pick]]
== 4. Miért _majdnem_ mindig átnevezés a következő pick MERGE_SIDE1-én is egy adott pick MERGE_SIDE1-én lévő bármely átnevezés. ==

Nézzük meg újra az első két picket:

....
To create A':
   MERGE_BASE:   E
   MERGE_SIDE1:  G
   MERGE_SIDE2:  A

To create B':
   MERGE_BASE:   A
   MERGE_SIDE1:  A'
   MERGE_SIDE2:  B
....

Most nézzük meg az első pick MERGE_SIDE1-éről származó bármely
átnevezést, azaz bármely E-ből G-be történő átnevezést.  Használjuk az
'oldfile' és 'newfile' fájlneveket demonstrációs célból.  Az az első pick
a következőképpen fog működni; amikor az átnevezést felismeri, a
merge-gépezet a következők háromutas tartalmi merge-ét végzi el:

....
    E:oldfile
    G:newfile
    A:oldfile
....

és új eredményt állít elő:

....
    A':newfile
....

Fentebb vedd figyelembe, hogy feltételeztem, hogy E->A nem nevezte át az
oldfile-t.  Ha az az oldal átnevezett, akkor nagy valószínűséggel van egy
rename/rename(1to2) konfliktusunk, amely miatt a rebase vagy cherry-pick
művelet megáll, és eldobja az átnevezések memóriabeli gyorsítótárát, így
nem kell tovább foglalkozni vele.  Abban a speciális esetben, amikor E->A
átnevezi a fájlt, de szintén newfile-ra nevezi át, akkor az átnevezésből
nincs konfliktus, és a merge sikeres lehet.  Ebben a speciális esetben az
átnevezést nem érvényes gyorsítótárazni, mert a második merge megtalálja
az A:newfile-t a MERGE_BASE-ben (lásd még a t6429 új teszteseteit,
amelyek leírásában szerepel a „rename same file identically").  Tehát egy
rename/rename(1to1)-et speciálisan kell kezelni azzal, hogy kimetsszük az
átnevezéseket a gyorsítótárból, és csökkentjük a dir_rename_counts-ot az
ezekhez az átnevezésekhez tartozó aktuális és vezető könyvtárakban.  Vagy
mivel ezek nagyon ritkák, választhatnánk a könnyebb utat is, és
kikapcsolhatnánk az átnevezések megjegyzésének optimalizációját, amikor
egy rename/rename(1to1) történik.

Az előző bekezdés az E->A oldfile-átnevezésének eseteit kezelte,
folytassuk azzal a feltételezéssel, hogy az oldfile nincs átnevezve
A-ban.

A B' létrehozásának diagramja szerint a MERGE_SIDE1 az A-ból A'-be tartó
változtatásokkal jár.  Tehát kíváncsiak vagyunk arra, hogy az A:oldfile
és az A':newfile átnevezésként lesz-e kezelve.  Vedd figyelembe, hogy:

  * Nem lesz A':oldfile (mert nem lehetett G:oldfile, hiszen a
    merge-gépezetben nem végzünk törésfelismerést, a G:newfile-t pedig
    átnevezésként ismertük fel, és a fenti, tisztán merge-elődő átnevezés
    felépítése folytán a merge-gépezet gondoskodik arról, hogy ne legyen
    'oldfile' az eredményben).

  * Nem lesz A:newfile (ha lett volna, rename/add konfliktusunk lett
    volna).

  * Az A:oldfile és az A':newfile egyértelműen „rokon" (az A':newfile egy
    tiszta, A:oldfile-t bevonó háromutas tartalmi merge-ből származott).

A fenti harmadik pontot ki is fejthetjük, ha megjegyezzük, hogy a
háromutas tartalmi merge-ek úgy is felfoghatók, mint az alap és az egyik
oldal közötti különbségek alkalmazása a másik oldalra.  Így az A':newfile-t
felfoghatjuk úgy, mint amelyet az E:oldfile és a G:newfile közötti
változtatásoknak (amelyekről kiderült, hogy rokonok, azaz <50%-ban
változtak) az A:oldfile-ra való alkalmazásával hoztunk létre.

Így az A:oldfile és az A':newfile éppúgy rokon, mint az E:oldfile és a
G:newfile – pontosan azonos különbségeik vannak.  Mivel az utóbbiakat
átnevezésként ismertük fel, az A:oldfile-nak és az A':newfile-nak is
majdnem mindig felismerhetőnek kell lennie átnevezésként.


[[_5_a_detailed_description_of_the_counter_examples_to_4]]
== 5. A #4-hez tartozó ellenpéldák részletes leírása. ==

A 4. szakaszban már megjegyeztük, hogy a rename/rename(1to1) (azaz amikor
mindkét oldal ugyanúgy nevez át egy fájlt) egy ellenpélda volt.  Az
érdekesebb rész azonban az, hogy miért kellett a „majdnem" pontosítást
használnunk, amikor kijelentettük, hogy az A:oldfile és az A':newfile
„majdnem" mindig felismerhető átnevezésként?

Ismételjük meg egy korábbi pontot, amelyet a 4. szakasz tett:

....
  A':newfile was created by applying the changes between E:oldfile and
  G:newfile to A:oldfile.  The changes between E:oldfile and G:newfile were
  <50% of the size of E:oldfile.
....

Ha azok a változtatások, amelyek az E:oldfile méretének <50%-át tették
ki, egyben az A:oldfile méretének is <50%-át teszik ki, akkor az
A:oldfile és az A':newfile felismerhető lesz átnevezésként.  Ha azonban
drámai méretcsökkenés van az E:oldfile és az A:oldfile között (de az
E:oldfile, a G:newfile és az A:oldfile közötti változtatások valahogy
mégis tisztán merge-elődnek), akkor a hagyományos átnevezés-felismerés
nem ismerné fel az A:oldfile-t és az A':newfile-t átnevezésként.

Íme egy példa, ahol ez megtörténhet:

  * Az E:oldfile 20 sorból állt
  * A G:newfile 10 új sort adott a fájl elejére
  * Az A:oldfile megtartotta a fájl első 3 sorát, a többit pedig törölte

akkor

....
  => A':newfile would have 13 lines, 3 of which matches those in A:oldfile.
  E:oldfile -> G:newfile would be detected as a rename, but A:oldfile and
  A':newfile would not be.
....


[[_6_why_the_special_cases_in_5_are_still_fully_reasonable_to_use_to_pair_up_files_for_three_way_content_merging_in_the_merge_machinery_and_why_they_do_not_affect_the_correctness_of_the_merge]]
== 6. Miért teljesen ésszerű mégis a #5-beli speciális esetek használata fájlok párosítására a merge-gépezetben végzett háromutas tartalmi merge-hez, és miért nem befolyásolják a merge helyességét. ==

A rename/rename(1to1) esetben az A:newfile és az A':newfile nem
átnevezések, mivel *ugyanazt* a fájlnevet használják.  Az azonos
fájlnevű fájlokat azonban nyilvánvalóan rendben van párosítani háromutas
tartalmi merge-hez (a merge-gépezet soha nem alkalmazott
törésfelismerést).  Az érdekes ellenpéldás eset tehát nem a
rename/rename(1to1) eset, hanem az az eset, amikor A nem nevezte át az
oldfile-t.  Ez volt az az eset, amelynek a megbeszélésével a legtöbb időt
töltöttük a 4. és 5. szakaszban.  E szakasz hátralevő része is ennek az
esetnek lesz szentelve.

Tehát még ha az A:oldfile és az A':newfile nem is felismerhető
átnevezésként, miért ésszerű mégis párosítani őket háromutas tartalmi
merge-hez a merge-gépezetben?  Több oka is van:

  * Ahogy a 4. és 5. szakaszban megjegyeztük, az A:oldfile és az
    A':newfile közötti diff *pontosan* ugyanaz, mint az E:oldfile és a
    G:newfile közötti diff.  Az utóbbi párt átnevezésként ismertük fel,
    ezért nem valószínű, hogy meglepné a felhasználókat, ha az A:oldfile-t
    és az A':newfile-t átnevezésként kezeljük.

  * Valójában az „oldfile"-t és a „newfile"-t egy ponton átnevezésként
    ismertük fel amiatt, ahogyan az E..G láncban felépítették őket.  És
    ezt az információt egyszer már felhasználtuk ebben a
    rebase-ben/cherry-pickben.  Szerintem nem valószínű, hogy a
    felhasználókat meglepné, ha továbbra is átnevezésként kezeljük a
    fájlokat, és gyorsan megértenék, miért tettük ezt.

  * A fájlok átnevezésként való megjelölése vagy deklarálása *nem* a
    merge-ek végcélja.  A merge-ek az átnevezéseket arra használják, hogy
    eldöntsék, mely fájlokat van értelme párosítani háromutas tartalmi
    merge-hez.

  * Az A:oldfile és az A':newfile _már_ párosítva volt egy háromutas
    tartalmi merge-ben; így jött létre az A':newfile.  Valójában az a
    háromutas tartalmi merge tiszta volt.  Tehát nagyon ésszerűnek tűnik
    újra felhasználni őket egy későbbi háromutas tartalmi merge-ben.

A fentiek azonban a gyakori forgatókönyvekre összpontosítanak.
Próbáljuk meg megnézni az összes lehetséges szokatlan forgatókönyvet, és
hasonlítsuk össze az optimalizáció nélküli esetet az optimalizációssal.
Vedd fontolóra a következő elméleti eseteket; ezután belemerülünk
mindegyikbe, hogy meghatározzuk, melyikük lehetséges, és ha igen, mit
jelentenek:

  1. Optimalizáció nélkül a második merge konfliktust eredményez.
     Az optimalizációval a második merge szintén konfliktust eredményez.
     Kérdések: Zavaróan különböznek a konfliktusok?  Az egyik esetben jobb?

  2. Optimalizáció nélkül a második merge NEM eredményez konfliktust.
     Az optimalizációval a második merge szintén NEM eredményez konfliktust.
     Kérdések: Azonosak a merge-ek?

  3. Optimalizáció nélkül a második merge konfliktust eredményez.
     Az optimalizációval a második merge NEM eredményez konfliktust.
     Kérdések: Lehetséges?  Bug, bugjavítás vagy valami más?

  4. Optimalizáció nélkül a második merge NEM eredményez konfliktust.
     Az optimalizációval a második merge konfliktust eredményez.
     Kérdések: Lehetséges?  Bug, bugjavítás vagy valami más?

Mind a négy esetet megvizsgálom, de nem sorrendben.

A negyedik eset lehetetlen.  Ahhoz, hogy az átnevezés-megjegyző
optimalizáció nélküli kód ne kapjon konfliktust, a B:oldfile-nak pontosan
egyeznie kellene az A:oldfile-lal – ha nem egyezik, módosítás/törlés
konfliktus lenne.  Ha az A:oldfile pontosan egyezik a B:oldfile-lal,
akkor az A:oldfile, az A':newfile és a B:oldfile közötti háromutas
tartalmi merge-ben nem lenne konfliktus, és egyszerűen az A'-ből
származó newfile verzióját adná eredményül.

A fenti bekezdéssel azonos logika alapján a második eset valóban azonos
merge-eket eredményezne.  Amikor az A:oldfile pontosan egyezik a
B:oldfile-lal, egy fel nem ismert átnevezés azt mondaná: „Ó, látom, hogy
az egyik oldal nem módosította az 'oldfile'-t, a másik oldal pedig
törölte.  Törölni fogom.  És látom, hogy van ez a vadonatúj, 'newfile'
nevű fájlod A'-ben, szóval megtartom."  Ez ugyanazt az eredményt adja,
mint az A:oldfile, az A':newfile és a B:oldfile háromutas tartalmi
merge-e – az oldfile eltávolítása úgy, hogy az A'-ből származó newfile
verziója jelenik meg az eredményben.

A harmadik eset érdekes.  Azt jelenti, hogy az A:oldfile és az A':newfile
nemcsak elég hasonló volt, hanem a köztük lévő változtatások nem
ütköztek az A:oldfile és a B:oldfile közötti változtatásokkal.  Ez
igazolná a megérzésünket, hogy a fájlok elég hasonlóak voltak ahhoz,
hogy háromutas tartalmi merge-ben használjuk őket, és így teljesen
helyesnek tűnik, hogy úgy használtuk őket.  (Széljegyzet: egy konkrét
példa itt megvilágító erejű lehet.  Tegyük fel, hogy B az A közvetlen
revertje volt.  B egyértelműen A tiszta revertje lett volna, mivel A volt
B közvetlen szülője.  Az ember azt feltételezné, hogy ha ki tudsz pickelni
egy commitot, akkor a közvetlen revertjét is ki tudod cherry-pickelni.
Ez azonban egyike azoknak a fura sarokeseteknek; ezen optimalizáció
nélkül épp sikeresen, tisztán kipickeltünk egy commitot, de nem tudjuk
cherry-pickelni a közvetlen revertjét az E:oldfile és az A:oldfile
közötti méretkülönbségek miatt.)

Így csak az első esetet kell megfontolni – amikor mind az optimalizációval,
mind anélkül konfliktust kapunk.  Optimalizáció nélkül módosítás/törlés
konfliktusunk lesz, ahol mind az A':newfile, mind a B:oldfile a tree-ben
marad, hogy a felhasználó kezelje, és nincs utalás a kettő közötti
lehetséges hasonlóságra.  Az optimalizációval egy háromutasan
tartalmilag merge-elt A:oldfile-unk, A':newfile-unk és B:oldfile-unk
lesz, konfliktusjelölőkkel, amelyek arra utalnak, hogy úgy gondoltuk, a
fájlok rokonok, de a felhasználónak megadják a lehetőséget a
feloldásra.  Ahogy fentebb megjegyeztük, nem hiszem, hogy a felhasználók
meglepőnek találnák, hogy az 'oldfile'-t és a 'newfile'-t rokonként
kezeljük, hiszen E és G között voltak.  Mindenesetre ez az eset nem lehet
aggasztó, mivel mindkét esetben konfliktusba ütköztünk, elmondtuk a
felhasználónak, amit tudunk, és megkértük, hogy oldja fel.

Tehát összefoglalva, a 4. eset lehetetlen, a 2. eset ugyanazt a
viselkedést eredményezi, az 1. és a 3. eset pedig úgy tűnik, hogy az
optimalizációval ugyanolyan jó vagy jobb viselkedést nyújt, mint
nélküle.


[[_7_interaction_with_skipping_of_irrelevant_renames]]
== 7. Kölcsönhatás az „irreleváns" átnevezések kihagyásával ==

Korábbi optimalizációk közé tartozott az átnevezés-felismerés kihagyása
az „irrelevánsnak" tekintett útvonalaknál.  Lásd például a következő
commitokat:

  * 32a56dfb99 ("merge-ort: precompute subset of sources for which we
		need rename detection", 2021-03-11)
  * 2fd9eda462 ("merge-ort: precompute whether directory rename
		detection is needed", 2021-03-11)
  * 9bd342137e ("diffcore-rename: determine which relevant_sources are
		no longer relevant", 2021-03-13)

A relevanciát mindig az határozza meg, hogy az előzmény _másik_ oldala
mit tett, olyan értelemben, hogy módosított-e egy fájlt, amelyet a mi
oldalunk átnevezett, vagy hozzáadott-e egy fájlt egy olyan könyvtárhoz,
amelyet a mi oldalunk átnevezett.  Ez azt jelenti, hogy egy útvonal,
amely „irreleváns" egy rebase vagy cherry-pick sorozat első commitjának
pickelésekor, hirtelen „relevánssá" válhat a következő commit
pickelésekor.

Ennek a következménye az, hogy csak a releváns útvonalakra tudjuk
gyorsítótárazni az átnevezés-felismerés eredményeit, és az azt követő
commitoknál újra kell ellenőriznünk a relevanciát.  Ha azoknak a
későbbi commitoknak vannak további útvonalai, amelyek relevánsak az
átnevezés-felismerés szempontjából, akkor újra kell végeznünk az
átnevezés-felismerést – bár korlátozhatjuk azokra az útvonalakra,
amelyeknél még nem ismertünk fel átnevezéseket.


[[_8_additional_items_that_need_to_be_cached]]
== 8. További elemek, amelyeket gyorsítótárazni kell ==

Kiderül, hogy nem csak az átnevezéseket kell gyorsítótáraznunk; ezeket is
gyorsítótárazzuk:

....
  A) non-renames (i.e. unpaired deletes)
  B) counts of renames within directories
  C) sources that were marked as RELEVANT_LOCATION, but which were
     downgraded to RELEVANT_NO_MORE
  D) the toplevel trees involved in the merge
....

Ezeket mind a struct rename_info tárolja, és rendre itt jelennek meg:

  * cached_pairs (a tényleges átnevezések mellett, csak NULL értékkel)
  * dir_rename_counts
  * cached_irrelevant
  * merge_trees

Az `(A)` oka a 7. szakaszban tárgyalt, irreleváns átnevezéseket kihagyó
optimalizációból ered.  Az, hogy az irreleváns átnevezéseket kihagyjuk,
azt jelenti, hogy csak a potenciális átnevezések egy részhalmazát
ismerjük fel, és a későbbi commitoknak szükségük lehet arra, hogy az
upstream oldalon átnevezés-felismerést futtassanak a fennmaradó
átnevezések egy részhalmazán (hogy megkapják az adott későbbi commit
szempontjából releváns átnevezéseket).  Mivel a párosítatlan törlések is
részt vesznek az átnevezés-felismerésben, nem akarjuk minden átültetett
commitnál újra és újra ellenőrizni, hogy azok az útvonalak párosítatlanok
maradnak-e az upstream oldalon.

A `(B)` oka az, hogy a diffcore_rename_extended() az, ami legenerálja az
átnevezések könyvtáronkénti számát, amelyre a könyvtár-átnevezés
felismeréséhez szükség van, és ha nem futtatjuk újra a
diffcore_rename_extended()-et, akkor rendelkeznünk kell a kimenetével,
beleértve a dir_rename_counts-ot, az előző futásból.

A `(C)` oka az, hogy a merge-ort tree-bejárása újra relevánsnak fogja
gondolni azokat az útvonalakat (RELEVANT_LOCATION-ként megjelölve őket),
de az, hogy RELEVANT_NO_MORE-ra fokoztuk le őket, azt jelenti, hogy a
dir_rename_counts már tartalmazza a könyvtár-átnevezés felismeréséhez
szükséges információt.  (Egy útvonal, amely egy későbbi commitban
RELEVANT_CONTENT-té válik, eltávolításra kerül a cached_irrelevantból.)

A `(D)` oka az, hogy így határozzuk meg, használható-e az
átnevezés-megjegyző optimalizáció.  Konkrétan, emlékezve arra, hogy a
merge-eink sorozata így néz ki:

....
   Merge 1:
   MERGE_BASE:   E
   MERGE_SIDE1:  G
   MERGE_SIDE2:  A
   => Creates    A'

   Merge 2:
   MERGE_BASE:   A
   MERGE_SIDE1:  A'
   MERGE_SIDE2:  B
   => Creates    B'
....

Az teszi lehetővé ezt az optimalizációt, hogy az A és az A' tree
egyaránt megjelenik az 1. merge-ben és a 2. merge-ben, ahol A az A'
szülője.  Ezért eltároljuk a tree-ket, hogy összehasonlítsuk azzal, amit
legközelebb merge-elni kérnek tőlünk.


[[_9_how_directory_rename_detection_interacts_with_the_above_and_why_this_optimization_is_still_safe_even_if_merge_directoryrenames_is_set_to_true]]
== 9. Hogyan lép kölcsönhatásba a könyvtár-átnevezés felismerése a fentiekkel, és miért biztonságos még mindig ez az optimalizáció akkor is, ha a merge.directoryRenames „true"-ra van állítva. ==

Ahogy a feltételezések szakaszban megjegyeztük:

....
    """
    ...if directory renames do occur, then the default of
    merge.directoryRenames being set to "conflict" means that the operation
    will stop for users to resolve the conflicts and the cache will be
    thrown away, and thus that there won't be an optimization to apply.
    So, the only reason we need to address directory renames specifically,
    is that some users will have set merge.directoryRenames to "true" to
    allow the merges to continue to proceed automatically.
    """
....

Emlékezzünk arra, hogy meg kell néznünk, hogyan hat egy adott pick a
következőre.  Használjuk tehát újra az első két picket az egyes szakasz
diagramjából:

....
  First pick does this three-way merge:
    MERGE_BASE:   E
    MERGE_SIDE1:  G
    MERGE_SIDE2:  A
    => creates A'

  Second pick does this three-way merge:
    MERGE_BASE:   A
    MERGE_SIDE1:  A'
    MERGE_SIDE2:  B
    => creates B'
....

A könyvtár-átnevezés felismerése azért létezik, hogy ha az előzmény
egyik oldala átnevez egy könyvtárat, a másik oldal pedig hozzáad egy új
fájlt a régi könyvtárhoz, akkor a merge (merge.directoryRenames=true
mellett) át tudja mozgatni a fájlt az új könyvtárba.  Kétféle,
minőségileg különböző módon lehet új fájlt hozzáadni egy régi
könyvtárhoz: új fájlt létrehozni, vagy egy fájlt átnevezni abba a
könyvtárba.  Ráadásul a könyvtárátnevezések az előzmény bármelyik
oldalán történhetnek, tehát négy esetet kell megfontolni:

  * MERGE_SIDE1 átnevezi a régi könyvtárat, MERGE_SIDE2 új fájlt ad a régi könyvtárhoz
  * MERGE_SIDE1 átnevezi a régi könyvtárat, MERGE_SIDE2 egy fájlt nevez át a régi könyvtárba
  * MERGE_SIDE1 új fájlt ad a régi könyvtárhoz, MERGE_SIDE2 átnevezi a régi könyvtárat
  * MERGE_SIDE1 egy fájlt nevez át a régi könyvtárba, MERGE_SIDE2 átnevezi a régi könyvtárat

Egy utolsó megjegyzés, mielőtt megvizsgálnánk ezt a négy esetet: van
néhány fontos tulajdonsága annak, hogyan valósítjuk meg ezt az
optimalizációt a könyvtár-átnevezés felismerésével kapcsolatban,
amelyeket szem előtt kell tartanunk, miközben ezeket az eseteket
vizsgáljuk:

  * az átnevezés-gyorsítótárazás a könyvtárátnevezések alkalmazása *után*
    történik

  * a könyvtár-átnevezés felismerése által létrehozott átnevezést az
    előzmény azon oldalára rögzítjük, amely a könyvtárátnevezést végezte.

  * a dir_rename_counts, a
	{oldname => {newname => count}}
    beágyazott map, szintén gyorsítótárazódik a futások között.  Ez
    lényegében azt jelenti, hogy a könyvtár-átnevezés felismerése is
    gyorsítótárazódik, bár csak az előzmény azon oldalán, amelyre az
    átnevezéseket gyorsítótárazzuk (MERGE_SIDE1, ami e dokumentumot
    illeti; lásd a feltételezések szakaszt).  Két érdekes almegjegyzés
    ezekről a számokról:

   ** Ha újra el kell végeznünk az átnevezés-felismerést az adott oldalon
      (pl. néhány útvonal releváns az átnevezés-felismerés szempontjából,
      amely korábban nem volt az), akkor kitöröljük a dir_rename_counts-ot,
      és újraszámoljuk, a cached_pairs felhasználásával.  Ennek azért
      fontos megtenni, mert a RELEVANT_LOCATION körüli optimalizációk
      azért léteznek, hogy megakadályozzák, hogy szükségtelen
      átnevezéseket számoljunk a könyvtár-átnevezés felismeréséhez, és
      hogy dir_rename_counts-ot számoljunk irreleváns könyvtárakhoz; de
      ugyanazok az átnevezések vagy könyvtárak szükségessé válhatnak a
      későbbi merge-ekhez.  A legegyszerűbb módja a dir_rename_counts
      „rendbe tételének" ilyen esetekben az, hogy egyszerűen újraszámoljuk.

   ** Ha kimetsszük a rename/rename(1to1) bejegyzéseket a gyorsítótárból,
      akkor frissítenünk kell a dir_rename_counts-ot is, hogy csökkentsük
      a számokat az érintett könyvtárnál és bármely releváns szülő
      könyvtárnál (hogy visszavonjuk azt, amit a diffcore-rename.c-beli
      update_dir_rename_counts() növelt, amikor az átnevezést először
      megtaláltuk).  Ha ehelyett egyszerűen kikapcsoljuk az
      átnevezés-megjegyző optimalizációt, amikor az igen ritka
      rename/rename(1to1) esetek előfordulnak, akkor a dir_rename_counts
      újraszámolódik, amikor legközelebb átnevezés-felismerés történik,
      ahogy fentebb megjegyeztük.

  * az az oldal, amelynek több commitját kell pickelni, az az oldala az
    előzménynek, amelyre NEM gyorsítótárazzuk az átnevezéseket.  Így
    nincsenek további commitok, amelyek megváltoztatnák egy könyvtárban
    az átnevezések számát, kivéve azokat, amelyeket a könyvtár-átnevezés
    felismerése végez (amelyek mindig a többséghez adnak).

  * az általunk gyorsítótárazott „átnevezéseket" bármely
    könyvtárátnevezés kissé módosítja, ahogy alább megjegyezzük.

Most, hogy ezeken a megjegyzéseken túl vagyunk, menjünk végig a négy
eseten sorban:

1. eset: MERGE_SIDE1 átnevezi a régi könyvtárat, MERGE_SIDE2 új fájlt ad a régi könyvtárhoz

....
  This case looks like this:

    MERGE_BASE:   E,   Has olddir/
    MERGE_SIDE1:  G,   Renames olddir/ -> newdir/
    MERGE_SIDE2:  A,   Adds olddir/newfile
    => creates    A',  With newdir/newfile

    MERGE_BASE:   A,   Has olddir/newfile
    MERGE_SIDE1:  A',  Has newdir/newfile
    MERGE_SIDE2:  B,   Modifies olddir/newfile
    => expected   B',  with threeway-merged newdir/newfile from above

  In this case, with the optimization, note that after the first commit:
    * MERGE_SIDE1 remembers olddir/ -> newdir/
    * MERGE_SIDE1 has cached olddir/newfile -> newdir/newfile
  Given the cached rename noted above, the second merge can proceed as
  expected without needing to perform rename detection from A -> A'.
....

2. eset: MERGE_SIDE1 átnevezi a régi könyvtárat, MERGE_SIDE2 egy fájlt nevez át a régi könyvtárba

....
  This case looks like this:

    MERGE_BASE:   E    oldfile, olddir/
    MERGE_SIDE1:  G    oldfile, olddir/ -> newdir/
    MERGE_SIDE2:  A    oldfile -> olddir/newfile
    => creates    A',  With newdir/newfile representing original oldfile

    MERGE_BASE:   A    olddir/newfile
    MERGE_SIDE1:  A'   newdir/newfile
    MERGE_SIDE2:  B    modify olddir/newfile
    => expected   B',  with threeway-merged newdir/newfile from above

  In this case, with the optimization, note that after the first commit:
    * MERGE_SIDE1 remembers olddir/ -> newdir/
    * MERGE_SIDE1 has cached olddir/newfile -> newdir/newfile
		  (NOT oldfile -> newdir/newfile; compare to case with
		   (p->status == 'R' && new_path) in possibly_cache_new_pair())

  Given the cached rename noted above, the second merge can proceed as
  expected without needing to perform rename detection from A -> A'.
....

3. eset: MERGE_SIDE1 új fájlt ad a régi könyvtárhoz, MERGE_SIDE2 átnevezi a régi könyvtárat

....
  This case looks like this:

    MERGE_BASE:   E,   Has olddir/
    MERGE_SIDE1:  G,   Adds olddir/newfile
    MERGE_SIDE2:  A,   Renames olddir/ -> newdir/
    => creates    A',  With newdir/newfile

    MERGE_BASE:   A,   Has newdir/, but no notion of newdir/newfile
    MERGE_SIDE1:  A',  Has newdir/newfile
    MERGE_SIDE2:  B,   Has newdir/, but no notion of newdir/newfile
    => expected   B',  with newdir/newfile from A'

  In this case, with the optimization, note that after the first commit there
  were no renames on MERGE_SIDE1, and any renames on MERGE_SIDE2 are tossed.
  But the second merge didn't need any renames so this is fine.
....

4. eset: MERGE_SIDE1 egy fájlt nevez át a régi könyvtárba, MERGE_SIDE2 átnevezi a régi könyvtárat

....
  This case looks like this:

    MERGE_BASE:   E,   Has olddir/
    MERGE_SIDE1:  G,   Renames oldfile -> olddir/newfile
    MERGE_SIDE2:  A,   Renames olddir/ -> newdir/
    => creates    A',  With newdir/newfile representing original oldfile

    MERGE_BASE:   A,   Has oldfile
    MERGE_SIDE1:  A',  Has newdir/newfile
    MERGE_SIDE2:  B,   Modifies oldfile
    => expected   B',  with threeway-merged newdir/newfile from above

  In this case, with the optimization, note that after the first commit:
    * MERGE_SIDE1 remembers oldfile -> newdir/newfile
		  (NOT oldfile -> olddir/newfile; compare to case of second
		   block under p->status == 'R' in possibly_cache_new_pair())
    * MERGE_SIDE2 renames are tossed because only MERGE_SIDE1 is remembered

  Given the cached rename noted above, the second merge can proceed as
  expected without needing to perform rename detection from A -> A'.
....

Végezetül itt csak megjegyzem, hogy az irreleváns átnevezéseket kihagyó
optimalizációval való kölcsönhatás azt jelenti, hogy néha nem ismerünk
fel átnevezést egyetlen fájlnál sem egy átnevezett könyvtáron belül,
amely esetben magára a könyvtárra sem tudtunk átnevezést felismerni.
Ilyen esetben nem tudjuk, hogy a könyvtárat átnevezték-e; óvatosak
akarunk lenni, hogy elkerüljük valamiféle „ezt a könyvtárat nem nevezték
át" kijelentés gyorsítótárazását.  Ha megtennénk, akkor egy későbbi,
rebase-elt commit hozzáadhatna egy fájlt a régi könyvtárhoz, és a
felhasználó azt várná, hogy az a helyes könyvtárba kerüljön – amit a
téves „ezt a könyvtárat nem nevezték át" gyorsítótárunk megakadályozna.
