[[_rerere]]
Rerere
======

Ez a dokumentum a rerere logikáját írja le.

[[_conflict_normalization]]
Konfliktus-normalizálás
-----------------------

Annak biztosítására, hogy a rögzített konfliktusfeloldások
visszakereshetők legyenek a rerere adatbázisban akkor is, ha a
brancheket eltérő sorrendben merge-elik, ha különböző branchek merge-e
ugyanazt a konfliktust eredményezi, vagy ha eltérő konfliktusstílus-
beállításokat használnak, a rerere normalizálja a konfliktusokat,
mielőtt a rerere adatbázisba írná őket.

A különböző konfliktusstílusokat és branchneveket úgy normalizáljuk,
hogy leszedjük a címkéket a konfliktusjelölőkről, és eltávolítjuk a
közös ős verzióját a `diff3` vagy `zdiff3` konfliktusstílusokból.  Az
eltérő sorrendben merge-elt brancheket a konfliktus-hunkok rendezésével
normalizáljuk.  Az egyes lépésekről bővebben a következő szakaszokban.

Miután ezt a két normalizálási műveletet elvégeztük, a normalizált
konfliktus alapján kiszámításra kerül egy konfliktus-azonosító, amelyet
a rerere később a konfliktus rerere adatbázisban való kikeresésére
használ.

[[_removing_the_common_ancestor_version]]
A közös ős verziójának eltávolítása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Tegyük fel, hogy van három branchünk: AB, AC és AC2.  E branchek közös
őse tartalmaz egy fájlt, amelyben van egy sor az „A" sztringgel (a
rövidség kedvéért ezt a dokumentum további részében „A sor"-nak
nevezzük).  Az AB branchben ezt a sort „B"-re változtatjuk, az AC-ben
„C"-re, az AC2 branch pedig az AC-ből ágazik le, miután a sort „C"-re
változtattuk.

Ha az AB branchből leágaztatunk egy ABAC branchet, majd bemerge-eljük
az AC-t, a következőhöz hasonló konfliktust kapunk:

    <<<<<<< HEAD
    B
    =======
    C
    >>>>>>> AC

Ha ugyanezt megtesszük az AC2-vel (leágaztatunk egy ABAC2 branchet az
AB branchből, majd bemerge-eljük az AC2 branchet), a diff3 vagy zdiff3
konfliktusstílust használva, a következőhöz hasonló konfliktust kapunk:

    <<<<<<< HEAD
    B
    ||||||| merged common ancestors
    A
    =======
    C
    >>>>>>> AC2

Azzal, hogy ezt a konfliktust úgy oldja fel, hogy a D sort hagyja meg,
a felhasználó a következőt jelenti ki:

    After examining what branches AB and AC did, I believe that making
    line A into line D is the best thing to do that is compatible with
    what AB and AC wanted to do.

Mivel az AC2 branch ugyanarra a commitra hivatkozik, mint az AC, a
fentiek azt jelentik, hogy ez azzal is kompatibilis, amit az AB és az
AC2 tenni akart.

Kiterjesztve ez azt jelenti, hogy a rerere-nek fel kell ismernie, hogy
a fenti konfliktusok azonosak.  Ehhez a konfliktusjelölőkről leszedjük
a címkéket, és eltávolítjuk a közös ős verzióját.  A fenti példák
mindegyike a következő normalizált konfliktust eredményezné:

    <<<<<<<
    B
    =======
    C
    >>>>>>>

[[_sorting_hunks]]
A hunkok rendezése
~~~~~~~~~~~~~~~~~~

Ahogy korábban, képzeljük el, hogy egy közös ős tartalmazott egy fájlt,
amelyben az elején az A sor, a végén pedig az X sor volt.  Aztán négy
branchet ágaztatunk le, amelyek ezeket teszik:

    - AB: changes A to B
    - AC: changes A to C
    - XY: changes X to Y
    - XZ: changes X to Z

Namármost, ha az AB branchből leágaztatunk egy ABAC branchet, majd
bemerge-eljük az AC-t, illetve ha az AC branchből leágaztatunk egy ACAB
branchet, majd bemerge-eljük az AB-t, a konfliktust eltérő sorrendben
kapnánk.  Az előbbi azt mondaná: „A-ból B vagy C lett, most mi
legyen?", míg az utóbbi azt mondaná: „A-ból C vagy B lett, most mi
legyen?"

Emlékeztetőül: az, hogy az AC-t bemerge-eljük az ABAC-ba, és a
konfliktust úgy oldjuk fel, hogy a D sort hagyjuk meg, azt jelenti,
hogy a felhasználó a következőt jelenti ki:

    Miután megvizsgáltam, mit tett az AB és az AC branch, úgy vélem, hogy
    az A sort D sorrá alakítani a legjobb, amit tenni lehet, és ez
    összeegyeztethető azzal, amit az AB és az AC tenni akart.

Így azt a konfliktust, amit akkor látnánk, amikor az AB-t bemerge-eljük
az ACAB-ba, ugyanúgy kell feloldani – ez az a feloldás, amely
összhangban van azzal a kijelentéssel.

Képzeljük el, hogy hasonlóképpen korábban az XY-ból leágaztattunk egy
XYXZ branchet, bemerge-eltük az XZ-t, és az „X-ből Y vagy Z lett"-et
„X-ből W lett"-re oldottuk fel.

Namármost, ha az AB-ből leágaztatunk egy ABXY branchet, majd
bemerge-eljük az XY-t, akkor az ABXY-nak az elején a B sor, a végén
pedig az Y sor lenne.  Egy ilyen merge egészen tiszta lenne.  E négy
branchből 4 kombinációt tudunk összeállítani ((AB, AC) x (XY, XZ)).

Az ABXY és az ACXZ merge-e „egy korai A-ból B vagy C lett, egy késői
X-ből Y vagy Z lett" konfliktust adna, míg az ACXY és az ABXZ merge-e
„egy korai A-ból C vagy B lett, egy késői X-ből Y vagy Z lett"-et.
Látható, hogy 4 kombináció van: („B vagy C", „C vagy B") x („X vagy Y",
„Y vagy X").

A rendezéssel a konfliktus megkapja a kanonikus nevét, nevezetesen
„egy korai részből B vagy C lett, egy késői részből X vagy Y lett", és
valahányszor e négy minta bármelyike megjelenik, eljuthatunk ugyanahhoz
a konfliktushoz és feloldáshoz, amit korábban láttunk.

A rendezés nélkül valahogy egy kombinatorikus robbanásból kellene
megtalálnunk egy korábbi feloldást.

[[_conflict_id_calculation]]
A konfliktus-azonosító kiszámítása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Miután a konfliktus-normalizálás megtörtént, a konfliktus-azonosító az
egymás után fűzött, <NUL> karakterekkel elválasztott konfliktus-hunkok
sha1 hasheként kerül kiszámításra.  A konfliktusjelölőket eltávolítjuk,
mielőtt a sha1-et kiszámítanánk.  Így a fenti példában, ahol az A sort
C sorra változtató AC branchet bemerge-eljük az A sort C sorra
változtató AB branchbe, a konfliktus-azonosító
SHA1('B<NUL>C<NUL>') lenne.

Ha egy fájlban több konfliktus van, a sha1-et ugyanígy számítjuk ki:
az összes hunkot egymás után fűzzük, abban a sorrendben, ahogy a
fájlban megjelennek, <NUL> karakterrel elválasztva.

[[_nested_conflicts]]
Egymásba ágyazott konfliktusok
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Az egymásba ágyazott konfliktusokat nagyon hasonlóan kezeljük, mint az
„egyszerű" konfliktusokat.  Az egyszerű konfliktusokhoz hasonlóan a
konfliktust először normalizáljuk: leszedjük a címkéket a
konfliktusjelölőkről, leszedjük a közös ős verzióját, és rendezzük a
konfliktus-hunkokat, mind a külső, mind a belső konfliktusnál.  Ez
rekurzívan történik, így tetszőleges számú egymásba ágyazott
konfliktus kezelhető.

Vedd figyelembe, hogy ez csak azoknál a konfliktusjelölőknél működik,
amelyek „tisztán egymásba ágyazódnak".  Ha vannak nem illeszkedő
konfliktusjelölők, a rerere nem lesz képes kezelni a konfliktust és
rögzíteni egy konfliktusfeloldást.

Az egyetlen különbség a konfliktus-azonosító kiszámításának módjában
van.  A belső konfliktusnál magukat a konfliktusjelölőket nem
távolítjuk el a sha1 kiszámítása előtt.

Tegyük fel, hogy például a következő konfliktusunk van:

    <<<<<<< HEAD
    1
    =======
    <<<<<<< HEAD
    3
    =======
    2
    >>>>>>> branch-2
    >>>>>>> branch-3~

Miután leszedtük a konfliktusjelölők címkéit, és rendeztük a hunkokat,
a konfliktus a következőképpen nézne ki:

    <<<<<<<
    1
    =======
    <<<<<<<
    2
    =======
    3
    >>>>>>>
    >>>>>>>

és végül a konfliktus-azonosító a következőképpen kerülne kiszámításra:
`sha1('1<NUL><<<<<<<\n3\n=======\n2\n>>>>>>><NUL>')`
