[[_shallow_commits]]
Sekély commitok
===============

.Definíció
*********************************************************
A sekély commitoknak vannak szülei, de nem a sekély
repóban, ezért graftok kerülnek bevezetésre, amelyek úgy
tesznek, mintha ezeknek a commitoknak nem lennének szülei.
*********************************************************

A $GIT_DIR/shallow felsorolja a commitok objektumneveit, és arra
utasítja a Gitet, hogy tegyen úgy, mintha gyökér commitok lennének
(pl. a "git log" bejárása leáll, miután megjelenítette őket; a "git
fsck" nem panaszkodik amiatt, hogy a "parent" soraikon felsorolt
commitok nem léteznek).

Minden sor pontosan egy objektumnevet tartalmaz. Olvasáskor egy
commit_graft jön létre, amelynek nr_parent < 0, hogy könnyebb legyen
megkülönböztetni a felhasználó által megadott graftoktól.

Vedd figyelembe, hogy a sekély funkciót nem lehetett könnyen átalakítani
úgy, hogy replace refeket használjon: egy `mergetag`-et tartalmazó
commitot nem szabad lecserélni, még egy gyökér commitra sem. Egy ilyen
commit ettől még sekéllyé tehető. Ráadásul az, hogy van egy `shallow`
fájl, amely explicit felsorolja az összes sekéllyé tett commitot,
*sokkal* könnyebbé teszi a sekély-specifikus műveleteket, például az
előzmények mélyítését.

Mivel az fsck-objects a könyvtárra támaszkodik az objektumok
olvasásához, automatikusan tiszteletben tartja a sekély commitokat.

Az egész sekély témának van néhány elvarratlan szála:

- lehet, hogy kényszerítenünk kell a nem vékony packeket, amikor egy
  sekély repóba fetchelünk (jelenleg kényszerítve nem vékonyak).

- Szükség van a sekély upstream speciális kezelésére. Valamely
  ponton az upload-pack-nek ellenőriznie kell, hogy sekély commitot
  küld-e, és ezt az információt korán el kell küldenie (vagy hibáznia
  kell, ha a kliens nem támogatja a sekély repository-kat). Ehhez
  ebben a patch-sorozatban egyáltalán nincs támogatás.

- Ahelyett, hogy a $GIT_DIR/shallow-t az elején zárolná, csak az
  időbélyegét jegyzi fel, és amikor az írásra kerül a sor, ellenőrzi,
  hogy az mtime még mindig ugyanaz-e, és leáll, ha nem.

- Nem világos, hogyan viselkedjen a "push egy sekély repóba / repóból".

- Ha elmélyítesz egy előzményt, szeretnéd megkapni az újonnan tárolt
  (de régebbi!) commitok tagjeit. Ez jelenleg nem működik.

Sekély klón készítéséhez hívhatod a "git-clone --depth 20 repo"
parancsot.  Az eredmény csak legfeljebb 20 hosszú commit-láncokat
tartalmaz.  Ezenkívül megír egy megfelelő $GIT_DIR/shallow fájlt.

Egy sekély repository-t elmélyíthetsz a "git-fetch --depth 20
repo branch" paranccsal, amely fetcheli a branchet a repóból, de a 20-as
mélységnél megáll, és frissíti a $GIT_DIR/shallow fájlt.

A speciális 2147483647-es mélység (avagy 0x7fffffff, a legnagyobb
pozitív szám, amelyet egy előjeles 32 bites egész tárolni tud) végtelen
mélységet jelent.
