A Git sparse-index tervdokumentuma
==================================

A sparse-checkout funkció lehetővé teszi, hogy a felhasználók a
munkakönyvtárat a HEAD-nél lévő fájlok egy részhalmazára összpontosítsák. A
`core.sparseCheckoutCone` által engedélyezett cone mode minták nagyon gyors
mintaillesztést tesznek lehetővé annak megállapításához, hogy a HEAD-nél lévő
fájlok közül melyek tartoznak a sparse-checkout cone-jába.

Egy Git-munkakönyvtár három fontos méretezési dimenziója:

* `HEAD`: hány fájl van jelen a `HEAD`-nél?

* Populated: hány fájl van a sparse-checkout cone-ján belül.

* Modified: hány fájlt módosított a felhasználó a munkakönyvtárban?

A nagy ordó jelölést -- O(X) -- használjuk annak jelölésére, hogy bizonyos
műveletek mennyire költségesek e dimenziók függvényében.

Ezeket a dimenziókat a nagyságrendjük szerint rendezzük: a felhasználók
(jellemzően) kevesebb fájlt módosítanak, mint amennyi ki van töltve, és csak a
`HEAD`-nél lévő fájlokat tudjuk kitölteni.

Problémák akkor merülnek fel, ha ezek a dimenziók rendkívül
kiegyensúlyozatlanok. Ha például a `HEAD` több millió útvonalat tartalmaz, de a
kitöltött halmaz csak több tízezret, akkor az olyan parancsoknál, mint a `git
status` és a `git add`, azok a műveletek dominálhatnak, amelyek O(`HEAD`)
műveletet igényelnek O(Populated) helyett. A költség elsősorban az index
elemzésében és újraírásában van, amely főként a `HEAD`-nél lévő, `SKIP_WORKTREE`
bittel megjelölt fájlokkal van tele.

A sparse-index célja, hogy ezeket az indexet olvasó és módosító parancsokat
O(`HEAD`)-ről O(Populated)-re vigye. Ehhez jelentős módon módosítanunk kell az
indexformátumot: „sparse directory" bejegyzéseket kell hozzáadnunk.

A cone mode mintákkal észlelhető, amikor egy teljes könyvtár tartalma a
sparse-checkout definícióján kívül lesz. Ahelyett, hogy az összes benne lévő
fájlt külön bejegyzésként listázná, a sparse-index egy olyan bejegyzést
tartalmaz a könyvtár nevével, amely a `HEAD`-nél lévő tree
objektumazonosítójára hivatkozik, és a `SKIP_WORKTREE` bittel van megjelölve.
Ha fel kell derítenünk az adott könyvtáron belüli útvonalak részleteit, tree-ket
elemezhetünk a lista megtalálásához.

Az írás pillanatában a sparse-directory bejegyzések megsértik az
indexformátummal és annak memóriabeli adatszerkezetével kapcsolatos
elvárásokat. A kódbázisban sok olyan fogyasztó van, amely azt várja, hogy az
összes index-bejegyzésen végigiterálhat, és csak fájlokat lát. Valójában ezek a
ciklusok minden stage-elt fájlra hivatkozást várnak. Ennek egyik kezelési módja,
hogy az index betöltésekor tree-ket elemzünk, és egy sparse-directory
bejegyzést lecserélünk az adott tree-n belüli összes fájlra. A tree-k elemzése
azonban lassabb, mint az indexformátum elemzése, így ez lassabb művelet, mintha
békén hagynánk az indexet. A terv az, hogy mindezeket az integrációkat „sparse
aware"-ré tesszük, hogy a tree-elemzésen keresztüli kibontás szükségtelen
legyen, és kevesebb erőforrást használjanak, mint teljes index használatakor.

Az alábbi implementációs terv négy fázist követ, hogy fokozatosan
integrálódjon a sparse-indexszel. A szándék az, hogy a Git-parancsokat
fokozatosan frissítsük, hogy jelentős lassulás nélkül, biztonságosan
működjenek együtt a sparse-indexszel. Ez nem mindig lehetséges, de a remény az,
hogy azok az elsődleges parancsok, amelyekre a felhasználóknak a napi
munkájukhoz szükségük van, drámaian javulnak.

[[_phase_i_format_and_initial_speedups]]
I. fázis: formátum és kezdeti gyorsítások
-----------------------------------------

Ebben a fázisban a Git megtanulja engedélyezni a sparse-indexet és
biztonságosan elemezni azt. Védelmek kerülnek a helyükre, hogy a memóriabeli
adatszerkezet minden fogyasztója működhessen a jelenlegi, minden `HEAD`-nél
lévő fájlra vonatkozó feltételezésével.

Kezdetben minden indexelemzés meghív egy `ensure_full_index()` segédmetódust,
amely átvizsgálja az indexet sparse-directory bejegyzésekért (amelyek tree-kre
mutatnak), és tree objektumok elemzésével lecseréli őket az útvonalak teljes
listájára (blob-tartalommal). Ez minden esetben lassabb lesz. Az egyetlen
észrevehető viselkedésbeli változás az lesz, hogy a szerializált indexfájl
sparse-directory bejegyzéseket tartalmaz.

Kezdetnek egy új, kötelező `sdir` index-kiterjesztést használunk, hogy
sparse-directory bejegyzéseket lehessen beszúrni a 2-es, 3-as és 4-es
fájlformátum-verziójú indexekbe. Ez megakadályozza, hogy a sparse-indexet nem
értő Git-verziók műveleteket végezzenek rajta, ugyanakkor lehetővé teszi, hogy
a sparse-indexet nem értő eszközök repository-kon dolgozzanak, amíg nem lépnek
kapcsolatba az indexszel. Bevezetésre kerül egy új formátum, az index v5, amely
alapértelmezés szerint tartalmaz sparse-directory bejegyzéseket. Ezen felül
más, az index javítására fontolóra vett funkciókat is bevezethet.

Ezután az index fogyasztóit megvédjük attól, hogy sparse-indexen dolgozzanak,
`ensure_full_index()` vagy `expand_index_to_path()` hívások beszúrásával. Ha egy
adott útvonalat kérnek, akkor azokat az `index_file_exists()` és
`index_name_pos()` API-hívásokon belülről védjük: szükség esetén meghívják az
`ensure_full_index()`-et. A szándék itt a meglévő viselkedés megőrzése
sparse-checkouttal való munka során. Nem akarjuk, hogy egy változás véletlenül,
tesztek nélkül történjen. E helyek közül sok esetleg nem igényel semmilyen
változtatást az őrök eltávolítása előtt, de ezt nem szabad tesztek nélkül
megtenni, amelyek biztosítják, hogy az elvárt viselkedés következzen be.

Kívánatos lehet egyes parancsok viselkedésének _megváltoztatása_ sparse index
jelenlétében, vagy általánosabban bármely sparse-checkout forgatókönyvben.
Ilyen esetekben ezeket gondosan kommunikálni és tesztelni kell. Ebben a
fázisban nem tervezünk ilyen viselkedésbeli változásokat.

A kódbázis átvizsgálása során nem minden cache-bejegyzés-iterációhoz szükséges
`ensure_full_index()` ellenőrzés. Az alapvető okok többek között:

1. A ciklus nem nulla stage-ű bejegyzéseket keres. Ezek a bejegyzések nincsenek
   sparse-directory bejegyzésbe összevonva.

2. A ciklus submodule-okat keres. Ezek a bejegyzések nincsenek sparse-directory
   bejegyzésbe összevonva.

3. A ciklus az index API része, különösen a formátum olvasása vagy írása körül.

4. A ciklus a cache-bejegyzések helyes sorrendjét ellenőrzi, és ez akkor és csak
   akkor helyes, ha a sparse-directory bejegyzések a megfelelő helyen vannak.

5. A ciklus figyelmen kívül hagyja a `SKIP_WORKTREE` bittel rendelkező
   bejegyzéseket, vagy egyébként már ismeri a sparse directory bejegyzéseket.

6. A sparse-index ezen a ponton le van tiltva a split-index funkció
   használatakor, így nem történik erőfeszítés a split-index API védelmére.

Még ezeknek az őröknek a beszúrása után is folytatjuk a sparse-indexek
kibontását a legtöbb Git-parancsnál a `command_requires_full_index`
repository-beállítással. Ez a beállítás alapértelmezés szerint be lesz
kapcsolva, és builtinenként egyesével letiltjuk, amíg kellő bizonyosságunk nem
lesz, hogy minden indexművelet megfelelően védett.

E fázis befejezéséhez a `git status` és a `git add` parancsokat integráljuk a
sparse-indexszel, hogy O(Populated) teljesítménnyel működjenek. Gondosan
tesztelni fogjuk őket a sparse-checkout definícióján belüli és kívüli
műveletekre.

[[_phase_ii_careful_integrations]]
II. fázis: óvatos integrációk
-----------------------------

Ez a fázis annak biztosítására összpontosít, hogy minden index-kiterjesztés
és API jól működjön sparse-indexszel. Ehhez jelentősen növelni kell a
tesztlefedettségünket, különösen azoknál a műveleteknél, amelyek a
sparse-checkout definícióján kívül lépnek kapcsolatba a munkakönyvtárral. Ezek
a viselkedések közül némelyik nem biztos, hogy a kívánatos, például néhány
teszt, amely a `t1092-sparse-checkout-compatibility.sh`-ban már bukásra van
jelölve.

A különleges integrációt igénylő index-kiterjesztések:

* FS Monitor
* Untracked cache

Az ezekkel a funkciókkal való integráció során olyan mintákat kell keresnünk,
amelyek jobb API-khoz vezethetnek az indexszel való munkához. Ha a gyakori
használati mintákat egy API-hívásba vonjuk össze, csökkenthető azoknak a
helyeknek a száma, ahol a sparse-directory-kat gondosan kell kezelni.

[[_phase_iii_important_command_speedups]]
III. fázis: fontos parancsok gyorsítása
---------------------------------------

Ezen a ponton a sparse-directory logika tesztelésének és
implementálásának mintái viszonylag stabilnak számítanak. Ez a fázis néhány
leggyakoribb, az indexet használó builtin frissítésére összpontosít, hogy
O(Populated) módon működjenek. Íme egy lehetséges lista azokról a parancsokról,
amelyeket ezen a ponton érdemes lehet integrálni:

* `git commit`
* `git checkout`
* `git merge`
* `git rebase`

Remélhetőleg az olyan parancsok, mint a `git merge` és a `git rebase`, inkább
olyan merge-algoritmusokból profitálhatnak, amelyek nem használják az indexet
adatszerkezetként, mint például a merge-ORT stratégia. Ahogy ezek a témák
érnek, engedélyezhetjük az ORT stratégiát alapértelmezés szerint a
sparse-index funkciót használó repository-kra.

A `git status` és a `git add` mellett ezek a parancsok fedik le a
felhasználók munkakönyvtárral való interakcióinak többségét. Ezen felül a
következő parancsokkal is integrálhatunk:

* `git grep`
* `git rm`

Ezeket olyanokként javasolták, amelyek viselkedése megváltozhat sparse-checkout
definícióval rendelkező repóban. Jó lenne ezt a viselkedést automatikusan
beépíteni sparse-index használatakor. Bizonyos egyértelműségre van szükség
ahhoz, hogy a viselkedésváltás világos legyen a felhasználó számára.

Ez az első olyan fázis, ahol a párhuzamos munka lehetséges lehet a témák közötti
túl sok konfliktus nélkül.

[[_phase_iv_the_long_tail]]
IV. fázis: a hosszú farok
-------------------------

Ez az utolsó fázis kevésbé „fázis", inkább „az új normális" az összes korábbi
munka után.

Kezdetnek a `command_requires_full_index` opció eltávolítható lenne annak
javára, hogy a kibontás csak akkor történjen, amikor egy API-őrbe ütközünk.

Sok olyan Git-parancs van, amely különös figyelmet érdemelne, hogy O(Populated)
módon működjön, míg néhány annyira ritka lehet, hogy elfogadható őket
sparse-index jelenlétében többletterheléssel hagyni.

Íme néhány parancs, amelyet érdemes lehet frissíteni:

* `git sparse-checkout set`
* `git am`
* `git clean`
* `git stash`
