= Egyértelmű típusok

A leképezések többsége nyilvánvaló, de a Rust FFI-vel (Foreign Function
Interface) kapcsolatban van néhány árnyalatnyi különbség és buktató.

Ez a dokumentum világos, egy-az-egyhez leképezéseket határoz meg a C, a Rust
(és a jövőben esetleg más nyelvek) primitív típusai között. Célja, hogy
kiküszöbölje a típusszélességek, az előjelesség és a bináris ábrázolás
körüli többértelműséget a különböző platformok és nyelvek között.

A Gitben C-ben ezeknek az egyértelmű típusoknak a használatához az egyetlen
szükséges header a `git-compat-util.h`.

[[_boolean_types]]
== Logikai típusok
[cols="1,1", options="header"]
|===
| C-típus | Rust-típus
| bool^1^       | bool
|===

[[_integer_types]]
== Egész típusok

C-ben be kell húzni a `<stdint.h>`-t (vagy egy megfelelőjét).

[cols="1,1", options="header"]
|===
| C-típus | Rust-típus
| uint8_t    | u8
| uint16_t   | u16
| uint32_t   | u32
| uint64_t   | u64

| int8_t     | i8
| int16_t    | i16
| int32_t    | i32
| int64_t    | i64
|===

[[_floating_point_types]]
== Lebegőpontos típusok

A Rust IEEE-754 szemantikát követel meg.
C-ben ez jellemzően igaz, de a szabvány nem garantálja.

[cols="1,1", options="header"]
|===
| C-típus | Rust-típus
| float^2^      | f32
| double^2^     | f64
|===

[[_size_types]]
== Méret-típusok

Ezek a típusok mutató méretű egész számokat képviselnek, és jellemzően a
`<stddef.h>`-ban vagy egy megfelelő headerben vannak definiálva.

Méret-típusokat kell használni minden alkalommal, amikor mutatóaritmetika
történik, pl. tömb indexelése, a memóriában lévő elemek számának megadása
stb...

[cols="1,1", options="header"]
|===
| C-típus | Rust-típus
| size_t^3^     | usize
| ptrdiff_t^3^  | isize
|===

[[_character_types]]
== Karaktertípusok

Itt nincs tiszta egy-az-egyhez leképezés a C és a Rust között.

A C `char` és a Rust `u8` bitszélessége azonos, így bármely `char`-t
tartalmazó C struct mérete megegyezik a `u8`-at használó megfelelő Rust
structéval. Ilyen értelemben az ilyen structok biztonságosan átadhatók az
FFI-határon, mert a mezőik elrendezése azonos lesz. A bitszélességen túl
azonban a C `char` további szemantikával és platformfüggő viselkedéssel
rendelkezik, ami az alább tárgyalt módon problémákat okozhat.

A C nyelv a `char` előjelességét implementációfüggőként hagyja. Mivel a
fejlesztői buildünk bekapcsolja a -Wsign-compare-t, egy `char` típusú érték
előjeles vagy előjel nélküli egészekkel való összehasonlítása
figyelmeztetéseket válthat ki a fordítóból.

Megjegyzés: a Rust `char` típusa egy előjel nélküli 32 bites egész szám,
amely Unicode kódpontok leírására szolgál.

[[_notes]]
=== Megjegyzések
^1^ Ez csak akkor igaz, ha a stdbool.h-t (vagy megfelelőjét) használják. +
^2^ A C nem kényszeríti ki az IEEE-754 kompatibilitást, de a Rust elvárja azt.
Ha a C platformja/architektúrája nem követi az IEEE-754-et, akkor ez az
ekvivalencia nem áll fenn. Továbbá feltételezzük, hogy a `float` 32 bites, a
`double` pedig 64, de lehet olyan furcsa platform/architektúra, ahol még ez
sem igaz. +
^3^ A C definiálja az uintptr_t, ssize_t és intptr_t típusokat is, de ezek a
típusok FFI célokra nem ajánlottak. Az olyan függvényeknél, mint a `read()` és
a `write()`, az ssize_t-t egy másik, egyértelmű típusra kell kasztolni, mielőtt
átadnák az FFI-határon. +

[[_problems_with_std_ffi_c_types_in_rust]]
== A std::ffi::c_* típusok problémái a Rustban
TL;DR: a gyakorlatban a Rust `c_*` típusai nem garantáltan egyeznek a C
típusokkal az összes lehetséges C fordító, platform vagy architektúra esetén,
mert a Rust csak a hivatalosan támogatott célpontokon biztosítja a C típusok
helyességét. Ezek a definíciók az idők során változtak, hogy több célpontot
lefedjenek, ami azt jelenti, hogy a c_* definíciók attól függően különböznek,
melyik Rust verziót választja a Git.

A biztonságos, Rust oldali FFI típusok jelenlegi listája a Gitben: +

* `c_void`
* `CStr`
* `CString`

Még ekkor is takarékosan kell használni őket, és csak ott, ahol a szemantika
pontosan egyezik.

A std::os::raw::c_* közvetlenül örökli a core::ffi problémáit, amely az idők
során változik, és úgy tűnik, hogy egy adott platformhoz/célponthoz a helyes
definícióra tett legjobb becsléssel dolgozik. Ez valószínűleg nem probléma az
összes többi platformon, amelyet a Rust jelenleg támogat, de meg tudja-e
bárki mondani, hogy a Rust minden platform/célpont minden C fordítójára
helyesen csinálta?

Egy példa: a c_long így van definiálva:
footnote:[https://doc.rust-lang.org/1.63.0/src/core/ffi/mod.rs.html#175-189[c_long az 1.63.0-ban]]
footnote:[https://doc.rust-lang.org/1.89.0/src/core/ffi/primitives.rs.html#135-151[c_long az 1.89.0-ban]]

[[_rust_version_1_63_0]]
=== Rust 1.63.0-s verzió

```
mod c_long_definition {
    cfg_if! {
        if #[cfg(all(target_pointer_width = "64", not(windows)))] {
            pub type c_long = i64;
            pub type NonZero_c_long = crate::num::NonZeroI64;
            pub type c_ulong = u64;
            pub type NonZero_c_ulong = crate::num::NonZeroU64;
        } else {
            // The minimal size of `long` in the C standard is 32 bits
            pub type c_long = i32;
            pub type NonZero_c_long = crate::num::NonZeroI32;
            pub type c_ulong = u32;
            pub type NonZero_c_ulong = crate::num::NonZeroU32;
        }
    }
}
```

[[_rust_version_1_89_0]]
=== Rust 1.89.0-s verzió

```
mod c_long_definition {
    crate::cfg_select! {
        any(
            all(target_pointer_width = "64", not(windows)),
            // wasm32 Linux ABI uses 64-bit long
            all(target_arch = "wasm32", target_os = "linux")
        ) => {
            pub(super) type c_long = i64;
            pub(super) type c_ulong = u64;
        }
        _ => {
            // The minimal size of `long` in the C standard is 32 bits
            pub(super) type c_long = i32;
            pub(super) type c_ulong = u32;
        }
    }
}
```

Még azokban az esetekben is vannak problémák, amikor a C típusok helyesen
vannak leképezve Rust típusokra a std::ffi::c_* révén. Vegyük például a
c_char-t. Egyes platformokon u8, másokon i8.

[[_subtraction_underflow_in_debug_mode]]
=== Kivonási alulcsordulás debug módban

A következő kód debug módban pánikol azokon a platformokon, amelyek a
c_char-t u8-ként definiálják, de nem, ha az i8.

```
let mut x: std::ffi::c_char = 0;
x -= 1;
```

[[_inconsistent_shift_behavior]]
=== Inkonzisztens eltolási viselkedés

Az `x` értéke 0xC0 lesz az i8-at használó platformokon, de 0x40 ott, ahol u8.

```
let mut x: std::ffi::c_char = 0x80;
x >>= 1;
```

[[_equality_fails_to_compile_on_some_platforms]]
=== Az egyenlőség egyes platformokon nem fordul le

A következő nem fordul le azokon a platformokon, amelyek a c_char-t
i8-ként definiálják, de lefordul, ha u8. Az x kasztolható, pl.
`assert_eq!(x as u8, b'a');`, de akkor az u8-at használó platformokon
figyelmeztetést kapsz, ott pedig, ahol i8-at használnak, tiszta fordítást.

```
let mut x: std::ffi::c_char = 0x61;
assert_eq!(x, b'a');
```

[[_enum_types]]
== Enum típusok
A Rust enum típusokat nem szabad FFI típusként használni. A Rust enum
típusok inkább a C union típusokra hasonlítanak, mint a C enumjaira. Valami
ilyesmihez:

```
#[repr(C, u8)]
enum Fruit {
    Apple,
    Banana,
    Cherry,
}
```

Elég egyszerű biztosítani, hogy a Rust enum megfeleljen annak, amit a C
elvárna, de egy összetettebb típus, mint például.

```
enum HashResult {
    SHA1([u8; 20]),
    SHA256([u8; 32]),
}
```

A Rust fordítónak diszkriminánst kell hozzáadnia az enumhoz, hogy
megkülönböztesse a variánsokat. Ennek a diszkriminánsnak a szélessége, helye
és értékei a Rust fordítóra vannak bízva, és nem ABI-stabilak.
