= Közelgő kompatibilitástörő változások

A Git projekt a lehető legjobban törekszik a visszafelé kompatibilitás
biztosítására. A minor kiadások nem törik meg a visszafelé kompatibilitást,
hacsak nincs nagyon erős ok rá, mint például egy biztonsági sebezhetőség.

Ettől függetlenül a Git projekt kora miatt csak természetes, hogy
felhalmozódik a visszafelé nem kompatibilis változások hátraléka, amelyekre
végül szükség lesz ahhoz, hogy a projekt lépést tartson a változó világgal.
Ezek a változások több kategóriába esnek:

* Régóta bevett alapértelmezések megváltoztatása.
* Fogalmak, amelyeket egy jobb kialakítás váltott le.
* Fogalmak, parancsok, konfiguráció vagy opciók, amelyek jelentős
  hiányosságokkal bírtak, és nem javíthatók, ezért mindenféle pótlás nélkül
  eltávolításra kerülnek.

Kifejezetten nem szerepelnek ezen a listán a kisebb hibák javításai,
amelyek a felhasználó által látható viselkedés megváltozását okozhatják.

A Git projekt szabálytalan időközönként ad ki olyan kompatibilitástörő
verziókat, amelyek szándékosan megtörik a visszafelé kompatibilitást a
régebbi verziókkal. Ez azért történik, hogy a Git a jövőben is releváns,
biztonságos és karbantartható maradjon. A kompatibilitástörő verziók kiadási
üteme jellemzően több évben mérhető. A múltban a következő nagyobb
kompatibilitástörő kiadásaink voltak:

* Git 1.6.0, kiadva 2008 augusztusában.
* Git 2.0, kiadva 2014 májusában.

Manapság <major>.<minor> kiadási számokat használunk, a Git 2.0-tól kezdve. A
jövőbeli kiadásoknál az a tervünk, hogy a kiadási szám <major> részét
növeljük, amikor a következő kompatibilitástörő kiadást készítjük. A Git 2.0
előtt a kiadási számok 1.<major>.<minor> alakúak voltak, azzal a szándékkal,
hogy a <major> a „szokásos" kompatibilitástörő kiadásoknál növekedjen, a Git
2.0-ra való ugrást pedig a valóban nagy, visszafelé kompatibilitást törő
változásoknak tartsuk fenn.

Ennek a dokumentumnak a célja a jövőbeli kompatibilitástörő kiadásokhoz
tartozó közelgő elavulttá nyilvánítások nyomon követése. Továbbá ez a
dokumentum azt is nyomon követi, mi _nem_ lesz elavulttá nyilvánítva. Ez
azért van így, hogy a megbeszélések kimenete dokumentálja mind azt, amikor a
megbeszélés az elavulttá nyilvánítást támogatja, mind azt, amikor elutasítja.

A tételekhez tartoznia kell egy világos összefoglalónak arról, miért
szeretnénk vagy nem szeretnénk elvégezni a leírt változtatást, amely
könnyen érthető anélkül, hogy el kellene olvasni a levelezőlista-vitákat. Ha
a megváltoztatott funkciónak vannak alternatívái, ezekre az alternatívákra
rá kell mutatni a felhasználóinknak.

Minden tételt kísérnie kell a releváns levelezőlista-szálakra való
hivatkozásoknak, ahol az elavulttá nyilvánítást megvitatták. Ezek a
hivatkozások message-ID-kat használnak, amelyek a

  https://lore.kernel.org/git/$message_id/

címen látogathatók meg az üzenet és a körülötte lévő megbeszélés
megtekintéséhez. Egy ilyen hivatkozás azért van ott, hogy megkönnyítse
számodra annak felderítését, hogyan jutott a projekt akkoriban konszenzusra a
leírt tételről.

Ez egy élő dokumentum, mivel a projektet körülvevő környezet idővel
változik. Ha a körülmények megváltoznak, egy korábbi döntést valaminek az
elavulttá nyilvánításáról vagy megváltoztatásáról időnként újra kell
gondolni. Ezért ne úgy értelmezd az ezen a listán szereplő tételeket, hogy
„ez el van döntve, ne pazarold az időnket azzal, hogy újra előhozod".

[[_procedure]]
== Eljárás

A kompatibilitástörő változtatások iránti igény megvitatása, annak
kijelentése, hogy a kompatibilitástörő változtatások egy bizonyos
verzióhatárnál történnek meg, és e döntések rögzítése ebben a dokumentumban
szükséges, de nem elegendő.
Mivel az ilyen változtatások várhatóan számosak, és a kialakításuk, valamint
a megvalósításuk várhatóan hosszabb időt fog át, egy ilyen verzióhatárnál
triviálisan bevethetőnek kell lenniük, hosszú idő alatt előkészítve.

A kompatibilitástörő változtatásokat egy fordításidejű kapcsolóval,
a WITH_BREAKING_CHANGES kapcsolóval MUST védeni, hogy ez a folyamat
könnyebb legyen.  Amikor ezzel fordítják le, az eredményül kapott Git
bináris a dokumentációjával együtt úgy viselkedne, mintha a következő nagy
verzióhatárra tervezett kompatibilitástörő változtatások már érvényben
lennének.  Van egy CI feladatunk is a Git folyamatban lévő verziójának
gyakorlására ezekkel a kompatibilitástörő változtatásokkal.


[[_git_3_0]]
== Git 3.0

A következő alszakaszok a Git 3.0-hoz tartozó közelgő kompatibilitástörő
változásokat dokumentálják. Ehhez a kompatibilitástörő verzióhoz még nincs
tervezett kiadási dátum.

A javasolt változások és eltávolítások csak olyan tételeket tartalmaznak,
amelyek „készen állnak" az elvégzésre. Más szóval ez nem egy kívánságlista
olyan funkciókról, amelyekre át kellene váltani vagy amelyeket le kellene
cserélni, ha az alternatívát már megvalósították.

[[_changes]]
=== Változások

* Az új repositorykhoz tartozó alapértelmezett hash függvény "sha1"-ről
  "sha256"-ra változik. Az SHA-1-et a NIST 2011-ben elavulttá nyilvánította,
  és manapság a FIPS 140-2 és hasonló tanúsítványok ellenjavallják.
  Továbbá vannak gyakorlati támadások az SHA-1 ellen, amelyek gyengítik a
  kriptográfiai tulajdonságait:
+
  ** The SHAppening (2015). Az első demonstrációja egy gyakorlati SHA-1
     elleni támadásnak 2^57 művelettel.
  ** SHAttered (2017). Két érvényes PDF fájl előállítása 2^63 művelettel.
  ** Birthday-Near-Collision (2019). Ez a támadás választott előtagú
     támadásokat tesz lehetővé 2^68 művelettel.
  ** Shambles (2020). Ez a támadás választott előtagú támadásokat tesz
     lehetővé 2^63 művelettel.
+
Bár vannak védelmeink az ismert támadásokkal szemben, várható, hogy a
jövőbeli kutatás további SHA-1 elleni támadásokat talál majd. Párosítva a
hardver folyamatosan növekvő képességével, csak idő kérdése, mikor tekintik
az SHA-1-et teljesen feltörtnek. Fel akarunk készülni, ezért az újonnan
inicializált repositorykhoz az alapértelmezett hash algoritmust "sha256"-ra
változtatjuk.
+
E változás fontos követelménye, hogy az ökoszisztéma készen álljon a
"sha256" objektumformátum támogatására. Ez magában foglalja a népszerű Git
könyvtárakat, alkalmazásokat és forge-okat.
+
Jelenleg nincs terv a "sha1" objektumformátum elavulttá nyilvánítására.
+
Vö. <2f5de416-04ba-c23d-1e0b-83bb655829a7@zombino.com>,
<20170223155046.e7nxivfwqqoprsqj@LykOS.localdomain>,
<CA+EOSBncr=4a4d8n9xS4FNehyebpmX8JiUwCsXD47EQDE+DiUQ@mail.gmail.com>.

* Az újonnan létrehozott repositorykban a referenciák alapértelmezett
  tárolási formátuma "files"-ról "reftable"-re változik. A "reftable"
  formátum több előnyt is nyújt a "files" formátummal szemben:
+
  ** A "files" formátummal lehetetlen két olyan referenciát tárolni, amelyek
     csak a kis-/nagybetűkben térnek el, kis-/nagybetűre érzéketlen
     fájlrendszereken. Ez a probléma gyakori Windows és macOS platformokon.
     Mivel a "reftable" backend nem használ fájlrendszerbeli útvonalakat a
     referencianevek kódolására, ez a probléma megszűnik.
  ** Hasonlóképpen a macOS normalizálja az unicode karaktereket tartalmazó
     útvonalneveket, aminek az a következménye, hogy nem tárolhatsz két
     unicode karaktereket tartalmazó nevet, amelyek eltérően vannak kódolva,
     a "files" backenddel. Ez a "reftable" backenddel megint csak nem
     probléma.
  ** A referenciák törléséhez a "files" backenddel a Gitnek újra kell írnia
     a teljes "packed-refs" fájlt. Sok referenciával rendelkező nagy
     repositorykban ez a fájl könnyen tucatnyi megabájt méretű lehet,
     szélsőséges esetekben akár gigabájtos. A "reftable" backend
     sírkő-jelölőket használ a törölt referenciákhoz, így nem kell újraírnia
     az összes adatát.
  ** A repository-karbantartás a "files" backenddel jellemzően a referenciák
     mindent-egybe újracsomagolását végzi. Ez elég költséges lehet, és
     ennek következtében a karbantartás kompromisszum a felhalmozódó, a
     referenciákat olvasó műveleteket lassító laza referenciák száma, és e
     laza referenciáknak a "packed-refs" fájlba tömörítése között. A
     "reftable" backend geometriai tömörítést használ minden írás után, ami
     amortizálja a költségeket, és biztosítja, hogy a backend mindig
     jól karbantartott állapotban legyen.
  ** Az egyszerre több referenciát író műveletek nem atomiak a "files"
     backenddel. Ennek következtében a Git köztes állapotokat láthat, amikor
     referenciákat olvas, miközben egy referenciatranzakció éppen lemezre
     íródik.
  ** Sok referencia egyszerre való írása lassú a "files" backenddel, mert
     minden referencia külön fájlként jön létre. A "reftable" backend
     jelentősen, több nagyságrenddel felülmúlja a "files" backendet.
  ** A reftable backend bináris formátumot használ előtag-tömörítéssel a
     referencianevekhez. Ennek eredményeként a formátum kevesebb helyet
     használ a "packed-refs" fájlhoz képest.
+
Azok a felhasználók, akik azonnali hasznot húznak a "reftable" backendből,
továbbra is kézzel opt-inolhatnak a "reftable" formátumra az
"init.defaultRefFormat" config beállításával. De az alapértelmezések
számítanak, és úgy gondoljuk, hogy összességében a felhasználóknak jobb
lesz az élményük, kevesebb platformspecifikus furcsasággal, ha
alapértelmezés szerint az új backendet használják.
+
E változás előfeltétele, hogy az ökoszisztéma készen álljon a "reftable"
formátum támogatására. Legfontosabb, hogy a Git alternatív implementációi,
mint a JGit, a libgit2 és a Gitoxide, támogassák.

* Az új repositorykban az alapértelmezett branchnév `main` lesz. A
  675704c74dd (init: provide useful advice about init.defaultBranch,
  2020-12-11) óta figyelmeztetünk, hogy az alapértelmezett név változni fog.
  Az új név megegyezik azzal az alapértelmezett branchnévvel, amelyet sok
  nagy Git forge használ az új repositorykban.

* A Git a build folyamat kötelező részeként meg fogja követelni a Rustot. Bár
  a Git a Git 2.49-ben már elkezdte átvenni a Rustot, a Rustban írt összes
  rész egyelőre opcionális. Ez magában foglalja:
+
  ** A libgit.a köré írt Rust wrappert, amely a "contrib/" része, és amelyet
     a Git 2.49-ben vezettek be.
  ** Azokat az alrendszereket, amelyeknek van alternatív Rust
     implementációjuk a C és a Rust kódbázisunk közötti interoperabilitás
     tesztelésére.
  ** Az újonnan írt funkciókat, amelyek nem kritikusak egy teljesen működő
     Git kliens szempontjából.
+
Ezek a változtatások próbaléggömböknek szánták, hogy a Git terjesztői
felkészülhessenek arra, hogy a Rust a build folyamat kötelező részévé válik.
A Rust bevezetésének több mérföldköve lesz:
+
--
1. Kezdetben, a Git 2.52-vel, a Rust támogatását a Meson automatikusan
   felismeri, a Makefile-unkban pedig letiltja, hogy a projekt rendezni
   tudja a kezdeti infrastruktúrát.
2. A Git 2.55-ben mindkét build rendszer alapértelmezés szerint engedélyezi a
   Rust támogatását. Ennek következtében a buildek alapértelmezés szerint
   megtörnek, ha a Rust nem érhető el a build hoszton. A Rust használata
   továbbra is kifejezetten letiltható build kapcsolókkal.
3. A Git 3.0-ban a build opciók eltávolításra kerülnek, és a Rust támogatása
   kötelező.
--
+
Kifejezetten megkérheted mind a Mesont, mind a Makefile-alapú rendszerünket a
Rust engedélyezésére a `meson configure -Drust=enabled`, illetve a
`make WITH_RUST=YesPlease` megadásával.
+
A Git projekt a Git 3.0 előtti utolsó verziót hosszú távú támogatási
kiadásnak nyilvánítja. Ez a hosszú távú kiadás legalább négy kiadási
cikluson át fontos hibajavításokat, hat kiadási cikluson át pedig
biztonsági javításokat kap. A Git projekt átadja a hosszú távú kiadás
karbantartását a terjesztőknek arra az esetre, ha még tovább kell
hosszabbítaniuk annak a hosszú távú kiadásnak az életét. Annak részleteit,
hogy ez a hosszú távú kiadás hogyan kerül átadásra a közösségnek, akkor
vitatják meg, amikor a Git projekt úgy dönt, hogy leállítja a hivatalos
támogatását.
+
Kiértékeljük a downstream disztribúciókra gyakorolt hatást, mielőtt a Rustot
kötelezővé tennénk a Git 3.0-ban. Ha azt látjuk, hogy a downstream
disztribúciókra gyakorolt hatás jelentős lenne, dönthetünk úgy, hogy ezt a
változást egy későbbi minor kiadásra halasztjuk. Ez a kiértékelés a saját
tapasztalatunkat is figyelembe veszi arról, mennyire fájdalmas a Rustot
opcionális komponensként tartani.

* A `safe.bareRepository` alapértelmezett értéke `all`-ról `explicit`-re
  változik. Túl könnyű egy támadónak rávennie egy felhasználót arra, hogy
  klónozzon egy olyan repositoryt, amely beágyazott bare repositoryt
  tartalmaz, rosszindulatú hookokkal konfigurálva. Ha a felhasználó belép
  abba az alkönyvtárba, és bármilyen Git parancsot futtat, a Git felfedezi a
  bare repositoryt, és a hookok elsülnek. A felhasználónak még csak
  kifejezetten futtatnia sem kell Git parancsot: sok shell prompt a háttérben
  futtatja a `git status`-t, hogy branch- és piszkos-állapot-információt
  jelenítsen meg, a `git status` pedig meghívhatja az fsmonitor hookot, ha
  így van konfigurálva, sebezhetővé téve a felhasználót abban a pillanatban,
  amikor `cd`-vel belép a könyvtárba. A `safe.bareRepository` konfigurációs
  változót a 8959555cee (setup_git_directory(): add an owner check for the
  top-level directory, 2022-03-02) vezette be `all` alapértelmezéssel a
  visszafelé kompatibilitás megőrzésére.
+
Az alapértelmezés `explicit`-re változtatása azt jelenti, hogy a Git megtagadja
a munkát azokkal a bare repositorykkal, amelyeket implicit módon, a
könyvtárfán felfelé haladva fedez fel. Azok a bare repositoryk, amelyeket
kifejezetten a `--git-dir` parancssori opcióval vagy a `GIT_DIR` környezeti
változóval adnak meg, ettől a beállítástól függetlenül továbbra is működnek.
Azok a repositoryk, amelyek `.git` könyvtárnak, worktree-nek vagy submodule
könyvtárnak tűnnek, szintén érintetlenek.
+
Azok a felhasználók, akik a bare repositoryk implicit felfedezésére
támaszkodnak, visszaállíthatják a korábbi viselkedést a
`safe.bareRepository=all` beállításával a globális vagy rendszerszintű
konfigurációjukban.

[[_removals]]
=== Eltávolítások

* A commitok graftolásának támogatását régóta leváltotta a git-replace(1). A
  graftok gyengébbek a helyettesítő refeknél:
+
  ** A graftok kizárólag lokális mechanizmus, és nem oszthatók meg
     repositoryk között.
  ** A graftok nehezen diagnosztizálható problémákhoz vezethetnek az
     objektumok repositoryk közötti átvitelekor.
+
A graftolási mechanizmust az e650d0643b (docs: mark info/grafts as outdated,
2014-03-05) óta elavultként jelöltük, és el fog távolításra kerülni.
+
Vö. <20140304174806.GA11561@sigill.intra.peff.net>.

* A git-pack-redundant(1) parancs redundáns pack fájlok eltávolítására
  használható. Az alparancs használhatatlanul lassú, és feltehetően azért nem
  jelenti senki teljesítménybugként, mert nincsenek felhasználói. A parancsot
  eltávolításra jelöltük, és a c3b58472be (pack-redundant: gauge the usage
  before proposing its removal, 2020-08-25) óta felhasználó által látható
  figyelmeztetést adunk, valahányszor a parancs végrehajtódik.
+
Eddig egyetlen panasz volt arról, hogy valaki még használja a parancsot, de
ez a panasz nem késztetett minket az irány megfordítására. Épp ellenkezőleg,
megkétszereztük az elavulttá nyilvánítást, és a 4406522b76 (pack-redundant:
escalate deprecation warning to an error, 2023-03-23) óta a parancs meghal,
hacsak a felhasználó nem adja meg a `--i-still-use-this` opciót.
+
Nem érkeztek további panaszok, így ez a parancs végül eltávolításra kerül.
+
Vö. <xmqq1rjuz6n3.fsf_-_@gitster.c.googlers.com>,
    <CAKvOHKAFXQwt4D8yUCCkf_TQL79mYaJ=KAKhtpDNTvHJFuX1NA@mail.gmail.com>,
    <20230323204047.GA9290@coredump.intra.peff.net>,

* A remote URL-ekhez tartozó rövidítések "$GIT_COMMON_DIR/branches/"-ban és
  "$GIT_COMMON_DIR/remotes/"-ban való tárolásának támogatását régóta
  leváltotta a remote-ok repository-konfigurációban való tárolása.
+
A mechanizmust eredetileg az f170e4b39d ([PATCH] fetch/pull: short-hand
notation for remote repositories., 2005-07-16) vezette be, és leváltotta a
6687f8fea2 ([PATCH] Use .git/remote/origin, not .git/branches/origin.,
2005-08-20), ahol áttértünk a ".git/branches/"-ról a ".git/remotes/"-ra. Az a
commit már említ egy közelgő elavulttá nyilvánítást a ".git/branches/"
könyvtárra, és az a1d4aa7424 (Add repository-layout document., 2005-09-01)
óta ezt az elrendezést is elavultként jelöltük. Végül elkezdtünk elvándorolni
a ".git/remotes/"-tól is a config-alapú remote-ok javára, és a 3d3d282146
(Documentation: Grammar correction, wording fixes and cleanup, 2011-08-23)
óta a könyvtárat régi (legacy) jelöléssel láttuk el
+
Ahogy a dokumentációnk említi, ezeket a könyvtárakat modern repositorykban
valószínűleg nem használják, és a legtöbb felhasználó nincs is tudatában
ezeknek a mechanizmusoknak. Csaknem 20, illetve 14 éve elavulttá vannak
nyilvánítva, és nincs tudomásunk egyetlen aktív felhasználóról sem, aki
panaszkodott volna erre az elavulttá nyilvánításra. Továbbá a
".git/branches/" könyvtár manapság megtévesztő nevű, és zavart okozhat, mivel
a „branchek" szinte kizárólag a referenciák kontextusában használatosak.
+
Ezek a funkciók el fognak távolításra kerülni.

* A "--stdin" opció támogatását a "name-rev" parancsban a Git 2.40
  időszakában elavulttá nyilvánították (és elrejtették a dokumentációból), a
  szinonimája, a "--annotate-stdin" javára.  A Git 3.0 teljesen eltávolítja a
  "--stdin" támogatását.

* A git-whatchanged(1) parancs több mint 10 éve túlélte a hasznosságát, és
  több billentyűleütést igényel begépelni, mint a nagyjából egyenértékű
  `git log --raw`.  A parancsot eltávolításra jelöltük, megváltoztattuk a
  parancsot úgy, hogy megtagadja a működést, hacsak a `--i-still-use-this`
  opciót nem adják meg, és megkértük a felhasználókat, hogy jelezzék, ha így
  tesznek.
+
A parancs el fog távolításra kerülni.

* A `core.commentString=auto` támogatását elavulttá nyilvánították, és a Git
  3.0-ban eltávolításra kerül.
+
vö. <xmqqa59i45wc.fsf@gitster.g>

* A `core.preferSymlinkRefs=true` támogatását elavulttá nyilvánították, és a
  Git 3.0-ban eltávolításra kerül. A szimbolikus refek szimbolikus linkként
  való írását fokozatosan kivezetik, a szimbolikus refek szöveges
  ábrázolását használó egyszerű fájlok javára.
+
A szimbolikus referenciákat kezdetben mindig szimbolikus linkként tárolták.
Ez a 9b143c6e15 (Teach update-ref about a symbolic ref stored in a textfile.,
2005-09-25) commitban változott meg, ahol egy új szöveges symref formátumot
vezettek be, hogy ezeket a szimbolikus refeket egyszerű fájlban tárolják. A
9f0bb90d16 (core.prefersymlinkrefs: use symlinks for .git/HEAD, 2006-05-02)
commitban a Git projekt átállította az alapértelmezést a szöveges symrefek
használatára a szimbolikus linkek helyett.
+
A szimbolikus linkektől való elvándorlás mostanra csaknem 20 éve megtörtént,
és nincs ismert ok, amiért manapság előnyben kellene részesíteni őket.
Továbbá a szimbolikus linkeket egyes platformok nem támogatják.
+
Vedd figyelembe, hogy csak az ilyen szimbolikus linkek írási oldala van
elavulttá nyilvánítva. Az ilyen szimbolikus linkek olvasása egyelőre
továbbra is támogatott.

[[_superseded_features_that_will_not_be_deprecated]]
== Leváltott funkciók, amelyeket nem nyilvánítanak elavulttá

Egyes funkciók újabb helyettesítőket kaptak, amelyek bizonyos módokon a
kialakítás javítását célozzák. Az, hogy létezik helyettesítő, nem jelenti
automatikusan, hogy a dolgok régi módja végül eltávolításra kerül. Ez a
szakasz az újabb alternatívával rendelkező funkciókat követi nyomon.

* A git-checkout(1) által kínált funkciókat lefedi a git-restore(1) és a
  git-switch(1) parancspáros. Mivel a git-checkout(1) használata még mindig
  elterjedt, és nem várható, hogy ez a közeljövőben változni fog, mindhárom
  parancs megmarad.
+
Ez a döntés újragondolható arra az esetre, ha valaha kiderülne, hogy már
szinte egyik parancsnak sincsenek felhasználói.
+
Vö. <xmqqttjazwwa.fsf@gitster.g>,
<xmqqleeubork.fsf@gitster.g>,
<112b6568912a6de6672bf5592c3a718e@manjaro.org>.
