DATE FORMATS
------------

A `GIT_AUTHOR_DATE` és a `GIT_COMMITTER_DATE` környezeti változók a
következő dátumformátumokat támogatják:

Git belső formátum::
	Ez `<unix-timestamp> <time-zone-offset>` alakú, ahol az
	`<unix-timestamp>` a UNIX-epoch óta eltelt másodpercek száma.
	A `<time-zone-offset>` az UTC-től való pozitív vagy negatív
	eltolás. Például a CET (amely 1 órával jár az UTC előtt) `+0100`.
+
Biztonságosabb, ha az `<unix-timestamp>` elé `@`-ot teszel (pl.
`@0 +0000`), ami arra kényszeríti a Gitet, hogy nyers timestampként
értelmezze. Ez 100 000 000-nál kisebb értékeknél (amelyeknek kevesebb
mint 9 számjegyük van) kötelező, hogy elkerüld az összetévesztést
más dátumformátumokkal, mint például a `YYYYMMDD`.

RFC 2822::
	Az RFC 2822 által leírt szabványos dátumformátum, például
	`Thu, 07 Apr 2005 22:13:13 +0200`.

ISO 8601::
	Az ISO 8601 szabvány által megadott idő és dátum, például
	`2005-04-07T22:13:13`. Az értelmező a `T` karakter helyett egy
	szóközt is elfogad. A másodperc törtrészei figyelmen kívül
	maradnak, például a `2005-04-07T22:13:13.019` úgy lesz kezelve,
	mintha `2005-04-07T22:13:13` lenne.
+
NOTE: Emellett a dátumrész a következő formátumokban is elfogadott:
`YYYY.MM.DD`, `MM/DD/YYYY` és `DD.MM.YYYY`.

ifdef::git-commit[]
A fenti dátumformátumok felismerésén túl a `--date` opció más,
emberközpontúbb dátumformátumokat is megpróbál értelmezni, például
relatív dátumokat, mint "yesterday" vagy "last Friday at noon".
endif::git-commit[]
