Döntéshozatali folyamat a Git projektben
========================================

[[_introduction]]
Bevezetés
---------
Ez a dokumentum a Git projekt jelenlegi döntéshozatali folyamatát írja
le. Ez inkább leíró, mint előíró dokumentum; azaz azt szeretnénk
leírni, hogyan működnek a dolgok a gyakorlatban, nem pedig kifejezetten
ajánlani valamely konkrét folyamatot vagy a jelenlegi folyamat
módosításait.

Itt azt dokumentáljuk, hogyan hoz döntéseket a projekt olyan
megbeszélésekhez (patchekkel vagy azok nélkül), amelyek egy önálló
patchsorozatnál nagyobb léptékűek (ez utóbbit teljes egészében lefedi a
SubmittingPatches dokumentum).


[[_larger_discussions_with_patches]]
Nagyobb megbeszélések (patchekkel)
----------------------------------
Ahogy egy önálló patchsorozatról szóló megbeszéléseknél, egy nagyobb
léptékű megbeszélés indítása gyakran egy patch vagy sorozat listára
küldésével kezdődik. Ez öltheti egy kezdeti tervdokumentum formáját,
amelyet a sorozat későbbi iterációiban követ a megvalósítás (például
link:https://lore.kernel.org/git/0169ce6fb9ccafc089b74ae406db0d1a8ff8ac65.1688165272.git.steadmon@google.com/[unit tesztek hozzáadása] vagy
link:https://lore.kernel.org/git/20200420235310.94493-1-emilyshaffer@google.com/[konfigurációalapú hookok]),
vagy tartalmazhat teljes megvalósítást a kezdetektől.
Mindkét esetben a megbeszélés ugyanúgy halad, mint egy önálló
patchsorozatnál, amíg konszenzus nem születik, vagy a témát el nem
ejtik.


[[_larger_discussions_without_patches]]
Nagyobb megbeszélések (patchek nélkül)
--------------------------------------
Időnként nagyobb megbeszélések fordulhatnak elő hozzájuk tartozó
patchsorozat nélkül. Ezek lehetnek nagyon nagy léptékű technikai
döntések, amelyek még egyetlen nagy patchsorozat hatókörét is
meghaladják, vagy lehetnek nyitottabb, irányelv-orientált megbeszélések
(példák:
link:https://lore.kernel.org/git/ZZ77NQkSuiRxRDwt@nand.local/[a Rust bevezetése]
vagy link:https://lore.kernel.org/git/YHofmWcIAidkvJiD@google.com/[a submodule UX javítása]).
Mindkét esetben a megbeszélés az általános patchsorozatoknál fent
leírtak szerint halad.

Patchsorozat vagy más konkrét megvalósítás nélküli nagyobb
megbeszéléseknél nehéz lehet megítélni, mikor született konszenzus,
mivel nincsenek hivatalos irányelvek. Ha a megbeszélés ezen a ponton
elakad, hasznos lehet egy RFC patchsorozattal (például egy részleges,
befejezetlen megvalósítással vagy proof of concepttel) újraindítani a
megbeszélést, amely könnyebben megvitatható.

Amikor konszenzus születik arról, hogy ez jó ötlet, az eredeti
javaslattevőtől elvárt, hogy koordinálja a megvalósításához szükséges
munkát, szükség szerint a megbeszélésben részt vett többiek
segítségével.

A kódmódosítást igénylő döntéseknél gyakran előfordul, hogy az eredeti
javaslattevő egy patchsorozattal folytatja, bár az is gyakori, hogy más
érdekelt felek biztosítják a megvalósítást (vagy a megvalósítás
részeit, nagyon nagy változtatásoknál).

A nem technikai döntéseknél, mint a közösségi normák vagy folyamatok, a
közösség egészén múlik a megállapodott változtatások megvalósítása és
fenntartása. A projekt vezetői bizottsága (PLC) segítheti az
irányelvdöntések megvalósítását.


[[_other_discussion_venues]]
Egyéb megbeszélési helyszínek
-----------------------------
Időnként döntési javaslatokat a listán kívül mutatnak be, pl. a
félrendszeres Contributors' Summiton. Bár a nagyobb sávszélességű,
személyes megbeszélés gyakran hasznos a résztvevők közötti gyors
konszenzus eléréséhez, általában elvárjuk, hogy a megbeszélést
jegyzetekben foglaljuk össze, amelyek később a listán bemutathatók.
Példaként lásd a
link:https://lore.kernel.org/git/AC2EB721-2979-43FD-922D-C5076A57F24B@jramsay.com.au/[Notes
from Git Contributor Summit, Los Angeles (April 5, 2020)] szálat James
Ramsaytől.

Azt szeretjük, ha a "hivatalos" megbeszélés a listán zajlik, hogy a
teljes közösségnek lehetősége legyen bekapcsolódni. Ez azt is jelenti,
hogy a levelezőlista archívumai többé-kevésbé teljes előzményét
tartalmazzák a projekt megbeszéléseinek és döntéseinek.
