// Please don't remove this comment as asciidoc behaves badly when
// the first non-empty line is ifdef/ifndef. The symptom is that
// without this comment the <git-diff-core> attribute conditionally
// defined below ends up being defined unconditionally.
// Last checked with asciidoc 7.0.2.

ifndef::git-format-patch[]
ifndef::git-diff[]
ifndef::git-log[]
:git-diff-core: 1
endif::git-log[]
endif::git-diff[]
endif::git-format-patch[]

ifdef::git-format-patch[]
`-p`::
`--no-stat`::
	Egyszerű patcheket generál diffstat nélkül.
endif::git-format-patch[]

ifndef::git-format-patch[]
`-p`::
`-u`::
`--patch`::
	Patchet generál (lásd <<generate_patch_text_with_p>>).
ifdef::git-diff[]
	Ez az alapértelmezett.
endif::git-diff[]

`-s`::
`--no-patch`::
	Elnyom minden kimenetet a diff gépezetből. Olyan parancsoknál
	hasznos, mint a `git show`, amely alapértelmezetten megjeleníti
	a patchet, ha el akarjuk némítani a kimenetét, vagy ha egy
	aliasban korábban megadott `--patch`, `--stat` opciók hatását
	akarjuk visszavonni a parancssorban.

endif::git-format-patch[]

ifdef::git-log[]
`-m`::
	Megjeleníti a merge commitok diffjeit az alapértelmezett
	formátumban. Ez hasonló a `--diff-merges=on` opcióhoz, azzal a
	különbséggel, hogy a `-m` nem hoz létre kimenetet, hacsak a
	`-p` is meg van adva.

`-c`::
	Kombinált diff kimenetet állít elő a merge commitokhoz.
	Rövidítés a `--diff-merges=combined -p` helyett.

`--cc`::
	Tömör kombinált diff kimenetet állít elő a merge commitokhoz.
	Rövidítés a `--diff-merges=dense-combined -p` helyett.

`--dd`::
	Az első szülőhöz viszonyított diffet állít elő mind a merge,
	mind a rendes commitokhoz.
	Rövidítés a `--diff-merges=first-parent -p` helyett.

`--remerge-diff`::
	Remerge-diff kimenetet állít elő a merge commitokhoz.
	Rövidítés a `--diff-merges=remerge -p` helyett.

`--no-diff-merges`::
	Szinonimája a `--diff-merges=off`-nak.

`--diff-merges=<format>`::
	Megadja a merge commitokhoz használandó diff-formátumot. Az
	alapértelmezett {diff-merges-default}, kivéve, ha a
	`--first-parent` van használatban, mert ekkor a `first-parent`
	az alapértelmezett.
+
A következő formátumok támogatottak:
+
--
`off`::
`none`::
	Kikapcsolja a merge commitok diffjeinek kimenetét. Hasznos egy
	beépített érték felülbírálásához.

`on`::
`m`::
	A merge commitok diff kimenetét az alapértelmezett formátumban
	jeleníti meg. Az alapértelmezett formátum a `log.diffMerges`
	konfigurációs változóval módosítható, amelynek alapértelmezett
	értéke `separate`.

`first-parent`::
`1`::
	Teljes diffet jelenít meg az első szülőhöz viszonyítva. Ez
	ugyanaz a formátum, amit a `--patch` állít elő nem-merge
	commitoknál.

`separate`::
	Teljes diffet jelenít meg az egyes szülőkhöz viszonyítva.
	Minden szülőhöz külön log-bejegyzés és diff generálódik.

`combined`::
`c`::
	Egyidejűleg mutatja az egyes szülők és a merge eredménye
	közötti különbségeket, ahelyett hogy páronként, egyszerre
	egy szülő és az eredmény közötti diffet mutatná. Emellett
	csak azokat a fájlokat listázza, amelyek minden szülőhöz
	képest módosultak.

`dense-combined`::
`cc`::
	Tovább tömöríti a `--diff-merges=combined` által előállított
	kimenetet azáltal, hogy elhagyja azokat az érdektelen
	hunkokat, amelyek tartalma a szülőkben csak két változatban
	létezik, és a merge eredménye módosítás nélkül választja ki
	az egyiket.

`remerge`::
`r`:: Újra merge-eli a kétszülős merge commitokat, hogy egy
	ideiglenes tree objektumot hozzon létre -- amely esetleg
	konfliktusjelölőket és hasonlókat tartalmazó fájlokat
	tartalmaz. Ezután megjelenik egy diff ez között az ideiglenes
	tree és a tényleges merge commit között.
--
+
Az ennél az opciónál kiadott kimenet változhat, ahogyan más
opciókkal való kölcsönhatása is (hacsak az kifejezetten nincs
dokumentálva).


`--combined-all-paths`::
	Azt eredményezi, hogy a kombinált diffek (amelyeket a merge
	commitoknál használ) az összes szülőből listázzák a fájl nevét.
	Ez tehát csak akkor hat, ha a `--diff-merges=[dense-]combined`
	van használatban, és valószínűleg csak akkor hasznos, ha
	fájlnév-változásokat észlel (azaz ha vagy átnevezés-, vagy
	másolásészlelés kérve lett).
endif::git-log[]

`-U<n>`::
`--unified=<n>`::
	Diffeket generál _<n>_ sornyi kontextussal. A kontextussorok
	száma alapértelmezetten a `diff.context` értéke, vagy 3, ha a
	konfigurációs változó nincs beállítva. (A `<n>` nélküli `-U`-t
	egy történelmi véletlen miatt csendben elfogadja a `-p`
	szinonimájaként.)
ifndef::git-format-patch[]
	A `--patch`-et vonja maga után.
endif::git-format-patch[]

`--output=<file>`::
	A szabványos kimenet helyett egy megadott fájlba ír.

`--output-indicator-new=<char>`::
`--output-indicator-old=<char>`::
`--output-indicator-context=<char>`::
	Megadja a generált patchben az új, régi vagy kontextussorok
	jelölésére használt karaktert. Alapesetben ezek rendre `+`,
	`-` és ' '.

ifndef::git-format-patch[]
`--raw`::
ifndef::git-log[]
	A diffet raw formátumban generálja.
ifdef::git-diff-core[]
	Ez az alapértelmezett.
endif::git-diff-core[]
endif::git-log[]
ifdef::git-log[]
	Minden commithoz megjelenít egy változás-összefoglalót a raw
	diff formátum használatával. Lásd a linkgit:git-diff[1] "RAW
	OUTPUT FORMAT" szekcióját. Ez különbözik magának a lognak raw
	formátumban való megjelenítésétől, amit a `--format=raw`
	opcióval érhet el.
endif::git-log[]
endif::git-format-patch[]

ifndef::git-format-patch[]
`--patch-with-raw`::
	Szinonimája a `-p --raw`-nak.
endif::git-format-patch[]

ifdef::git-log[]
`-t`::
	Megjeleníti a tree objektumokat a diff kimenetben.
endif::git-log[]

`--indent-heuristic`::
	Bekapcsolja azt a heurisztikát, amely eltolja a diff-hunkok
	határait, hogy a patchek könnyebben olvashatók legyenek. Ez az
	alapértelmezett.

`--no-indent-heuristic`::
	Kikapcsolja az indent-heurisztikát.

`--minimal`::
	Extra időt fordít annak biztosítására, hogy a lehető
	legkisebb diff jöjjön létre.

`--patience`::
	Diffet generál a "patience diff" algoritmus használatával.

`--histogram`::
	Diffet generál a "histogram diff" algoritmus használatával.

`--anchored=<text>`::
	Diffet generál az "anchored diff" algoritmus használatával.
+
Ez az opció többször is megadható.
+
Ha egy sor létezik mind a forrásban, mind a célban, csak egyszer
fordul elő, és _<text>_-tel kezdődik, ez az algoritmus megpróbálja
megakadályozni, hogy törlésként vagy hozzáadásként jelenjen meg a
kimenetben. Belsőleg a "patience diff" algoritmust használja.

include::diff-algorithm-option.adoc[]

`--stat[=<width>[,<name-width>[,<count>]]]`::
	Diffstatot generál. Alapértelmezetten a fájlnév-rész annyi
	helyet kap, amennyi szükséges, a többi pedig a grafikon-részé
	lesz. A maximális szélesség alapértelmezetten a terminál
	szélessége, vagy 80 oszlop, ha nincs terminálhoz csatlakoztatva,
	és felülbírálható _<width>_-tel. A fájlnév-rész szélessége egy
	vessző utáni másik _<name-width>_ szélesség megadásával, vagy a
	`diff.statNameWidth=<name-width>` beállításával korlátozható. A
	grafikon-rész szélessége a `--stat-graph-width=<graph-width>`
	használatával, vagy a `diff.statGraphWidth=<graph-width>`
	beállításával korlátozható. A `--stat` vagy a
	`--stat-graph-width` használata minden stat-grafikont generáló
	parancsot érint, míg a `diff.statNameWidth` vagy a
	`diff.statGraphWidth` beállítása nem érinti a `git format-patch`-et.
	Egy harmadik, _<count>_ paraméter megadásával az első
	_<count>_ sorra korlátozhatja a kimenetet, amit `...` követ,
	ha még több van.
+
Ezek a paraméterek egyenként is beállíthatók a `--stat-width=<width>`,
a `--stat-name-width=<name-width>` és a `--stat-count=<count>` opciókkal.

`--compact-summary`::
	A diffstatban egy tömörített összefoglalót ad ki a kiterjesztett
	fejlécinformációkról, mint például a fájlok létrehozása vagy
	törlése ("new" vagy "gone", opcionálisan `+l`, ha symlinkről van
	szó) és a módváltozások (`+x` vagy `-x` a végrehajtható bit
	hozzáadásához, illetve eltávolításához). Az információ a
	fájlnév-rész és a grafikon-rész közé kerül. A `--stat`-ot vonja
	maga után.

`--numstat`::
	Hasonló a `--stat`-hoz, de decimális jelöléssel mutatja a
	hozzáadott és törölt sorok számát, valamint rövidítés nélküli
	elérési utat, hogy gépi feldolgozásra alkalmasabb legyen. Bináris
	fájloknál `0 0` helyett két `-`-t ír ki.

`--shortstat`::
	Csak a `--stat` formátum utolsó sorát adja ki, amely tartalmazza
	a módosított fájlok teljes számát, valamint a hozzáadott és
	törölt sorok számát.

`-X [<param>,...]`::
`--dirstat[=<param>,...]`::
	Megjeleníti az egyes alkönyvtárakra eső változások relatív
	mennyiségének eloszlását. A `--dirstat` viselkedése vesszővel
	elválasztott paraméterlista átadásával testre szabható.
	Az alapértelmezéseket a `diff.dirstat` konfigurációs változó
	vezérli (lásd linkgit:git-config[1]).
	A következő paraméterek érhetők el:
+
--
`changes`;;
	A dirstat-számokat a forrásból eltávolított, illetve a célba
	hozzáadott sorok megszámlálásával számítja ki. Ez figyelmen
	kívül hagyja a fájlon belüli tiszta kódmozgatások mennyiségét.
	Más szóval a sorok egy fájlon belüli átrendezése nem számít
	annyira, mint más változások. Ez az alapértelmezett viselkedés,
	ha nincs paraméter megadva.
`lines`;;
	A dirstat-számokat a szokásos sor alapú diff-elemzéssel
	számítja ki, összegezve az eltávolított/hozzáadott sorok
	számát. (Bináris fájloknál 64 bájtos darabokat számol
	helyette, mivel a bináris fájloknak nincs természetes
	sor-fogalmuk.) Ez a `--dirstat` egy drágább viselkedése, mint
	a `changes`, viszont a fájlon belüli átrendezett sorokat is
	annyira számítja, mint más változásokat. Az eredményül kapott
	kimenet konzisztens azzal, amit a többi `--*stat` opciótól kap.
`files`;;
	A dirstat-számokat a megváltozott fájlok számának
	megszámlálásával számítja ki. A dirstat-elemzésben minden
	megváltozott fájl egyformán számít. Ez a számításilag
	legolcsóbb `--dirstat` viselkedés, mivel egyáltalán nem kell
	megnéznie a fájlok tartalmát.
`cumulative`;;
	A gyermekkönyvtárban lévő változásokat a szülőkönyvtárnál is
	számolja. Vegye figyelembe, hogy a `cumulative` használatakor
	a jelentett százalékok összege meghaladhatja a 100%-ot. Az
	alapértelmezett (nem kumulatív) viselkedés a `noncumulative`
	paraméterrel adható meg.
_<limit>_;;
	Egy egész szám paraméter megad egy levágási százalékot
	(alapértelmezetten 3%). Azok a könyvtárak, amelyek ennél
	kisebb arányban járulnak hozzá a változásokhoz, nem jelennek
	meg a kimenetben.
--
+
Példa: a következő megszámlálja a megváltozott fájlokat, közben
figyelmen kívül hagyva azokat a könyvtárakat, amelyek a
megváltozott fájlok teljes mennyiségének kevesebb mint 10%-át
adják, és összesítve a gyermekkönyvtárak számait a
szülőkönyvtáraknál: `--dirstat=files,10,cumulative`.

`--cumulative`::
	Szinonimája a `--dirstat=cumulative`-nak.

`--dirstat-by-file[=<param>,...]`::
	Szinonimája a `--dirstat=files,<param>,...`-nak.

`--summary`::
	Egy tömörített összefoglalót ad ki a kiterjesztett
	fejlécinformációkról, mint például a létrehozások, átnevezések
	és módváltozások.

ifndef::git-format-patch[]
`--patch-with-stat`::
	Szinonimája a `-p --stat`-nak.
endif::git-format-patch[]

ifndef::git-format-patch[]

`-z`::
ifdef::git-log[]
	A commitokat __NUL__-okkal választja el újsorok helyett.
+
Emellett, ha a `--raw` vagy a `--numstat` meg van adva, nem
csonkítja az elérési utakat, és __NUL__-okat használ kimeneti mező
elválasztóként.
endif::git-log[]
ifndef::git-log[]
	Ha a `--raw`, a `--numstat`, a `--name-only` vagy a
	`--name-status` meg van adva, nem csonkítja az elérési
	utakat, és NUL-okat használ kimeneti mező elválasztóként.
endif::git-log[]
+
Ezen opció nélkül a "szokatlan" karaktereket tartalmazó elérési
utak idézőjelbe kerülnek, ahogyan azt a `core.quotePath`
konfigurációs változó leírja (lásd linkgit:git-config[1]).

`--name-only`::
	Csak az egyes megváltozott fájlok nevét jeleníti meg a
	post-image tree-ben. A fájlnevek gyakran UTF-8-ban vannak
	kódolva. További információért lásd a kódolásról szóló
	tárgyalást a linkgit:git-log[1] man page-ben.

`--name-status`::
	Csak az egyes megváltozott fájlok nevét (neveit) és állapotát
	jeleníti meg. Lásd a `--diff-filter` opció leírását arról,
	hogy mit jelentenek az állapotbetűk. A `--name-only`-hoz
	hasonlóan a fájlnevek gyakran UTF-8-ban vannak kódolva.

`--submodule[=<format>]`::
	Megadja, hogyan jelenjenek meg a submodule-okban lévő
	különbségek. A `--submodule=short` megadásakor a `short`
	formátum kerül használatra. Ez a formátum csak a tartomány
	elején és végén lévő commitok neveit mutatja. Ha a
	`--submodule` vagy a `--submodule=log` van megadva, a `log`
	formátum kerül használatra. Ez a formátum úgy listázza a
	tartományban lévő commitokat, ahogyan a linkgit:git-submodule[1]
	`summary` parancsa teszi. Ha a `--submodule=diff` van megadva,
	a `diff` formátum kerül használatra. Ez a formátum egy
	beágyazott diffet mutat a submodule tartalmának a commit
	tartományon belüli változásairól. Alapértelmezetten a
	`diff.submodule` értékét, vagy a `short` formátumot használja,
	ha a konfigurációs opció nincs beállítva.

`--color[=<when>]`::
	Színes diffet jelenít meg.
	A `--color` (azaz `=<when>` nélkül) ugyanaz, mint a
	`--color=always`. _<when>_ értéke lehet `always`, `never`
	vagy `auto`.
ifdef::git-diff[]
	A `color.ui` és a `color.diff` konfigurációs beállításokkal
	módosítható.
endif::git-diff[]

`--no-color`::
	Kikapcsolja a színes diffet.
ifdef::git-diff[]
	Ez a konfigurációs beállítások felülbírálására használható.
endif::git-diff[]
	Ugyanaz, mint a `--color=never`.

`--color-moved[=<mode>]`::
	Az áthelyezett kódsorok eltérő színnel jelennek meg.
ifdef::git-diff[]
	A `diff.colorMoved` konfigurációs beállítással módosítható.
endif::git-diff[]
	A _<mode>_ alapértelmezetten `no`, ha az opció nincs megadva,
	és `zebra`, ha az opció mód nélkül van megadva. A mód a
	következők egyike lehet:
+
--
`no`::
	Az áthelyezett sorok nincsenek kiemelve.
`default`::
	A `zebra` szinonimája. Ez a jövőben egy ésszerűbb módra
	változhat.
`plain`::
	Bármely sor, amely egy helyen hozzáadásra, egy másik helyen
	pedig eltávolításra került, a `color.diff.newMoved` színnel
	jelenik meg. Hasonlóképp a `color.diff.oldMoved` kerül
	felhasználásra azoknál az eltávolított soroknál, amelyek a
	diff egy másik helyén hozzáadásra kerültek. Ez a mód minden
	áthelyezett sort felismer, de egy review során nem túl
	hasznos annak megállapítására, hogy egy kódblokk permutáció
	nélkül lett-e áthelyezve.
`blocks`::
	Legalább 20 alfanumerikus karakterből álló, áthelyezett
	szövegblokkokat mohó módon ismeri fel. A felismert blokkok a
	`color.diff.(old|new)Moved` színek egyikével jelennek meg.
	A szomszédos blokkok nem különböztethetők meg egymástól.
`zebra`::
	Az áthelyezett szövegblokkokat ugyanúgy ismeri fel, mint a
	`blocks` mód. A blokkok a `color.diff.(old|new)Moved` vagy a
	`color.diff.(old|new)MovedAlternative` szín egyikével jelennek
	meg. A két szín közötti váltás jelzi, hogy egy új blokkot
	észlelt.
`dimmed-zebra`::
	Hasonló a `zebra`-hoz, de emellett elhalványítja az
	áthelyezett kód érdektelen részeit is. A két szomszédos blokk
	határoló sorai érdekesnek számítanak, a többi érdektelennek.
	A `dimmed_zebra` egy elavult szinonima.
--

`--no-color-moved`::
	Kikapcsolja az áthelyezés-észlelést. Ez a konfigurációs
	beállítások felülbírálására használható. Ugyanaz, mint a
	`--color-moved=no`.

`--color-moved-ws=<mode>,...`::
	Ez megadja, hogyan legyen figyelmen kívül hagyva a whitespace
	a `--color-moved` áthelyezés-észlelésének végrehajtásakor.
ifdef::git-diff[]
	A `diff.colorMovedWS` konfigurációs beállítással állítható be.
endif::git-diff[]
	Ezek a módok vesszővel elválasztott listaként adhatók meg:
+
--
`no`::
	Az áthelyezés-észlelés végrehajtásakor nem hagyja figyelmen
	kívül a whitespace-t.
`ignore-space-at-eol`::
	Figyelmen kívül hagyja a sor végi whitespace változásait.
`ignore-space-change`::
	Figyelmen kívül hagyja a whitespace mennyiségének
	változásait. Ez figyelmen kívül hagyja a sor végi
	whitespace-t, és a whitespace-karakterek minden egy vagy több
	elemből álló sorozatát egyenértékűnek tekinti.
`ignore-all-space`::
	Figyelmen kívül hagyja a whitespace-t a sorok
	összehasonlításakor. Ez akkor is figyelmen kívül hagyja a
	különbségeket, ha az egyik sorban van whitespace ott, ahol a
	másikban nincs.
`allow-indentation-change`::
	Kezdetben figyelmen kívül hagy minden whitespace-t az
	áthelyezés-észlelésben, majd az áthelyezett kódblokkokat csak
	akkor csoportosítja egy blokkba, ha a whitespace-változás
	soronként azonos. Ez összeegyeztethetetlen a többi móddal.
--

`--no-color-moved-ws`::
	Az áthelyezés-észlelés végrehajtásakor nem hagyja figyelmen
	kívül a whitespace-t. Ez a konfigurációs beállítások
	felülbírálására használható. Ugyanaz, mint a
	`--color-moved-ws=no`.

`--word-diff[=<mode>]`::
	Alapértelmezetten a szavakat whitespace határolja; lásd
	lentebb a `--word-diff-regex`-et. A _<mode>_ alapértelmezetten
	`plain`, és a következők egyike lehet:
+
--
`color`::
	Csak színekkel emeli ki a megváltozott szavakat. A `--color`-t
	vonja maga után.
`plain`::
	A szavakat ++[-removed-]++ és ++{+added+}++ formában
	mutatja. Nem próbálja meg escapelni a határolókat, ha azok
	megjelennek a bemenetben, így a kimenet félreérthető lehet.
`porcelain`::
	Egy szkriptfeldolgozásra szánt, speciális, sor alapú
	formátumot használ. A hozzáadott/eltávolított/változatlan
	szakaszok a szokásos unified diff formátumban kerülnek
	kiírásra, a sor elején egy `+`/`-`/` ` karakterrel kezdve,
	és a sor végéig tartva. A bemenetben lévő újsorokat egy
	önálló soron álló tilde (`~`) jelöli.
`none`::
	Ismét kikapcsolja a word diffet.
--
+
Vegye figyelembe, hogy az első mód neve ellenére a színeket
minden módban a megváltozott részek kiemelésére használja, ha
be van kapcsolva.
+
A `--word-diff` opció úgy működik, hogy ugyanazt a soronkénti
diffet veszi, amit az opció nélkül állítana elő, és
szavankénti változásokat számít az egyes hunkokon belül. Ez
nagyobb diffet eredményezhet, mint amit egy dedikált
word-diff-eszköz produkálna. Ha a Git a jövőben egy másik
implementációt vezet be, a kimenet változhat. Vegye figyelembe,
hogy ez hasonló a `--diff-algorithm` opcióhoz, amely szintén
megváltoztathatja a kimenetet.

`--word-diff-regex=<regex>`::
	A _<regex>_ segítségével dönti el, mi számít szónak, ahelyett
	hogy a nem-whitespace karakterek sorozatait tekintené szónak.
	Emellett a `--word-diff`-et is maga után vonja, hacsak az még
	nem volt bekapcsolva.
+
A _<regex>_ minden nem átfedő találata egy szónak számít. Bármi,
ami e találatok között van, whitespace-nek számít, és figyelmen
kívül marad(!) a különbségek keresése szempontjából. Érdemes
lehet a `|[^[:space:]]`-t hozzáfűzni a reguláris kifejezéshez,
hogy biztosan illeszkedjen minden nem-whitespace karakterre. Egy
újsort tartalmazó találat csendben csonkolásra kerül(!) az
újsornál.
+
Például a `--word-diff-regex=.` minden karaktert szónak fog
kezelni, és ennek megfelelően karakterenként mutatja a
különbségeket.
+
A regex diff driveren vagy konfigurációs opción keresztül is
beállítható, lásd linkgit:gitattributes[5] vagy
linkgit:git-config[1]. Explicit megadása felülbírál minden diff
drivert vagy konfigurációs beállítást. A diff driverek
felülbírálják a konfigurációs beállításokat.

`--color-words[=<regex>]`::
	Egyenértékű a `--word-diff=color`-ral, plusz (ha meg lett adva
	egy regex) a `--word-diff-regex=<regex>`-szel.
endif::git-format-patch[]

`--no-renames`::
	Kikapcsolja az átnevezés-észlelést, még akkor is, ha a
	konfigurációs fájl ezt adja alapértelmezésként.

`--rename-empty`::
`--no-rename-empty`::
	Hogy üres blobokat használjon-e átnevezés forrásaként.

ifndef::git-format-patch[]
`--check`::
	Figyelmeztet, ha a változtatások konfliktusjelölőket vagy
	whitespace-hibákat vezetnek be. Hogy mi számít
	whitespace-hibának, azt a `core.whitespace` konfiguráció
	vezérli. Alapértelmezetten a sorvégi whitespace (beleértve a
	kizárólag whitespace-ből álló sorokat is) és a sor kezdő
	behúzásán belül közvetlenül tab karakter által követett
	szóköz karakter számít whitespace-hibának. Ha problémákat
	talál, nem nulla állapotkóddal lép ki. Nem kompatibilis a
	`--exit-code`-dal.

`--ws-error-highlight=<kind>`::
	Kiemeli a whitespace-hibákat a diff `context`, `old` vagy
	`new` soraiban. Több érték vesszővel választható el, a `none`
	visszaállítja az előző értékeket, a `default` a listát
	`new`-ra állítja vissza, az `all` pedig az `old,new,context`
	rövidítése. Ha ez az opció nincs megadva, és a
	`diff.wsErrorHighlight` konfigurációs változó sincs
	beállítva, csak a `new` sorokban lévő whitespace-hibák
	kerülnek kiemelésre. A whitespace-hibák a `color.diff.whitespace`
	színnel jelennek meg.

endif::git-format-patch[]

`--full-index`::
	Az első néhány karakter helyett a teljes pre- és post-image
	blob objektumneveket jeleníti meg az "index" sorban patch
	formátumú kimenet generálásakor.

`--binary`::
	A `--full-index` mellett egy bináris diffet is kiad, amely a
	`git-apply`-jal alkalmazható.
ifndef::git-format-patch[]
	A `--patch`-et vonja maga után.
endif::git-format-patch[]

`--abbrev[=<n>]`::
	A diff-raw formátumú kimenetben és a diff-tree fejlécsorokban
	a teljes 40 bájtos hexadecimális objektumnév helyett a
	legrövidebb, legalább _<n>_ hexajegy hosszú prefixet
	jeleníti meg, amely egyértelműen az objektumra hivatkozik. A
	diff-patch kimeneti formátumban a `--full-index` élvez
	elsőbbséget, azaz ha a `--full-index` meg van adva, a teljes
	blob nevek jelennek meg, függetlenül az `--abbrev`-től. Az
	alapértelmezettől eltérő számú számjegy a `--abbrev=<n>`-nel
	adható meg.

`-B[<n>][/<m>]`::
`--break-rewrites[=[<n>][/<m>]]`::
	A teljes újraírásnak számító változtatásokat törlés-létrehozás
	párokra bontja. Ez két célt szolgál:
+
Befolyásolja, hogy egy fájl teljes újraírásának számító
változtatás ne törlések és beszúrások olyan sorozataként jelenjen
meg, amelybe néhány, kontextusként szövegszerűen egyező sor is
keveredik, hanem az összes régi egyetlen törléseként, amelyet az
összes új egyetlen beszúrása követ; ezt az aspektusát a `-B`
opciónak az _<m>_ szám vezérli (alapértelmezetten 60%). A
`-B/70%` azt jelenti, hogy az eredeti tartalom kevesebb mint
30%-ának kell megmaradnia az eredményben ahhoz, hogy a Git teljes
újraírásnak tekintse (azaz ellenkező esetben a kapott patch
törlések és beszúrások kontextussorokkal kevert sorozata lesz).
+
A `-M`-mel együtt használva egy teljesen újraírt fájl is egy
átnevezés forrásának számít (a `-M` rendszerint csak egy eltűnt
fájlt tekint egy átnevezés forrásának), és ezt az aspektusát a
`-B` opciónak az _<n>_ szám vezérli (alapértelmezetten 50%). A
`-B20%` azt jelenti, hogy egy olyan változtatás, amelynek
hozzáadása és törlése a fájl méretének 20%-át vagy annál többet
tesz ki, jogosult arra, hogy egy másik fájlba történő átnevezés
lehetséges forrásaként vegyék figyelembe.

`-M[<n>]`::
`--find-renames[=<n>]`::
ifndef::git-log[]
	Átnevezéseket észlel.
endif::git-log[]
ifdef::git-log[]
	Diffek generálásakor minden commithoz észleli és jelenti az
	átnevezéseket. A fájlok átnevezéseken átívelő követéséhez a
	history bejárása közben lásd a `--follow`-t.
endif::git-log[]
	Ha _<n>_ meg van adva, az a hasonlósági index küszöbértéke
	(azaz a hozzáadás/törlés mennyisége a fájl méretéhez
	viszonyítva). Például a `-M90%` azt jelenti, hogy a Gitnek
	egy törlés/hozzáadás párt átnevezésnek kell tekintenie, ha a
	fájl több mint 90%-a nem változott. `%` jel nélkül a szám
	törtként értelmezendő, elé képzelt tizedesponttal. Azaz a
	`-M5` 0,5-öt jelent, és így ugyanaz, mint a `-M50%`. Hasonlóan
	a `-M05` ugyanaz, mint a `-M5%`. Az észlelés pontos
	átnevezésekre korlátozásához használja a `-M100%`-ot. Az
	alapértelmezett hasonlósági index 50%.

`-C[<n>]`::
`--find-copies[=<n>]`::
	Az átnevezések mellett a másolásokat is észleli. Lásd még a
	`--find-copies-harder`-t. Ha _<n>_ meg van adva, ugyanaz a
	jelentése, mint a `-M<n>` esetében.

`--find-copies-harder`::
	Teljesítményi okokból a `-C` opció alapértelmezetten csak
	akkor talál másolatokat, ha a másolat eredeti fájlja
	ugyanabban a changesetben módosult. Ez a kapcsoló arra
	kényszeríti a parancsot, hogy a nem módosított fájlokat is
	megvizsgálja a másolás forrásának lehetséges jelöltjeként.
	Ez egy nagyon drága művelet nagy projekteknél, ezért
	óvatosan használja. Egynél több `-C` opció megadásának
	ugyanaz a hatása.

`-D`::
`--irreversible-delete`::
	Elhagyja a preimage-et a törléseknél, azaz csak a fejlécet
	írja ki, a preimage és a `/dev/null` közötti diffet nem. Az
	eredményül kapott patch nem a `patch`-csel vagy a `git
	apply`-jal való alkalmazásra szánt; ez kizárólag azoknak
	szól, akik csak a változtatás utáni szöveg átnézésére akarnak
	koncentrálni. Emellett a kimenetből nyilvánvalóan hiányzik
	elegendő információ ahhoz, hogy egy ilyen patchet fordítva,
	akár kézzel is alkalmazni lehessen, innen az opció neve.
+
A `-B`-vel együtt használva a delete/create pár törlési
részében is elhagyja a preimage-et.

`-l<num>`::
	A `-M` és a `-C` opciók néhány előzetes lépést tartalmaznak,
	amelyek olcsón képesek az átnevezések/másolások egy részhalmazát
	észlelni, amit egy kimerítő tartalék rész követ, amely az
	összes megmaradt párosítatlan célt az összes releváns
	forráshoz hasonlítja. (Átnevezéseknél csak a megmaradt
	párosítatlan források relevánsak; másolásoknál minden eredeti
	forrás releváns.) N forrás és cél esetén ez a kimerítő
	ellenőrzés O(N^2). Ez az opció megakadályozza, hogy az
	átnevezés-/másolásészlelés kimerítő része lefusson, ha az
	érintett forrás-/célfájlok száma meghaladja a megadott
	számot. Alapértelmezetten a `diff.renameLimit` értékét
	használja. Vegye figyelembe, hogy a 0 érték korlátlanként
	kezelendő.

ifndef::git-format-patch[]
`--diff-filter=[(A|C|D|M|R|T|U|X|B)...[*]]`::
	Csak azokat a fájlokat választja ki, amelyek Hozzáadva
	(`A`), Másolva (`C`), Törölve (`D`), Módosítva (`M`),
	Átnevezve (`R`) lettek, amelyeknek a típusa (azaz rendes
	fájl, symlink, submodule, ...) megváltozott (`T`), amelyek
	Nem Merge-eltek (`U`) vagy Ismeretlenek (`X`), vagy amelyeknek
	a párosítása Megszakadt (`B`). A szűrőkarakterek bármilyen
	kombinációja használható (a nulla kombinációt is beleértve).
	Ha a kombinációhoz hozzáadja a `*`-ot (mind-vagy-semmi), az
	összes elérési út kiválasztásra kerül, ha van olyan fájl,
	amely megfelel az összehasonlítás más kritériumainak; ha
	nincs ilyen fájl, semmi sem kerül kiválasztásra.
+
Emellett ezek a nagybetűk kisbetűsre alakíthatók a kizáráshoz.
Pl. a `--diff-filter=ad` kizárja a hozzáadott és törölt elérési
utakat.
+
Vegye figyelembe, hogy nem minden diff tartalmazhat minden
típust. Például a másolt és átnevezett bejegyzések nem jelenhetnek
meg, ha az adott típusok észlelése ki van kapcsolva.

`-S<string>`::
	Olyan különbségeket keres, amelyek megváltoztatják a megadott
	_<string>_ előfordulásainak számát (azaz hozzáadás/törlés)
	egy fájlban. Szkriptelésre szánt funkció.
+
Akkor hasznos, ha egy pontos kódblokkot (például egy structot)
keres, és tudni szeretné annak history-ját attól kezdve, hogy
először létrejött: használja a funkciót iteratívan úgy, hogy a
preimage-ben lévő érdekes blokkot visszaadja a `-S`-nek, és
folytassa mindaddig, amíg meg nem kapja a blokk legelső
verzióját.
+
A bináris fájlok is átkeresésre kerülnek.

`-G<regex>`::
	Olyan különbségeket keres, amelyek patch szövege az
	_<regex>_-re illeszkedő hozzáadott/eltávolított sorokat
	tartalmaz.
+
A `-S<regex>` `--pickaxe-regex` és a `-G<regex>` közötti
különbség szemléltetéséhez tekintsen egy commitot, amelynek a
következő diffje van ugyanabban a fájlban:
+
----
+    return frotz(nitfol, two->ptr, 1, 0);
...
-    hit = frotz(nitfol, mf2.ptr, 1, 0);
----
+
Míg a `git log -G"frotz\(nitfol"` megmutatja ezt a commitot, a
`git log -S"frotz\(nitfol" --pickaxe-regex` nem (mivel az adott
string előfordulásainak száma nem változott).
+
Hacsak a `--text` nincs megadva, a textconv filter nélküli
bináris fájlok patchei figyelmen kívül maradnak.
+
További információért lásd a linkgit:gitdiffcore[7]-ben a
'pickaxe' bejegyzést.

`--find-object=<object-id>`::
	Olyan különbségeket keres, amelyek megváltoztatják a megadott
	objektum előfordulásainak számát. Hasonló a `-S`-hez, csak az
	argumentum más abban, hogy nem egy konkrét stringet, hanem
	egy konkrét objektum-id-t keres.
+
Az objektum lehet blob vagy submodule commit. Ez maga után
vonja a `-t` opciót a `git-log`-ban, hogy a tree-ket is
megtalálja.

`--pickaxe-all`::
	Ha a `-S` vagy a `-G` egy változást talál, megjeleníti az
	adott changeset összes változását, nem csak azokat a
	fájlokat, amelyek tartalmazzák a _<string>_-ben lévő
	változást.

`--pickaxe-regex`::
	A `-S`-nek átadott _<string>_-et kiterjesztett POSIX
	reguláris kifejezésként kezeli az illesztéshez.

endif::git-format-patch[]

`-O<orderfile>`::
	Szabályozza, hogy a fájlok milyen sorrendben jelenjenek meg a
	kimenetben. Ez felülbírálja a `diff.orderFile` konfigurációs
	változót (lásd linkgit:git-config[1]). A `diff.orderFile`
	törléséhez használja a `-O/dev/null`-t.
+
A kimeneti sorrendet az _<orderfile>_-ban lévő glob minták
sorrendje határozza meg. Először azok a fájlok kerülnek
kiírásra, amelyek elérési útja az első mintára illeszkedik, majd
azok, amelyek a második mintára illeszkednek (de az elsőre nem),
és így tovább. Azok a fájlok, amelyek elérési útja egyetlen
mintára sem illeszkedik, utoljára kerülnek kiírásra, mintha a
fájl végén egy hallgatólagos, mindenre illeszkedő minta lenne.
Ha több elérési útnak azonos a rangja (ugyanarra a mintára
illeszkednek, korábbi mintára nem), az egymáshoz viszonyított
kiírási sorrendjük a normál sorrend.
+
Az _<orderfile>_ értelmezése a következő:
+
--
 - Az üres sorok figyelmen kívül maradnak, így olvashatóság
   céljából elválasztóként használhatók.

 - A kettőskereszttel ("`#`") kezdődő sorok figyelmen kívül
   maradnak, így megjegyzésekre használhatók. Tegyen egy
   backslash-t ("`\`") a minta elejére, ha az kettőskereszttel
   kezdődik.

 - Minden más sor egyetlen mintát tartalmaz.
--
+
A minták szintaxisa és szemantikája ugyanaz, mint az
`FNM_PATHNAME` jelző nélküli `fnmatch`(3) által használt
mintáké, azzal a kivétellel, hogy egy elérési út akkor is
illeszkedik egy mintára, ha az utolsó néhány elérésiút-komponens
elhagyása illeszkedést eredményez. Például a "`foo*bar`" minta
illeszkedik a "`fooasdfbar`"-ra és a "`foo/bar/baz/asdf`"-ra, de
a "`foobarx`"-re nem.

`--skip-to=<file>`::
`--rotate-to=<file>`::
	Eldobja a kimenetből a megnevezett _<file>_ előtti fájlokat
	(azaz 'skip to'), vagy a kimenet végére mozgatja őket (azaz
	'rotate to'). Ezeket az opciókat elsősorban a `git difftool`
	parancs használatához találták ki, és máshol nem feltétlenül
	túl hasznosak.

ifndef::git-format-patch[]
`-R`::
	Felcseréli a két bemenetet; azaz megjeleníti a
	különbségeket az indexből vagy a lemezen lévő fájlból a
	tree tartalmához képest.
endif::git-format-patch[]

`--relative[=<path>]`::
`--no-relative`::
	Ha a projekt egy alkönyvtárából fut, ezzel az opcióval
	megadható neki, hogy zárja ki a könyvtáron kívüli
	változtatásokat, és az elérési utakat ahhoz viszonyítva
	jelenítse meg. Ha nincs egy alkönyvtárban (pl. egy bare
	repositoryban), megadhatja, hogy a kimenetet melyik
	alkönyvtárhoz viszonyítsa, egy _<path>_ argumentum
	megadásával. A `--no-relative` mind a `diff.relative`
	konfigurációs opció, mind egy korábbi `--relative`
	érvénytelenítésére használható.

`-a`::
`--text`::
	Minden fájlt szövegként kezel.

`--ignore-cr-at-eol`::
	Összehasonlításkor figyelmen kívül hagyja a sor végi
	kocsivissza-karaktert.

`--ignore-space-at-eol`::
	Figyelmen kívül hagyja a sor végi whitespace változásait.

`-b`::
`--ignore-space-change`::
	Figyelmen kívül hagyja a whitespace mennyiségének
	változásait. Ez figyelmen kívül hagyja a sor végi
	whitespace-t, és a whitespace-karakterek minden egy vagy több
	elemből álló sorozatát egyenértékűnek tekinti.

`-w`::
`--ignore-all-space`::
	Figyelmen kívül hagyja a whitespace-t a sorok
	összehasonlításakor. Ez akkor is figyelmen kívül hagyja a
	különbségeket, ha az egyik sorban van whitespace ott, ahol a
	másikban nincs.

`--ignore-blank-lines`::
	Figyelmen kívül hagyja azokat a változtatásokat, amelyek
	sorai mind üresek.


`-I<regex>`::
`--ignore-matching-lines=<regex>`::
	Figyelmen kívül hagyja azokat a változtatásokat, amelyek
	minden sora illeszkedik az _<regex>_-re. Ez az opció
	többször is megadható.

`--inter-hunk-context=<number>`::
	Megjeleníti a diff-hunkok közötti kontextust, legfeljebb a
	megadott _<number>_ sorig, ezzel egybeolvasztva az egymáshoz
	közeli hunkokat. Alapértelmezetten a `diff.interHunkContext`
	értékét, vagy 0-t használ, ha a konfigurációs opció nincs
	beállítva.

`-W`::
`--function-context`::
	A teljes függvényt megjeleníti kontextussorként minden egyes
	változtatáshoz. A függvényneveket ugyanúgy határozza meg, mint
	ahogyan a `git diff` kidolgozza a patch-hunk fejléceit (lásd
	"Defining a custom hunk-header" a linkgit:gitattributes[5]-ben).

ifndef::git-format-patch[]
ifndef::git-log[]
`--exit-code`::
	A programot a `diff`(1)-hez hasonló kilépőkódokkal lépteti
	ki. Azaz 1-gyel lép ki, ha voltak különbségek, és a 0 azt
	jelenti, hogy nincs különbség.

`--quiet`::
	Kikapcsolja a program teljes kimenetét. A `--exit-code`-ot
	vonja maga után. Kikapcsolja azoknak a külső diff-segédeknek
	a futtatását, amelyek kilépőkódja nem megbízható, azaz a
	megfelelő `diff.trustExitCode` vagy
	++diff.++__<driver>__++.trustExitCode++ konfigurációs opció,
	vagy a `GIT_EXTERNAL_DIFF_TRUST_EXIT_CODE` környezeti
	változó hamis.
endif::git-log[]
endif::git-format-patch[]

`--ext-diff`::
	Engedélyezi egy külső diff-segéd futtatását. Ha
	linkgit:gitattributes[5]-tel állított be egy külső diff
	drivert, ezt az opciót kell használnia a linkgit:git-log[1]-gyel
	és a hozzá hasonlókkal.

`--no-ext-diff`::
	Letiltja a külső diff drivereket.

`--textconv`::
`--no-textconv`::
	Engedélyezi (vagy letiltja) a külső szövegkonverziós filterek
	futtatását bináris fájlok összehasonlításakor. A részletekért
	lásd a linkgit:gitattributes[5]-öt. Mivel a textconv filterek
	jellemzően egyirányú konverziót végeznek, az eredményül kapott
	diff emberi olvasásra alkalmas, de nem alkalmazható. Emiatt a
	textconv filterek alapértelmezetten csak a linkgit:git-diff[1]
	és a linkgit:git-log[1] esetében vannak bekapcsolva, a
	linkgit:git-format-patch[1] vagy a diff plumbing parancsok
	esetében nem.


`--ignore-submodules[=(none|untracked|dirty|all)]`::
	Figyelmen kívül hagyja a submodule-okban lévő változtatásokat
	a diff generálásakor. Az `all` az alapértelmezett. A `none`
	használatakor a submodule módosítottnak számít, ha vagy
	nem követett, vagy módosított fájlokat tartalmaz, vagy a
	`HEAD`-je eltér a szuperprojektben rögzített committól, és
	felülbírálhatja az `ignore` opció bármely beállítását a
	linkgit:git-config[1]-ben vagy a linkgit:gitmodules[5]-ben.
	Ha az `untracked` van használatban, a submodule-ok nem
	számítanak piszkosnak, ha csak nem követett tartalmat
	tartalmaznak (de továbbra is átvizsgálásra kerülnek módosított
	tartalom szempontjából). A `dirty` használata figyelmen kívül
	hagy minden változtatást a submodule-ok munkakönyvtárában,
	csak a szuperprojektben tárolt commitok változásai jelennek
	meg (ez volt a viselkedés az 1.7.0-ig). Az `all` használata
	elrejt minden változtatást a submodule-okban.

`--src-prefix=<prefix>`::
	Az "a/" helyett a megadott forrás-_<prefix>_-et jeleníti meg.

`--dst-prefix=<prefix>`::
	A "b/" helyett a megadott cél-_<prefix>_-et jeleníti meg.

`--no-prefix`::
	Nem jelenít meg forrás- vagy célprefixet.

`--default-prefix`::
ifdef::git-format-patch[]
	Az alapértelmezett forrás- és célprefixeket ("a/" és "b/")
	használja. Ez felülbírálja az olyan konfigurációs változókat,
	mint a `format.noprefix`, a `diff.srcPrefix`, a
	`diff.dstPrefix` és a `diff.mnemonicPrefix` (lásd
	linkgit:git-config[1]).
endif::git-format-patch[]
ifndef::git-format-patch[]
	Az alapértelmezett forrás- és célprefixeket ("a/" és "b/")
	használja. Ez felülbírálja az olyan konfigurációs változókat,
	mint a `diff.noprefix`, a `diff.srcPrefix`, a `diff.dstPrefix`
	és a `diff.mnemonicPrefix` (lásd linkgit:git-config[1]).
endif::git-format-patch[]

`--line-prefix=<prefix>`::
	Egy további _<prefix>_-et fűz a kimenet minden sora elé.

`--ita-invisible-in-index`::
	Alapértelmezetten a `git add -N` által hozzáadott bejegyzések
	egy létező üres fájlként jelennek meg a `git diff`-ben, és
	egy új fájlként a `git diff --cached`-ben. Ez az opció azt
	eredményezi, hogy a bejegyzés új fájlként jelenik meg a `git
	diff`-ben, és nem létezőként a `git diff --cached`-ben. Ez
	az opció a `--ita-visible-in-index`-szel visszavonható.
	Mindkét opció kísérleti, és a jövőben eltávolításra kerülhet.

`--max-depth=<depth>`::
	A parancssorban megadott egyes pathspecekhez legfeljebb
	_<depth>_ könyvtárszintet ereszkedik le. A `-1` érték azt
	jelenti, hogy nincs korlát. Nem kombinálható helyettesítő
	karakterekkel a pathspecben. Egy `foo/bar/baz`-t tartalmazó
	tree esetén a következő lista mutatja az egyes
	opció-kombinációk által generált találatokat:
+
--
 - `--max-depth=0 -- foo`: `foo`

 - `--max-depth=1 -- foo`: `foo/bar`

 - `--max-depth=1 -- foo/bar`: `foo/bar/baz`

 - `--max-depth=1 -- foo foo/bar`: `foo/bar/baz`

 - `--max-depth=2 -- foo`: `foo/bar/baz`
--
+
Ha nincs pathspec megadva, a mélység úgy mérendő, mintha az
összes felső szintű bejegyzés meg lett volna adva. Vegye
figyelembe, hogy ez különbözik a gyökértől való méréstől, mivel
a `--max-depth=0` így is a `foo`-t adná vissza. Ez lehetővé
teszi, hogy továbbra is korlátozza a mélységet, miközben a
felső szintű bejegyzések egy részhalmazát kéri.
+
Vegye figyelembe, hogy ez az opció csak a tree objektumok közötti
diffekhez támogatott, az index vagy a munkakönyvtár elleni
diffekhez nem.

Ezekről a gyakori opciókról részletesebb magyarázatért lásd még
a linkgit:gitdiffcore[7]-et.
