[[_raw_output_format]]
Nyers kimeneti formátum
-----------------------

A `git-diff-index`, `git-diff-tree`, `git-diff-files` és a
`git diff --raw` nyers kimeneti formátuma nagyon hasonló.

Ezek a parancsok mind két halmaznyi dolgot hasonlítanak össze; hogy mit,
az eltérő:

`git-diff-index <tree-ish>`::
	a _<tree-ish>_-t és a fájlrendszeren lévő fájlokat hasonlítja össze.

`git-diff-index --cached <tree-ish>`::
	a _<tree-ish>_-t és az indexet hasonlítja össze.

`git-diff-tree [-r] <tree-ish-1> <tree-ish-2> [<pattern>...]`::
        a két argumentum által megnevezett tree-ket hasonlítja össze.

`git-diff-files [<pattern>...]`::
        az indexet és a fájlrendszeren lévő fájlokat hasonlítja össze.

Az összes parancs megváltozott fájlonként egy kimeneti sort ír ki,
kivéve a `git diff-files`-t egy nem merge-elt fájl esetén, amely egy
"unmerged" és egy "in-place edit" sort is kiír.

Egy kimeneti sor formátuma a következő:

------------------------------------------------
in-place edit  :100644 100644 bcd1234 0123456 M file0
copy-edit      :100644 100644 abcd123 1234567 C68 file1 file2
rename-edit    :100644 100644 abcd123 1234567 R86 file1 file3
create         :000000 100644 0000000 1234567 A file4
delete         :100644 000000 1234567 0000000 D file5
unmerged       :000000 000000 0000000 0000000 U file6
------------------------------------------------

Azaz balról jobbra:

. egy kettőspont.
. mód a "src"-hez; 000000, ha létrehozás, vagy ha a "src" az indexből származik és nem merge-elt.
. egy szóköz.
. mód a "dst"-hez; 000000, ha törlés, vagy ha a "dst" az indexből származik és nem merge-elt.
. egy szóköz.
. sha1 a "src"-hez; 0\{40\}, ha létrehozás, vagy ha a "src" az indexből származik és nem merge-elt.
. egy szóköz.
. sha1 a "dst"-hez; 0\{40\}, ha törlés, ha a "dst" az indexből származik és nem merge-elt, vagy ha a "dst" a work tree-ből származik és nincs szinkronban az indexszel.
. egy szóköz.
. státusz, amelyet egy opcionális "score" szám követ.
. egy tab vagy egy NUL, ha a `-z` opció használatban van.
. útvonal a "src"-hez
. egy tab vagy egy NUL, ha a `-z` opció használatban van; csak C vagy R esetén létezik.
. útvonal a "dst"-hez; csak C vagy R esetén létezik.
. egy LF vagy egy NUL, ha a `-z` opció használatban van, a rekord lezárására.

A lehetséges státuszbetűk:

- `A`: egy fájl hozzáadása
- `C`: egy fájl másolása egy újba
- `D`: egy fájl törlése
- `M`: egy fájl tartalmának vagy módjának módosítása
- `R`: egy fájl átnevezése
- `T`: a fájl típusának megváltozása (közönséges fájl, szimbolikus link vagy submodule)
- `U`: a fájl nem merge-elt (be kell fejezned a merge-et, mielőtt
  commitolható lenne)
- `X`: "ismeretlen" változtatástípus (nagy valószínűséggel hiba, kérjük, jelentsd)

A `C` és `R` státuszbetűket mindig egy score követi (amely a mozgatás
vagy másolás forrása és célja közötti hasonlóság százalékát jelöli).  Az
`M` státuszbetűt fájl-újraírásoknál követheti egy score (amely a
különbözőség százalékát jelöli).

A "dst" sha1-e csupa 0-ként jelenik meg, ha a fájlrendszeren lévő fájl
nincs szinkronban az indexszel.

Példa:

------------------------------------------------
:100644 100644 5be4a4a 0000000 M file.c
------------------------------------------------

A `-z` opció nélkül a "szokatlan" karaktereket tartalmazó útvonalnevek
idézőjelbe kerülnek a `core.quotePath` konfigurációs változónál leírtak
szerint (l. linkgit:git-config[1]).  A `-z` használatával a fájlnév szó
szerint kerül a kimenetre, és a sort egy NUL bájt zárja.

[[_diff_format_for_merges]]
diff formátum merge-ekhez
-------------------------

A `git-diff-tree`, a `git-diff-files` és a `git-diff --raw` a `-c` vagy
a `--cc` opciót is elfogadja, hogy merge-commitokhoz is generáljon diff
kimenetet.  A kimenet a fent leírt formátumtól a következő módon tér el:

. minden szülőhöz van egy kettőspont
. több "src" mód és "src" sha1 van
. a státusz minden szülőhöz összefűzött státuszkarakterek
. nincs opcionális "score" szám
. a fájl tabbal elválasztott útvonalnév(ei)

A `-c` és a `--cc` esetén csak a cél vagy a végső útvonal jelenik meg,
még akkor is, ha a fájlt az előzmények bármely oldalán átnevezték.  A
`--combined-all-paths` esetén minden szülőben megjelenik az útvonal
neve, amelyet a merge-commitban lévő útvonal neve követ.

Példák a `-c`-re és a `--cc`-re a `--combined-all-paths` nélkül:

------------------------------------------------
::100644 100644 100644 fabadb8 cc95eb0 4866510 MM	desc.c
::100755 100755 100755 52b7a2d 6d1ac04 d2ac7d7 RM	bar.sh
::100644 100644 100644 e07d6c5 9042e82 ee91881 RR	phooey.c
------------------------------------------------

Példák, amikor a `--combined-all-paths` hozzáadódik a `-c`-hez vagy a `--cc`-hez:

------------------------------------------------
::100644 100644 100644 fabadb8 cc95eb0 4866510 MM	desc.c	desc.c	desc.c
::100755 100755 100755 52b7a2d 6d1ac04 d2ac7d7 RM	foo.sh	bar.sh	bar.sh
::100644 100644 100644 e07d6c5 9042e82 ee91881 RR	fooey.c	fuey.c	phooey.c
------------------------------------------------

Vedd figyelembe, hogy a 'combined diff' csak azokat a fájlokat sorolja
fel, amelyek minden szülőhöz képest módosultak.


include::diff-generate-patch.adoc[]


[[_other_diff_formats]]
egyéb diff formátumok
---------------------

A `--summary` opció az újonnan hozzáadott, törölt, átnevezett és másolt
fájlokat írja le.  A `--stat` opció `diffstat`(1) grafikont ad a
kimenethez.  Ezek az opciók más opciókkal (mint a `-p`) kombinálhatók,
és ember általi feldolgozásra szolgálnak.

Amikor egy átnevezést vagy másolást is magában foglaló változtatást
mutat, a `--stat` kimenet kompaktan formázza az útvonalneveket az
útvonalnevek közös előtagjának és utótagjának összevonásával.  Például
egy változtatás, amely az `arch/i386/Makefile`-t az `arch/x86/Makefile`-ba
mozgatja 4 sor módosításával, így jelenik meg:

------------------------------------
arch/{i386 => x86}/Makefile    |   4 +--
------------------------------------

A `--numstat` opció a diffstat(1) információt adja, de a könnyebb gépi
feldolgozásra tervezték.  Egy bejegyzés a `--numstat` kimenetében így
néz ki:

----------------------------------------
1	2	README
3	1	arch/{i386 => x86}/Makefile
----------------------------------------

Azaz balról jobbra:

. a hozzáadott sorok száma;
. egy tab;
. a törölt sorok száma;
. egy tab;
. útvonalnév (esetleg átnevezés/másolás információval);
. egy újsor.

Amikor a `-z` kimeneti opció érvényben van, a kimenet formátuma a következő:

----------------------------------------
1	2	README NUL
3	1	NUL arch/i386/Makefile NUL arch/x86/Makefile NUL
----------------------------------------

Azaz:

. a hozzáadott sorok száma;
. egy tab;
. a törölt sorok száma;
. egy tab;
. egy NUL (csak átnevezés/másolás esetén létezik);
. útvonalnév az előképben;
. egy NUL (csak átnevezés/másolás esetén létezik);
. útvonalnév az utóképben (csak átnevezés/másolás esetén létezik);
. egy NUL.

Az extra `NUL` az előkép-útvonal előtt átnevezés esetén azért van, hogy
a kimenetet olvasó szkriptek előreolvasás nélkül meg tudják állapítani,
hogy az éppen olvasott rekord egyutas rekord-e, vagy átnevezés/másolás
rekord.  A hozzáadott és törölt sorok elolvasása után a `NUL`-ig való
olvasás az útvonalnevet adná, de ha az `NUL`, a rekord két útvonalat
fog mutatni.
