[[generate_patch_text_with_p]]
Patch-szöveg előállítása a -p opcióval
--------------------------------------

A
linkgit:git-diff[1],
linkgit:git-log[1],
linkgit:git-show[1],
linkgit:git-diff-index[1],
linkgit:git-diff-tree[1], vagy
linkgit:git-diff-files[1]
`-p` opcióval való futtatása patch-szöveget állít elő.
A patch-szöveg előállítása testreszabható a `GIT_EXTERNAL_DIFF` és a
`GIT_DIFF_OPTS` környezeti változókkal (lásd linkgit:git[1]), valamint a
`diff` attribútummal (lásd linkgit:gitattributes[5]).

Amit a `-p` opció előállít, az kissé eltér a hagyományos
diff-formátumtól:

1.   Megelőzi egy "git diff" fejléc, amely így néz ki:

       diff --git a/file1 b/file2
+
Az `a/` és `b/` fájlnevek megegyeznek, hacsak nincs átnevezés/másolás.
Különösen: még létrehozásnál vagy törlésnél sem használ `/dev/null`-t az
`a/` vagy `b/` fájlnevek helyett.
+
Átnevezés/másolás esetén a `file1` és a `file2` az átnevezés/másolás
forrásfájljának nevét, illetve az átnevezés/másolás által előállított
fájl nevét mutatja.

2.   Egy vagy több kiterjesztett fejlécsor követi:
+
[synopsis]
old mode <mode>
new mode <mode>
deleted file mode <mode>
new file mode <mode>
copy from <path>
copy to <path>
rename from <path>
rename to <path>
similarity index <number>
dissimilarity index <number>
index <hash>..<hash> <mode>
+
A fájlmódok (_<mode>_) 6 számjegyű oktális számként vannak kiírva,
beleértve a fájltípust és a fájljogosultsági biteket.
+
A kiterjesztett fejlécekben az elérési utak nem tartalmazzák az `a/` és
`b/` előtagot.
+
A hasonlósági index a változatlan sorok százalékos aránya, a
különbözőségi index pedig a megváltozott sorok százalékos aránya.  Ez egy
lefelé kerekített egész szám, százalékjellel követve.  A 100%-os
hasonlósági index értéke így két egyenlő fájlnak van fenntartva, míg a
100%-os különbözőség azt jelenti, hogy a régi fájlból egyetlen sor sem
került át az újba.
+
Az index sor tartalmazza a blob objektumneveket a változás előtt és
után.  A _<mode>_ akkor szerepel, ha a fájlmód nem változik; egyébként
külön sorok jelzik a régi és az új módot.

3.  A "szokatlan" karaktereket tartalmazó elérési utak idézőjelezve
    vannak a `core.quotePath` konfigurációs változónál leírtak szerint
    (lásd linkgit:git-config[1]).

4.  A kimenetben az összes `file1` fájl a commit előtti fájlokra
    hivatkozik, az összes `file2` fájl pedig a commit utáni fájlokra.
    Helytelen az egyes változásokat sorban egymás után alkalmazni az
    egyes fájlokra.  Például ez a patch felcseréli az a-t és a b-t:

      diff --git a/a b/b
      rename from a
      rename to b
      diff --git a/b b/a
      rename from b
      rename to a

5.  A hunk-fejlécek megemlítik annak a függvénynek a nevét, amelyre a
    hunk vonatkozik.  Arról, hogyan szabható ez testre konkrét
    nyelvekhez, lásd a "Defining a custom hunk-header" szakaszt a
    linkgit:gitattributes[5] oldalon.


[[_combined_diff_format]]
Kombinált diff-formátum
-----------------------

Bármely diffet előállító parancs megkaphatja a `-c` vagy `--cc` opciót,
hogy 'kombinált diffet' állítson elő egy merge megjelenítésekor. Ez az
alapértelmezett formátum, amikor merge-eket jelenítesz meg a
linkgit:git-diff[1] vagy a linkgit:git-show[1] paranccsal. Vedd
figyelembe azt is, hogy bármelyik ilyen parancsnak megadhatsz megfelelő
`--diff-merges` opciót, hogy egy adott formátumú diff generálását
kényszerítsd ki.

Egy "kombinált diff" formátum így néz ki:

------------
diff --combined describe.c
index fabadb8,cc95eb0..4866510
--- a/describe.c
+++ b/describe.c
@@@ -98,20 -98,12 +98,20 @@@
	return (a_date > b_date) ? -1 : (a_date == b_date) ? 0 : 1;
  }

- static void describe(char *arg)
 -static void describe(struct commit *cmit, int last_one)
++static void describe(char *arg, int last_one)
  {
 +	unsigned char sha1[20];
 +	struct commit *cmit;
	struct commit_list *list;
	static int initialized = 0;
	struct commit_name *n;

 +	if (get_sha1(arg, sha1) < 0)
 +		usage(describe_usage);
 +	cmit = lookup_commit_reference(sha1);
 +	if (!cmit)
 +		usage(describe_usage);
 +
	if (!initialized) {
		initialized = 1;
		for_each_ref(get_name);
------------

1.   Megelőzi egy "git diff" fejléc, amely így néz ki (amikor a `-c`
     opciót használod):

       diff --combined file
+
vagy így (amikor a `--cc` opciót használod):

       diff --cc file

2.   Egy vagy több kiterjesztett fejlécsor követi (ez a példa egy két
     szülős merge-et mutat):
+
[synopsis]
index <hash>,<hash>..<hash>
mode <mode>,<mode>..<mode>
new file mode <mode>
deleted file mode <mode>,<mode>
+
A `mode <mode>,<mode>..<mode>` sor csak akkor jelenik meg, ha a <mode>-ok
közül legalább egy különbözik a többitől. A felderített
tartalommozgásról (átnevezések és másoláskimutatás) információt hordozó
kiterjesztett fejlécek két _<tree-ish>_ diffjével való működésre lettek
tervezve, és a kombinált diff-formátum nem használja őket.

3.   Egy kétsoros from-file/to-file fejléc követi:

       --- a/file
       +++ b/file
+
A hagyományos 'unified' diff-formátum kétsoros fejlécéhez hasonlóan a
`/dev/null` jelzi a létrehozott vagy törölt fájlokat.
+
Ha azonban a --combined-all-paths opció meg van adva, kétsoros
from-file/to-file helyett egy N+1 soros from-file/to-file fejlécet
kapsz, ahol N a merge-commit szüleinek száma:

       --- a/file
       --- a/file
       --- a/file
       +++ b/file
+
Ez a kiterjesztett formátum akkor hasznos, ha az átnevezés- vagy
másoláskimutatás aktív, mert lehetővé teszi, hogy lásd a fájl eredeti
nevét a különböző szülőkben.

4.   A chunk-fejléc formátuma úgy van módosítva, hogy megakadályozza,
     hogy az emberek véletlenül a `patch -p1`-nek adják. A kombinált
     diff-formátum a merge-commitok változásainak áttekintésére
     készült, nem alkalmazásra szánták. A változás hasonló a
     kiterjesztett 'index' fejléc változásához:

       @@@ <from-file-range> <from-file-range> <to-file-range> @@@
+
A kombinált diff-formátum chunk-fejlécében (szülők száma + 1) `@`
karakter van.

A hagyományos 'unified' diff-formátummal ellentétben, amely két fájlt (A
és B) mutat egyetlen oszloppal, amelyben `-` (mínusz – megjelenik A-ban,
de eltávolítva B-ben), `+` (plusz – hiányzik A-ból, de hozzáadva B-hez)
vagy `" "` (szóköz – változatlan) előtag van, ez a formátum két vagy több
fájlt (file1, file2, ...) hasonlít össze egyetlen X fájllal, és
megmutatja, hogyan tér el X az egyes fileN-ektől.  Minden fileN-hez egy-
egy oszlop kerül a kimeneti sor elé, hogy jelezze, X sora miben tér el
tőle.

Egy `-` karakter az N. oszlopban azt jelenti, hogy a sor megjelenik a
fileN-ben, de nem jelenik meg az eredményben.  Egy `+` karakter az N.
oszlopban azt jelenti, hogy a sor megjelenik az eredményben, és a fileN-
nek nincs meg ez a sora (más szóval a sor hozzá lett adva, annak a
szülőnek a szemszögéből).

A fenti példakimenetben a függvény szignatúrája mindkét fájlban
megváltozott (innen a két `-` eltávolítás a file1-ből és a file2-ből is,
plusz a `++`, ami azt jelenti, hogy egy hozzáadott sor egyik fájlban sem
jelenik meg: sem a file1-ben, sem a file2-ben).  Emellett nyolc további
sor megegyezik a file1-gyel, de nem jelenik meg a file2-ben (innen a `+`
előtag).

Amikor a `git diff-tree -c` jeleníti meg, egy merge-commit szüleit
hasonlítja össze a merge eredményével (azaz a file1..fileN a szülők).
Amikor a `git diff-files -c` jeleníti meg, a két feloldatlan merge-szülőt
hasonlítja össze a working tree-beli fájllal (azaz a file1 a 2. stage,
más néven "our version", a file2 a 3. stage, más néven "their version").
