git-merge(1)
============

NAME
----
git-merge - Két vagy több fejlődéstörténet összekapcsolása


SYNOPSIS
--------
[synopsis]
git merge [-n] [--stat] [--compact-summary] [--no-commit] [--squash] [--[no-]edit]
	[--no-verify] [-s <strategy>] [-X <strategy-option>] [-S[<keyid>]]
	[--[no-]allow-unrelated-histories]
	[--[no-]rerere-autoupdate] [-m <msg>] [-F <file>]
	[--into-name <branch>] [<commit>...]
git merge (--continue | --abort | --quit)

DESCRIPTION
-----------
Beépíti a megnevezett commitok változásait (attól kezdve, hogy a
történetük eltért az aktuális branchtől) az aktuális branchbe. Ezt a
parancsot használja a `git pull` egy másik repository változásainak
beépítéséhez, és kézzel is használható arra, hogy egy branch változásait
egy másikba merge-eld.

Tegyük fel, hogy a következő történet létezik, és az aktuális branch a
`master`:

------------
          A---B---C topic
         /
    D---E---F---G master
------------

Ekkor a `git merge topic` újrajátssza a `topic` branchen végzett
változásokat attól kezdve, hogy az eltért a `master`-től (azaz `E`), az
aktuális commitjáig (`C`), a `master` tetejére, és az eredményt egy új
commitban rögzíti a két szülőcommit nevével és a felhasználótól származó,
a változásokat leíró napló-üzenettel együtt. A művelet előtt az
`ORIG_HEAD` az aktuális branch csúcsára (`G`) áll be.

------------
          A---B---C topic
         /         \
    D---E---F---G---H master
------------

A merge leáll, ha van egy olyan konfliktus, amely nem oldható fel
automatikusan, vagy ha a `--no-commit` meg volt adva a merge
kezdeményezésekor. Ekkor lefuttathatod a `git merge --abort` vagy a
`git merge --continue` parancsot.

A `git merge --abort` megszakítja a merge folyamatát, és megpróbálja
helyreállítani a merge előtti állapotot. Ha viszont voltak nem
commitolt változások, amikor a merge elindult (és különösen, ha ezeket a
változásokat a merge indulása után tovább módosították), a
`git merge --abort` bizonyos esetekben nem lesz képes helyreállítani az
eredeti (merge előtti) változásokat. Ezért:

WARNING: A `git merge` futtatása nem triviális, nem commitolt
változásokkal nem ajánlott: bár lehetséges, olyan állapotban hagyhat,
amiből konfliktus esetén nehéz kihátrálni.

OPTIONS
-------
:git-merge: 1

include::merge-options.adoc[]

`-m <msg>`::
	Beállítja a merge commithoz használandó commit-üzenetet (arra az
	esetre, ha létrejön ilyen).
+
Ha a `--log` meg van adva, a merge-elt commitok shortlogja hozzáfűződik
a megadott üzenethez.
+
A `git fmt-merge-msg` parancs jó alapértelmezést tud adni az
automatizált `git merge` hívásokhoz. Az automatikus üzenet tartalmazhatja
a branch leírását.

`--into-name <branch>`::
	Úgy készíti elő az alapértelmezett merge-üzenetet, mintha a
	`_<branch>_` branchbe merge-elne, nem pedig annak a valódi
	branchnek a nevével, amelybe a merge történik.

`-F <file>`::
`--file=<file>`::
	Beolvassa a merge commithoz használandó commit-üzenetet (arra az
	esetre, ha létrejön ilyen).
+
Ha a `--log` meg van adva, a merge-elt commitok shortlogja hozzáfűződik
a megadott üzenethez.

include::rerere-options.adoc[]

`--overwrite-ignore`::
`--no-overwrite-ignore`::
	Csendben felülírja a merge eredményéből az ignorált fájlokat. Ez az
	alapértelmezett viselkedés. A `--no-overwrite-ignore`-ral
	megszakítható.

`--abort`::
	Megszakítja az aktuális konfliktusfeloldási folyamatot, és
	megpróbálja helyreállítani a merge előtti állapotot. Ha van
	autostash bejegyzés, alkalmazza a worktree-re.
+
Ha voltak nem commitolt worktree-változások, amikor a merge elindult, a
`git merge --abort` bizonyos esetekben nem lesz képes helyreállítani
ezeket a változásokat. Ezért ajánlott mindig commitolni vagy stashelni a
változásaidat, mielőtt a `git merge`-et lefuttatnád.
+
A `git merge --abort` egyenértékű a `git reset --merge`-dzsel, amikor a
`MERGE_HEAD` jelen van, kivéve, ha a `MERGE_AUTOSTASH` is jelen van, amely
esetben a `git merge --abort` a worktree-re alkalmazza a stash-bejegyzést,
míg a `git reset --merge` a stash-elt változásokat a stash-listába menti.

`--quit`::
	Elfelejti az aktuális, folyamatban lévő merge-et. Az indexet és a
	munkakönyvtárat úgy hagyja, ahogy van. Ha a `MERGE_AUTOSTASH` jelen
	van, a stash-bejegyzés a stash-listába mentődik.

`--continue`::
	Miután egy `git merge` konfliktusok miatt leáll, befejezheted a
	merge-et a `git merge --continue` lefuttatásával (lásd a "HOW TO
	RESOLVE CONFLICTS" szakaszt lentebb).

`<commit>...`::
	Commitok — általában más branchek fejei —, amelyeket a mi branchünkbe
	kell merge-elni. Egynél több commit megadása kettőnél több szülővel
	járó merge-et hoz létre (amit szeretettel Octopus merge-nek
	neveznek).
+
Ha nincs commit megadva a parancssorból, azokat a remote-tracking
brancheket merge-eli, amelyeket az aktuális branch az upstreamjeként
való használatra van beállítva. Lásd még e kézikönyvlap konfigurációs
szakaszát.
+
Ha a `FETCH_HEAD` (és semmilyen más commit) van megadva, a `git fetch`
előző hívása által a `.git/FETCH_HEAD` fájlba merge-elésre rögzített
branchek merge-elődnek az aktuális branchbe.


PRE-MERGE CHECKS
----------------

Mielőtt külső változásokat alkalmaznál, jó formába kell hoznod és
helyben commitolnod a saját munkádat, hogy az ne íródjon felül, ha
konfliktusok vannak. Lásd még: linkgit:git-stash[1].
A `git pull` és a `git merge` bármi tevés nélkül leáll, amikor a helyi,
nem commitolt változások átfednek olyan fájlokkal, amelyeket a
`git pull`/`git merge`-nek frissítenie kellhet.

Hogy elkerülje a nem kapcsolódó változások rögzítését a merge commitban,
a `git pull` és a `git merge` akkor is megszakad, ha bármilyen változás
van regisztrálva az indexben a `HEAD` commithoz képest. (Ez alól a
szabály alól szűk, speciális kivételek létezhetnek attól függően, hogy
melyik merge-stratégia van használatban, de általában az indexnek
egyeznie kell a `HEAD`-del.)

Ha az összes megnevezett commit már a `HEAD` őse, a `git merge` korán
kilép az "Already up to date." üzenettel.

FAST-FORWARD MERGE
------------------

Gyakran az aktuális branch feje a megnevezett commit őse. Ez a
leggyakoribb eset, különösen amikor a `git pull`-ból hívódik meg: egy
upstream repository-t követsz, nem commitoltál helyi változásokat, és
most egy újabb upstream revízióra szeretnél frissíteni. Ebben az
esetben nincs szükség új commitra az egyesített történet tárolásához;
helyette a `HEAD` (az indexszel együtt) úgy frissül, hogy a megnevezett
commitra mutasson, extra merge commit létrehozása nélkül.

Ez a viselkedés a `--no-ff` kapcsolóval elnyomható.

TRUE MERGE
----------

A fast-forward merge (lásd fent) kivételével a merge-elendő brancheket
egy merge commitnak kell összekötnie, amelynek mindkettő a szülője.

Egy merge-elt verzió commitolódik, amely összeegyezteti az összes
merge-elendő branch változásait, és a `HEAD`-ed, az indexed és a working
tree-d erre frissül. Lehetnek módosítások a working tree-ben, amíg nem
fednek át; a frissítés megőrzi őket.

Amikor nem nyilvánvaló, hogyan kell összeegyeztetni a változásokat, a
következő történik:

1. A `HEAD` mutató ugyanaz marad.
2. A `MERGE_HEAD` ref a másik branch fejére áll be.
3. A tisztán merge-elődött útvonalak mind az indexfájlban, mind a
   working tree-dben frissülnek.
4. A konfliktusos útvonalakhoz az indexfájl legfeljebb három verziót
   rögzít: az 1-es stage a közös ős verzióját tárolja, a 2-es a
   `HEAD`-ét, a 3-as pedig a `MERGE_HEAD`-ét (a stage-eket a
   `git ls-files -u`-val vizsgálhatod meg). A working tree fájljai a
   merge művelet eredményét tartalmazzák; azaz háromutas merge
   eredményeit az ismerős +<<<+ `===` +>>>+ konfliktusjelölőkkel.
5. Egy `AUTO_MERGE` nevű ref íródik ki, amely egy olyan fára mutat,
   amely a working tree aktuális tartalmának felel meg (a szöveges
   konfliktusok konfliktusjelölőit is beleértve). Vedd figyelembe, hogy
   ez a ref csak akkor íródik ki, amikor az `ort` merge-stratégia van
   használatban (az alapértelmezett).
6. Semmilyen más változás nem történik. Konkrétan a helyi
   módosítások, amelyeid a merge megkezdése előtt voltak, ugyanazok
   maradnak, és a hozzájuk tartozó indexbejegyzések is úgy maradnak,
   ahogy voltak, azaz egyeznek a `HEAD`-del.

Ha megpróbáltál egy merge-et, amely bonyolult konfliktusokat
eredményezett, és elölről akarod kezdeni, a `git merge --abort`-tal
állhatsz vissza.

MERGING TAG
-----------

Egy annotált (és esetleg aláírt) tag merge-elésekor a Git mindig
létrehoz egy merge commitot, még akkor is, ha fast-forward merge
lehetséges, és a commit-üzenet sablonja a tag üzenetével készül el.
Ezenfelül, ha a tag alá van írva, az aláírás-ellenőrzés kommentként
jelenik meg az üzenetsablonban. Lásd még: linkgit:git-tag[1].

Amikor csak azzal a munkával akarsz integrálódni, amely a történetesen
megtagelt commithoz vezet, pl. egy upstream kiadási ponttal
szinkronizálva, lehet, hogy nem akarsz szükségtelen merge commitot
csinálni.

Ilyen esetben magad „kicsomagolhatod" a taget, mielőtt a `git merge`-nek
adnád, vagy megadhatod a `--ff-only`-t, amikor nincs saját munkád. Pl.

----
git fetch origin
git merge v1.2.3^0
git merge --ff-only v1.2.3
----

HOW CONFLICTS ARE PRESENTED
---------------------------

Merge közben a working tree fájljai frissülnek, hogy a merge eredményét
tükrözzék. A közös ős verzióján végzett változások közül a nem
átfedőek (azaz te megváltoztattad a fájl egy területét, míg a másik
oldal azt a területet érintetlenül hagyta, vagy fordítva) szó szerint
beépülnek a végeredménybe. Amikor viszont mindkét oldal ugyanazt a
területet módosította, a Git nem tud véletlenszerűen egyik oldalt a
másik elé sorolni, és arra kér, hogy oldd fel úgy, hogy meghagyod, amit
mindkét oldal tett azzal a területtel.

Alapból a Git ugyanazt a stílust használja egy ilyen konfliktusos hunk
bemutatására, mint az RCS csomag „merge" programja, így:

------------
Here are lines that are either unchanged from the common
ancestor, or cleanly resolved because only one side changed,
or cleanly resolved because both sides changed the same way.
<<<<<<< yours:sample.txt
Conflict resolution is hard;
let's go shopping.
=======
Git makes conflict resolution easy.
>>>>>>> theirs:sample.txt
And here is another line that is cleanly resolved or unmodified.
------------

Az a terület, ahol egy konfliktusos változáspár keletkezett, a
+<<<<<<<+, `=======` és +>>>>>>>+ jelölőkkel van megjelölve. A `=======`
előtti rész jellemzően a te oldalad, az utána következő rész pedig
jellemzően az ő oldaluk.

Az alapértelmezett formátum nem mutatja meg, mit mondott az eredeti a
konfliktusos területen. Nem tudod megmondani, hány sor törlődött, és
cserélődött ki Barbie megjegyzésével a te oldaladon. Az egyetlen, amit
meg tudsz mondani, hogy a te oldalad azt akarja mondani, hogy nehéz, és
inkább vásárolni mennél, míg a másik oldal azt akarja állítani, hogy
könnyű.

Egy alternatív stílus használható a `merge.conflictStyle` konfigurációs
változó `diff3`-ra vagy `zdiff3`-ra állításával. `diff3` stílusban a
fenti konfliktus így nézhet ki:

------------
Here are lines that are either unchanged from the common
ancestor, or cleanly resolved because only one side changed,
<<<<<<< yours:sample.txt
or cleanly resolved because both sides changed the same way.
Conflict resolution is hard;
let's go shopping.
||||||| base:sample.txt
or cleanly resolved because both sides changed identically.
Conflict resolution is hard.
=======
or cleanly resolved because both sides changed the same way.
Git makes conflict resolution easy.
>>>>>>> theirs:sample.txt
And here is another line that is cleanly resolved or unmodified.
------------

míg `zdiff3` stílusban így nézhet ki:

------------
Here are lines that are either unchanged from the common
ancestor, or cleanly resolved because only one side changed,
or cleanly resolved because both sides changed the same way.
<<<<<<< yours:sample.txt
Conflict resolution is hard;
let's go shopping.
||||||| base:sample.txt
or cleanly resolved because both sides changed identically.
Conflict resolution is hard.
=======
Git makes conflict resolution easy.
>>>>>>> theirs:sample.txt
And here is another line that is cleanly resolved or unmodified.
------------

A +<<<<<<<+, `=======` és +>>>>>>>+ jelölőkön felül egy másik +|||||||+
jelölőt is használ, amelyet az eredeti szöveg követ. Meg tudod mondani,
hogy az eredeti csak egy tényt állapított meg, és a te oldalad egyszerűen
beadta a derekát ennek a kijelentésnek, és feladta, míg a másik oldal
pozitívabb hozzáállással próbálkozott. Néha jobb feloldás juthat
eszedbe, ha megnézed az eredetit.


HOW TO RESOLVE CONFLICTS
------------------------

Miután láttál egy konfliktust, két dolgot tehetsz:

 * Úgy döntesz, hogy nem merge-elsz. Az egyetlen takarítás, amire
   szükséged van, hogy visszaállítsd az indexfájlt a `HEAD` commitra a
   2. visszavonásához, és feltakarítsd a 2. és 3. által végzett
   working tree-változásokat; ehhez a `git merge --abort` használható.

 * Feloldod a konfliktusokat. A Git megjelöli a konfliktusokat a
   working tree-ben. Formába szerkeszted a fájlokat, és `git add`-del
   hozzáadod őket az indexhez. A `git commit`-tal vagy a
   `git merge --continue`-val nyélbe ütöd a dolgot. Az utóbbi parancs
   ellenőrzi, van-e (megszakított) merge folyamatban, mielőtt meghívná
   a `git commit`-ot.

A konfliktust számos eszközzel átdolgozhatod:

 * Használj mergetoolt. A `git mergetool` egy grafikus mergetoolt
   indít, amely veled együtt átdolgozza a merge-et.

 * Nézd meg a diffeket. A `git diff` egy háromutas diffet mutat,
   kiemelve a `HEAD` és a `MERGE_HEAD` verzió változásait is. A
   `git diff AUTO_MERGE` megmutatja, milyen változásokat végeztél
   eddig a szöveges konfliktusok feloldásához.

 * Nézd meg az egyes branchek diffjeit. A `git log --merge -p <path>`
   először a `HEAD` verzióhoz, majd a `MERGE_HEAD` verzióhoz mutat
   diffeket.

 * Nézd meg az eredetieket. A `git show :1:filename` a közös őst
   mutatja, a `git show :2:filename` a `HEAD` verziót, a
   `git show :3:filename` pedig a `MERGE_HEAD` verziót.


EXAMPLES
--------

* A `fixes` és `enhancements` branch merge-elése az aktuális branch
  tetejére, octopus merge-et készítve:
+
------------------------------------------------
$ git merge fixes enhancements
------------------------------------------------

* Az `obsolete` branch merge-elése az aktuális branchbe, `ours`
  merge-stratégiával:
+
------------------------------------------------
$ git merge -s ours obsolete
------------------------------------------------

* A `maint` branch merge-elése az aktuális branchbe, de új commit
  automatikus készítése nélkül:
+
------------------------------------------------
$ git merge --no-commit maint
------------------------------------------------
+
Ez akkor használható, ha további változásokat akarsz belefoglalni a
merge-be, vagy a saját merge commit-üzenetedet akarod megírni.
+
Tartózkodj attól, hogy visszaélj ezzel a kapcsolóval, és jelentős
változásokat csempéssz egy merge commitba. Kis igazítások, mint a
kiadás-/verziónév megnövelése, elfogadhatók lennének.


include::merge-strategies.adoc[]

CONFIGURATION
-------------

`branch.<name>.mergeOptions`::
	Alapértelmezett opciókat állít be a `_<name>_` branchbe merge-eléshez.
	A szintaxis és a támogatott opciók ugyanazok, mint a `git merge`-é,
	de a whitespace-karaktereket tartalmazó opcióértékek jelenleg nem
	támogatottak.

include::includes/cmd-config-section-rest.adoc[]

include::config/merge.adoc[]

SEE ALSO
--------
linkgit:git-fmt-merge-msg[1], linkgit:git-pull[1],
linkgit:gitattributes[5],
linkgit:git-reset[1],
linkgit:git-diff[1], linkgit:git-ls-files[1],
linkgit:git-add[1], linkgit:git-rm[1],
linkgit:git-mergetool[1]

GIT
---
A linkgit:git[1] csomag része
