git-commit(1)
=============

NAME
----
git-commit - Változtatások rögzítése a repository-ban

SYNOPSIS
--------
[synopsis]
git commit [-a | --interactive | --patch] [-s] [-v] [-u[<mode>]] [--amend]
	   [--dry-run] [(-c | -C | --squash) <commit> | --fixup [(amend|reword):]<commit>]
	   [-F <file> | -m <msg>] [--reset-author] [--allow-empty]
	   [--allow-empty-message] [--no-verify] [-e] [--author=<author>]
	   [--date=<date>] [--cleanup=<mode>] [--[no-]status]
	   [-i | -o] [--pathspec-from-file=<file> [--pathspec-file-nul]]
	   [(--trailer <token>[(=|:)<value>])...] [-S[<keyid>]]
	   [--] [<pathspec>...]

DESCRIPTION
-----------
Új commit létrehozása, amely az index jelenlegi tartalmát és a
változtatásokat leíró, megadott napló-üzenetet tartalmazza. Az új
commit a HEAD közvetlen gyermeke, általában az aktuális branch csúcsa,
és a branch frissül, hogy erre mutasson (kivéve, ha nincs branch
társítva a munkakönyvtárhoz, ebben az esetben a `HEAD` "leválasztott",
ahogy azt a linkgit:git-checkout[1] leírja).

A commitolandó tartalom többféleképpen megadható:

1. a linkgit:git-add[1] használatával, hogy fokozatosan "hozzáadd"
   (add) a változtatásokat az indexhez a `commit` parancs használata
   előtt (Megjegyzés: még a módosított fájlokat is "hozzá kell adni");

2. a linkgit:git-rm[1] használatával, hogy fájlokat távolíts el a
   munkakönyvtárból és az indexből, szintén a `commit` parancs
   használata előtt;

3. ha fájlokat sorolsz fel a `commit` parancs argumentumaként (a
   `--interactive` vagy a `--patch` kapcsoló nélkül), ebben az esetben
   a commit figyelmen kívül hagyja az indexben stage-elt
   változtatásokat, és ehelyett a felsorolt fájlok jelenlegi tartalmát
   rögzíti (amelyeknek már ismertnek kell lenniük a Git számára);

4. a `commit` paranccsal használt `-a` kapcsolóval, hogy automatikusan
   "hozzáadj" (add) minden ismert fájlból (azaz minden olyan fájlból,
   amely már szerepel az indexben) származó változtatást, és
   automatikusan "eltávolítsd" (rm) az indexből azokat a fájlokat,
   amelyeket eltávolítottak a munkakönyvtárból, majd elvégezd a tényleges
   commitolást;

5. a `commit` paranccsal használt `--interactive` vagy `--patch`
   kapcsolóval, hogy egyenként eldöntsd, mely fájlok vagy hunkok legyenek
   részei a commitnak az index tartalma mellett, mielőtt véglegesítenéd
   a műveletet. Lásd a linkgit:git-add[1] „Interaktív mód" szakaszát,
   hogy megtudd, hogyan kell működtetni ezeket a módokat.

A `--dry-run` opció segítségével összefoglaló kapható arról, hogy a
fentiek bármelyike mit foglalna bele a következő commitba, ugyanazon
paraméterhalmaz (opciók és útvonalak) megadásával.

Ha commitolsz, majd közvetlenül utána hibát találsz, a `git reset`
paranccsal tudsz belőle helyreállni.

:git-commit: 1

OPTIONS
-------
`-a`::
`--all`::
	Automatikusan stage-eli azokat a fájlokat, amelyeket
	módosítottak vagy töröltek, de az új fájlokra, amelyekről
	még nem tudtál a Gitnek, ez nincs hatással.

`-p`::
`--patch`::
	Az interaktív patch-kiválasztási felület használata, hogy
	kiválaszd, mely változtatásokat kívánod commitolni. Részletekért
	lásd a linkgit:git-add[1] leírását.

include::diff-context-options.adoc[]

`-C <commit>`::
`--reuse-message=<commit>`::
	Egy meglévő _<commit>_ objektum felhasználásával a napló-üzenet
	és a szerzőségi információk (beleértve az időbélyeget is)
	újrafelhasználása a commit létrehozásakor.

`-c <commit>`::
`--reedit-message=<commit>`::
	Mint a `-C`, de a `-c` esetén a szerkesztő elindul, hogy a
	felhasználó tovább szerkeszthesse a commit-üzenetet.

`--fixup=[(amend|reword):]<commit>`::
	Új commit létrehozása, amely "kijavítja" ("fixes up") a
	_<commit>_-ot, amikor a `git rebase --autosquash` alkalmazza.
	Az egyszerű `--fixup=<commit>` egy "fixup!" commitot hoz létre,
	amely megváltoztatja a _<commit>_ tartalmát, de a napló-üzenetét
	érintetlenül hagyja. A `--fixup=amend:<commit>` hasonló, de egy
	"amend!" commitot hoz létre, amely a _<commit>_ napló-üzenetét is
	lecseréli az "amend!" commit napló-üzenetére. A
	`--fixup=reword:<commit>` egy "amend!" commitot hoz létre, amely
	a _<commit>_ napló-üzenetét a saját napló-üzenetére cseréli, de
	nem változtat a _<commit>_ tartalmán.
+
Az egyszerű `--fixup=<commit>` által létrehozott commit címe
"fixup!"-ból és az azt követő _<commit>_ címéből áll össze, és a
`git rebase --autosquash` külön felismeri. A `-m` opció
használható a létrehozott commit napló-üzenetének kiegészítésére,
de a kiegészítő megjegyzés elvész, amint a "fixup!" commitot a
`git rebase --autosquash` beleolvasztja ("squasheli") a
_<commit>_-ba.
+
A `--fixup=amend:<commit>` által létrehozott commit hasonló, de a
címe helyette "amend!" előtaggal kezdődik. A _<commit>_
napló-üzenete átmásolódik az "amend!" commit napló-üzenetébe, és
megnyílik egy szerkesztőben, hogy finomítható legyen. Amikor a
`git rebase --autosquash` az "amend!" commitot beleolvasztja a
_<commit>_-ba, a _<commit>_ napló-üzenete lecserélődik az "amend!"
commit finomított napló-üzenetére. Hiba, ha az "amend!" commit
napló-üzenete üres, kivéve, ha az `--allow-empty-message` meg van
adva.
+
A `--fixup=reword:<commit>` a `--fixup=amend:<commit> --only`
rövidítése. Egy csak napló-üzenetet tartalmazó "amend!" commitot
hoz létre (figyelmen kívül hagyva az indexben stage-elt
változtatásokat). Amikor a `git rebase --autosquash` beleolvasztja,
lecseréli a _<commit>_ napló-üzenetét, minden más változtatás
nélkül.
+
Sem a "fixup!", sem az "amend!" commitok nem változtatják meg a
_<commit>_ szerzőségét, amikor a `git rebase --autosquash`
alkalmazza őket. Részletekért lásd a linkgit:git-rebase[1] leírását.

`--squash=<commit>`::
	Commit-üzenet összeállítása a `git rebase --autosquash` paranccsal
	való használatra. A commit-üzenet címe a megadott commitból
	származik, "squash! " előtaggal. Használható további
	commit-üzenet opciókkal is (`-m`/`-c`/`-C`/`-F`). Részletekért
	lásd a linkgit:git-rebase[1] leírását.

`--reset-author`::
	Amikor a `-C`/`-c`/`--amend` opciókkal együtt használják, vagy
	amikor egy ütköző cherry-pick után commitolsz, kijelenti, hogy a
	létrejövő commit szerzősége mostantól a commiterhez tartozik. Ez
	emellett megújítja a szerzői időbélyeget is.

`--short`::
	Dry-run esetén az output rövid formátumban ("short-format") jelenjen
	meg. Részletekért lásd a linkgit:git-status[1] leírását. Ez
	maga után vonja a `--dry-run`-t.

`--branch`::
	A branch és a tracking-információ megjelenítése akkor is, ha
	rövid formátumú a kimenet. Részletekért lásd a
	linkgit:git-status[1] leírását.

`--porcelain`::
	Dry-run esetén az output porcelain-kész formátumban jelenjen
	meg. Részletekért lásd a linkgit:git-status[1] leírását. Ez
	maga után vonja a `--dry-run`-t.

`--long`::
	Dry-run esetén az output hosszú formátumban ("long-format")
	jelenjen meg. Ez a linkgit:git-status[1] alapértelmezett
	kimenete. Ez maga után vonja a `--dry-run`-t.

`-z`::
`--null`::
	Amikor `short` vagy `porcelain` linkgit:git-status[1] kimenetet
	mutat, a fájlnév szó szerinti kiírása, és a bejegyzések
	lezárása _NUL_-lal _LF_ helyett. Ha nincs formátum megadva, ez
	maga után vonja a `--porcelain` kimeneti formátumot. A `-z`
	opció nélkül a "szokatlan" karaktereket tartalmazó fájlnevek
	idézőjelbe kerülnek, ahogy azt a `core.quotePath`
	konfigurációs változó leírja (lásd a linkgit:git-config[1]
	leírását).

`-F <file>`::
`--file=<file>`::
	A commit-üzenet átvétele a _<file>_-ból. Használj '-'-t, hogy
	az üzenetet a standard bemenetről olvasd be.

`--author=<author>`::
	A commit szerzőjének felülbírálása. Adj meg egy explicit
	szerzőt a szabványos `A U Thor <author@example.com>` formátum
	használatával. Egyébként a _<author>_ egy mintának tekintendő,
	és egy már létező, ilyen szerzőjű commit keresésére szolgál
	(azaz `git rev-list --all -i --author=<author>`); a commit
	szerzője ezután az így talált első commitból kerül átmásolásra.

`--date=<date>`::
	A commitban használt szerzői dátum felülbírálása.

`-m <msg>`::
`--message=<msg>`::
	A _<msg>_ használata commit-üzenetként.
	Ha több `-m` opció is meg van adva, az értékeik külön
	bekezdésekként lesznek összefűzve.
+
A `-m` opció kölcsönösen kizárja a `-c`, `-C` és `-F` opciókat.

`-t <file>`::
`--template=<file>`::
	A commit-üzenet szerkesztésekor a szerkesztő a _<file>_
	tartalmával induljon el. A `commit.template` konfigurációs
	változót gyakran használják arra, hogy ezt az opciót
	implicit módon adják meg a parancsnak. Ez a mechanizmus olyan
	projekteknél használható, amelyek néhány tippel szeretnék
	irányítani a résztvevőket, hogy mit és milyen sorrendben
	írjanak az üzenetbe. Ha a felhasználó az üzenet szerkesztése
	nélkül lép ki a szerkesztőből, a commit megszakad. Ennek nincs
	hatása, ha az üzenet más módon van megadva, például a `-m` vagy
	a `-F` opcióval.

include::signoff-option.adoc[]

`--trailer <token>[(=|:)<value>]`::
	Egy (_<token>_, _<value>_) pár megadása, amelyet trailerként kell
	alkalmazni. (Például a `git commit --trailer "Signed-off-by:C O Mitter \
	<committer@example.com>" --trailer "Helped-by:C O Mitter \
	<committer@example.com>"` hozzáadja a `Signed-off-by` és a
	`Helped-by` trailert a commit-üzenethez.)
	A `trailer.*` konfigurációs változók
	(linkgit:git-interpret-trailers[1]) használhatók annak
	meghatározására, hogy egy duplikált trailer kimarad-e, hol
	jelenjen meg az adott trailer a trailerek sorában, és egyéb
	részletek megadására.

`-n`::
`--verify`::
`--no-verify`::
	A `pre-commit` és a `commit-msg` hookok megkerülése.
	Lásd még a linkgit:githooks[5] leírását.

`--allow-empty`::
	Általában hiba, ha olyan commitot rögzítesz, amelynek fája
	pontosan megegyezik az egyetlen szülő commitjáéval, és a parancs
	megakadályozza, hogy ilyen commitot hozz létre. Ez az opció
	megkerüli ezt a biztonsági ellenőrzést, és elsősorban idegen
	SCM-interfész szkriptek általi használatra szolgál.

`--allow-empty-message`::
	Commit létrehozása üres commit-üzenettel, plumbing parancsok
	(mint a linkgit:git-commit-tree[1]) használata nélkül. Az
	`--allow-empty`-hez hasonlóan ez a parancs is elsősorban idegen
	SCM-interfész szkriptek általi használatra szolgál.

`--cleanup=<mode>`::
	Meghatározza, hogyan legyen megtisztítva a megadott commit-üzenet
	a commitolás előtt. A '<mode>' lehet `strip`, `whitespace`,
	`verbatim`, `scissors` vagy `default`.
+
--
`strip`::
	A kezdő és záró üres sorok, a sorvégi whitespace, a megjegyzések
	eltávolítása, és az egymást követő üres sorok összevonása.
`whitespace`::
	Ugyanaz, mint a `strip`, azzal a különbséggel, hogy a
	#-megjegyzések nem kerülnek eltávolításra.
`verbatim`::
	Az üzenet egyáltalán nem változik.
`scissors`::
	Ugyanaz, mint a `whitespace`, azzal a különbséggel, hogy minden,
	ami a lent található sortól kezdve (azt is beleértve) szerepel,
	levágásra kerül, ha az üzenetet szerkeszteni kell. A "`#`"
	testre szabható a `core.commentChar` beállítással.

		# ------------------------ >8 ------------------------

`default`::
	Ugyanaz, mint a `strip`, ha az üzenetet szerkeszteni kell.
	Egyébként ugyanaz, mint a `whitespace`.
--
+
Az alapértelmezés megváltoztatható a `commit.cleanup`
konfigurációs változóval (lásd a linkgit:git-config[1] leírását).

`-e`::
`--edit`::
	Lehetővé teszi a felhasználónak, hogy tovább szerkessze a
	_<file>_-ból (`-F <file>`), a parancssorból (`-m <message>`)
	vagy a _<commit>_-ból (`-C <commit>`) átvett üzenetet.

`--no-edit`::
	A kiválasztott commit-üzenet használata szerkesztő indítása
	nélkül. Például a `git commit --amend --no-edit` amendel egy
	commitot anélkül, hogy megváltoztatná a commit-üzenetét.

`--amend`::
	Az aktuális branch csúcsának lecserélése egy új commit
	létrehozásával. A rögzített fa a szokásos módon készül el
	(beleértve a `-i` és a `-o` opciók hatását és az explicit
	pathspecet is), és az eredeti commit üzenete kerül felhasználásra
	kiindulópontként üres üzenet helyett, ha a parancssorból nincs
	más üzenet megadva olyan opciókkal, mint a `-m`, `-F`, `-c`
	stb. Az új commitnak ugyanazok a szülei és ugyanaz a szerzője,
	mint az aktuálisnak (ezt a `--reset-author` opció
	felülbírálhatja).
+
--
Ez nagyjából egyenértékű az alábbival:

------
	$ git reset --soft HEAD^
	$ ... csinálj valami mást, hogy előálljon a megfelelő fa ...
	$ git commit -c ORIG_HEAD

------
de egy merge commit amendelésére is használható.
--
+
Meg kell értened az előzmények átírásának következményeit, ha egy
már publikált commitot amendelsz. (Lásd a "RECOVERING FROM UPSTREAM
REBASE" szakaszt a linkgit:git-rebase[1] leírásában.)

`--no-post-rewrite`::
	A `post-rewrite` hook megkerülése.

`-i`::
`--include`::
	Mielőtt az eddig stage-elt tartalomból commitot készítenél, a
	parancssorban megadott útvonalak tartalmának stage-elése is.
	Ez általában nem az, amit szeretnél, hacsak nem egy ütköző
	merge lezárásáról van szó.

`-o`::
`--only`::
	Commit létrehozása a parancssorban megadott útvonalak frissített
	munkakönyvtár-tartalmának felhasználásával, figyelmen kívül
	hagyva minden más útvonalra stage-elt tartalmat. Ez a `git
	commit` alapértelmezett működési módja, ha bármilyen útvonal
	meg van adva a parancssorban, ebben az esetben ez az opció
	elhagyható. Ha ez az opció a `--amend`-del együtt van megadva,
	akkor nem szükséges útvonalakat megadni, ami arra használható,
	hogy az utolsó commitot amendeld anélkül, hogy commitolnád a
	már stage-elt változtatásokat. Ha az `--allow-empty`-vel együtt
	van használva, útvonalak szintén nem szükségesek, és egy üres
	commit jön létre.

`--pathspec-from-file=<file>`::
	A pathspec átadása a _<file>_-ban a parancssori argumentumok
	helyett. Ha a _<file>_ pontosan `-`, akkor a standard bemenet
	kerül felhasználásra. A pathspec elemek _LF_-fel vagy
	_CR_/_LF_-fel vannak elválasztva. A pathspec elemek idézőjelbe
	tehetők, ahogy azt a `core.quotePath` konfigurációs változó
	leírja (lásd a linkgit:git-config[1] leírását). Lásd még a
	`--pathspec-file-nul` és a globális `--literal-pathspecs`
	opciókat.

`--pathspec-file-nul`::
	Csak a `--pathspec-from-file`-lal együtt van jelentése. A
	pathspec elemek _NUL_ karakterrel vannak elválasztva, és minden
	más karakter szó szerint értendő (beleértve a sortöréseket és
	az idézőjeleket is).

`-u[<mode>]`::
`--untracked-files[=<mode>]`::
	Nem követett fájlok megjelenítése.
+
--
A _<mode>_ paraméter opcionális (alapértelmezés: `all`), és a nem
követett fájlok kezelésének megadására szolgál; ha a `-u` nincs
használva, az alapértelmezés `normal`, azaz a nem követett fájlok
és könyvtárak megjelennek.

A lehetséges opciók:

`no`:: Nem jelenít meg nem követett fájlokat
`normal`:: Megjeleníti a nem követett fájlokat és könyvtárakat
`all`:: A nem követett könyvtárakon belüli egyes fájlokat is megjeleníti.

A `true` logikai érték minden szokásos írásmódja `normal`-ként,
a `false` pedig `no`-ként értendő.
Az alapértelmezés a `status.showUntrackedFiles` konfigurációs
változóval változtatható meg, amelyet a linkgit:git-config[1]
dokumentál.
--

`-v`::
`--verbose`::
	Egyesített diff megjelenítése a `HEAD` commit és a commitolásra
	kerülő tartalom között, a commit-üzenet sablon alján, hogy
	segítse a felhasználót a commit leírásában, emlékeztetve arra,
	milyen változtatásokat tartalmaz a commit.
	Vedd figyelembe, hogy ennek a diffnek a sorai nincsenek
	`#`-lal ellátva. Ez a diff nem lesz része a commit-üzenetnek.
	Lásd a `commit.verbose` konfigurációs változót a
	linkgit:git-config[1] leírásában.
+
Ha kétszer van megadva, emellett az egyesített diffet is megjeleníti
a commitolásra kerülő tartalom és a munkakönyvtár fájljai között,
azaz a követett fájlok unstaged változtatásait.

`-q`::
`--quiet`::
	A commit-összefoglaló üzenet elnyomása.

`--dry-run`::
	Nem hoz létre commitot, hanem megjeleníti a commitolandó
	útvonalak listáját, a helyi változtatásokkal rendelkező, de
	commit nélkül maradó útvonalakat, valamint a nem követett
	útvonalakat.

`--status`::
	A linkgit:git-status[1] kimenetének belefoglalása a commit-üzenet
	sablonjába, amikor egy szerkesztő segítségével készül a
	commit-üzenet. Alapértelmezésben be van kapcsolva, de a
	`commit.status` konfigurációs változóval felülbírálható.

`--no-status`::
	A linkgit:git-status[1] kimenetének kihagyása a commit-üzenet
	sablonjából, amikor egy szerkesztő segítségével készül az
	alapértelmezett commit-üzenet.

`-S[<key-id>]`::
`--gpg-sign[=<key-id>]`::
`--no-gpg-sign`::
	Commitok GPG-aláírása. A _<key-id>_ opcionális, és
	alapértelmezésben a commiter identitása; ha meg van adva, a
	kapcsolóhoz kell tapadnia szóköz nélkül. A `--no-gpg-sign`
	hasznos mind a `commit.gpgSign` konfigurációs változó, mind
	egy korábbi `--gpg-sign` felülbírálására.

`--`::
	Az ezt követő argumentumok ne opcióként legyenek értelmezve.

`<pathspec>...`::
	Amikor a _<pathspec>_ meg van adva a parancssorban, a
	pathspecnek megfelelő fájlok tartalmának commitolása, az
	indexhez már hozzáadott változtatások rögzítése nélkül. Ezeknek
	a fájloknak a tartalma emellett stage-elődik a következő
	commithoz is, a korábban stage-elt tartalom tetejére.
+
További részletekért lásd a 'pathspec' szócikket a
linkgit:gitglossary[7] leírásában.

EXAMPLES
--------
Amikor a saját munkádat rögzíted, a munkakönyvtáradban módosított
fájlok tartalma ideiglenesen egy "index" nevű staging area-ba kerül
tárolásra a `git add` paranccsal. Egy fájl visszaállítható – csak
az indexben, de a munkakönyvtárban nem – az utolsó commit
állapotára a `git restore --staged <file>` paranccsal, amely
gyakorlatilag visszavonja a `git add`-et, és megakadályozza, hogy e
fájl változtatásai részt vegyenek a következő commitban. Miután
ezekkel a parancsokkal fokozatosan felépítetted a commitolandó
állapotot, a `git commit` (útvonalnév-paraméter nélkül) segítségével
rögzítheted, ami eddig stage-elve lett. Ez a parancs legalapvetőbb
formája. Egy példa:

------------
$ edit hello.c
$ git rm goodbye.c
$ git add hello.c
$ git commit
------------

Ahelyett, hogy minden egyes változtatás után külön stage-elnéd a
fájlokat, megkérheted a `git commit`-ot, hogy vegye észre a
munkakönyvtáradban követett tartalmú fájlok változtatásait, és
végezze el helyetted a megfelelő `git add` és `git rm` műveleteket.
Vagyis ez a példa ugyanazt teszi, mint a korábbi példa, ha nincs
más változtatás a munkakönyvtáradban:

------------
$ edit hello.c
$ rm goodbye.c
$ git commit -a
------------

A `git commit -a` parancs először megnézi a munkakönyvtáradat,
észreveszi, hogy módosítottad a `hello.c`-t és eltávolítottad a
`goodbye.c`-t, majd elvégzi helyetted a szükséges `git add` és
`git rm` műveleteket.

Miután sok fájl változtatásait stage-elted, megváltoztathatod azt a
sorrendet, amelyben a változtatások rögzülnek, ha útvonalneveket adsz
meg a `git commit`-nak. Ha útvonalnevek vannak megadva, a parancs
olyan commitot készít, amely csak a megnevezett útvonalakon végzett
változtatásokat rögzíti:

------------
$ edit hello.c hello.h
$ git add hello.c hello.h
$ edit Makefile
$ git commit Makefile
------------

Ez egy olyan commitot készít, amely a `Makefile` módosítását
rögzíti. A `hello.c`-hez és a `hello.h`-hoz stage-elt változtatások
nem kerülnek bele a létrejövő commitba. Ugyanakkor a
változtatásaik nem vesznek el – továbbra is stage-elve maradnak,
csak visszatartva. A fenti sorozat után, ha a következőt teszed:

------------
$ git commit
------------

ez a második commit a várt módon rögzíti a `hello.c` és a
`hello.h` változtatásait.

Miután egy merge (a `git merge` vagy a `git pull` által
kezdeményezve) ütközések miatt megáll, a tisztán merge-elt
útvonalak már stage-elve vannak neked commitolásra, az ütközött
útvonalak pedig unmerged állapotban maradnak. Először a `git
status` paranccsal kellene ellenőrizned, mely útvonalak
ütköznek, és miután manuálisan javítottad őket a
munkakönyvtáradban, a szokásos módon, a `git add` paranccsal
stage-elnéd az eredményt:

------------
$ git status | grep unmerged
unmerged: hello.c
$ edit hello.c
$ git add hello.c
------------

Az ütközések feloldása és az eredmény stage-elése után a `git
ls-files -u` már nem említi az ütközött útvonalat. Amikor
végeztél, futtasd a `git commit` parancsot, hogy végül rögzítsd a
merge-öt:

------------
$ git commit
------------

Ahogy a saját változtatásaid rögzítésénél, itt is használhatod a
`-a` opciót, hogy gépelést spórolj meg. Az egyik különbség az, hogy
egy merge feloldása közben nem használhatod a `git commit`-ot
útvonalnevekkel a változtatások commitolási sorrendjének
megváltoztatására, mert a merge-öt egyetlen commitként kell
rögzíteni. Valójában a parancs megtagadja a futást, ha útvonalnevek
vannak megadva (de lásd a `-i` opciót).

COMMIT INFORMATION
------------------

A szerzői és a commiter információ a következő környezeti
változókból származik, ha be vannak állítva:

 * `GIT_AUTHOR_NAME`
 * `GIT_AUTHOR_EMAIL`
 * `GIT_AUTHOR_DATE`
 * `GIT_COMMITTER_NAME`
 * `GIT_COMMITTER_EMAIL`
 * `GIT_COMMITTER_DATE`

(megjegyzés: a "<", ">" és "\n" karakterek eltávolításra kerülnek)

A szerzői és a commiter nevek megállapodás szerint valamilyen
személynév-formát öltenek (azaz azt a nevet, amellyel más emberek
rád hivatkoznak), bár a Git nem kényszerít vagy követel meg
semmilyen konkrét formát. Tetszőleges Unicode használható, a fent
felsorolt megkötéseknek megfelelően. Ennek a névnek nincs hatása a
hitelesítésre; ehhez lásd a `credential.username` változót a
linkgit:git-config[1] leírásában.

Ha ezek a környezeti változók (részben) nincsenek beállítva, az
információ a `user.name` és `user.email` konfigurációs elemekből
származik, vagy ha ezek sincsenek jelen, akkor az `EMAIL` környezeti
változóból, vagy ha ez sincs beállítva, a rendszer felhasználónevéből
és a kimenő levelekhez használt hosztnévből (amelyet az
`/etc/mailname` fájlból vesz, és a teljesen minősített hosztnévre
esik vissza, ha ez a fájl nem létezik).

Az `author.name` és a `committer.name`, valamint a hozzájuk tartozó
e-mail-opciók felülbírálják a `user.name`-et és a `user.email`-t, ha
be vannak állítva, és őket magukat a környezeti változók bírálják
felül.

A tipikus használat az, hogy csak a `user.name` és a `user.email`
változókat állítod be; a többi opció bonyolultabb használati
esetekhez áll rendelkezésre.

:git-commit: 1
include::date-formats.adoc[]

DISCUSSION
----------

Bár nem kötelező, jó ötlet a commit-üzenetet egyetlen rövid
(legfeljebb 50 karakteres) sorral kezdeni, amely összefoglalja a
változtatást, majd egy üres sorral, és ezt követően egy alaposabb
leírással folytatni. A commit-üzenetben az első üres sorig terjedő
szöveg a commit címeként kezelendő, és ezt a címet a Git mindenhol
felhasználja. Például a linkgit:git-format-patch[1] e-mail-lé
alakítja a commitot, és a címet a Subject sorban, a commit többi
részét pedig a törzsben használja fel.

include::i18n.adoc[]

ENVIRONMENT AND CONFIGURATION VARIABLES
---------------------------------------
A commit napló-üzenetének szerkesztésére használt szerkesztő a
`GIT_EDITOR` környezeti változóból, a `core.editor` konfigurációs
változóból, a `VISUAL` környezeti változóból vagy az `EDITOR`
környezeti változóból kerül kiválasztásra (ebben a sorrendben).
Részletekért lásd a linkgit:git-var[1] leírását.

include::includes/cmd-config-section-rest.adoc[]

include::config/commit.adoc[]

HOOKS
-----
Ez a parancs futtathatja a `commit-msg`, a `prepare-commit-msg`, a
`pre-commit`, a `post-commit` és a `post-rewrite` hookokat. További
információért lásd a linkgit:githooks[5] leírását.

FILES
-----

`$GIT_DIR/COMMIT_EDITMSG`::
	Ez a fájl egy folyamatban lévő commit commit-üzenetét
	tartalmazza. Ha a `git commit` hiba miatt lép ki a commit
	létrehozása előtt, a felhasználó által megadott (pl. egy
	szerkesztő-munkamenetben beírt) commit-üzenet elérhető lesz
	ebben a fájlban, de a `git commit` következő meghívásakor
	felülíródik.

SEE ALSO
--------
linkgit:git-add[1],
linkgit:git-rm[1],
linkgit:git-mv[1],
linkgit:git-merge[1],
linkgit:git-commit-tree[1]

GIT
---
A linkgit:git[1] csomag része
