git-tag(1)
==========

NAME
----
git-tag - Tagek létrehozása, listázása, törlése vagy ellenőrzése


SYNOPSIS
--------
[synopsis]
git tag [-a | -s | -u <key-id>] [-f] [-m <msg> | -F <file>] [-e]
	[(--trailer <token>[(=|:)<value>])...]
	<tagname> [<commit> | <object>]
git tag -d <tagname>...
git tag [-n[<num>]] -l [--contains <commit>] [--no-contains <commit>]
	[--points-at <object>] [--column[=<options>] | --no-column]
	[--create-reflog] [--sort=<key>] [--format=<format>]
	[--merged <commit>] [--no-merged <commit>] [<pattern>...]
git tag -v [--format=<format>] <tagname>...

DESCRIPTION
-----------

Hozzáad egy tag-referenciát a `refs/tags/`-be, hacsak a `-d`/`-l`/`-v`
nincs megadva tagek törléséhez, listázásához vagy ellenőrzéséhez.

Hacsak a `-f` nincs megadva, a megnevezett tag még nem létezhet.

Ha a `-a`, `-s` vagy `-u <key-id>` egyike át van adva, a parancs egy
'tag' objektumot hoz létre, és tag-üzenetet igényel. Hacsak a
`-m <msg>` vagy `-F <file>` nincs megadva, egy szerkesztő indul, hogy a
felhasználó begépelje a tag-üzenetet.

Ha a `-m <msg>` vagy `-F <file>` vagy `--trailer <token>[=<value>]` meg
van adva, és a `-a`, `-s`, `-u <key-id>` hiányzik, a `-a` implikált.

Egyébként egy olyan tag-referencia jön létre, amely közvetlenül a
megadott objektumra mutat (azaz egy könnyűsúlyú tag).

Kriptográfiailag aláírt tagobjektum jön létre, amikor a `-s` vagy
`-u <key-id>` van használatban. Az aláíró backendet (GPG, X.509, SSH
stb.) a `gpg.format` konfigurációs változó vezérli, amely alapból
OpenPGP. Amikor a `-u <key-id>` nincs használatban, az aktuális
felhasználó committer-identitása kerül felhasználásra az aláírókulcs
megtalálásához. A `gpg.program` konfigurációs változó egyéni aláíró
bináris megadására szolgál.

A tagobjektumokat (amelyek a `-a`, `-s` vagy `-u`-val jönnek létre)
„annotált" tageknek nevezik; tartalmaznak egy létrehozási dátumot, a
tagelő nevét és e-mail-címét, egy tagelési üzenetet és egy opcionális
kriptográfiai aláírást. Míg egy „könnyűsúlyú" tag egyszerűen egy név
egy objektumhoz (általában egy commitobjektumhoz).

Az annotált tagek kiadáshoz valók, míg a könnyűsúlyú tagek privát vagy
ideiglenes objektumcímkékhez. Emiatt egyes git parancsok, amelyek
objektumokat neveznek meg (mint a `git describe`), alapból figyelmen
kívül hagyják a könnyűsúlyú tageket.


OPTIONS
-------
`-a`::
`--annotate`::
	Aláíratlan, annotált tagobjektumot készít

`-s`::
`--sign`::
	Kriptográfiailag aláírt taget készít, az alapértelmezett
	aláírókulcs használatával. A használt aláíró backend a `gpg.format`
	konfigurációs változótól függ. Az alapértelmezett kulcsot a backend
	határozza meg. A GPG esetén a committer e-mail-címén alapul, míg az
	SSH esetén lehet egy konkrét kulcsfájl vagy ágensidentitás. Lásd:
	linkgit:git-config[1].

`--no-sign`::
	Felülbírálja a `tag.gpgSign` konfigurációs változót, amely úgy van
	beállítva, hogy minden egyes tag aláírását kikényszerítse.

`-u <key-id>`::
`--local-user=<key-id>`::
	Kriptográfiailag aláírt taget készít a megadott kulccsal. A
	<key-id> formátuma és a használt backend a `gpg.format`
	konfigurációs változótól függ. Lásd: linkgit:git-config[1].

`-f`::
`--force`::
	Lecseréli a megadott nevű meglévő taget (hiba helyett)

`-d`::
`--delete`::
	Törli a megadott nevű meglévő tageket.

`-v`::
`--verify`::
	Ellenőrzi a megadott tagek kriptográfiai aláírását.

`-n<num>`::
	A `_<num>_` megadja, hogy az annotációból hány sor kerül kiírásra,
	ha van, a `-l` használatakor. Maga után vonja a `--list`-et.
+
Alapból egyetlen annotációs sor sem kerül kiírásra. Ha nincs szám
megadva a `-n`-hez, csak az első sor kerül kiírásra. Ha a tag nem
annotált, helyette a commit-üzenet jelenik meg.

`-l`::
`--list`::
	Kilistázza a tageket. Az opcionális `<pattern>...`-nal, pl.
	`git tag --list 'v-*'`, csak azokat a tageket listázza, amelyek
	illeszkednek a minta(ák)ra.
+
A `git tag` argumentumok nélküli futtatása szintén kilistázza az összes
taget. A minta egy shell helyettesítő karakter (azaz `fnmatch`(3)-mal
illesztve). Több minta is megadható; ha bármelyik illeszkedik, a tag
megjelenik.
+
Ez a kapcsoló implicit módon megadódik, ha bármely más listaszerű
kapcsoló, például a `--contains` meg van adva. A részletekért lásd az
egyes ilyen kapcsolók dokumentációját.

`--sort=<key>`::
	A megadott kulcs alapján rendez. A `-` előtaggal az érték szerint
	csökkenő sorrendben rendez. A `--sort=<key>` kapcsolót többször is
	használhatod, amely esetben az utolsó `_<key>_` lesz az elsődleges
	kulcs. Támogatja a "`version:refname`"-et vagy a "`v:refname`"-et is
	(a tagneveket verziókként kezeli). A "`version:refname`" rendezési
	sorrendjét a "`versionsort.suffix`" konfigurációs változó is
	befolyásolhatja.
	A támogatott kulcsok ugyanazok, mint a `git for-each-ref`-nél. A
	rendezési sorrend alapból a `tag.sort` változóhoz konfigurált érték,
	ha az létezik, egyébként pedig lexikografikus sorrend. Lásd:
	linkgit:git-config[1].

`--color[=<when>]`::
	Tiszteletben tartja a `--format` kapcsolóban megadott színeket. A
	`_<when>_` mezőnek az `always`, `never` vagy `auto` egyikének kell
	lennie (ha a `_<when>_` hiányzik, úgy viselkedik, mintha `always`
	lett volna megadva).

`-i`::
`--ignore-case`::
	A tagek rendezése és szűrése kis-nagybetűt nem különböztet meg.

`--omit-empty`::
	Nem ír ki sortörést a formázott refek után, ahol a formátum üres
	sztringgé fejlik ki.

`--column[=<options>]`::
`--no-column`::
	A tag-listát oszlopokban jeleníti meg. Az opciók szintaxisáért lásd
	a `column.tag` konfigurációs változót. Az opciók nélküli `--column`
	és `--no-column` az `always`-zel, ill. a `never`-rel egyenértékű.
+
Ez a kapcsoló csak akkor alkalmazható, amikor a tageket annotációs
sorok nélkül listázod.

`--contains [<commit>]`::
	Csak azokat a tageket listázza, amelyek tartalmazzák a
	`_<commit>_`-ot (`HEAD`, ha nincs megadva). Maga után vonja a
	`--list`-et.

`--no-contains [<commit>]`::
	Csak azokat a tageket listázza, amelyek nem tartalmazzák a
	`_<commit>_`-ot (`HEAD`, ha nincs megadva). Maga után vonja a
	`--list`-et.

`--merged [<commit>]`::
	Csak azokat a tageket listázza, amelyeknek a commitjai elérhetők a
	`_<commit>_`-ból (`HEAD`, ha nincs megadva).

`--no-merged [<commit>]`::
	Csak azokat a tageket listázza, amelyeknek a commitjai nem elérhetők
	a `_<commit>_`-ból (`HEAD`, ha nincs megadva).

`--points-at [<object>]`::
	Csak a `_<object>_` tagjeit listázza (`HEAD`, ha nincs megadva).
	Maga után vonja a `--list`-et.

`-m <msg>`::
`--message=<msg>`::
	A `_<msg>_`-t használja (bekérés helyett). Ha több `-m` kapcsoló van
	megadva, az értékeik külön bekezdésekként fűződnek össze. Maga után
	vonja a `-a`-t, ha a `-a`, `-s`, `-u <key-id>` egyike sincs megadva.

`-F <file>`::
`--file=<file>`::
	A tag-üzenetet a `_<file>_`-ból veszi. A `-`-t használva a
	standard bemenetről olvassa be az üzenetet. Maga után vonja a
	`-a`-t, ha a `-a`, `-s`, `-u <key-id>` egyike sincs megadva.

`--trailer <token>[(=|:)<value>]`::
	Megad egy (`_<token>_`, `_<value>_`) párt, amelyet trailerként kell
	alkalmazni. (pl. a `git tag --trailer "Custom-Key: value"` egy
	"Custom-Key" trailert ad a tag-üzenethez.) A `trailer.*`
	konfigurációs változók (linkgit:git-interpret-trailers[1]) annak
	meghatározására használhatók, hogy egy duplikált trailer
	kihagyódjon-e, hol jelenjen meg az egyes trailerek a trailerek
	sorában, és egyéb részletek.
	A trailerek a `git tag --list`-ben kinyerhetők a
	`--format="%(trailers)"` helyőrzővel.

`-e`::
`--edit`::
	Lehetővé teszi a `-F`-fel fájlból és a `-m`-mel a parancssorból
	vett üzenet további szerkesztését.

`--cleanup=<mode>`::
	Beállítja, hogyan takarítódik fel a tag-üzenet. A `_<mode>_` a
	`verbatim`, `whitespace` és `strip` egyike lehet. A `strip` mód az
	alapértelmezett. A `verbatim` mód egyáltalán nem változtatja meg az
	üzenetet, a `whitespace` csak a sorvégi/sor eleji whitespace-sorokat
	távolítja el, a `strip` pedig a whitespace-t és a kommentárt is
	eltávolítja.

`--create-reflog`::
	Reflogot hoz létre a taghez. Ahhoz, hogy globálisan engedélyezd a
	reflogokat a tagekhez, lásd a `core.logAllRefUpdates`-et a
	linkgit:git-config[1]-ben. A tagadott `--no-create-reflog` alak
	csak egy korábbi `--create-reflog`-ot bírál felül, de jelenleg nem
	tagadja a `core.logAllRefUpdates` beállítását.

`--format=<format>`::
	Egy sztring, amely a megjelenített tag-refből és az általa mutatott
	objektumból `%(fieldname)`-eket interpolál. A formátum ugyanaz, mint
	a linkgit:git-for-each-ref[1]-é. Ha nincs megadva, alapból
	`%(refname:strip=2)`.

_<tagname>_::
	A létrehozandó, törlendő vagy leírandó tag neve. Az új tagnévnek át
	kell mennie a linkgit:git-check-ref-format[1] által definiált összes
	ellenőrzésen. Ezen ellenőrzések némelyike korlátozhatja a tagnévben
	megengedett karaktereket.

_<commit>_::
_<object>_::
	Az objektum, amelyre az új tag hivatkozni fog, általában egy
	commit. Alapból `HEAD`.

CONFIGURATION
-------------
Alapból a `git tag` az alapértelmezettel-aláírás módban (`-s`) a
committer-identitásodat (`Your Name <your@email.address>` alakban)
használja egy kulcs megtalálásához. Ha másik alapértelmezett kulcsot
szeretnél használni, megadhatod a repository konfigurációjában a
következőképp:

-------------------------------------
[user]
    signingKey = <key-id>
-------------------------------------

Az aláíró backend a `gpg.format` konfigurációs változóval választható
ki, amely alapból `openpgp`. A többi támogatott formátum listájáért
lásd: linkgit:git-config[1].

Az egyes aláíró backendekhez használt program útvonala a
`gpg.<format>.program` konfigurációs változóval adható meg. Az `openpgp`
backendnél a `gpg.program` a `gpg.openpgp.program` szinonimájaként
használható. A részletekért lásd: linkgit:git-config[1].

A `pager.tag`-et csak tagek listázásakor veszi figyelembe, azaz amikor a
`-l` van használatban vagy implikálva. Alapból pagert használ.

A további részletekért és egyéb konfigurációs változókért lásd:
linkgit:git-config[1].

DISCUSSION
----------

[[_on_re_tagging]]
Az újratagelésről
~~~~~~~~~~~~~~~~~

Mit tegyél, amikor rossz commitot tagelsz, és újra szeretnél tagelni?

Ha soha nem pusholtál ki semmit, egyszerűen tageld újra. A `-f`-fel
cseréld le a régit. És kész is vagy.

De ha kipusholtál dolgokat (vagy mások közvetlenül is olvashatták a
repository-dat), akkor mások már látták a régi taget. Ebben az esetben
egyet a két dolog közül tehetsz:

. A józan dolog.
  Egyszerűen ismerd be, hogy elszúrtad, és használj másik nevet. Mások
  már láttak egy tagnevet, és ha megtartod ugyanazt a nevet, olyan
  helyzetbe kerülhetsz, hogy két embernek is van "version X"-e, de
  valójában 'különböző' "X"-eik vannak. Így egyszerűen nevezd el
  "X.1"-nek, és ennyi.

. Az őrült dolog.
  Tényleg az új verziót is "X"-nek akarod hívni, 'annak ellenére', hogy
  mások már látták a régit. Így egyszerűen használd újra a `git tag
  -f`-et, mintha a régit még nem publikáltad volna.

A Git azonban *nem* változtatja meg (és nem is szabadna) a tageket a
felhasználók háta mögött. Így ha valaki már megkapta a régi taget, egy
`git pull` a fádon nem szabad, hogy egyszerűen felülírassa vele a
régit.

Ha valaki egy kiadási taget kapott tőled, nem változtathatod meg
egyszerűen a tagjét úgy, hogy a sajátodat frissíted. Ez nagy biztonsági
probléma, abban az értelemben, hogy az embereknek meg KELL tudniuk
bízni a tag-neveikben. Ha tényleg az őrült dolgot akarod tenni, egyszerűen
be kell vallanod, és el kell mondanod az embereknek, hogy elrontottad.
Ezt egy nagyon nyilvános bejelentéssel teheted meg, amelyben ezt mondod:

------------
Ok, I messed up, and I pushed out an earlier version tagged as X. I
then fixed something, and retagged the *fixed* tree as X again.

If you got the wrong tag, and want the new one, please delete
the old one and fetch the new one by doing:

	git tag -d X
	git fetch origin tag X

to get my updated tag.

You can test which tag you have by doing

	git rev-parse X

which should return 0123456789abcdef.. if you have the new version.

Sorry for the inconvenience.
------------

Kicsit bonyolultnak tűnik ez? *Kell is*, hogy az legyen. Nincs mód arra,
hogy helyes legyen egyszerűen automatikusan „megjavítani". Az embereknek
tudniuk kell, hogy a tagjeik esetleg megváltoztak.


[[_on_automatic_following]]
Az automatikus követésről
~~~~~~~~~~~~~~~~~~~~~~~~~

Ha valaki más fáját követed, akkor nagy valószínűséggel
remote-tracking brancheket használsz (pl. `refs/remotes/origin/master`).
Általában szeretnéd a tageket a másik végről.

Másrészről, ha azért fetchelsz, mert egy egyszeri merge-et szeretnél
valaki mástól, jellemzően nem akarsz onnan tageket kapni. Ez gyakrabban
fordul elő a felső szinthez közeli embereknél, de nem korlátozódik
rájuk. Az egyszerű halandók, amikor egymástól pull-olnak, nem
feltétlenül akarnak automatikusan privát horgonypont-tageket kapni a
másik személytől.

A levelezőlistán a „please pull" üzenetek gyakran csak két információt
adnak: egy repo URL-t és egy branchnevet; ez úgy van kialakítva, hogy
könnyen kivágható-beilleszthető legyen egy `git fetch` parancssor
végére:

------------
Linus, please pull from

	git://git..../proj.git master

to get the following updates...
------------

ebből:

------------
$ git pull git://git..../proj.git master
------------

Ilyen esetben nem akarod automatikusan követni a másik személy tagjeit.

A Git egyik fontos aspektusa az elosztott természete, ami nagyrészt azt
jelenti, hogy nincs eleve „upstream" vagy „downstream" a rendszerben.
Első ránézésre a fenti példa látszólag arra utalhat, hogy a
tag-névteret az emberek felső rétegei birtokolják, és hogy a tagek csak
lefelé áramlanak, de ez nem így van. Csak azt mutatja, hogy a
használati minta határozza meg, hogy kit érdekelnek kinek a tagjei.

Egy egyszeri pull annak a jele, hogy egy commit-történet most átlépi a
határt az egyik embercsoport (pl. „azok, akiket elsősorban a kernel
hálózati része érdekel"), amelynek lehet saját tag-készlete (pl. „ez a
harmadik kiadásjelölt a hálózati csoporttól, amelyet a 2.6.21 kiadással
általános fogyasztásra javasolnak"), és egy másik embercsoport (pl.
„azok, akik különböző alrendszer-fejlesztéseket integrálnak") között. Az
utóbbiakat általában nem érdeklik a részletes tagek, amelyeket az előbbi
csoportban belsőleg használnak (ez az, amit a „belső" jelent). Ezért
kívánatos, hogy ebben az esetben ne kövessük automatikusan a tageket.

Könnyen lehet, hogy a hálózati emberek egymás közt szeretnék cserélni a
csoportjukon belüli tageket, de abban a munkafolyamatban nagy
valószínűséggel remote-tracking branchekkel követik egymás haladását.
Itt is jó dolog az a heurisztika, amely automatikusan követi az ilyen
tageket.


[[_on_backdating_tags]]
A tagek visszadátumozásáról
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ha importáltál néhány változást egy másik VCS-ből, és szeretnél tageket
hozzáadni a munkád főbb kiadásaihoz, hasznos, ha meg tudod adni a
tagobjektumba beágyazandó dátumot; az ilyen adat a tagobjektumban
befolyásolja például a tagek sorrendjét a gitweb felületen.

Ahhoz, hogy beállítsd a jövőbeli tagobjektumokban használt dátumot,
állítsd be a GIT_COMMITTER_DATE környezeti változót (lásd a lehetséges
értékek későbbi tárgyalását; a leggyakoribb alak a "YYYY-MM-DD HH:MM").

Például:

------------
$ GIT_COMMITTER_DATE="2006-10-02 10:31" git tag -s v1.0.1
------------

include::date-formats.adoc[]

FILES
-----

`$GIT_DIR/TAG_EDITMSG`::
	Ez a fájl egy folyamatban lévő annotált tag üzenetét tartalmazza.
	Ha a `git tag` egy hiba miatt kilép, mielőtt létrehozna egy
	annotált taget, akkor a felhasználó által egy szerkesztő-munkamenetben
	megadott tag-üzenet elérhető lesz ebben a fájlban, de a `git tag`
	következő hívása felülírhatja.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

:git-tag: 1
include::config/tag.adoc[]

NOTES
-----

include::ref-reachability-filters.adoc[]

SEE ALSO
--------
linkgit:git-check-ref-format[1].
linkgit:git-config[1].

GIT
---
A linkgit:git[1] csomag része
