git-receive-pack(1)
===================

NAME
----
git-receive-pack - A repositoryba pusholt tartalom fogadása


SYNOPSIS
--------
[verse]
'git receive-pack' <git-dir>

DESCRIPTION
-----------
A 'git send-pack' hívja meg, és a távoli oldalról betáplált információval
frissíti a repositoryt.

Ezt a parancsot a végfelhasználó általában nem hívja meg közvetlenül.
A protokoll felhasználói felülete a 'git send-pack' oldalán van, és a
programpár célja, hogy frissítéseket pusholjon egy remote repositoryba.
Pull műveletekhez lásd linkgit:git-fetch-pack[1].

A parancs lehetővé teszi sha1 refek (headek/tagek) létrehozását és
fast-forwardolását a távoli oldalon (szigorúan véve a lokális oldal az,
ahol a 'git-receive-pack' fut, de a send-pack oldalán ülő felhasználó
szemszögéből a remote-ot frissíti.  Össze vagy zavarodva?)

Az update és a post-update hookok használatára további, valós életből vett
példák találhatók a Documentation/howto könyvtárban.

A 'git-receive-pack' figyelembe veszi a receive.denyNonFastForwards config
opciót, amely megmondja neki, hogy elutasítsa-e egy ref frissítéseit, ha
azok nem fast-forwardok.

Számos további receive.* config opció áll rendelkezésre a viselkedésének
finomhangolásához, lásd linkgit:git-config[1].

OPTIONS
-------
<git-dir>::
	A repository, amelybe szinkronizálni kell.

--http-backend-info-refs::
	A linkgit:git-http-backend[1] használja a
	`$GIT_URL/info/refs?service=git-receive-pack` kérések kiszolgálására.
	Lásd a `--http-backend-info-refs`-et a linkgit:git-upload-pack[1]-ben.

--skip-connectivity-check::
	Megkerüli a kapcsolódási ellenőrzéseket, amelyek az elérhető objektumok
	tranzitív lezártjában lévő összes objektum létezését ellenőrzik. Ez a
	kapcsoló olyan szerverüzemeltetőknek szól, akik a saját
	objektum-kapcsolódási ellenőrzésüket a Giten kívül szeretnék
	megvalósítani. Ez olyan esetekben hasznos, amikor a szerveroldal további
	információt tud arról, hogyan használják a Gitet, és így bizonyos
	garanciákra támaszkodhat, hogy hatékonyabban számítsa ki az
	objektum-kapcsolódást, mint amit a Git maga meg tud tenni. Ennek a
	kapcsolónak a használata olyan megbízható külső mechanizmus nélkül,
	amely garantálja az elérhető objektumok teljes kapcsolódását, azzal a
	kockázattal jár, hogy megsérti a repositoryt, és általános esetben nem
	szabad használni.

PRE-RECEIVE HOOK
----------------
Mielőtt bármely ref frissülne, ha a $GIT_DIR/hooks/pre-receive fájl létezik
és végrehajtható, egyszer meghívódik, paraméterek nélkül.  A hook standard
bemenete frissítendő refenként egy sor lesz:

       sha1-old SP sha1-new SP refname LF

A refname érték a $GIT_DIR-hez képest relatív; pl. a master head esetén ez
"refs/heads/master".  Az egyes refname-ek előtti két sha1 érték a refname
frissítés előtti és utáni objektumneve.  A létrehozandó refeknél a
sha1-old 0\{40}-nel egyenlő, a törlendő refeknél a sha1-new 0\{40}-nel
egyenlő, egyébként a sha1-old és a sha1-new érvényes objektumok kell
legyenek a repositoryban.

Aláírt push elfogadásakor (lásd linkgit:git-push[1]) az aláírt
push-tanúsítvány egy blobban tárolódik, és a `GIT_PUSH_CERT` környezeti
változóból kérdezhető le az objektumneve.  Példáért lásd a `post-receive`
hook leírását.  Ezenkívül a tanúsítványt GPG-vel ellenőrzi, és az eredményt
a következő környezeti változókban exportálja:

`GIT_PUSH_CERT_SIGNER`::
	A push-tanúsítványt aláíró kulcs tulajdonosának neve és e-mail-címe.

`GIT_PUSH_CERT_KEY`::
	A push-tanúsítványt aláíró kulcs GPG kulcsazonosítója.

`GIT_PUSH_CERT_STATUS`::
	A push-tanúsítvány GPG-ellenőrzésének állapota, ugyanazzal a
	mnemonikkal, mint amit a `git log` parancscsalád `%G?` formátuma
	használ (lásd linkgit:git-log[1]).

`GIT_PUSH_CERT_NONCE`::
	A nonce-sztring, amelyet a folyamat kért az aláírótól, hogy vegye bele
	a push-tanúsítványba.  Ha ez nem egyezik a push-tanúsítvány "nonce"
	fejlécében rögzített értékkel, az arra utalhat, hogy a tanúsítvány egy
	érvényes tanúsítvány, amelyet egy külön "git push" munkamenetből
	játszanak vissza.

`GIT_PUSH_CERT_NONCE_STATUS`::
`UNSOLICITED`;;
	A "git push --signed" nonce-ot küldött, amikor nem kértük, hogy
	küldjön.
`MISSING`;;
	A "git push --signed" nem küldött nonce fejlécet.
`BAD`;;
	A "git push --signed" hamis nonce-ot küldött.
`OK`;;
	A "git push --signed" azt a nonce-ot küldte, amit kértünk tőle.
`SLOP`;;
	A "git push --signed" olyan nonce-ot küldött, amely eltér attól, amit
	most kértünk tőle, de egy korábbi munkamenetben.  Lásd a
	`GIT_PUSH_CERT_NONCE_SLOP` környezeti változót.

`GIT_PUSH_CERT_NONCE_SLOP`::
	A "git push --signed" olyan nonce-ot küldött, amely eltér attól, amit
	most kértünk tőle, de egy másik munkamenetben, amelynek a kezdési
	ideje ennyi másodperccel tér el az aktuális munkamenetétől.  Csak
	akkor van jelentése, ha a `GIT_PUSH_CERT_NONCE_STATUS` `SLOP`-ot mond.
	Olvass a `receive.certNonceSlop` változóról is a linkgit:git-config[1]-ben.

Ez a hook azelőtt hívódik meg, hogy bármely refname frissülne, és mielőtt
bármilyen fast-forward ellenőrzés lefutna.

Ha a pre-receive hook nem nulla kilépési állapottal lép ki, nem történik
frissítés, és az update, a post-receive és a post-update hook sem hívódik
meg.  Ez hasznos lehet a gyors kilépéshez, ha a frissítés nem támogatott.

Lásd lentebb a karantén környezetről szóló megjegyzéseket.

UPDATE HOOK
-----------
Mielőtt az egyes refek frissülnének, ha a $GIT_DIR/hooks/update fájl
létezik és végrehajtható, refenként egyszer meghívódik, három paraméterrel:

       $GIT_DIR/hooks/update refname sha1-old sha1-new

A refname paraméter a $GIT_DIR-hez képest relatív; pl. a master head
esetén ez "refs/heads/master".  A két sha1 argumentum a refname frissítés
előtti és utáni objektumneve.  Vedd figyelembe, hogy a hook a refname
frissítése előtt hívódik meg, így vagy a sha1-old 0\{40} (ami azt jelenti,
hogy még nincs ilyen ref), vagy meg kell egyeznie azzal, ami a refname-ben
rögzítve van.

A hooknak nem nulla állapottal kell kilépnie, ha meg akarja tiltani a
megnevezett ref frissítését.  Egyébként nullával kell kilépnie.

A hook sikeres végrehajtása (nulla kilépési állapot) nem biztosítja, hogy
a ref ténylegesen frissülni fog, ez csak előfeltétel.  Ezért nem jó ötlet
értesítéseket (pl. e-mailt) küldeni ebből a hookból.  Fontold meg helyette
a post-receive hook használatát.

POST-RECEIVE HOOK
-----------------
Miután az összes ref frissült (vagy megkísérelték a frissítésüket), ha
bármely ref-frissítés sikeres volt, és ha a $GIT_DIR/hooks/post-receive
fájl létezik és végrehajtható, egyszer meghívódik, paraméterek nélkül.  A
hook standard bemenete minden sikeresen frissített refhez egy sor lesz:

       sha1-old SP sha1-new SP refname LF

A refname érték a $GIT_DIR-hez képest relatív; pl. a master head esetén ez
"refs/heads/master".  Az egyes refname-ek előtti két sha1 érték a refname
frissítés előtti és utáni objektumneve.  A létrehozott refeknél a
sha1-old 0\{40}-nel egyenlő, a törölt refeknél a sha1-new 0\{40}-nel
egyenlő, egyébként a sha1-old és a sha1-new érvényes objektumok kell
legyenek a repositoryban.

A `GIT_PUSH_CERT*` környezeti változók megvizsgálhatók, ugyanúgy, mint a
`pre-receive` hookban, aláírt push elfogadása után.

Ezzel a hookkal könnyű a repository frissítéseit leíró e-maileket
generálni.  Ez a példaszkript refenként egy e-mail üzenetet küld, amely
felsorolja a repositoryba pusholt commitokat, és a jó aláírású aláírt
pushok push-tanúsítványait egy naplózó szolgáltatásba naplózza:

----
#!/bin/sh
# mail out commit update information.
while read oval nval ref
do
	if expr "$oval" : '0*$' >/dev/null
	then
		echo "Created a new ref, with the following commits:"
		git rev-list --pretty "$nval"
	else
		echo "New commits:"
		git rev-list --pretty "$nval" "^$oval"
	fi |
	mail -s "Changes to ref $ref" commit-list@mydomain
done
# log signed push certificate, if any
if test -n "${GIT_PUSH_CERT-}" && test ${GIT_PUSH_CERT_STATUS} = G
then
	(
		echo expected nonce is ${GIT_PUSH_NONCE}
		git cat-file blob ${GIT_PUSH_CERT}
	) | mail -s "push certificate from $GIT_PUSH_CERT_SIGNER" push-log@mydomain
fi
exit 0
----

A hook e meghívásából származó kilépési kódot figyelmen kívül hagyja,
ugyanakkor egy nem nulla kilépési kód hibaüzenetet generál.

Vedd figyelembe, hogy előfordulhat, hogy a refname-nek nincs sha1-new
értéke, amikor ez a hook fut.  Ez könnyen megtörténhet, ha egy másik
felhasználó módosítja a refet azután, hogy a 'git-receive-pack' frissítette,
de mielőtt a hook ki tudta volna értékelni.  Ajánlott, hogy a hookok a
sha1-new-ra támaszkodjanak a refname aktuális értéke helyett.

POST-UPDATE HOOK
----------------
Minden más feldolgozás után, ha legalább egy ref frissült, és ha a
$GIT_DIR/hooks/post-update fájl létezik és végrehajtható, akkor a
post-update meghívódik a frissült refek listájával.  Ezzel bármilyen
repository-szintű takarítási feladat megvalósítható.

A hook e meghívásából származó kilépési kódot figyelmen kívül hagyja; a
'git-receive-pack'-nek ezen a ponton már úgyis csak annyi dolga marad,
hogy maga is kilépjen.

Ez a hook használható például a `git update-server-info` futtatására, ha a
repository csomagolt, és dumb transzporton keresztül szolgálják ki.

----
#!/bin/sh
exec git update-server-info
----


QUARANTINE ENVIRONMENT
----------------------

Amikor a `receive-pack` objektumokat vesz át, azok egy ideiglenes
"quarantine" könyvtárba kerülnek a `$GIT_DIR/objects` könyvtáron belül, és
csak azután vándorolnak át a fő objektumtárba, hogy a `pre-receive` hook
befejeződött. Ha a push ez előtt meghiúsul, az ideiglenes könyvtár
teljesen törlődik.

Ennek van néhány felhasználó számára látható hatása és buktatója:

  1. Azok a pushok, amelyek a beérkező pack problémái, hiányzó objektumok
     vagy a `pre-receive` hook miatt hiúsulnak meg, nem hagynak hátra
     lemezen tárolt adatot. Ez általában segít megakadályozni, hogy az
     ismételt sikertelen pushok teleírják a lemezedet, de a hibakeresést
     nehezebbé teheti.

  2. A `pre-receive` hook által létrehozott bármely objektum a quarantine
     könyvtárban jön létre (és csak siker esetén vándorol át).

  3. A `pre-receive` hook MUST NOT frissítsen egyetlen refet sem úgy, hogy
     karanténba helyezett objektumokra mutasson. A repositoryhoz hozzáférő
     más programok nem fogják látni az objektumokat (és ha a pre-receive
     hook meghiúsul, azok a refek megsérülnének). Biztonsági okokból a
     `pre-receive`-en belülről érkező bármely ref-frissítés automatikusan
     elutasításra kerül.


SEE ALSO
--------
linkgit:git-send-pack[1], linkgit:gitnamespaces[7]

GIT
---
A linkgit:git[1] csomag része
