git-diff-tree(1)
================

NAME
----
git-diff-tree - Két fa (tree) objektumon keresztül talált blobok tartalmának és módjának összehasonlítása


SYNOPSIS
--------
[verse]
'git diff-tree' [--stdin] [-m] [-s] [-v] [--no-commit-id] [--pretty]
	      [-t] [-r] [-c | --cc] [--combined-all-paths] [--root] [--merge-base]
	      [<common-diff-options>] <tree-ish> [<tree-ish>] [<path>...]

DESCRIPTION
-----------
Két fa (tree) objektumon keresztül talált blobok tartalmát és módját hasonlítja össze.

Ha csak egyetlen <tree-ish> van megadva, a commit a szüleivel kerül összehasonlításra
(lásd lent a --stdin opciót).

Vegyük figyelembe, hogy a 'git diff-tree' képes felhasználni a commit objektumba
zárt fát is.

OPTIONS
-------
include::diff-options.adoc[]

<tree-ish>::
	Egy fa objektum azonosítója.

<path>...::
	Ha meg van adva, az eredmények a megadott pathspecek valamelyikére
	illeszkedő fájlok részhalmazára korlátozódnak.

-r::
	Rekurzió az alfákba.

-t::
	Magát a fa-bejegyzést is megjeleníti, az alfákon kívül. A -r-t
	implikálja.

--root::
	Ha a `--root` meg van adva, a kezdeti commit egy nagy létrehozási
	eseményként jelenik meg. Ez egyenértékű a NULL fával szembeni diffel.

--merge-base::
	Ahelyett, hogy közvetlenül hasonlítaná össze a <tree-ish>-eket, a
	két <tree-ish> közötti merge-alapot használja "előtte" oldalként.
	Két <tree-ish>-t kell megadni, és mindkettőnek commitnak kell lennie.

--stdin::
	Ha a `--stdin` meg van adva, a parancs nem a parancssorból veszi a
	<tree-ish> argumentumokat. Ehelyett a standard bemenetéről olvas be
	sorokat, amelyek vagy két <tree>-t, egy <commit>-ot, vagy egy
	<commit>-lista tartalmaznak. (Elválasztóként egyetlen szóközt
	használj.)
+
Ha két fa van megadva, az elsőt a másodikkal hasonlítja össze. Ha egyetlen
commit van megadva, a commitot a szüleivel hasonlítja össze. A további,
megadott commitok úgy kerülnek felhasználásra, mintha az első commit
szülei lennének.
+
Két fa összehasonlításakor mindkét fa azonosítója (szóközzel elválasztva,
és sortöréssel lezárva) kiíródik a különbség előtt. Commitok
összehasonlításakor az első (vagy egyetlen) commit azonosítója kerül
kiírásra, majd egy sortörés.
+
Az alábbi kapcsolók további hatással vannak a viselkedésre commitok
összehasonlításakor (de fák esetén nem).

-m::
	Alapértelmezés szerint a 'git diff-tree --stdin' nem mutatja a merge
	commitok különbségeit. E kapcsolóval megmutatja az adott commithoz
	tartozó, az összes szülőjéhez viszonyított különbségeket. Lásd még
	a `-c`-t is.

-s::
	Alapértelmezés szerint a 'git diff-tree --stdin' megmutatja a
	különbségeket, akár géppel olvasható formában (a `-p` nélkül), akár
	patch formában (a `-p`-vel). Ez a kimenet elnyomható. Csak a `-v`
	kapcsolóval együtt hasznos.

-v::
	E kapcsoló hatására a 'git diff-tree --stdin' a különbségek előtt a
	commit-üzenetet is megjeleníti.

include::pretty-options.adoc[]

--no-commit-id::
	A 'git diff-tree' adott esetben egy sort ír ki a commit
	azonosítójával. Ez a kapcsoló elnyomja a commit-azonosító kiírását.

-c::
	Ez a kapcsoló megváltoztatja a merge commit megjelenítésének módját
	(ami azt jelenti, hogy csak akkor hasznos, ha a parancsnak egyetlen
	<tree-ish>, vagy a `--stdin` van megadva). Egyidejűleg mutatja a
	különbségeket az egyes szülőktől a merge eredményéig, ahelyett hogy
	páronként, egyszerre egy szülő és az eredmény közötti diffet mutatná
	(ahogy azt a `-m` opció teszi). Továbbá csak azokat a fájlokat
	sorolja fel, amelyek az összes szülőhöz képest módosultak.

--cc::
	Ez a kapcsoló a `-c` opcióhoz hasonló módon megváltoztatja a merge
	commit patch-jének megjelenítését. Implikálja a `-c` és a `-p`
	opciókat, és tovább tömöríti a patch kimenetét azáltal, hogy kihagyja
	azokat az érdektelen hunkokat, amelyek tartalmának a szülőkben csak
	két változata van, és a merge eredménye módosítás nélkül az egyiket
	választja. Ha minden hunk érdektelen, sem maga a commit, sem a
	napló-üzenete nem jelenik meg, ahogy bármelyik másik "üres diff"
	esetben sem.

--combined-all-paths::
	Ez a kapcsoló hatására a kombinált diffek (amelyeket a merge
	commitoknál használ) az összes szülőtől megjelenítik a fájl nevét.
	Ezért csak akkor van hatása, ha a -c vagy a --cc meg van adva, és
	valószínűleg csak akkor hasznos, ha fájlnév-változásokat észlel
	(azaz ha átnevezés- vagy másolás-észlelést kértek).

--always::
	Megjeleníti magát a commitot és a napló-üzenetét akkor is, ha maga
	a diff üres.


include::pretty-formats.adoc[]

include::diff-format.adoc[]

GIT
---
A linkgit:git[1] csomag része
