git-gc(1)
=========

NAME
----
git-gc - Szükségtelen fájlok kitakarítása és a helyi repository optimalizálása


SYNOPSIS
--------
[verse]
'git gc' [--aggressive] [--auto] [--[no-]detach] [--quiet] [--prune=<date> | --no-prune] [--force] [--keep-largest-pack]

DESCRIPTION
-----------
Számos karbantartási feladatot végez a jelenlegi repository-n belül,
például fájlrevíziók tömörítését (a lemezterület csökkentése és a
teljesítmény növelése érdekében), a 'git add' korábbi hívásai során
esetleg létrejött elérhetetlen objektumok eltávolítását, a refek
csomagolását, a reflog, a rerere-metaadatok vagy az elavult munkakönyvtárak
nyesését. Frissíthet kiegészítő indexeket is, például a commit-graphot.

Amikor objektumokat létrehozó, gyakori porcelain műveletek futnak,
ellenőrzik, hogy a repository jelentősen megnőtt-e az utolsó
karbantartás óta, és ha igen, automatikusan lefuttatják a `git gc`-t.
A viselkedés kikapcsolásához lásd lentebb a `gc.auto` beállítást.

A `git gc` kézi futtatására csak akkor lehet szükség, ha úgy adsz
objektumokat egy repository-hoz, hogy nem futtatsz rendszeresen ilyen
porcelain parancsokat, ha egyszeri repository-optimalizálást végzel,
vagy pl. egy nem optimális tömeges import kitakarításához. Az import
esetéről lásd a "PACKFILE OPTIMIZATION" szakaszt a linkgit:git-fast-import[1] oldalon.

OPTIONS
-------

--aggressive::
	A 'git gc' általában nagyon gyorsan lefut, miközben jó
	lemezterület-kihasználtságot és teljesítményt nyújt.  Ez az opció
	ráveszi a 'git gc'-t, hogy agresszívebben optimalizálja a repository-t,
	cserébe sokkal több időt vesz igénybe.  Ennek az optimalizálásnak a
	hatásai többnyire tartósak. Részletekért lásd lentebb az "AGGRESSIVE" szakaszt.

--auto::
	Ezzel az opcióval a 'git gc' ellenőrzi, hogy szükség van-e
	bármilyen karbantartásra; ha nincs, munka végzése nélkül kilép.
+
Arról, hogy ez a heurisztika hogyan működik, lásd a `gc.auto` opciót
lentebb a "CONFIGURATION" szakaszban.
+
Amint a karbantartást olyan konfigurációs opciók korlátainak túllépése
váltja ki, mint a `gc.auto` és a `gc.autoPackLimit`, az összes többi
karbantartási feladat (pl. rerere, munkakönyvtárak, reflog...) is
végrehajtódik.

--detach::
--no-detach::
	Futás a háttérben, ha a rendszer támogatja. Ez az opció felülírja
	a `gc.autoDetach` konfigurációt.

--cruft::
--no-cruft::
	Az elérhetetlen objektumok lejáratásakor egy külön cruft packbe
	csomagolja őket, ahelyett, hogy laza objektumként tárolná. A `--cruft`
	alapból be van kapcsolva.

--max-cruft-size=<n>::
	Az elérhetetlen objektumok cruft packbe csomagolásakor korlátozza
	az új cruft packek méretét legfeljebb `<n>` bájtra. Felülír minden,
	a `gc.maxCruftSize` konfiguráción keresztül megadott értéket.
	Bővebben lásd a linkgit:git-repack[1] `--max-cruft-size`
	opcióját.

--expire-to=<dir>::
	Az elérhetetlen objektumok cruft packbe csomagolásakor a nyesett
	objektumokat (ha vannak) tartalmazó cruft packet a `<dir>` könyvtárba
	írja. Ennek az opciónak csak a `--cruft` opcióval együtt használva
	van hatása. Bővebb információért lásd a linkgit:git-repack[1]
	`--expire-to` opcióját.

--prune=<date>::
	A dátumnál régebbi laza objektumok nyesése (az alapértelmezés 2 hete,
	felülírható a `gc.pruneExpire` konfigurációs változóval).
	A --prune=now a laza objektumokat koruktól függetlenül nyesi, és
	növeli a sérülés kockázatát, ha egy másik folyamat egyidejűleg ír a
	repository-ba; lásd lentebb a "NOTES" szakaszt. A --prune alapból be
	van kapcsolva.

--no-prune::
	Ne nyessen egyetlen laza objektumot sem.

--quiet::
	Minden folyamatjelzés elnyomása.

--force::
	A `git gc` futásának kikényszerítése akkor is, ha esetleg egy másik
	`git gc` példány fut ezen a repository-n.

--keep-largest-pack::
	A legnagyobb nem cruft pack, a `.keep` fájllal megjelölt packek és
	a cruft pack(ek) kivételével minden pack egyetlen packbe lesz
	összevonva. Ha ezt az opciót használod, a `gc.bigPackThreshold`
	figyelmen kívül marad.

AGGRESSIVE
----------

Ha a `--aggressive` opció meg van adva, a linkgit:git-repack[1] a `-f`
kapcsolóval hívódik meg, ami viszont átadja a `--no-reuse-delta`-t a
linkgit:git-pack-objects[1]-nek. Ez eldobja a meglévő deltákat, és
újraszámolja őket, cserébe sokkal több időt fordítva az
újracsomagolásra.

Ennek a hatásai többnyire tartósak, pl. amikor packeket és laza
objektumokat egy másik packbe vonnak össze, az abban a packben lévő
meglévő delták újrahasználódhatnak, de számos olyan eset is van, amikor
inkább egy újabb pack nem optimális deltáját választjuk.

Ezenfelül a `--aggressive` megadása módosítja a linkgit:git-repack[1]-nek
átadott `--depth` és `--window` opciókat. Lásd lentebb a
`gc.aggressiveDepth` és `gc.aggressiveWindow` beállításokat. Nagyobb
ablakméret használatával nagyobb eséllyel találunk optimálisabb
deltákat.

Valószínűleg nem éri meg ezt az opciót egy adott repository-n használni
anélkül, hogy testre szabott teljesítmény-benchmarkokat futtatnál rajta.
Sokkal több időt vesz igénybe, és az eredményül kapott hely-/delta-
optimalizálás megérheti vagy sem. A legtöbb felhasználó és repository-juk
számára az a helyes kompromisszum, ha egyáltalán nem használják.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/gc.adoc[]

NOTES
-----

A 'git gc' nagyon igyekszik nem törölni olyan objektumokat, amelyekre
bárhol hivatkoznak a repository-dban. Konkrétan nemcsak a branchek és
tagek jelenlegi halmaza által hivatkozott objektumokat tartja meg, hanem
az index, a remote-tracking branchek, a reflogok (amelyek olyan branchek
commitjaira hivatkozhatnak, amelyeket később amendeltek vagy
visszatekertek) és bármi más által hivatkozottakat is a refs/* névtérben.
Vedd figyelembe, hogy egy objektumhoz csatolt jegyzet (amilyet a 'git
notes' hoz létre) nem járul hozzá az objektum életben tartásához. Ha arra
számítasz, hogy bizonyos objektumok törlődnek, de nem törlődnek,
ellenőrizd mindezeket a helyeket, és döntsd el, van-e értelme a te
esetedben eltávolítani azokat a hivatkozásokat.

Másrészről, amikor a 'git gc' egy másik folyamattal egyidejűleg fut,
fennáll a kockázata annak, hogy töröl egy olyan objektumot, amelyet a
másik folyamat használ, de még nem hozott rá létre hivatkozást. Ez
egyszerűen a másik folyamat hibáját okozhatja, vagy megsértheti a
repository-t, ha a másik folyamat később hivatkozást ad a törölt
objektumra. A Gitnek két olyan funkciója van, amely jelentősen enyhíti
ezt a problémát:

. Minden olyan objektum megmarad, amelynek módosítási ideje újabb a
  `--prune` dátumnál, mindennel együtt, ami elérhető belőle.

. A legtöbb művelet, amely objektumot ad az adatbázishoz, frissíti az
  objektum módosítási idejét, ha az már jelen van, hogy az #1 pont
  érvényes legyen.

Ezek a funkciók azonban nem érnek fel egy teljes megoldással, így azoknak
a felhasználóknak, akik egyidejűleg futtatnak parancsokat, együtt kell
élniük a sérülés némi kockázatával (ami a gyakorlatban alacsonynak tűnik).

HOOKS
-----

A 'git gc --auto' parancs lefuttatja a 'pre-auto-gc' hookot.  Bővebb
információért lásd a linkgit:githooks[5] oldalt.


SEE ALSO
--------
linkgit:git-prune[1]
linkgit:git-reflog[1]
linkgit:git-repack[1]
linkgit:git-rerere[1]

GIT
---
A linkgit:git[1] csomag része
