git-archimport(1)
=================

NAME
----
git-archimport - GNU Arch repository importálása Git-be


SYNOPSIS
--------
[verse]
'git archimport' [-h] [-v] [-o] [-a] [-f] [-T] [-D <depth>] [-t <tempdir>]
	       <archive>/<branch>[:<git-branch>]...

DESCRIPTION
-----------
Importál egy projektet egy vagy több GNU Arch repository-ból.
A megadott <archive>/<branch> paraméterek által meghatározott névtereken
belül követi a brancheket és a repository-kat. Ha nem találja meg azt a
remote branchet, amelyből egy merge származik, egyszerű, rendes commitként
importálja. Ha megtalálja, ahol csak lehet, merge-ként jelöli meg
(lásd a lenti tárgyalást).

A szkript elvárja, hogy megadd azokat a kulcsfontosságú gyökereket,
ahonnan elindíthatja az importot egy 'initial import' vagy 'tag' típusú
Arch commitból. A megadott gyökereken belül követi és importálja az új
brancheket.

Azt várja, hogy csak egyetlen projekttel foglalkozzon. Ha eltérő
gyökerű brancheket észlel, megtagadja a futást. Ebben az esetben
szerkeszd az <archive>/<branch> paramétereidet, hogy egyértelműen
meghatározzák az import hatókörét.

A 'git archimport' a háttérben nagymértékben a `tla`-t használja az Arch
repository eléréséhez.
Győződj meg róla, hogy a `tla` egy friss verziója elérhető a path-on. A
`tla`-nak ismernie kell azokat a repository-kat, amelyeket a 'git archimport'-nak
átadsz.

A kezdeti importhoz a 'git archimport' azt várja, hogy egy üres könyvtárban
találja magát. Ahhoz, hogy egy Arch-ot használó projekt fejlesztését
kövesd, futtasd újra a 'git archimport'-ot ugyanazokkal a paraméterekkel,
mint a kezdeti importnál, hogy inkrementális importokat végezz.

Bár a 'git archimport' megpróbál értelmes branchneveket létrehozni az
importált archívumokhoz, Git branchneveket kézzel is meg lehet adni.
Ehhez írj egy Git branchnevet minden <archive>/<branch> paraméter után,
kettősponttal elválasztva. Ily módon lerövidítheted az Arch branchneveket,
és az Arch zsargont Git zsargonra fordíthatod, például egy
"PROJECT{litdd}devo{litdd}VERSION" branch "master"-re való leképezésével.

Több Arch branch egyetlen Git branchhez társítása is lehetséges; az
eredmény csak akkor lesz igazán értelmes, ha az első branchbe nem
kerülnek commitok azután, hogy a második branch létrejött. Ennek ellenére
hasznos az időszakosan rotált Arch repository-k konvertálásához.


MERGES
------
Az Archból származó patch-merge adatokat a Gitben is a merge-ek
megjelölésére használjuk. A Gitet nem nagyon érdekli a patchek követése,
és csak akkor tekint egy merge-et merge-nek, ha egy branch magába
foglalja az összes commitot az elágazás pontja óta. Ennek eredményeként
a Git jó képet kap arról, mennyire tértek el egymástól a branchek. Az
import folyamat így elveszít némi patch-cserélési metaadatot.

Szerencsére amikor Archból importált brancheket próbálsz merge-elni,
a Git jó merge-alapot talál, és jó eséllyel azonosítja azokat a
patcheket, amelyeket a branchek között nem sorrendben cseréltek ki.

OPTIONS
-------

-h::
	Használat kiírása.

-v::
	Részletes kimenet.

-T::
	Sok tag. Minden commithoz létrehoz egy taget, amely tükrözi a
	commit nevét az Arch repository-ban.

-f::
	A gyors patchset-import stratégia használata. Ez nagy fáknál
	jelentősen gyorsabb lehet, de nem tud kezelni könyvtár-átnevezéseket
	vagy jogosultságváltozásokat. Az alapértelmezett stratégia lassú, de
	biztonságos.

-o::
	Ezt a korábbi 'git archimport' verziók által használt régi stílusú
	branchnevekkel való kompatibilitáshoz használd. A régi stílusú
	branchnevek category{litdd}branch alakúak voltak, míg az új stílusú
	branchnevek archive,category{litdd}branch{litdd}version alakúak.
	Mindkét esetben a parancssorban megadott nevek felülírják az
	automatikusan generáltakat.

-D <depth>::
	Követi a merge-származást, és megpróbálja importálni azokat a
	fákat, amelyekből merge-eltek. Adj meg 1-nél nagyobb mélységet,
	ha a patch-naplókat megnyesték.

-a::
	Megpróbálja automatikusan regisztrálni az archívumokat a
	`http://mirrors.sourcecontrol.net` címen.
	Ez különösen hasznos a -D opcióval együtt.

-t <tmpdir>::
	Felülírja az alapértelmezett tempdir-t.


<archive>/<branch>::
	<archive>/<branch> azonosító olyan formátumban, amelyet a
	`tla log` megért.


GIT
---
A linkgit:git[1] csomag része
