git-cvsexportcommit(1)
======================

NAME
----
git-cvsexportcommit - Egyetlen commit exportálása egy CVS checkoutba


SYNOPSIS
--------
[verse]
'git cvsexportcommit' [-h] [-u] [-v] [-c] [-P] [-p] [-a] [-d <cvsroot>]
	[-w <cvs-workdir>] [-W] [-f] [-m <msgprefix>] [<parent-commit>] <commit-id>


DESCRIPTION
-----------
Egy commitot exportál a Gitből egy CVS checkoutba, ezzel
megkönnyítve a patch-ek merge-elését egy Git repository-ból egy CVS
repository-ba.

Add meg a CVS checkout nevét a -w kapcsolóval, vagy futtasd a
parancsot a CVS munkapéldány gyökeréből. Az utóbbi esetben a GIT_DIR-t
be kell állítani. Lásd az alábbi példákat.

Igyekszik a biztonságos megoldást választani: ellenőrzi, hogy a fájlok
változatlanok és naprakészek-e a CVS checkoutban, és alapértelmezetten
nem commitol automatikusan.

Támogatja a fájlok hozzáadását, eltávolítását, valamint a bináris
fájlokat érintő commitokat.

Ha a commit egy merge commit, meg kell mondanod a 'git cvsexportcommit'
parancsnak, hogy melyik szülőhöz képest készüljön el a changeset.

OPTIONS
-------

-c::
	Automatikus commitolás, ha a patch tisztán alkalmazható volt. Nem
	commitol, ha bármelyik hunk alkalmazása sikertelen, vagy más
	probléma merült fel.

-p::
	Pedáns (paranoiás) legyen a patch-ek alkalmazásakor. A patch-et
	--fuzz=0 kapcsolóval hívja meg.

-a::
	Szerzőségi információ hozzáadása. Hozzáadja az Author sort, és a
	Committer-t (ha eltér a szerzőtől) az üzenethez.

-d::
	Egy alternatív CVSROOT beállítása használatra. Ez a CVS -d
	paraméterének felel meg. Ezt a felhasználók általában nem
	szeretnék beállítani, kivéve ha a CVS-t aszimmetrikus módon
	használják.

-f::
	A merge kikényszerítése, még akkor is, ha a fájlok nem naprakészek.

-P::
	A szülő commit kikényszerítése, még akkor is, ha az nem közvetlen
	szülő.

-m::
	A megadott előtag hozzáfűzése a commit-üzenet elejéhez. Hasznos
	patch-sorozatoknál és hasonlóknál.

-u::
	Az érintett fájlok frissítése a CVS repository-ból az exportálás
	megkísérlése előtt.

-k::
	A CVS kulcsszó-behelyettesítés visszafordítása (pl. a
	$Revision: 1.2.3.4$ ebből lesz: $Revision$) a CVS munkapéldányban a
	patch alkalmazása előtt.

-w::
	Az exportáláshoz használandó CVS checkout helyének megadása. Ehhez
	az opcióhoz nem szükséges a GIT_DIR beállítása a végrehajtás előtt,
	ha az aktuális könyvtár egy Git repository-n belül van. Az
	alapértelmezés a 'cvsexportcommit.cvsdir' értéke.

-W::
	Közli a cvsexportcommit-tal, hogy az aktuális munkakönyvtár nem
	csak egy Git checkout, hanem egyben a CVS checkout is. Ezért a
	Git a folytatás előtt visszaállítja a munkakönyvtárat a szülő
	commitra.

-v::
	Bőbeszédű (verbose) mód.

CONFIGURATION
-------------
cvsexportcommit.cvsdir::
	Az exportáláshoz használandó CVS checkout alapértelmezett helye.

EXAMPLES
--------

Egy patch merge-elése a CVS-be::
+
------------
$ export GIT_DIR=~/project/.git
$ cd ~/project_cvs_checkout
$ git cvsexportcommit -v <commit-sha1>
$ cvs commit -F .msg <files>
------------

Egy patch merge-elése a CVS-be (-c és -w opciók). A munkakönyvtár a Git repón belül van::
+
------------
	$ git cvsexportcommit -v -c -w ~/project_cvs_checkout <commit-sha1>
------------

Függőben lévő patch-ek automatikus merge-elése a CVS-be -- csak akkor, ha tényleg tudod, mit csinálsz::
+
------------
$ export GIT_DIR=~/project/.git
$ cd ~/project_cvs_checkout
$ git cherry cvshead myhead | sed -n 's/^+ //p' | xargs -l1 git cvsexportcommit -c -p -v
------------

GIT
---
A linkgit:git[1] csomag része
