git-web{litdd}browse(1)
=======================

NAME
----
git-web--browse - Git segédszkript webböngésző indításához

SYNOPSIS
--------
[verse]
'git web{litdd}browse' [<options>] (<URL>|<file>)...

DESCRIPTION
-----------

Ez a szkript, amennyire csak lehetséges, megpróbálja megjeleníteni az
argumentumként átadott URL-eket és FILE-okat HTML-oldalakként egy már
megnyitott webböngésző új lapjain.

Jelenleg a következő böngészők (vagy parancsok) támogatottak:

* firefox (ez az alapértelmezett X Window alatt, ha nem KDE-t használsz)
* iceweasel
* seamonkey
* iceape
* chromium (chromium-browser néven is támogatott)
* google-chrome (chrome néven is támogatott)
* konqueror (ez az alapértelmezett KDE alatt, lásd lent a 'Note about konqueror' részt)
* opera
* w3m (ez az alapértelmezett grafikus környezeteken kívül)
* elinks
* links
* lynx
* dillo
* open (ez az alapértelmezett Mac OS X GUI alatt)
* start (ez az alapértelmezett MinGW alatt)
* cygstart (ez az alapértelmezett Cygwin alatt)
* xdg-open

Egyéni parancsok is megadhatók.

OPTIONS
-------
-b <browser>::
--browser=<browser>::
	A megadott böngészőt használja. Szerepelnie kell a támogatott
	böngészők listájában.

-t <browser>::
--tool=<browser>::
	Ugyanaz, mint fent.

-c <conf.var>::
--config=<conf.var>::
	A CONF.VAR a Git konfigurációs fájljaiban lesz keresve. Ha be van
	állítva, akkor az értéke adja meg a használandó böngészőt.

CONFIGURATION VARIABLES
-----------------------

[[_conf_var_from_c_option_and_web_browser]]
A CONF.VAR (a -c opcióból) és a web.browser
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A webböngésző megadható egy konfigurációs változóval, amelyet a -c (vagy
--config) parancssori opcióval adsz át, vagy a `web.browser`
konfigurációs változóval, ha az előbbit nem használod.

browser.<tool>.path
~~~~~~~~~~~~~~~~~~~

Kifejezetten megadhatod a preferált böngésződ teljes elérési útját a
`browser.<tool>.path` konfigurációs változó beállításával. Például a
firefox abszolút elérési útját a 'browser.firefox.path' beállításával
konfigurálhatod. Egyébként a 'git web{litdd}browse' feltételezi, hogy az
eszköz elérhető a PATH-ban.

browser.<tool>.cmd
~~~~~~~~~~~~~~~~~~

Ha az opciókkal vagy konfigurációs változókkal megadott böngésző nincs
a támogatottak között, akkor a megfelelő `browser.<tool>.cmd`
konfigurációs változó lesz keresve. Ha ez a változó létezik, akkor a
'git web{litdd}browse' a megadott eszközt egyéni parancsként kezeli, és
shell eval-lal futtatja a parancsot az argumentumként átadott
URL-ekkel.

NOTE ABOUT KONQUEROR
--------------------

Amikor a 'konqueror'-t parancssori opció vagy konfigurációs változó
adja meg, elindítjuk a 'kfmclient'-et, hogy ha lehetséges, megpróbálja
megnyitni a HTML man page-et egy már megnyitott konqueror új lapján.

A konzisztencia kedvéért ezt a trükköt akkor is megpróbáljuk, ha a
'browser.konqueror.path' valami olyasmire van állítva, mint
`A_PATH_TO/konqueror`. Ez azt jelenti, hogy helyette a
`A_PATH_TO/kfmclient` indítását próbáljuk meg.

Ha tényleg a 'konqueror'-t szeretnéd használni, akkor valami ilyesmit
használhatsz:

------------------------------------------------
	[web]
		browser = konq

	[browser "konq"]
		cmd = A_PATH_TO/konqueror
------------------------------------------------

[[_note_about_git_config_global]]
Megjegyzés a git-config --global-ról
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Vedd figyelembe, hogy ezeket a konfigurációs változókat valószínűleg a
`--global` kapcsolóval érdemes beállítani, például így:

------------------------------------------------
$ git config --global web.browser firefox
------------------------------------------------

mivel valószínűleg inkább felhasználóspecifikusak, mint
repository-specifikusak. Erről bővebben lásd a linkgit:git-config[1]-et.

GIT
---
A linkgit:git[1] csomag része
