git-bundle(1)
=============

NAME
----
git-bundle - Objektumok és refek mozgatása archívumon keresztül


SYNOPSIS
--------
[verse]
'git bundle' create [-q | --quiet | --progress]
		    [--version=<version>] <file> <git-rev-list-args>
'git bundle' verify [-q | --quiet] <file>
'git bundle' list-heads <file> [<refname>...]
'git bundle' unbundle [--progress] <file> [<refname>...]

DESCRIPTION
-----------

„Bundle" fájlok létrehozása, kicsomagolása és kezelése. A bundle-öket
Git-objektumok "offline" átviteléhez használjuk, anélkül, hogy egy aktív
"szerver" ülne a hálózati kapcsolat másik végén.

Használhatók repository-k inkrementális és teljes biztonsági mentésének
elkészítésére is (lásd a "teljes biztonsági mentés" példát az
"EXAMPLES"-ben), valamint egy repository referenciáinak állapotát egy
másikba továbbítására (lásd a második példát).

A Git parancsok, amelyek fetch-elnek vagy más módon "olvasnak" olyan
protokollokon keresztül, mint az `ssh://` és a `https://`, bundle
fájlokon is tudnak működni. Lehetséges a linkgit:git-clone[1]-lel egy új
repository-t klónozni egy bundle-ből, a linkgit:git-fetch[1]-et
használni egy bundle-ből való fetch-eléshez, és a benne található
referenciákat listázni a linkgit:git-ls-remote[1]-lel. Nincs
megfelelő "írás" támogatás, azaz egy bundle-be való 'git push' nem
támogatott.

BUNDLE FORMAT
-------------

A bundle-ök `.pack` fájlok (lásd linkgit:git-pack-objects[1]), egy
fejléccel, amely jelzi, milyen referenciák találhatók a bundle-ben.

Ahogy magának a csomagolt archívumformátumnak, a bundle-öknek is
lehetnek önmagukban is teljes, vagy kizárásokkal létrehozott változatai.
Lásd az alábbi "OBJECT PREREQUISITES" szakaszt.

A revízió-kizárásokkal létrehozott bundle-ök "thin pack"-ek, amelyek a
`--thin` opcióval jönnek létre a linkgit:git-pack-objects[1]-ben, és a
`--fix-thin` opcióval kerülnek kicsomagolásra a
linkgit:git-index-pack[1]-ben.

Nincs olyan opció, amellyel "thick pack"-et lehetne létrehozni revízió-
kizárások használatakor, és a felhasználóknak nem is kell foglalkozniuk
ezzel a különbséggel. A "thin pack"-ek használatával a kizárásokkal
létrehozott bundle-ök mérete kisebb lesz. Az, hogy a háttérben "thin"-ek,
csupán érdekességként van itt megjegyezve, más dokumentációra utalva.

Bővebb részletekért lásd a linkgit:gitformat-bundle[5]-öt, a "thin pack"
tárgyalásáért pedig a linkgit:gitformat-pack[5]-öt.

OPTIONS
-------

create [options] <file> <git-rev-list-args>::
	Egy 'file' nevű bundle létrehozására szolgál. Ehhez a
	'<git-rev-list-args>' argumentumok szükségesek a bundle
	tartalmának meghatározásához. Az 'options' a `git bundle create`
	alparancsra jellemző opciókat tartalmazza. Ha a 'file' `-`, a
	bundle a stdoutra kerül kiírásra.

verify <file>::
	Annak ellenőrzésére szolgál, hogy egy bundle fájl érvényes-e, és
	tisztán alkalmazható-e az aktuális repository-ra. Ez magában
	foglalja a bundle formátumának ellenőrzését, valamint annak
	ellenőrzését, hogy az előfeltétel-commitok léteznek-e és teljesen
	össze vannak-e kapcsolva az aktuális repository-ban. Ezután a
	`git bundle` kiírja a hiányzó commitok listáját, ha vannak
	ilyenek. Végül kiírásra kerül a további képességekről, például az
	"objektumszűrésről" (object filter) szóló információ. Bővebb
	információért lásd a "Capabilities" szakaszt a
	linkgit:gitformat-bundle[5]-ben. A kilépési kód siker esetén
	nulla, de nem nulla, ha a bundle fájl érvénytelen. Ha a 'file'
	`-`, a bundle a stdinről kerül beolvasásra.

list-heads <file>::
	Listázza a bundle-ben meghatározott referenciákat. Ha egy
	referencialista követi, csak a megadottakra illeszkedő
	referenciák kerülnek kiírásra. Ha a 'file' `-`, a bundle a
	stdinről kerül beolvasásra.

unbundle <file>::
	Átadja a bundle-ben lévő objektumokat a 'git index-pack'-nek a
	repository-ban való tárolás céljából, majd kiírja az összes
	meghatározott referencia nevét. Ha meg van adva egy
	referencialista, csak a listán szereplőkre illeszkedő referenciák
	kerülnek kiírásra. Ez a parancs valójában plumbing, és csak a
	'git fetch' általi meghívásra szánt. Ha a 'file' `-`, a bundle a
	stdinről kerül beolvasásra.

<git-rev-list-args>::
	Egy argumentumlista, amelyet a 'git rev-parse' és a 'git
	rev-list' elfogad (és amely tartalmaz egy megnevezett refet,
	lásd alább a SPECIFYING REFERENCES-t), és amely meghatározza a
	továbbítandó objektumokat és referenciákat. Például a
	`master~10..master` azt eredményezi, hogy az aktuális master
	referencia csomagolásra kerül az összes olyan objektummal együtt,
	amely a 10. ős-commitja óta hozzáadásra került. Nincs explicit
	korlát a csomagolható referenciák és objektumok számára.


[<refname>...]::
	Egy referencialista, amellyel korlátozható, mely referenciák
	kerülnek elérhetőként jelentésre. Ez elsősorban a 'git fetch'
	számára hasznos, amely csak a kért referenciákat várja megkapni,
	nem feltétlenül a packben lévő összeset (ebben az esetben a
	`git bundle` úgy viselkedik, mint a 'git fetch-pack').

--progress::
	A folyamat állapota alapértelmezésben a standard hibakimeneti
	adatfolyamra kerül jelentésre, amikor az egy terminálhoz van
	kötve, hacsak a -q nincs megadva. Ez a kapcsoló kikényszeríti a
	folyamat-állapot jelentését még akkor is, ha a standard
	hibakimeneti adatfolyam nem egy terminálra irányul.

--version=<version>::
	Megadja a bundle verzióját. A 2-es verzió a régebbi formátum, és
	csak SHA-1 repository-kkal használható; az újabb 3-as verzió
	olyan képességeket tartalmaz, amelyek bővítéseket tesznek
	lehetővé. Az alapértelmezés a legrégebbi támogatott formátum, a
	használt hash-algoritmus alapján.

-q::
--quiet::
	Ez a kapcsoló azt eredményezi, hogy a parancs nem jelenti a
	folyamatát a standard hibakimeneti adatfolyamon.

SPECIFYING REFERENCES
---------------------

A revízióknak referencianevekkel kell rendelkezniük ahhoz, hogy egy
bundle-be csomagolhatók legyenek. Alternatívaként a `--all` használható
az összes ref csomagolásához.

Egynél több referencia is csomagolható, és az előfeltétel-objektumok
több halmaza is megadható. A csomagolt objektumok azok, amelyek nem
találhatók meg az előfeltételek uniójában.

A `git bundle create` parancs feloldja neked a referenciák neveit,
ugyanazokat a szabályokat használva, mint a `git rev-parse
--abbrev-ref=loose`. Minden előfeltétel megadható explicit módon (pl.
`^master~10`), vagy implicit módon (pl. `master~10..master`,
`--since=10.days.ago master`).

Az összes alábbi egyszerű eset rendben van (feltéve, hogy van egy
"master" és egy "next" branchünk):

----------------
$ git bundle create master.bundle master
$ echo master | git bundle create master.bundle --stdin
$ git bundle create master-and-next.bundle master next
$ (echo master; echo next) | git bundle create master-and-next.bundle --stdin
----------------

És ezek is (valamint ugyanezek `--stdin` nélkül):

----------------
$ git bundle create recent-master.bundle master~10..master
$ git bundle create recent-updates.bundle master~10..master next~5..next
----------------

Egy olyan revíziónév vagy tartomány, amelynek jobb oldala nem oldható
fel referenciára, nem kerül elfogadásra:

----------------
$ git bundle create HEAD.bundle $(git rev-parse HEAD)
fatal: Refusing to create empty bundle.
$ git bundle create master-yesterday.bundle master~10..master~5
fatal: Refusing to create empty bundle.
----------------

OBJECT PREREQUISITES
--------------------

Bundle-ök létrehozásakor lehetőség van olyan önmagában is teljes bundle
létrehozására, amely kicsomagolható egy közös történet nélküli
repository-ban is, valamint negatív revíziók megadására a történet
korábbi részeiben szükséges objektumok kizárásához.

Ha egy olyan revíziót adunk meg a `git bundle create`-nek, mint a
`new`, az egy olyan bundle fájlt hoz létre, amely tartalmazza a `new`
revízióból elérhető összes objektumot. Az a bundle bármely
repository-ban kicsomagolható, hogy megkapjuk a `new` revízióhoz
vezető teljes történetet:

----------------
$ git bundle create full.bundle new
----------------

Egy olyan revízió-tartomány, mint az `old..new`, egy olyan bundle
fájlt eredményez, amelynél az `old` revíziónak (és minden belőle
elérhető objektumnak) léteznie kell ahhoz, hogy a bundle
"kicsomagolható" legyen:

----------------
$ git bundle create full.bundle old..new
----------------

Egy önmagában is teljes, előfeltételek nélküli bundle bárhová
kicsomagolható, akár egy üres repository-ba is, vagy klónozható belőle
(azaz `new`, de nem `old..new`).

Nyugodtan lehetünk óvatosak, ami azt eredményezi, hogy a bundle fájl
olyan objektumokat is tartalmaz, amelyek már megvannak a célban, mivel
ezek figyelmen kívül maradnak a célnál történő kicsomagoláskor.

Ha ugyanazt a refhalmazt szeretnéd megkapni, mint amit egy közvetlenül
a forrás repository-ból történő klónozás adna, használd a
`--branches --tags`-et a `<git-rev-list-args>`-hoz.

A `git bundle verify` paranccsal ellenőrizhető, hogy a fogadó
repository-dban megvannak-e a bundle-höz szükséges előfeltétel-commitok.

EXAMPLES
--------

Két esetet fogunk tárgyalni:

1. Egy repository teljes biztonsági mentésének elkészítése
2. Egy repository történetének átvitele egy másik gépre, amikor a két
   gép között nincs közvetlen kapcsolat

Először nézzük meg a repository teljes biztonsági mentését. A
következő parancs abban az értelemben készít teljes biztonsági
mentést a repository-ról, hogy az összes ref bekerül a bundle-be:

----------------
$ git bundle create backup.bundle --all
----------------

De vedd figyelembe újra, hogy ez csak a refekre vonatkozik, azaz csak
azokat a refeket és az azokból elérhető commitokat foglalod bele. Nem
foglalod bele az egyéb helyi állapotot, mint az index tartalma, a
munkakönyvtár, a stash, a repository-specifikus konfiguráció, a hookok,
stb.

Ezt a repository-t később helyreállíthatod például a
linkgit:git-clone[1] használatával:

----------------
$ git clone backup.bundle <new directory>
----------------

A következő példához tegyük fel, hogy át akarod vinni a történetet egy
R1 repository-ból az A gépen egy másik, R2 repository-ba a B gépen.
Bármi is legyen az ok, az A és a B közötti közvetlen kapcsolat nem
megengedett, de valamilyen mechanizmussal (CD, e-mail, stb.) át tudunk
mozgatni adatokat A-ból B-be. Az R2-t az R1-ben lévő master branchen
végzett fejlesztéssel akarjuk frissíteni.

A folyamat elindításához először létrehozhatsz egy előfeltételek
nélküli bundle-t. Használhatsz egy taged, hogy megjegyezd, meddig a
commitig dolgoztad már fel, hogy később könnyű legyen a másik
repository-t egy inkrementális bundle-lel frissíteni:

----------------
machineA$ cd R1
machineA$ git bundle create file.bundle master
machineA$ git tag -f lastR2bundle master
----------------

Ezután átviszed a file.bundle-t a célgépre, B-re. Mivel ehhez a
bundle-höz nincs szükség semmilyen meglévő objektumra a
kicsomagoláshoz, létrehozhatsz egy új repository-t a B gépen a belőle
való klónozással:

----------------
machineB$ git clone -b master /home/me/tmp/file.bundle R2
----------------

Ez az eredményül kapott repository-ban definiálni fog egy "origin"
nevű remote-ot, amely lehetővé teszi a fetch-elést és a pull-olást a
bundle-ből. Az R2-ben lévő $GIT_DIR/config fájl a következőhöz hasonló
bejegyzést fog tartalmazni:

------------------------
[remote "origin"]
    url = /home/me/tmp/file.bundle
    fetch = refs/heads/*:refs/remotes/origin/*
------------------------

Az eredményül kapott mine.git repository frissítéséhez fetch-elhetsz
vagy pull-olhatsz, miután a /home/me/tmp/file.bundle-ben tárolt
bundle-t inkrementális frissítésekre cserélted.

Miután még dolgoztál egy kicsit az eredeti repository-ban, létrehozhatsz
egy inkrementális bundle-t a másik repository frissítéséhez:

----------------
machineA$ cd R1
machineA$ git bundle create file.bundle lastR2bundle..master
machineA$ git tag -f lastR2bundle master
----------------

Ezután átviszed a bundle-t a másik gépre, hogy lecseréld a
/home/me/tmp/file.bundle-t, majd pull-olsz belőle.

----------------
machineB$ cd R2
machineB$ git pull
----------------

Ha tudod, hogy meddig a commitig kellene meglenniük a szükséges
objektumoknak a fogadó repository-ban, ezt a tudást felhasználhatod az
előfeltételek megadásához, egy vágási pontot adva, amely korlátozza az
eredményül kapott bundle-be kerülő revíziókat és objektumokat. Az
előző példa a lastR2bundle taget használta erre a célra, de bármilyen
más opciót is használhatsz, amelyet a linkgit:git-log[1] parancsnak
adnál meg. Íme további példák:

Használhatsz egy mindkettőben jelen lévő taget:

----------------
$ git bundle create mybundle v1.0.0..master
----------------

Használhatsz időn alapuló előfeltételt:

----------------
$ git bundle create mybundle --since=10.days master
----------------

Használhatod a commitok számát:

----------------
$ git bundle create mybundle -10 master
----------------

Lefuttathatod a `git-bundle verify`-t, hogy lásd, ki tudsz-e csomagolni
egy olyan bundle-ből, amely egy előfeltétellel lett létrehozva:

----------------
$ git bundle verify mybundle
----------------

Ez felsorolja, mely commitoknak kell meglenniük nálad ahhoz, hogy ki
tudj csomagolni a bundle-ből, és hibával leáll, ha nincsenek meg.

Egy bundle a fogadó repository szemszögéből pontosan olyan, mint egy
rendes repository, amelyből fetch-el vagy pull-ol. Például
leképezhetsz referenciákat fetch-elés közben:

----------------
$ git fetch mybundle master:localRef
----------------

Azt is megnézheted, milyen referenciákat kínál:

----------------
$ git ls-remote mybundle
----------------

DISCUSSION
----------

Egy repository teljes biztonsági mentésének naiv módja valami olyasmi
használata, mint a `cp -r <repo> <destination>`. Ez nem ajánlott, mivel
a repository-ba írás történhet a másolási művelet közben. Ennek
következtében néhány fájl a `<destination>`-nél sérülhet.

Ezért ajánlott Git-eszközöket használni a repository-mentések
készítéséhez, akár ezzel a paranccsal, akár például a
linkgit:git-clone[1]-lel. De ne feledd, hogy ezek az eszközök nem
segítenek a refeken és a commitokon kívüli állapot mentésében. Más
szóval nem segítenek az index, a munkakönyvtár, a stash, a
repository-specifikus konfiguráció, a hookok stb. tartalmának
mentésében.

Lásd még a linkgit:gitfaq[7] "TRANSFERS" szakaszát a rendszerek közötti
fájlszinkronizációval kapcsolatos problémák tárgyalásához.

FILE FORMAT
-----------

Lásd linkgit:gitformat-bundle[5].

GIT
---
A linkgit:git[1] csomag része
