git-diff-files(1)
=================

NAME
----
git-diff-files - Összehasonlítja a munkakönyvtárban és az indexben lévő fájlokat


SYNOPSIS
--------
[verse]
'git diff-files' [-q] [-0 | -1 | -2 | -3 | -c | --cc] [<common-diff-options>] [<path>...]

DESCRIPTION
-----------
Összehasonlítja a munkakönyvtárban és az indexben lévő fájlokat.  Ha
útvonalak vannak megadva, csak a megnevezett útvonalakat hasonlítja
össze.  Egyébként az index összes bejegyzését összehasonlítja.  A
kimeneti formátum megegyezik a 'git diff-index' és a 'git diff-tree'
parancséval.

OPTIONS
-------
include::diff-options.adoc[]

-1 --base::
-2 --ours::
-3 --theirs::
-0::
	A diffet rendre a "base" verzióhoz, a "saját branch"-hez vagy a
	"másik branch"-hez képest készíti.  Ezekkel az opciókkal a
	merge-elt bejegyzésekhez tartozó diffek nem jelennek meg.
+
Alapértelmezés szerint a diff a saját branch-hez (-2) és a tisztán
feloldott útvonalakhoz képest készül.  A -0 opció megadásával a
merge-eletlen bejegyzésekhez tartozó diff-kimenet elhagyható, és
helyette csak az "Unmerged" felirat jelenik meg.

-c::
--cc::
	Ez összehasonlítja a 2. stage-et (saját branch), a 3. stage-et
	(másik branch) és a munkakönyvtárbeli fájlt, majd egy kombinált
	diffet ír ki, hasonlóan ahhoz, ahogyan a 'diff-tree' ezekkel a
	kapcsolókkal egy merge-commitot megjelenít.

-q::
	Csendben marad még a nem létező fájlok esetén is


include::diff-format.adoc[]

GIT
---
A linkgit:git[1] csomag része
