git-instaweb(1)
===============

NAME
----
git-instaweb - Azonnal böngészd a munka-repository-dat a gitwebben

SYNOPSIS
--------
[verse]
'git instaweb' [--local] [--httpd=<httpd>] [--port=<port>]
               [--browser=<browser>]
'git instaweb' [--start] [--stop] [--restart]

DESCRIPTION
-----------
Egy egyszerű szkript a `gitweb` és egy webszerver beállítására a helyi
repository böngészéséhez.

OPTIONS
-------

-l::
--local::
	Csak a helyi IP-hez (127.0.0.1) köti a webszervert.

-d::
--httpd::
	A végrehajtandó HTTP daemon parancssora. Itt parancssori
	opciók is megadhatók, a konfigurációs fájl pedig a
	parancssor végéhez kerül hozzáadásra. Jelenleg az apache2, a
	lighttpd, a mongoose, a plackup, a python és a webrick
	támogatott.
	(Alapértelmezés: lighttpd)

-m::
--module-path::
	A modul-útvonal (csak akkor szükséges, ha a httpd Apache).
	(Alapértelmezés: /usr/lib/apache2/modules)

-p::
--port::
	A portszám, amelyhez a httpd-t kötni kell. (Alapértelmezés: 1234)

-b::
--browser::
	A gitweb-oldal megtekintéséhez használandó webböngésző. Ez
	átadásra kerül a 'git web{litdd}browse' segédszkriptnek, a
	gitweb-példány URL-jével együtt. Lásd a
	linkgit:git-web{litdd}browse[1]-et további információért erről.
	Ha a szkript sikertelen, az URL a stdout-ra kerül kiírásra.

start::
--start::
	Elindítja a httpd-példányt, és kilép. Szükség szerint
	újragenerálja a konfigurációs fájlokat egy új példány
	indításához.

stop::
--stop::
	Leállítja a httpd-példányt, és kilép. Ez nem generálja a
	konfigurációs fájlokat egy új példány indításához, és nem is
	zárja be a böngészőt.

restart::
--restart::
	Újraindítja a httpd-példányt, és kilép. Szükség szerint
	újragenerálja a konfigurációs fájlokat egy új példány
	indításához.

CONFIGURATION
-------------

Megadhatsz konfigurációt a .git/config fájlodban

-----------------------------------------------------------------------
[instaweb]
	local = true
	httpd = apache2 -f
	port = 4321
	browser = konqueror
	modulePath = /usr/lib/apache2/modules

-----------------------------------------------------------------------

Ha az `instaweb.browser` konfigurációs változó nincs beállítva,
helyette a `web.browser` lesz használva, ha az definiálva van. Lásd
a linkgit:git-web{litdd}browse[1]-et további információért erről.

SEE ALSO
--------
linkgit:gitweb[1]

GIT
---
A linkgit:git[1] csomag része
