git-hash-object(1)
==================

NAME
----
git-hash-object - Kiszámítja az objektumazonosítót, és opcionálisan létrehoz egy objektumot egy fájlból


SYNOPSIS
--------
[verse]
'git hash-object' [-t <type>] [-w] [--path=<file> | --no-filters]
		[--stdin [--literally]] [--] <file>...
'git hash-object' [-t <type>] [-w] --stdin-paths [--no-filters]

DESCRIPTION
-----------
Kiszámítja az objektumazonosító értékét egy megadott típusú
objektumhoz, a megnevezett fájl tartalmával (amely a munkakönyvtáron
kívül is lehet), és opcionálisan kiírja az eredményül kapott
objektumot az objektumadatbázisba. Az objektumazonosítóját a standard
kimenetre jelenti. Ha a <type> nincs megadva, alapértelmezés szerint
"blob".

OPTIONS
-------

-t <type>::
	Megadja a létrehozandó objektum típusát (alapértelmezés:
	"blob"). A lehetséges értékek: `commit`, `tree`, `blob` és `tag`.

-w::
	Ténylegesen kiírja az objektumot az objektumadatbázisba.

--stdin::
	Az objektumot a standard bemenetről olvassa be, nem egy
	fájlból.

--stdin-paths::
	Fájlneveket olvas be a standard bemenetről, soronként egyet, a
	parancssor helyett.

--path::
	Az objektumot úgy hasheli, mintha a megadott útvonalon lenne.
	A fájl helye nem befolyásolja közvetlenül a hash-értéket, de az
	útvonalat annak meghatározására használja, mely Git-szűrőket
	kell alkalmazni az objektumon, mielőtt az objektumadatbázisba
	kerülne. A szűrők alkalmazásának eredményeként a ténylegesen
	az objektumadatbázisba kerülő blob eltérhet a megadott fájltól.
	Ez az opció főként a munkakönyvtáron kívül elhelyezkedő
	ideiglenes fájlok vagy a stdin-ről olvasott fájlok hasheléséhez
	hasznos.

--no-filters::
	A tartalmat úgy hasheli, ahogy van, figyelmen kívül hagyva
	minden olyan bemeneti szűrőt, amelyet az attribútum-mechanizmus
	választott volna ki, beleértve a sorvég-konverziót is. Ha a
	fájl a standard bemenetről kerül beolvasásra, ez mindig
	implikálva van, hacsak a `--path` opció nincs megadva.

--literally::
	Lehetővé teszi a `--stdin` számára, hogy bármilyen szemetet
	hasheljen egy laza objektumba, amely egyébként nem menne át a
	szabványos objektum-elemzésen vagy a git-fsck ellenőrzésein.
	Hasznos magának a Gitnek a stressztesztelésére, vagy a
	valóságban előforduló sérült vagy hamis objektumok
	tulajdonságainak reprodukálására.

GIT
---
A linkgit:git[1] csomag része
