git-read-tree(1)
================

NAME
----
git-read-tree - Fa-információt olvas be az indexbe


SYNOPSIS
--------
[verse]
'git read-tree' [(-m [--trivial] [--aggressive] | --reset | --prefix=<prefix>)
		[-u | -i]] [--index-output=<file>] [--no-sparse-checkout]
		(--empty | <tree-ish1> [<tree-ish2> [<tree-ish3>]])


DESCRIPTION
-----------
Beolvassa a <tree-ish> által megadott fa-információt az indexbe, de
valójában *nem* frissíti egyik fájlt sem, amelyet „gyorsítótáraz".
(lásd: linkgit:git-checkout-index[1])

Opcionálisan a `-m` kapcsolóval merge-elhet egy fát az indexbe,
végrehajthat egy fast-forward (azaz kétutas) merge-et, vagy egy
háromutas merge-et. A `-m`-mel együtt használva a `-u` kapcsoló azt is
előidézi, hogy a work tree fájljait a merge eredményével frissítse.

Csak triviális merge-eket végez maga a 'git read-tree'. Amikor a
'git read-tree' visszatér, csak a konfliktusos útvonalak lesznek
nem merge-elt állapotban.

OPTIONS
-------
-m::
	Merge-et hajt végre, nem csak beolvasást. A parancs megtagadja a
	futást, ha az indexfájlodban nem merge-elt bejegyzések vannak, ami
	azt jelzi, hogy nem fejeztél be egy korábban elkezdett merge-et.

--reset::
	Ugyanaz, mint a -m, azzal a különbséggel, hogy a nem merge-elt
	bejegyzéseket eldobja, ahelyett, hogy hibázna. A `-u`-val együtt
	használva a working tree-változások vagy nem követett fájlok, ill.
	könyvtárak elvesztéséhez vezető frissítések nem szakítják meg a
	műveletet.

-u::
	Egy sikeres merge után frissíti a work tree fájljait a merge
	eredményével.

-i::
	Egy merge általában megköveteli, hogy mind az indexfájl, mind a
	working tree fájljai naprakészek legyenek az aktuális fejcommittal,
	hogy ne vesszenek el a helyi változások. Ez a kapcsoló letiltja a
	working tree-vel való ellenőrzést, és arra való, hogy olyan fák
	merge-ét hozd létre egy ideiglenes indexfájlba, amelyek nincsenek
	közvetlen kapcsolatban az aktuális working tree állapotával.

-n::
--dry-run::
	Ellenőrzi, hogy a parancs hibázna-e, anélkül, hogy ténylegesen
	frissítené az indexet vagy a working tree fájljait.

-v::
	Megjeleníti a fájlok checkoutolásának folyamatát.

--trivial::
	Korlátozza a 'git read-tree' általi háromutas merge-et, hogy csak
	akkor történjen meg, ha nincs szükség fájlszintű merge-elésre,
	ahelyett, hogy triviális esetekben feloldaná a merge-et, és a
	konfliktusos fájlokat feloldatlanul hagyná az indexben.

--aggressive::
	A 'git read-tree' általi háromutas merge általában a valóban
	triviális eseteknél feloldja a merge-et, a többi esetet pedig
	feloldatlanul hagyja az indexben, hogy a porcelainek különböző
	merge-politikákat valósíthassanak meg. Ez a kapcsoló ráveszi a
	parancsot, hogy néhány további esetet belsőleg feloldjon:
+
* amikor az egyik oldal eltávolít egy útvonalat, a másik oldal pedig
  módosítatlanul hagyja. A feloldás az útvonal eltávolítása.
* amikor mindkét oldal eltávolít egy útvonalat. A feloldás az útvonal
  eltávolítása.
* amikor mindkét oldal azonos módon ad hozzá egy útvonalat. A feloldás
  az útvonal hozzáadása.

--prefix=<prefix>::
	Megtartja az aktuális indextartalmat, és beolvassa a megnevezett
	tree-ish tartalmát a `<prefix>`-nél lévő könyvtár alá. A parancs
	megtagadja azoknak a bejegyzéseknek a felülírását, amelyek már
	léteztek az eredeti indexfájlban.

--index-output=<file>::
	Ahelyett, hogy az eredményeket a `$GIT_INDEX_FILE`-ba írná, a
	kapott indexet a megnevezett fájlba írja. Amíg a parancs működik,
	az eredeti indexfájl a szokásos mechanizmussal van zárolva. A
	fájlnak lehetővé kell tennie, hogy egy ideiglenes fájlból
	rename(2)-eljenek bele, amely a szokásos indexfájl mellett jön
	létre; ez jellemzően azt jelenti, hogy ugyanazon a fájlrendszeren
	kell lennie, mint magának az indexfájlnak, és írási jogosultsággal
	kell rendelkezned azokhoz a könyvtárakhoz, amelyekben az indexfájl
	és az indexkimeneti fájl található.

--recurse-submodules::
--no-recurse-submodules::
	A --recurse-submodules használata az összes aktív submodule
	tartalmát a szuperprojektben rögzített commitnak megfelelően
	frissíti, a read-tree rekurzív meghívásával, egyben a submodule-ok
	HEAD-jét is arra a commitra leválasztva állítja be.

--no-sparse-checkout::
	Letiltja a sparse checkout támogatását, még akkor is, ha a
	`core.sparseCheckout` true.

--empty::
	Ahelyett, hogy faobjektumo(ka)t olvasna be az indexbe, egyszerűen
	kiüríti azt.

-q::
--quiet::
	Csendes, elnyomja a visszajelző üzeneteket.

<tree-ish#>::
	A beolvasandó/merge-elendő faobjektumo(k) azonosítója.


MERGING
-------
Ha a `-m` meg van adva, a 'git read-tree' 3 fajta merge-et tud
végrehajtani: egyfás merge-et, ha csak 1 fa van megadva, fast-forward
merge-et 2 fával, vagy háromutas merge-et, ha 3 vagy több fa van
megadva.


[[_single_tree_merge]]
Egyfás merge
~~~~~~~~~~~~
Ha csak 1 fa van megadva, a 'git read-tree' úgy működik, mintha a
felhasználó nem adta volna meg a `-m`-et, azzal a különbséggel, hogy ha
az eredeti indexnek van bejegyzése egy adott útvonalnévhez, és az
útvonal tartalma egyezik a beolvasott fával, akkor az indexből származó
stat-információ kerül felhasználásra. (Más szóval az index stat()-jai
elsőbbséget élveznek a merge-elt fáéval szemben.)

Ez azt jelenti, hogy ha egy `git read-tree -m <newtree>`-t egy
`git checkout-index -f -u -a` követ, a 'git checkout-index' csak azt
checkoutolja ki, ami valóban megváltozott.

Ez arra szolgál, hogy elkerülje a felesleges hamis találatokat, amikor a
'git diff-files' a 'git read-tree' után fut.


[[_two_tree_merge]]
Kétfás merge
~~~~~~~~~~~~

Ezt jellemzően `git read-tree -m $H $M`-ként hívják meg, ahol $H az
aktuális repository fejcommitja, $M pedig egy idegen fa feje, amely
egyszerűen előrébb van, mint $H (azaz fast-forward helyzetben vagyunk).

Amikor két fa van megadva, a felhasználó a következőt közli a
'git read-tree'-vel:

     1. Az aktuális index és work tree $H-ból származik, de a
	felhasználónak lehetnek benne helyi változásai $H óta.

     2. A felhasználó $M-ig akar fast-forwardolni.

Ebben az esetben a `git read-tree -m $H $M` parancs biztosítja, hogy
egyetlen helyi változás se vesszen el ennek a „merge"-nek az
eredményeként. Íme a „carry forward" szabályok, ahol az „I" az indexet
jelöli, a „clean" azt jelenti, hogy az index és a work tree egybeesik, az
„exists"/„nothing" pedig egy útvonal jelenlétére utal a megadott
commitban:

....
	I                   H        M        Result
       -------------------------------------------------------
     0  nothing             nothing  nothing  (does not happen)
     1  nothing             nothing  exists   use M
     2  nothing             exists   nothing  remove path from index
     3  nothing             exists   exists,  use M if "initial checkout",
				     H == M   keep index otherwise
				     exists,  fail
				     H != M

        clean I==H  I==M
       ------------------
     4  yes   N/A   N/A     nothing  nothing  keep index
     5  no    N/A   N/A     nothing  nothing  keep index

     6  yes   N/A   yes     nothing  exists   keep index
     7  no    N/A   yes     nothing  exists   keep index
     8  yes   N/A   no      nothing  exists   fail
     9  no    N/A   no      nothing  exists   fail

     10 yes   yes   N/A     exists   nothing  remove path from index
     11 no    yes   N/A     exists   nothing  fail
     12 yes   no    N/A     exists   nothing  fail
     13 no    no    N/A     exists   nothing  fail

	clean (H==M)
       ------
     14 yes                 exists   exists   keep index
     15 no                  exists   exists   keep index

        clean I==H  I==M (H!=M)
       ------------------
     16 yes   no    no      exists   exists   fail
     17 no    no    no      exists   exists   fail
     18 yes   no    yes     exists   exists   keep index
     19 no    no    yes     exists   exists   keep index
     20 yes   yes   no      exists   exists   use M
     21 no    yes   no      exists   exists   fail
....

Minden „keep index" esetben az indexbejegyzés úgy marad, ahogy az
eredeti indexfájlban volt. Ha a bejegyzés nem naprakész, a
'git read-tree' a -u kapcsoló alatt működve érintetlenül hagyja a
work tree-ben lévő másolatot.

Amikor a 'git read-tree' ez a formája sikeresen visszatér, a
`git diff-index --cached $M` futtatásával láthatod, hogy az általad
végzett „local changes" közül melyeket vittél tovább. Vedd figyelembe,
hogy ez nem feltétlenül egyezik azzal, amit a `git diff-index --cached
$H` produkált volna egy ilyen kétfás merge előtt. Ez a 18-as és 19-es
eset miatt van – ha a $M változásai már megvoltak (pl. talán e-mailben
kaptad meg patch formájában), a `git diff-index --cached $H` a merge
előtt közölte volna veled a változást, de a kétfás merge után nem
jelenne meg a `git diff-index --cached $M` kimenetében.

A 3-as eset kissé trükkös, és magyarázatra szorul. Ennek a szabálynak az
eredménye logikailag az útvonal eltávolítása kellene legyen, ha a
felhasználó stage-elte az útvonal eltávolítását, majd egy új branchre
váltott. Ez azonban megakadályozná a kezdeti checkout megtörténtét, így a
szabály úgy módosul, hogy csak akkor használja M-et (az új fát), amikor
az index tartalma üres. Egyébként az útvonal eltávolítása megmarad, amíg
$H és $M megegyezik.

[[_3_way_merge]]
Háromutas merge
~~~~~~~~~~~~~~~
Minden „index" bejegyzésnek van két bitnyi „stage" állapota. A 0-s stage
a normál, és ez az egyetlen, amit bármilyen normál használat során
látnál.

Amikor viszont a 'git read-tree'-t három fával futtatod, a „stage" 1-nél
kezdődik.

Ez azt jelenti, hogy megteheted a következőt:

----------------
$ git read-tree -m <tree1> <tree2> <tree3>
----------------

és a végén egy olyan indexed lesz, amelyben az összes <tree1> bejegyzés
a „stage1"-ben, az összes <tree2> bejegyzés a „stage2"-ben, az összes
<tree3> bejegyzés pedig a „stage3"-ban van. Amikor egy másik branch
merge-ét végzed az aktuális branchbe, a közös ős fáját használjuk
<tree1>-ként, az aktuális branch fejét <tree2>-ként, a másik branch
fejét pedig <tree3>-ként.

Továbbá a 'git read-tree' rendelkezik egy speciális esetlogikával, amely
azt mondja: ha látsz egy fájlt, amely minden szempontból egyezik a
következő állapotokban, az „összeomlik" vissza „stage0"-ra:

   - a 2-es és 3-as stage egyforma; vedd az egyiket vagy a másikat (nem
     számít – ugyanaz a munka lett elvégezve a mi branchünkön a 2-es
     stage-ben és az ő branchükön a 3-as stage-ben)

   - az 1-es és a 2-es stage egyforma, a 3-as stage pedig más; vedd a
     3-as stage-et (a mi branchünk a 2-es stage-ben nem tett semmit az
     1-es stage-beli ős óta, míg az ő branchük a 3-as stage-ben dolgozott
     rajta)

   - az 1-es és a 3-as stage egyforma, a 2-es stage pedig más; vedd a
     2-es stage-et (mi tettünk valamit, míg ők nem tettek semmit)

A 'git write-tree' parancs megtagadja egy értelmetlen fa írását, és a
nem merge-elt bejegyzésekre panaszkodik, ha egyetlen olyan bejegyzést is
lát, amely nem 0-s stage-ben van.

Oké, ez az egész úgy hangzik, mint teljesen értelmetlen szabályok
gyűjteménye, de valójában pontosan ez az, amire szükséged van egy gyors
merge elvégzéséhez. A különböző stage-ek az „result tree"-t (0-s stage,
azaz „merged"), az eredeti fát (1-es stage, azaz „orig") és a két fát
képviselik, amelyeket merge-elni próbálsz (2-es, ill. 3-as stage).

Az 1-es, 2-es és 3-as stage sorrendje (és így a három <tree-ish>
parancssori argumentum sorrendje) jelentős, amikor egy háromutas
merge-et olyan indexfájllal kezdesz, amely már fel van töltve. Íme egy
vázlat arról, hogyan működik az algoritmus:

- ha egy fájl azonos formában létezik mind a három fában, a
  'git read-tree' automatikusan „merged" állapotba omlasztja.

- egy olyan fájl, amelynek _bármilyen_ különbsége van a három fában,
  külön bejegyzésekként marad az indexben. A „porcelain policy" dolga
  meghatározni, hogyan távolítsa el a nem 0-s stage-eket, és szúrjon be
  egy merge-elt verziót.

- az indexfájl mindezt az információt elmenti és visszaállítja, így
  inkrementálisan merge-elhetsz dolgokat, de amíg vannak 1/2/3-as
  stage-ben lévő bejegyzései (azaz „unmerged entries"), nem tudod
  kiírni az eredményt. Így most a merge algoritmus nagyon egyszerűvé
  válik:

  * sorban végigjárod az indexet, és figyelmen kívül hagysz minden 0-s
    stage-ben lévő bejegyzést, mivel azok már készen vannak.

  * ha találsz egy „stage1"-et, de nincs hozzá illő „stage2" vagy
    „stage3", tudod, hogy mindkét fából eltávolították (csak az eredeti
    fában létezett), és eltávolítod azt a bejegyzést.

  * ha találsz egymáshoz illő „stage2" és „stage3" fát, az egyiket
    eltávolítod, a másikat pedig „stage0" bejegyzéssé alakítod. Ha van
    hozzá illő „stage1" bejegyzés is, azt is eltávolítod. .. az összes
    normál triviális szabály ..

Ezt az utolsó lépést általában a 'git merge-index'-szel végeznéd a
mellékelt 'git merge-one-file'-lal. A szkript frissíti a working tree
fájljait, ahogy merge-eli az egyes útvonalakat, és egy sikeres merge
végén.

Amikor egy háromutas merge-et olyan indexfájllal kezdesz, amely már fel
van töltve, feltételezzük, hogy az a work tree-dben lévő fájlok
állapotát képviseli, és lehetnek akár olyan fájljaid is, amelyeknek a
változásai nincsenek rögzítve az indexfájlban. Továbbá feltételezzük,
hogy ez az állapot a 2-es stage fájból „származik". A háromutas merge
megtagadja a futást, ha olyan bejegyzést talál az eredeti indexfájlban,
amely nem egyezik a 2-es stage-gel.

Ez azért van, hogy megakadályozza, hogy elveszítsd a folyamatban lévő
munkád változásait, és hogy a véletlenszerű változásaidat egy nem
kapcsolódó merge commitba keverd. Szemléltetésképp tegyük fel, hogy
abból indulsz ki, amit utoljára commitoltak a repository-dba:

----------------
$ JC=`git rev-parse --verify "HEAD^0"`
$ git checkout-index -f -u -a $JC
----------------

Véletlenszerű szerkesztéseket végzel, a 'git update-index' futtatása
nélkül. Aztán észreveszed, hogy az „upstream" fád csúcsa előrébb jutott,
mióta pull-oltál róla:

----------------
$ git fetch git://.... linus
$ LT=`git rev-parse FETCH_HEAD`
----------------

A work tree-d még mindig a HEAD-eden ($JC) alapul, de van néhány
szerkesztésed azóta. A háromutas merge biztosítja, hogy $JC óta nem
adtál hozzá vagy módosítottál indexbejegyzéseket, és ha nem tetted,
akkor a helyes dolgot teszi. Így a következő sorozattal:

----------------
$ git read-tree -m -u `git merge-base $JC $LT` $JC $LT
$ git merge-index git-merge-one-file -a
$ echo "Merge with Linus" | \
  git commit-tree `git write-tree` -p $JC -p $LT
----------------

amit commitolnál, az egy tiszta merge $JC és $LT között, a folyamatban
lévő munkád változásai nélkül, és a work tree-d a merge eredményére
frissülne.

Ha viszont vannak olyan helyi változásaid a working tree-ben, amelyeket
ez a merge felülírna, a 'git read-tree' megtagadja a futást, hogy
megakadályozza a változásaid elvesztését.

Más szóval nem kell aggódnod amiatt, ami csak a working tree-ben
létezik. Amikor helyi változásaid vannak a projekt egy olyan részén,
amely nem érintett a merge-ben, a változásaid nem zavarják a merge-et,
és érintetlenül maradnak. Amikor *tényleg* zavarnak, a merge el sem
kezdődik (a 'git read-tree' hangosan panaszkodik, és hibázik anélkül,
hogy bármit módosítana). Ilyen esetben egyszerűen folytathatod, amit
éppen csináltál, és amikor a working tree-d készen áll (azaz befejezted
a folyamatban lévő munkádat), próbáld meg újra a merge-et.


SPARSE CHECKOUT
---------------

Megjegyzés: A skip-worktree képességek a linkgit:git-update-index[1]-ben
és a `read-tree`-ben megelőzték a linkgit:git-sparse-checkout[1]
bevezetését. A felhasználóknak azt javasoljuk, hogy a
sparse-checkout/skip-worktree jellegű igényekhez ezekkel a plumbing
parancsokkal szemben inkább a `sparse-checkout` parancsot használják. Az
alábbi információ azonban hasznos lehet azoknak a felhasználóknak, akik
megpróbálják megérteni a `sparse-checkout` parancs non-cone módjában
használt mintastílust.

A „Sparse checkout" lehetővé teszi a munkakönyvtár ritka feltöltését.
A skip-worktree bitet (lásd: linkgit:git-update-index[1]) használja
arra, hogy közölje a Gittel, hogy egy fájl a munkakönyvtárban
érdemes-e a megtekintésre.

A 'git read-tree' és más merge-alapú parancsok ('git merge', 'git
checkout'...) segíthetnek a skip-worktree bitmap karbantartásában és a
munkakönyvtár frissítésében. A `$GIT_DIR/info/sparse-checkout` a
skip-worktree referencia-bitmap definiálására szolgál. Amikor a
'git read-tree'-nek frissítenie kell a munkakönyvtárat, e fájl alapján
alaphelyzetbe állítja a skip-worktree bitet az indexben, amely ugyanazt a
szintaxist használja, mint a .gitignore fájlok. Ha egy bejegyzés
illeszkedik egy mintára ebben a fájlban, vagy a bejegyzés egy a working
tree-ben jelen lévő fájlnak felel meg, akkor a skip-worktree nem lesz
beállítva azon a bejegyzésen. Egyébként a skip-worktree be lesz
állítva.

Ezután összehasonlítja az új skip-worktree értéket az előzővel. Ha a
skip-worktree beállítottból beállítatlanná válik, visszaadja a
megfelelő fájlt. Ha beállítatlanból beállítottá válik, az a fájl
eltávolításra kerül.

Míg a `$GIT_DIR/info/sparse-checkout`-ot általában annak megadására
használják, mely fájlok vannak benne, azt is megadhatod, mely fájlok
_nincsenek_ benne, negáló minták használatával. Például az `unwanted`
fájl eltávolításához:

----------------
/*
!unwanted
----------------

Egy másik trükkös dolog a munkakönyvtár teljes újratöltése, amikor már
nem akarsz sparse checkoutot. Nem tilthatod le egyszerűen a „sparse
checkout"-ot, mert a skip-worktree bitek még mindig az indexben vannak,
és a munkakönyvtárad még mindig ritkán van feltöltve. A munkakönyvtárat
a `$GIT_DIR/info/sparse-checkout` fájl tartalmával kell újratöltened, a
következőképp:

----------------
/*
----------------

Ezután letilthatod a sparse checkoutot. A sparse checkout támogatása a
'git read-tree'-ben és a hasonló parancsokban alapból le van tiltva. A
`core.sparseCheckout`-ot be kell kapcsolnod ahhoz, hogy sparse checkout
támogatásod legyen.


SEE ALSO
--------
linkgit:git-write-tree[1], linkgit:git-ls-files[1],
linkgit:gitignore[5], linkgit:git-sparse-checkout[1]

GIT
---
A linkgit:git[1] csomag része
