git-patch-id(1)
===============

NAME
----
git-patch-id - Egyedi azonosítók számítása patchekhez

SYNOPSIS
--------
[synopsis]
git patch-id [--stable | --unstable | --verbatim]

DESCRIPTION
-----------
Patcheket olvas be a standard bemenetről, és kiszámítja a patch
ID-ket.

A "patch ID" nem más, mint egy patchhez tartozó fájldiffek SHA-1-jeinek
összege, a sorszámok figyelmen kívül hagyásával.  Ilyenformán
"észszerűen stabil", de ugyanakkor észszerűen egyedi is, azaz két
patch, amelynek ugyanaz a "patch ID"-je, szinte biztosan ugyanaz.

Ennek a parancsnak a fő felhasználási esete a valószínűsíthetően
duplikált commitok keresése.

A `git diff-tree --patch` kimenetének feldolgozásakor kihasználja azt a
tényt, hogy a patch elé a commit objektumneve van fűzve, és két
40 bájtos hexadecimális karakterláncot ad ki.  Az első karakterlánc a
patch ID, a második pedig a commit ID.  Ez felhasználható arra, hogy
egy commithalmazhoz vagy -tartományhoz leképezést készíts patch
ID-ből commit ID-be.

OPTIONS
-------

`--verbatim`::
	Kiszámítja a bemenet patch ID-jét úgy, ahogy meg van adva, nem
	távolít el semmilyen whitespace-t. Maga után vonja a `--stable`-t,
	és tiltja a `--unstable`-t.
+
Ez az alapértelmezés, ha a `patchid.verbatim` értéke `true`.

`--stable`::
	"Stabil" hashösszeget használ patch ID-ként. Ezzel az opcióval:
+
--
- A patchet alkotó fájldiffek átrendezése nem befolyásolja az ID-t.
  Konkrétan két patch, amelyet ugyanannak a két tree-nek az
  összehasonlításával állítottak elő az `-O<orderfile>` két különböző
  beállításával, ugyanazt a patch ID-aláírást eredményezi, így a
  kiszámított eredmény kulcsként használható a két tree közötti
  változásra vonatkozó metainformációk indexeléséhez.

- Az eredmény eltér a Git 1.9 és korábbi által előállított értéktől,
  illetve az "instabil" hash (lásd lent a `--unstable`-t)
  konfigurálásakor előállítottól - még akkor is, ha `-O<orderfile>`
  használata nélkül készített diff-kimeneten alkalmazzák, így az ilyen
  "instabil" vagy régi patch ID-ket tároló meglévő adatbázisok
  használhatatlanná válnak.

- A patchen belüli minden whitespace figyelmen kívül marad, és nem
  befolyásolja az ID-t.
--
+
Ez az alapértelmezés, ha a `patchid.stable` értéke `true`.

`--unstable`::
	"Instabil" hasht használ patch ID-ként. Ezzel az opcióval az
	előállított eredmény kompatibilis a Git 1.9 és korábbi által
	előállított patch ID-értékkel, és a whitespace figyelmen kívül
	marad.  Azok a felhasználók, akiknek már van a Git 1.9 és korábbi
	által előállított patch ID-ket tároló adatbázisuk (és nem kezelnek
	átrendezett patcheket), használhatják ezt az opciót.
+
Ez az alapértelmezés.

EXAMPLES
--------

A linkgit:git-cherry[1] megmutatja, hogy egy branch mely commitjainak
van patch ID szerint megegyező commitjuk valamely upstream branchen.
De csak azt mondja meg, hogy létezik-e ilyen commit vagy sem. Mi van, ha
tudni szeretnéd a releváns commitokat az upstreamben? Ezzel a paranccsal
leképezést készíthetünk a branched és az upstream branch között:

----
#!/bin/sh

upstream="$1"
branch="$2"
test -z "$branch" && branch=HEAD
limit="$3"
if test -n "$limit"
then
    tail_opts="$limit".."$upstream"
else
    since=$(git log --format=%aI "$upstream".."$branch" | tail -1)
    tail_opts=--since="$since"' '"$upstream"
fi
for_branch=$(mktemp)
for_upstream=$(mktemp)

git rev-list --no-merges "$upstream".."$branch" |
    git diff-tree --patch --stdin |
    git patch-id  --stable | sort >"$for_branch"
git rev-list --no-merges $tail_opts |
    git diff-tree --patch --stdin |
    git patch-id  --stable | sort >"$for_upstream"
join -a1 "$for_branch" "$for_upstream" | cut -d' ' -f2,3
rm "$for_branch"
rm "$for_upstream"
----

Az első oszlop most a branchedről származó commitot mutatja, a második
oszlop pedig a patch ID szerint megegyező commitot, ha létezik.

SEE ALSO
--------
linkgit:git-cherry[1]

GIT
---
A linkgit:git[1] csomag része
