git-mergetool{litdd}lib(1)
==========================

NAME
----
git-mergetool--lib - Közös Git merge-eszköz shell szkriptrészletek

SYNOPSIS
--------
[verse]
'TOOL_MODE=(diff|merge) . "$(git --exec-path)/git-mergetool{litdd}lib"'

DESCRIPTION
-----------

Ez nem egy olyan parancs, amelyet a végfelhasználó futtatni akarna.
Soha. Ez a dokumentáció azoknak szól, akik a porcelain-szerű
szkripteket tanulmányozzák, és/vagy újakat írnak.

A 'git-mergetool{litdd}lib' szkriptrészlet arra lett tervezve, hogy
más shell szkriptek forrásként (a `.`-tal) beolvassák, hogy
függvényeket állítsanak be a Git merge-eszközökkel való munkához.

A 'git-mergetool{litdd}lib' forrásként való beolvasása előtt a
szkriptednek be kell állítania a `TOOL_MODE`-ot, hogy meghatározza
az alábbi függvények működési módját. A 'diff' és a 'merge' érvényes
értékek.

FUNCTIONS
---------
get_merge_tool::
	Visszaad egy merge-eszközt. A visszatérési kód 1, ha egy
	kitalált merge-eszközt adtunk vissza, egyébként 0. A
	'$GIT_MERGETOOL_GUI' 'true'-ra állítható, hogy a megfelelő
	guitoolt keresse.

get_merge_tool_cmd::
	Visszaadja egy merge-eszköz egyéni parancsát.

get_merge_tool_path::
	Visszaadja egy merge-eszköz egyéni elérési útját.

initialize_merge_tool::
	Hatókörbe hozza a merge-eszköz-specifikus függvényeket, hogy
	használhatók vagy felülírhatók legyenek.

run_merge_tool::
	Elindít egy merge-eszközt az eszköznév és egy true/false
	jelző alapján, amely jelzi, hogy van-e jelen merge-alap.
	A '$MERGED', a '$LOCAL', a '$REMOTE' és a '$BASE' definiálva
	kell, hogy legyen a merge-eszköz számára.

GIT
---
A linkgit:git[1] csomag része
