git-cvsserver(1)
================

NAME
----
git-cvsserver - CVS szerver-emulátor a Githez

SYNOPSIS
--------

SSH:

[verse]
export CVS_SERVER="git cvsserver"
'cvs' -d :ext:user@server/path/repo.git co <HEAD_name>

pserver (/etc/inetd.conf):

[verse]
cvspserver stream tcp nowait nobody /usr/bin/git-cvsserver git-cvsserver pserver

Használat:

[verse]
'git-cvsserver' [<options>] [pserver|server] [<directory> ...]

DESCRIPTION
-----------

Ez az alkalmazás egy CVS-emulációs réteg a Git számára.

Erősen funkcionális. Azonban nem minden metódus van megvalósítva, és
azoknál a metódusoknál, amelyek meg vannak valósítva, nem minden
kapcsoló van megvalósítva.

A tesztelés mind a CLI CVS-kliens, mind az Eclipse CVS-plugin
használatával megtörtént. A legtöbb funkció mindkét klienssel jól
működik.

OPTIONS
-------

Ezeknek az opcióknak nyilvánvalóan csak akkor van értelme, ha a
szerveroldal kikényszeríti őket. Úgy lettek megvalósítva, hogy a
lehető legjobban hasonlítsanak a linkgit:git-daemon[1] opcióira.

--base-path <path>::
A 'path' hozzáfűzése a kért CVSROOT elé.

--strict-paths::
Nem engedélyezi az alkönyvtárakba való rekurzív bejárást.

--export-all::
Ne ellenőrizze a `gitcvs.enabled` beállítást a konfigurációban. Ennek
az opciónak a használatához meg kell adnod az engedélyezett
könyvtárak listáját is (lásd lent).

-V::
--version::
Verzióinformáció kiírása és kilépés.

-h::
-H::
--help::
Használati útmutató kiírása és kilépés.

<directory>::
A fennmaradó argumentumok egy könyvtárlistát adnak meg. Ha nincs
megadva könyvtár, akkor mindegyik engedélyezett. Az ezeken a
könyvtárakon belüli repository-k továbbra is megkövetelik a
`gitcvs.enabled` konfigurációs opciót, hacsak nincs megadva a
`--export-all`.

LIMITATIONS
-----------

A CVS-kliensek nem tudnak tag-elni, branch-elni vagy Git merge-eket
végrehajtani.

A 'git-cvsserver' a Git branch-eket CVS modulokra képezi le. Ez nagyon
eltér attól, amit a legtöbb CVS-felhasználó elvárna, mivel a CVS-ben a
modulok jellemzően egy vagy több könyvtárat reprezentálnak.

TELEPÍTÉS
---------

1. Ha CVS-elérést szeretnél biztosítani pserveren keresztül, adj hozzá
   egy sort az /etc/inetd.conf-hoz, valahogy így:
+
--
------
   cvspserver stream tcp nowait nobody git-cvsserver pserver

------
Megjegyzés: néhány inetd szerver lehetővé teszi a végrehajtható fájl
nevének megadását az argv[0] értékétől függetlenül (azaz attól a
névtől, amellyel a program szerint elindították). Ebben az esetben a
helyes sor az /etc/inetd.conf-ban így néz ki:

------
   cvspserver stream tcp nowait nobody /usr/bin/git-cvsserver git-cvsserver pserver

------

A pserver alapértelmezetten csak anonim hozzáférést biztosít. A
commitoláshoz létre kell hoznod pserver-fiókokat: egyszerűen adj hozzá
egy gitcvs.authdb beállítást azoknak a repository-knak a config
fájljában, amelyekhez engedélyezni szeretnéd az írást a cvsserveren
keresztül, például:

------

   [gitcvs]
	authdb = /etc/cvsserver/passwd

------
Ezeknek a fájloknak a formátuma a felhasználónév, amelyet a titkosított
jelszó követ, például:

------
   myuser:sqkNi8zPf01HI
   myuser:$1$9K7FzU28$VfF6EoPYCJEYcVQwATgOP/
   myuser:$5$.NqmNH1vwfzGpV8B$znZIcumu1tNLATgV2l6e1/mY8RzhUDHMOaVOeL1cxV3
------
Ezeknek a fájloknak az elkészítéséhez használhatod az Apache-hoz
mellékelt 'htpasswd' eszközt, de csak a -d opcióval (vagy -B-vel, ha a
rendszered támogatja).

Lehetőleg a platformodon a jelszó-hash létrehozását kezelő,
rendszerspecifikus segédprogramot használd (pl. mkpasswd Linuxon,
encrypt OpenBSD-n, vagy pwhash NetBSD-n), és illeszd be a megfelelő
helyre.

Ezután add meg a jelszavadat a pserver metóduson keresztül, például:

------
   cvs -d:pserver:someuser:somepassword@server:/path/repo.git co <HEAD_name>
------

SSH-eléréshez nincs szükség speciális beállításra, azon kívül, hogy a
Git eszközöknek szerepelniük kell a PATH-ban. Ha vannak olyan
klienseid, amelyek nem fogadják el a CVS_SERVER környezeti változót,
átnevezheted a 'git-cvsserver'-t `cvs`-re.

Megjegyzés: az újabb CVS-verziók (>= 1.12.11) azt is támogatják, hogy a
CVS_SERVER-t közvetlenül a CVSROOT-ban add meg, így:

------
   cvs -d ":ext;CVS_SERVER=git cvsserver:user@server/path/repo.git" co <HEAD_name>
------

Ennek az az előnye, hogy elmentődik a 'CVS/Root' fájljaidban, és nem
kell mindig aggódnod a megfelelő környezeti változó beállítása miatt.
A 'git-shell'-re korlátozott SSH-felhasználóknak nem kell felülírniuk
az alapértelmezést a CVS_SERVER-rel (és nem is szabad), mivel a
'git-shell' a `cvs`-t úgy érti, mint a 'git-cvsserver'-t, és úgy tesz,
mintha a másik oldal a valódi 'cvs'-t futtatná, jobban.
--
2. Minden egyes repóhoz, amelyet CVS-ből elérhetővé szeretnél tenni, szerkesztened
   kell a config-ot a repóban, és hozzá kell adnod a következő szakaszt.
+
--
------
   [gitcvs]
        enabled=1
        # optional for debugging
	logFile=/path/to/logfile

------
Megjegyzés: gondoskodnod kell arról, hogy minden felhasználó, aki
meghívja a 'git-cvsserver'-t, írási jogosultsággal rendelkezzen a
naplófájlhoz és az adatbázishoz is (lásd <<dbbackend,Adatbázis backend>>.
Ha SSH-n keresztül szeretnél írási hozzáférést biztosítani, a
felhasználóknak természetesen magához a Git repository-hoz is írási
jogosultsággal kell rendelkezniük.

Arról is gondoskodnod kell, hogy minden repository "bare" legyen
(Git-index fájl nélkül), hogy a `cvs commit` működjön. Lásd a
linkgit:gitcvs-migration[7] leírást.

[[configaccessmethod]]
Minden konfigurációs változó felülírható egy adott elérési módra
vonatkozóan is. Érvényes metódusnevek az "ext" (SSH-eléréshez) és a
"pserver". Az alábbi példakonfiguráció letiltaná a pserver-elérést,
miközben továbbra is engedélyezné az SSH-n keresztüli elérést.

------
   [gitcvs]
        enabled=0

   [gitcvs "ext"]
        enabled=1
------
--
3. Ha nem adtad meg közvetlenül a CVSROOT/CVS_SERVER-t a checkout
   parancsban, ami automatikusan elmentette volna a 'CVS/Root'
   fájljaidban, akkor explicit módon be kell állítanod ezeket a
   környezetedben. A CVSROOT-ot a szokásos módon kell beállítani, de a
   könyvtárnak a megfelelő Git repóra kell mutatnia. Mint fent, a
   'git-shell'-re _nem_ korlátozott SSH-kliensek esetén a CVS_SERVER-t
   'git-cvsserver'-re kell állítani.
+
--
------
   export CVSROOT=:ext:user@server:/var/git/project.git
   export CVS_SERVER="git cvsserver"
------
--
4. Azoknál az SSH-klienseknél, amelyek commitolni fognak, győződj meg
   róla, hogy a szerveroldali .ssh/environment fájljaik (vagy a
   .bashrc, stb., a saját shelljüknek megfelelően) exportálják a
   megfelelő értékeket a GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL,
   GIT_COMMITTER_NAME és GIT_COMMITTER_EMAIL számára. Azoknál az
   SSH-klienseknél, amelyeknek a bejelentkezési shellje bash, a
   .bashrc ésszerű alternatíva lehet.

5. A kliensek mostantól ki tudják checkoutolni a projektet. A CVS
   'module' nevét használd annak jelzésére, hogy melyik Git 'head'-et
   szeretnéd checkoutolni. Ez az újonnan checkoutolt könyvtárad nevét
   is beállítja, hacsak nem adsz meg mást a `-d <dir-name>` kapcsolóval.
   Például ez a 'master' branch-et checkoutolja a `project-master`
   könyvtárba:
+
------
   cvs co -d project-master master
------

[[dbbackend]]
ADATBÁZIS BACKEND
-----------------

A 'git-cvsserver' Git head-enként (azaz CVS modulonként) egy
adatbázist használ a repositoryra vonatkozó információk tárolására, a
konzisztens CVS revíziószámok fenntartása érdekében. Az adatbázist
minden commit után frissíteni kell (azaz írni kell bele).

Ha a commit közvetlenül a `git` használatával történik (a
'git-cvsserver' használata helyett), a frissítésnek a 'git-cvsserver'
következő repository-elérésekor kell megtörténnie, az elérési módtól
és a kért művelettől függetlenül.

Ez azt jelenti, hogy még ha csak olvasási hozzáférést biztosítasz is
(pl. a pserver metódus használatával), a 'git-cvsserver'-nek írási
hozzáféréssel kell rendelkeznie az adatbázishoz a megbízható
működéshez (ellenkező esetben gondoskodnod kell arról, hogy az
adatbázis mindig naprakész legyen, amikor a 'git-cvsserver' fut).

Alapértelmezetten SQLite adatbázisokat használ a Git könyvtárban,
`gitcvs.<module-name>.sqlite` néven. Vedd figyelembe, hogy az SQLite
backend íráskor ideiglenes fájlokat hoz létre ugyanabban a
könyvtárban, mint az adatbázisfájl, ezért lehet, hogy nem elég az
adatbázisfájlra vonatkozó írási jogosultságot megadni a
'git-cvsserver'-t használó felhasználóknak, hanem magára a könyvtárra
vonatkozó írási jogosultságot is meg kell adni nekik.

Az adatbázis nem regenerálható megbízhatóan, konzisztens formában,
miután a követett branch megváltozott. Példa: merge-elt branch-ek
esetén a 'git-cvsserver' csak a fejlesztés egyetlen branch-ét követi,
és egy 'git merge' után egy fokozatosan frissített adatbázis egy más
branch-et követhet, mint egy nulláról regenerált adatbázis, ami
inkonzisztens CVS revíziószámokat okoz. A `git-cvsserver`-nek nincs
módja megtudni, hogy melyik branch-et választotta volna, ha
fokozatosan futtatták volna a merge előtt. Tehát ha teljesen vagy
részlegesen (régi biztonsági mentésből) regenerálnod kell az
adatbázist, gyanakodnod kell a már meglévő CVS sandboxokra.

Az adatbázis backendet a következő konfigurációs változókkal
állíthatod be:

Az adatbázis backend beállítása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A 'git-cvsserver' a Perl DBI modult használja. Kérjük, ha megváltoztatod
ezeket a változókat, olvasd el annak dokumentációját is, különösen a
`DBI->connect()`-tel kapcsolatban.

gitcvs.dbName::
	Adatbázisnév. A pontos jelentés a kiválasztott adatbázis-
	drivertől függ, SQLite esetén ez egy fájlnév. Támogatja a
	változó-behelyettesítést (lásd lent). Nem tartalmazhat
	pontosvesszőt (`;`).
	Alapértelmezés: '%Ggitcvs.%m.sqlite'

gitcvs.dbDriver::
	A használt DBI driver. Bármilyen elérhető drivert megadhatsz
	itt, de lehet, hogy nem fog működni. A cvsserver a
	'DBD::SQLite'-tal van tesztelve, jelentések szerint működik a
	'DBD::Pg'-vel, és jelentések szerint *nem* működik a
	'DBD::mysql'-lel. Kérjük, kísérleti funkcióként kezeld. Nem
	tartalmazhat kettőspontot (`:`).
	Alapértelmezés: 'SQLite'

gitcvs.dbuser::
	Adatbázis-felhasználó. Csak akkor hasznos, ha a `dbDriver` be van
	állítva, mivel az SQLite-nak nincs fogalma adatbázis-
	felhasználókról. Támogatja a változó-behelyettesítést (lásd
	lent).

gitcvs.dbPass::
	Adatbázis-jelszó. Csak akkor hasznos, ha a `dbDriver` be van
	állítva, mivel az SQLite-nak nincs fogalma adatbázis-
	jelszavakról.

gitcvs.dbTableNamePrefix::
	Adatbázistábla-név-előtag. Támogatja a változó-behelyettesítést
	(lásd lent). Minden nem alfabetikus karakter aláhúzásjelre
	cserélődik.

Minden változó beállítható elérési módonként is, lásd <<configaccessmethod,fent>>.

Változó-behelyettesítés
^^^^^^^^^^^^^^^^^^^^^^^
A `dbDriver`-ben és a `dbUser`-ben a következő változókat használhatod:

%G::
	Git-könyvtárnév
%g::
	Git-könyvtárnév, amelyben minden karakter, az alfanumerikusak, a
	`.` és a `-` kivételével, `_`-ra cserélődik (ez megkönnyítheti a
	könyvtárnév fájlnévben való felhasználását, ha szükséges)
%m::
	CVS modul/Git head neve
%a::
	elérési mód (az "ext" vagy "pserver" egyike)
%u::
	A 'git-cvsserver'-t futtató felhasználó neve.
	Ha nem határozható meg a név, a
	numerikus uid kerül felhasználásra.

ENVIRONMENT
-----------

Ezek a változók bizonyos esetekben feleslegessé teszik a parancssori
opciók használatát, megkönnyítve a git-shellen keresztüli, korlátozott
használatot.

GIT_CVSSERVER_BASE_PATH::
	Ez a változó helyettesíti a --base-path argumentumát.

GIT_CVSSERVER_ROOT::
	Ez a változó egyetlen könyvtárat ad meg, helyettesítve a
	`<directory>...` argumentumlistát. A repository továbbra is
	megköveteli a `gitcvs.enabled` konfigurációs opciót, hacsak
	nincs megadva a `--export-all`.

Amikor ezek a környezeti változók be vannak állítva, a megfelelő
parancssori argumentumok nem használhatók.

ECLIPSE CVS-KLIENS MEGJEGYZÉSEK
-------------------------------

Egy checkout elkészítéséhez az Eclipse CVS-kliensével:

1. Válaszd a "Create a new project -> From CVS checkout" lehetőséget.
2. Hozz létre egy új helyet. A megfelelő protokoll kiválasztásának
   részleteiért lásd a lenti megjegyzéseket.
3. Böngészd az elérhető 'modules'-okat. Ez megadja a repository-ban
   lévő head-ek listáját. Onnan nem tudod böngészni a fát. Csak a
   head-eket.
4. Válaszd a `HEAD`-et, amikor megkérdezi, melyik branch-et/tag-et
   szeretnéd checkoutolni. Kapcsold ki a "launch commit wizard"
   opciót, hogy elkerüld a .project fájl commitolását.

Protokoll-megjegyzések: ha anonim hozzáférést használsz pserveren
keresztül, egyszerűen azt válaszd. Azoknak, akik SSH-elérést
használnak, az 'ext' protokollt kell választaniuk, és be kell
állítaniuk az 'ext' elérést a Preferences->Team->CVS->ExtConnection
panelen. Állítsd be a CVS_SERVER-t "`git cvsserver`"-re. Vedd
figyelembe, hogy a jelszótámogatás nem jó 'ext' használatakor,
mindenképpen SSH-kulcsokat érdemes beállítanod.

Alternatívaként egyszerűen használhatod az Eclipse által kínált, nem
szabványos extssh protokollt. Ebben az esetben a CVS_SERVER figyelmen
kívül marad, és le kell cserélned a cvs segédprogramot a szerveren
'git-cvsserver'-re, vagy módosítanod kell a `.bashrc`-det, hogy a
'cvs' meghívása valójában a 'git-cvsserver'-t hívja meg.

ISMERTEN MŰKÖDŐ KLIENSEK
------------------------

- CVS 1.12.9 Debianon
- CVS 1.11.17 MacOSX-en (Fink csomagból)
- Eclipse 3.0, 3.1.2 MacOSX-en (lásd az Eclipse CVS-kliens megjegyzéseket)
- TortoiseCVS

TÁMOGATOTT MŰVELETEK
--------------------

A normál használathoz szükséges összes művelet támogatott, beleértve
a checkout, diff, status, update, log, add, remove, commit
parancsokat.

A legtöbb, CVS tag-eket vagy revíziószámokat beolvasó CVS
parancsargumentum (jellemzően -r) működik, és bármilyen git refspec-et
is támogat (tag, branch, commit-azonosító, stb.). Azonban a
nem-alapértelmezett branch-ek CVS revíziószámai nincsenek jól
emulálva, és a cvs log egyáltalán nem mutat tag-eket vagy branch-eket.
(A nem fő branch-en lévő CVS revíziószámok felszínesen hasonlítanak a
CVS revíziószámokra, de valójában közvetlenül egy git commit-
azonosítót kódolnak, ahelyett hogy a branch-pont óta eltelt revíziók
számát reprezentálnák.)

Vedd figyelembe, hogy két módja van egy adott branch checkoutolásának.
Ahogy máshol is le van írva ezen az oldalon, a cvs checkout "module"
paramétere branch-névként kerül értelmezésre, és ez lesz a fő
branch. Ez marad a fő branch egy adott sandbox esetén, még akkor is,
ha ideiglenesen egy másik branch-et teszel sticky-vé a cvs
update -r paranccsal. Alternatívaként a -r argumentum jelezhet egy
másik branch-et, amelyet ténylegesen checkoutolni kell, még akkor is,
ha a modul továbbra is a "main" branch. Kompromisszumok (a jelenlegi
megvalósítás szerint): minden új "module" új adatbázist hoz létre a
lemezen, az adott modul előzményeivel, és az adatbázis létrehozása
után az adott fő branch elleni műveletek gyorsak. Vagy alternatívaként
a -r nem foglal extra lemezterületet, de jelentősen lassabb lehet sok
művelethez, mint például a cvs update.

Ha egy olyan git refspecre szeretnél hivatkozni, amely a CVS által
nem engedélyezett karaktereket tartalmaz, két lehetőséged van. Először
is, előfordulhat, hogy egyszerűen működik, ha közvetlenül megadod a
git refspecet a megfelelő CVS -r argumentumnak; úgy tűnik, néhány
CVS-kliens nem sokat ellenőrzi az argumentumot. Másodszor, ha ez nem
sikerül, használhatsz egy speciális karakter-escape mechanizmust,
amely csak a CVS tag-ekben érvényes karaktereket használja. Egy 4
vagy 5 karakterből álló, (aláhúzásjel (`"_"`), kötőjel (`"-"`), egy
vagy két karakter, és kötőjel (`"-"`)) formájú szekvencia különböző
karaktereket kódolhat az egy vagy két betű alapján: `"s"` a perjelhez
(`"/"`), `"p"` a ponthoz (`"."`), `"u"` az aláhúzásjelhez (`"_"`),
vagy két hexadecimális számjegy bármilyen bájtértékhez (jellemzően
egy ASCII-szám, vagy esetleg egy UTF-8 kódolású karakter része).

A régi típusú felügyeleti műveletek nem támogatottak (edit, watch és
kapcsolódók). Az exportok és a tag-elés (tag-ek és branch-ek) ezen a
ponton nem támogatottak.

CRLF sorvég-konverziók
~~~~~~~~~~~~~~~~~~~~~~

Alapértelmezetten a szerver üresen hagyja a `-k` módot minden fájlnál,
ami miatt a CVS-kliens szöveges fájlként kezeli őket, egyes
platformokon a sorvég-konverziónak alávetve.

Beállíthatod, hogy a szerver a sorvég-konverziós attribútumokat
használja a fájlok `-k` módjának beállításához, a `gitcvs.usecrlfattr`
konfigurációs változó beállításával. A sorvég-konverzióról további
információért lásd a linkgit:gitattributes[5] leírást.

Alternatívaként, ha a `gitcvs.usecrlfattr` konfiguráció nincs
engedélyezve, vagy az attribútumok nem teszik lehetővé az automatikus
felismerést egy fájlnévhez, akkor a szerver a `gitcvs.allBinary`
konfigurációt használja az alapértelmezett beállításhoz. Ha a
`gitcvs.allBinary` be van állítva, akkor az egyébként meg nem adott
fájl alapértelmezetten '-kb' módba kerül. Egyébként a `-k` mód
üresen marad. De ha a `gitcvs.allBinary` "guess"-re van állítva, akkor
a helyes `-k` mód a fájl tartalma alapján kerül kitalálásra.

A 'cvs'-szel való legjobb konzisztencia érdekében valószínűleg a
legjobb felülírni az alapértelmezéseket, a `gitcvs.usecrlfattr`
igazra állításával, és a `gitcvs.allBinary` "guess"-re állításával.

FÜGGŐSÉGEK
----------
A 'git-cvsserver' a DBD::SQLite-tól függ.

GIT
---
A linkgit:git[1] csomag része
