Regressziók elleni küzdelem a git bisect segítségével
=====================================================
:Author: Christian Couder
:Email: chriscool@tuxfamily.org
:Date: 2009/11/08

Kivonat
-------

A "git bisect" lehetővé teszi a szoftverek felhasználói és fejlesztői
számára, hogy könnyen megtalálják azt a commitot, amelyik egy
regressziót bevezetett. Megmutatjuk, miért fontos jó eszközökkel
rendelkezni a regressziók elleni küzdelemhez. Leírjuk, hogyan működik
a "git bisect" kívülről, és milyen algoritmusokat használ belül. Ezután
elmagyarázzuk, hogyan lehet kihasználni a "git bisect" előnyeit a
jelenlegi gyakorlatok javítására. Végül megvitatjuk, hogyan
fejlődhetne a "git bisect" a jövőben.


Bevezetés a "git bisect"-be
---------------------------

A Git egy elosztott verziókövető rendszer (DVCS), amelyet Linus
Torvalds hozott létre, és Junio Hamano tart karban.

A Gitben, ahogy sok más verziókövető rendszerben (VCS) is, a rendszer
által kezelt adatok különböző állapotait commitoknak nevezik. És mivel
a VCS-eket főleg szoftverek forráskódjának kezelésére használják,
néha „érdekes" viselkedésváltozásokat vezetnek be egyes commitok.

Az embereket valójában különösen érdeklik azok a commitok, amelyek
„rossz" viselkedést vezetnek be, amit hibának vagy regressziónak
neveznek. Azért érdeklik őket ezek a commitok, mert egy commit
(reménység szerint) a forráskód-változtatások egy nagyon kis
halmazát tartalmazza. És sokkal könnyebb megérteni és megfelelően
kijavítani egy problémát, ha csak egy nagyon kis változtatáshalmazt
kell átnézned, mint amikor eleve nem tudod, hol keresd.

Így hát, hogy segítsen az embereknek megtalálni a „rossz" viselkedést
bevezető commitokat, feltalálták a "git bisect" parancskészletet. Ebből
természetesen az is következik, hogy a "git bisect" szóhasználatában
azokat a commitokat, amelyekben jelen van az „érdekes viselkedés",
"bad" (azaz rossz) commitoknak nevezik, a többi commitot pedig "good"
(azaz jó) commitoknak. Azt a commitot pedig, amelyik bevezeti a minket
érdeklő viselkedést, "first bad commit"-nek (az első "bad" commitnak)
nevezik. Vedd figyelembe, hogy a keresett commit-térben több "first bad
commit" is lehet.

A "git bisect"-et tehát arra tervezték, hogy segítsen megtalálni egy
"first bad commit"-ot. És hogy a lehető leghatékonyabb legyen, bináris
keresést próbál végrehajtani.


Regressziók elleni küzdelem áttekintése
---------------------------------------

Regressziók: egy nagy probléma
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A regressziók nagy problémát jelentenek a szoftveriparban. De nehéz
valódi számokat rendelni ehhez az állításhoz.

Vannak számok a hibákról általánosságban, például egy 2002-es NIST-
tanulmány <<1>>, amely a következőt mondta:

_____________
Software bugs, or errors, are so prevalent and so detrimental that
they cost the U.S. economy an estimated $59.5 billion annually, or
about 0.6 percent of the gross domestic product, according to a newly
released study commissioned by the Department of Commerce's National
Institute of Standards and Technology (NIST). At the national level,
over half of the costs are borne by software users and the remainder
by software developers/vendors.  The study also found that, although
all errors cannot be removed, more than a third of these costs, or an
estimated $22.2 billion, could be eliminated by an improved testing
infrastructure that enables earlier and more effective identification
and removal of software defects. These are the savings associated with
finding an increased percentage (but not 100 percent) of errors closer
to the development stages in which they are introduced. Currently,
over half of all errors are not found until "downstream" in the
development process or during post-sale software use.
_____________

És aztán:

_____________
Software developers already spend approximately 80 percent of
development costs on identifying and correcting defects, and yet few
products of any type other than software are shipped with such high
levels of errors.
_____________

Végül a következtetés így kezdődött:

_____________
The path to higher software quality is significantly improved software
testing.
_____________

Vannak más becslések is, amelyek szerint a szoftverrel kapcsolatos
költségek 80%-a a karbantartásra megy el <<2>>.

Bár a Wikipédia szerint <<3>>:

_____________
A common perception of maintenance is that it is merely fixing
bugs. However, studies and surveys over the years have indicated that
the majority, over 80%, of the maintenance effort is used for
non-corrective actions (Pigosky 1997). This perception is perpetuated
by users submitting problem reports that in reality are functionality
enhancements to the system.
_____________

De feltételezhetjük, hogy a meglévő szoftverek fejlesztése nagyon
költséges, mert oda kell figyelni a regressziókra. Ez legalábbis
konzisztenssé tenné egymással a fenti tanulmányokat.

Természetesen léteznek olyan szoftverek, amelyeket kifejlesztenek,
egy ideig használnak anélkül, hogy sokat javítanának rajtuk, majd
végül eldobják. Ebben az esetben a regressziók természetesen nem
jelentenek nagy problémát. Másrészt viszont rengeteg olyan nagy
szoftver van, amelyet folyamatosan fejlesztenek és tartanak karban
éveken, vagy akár évtizedeken át, sok ember közreműködésével. És
mivel sokan (néha kritikus mértékben) függenek az ilyen
szoftverektől, a regressziók valóban nagy problémát jelentenek.

Az egyik ilyen szoftver a Linux kernel. És ha megnézzük a Linux
kernelt, láthatjuk, hogy rengeteg időt és erőfeszítést fordítanak a
regressziók elleni küzdelemre. A kiadási ciklus egy 2 hetes merge
ablakkal kezdődik. Ezután megjelölik az első release candidate (rc)
verziót. Majd ezután körülbelül még 7-8 rc verzió jelenik meg,
egymás között nagyjából egy hetes időközzel, a végleges kiadás előtt.

Az első rc-kiadás és a végleges kiadás közötti időt az rc verziók
tesztelésére és a hibák, különösen a regressziók elleni küzdelemre
szánják. És ez az idő a kiadási ciklus idejének több mint 80%-a. De ez
még nem a küzdelem vége, hiszen az természetesen a kiadás után is
folytatódik.

És most nézzük, mit mond Ingo Molnar (egy jól ismert Linux
kernel-fejlesztő) a git bisect saját használatáról:

_____________
I most actively use it during the merge window (when a lot of trees
get merged upstream and when the influx of bugs is the highest) - and
yes, there have been cases that i used it multiple times a day. My
average is roughly once a day.
_____________

A regressziók elleni küzdelem tehát folyamatosan zajlik a fejlesztők
között, és köztudott, hogy a hibákat a lehető leghamarabb ki kell
javítani, tehát amint megtalálják őket. Ezért érdekes, ha jó
eszközeink vannak erre a célra.

Egyéb eszközök a regressziók elleni küzdelemhez
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Milyen eszközöket használnak tehát a regressziók elleni küzdelemhez?
Ezek szinte megegyeznek a szokásos hibák elleni küzdelemhez használt
eszközökkel. Az egyedüli speciális eszközök a tesztkészletek és a
"git bisect"-hez hasonló eszközök.

A tesztkészletek nagyon hasznosak. De ha önmagukban használják őket,
akkor feltételezés szerint úgy kell használni, hogy minden commit után
lefusson az összes teszt. Ez azt jelenti, hogy nem túl hatékonyak,
mert sok teszt fut le érdekes eredmény nélkül, és szenvednek a
kombinatorikus robbanástól.

Valójában az a probléma, hogy a nagy szoftvereknek gyakran sokféle
konfigurációs opciója van, és minden tesztesetnek minden konfiguráció
mellett, minden commit után teljesülnie kell. Tehát ha minden
kiadáshoz N konfigurációnk, M commitunk és T tesztesetünk van, akkor
a következőt kell elvégezni:

-------------
N * M * T tests
-------------

ahol N, M és T mind a szoftvered méretével együtt nő.

Így nagyon hamar lehetetlenné válik mindent teljeskörűen tesztelni.

És ha néhány hiba átcsúszik a tesztkészleteden, akkor hozzáadhatsz egy
tesztet a tesztkészletedhez. De ha az új, javított tesztkészletedet
akarod használni annak megtalálására, hogy hol csúszott be a hiba,
akkor vagy szimulálnod kell egy bisect-folyamatot, vagy esetleg
nyersen, visszafelé kell tesztelned minden egyes commitot a meglévő
"bad" committól kezdve, ami nagyon pazarló lehet.

A "git bisect" áttekintése
--------------------------

A bisect indítása
~~~~~~~~~~~~~~~~~

Az első használandó "git bisect" alparancs a "git bisect start", amely
elindítja a keresést. Ezután korlátokat kell megadni a commit-tér
behatárolásához. Ezt általában úgy tesszük, hogy megadunk egy "bad" és
legalább egy "good" commitot. Ezek átadhatók a "git bisect start"
kezdeti hívásában, így:

-------------
$ git bisect start [BAD [GOOD...]]
-------------

vagy beállíthatók a következőkkel:

-------------
$ git bisect bad [COMMIT]
-------------

és:

-------------
$ git bisect good [COMMIT...]
-------------

ahol a BAD, GOOD és COMMIT mind olyan nevek, amelyek egy commitra
oldhatók fel.

Ezután a "git bisect" checkoutol egy általa kiválasztott commitot, és
megkéri a felhasználót, hogy tesztelje azt, így:

-------------
$ git bisect start v2.6.27 v2.6.25
Bisecting: 10928 revisions left to test after this (roughly 14 steps)
[2ec65f8b89ea003c27ff7723525a2ee335a2b393] x86: clean up using max_low_pfn on 32-bit
-------------

Vedd figyelembe, hogy az itt használt példa valójában csak egy
játékpélda: azt az első commitot fogjuk keresni, amelynek verziója
"2.6.26-valami" alakú, tehát azt a commitot, amelyben a felső szintű
Makefile-ban egy "SUBLEVEL = 26" sor van. Ez azért játékpélda, mert
vannak jobb módszerek is ennek a commitnak a Git-tel történő
megtalálására, mint a "git bisect" (például a "git blame" vagy a
"git log -S<string>").

A bisect kézi vezérlése
~~~~~~~~~~~~~~~~~~~~~~~

Ezen a ponton alapvetően 2 módja van a keresés vezérlésének. Vezérelhető
kézzel a felhasználó által, vagy automatikusan egy szkript vagy egy
parancs által.

Ha a felhasználó vezérli, akkor a keresés minden lépésénél a
felhasználónak kell tesztelnie az aktuális commitot, és megmondania,
hogy az "good" vagy "bad", a fent leírt "git bisect good", illetve
"git bisect bad" parancsok segítségével. Például:

-------------
$ git bisect bad
Bisecting: 5480 revisions left to test after this (roughly 13 steps)
[66c0b394f08fd89236515c1c84485ea712a157be] KVM: kill file->f_count abuse in kvm
-------------

És néhány további, hasonló lépés után a "git bisect" végül megtalál
egy "first bad commit"-ot:

-------------
$ git bisect bad
2ddcca36c8bcfa251724fe342c8327451988be0d is the first bad commit
commit 2ddcca36c8bcfa251724fe342c8327451988be0d
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat May 3 11:59:44 2008 -0700

    Linux 2.6.26-rc1

:100644 100644 5cf82581... 4492984e... M      Makefile
-------------

Ezen a ponton megnézhetjük, mit csinál a commit, checkoutolhatjuk (ha
még nincs checkoutolva), vagy babrálhatunk vele, például:

-------------
$ git show HEAD
commit 2ddcca36c8bcfa251724fe342c8327451988be0d
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat May 3 11:59:44 2008 -0700

    Linux 2.6.26-rc1

diff --git a/Makefile b/Makefile
index 5cf8258..4492984 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 VERSION = 2
 PATCHLEVEL = 6
-SUBLEVEL = 25
-EXTRAVERSION =
+SUBLEVEL = 26
+EXTRAVERSION = -rc1
 NAME = Funky Weasel is Jiggy wit it

 # *DOCUMENTATION*
-------------

És amikor végeztünk, a "git bisect reset" paranccsal visszatérhetünk
arra a branchre, amelyen a bisectelés megkezdése előtt voltunk:

-------------
$ git bisect reset
Checking out files: 100% (21549/21549), done.
Previous HEAD position was 2ddcca3... Linux 2.6.26-rc1
Switched to branch 'master'
-------------

A bisect automatikus vezérlése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A bisect-folyamat vezérlésének másik módja, hogy megmondjuk a "git
bisect"-nek, hogy minden bisect-lépésnél indítson el egy szkriptet
vagy parancsot annak megállapítására, hogy az aktuális commit "good"
vagy "bad". Ehhez a "git bisect run" parancsot használjuk. Például:

-------------
$ git bisect start v2.6.27 v2.6.25
Bisecting: 10928 revisions left to test after this (roughly 14 steps)
[2ec65f8b89ea003c27ff7723525a2ee335a2b393] x86: clean up using max_low_pfn on 32-bit
$
$ git bisect run grep '^SUBLEVEL = 25' Makefile
running grep ^SUBLEVEL = 25 Makefile
Bisecting: 5480 revisions left to test after this (roughly 13 steps)
[66c0b394f08fd89236515c1c84485ea712a157be] KVM: kill file->f_count abuse in kvm
running grep ^SUBLEVEL = 25 Makefile
SUBLEVEL = 25
Bisecting: 2740 revisions left to test after this (roughly 12 steps)
[671294719628f1671faefd4882764886f8ad08cb] V4L/DVB(7879): Adding cx18 Support for mxl5005s
...
...
running grep ^SUBLEVEL = 25 Makefile
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[2ddcca36c8bcfa251724fe342c8327451988be0d] Linux 2.6.26-rc1
running grep ^SUBLEVEL = 25 Makefile
2ddcca36c8bcfa251724fe342c8327451988be0d is the first bad commit
commit 2ddcca36c8bcfa251724fe342c8327451988be0d
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat May 3 11:59:44 2008 -0700

    Linux 2.6.26-rc1

:100644 100644 5cf82581... 4492984e... M      Makefile
bisect run success
-------------

Ebben a példában a "grep '^SUBLEVEL = 25' Makefile" parancsot adtuk át
paraméterként a "git bisect run"-nak. Ez azt jelenti, hogy minden
lépésnél az általunk átadott grep parancs kerül elindításra. És ha az
0-s kóddal lép ki (ez sikert jelent), akkor a git bisect "good"-ként
jelöli meg az aktuális állapotot. Ha 1-es kóddal (vagy bármilyen, 1 és
127 közötti kóddal, a speciális 125-ös kód kivételével) lép ki, akkor
az aktuális állapot "bad"-ként lesz megjelölve.

A 128 és 255 közötti kilépési kódok speciálisak a "git bisect run"
számára. Ezek azonnal leállítják a bisect-folyamatot. Ez akkor
hasznos például, ha az átadott parancs végrehajtása túl sokáig tart,
mert ilyenkor leállíthatod egy szignállal, és ez megállítja
a bisect-folyamatot.

Az is hasznos lehet, ha a "git bisect run"-nak átadott szkriptekben
"exit 255"-öt használunk, ha valamilyen nagyon abnormális helyzetet
észlelünk.

A nem tesztelhető commitok elkerülése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Néha előfordul, hogy az aktuális állapot nem tesztelhető, például ha
nem fordul le, mert akkor egy hiba megakadályozta ezt. Erre való a
speciális 125-ös kilépési kód. Ez közli a "git bisect run"-nal, hogy
az aktuális commitot nem tesztelhetőként kell megjelölni, és egy
másikat kell választani és checkoutolni.

Ha a bisect-folyamatot kézzel vezérled, akkor ugyanezt a "git bisect
skip" használatával teheted meg. (Valójában a speciális 125-ös
kilépési kód miatt a "git bisect run" a háttérben a "git bisect
skip"-et használja.)

Vagy ha nagyobb kontrollt szeretnél, megvizsgálhatod az aktuális
állapotot például a "git bisect visualize" segítségével. Ez elindítja
a gitk-t (vagy a "git log"-ot, ha a `DISPLAY` környezeti változó nincs
beállítva), hogy segítsen jobb bisect-pontot találni.

Bármelyik esetben, ha van egy sor nem tesztelhető commitod, előfordulhat,
hogy a keresett regressziót az egyik ilyen nem tesztelhető commit
vezette be. Ebben az esetben nem lehet biztosan megmondani, melyik
commit vezette be a regressziót.

Tehát ha a "git bisect skip"-et használtad (vagy a run szkript a
speciális 125-ös kóddal lépett ki), akkor egy ehhez hasonló eredményt
kaphatsz:

-------------
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
15722f2fa328eaba97022898a305ffc8172db6b1
78e86cf3e850bd755bb71831f42e200626fbd1e0
e15b73ad3db9b48d7d1ade32f8cd23a751fe0ace
070eab2303024706f2924822bfec8b9847e4ac1b
We cannot bisect more!
-------------

A napló mentése és visszajátszása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ha meg akarod mutatni másoknak a bisect-folyamatodat, létrehozhatsz
egy naplót például a következővel:

-------------
$ git bisect log > bisect_log.txt
-------------

És visszajátszani a következővel lehet:

-------------
$ git bisect replay bisect_log.txt
-------------


A "git bisect" részletei
------------------------

A bisect-algoritmus
~~~~~~~~~~~~~~~~~~~

Mivel a Git commitok irányított körmentes gráfot (DAG-ot) alkotnak, a
minden lépésnél tesztelendő legjobb bisect-commit megtalálása nem
egyszerű feladat. Linus mindenesetre talált és megvalósított egy
"valóban buta" algoritmust, amelyet később Junio Hamano javított
tovább, és amely egészen jól működik.

A "git bisect" által a legjobb bisect-commit megtalálására használt
algoritmus tehát a következő, ha nincsenek kihagyott commitok:

1) csak azokat a commitokat tartjuk meg, amelyek:

a) a "bad" commit ősei (beleértve magát a "bad" commitot is),
b) nem ősei egyetlen "good" commitnak sem (a "good" commitokat kizárva).

Ez azt jelenti, hogy megszabadulunk a DAG érdektelen commitjaitól.

Például, ha egy ilyen gráffal indulunk:

-------------
G-Y-G-W-W-W-X-X-X-X
	   \ /
	    W-W-B
	   /
Y---G-W---W
 \ /   \
Y-Y     X-X-X-X

-> time goes this way ->
-------------

ahol B a "bad" commit, "G" a "good" commitok, W, X és Y pedig egyéb
commitok, akkor ennek az első lépésnek az elvégzése után a következő
gráfot kapjuk:

-------------
W-W-W
     \
      W-W-B
     /
W---W
-------------

Így csak a W és B commitok maradnak meg. Mert az X és Y commitokat
rendre az a), illetve a b) szabály távolítja el, a G commitokat pedig
szintén a b) szabály távolítja el.

A Git-felhasználók számára megjegyezzük, hogy ez ekvivalens azzal,
mintha csak a következő által megadott commitot tartanánk meg:

-------------
git rev-list BAD --not GOOD1 GOOD2...
-------------

Azt is jegyezzük meg, hogy nem követeljük meg, hogy a megtartott
commitok egy "good" commit leszármazottai legyenek. Így a következő
példában a W és Z commitok is megmaradnak:

-------------
G-W-W-W-B
   /
Z-Z
-------------

2) a gráf "good" végeiből kiindulva rendeljük hozzá minden commithoz
   az ősei számát, plusz egyet

Például a következő gráffal, ahol H a "bad" commit, A és D pedig
néhány "good" commit szülei:

-------------
A-B-C
     \
      F-G-H
     /
D---E
-------------

ez a következőt adja:

-------------
1 2 3
A-B-C
     \6 7 8
      F-G-H
1   2/
D---E
-------------

3) minden commithoz rendeljük hozzá: min(X, N - X)

ahol X a commithoz a 2) lépésben rendelt érték, N pedig a gráfban
lévő commitok teljes száma.

A fenti példában N = 8, tehát ez a következőt adja:

-------------
1 2 3
A-B-C
     \2 1 0
      F-G-H
1   2/
D---E
-------------

4) a legjobb bisect-pont az a commit, amelyikhez a legmagasabb
   hozzárendelt szám tartozik

Tehát a fenti példában a legjobb bisect-pont a C commit.

5) vedd figyelembe, hogy az algoritmus felgyorsítására néhány
   rövidítő megoldás is be van építve

Mivel N-t az elejétől fogva ismerjük, tudjuk, hogy a min(X, N - X)
nem lehet nagyobb, mint N/2. Így a 2) és 3) lépések során, ha egy
commithoz N/2-t rendelnénk, akkor tudjuk, hogy ez a legjobb
bisect-pont. Ebben az esetben tehát egyszerűen leállíthatjuk bármely
további commit feldolgozását, és visszaadhatjuk az aktuális commitot.

A bisect-algoritmus hibakeresése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bármely commit-gráf esetén megnézheted az egyes commitokhoz rendelt
számot a "git rev-list --bisect-all" segítségével.

Például a fenti gráfhoz egy ilyen parancs:

-------------
$ git rev-list --bisect-all BAD --not GOOD1 GOOD2
-------------

valami ehhez hasonlót adna kimenetként:

-------------
e15b73ad3db9b48d7d1ade32f8cd23a751fe0ace (dist=3)
15722f2fa328eaba97022898a305ffc8172db6b1 (dist=2)
78e86cf3e850bd755bb71831f42e200626fbd1e0 (dist=2)
a1939d9a142de972094af4dde9a544e577ddef0e (dist=2)
070eab2303024706f2924822bfec8b9847e4ac1b (dist=1)
a3864d4f32a3bf5ed177ddef598490a08760b70d (dist=1)
a41baa717dd74f1180abf55e9341bc7a0bb9d556 (dist=1)
9e622a6dad403b71c40979743bb9d5be17b16bd6 (dist=0)
-------------

A bisect-algoritmus megvitatása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Először is definiáljuk a "legjobb bisect-pont" fogalmát. Azt fogjuk
mondani, hogy egy X commit a legjobb bisect-pont vagy legjobb
bisect-commit, ha az állapotának ismerete ("good" vagy "bad") a
lehető legtöbb információt adja arról, hogy a commit állapota "good"
vagy "bad".

Ez azt jelenti, hogy a legjobb bisect-commitok azok a commitok,
amelyeknél a következő függvény maximális:

-------------
f(X) = min(information_if_good(X), information_if_bad(X))
-------------

ahol information_if_good(X) az az információ, amit akkor kapunk, ha
X good, és information_if_bad(X) az az információ, amit akkor kapunk,
ha X bad.

Most tegyük fel, hogy csak egyetlen "first bad commit" van. Ez azt
jelenti, hogy minden leszármazottja "bad", és az összes többi commit
"good". És tegyük fel azt is, hogy minden commitnak egyenlő az
esélye arra, hogy good vagy bad legyen, illetve hogy az első bad
commit legyen, tehát c commit állapotának ismerete mindig ugyanannyi
információt ad, függetlenül attól, hogy ez a c commit hol van a
gráfon, és mennyi c. (Tehát feltételezzük, hogy az, hogy ezek a
commitok például egy branchen vannak, vagy egy good vagy bad commit
közelében, nem ad se több, se kevesebb információt.)

Tegyük fel azt is, hogy egy megtisztított gráffal rendelkezünk, mint
amilyet a fenti bisect-algoritmus 1) lépése után kapunk. Ez azt
jelenti, hogy az általunk kapott információt a gráfból eltávolítható
commitok számában mérhetjük.

És vegyünk egy X commitot a gráfban.

Ha X-ről kiderül, hogy "good", akkor tudjuk, hogy az ősei mind
"good"-ok, tehát azt szeretnénk mondani, hogy:

-------------
information_if_good(X) = number_of_ancestors(X)  (TRUE)
-------------

És ez igaz, mert az 1) b) lépésben eltávolítjuk a "good" commitok
őseit.

Ha X-ről kiderül, hogy "bad", akkor tudjuk, hogy a leszármazottai mind
"bad"-ok, tehát azt szeretnénk mondani, hogy:

-------------
information_if_bad(X) = number_of_descendants(X)  (WRONG)
-------------

De ez helytelen, mert az 1) a) lépésben csak a bad commit őseit
tartjuk meg. Tehát több információt kapunk, amikor egy commitot
"bad"-ként jelölünk meg, mert azt is tudjuk, hogy az előző "bad"
commit ősei közül azok, amelyek nem ősei az új "bad" commitnak, nem
lehetnek az első bad commit. Nem tudjuk, hogy good-ok vagy bad-ek-e,
de tudjuk, hogy nem ők az első bad commit, mert nem ősei az új "bad"
commitnak.

Tehát amikor egy commitot "bad"-ként jelölünk meg, tudjuk, hogy a
gráf összes commitját eltávolíthatjuk, kivéve azokat, amelyek az új
"bad" commit ősei. Ez azt jelenti, hogy:

-------------
information_if_bad(X) = N - number_of_ancestors(X)  (TRUE)
-------------

ahol N a (megtisztított) gráfban lévő commitok száma.

Ez tehát végül azt jelenti, hogy a legjobb bisect-commitok
megtalálásához a következő függvényt kell maximalizálnunk:

-------------
f(X) = min(number_of_ancestors(X), N - number_of_ancestors(X))
-------------

És ez azért kényelmes, mert a 2) lépésben kiszámítjuk a
number_of_ancestors(X)-et, így a 3) lépésben már f(X)-et számítjuk ki.

Vegyük példaként a következő gráfot:

-------------
            G-H-I-J
           /       \
A-B-C-D-E-F         O
           \       /
            K-L-M-N
-------------

Ha kiszámítjuk rajta a következő nem optimális függvényt:

-------------
g(X) = min(number_of_ancestors(X), number_of_descendants(X))
-------------

a következőt kapjuk:

-------------
            4 3 2 1
            G-H-I-J
1 2 3 4 5 6/       \0
A-B-C-D-E-F         O
           \       /
            K-L-M-N
            4 3 2 1
-------------

de a git bisect által használt algoritmussal a következőt kapjuk:

-------------
            7 7 6 5
            G-H-I-J
1 2 3 4 5 6/       \0
A-B-C-D-E-F         O
           \       /
            K-L-M-N
            7 7 6 5
-------------

Tehát a G, H, K vagy L commitot választjuk legjobb bisect-pontnak, ami
jobb, mint F. Mert ha például L bad, akkor nemcsak azt fogjuk tudni,
hogy L, M és N is bad, hanem azt is, hogy G, H, I és J nem az első bad
commit (mivel feltételezzük, hogy csak egyetlen első bad commit van,
és annak L ősének kell lennie).

Tehát úgy tűnik, hogy a jelenlegi algoritmus a lehető legjobb azok
alapján, amit kezdetben feltételeztünk.

A skip-algoritmus
~~~~~~~~~~~~~~~~~

Amikor néhány commitot kihagytak (a "git bisect skip" használatával),
akkor a bisect-algoritmus az 1)–3) lépésekig ugyanaz marad. Ezután
azonban nagyjából a következő lépéseket használjuk:

6) rendezzük a commitokat a hozzájuk rendelt érték csökkenő sorrendje
   szerint

7) ha az első commitot nem hagyták ki, visszaadhatjuk azt, és itt
   megállhatunk

8) egyébként szűrjük ki a rendezett listából az összes kihagyott
   commitot

9) egy pszeudovéletlenszám-generátor (PRNG) segítségével generáljunk
   egy 0 és 1 közötti véletlen számot

10) szorozzuk meg ezt a véletlen számot a saját négyzetgyökével, hogy
    0 felé toljuk el

11) szorozzuk meg az eredményt a szűrt listában lévő commitok
    számával, hogy egy indexet kapjunk ebbe a listába

12) adjuk vissza a kiszámított indexen lévő commitot

A skip-algoritmus megvitatása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A 7) lépés után (a skip-algoritmusban) megvizsgálhatnánk, hogy a
második commitot kihagyták-e, és ha nem, visszaadhatnánk azt.
Valójában ezt az algoritmust használtuk attól kezdve, hogy a "git
bisect skip" a Git 1.5.4-es verziójában (megjelent 2008. február
1-jén) elkészült, egészen a Git 1.6.4-es verziójáig (megjelent 2009.
július 29-én).

De Ingo Molnar és H. Peter Anvin (egy másik jól ismert linux
kernel-fejlesztő) is panaszkodtak arra, hogy néha a legjobb
bisect-pontok mind egy olyan területre estek, ahol minden commit nem
tesztelhető. És ebben az esetben a felhasználót arra kérték, hogy sok
nem tesztelhető commitot teszteljen, ami nagyon nem hatékony lehet.

Valóban, a nem tesztelhető commitok gyakran azért nem tesztelhetők,
mert egy adott ponton egy törés került bevezetésre, és ezt a törést
csak sok további commit bevezetése után javították ki.

Ez a törés természetesen a legtöbbször nem áll kapcsolatban azzal a
töréssel, amelyet a commit-gráfban próbálunk megkeresni. De
megakadályozza, hogy megtudjuk, jelen van-e az érdekes "bad
behavior" (rossz viselkedés) vagy sem.

Tény tehát, hogy egy nem tesztelhető commit közelében lévő
commiteknek nagy az esélyük arra, hogy ők maguk is nem tesztelhetők
legyenek. És (a bisect-algoritmus miatt) a legjobb bisect-commitok is
gyakran együtt találhatók.

Ezért rossz ötlet egyszerűen a következő legjobb, ki nem hagyott
bisect-commitot választani, amikor az elsőt kihagyták.

Azt tapasztaltuk, hogy a gráf legtöbb commitja elég sok információt
adhat, ha teszteljük őket. És azok a commitok, amelyek átlagosan nem
adnak sok információt, a good és bad commitok közelében lévők.

Így egy olyan PRNG használata, amely a good és bad commitoktól távol
eső commitokat részesíti előnyben, jó választásnak tűnt.

Az algoritmus egyik nyilvánvaló javítása az lenne, hogy a PRNG
használata előtt megkeressünk egy olyan commitot, amelynek hozzárendelt
értéke közel van a legjobb bisect-commitéhoz, és amely egy másik
branchen van. Mert ha létezik ilyen commit, akkor nem valószínű, hogy
az is nem tesztelhető, tehát valószínűleg több információt fog adni,
mint egy majdnem véletlenszerűen választott.

A merge-alapok ellenőrzése
~~~~~~~~~~~~~~~~~~~~~~~~~~

A bisect-algoritmusban van még egy másik finomítás is, amelyet a fenti
"bisect-algoritmus" szakaszban nem írtunk le.

Az előző példákban azt feltételeztük, hogy a "good" commitok a "bad"
commit ősei. De ez nem követelmény a "git bisect" számára.

A "bad" commit természetesen nem lehet egy "good" commit őse, mert a
good commitok őseiről feltételezzük, hogy "good"-ok. És minden "good"
commitnak kapcsolódnia kell a bad commithoz. Nem lehetnek olyan
branchen, amelynek nincs kapcsolata a "bad" commit branchével. De az
lehetséges, hogy egy good commit kapcsolódik egy bad commithoz, mégsem
őse, sem leszármazottja annak.

Például lehet egy "main" branch, és egy "dev" branch, amelyet a main
branchből ágaztattak le egy "D" nevű commitnál, így:

-------------
A-B-C-D-E-F-G  <--main
       \
        H-I-J  <--dev
-------------

A "D" commitot a "main" és a "dev" branch "merge-alapjának" nevezzük,
mert ez a legjobb közös ős e két branch egy merge-eléséhez.

Most tegyük fel, hogy a J commit bad, a G commit pedig good, és
alkalmazzuk a bisect-algoritmust úgy, ahogy korábban leírtuk.

A bisect-algoritmus 1) b) lépésében leírtak szerint eltávolítjuk a
good commitok minden ősét, mert azokról is feltételezzük, hogy
good-ok.

Így már csak ez maradna:

-------------
H-I-J
-------------

De mi történik, ha az első bad commit "B", és azt a "main" branchen az
"F" commit javította ki?

Egy ilyen bisect eredménye az lenne, hogy azt találnánk, hogy H az
első bad commit, holott valójában B az. Ez tehát hibás eredmény
lenne!

És igen, a gyakorlatban előfordulhat, hogy az egyik branchen dolgozó
emberek nincsenek tudatában annak, hogy egy másik branchen dolgozó
emberek kijavítottak egy hibát! Az is előfordulhat, hogy F egynél
több hibát javított ki, vagy hogy egy olyan nagy fejlesztési erőfeszítés
visszavonása, amely még nem volt kész a kiadásra.

Valójában a fejlesztőcsapatok gyakran tartanak fenn egyszerre egy
fejlesztői branchet és egy karbantartási branchet, és nagyon
egyszerű lenne a számukra, ha a "git bisect" egyszerűen működne, amikor
egy olyan regressziót akarnak bisectelni a fejlesztői branchen, amely
nincs jelen a karbantartási branchen. Ilyenkor a bisectelést a
következővel kellene tudniuk elindítani:

-------------
$ git bisect start dev main
-------------

Ennek a kényelmes kiegészítő funkciónak a megvalósításához, amikor egy
bisect elindul, és néhány good commit nem őse a bad commitnak, először
kiszámítjuk a bad és a good commitok közötti merge-alapokat, és
ezeket a merge-alapokat választjuk első checkoutolandó és tesztelendő
commitoknak.

Ha az történik, hogy az egyik merge-alap bad, akkor a bisect-folyamat
egy ehhez hasonló üzenettel leáll:

-------------
The merge base BBBBBB is bad.
This means the bug has been fixed between BBBBBB and [GGGGGG,...].
-------------

ahol BBBBBB a bad merge-alap sha1 hasje, a [GGGGGG,...] pedig a good
commitok sha1-jeinek vesszővel elválasztott listája.

Ha a merge-alapok közül néhányat kihagynak, akkor a bisect-folyamat
folytatódik, de minden kihagyott merge-alaphoz kiíródik a következő
üzenet:

-------------
Warning: the merge base between BBBBBB and [GGGGGG,...] must be skipped.
So we cannot be sure the first bad commit is between MMMMMM and BBBBBB.
We continue anyway.
-------------

ahol BBBBBB a bad commit sha1 hasje, MMMMMM a kihagyott merge-alap
sha1 hasje, a [GGGGGG,...] pedig a good commitok sha1-jeinek vesszővel
elválasztott listája.

Tehát ha nincs bad merge-alap, a bisect-folyamat ez után a lépés után
a szokásos módon folytatódik.

A bisectelés legjobb gyakorlatai
--------------------------------

A tesztkészletek és a git bisect együttes használata
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ha egyszerre van tesztkészleted és használod a git bisect-et, akkor
kevésbé lesz fontos minden commit után ellenőrizni, hogy az összes
teszt lefut-e sikeresen. Bár természetesen valószínűleg jó ötlet
néhány ellenőrzést fenntartani, hogy elkerüld túl sok dolog
elrontását, mert az megnehezítheti más hibák bisectelését.

Az erőfeszítéseidet néhány pontra összpontosíthatod (például az rc és
a béta kiadásoknál), ahol ellenőrzöd, hogy az összes T teszteset
lefut-e sikeresen az összes N konfigurációnál. És amikor néhány teszt
nem fut le sikeresen, használhatod a "git bisect"-et (vagy inkább a
"git bisect run"-t). Tehát nagyjából a következőt kell elvégezned:

-------------
c * N * T + b * M * log2(M) tests
-------------

ahol c a tesztek körének száma (tehát egy kis konstans), b pedig a
hibák commitonkénti aránya (reménység szerint szintén egy kis
konstans).

Tehát ez természetesen sokkal jobb, mert O(N * T), szemben az
O(N * T * M)-mel, ha mindent tesztelnél minden commit után.

Ez azt jelenti, hogy a tesztkészletek jók abban, hogy megakadályozzák
néhány hiba commitolását, és abban is elég jók, hogy megmondják, hogy
van néhány hibád. De abban nem olyan jók, hogy megmondják, hol vezették
be ezeket a hibákat. Ennek hatékony megmondásához a git bisect
szükséges.

A tesztkészletekkel kapcsolatos másik kellemes dolog, hogy ha van
egyed, akkor már tudod, hogyan kell tesztelni a "bad behavior"-t
(rossz viselkedést). Ezt a tudást felhasználhatod egy új teszteset
létrehozására a "git bisect" számára, amikor kiderül, hogy van egy
regresszió. Így könnyebb lesz bisectelni a hibát és kijavítani. Majd
hozzáadhatod az imént létrehozott tesztesetet a tesztkészletedhez.

Tehát ha tudod, hogyan kell teszteseteket létrehozni, és hogyan kell
bisectelni, egy önerősítő körforgás részesévé válsz:

több teszt => könnyebb teszteket létrehozni => könnyebb bisectelni => több teszt

Így a tesztkészletek és a "git bisect" egymást kiegészítő eszközök,
amelyek nagyon hatékonyak és erősek, ha együtt használjuk őket.

Build-hibák bisectelése
~~~~~~~~~~~~~~~~~~~~~~~

Nagyon könnyen, automatikusan bisectelheted a hibás buildeket, valami
ehhez hasonlóval:

-------------
$ git bisect start BAD GOOD
$ git bisect run make
-------------

A sh -c "parancsok" átadása a "git bisect run"-nak
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Például:

-------------
$ git bisect run sh -c "make || exit 125; ./my_app | grep 'good output'"
-------------

Másrészt, ha ezt gyakran csinálod, akkor megérheti szkripteket
készíteni, hogy elkerüld a túl sok gépelést.

Teljesítmény-regressziók felderítése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Íme egy példaszkript, amely egy valós, Junio Hamano által használt
szkriptből származik, kicsit módosítva <<4>>.

Ez a szkript átadható a "git bisect run"-nak, hogy megtalálja azt a
commitot, amely bevezetett egy teljesítmény-regressziót:

-------------
#!/bin/sh

# Build errors are not what I am interested in.
make my_app || exit 255

# We are checking if it stops in a reasonable amount of time, so
# let it run in the background...

./my_app >log 2>&1 &

# ... and grab its process ID.
pid=$!

# ... and then wait for sufficiently long.
sleep $NORMAL_TIME

# ... and then see if the process is still there.
if kill -0 $pid
then
	# It is still running -- that is bad.
	kill $pid; sleep 1; kill $pid;
	exit 1
else
	# It has already finished (the $pid process was no more),
	# and we are happy.
	exit 0
fi
-------------

Általános bevált gyakorlatok követése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Nyilvánvalóan jó ötlet elkerülni olyan commitokat, amelyek tudatosan
elrontanak dolgokat, még akkor is, ha később más commitok kijavítják
a törést.

Az is jó ötlet, bármelyik VCS-t is használod, hogy commitonként csak
egyetlen kis logikai változtatás legyen.

Minél kisebbek a változtatások a commitodban, a "git bisect" annál
hatékonyabb lesz. És valószínűleg eleve kevésbé lesz szükséged a
"git bisect"-re, mivel a kis változtatásokat könnyebb átnézni, még
akkor is, ha csak a commitoló nézi át őket.

Egy másik jó ötlet a jó commit-üzenetek írása. Ezek nagyon hasznosak
lehetnek annak megértéséhez, hogy miért történtek bizonyos
változtatások.

Ezek az általános bevált gyakorlatok nagyon hasznosak, ha gyakran
bisectelsz.

A hibára hajlamos merge-ek elkerülése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Már önmagukban a merge-ek is bevezethetnek néhány regressziót, még
akkor is, ha a merge-nek nincs szüksége forráskód-ütközés feloldására.
Ez azért van, mert egy szemantikai változás történhet az egyik
branchen, miközben a másik branch nincs ennek tudatában.

Például az egyik branch megváltoztathatja egy függvény szemantikáját,
miközben a másik branch további hívásokat ad hozzá ugyanahhoz a
függvényhez.

Ez sokkal rosszabbá válik, ha sok fájlt kell kijavítani az ütközések
feloldásához. Ezért nevezik az ilyen merge-eket "gonosz merge-eknek"
("evil merges"). Ezek nagyon megnehezíthetik a regressziók
felkutatását. Az első bad commit ismerete akár félrevezető is lehet,
ha az véletlenül egy ilyen merge, mert az emberek azt gondolhatják,
hogy a hiba egy rossz ütközésfeloldásból ered, holott valójában egy
szemantikai változásból ered az egyik branchen.

Mindenesetre a "git rebase" használható a history linearizálására.
Ez használható arra, hogy eleve elkerüljük a merge-elést. Vagy arra
is használható, hogy egy lineáris historyn bisecteljünk a nem
lineáris helyett, mivel ez több információt adhat egy szemantikai
változás esetén az egyik branchen.

A merge-ek egyszerűsíthetők kisebb branchek használatával is, vagy
sok topic branch használatával a csak hosszú, verzióhoz kötött
branchek helyett.

És a tesztelés gyakrabban végezhető speciális integrációs brancheken,
mint amilyen a linux-next a linux kernel esetében.

A munkafolyamatod igazítása
~~~~~~~~~~~~~~~~~~~~~~~~~~~

A regressziók kezelésére kialakított speciális munkafolyamat nagyszerű
eredményeket hozhat.

Íme egy példa az Andreas Ericsson által használt munkafolyamatra:

* a tesztkészletben megírunk egy tesztszkriptet, amely felfedi a regressziót
* a "git bisect run" segítségével megkeressük a commitot, amelyik bevezette
* kijavítjuk a hibát, amit az előző lépés gyakran nyilvánvalóvá tesz
* commitoljuk mind a javítást, mind a tesztszkriptet (és ha szükséges, további teszteket is)

Íme, mit mondott Andreas erről a munkafolyamatról <<5>>:

_____________
To give some hard figures, we used to have an average report-to-fix
cycle of 142.6 hours (according to our somewhat weird bug-tracker
which just measures wall-clock time). Since we moved to Git, we've
lowered that to 16.2 hours. Primarily because we can stay on top of
the bug fixing now, and because everyone's jockeying to get to fix
bugs (we're quite proud of how lazy we are to let Git find the bugs
for us). Each new release results in ~40% fewer bugs (almost certainly
due to how we now feel about writing tests).
_____________

Ez a munkafolyamat egyértelműen a tesztkészletek és a "git bisect"
közötti önerősítő körforgást használja ki. Valójában ez teszi a
szabványos eljárássá a regressziók kezelését.

Más üzenetekben Andreas azt mondja, hogy a fent leírt "bevált
gyakorlatokat" is használják: kis logikai commitok, topic branchek,
nincs gonosz merge... Ezek a gyakorlatok mind javítják a commit-gráf
bisectelhetőségét, azáltal, hogy könnyebbé és hasznosabbá teszik a
bisectelést.

Egy jó munkafolyamatot tehát a fenti pontok köré érdemes tervezni. Ez
azt jelenti, hogy a bisectelést könnyebbé, hasznosabbá és
szabványossá kell tenni.

A QA-csapat és lehetőség szerint a végfelhasználók bevonása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A "git bisect"-ben az egyik szép dolog, hogy nem csak fejlesztői
eszköz. Hatékonyan használhatja a QA-csapat, vagy akár a
végfelhasználók is (ha hozzáférnek a forráskódhoz, vagy ha hozzá
tudnak férni az összes buildhez).

Egyszer volt egy vita a linux kernel levelezőlistáján arról, hogy
rendben van-e mindig megkérni a végfelhasználót a bisectelésre, és
nagyon jó érvek hangzottak el amellett az álláspont mellett, hogy ez
rendben van.

Például David Miller ezt írta <<6>>:

_____________
What people don't get is that this is a situation where the "end node
principle" applies. When you have limited resources (here: developers)
you don't push the bulk of the burden upon them. Instead you push
things out to the resource you have a lot of, the end nodes (here:
users), so that the situation actually scales.
_____________

Ez azt jelenti, hogy gyakran "olcsóbb", ha a QA-csapat vagy a
végfelhasználók végzik el.

Az is érdekes, hogy azok a végfelhasználók, akik hibákat jelentenek
(vagy azok a QA-csapattagok, akik reprodukáltak egy hibát), hozzáférnek
ahhoz a környezethez, ahol a hiba történik. Így gyakran könnyebben
tudnak reprodukálni egy regressziót. És ha tudnak bisectelni, akkor
több információt lehet kinyerni abból a környezetből, ahol a hiba
történik, ami azt jelenti, hogy könnyebb lesz megérteni, majd
kijavítani a hibát.

Nyílt forráskódú projektek esetében ez jó módja lehet annak, hogy
hasznosabb hozzájárulásokat kapjunk a végfelhasználóktól, és bevezessük
őket a QA és a fejlesztési tevékenységekbe.

Összetett szkriptek használata
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Bizonyos esetekben, mint például a kernel-fejlesztésnél, megérheti
összetett szkripteket fejleszteni, hogy a bisectelés teljesen
automatizálható legyen.

Íme, mit mond erről Ingo Molnar <<7>>:

_____________
i have a fully automated bootup-hang bisection script. It is based on
"git-bisect run". I run the script, it builds and boots kernels fully
automatically, and when the bootup fails (the script notices that via
the serial log, which it continuously watches - or via a timeout, if
the system does not come up within 10 minutes it's a "bad" kernel),
the script raises my attention via a beep and i power cycle the test
box. (yeah, i should make use of a managed power outlet to 100%
automate it)
_____________

Tesztkészletek, a git bisect és más rendszerek kombinálása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Láttuk, hogy a tesztkészletek és a git bisect együtt nagyon hatékonyak.
Még hatékonyabb lehet, ha más rendszerekkel is kombináljuk őket.

Például néhány tesztkészletet automatikusan lehetne futtatni éjszaka,
néhány szokatlan (vagy akár véletlenszerű) konfigurációval. És ha egy
tesztkészlet talál egy regressziót, akkor a "git bisect"
automatikusan elindítható, és az eredménye elküldhető e-mailben a "git
bisect" által megtalált first bad commit szerzőjének, illetve talán
másoknak is. És a hibakövető rendszerben automatikusan létrehozható
lenne egy új bejegyzés is.


A bisectelés jövője
-------------------

"git replace"
~~~~~~~~~~~~~

Korábban láttuk, hogy a "git bisect skip" most már egy PRNG-t használ
annak érdekében, hogy elkerülje a commit-gráf azon területeit, ahol a
commitok nem tesztelhetők. A probléma az, hogy néha az első bad commit
egy nem tesztelhető területen lesz.

A tárgyalás egyszerűsítése érdekében feltételezzük, hogy a nem
tesztelhető terület egy egyszerű commit-sorozat, amelyet egy commit
által bevezetett törés hozott létre (nevezzük ezt BBC-nek, azaz
"bisect breaking commit"-nek), és amelyet később egy másik javított ki
(nevezzük ezt BFC-nek, azaz "bisect fixing commit"-nek).

Például:

-------------
...-Y-BBC-X1-X2-X3-X4-X5-X6-BFC-Z-...
-------------

ahol tudjuk, hogy Y good, a BFC pedig bad, és a BBC, valamint az X1-X6
nem tesztelhetők.

Ebben az esetben, ha kézzel bisectelsz, azt teheted, hogy létrehozol
egy speciális branchet, amely közvetlenül a BBC előtt kezdődik. Ennek
a branchnek az első commitja legyen a BBC, amelybe be van squashelve a
BFC. A branch többi commitja pedig legyen a BBC és a BFC közötti
commitok, a branch első commitjára rebase-elve, majd a BFC utáni
commit is szintén erre rebase-elve.

Például:

-------------
      (BBC+BFC)-X1'-X2'-X3'-X4'-X5'-X6'-Z'
     /
...-Y-BBC-X1-X2-X3-X4-X5-X6-BFC-Z-...
-------------

ahol a '-vel jelölt commitok lettek rebase-elve.

Egy ilyen branchet könnyen létrehozhatsz a Git-tel, interaktív rebase
segítségével.

Például a következővel:

-------------
$ git rebase -i Y Z
-------------

majd a BFC-t a BBC utánra mozgatod, és belesquasheled.

Ezután a szokásos módon elkezdheted a bisectelést az új branchen, és
végül meg kell találnod az első bad commitot.

Például:

-------------
$ git bisect start Z' Y
-------------

Ha a "git bisect run"-t használod, alkalmazhatod ugyanazt a kézi
javítást, mint fent, majd elindíthatsz egy másik "git bisect run"-t a
speciális branchen. Vagy, ahogy a "git bisect" man page mondja, a
"git bisect run"-nak átadott szkript alkalmazhat egy patchet, mielőtt
lefordítja és teszteli a szoftvert <<8>>. A patchnek egy jelenleg nem
tesztelhető commitot tesztelhetővé kell tennie. Így a tesztelés
eredménye "good" vagy "bad" lesz, és a "git bisect" képes lesz
megtalálni az első bad commitot. És a szkript ne felejtse el eltávolítani
a patchet, miután a tesztelés befejeződött, mielőtt kilépne a
szkriptből.

(Vedd figyelembe, hogy patch helyett használhatod a "git cherry-pick
BFC" parancsot is a javítás alkalmazásához, és ebben az esetben a
"git reset --hard HEAD^" parancsot kell használnod a cherry-pick
visszavonásához a tesztelés után, mielőtt visszatérnél a szkriptből.)

De a fenti módszerek a nem tesztelhető területek megkerülésére kicsit
esetlenek. A speciális branchek használata azért kellemes, mert ezek
a branchek a szokásos branchekhez hasonlóan megoszthatók a fejlesztők
között, de fennáll a kockázat, hogy az emberek sok ilyen branchet
kapnak. És ez megzavarja a normál "git bisect" munkafolyamatot. Tehát
ha teljesen automatikusan akarod használni a "git bisect run"-t, akkor
speciális kódot kell hozzáadnod a szkriptedhez a bisectelés
speciális brancheken történő újraindításához.

Mindenesetre a fenti speciális branch-példában megfigyelhető, hogy a
Z' és Z commiteknek ugyanarra a forráskód-állapotra kell mutatniuk
(git szóhasználatban ugyanarra a "tree"-re). Ez azért van, mert Z'
ugyanazoknak a változtatásoknak az alkalmazásából adódik, mint Z,
csak kicsit eltérő sorrendben.

Tehát ha bisectelés közben egyszerűen csak "helyettesíthetnénk" Z-t
Z'-vel, akkor nem kellene semmit hozzáadnunk egy szkripthez. Egyszerűen
működne mindenki számára a projektben, aki osztozik a speciális
brancheken és a helyettesítéseken.

A fenti példával ez a következőt adná:

-------------
      (BBC+BFC)-X1'-X2'-X3'-X4'-X5'-X6'-Z'-...
     /
...-Y-BBC-X1-X2-X3-X4-X5-X6-BFC-Z
-------------

Ezért hozták létre a "git replace" parancsot. Technikailag a
helyettesítő "refeket" a "refs/replace/" hierarchiában tárolja. Ezek
a "refek" olyanok, mint a branchek (amelyeket a "refs/heads/"-ben
tárolnak), vagy a tagek (amelyeket a "refs/tags"-ban tárolnak), ami
azt jelenti, hogy automatikusan megoszthatók a fejlesztők között, mint
a branchek vagy a tagek.

A "git replace" egy nagyon hatékony mechanizmus. Használható már
kiadott historyban lévő commitok javítására, például a commit-üzenet
vagy a szerző megváltoztatására. És a git "grafts" helyett is
használható egy repository másik, régi repositoryhoz kapcsolására.

Valójában ez az utolsó funkció "adta el" a Git közösségének, így most
már benne van a Git saját Git repositoryjának "master" branchében, és
2009 októberében vagy novemberében a Git 1.6.5-ben kellene megjelennie.

A "git replace" egyik problémája, hogy jelenleg az összes helyettesítő
refet a "refs/replace/"-ben tárolja, de talán jobb lenne, ha azok a
helyettesítő refek, amelyek csak bisecteléshez hasznosak, a
"refs/replace/bisect/"-ben lennének. Így a helyettesítő refek csak
bisecteléshez lennének használhatók, míg a közvetlenül a
"refs/replace/"-ben lévő többi ref szinte mindig használatban lenne.

Szórványos hibák bisectelése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A "git bisect" egy másik lehetséges fejlesztése az lenne, hogy
opcionálisan némi redundanciát adjunk az elvégzett tesztekhez, hogy
megbízhatóbb legyen a szórványos hibák felkutatásakor.

Erre néhány kernel-fejlesztő kért fel, mert néhány, szórványos
hibáknak nevezett hiba nem jelenik meg minden kernel-buildben, mivel
nagyon függenek a fordító kimenetétől.

Az ötlet az, hogy például minden 3. tesztnél a "git bisect"
megkérhetné a felhasználót, hogy teszteljen egy olyan commitot, amelyről
már kiderült, hogy "good" vagy "bad" (mert az egyik leszármazottjáról,
illetve az egyik ősétől kiderült, hogy "good", illetve "bad"). Ha az
történik, hogy egy commitot korábban hibásan osztályoztak, akkor a
bisectelés korán megszakítható, remélhetőleg mielőtt túl sok hiba
történne. Ezután a felhasználónak meg kell néznie, mi történt, majd
újra kell indítania a bisectelést egy javított bisect naplóval.

Már létezik egy BBChop nevű projekt, amelyet Ealdwulf Wuffinga hozott
létre a Github-on, és amely valami hasonlót csinál, Bayes-i
keresési elmélet segítségével <<9>>:

_____________
BBChop is like 'git bisect' (or equivalent), but works when your bug
is intermittent. That is, it works in the presence of false negatives
(when a version happens to work this time even though it contains the
bug). It assumes that there are no false positives (in principle, the
same approach would work, but adding it may be non-trivial).
_____________

De a BBChop független bármilyen VCS-től, és a Git felhasználói számára
egyszerűbb lenne, ha valami a Git-be integrálva lenne.

Összegzés
---------

Láttuk, hogy a regressziók fontos problémát jelentenek, és hogy a
"git bisect" olyan kellemes funkciókkal rendelkezik, amelyek nagyon
jól kiegészítik a gyakorlatokat és más eszközöket, különösen a
tesztkészleteket, amelyeket általában a regressziók elleni
küzdelemhez használnak. De ahhoz, hogy a legtöbbet hozzuk ki belőle,
szükség lehet néhány munkafolyamat és (rossz) szokás megváltoztatására.

Néhány fejlesztés lehetséges a "git bisect" belső algoritmusaiban, és
néhány új funkció is segíthetne bizonyos esetekben, de összességében
a "git bisect" már most is nagyon jól működik, sokan használják, és
már most is nagyon hasznos. Ennek az utolsó állításnak az
alátámasztására adjuk át a záró szót Ingo Molnarnak, akit a szerző
megkérdezett, szerinte mennyi időt takarít meg neki a "git bisect",
amikor használja:

_____________
a _lot_.

About ten years ago did i do my first 'bisection' of a Linux patch
queue. That was prior the Git (and even prior the BitKeeper) days. I
literally days spent sorting out patches, creating what in essence
were standalone commits that i guessed to be related to that bug.

It was a tool of absolute last resort. I'd rather spend days looking
at printk output than do a manual 'patch bisection'.

With Git bisect it's a breeze: in the best case i can get a ~15 step
kernel bisection done in 20-30 minutes, in an automated way. Even with
manual help or when bisecting multiple, overlapping bugs, it's rarely
more than an hour.

In fact it's invaluable because there are bugs i would never even
_try_ to debug if it wasn't for git bisect. In the past there were bug
patterns that were immediately hopeless for me to debug - at best i
could send the crash/bug signature to lkml and hope that someone else
can think of something.

And even if a bisection fails today it tells us something valuable
about the bug: that it's non-deterministic - timing or kernel image
layout dependent.

So git bisect is unconditional goodness - and feel free to quote that
;-)
_____________

Köszönetnyilvánítás
-------------------

Nagyon köszönöm Junio Hamanónak a segítségét e cikk átnézésében, a
Git levelezőlistára küldött patcheim átnézését, néhány ötlet
megvitatását és azok javításában nyújtott segítségét, a "git bisect"
sokrétű fejlesztését, valamint a Git karbantartásában és
fejlesztésében végzett lenyűgöző munkáját.

Nagyon köszönöm Ingo Molnarnak, hogy nagyon hasznos információkat adott
nekem, amelyek megjelennek ebben a cikkben, hogy hozzászólt ehhez a
cikkhez, a "git bisect" fejlesztésére vonatkozó javaslataiért, és
azért, hogy hirdette a "git bisect"-et a linux kernel
levelezőlistákon.

Nagyon köszönöm Linus Torvaldsnak a "git bisect", a Git és a Linux
feltalálását, fejlesztését és hirdetését.

Nagyon köszönöm a sok más nagyszerű embernek, akik egyik vagy másik
módon segítettek, amikor a Git-en dolgoztam, különösen Andreas
Ericssonnak, Johannes Schindelinnek, H. Peter Anvinnak, Daniel
Barkalow-nak, Bill Learnek, John Hawley-nak, Shawn O. Pierce-nek, Jeff
Kingnek, Sam Vilainnek, Jon Seymournak.

Nagyon köszönöm a Linux-Kongress programbizottságának, hogy a szerzőt
választották egy előadás megtartására, és hogy publikálták ezt a
cikket.

Hivatkozások
------------

- [[[1]]] https://web.archive.org/web/20091206032101/http://www.nist.gov/public_affairs/releases/n02-10.htm['Software Errors Cost U.S. Economy $59.5 Billion Annually'. Nist News Release.] See also https://www.nist.gov/system/files/documents/director/planning/report02-3.pdf['The Economic Impacts of Inadequate Infratructure for Software Testing'.  Nist Planning Report 02-3], Executive Summary and Chapter 8.
- [[[2]]] https://www.oracle.com/java/technologies/javase/codeconventions-introduction.html['Code Conventions for the Java Programming Language: 1. Introduction'. Sun Microsystems.]
- [[[3]]] https://en.wikipedia.org/wiki/Software_maintenance['Software maintenance'. Wikipedia.]
- [[[4]]] https://lore.kernel.org/git/7vps5xsbwp.fsf_-_@assigned-by-dhcp.cox.net/[Junio C Hamano. 'Automated bisect success story'.]
- [[[5]]] https://lwn.net/Articles/317154/[Christian Couder. 'Fully automated bisecting with "git bisect run"'. LWN.net.]
- [[[6]]] https://lwn.net/Articles/277872/[Jonathan Corbet. 'Bisection divides users and developers'. LWN.net.]
- [[[7]]] https://lore.kernel.org/lkml/20071207113734.GA14598@elte.hu/[Ingo Molnar. 'Re: BUG 2.6.23-rc3 can't see sd partitions on Alpha'. Linux-kernel mailing list.]
- [[[8]]] https://www.kernel.org/pub/software/scm/git/docs/git-bisect.html[Junio C Hamano and the git-list. 'git-bisect(1) Manual Page'. Linux Kernel Archives.]
- [[[9]]] https://github.com/Ealdwulf/bbchop[Ealdwulf. 'bbchop'. GitHub.]
