git-check-ignore(1)
===================

NAME
----
git-check-ignore - A gitignore / kizárási fájlok hibakeresése


SYNOPSIS
--------
[verse]
'git check-ignore' [<options>] <pathname>...
'git check-ignore' [<options>] --stdin

DESCRIPTION
-----------

Minden, a parancssoron keresztül vagy a `--stdin` révén egy fájlból
megadott útvonalnévhez ellenőrzi, hogy a fájl ki van-e zárva a
.gitignore (vagy a kizárási mechanizmus egyéb bemeneti fájljai) által,
és kiírja az útvonalat, ha az ki van zárva.

Alapértelmezésben a követett fájlok egyáltalán nem kerülnek
megjelenítésre, mivel rájuk nem vonatkoznak a kizárási szabályok; de
lásd a `--no-index`-et.

OPTIONS
-------
-q::
--quiet::
	Nem ír ki semmit, csak beállítja a kilépési státuszt. Ez csak
	egyetlen útvonalnévvel érvényes.

-v::
--verbose::
	A kizárt útvonalak kiírása helyett, minden olyan útvonalhoz,
	amely illeszkedik egy kizárási mintára, kiírja a kizárási
	mintát az útvonallal együtt. (Egy kizárási mintára illeszkedés
	általában azt jelenti, hogy az útvonal ki van zárva, de ha a
	minta "`!`"-lel kezdődik, az egy negált minta, és a rá való
	illeszkedés azt jelenti, hogy az útvonal NINCS kizárva.)
+
A kizárási forrásokon belüli és azok közötti elsőbbségi szabályokért
lásd linkgit:gitignore[5].

--stdin::
	Útvonalneveket olvas be a standard bemenetről, soronként egyet,
	a parancssor helyett.

-z::
	A kimeneti formátum géppel elemezhetővé van módosítva (lásd
	alább). Ha a `--stdin` is meg van adva, a bemeneti útvonalak
	NUL karakterrel vannak elválasztva a sortörés karakter helyett.

-n::
--non-matching::
	Megjeleníti a megadott útvonalakat, amelyek nem illeszkednek
	semmilyen mintára. Ennek csak akkor van értelme, ha a
	`--verbose` engedélyezve van, egyébként nem lenne lehetséges
	megkülönböztetni a mintára illeszkedő és a nem illeszkedő
	útvonalakat.

--no-index::
	Az ellenőrzések elvégzésekor nem néz bele az indexbe. Ez
	felhasználható annak hibakeresésére, hogy egy útvonal miért
	vált követetté, pl. a `git add .` révén, és miért nem lett
	kizárva a szabályok által a felhasználó elvárása szerint, vagy
	negációt is tartalmazó minták fejlesztésekor egy korábban
	`git add -f`-fel hozzáadott útvonal illesztéséhez.

OUTPUT
------

Alapértelmezésben minden megadott útvonalnév, amely illeszkedik egy
kizárási mintára, kiírásra kerül, soronként egy. Ha egyetlen minta sem
illeszkedik egy adott útvonalra, semmi nem kerül kiírásra ehhez az
útvonalhoz; ez azt jelenti, hogy az útvonal nincs kizárva.

Ha a `--verbose` meg van adva, a kimenet a következő alakú sorok sorozata:

<source> <COLON> <linenum> <COLON> <pattern> <HT> <pathname>

<pathname> a lekérdezett fájl útvonala, <pattern> az illeszkedő minta,
<source> a minta forrásfájlja, <linenum> pedig a minta sorszáma az
adott forráson belül. Ha a minta "`!`" előtaggal vagy "`/`" utótaggal
rendelkezett, az megmarad a kimenetben. A <source> abszolút útvonal
lesz, ha a `core.excludesFile` által beállított fájlra hivatkozik,
illetve a repository gyökeréhez képest relatív, ha a
`.git/info/exclude`-ra vagy egy könyvtárankénti kizárási fájlra
hivatkozik.

Ha a `-z` meg van adva, a kimeneti útvonalneveket a NUL karakter
választja el; ha a `--verbose` is meg van adva, akkor a kettőspontok
és a tabkarakterek helyett szintén NUL karakterek kerülnek
felhasználásra:

<source> <NULL> <linenum> <NULL> <pattern> <NULL> <pathname> <NULL>

Ha a `-n` vagy a `--non-matching` meg van adva, a nem illeszkedő
útvonalnevek is kiírásra kerülnek; ebben az esetben minden mező üres
lesz az adott kimeneti rekordban, a <pathname> kivételével. Ez akkor
lehet hasznos, amikor nem interaktív módban futtatjuk, hogy a fájlok
fokozatosan streamelhetők legyenek egy hosszan futó check-ignore
folyamat STDIN-jébe, és minden ilyen fájlhoz a STDOUT jelezze, hogy az
adott fájl illeszkedett-e egy mintára vagy sem. (Ezen opció nélkül
lehetetlen lenne megállapítani, hogy egy adott fájlhoz tartozó kimenet
hiánya azt jelenti-e, hogy nem illeszkedett semmilyen mintára, vagy
azt, hogy a kimenet még nem került legenerálásra.)

A pufferelés a linkgit:git[1]-ben dokumentált `GIT_FLUSH` opció
szerint történik. A hívó felelőssége elkerülni a holtpontokat, amelyeket
egy bemeneti puffer túltöltése vagy egy üres kimeneti pufferből való
olvasás okozhat.

EXIT STATUS
-----------

0::
	Egy vagy több megadott útvonal ki van zárva.

1::
	A megadott útvonalak egyike sincs kizárva.

128::
	Végzetes hiba történt.

SEE ALSO
--------
linkgit:gitignore[5]
linkgit:git-config[1]
linkgit:git-ls-files[1]

GIT
---
A linkgit:git[1] csomag része
