git-credential-cache(1)
=======================

NAME
----
git-credential-cache - Helper jelszavak átmeneti tárolásához a memóriában

SYNOPSIS
--------
-----------------------------
git config credential.helper 'cache [<options>]'
-----------------------------

DESCRIPTION
-----------

Ez a parancs elrejti (cache-eli) a hitelesítő adatokat a jövőbeli Git
programok számára. A tárolt hitelesítő adatok a cache-daemon
folyamatának memóriájában maradnak (nem íródnak fájlba), és egy
beállítható időkorlát után elfelejtődnek. A hitelesítő adatok
hamarabb elfelejtődnek, ha a cache-daemon leáll, például
rendszer-újraindításkor. A cache egy Unix domain socketen keresztül
érhető el, amelyet a fájlrendszer jogosultságai a jelenlegi felhasználóra
korlátoznak.

Valószínűleg nem akarod ezt a parancsot közvetlenül meghívni; a Git
más részei használják credential helperként. Lásd a
linkgit:gitcredentials[7] leírást, vagy a lenti `EXAMPLES` szakaszt.

OPTIONS
-------

--timeout <seconds>::

	A hitelesítő adatok cache-elésének időtartama másodpercben
	(alapértelmezés: 900).

--socket <path>::

	A `<path>` használata egy futó cache-daemon eléréséhez (vagy egy
	új cache-daemon indítása, ha még nincs elindítva).
	Alapértelmezés szerint `$XDG_CACHE_HOME/git/credential/socket`,
	hacsak nem létezik a `~/.git-credential-cache/` könyvtár, mely
	esetben a `~/.git-credential-cache/socket` kerül használatra
	helyette.
	Ha a saját könyvtárad hálózatra csatolt fájlrendszeren van, előfordulhat,
	hogy ezt egy helyi fájlrendszerre kell módosítanod. Abszolút
	útvonalat kell megadnod.

A DAEMON VEZÉRLÉSE
------------------

Ha azt szeretnéd, hogy a daemon időkorlát előtt leálljon, és elfelejtse
az összes cache-elt hitelesítő adatot, kiadhatsz egy `exit` akciót:

--------------------------------------
git credential-cache exit
--------------------------------------

EXAMPLES
--------

Ennek a helpernek az a célja, hogy csökkentse azoknak az eseteknek a
számát, amikor be kell gépelned a felhasználóneved vagy jelszavad.
Például:

------------------------------------
$ git config credential.helper cache
$ git push http://example.com/repo.git
Username: <type your username>
Password: <type your password>

[work for 5 more minutes]
$ git push http://example.com/repo.git
[your credentials are used automatically]
------------------------------------

Opciókat a credential.helper konfigurációs változón keresztül adhatsz
meg (ez a példa 1 órára növeli a cache-elés időtartamát):

-------------------------------------------------------
$ git config credential.helper 'cache --timeout=3600'
-------------------------------------------------------

SZEMÉLYES HOZZÁFÉRÉSI TOKENEK
-----------------------------

Egyes remote-ok elfogadnak személyes hozzáférési tokeneket (personal
access token), amelyeket véletlenszerűen generálnak, és nehéz
megjegyezni. Ezeknek jellemzően heteken vagy hónapokban mérhető az
élettartamuk.

A git-credential-cache eredendően nem alkalmas a személyes hozzáférési
tokenek tartós tárolására. A hitelesítő adat a cache időkorlátjának
lejártával elfelejtődik. Még ha hosszú időkorlátot állítasz is be, a
hitelesítő adatok elfelejtődnek, ha a daemon leáll.

A személyes hozzáférési tokenek gyakori újragenerálásának elkerülése
érdekében állíts be egy tartós tárolású credential helpert.
Alternatívaként állíts be egy OAuth credential helpert a hitelesítő
adatok automatikus generálásához. Lásd a linkgit:gitcredentials[7]
"Available helpers" és "OAuth" szakaszait.

GIT
---
A linkgit:git[1] csomag része
