git-blame(1)
============

NAME
----
git-blame - Megmutatja, mely revízió és szerző módosította utoljára a fájl egyes sorait

SYNOPSIS
--------
[synopsis]
git blame [-c] [-b] [-l] [--root] [-t] [-f] [-n] [-s] [-e] [-p] [-w] [--incremental]
	  [-L <range>] [-S <revs-file>] [-M] [-C] [-C] [-C] [--since=<date>]
	  [--ignore-rev <rev>] [--ignore-revs-file <file>]
	  [--color-lines] [--color-by-age] [--progress] [--abbrev=<n>]
	  [ --contents <file> ] [<rev> | --reverse <rev>..<rev>] [--] <file>

DESCRIPTION
-----------

Annotálja a megadott fájl minden sorát azzal az információval, amely
abból a revízióból származik, amelyik utoljára módosította az adott
sort. Opcionálisan a megadott revíziótól kezdve is elindítható az
annotálás.

Ha egy vagy több alkalommal megadod, a `-L` a kért sorokra korlátozza
az annotálást.

A sorok eredete automatikusan követve van a teljes fájlt érintő
átnevezéseken keresztül (jelenleg nincs opció az átnevezés-követés
kikapcsolására). Ahhoz, hogy kövesd az egyik fájlból a másikba
áthelyezett sorokat, vagy egy másik fájlból másolt és beillesztett
sorokat stb., lásd a `-C` és `-M` opciókat.

A jelentés nem mond semmit azokról a sorokról, amelyeket töröltek
vagy lecseréltek; ehhez olyan eszközt kell használnod, mint a
`git diff`, vagy a következő bekezdésben röviden említett "pickaxe"
felületet.

A fájlannotáció támogatása mellett a Git a fejlesztési történet
keresését is támogatja, hogy megtudd, mikor jelent meg egy
kódrészlet egy változtatásban. Ez lehetővé teszi annak nyomon
követését, hogy egy kódrészlet mikor került egy fájlba, mikor lett
áthelyezve vagy másolva fájlok között, és mikor lett végül törölve
vagy lecserélve. Ez úgy működik, hogy egy szövegsztringet keres a
diffben. Egy kis példa a pickaxe felületre, amely a `blame_usage`-ra
keres:

-----------------------------------------------------------------------------
$ git log --pretty=oneline -S'blame_usage'
5040f17eba15504bad66b14a645bddd9b015ebb7 blame -S <ancestry-file>
ea4c7f9bf69e781dd0cd88d2bccb2bf5cc15c9a7 git-blame: Make the output
-----------------------------------------------------------------------------

OPTIONS
-------
include::blame-options.adoc[]

`-c`::
	Ugyanazt a kimeneti módot használja, mint a linkgit:git-annotate[1] (Alapértelmezés: ki).

`--score-debug`::
	Belefoglalja a fájlok közötti sormozgásokra (lásd `-C`) és a
	fájlon belüli sormozgásokra (lásd `-M`) vonatkozó hibakeresési
	információt. Az elsőként felsorolt szám a pontszám. Ez azoknak
	az alfanumerikus karaktereknek a száma, amelyekről érzékelte,
	hogy fájlok között vagy fájlon belül mozogtak. Ennek egy adott
	küszöbérték felett kell lennie ahhoz, hogy a `git blame` úgy
	tekintse, hogy az adott kódsorok mozgásra kerültek.

`-f`::
`--show-name`::
	Megjeleníti a fájlnevet az eredeti commitban. Alapértelmezetten
	a fájlnév akkor jelenik meg, ha van olyan sor, amely egy más
	nevű fájlból származik, az átnevezés-felismerés miatt.

`-n`::
`--show-number`::
	Megjeleníti a sorszámot az eredeti commitban (Alapértelmezés: ki).

`-s`::
	Elnyomja a szerző nevét és az időbélyeget a kimenetből.

`-e`::
`--show-email`::
	A szerző neve helyett a szerző e-mail-címét jeleníti meg
	(Alapértelmezés: ki). Ez a `blame.showEmail` config-opcióval
	is vezérelhető.

`-w`::
	Figyelmen kívül hagyja a whitespace-t a szülő és a gyermek
	verziójának összehasonlításakor, amikor megkeresi, honnan
	származnak a sorok.

include::diff-algorithm-option.adoc[]

`--abbrev=<n>`::
	Az alapértelmezett _7_ hexadecimális számjegy helyett, amit
	rövidített objektumnévként használ, legalább _<n>_ számjegyet
	használ, de biztosítja, hogy a commit objektumnevek egyediek
	legyenek. Ha kúpjellel (boundary), kérdőjellel (ignored) vagy
	csillaggal (unblamable) megjelölt commitok jelennek meg, a nem
	megjelölt objektumneveket kiterjeszti, hogy igazodjanak hozzájuk.


[[_the_default_format]]
Az alapértelmezett formátum
---------------------------

Ha sem a `--porcelain`, sem a `--incremental` opció nincs megadva, a
`git blame` a következőkkel adja ki az annotációt minden sorhoz:

- annak a commitnak a rövidített objektumneve, amelyből a sor származik;
- a szerző azonosítója (alapértelmezetten a szerző neve és a dátum,
  hacsak nincs megadva a `-s` vagy a `-e`); és
- sorszám

a sor tartalma előtt.

[[_the_porcelain_format]]
A porcelain formátum
--------------------

Ebben a formátumban minden sor egy fejléc után kerül kiadásra; a
fejléc legalább az első sort tartalmazza, amelynek van:

- annak a commitnak a 40 bájtos SHA-1-e, amelynek a sor tulajdonítható;
- a sor sorszáma az eredeti fájlban;
- a sor sorszáma a végleges fájlban;
- egy olyan soron, amely egy, az előzőtől eltérő commitból származó
  sorcsoportot indít, a csoportban lévő sorok száma. A rákövetkező
  sorokban ez a mező hiányzik.

Ezt a fejlécsort a következő információ követi legalább egyszer minden
commithoz:

- a szerző neve (`author`), e-mail-címe (`author-mail`), ideje
  (`author-time`) és időzónája (`author-tz`); hasonlóan a
  commiterhez is.
- annak a commitnak a fájlneve, amelynek a sor tulajdonítható.
- a commit napló-üzenetének első sora (`summary`).

Az adott sor tartalma a fenti fejléc után kerül kiadásra, egy _TAB_
karakterrel megelőzve. Ez azért van, hogy később további fejléc-
elemeket lehessen hozzáadni.

A porcelain formátum általában elnyomja a már látott commit-
információt. Például, ha két sor ugyanannak a commitnak tulajdonítható,
mindkettő megjelenik, de az adott commit részletei csak egyszer
jelennek meg. Az egyedi sorokra jellemző információ (mint az
`ignored` vagy `unblamable` jelölésű revíziók) nem lesz csoportosítva.
Ez hatékonyabb, de több állapot megőrzését igényelheti az
olvasótól. A `--line-porcelain` opcióval a teljes commit-információ
kiadható minden sorhoz, ami egyszerűbb (de kevésbé hatékony)
használatot tesz lehetővé, például:

	# count the number of lines attributed to each author
	git blame --line-porcelain file |
	sed -n 's/^author //p' |
	sort | uniq -c | sort -rn


[[_specifying_ranges]]
Tartományok megadása
--------------------

A git régebbi verzióiban lévő `git blame`-mel és `git annotate`-tel
ellentétben az annotáció kiterjedése sortartományokra és
revíziótartományokra egyaránt korlátozható. A `-L` opció, amely az
annotációt sorok egy tartományára korlátozza, több alkalommal is
megadható.

Ha az érdekel, hogy megtaláld a `foo` fájl 40-60. sorainak eredetét,
így használhatod a `-L` opciót (ugyanazt jelentik -- mindkettő 21
sort kér a 40. sortól kezdve):

	git blame -L 40,60 foo
	git blame -L 40,+21 foo

A sortartomány megadásához reguláris kifejezést is használhatsz:

	git blame -L '/^sub hello {/,/^}$/' foo

amely a `hello` szubrutin törzsére korlátozza az annotációt.

Ha nem érdekelnek a v2.6.18 verziónál vagy 3 hétnél régebbi
változtatások, a `git rev-list`-hez hasonló revíziótartomány-
specifikátorokat használhatsz:

	git blame v2.6.18.. -- foo
	git blame --since=3.weeks -- foo

Ha revíziótartomány-specifikátorokat használnak az annotáció
korlátozására, azok a sorok, amelyek a tartományhatár óta nem
változtak (a fenti példában vagy a v2.6.18 commit, vagy a
legutolsó 3 hétnél régebbi commit), a tartományhatár commitjának
tulajdoníthatók.

Egy különösen hasznos módszer megnézni, hogy egy hozzáadott
fájlnak vannak-e meglévő fájlokból másolt és beillesztett sorai.
Ez néha azt jelzi, hogy a fejlesztő hanyag volt, és nem
refaktorálta megfelelően a kódot. Először megtalálhatod a fájlt
bevezető commitot a következővel:

	git log --diff-filter=A --pretty=short -- foo

majd annotáld a változást a commit és a szülei között, a
`commit^!` jelölés használatával:

	git blame -C -C -f $commit^! -- foo


[[_incremental_output]]
Inkrementális kimenet
---------------------

Amikor a `--incremental` opcióval hívod meg, a parancs a felépülése
közben adja ki az eredményt. A kimenet általában a legfrissebb
commitok által érintett sorokról beszél először (azaz a sorok
sorrenden kívül lesznek annotálva), és interaktív megjelenítőkkel
való használatra szánták.

A kimeneti formátum hasonló a Porcelain formátumhoz, de nem
tartalmazza az annotálandó fájl tényleges sorait.

. Minden blame bejegyzés mindig a következő formátumú sorral kezdődik:
+
[synopsis]
<40-byte-hex-sha1> <sourceline> <resultline> <num-lines>
+
A sorszámozás 1-től indul.

. Amikor egy commit először jelenik meg a streamben, róla különféle
  további információ kerül kiírásra, minden sor elején egy
  egyszavas címkével, amely a további commit-információt írja le
  (szerző, e-mail, committer, dátumok, summary stb.).

. A Porcelain formátummal ellentétben a fájlnévinformáció mindig
  meg van adva, és ez zárja le a bejegyzést:
+
[synopsis]
filename <whitespace-quoted-filename-goes-here>
+
így egy sor- és szóorientált parser (ami a legtöbb szkriptnyelvhez
egészen természetes) számára valóban egyszerű a feldolgozás.
+
[NOTE]
Azoknak, akik parszolnak: hogy robusztusabbá tedd, egyszerűen hagyj
figyelmen kívül minden sort az első és az utolsó (_<40-byte-hex-sha1>_
és `filename` sorok) között, ahol nem ismered fel a címkeszavakat (vagy
nem érdekel az adott sor) a "kiterjesztett információ" sorok elején.
Így, ha valaha is hozzáadnak új információt (mint a commit kódolása
vagy kiterjesztett commit-kommentár), egy blame-megjelenítőt ez nem
fog zavarni.


[[_mapping_authors]]
Szerzők leképezése
------------------

Lásd linkgit:gitmailmap[5].

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/blame.adoc[]

SEE ALSO
--------
linkgit:git-annotate[1]

GIT
---
A linkgit:git[1] csomag része
