git-cherry-pick(1)
==================

NAME
----
git-cherry-pick - Néhány létező commit által bevezetett változtatások alkalmazása

SYNOPSIS
--------
[verse]
'git cherry-pick' [--edit] [-n] [-m <parent-number>] [-s] [-x] [--ff]
		  [-S[<keyid>]] <commit>...
'git cherry-pick' (--continue | --skip | --abort | --quit)

DESCRIPTION
-----------

Egy vagy több létező commit esetén alkalmazza az egyes commitok által
bevezetett változtatást, és mindegyikhez felvesz egy új commitot. Ehhez
a munkakönyvtárnak tisztának kell lennie (nincs eltérés a HEAD commithoz
képest).

Ha nem egyértelmű, hogyan kell alkalmazni egy változtatást, a következő
történik:

1. Az aktuális branch és a `HEAD` mutató az utoljára sikeresen létrehozott
   commitnál marad.
2. A `CHERRY_PICK_HEAD` ref arra a commitra mutat, amely bevezette a
   nehezen alkalmazható változtatást.
3. Azok az útvonalak, amelyeken a változtatás tisztán alkalmazódott,
   frissülnek mind az index fájlban, mind a munkakönyvtáradban.
4. Az ütköző útvonalak esetén az index fájl legfeljebb három verziót
   rögzít, ahogy azt a linkgit:git-merge[1] "TRUE MERGE" szakasza
   leírja. A munkakönyvtár fájljai tartalmazni fogják az ütközés
   leírását, a szokásos `<<<<<<<` és `>>>>>>>` ütközésjelölők közé
   zárva.
5. Más módosítás nem történik.

Az ilyen ütközések megoldásához lásd a linkgit:git-merge[1] néhány
tippjét.

OPTIONS
-------
<commit>...::
	A cherry-pickelendő commitok.
	A commitok megadásának teljesebb listájáért lásd a
	linkgit:gitrevisions[7] oldalt.
	Commit-halmazok is megadhatók, de alapértelmezés szerint nem
	történik bejárás, mintha a `--no-walk` opció lett volna
	megadva, lásd linkgit:git-rev-list[1]. Vedd figyelembe, hogy
	egy tartomány megadása az összes <commit>... argumentumot egy
	közös revízióbejáráshoz adja (lásd egy későbbi példát, amely
	a 'maint master..next' alakot használja).

-e::
--edit::
	Ezzel az opcióval a 'git cherry-pick' lehetővé teszi, hogy
	commitolás előtt szerkeszd a commit-üzenetet.

--cleanup=<mode>::
	Ez az opció meghatározza, hogyan tisztuljon meg a commit-üzenet, mielőtt
	továbbadásra kerül a commit-gépezetnek. További részletekért lásd a
	linkgit:git-commit[1] oldalt. Ha a '<mode>' értéke `scissors`, akkor
	ütközés esetén egy olló-jelzés kerül a `MERGE_MSG` végére a továbbadás
	előtt.

-x::
	A commit rögzítésekor fűzz hozzá egy sort, amely azt mondja:
	"(cherry picked from commit ...)" az eredeti commit-üzenethez,
	hogy jelezze, melyik commitból lett ez a változtatás
	cherry-pickelve. Ez csak ütközés nélküli cherry-pickek esetén
	történik meg. Ne használd ezt az opciót, ha a saját privát
	branchedről cherry-pickelsz, mert ez az információ haszontalan
	a fogadó fél számára. Ha viszont két nyilvánosan látható branch
	között cherry-pickelsz (pl. egy javítás visszaportolása egy régebbi
	kiadás karbantartási branchére egy fejlesztési branchről), akkor
	ennek az információnak a hozzáadása hasznos lehet.

-r::
	Régebben a parancs alapértelmezésben elvégezte a fent leírt
	`-x`-et, és a `-r` volt hivatott ezt kikapcsolni. Mostanra az
	alapértelmezés az, hogy nem hajtja végre a `-x`-et, így ez az
	opció hatástalan.

-m <parent-number>::
--mainline <parent-number>::
	Általában nem lehet cherry-pickelni egy merge-öt, mert nem
	tudni, a merge melyik oldalát kell mainline-nak tekinteni.
	Ez az opció megadja a mainline szülő sorszámát (1-től számozva),
	és lehetővé teszi, hogy a cherry-pick a megadott szülőhöz
	viszonyítva játssza le a változtatást.

-n::
--no-commit::
	Általában a parancs automatikusan létrehoz egy commit-sorozatot.
	Ez a kapcsoló az egyes megnevezett commitok cherry-pickeléséhez
	szükséges változtatásokat a munkakönyvtáradra és az indexre
	alkalmazza, anélkül hogy bármilyen commitot létrehozna. Emellett
	ennek az opciónak a használatakor az indexednek nem kell
	megegyeznie a HEAD committal. A cherry-pick az indexed kezdeti
	állapotához képest történik.
+
Ez akkor hasznos, ha egynél több commit hatását akarod egymás után
az indexedbe cherry-pickelni.

-s::
--signoff::
	Egy `Signed-off-by` trailert ad a commit-üzenet végéhez.
	További információért lásd a signoff opciót a linkgit:git-commit[1]
	oldalon.

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	GPG-vel aláírja a commitokat. A `keyid` argumentum opcionális, és
	alapértelmezés szerint a committer identitása; ha meg van adva,
	szóköz nélkül kell az opcióhoz tapadnia. A `--no-gpg-sign` arra
	hasznos, hogy felülbírálja mind a `commit.gpgSign` konfigurációs
	változót, mind egy korábbi `--gpg-sign`-t.

--ff::
	Ha az aktuális HEAD megegyezik a cherry-pickelt commit szülőjével,
	akkor egy fast-forward történik erre a commitra.

--allow-empty::
	Alapértelmezés szerint egy üres commit cherry-pickelése
	meghiúsul, jelezve, hogy a `git commit --allow-empty` explicit
	meghívására van szükség. Ez az opció felülbírálja ezt a
	viselkedést, lehetővé téve, hogy az üres commitok automatikusan
	megmaradjanak egy cherry-pick során. Vedd figyelembe, hogy amikor
	a "--ff" érvényben van, a "fast-forward" követelménynek megfelelő
	üres commitok e nélkül az opció nélkül is megmaradnak. Azt is
	vedd figyelembe, hogy ez az opció csak azokat a commitokat tartja
	meg, amelyek eredetileg is üresek voltak (azaz a commit ugyanazt
	a fát rögzítette, mint a szülője). Azok a commitok, amelyek egy
	korábbi commit miatt válnak üressé, meghiúsítják a cherry-picket.
	Ezeknek a commitoknak a kényszerített felvételéhez használd a
	`--empty=keep` opciót.

--allow-empty-message::
	Alapértelmezés szerint egy üres üzenetű commit cherry-pickelése
	meghiúsul. Ez az opció felülbírálja ezt a viselkedést, lehetővé
	téve, hogy az üres üzenetű commitok is cherry-pickelhetők legyenek.

--empty=(drop|keep|stop)::
	Hogyan kezelje azokat a cherry-pickelt commitokat, amelyek
	redundánsak az aktuális történetben már meglévő változtatásokkal.
+
--
`drop`;;
	A commit el lesz dobva.
`keep`;;
	A commit megmarad. Ez maga után vonja a `--allow-empty`-t.
`stop`;;
	A cherry-pick megáll, amikor a commit alkalmazásra kerül, így
	lehetőséget adva a commit megvizsgálására. Ez az alapértelmezett
	viselkedés.
--
+
Vedd figyelembe, hogy a `--empty=drop` és a `--empty=stop` csak azt adja
meg, hogyan kell kezelni egy olyan commitot, amely nem eredetileg volt
üres, hanem egy korábbi commit miatt vált azzá. Az eredetileg üres
commitok továbbra is meghiúsítják a cherry-picket, hacsak nincs megadva
a `--empty=keep` vagy a `--allow-empty` valamelyike.
+

--keep-redundant-commits::
	Elavult szinonimája a `--empty=keep`-nek.

--strategy=<strategy>::
	A megadott merge-stratégia használata. Csak egyszer szabad
	megadni. A részletekért lásd a linkgit:git-merge[1] oldal
	MERGE STRATEGIES szakaszát.

-X<option>::
--strategy-option=<option>::
	Átadja a merge-stratégia-specifikus opciót a merge-stratégiának.
	A részletekért lásd a linkgit:git-merge[1] oldalt.

include::rerere-options.adoc[]

SEQUENCER SUBCOMMANDS
---------------------
include::sequencer.adoc[]

EXAMPLES
--------
`git cherry-pick master`::

	A master branch csúcsán lévő commit által bevezetett
	változtatás alkalmazása, és egy új commit létrehozása ezzel a
	változtatással.

`git cherry-pick ..master`::
`git cherry-pick ^HEAD master`::

	Az összes olyan commit által bevezetett változtatás
	alkalmazása, amely a master őse, de a HEAD-nek nem, új
	commitok létrehozásához.

`git cherry-pick maint next ^master`::
`git cherry-pick maint master..next`::

	Az összes olyan commit által bevezetett változtatás
	alkalmazása, amely a maint vagy a next őse, de a master-nek
	vagy annak bármely ősének nem. Vedd figyelembe, hogy az
	utóbbi nem azt jelenti, hogy `maint` és minden, ami `master`
	és `next` között van; konkrétan a `maint` nem lesz
	felhasználva, ha az benne van a `master`-ben.

`git cherry-pick master~4 master~2`::

	A master által mutatott ötödik és harmadik utolsó commit által
	bevezetett változtatások alkalmazása, és 2 új commit
	létrehozása ezekkel a változtatásokkal.

`git cherry-pick -n master~1 next`::

	A master által mutatott utolsó előtti commit és a next által
	mutatott utolsó commit által bevezetett változtatások
	alkalmazása a munkakönyvtárra és az indexre, de commit
	létrehozása nélkül ezekkel a változtatásokkal.

`git cherry-pick --ff ..next`::

	Ha a történet lineáris, és a HEAD a next őse, akkor a
	munkakönyvtár frissítése, és a HEAD mutató előreléptetése,
	hogy megegyezzen a next-tel. Egyébként azoknak a commitoknak a
	bevezetett változtatásait alkalmazza, amelyek a next-ben benne
	vannak, de a HEAD-ben nem, az aktuális branchre, minden új
	változtatáshoz új commitot hozva létre.

`git rev-list --reverse master -- README | git cherry-pick -n --stdin`::

	Az összes olyan commit által bevezetett változtatás
	alkalmazása a munkakönyvtárra és az indexre, amely a master
	branchen a README-t érintette, hogy az eredmény
	megvizsgálható, és ha megfelelő, egyetlen új committá
	alakítható legyen.

A következő sorozat megpróbál visszaportolni egy patchet, meghiúsul,
mert a kód, amelyre a patch vonatkozik, túl sokat változott, majd
újra megpróbálja, ezúttal nagyobb gondossággal ügyelve a
kontextussorok illesztésére.

------------
$ git cherry-pick topic^             <1>
$ git diff                           <2>
$ git cherry-pick --abort            <3>
$ git cherry-pick -Xpatience topic^  <4>
------------
<1> annak a változtatásnak az alkalmazása, amelyet a
    `git show topic^` mutatna. Ebben a példában a patch nem
    alkalmazódik tisztán, ezért az ütközésről szóló információ
    bekerül az indexbe és a munkakönyvtárba, és nem keletkezik új
    commit.
<2> az összeegyeztetendő változtatások összegzése
<3> a cherry-pick megszakítása. Más szóval visszatérés a
    cherry-pick előtti állapotba, megőrizve a munkakönyvtárban
    lévő esetleges helyi módosításokat.
<4> a `topic^` által bevezetett változtatás újbóli alkalmazásának
    megkísérlése, extra időt fordítva arra, hogy elkerülje a
    kontextussorok helytelen illesztéséből eredő hibákat.

SEE ALSO
--------
linkgit:git-revert[1]

GIT
---
A linkgit:git[1] csomag része
