git-add(1)
==========

NAME
----
git-add - Fájltartalmak hozzáadása az indexhez

SYNOPSIS
--------
[synopsis]
git add [--verbose | -v] [--dry-run | -n] [--force | -f] [--interactive | -i] [--patch | -p]
	[--edit | -e] [--[no-]all | -A | --[no-]ignore-removal | [--update | -u]] [--sparse]
	[--intent-to-add | -N] [--refresh] [--ignore-errors] [--ignore-missing] [--renormalize]
	[--resolved] [--chmod=(+|-)x] [--pathspec-from-file=<file> [--pathspec-file-nul]]
	[--] [<pathspec>...]

DESCRIPTION
-----------
Új vagy megváltozott fájlok tartalmának hozzáadása az indexhez. Az
„index" (más néven a „staging area") az, amivel a következő commit
tartalmát előkészíted.

Ha a `git commit` parancsot más argumentumok nélkül futtatod, az csak a
staged változásokat commitolja. Ha például módosítottad a `file.c`
fájlt, és a rá vonatkozó változásokat szeretnéd commitolni, futtathatod:

   git add file.c
   git commit

A `git add -p` paranccsal a fájl változásainak csak egy részét is
hozzáadhatod.

Ez a parancs egy commit előtt többször is végrehajtható. Csak a megadott
fájl(ok) tartalmát adja hozzá, mégpedig abban az állapotban, amilyen az
add parancs futtatásának pillanatában volt; ha a következő commitba a
későbbi módosításokat is bele akarod foglalni, akkor a `git add`
parancsot újra kell futtatnod, hogy az új tartalmat hozzáadd az
indexhez.

A `git status` parancs segítségével áttekintheted, mely fájloknak vannak
a következő commitra staged változásai.

A `git add` parancs alapesetben nem adja hozzá az ignorált fájlokat. A
`--force` opcióval az ignorált fájlok is hozzáadhatók. Ha egy ignorált
fájl pontos nevét adod meg, a `git add` meghiúsul, és kiírja az
ignorált fájlok listáját. Egyébként csendben kihagyja a fájlt.

A commitokhoz való tartalom hozzáadásának alternatív módjaiért lásd a
linkgit:git-commit[1] parancsot.


OPTIONS
-------
`<pathspec>...`::
	Fájlok, amelyek tartalmát hozzá kell adni. Fileglobok (pl. `*.c`)
	adhatók meg az összes illeszkedő fájl hozzáadásához. Egy vezető
	könyvtárnév (pl. `dir`, hogy a `dir/file1` és `dir/file2` fájlok
	hozzáadódjanak) is megadható, hogy az index a könyvtár egészének
	aktuális állapotához igazodjon (pl. a `dir` megadása nem csak a
	munkakönyvtárban módosított `dir/file1` fájlt, illetve a
	munkakönyvtárhoz hozzáadott `dir/file2` fájlt rögzíti, hanem a
	munkakönyvtárból eltávolított `dir/file3` fájlt is). Megjegyzendő,
	hogy a Git régebbi verziói figyelmen kívül hagyták az eltávolított
	fájlokat; használd a `--no-all` opciót, ha a módosított vagy új
	fájlokat szeretnéd hozzáadni, de az eltávolítottakat mellőzni.
+
A _<pathspec>_ szintaxisáról bővebben lásd a 'pathspec' szócikket a
linkgit:gitglossary[7] oldalon.

`-n`::
`--dry-run`::
	Ne add hozzá ténylegesen a fájl(oka)t, csak mutasd meg, léteznek-e,
	illetve figyelmen kívül lesznek-e hagyva.

`-v`::
`--verbose`::
        Legyen bőbeszédű.

`-f`::
`--force`::
	Egyébként ignorált fájlok hozzáadásának engedélyezése. Ez az opció
	akkor is használatos, ha a `submodule.<name>.ignore=all` be van
	állítva, de mégis stage-elni szeretnéd a submodule frissítését. A
	submodule `path`-ját ekkor explicit módon meg kell adni.

`--sparse`::
	A sparse-checkout cone-on kívül eső index-bejegyzések frissítésének
	engedélyezése. Alapesetben a `git add` visszautasítja az olyan
	útvonalú index-bejegyzések frissítését, amelyek nem férnek bele a
	sparse-checkout cone-ba, mivel ezek a fájlok figyelmeztetés nélkül
	is eltávolíthatók a munkakönyvtárból. További részletekért lásd a
	linkgit:git-sparse-checkout[1] parancsot.

`-i`::
`--interactive`::
	A munkakönyvtár módosított tartalmának interaktív hozzáadása az
	indexhez. Opcionális útvonal-argumentumok adhatók meg, hogy a
	művelet a munkakönyvtár egy részhalmazára korlátozódjon. A
	részletekért lásd az „Interaktív mód" szakaszt.

`-p`::
`--patch`::
	Az index és a munkakönyvtár közti patch hunkjainak interaktív
	kiválasztása és hozzáadása az indexhez. Ez lehetőséget ad a
	felhasználónak, hogy áttekintse a különbséget, mielőtt a módosított
	tartalmat hozzáadná az indexhez.
+
Ez lényegében az `add --interactive` parancsot futtatja, de kihagyja a
kezdeti parancsmenüt, és egyenesen a `patch` alparancsra ugrik. A
részletekért lásd az „Interaktív mód" szakaszt.

include::diff-context-options.adoc[]

`-e`::
`--edit`::
	Az index és a munkakönyvtár közti diff megnyitása egy
	szerkesztőben, hogy a felhasználó szerkeszthesse. A szerkesztő
	bezárása után a hunk-fejlécek igazítása és a patch alkalmazása
	az indexre.
+
Ennek az opciónak az a célja, hogy a felhasználó válogathasson a patch
sorai közül, sőt akár a stage-elendő sorok tartalmát is módosíthassa.
Ez gyorsabb és rugalmasabb lehet, mint az interaktív hunk-választó
használata. Ugyanakkor könnyű összezavarodni, és olyan patch-et
létrehozni, amely nem alkalmazható az indexre. Lásd az EDITING PATCHES
szakaszt lentebb.

`-u`::
`--update`::
	Az index frissítése csak ott, ahol már van egy _<pathspec>_-nek
	megfelelő bejegyzése. Ez az index-bejegyzéseket a munkakönyvtárhoz
	igazítva el is távolítja, meg is módosítja, de új fájlokat nem ad
	hozzá.
+
Ha a `-u` opció használatakor nincs megadva _<pathspec>_, a teljes
munkakönyvtárban lévő összes követett fájl frissül (a Git régebbi
verziói a frissítést az aktuális könyvtárra és annak alkönyvtáraira
korlátozták).

`-A`::
`--all`::
`--no-ignore-removal`::
	Az index frissítése nemcsak ott, ahol a munkakönyvtárban van a
	_<pathspec>_-nek megfelelő fájl, hanem ott is, ahol az indexben
	már van egy bejegyzés. Ez az index-bejegyzéseket a
	munkakönyvtárhoz igazítva hozzáadja, módosítja és el is
	távolítja.
+
Ha a `-A` opció használatakor nincs megadva _<pathspec>_, a teljes
munkakönyvtárban lévő összes fájl frissül (a Git régebbi
verziói a frissítést az aktuális könyvtárra és annak alkönyvtáraira
korlátozták).

`--no-all`::
`--ignore-removal`::
	Az index frissítése az indexben ismeretlen új fájlok és a
	munkakönyvtárban módosított fájlok hozzáadásával, de a
	munkakönyvtárból eltávolított fájlok mellőzésével. Ez az opció
	nem csinál semmit, ha nincs megadva _<pathspec>_.
+
Ez az opció elsősorban azoknak a felhasználóknak segít, akik a Git
régebbi verzióihoz szoktak hozzá, ahol a `git add <pathspec>...` a
`git add --no-all <pathspec>...` szinonimája volt, azaz figyelmen
kívül hagyta az eltávolított fájlokat.

`-N`::
`--intent-to-add`::
	Csak annak a ténynek a rögzítése, hogy az útvonal később hozzá
	lesz adva. Az útvonalhoz egy tartalom nélküli bejegyzés kerül az
	indexbe. Ez többek között hasznos az ilyen fájlok unstaged
	tartalmának megjelenítéséhez a `git diff` paranccsal, és a
	`git commit -a` paranccsal történő commitolásukhoz.

`--refresh`::
	Ne add hozzá a fájl(oka)t, csak frissítsd a stat()
	információjukat az indexben.

`--ignore-errors`::
	Ha néhány fájlt indexelési hiba miatt nem sikerül hozzáadni, ne
	szakítsd meg a műveletet, hanem folytasd a többi hozzáadásával.
	A parancs ekkor is nullától eltérő státuszkóddal lép ki. Az
	`add.ignoreErrors` konfigurációs változó `true`-ra állításával ez
	tehető alapértelmezett viselkedéssé.

`--ignore-missing`::
	Ez az opció csak a `--dry-run` opcióval együtt használható. Ezzel
	az opcióval a felhasználó ellenőrizheti, hogy a megadott fájlok
	közül bármelyik figyelmen kívül lenne-e hagyva, függetlenül attól,
	hogy már jelen vannak-e a munkafában vagy sem.

`--no-warn-embedded-repo`::
	Alapesetben a `git add` figyelmeztet, ha egy beágyazott
	repository-t ad hozzá az indexhez anélkül, hogy a `git submodule
	add` paranccsal bejegyzést hozna létre a `.gitmodules` fájlban.
	Ez az opció elnyomja a figyelmeztetést (pl. ha kézzel végzel
	műveleteket a submodule-okon).

`--renormalize`::
	A „clean" folyamat friss alkalmazása az összes követett fájlra,
	hogy azok erőltetetten újra hozzáadódjanak az indexhez. Ez akkor
	hasznos, ha a `core.autocrlf` konfiguráció vagy a `text` attribútum
	megváltoztatása után a hibás _CRLF/LF_ sorvégekkel hozzáadott
	fájlokat szeretnéd korrigálni. Ez az opció maga után vonja a `-u`
	opciót. A magányos CR karakterek érintetlenek maradnak, így míg egy
	_CRLF_ _LF_-re tisztul, egy _CRCRLF_ sorozat csak részben tisztul
	_CRLF_-re.

`--resolved`::
	Az index frissítése azoknál a _<pathspec>_-nek megfelelő,
	nem-merge-elt útvonalaknál, ahol a munkakönyvtárban már nem
	maradt konfliktusjelölő. A konfliktusjelölő nélküli nem-merge-elt
	útvonalak (beleértve a bináris fájlokat és a fájltörléseket is)
	megoldottként kerülnek stage-elésre, míg bármely, megmaradt
	konfliktusjelölővel rendelkező útvonal miatt a parancs
	megtagadja bármely fájl stage-elését. Nem kombinálható a `-u`
	vagy a `-A` opcióval.

`--chmod=(+|-)x`::
	A hozzáadott fájlok végrehajthatósági bitjének felülírása. A
	végrehajthatósági bit csak az indexben változik meg, a lemezen
	lévő fájlok változatlanok maradnak.

`--pathspec-from-file=<file>`::
	A pathspec a parancssori argumentumok helyett a _<file>_-ban van
	átadva. Ha a _<file>_ pontosan `-`, akkor a szabványos bemenet
	kerül felhasználásra. A pathspec-elemeket _LF_ vagy _CR/LF_
	választja el. A pathspec-elemek idézőjelbe tehetők a
	`core.quotePath` konfigurációs változónál leírtak szerint (lásd a
	linkgit:git-config[1] parancsot). Lásd még a `--pathspec-file-nul`
	opciót és a globális `--literal-pathspecs` opciót.

`--pathspec-file-nul`::
	Csak a `--pathspec-from-file` opcióval együtt van jelentése. A
	pathspec-elemeket _NUL_ karakter választja el, és minden más
	karakter szó szerint értendő (beleértve az újsorokat és az
	idézőjeleket is).

`--`::
	Ez az opció a parancssori opciók és a fájlok listájának
	elválasztására használható (akkor hasznos, ha a fájlneveket
	esetleg parancssori opciónak lehetne nézni).


EXAMPLES
--------

* Tartalom hozzáadása a `Documentation` könyvtár és alkönyvtárai
  alatti összes ++*.txt++ fájlból:
+
------------
$ git add Documentation/\*.txt
------------
+
Vedd figyelembe, hogy a csillagot (++*++) ebben a példában a shell
elől idézőjelbe tettük; ez teszi lehetővé, hogy a parancs a
`Documentation/` könyvtár alkönyvtáraiból is felvegye a fájlokat.

* Az összes ++git-*.sh++ szkript tartalmának hozzáadását fontolgatja:
+
------------
$ git add git-*.sh
------------
+
Mivel ez a példa hagyja, hogy a shell fejtse ki a csillagot (azaz a
fájlokat explicit módon soroltad fel), a `subdir/git-foo.sh` fájlt nem
veszi figyelembe.

Interaktív mód
--------------
Amikor a parancs interaktív módba lép, megjeleníti a 'status'
alparancs kimenetét, majd belép az interaktív parancs-hurokba.

A parancs-hurok megjeleníti az elérhető alparancsok listáját, és
kiírja a „What now> " promptot. Általában, amikor a prompt egyetlen
'>' karakterrel végződik, csak egyet választhatsz a felkínált
lehetőségek közül, és entert nyomsz, így:

------------
    *** Commands ***
      1: status       2: update       3: revert       4: add untracked
      5: patch        6: diff         7: quit         8: help
    What now> 1
------------

Fent az `s`, `sta` vagy `status` rövidítést is mondhatod, amíg a
választás egyértelmű.

A fő parancs-huroknak 6 alparancsa van (a help és a quit mellett).

status::

   Ez megmutatja az egyes útvonalak `HEAD` és index közti (azaz amit a
   `git commit` mondásakor commitolni fogsz), valamint index és
   munkakönyvtár-fájlok közti (azaz amit a `git commit` előtt a
   `git add` paranccsal még tovább stage-elhetnél) különbségeit. Egy
   minta kimenet így néz ki:
+
------------
              staged     unstaged path
     1:       binary      nothing foo.png
     2:     +403/-35        +1/-1 add-interactive.c
------------
+
Ez azt mutatja, hogy a `foo.png` eltér a `HEAD`-től (de mivel bináris,
a sorok száma nem jeleníthető meg), és nincs különbség az indexelt
másolat és a munkakönyvtár-verzió között (ha a munkakönyvtár-verzió is
eltérne, 'nothing' helyett 'binary' jelenne meg). A másik fájlnak,
az `add-interactive.c`-nek, 403 sora lett hozzáadva és 35 sora
törölve, ha azt commitolod, ami az indexben van, de a
munkakönyvtár-fájl további módosításokat tartalmaz (egy hozzáadást és
egy törlést).

update::

   Ez megjeleníti a státuszinformációt, és kiírja az „Update>>"
   promptot. Amikor a prompt dupla '>>' karakterrel végződik, egynél
   több kiválasztást is tehetsz, szóközzel vagy vesszővel
   összefűzve. Tartományokat is megadhatsz. Pl. „2-5 7,9" a
   2,3,4,5,7,9 elemek kiválasztásához a listából. Ha egy tartomány
   második száma hiányzik, az összes hátralévő patch kiválasztásra
   kerül. Pl. „7-" a 7,8,9 elemek kiválasztásához a listából. A '*'
   karakterrel az összeset kiválaszthatod.
+
Amit kiválasztottál, azt ezután '*' jelöli, így:
+
------------
           staged     unstaged path
  1:       binary      nothing foo.png
* 2:     +403/-35        +1/-1 add-interactive.c
------------
+
A kiválasztás megszüntetéséhez a bemenetet `-` előjellel add meg,
így:
+
------------
Update>> -2
------------
+
A kiválasztás elvégzése után egy üres sorral válaszolva a kiválasztott
útvonalak munkakönyvtár-fájljainak tartalma stage-elődik az indexbe.

revert::

  Ennek nagyon hasonló a felülete az 'update'-hez, és a kiválasztott
  útvonalak staged információja visszaáll a HEAD-verzióéra. Az új
  útvonalak visszaállítása untracked állapotúvá teszi őket.

add untracked::

  Ennek nagyon hasonló a felülete az 'update'-hez és a
  'revert'-hez, és lehetővé teszi untracked útvonalak hozzáadását az
  indexhez.

patch::

  Ez lehetővé teszi, hogy egy 'status'-szerű kiválasztásból egyetlen
  útvonalat válassz ki. Az útvonal kiválasztása után megjeleníti az
  index és a munkakönyvtár-fájl közti diffet, és megkérdezi, hogy
  szeretnéd-e stage-elni az egyes hunkok módosítását. A következő
  opciók közül választhatsz, majd entert nyomsz:

       y - stage this hunk
       n - do not stage this hunk
       q - quit; do not stage this hunk or any of the remaining ones
       a - stage this hunk and all later hunks in the file
       d - do not stage this hunk or any of the later hunks in the file
       g - select a hunk to go to
       / - search for a hunk matching the given regex
       j - go to the next undecided hunk, roll over at the bottom
       J - go to the next hunk, roll over at the bottom
       k - go to the previous undecided hunk, roll over at the top
       K - go to the previous hunk, roll over at the top
       s - split the current hunk into smaller hunks
       e - manually edit the current hunk
       p - print the current hunk
       P - print the current hunk using the pager
       ? - print help
+
Miután minden hunk sorsáról döntöttél, ha volt kiválasztott hunk, az
index frissül a kiválasztott hunkokkal.
+
Az `interactive.singleKey` konfigurációs változó `true`-ra
állításával elkerülheted, hogy itt entert kelljen nyomnod.

diff::

  Ez lehetővé teszi, hogy áttekintsd, mi kerül commitolásra (azaz a
  `HEAD` és az index közötti különbséget).


EDITING PATCHES
---------------

A `git add -e` meghívása, vagy az `e` kiválasztása az interaktív
hunk-választóból megnyit egy patchet a szerkesztődben; a szerkesztő
bezárása után az eredmény alkalmazásra kerül az indexre. Szabadon
végezhetsz tetszőleges módosításokat a patchen, de vedd figyelembe,
hogy egyes módosítások zavaros eredményhez vezethetnek, vagy akár
olyan patchet is eredményezhetnek, amely nem alkalmazható. Ha
teljesen meg akarod szakítani a műveletet (azaz semmi újat nem akarsz
stage-elni az indexben), egyszerűen töröld a patch összes sorát. Az
alábbi lista néhány olyan gyakori dolgot ír le, amellyel egy patchben
találkozhatsz, és hogy melyik szerkesztési művelet van értelme rajtuk.

--
added content::

A hozzáadott tartalmat a „{plus}" karakterrel kezdődő sorok
képviselik. Bármely hozzáadási sor stage-elését megakadályozhatod a
törlésükkel.

removed content::

Az eltávolított tartalmat a „-" karakterrel kezdődő sorok képviselik.
Az eltávolításuk stage-elését megakadályozhatod a „-" karakter „ "
(szóköz) karakterré alakításával.

modified content::

A módosított tartalmat „-" sorok (a régi tartalom eltávolítása)
képviselik, amelyeket „{plus}" sorok (a cseretartalom hozzáadása)
követnek. A módosítás stage-elését megakadályozhatod úgy, hogy a „-"
sorokat " "-ra alakítod, és eltávolítod a „{plus}" sorokat. Vigyázz,
mert a párnak csak a felét módosítani valószínűleg zavaró
módosításokat visz be az indexbe.
--

Vannak ennél összetettebb műveletek is, amelyeket el lehet végezni. De
vigyázz, mert mivel a patch csak az indexre kerül alkalmazásra, nem a
munkakönyvtárra, a munkakönyvtár úgy fog tűnni, mintha „visszavonná" az
indexbeli módosítást. Ha például egy olyan új sort viszel be az
indexbe, amely sem a `HEAD`-ben, sem a munkakönyvtárban nincs jelen, az
staged lesz a commithoz, de a munkakönyvtárban úgy tűnik majd, mintha
vissza lett volna állítva.

Kerüld ezeknek a konstrukcióknak a használatát, vagy csak rendkívüli
óvatossággal alkalmazd őket.

--
removing untouched content::

Az olyan tartalom, amely nem különbözik az index és a munkakönyvtár
között, kontextussorokon jelenhet meg, amelyek " " (szóköz) karakterrel
kezdődnek. A kontextussorokat az eltávolításhoz stage-elheted a szóköz
"-"-ra alakításával. Az eredményül kapott munkakönyvtár-fájl úgy fog
tűnni, mintha újra hozzáadta volna a tartalmat.

modifying existing content::

A kontextussorokat úgy is módosíthatod, hogy stage-eled őket
eltávolításra (a " " karaktert "-"-ra alakítva), és hozzáadsz egy
„{plus}" sort az új tartalommal. Hasonlóképp módosíthatod a meglévő
hozzáadások vagy módosítások „{plus}" sorait is. Minden esetben az új
módosítás visszavontnak fog tűnni a munkakönyvtárban.

new content::

Olyan új tartalmat is hozzáadhatsz, amely nem létezik a patchben;
egyszerűen adj hozzá új sorokat, mindegyiket „{plus}"-szal kezdve. A
hozzáadás visszavontnak fog tűnni a munkakönyvtárban.
--

Vannak továbbá olyan műveletek is, amelyeket teljesen kerülni kell,
mert lehetetlenné teszik a patch alkalmazását:

* kontextus- (" ") vagy eltávolítási ("-") sorok hozzáadása
* kontextus- vagy eltávolítási sorok törlése
* kontextus- vagy eltávolítási sorok tartalmának módosítása

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

:git-add: 1
include::config/add.adoc[]

SEE ALSO
--------
linkgit:git-status[1]
linkgit:git-rm[1]
linkgit:git-reset[1]
linkgit:git-mv[1]
linkgit:git-commit[1]
linkgit:git-update-index[1]

GIT
---
A linkgit:git[1] csomag része
