git-refs(1)
===========

NAME
----
git-refs - Alacsonyszintű hozzáférés a refekhez


SYNOPSIS
--------
[synopsis]
git refs migrate --ref-format=<format> [--no-reflog] [--dry-run]
git refs verify [--strict] [--verbose]
git refs list [--count=<count>] [--shell|--perl|--python|--tcl]
		   [(--sort=<key>)...] [--format=<format>]
		   [--include-root-refs] [--points-at=<object>]
		   [--merged[=<object>]] [--no-merged[=<object>]]
		   [--contains[=<object>]] [--no-contains[=<object>]]
		   [(--exclude=<pattern>)...] [--start-after=<marker>]
		   [ --stdin | (<pattern>...)]
git refs exists <ref>
git refs optimize [--all] [--no-prune] [--auto] [--include <pattern>] [--exclude <pattern>]
git refs create [--message=<reason>] [--no-deref] [--create-reflog] <ref> <new-value>
git refs delete [--message=<reason>] [--no-deref] <ref> [<old-value>]
git refs update [--message=<reason>] [--no-deref] [--create-reflog] <ref> <new-value> [<old-value>]
git refs rename [--message=<reason>] <old-ref> <new-ref>

DESCRIPTION
-----------

Ez a parancs alacsonyszintű hozzáférést biztosít a refekhez.

COMMANDS
--------

`migrate`::
	Ref-tároló migrálása különböző formátumok között.
+
[WARNING]
--
A ref-formátum migrálásának jelenlegi formájában több ismert korlátja van:

* A worktree-kkel rendelkező repository-k nem migrálhatók.

* Nincs mód a repository-ba irányuló párhuzamos írások blokkolására egy
  folyamatban lévő migráció során. A párhuzamos írások inkonzisztens
  migrált állapothoz vezethetnek. A felhasználóknak magasabb szinten kell
  blokkolniuk az írásokat. Ha a repository-d ütemezett karbantartásra van
  regisztrálva, ajánlott előbb kiregisztrálni a linkgit:git-maintenance[1]-gyel.

Ezek a korlátok idővel feloldásra kerülhetnek.
--

`verify`::
	A referencia-adatbázis konzisztenciájának ellenőrzése.

list::
	A repository-ban lévő referenciák listázása szűrés, formázás és
	rendezés támogatásával. Ez az alparancs a linkgit:git-for-each-ref[1]
	álneve, és azzal azonos funkcionalitást kínál.

exists::
	Ellenőrzi, hogy a megadott referencia létezik-e. 0 kilépési kódot ad
	vissza, ha igen, 2-t, ha hiányzik, és 1-et, ha a referencia
	kikeresése a referencia hiányától eltérő hibával hiúsult meg. Ez nem
	ellenőrzi, hogy a referencia egy tényleges objektumra oldódik-e fel.

optimize::
	Optimalizálja a referenciákat a repository teljesítményének javítása és
	a lemezhasználat csökkentése érdekében. Ez az alparancs a
	linkgit:git-pack-refs[1] álneve, és azzal azonos funkcionalitást kínál.

create::
	A megadott referencia létrehozása – amely még nem létezhet – a
	`<new-value>`-ra mutatva.

delete::
	A megadott referencia törlése. Ez az alparancs a `git update-ref -d`-t
	tükrözi (l. linkgit:git-update-ref[1]). Ha a `<old-value>` meg van
	adva, a referencia csak azután törlődik, hogy ellenőrizve lett: jelenleg
	a `<old-value>`-t tartalmazza.

update::
	A megadott referencia frissítése úgy, hogy a `<new-value>`-ra mutasson.
	Ha a `<old-value>` meg van adva, a referencia csak azután frissül, hogy
	ellenőrizve lett: jelenleg a `<old-value>`-t tartalmazza. Speciális
	esetként a csupa nulla `<new-value>` törli a branchet, míg a csupa nulla
	`<old-value>` biztosítja, hogy a branch még nem létezik.

rename::
	A `<oldref>` referencia átnevezése `<newref>`-re. A régi referenciának
	léteznie kell, az új referencia még nem létezhet, és mindkettőnek
	jól formált nevűnek kell lennie (l. linkgit:git-check-ref-format[1]).

OPTIONS
-------

A következő opciók a `git refs migrate`-re jellemzők:

`--ref-format=<format>`::
	A ref-formátum, amelyre a ref-tárolót migrálni kell. A következők egyike lehet:
+
include::ref-storage-format.adoc[]

`--dry-run`::
	A migráció végrehajtása, de a repository módosítása nélkül. A migrált
	refek egy külön könyvtárba íródnak, amely külön megvizsgálható. A
	könyvtár neve az stdouton jelenik meg. Ezzel ellenőrizhető, hogy a
	migráció a várt módon működik-e, mielőtt a tényleges migrációt
	végrehajtanád.

`--reflog`::
`--no-reflog`::
	Választás aközött, hogy a reflog adatait az új backendre migráljuk,
	vagy eldobjuk.  Az alapértelmezés a "--reflog", azaz a migrálás.

A következő opciók a `git refs verify`-re jellemzők:

`--strict`::
	Szigorúbb hibaellenőrzés bekapcsolása. Ettől a figyelmeztetések
	hibaként jelennek meg. L. linkgit:git-fsck[1].

`--verbose`::
	A referencia-adatbázis konzisztenciájának ellenőrzésekor legyen bőbeszédű.

A következő opciók a 'git refs list'-re jellemzők:

include::for-each-ref-options.adoc[]

A következő opciók a 'git refs optimize'-ra jellemzők:

include::pack-refs-options.adoc[]

A következő opciók a referenciákat író parancsokra jellemzők:

`--create-reflog`::
	Reflog létrehozása a referenciához akkor is, ha egyébként nem jönne
	létre.

`--message=<reason>`::
	A megadott <reason> karakterlánc használata a frissítéshez tartozó
	reflog-bejegyzéshez. Az üres üzenet elutasításra kerül.

`--no-deref`::
	Magán a <ref>-en végezzen műveletet, ne azon a referencián, amelyre az
	egy szimbolikus refen keresztül mutat.

GIT
---
A linkgit:git[1] csomag része
