git-request-pull(1)
===================

NAME
----
git-request-pull - Egy összefoglalót generál a függőben lévő változtatásokról

SYNOPSIS
--------
[synopsis]
git request-pull [-p] <start> <URL> [<end>]

DESCRIPTION
-----------

Generál egy kérést, amely arra kéri az upstream projektet, hogy
húzza be (pull) a változtatásokat a fájukba. A kérés, amely a
standard kimenetre íródik ki, a branch leírásával kezdődik,
összefoglalja a változtatásokat, és jelzi, honnan lehet őket
lehúzni.

Az upstream projektről feltételezi, hogy megvan neki a _<start>_
által megnevezett commit, és a kimenet arra kéri, hogy integrálja az
azóta a commit óta végzett változtatásaidat, egészen a _<end>_ által
megnevezett commitig, a _<URL>_ által megnevezett repository
felkeresésével.


OPTIONS
-------
`-p`::
	Belefoglalja a patch-szöveget a kimenetbe.

_<start>_::
	A kezdő commit. Ez egy olyan commitot nevez meg, amely már
	benne van az upstream előzményekben.

_<URL>_::
	A lehúzáshoz (pull) használandó repository URL.

_<end>_::
	A záró commit (alapértelmezés: `HEAD`). Ez azt a commitot
	nevezi meg, amely az előzmények csúcsán van, amelyet le
	szeretnél húzatni.
+
Ha a _<URL>_ által megnevezett repository-ban a commit egy olyan
referencia csúcsán van, amely eltér a nálad helyileg meglévő
referenciától, használhatod a `<local>:<remote>` szintaxist, hogy
megadd a helyi nevét, egy kettőspontot (`:`), és a remote nevét.


EXAMPLES
--------

Képzeld el, hogy a munkádat a `master` branchen, a `v1.0` kiadás
tetején építetted, és szeretnéd, ha integrálva lenne a projektbe.
Először pusholod ezt a változtatást a nyilvános repository-dba, hogy
mások is lássák:

----
git push https://git.ko.xz/project master
----

Aztán lefuttatod ezt a parancsot:

----
git request-pull v1.0 https://git.ko.xz/project master
----

amely egy kérést állít elő az upstream felé, összefoglalva a `v1.0`
kiadás és a `master`-ed közötti változtatásokat, hogy lehúzhassa
azokat a nyilvános repository-dból.

Ha a változtatásodat egy olyan branchre pusholtad, amelynek neve
eltér a nálad helyileg meglévőtől, pl.

----
git push https://git.ko.xz/project master:for-linus
----

akkor ezt kérheted lehúzatni a következővel:

----
git request-pull v1.0 https://git.ko.xz/project master:for-linus
----


GIT
---
A linkgit:git[1] csomag része
