git-init(1)
===========

NAME
----
git-init - Üres Git repository létrehozása vagy egy meglévő újrainicializálása


SYNOPSIS
--------
[synopsis]
git init [-q | --quiet] [--bare] [--template=<template-directory>]
	 [--separate-git-dir <git-dir>] [--object-format=<format>]
	 [--ref-format=<format>]
	 [-b <branch-name> | --initial-branch=<branch-name>]
	 [--shared[=<permissions>]] [<directory>]


DESCRIPTION
-----------

Ez a parancs egy üres Git repository-t hoz létre – alapvetően egy `.git`
könyvtárat, amelyben alkönyvtárak vannak az `objects`, `refs/heads`,
`refs/tags` számára, valamint sablonfájlok.  Létrejön egy kezdő branch
commitok nélkül (a nevéhez lásd lentebb a `--initial-branch`
opciót).

Ha a `GIT_DIR` környezeti változó be van állítva, akkor az a `./.git`
helyett használandó elérési utat adja meg a repository alapjaként.

Ha az objektumtároló könyvtár a `GIT_OBJECT_DIRECTORY` környezeti
változón keresztül van megadva, akkor a sha1 könyvtárak az alatt jönnek
létre; egyébként az alapértelmezett `$GIT_DIR/objects` könyvtár lesz
használva.

A `git init` futtatása egy meglévő repository-ban biztonságos. Nem írja
felül azt, ami már ott van. A `git init` újrafuttatásának elsődleges oka
az újonnan hozzáadott sablonok átvétele (vagy a repository áthelyezése
máshová, ha a `--separate-git-dir` meg van adva).

OPTIONS
-------

`-q`::
`--quiet`::

Csak hiba- és figyelmeztető üzenetek kiírása; minden más kimenet el lesz nyomva.

`--bare`::

Bare repository létrehozása. Ha a `GIT_DIR` környezeti változó nincs
beállítva, akkor a jelenlegi munkakönyvtárra lesz beállítva.

`--object-format=<format>`::
A megadott objektum-_<format>_ (hash algoritmus) beállítása a
repository-hoz.  Az érvényes értékek: `sha1` és (ha engedélyezve van)
`sha256`.  A `sha1` az alapértelmezés.
+
include::object-format-disclaimer.adoc[]

`--ref-format=<format>`::
A megadott ref-tároló _<format>_ beállítása a repository-hoz. Az érvényes értékek:
+
include::ref-storage-format.adoc[]

`--template=<template-directory>`::
Annak a könyvtárnak a megadása, amelyből a sablonok használva lesznek.
(Lásd lentebb a "TEMPLATE DIRECTORY" szakaszt.)

`--separate-git-dir=<git-dir>`::
Ahelyett, hogy a repository-t könyvtárként inicializálná a `$GIT_DIR`
vagy a `./.git/` alatt, létrehoz ott egy szövegfájlt, amely a tényleges
repository elérési útját tartalmazza.  Ez a fájl fájlrendszertől független
Git szimbolikus linkként működik a repository-hoz.
+
Ha ez újrainicializálás, a repository a megadott elérési útra lesz áthelyezve.

`-b <branch-name>`::
`--initial-branch=<branch-name>`::
A _<branch-name>_ használata a kezdő branchhez az újonnan létrehozott
repository-ban.  Ha nincs megadva, az alapértelmezett névre esik vissza
ifndef::with-breaking-changes[]
(jelenleg `master`, de ez `main`-re változik, amikor a Git 3.0 megjelenik).
endif::with-breaking-changes[]
ifdef::with-breaking-changes[]
`main`.
endif::with-breaking-changes[]
Az alapértelmezett név a `init.defaultBranch` konfigurációs változóval
szabható testre.

`--shared[=(false|true|umask|group|all|world|everybody|<perm>)]`::

Annak megadása, hogy a Git repository több felhasználó között legyen
megosztva.  Ez lehetővé teszi, hogy az azonos csoportba tartozó
felhasználók pusholjanak abba a repository-ba.  Megadásakor a
`core.sharedRepository` konfigurációs változó úgy lesz beállítva, hogy a
`$GIT_DIR` alatti fájlok és könyvtárak a kért jogosultságokkal jöjjenek
létre.  Ha nincs megadva, a Git a `umask`(2) által jelentett
jogosultságokat használja.
+
Az opció a következő értékeket veheti fel, `group`-ra alapértelmezve, ha
nincs érték megadva:
+
--
`umask`::
`false`::

A `umask`(2) által jelentett jogosultságok használata. Az alapértelmezés,
amikor a `--shared` nincs megadva.

`group`::
`true`::

A repository csoport számára írhatóvá tétele (és `g+sx`, mivel a git
csoport nem feltétlenül az összes felhasználó elsődleges csoportja). Ez
egy egyébként biztonságos `umask`(2) érték jogosultságainak lazítására
szolgál. Vedd figyelembe, hogy az umask továbbra is érvényes a többi
jogosultsági bitre (pl. ha az umask `0022`, a `group` használata nem
vesz el olvasási jogot a többi (nem csoportbeli) felhasználótól). A
repository jogosultságainak pontos megadásához lásd a `0xxx`-t.

`all`::
`world`::
`everybody`::

Ugyanaz, mint a `group`, de a repository minden felhasználó számára olvashatóvá válik.

_<perm>_::

A _<perm>_ egy `0`-val kezdődő, 3 számjegyű oktális szám, és minden fájl
_<perm>_ módú lesz. A _<perm>_ felülírja a felhasználók `umask`(2)
értékét (és nem csak lazítja a jogosultságokat, ahogy a `group` és az
`all` teszi). A `0640` olyan repository-t hoz létre, amely csoport
számára olvasható, de nem csoport számára írható, és mások számára sem
elérhető. A `0660` olyan repót hoz létre, amely a jelenlegi felhasználó
és csoport számára olvasható és írható, de mások számára nem elérhető
(a könyvtárak és a végrehajtható fájlok az `x` bitjüket az `r` bitből
kapják a felhasználók megfelelő osztályaira).
--

Alapból a `receive.denyNonFastForwards` konfigurációs kapcsoló engedélyezve
van a megosztott repository-kban, így nem tudsz non-fast-forward pusht
kikényszeríteni bele.

Ha megadsz egy _<directory>_-t, a parancs azon belül fut. Ha ez a könyvtár
nem létezik, létrejön.

TEMPLATE DIRECTORY
------------------

A sablonkönyvtárban lévő azon fájlok és könyvtárak, amelyek neve nem
ponttal kezdődik, a `$GIT_DIR` létrehozása után oda lesznek másolva.

A sablonkönyvtár a következők egyike lesz (sorrendben):

 - a `--template` opcióval megadott argumentum;

 - a `$GIT_TEMPLATE_DIR` környezeti változó tartalma;

 - az `init.templateDir` konfigurációs változó; vagy

 - az alapértelmezett sablonkönyvtár: `/usr/share/git-core/templates`.

Az alapértelmezett sablonkönyvtár tartalmaz némi könyvtárstruktúrát,
javasolt „kizárási mintákat" (lásd linkgit:gitignore[5]) és minta
hook-fájlokat.

A minta hookok alapból mind le vannak tiltva. Egy minta hook
engedélyezéséhez nevezd át úgy, hogy eltávolítod a `.sample` utótagját.

A hook-végrehajtásról szóló általánosabb információért lásd a linkgit:githooks[5] oldalt.

EXAMPLES
--------

Új Git repository indítása egy meglévő kódbázishoz::
+
----------------
$ cd /path/to/my/codebase
$ git init      <1>
$ git add .     <2>
$ git commit    <3>
----------------
+
<1> Létrehoz egy `/path/to/my/codebase/.git` könyvtárat.
<2> Hozzáadja az összes meglévő fájlt az indexhez.
<3> Rögzíti a szűz állapotot az előzmény első commitjaként.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

:git-init:

include::config/init.adoc[]

GIT
---
A linkgit:git[1] csomag része
