git-merge-index(1)
==================

NAME
----
git-merge-index - Merge-et futtat a merge-elést igénylő fájlokra


SYNOPSIS
--------
[verse]
'git merge-index' [-o] [-q] <merge-program> (-a | ( [--] <file>...) )

DESCRIPTION
-----------
Ez felkeresi a <file>(oka)t az indexben, és ha vannak merge-
bejegyzések, átadja azon fájlok SHA-1 hash-ét 1., 2., 3. argumentumként
(üres argumentum, ha nincs fájl), a <file>-t pedig 4. argumentumként.
A három fájl fájlmódjai az 5., 6. és 7. argumentumként kerülnek
átadásra.

OPTIONS
-------
\--::
	A további argumentumokat már nem értelmezi opcióként.

-a::
	Merge-et futtat az index minden olyan fájljára, amely
	merge-elést igényel.

-o::
	Ahelyett, hogy az első sikertelen merge-nél megállna, egy
	menetben végzi el mindet - folytatja a merge-elést akkor is,
	ha a korábbi merge-ek hibát adtak vissza, és csak az összes
	merge után adja vissza a hibakódot.

-q::
	Nem panaszkodik egy sikertelen merge-programra (egy
	merge-program hibája rendszerint konfliktusokra utal a
	merge-elés során). Ez olyan porcelainoknak szól, amelyek egyéni
	üzeneteket szeretnének kiadni.

Ha a 'git merge-index'-et több <file>-lal (vagy -a-val) hívják meg,
akkor sorban feldolgozza őket, csak akkor állva meg, ha a merge nem
nulla kilépési kóddal tér vissza.

Ezt jellemzően egy olyan szkripttel futtatják, amely a Git
utánzatát hívja meg az RCS csomag 'merge' parancsának.

Egy 'git merge-one-file' nevű mintaszkript szerepel a
disztribúcióban.

FIGYELEM, FIGYELEM, FIGYELEM! A Git "merge object order"-je eltér az
RCS 'merge' programjának merge object order-jétől. A fenti
sorrendben az eredeti van elöl. De a háromutas merge-program,
a 'merge', argumentumsorrendjében az eredeti van középen. Ne kérdezd,
miért.

Példák:

----
torvalds@ppc970:~/merge-test> git merge-index cat MM
This is MM from the original tree.		# original
This is modified MM in the branch A.		# merge1
This is modified MM in the branch B.		# merge2
This is modified MM in the branch B.		# current contents
----

vagy

----
torvalds@ppc970:~/merge-test> git merge-index cat AA MM
cat: : No such file or directory
This is added AA in the branch A.
This is added AA in the branch B.
This is added AA in the branch B.
fatal: merge program failed
----

ahol az utóbbi példa megmutatja, hogyan hagyja abba a 'git merge-index'
a merge-elés megkísérlését, amint bármi hibát ad vissza (azaz a `cat`
hibát adott vissza az AA fájlra, mert az nem létezett az eredetiben,
így a 'git merge-index' meg sem próbálta merge-elni az MM dolgot).

GIT
---
A linkgit:git[1] csomag része
