git-count-objects(1)
====================

NAME
----
git-count-objects - A be nem csomagolt objektumok számának és lemezterület-felhasználásának megszámolása

SYNOPSIS
--------
[verse]
'git count-objects' [-v] [-H | --human-readable]

DESCRIPTION
-----------
Megszámolja a be nem csomagolt objektumfájlok számát és az általuk
elfoglalt lemezterületet, hogy segítsen eldönteni, mikor van itt az
ideje az újracsomagolásnak.


OPTIONS
-------
-v::
--verbose::
	Részletesebb jelentés megadása:
+
count: a laza objektumok száma
+
size: a laza objektumok által elfoglalt lemezterület, KiB-ban (hacsak nincs megadva a -H)
+
in-pack: a pack-fájlokban lévő objektumok száma
+
packs: a pack-fájlok száma
+
size-pack: a packok által elfoglalt lemezterület, KiB-ban (hacsak nincs megadva a -H)
+
prune-packable: azon laza objektumok száma, amelyek a packokban is
megtalálhatók. Ezek az objektumok eltávolíthatók a `git prune-packed` paranccsal.
+
garbage: az objektumadatbázisban lévő azon fájlok száma, amelyek sem
érvényes laza objektumok, sem érvényes packok
+
size-garbage: a szemétfájlok (garbage) által elfoglalt lemezterület,
KiB-ban (hacsak nincs megadva a -H)
+
alternate: az alternatív objektumadatbázisok abszolút útvonala; többször
is megjelenhet, soronként egy útvonallal. Vedd figyelembe, hogy ha az
útvonal nem nyomtatható karaktereket tartalmaz, dupla idézőjelek közé
kerülhet, és C-stílusú backslash escape-szekvenciákat tartalmazhat.

-H::
--human-readable::

Méretek kiírása emberi szemmel olvasható formátumban

GIT
---
A linkgit:git[1] csomag része
