git-rev-parse(1)
================

NAME
----
git-rev-parse - Pick out and massage parameters


SYNOPSIS
--------
[verse]
'git rev-parse' [<options>] <arg>...

DESCRIPTION
-----------

Sok Git porcelain-jellegű parancs a flagek
(azaz a '-' kötőjellel kezdődő paraméterek) és a belsőleg használt
'git rev-list' parancsnak szánt paraméterek, valamint a 'git rev-list'
után használt egyéb parancsok flagjeinek és paramétereinek
keverékét fogadja el.  Ennek a parancsnak az elsődleges célja,
hogy lehetővé tegye a hívó programok számára, hogy megkülönböztessék
őket.  Van néhány más működési mód is, amelyeknek semmi közük a fenti
"help parse command line options"-hoz.

Hacsak másképp nincs megadva, az opciók és működési módok többsége
megköveteli, hogy ezt a parancsot egy git repository-n vagy egy git
repository által vezérelt working tree-n belül futtasd, egyébként
végzetes hibát ad.


OPTIONS
-------

[[_operation_modes]]
Működési módok
~~~~~~~~~~~~~~

Ezek az opciók mindegyikének elsőként kell megjelennie a parancssoron.

--parseopt::
	A 'git rev-parse' használata opció-elemző módban (lásd a PARSEOPT szakaszt lentebb).
	A parancs ebben a módban repository-n vagy
	repository által vezérelt working tree-n kívül is használható.

--sq-quote::
	A 'git rev-parse' használata shell-idézőjelezési módban (lásd az
	SQ-QUOTE szakaszt lentebb). Az alábbi `--sq` opcióval ellentétben ez a
	mód csak idézőjelezést végez. Semmi mást nem tesz a parancs bemenetével.
	A parancs ebben a módban repository-n vagy
	repository által vezérelt working tree-n kívül is használható.

[[_options_for_parseopt]]
A --parseopt opciói
~~~~~~~~~~~~~~~~~~~

--keep-dashdash::
	Csak `--parseopt` módban van értelme. Utasítja az opció-elemzőt, hogy
	az első talált `--` jelet írja ki ahelyett, hogy átugorná.

--stop-at-non-option::
	Csak `--parseopt` módban van értelme.  Lehetővé teszi, hogy az opció-elemző
	megálljon az első nem opció argumentumnál.  Ez olyan alparancsok elemzésére
	használható, amelyek maguk is opciókat fogadnak.

--stuck-long::
	Csak `--parseopt` módban van értelme. Az opciókat a hosszú formájukban
	adja ki, ha van ilyen, az argumentumaikkal összeragasztva.

[[_options_for_filtering]]
Szűrési opciók
~~~~~~~~~~~~~~

--revs-only::
	Ne adja ki azokat a flageket és paramétereket, amelyek nem a
	'git rev-list' parancsnak szólnak.

--no-revs::
	Ne adja ki azokat a flageket és paramétereket, amelyek a
	'git rev-list' parancsnak szólnak.

--flags::
	Ne adja ki a nem flag paramétereket.

--no-flags::
	Ne adja ki a flag paramétereket.

[[_options_for_output]]
Kimeneti opciók
~~~~~~~~~~~~~~~

--default <arg>::
	Ha a felhasználó nem adott meg paramétert, helyette a `<arg>`-ot
	használja.

--prefix <arg>::
	Úgy viselkedik, mintha a 'git rev-parse' a working tree `<arg>`
	alkönyvtárából lett volna meghívva.  Minden relatív fájlnév úgy
	oldódik fel, mintha a `<arg>` előtaggal lenne ellátva, és ilyen
	formában lesz kiírva.
+
Ez arra használható, hogy egy alkönyvtárban futó parancs argumentumait
átalakítsuk, hogy a repository legfelső szintjére lépve is használhatók
legyenek.  Például:
+
----
prefix=$(git rev-parse --show-prefix)
cd "$(git rev-parse --show-toplevel)"
# rev-parse provides the -- needed for 'set'
eval "set $(git rev-parse --sq --prefix "$prefix" -- "$@")"
----

--verify::
	Ellenőrzi, hogy pontosan egy paraméter van megadva, és hogy az
	átalakítható egy nyers 20 bájtos SHA-1-gyé, amely az
	objektumadatbázis eléréséhez használható. Ha igen, kiírja a standard
	kimenetre; egyébként hibával kilép.
+
Ha meg akarsz bizonyosodni arról, hogy a kimenet valóban egy objektumot nevez
meg az objektumadatbázisodban, és/vagy használható egy adott, általad
megkövetelt objektumtípusként, hozzáadhatod a `^{type}` lehántó operátort a paraméterhez.
Például a `git rev-parse "$VAR^{commit}"` biztosítja, hogy a `$VAR`
egy létező objektumot nevez meg, amely commit-ish (azaz egy commit, vagy egy
commitra mutató annotált tag).  Annak biztosítására, hogy a `$VAR`
bármilyen típusú létező objektumot nevezzen meg, a `git rev-parse "$VAR^{object}"`
használható.
+
Vedd figyelembe, hogy ha egy nem megbízható forrásból származó nevet ellenőrzöl,
bölcs dolog a `--end-of-options` opciót használni, hogy a névargumentumot ne
tévesszék össze egy másik opcióval.

-q::
--quiet::
	Csak `--verify` módban van értelme. Ne adjon ki hibaüzenetet,
	ha az első argumentum nem érvényes objektumnév;
	ehelyett csendben lépjen ki nem nulla státusszal.
	Az érvényes objektumnevek SHA-1-ei sikeres esetben a stdout-ra kerülnek kiírásra.

--sq::
	A kimenet általában flagenként és paraméterenként egy sorban
	készül.  Ez az opció a kimenetet egyetlen sorrá teszi,
	megfelelően idézőjelezve a shell általi feldolgozáshoz.  Hasznos, ha
	arra számítasz, hogy a paramétered whitespace-t és
	sortöréseket tartalmaz (pl. amikor a pickaxe `-S` opciót használod a
	'git diff-{asterisk}'-gal). A `--sq-quote` opcióval ellentétben
	a parancs bemenete továbbra is a szokásos módon van értelmezve.

--short[=<length>]::
	Ugyanaz, mint a `--verify`, de az objektumnevet egy egyedi,
	legalább `length` karakteres előtagra rövidíti. A minimális hossz
	4, az alapértelmezés a `core.abbrev`
	konfigurációs változó tényleges értéke (lásd linkgit:git-config[1]).

--not::
	Az objektumnevek megjelenítésekor lássa el őket '{caret}' előtaggal, és
	távolítsa el a '{caret}' előtagot azokból az objektumnevekből, amelyeknek már
	van.

--abbrev-ref[=(strict|loose)]::
	Az objektum nevének nem félreérthető rövid neve.
	A core.warnAmbiguousRefs opció a szigorú rövidítési mód
	kiválasztására szolgál.

--symbolic::
	Az objektumnevek általában SHA-1 formában kerülnek kiadásra
	(esetleges '{caret}' előtaggal); ez az opció olyan formában adja ki őket, amely a
	lehető legközelebb áll az eredeti bemenethez.

--symbolic-full-name::
	Ez hasonló a --symbolic opcióhoz, de kihagyja azokat a bemeneteket, amelyek
	nem refek (azaz branch- vagy tagnevek; vagy a kifejezettebben
	egyértelműsítő "heads/master" forma, amikor a "master" branchet akarod
	megnevezni, miközben van egy
	szerencsétlenül elnevezett "master" tag), és teljes
	refnevekként mutatja őket (pl. "refs/heads/master").

--output-object-format=(sha1|sha256|storage)::

	Lehetővé teszi, hogy az oid-ok bármilyen objektumformátumból bevihetők legyenek,
	amelyet az aktuális repository támogat.
+
A "sha1" megadása szükség esetén átalakít, és egy sha1 oid-ot ad vissza.
+
A "sha256" megadása szükség esetén átalakít, és egy sha256 oid-ot ad vissza.
+
A "storage" megadása szükség esetén átalakít, és egy, a tároló
hash-algoritmusában kódolt oid-ot ad vissza.

[[_options_for_objects]]
Objektum-opciók
~~~~~~~~~~~~~~~

--all::
	Az összes `refs/`-ben talált ref megjelenítése.

--branches[=<pattern>]::
--tags[=<pattern>]::
--remotes[=<pattern>]::
	Az összes branch, tag, illetve remote-tracking branch
	megjelenítése (azaz a `refs/heads`,
	`refs/tags`, illetve `refs/remotes` alatt talált refek).
+
Ha meg van adva egy `pattern`, csak a megadott shell globra illeszkedő refek
jelennek meg.  Ha a minta nem tartalmaz globbing karaktert (`?`,
`*` vagy `[`), akkor `/*` hozzáfűzésével előtag-illesztéssé alakul.

--glob=<pattern>::
	Az összes olyan ref megjelenítése, amely illeszkedik a `pattern` shell glob mintára. Ha
	a minta nem `refs/`-fel kezdődik, ez automatikusan elé
	kerül.  Ha a minta nem tartalmaz globbing
	karaktert (`?`, `*` vagy `[`), akkor `/*` hozzáfűzésével előtag-illesztéssé
	alakul.

--exclude=<glob-pattern>::
	Ne vegye figyelembe a '<glob-pattern>'-re illeszkedő refeket, amelyeket a következő `--all`,
	`--branches`, `--tags`, `--remotes` vagy `--glob` egyébként
	figyelembe venne. Ennek az opciónak az ismétlései a kizárási mintákat
	a következő `--all`, `--branches`, `--tags`, `--remotes` vagy
	`--glob` opcióig halmozzák (más opciók vagy argumentumok nem törlik
	a felhalmozott mintákat).
+
A megadott minták ne kezdődjenek `refs/heads`, `refs/tags` vagy
`refs/remotes` előtaggal, amikor `--branches`, `--tags`, illetve `--remotes`
opcióra alkalmazzák őket, és `refs/`-fel kell kezdődniük, amikor `--glob`
vagy `--all` opcióra alkalmazzák. Ha záró '/{asterisk}' a szándék, azt
kifejezetten meg kell adni.

--exclude-hidden=(fetch|receive|uploadpack)::
	Ne vegye figyelembe azokat a refeket, amelyeket a `git-fetch`,
	`git-receive-pack` vagy `git-upload-pack` elrejtene a megfelelő
	`fetch.hideRefs`, `receive.hideRefs` vagy `uploadpack.hideRefs`
	konfiguráció, valamint a `transfer.hideRefs` alapján (lásd
	linkgit:git-config[1]). Ez az opció a következő pszeudoref-opciót
	(`--all` vagy `--glob`) érinti, és a feldolgozásuk után törlődik.

--disambiguate=<prefix>::
	Minden olyan objektum megjelenítése, amelynek neve a megadott előtaggal kezdődik.
	A <prefix> legalább 4 hexadecimális számjegy hosszú kell legyen, hogy
	elkerüljük a repository összes objektumának véletlen
	felsorolását.

[[_options_for_files]]
Fájl-opciók
~~~~~~~~~~~

--local-env-vars::
	A repository-hoz lokális GIT_* környezeti változók listázása
	(pl. GIT_DIR vagy GIT_WORK_TREE, de nem GIT_EDITOR).
	Csak a változók neve van felsorolva, az értékük nem,
	még ha be is vannak állítva.

--path-format=(absolute|relative)::
	Bizonyos más opciók viselkedését vezérli. Ha absolute-ként adják meg, az
	ezen opciók által kiírt útvonalak abszolútak és kanonikusak lesznek. Ha
	relative-ként adják meg, az útvonalak az aktuális munkakönyvtárhoz képest
	relatívak lesznek, ha ez lehetséges.  Az alapértelmezés opciófüggő.
+
Ez az opció többször is megadható, és csak azokat az argumentumokat érinti, amelyek
a parancssoron követik, vagy a parancssor végéig, vagy ennek az opciónak a következő
előfordulásáig.

A következő opciókat módosítja a `--path-format`:

--git-dir::
	A `$GIT_DIR` megjelenítése, ha definiálva van. Egyébként a
	.git könyvtár útvonalának megjelenítése. A megjelenített útvonal, ha relatív,
	az aktuális munkakönyvtárhoz képest relatív.
+
Ha a `$GIT_DIR` nincs definiálva, és az aktuális könyvtárról
nem állapítható meg, hogy egy Git repository-ban vagy working tree-ben van,
üzenetet ír a stderr-re, és nem nulla státusszal lép ki.

--git-common-dir::
	A `$GIT_COMMON_DIR` megjelenítése, ha definiálva van, egyébként a `$GIT_DIR`.

--resolve-git-dir <path>::
	Ellenőrzi, hogy a <path> egy érvényes repository vagy egy
	érvényes repository-ra mutató gitfile, és kiírja a
	repository helyét.  Ha a <path> egy gitfile, akkor a valódi repository
	feloldott útvonala kerül kiírásra.

--git-path <path>::
	Feloldja a "$GIT_DIR/<path>"-t, és figyelembe vesz más útvonal-áthelyezési
	változókat, például a $GIT_OBJECT_DIRECTORY,
	$GIT_INDEX_FILE... változókat. Például ha a
	$GIT_OBJECT_DIRECTORY /foo/bar-ra van állítva, akkor a "git rev-parse
	--git-path objects/abc" a /foo/bar/abc értéket adja vissza.

--show-toplevel::
	A working tree legfelső szintű könyvtárának (alapból abszolút) útvonalának
	megjelenítése. Ha nincs working tree, hibát jelez.

--show-superproject-working-tree::
	Annak a szuperprojektnek a working tree-je gyökerének abszolút útvonalának
	megjelenítése (ha létezik), amely az aktuális repository-t
	submodule-ként használja.  Semmit nem ad ki, ha az aktuális repository-t
	egyetlen projekt sem használja submodule-ként.

--shared-index-path::
	A megosztott indexfájl útvonalának megjelenítése split index módban, vagy
	üres, ha nem split-index módban vagyunk.

A következő opciókat nem érinti a `--path-format`:

--absolute-git-dir::
	Mint a `--git-dir`, de a kimenete mindig a kanonizált
	abszolút útvonal.

--is-inside-git-dir::
	Ha az aktuális munkakönyvtár a repository könyvtára
	alatt van, "true"-t ír ki, egyébként "false"-t.

--is-inside-work-tree::
	Ha az aktuális munkakönyvtár a repository working tree-jén
	belül van, "true"-t ír ki, egyébként "false"-t.

--is-bare-repository::
	Ha a repository bare, "true"-t ír ki, egyébként "false"-t.

--is-shallow-repository::
	Ha a repository shallow, "true"-t ír ki, egyébként "false"-t.

--show-cdup::
	Ha a parancsot egy alkönyvtárból hívják meg, megjeleníti a
	legfelső szintű könyvtár útvonalát az aktuális
	könyvtárhoz képest (jellemzően "../" sorozat, vagy üres sztring).

--show-prefix::
	Ha a parancsot egy alkönyvtárból hívják meg, megjeleníti az
	aktuális könyvtár útvonalát a legfelső szintű
	könyvtárhoz képest.

--show-object-format[=(storage|input|output|compat)]::
	A repository-hoz használt objektumformátum (hash-algoritmus) megjelenítése a
	`.git` könyvtáron belüli tároláshoz, bemenethez, kimenethez vagy kompatibilitáshoz. Bemenet esetén
	több algoritmus is kiírható, szóközzel elválasztva. Ha `compat` van
	kérve, és nincs engedélyezve kompatibilitási algoritmus, üres sort ír ki. Ha
	nincs megadva, az alapértelmezés a "storage".

--show-ref-format::
	A repository-hoz használt referencia-tárolási formátum megjelenítése.


[[_other_options]]
Egyéb opciók
~~~~~~~~~~~~

--since=<datestring>::
--after=<datestring>::
	A dátum-sztring elemzése, és a megfelelő
	--max-age= paraméter kiadása a 'git rev-list' számára.

--until=<datestring>::
--before=<datestring>::
	A dátum-sztring elemzése, és a megfelelő
	--min-age= paraméter kiadása a 'git rev-list' számára.

<arg>...::
	Az elemzendő flagek és paraméterek.


include::revisions.adoc[]

PARSEOPT
--------

`--parseopt` módban a 'git rev-parse' segít az opciók feldolgozásában, hogy a shell
szkriptek ugyanazokat a lehetőségeket kapják, amelyekkel a C built-inek rendelkeznek. Opció-normalizálóként
működik (pl. szétbontja az egyetlen kapcsolóba összevont értékeket), kicsit úgy, ahogy a `getopt(1)` teszi.

A standard bemenetről veszi az elemzendő és értelmezendő opciók
specifikációját, és a standard kimenetre ír egy sztringet, amely alkalmas arra, hogy a `sh(1)` `eval`
az argumentumokat normalizáltakra cserélje.  Hiba esetén a
használati útmutatót a standard hibakimenetre írja, és a 129-es kóddal lép ki.

Megjegyzés: Ügyelj rá, hogy idézőjelezd az eredményt, amikor átadod az `eval`-nak.  Lásd
lentebb egy példát.

[[_input_format]]
Bemeneti formátum
~~~~~~~~~~~~~~~~~

A 'git rev-parse --parseopt' bemeneti formátuma teljesen szöveg alapú. Két részből áll,
amelyeket egy csak `--` jelet tartalmazó sor választ el. Az elválasztó előtti sorok
(egynek vagy többnek kell lennie) a használati útmutatóhoz vannak.
Az elválasztó utáni sorok az opciókat írják le.

Minden opciósor ilyen formátumú:

------------
<opt-spec><flags>*<arg-hint>? SP+ help LF
------------

`<opt-spec>`::
	a formátuma a rövid opciókarakter, majd a hosszú opciónév,
	vesszővel elválasztva. Mindkét rész nem kötelező, bár legalább az egyik
	szükséges. Nem tartalmazhatja a `<flags>` karakterek egyikét sem.
	A `h,help`, `dry-run` és `f` helyes `<opt-spec>` példák.

`<flags>`::
	a `<flags>` a következők egyike: `*`, `=`, `?` vagy `!`.
	* Használj `=`-t, ha az opció argumentumot fogad.

	* Használj `?`-t annak jelzésére, hogy az opció opcionális argumentumot fogad. Valószínűleg
	  a `--stuck-long` módot akarod használni, hogy egyértelműen tudd
	  elemezni az opcionális argumentumot.

	* Használj `*`-ot annak jelzésére, hogy ez az opció ne szerepeljen a
	  `-h` argumentumhoz generált használati útmutatóban. A `--help-all` esetén megjelenik, ahogy
	  azt a linkgit:gitcli[7] dokumentálja.

	* Használj `!`-t, hogy a megfelelő negált hosszú opció ne legyen elérhető.

`<arg-hint>`::
	a `<arg-hint>`, ha meg van adva, az argumentum neveként van használva a
	help kimenetben, azoknál az opcióknál, amelyek argumentumot fogadnak. A `<arg-hint>`-et
	az első whitespace zárja le.  Szokás kötőjelet
	használni a szavak elválasztására egy több szóból álló argumentum-hintben.

A sor maradéka, a szóközök levágása után, az opcióhoz tartozó
helpként van használva.

Az üres sorok figyelmen kívül maradnak, és azok a sorok, amelyek nem illeszkednek erre a specifikációra,
opciócsoport-fejlécként vannak használva (kezdd a sort szóközzel, hogy szándékosan
ilyen sorokat hozz létre).

Példa
~~~~~

------------
OPTS_SPEC="\
some-command [<options>] <args>...

some-command does foo and bar!
--
h,help!   show the help

foo       some nifty option --foo
bar=      some cool option --bar with an argument
baz=arg   another cool option --baz with a named argument
qux?path  qux may take a path argument but has meaning by itself

  An option group Header
C?        option C with an optional argument"

eval "$(echo "$OPTS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"
------------


[[_usage_text]]
Használati szöveg
~~~~~~~~~~~~~~~~~

Amikor a `"$@"` `-h` vagy `--help` a fenti példában, a következő
használati szöveg jelenne meg:

------------
usage: some-command [<options>] <args>...

    some-command does foo and bar!

    -h, --help            show the help
    --[no-]foo            some nifty option --foo
    --[no-]bar ...        some cool option --bar with an argument
    --[no-]baz <arg>      another cool option --baz with a named argument
    --[no-]qux[=<path>]   qux may take a path argument but has meaning by itself

An option group Header
    -C[...]               option C with an optional argument
------------

SQ-QUOTE
--------

`--sq-quote` módban a 'git rev-parse' a standard kimenetre ír egy
egyetlen sort, amely alkalmas a `sh(1)` `eval` számára. Ez a sor a
`--sq-quote` után következő argumentumok normalizálásával jön létre. Az
argumentumok idézőjelezésén kívül semmi mást nem tesz.

Ha azt szeretnéd, hogy a parancs bemenetét a 'git rev-parse' továbbra is a
szokásos módon értelmezze, mielőtt a kimenet shell-idézőjelezésre kerül, lásd a `--sq`
opciót.

Példa
~~~~~

------------
$ cat >your-git-script.sh <<\EOF
#!/bin/sh
args=$(git rev-parse --sq-quote "$@")   # quote user-supplied arguments
command="git frotz -n24 $args"          # and use it inside a handcrafted
					# command line
eval "$command"
EOF

$ sh your-git-script.sh "a b'c"
------------

EXAMPLES
--------

* Az aktuális commit objektumnevének kiírása:
+
------------
$ git rev-parse --verify HEAD
------------

* A commit objektumnevének kiírása a $REV shell-változóban lévő revízióból:
+
------------
$ git rev-parse --verify --end-of-options $REV^{commit}
------------
+
Ez hibával kilép, ha a $REV üres vagy nem érvényes revízió.

* Hasonló a fentihez:
+
------------
$ git rev-parse --default master --verify --end-of-options $REV
------------
+
de ha a $REV üres, a master commit objektumneve kerül kiírásra.

GIT
---
A linkgit:git[1] csomag része
