git-pull(1)
===========

NAME
----
git-pull - Fetchelés egy másik repositoryból vagy lokális branchből és integrálása


SYNOPSIS
--------
[synopsis]
git pull [<options>] [<repository> [<refspec>...]]


DESCRIPTION
-----------

Egy remote repositoryból származó változtatások integrálása az aktuális
branchbe.

Először a `git pull` lefuttatja a `git fetch`-et ugyanazokkal az
argumentumokkal (a merge-opciók kivételével), hogy fetchelje a remote
branch(eke)t.
Ezután eldönti, melyik remote branchet integrálja: ha argumentumok nélkül
futtatod a `git pull`-t, ez alapból az aktuális branchhez tartozó
<<UPSTREAM-BRANCHES,upstream>>-ra áll.
Ezután integrálja azt a branchet az aktuális branchbe.

A remote branch integrálására 4 fő lehetőség van:

1. A `git pull --ff-only` csak "fast-forward" frissítéseket végez: sikertelen,
   ha a lokális branched eltért a remote branchtől.
   Ez az alapértelmezés.
2. A `git pull --rebase` lefuttatja a `git rebase`-t
3. A `git pull --no-rebase` lefuttatja a `git merge`-t.
4. A `git pull --squash` lefuttatja a `git merge --squash`-t

A kívánt viselkedést a `pull.rebase`, `pull.squash` vagy `pull.ff`
konfigurációs opcióval is beállíthatod.

Ha a merge vagy rebase közben olyan merge-konfliktus lép fel, amelyet nem
akarsz kezelni, biztonságosan megszakíthatod a `git merge --abort` vagy a
`git rebase --abort` paranccsal.

OPTIONS
-------

_<repository>_::
	A "remote" repository, amelyből pull-olni kell.  Ez lehet vagy egy
	URL (lásd lent a <<URLS,GIT URL-ek>> szakaszt), vagy egy remote neve
	(lásd lent a <<REMOTES,REMOTES>> szakaszt).
+
Alapból az aktuális branchhez beállított upstreamre, vagy az `origin`-ra áll.
Az upstreamek beállításáról bővebben lásd lent a
<<UPSTREAM-BRANCHES,UPSTREAM BRANCHES>> szakaszt.

_<refspec>_::
	Melyik branchet vagy más referenciá(ka)t kell fetchelni és integrálni
	az aktuális branchbe, például `main` a `git pull origin main`-ben.
	Alapból az aktuális branchhez beállított upstreamre áll.
+
Ez lehet egy branch, tag vagy más referenciák gyűjteménye.
A teljes szintaxisért lásd lent a <<fetch-refspec,_<refspec>_>>-et a
„Fetcheléssel kapcsolatos opciók" szakaszban, azt pedig, hogy a `git pull`
hogyan használja ezt az argumentumot annak eldöntéséhez, melyik remote
branchet integrálja, lásd lent a <<DEFAULT-BEHAVIOUR,DEFAULT BEHAVIOUR>>
szakaszban.

`-q`::
`--quiet`::
	Ez átadódik mind a mögöttes git-fetchnek az átvitel közbeni jelentés
	elnyomásához, mind a mögöttes git-merge-nek a merge-elés közbeni kimenet
	elnyomásához.

`-v`::
`--verbose`::
	A `--verbose` átadása a git-fetchnek és a git-merge-nek.

`--recurse-submodules[=(yes|on-demand|no)]`::
`--no-recurse-submodules`::
	Ez a kapcsoló szabályozza, hogy a feltöltött submodule-ok új commitjait
	fetchelni kell-e, és hogy az aktív submodule-ok munkakönyvtárait is
	frissíteni kell-e (lásd linkgit:git-fetch[1], linkgit:git-config[1] és
	linkgit:gitmodules[5]).
+
Ha a checkout rebase-en keresztül történik, a lokális submodule-commitok is
rebase-elődnek.
+
Ha a frissítés merge-en keresztül történik, a submodule-konfliktusok
feloldódnak és checkoutolódnak.

[[_options_related_to_merging]]
Merge-eléssel kapcsolatos opciók
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:git-pull: 1

include::merge-options.adoc[]

`-r`::
`--rebase[=(true|merges|false|interactive)]`::
`true`;; a fetchelés után az aktuális branch rebase-elése az upstream
	branch tetejére. Ha van az upstream branchnek megfelelő
	remote-tracking branch, és az upstream branchet az utolsó fetchelés
	óta rebase-elték, a rebase ezt az információt használja, hogy elkerülje
	a nem lokális változtatások rebase-elését. Ez az alapértelmezés.

`merges`;; rebase-elés `git rebase --rebase-merges`-dzsel, hogy a lokális
merge-commitok is bekerüljenek a rebase-be (részletekért lásd
linkgit:git-rebase[1]).
`false`;; az upstream branch merge-elése az aktuális branchbe.
`interactive`;; a rebase interaktív módjának engedélyezése.

+
Ha azt szeretnéd, hogy a `git pull` merge-elés helyett mindig a `--rebase`-t
használja, lásd a `pull.rebase`, `branch.<name>.rebase` és
`branch.autoSetupRebase` beállítást a linkgit:git-config[1]-ben.
+
[NOTE]
Ez egy potenciálisan _veszélyes_ működési mód.
Átírja az előzményt, ami nem sok jóval kecsegtet, ha az előzményt már
publikáltad.  *Ne* használd ezt a kapcsolót, hacsak nem olvastad el
figyelmesen a linkgit:git-rebase[1]-et.

`--no-rebase`::
	Ez a `--rebase=false` rövidítése.

[[_options_related_to_fetching]]
Fetcheléssel kapcsolatos opciók
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

include::urls-remotes.adoc[]

include::merge-strategies.adoc[]

[[DEFAULT-BEHAVIOUR]]
DEFAULT BEHAVIOUR
-----------------

Az emberek gyakran paraméter megadása nélkül használják a `git pull`-t.
Hagyományosan ez egyenértékű volt a `git pull origin` kiadásával.  Ha
azonban a `branch.<name>.remote` beállítás jelen van, miközben a `<name>`
branchen vagy, az `origin` helyett azt az értéket használja.

Annak eldöntéséhez, milyen URL-t használjon a fetcheléshez, a
`remote.<origin>.url` beállítás értékét nézi meg, és ha nincs ilyen
változó, a `$GIT_DIR/remotes/<origin>` `URL:` sorában lévő értéket
használja.

Annak eldöntéséhez, mely remote brancheket fetchelje (és opcionálisan
tárolja a remote-tracking branchekben), amikor a parancsot a parancssorban
refspec-paraméterek nélkül futtatják, a `remote.<origin>.fetch`
konfigurációs változó értékeit nézi meg, és ha nincsenek, a
`$GIT_DIR/remotes/<origin>`-t nézi meg, és annak `Pull:` sorait használja.
Az OPTIONS szakaszban leírt refspec-formátumokon túl olyan globbing
refspecet is használhatsz, amely így néz ki:

------------
refs/heads/*:refs/remotes/origin/*
------------

Egy globbing refspecnek nem üres jobb oldallal (RHS) kell rendelkeznie
(azaz tárolnia kell a fetchelteket a remote-tracking branchekben), és a bal
(LHS) és jobb (RHS) oldalának `/*`-ra kell végződnie.  A fenti azt adja
meg, hogy az összes remote branchet a `refs/remotes/origin/` hierarchiában
lévő, azonos nevű remote-tracking branchek követik.

A szabály, amely eldönti, melyik remote branchet kell merge-elni a
fetchelés után, kissé bonyolult, hogy ne törje meg a visszafelé
kompatibilitást.

Ha explicit refspecek voltak megadva a `git pull` parancssorában, azok mind
merge-elődnek.

Ha nem volt refspec megadva a parancssorban, akkor a `git pull` a
konfigurációból vagy a `$GIT_DIR/remotes/<origin>`-ból származó refspecet
használja.  Ilyen esetekben a következő szabályok érvényesek:

. Ha létezik `branch.<name>.merge` beállítás az aktuális _<name>_ branchhez,
  az a remote oldalon lévő azon branch neve, amelyet merge-el.

. Ha a refspec globbing típusú, semmit sem merge-el.

. Egyébként az első refspec remote branchét merge-eli.


EXAMPLES
--------

* Frissítsd a remote-tracking brancheket ahhoz a repositoryhoz, amelyből
  klónoztál, majd merge-eld az egyiket az aktuális branchedbe:
+
------------------------------------------------
$ git pull
$ git pull origin
------------------------------------------------
+
Normál esetben a bemerge-elt branch a remote repository `HEAD`-je, de a
választást a `branch.<name>.remote` és a `branch.<name>.merge` opció
határozza meg; részletekért lásd linkgit:git-config[1].

* Merge-eld az aktuális branchbe a `next` remote branchet:
+
------------------------------------------------
$ git pull origin next
------------------------------------------------
+
Ez ideiglenesen a `FETCH_HEAD`-ben hagyja a `next` egy másolatát, és
frissíti az `origin/next` remote-tracking branchet.
Ugyanez elvégezhető a fetch és a merge meghívásával:
+
------------------------------------------------
$ git fetch origin
$ git merge origin/next
------------------------------------------------


Ha megpróbáltál egy pull-t, amely bonyolult konfliktusokat eredményezett,
és elölről kezdenéd, a `git reset`-tel állhatsz helyre.


include::transfer-data-leaks.adoc[]

BUGS
----
A `--recurse-submodules` használata jelenleg csak a már checkoutolt
submodule-okban tud új commitokat fetchelni. Ha pl. az upstream egy új
submodule-t adott hozzá a szuperprojekt éppen fetchelt commitjaiban, magát
a submodule-t nem lehet fetchelni, ami lehetetlenné teszi az adott
submodule későbbi checkoutolását anélkül, hogy újra fetchelni kellene. Ezt
várhatóan egy jövőbeli Git-verzió javítja.

SEE ALSO
--------
linkgit:git-fetch[1], linkgit:git-merge[1], linkgit:git-config[1]

GIT
---
A linkgit:git[1] csomag része
