git-last-modified(1)
====================

NAME
----
git-last-modified - KÍSÉRLETI: Megjeleníti, mikor módosultak utoljára a fájlok


SYNOPSIS
--------
[synopsis]
git last-modified [--recursive] [--show-trees] [--max-depth=<depth>] [-z]
		  [<revision-range>] [[--] <pathspec>...]

DESCRIPTION
-----------

Megjeleníti, hogy az egyes érintett fájlokat és alkönyvtárakat melyik
commit módosította utoljára. Egy útvonalat átnevező, vagy annak
módját megváltoztató commit is figyelembe van véve.

EZ A PARANCS KÍSÉRLETI. A VISELKEDÉSE MEGVÁLTOZHAT.

OPTIONS
-------

`-r`::
`--recursive`::
	Rekurzívan bejár minden alfát. Alapértelmezés szerint a parancs
	csak a `<pathspec>`-nek megfelelő fabejegyzéseket mutatja. Ezzel
	az opcióval leszáll az alfákba, és megjeleníti a bennük lévő
	összes bejegyzést. Egyenértékű a `--max-depth=-1`-gyel.

`-t`::
`--show-trees`::
	Megjeleníti a fabejegyzéseket akkor is, ha belébejár.

`--max-depth=<depth>`::
	A parancssorban megadott minden pathspecnél legfeljebb `<depth>`
	szintig száll le az alfákba. Egy negatív érték korlátlant
	jelent. Az alapértelmezés 0, amely az összes, a pathspecnek
	megfelelő útvonalat megjeleníti, anélkül, hogy leszállna az
	alfákba.

`-z`::
	Minden sort egy _NUL_ karakterrel zár le, újsor helyett.

`<revision-range>`::
	Csak a megadott revíziótartományban lévő commitokat járja be.
	Ha nincs `<revision-range>` megadva, alapértelmezés szerint
	`HEAD` (azaz az aktuális commithoz vezető teljes előzmény). A
	`<revision-range>` megadásának teljes listájáért lásd a
	linkgit:gitrevisions[7] 'Specifying Ranges' szakaszát.

`[--] <pathspec>...`::
	Megjeleníti azt a commitot, amely a _<pathspec>_-nek megfelelő
	minden útvonalat utoljára módosított. Ha nincs _<pathspec>_
	megadva, minden fájl és alkönyvtár bekerül. A pathspec-szintaxis
	részleteiért lásd a linkgit:gitglossary[7]-et.

OUTPUT
------

A kimenet formátuma:

------------
 <oid> TAB <path> LF
------------

Ha egy útvonal bármilyen speciális karaktert tartalmaz, az útvonal
C-stílusban idézőjelbe kerül. Az idézőjelezés elkerüléséhez add meg a
`-z` opciót, hogy minden sort NUL-lal zárjon le.

------------
 <oid> TAB <path> NUL
------------

SEE ALSO
--------
linkgit:git-blame[1],
linkgit:git-log[1].

GIT
---
A linkgit:git[1] csomag része
