git-diff-index(1)
=================

NAME
----
git-diff-index - Egy fa összehasonlítása a munkakönyvtárral vagy az indexszel


SYNOPSIS
--------
[verse]
'git diff-index' [-m] [--cached] [--merge-base] [<common-diff-options>] <tree-ish> [<path>...]

DESCRIPTION
-----------
Összehasonlítja egy fa-objektumban található blobok tartalmát és módját
a munkakönyvtárban lévő megfelelő követett fájlokkal, vagy az indexben
lévő megfelelő útvonalakkal.  Ha <path> argumentumok vannak megadva,
csak az azoknak a mintáknak megfelelő útvonalakat hasonlítja össze.
Egyébként az összes követett fájlt összehasonlítja.

OPTIONS
-------
include::diff-options.adoc[]

<tree-ish>::
	Annak a fa-objektumnak az azonosítója, amelyhez a diff készül.

--cached::
	Egyáltalán nem veszi figyelembe a lemezen lévő fájlt.

--merge-base::
	A <tree-ish> közvetlen összehasonlítása helyett a <tree-ish> és
	a HEAD közötti merge-alapot használja.  A <tree-ish>-nek
	commitnak kell lennie.

-m::
	Alapértelmezés szerint az indexben rögzített, de ki nem
	checkoutolt fájlok töröltként jelennek meg.  Ez a kapcsoló
	azt eredményezi, hogy a 'git diff-index' minden ki nem
	checkoutolt fájlt naprakésznek mond.

include::diff-format.adoc[]

OPERATING MODES
---------------
Választhatsz, hogy teljesen megbízol az indexfájlban (a `--cached`
kapcsoló használatával), vagy megkéred a diff-logikát, hogy minden
olyan fájlt, amely nem egyezik a stat-állapottal, "feltételezetten
megváltozottként" mutasson.  Mindkét működési mód igen hasznos.

CACHED MODE
-----------
Ha a `--cached` meg van adva, akkor a következőt kérdezheted meg:

	mutasd meg a HEAD és a jelenlegi index tartalma közötti
	különbségeket (azokat, amelyeket a 'git write-tree'
	paranccsal írnék ki)

Tegyük fel például, hogy dolgoztál a munkakönyvtáradon, frissítettél
néhány fájlt az indexben, és készen állsz a commitolásra. Pontosan
látni akarod, *mit* fogsz commitolni, anélkül hogy egy új
fa-objektumot kellene írnod és úgy hasonlítanád össze; ehhez egyszerűen
csak ennyit kell tenned:

	git diff-index --cached HEAD

Példa: tegyük fel, hogy átneveztem a `commit.c`-t `git-commit.c`-re, és
végrehajtottam egy `update-index`-et, hogy ez érvénybe lépjen az
indexfájlban.  A `git diff-files` egyáltalán nem mutatna semmit, mivel
az indexfájl megegyezik a munkakönyvtárammal. De egy 'git diff-index'
futtatása igen:

  torvalds@ppc970:~/git> git diff-index --cached HEAD
  :100644 000000 4161aecc6700a2eb579e842af0b7f22b98443f74 0000000000000000000000000000000000000000 D	commit.c
  :000000 100644 0000000000000000000000000000000000000000 4161aecc6700a2eb579e842af0b7f22b98443f74 A	git-commit.c

Könnyen látható, hogy a fenti egy átnevezés.

Valójában a `git diff-index --cached`-nek *mindig* teljesen egyenértékűnek
*kellene* lennie azzal, mintha ténylegesen elvégeznél egy 'git write-tree'-t
és azt hasonlítanád össze. Ez a módszer viszont sokkal kényelmesebb arra az
esetre, ha csak azt akarod ellenőrizni, hol tartasz.

Tehát a `git diff-index --cached` futtatása alapvetően akkor nagyon
hasznos, ha azt kérdezed magadtól, hogy "mit jelöltem már meg
commitolásra, és mi a különbség egy korábbi fához képest".

NON-CACHED MODE
---------------
A "non-cached" (nem gyorsítótárazott) mód más megközelítést alkalmaz, és
a kettő közül potenciálisan hasznosabb, mivel amit csinál, azt nem lehet
egy 'git write-tree' + 'git diff-tree' kombinációval emulálni. Emiatt ez
az alapértelmezett mód. A non-cached változat a következő kérdést teszi
fel:

  mutasd meg a HEAD és a jelenleg checkoutolt fa közötti különbségeket
  - az index tartalmát _és_ a nem naprakész fájlokat is

ami nyilvánvalóan szintén nagyon hasznos kérdés, mivel megmutatja, mit
*tudnál* commitolni. A kimenet ismét pontosan megegyezik a
'git diff-tree -r' kimenetével, de egy csavarral.

A csavar az, hogy ha egy fájl nem egyezik az indexszel, akkor nincs
hozzá tartozó háttértároló-elemünk, és ezt a varázslatos "csupa nulla"
sha1-gyel jelezzük. Tegyük fel tehát, hogy szerkesztetted a
`kernel/sched.c`-t, de még nem futtattál rajta egy 'git update-index'-et
- az új állapothoz nem tartozik "objektum", és ezt kapod:

  torvalds@ppc970:~/v2.6/linux> git diff-index --abbrev HEAD
  :100644 100644 7476bb5ba 000000000 M	kernel/sched.c

azaz megmutatja, hogy a fa megváltozott, és hogy a `kernel/sched.c` nem
naprakész, és új tartalmat tartalmazhat. A csupa nulla sha1 azt
jelenti, hogy a valódi diff megtekintéséhez közvetlenül a
munkakönyvtárban lévő objektumot kell megnézned, objektum-objektum diff
elvégzése helyett.

NOTE: Az ilyen típusú többi parancshoz hasonlóan a 'git diff-index'
valójában egyáltalán nem vizsgálja a fájl tartalmát. Így lehet, hogy a
`kernel/sched.c` valójában nem is változott, és csak hozzáértél. Bármelyik
esetben ez arra figyelmeztet, hogy futtatnod kell rajta a
'git update-index'-et, hogy az index szinkronban legyen.

NOTE: Előfordulhat, hogy egyszerre jelennek meg "frissítve lett" és
"még mindig piszkos a munkakönyvtárban" állapotú fájlok is. Mindig meg
tudod állapítani, melyik fájl melyik állapotban van, mivel a "frissítve
lett" fájlok érvényes sha1-et mutatnak, a "nincs szinkronban az
indexszel" fájlok pedig mindig a speciális csupa nulla sha1-et kapják.

GIT
---
A linkgit:git[1] csomag része
