git-merge-file(1)
=================

NAME
----
git-merge-file - Háromutas fájl-merge futtatása


SYNOPSIS
--------
[verse]
'git merge-file' [-L <current-name> [-L <base-name> [-L <other-name>]]]
	[--ours|--theirs|--union] [-p|--stdout] [-q|--quiet] [--marker-size=<n>]
	[--[no-]diff3] [--object-id] <current> <base> <other>


DESCRIPTION
-----------
Adott három fájl, a `<current>`, a `<base>` és az `<other>`; a
'git merge-file' minden olyan változtatást beépít a `<current>`-be,
amely a `<base>`-től az `<other>`-hez vezet. Az eredmény rendszerint a
`<current>`-be kerül. A 'git merge-file' egy eredeti fájlon végzett
külön változtatások egyesítésére hasznos. Tegyük fel, hogy a `<base>`
az eredeti, a `<current>` és az `<other>` pedig egyaránt a `<base>`
módosításai; ekkor a 'git merge-file' egyesíti mindkét változtatást.

Konfliktus keletkezik, ha mind a `<current>`-ben, mind az `<other>`-ben
van változtatás a sorok egy közös szakaszában. Ha talál konfliktust, a
'git merge-file' általában figyelmeztetést ad, és a konfliktust
<<<<<<< és >>>>>>> jelölőket tartalmazó sorokkal keríti be. Egy tipikus
konfliktus így néz ki:

	<<<<<<< A
	lines in file A
	=======
	lines in file B
	>>>>>>> B

Ha vannak konfliktusok, a felhasználónak szerkesztenie kell az
eredményt, és törölnie kell az egyik alternatívát.  Ha azonban a
`--ours`, `--theirs` vagy `--union` opció van érvényben, ezek a
konfliktusok úgy oldódnak fel, hogy rendre a `<current>` sorait, az
`<other>` sorait, illetve mindkettő sorait részesítik előnyben.  A
konfliktusjelölők hossza a `--marker-size` opcióval adható meg.

Ha a `--object-id` meg van adva, pontosan ugyanez a viselkedés
történik, azzal a különbséggel, hogy a mergelendő tartalmat nem
fájlként, hanem blobokra hivatkozó objektumazonosítók listájaként adod
meg.

A program kilépési értéke hiba esetén negatív, egyébként a
konfliktusok száma (127-re csonkítva, ha ennél több konfliktus van).
Ha a merge tiszta volt, a kilépési érték 0.

A 'git merge-file' az RCS 'merge' minimális klónjának készült; azaz az
RCS 'merge' minden olyan funkcióját megvalósítja, amelyre a
linkgit:git[1]-nek szüksége van.


OPTIONS
-------

--object-id::
	A mergelendő tartalmat fájlok helyett az aktuális repository-ban lévő
	blobokként add meg.  Ebben az esetben a műveletnek érvényes
	repository-n belül kell történnie.
+
Ha a `-p` opció meg van adva, a merge-elt fájl (a konfliktusokkal
együtt, ha vannak) a szokásos módon a standard kimenetre kerül;
egyébként a merge-elt fájl az objektumtárba íródik, a blobjának
objektumazonosítója pedig a standard kimenetre.

-L <label>::
	Ez az opció legfeljebb háromszor adható meg, és olyan címkéket ad
	meg, amelyeket a konfliktusjelentésekben a megfelelő fájlnevek
	helyett kell használni. Azaz a
	`git merge-file -L x -L y -L z a b c` olyan kimenetet állít elő,
	amely úgy néz ki, mintha az a, b és c fájlok helyett az x, y és z
	fájlokból származna.

-p::
	Az eredményeket a standard kimenetre küldi a `<current>` felülírása
	helyett.

-q::
	Csendes; nem figyelmeztet a konfliktusokra.

--diff3::
	A konfliktusokat "diff3" stílusban jeleníti meg.

--zdiff3::
	A konfliktusokat "zdiff3" stílusban jeleníti meg.
+
A `--diff3` és a `--zdiff3` opció alapértelmezése a
`merge.conflictStyle` konfigurációs változó értéke (lásd
linkgit:git-config[1]).

--ours::
--theirs::
--union::
	A konfliktusok fájlban hagyása helyett úgy oldja fel a
	konfliktusokat, hogy a sorok saját (vagy az ő, vagy mindkét)
	oldalát részesíti előnyben.

--diff-algorithm={patience|minimal|histogram|myers}::
	Más diff algoritmust használ a merge során. A jelenlegi
	alapértelmezés a "myers", de egy újabb algoritmus, például a
	"histogram" választása segíthet elkerülni a lényegtelen egyező
	sorok (például különböző függvények kapcsos zárójelei) miatt
	bekövetkező hibás merge-eket. Lásd még a linkgit:git-diff[1]
	`--diff-algorithm`-ot.

EXAMPLES
--------

`git merge-file README.my README README.upstream`::

	egyesíti a README.my és a README.upstream README óta történt
	változtatásait, megpróbálja merge-elni őket, és az eredményt a
	README.my-ba írja.

`git merge-file -L a -L b -L c tmp/a123 tmp/b234 tmp/c345`::

	merge-eli a tmp/a123-at és a tmp/c345-öt a tmp/b234 alappal, de az
	`a` és `c` címkéket használja a `tmp/a123` és `tmp/c345` helyett.

`git merge-file -p --object-id abc1234 def567 890abcd`::

	egyesíti az abc1234 és a 890abcd blob def567 óta történt
	változtatásait, megpróbálja merge-elni őket, és az eredményt a
	standard kimenetre írja

GIT
---
A linkgit:git[1] csomag része
