git-sh-setup(1)
===============

NAME
----
git-sh-setup - Közös Git shell-szkript inicializáló kód

SYNOPSIS
--------
[verse]
'. "$(git --exec-path)/git-sh-setup"'

DESCRIPTION
-----------

Ez nem olyan parancs, amelyet a végfelhasználó valaha is futtatni
szeretne. Soha. Ez a dokumentáció azoknak szól, akik a
porcelain-szerű szkripteket tanulmányozzák, és/vagy újakat írnak.

A 'git sh-setup' szkriptrészletet arra tervezték, hogy más
shell-szkriptek behúzzák (a `.` használatával), és így beállítson
néhány, a szokásos Git-könyvtárakra mutató változót, valamint
néhány segéd shell-függvényt.

Behúzása előtt a szkriptednek be kell állítania néhány változót;
az `USAGE` (és a `LONG_USAGE`, ha van) a `usage()` shell-függvény
által adott üzenet meghatározására szolgál. A `SUBDIRECTORY_OK`
akkor állítható be, ha a szkript a working tree egy alkönyvtárából
is futtatható (egyes parancsok nem).

A szkriptrészlet beállítja a `GIT_DIR` és a `GIT_OBJECT_DIRECTORY`
shell-változókat, de *nem* exportálja őket a környezetbe.

FUNCTIONS
---------

die::
	kilép, miután a megadott hibaüzenetet kiírta a standard
	hibakimenetre.

usage::
	die a használati üzenettel.

set_reflog_action::
	Beállítja a `GIT_REFLOG_ACTION` környezeti változót egy adott
	karakterláncra (jellemzően a program nevére), hacsak nincs már
	beállítva. Valahányszor a szkript egy referenciákat frissítő
	`git` parancsot futtat, létrejön egy reflog-bejegyzés ennek a
	karakterláncnak az értékével, hogy nyoma maradjon, melyik
	parancs frissítette a referenciát.

git_editor::
	a felhasználó által választott szerkesztőt (GIT_EDITOR,
	core.editor, VISUAL vagy EDITOR) futtatja egy adott fájlon, de
	hibával leáll, ha nincs szerkesztő megadva, és a terminál dumb.

is_bare_repository::
	`true` vagy `false` értéket ír a standard kimenetre annak
	jelzésére, hogy a repository bare repository-e (azaz nincs
	hozzá tartozó working tree).

cd_to_toplevel::
	chdir-t futtat a working tree legfelső szintjére.

require_work_tree::
	ellenőrzi, hogy az aktuális könyvtár a repository working
	tree-jén belül van-e, egyébként die.

require_work_tree_exists::
	ellenőrzi, hogy létezik-e a repository-hoz tartozó working
	tree, egyébként die. Gyakran a cd_to_toplevel hívása előtt
	történik, amit lehetetlen elvégezni, ha nincs working tree.

require_clean_work_tree <action> [<hint>]::
	ellenőrzi, hogy a repository-hoz tartozó working tree-ben és
	indexben nincsenek nem commitolt módosítások a követett
	fájlokon. Egyébként `Cannot <action>: <reason>. <hint>` alakú
	hibaüzenetet ír ki, és die. Példa:
+
----------------
require_clean_work_tree rebase "Please commit or stash them."
----------------

get_author_ident_from_commit::
	eval-lal használható kódot ír ki, amely beállítja a
	GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL és GIT_AUTHOR_DATE változókat
	egy adott commithoz.

create_virtual_base::
	úgy módosítja az első fájlt, hogy csak a második fájllal közös
	sorok maradjanak meg. Ha nincs elég közös anyag, akkor az első
	fájl üresen marad. Az eredmény alkalmas virtuális alap
	bemenetként egy háromutas merge-hez.

GIT
---
A linkgit:git[1] csomag része
