git-update-index(1)
===================

NAME
----
git-update-index - A munkakönyvtárban lévő fájlok tartalmának regisztrálása az indexben


SYNOPSIS
--------
[verse]
'git update-index'
	     [--add] [--remove | --force-remove] [--replace]
	     [--refresh] [-q] [--unmerged] [--ignore-missing]
	     [(--cacheinfo <mode>,<object>,<file>)...]
	     [--chmod=(+|-)x]
	     [--[no-]assume-unchanged]
	     [--[no-]skip-worktree]
	     [--[no-]ignore-skip-worktree-entries]
	     [--[no-]fsmonitor-valid]
	     [--ignore-submodules]
	     [--[no-]split-index]
	     [--[no-|test-|force-]untracked-cache]
	     [--[no-]fsmonitor]
	     [--really-refresh] [--unresolve] [--again | -g]
	     [--info-only] [--index-info]
	     [-z] [--stdin] [--index-version <n>]
	     [--show-index-version]
	     [--verbose]
	     [--] [<file>...]

DESCRIPTION
-----------
Módosítja az indexet. Minden megadott fájl frissül az indexben, és
az 'unmerged' vagy 'needs updating' állapot törlődik.

Lásd még a linkgit:git-add[1] parancsot, amely felhasználóbarátabb módon
végzi el az index néhány leggyakoribb műveletét.

Az, hogy a 'git update-index' hogyan kezeli a neki megadott fájlokat,
a különféle opciókkal módosítható:

OPTIONS
-------
--add::
	Ha egy megadott fájl még nincs az indexben, akkor
	hozzáadódik.
	Az alapértelmezett viselkedés az új fájlok figyelmen kívül hagyása.

--remove::
	Ha egy megadott fájl benne van az indexben, de hiányzik, akkor
	eltávolításra kerül.
	Az alapértelmezett viselkedés az eltávolított fájlok figyelmen kívül hagyása.

--refresh::
	Megnézi az aktuális indexet, és a stat() információk
	ellenőrzésével megállapítja, szükséges-e merge vagy frissítés.

-q::
        Csendes mód. Ha a --refresh azt találja, hogy az indexet frissíteni
        kell, az alapértelmezett viselkedés a hibával való leállás. Ez az
	opció miatt a 'git update-index' ennek ellenére folytatja.

--ignore-submodules::
	Ne próbálja frissíteni a submodule-okat. Ez az opció csak akkor
	érvényesül, ha a --refresh előtt van megadva.

--unmerged::
        Ha a --refresh nem merge-elt módosításokat talál az indexben, az
	alapértelmezett viselkedés a hibával való leállás. Ez az opció miatt
        a 'git update-index' ennek ellenére folytatja.

--ignore-missing::
	Figyelmen kívül hagyja a hiányzó fájlokat egy --refresh során

--cacheinfo <mode>,<object>,<path>::
--cacheinfo <mode> <object> <path>::
	Közvetlenül beszúrja a megadott információt az indexbe. A
	visszafelé kompatibilitás kedvéért ezt a három argumentumot
	három külön paraméterként is meg lehet adni, de az új
	felhasználóknak az egyparaméteres forma használata ajánlott.

--index-info::
        Index-információk beolvasása a standard bemenetről.

--chmod=(+|-)x::
        Beállítja a végrehajtási jogosultságokat a frissített fájlokon.

--assume-unchanged::
--no-assume-unchanged::
	Ha ez a kapcsoló meg van adva, az adott útvonalakhoz
	rögzített objektumnevek nem frissülnek. Ehelyett ez az
	opció be- vagy kikapcsolja az útvonalak "assume unchanged"
	bitjét. Amikor az "assume unchanged" bit be van kapcsolva,
	a felhasználó megígéri, hogy nem módosítja a fájlt, és
	engedélyezi a Gitnek, hogy feltételezze: a munkakönyvtárbeli
	fájl megegyezik az indexben rögzítettel. Ha módosítani
	akarod a munkakönyvtárbeli fájlt, ki kell kapcsolnod a
	bitet, hogy jelezd ezt a Gitnek. Ez néha hasznos, ha nagy
	projekttel dolgozol olyan fájlrendszeren, amelynek nagyon
	lassú az lstat(2) rendszerhívása (pl. cifs).
+
A Git (szabályosan) meg fog hiúsulni, ha módosítania kell ezt a
fájlt az indexben, pl. egy commit merge-elésekor;
ezért ha a feltételezetten-nem-követett fájl az upstreamben
megváltozik, a helyzetet kézzel kell kezelned.

--really-refresh::
	Olyan, mint a `--refresh`, de feltétel nélkül ellenőrzi a
	stat-információkat, az "assume unchanged" beállítástól függetlenül.

--skip-worktree::
--no-skip-worktree::
	Ha az egyik ilyen kapcsoló meg van adva, az adott útvonalakhoz
	rögzített objektumnevek nem frissülnek. Ehelyett ezek az
	opciók be- és kikapcsolják az útvonalak "skip-worktree" bitjét.
	Bővebben lásd a lenti "Skip-worktree bit" szakaszt.


--ignore-skip-worktree-entries::
--no-ignore-skip-worktree-entries::
	Ne távolítsa el a skip-worktree (más néven "index-only")
	bejegyzéseket még akkor sem, ha a `--remove` opció meg lett adva.

--fsmonitor-valid::
--no-fsmonitor-valid::
	Ha az egyik ilyen kapcsoló meg van adva, az adott útvonalakhoz
	rögzített objektumnevek nem frissülnek. Ehelyett ezek az
	opciók be- és kikapcsolják az útvonalak "fsmonitor valid" bitjét.
	Bővebben lásd a lenti "File System Monitor" szakaszt.

-g::
--again::
	Újrafuttatja a 'git update-index'-et azokon az útvonalakon,
	amelyeknek az index-bejegyzései eltérnek a `HEAD` commit
	bejegyzéseitől.

--unresolve::
	Visszaállítja egy fájl 'unmerged' vagy 'needs updating'
	állapotát egy merge során, ha az véletlenül törlődött.

--info-only::
	Nem hoz létre objektumokat az objektumadatbázisban az ezt a
	kapcsolót követő összes <file> argumentumhoz; csak beszúrja
	azok objektum-ID-jét az indexbe.

--force-remove::
	Eltávolítja a fájlt az indexből még akkor is, ha a
	munkakönyvtárban még megvan az adott fájl. (Magában
	foglalja a --remove-ot.)

--replace::
	Alapértelmezés szerint, ha egy `path` nevű fájl létezik az
	indexben, a 'git update-index' visszautasítja a `path/file`
	hozzáadására tett kísérletet. Hasonlóképp, ha létezik egy
	`path/file` fájl, egy `path` nevű fájl nem adható hozzá. A
	--replace kapcsolóval a hozzáadandó bejegyzéssel ütköző
	meglévő bejegyzések automatikusan eltávolításra kerülnek,
	figyelmeztető üzenetekkel.

--stdin::
	Ahelyett, hogy a parancssorból venné az útvonalak listáját,
	beolvassa az útvonalak listáját a standard bemenetről. Az
	útvonalakat alapértelmezés szerint LF választja el (azaz
	soronként egy útvonal).

--verbose::
	Jelenti, hogy mi kerül hozzáadásra és eltávolításra az indexből.

--index-version <n>::
	A keletkező indexet a megadott lemezes formátumverzióban írja ki.
	A támogatott verziók: 2, 3 és 4. A jelenlegi alapértelmezett
	verzió 2 vagy 3, attól függően, hogy használnak-e extra
	funkciókat, mint például a `git add -N`. A `--verbose`
	kapcsolóval azt is jelenti, hogy az indexfájl milyen verziót
	használt a parancs előtt és után.
+
A 4-es verzió egyszerű útvonalnév-tömörítést végez, ami nagy
repository-kban 30-50%-kal csökkenti az index méretét, ami
gyorsabb betöltési időt eredményez. A Git az 1.8.0-s verziója óta
támogatja, amely 2012 októberében jelent meg, a libgit2-be 2016-ban,
a JGit-be pedig 2020-ban került bele a támogatása. E kézikönyvoldal
korábbi verziói "viszonylag fiatalnak" nevezték, de manapság már
érett technológiának tekinthető.

--show-index-version::
	Jelenti a lemezes indexfájl által használt index-formátumverziót.
	Lásd fent a `--index-version` opciót.

-z::
	Csak `--stdin`-nel vagy `--index-info`-val együtt van értelme;
	az útvonalakat LF helyett NUL karakter választja el.

--split-index::
--no-split-index::
	Bekapcsolja vagy kikapcsolja a split index módot. Ha a
	split-index mód már be van kapcsolva, és a `--split-index` újra
	meg van adva, a $GIT_DIR/index minden változása visszakerül a
	megosztott indexfájlba.
+
Ezek az opciók a `core.splitIndex` konfigurációs változó értékétől
függetlenül érvénybe lépnek (lásd linkgit:git-config[1]). De egy
figyelmeztetés jelenik meg, ha a változtatás ellentmond a beállított
értéknek, mivel a beállított érték lép érvénybe legközelebb, amikor
az index beolvasásra kerül, ez pedig megszünteti az opció szándékolt
hatását.

--untracked-cache::
--no-untracked-cache::
	Bekapcsolja vagy kikapcsolja az untracked cache funkciót. Kérjük,
	a bekapcsolása előtt használd a `--test-untracked-cache` opciót.
+
Ezek az opciók a `core.untrackedCache` konfigurációs változó
értékétől függetlenül érvénybe lépnek (lásd linkgit:git-config[1]).
De egy figyelmeztetés jelenik meg, ha a változtatás ellentmond a
beállított értéknek, mivel a beállított érték lép érvénybe
legközelebb, amikor az index beolvasásra kerül, ez pedig
megszünteti az opció szándékolt hatását.

--test-untracked-cache::
	Csak teszteket végez a munkakönyvtáron, hogy megbizonyosodjon
	róla, használható-e az untracked cache. Ha ezután valóban
	használni akarod, kézzel kell bekapcsolnod az untracked
	cache-t a `--untracked-cache`, a `--force-untracked-cache`
	opcióval vagy a `core.untrackedCache` konfigurációs változóval.
	Ha egy teszt sikertelen, a kilépési kód 1, és egy üzenet
	elmagyarázza, mi nem működik a szükséges módon; egyébként a
	kilépési kód 0, és az OK szöveg jelenik meg.

--force-untracked-cache::
	Ugyanaz, mint a `--untracked-cache`. A Git korábbi verzióival
	való visszafelé kompatibilitás miatt biztosított, ahol a
	`--untracked-cache` régen a `--test-untracked-cache`-t is
	jelentette, de ez az opció feltétel nélkül bekapcsolta a
	kiterjesztést.

--fsmonitor::
--no-fsmonitor::
	Bekapcsolja vagy kikapcsolja a fájlrendszer-figyelő funkciót.
	Ezek az opciók a `core.fsmonitor` konfigurációs változó
	értékétől függetlenül érvénybe lépnek (lásd
	linkgit:git-config[1]). De egy figyelmeztetés jelenik meg, ha a
	változtatás ellentmond a beállított értéknek, mivel a beállított
	érték lép érvénybe legközelebb, amikor az index beolvasásra
	kerül, ez pedig megszünteti az opció szándékolt hatását.

\--::
	Az ezt követő argumentumokat ne értelmezze többé opcióként.

<file>::
	A fájlok, amelyeken a művelet végrehajtódik.
	Vedd figyelembe, hogy a '.'-tal kezdődő fájlok figyelmen kívül
	maradnak. Ez vonatkozik a `./file` és a `dir/./file` alakra is.
	Ha ezt nem szeretnéd, használj tisztább neveket.
	Ugyanez vonatkozik a '/'-re végződő könyvtárakra és a '//'-t
	tartalmazó útvonalakra is

USING --REFRESH
---------------
A `--refresh` nem számol ki új sha1 fájlt, és nem hozza naprakész
állapotba az indexet mode-/tartalomváltozások esetén. De amit *igenis*
megtesz, az az, hogy "újra összepárosítja" egy fájl stat-információját
az indexszel, így frissítheted az indexet egy olyan fájlhoz, amely
nem változott, de amelynek a stat-bejegyzése elavult.

Például akkor akarnál ezt megtenni, ha egy 'git read-tree' után
össze akarod kapcsolni a stat index-részleteket a megfelelő
fájlokkal.

USING --CACHEINFO OR --INFO-ONLY
--------------------------------
A `--cacheinfo` egy olyan fájl regisztrálására szolgál, amely nincs
az aktuális munkakönyvtárban. Ez minimum-checkout merge-eléshez
hasznos.

Ahhoz, hogy úgy tegyél, mintha lenne egy fájlod a megadott
útvonalon, mode-dal és sha1-gyel, add ki a következőt:

----------------
$ git update-index --add --cacheinfo <mode>,<sha1>,<path>
----------------

A `--info-only` fájlok regisztrálására szolgál anélkül, hogy azokat
elhelyezné az objektumadatbázisban. Ez status-only repository-khoz
hasznos.

A `--cacheinfo` és a `--info-only` hasonlóan viselkedik: az index
frissül, de az objektumadatbázis nem. A `--cacheinfo` akkor hasznos,
ha az objektum megvan az adatbázisban, de a fájl helyben nem
érhető el. A `--info-only` akkor hasznos, ha a fájl elérhető, de
nem akarod frissíteni az objektumadatbázist.


USING --INDEX-INFO
------------------

A `--index-info` egy erősebb mechanizmus, amellyel több
bejegyzés-definíciót adhatsz be a standard bemenetről, és
kifejezetten szkriptekhez lett tervezve. Háromféle formátumú
bemenetet tud fogadni:

    . mode SP type SP sha1          TAB path
+
Ez a formátum arra való, hogy a `git ls-tree` kimenetét betömd
az indexbe.

    . mode         SP sha1 SP stage TAB path
+
Ez a formátum arra való, hogy magasabb rendű stage-eket helyezz
az indexfájlba, és megegyezik a 'git ls-files --stage' kimenetével.

    . mode         SP sha1          TAB path
+
Ezt a formátumot már egyetlen Git parancs sem állítja elő, de a
`update-index --index-info` továbbra is támogatja és támogatni
fogja.

Ahhoz, hogy egy magasabb stage-ű bejegyzést helyezz az indexbe,
az útvonalat először el kell távolítani egy mode=0 bejegyzés
beadásával az útvonalhoz, majd be kell adni a szükséges
bemeneti sorokat a harmadik formátumban.

Például, ha ebből az indexből indulunk ki:

------------
$ git ls-files -s
100644 8a1218a1024a212bb3db30becd860315f9f3ac52 0       frotz
------------

a következő bemenetet adhatod be a `--index-info`-nak:

------------
$ git update-index --index-info
0 0000000000000000000000000000000000000000	frotz
100644 8a1218a1024a212bb3db30becd860315f9f3ac52 1	frotz
100755 8a1218a1024a212bb3db30becd860315f9f3ac52 2	frotz
------------

A bemenet első sora 0-t ad meg mode-ként az útvonal
eltávolításához; a SHA-1 nem számít, amíg jól formázott. Ezután a
második és a harmadik sor beadja az 1-es és a 2-es stage
bejegyzéseit ehhez az útvonalhoz. A fentiek után ezzel
végeznénk:

------------
$ git ls-files -s
100644 8a1218a1024a212bb3db30becd860315f9f3ac52 1	frotz
100755 8a1218a1024a212bb3db30becd860315f9f3ac52 2	frotz
------------


USING ``ASSUME UNCHANGED'' BIT
------------------------------

A Git sok művelete arra épít, hogy a fájlrendszered hatékony
`lstat(2)` implementációval rendelkezik, hogy a munkakönyvtárbeli
fájlok `st_mtime` információja olcsón ellenőrizhető legyen annak
megállapítására, hogy a fájl tartalma megváltozott-e az indexfájlban
rögzített verzióhoz képest. Sajnos néhány fájlrendszeren az
`lstat(2)` nem hatékony. Ha a te fájlrendszered is ilyen, akkor
beállíthatod az "assume unchanged" bitet azokra az útvonalakra,
amelyeket nem módosítottál, hogy a Git ne végezze el ezt az
ellenőrzést. Ne feledd, hogy ha ezt a bitet beállítod egy útvonalon,
az nem azt jelenti, hogy a Git ellenőrizni fogja a fájl tartalmát
annak megállapítására, hogy megváltozott-e -- ez azt eredményezi,
hogy a Git kihagy minden ellenőrzést, és feltételezi, hogy *nem*
változott. Amikor módosítasz munkakönyvtárbeli fájlokat, kifejezetten
jelezned kell ezt a Gitnek az "assume unchanged" bit levételével,
akár a módosítás előtt, akár utána.

Az "assume unchanged" bit beállításához használd a
`--assume-unchanged` opciót. A visszaállításához használd a
`--no-assume-unchanged`-et. Hogy megnézd, mely fájloknál van
beállítva az "assume unchanged" bit, használd a `git ls-files -v`
parancsot (lásd linkgit:git-ls-files[1]).

A parancs megnézi a `core.ignorestat` konfigurációs változót. Ha ez
igaz, a `git update-index útvonalak...` paranccsal frissített
útvonalak, valamint más, az indexet és a munkakönyvtárat egyaránt
frissítő Git-parancsokkal (pl. 'git apply --index', 'git
checkout-index -u' és 'git read-tree -u') frissített útvonalak
automatikusan "assume unchanged"-nek jelölődnek. Ne feledd, hogy az
"assume unchanged" bit *nem* kerül beállításra, ha a `git
update-index --refresh` azt találja, hogy a munkakönyvtárbeli fájl
megegyezik az indexszel (használd a `git update-index
--really-refresh` parancsot, ha "assume unchanged"-nek akarod
jelölni őket).

A felhasználók néha összekeverik az assume-unchanged bitet a
skip-worktree bittel. A különbségek magyarázatáért lásd a lenti
"Skip-worktree bit" szakasz utolsó bekezdését.


EXAMPLES
--------
A már checkoutolt fájlok frissítéséhez és refresheléséhez:

----------------
$ git checkout-index -n -f -a && git update-index --ignore-missing --refresh
----------------

Nem hatékony fájlrendszeren, ha a `core.ignorestat` be van állítva::
+
------------
$ git update-index --really-refresh              <1>
$ git update-index --no-assume-unchanged foo.c   <2>
$ git diff --name-only                           <3>
$ edit foo.c
$ git diff --name-only                           <4>
M foo.c
$ git update-index foo.c                         <5>
$ git diff --name-only                           <6>
$ edit foo.c
$ git diff --name-only                           <7>
$ git update-index --no-assume-unchanged foo.c   <8>
$ git diff --name-only                           <9>
M foo.c
------------
+
<1> az lstat(2)-t az indexnek megfelelő útvonalak "assume unchanged"
bitjeinek beállítására kényszeríti.
<2> megjelöli a szerkesztendő útvonalat.
<3> ez elvégzi az lstat(2)-t, és azt találja, hogy az index megfelel
az útvonalnak.
<4> ez elvégzi az lstat(2)-t, és azt találja, hogy az index *nem*
felel meg az útvonalnak.
<5> az új verzió indexbe való regisztrálása beállítja az "assume
unchanged" bitet.
<6> és feltételezetten változatlannak számít.
<7> még azután is, hogy szerkeszted.
<8> utólag is jelezheted a változást.
<9> most lstat(2)-vel ellenőriz, és azt találja, hogy megváltozott.


SKIP-WORKTREE BIT
-----------------

A skip-worktree bit egyetlen (hosszú) mondatban meghatározható:
mondd meg a gitnek, hogy kerülje a fájl munkakönyvtárba írását,
amikor ez ésszerűen lehetséges, és kezelje a fájlt változatlanként,
amikor az nincs jelen a munkakönyvtárban.

Ne feledd, hogy nem minden git-parancs veszi figyelembe ezt a
bitet, és némelyik csak részlegesen támogatja.

Az update-index kapcsolói és a read-tree képességei a
skip-worktree bittel kapcsolatban megelőzték a
linkgit:git-sparse-checkout[1] parancs bevezetését, amely sokkal
egyszerűbb módot biztosít a skip-worktree bitek beállítására és
kezelésére. Ha a munkakönyvtáradat a repository fájljainak csak
egy részhalmazára akarod korlátozni, erősen ajánljuk a
linkgit:git-sparse-checkout[1] használatát az alacsonyszintű
update-index és read-tree primitívek helyett.

A skip-worktree bit elsődleges célja a sparse checkoutok
lehetővé tétele, azaz olyan munkakönyvtárak megléte, amelyekben az
útvonalaknak csak egy része van jelen. Amikor a skip-worktree bit
be van állítva, a Git-parancsok (mint a `switch`, `pull`, `merge`)
kerülik ezeknek a fájloknak az írását. Ezek a parancsok azonban
néha mégis megírják ezeket a fájlokat olyan fontos esetekben, mint
egy merge vagy rebase közbeni konfliktus. A Git-parancsok azt is
kerülik, hogy az ilyen fájlok hiányát szándékos törlésként
kezeljék; például a `git add -u` nem fog törlést stage-elni ezekhez
a fájlokhoz, és a `git commit -a` sem fog olyan commitot létrehozni,
amely törli őket.

Bár ez a bit hasonlónak tűnik az assume-unchanged bithez, a célja
más. Az assume-unchanged bit arra való, hogy a fájlt a
munkakönyvtárban hagyva a Git kihagyja a változásainak
ellenőrzését, és feltételezze, hogy a fájl nem változott (bár ha
meg tudja állapítani a fájl stat-olása nélkül, hogy megváltozott,
szabadon rögzítheti a változásokat). A skip-worktree arra utasítja
a Gitet, hogy hagyja figyelmen kívül a fájl hiányát, kerülje annak
frissítését, amikor lehetséges, olyan parancsokkal, amelyek
rendszerint a munkakönyvtár nagy részét frissítik (pl. `checkout`,
`switch`, `pull` stb.), és a hiányát ne rögzítse a commitokban. Ne
feledd, hogy sparse checkoutokban (amelyeket a `git
sparse-checkout` állít be, vagy a core.sparseCheckout true-ra
állításával) ha egy fájl skip-worktree-ként van megjelölve az
indexben, de megtalálható a munkakönyvtárban, a Git törölni fogja
az adott fájl skip-worktree bitjét.

SPLIT INDEX
-----------

Ez a mód nagyon nagy indexekkel rendelkező repository-khoz készült,
és célja az ezen indexek ismételt kiírásához szükséges idő
csökkentése.

Ebben a módban az index két fájlra van felosztva: $GIT_DIR/index és
$GIT_DIR/sharedindex.<SHA-1>. A változások a $GIT_DIR/index-ben,
azaz a split indexben halmozódnak, míg a megosztott indexfájl az
összes index-bejegyzést tartalmazza, és változatlan marad.

A split index minden változása visszakerül a megosztott
indexfájlba, amikor a split indexben lévő bejegyzések száma eléri
a splitIndex.maxPercentChange konfigurációs változó által megadott
szintet (lásd linkgit:git-config[1]).

Minden alkalommal, amikor új megosztott indexfájl jön létre, a régi
megosztott indexfájlok törlődnek, ha a módosítási idejük régebbi,
mint amit a splitIndex.sharedIndexExpire konfigurációs változó
megad (lásd linkgit:git-config[1]).

Annak elkerülésére, hogy egy még használatban lévő megosztott
indexfájl törlődjön, a módosítási ideje az aktuális időre frissül
minden alkalommal, amikor a megosztott indexfájlon alapuló új
split index létrejön vagy beolvasásra kerül.

UNTRACKED CACHE
---------------

Ez a cache azon parancsok gyorsítására szolgál, amelyek a nem
követett fájlok meghatározásával járnak, mint például a `git status`.

Ez a funkció úgy működik, hogy rögzíti a munkakönyvtár-könyvtárak
mtime-ját, majd kihagyja a könyvtárolvasásokat és a stat-hívásokat
azokra a fájlokra vonatkozóan azokban a könyvtárakban, amelyeknek
az mtime-ja nem változott. Ehhez az alapul szolgáló operációs
rendszernek és fájlrendszernek meg kell változtatnia a könyvtárak
`st_mtime` mezőjét, ha a könyvtárban lévő fájlokat hozzáadják,
módosítják vagy törlik.

Azt, hogy a fájlrendszer támogatja-e ezt, a
`--test-untracked-cache` opcióval tesztelheted. A
`--untracked-cache` opció a Git régebbi verzióiban implicit módon
elvégezte ezt a tesztet, de ez már nincs így.

Ha be (vagy ki) akarod kapcsolni ezt a funkciót, egyszerűbb a
`core.untrackedCache` konfigurációs változót használni (lásd
linkgit:git-config[1]), mint a `--untracked-cache` opciót a `git
update-index`-hez minden egyes repository-ban, különösen ha ezt az
összes általad használt repository-ban meg akarod tenni, mert a
konfigurációs változót beállíthatod `true`-ra (vagy `false`-ra) a
`$HOME/.gitconfig`-odban egyszer, és ez minden repository-ra
hatással lesz, amelyhez hozzányúlsz.

Amikor a `core.untrackedCache` konfigurációs változó megváltozik,
az untracked cache a következő alkalommal kerül hozzáadásra vagy
eltávolításra az indexből, amikor egy parancs beolvassa az
indexet; míg amikor a `--[no-|force-]untracked-cache` van
használva, az untracked cache azonnal hozzáadásra vagy
eltávolításra kerül az indexből.

A 2.17 előtt az untracked cache-nek volt egy hibája, ahol egy
könyvtár egy másik könyvtárra mutató szimbolikus linkkel való
helyettesítése azt okozhatta, hogy tévesen nem követettként
mutatott git által követett fájlokat. Lásd a "status: add a
failing test showing a core.untrackedCache bug" commitot a
git.git-ben. Erre az egyik megoldás (és ez a jövőben más, még fel
nem fedezett hibáknál is működhet):

----------------
$ git -c core.untrackedCache=false status
----------------

Ez a hiba bizonyítottan érinti azokat a nem-symlinkes eseteket is,
amikor egy könyvtárat egy fájllal helyettesítenek, ami az untracked
cache belső struktúráit illeti, de nem jelentettek olyan esetet,
amikor ez hibás "git status" kimenetet eredményezett volna.

Vannak olyan esetek is, amikor a 2.17 előtti git-verziók által
írt, meglévő indexek olyan könyvtárakra hivatkoznak, amelyek már
nem léteznek, ami potenciálisan sok "could not open directory"
figyelmeztetés kiírását okozhatja a "git status" futtatásakor.
Ezek új figyelmeztetések meglévő, korábban csendben eldobott
problémákra.

A fent leírt hibához hasonlóan a megoldás az, hogy egyszeri
alkalommal futtatsz egy "git status"-t `core.untrackedCache=false`
mellett, hogy kiürítsd a visszamaradt hibás adatokat.

FILE SYSTEM MONITOR
-------------------

Ez a funkció azoknak a repository-knak a git-műveleteit hivatott
felgyorsítani, amelyeknek nagy a munkakönyvtáruk.

Lehetővé teszi a gitnek, hogy együttműködjön egy fájlrendszer-figyelővel
(lásd linkgit:git-fsmonitor{litdd}daemon[1]
és a linkgit:githooks[5] "fsmonitor-watchman" szakaszát), amely
tájékoztatni tudja arról, mely fájlok módosultak. Ez lehetővé teszi
a gitnek, hogy elkerülje a lstat() minden egyes fájlon való
végrehajtását a módosított fájlok megtalálásához.

Az untracked cache-sel együtt használva tovább javíthatja a
teljesítményt azáltal, hogy elkerüli a teljes munkakönyvtár új
fájlok keresésére irányuló átvizsgálásának költségét.

Ha be (vagy ki) akarod kapcsolni ezt a funkciót, egyszerűbb a
`core.fsmonitor` konfigurációs változót használni (lásd
linkgit:git-config[1]), mint a `--fsmonitor` opciót a `git
update-index`-hez minden egyes repository-ban, különösen ha ezt az
összes általad használt repository-ban meg akarod tenni, mert a
konfigurációs változót beállíthatod a `$HOME/.gitconfig`-odban
egyszer, és ez minden repository-ra hatással lesz, amelyhez
hozzányúlsz.

Amikor a `core.fsmonitor` konfigurációs változó megváltozik, a
fájlrendszer-figyelő a következő alkalommal kerül hozzáadásra vagy
eltávolításra az indexből, amikor egy parancs beolvassa az
indexet. Amikor a `--[no-]fsmonitor` van használva, a
fájlrendszer-figyelő azonnal hozzáadásra vagy eltávolításra kerül
az indexből.

CONFIGURATION
-------------

A parancs figyelembe veszi a `core.filemode` konfigurációs
változót. Ha a repository-d olyan fájlrendszeren van, amelynek a
végrehajtási bitjei megbízhatatlanok, ezt 'false'-ra kell állítani
(lásd linkgit:git-config[1]). Ez azt eredményezi, hogy a parancs
figyelmen kívül hagyja az indexben rögzített és a fájlrendszerbeli
fájlmódok közti eltéréseket, ha azok csak a végrehajtási bitben
térnek el. Egy ilyen szerencsétlen fájlrendszeren szükséged lehet a
'git update-index --chmod=' használatára.

Hasonlóképp, ha a `core.symlinks` konfigurációs változó 'false'-ra
van állítva (lásd linkgit:git-config[1]), a szimbolikus linkek
sima fájlokként kerülnek checkoutolásra, és ez a parancs nem
módosítja a rögzített fájlmódot szimbolikus linkről szabályos
fájlra.

A parancs megnézi a `core.ignorestat` konfigurációs változót. Lásd
a fenti 'Using "assume unchanged" bit' szakaszt.

A parancs a `core.trustctime` konfigurációs változót is megnézi.
Ez akkor lehet hasznos, ha az inode változási idejét rendszeresen
módosítja valami a Giten kívül (a fájlrendszer-crawlerek és a
biztonságimentés-rendszerek a ctime-ot használják a feldolgozott
fájlok megjelölésére) (lásd linkgit:git-config[1]).

Az untracked cache kiterjesztés a `core.untrackedCache`
konfigurációs változóval kapcsolható be (lásd
linkgit:git-config[1]).

NOTES
-----

A felhasználók gyakran próbálják az assume-unchanged és a
skip-worktree biteket felhasználni arra, hogy megmondják a
Gitnek, hagyja figyelmen kívül a követett fájlok változásait. Ez
nem úgy működik, ahogy elvárnánk, mivel a Git bizonyos műveletek
végrehajtásakor még mindig ellenőrizheti a munkakönyvtárbeli
fájlokat az indexhez képest. Általánosságban a Git nem biztosít
módot a követett fájlok változásainak figyelmen kívül hagyására,
ezért alternatív megoldások ajánlottak.

Ha például a módosítani kívánt fájl valamiféle konfigurációs
fájl, a repository tartalmazhat egy minta konfigurációs fájlt,
amelyet aztán az ignorált névre lehet másolni és módosítani. A
repository akár tartalmazhat egy szkriptet is, amely a minta
fájlt sablonként kezeli, automatikusan módosítva és másolva azt.

SEE ALSO
--------
linkgit:git-config[1],
linkgit:git-add[1],
linkgit:git-ls-files[1]

GIT
---
A linkgit:git[1] csomag része
