git-cat-file(1)
===============

NAME
----
git-cat-file - Repository-objektumok tartalmának vagy részleteinek megjelenítése

SYNOPSIS
--------
[verse]
'git cat-file' <type> <object>
'git cat-file' (-e | -p | -t | -s) <object>
'git cat-file' (--textconv | --filters)
	     [<rev>:<path|tree-ish> | --path=<path|tree-ish> <rev>]
'git cat-file' (--batch | --batch-check | --batch-command) [--batch-all-objects]
	     [--buffer] [--follow-symlinks] [--unordered]
	     [--textconv | --filters] [-Z]

DESCRIPTION
-----------
Kiírja egy vagy több objektum tartalmát, vagy egyéb tulajdonságait,
mint a méret, a típus vagy a delta-információ.

Ez a parancs két módban tud működni, attól függően, hogy meg van-e
adva egy opció a `--batch` családból.

Nem-batch módban a parancs a parancssorban megnevezett objektumról ad
információt.

Batch módban az argumentumok a standard bemenetről kerülnek beolvasásra.

OPTIONS
-------
<object>::
	A megjelenítendő objektum neve.
	Az objektumnevek megadási módjainak teljesebb listájáért lásd a
	"SPECIFYING REVISIONS" szakaszt a linkgit:gitrevisions[7]-ben.

-t::
	A tartalom helyett a `<object>` által azonosított objektumtípust
	mutatja.

-s::
	A tartalom helyett a `<object>` által azonosított objektum
	méretét mutatja. Ha a `--use-mailmap` opcióval együtt van
	használva, a frissített objektum méretét mutatja azután, hogy a
	mailmap mechanizmus lecserélte az identitásokat.

-e::
	Nulla státusszal lép ki, ha a `<object>` létezik és érvényes
	objektum. Ha a `<object>` érvénytelen formátumú, nem nulla
	státusszal lép ki, és hibát ad ki a stderr-re.

-p::
	Szépen kiírja a `<object>` tartalmát a típusa alapján.

<type>::
	Ez jellemzően megegyezik a `<object>` valós típusával, de olyan
	típus kérése is megengedett, amely triviálisan
	feloldható a megadott `<object>`-ből. Példa erre egy "tree"
	kérése, ahol a `<object>` egy azt tartalmazó commit objektum,
	vagy egy "blob" kérése, ahol a `<object>` egy arra mutató tag
	objektum.

--mailmap::
--no-mailmap::
--use-mailmap::
--no-use-mailmap::
       A mailmap fájlt használja a szerző-, committer- és tagelő-nevek,
       valamint az e-mail-címek kanonikus valódi nevekre és
       e-mail-címekre való leképezéséhez.
       Lásd linkgit:git-shortlog[1].

--textconv::
	A tartalmat egy textconv filter által átalakított formában
	mutatja. Ebben az esetben a `<object>`-nek `<tree-ish>:<path>`
	vagy `:<path>` alakúnak kell lennie, hogy a filter alkalmazható
	legyen az indexben a `<path>`-nál rögzített tartalomra.

--filters::
	A tartalmat az aktuális munkakönyvtárban a megadott `<path>`-hoz
	konfigurált filterek (azaz smudge filterek, sorvég-konverzió,
	stb.) által konvertált formában mutatja. Ebben az esetben a
	`<object>`-nek `<tree-ish>:<path>` vagy `:<path>` alakúnak kell
	lennie.

--filter=<filter-spec>::
--no-filter::
	Kihagyja az objektumokat a kiírt objektumok listájából. Ez csak a
	batch módok egyikével kombinálva használható. Azok a kizárt
	objektumok, amelyeket a standard bemeneten keresztül objektumokat
	olvasó batch módok bármelyikén keresztül (`--batch`,
	`--batch-check`) explicit módon kértek, "filtered"-ként lesznek
	jelentve. A `--batch-all-objects` módban a kizárt objektumok
	egyáltalán nem kerülnek kiírásra. A '<filter-spec>' a következők
	egyike lehet:
+
A '--filter=blob:none' alak minden blobot kihagy.
+
A '--filter=blob:limit=<n>[kmg]' alak azokat a blobokat hagyja ki,
amelyek mérete legalább n byte vagy egység. Az n lehet nulla. A k, m
és g utótagok a KiB, MiB vagy GiB egységek megnevezésére
használhatók. Például a 'blob:limit=1k' ugyanaz, mint a
'blob:limit=1024'.
+
A '--filter=object:type=(tag|commit|tree|blob)' alak minden olyan
objektumot kihagy, amely nem a kért típusú.

--path=<path>::
	A `--textconv`-vel vagy a `--filters`-szel együtt használva, hogy
	lehetővé tegye egy objektumnév és egy útvonal külön-külön
	megadását, pl. amikor nehéz kideríteni, melyik revízióból
	származik a blob.

--batch::
--batch=<format>::
	Kiírja az objektum-információt és a tartalmat minden, a stdinen
	megadott objektumhoz. Nem kombinálható más opciókkal vagy
	argumentumokkal, kivéve a `--textconv`-et, a `--filters`-t vagy a
	`--use-mailmap`-et.
+
--
	* A `--textconv`-vel vagy a `--filters`-szel használva, a
	  bemeneti soroknak meg kell adniuk az útvonalat, whitespace-szel
	  elválasztva. A részletekért lásd az alábbi `BATCH OUTPUT`
	  szakaszt.

	* A `--use-mailmap`-pel használva, commit- és tag-objektumoknál
	  a kimenet tartalom-része a mailmap mechanizmus által
	  lecserélt identitásokat mutatja, míg a kimenet
	  információ-része az objektum méretét úgy mutatja, mintha az
	  ténylegesen a lecserélt identitásokat rögzítette volna.
--

--batch-check::
--batch-check=<format>::
	Kiírja az objektum-információt minden, a stdinen megadott
	objektumhoz. Nem kombinálható más opciókkal vagy
	argumentumokkal, kivéve a `--textconv`-et, a `--filters`-t vagy a
	`--use-mailmap`-et.
+
--
	* A `--textconv`-vel vagy a `--filters`-szel használva, a
	 bemeneti soroknak meg kell adniuk az útvonalat, whitespace-szel
	 elválasztva. A részletekért lásd az alábbi `BATCH OUTPUT`
	 szakaszt.

	* A `--use-mailmap`-pel használva, commit- és tag-objektumoknál
	  a kiírt objektum-információ úgy mutatja az objektum méretét,
	  mintha a benne rögzített identitásokat a mailmap mechanizmus
	  lecserélte volna.
--

--batch-command::
--batch-command=<format>::
	Belép egy parancsmódba, amely parancsokat és argumentumokat
	olvas be a stdinről. Csak a `--buffer`-rel, a `--textconv`-vel, a
	`--use-mailmap`-pel vagy a `--filters`-szel kombinálható.
+
--
	* A `--textconv`-vel vagy a `--filters`-szel használva, a
	  bemeneti soroknak meg kell adniuk az útvonalat, whitespace-szel
	  elválasztva. A részletekért lásd az alábbi `BATCH OUTPUT`
	  szakaszt.

	* A `--use-mailmap`-pel használva, commit- és tag-objektumoknál
	  a `contents` parancs a mailmap mechanizmus által lecserélt
	  identitásokat mutatja, míg az `info` parancs az objektum
	  méretét úgy mutatja, mintha az ténylegesen a lecserélt
	  identitásokat rögzítette volna.
--
+
A `--batch-command` a következő parancsokat ismeri fel:
+
--
contents <object>::
	Kiírja az objektum tartalmát a `<object>` objektumreferenciához.
	Ez a `--batch` kimenetének felel meg.

info <object>::
	Kiírja az objektum-információt a `<object>` objektumreferenciához.
	Ez a `--batch-check` kimenetének felel meg.

remote-object-info <remote> <object>...::
	Kiírja az objektum-információt a `<object>` objektumreferenciákhoz
	a megadott `<remote>`-nál, anélkül, hogy objektumokat töltene le a
	remote-ról. Hibát ad, ha a remote nem támogatja az
	`object-info` képességet. Hibát ad, ha nincs megadva egyetlen
	objektumreferencia sem. Ez a parancs kombinálható a `--buffer`-rel.

flush::
	A `--buffer`-rel használva végrehajtja az összes megelőző
	parancsot, amely az elejétől vagy az utolsó flush kiadása óta
	érkezett. Amikor a `--buffer` van használva, nem érkezik kimenet,
	amíg egy `flush` ki nem lett adva. Amikor a `--buffer` nincs
	használva, a parancsok minden alkalommal flush-olva vannak,
	`flush` kiadása nélkül is.

`mailmap (<bool>)`::
	Be- vagy kikapcsolja a mailmapet a következő parancsokhoz. A
	`<bool>` argumentum ugyanazokat a logikai értékeket fogadja el,
	mint a linkgit:git-config[1]. A mailmap-adatok az első
	használatkor, csak egyszer kerülnek beolvasásra.
--
+

--batch-all-objects::
	Ahelyett, hogy a stdinen egy objektumlistát olvasna be, a kért
	batch műveletet a repository összes objektumán és bármely
	alternatív objektumtárolón hajtja végre (nem csak az elérhető
	objektumokon). A `--batch` vagy a `--batch-check` megadását
	igényli. Alapértelmezésben az objektumok bejárása a hash-eik
	szerint rendezett sorrendben történik; lásd még az alábbi
	`--unordered`-et. Az objektumok úgy jelennek meg, ahogy vannak,
	a linkgit:git-replace[1] "replace" mechanizmusát figyelmen kívül
	hagyva.

--buffer::
	Normál esetben a batch kimenet minden objektum kiírása után
	flush-olva van, hogy egy folyamat interaktívan tudjon olvasni és
	írni a `cat-file`-hoz. Ezzel az opcióval a kimenet a normál stdio
	pufferelést használja; ez sokkal hatékonyabb, amikor a
	`--batch-check`-et vagy a `--batch-command`-ot nagyszámú
	objektumon hívjuk meg.

--unordered::
	Amikor a `--batch-all-objects` van használva, az objektumok
	bejárása olyan sorrendben történik, amely hatékonyabb lehet az
	objektumtartalom eléréséhez, mint a hash-sorrend. A sorrend
	pontos részletei nincsenek meghatározva, de ha nincs szükséged
	konkrét sorrendre, ez általában gyorsabb kimenetet eredményez,
	különösen a `--batch`-tel. Vedd figyelembe, hogy a `cat-file`
	továbbra is csak egyszer mutatja meg mindegyik objektumot, még
	akkor is, ha az több példányban van tárolva a repository-ban.

--follow-symlinks::
	A `--batch`-tel vagy a `--batch-check`-kel együtt követi a
	repositoryban lévő szimbolikus linkeket, amikor objektumokat kér
	tree-ish:path-in-tree alakú kiterjesztett SHA-1-kifejezésekkel.
	Ahelyett, hogy magáról a linkről adna kimenetet, a link által
	mutatott objektumról ad kimenetet. Ha egy szimbolikus link a
	tree-ish-en kívülre mutat (pl. egy `/foo`-ra mutató link, vagy
	egy gyökérszintű link a `../foo`-ra), a link tree-n kívüli
	része kerül kiírásra.
+
Ez az opció (jelenleg) nem működik helyesen, amikor egy indexben
lévő objektum van megadva (pl. `:link` a `HEAD:link` helyett) a
tree-ben lévő helyett.
+
Ez az opció (jelenleg) nem használható, hacsak nincs használva a
`--batch` vagy a `--batch-check`.
+
Vegyünk például egy git repository-t, amely a következőket tartalmazza:
+
--
	f: egy fájl "hello\n" tartalommal
	link: egy szimbolikus link az f-re
	dir/link: egy szimbolikus link a ../f-re
	plink: egy szimbolikus link a ../f-re
	alink: egy szimbolikus link a /etc/passwd-re
--
+
Egy `f` reguláris fájlhoz az `echo HEAD:f | git cat-file --batch` a
következőt írná ki
+
--
	ce013625030ba8dba906f756967f9e9ca394464a blob 6
--
+
Az `echo HEAD:link | git cat-file --batch --follow-symlinks` ugyanezt
írná ki, ahogy a `HEAD:dir/link` is, mivel mindkettő a `HEAD:f`-re
mutat.
+
A `--follow-symlinks` nélkül ezek magáról a szimbolikus linkről
mutatnának adatot. A `HEAD:link` esetében a következőt látnád
+
--
	4d1ae35ba2c8ec712fa2a379db44ad639ca277bd blob 1
--
+
Mind a `plink`, mind az `alink` a tree-n kívülre mutat, így ezeket
írnák ki, rendre:
+
--
	symlink 4
	../f

	symlink 11
	/etc/passwd
--

-Z::
	Csak a `--batch`-tel, a `--batch-check`-kel vagy a
	`--batch-command`-dal együtt van jelentősége; a bemenet és a
	kimenet NUL-lal határolt, nem újsor-határolt.

-z::
	Csak a `--batch`-tel, a `--batch-check`-kel vagy a
	`--batch-command`-dal együtt van jelentősége; a bemenet NUL-lal
	határolt, nem újsor-határolt. Ez az opció elavult a `-Z` javára,
	mivel a kimenet enélkül félreérthető lehet.


OUTPUT
------
Ha a `-t` van megadva, a `<type>` egyike.

Ha a `-s` van megadva, a `<object>` mérete byte-okban.

Ha a `-e` van megadva, nincs kimenet, hacsak a `<object>` nem
hibásan formázott.

Ha a `-p` van megadva, a `<object>` tartalma szépen kiírva.

Ha a `<type>` van megadva, a `<object>` nyers (bár tömörítetlen)
tartalma kerül visszaadásra.

BATCH OUTPUT
------------

Ha a `--batch` vagy a `--batch-check` van megadva, a `cat-file`
objektumokat olvas be a stdinről, soronként egyet, és ugyanabban a
sorrendben ír ki róluk információt, ahogyan beolvasásra kerültek.
Alapértelmezésben a teljes sor objektumnak számít, mintha a
linkgit:git-rev-parse[1]-nek adták volna át.

Ha a `--batch-command` van megadva, a `cat-file` parancsokat olvas be
a stdinről, soronként egyet, és a megadott parancs alapján ír ki
információt. A `--batch-command`-dal az `info` parancs, amelyet egy
objektum követ, ugyanúgy ír ki információt az objektumról, ahogyan a
`--batch-check` tenné, a `contents` parancs pedig, amelyet egy
objektum követ, ugyanúgy írja ki a tartalmat, ahogyan a `--batch`
tenné. A `remote-object-info` parancs, amelyet egy remote és
objektumazonosítók követnek, objektum-információt ír ki a remote-ról,
anélkül, hogy letöltené az objektumokat.

Egy egyéni `<format>` használatával megadhatod, milyen információ
jelenjen meg az egyes objektumokhoz. A `<format>` szó szerint kerül
másolásra a stdoutra minden egyes objektumhoz, a `%(atom)` alakú
helyőrzők kifejtésével, amelyet egy újsor követ. Az elérhető atomok:

`objectname`::
	Az objektumnév teljes hexadecimális reprezentációja.

`objecttype`::
	Az objektum típusa (ugyanaz, amit a `cat-file -t` jelent).

`objectmode`::
	Ha a megadott objektumnak van mode-információja (mint egy tree
	vagy index bejegyzés), a mode oktális egész számként kifejezve.
	Egyébként üres string.

`objectsize`::
	Az objektum mérete byte-okban (ugyanaz, amit a `cat-file -s`
	jelent).

`objectsize:disk`::
	Az a méret byte-okban, amelyet az objektum a lemezen elfoglal.
	Lásd a lemezen elfoglalt méretekről szóló megjegyzést az alábbi
	`CAVEATS` szakaszban.

`deltabase`::
	Ha az objektum a lemezen deltaként van tárolva, ez a delta-alap
	objektum nevének teljes hexadecimális reprezentációjára fejtődik
	ki. Egyébként a null OID-ra (csupa nulla) fejtődik ki. Lásd
	alább a `CAVEATS`-t.

`rest`::
	Ha ez az atom van használva a kimeneti stringben, a bemeneti
	sorok az első whitespace-határnál kerülnek felosztásra. Az azt
	a whitespace-t megelőző összes karakter az objektumnévnek
	számít; az első whitespace-sorozat utáni karakterek (azaz a sor
	"maradéka") a `%(rest)` atom helyén kerülnek kiírásra.

A `remote-object-info` parancs csak a `%(objectname)`, a
`%(objectsize)` és a `%(objecttype)` helyőrzőket támogatja. Bővebb
információért lásd alább a `CAVEATS`-t.

Ha nincs formátum megadva, az alapértelmezett formátum a
`%(objectname) %(objecttype) %(objectsize)`.

Ha a `--batch` van megadva, vagy ha a `--batch-command` van használva
a `contents` paranccsal, az objektum-információt az objektum tartalma
követi (amely `%(objectsize)` byte-ból áll), amit egy újsor követ.

Például a `--batch` egyéni formátum nélkül a következőt produkálná:

-----------
<oid> SP <type> SP <size> LF
<contents> LF
-----------

Míg a `--batch-check='%(objectname) %(objecttype)'` a következőt
produkálná:

------------
<oid> SP <type> LF
------------

Ha a stdinen egy olyan név van megadva, amely nem oldható fel egy
objektumra a repository-ban, a `cat-file` figyelmen kívül hagy minden
egyéni formátumot és a következőt írja ki:

------------
<object> SP missing LF
------------

Ha a stdinen egy olyan név van megadva, amely a `--filter=` révén ki
van szűrve, a `cat-file` figyelmen kívül hagy minden egyéni formátumot
és a következőt írja ki:

------------
<object> SP excluded LF
------------

Ha egy olyan név van megadva, amely egynél több objektumra utalhat
(egy nem egyértelmű rövid sha), a `cat-file` figyelmen kívül hagy
minden egyéni formátumot és a következőt írja ki:

------------
<object> SP ambiguous LF
------------

Ha egy olyan név van megadva, amely egy tree-ben lévő submodule
bejegyzésre utal, és a célobjektum nem létezik a repository-ban, a
`cat-file` figyelmen kívül hagy minden egyéni formátumot, és a
következőt írja ki (a submodule objektumazonosítójával):

------------
<oid> SP submodule LF
------------

Ha a `--follow-symlinks` van használva, és egy szimbolikus link a
repository-ban a repository-n kívülre mutat, a `cat-file` figyelmen
kívül hagy minden egyéni formátumot, és a következőt írja ki:

------------
symlink SP <size> LF
<symlink> LF
------------

A szimbolikus link vagy abszolút (`/`-vel kezdődik), vagy a tree
gyökeréhez relatív. Például ha a dir/link a `../../foo`-ra mutat,
akkor a `<symlink>` `../foo` lesz. A `<size>` a szimbolikus link
mérete byte-okban.

Ha a `--follow-symlinks` van használva, a következő hibaüzenetek
jelenhetnek meg:

------------
<object> SP missing LF
------------
akkor kerül kiírásra, amikor a kért kezdeti szimbolikus link nem létezik.

------------
dangling SP <size> LF
<object> LF
------------
akkor kerül kiírásra, amikor a kezdeti szimbolikus link létezik, de
valami, amire (közvetve) mutat, nem.

------------
loop SP <size> LF
<object> LF
------------
szimbolikus link-hurkok esetén kerül kiírásra (vagy bármely olyan
szimbolikus linknél, amelynek feloldásához több mint 40 link-feloldás
szükséges).

------------
notdir SP <size> LF
<object> LF
------------
akkor kerül kiírásra, amikor a szimbolikus link feloldása során egy
fájlt könyvtárnévként használnak.

Alternatívaként, ha a `-Z` van átadva, a fenti példák bármelyikében a
sortörések NUL-terminátorokra cserélődnek. Ez biztosítja, hogy a
kimenet elemezhető maradjon, ha maga a kimenet sortörést tartalmazna,
így szkriptelési célokra ajánlott.

CAVEATS
-------

Vedd figyelembe, hogy a `remote-object-info` parancs jelenleg csak a
`%(objectname)`-t, a `%(objectsize)`-ot és a `%(objecttype)`-ot
támogatja. Bármely más helyőrző használata a formátumstringben üres
stringet ad vissza a helyén.

Vedd figyelembe, hogy az objektumok lemezen elfoglalt mérete pontosan
kerül jelentésre, de óvatosan kell levonni a következtetéseket arról,
mely refek vagy objektumok felelősek a lemezhasználatért. Egy
csomagolt, nem delta objektum mérete sokkal nagyobb lehet, mint az
ellene deltázó objektumok mérete, de az, hogy melyik objektum az alap
és melyik a delta, önkényes, és egy repack során változhat.

Azt is vedd figyelembe, hogy egy objektum több példánya is jelen
lehet az objektumadatbázisban; ebben az esetben nem meghatározott,
melyik példány mérete vagy delta-alapja kerül jelentésre.

GIT
---
A linkgit:git[1] csomag része
