git-help(1)
===========

NAME
----
git-help - Súgóinformációk megjelenítése a Gitről

SYNOPSIS
--------
[verse]
'git help' [-a|--all] [--[no-]verbose] [--[no-]external-commands] [--[no-]aliases]
'git help' [[-i|--info] [-m|--man] [-w|--web]] [<command>|<doc>]
'git help' [-g|--guides]
'git help' [-c|--config]
'git help' [--user-interfaces]
'git help' [--developer-interfaces]

DESCRIPTION
-----------

Ha nincs megadva kapcsoló és '<command>' vagy '<doc>' sem, a 'git' parancs
szinopszisa és a leggyakrabban használt Git-parancsok listája íródik ki a
standard kimenetre.

Ha a `--all` vagy a `-a` kapcsoló meg van adva, az összes elérhető parancs
kiíródik a standard kimenetre.

Ha a `--guides` vagy a `-g` kapcsoló meg van adva, a Git fogalmi útmutatóinak
listája is kiíródik a standard kimenetre.

Ha egy parancs vagy más dokumentáció van megadva, a vonatkozó man oldal
jelenik meg. Erre a célra alapértelmezés szerint a 'man' programot
használja, de ez felülbírálható más kapcsolókkal vagy konfigurációs
változókkal.

Ha egy alias van megadva, a git az alias definícióját mutatja a standard
kimeneten. Az aliasolt parancs man oldalának megjelenítéséhez használd a
`git <command> --help`-et.

Vedd figyelembe, hogy a `git --help ...` azonos a `git help ...`-pel, mivel
az előbbi belsőleg az utóbbivá alakul.

A linkgit:git[1] man oldal megjelenítéséhez használd a `git help git`-et.

Ez az oldal a 'git help help' vagy a `git help --help` paranccsal
jeleníthető meg.

OPTIONS
-------
-a::
--all::
	Az összes elérhető parancs kiírása a standard kimenetre.

--no-external-commands::
	A `--all`-lal használva kihagyja a `$PATH`-ban talált külső "git-*"
	parancsok listázását.

--no-aliases::
	A `--all`-lal használva kihagyja a beállított aliasok listázását.

--verbose::
	A `--all`-lal használva minden felismert parancshoz kiírja a leírást.
	Ez az alapértelmezés.

-c::
--config::
	Az összes elérhető konfigurációs változó listázása. Ez a
	linkgit:git-config[1] listájának rövid összefoglalása.

-g::
--guides::
	A Git fogalmi útmutatóinak listája a standard kimenetre.

--user-interfaces::
	A repository-, parancs- és fájlfelületek dokumentációjának listája a
	standard kimenetre.
+
A repository-n belüli fájlfelületek, mint a `.git/info/exclude`, itt vannak
dokumentálva (lásd linkgit:gitrepository-layout[5]), csakúgy, mint a fán
belüli konfiguráció, például a `.mailmap` (lásd linkgit:gitmailmap[5]).
+
A dokumentáció ezen szakasza az általános vagy elterjedt felhasználói
felületi konvenciókat is lefedi (pl. linkgit:gitcli[7]), valamint a
pszeudo-konfigurációt, például a linkgit:githooks[5]-ben leírt, fájlalapú
`.git/hooks/*` felületet.

--developer-interfaces::
	Fájlformátumok, protokollok és más fejlesztői felületek
	dokumentációjának listája a standard kimenetre.

-i::
--info::
	A parancs man oldalának megjelenítése 'info' formátumban. Erre a célra
	az 'info' programot használja.

-m::
--man::
	A parancs man oldalának megjelenítése 'man' formátumban. Ezzel a
	kapcsolóval felülbírálható a `help.format` konfigurációs változóban
	beállított érték.
+
Alapértelmezés szerint a man oldalt a 'man' program jeleníti meg, de a
`man.viewer` konfigurációs változóval más megjelenítő programok is
választhatók (lásd lent).

-w::
--web::
	A parancs man oldalának megjelenítése 'web' (HTML) formátumban. Erre a
	célra egy webböngészőt használ.
+
A webböngésző a `help.browser` konfigurációs változóval adható meg, vagy a
`web.browser`-rel, ha az előbbi nincs beállítva. Ha egyik konfigurációs
változó sincs beállítva, a 'git web{litdd}browse' segédszkript (amelyet a
'git help' hív) választ egy megfelelő alapértelmezést. Erről bővebben lásd
linkgit:git-web{litdd}browse[1].

CONFIGURATION VARIABLES
-----------------------

help.format
~~~~~~~~~~~

Ha nincs átadva parancssori kapcsoló, a `help.format` konfigurációs változót
ellenőrzi. Ez a változó a következő értékeket támogatja; ezek a nekik
megfelelő parancssori kapcsoló szerint viselkedtetik a 'git help'-et:

* a "man" a '-m|--man'-nek felel meg,
* az "info" a '-i|--info'-nak felel meg,
* a "web" vagy a "html" a '-w|--web'-nek felel meg.

help.browser, web.browser, and browser.<tool>.path
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A `help.browser`, a `web.browser` és a `browser.<tool>.path` szintén
ellenőrzésre kerül, ha a 'web' formátumot választják (akár parancssori
kapcsolóval, akár konfigurációs változóval). Lásd a '-w|--web'-et a fenti
OPTIONS szakaszban és linkgit:git-web{litdd}browse[1].

man.viewer
~~~~~~~~~~

A `man.viewer` konfigurációs változót akkor ellenőrzi, ha a 'man'
formátumot választják. Jelenleg a következő értékeket támogatja:

* "man": a 'man' program szokásos használata,
* "woman": az 'emacsclient' használata az emacs "woman" módjának
  elindításához (ez csak a 22-es verziótól működő emacsclienttel működik),
* "konqueror": a 'kfmclient' használata a man oldal új konqueror-fülön
  való megnyitásához (lásd lent a 'Note about konqueror' részt).

Más eszközökhöz tartozó értékek is használhatók, ha van hozzájuk tartozó
`man.<tool>.cmd` konfigurációs bejegyzés (lásd lent).

A `man.viewer` konfigurációs változónak több érték is adható. A hozzájuk
tartozó programokat a konfigurációs fájlban felsorolt sorrendben próbálja.

Például ez a konfiguráció:

------------------------------------------------
	[man]
		viewer = konqueror
		viewer = woman
------------------------------------------------

először a konquerort próbálja használni. Ez azonban meghiúsulhat (például ha
a DISPLAY nincs beállítva), és ebben az esetben az emacs woman módját
próbálja.

Ha minden meghiúsul, vagy ha nincs megjelenítő beállítva, a
`GIT_MAN_VIEWER` környezeti változóban megadott megjelenítőt próbálja.  Ha
az is meghiúsul, mindenképp a 'man' programot próbálja.

man.<tool>.path
~~~~~~~~~~~~~~~

A `man.<tool>.path` konfigurációs változó beállításával explicit módon
megadhatod a kívánt man-megjelenítőd teljes elérési útját. Például a
konqueror abszolút elérési útját a 'man.konqueror.path' beállításával
konfigurálhatod. Egyébként a 'git help' feltételezi, hogy az eszköz elérhető
a PATH-ban.

man.<tool>.cmd
~~~~~~~~~~~~~~

Ha a `man.viewer` konfigurációs változókkal megadott man-megjelenítő nincs
a támogatottak között, akkor a hozzá tartozó `man.<tool>.cmd` konfigurációs
változót keresi meg. Ha ez a változó létezik, a megadott eszközt egyéni
parancsként kezeli, és egy shell eval segítségével futtatja a parancsot,
argumentumként átadva a man oldalt.

Note about konqueror
~~~~~~~~~~~~~~~~~~~~

Amikor a `man.viewer` konfigurációs változóban a 'konqueror' van megadva, a
'kfmclient'-et indítjuk, hogy ha lehetséges, egy már megnyitott konqueror
új fülén nyissuk meg a man oldalt.

A konzisztencia kedvéért ugyanezt a trükköt akkor is megpróbáljuk, ha a
'man.konqueror.path' valami olyasmire van állítva, mint az
`A_PATH_TO/konqueror`. Ez azt jelenti, hogy helyette az
`A_PATH_TO/kfmclient` indítását próbáljuk meg.

Ha tényleg a 'konqueror'-t akarod használni, akkor valami ilyesmit
használhatsz:

------------------------------------------------
	[man]
		viewer = konq

	[man "konq"]
		cmd = A_PATH_TO/konqueror
------------------------------------------------

Note about git config --global
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Vedd figyelembe, hogy ezeket a konfigurációs változókat valószínűleg a
`--global` kapcsolóval kellene beállítani, például így:

------------------------------------------------
$ git config --global help.format web
$ git config --global web.browser firefox
------------------------------------------------

mivel valószínűleg inkább felhasználófüggők, mint repository-függők.
Erről bővebben lásd linkgit:git-config[1].

GIT
---
A linkgit:git[1] csomag része
