git-stripspace(1)
=================

NAME
----
git-stripspace - Szükségtelen whitespace eltávolítása


SYNOPSIS
--------
[verse]
'git stripspace' [-s | --strip-comments]
'git stripspace' [-c | --comment-lines]

DESCRIPTION
-----------

Szöveg — például commit-üzenetek, jegyzetek, tagek és branch-leírások —
beolvasása a standard bemenetről, és megtisztítása a Git által használt
módon.

Argumentumok nélkül a következőt teszi:

- eltávolítja a sorvégi whitespace-t minden sorból
- több egymást követő üres sort egyetlen üres sorrá von össze
- eltávolítja az üres sorokat a bemenet elejéről és végéről
- szükség esetén hozzáad egy hiányzó '\n'-t az utolsó sorhoz.

Ha a bemenet teljes egészében whitespace-karakterekből áll, nem keletkezik
kimenet.

*NOTE*: Ez metaadatok tisztítására szolgál. Patchek vagy a repository-ban lévő
fájlok whitespace-ének javításához inkább a linkgit:git-apply[1]
`--whitespace=fix` módját használd.

OPTIONS
-------
-s::
--strip-comments::
	Kihagyja és eltávolítja az összes, megjegyzés-karakterrel kezdődő sort
	(`core.commentChar`, alapértelmezés `#`).

-c::
--comment-lines::
	Minden sor elé beszúrja a megjegyzés-karaktert és egy szóközt. A sorok
	automatikusan sortöréssel záródnak. Üres sorok elé csak a
	megjegyzés-karakter kerül.

EXAMPLES
--------

Az alábbi zajos bemenet esetén, ahol a '$' a sor végét jelöli:

---------
|A brief introduction   $
|   $
|$
|A new paragraph$
|# with a commented-out line    $
|explaining lots of stuff.$
|$
|# An old paragraph, also commented-out. $
|      $
|The end.$
|  $
---------

A 'git stripspace' argumentumok nélküli használatával a következőt kapod:

---------
|A brief introduction$
|$
|A new paragraph$
|# with a commented-out line$
|explaining lots of stuff.$
|$
|# An old paragraph, also commented-out.$
|$
|The end.$
---------

A 'git stripspace --strip-comments' használatával a következőt kapod:

---------
|A brief introduction$
|$
|A new paragraph$
|explaining lots of stuff.$
|$
|The end.$
---------

GIT
---
A linkgit:git[1] csomag része
