git-replay(1)
=============

NAME
----
git-replay - KÍSÉRLETI: Commitok újrajátszása egy új alapon, bare repókkal is működik


SYNOPSIS
--------
[verse]
(KÍSÉRLETI!) 'git replay' ([--contained] --onto=<newbase> | --advance=<branch> | --revert=<branch>)
			     [--ref=<ref>] [--ref-action=<mode>] <revision-range>

DESCRIPTION
-----------

Vesz egy committartományt, és újrajátssza őket egy új helyre. A
munkakönyvtárat és az indexet érintetlenül hagyja. Alapértelmezés szerint a
vonatkozó referenciákat atomi tranzakcióval frissíti (vagy minden ref
frissül, vagy egyik sem). A `--ref-action=print` használatával elkerülhető az
automatikus ref-frissítés, helyette olyan frissítő parancsokat kapsz,
amelyek a `git update-ref --stdin`-be csövezhetők (lásd lentebb a
<<output,OUTPUT>> szakaszt).

EZ A PARANCS KÍSÉRLETI. A VISELKEDÉSE MEGVÁLTOZHAT.

OPTIONS
-------

--onto=<newbase>::
	Kiindulópont, amelyen az új commitok létrejönnek.  Bármely érvényes
	commit lehet, nem csak egy meglévő branchnév.
+
Ha a `--onto` meg van adva, a revíziótartományba eső branch(ek) frissülnek,
hogy az új commitokra mutassanak, hasonlóan ahhoz, ahogy a
`git rebase --update-refs` frissít több branchet az érintett tartományban.

--advance=<branch>::
	Kiindulópont, amelyen az új commitok létrejönnek; branchnévnek kell
	lennie.
+
Az előzmény a <branch> tetejére kerül újrajátszásra, és a <branch> frissül,
hogy a kapott előzmény csúcsára mutasson. Ez eltér a `--onto`-tól, amely a
célt csak kiindulópontként használja, anélkül hogy frissítené.

--revert=<branch>::
	Kiindulópont, amelyen a visszavont commitok létrejönnek; branchnévnek
	kell lennie.
+
Ha a `--revert` meg van adva, a revíziótartományba eső commitokat visszavonja
(a változtatásaikat visszacsinálja), és a visszavont commitok a <branch>
tetejére jönnek létre. A <branch> ezután frissül, hogy az új commitokra
mutasson. Ez ugyanaz, mint a `git revert <revision-range>` futtatása, de nem
frissíti a munkakönyvtárat.
+
A commit-üzenetek a `git revert` konvencióit követik: "Revert" előtaggal
kezdődnek, és tartalmazzák a "This reverts commit <hash>." sort. Amikor egy
olyan commitot vonsz vissza, amelynek üzenete "Revert"-tel kezdődik, az új
üzenet helyette a "Reapply" szót használja. A cherry-pickkel ellentétben,
amely megőrzi az eredeti szerzőt, a revert-commitok az aktuális felhasználót
használják szerzőként, összhangban a `git revert` viselkedésével.
+
Ez a kapcsoló kölcsönösen kizárja egymást a `--onto`-val és az `--advance`-szel.
Emellett nem kompatibilis a `--contained`-del sem (amely csak az `--onto`
módosítója).

--contained::
	Minden olyan branch frissítése, amely a <revision-range> commitjaira
	mutat. A `--onto`-t igényli.

--ref=<ref>::
	Felülírja, hogy melyik referencia frissüljön az újrajátszás
	eredményével. A refnek teljesen minősítettnek kell lennie.
	Az `--onto`-val használva a `<revision-range>`-nek egyetlen csúccsal
	kell rendelkeznie, és csak a megadott referencia frissül, ahelyett
	hogy a refeket a revíziótartományból következtetné ki.
	Az `--advance`-szel vagy a `--revert`-tel használva a megadott
	referencia frissül az ezen kapcsolóknak adott branch helyett.
	Ez a kapcsoló nem kompatibilis a `--contained`-del.

--ref-action[=<mode>]::
	Szabályozza, hogyan frissülnek a referenciák. A mód lehet:
+
--
////
Expanded description list compared to 'replay.refAction'.
////
`update`;; (alapértelmezett) A refek közvetlen frissítése atomi
	tranzakcióval. Vagy minden ref frissül, vagy egyik sem (mindent vagy
	semmit viselkedés).
`print`;; Update-ref parancsok kiírása pipeline-használatra. Ez a
	hagyományos viselkedés, ahol a kimenet a `git update-ref --stdin`-be csövezhető.
--
+
Az alapértelmezett mód a `replay.refAction` konfigurációs változóval állítható be.

<revision-range>::
	Az újrajátszandó commitok tartománya; lásd a "Specifying Ranges"
	szakaszt a linkgit:git-rev-parse[1]-ben. `--advance=<branch>` vagy
	`--revert=<branch>` módban a tartománynak egyetlen csúccsal kell
	rendelkeznie, hogy egyértelmű legyen, melyik csúcsra mutasson az
	előreléptetett vagy visszavont <branch>. A tartomány azon commitjai,
	amelyek változtatásai már jelen vannak abban a branchben, amelyre a
	commitokat újrajátsszák, eldobásra kerülnek.

:git-replay: 1
include::rev-list-options.adoc[]

[[output]]
OUTPUT
------

Alapértelmezés szerint, vagy `--ref-action=update` esetén, ez a parancs siker
esetén nem állít elő kimenetet, mivel a refek közvetlenül, atomi
tranzakcióval frissülnek.

`--ref-action=print` használatakor a kimenet felhasználható a
`git update-ref --stdin` bemeneteként. A formája:

	update refs/heads/branch1 ${NEW_branch1_HASH} ${OLD_branch1_HASH}
	update refs/heads/branch2 ${NEW_branch2_HASH} ${OLD_branch2_HASH}
	update refs/heads/branch3 ${NEW_branch3_HASH} ${OLD_branch3_HASH}

ahol a frissített refek száma az átadott argumentumoktól és az újrajátszott
előzmény alakjától függ.  Az `--advance` vagy a `--revert` használatakor a
frissített refek száma mindig egy, de az `--onto` esetén lehet egy vagy több
(több branch egyidejű rebase-elése támogatott).

Konfliktusok esetén nincs stderr-kimenet; lásd lentebb a
<<exit-status,EXIT STATUS>> szakaszt.

[[exit-status]]
EXIT STATUS
-----------

Sikeres, konfliktusmentes újrajátszás esetén a kilépési állapot 0.  Ha az
újrajátszásban konfliktusok vannak, a kilépési állapot 1.  Ha az újrajátszás
valamilyen hiba miatt nem tud befejeződni (vagy elindulni), a kilépési
állapot 0-tól és 1-től eltérő valami.

EXAMPLES
--------

A `mybranch` egyszerű rebase-eléséhez a `target`-ra:

------------
$ git replay --onto=target origin/main..mybranch
------------

A refek atomian frissülnek, és siker esetén nem keletkezik kimenet.

Annak megtekintéséhez, hogy mi frissülne, tényleges frissítés nélkül:

------------
$ git replay --ref-action=print --onto=target origin/main..mybranch
update refs/heads/mybranch ${NEW_mybranch_HASH} ${OLD_mybranch_HASH}
------------

A commitok cherry-pickeléséhez a mybranchből a targetre:

------------
$ git replay --advance=target origin/main..mybranch
------------

Vedd figyelembe, hogy az első két példa pontosan ugyanazokat a commitokat
játssza újra, pontosan ugyanazon új alap tetejére; csak abban különböznek,
hogy az első a mybranchöt frissíti, hogy az új commitokra mutasson, a
második pedig a targetet frissíti, hogy azokra mutasson.

Mi van, ha van egy egymásra épülő branchek verme, egyik a másiktól függ, és
tényleg szeretnéd az egész készletet rebase-elni?

------------
$ git replay --contained --onto=origin/main origin/main..tipbranch
------------

Mindhárom branch (`branch1`, `branch2` és `tipbranch`) atomian frissül.

A `git replay` hívásakor nem szükséges az újrajátszandó committartományt az
`A..B` szintaxissal megadni; bármilyen tartománykifejezés megfelel:

------------
$ git replay --onto=origin/main ^base branch1 branch2 branch3
------------

Ez egyidejűleg rebase-eli a `branch1`, `branch2` és `branch3` branchet,
minden commitjukat a `base` óta, az `origin/main` tetejére játszva őket. E
három branchnek lehetnek közös commitjai a `base` tetején, de ennek nem kell
így lennie.

Egy branchen lévő commitok visszavonásához:

------------
$ git replay --revert=main topic~2..topic
------------

Ez visszavonja az utolsó két commitot a `topic`-ból, revert-commitokat
létrehozva a `main` tetején, és frissíti a `main`-t, hogy az eredményre
mutasson. Ez akkor hasznos, ha a `topic` commitjait korábban merge-elték vagy
cherry-pickelték a `main`-be, és vissza kell csinálni őket.

NOTE: Egy teljes merge request egyetlen commitként való visszavonásához
(commitonkénti helyett) fontold meg a `git merge-tree --merge-base $TIP HEAD $BASE`
használatát, amely elkerülheti a felesleges merge-konfliktusokat.

Egy adott commitra való újrajátszáshoz, miközben egy másik referenciát
frissítesz:

------------
$ git replay --onto=112233 --ref=refs/heads/mybranch aabbcc..ddeeff
------------

Ez újrajátssza az `aabbcc..ddeeff` tartományt a `112233` commitra, és
frissíti a `refs/heads/mybranch`-et, hogy az eredményre mutasson. Ez akkor
lehet hasznos, ha branchnevek helyett puszta commit-azonosítókat szeretnél
használni.

CONFIGURATION
-------------
:git-replay: 1
include::config/replay.adoc[]

GIT
---
A linkgit:git[1] csomag része
