git-credential(1)
=================

NAME
----
git-credential - Felhasználói hitelesítő adatok lekérése és tárolása

SYNOPSIS
--------
------------------
'git credential' (fill|approve|reject|capability)
------------------

DESCRIPTION
-----------

A Gitnek van egy belső felülete a hitelesítő adatok
rendszerspecifikus helperekből történő tárolására és lekérésére,
valamint arra, hogy felhasználóneveket és jelszavakat kérjen be a
felhasználótól. A git-credential parancs ezt a felületet teszi
elérhetővé szkriptek számára, amelyek a Githez hasonló módon
szeretnének hitelesítő adatokat lekérni, tárolni, vagy bekéretni.
Ennek a szkriptelhető felületnek a felépítése a belső C API-t
mintázza; a fogalmak háttereként lásd a credential.h fájlt.

A git-credential a parancssorból egy "action" opciót vár (a `fill`,
`approve` vagy `reject` egyikét), és a szabványos bemenetről beolvas
egy hitelesítőadat-leírást (lásd <<IOFMT,BEMENETI/KIMENETI FORMÁTUM>>).

Ha az akció `fill`, a git-credential megpróbál "username" és
"password" attribútumokat hozzáadni a leíráshoz konfigurációs fájlok
beolvasásával, bármely beállított credential helper megkeresésével,
vagy a felhasználó bekérdezésével. A hitelesítőadat-leírás
felhasználónév és jelszó attribútumai ezután a már megadott
attribútumokkal együtt a szabványos kimenetre íródnak.

Ha az akció `approve`, a git-credential elküldi a leírást minden
beállított credential helpernek, amelyek eltárolhatják a hitelesítő
adatot későbbi felhasználásra.

Ha az akció `reject`, a git-credential elküldi a leírást minden
beállított credential helpernek, amelyek törölhetik a leírásnak
megfelelő, tárolt hitelesítő adatokat.

Ha az akció `capability`, a git-credential a szabványos kimeneten
bejelenti az általa támogatott képességeket.

Ha az akció `approve` vagy `reject`, nem szabad kimenetet produkálni.

A GIT CREDENTIAL TIPIKUS HASZNÁLATA
-----------------------------------

A git-credential-t használó alkalmazás jellemzően az alábbi lépések
szerint használja a `git credential` parancsot:

  1. Hitelesítőadat-leírás generálása a kontextus alapján.
+
Például ha jelszót szeretnénk a `https://example.com/foo.git`
címhez, előállíthatjuk a következő hitelesítőadat-leírást (ne
feledkezz meg a végén lévő üres sorról; ez jelzi a `git credential`
parancsnak, hogy az alkalmazás befejezte az összes rendelkezésére
álló információ átadását):

	 protocol=https
	 host=example.com
	 path=foo.git

  2. Megkérjük a git-credential-t, hogy adjon egy felhasználónevet és
     jelszót ehhez a leíráshoz. Ez a `git credential fill` futtatásával
     történik, az (1) lépésből származó leírást a szabványos bemenetére
     táplálva. A teljes hitelesítőadat-leírás (magát a hitelesítő adatot
     is beleértve, azaz a bejelentkezési nevet és a jelszót) a szabványos
     kimeneten jelenik meg, például így:

	protocol=https
	host=example.com
	username=bob
	password=secr3t
+
A legtöbb esetben ez azt jelenti, hogy a bemenetben megadott
attribútumok megismétlődnek a kimeneten, de a Git módosíthatja is a
hitelesítőadat-leírást, például eltávolíthatja a `path` attribútumot,
ha a protokoll HTTP(s), és a `credential.useHttpPath` hamis.
+
Ha a `git credential` már ismerte a jelszót, ez a lépés lehet, hogy
nem is igényelte, hogy a felhasználó ténylegesen beírja a jelszót (a
felhasználó ehelyett esetleg egy jelszót írt be a kulcstartó
feloldásához, vagy egyáltalán nem volt szükség felhasználói
beavatkozásra, ha a kulcstartó már fel volt oldva), mielőtt
visszaadta volna a `password=secr3t` értéket.

  3. A hitelesítő adat felhasználása (pl. az URL elérése a (2)
     lépésből származó felhasználónévvel és jelszóval), és annak
     ellenőrzése, hogy elfogadásra került-e.

  4. A jelszó sikerének vagy sikertelenségének jelentése. Ha a
     hitelesítő adat lehetővé tette a művelet sikeres befejezését,
     akkor megjelölhető egy "approve" akcióval, hogy jelezze a `git
     credential` parancsnak, hogy a következő meghívásakor
     használja fel újra. Ha a hitelesítő adatot a művelet során
     elutasították, használd a "reject" akciót, hogy a `git
     credential` a következő meghívásakor új jelszót kérjen. Mindkét
     esetben a `git credential` parancsot a (2) lépésből kapott
     hitelesítőadat-leírással kell táplálni (amely az (1) lépésben
     megadott mezőket is tartalmazza).

[[IOFMT]]
BEMENETI/KIMENETI FORMÁTUM
--------------------------

A `git credential` (a használt akciótól függően) hitelesítőadat-
információt olvas és/vagy ír a szabványos bemenetén/kimenetén. Ez az
információ vonatkozhat olyan kulcsokra, amelyekhez a `git credential`
be fogja szerezni a bejelentkezési adatokat (pl. host, protocol,
path), vagy magára a beszerzendő hitelesítő adatra
(username/password).

A hitelesítő adat elnevezett attribútumok halmazára van felosztva,
soronként egy attribútummal. Minden attribútumot egy kulcs-érték pár
ad meg, amelyeket egy `=` (egyenlőségjel) választ el, azt pedig egy
újsor-karakter követi.

A kulcs bármilyen bájtot tartalmazhat, kivéve a `=` jelet, az
újsor-karaktert vagy a NUL-t. Az érték bármilyen bájtot tartalmazhat,
kivéve az újsor-karaktert vagy a NUL-t. Egy sor, a végén lévő
újsor-karakterrel együtt, nem haladhatja meg a 65535 bájtot, hogy az
implementációk hatékonyan tudják feldolgozni.

Azok az attribútumok, amelyek kulcsa C-stílusú tömbzárójelekkel
(`[]`) végződik, több értéket is felvehetnek. A többértékű attribútum
minden előfordulása egy rendezett értéklistát alkot — az ismételt
attribútumok sorrendje határozza meg az értékek sorrendjét. Egy üres
többértékű attribútum (`key[]=\n`) az előző bejegyzések törlésére és
a lista visszaállítására szolgál.

Minden esetben az összes bájt úgy, ahogy van, kerül kezelésre (azaz
nincs idézés, és nem lehet olyan értéket továbbítani, amelyben
újsor-karakter vagy NUL szerepel). Az attribútumok listáját egy üres
sor vagy a fájl vége zárja le.

A Git a következő attribútumokat érti:

`protocol`::

	A protokoll, amelyen keresztül a hitelesítő adat felhasználásra
	kerül (pl. `https`).

`host`::

	A hálózati hitelesítő adathoz tartozó remote hosztnév. Ez
	tartalmazza a portszámot is, ha meg volt adva (pl.
	"example.com:8088").

`path`::

	Az útvonal, amellyel a hitelesítő adat felhasználásra kerül.
	Pl. egy remote https repository eléréséhez ez a repository
	útvonala lesz a szerveren.

`username`::

	A hitelesítő adat felhasználóneve, ha már van ilyenünk (pl. egy
	URL-ből, a konfigurációból, a felhasználótól, vagy egy korábban
	futtatott helpertől).

`password`::

	A hitelesítő adat jelszava, ha a tárolását kérjük.

`password_expiry_utc`::

	A generált jelszavaknak, mint például egy OAuth hozzáférési
	tokennek, lehet lejárati dátuma. Amikor helperekből olvas be
	hitelesítő adatokat, a `git credential fill` figyelmen kívül
	hagyja a lejárt jelszavakat. Unix time UTC formátumban van
	megadva, 1970 óta eltelt másodpercekben.

`oauth_refresh_token`::

	Egy OAuth frissítő tokent egy olyan jelszó kísérhet, amely egy
	OAuth hozzáférési token. A helpereknek ezt az attribútumot a
	jelszó attribútumhoz hasonlóan bizalmasan kell kezelniük. Maga a
	Git nem tanúsít semmilyen különleges viselkedést ezzel az
	attribútummal kapcsolatban.

`url`::

	Amikor ezt a speciális attribútumot a `git credential` beolvassa,
	az érték URL-ként kerül feldolgozásra, és úgy kezelendő, mintha az
	alkotórészei lettek volna beolvasva (pl. az `url=https://example.com`
	úgy viselkedik, mintha `protocol=https` és `host=example.com` lett
	volna megadva). Ez segíthet a hívóknak elkerülni, hogy maguk
	elemezzék az URL-eket.
+
Vedd figyelembe, hogy a protokoll megadása kötelező, és ha az URL nem
ad meg hosztnevet (pl. "cert:///path/to/file"), a hitelesítő adat
tartalmazni fog egy hostname attribútumot, amelynek értéke egy üres
string.
+
Az URL-ből hiányzó összetevők (pl. a fenti példában nincs
felhasználónév) beállítatlanul maradnak.

`authtype`::
	Ez jelzi, hogy a kérdéses hitelesítési sémát kell használni.
	A HTTP és HTTPS esetén gyakori értékek a `basic`, `bearer` és
	`digest`, bár az utóbbi nem biztonságos, és nem szabad használni.
	Ha `credential` van használatban, ez tetszőleges, a kérdéses
	protokollnak megfelelő stringre állítható (általában HTTP).
+
Ezt az értéket csak akkor szabad elküldeni, ha a megfelelő képesség
(lásd lent) meg van adva a bemeneten.

`credential`::
	Az előre kódolt hitelesítő adat, a kérdéses protokollnak
	megfelelően (általában HTTP). Ha ezt a kulcsot elküldik, az
	`authtype` kötelező, és a `username` és `password` nem
	kerül felhasználásra. HTTP esetén a Git összefűzi az `authtype`
	értéket és ezt az értéket egyetlen szóközzel az `Authorization`
	fejléc meghatározásához.
+
Ezt az értéket csak akkor szabad elküldeni, ha a megfelelő képesség
(lásd lent) meg van adva a bemeneten.

`ephemeral`::
	Ez a logikai érték jelzi, ha igaz, hogy a `credential` mezőben
	lévő értéket a credential helpernek nem szabad elmentenie, mert
	hasznossága időben korlátozott. Például egy HTTP Digest
	`credential` érték kiszámítása egy nonce felhasználásával
	történik, és az újrafelhasználása nem eredményez sikeres
	hitelesítést. Ez rövid időtartamú (pl. 24 órás) hitelesítő
	adatok esetén is használható. Az alapértelmezett érték hamis.
+
A credential helper továbbra is meghívásra kerül a `store` vagy
`erase` akcióval, hogy meg tudja állapítani, sikeres volt-e a
művelet.
+
Ezt az értéket csak akkor szabad elküldeni, ha a megfelelő képesség
(lásd lent) meg van adva a bemeneten.

`state[]`::
	Ez az érték egy átlátszatlan állapotot ad meg, amelyet
	visszaküldenek ennek a helpernek, ha újra meghívásra kerül.
	Minden egyes eltérő credential helper csak egyszer adhatja meg
	ezt. Az értéknek tartalmaznia kell a credential helperre
	jellemző, egyedi előtagot, és figyelmen kívül kell hagynia azokat
	az értékeket, amelyek nem illeszkednek az előtagjára.
+
Ezt az értéket csak akkor szabad elküldeni, ha a megfelelő képesség
(lásd lent) meg van adva a bemeneten.

`continue`::
	Ez egy logikai érték, amely, ha engedélyezve van, azt jelzi,
	hogy ez a hitelesítés egy többlépcsős hitelesítési folyamat nem
	végleges része. Ez gyakori olyan protokollokban, mint az NTLM és
	a Kerberos, ahol a kliens hitelesítésének két fordulója
	szükséges, és ennek a jelzőnek a beállítása lehetővé teszi a
	credential helper számára a többlépcsős hitelesítési lépés
	megvalósítását. Ezt a jelzőt csak akkor szabad elküldeni, ha
	további lépcső szükséges; azaz ha a hitelesítés egy újabb
	fordulója várható.
+
Ezt az értéket csak akkor szabad elküldeni, ha a megfelelő képesség
(lásd lent) meg van adva a bemeneten. Ez az attribútum 'one-way'
(egyirányú) a credential helpertől a Git felé (vagy a `git
credential`-t meghívó más programok felé) információ átadására.

`wwwauth[]`::

	Amikor a Git egy olyan HTTP-választ kap, amely egy vagy több
	'WWW-Authenticate' hitelesítési fejlécet tartalmaz, ezeket a Git
	továbbítja a credential helpereknek.
+
Minden 'WWW-Authenticate' fejlécérték egy 'wwwauth[]' többértékű
attribútumként kerül átadásra, ahol az attribútumok sorrendje
megegyezik a HTTP-válaszban megjelenő sorrendjükkel. Ez az attribútum
'one-way' (egyirányú) a Git felől a credential helperek felé,
kiegészítő információk átadására.

`capability[]`::
	Ez jelzi, hogy a Git, vagy adott esetben a helper, támogatja a
	kérdéses képességet. Ez felhasználható jobb, specifikusabb adatok
	biztosítására a protokoll részeként. Egy `capability[]`
	direktívának meg kell előznie minden tőle függő értéket, és ezeket
	a direktíváknak _ajánlott_ elsőként bejelentett elemként szerepelniük
	a protokollban.
+
Jelenleg két támogatott képesség van. Az első az `authtype`, amely
azt jelzi, hogy az `authtype`, `credential` és `ephemeral` értékeket
megérti. A második a `state`, amely azt jelzi, hogy a `state[]` és
`continue` értékeket megérti.
+
Nem kötelező az additív funkciókat használni pusztán azért, mert a
képesség támogatott, de ezeket nem szabad megadni a képesség nélkül.

A fel nem ismert attribútumok és képességek némán elvetésre kerülnek.

[[CAPA-IOFMT]]
KÉPESSÉG BEMENETI/KIMENETI FORMÁTUMA
------------------------------------

A `git credential capability` esetén a formátum kissé eltérő. Először
egy `version 0` bejelentés jelzi a protokoll jelenlegi verzióját, majd
minden képesség bejelentésre kerül egy olyan sorral, mint a
`capability authtype`. A credential helperek is megvalósíthatják ezt
a formátumot, szintén a `capability` argumentummal. A jövőben további
sorok is hozzáadhatók; a hívóknak figyelmen kívül kell hagyniuk azokat
a sorokat, amelyeket nem értenek.

Mivel ez a credential helper protokoll egy új része, a Git régebbi
verziói, valamint néhány credential helper, nem biztos, hogy
támogatja. Ha nem nulla kilépési státusz érkezik, vagy ha az első sor
nem a `version` szóval és egy szóközzel kezdődik, a hívóknak fel kell
tételezniük, hogy nincs támogatott képesség.

Ennek a formátumnak a célja, hogy egyértelműen megkülönböztesse magát
a hitelesítőadat-kimenettől. Lehetséges nagyon egyszerű credential
helpereket használni (pl. inline shell szkripteket), amelyek mindig
azonos kimenetet produkálnak. Egy különálló formátum használata
lehetővé teszi a felhasználók számára, hogy továbbra is használják ezt
a szintaxist anélkül, hogy aggódniuk kellene a képesség-bejelentések
helyes megvalósítása miatt, vagy amiatt, hogy véletlenül összezavarják
a képességeket lekérdező hívókat.

GIT
---
A linkgit:git[1] csomag része
