git-index-pack(1)
=================

NAME
----
git-index-pack - Pack-indexfájl felépítése egy meglévő csomagolt archívumhoz


SYNOPSIS
--------
[verse]
'git index-pack' [-v] [-o <index-file>] [--[no-]rev-index] <pack-file>
'git index-pack' --stdin [--fix-thin] [--keep] [-v] [-o <index-file>]
		  [--[no-]rev-index] [<pack-file>]


DESCRIPTION
-----------
Beolvas egy csomagolt archívumot (.pack) a megadott fájlból, felépít
hozzá egy pack-indexfájlt (.idx), és opcionálisan ír egy fordított
indexet (.rev) a megadott packhez. A csomagolt archívum a
pack-indexszel együtt ezután elhelyezhető egy Git repository
objects/pack/ könyvtárában.


OPTIONS
-------
-v::
	Bőbeszédűség a történésekről, beleértve a folyamatállapotot is.

-o <index-file>::
	A generált pack-index kiírása a megadott fájlba.  Ezen opció
	nélkül a pack-indexfájl neve a csomagolt archívumfájl nevéből
	épül fel úgy, hogy a .pack helyére .idx kerül (és a program
	hibázik, ha a csomagolt archívum neve nem .pack-re végződik).

--rev-index::
--no-rev-index::
	Ha ez a flag meg van adva, egy, a megadott packnek megfelelő
	fordított index (egy `.rev` fájl) generálása. Ha a `--verify` meg
	van adva, annak biztosítása, hogy a meglévő fordított index helyes.
	Elsőbbséget élvez a `pack.writeReverseIndex`-szel szemben.

--stdin::
	Ha ez a flag meg van adva, a pack helyette az stdinről olvasódik
	be, és egy másolat íródik a <pack-file>-ba. Ha a <pack-file> nincs
	megadva, a pack az aktuális Git repository objects/pack/
	könyvtárába íródik egy, a pack tartalmából meghatározott
	alapértelmezett névvel.  Ha a <pack-file> nincs megadva, fontold
	meg a --keep használatát, hogy elkerüld a versenyhelyzetet e
	folyamat és a 'git repack' között.

--fix-thin::
	A `git pack-objects --thin` által előállított "thin" (vékony) pack
	javítása (l. linkgit:git-pack-objects[1] a részletekért) úgy, hogy
	a packhez hozzáadja azokat a kizárt objektumokat, amelyeken a
	deltásított objektumok alapulnak. Ennek az opciónak csak a --stdin
	mellett van értelme.

--keep::
	Mielőtt az indexet a végleges helyére mozgatná, egy üres .keep
	fájl létrehozása a hozzá tartozó packfájlhoz. Ez az opció a
	--stdin mellett általában szükséges, hogy megakadályozza, hogy egy
	egyidejűleg futó 'git repack' folyamat törölje az újonnan
	felépített packet és indexet, mielőtt a refek frissülhetnének a
	packben lévő objektumok használatára.

--keep=<msg>::
	A --keep-hez hasonlóan .keep fájl létrehozása az index végleges
	helyére mozgatása előtt.  Azonban üres fájl létrehozása helyett a
	.keep fájlba a '<msg>'-t, majd egy LF-et helyez el.  A '<msg>'
	üzenet később kikereshető az összes .keep fájlban, hogy megtaláld
	azokat, amelyek túlélték a hasznosságukat.

--index-version=<version>[,<offset>]::
	Ez csak a tesztkészlet általi használatra szolgál. Lehetővé teszi
	a generált pack-index verziójának kikényszerítését, és a 64 bites
	indexbejegyzések kikényszerítését a megadott eltolás felett
	elhelyezkedő objektumokon.

--strict[=<msg-id>=<severity>...]::
	Kilép hibával, ha a pack törött objektumokat vagy linkeket
	tartalmaz. Átadható egy opcionális, vesszővel elválasztott
	`<msg-id>=<severity>` lista egyes lehetséges problémák
	súlyosságának megváltoztatásához, pl.
	 `--strict="missingEmail=ignore,badTagName=error"`. A `<msg-id>` és
	a `<severity>` lehetséges értékeiről további információért l. a
	`fsck.<msg-id>` konfigurációs opciók bejegyzését a linkgit:git-fsck[1]-ben.

--progress-title::
	Csak belső használatra.
+
A folyamatjelző sáv címének beállítása. A cím alapból "Receiving objects",
és "Indexing objects", ha a `--stdin` meg van adva.

--check-self-contained-and-connected::
	Kilép hibával, ha a pack törött linkeket tartalmaz. Csak belső
	használatra.

--fsck-objects[=<msg-id>=<severity>...]::
	Kilép hibával, ha a pack törött objektumokat tartalmaz, de a
	`--strict`-kel ellentétben nem akad fenn a törött linkeken. Ha a
	pack tartalmaz egy tree-t, amely egy nem létező .gitmodules blobra
	mutat, kiírja annak a blobnak a hash-ét (hogy a hívó ellenőrizze) a
	pack/idx fájl nevébe kerülő hash után (l. "Notes").
+
Átadható egy opcionális, vesszővel elválasztott `<msg-id>=<severity>`
lista egyes lehetséges problémák súlyosságának megváltoztatásához, pl.
`--fsck-objects="missingEmail=ignore,badTagName=ignore"`. A `<msg-id>` és
a `<severity>` lehetséges értékeiről további információért l. a
`fsck.<msg-id>` konfigurációs opciók bejegyzését a linkgit:git-fsck[1]-ben.

--threads=<n>::
	Megadja a delták feloldásakor indítandó szálak számát. Ehhez az
	kell, hogy az index-pack pthreads-szel legyen fordítva, egyébként
	ez az opció figyelmen kívül marad egy figyelmeztetéssel.  Ez a
	csomagolási idő csökkentésére szolgál többprocesszoros gépeken. A
	delta-keresési ablakhoz szükséges memória mennyisége azonban
	megszorzódik a szálak számával.  A 0 megadása hatására a Git
	automatikusan felismeri a CPU-k számát, és legfeljebb 3 szálat
	használ.

--max-input-size=<size>::
	Kilép hibával, ha a pack nagyobb, mint <size>.

--object-format=<hash-algorithm>::
	A megadott objektumformátum (hash-algoritmus) megadása a packhez.
	Az érvényes értékek a 'sha1' és (ha engedélyezve van) a 'sha256'.
	Az alapértelmezés az aktuális repository algoritmusa (amelyet az
	`extensions.objectFormat` állít be), vagy a 'sha1', ha nincs érték
	beállítva, vagy repository-n kívül vagy.
+
Ez az opció nem használható a --stdin-nel.
+
include::object-format-disclaimer.adoc[]

--promisor[=<message>]::
	A pack-index véglegesítése előtt egy .promisor fájl létrehozása
	ehhez a packhez. Különösen hasznos, amikor promisor packet írsz a
	--fix-thinnel, mivel a pack neve nem végleges addig, amíg a pack
	teljesen ki nincs írva. Ha egy `<message>` meg van adva, akkor az a
	tartalom a .promisor fájlba íródik későbbi hivatkozás céljából.
	További információért l. link:technical/partial-clone.html[partial clone].
+
Továbbá, ha a megadott packben vannak olyan objektumok, amelyek
nem-promisor objektumokra hivatkoznak (a repóban), azokat a
nem-promisor objektumokat egy promisor packbe csomagolja újra. Ez
elkerül egy olyan helyzetet, amelyben egy repónak vannak nem-promisor
objektumai, amelyek promisor objektumokon keresztül elérhetők.
+
Megköveteli, hogy a <pack-file> ne legyen megadva.

NOTES
-----

Miután az index létrejött, a pack/idx fájl nevébe kerülő hash az
stdoutra íródik. Ha a --stdin is használva volt, akkor ez elé vagy
"pack\t", vagy – ha egy új .keep fájl sikeresen létrejött – "keep\t"
kerül. Ez hasznos a fent említett 'git repack'-kel való versenyhelyzet
megakadályozására zárként használt .keep fájl eltávolításához.

GIT
---
A linkgit:git[1] csomag része
