git-rev-list(1)
===============

NAME
----
git-rev-list - Commit-objektumokat listáz fordított időrendben


SYNOPSIS
--------
[verse]
'git rev-list' [<options>] <commit>... [--] [<path>...]

DESCRIPTION
-----------

:git-rev-list: 1
include::rev-list-description.adoc[]

A 'rev-list' egy alapvető Git-parancs, mivel lehetővé teszi
commit-ősgráfok felépítését és bejárását. Ezért sokféle különböző
opciója van, amelyek lehetővé teszik, hogy olyan eltérő parancsok
használják, mint a 'git bisect' és a 'git repack'.

OPTIONS
-------

:git-rev-list: 1
include::rev-list-options.adoc[]

include::pretty-formats.adoc[]

EXAMPLES
--------

* Az aktuális branchből elérhető commitok listájának kiírása.
+
----------
git rev-list HEAD
----------

* Az ezen a branchen lévő, de az upstream branchen nem szereplő
  commitok listájának kiírása.
+
----------
git rev-list @{upstream}..HEAD
----------

* Commitok formázása a szerzőjükkel és a commit-üzenetükkel együtt
  (lásd még a porcelain linkgit:git-log[1]-et).
+
----------
git rev-list --format=medium HEAD
----------

* Commitok formázása a diffjeikkel együtt (lásd még a porcelain
  linkgit:git-log[1]-et, amely ezt egyetlen folyamatban meg tudja tenni).
+
----------
git rev-list HEAD |
git diff-tree --stdin --format=medium -p
----------

* Az aktuális branchen lévő azon commitok listájának kiírása, amelyek
  a `Documentation` könyvtár bármely fájlját érintették.
+
----------
git rev-list HEAD -- Documentation/
----------

* Az általad az elmúlt évben írt commitok listájának kiírása bármely
  branchen, tagen vagy más referencián.
+
----------
git rev-list --author=you@example.com --since=1.year.ago --all
----------

* Az aktuális branchből elérhető objektumok listájának kiírása (azaz
  minden commit, valamint az általuk tartalmazott blobok és tree-k).
+
----------
git rev-list --objects HEAD
----------

* Az összes elérhető objektum lemezméretének összehasonlítása a
  reflogokból elérhetőkével, illetve a teljes csomagolt mérettel. Ez
  megmutatja, hogy a `git repack -ad` futtatása csökkentheti-e a
  repository méretét (az el nem érhető objektumok eldobásával), és hogy
  a reflogok lejáratása segíthet-e.
+
----------
# reachable objects
git rev-list --disk-usage --objects --all
# plus reflogs
git rev-list --disk-usage --objects --all --reflog
# total disk size used
du -c .git/objects/pack/*.pack .git/objects/??/*
# alternative to du: add up "size" and "size-pack" fields
git count-objects -v
----------

* Az egyes branchek lemezméretének jelentése, az aktuális branch által
  használt objektumok nélkül. Ez megtalálja azokat a kiugró értékeket,
  amelyek a repository méretének felduzzadásához járulnak hozzá (pl.
  mert valaki véletlenül nagy build-műtermékeket commitolt).
+
----------
git for-each-ref --format='%(refname)' |
while read branch
do
	size=$(git rev-list --disk-usage --objects HEAD..$branch)
	echo "$size $branch"
done |
sort -n
----------

* A branchek lemezméretének összehasonlítása a referenciák egyik
  csoportjában, egy másikat kizárva. Ha több remote objektumait
  kevered egyetlen repository-ban, ez megmutatja, mely remote-ok
  járulnak hozzá a repository méretéhez (az `origin` méretét véve
  alapvonalnak).
+
----------
git rev-list --disk-usage --objects --remotes=$suspect --not --remotes=origin
----------

GIT
---
A linkgit:git[1] csomag része
