git-remote-ext(1)
=================

NAME
----
git-remote-ext - Hidat képez a »smart« átvitel és egy külső parancs között.

SYNOPSIS
--------
[verse]
git remote add <nick> "ext::<command>[ <arguments>...]"

DESCRIPTION
-----------
Ez a remote helper a megadott '<command>'-ot használja egy remote Git
szerverhez való csatlakozáshoz.

A megadott '<command>' stdinjére írt adatokról feltételezi, hogy egy
git:// szervernek, a git-upload-packnek, a git-receive-packnek vagy a
git-upload-archive-nak küldi őket (a helyzettől függően), a <command>
stdoutjáról olvasott adatokról pedig, hogy ugyanattól a szolgáltatástól
érkeznek.

A parancsot és az argumentumokat nem escape-elt szóköz választja el.

A következő szekvenciáknak speciális jelentésük van:

'% '::
	Szó szerinti szóköz a parancsban vagy argumentumban.

'%%'::
	Szó szerinti százalékjel.

'%s'::
	Annak a szolgáltatásnak a nevével (receive-pack, upload-pack vagy
	upload-archive) helyettesítődik, amelyet a Git meg akar hívni.

'%S'::
	Annak a szolgáltatásnak a hosszú nevével (git-receive-pack,
	git-upload-pack vagy git-upload-archive) helyettesítődik, amelyet a
	Git meg akar hívni.

'%G' (must be the first characters in an argument)::
	Ez az argumentum nem kerül átadásra a '<command>'-nak. Ehelyett arra
	készteti a helpert, hogy azzal kezdjen, hogy git:// szolgáltatás-
	kéréseket küld a remote oldalnak, ahol a service mező megfelelő
	értékre, a repository mező pedig az argumentum maradékára van
	állítva. Alapértelmezés szerint nem küld ilyen kérést.
+
Ez akkor hasznos, ha a remote oldal egy valamilyen alagúton keresztül
elért git:// szerver.

'%V' (must be first characters in argument)::
	Ez az argumentum nem kerül átadásra a '<command>'-nak. Ehelyett
	beállítja a vhost mezőt a git:// szolgáltatás-kérésben (az argumentum
	maradékára). Alapértelmezés szerint nem küld vhostot ilyen kérésben
	(ha küld egyáltalán).

ENVIRONMENT VARIABLES
---------------------

GIT_TRANSLOOP_DEBUG::
	Ha be van állítva, hibakeresési információt ír ki a különféle
	olvasásokról/írásokról.

ENVIRONMENT VARIABLES PASSED TO COMMAND
---------------------------------------

GIT_EXT_SERVICE::
	Annak a szolgáltatásnak a hosszú nevére (git-upload-pack stb...) van
	állítva, amelyet a helpernek meg kell hívnia.

GIT_EXT_SERVICE_NOPREFIX::
	Annak a szolgáltatásnak a hosszú nevére (upload-pack stb...) van
	állítva, amelyet a helpernek meg kell hívnia.


EXAMPLES
--------
Ezt a remote helpert a Git átlátszóan használja, amikor olyan
parancsokat használsz, mint a "git fetch <URL>", "git clone <URL>",
, "git push <URL>" vagy "git remote add <nick> <URL>", ahol az <URL>
`ext::`-tel kezdődik.  Példák:

"ext::ssh -i /home/foo/.ssh/somekey user&#64;host.example %S 'foo/repo'"::
	Mint a host.example:foo/repo, de a /home/foo/.ssh/somekey-t
	használja kulcspárként, a user-t pedig a remote oldali
	felhasználóként. Ez feleslegessé teszi a .ssh/config szerkesztését.

"ext::socat -t3600 - ABSTRACT-CONNECT:/git-server %G/somerepo"::
	A /somerepo elérési útú repository-t képviseli, amely git
	protokollon keresztül elérhető a /git-server absztrakt
	névtér-címen.

"ext::git-server-alias foo %G/repo"::
	A /repo elérési útú repository-t képviseli, amelyet a
	"git-server-alias foo" helper program használatával érnek el.  A
	repository elérési útját és a kérés típusát nem a parancssoron adja
	át, hanem a protokoll-adatfolyam részeként, ahogy a git://
	protokollnál szokásos.

"ext::git-server-alias foo %G/repo %Vfoo"::
	A /repo elérési útú repository-t képviseli, amelyet a
	"git-server-alias foo" helper program használatával érnek el.  A
	protokoll-adatfolyamban átadott hosztnév a remote szerverhez "foo"
	lesz (ez lehetővé teszi, hogy több virtuális Git szerver
	megosszon egy link-szintű címet).

"ext::git-server-alias foo %G/repo% with% spaces %Vfoo"::
	A `/repo with spaces` elérési útú repository-t képviseli, amelyet a
	"git-server-alias foo" helper program használatával érnek el.  A
	protokoll-adatfolyamban átadott hosztnév a remote szerverhez "foo"
	lesz (ez lehetővé teszi, hogy több virtuális Git szerver
	megosszon egy link-szintű címet).

"ext::git-ssl foo.example /bar"::
	Egy olyan repository-t képvisel, amelyet a "git-ssl foo.example
	/bar" helper program használatával érnek el.  A kérés típusát a
	helper környezeti változók segítségével tudja meghatározni (lásd
	fent).

SEE ALSO
--------
linkgit:gitremote-helpers[7]

GIT
---
A linkgit:git[1] csomag része
