git-http-backend(1)
===================

NAME
----
git-http-backend - A Git HTTP feletti szerveroldali megvalósítása

SYNOPSIS
--------
[verse]
'git http-backend'

DESCRIPTION
-----------
Egyszerű CGI program, amely egy Git repository tartalmát szolgálja ki
azoknak a Git klienseknek, amelyek http:// és https:// protokollon keresztül
érik el a repositoryt. A program támogatja a „smart" HTTP-protokollal és a
visszafelé kompatibilis „dumb" HTTP-protokollal fetchelő klienseket,
valamint a „smart" HTTP-protokollal pusholó klienseket is. Megfelelő
konfiguráció esetén támogatja a Git hatékonyabb „v2" protokollját is; lásd a
`GIT_PROTOCOL` tárgyalását lentebb, az ENVIRONMENT szakaszban.

Ellenőrzi, hogy a könyvtárban megvan-e a „git-daemon-export-ok" mágikus
fájl, és megtagad minden olyan Git-könyvtár exportálását, amelyet nem
jelöltek meg kifejezetten így exportálásra (hacsak a `GIT_HTTP_EXPORT_ALL`
környezeti változó nincs beállítva).

Alapértelmezés szerint csak az `upload-pack` szolgáltatás engedélyezett,
amely a 'git fetch-pack' és 'git ls-remote' klienseket szolgálja ki, ezeket
pedig a 'git fetch', a 'git pull' és a 'git clone' hívja meg.  Ha a kliens
hitelesítve van, engedélyezetté válik a `receive-pack` szolgáltatás, amely a
'git send-pack' klienseket szolgálja ki, ezt a 'git push' hívja meg.

SERVICES
--------
Ezek a szolgáltatások a repositorynkénti konfigurációs fájllal
engedélyezhetők/letilthatók:

http.getanyfile::
	Az 1.6.6-nál régebbi Git klienseket szolgálja ki, amelyek nem
	tudják használni az upload pack szolgáltatást.  Engedélyezve a
	kliensek a repositoryn belül bármely fájlt olvashatnak, beleértve
	azokat az objektumokat is, amelyek egy branchből már nem elérhetők,
	de még jelen vannak.
	Alapértelmezés szerint engedélyezett, de egy repository letilthatja,
	ha ezt a konfigurációs értéket `false`-ra állítja.

http.uploadpack::
	A 'git fetch-pack' és 'git ls-remote' klienseket szolgálja ki.
	Alapértelmezés szerint engedélyezett, de egy repository letilthatja,
	ha ezt a konfigurációs értéket `false`-ra állítja.

http.receivepack::
	A 'git send-pack' klienseket szolgálja ki, lehetővé téve a
	pusholást.  Anonim felhasználók számára alapértelmezés szerint
	letiltott, a webszerver által hitelesített felhasználók számára
	pedig alapértelmezés szerint engedélyezett.  Letiltható, ha ezt a
	tételt `false`-ra állítod, vagy engedélyezhető minden felhasználó
	számára, az anonim felhasználókat is beleértve, ha `true`-ra
	állítod.

http.uploadarchive::
	A 'git archive' klienseket szolgálja ki távoli archiváláshoz
	HTTP/HTTPS protokollon. Alapértelmezés szerint letiltott. Csak a v2
	protokollban működik.

URL TRANSLATION
---------------
A repository lemezen lévő helyének meghatározásához a 'git http-backend'
összefűzi a PATH_INFO környezeti változót, amelyet a webszerver
automatikusan beállít, és a GIT_PROJECT_ROOT-ot, amelyet kézzel kell
beállítani a webszerver konfigurációjában.  Ha a GIT_PROJECT_ROOT nincs
beállítva, a 'git http-backend' a PATH_TRANSLATED-et olvassa, amelyet
szintén a webszerver állít be automatikusan.

EXAMPLES
--------
Az összes alábbi példa a `http://$hostname/git/foo/bar.git` címet a
`/var/www/git/foo/bar.git` helyre képezi le.

Apache 2.x::
	Győződj meg róla, hogy a mod_cgi, a mod_alias és a mod_env
	engedélyezve van, állítsd be megfelelően a GIT_PROJECT_ROOT-ot
	(vagy a DocumentRoot-ot), és hozz létre egy ScriptAliast a CGI-hez:
+
----------------------------------------------------------------
SetEnv GIT_PROJECT_ROOT /var/www/git
SetEnv GIT_HTTP_EXPORT_ALL
ScriptAlias /git/ /usr/libexec/git-core/git-http-backend/

# This is not strictly necessary using Apache and a modern version of
# git-http-backend, as the webserver will pass along the header in the
# environment as HTTP_GIT_PROTOCOL, and http-backend will copy that into
# GIT_PROTOCOL. But you may need this line (or something similar if you
# are using a different webserver), or if you want to support older Git
# versions that did not do that copying.
#
# Having the webserver set up GIT_PROTOCOL is perfectly fine even with
# modern versions (and will take precedence over HTTP_GIT_PROTOCOL,
# which means it can be used to override the client's request).
SetEnvIf Git-Protocol ".*" GIT_PROTOCOL=$0
----------------------------------------------------------------
+
Az anonim olvasási hozzáférés, de hitelesített írási hozzáférés
engedélyezéséhez követeld meg az engedélyezést mind a kezdeti
ref-hirdetéshez (amelyet a query stringben lévő service paraméter alapján
pushként érzékelünk), mind magához a receive-pack híváshoz:
+
----------------------------------------------------------------
RewriteCond %{QUERY_STRING} service=git-receive-pack [OR]
RewriteCond %{REQUEST_URI} /git-receive-pack$
RewriteRule ^/git/ - [E=AUTHREQUIRED:yes]

<LocationMatch "^/git/">
	Order Deny,Allow
	Deny from env=AUTHREQUIRED

	AuthType Basic
	AuthName "Git Access"
	Require group committers
	Satisfy Any
	...
</LocationMatch>
----------------------------------------------------------------
+
Ha nincs elérhető `mod_rewrite`-od a query stringre való illesztéshez,
elegendő magát a `git-receive-pack`-et védeni, például így:
+
----------------------------------------------------------------
<LocationMatch "^/git/.*/git-receive-pack$">
	AuthType Basic
	AuthName "Git Access"
	Require group committers
	...
</LocationMatch>
----------------------------------------------------------------
+
Ebben a módban a szerver nem kér hitelesítést addig, amíg a kliens
ténylegesen el nem kezdi a push objektum-egyeztetési fázisát, nem pedig a
kezdeti kapcsolatfelvételkor.  Ezért engedélyezned kell a
`http.receivepack` konfigurációs opciót is minden olyan repositoryban,
amelynek el kell fogadnia a pusholást. Ha a `http.receivepack` nincs
beállítva, az alapértelmezett viselkedés az, hogy elutasít minden
hitelesítetlen felhasználótól érkező pusholást; a kezdeti kérés így
`403 Forbidden` hibát jelez a kliensnek, anélkül, hogy egyáltalán
lehetőséget adna a hitelesítésre.
+
Ha az olvasáshoz és az íráshoz is hitelesítést szeretnél megkövetelni,
használj egy Location direktívát a repository vagy annak valamelyik
szülőkönyvtára köré:
+
----------------------------------------------------------------
<Location /git/private>
	AuthType Basic
	AuthName "Private Git Access"
	Require group committers
	...
</Location>
----------------------------------------------------------------
+
Ha a gitwebet ugyanazon az url-en szeretnéd kiszolgálni, használj
ScriptAliasMatch-et csak azokra az URL-ekre, amelyeket a 'git http-backend'
kezelni tud, a többit pedig továbbítsd a gitwebnek:
+
----------------------------------------------------------------
ScriptAliasMatch \
	"(?x)^/git/(.*/(HEAD | \
			info/refs | \
			objects/(info/[^/]+ | \
				 [0-9a-f]{2}/[0-9a-f]{38} | \
				 pack/pack-[0-9a-f]{40}\.(pack|idx)) | \
			git-(upload|receive)-pack))$" \
	/usr/libexec/git-core/git-http-backend/$1

ScriptAlias /git/ /var/www/cgi-bin/gitweb.cgi/
----------------------------------------------------------------
+
Ha egyetlen repositoryban több repositoryt szeretnél kiszolgálni különböző
linkgit:gitnamespaces[7] névterekből:
+
----------------------------------------------------------------
SetEnvIf Request_URI "^/git/([^/]*)" GIT_NAMESPACE=$1
ScriptAliasMatch ^/git/[^/]*(.*) /usr/libexec/git-core/git-http-backend/storage.git$1
----------------------------------------------------------------

Gyorsított statikus Apache 2.x::
	Hasonló a fentihez, de az Apache használható a lemezen tárolt
	statikus fájlok visszaadására.  Sok rendszeren ez hatékonyabb
	lehet, mivel az Apache megkérheti a kernelt, hogy a fájl tartalmát
	közvetlenül a fájlrendszerről a hálózatra másolja:
+
----------------------------------------------------------------
SetEnv GIT_PROJECT_ROOT /var/www/git

AliasMatch ^/git/(.*/objects/[0-9a-f]{2}/[0-9a-f]{38})$          /var/www/git/$1
AliasMatch ^/git/(.*/objects/pack/pack-[0-9a-f]{40}.(pack|idx))$ /var/www/git/$1
ScriptAlias /git/ /usr/libexec/git-core/git-http-backend/
----------------------------------------------------------------
+
Ez kombinálható a gitweb konfigurációjával:
+
----------------------------------------------------------------
SetEnv GIT_PROJECT_ROOT /var/www/git

AliasMatch ^/git/(.*/objects/[0-9a-f]{2}/[0-9a-f]{38})$          /var/www/git/$1
AliasMatch ^/git/(.*/objects/pack/pack-[0-9a-f]{40}.(pack|idx))$ /var/www/git/$1
ScriptAliasMatch \
	"(?x)^/git/(.*/(HEAD | \
			info/refs | \
			objects/info/[^/]+ | \
			git-(upload|receive)-pack))$" \
	/usr/libexec/git-core/git-http-backend/$1
ScriptAlias /git/ /var/www/cgi-bin/gitweb.cgi/
----------------------------------------------------------------

Lighttpd::
	Győződj meg róla, hogy a `mod_cgi`, `mod_alias`, `mod_auth`,
	`mod_setenv` be van töltve, majd állítsd be megfelelően a
	`GIT_PROJECT_ROOT`-ot, és irányíts át minden kérést a CGI-hez:
+
----------------------------------------------------------------
alias.url += ( "/git" => "/usr/lib/git-core/git-http-backend" )
$HTTP["url"] =~ "^/git" {
	cgi.assign = ("" => "")
	setenv.add-environment = (
		"GIT_PROJECT_ROOT" => "/var/www/git",
		"GIT_HTTP_EXPORT_ALL" => ""
	)
}
----------------------------------------------------------------
+
Az anonim olvasási hozzáférés, de hitelesített írási hozzáférés
engedélyezéséhez:
+
----------------------------------------------------------------
$HTTP["querystring"] =~ "service=git-receive-pack" {
	include "git-auth.conf"
}
$HTTP["url"] =~ "^/git/.*/git-receive-pack$" {
	include "git-auth.conf"
}
----------------------------------------------------------------
+
ahol a `git-auth.conf` valahogy így néz ki:
+
----------------------------------------------------------------
auth.require = (
	"/" => (
		"method" => "basic",
		"realm" => "Git Access",
		"require" => "valid-user"
	       )
)
# ...and set up auth.backend here
----------------------------------------------------------------
+
Ha az olvasáshoz és az íráshoz is hitelesítést szeretnél megkövetelni:
+
----------------------------------------------------------------
$HTTP["url"] =~ "^/git/private" {
	include "git-auth.conf"
}
----------------------------------------------------------------


ENVIRONMENT
-----------
A 'git http-backend' a hívó webszerver által beállított `CGI` környezeti
változókra támaszkodik, többek között:

* PATH_INFO (ha a GIT_PROJECT_ROOT be van állítva, egyébként PATH_TRANSLATED)
* REMOTE_USER
* REMOTE_ADDR
* CONTENT_TYPE
* QUERY_STRING
* REQUEST_METHOD

A `GIT_HTTP_EXPORT_ALL` környezeti változó átadható a
'git-http-backend'-nek, hogy megkerülje az egyes repositorykban a
"git-daemon-export-ok" fájl ellenőrzését, mielőtt engedélyezné az adott
repository exportálását.

A `GIT_HTTP_MAX_REQUEST_BUFFER` környezeti változó (vagy a
`http.maxRequestBuffer` konfigurációs opció) beállításával módosítható a
legnagyobb ref-egyeztetési kérés, amelyet a git egy fetch során kezel;
minden nagyobb buffert igénylő fetch sikertelen lesz.  Rendes esetben ezt
az értéket nem kell megváltoztatni, de hasznos lehet, ha rendkívül sok
refet tartalmazó repositoryból fetchelsz.  Az érték egységgel is megadható
(pl. `100M` 100 megabájthoz). Az alapértelmezés 10 megabájt.

A kliensek a `Git-Protocol` HTTP-fejléccel felderíthetik az opcionális
protokollképességeket (például a v2 protokollt). Ezek támogatásához a
fejléc tartalmának meg kell jelennie a `GIT_PROTOCOL` környezeti változóban.
A legtöbb webszerver a `HTTP_GIT_PROTOCOL` változón keresztül adja át ezt a
fejlécet a CGI-nek, és a `git-http-backend` automatikusan átmásolja azt a
`GIT_PROTOCOL`-ba. Egyes webszerverek azonban válogatósabbak lehetnek abban,
hogy mely fejléceket adják át, ilyenkor kifejezetten konfigurálni kell őket
(lásd a `Git-Protocol` említését a korábbi EXAMPLES szakasz Apache
konfigurációjában).

A backend folyamat a GIT_COMMITTER_NAME értékét '$REMOTE_USER'-re, a
GIT_COMMITTER_EMAIL értékét pedig '$\{REMOTE_USER}@http.$\{REMOTE_ADDR\}'-re
állítja, biztosítva, hogy a 'git-receive-pack' által létrehozott reflogok
tartalmazzanak valamiféle azonosító információt a pusholást végző remote
felhasználóról.

Minden `CGI` környezeti változó elérhető a 'git-receive-pack' által
meghívott összes hook számára.

GIT
---
A linkgit:git[1] csomag része
