git-apply(1)
============

NAME
----
git-apply - Egy patch alkalmazása fájlokra és/vagy az indexre


SYNOPSIS
--------
[synopsis]
git apply [--stat] [--numstat] [--summary] [--check]
	  [--index | --intent-to-add] [--3way] [--ours | --theirs | --union]
	  [--apply] [--no-add] [--build-fake-ancestor=<file>] [-R | --reverse]
	  [--allow-binary-replacement | --binary] [--reject] [-z]
	  [-p<n>] [-C<n>] [--inaccurate-eof] [--recount] [--cached]
	  [--ignore-space-change | --ignore-whitespace]
	  [--whitespace=(nowarn|warn|fix|error|error-all)]
	  [--exclude=<path>] [--include=<path>] [--directory=<root>]
	  [--verbose | --quiet] [--unsafe-paths] [--allow-empty] [<patch>...]

DESCRIPTION
-----------
Beolvassa a megadott diff-kimenetet (azaz „egy patchet"), és
alkalmazza azt fájlokra. Ha egy repository egy alkönyvtárából
futtatod, a könyvtáron kívül eső, patchelt útvonalak figyelmen kívül
maradnak.
A `--index` opcióval a patch az indexre is alkalmazásra kerül, a
`--cached` opcióval pedig a patch kizárólag az indexre kerül
alkalmazásra.
Ezek az opciók nélkül a parancs a patchet csak fájlokra alkalmazza,
és nem követeli meg, hogy azok egy Git repositoryban legyenek.

Ez a parancs alkalmazza a patchet, de nem hoz létre commitot.
Használd a linkgit:git-am[1] parancsot ahhoz, hogy commitokat hozz
létre a linkgit:git-format-patch[1] által generált és/vagy e-mailben
kapott patchekből.

OPTIONS
-------
`<patch>...`::
	Azok a fájlok, amelyekből a patchet olvassa. A `-` használható a
	standard bemenetről való olvasáshoz.

`--stat`::
	A patch alkalmazása helyett diffstat-ot ír ki a bemenethez.
	Kikapcsolja az „apply"-t.

`--numstat`::
	Hasonló a `--stat`-hoz, de tizedes jelöléssel mutatja a
	hozzáadott és törölt sorok számát, valamint rövidítés nélküli
	útvonalnevet ad, hogy gépileg jobban feldolgozható legyen.
	Bináris fájloknál `0 0` helyett két `-` jelet ír ki. Kikapcsolja
	az „apply"-t.

`--summary`::
	A patch alkalmazása helyett tömör összefoglalót ír ki a git diff
	kiterjesztett fejléceiből nyert információkról, mint például
	létrehozások, átnevezések és mód-módosítások. Kikapcsolja az
	„apply"-t.

`--check`::
	A patch alkalmazása helyett megnézi, hogy a patch alkalmazható-e
	az aktuális munkakönyvtárra és/vagy az index fájlra, és
	érzékeli a hibákat. Kikapcsolja az „apply"-t.

`--index`::
	Alkalmazza a patchet mind az indexre, mind a munkakönyvtárra (vagy
	ha a `--check` van érvényben, csupán ellenőrzi, hogy mindkettőre
	tisztán alkalmazható lenne-e). Vedd figyelembe, hogy a `--index`
	elvárja, hogy az érintett útvonalak index-bejegyzései és
	munkakönyvtárbeli másolatai azonosak legyenek (a tartalmuknak és
	az olyan metaadatoknak, mint a fájlmód, egyezniük kell), és hibát
	jelez, ha nem így van, még akkor is, ha a patch külön-külön mind
	az indexre, mind a munkakönyvtárra tisztán alkalmazható lenne.

`--cached`::
	Alkalmazza a patchet kizárólag az indexre, a munkakönyvtár
	érintése nélkül. Ha a `--check` érvényben van, csak azt
	ellenőrzi, hogy tisztán alkalmazható lenne-e az index-bejegyzésre.

`-N`::
`--intent-to-add`::
	Ha a patchet csak a munkakönyvtárra alkalmazza, megjelöli az új
	fájlokat, hogy azok később kerüljenek hozzáadásra az indexhez
	(lásd a `--intent-to-add` opciót a linkgit:git-add[1] parancsban).
	Ez az opció figyelmen kívül marad, ha a `--index` vagy a
	`--cached` van használatban, és nincs hatása Git repositoryn
	kívül. Vedd figyelembe, hogy a `--index`-et más opciók, például a
	`--3way`, is bevonhatják.

`-3`::
`--3way`::
	Megkísérel háromutas merge-et, ha a patch rögzíti azon blobok
	azonosítóját, amelyekre alkalmazni kellene, és ezek a blobok
	helyben elérhetők, adott esetben a munkakönyvtárbeli fájlokban
	hagyva az ütközésjelölőket a felhasználó számára feloldásra. Ez
	az opció bevonja a `--index` opciót, hacsak a `--cached` opció
	nincs használatban, és összeférhetetlen a `--reject` opcióval. A
	`--cached` opcióval együtt használva minden ütközés magasabb
	stage-eken marad a cache-ben.

`--ours`::
`--theirs`::
`--union`::
	Ahelyett, hogy a fájlban hagyná az ütközéseket, feloldja azokat
	a saját (vagy az övék, vagy mindkét) oldal javára. Megköveteli a
	`--3way`-t.

`--build-fake-ancestor=<file>`::
	Az újabb `git diff` kimenetek minden blobhoz beágyazott „index
	információt" tartalmaznak, hogy segítsenek azonosítani azt az
	eredeti verziót, amelyre a patch vonatkozik. Ha ez a kapcsoló meg
	van adva, és a blobok eredeti verziói helyben elérhetők, egy
	ideiglenes indexet épít, amely ezeket a blobokat tartalmazza.
+
Ha egy tiszta mód-módosítással találkozik (amelyhez nincs index
információ), az információ helyette az aktuális indexből kerül
kiolvasásra.

`-R`::
`--reverse`::
	Fordítva alkalmazza a patchet.

`--reject`::
	Az atomicitás érdekében a `git apply` alapértelmezésben
	meghiúsítja a teljes patchet, és nem nyúl a munkakönyvtárhoz, ha
	néhány hunk nem alkalmazható. Ez az opció alkalmazza a patch
	azon részeit, amelyek alkalmazhatók, és a visszautasított
	hunkokat a megfelelő `*.rej` fájlokban hagyja.

`-z`::
	Ha a `--numstat` meg van adva, nem alakítja át az útvonalneveket,
	hanem NUL-lel lezárt, géppel feldolgozható formátumot használ.
+
Ezen opció nélkül a „szokatlan" karaktereket tartalmazó útvonalnevek
idézőjelbe kerülnek, ahogy azt a `core.quotePath` konfigurációs
változó leírja (lásd: linkgit:git-config[1]).

`-p<n>`::
	Eltávolítja a hagyományos diff-útvonalak elejéről a (perjelekkel
	elválasztott) _<n>_ számú vezető útvonalkomponenst. Pl. `-p2`
	esetén az `a/dir/file` ellen készült patch közvetlenül a `file`-ra
	kerül alkalmazásra. Az alapértelmezés 1.

`-C<n>`::
	Biztosítja, hogy minden módosítás előtt és után legalább
	_<n>_ sornyi környező kontextus egyezzen. Ha kevesebb sornyi
	környező kontextus létezik, azoknak mind egyezniük kell.
	Alapértelmezésben soha nincs figyelmen kívül hagyva kontextus.

`--unidiff-zero`::
	Alapértelmezésben a `git apply` azt várja, hogy az
	alkalmazandó patch egy unified diff legyen, legalább egy sornyi
	kontextussal. Ez jó biztonsági intézkedés, de nem működik, ha a
	`--unified=0` opcióval generált diffet próbálod alkalmazni. Ezen
	ellenőrzések megkerüléséhez használd a `--unidiff-zero` opciót.
+
Vedd figyelembe, hogy a fent leírt okokból a kontextus nélküli patchek
használata nem ajánlott.

`--apply`::
	Ha a fent „Kikapcsolja az »apply«-t" jelölésű opciók
	bármelyikét használod, a `git apply` beolvassa és kiírja a
	kért információt anélkül, hogy ténylegesen alkalmazná a
	patchet. Add meg ezt a kapcsolót az adott opciók után, hogy a
	patchet is alkalmazza.

`--no-add`::
	Patch alkalmazásakor figyelmen kívül hagyja a patch által
	végzett hozzáadásokat. Ez felhasználható arra, hogy kinyerd
	két fájl közös részét úgy, hogy először lefuttatod rajtuk a
	`diff`-et, majd az eredményt ezzel az opcióval alkalmazod,
	ami a törlési részt alkalmazná, a hozzáadási részt viszont nem.

`--allow-binary-replacement`::
`--binary`::
	Korábban a bináris patch alkalmazását nem engedélyeztük a
	felhasználó explicit engedélye nélkül, és ez a kapcsoló volt
	erre a mód. Jelenleg mindig engedélyezzük a bináris patchek
	alkalmazását, így ez a kapcsoló hatástalan (no-op).

`--exclude=<path-pattern>`::
	Nem alkalmazza a módosításokat a(z) _<path-pattern>_ mintára
	illeszkedő fájlokra. Ez akkor hasznos, amikor patch-készleteket
	importálsz, és bizonyos fájlokat vagy könyvtárakat ki szeretnél
	zárni.

`--include=<path-pattern>`::
	Alkalmazza a módosításokat a(z) _<path-pattern>_ mintára
	illeszkedő fájlokra. Ez akkor hasznos, amikor patch-készleteket
	importálsz, és bizonyos fájlokat vagy könyvtárakat be szeretnél
	vonni.
+
Ha `--exclude` és `--include` minták is használatban vannak, azokat a
parancssorban való megjelenésük sorrendjében vizsgálja, és az első
találat dönti el, hogy egy adott útvonalra vonatkozó patch felhasználásra
kerül-e. Egy olyan útvonalra vonatkozó patch, amely nem illeszkedik
semelyik include/exclude mintára, alapértelmezésben felhasználásra
kerül, ha nincs include minta a parancssorban, és figyelmen kívül
marad, ha van bármilyen include minta.

`--ignore-space-change`::
`--ignore-whitespace`::
	Patch alkalmazásakor szükség esetén figyelmen kívül hagyja a
	whitespace-változásokat a kontextussorokban.
	A kontextussorok megőrzik a whitespace-üket, és nem esnek át
	whitespace-javításon, függetlenül a `--whitespace` opció
	értékétől. Az új sorok azonban továbbra is javításra kerülnek.

`--whitespace=<action>`::
	Patch alkalmazásakor felismeri az olyan új vagy módosított
	sorokat, amelyek whitespace-hibákat tartalmaznak. Hogy mi
	számít whitespace-hibának, azt a `core.whitespace` konfiguráció
	szabályozza. Alapértelmezésben a sorvégi whitespace-ek (beleértve
	a kizárólag whitespace-ből álló sorokat is), valamint a sor eleji
	behúzáson belül közvetlenül tab karakter által követett szóköz
	karakter számít whitespace-hibának.
+
Alapértelmezésben a parancs figyelmeztető üzeneteket ír ki, de
alkalmazza a patchet. Ha a `git-apply`-t statisztikára használod, nem
pedig patch alkalmazására, akkor alapértelmezésben `nowarn`-t használ.
+
Különböző _<action>_ értékekkel szabályozhatod ezt a viselkedést:
+
* `nowarn` kikapcsolja a sorvégi whitespace-figyelmeztetést.
* `warn` figyelmeztetéseket ír ki néhány ilyen hibára, de a
  patchet változatlanul alkalmazza (alapértelmezett).
* `fix` figyelmeztetéseket ír ki néhány ilyen hibára, és a
  patchet a hibák javítása után alkalmazza (a `strip` szinonima —
  az eszköz korábban csak a sorvégi whitespace karaktereket
  tekintette hibának, és a javítás azok 'lecsupaszításából' (stripping)
  állt, de a modern Git-ek ennél többet tesznek).
* `error` figyelmeztetéseket ír ki néhány ilyen hibára, és
  megtagadja a patch alkalmazását.
* `error-all` hasonló az `error`-hoz, de az összes hibát megjeleníti.

`--inaccurate-eof`::
	Bizonyos körülmények között a `diff` egyes verziói nem
	érzékelik helyesen a fájl végén hiányzó új sort. Ennek
	eredményeként az ilyen `diff` programok által létrehozott
	patchek nem rögzítik helyesen a hiányos sorokat. Ez az opció
	támogatást ad az ilyen patchek alkalmazásához azáltal, hogy
	megkerüli ezt a hibát.

`-v`::
`--verbose`::
	Az előrehaladást a stderr-re jelenti. Alapértelmezésben csak
	az éppen alkalmazott patchről szóló üzenet kerül kiírásra. Ez
	az opció további információk jelentését okozza.

`-q`::
`--quiet`::
	Elnyomja a stderr-kimenetet. A patch állapotáról és
	előrehaladásáról szóló üzenetek nem kerülnek kiírásra.

`--recount`::
	Nem bízik a hunk-fejlécekben szereplő sorszámokban, hanem a
	patch megvizsgálásával következteti ki azokat (pl. miután a
	patchet a hunk-fejlécek megfelelő módosítása nélkül szerkesztették).

`--directory=<root>`::
	Minden fájlnév elé odateszi a(z) _<root>_-ot. Ha egy `-p`
	argumentum is meg volt adva, az az új gyökér elé illesztése
	előtt kerül alkalmazásra.
+
Például egy olyan patch, amely az `a/git-gui.sh` fájlt `b/git-gui.sh`-ra
frissíti, alkalmazható a munkakönyvtárban lévő
`modules/git-gui/git-gui.sh` fájlra a `git apply
--directory=modules/git-gui` futtatásával.

`--unsafe-paths`::
	Alapértelmezésben egy olyan patch, amely a munkaterületen
	kívülre hat (akár egy Git által vezérelt munkakönyvtárra, akár
	az aktuális munkakönyvtárra, amikor a `git apply`-t a GNU
	`patch` helyettesítőjeként használják), tévedésként (vagy
	rosszindulatú szándékként) elutasításra kerül.
+
Amikor a `git apply`-t „jobb GNU `patch`"-ként használják, a
felhasználó megadhatja a `--unsafe-paths` opciót ennek a biztonsági
ellenőrzésnek a felülbírálásához. Ennek az opciónak nincs hatása, ha
a `--index` vagy a `--cached` van használatban.

`--allow-empty`::
	Nem ad hibát az olyan patchekre, amelyek nem tartalmaznak
	diffet. Ez magában foglalja az üres patcheket és a csak
	commit-szöveget tartalmazó patcheket.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

:git-apply: 1
include::config/apply.adoc[]

SUBMODULES
----------
Ha a patch bármilyen submodule-okat érintő módosítást tartalmaz, a
`git apply` a következőképpen kezeli ezeket a módosításokat.

Ha a `--index` meg van adva (explicit vagy implicit módon), akkor a
submodule commitjainak pontosan egyezniük kell az indexszel ahhoz, hogy
a patch alkalmazható legyen. Ha bármelyik submodule checkoutolva van,
ezek a checkoutok teljesen figyelmen kívül maradnak, azaz nem
követelmény, hogy naprakészek vagy tiszták legyenek, és nem is kerülnek
frissítésre.

Ha a `--index` nincs megadva, akkor a patchben szereplő submodule
commitok figyelmen kívül maradnak, és csak a megfelelő alkönyvtár
hiánya vagy megléte kerül ellenőrzésre, és (ha lehetséges) frissítésre.

SEE ALSO
--------
linkgit:git-am[1].

GIT
---
A linkgit:git[1] csomag része
