git-reset(1)
============

NAME
----
git-reset - Set `HEAD` or the index to a known state

SYNOPSIS
--------
[synopsis]
git reset [--soft | --mixed [-N] | --hard | --merge | --keep] [-q] [<commit>]
git reset [-q] [<tree-ish>] [--] <pathspec>...
git reset [-q] [--pathspec-from-file=<file> [--pathspec-file-nul]] [<tree-ish>]
git reset (--patch | -p) [<tree-ish>] [--] [<pathspec>...]

DESCRIPTION
-----------
A `git reset` a következők egyikét teszi:

1. A `git reset [<mode>] <commit>` megváltoztatja, hogy a `HEAD` melyik
   commitra mutat. Ez lehetővé teszi különböző Git-műveletek visszavonását,
   például commit, merge, rebase és pull.
2. Amikor fájlokat vagy könyvtárakat adsz meg, vagy a `--patch` opciót adod
   át, a `git reset` frissíti a megadott fájlok stage-elt verzióját.

`git reset [<mode>] [<commit>]`::
	Az aktuális branch fejét (`HEAD`) a _<commit>_-ra állítja.
	A _<mode>_-tól függően frissíti a munkakönyvtárat és/vagy az indexet is,
	hogy megegyezzen a _<commit>_ tartalmával.
	A _<commit>_ alapértéke `HEAD`.
	A művelet előtt az `ORIG_HEAD` az aktuális branch csúcsára áll be.
+
A _<mode>_ a következők egyike kell legyen (alapértelmezés `--mixed`):
+

--
`--mixed`::
	A munkakönyvtárat változatlanul hagyja.
	Az indexet az új `HEAD`-hez igazítja, így semmi nem lesz stage-elve.
+
Ha a `-N` meg van adva, az eltávolított útvonalakat intent-to-add jelöléssel
látja el (lásd linkgit:git-add[1]).

`--soft`::
	A working tree fájljait és az indexet változatlanul hagyja.
	Például ha nincsenek stage-elt változtatásaid, használhatod a
	`git reset --soft HEAD~5; git commit` parancsot,
	hogy az utolsó 5 commitot 1 commitba vond össze. Ez akkor is működik, ha vannak
	változtatások a working tree-ben, amelyeket érintetlenül hagy, de az ilyen
	használat zavart okozhat.

`--hard`::
	Minden fájlt és könyvtárat felülír a _<commit>_-ból származó verzióval,
	és felülírhat nem követett fájlokat is. A _<commit>_-ban nem szereplő követett fájlok
	eltávolításra kerülnek, hogy a working tree megegyezzen a _<commit>_-tal.
	Az indexet az új `HEAD`-hez igazítja, így semmi nem lesz stage-elve.

`--merge`::
	Visszaállítja az indexet, és frissíti a working tree azon fájljait, amelyek
	eltérnek a _<commit>_ és a `HEAD` között, de megtartja azokat, amelyek
	eltérnek az index és a working tree között (azaz amelyekben olyan változtatások
	vannak, amelyeket nem adtak hozzá).
	Főként a nem merge-elt indexbejegyzések visszaállítására létezik, mint amilyeneket a
	`git am -3` vagy a `git switch -m` hagy hátra bizonyos helyzetekben.
	Ha egy fájlnak, amely eltér a _<commit>_ és az index között,
	nem stage-elt változtatásai vannak, a reset megszakad.

`--keep`::
	Visszaállítja az indexbejegyzéseket, és frissíti a working tree azon fájljait, amelyek
	eltérnek a _<commit>_ és a `HEAD` között.
	Ha egy fájlnak, amely eltér a _<commit>_ és a `HEAD` között, helyi
	változtatásai vannak, a reset megszakad.

`--recurse-submodules`::
`--no-recurse-submodules`::
	Amikor a working tree frissül, a `--recurse-submodules` használatával az
	összes aktív submodule working tree-je is rekurzívan visszaállításra kerül
	a szuperprojektben rögzített commit szerint, a submodule-ok `HEAD`-jét is
	leválasztva az adott commitnál.
--

`git reset [-q] [<tree-ish>] [--] <pathspec>...`::
`git reset [-q] [--pathspec-from-file=<file> [--pathspec-file-nul]] [<tree-ish>]`::
	Az összes megadott fájlra vagy könyvtárra a stage-elt verziót az adott
	commitból vagy fából származó verzióra állítja (amely alapból `HEAD`).
+
Ez azt jelenti, hogy a `git reset <pathspec>` a `git add <pathspec>`
ellentéte: unstage-eli a megadott fájl(ok)ra vagy könyvtárakra vonatkozó
összes változtatást. Ez egyenértékű a `git restore --staged <pathspec>...` paranccsal.
+
Ebben a módban a `git reset` csak az indexet frissíti (a `HEAD` vagy a working
tree fájljainak frissítése nélkül). Ha a fájlokat és az indexbejegyzéseket is
frissíteni szeretnéd, használd a linkgit:git-restore[1] parancsot.

`git reset (--patch | -p) [<tree-ish>] [--] [<pathspec>...]`::
	Interaktívan válaszd ki a változtatásokat az index és a megadott commit
	vagy fa (amely alapból `HEAD`) közötti különbségből.
	Az index a kiválasztott változtatásokkal módosul.
+
Ez azt jelenti, hogy a `git reset -p` a `git add -p` ellentéte, azaz
használhatod a változtatások szelektív unstage-elésére. Lásd a linkgit:git-add[1]
"Interaktív mód" szakaszát, hogy megtudd, hogyan kell a `--patch` opciót használni.

A három parancs közötti különbségekért lásd a "Reset, restore and revert"
szakaszt a linkgit:git[1] oldalon.


OPTIONS
-------

`-q`::
`--quiet`::
	Csendben, csak a hibákat jelentse.

`--refresh`::
`--no-refresh`::
	Frissítse az indexet egy mixed reset után. Alapból engedélyezve.

`--pathspec-from-file=<file>`::
	A pathspec a _<file>_-ban van átadva a parancssori argumentumok helyett. Ha
	a _<file>_ pontosan `-`, akkor a standard bemenet van használva. A pathspec-elemeket
	_LF_ vagy _CR_/_LF_ választja el. A pathspec-elemek idézőjelezhetők,
	ahogy az a `core.quotePath` konfigurációs változónál le van írva
	(lásd linkgit:git-config[1]). Lásd még a `--pathspec-file-nul` opciót és a
	globális `--literal-pathspecs` opciót.

`--pathspec-file-nul`::
	Csak a `--pathspec-from-file` opcióval van értelme. A pathspec-elemeket
	_NUL_ karakter választja el, és minden más karakter literálisan van
	értelmezve (beleértve a sortöréseket és az idézőjeleket).

include::diff-context-options.adoc[]

`--`::
	Ne értelmezzen több argumentumot opcióként.

`<pathspec>...`::
	Korlátozza a művelet által érintett útvonalakat.
+
További részletekért lásd a 'pathspec' bejegyzést a linkgit:gitglossary[7] oldalon.

EXAMPLES
--------

Add visszavonása::
+
------------
$ edit                                     <1>
$ git add frotz.c filfre.c
$ mailx                                    <2>
$ git reset                                <3>
$ git pull git://info.example.com/ nitfol  <4>
------------
+
<1> Boldogan dolgozol valamin, és úgy találod, hogy a változtatások
    ezekben a fájlokban rendben vannak.  Nem akarod látni őket,
    amikor `git diff`-et futtatsz, mert más fájlokon tervezel dolgozni,
    és ezeknek a fájloknak a változtatásai elvonják a figyelmet.
<2> Valaki megkér, hogy pull-olj, és a változtatások merge-elésre érdemesnek hangzanak.
<3> Azonban már beszennyezted az indexet (azaz az indexed nem
    egyezik a `HEAD` committal).  De tudod, hogy a pull, amit végre
    fogsz hajtani, nem érinti a `frotz.c` vagy `filfre.c` fájlt, ezért erre a
    két fájlra visszavonod az indexbeli változtatásokat.  A working tree-beli
    változtatásaid ott maradnak.
<4> Ezután pull-olhatsz és merge-elhetsz, a `frotz.c` és `filfre.c`
    változtatásait továbbra is a working tree-ben hagyva.

Egy commit visszavonása és újbóli elvégzése::
+
------------
$ git commit ...
$ git reset --soft HEAD^      <1>
$ edit                        <2>
$ git commit -a -c ORIG_HEAD  <3>
------------
+
<1> Ezt leggyakrabban akkor teszik, amikor eszedbe jut, hogy amit
    épp commitoltál, hiányos, vagy elgépelted a commit-üzenetet, vagy
    mindkettő.  A working tree-t úgy hagyja, ahogy a "reset" előtt volt.
<2> Végezz javításokat a working tree fájljain.
<3> A "reset" a régi headet a `.git/ORIG_HEAD`-be másolja; végezd el újra a
    commitot a napló-üzenetéből kiindulva.  Ha nem kell tovább
    szerkesztened az üzenetet, helyette megadhatod a `-C` opciót.
+
Lásd még a linkgit:git-commit[1] `--amend` opcióját.

Egy commit visszavonása, topic branchré alakítva::
+
------------
$ git branch topic/wip          <1>
$ git reset --hard HEAD~3       <2>
$ git switch topic/wip          <3>
------------
+
<1> Készítettél néhány commitot, de rájössz, hogy korai volt őket
    a `master` branchbe tenni.  Egy topic branchben szeretnéd tovább
    csiszolni őket, ezért hozz létre egy `topic/wip` branchet az
    aktuális `HEAD`-ből.
<2> Tekerd vissza a master branchet, hogy megszabadulj attól a három committól.
<3> Válts a `topic/wip` branchre, és dolgozz tovább.

Commitok végleges visszavonása::
+
------------
$ git commit ...
$ git reset --hard HEAD~3   <1>
------------
+
<1> Az utolsó három commit (`HEAD`, `HEAD^` és `HEAD~2`) rossz volt,
    és soha többé nem akarod látni őket.  *Ne* tedd ezt, ha
    ezeket a commitokat már odaadtad valaki másnak.  (Ennek
    következményeiről lásd a "RECOVERING FROM UPSTREAM REBASE" szakaszt a
    linkgit:git-rebase[1] oldalon.)

Egy merge vagy pull visszavonása::
+
------------
$ git pull                         <1>
Auto-merging nitfol
CONFLICT (content): Merge conflict in nitfol
Automatic merge failed; fix conflicts and then commit the result.
$ git reset --hard                 <2>
$ git pull . topic/branch          <3>
Updating from 41223... to 13134...
Fast-forward
$ git reset --hard ORIG_HEAD       <4>
------------
+
<1> Az upstreamből való frissítési kísérlet sok konfliktust
    eredményezett; nem álltál készen arra, hogy most sok időt tölts
    merge-eléssel, ezért úgy döntesz, hogy ezt később teszed meg.
<2> A "pull" nem készített merge commitot, ezért a `git reset --hard`,
    amely a `git reset --hard HEAD` szinonimája, kitakarítja a rendetlenséget
    az indexfájlból és a working tree-ből.
<3> Merge-elj egy topic branchet az aktuális branchbe, ami
    fast-forwardot eredményezett.
<4> De úgy döntöttél, hogy a topic branch még nem áll készen a
    nyilvános felhasználásra.  A "pull" vagy "merge" mindig az aktuális branch
    eredeti csúcsát hagyja az `ORIG_HEAD`-ben, így a hard reset rá
    visszaállítja az indexfájlt és a working tree-t abba az állapotba,
    és a branch csúcsát is arra a commitra állítja.

Egy merge vagy pull visszavonása egy piszkos working tree-n belül::
+
------------
$ git pull                         <1>
Auto-merging nitfol
Merge made by recursive.
 nitfol                |   20 +++++----
 ...
$ git reset --merge ORIG_HEAD      <2>
------------
+
<1> Még akkor is, ha lehetnek helyi módosításaid a
    working tree-ben, nyugodtan mondhatod, hogy `git pull`, ha tudod,
    hogy a másik branch változtatása nem fedi át
    azokat.
<2> A merge eredményének megvizsgálása után úgy találhatod,
    hogy a másik branch változtatása nem kielégítő.  A
    `git reset --hard ORIG_HEAD` futtatása lehetővé teszi, hogy visszatérj oda, ahol
    voltál, de eldobja a helyi változtatásaidat, amit nem
    akarsz.  A `git reset --merge` megtartja a helyi változtatásaidat.


Megszakított munkafolyamat::
+
Tegyük fel, hogy egy sürgős javítási kérés szakít félbe, miközben
egy nagy változtatás közepén vagy.  A working tree
fájljaid még nincsenek olyan állapotban, hogy commitolni lehessen őket, de
át kell jutnod a másik branchre egy gyors bugfix miatt.
+
------------
$ git switch feature  ;# you were working in "feature" branch and
$ work work work      ;# got interrupted
$ git commit -a -m "snapshot WIP"                 <1>
$ git switch master
$ fix fix fix
$ git commit ;# commit with real log
$ git switch feature
$ git reset --soft HEAD^ ;# go back to WIP state  <2>
$ git reset                                       <3>
------------
+
<1> Ez a commit el fog tűnni, így egy eldobható napló-üzenet is megfelel.
<2> Ez eltávolítja a 'WIP' commitot a commit-történetből, és
    a working tree-t abba az állapotba állítja, amelyben közvetlenül a pillanatkép elkészítése előtt volt.
<3> Ezen a ponton az indexfájl még tartalmazza az összes WIP-változtatást, amelyet
    'snapshot WIP'-ként commitoltál.  Ez frissíti az indexet, hogy a
    WIP-fájljaidat nem commitoltként mutassa.
+
Lásd még: linkgit:git-stash[1].

Egyetlen fájl visszaállítása az indexben::
+
Tegyük fel, hogy hozzáadtál egy fájlt az indexedhez, de később úgy döntesz, hogy
nem akarod a commitodba tenni. A git reset segítségével eltávolíthatod a fájlt
az indexből, miközben megtartod a változtatásaidat.
+
------------
$ git reset -- frotz.c                      <1>
$ git commit -m "Commit files in index"     <2>
$ git add frotz.c                           <3>
------------
+
<1> Ez eltávolítja a fájlt az indexből, miközben a
    munkakönyvtárban megtartja.
<2> Ez commitolja az index összes többi változtatását.
<3> Ismét hozzáadja a fájlt az indexhez.

Változtatások megtartása a working tree-ben, miközben néhány korábbi commitot eldobsz::
+
Tegyük fel, hogy dolgozol valamin, commitolod, majd dolgozol
még egy kicsit, de most úgy gondolod, hogy amit a
working tree-dben van, annak egy másik branchben kellene lennie, aminek semmi köze ahhoz,
amit korábban commitoltál. Elindíthatsz egy új branchet, és
visszaállíthatod, miközben megtartod a working tree-beli változtatásokat.
+
------------
$ git tag start
$ git switch -c branch1
$ edit
$ git commit ...                            <1>
$ edit
$ git switch -c branch2                     <2>
$ git reset --keep start                    <3>
------------
+
<1> Ez commitolja az első szerkesztéseidet a `branch1`-ben.
<2> Ideális esetben rájöhettél volna, hogy a korábbi
    commit nem tartozik az új topichoz, amikor létrehoztad a `branch2`-t, és arra
    váltottál (azaz `git switch -c branch2 start`), de senki sem
    tökéletes.
<3> De használhatod a `reset --keep` parancsot a nem kívánt commit eltávolítására,
    miután a `branch2`-re váltottál.

Egy commit szétbontása commitok sorozatává::
+
Tegyük fel, hogy sok logikailag különálló változtatást hoztál létre, és együtt
commitoltad őket. Aztán később úgy döntesz, hogy jobb lenne, ha minden
logikai darabhoz saját commit tartozna. A git reset segítségével visszatekerheted
a történetet a helyi fájljaid tartalmának megváltoztatása nélkül, majd egymás után
használhatod a `git add -p` parancsot, hogy interaktívan kiválaszd, mely hunkok kerüljenek az egyes commitokba,
a `git commit -c` parancsot használva a commit-üzenet előre kitöltésére.
+
------------
$ git reset -N HEAD^                        <1>
$ git add -p                                <2>
$ git diff --cached                         <3>
$ git commit -c HEAD@{1}                    <4>
...                                         <5>
$ git add ...                               <6>
$ git diff --cached                         <7>
$ git commit ...                            <8>
------------
+
<1> Először állítsd vissza a történetet egy committal, hogy eltávolítsuk az eredeti
    commitot, de a working tree-ben hagyjuk az összes változtatást. A `-N` biztosítja,
    hogy a `HEAD`-del hozzáadott új fájlok továbbra is meg legyenek jelölve, hogy a `git add -p`
    megtalálja őket.
<2> Ezután interaktívan kiválasztjuk a hozzáadandó diff-hunkokat a `git add -p`
    eszközzel. Ez sorban rákérdez minden diff-hunkra, és
    használhatsz egyszerű parancsokat, például "yes, include this", "No don't include this",
    vagy akár a nagyon erős "edit" eszközt.
<3> Miután elégedett vagy a beemelni kívánt hunkokkal, ellenőrizned kell, mi lett
    előkészítve az első commithoz a `git diff --cached` használatával. Ez
    megmutatja az összes változtatást, amely az indexbe került, és
    commitolásra készül.
<4> Ezután commitold az indexben tárolt változtatásokat. A `-c` opció megadja, hogy
    a commit-üzenet az eredeti üzenetből legyen előre kitöltve, amellyel az
    első commitban indultál. Ez hasznos, hogy ne kelljen újra begépelni. A
    `HEAD@{1}` egy speciális jelölés arra a commitra, amelyen a `HEAD`
    az eredeti reset commit előtt volt (1 változtatással ezelőtt).
    További részletekért lásd a linkgit:git-reflog[1] oldalt. Bármely más
    érvényes commit-referenciát is használhatsz.
<5> A 2-4. lépéseket többször megismételheted, hogy az eredeti kódot
    tetszőleges számú commitra bontsd.
<6> Most már sok változtatást kiszedtél a saját commitjaikba, és lehet, hogy
    már nem használod a `git add` patch módját, hogy kiválaszd az összes megmaradt,
    nem commitolt változtatást.
<7> Ismét ellenőrizd, hogy beemelted-e, amit szerettél volna. Érdemes lehet
    azt is ellenőrizni, hogy a git diff nem mutat-e további, később
    commitolandó változtatásokat.
<8> És végül hozd létre a végső commitot.


DISCUSSION
----------

Az alábbi táblák megmutatják, mi történik a következő futtatásakor:

----------
git reset --option target
----------

hogy a `HEAD`-et egy másik commitra (`target`) állítsuk vissza a különböző
reset-opciókkal a fájlok állapotától függően.

Ezekben a táblákban az `A`, `B`, `C` és `D` egy fájl néhány különböző
állapota. Például az első tábla első sora azt jelenti, hogy ha egy
fájl `A` állapotban van a working tree-ben, `B` állapotban az indexben,
`C` állapotban a `HEAD`-ben és `D` állapotban a targetben, akkor a `git reset --soft
target` a fájlt a working tree-ben `A` állapotban, az indexben pedig
`B` állapotban hagyja.  Visszaállítja (azaz elmozdítja) a `HEAD`-et (azaz az
aktuális branch csúcsát, ha éppen egy branchen vagy) a `target`-re (amelyben a fájl
`D` állapotban van).

....
working index HEAD target         working index HEAD
----------------------------------------------------
 A       B     C    D     --soft   A       B     D
			  --mixed  A       D     D
			  --hard   D       D     D
			  --merge (disallowed)
			  --keep  (disallowed)
....

....
working index HEAD target         working index HEAD
----------------------------------------------------
 A       B     C    C     --soft   A       B     C
			  --mixed  A       C     C
			  --hard   C       C     C
			  --merge (disallowed)
			  --keep   A       C     C
....

....
working index HEAD target         working index HEAD
----------------------------------------------------
 B       B     C    D     --soft   B       B     D
			  --mixed  B       D     D
			  --hard   D       D     D
			  --merge  D       D     D
			  --keep  (disallowed)
....

....
working index HEAD target         working index HEAD
----------------------------------------------------
 B       B     C    C     --soft   B       B     C
			  --mixed  B       C     C
			  --hard   C       C     C
			  --merge  C       C     C
			  --keep   B       C     C
....

....
working index HEAD target         working index HEAD
----------------------------------------------------
 B       C     C    D     --soft   B       C     D
			  --mixed  B       D     D
			  --hard   D       D     D
			  --merge (disallowed)
			  --keep  (disallowed)
....

....
working index HEAD target         working index HEAD
----------------------------------------------------
 B       C     C    C     --soft   B       C     C
			  --mixed  B       C     C
			  --hard   C       C     C
			  --merge  B       C     C
			  --keep   B       C     C
....

A `git reset --merge` arra való, hogy egy konfliktusos merge-ből visszaállj.
Bármely merge-jellegű művelet garantálja, hogy a merge-ben érintett working tree
fájlnak nincs helyi változtatása az indexhez képest, mielőtt elindul, és hogy
az eredményt kiírja a working tree-be. Így ha valamilyen eltérést látunk
az index és a target között, valamint az index és a working tree között is,
akkor ez azt jelenti, hogy nem egy olyan állapotból állunk vissza, amelyet egy
merge-jellegű művelet hagyott hátra, miután konfliktussal elbukott. Ezért nem
engedélyezzük a `--merge` opciót ebben az esetben.

A `git reset --keep` arra való, hogy az aktuális branch utolsó
commitjai közül eltávolíts néhányat, miközben megtartod a working
tree-beli változtatásokat. Ha konfliktusok lehetnének az eltávolítani kívánt
commit változtatásai és a megtartani kívánt working tree-beli változtatások között,
a reset nem engedélyezett. Ezért nem engedélyezett, ha egyszerre vannak
változtatások a working tree és a `HEAD` között, valamint a `HEAD` és a
target között. A biztonság kedvéért akkor is nem engedélyezett, ha vannak nem merge-elt
bejegyzések.

Az alábbi táblák megmutatják, mi történik, ha vannak nem merge-elt
bejegyzések:

....
working index HEAD target         working index HEAD
----------------------------------------------------
 X       U     A    B     --soft  (disallowed)
			  --mixed  X       B     B
			  --hard   B       B     B
			  --merge  B       B     B
			  --keep  (disallowed)
....

....
working index HEAD target         working index HEAD
----------------------------------------------------
 X       U     A    A     --soft  (disallowed)
			  --mixed  X       A     A
			  --hard   A       A     A
			  --merge  A       A     A
			  --keep  (disallowed)
....

Az `X` bármilyen állapotot jelent, az `U` pedig egy nem merge-elt indexet.

GIT
---
A linkgit:git[1] csomag része
