git-fsck(1)
===========

NAME
----
git-fsck - Az adatbázisban lévő objektumok összekapcsoltságának és érvényességének ellenőrzése


SYNOPSIS
--------
[verse]
'git fsck' [--tags] [--root] [--unreachable] [--cache] [--no-reflogs]
	 [--[no-]full] [--strict] [--verbose] [--lost-found]
	 [--[no-]dangling] [--[no-]progress] [--connectivity-only]
	 [--[no-]name-objects] [--[no-]references] [<object>...]

DESCRIPTION
-----------
Ellenőrzi az adatbázisban lévő objektumok összekapcsoltságát és érvényességét.

OPTIONS
-------
<object>::
	Egy objektum, amelyet az elérhetetlenség-nyomkövetés fejeként kell kezelni.
+
Ha nincsenek objektumok megadva, a 'git fsck' alapból az indexfájlt,
a `refs` névtérben lévő összes SHA-1 hivatkozást és az összes reflogot
(hacsak a --no-reflogs nincs megadva) használja fejként.

--unreachable::
	Azon objektumok kiírása, amelyek léteznek, de egyik referencia-csomópontból
	sem érhetők el.

--dangling::
--no-dangling::
	Azon objektumok kiírása, amelyek léteznek, de soha nincsenek 'közvetlenül' használva (alapértelmezés).
	A `--no-dangling` használható arra, hogy ez az információ kimaradjon a kimenetből.

--root::
	Gyökércsomópontok jelentése.

--tags::
	Tagek jelentése.

--cache::
	Az indexben rögzített minden objektum figyelembevétele az
	elérhetetlenség-nyomkövetés fejcsomópontjaként is.

--no-reflogs::
	Ne tekintsd elérhetőnek azokat a commitokat, amelyekre csak egy
	reflog-bejegyzés hivatkozik.  Ez az opció csak arra való, hogy
	olyan commitokat keress, amelyek korábban egy refben voltak, de
	most már nincsenek, viszont a hozzá tartozó reflogban még igen.

--full::
	Ne csak a GIT_OBJECT_DIRECTORY ($GIT_DIR/objects) objektumait
	ellenőrizd, hanem a GIT_ALTERNATE_OBJECT_DIRECTORIES-ban vagy a
	$GIT_DIR/objects/info/alternates-ban felsorolt alternatív
	objektumkészletekben találhatókat is, valamint a
	$GIT_DIR/objects/pack-ban és az alternatív objektumkészletek
	megfelelő pack alkönyvtáraiban található csomagolt
	Git-archívumokat.  Ez most már az alapértelmezés; kikapcsolhatod
	a --no-full opcióval.

--connectivity-only::
	Csak az elérhető objektumok összekapcsoltságát ellenőrzi, megbizonyosodva
	arról, hogy egy elérhető tag, commit vagy fa által hivatkozott minden
	objektum jelen van. Ez felgyorsítja a műveletet azzal, hogy teljesen
	elkerüli a blobok olvasását (bár azt továbbra is ellenőrzi, hogy a
	hivatkozott blobok léteznek). Ez felderíti a commitok és fák sérülését,
	de nem végez semmilyen szemantikai ellenőrzést (pl. formátumhibákra).
	A blob objektumok sérülését egyáltalán nem deríti fel.
+
Az elérhetetlen tageket, commitokat és fákat is eléri, hogy megtalálja
a lógó előzményszegmensek csúcsait. Használd a `--no-dangling`-et, ha nem
érdekel ez a kimenet, és tovább akarod gyorsítani.

--strict::
	Szigorúbb ellenőrzés bekapcsolása, nevezetesen a g+w bittel
	rögzített fájlmódok elkapására, amelyeket a Git régebbi verziói
	hoztak létre.  A meglévő repository-k, köztük a Linux kernel, maga
	a Git és a sparse repository is tartalmaznak olyan régi objektumokat,
	amelyek kiváltják ezt az ellenőrzést, de az új projekteknél ajánlott
	ezzel a kapcsolóval ellenőrizni.

--verbose::
	Legyen bőbeszédű.

--lost-found::
	A lógó objektumok kiírása a .git/lost-found/commit/ vagy a
	.git/lost-found/other/ könyvtárba, típustól függően.  Ha az objektum
	egy blob, akkor a tartalma kerül a fájlba, nem pedig az
	objektumneve.

--name-objects::
	Az elérhető objektumok neveinek megjelenítésekor a SHA-1 mellett
	jeleníts meg egy nevet is, amely leírja, *hogyan* érhetők el, a
	linkgit:git-rev-parse[1]-gyel kompatibilis módon, pl.
	`HEAD@{1234567890}~25^2:src/`.

--progress::
--no-progress::
	A folyamatállapot alapból a standard hibakimeneten jelenik meg,
	amikor az egy terminálhoz van kapcsolva, hacsak a --no-progress
	vagy a --verbose nincs megadva. A --progress akkor is
	kikényszeríti a folyamatállapotot, ha a standard hibakimenet nem
	terminálra irányul.

--references::
--no-references::
	Szabályozza, hogy a 'git refs verify' segítségével ellenőrizze-e
	a referenciák adatbázisának konzisztenciáját. Részletekért lásd a
	linkgit:git-refs[1] oldalt. Az alapértelmezés a referenciák
	adatbázisának ellenőrzése.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/fsck.adoc[]

DISCUSSION
----------

A git-fsck teszteli a SHA-1-et és az objektumok általános épségét, és
teljes követést végez az ebből adódó elérhetőségről és minden másról.
Kiírja az általa talált összes sérülést (hiányzó vagy hibás objektumok),
és ha a `--unreachable` kapcsolót használod, kiírja azokat az
objektumokat is, amelyek léteznek, de egyik megadott fejcsomópontból
(vagy a fent említett alapértelmezett halmazból) sem érhetők el.

A sérült objektumokat biztonsági mentésekben vagy más archívumokban
kell megtalálnod (azaz egyszerűen eltávolíthatod őket, és 'rsync'-elhetsz
egy másik oldallal abban a reményben, hogy másnál megvan az az objektum,
amelyik nálad megsérült).

Ha a core.commitGraph értéke true, a commit-graph fájlt is megvizsgálja a
'git commit-graph verify' segítségével. Lásd a linkgit:git-commit-graph[1] oldalt.

[[_extracted_diagnostics]]
Kinyert diagnosztika
--------------------

unreachable <type> <object>::
	A <type> típusú <object> objektumra valójában sem közvetlenül,
	sem közvetve nem hivatkozik egyik látott fa vagy commit sem. Ez
	jelentheti azt, hogy van egy másik gyökércsomópont, amelyet nem
	adsz meg, vagy azt, hogy a fa sérült. Ha nem hagytál ki
	gyökércsomópontot, akkor akár törölheted is az elérhetetlen
	csomópontokat, mivel nem használhatók.

missing <type> <object>::
	A <type> típusú <object> objektumra hivatkoznak, de nincs jelen
	az adatbázisban.

dangling <type> <object>::
	A <type> típusú <object> objektum jelen van az adatbázisban, de
	soha nincs 'közvetlenül' használva. Egy lógó commit lehet
	gyökércsomópont.

hash mismatch <object>::
	Az adatbázisban van egy objektum, amelynek hashe nem egyezik az
	objektumadatbázis értékével.
	Ez komoly adatintegritási problémára utal.


FSCK MESSAGES
-------------

Az alábbi felsorolás a `git fsck` által felderített hibatípusokat és
azok jelentését tartalmazza, az alapértelmezett súlyosságukkal.  A hiba
súlyossága – a "(FATAL)"-ként megjelöltek kivételével – a megfelelő
`fsck.<msg-id>` konfigurációs változó beállításával módosítható.

include::fsck-msgids.adoc[]


[[_environment_variables]]
Környezeti változók
-------------------

GIT_OBJECT_DIRECTORY::
	az objektumadatbázis gyökerének megadására szolgál (általában $GIT_DIR/objects)

GIT_INDEX_FILE::
	az index indexfájljának megadására szolgál

GIT_ALTERNATE_OBJECT_DIRECTORIES::
	további objektumadatbázis-gyökerek megadására szolgál (általában nincs beállítva)

GIT
---
A linkgit:git[1] csomag része
