git-fetch-pack(1)
=================

NAME
----
git-fetch-pack - Hiányzó objektumok fogadása egy másik repository-ból


SYNOPSIS
--------
[verse]
'git fetch-pack' [--all] [--quiet|-q] [--keep|-k] [--thin] [--include-tag]
	[--upload-pack=<git-upload-pack>]
	[--depth=<n>] [--no-progress]
	[-v] <repository> [<refs>...]

DESCRIPTION
-----------
Rendszerint inkább a 'git fetch'-et érdemes használni, amely ennek
a parancsnak egy magasabb szintű burkolója.

Meghívja a 'git-upload-pack'-et egy esetleg távoli repository-n, és
megkéri, hogy küldje el az ebből a repository-ból hiányzó objektumokat
a megnevezett head-ek frissítéséhez. A helyileg elérhető commitok
listáját a helyi refs/ hierarchia átvizsgálásával állapítja meg, és
elküldi a másik végen futó 'git-upload-pack'-nek.

Ez a parancs a teljes letöltésre fajul a kért refek beszerzéséhez a
távoli oldalról, ha a helyi oldalnak nincs közös ős-commitja.


OPTIONS
-------
--all::
	Az összes remote ref lekérése.

--stdin::
	A refek listájának bekérése a stdin-ről, soronként egy.
	Ha a parancssorban ezenfelül is meg vannak adva refek, akkor
	a stdin-ről érkezők a parancssoriak után kerülnek feldolgozásra.
+
Ha a `--stateless-rpc` is meg van adva ezzel az opcióval együtt, akkor
a refek listájának csomagformátumban (pkt-line) kell lennie. Minden
refnek külön csomagban kell lennie, és a listát egy flush csomagnak
kell zárnia.

-q::
--quiet::
	A `-q` kapcsoló átadása a 'git unpack-objects'-nek; ettől a
	klónozási folyamat kevésbé lesz bőbeszédű.

-k::
--keep::
	Ne hívja meg a 'git unpack-objects'-et a fogadott adatokon,
	hanem hozzon létre belőle egyetlen packfile-t, és tárolja azt
	az objektumadatbázisban. Ha kétszer van megadva, a pack zárolva
	lesz az újracsomagolással szemben.

--thin::
	Egy "vékony" (thin) pack lekérése, amely a hálózati forgalom
	csökkentése érdekében a pack-ben nem szereplő objektumokra
	alapozva delta formában rögzíti az objektumokat.

--include-tag::
	Ha a távoli oldal támogatja, az annotált tag objektumok
	ugyanazon a kapcsolaton keresztül kerülnek letöltésre, mint a
	többi objektum, ha a tag által hivatkozott objektum is letöltésre
	kerül. A hívónak egyébként magának kell megállapítania, mely
	tageket tette elérhetővé ez az opció.

--upload-pack=<git-upload-pack>::
	Ezzel adható meg a 'git-upload-pack' elérési útja a távoli
	oldalon, ha az nem található meg a $PATH-adon.
	Az sshd-telepítések figyelmen kívül hagyják a felhasználó
	login shell-jeihez tartozó környezet-beállító szkriptjeit
	(pl. .bash_profile), így a saját telepítésű git-ed lehet, hogy
	nem található meg a rendszer alapértelmezett $PATH-ján. Egy másik
	javasolt megoldás a $PATH beállítása a ".bashrc"-ben, de ez a
	kapcsoló azoknak szól, akik nem akarják vállalni egy minden
	egyes nem-interaktív shellnél lefutó terjedelmes .bashrc
	költségét (ők a beállítások nagy részét a .bash_profile-ban végzik).

--exec=<git-upload-pack>::
	Ugyanaz, mint a --upload-pack=<git-upload-pack>.

--depth=<n>::
	A letöltés korlátozása a legfeljebb n hosszú ős-láncokra.
	A 'git-upload-pack' a speciális 2147483647 mélységet
	végtelenként kezeli, még akkor is, ha van ilyen hosszú ős-lánc.

--shallow-since=<date>::
	Egy sekély (shallow) repository előzményeinek mélyítése vagy
	rövidítése úgy, hogy az tartalmazzon minden, a <date> után
	elérhető commitot.

--shallow-exclude=<ref>::
	Egy sekély (shallow) repository előzményeinek mélyítése vagy
	rövidítése úgy, hogy az kizárja a megadott remote branch-ről
	vagy tagről elérhető commitokat. Ez az opció többször is
	megadható.

--deepen-relative::
	A --depth argumentum a jelenlegi shallow-határtól számított
	commitok számát adja meg, nem az egyes remote branch-ek
	előzményeinek csúcsától.

--refetch::
	Kihagyja a commitok szerverrel való egyeztetését annak
	érdekében, hogy minden illeszkedő objektumot letöltsön. Egy új
	partial clone blob/tree szűrő újbóli alkalmazásához használatos.

--no-progress::
	Ne mutassa a folyamatjelzőt.

--check-self-contained-and-connected::
	"connectivity-ok" kiírása, ha a fogadott pack önmagában
	teljes és összefüggő.

-v::
	Bőbeszédű futás.

<repository>::
	A távoli repository URL-je.

<refs>...::
	A frissítéshez használandó remote head-ek. Ez a $GIT_DIR-hez
	viszonyítva értendő (pl. "HEAD", "refs/heads/master"). Ha nincs
	megadva, a távoli oldal összes head-jéről történik a frissítés.
+
Ha a remote engedélyezte az `uploadpack.allowTipSHA1InWant`,
`uploadpack.allowReachableSHA1InWant` vagy `uploadpack.allowAnySHA1InWant`
opciókat, ezek alternatívaként a remote-on jelen lévő, 40 hexa
karakteres sha1-ek is lehetnek.

SEE ALSO
--------
linkgit:git-fetch[1]

GIT
---
A linkgit:git[1] csomag része
