git-history(1)
==============

NAME
----
git-history - KÍSÉRLETI: Előzmény átírása

SYNOPSIS
--------
[synopsis]
git history drop <commit> [--dry-run] [--update-refs=(branches|head)] [--empty=(drop|keep|abort)]
git history fixup <commit> [--dry-run] [--update-refs=(branches|head)] [--reedit-message] [--empty=(drop|keep|abort)]
git history reword <commit> [--dry-run] [--update-refs=(branches|head)]
git history split <commit> [--dry-run] [--update-refs=(branches|head)] [--] [<pathspec>...]

DESCRIPTION
-----------

Az előzmény átírása az előzményben lévő konkrét commitok átrendezésével
vagy módosításával.

EZ A PARANCS KÍSÉRLETI. A VISELKEDÉSE MEGVÁLTOZHAT.

Ez a parancs rokon a linkgit:git-rebase[1]-gyel abban, hogy mindkét parancs
használható előzmény átírására. Van azonban néhány nagy különbség:

* A linkgit:git-history[1] legtöbb alparancsa működik bare repositoryban,
  mivel nem kell megérinteniük sem az indexet, sem a worktree-t. A `fixup`
  alparancs ez alól kivétel, mivel a stage-elt változtatásokat az indexből
  olvassa.
* A linkgit:git-history[1] jelenleg nem futtat semmilyen linkgit:githooks[5]-ot.
  Ez a jövőben megváltozhat.
* A linkgit:git-history[1] alapértelmezés szerint frissíti az összes olyan
  branchet, amely az eredeti commit leszármazottja, hogy az átírt commitra
  mutasson.

Összességében a linkgit:git-history[1] célja, hogy határozottabb módot adjon
a commit-előzményed módosítására, amelyet általánosságban egyszerűbb
használni a linkgit:git-rebase[1]-hez képest.

Használd a linkgit:git-rebase[1]-et, ha commitok egy tartományát egy másik
alapra szeretnéd újra alkalmazni, vagy az interaktív rebase-t, ha commitok
egy tartományát egyszerre szeretnéd szerkeszteni.

LIMITATIONS
-----------

Ez a parancs (még) nem működik olyan előzményekkel, amelyek merge-eket
tartalmaznak. Helyette a linkgit:git-rebase[1]-et kell használnod a
`--rebase-merges` kapcsolóval.

Továbbá a parancs nem támogat olyan műveleteket, amelyek merge-konfliktust
eredményezhetnek. Ez a korlátozás szándékos, mivel az előzmény-átírások nem
állapottartó műveleteknek készültek. A korlátozás feloldható, ha (amennyiben)
a Git megtanulja az elsőrangú konfliktusokat.

A `fixup` `--empty=drop`-pal való használatakor a gyökércommit eldobása még
nem támogatott. Hasonlóképpen a `drop` nem tudja eltávolítani a
gyökércommitot vagy egy merge-commitot.

COMMANDS
--------

A következő parancsok érhetők el az előzmény különböző módokon való
átírásához:

`drop <commit>`::
	A megadott commit eltávolítása az előzményből. A commit összes
	leszármazottja közvetlenül a szülőjére kerül újrajátszásra.
+
A gyökércommit nem dobható el, mivel ez olyan határesetekhez vezethet, ahol
a refek végül commit nélkül maradnak. A merge-commitok szintén nem
dobhatók el; lásd LIMITATIONS.
+
Ha a `HEAD` egy átírandó commitra mutat, az index és a munkakönyvtár
frissül, hogy megegyezzen az új `HEAD`-del. A parancs megszakad, mielőtt
bármely referencia frissülne, arra az esetre, ha helyi módosítások
íródnának felül.
+
Ha bármelyik leszármazott újrajátszása konfliktust eredményezne, a parancs
hibával megszakad.

`fixup <commit>`::
	A jelenleg stage-elt változtatások alkalmazása a megadott commitra. Ez
	jellegében hasonló a `git commit --fixup=<commit>`-hoz, amelyet egy
	`git rebase --autosquash <commit>~` követ. A változtatások a
	cél-commitra egy háromutas merge végrehajtásával kerülnek alkalmazásra
	a HEAD commit, a cél-commit és a stage-elt változtatásokból generált
	fa között.
+
A cél-commit commit-üzenete és szerzősége alapértelmezés szerint megmarad,
hacsak nem adod meg a `--reedit-message`-t.
+
Ha a stage-elt változtatások alkalmazása konfliktust eredményezne, a
parancs hibával megszakad. Az eredeti commit összes leszármazott branché
frissül, hogy az átírt előzményre mutasson.

`reword <commit>`::
	A megadott commit commit-üzenetének átírása. A commit minden más
	részlete változatlan marad. Ez a parancs elindít egy szerkesztőt a
	commit aktuális üzenetével.

`split <commit> [--] [<pathspec>...]`::
	A <commit> interaktív szétvágása két commitra az általa bevezetett
	hunkok kiválasztásával, amelyek az új leválasztott commitba kerülnek.
	Ezek a hunkok ezután egy új commitba íródnak, amely az előző commit
	szülőjévé válik. Az eredeti commit érintetlen marad, kivéve hogy a
	szülője az újonnan leválasztott commit lesz.
+
A szétvágott commitok commit-üzeneteit a beállított szerkesztő
elindításával kéri be. A commit szerzősége megegyezik az eredeti commitéval.
+
Ha meg van adva, a _<pathspec>_ használható annak korlátozására, mely
változtatások váljanak le az eredeti commitból. Az egyik pathspecre sem
illeszkedő fájlok az eredeti commit részei maradnak. További részletekért
lásd a 'pathspec' bejegyzést a linkgit:gitglossary[7]-ben.
+
Érvénytelen az összes hunkot kiválasztani, vagy egyet sem, mivel ez azt
eredményezné, hogy az egyik commit üressé válik.

OPTIONS
-------

`--dry-run`::
	Ne frissítsen semmilyen referenciát, hanem írja ki a ref-frissítéseket
	olyan formátumban, amelyet a linkgit:git-update-ref[1] fel tud
	dolgozni. A szükséges új objektumok beíródnak a repositoryba, így
	ezeknek a kiírt ref-frissítéseknek az alkalmazása általában
	biztonságos.

`--reedit-message`::
	Szerkesztő megnyitása a cél-commit üzenetének módosításához.

`--empty=(drop|keep|abort)`::
	Szabályozza, mi történjen, amikor egy commit a fixup eredményeként
	üressé válik. Ez két helyzetben fordulhat elő:
+
--
* Maga a fixup célja válik üressé, mert a stage-elt változtatások pontosan
  kioltják az adott commit által bevezetett összes változtatást.

* Egy leszármazott commit válik üressé az újrajátszás során, mert ugyanazt a
  változtatást vezette be, amelyet épp most fixupoltak be egy ősbe.
--
+
A `drop` (az alapértelmezett) esetén az üres commitok eltávolításra kerülnek
az átírt előzményből. Egy eldobott cél-commit leszármazottai közvetlenül a
cél szülőjére kerülnek újrajátszásra. Vedd figyelembe, hogy a gyökércommit
eldobása nem támogatott; lásd LIMITATIONS.
+
A `keep` esetén az üres commitok változatlanul megmaradnak az átírt
előzményben.
+
Az `abort` esetén a parancs hibával leáll, ha bármely commit üressé válna.

`--update-refs=(branches|head)`::
	Szabályozza, mely referenciákat frissítse a parancs, ha egyáltalán. A
	`branches` esetén minden olyan lokális branch átíródik, amely az
	eredeti commit leszármazottjaira mutat. A `head` esetén csak az
	aktuális `HEAD` referencia íródik át. Az alapértelmezése `branches`.

EXAMPLES
--------

[[_fixup_a_commit]]
Commit fixupolása
~~~~~~~~~~~~~~~~~

----------
$ git log --oneline --stat
abc1234 (HEAD -> main) third
 third.txt | 1 +
def5678 second
 second.txt | 1 +
ghi9012 first
 first.txt | 1 +

$ echo "change" >>unrelated.txt
$ git add unrelated.txt
$ git history fixup ghi9012

$ git log --oneline --stat
jkl3456 (HEAD -> main) third
 third.txt | 1 +
mno7890 second
 second.txt | 1 +
pqr1234 first
 first.txt     | 1 +
 unrelated.txt | 1 +
----------

Az `unrelated.txt` stage-elt hozzáadása bekerült a `first` commitba. Az
összes leszármazott commit újra lett játszva az átírt előzmény tetején.

[[_drop_a_commit]]
Commit eldobása
~~~~~~~~~~~~~~~

----------
$ git log --oneline
abc1234 (HEAD -> main) third
def5678 second
ghi9012 first

$ git history drop 'main^{/second}'

$ git log --oneline
jkl3456 (HEAD -> main) third
ghi9012 first
----------

A `second` commit eltávolításra került az előzményből, és a `third`
közvetlenül a `first` tetejére lett újrajátszva. Az összes branch, amely az
eldobott commitra mutatott, a szülőjére lett mozgatva.

[[_split_a_commit]]
Commit szétvágása
~~~~~~~~~~~~~~~~~

----------
$ git log --stat --oneline
3f81232 (HEAD -> main) original
 bar | 1 +
 foo | 1 +
 2 files changed, 2 insertions(+)

$ git history split HEAD
diff --git a/bar b/bar
new file mode 100644
index 0000000..5716ca5
--- /dev/null
+++ b/bar
@@ -0,0 +1 @@
+bar
(1/1) Stage addition [y,n,q,a,d,p,?]? y

diff --git a/foo b/foo
new file mode 100644
index 0000000..257cc56
--- /dev/null
+++ b/foo
@@ -0,0 +1 @@
+foo
(1/1) Stage addition [y,n,q,a,d,p,?]? n

$ git log --stat --oneline
7cebe64 (HEAD -> main) original
 foo | 1 +
 1 file changed, 1 insertion(+)
d1582f3 split-out commit
 bar | 1 +
 1 file changed, 1 insertion(+)
----------

GIT
---
A linkgit:git[1] csomag része
