git-describe(1)
===============

NAME
----
git-describe - Ember által olvasható nevet ad egy objektumnak egy elérhető referencia alapján

SYNOPSIS
--------
[synopsis]
git describe [--all] [--tags] [--contains] [--abbrev=<n>] [<commit-ish>...]
git describe [--all] [--tags] [--contains] [--abbrev=<n>] --dirty[=<mark>]
git describe <blob>

DESCRIPTION
-----------
A parancs megkeresi a legutóbbi olyan taget, amely elérhető egy
commitból. Ha a tag a commitra mutat, akkor csak a tag jelenik meg.
Egyébként a tag nevéhez hozzáfűzi a tagelt objektum feletti további
commitok számát és a legutóbbi commit rövidített objektumnevét. Az
eredmény egy "ember által olvasható" objektumnév, amely más git
parancsoknak is átadható a commit azonosítására.

Alapértelmezetten (a `--all` vagy a `--tags` nélkül) a `git describe`
csak az annotált tageket mutatja. Az annotált tagek létrehozásáról
bővebb információért lásd a linkgit:git-tag[1] `-a` és `-s`
opcióit.

Ha a megadott objektum egy blobra hivatkozik, `<commit-ish>:<path>`
alakban lesz leírva, úgy, hogy a blob megtalálható legyen az
_<path>_-on az _<commit-ish>_-ben, amely maga azt az első commitot
írja le, amelyben ez a blob megjelenik egy `HEAD`-től visszafelé
végzett revízióbejárás során.

OPTIONS
-------
`<commit-ish>...`::
	A leírandó commit-ish objektumnevek. Elhagyás esetén az
	alapértelmezés `HEAD`.

`--dirty[=<mark>]`::
`--broken[=<mark>]`::
	A munkakönyvtár állapotát írja le. Ha a munkakönyvtár megegyezik
	a `HEAD`-del, a kimenet ugyanaz, mint a `git describe HEAD`-é.
	Ha a munkakönyvtárban lokális módosítás van, a `-dirty` kerül
	hozzáfűzésre. Ha egy repository sérült, és a Git nem tudja
	megállapítani, hogy van-e lokális módosítás, a Git hibával
	kilép, hacsak nincs megadva a `--broken`, amely ehelyett a
	`-broken` toldalékot fűzi hozzá.

`--all`::
	Ahelyett, hogy csak az annotált tageket használná, bármely,
	a `refs/` névtérben található referenciát használ. Ez az
	opció lehetővé teszi bármely ismert branch, remote-tracking
	branch vagy könnyűsúlyú tag illesztését.

`--tags`::
	Ahelyett, hogy csak az annotált tageket használná, bármely,
	a `refs/tags` névtérben található taget használ. Ez az opció
	lehetővé teszi egy könnyűsúlyú (nem annotált) tag illesztését.

`--contains`::
	Ahelyett, hogy a commit előtti taget keresné meg, a commit
	utáni taget keresi meg, amely így tartalmazza azt.
	Automatikusan maga után vonja a `--tags`-et.

`--abbrev=<n>`::
	Ahelyett, hogy a rövidített objektumnévhez a hexadecimális
	számjegyek alapértelmezett számát (amely a repository-ban lévő
	objektumok száma szerint változik, alapértelmezetten 7)
	használná, _<n>_ számjegyet használ, vagy annyi számjegyet,
	amennyi egy egyedi objektumnév kialakításához szükséges. Egy 0
	értékű _<n>_ elnyomja a hosszú formátumot, és csak a legközelebbi
	taget mutatja.

`--candidates=<n>`::
	Ahelyett, hogy a bemeneti commit-ish leírásához csak a 10
	legutóbbi taget venné figyelembe jelöltként, akár _<n>_
	jelöltet is figyelembe vesz. Az _<n>_ 10 fölé emelése kissé
	tovább tart, de pontosabb eredményt adhat. Egy 0 értékű _<n>_
	azt eredményezi, hogy csak a pontos egyezések kerülnek kiadásra.

`--exact-match`::
	Csak a pontos egyezéseket adja ki (amikor egy tag közvetlenül a
	megadott commitra hivatkozik). Ez a `--candidates=0` szinonimája.

`--debug`::
	Részletesen megjeleníti a használt keresési stratégiára
	vonatkozó információt a standard hibakimeneten. A tag neve
	továbbra is a standard kimenetre kerül kiírásra.

`--long`::
	Mindig a hosszú formátumot adja ki (a taget, a commitok számát
	és a rövidített commitnevet) még akkor is, ha egyezik egy
	taggel. Ez akkor hasznos, ha a commit objektumnév egyes
	részeit is látni szeretnéd a "describe" kimenetben, még akkor
	is, ha a szóban forgó commit éppen egy tagelt verzió. Ahelyett,
	hogy egyszerűen csak a tag nevét adná ki, egy ilyen commitot
	v1.2-0-gdeadbee alakban ír le (a v1.2 tag óta a 0. commit, amely
	a deadbee... objektumra mutat).

`--match <pattern>`::
	Csak a megadott `glob`(7) mintának megfelelő tageket veszi
	figyelembe, a "refs/tags/" előtag nélkül. Ha a `--all`-lal
	együtt használod, a mintának megfelelő lokális brancheket és
	remote-tracking referenciákat is figyelembe veszi, a "refs/heads/"
	illetve a "refs/remotes/" előtagok nélkül; más típusú
	referenciák soha nem kerülnek figyelembevételre. Ha többször is
	megadod, a minták listája felhalmozódik, és bármelyik mintának
	megfelelő tagek figyelembevételre kerülnek. A `--no-match`
	használatával törölheted és visszaállíthatod a minták listáját.

`--exclude <pattern>`::
	Nem veszi figyelembe a megadott `glob`(7) mintának megfelelő
	tageket, a "refs/tags/" előtag nélkül. Ha a `--all`-lal együtt
	használod, a mintának megfelelő lokális brancheket és
	remote-tracking referenciákat sem veszi figyelembe, a
	"`refs/heads/`" illetve a "`refs/remotes/`" előtagok nélkül; más
	típusú referenciák soha nem kerülnek figyelembevételre. Ha
	többször is megadod, a minták listája felhalmozódik, és
	bármelyik mintának megfelelő tagek kizárásra kerülnek. A
	`--match`-csel kombinálva egy tag akkor kerül figyelembevételre,
	ha megfelel legalább egy `--match` mintának, és nem felel meg
	egyik `--exclude` mintának sem. A `--no-exclude` használatával
	törölheted és visszaállíthatod a minták listáját.

`--always`::
	Tartalék megoldásként egyedileg rövidített commit objektumot
	mutat.

`--first-parent`::
	Merge commit észlelésekor csak az első szülő commitot kövesse.
	Ez akkor hasznos, ha nem szeretnéd, hogy a célcommit
	történetébe mergelt brancheken lévő tagek illeszkedjenek.

EXAMPLES
--------

A git.git aktuális fájához hasonlóval a következőt kapom:

	[torvalds@g5 git]$ git describe parent
	v1.0.4-14-g2414721

azaz a "parent" branchem aktuális feje a v1.0.4-en alapul, de mivel
azon felül van néhány commitja, a describe hozzáadta a végéhez a
további commitok számát ("14") és magának a commitnak a rövidített
objektumnevét ("2414721").

A további commitok száma azoknak a commitoknak a száma, amelyeket a
`git log v1.0.4..parent` jelenítene meg. A hash-toldalék "`-g`" + a
parent csúcs-commitjának egyértelmű rövidítése (amely
`2414721b194453f058079d897d13c4e377f92dc6` volt). A rövidítés
hossza a repository növekedésével skálázódik, a repository-ban lévő
objektumok közelítő száma és a születésnap-paradoxon körüli
matematika alapján, és alapértelmezetten legalább 7.
A "g" előtag a "git"-et jelenti, és arra szolgál, hogy lehetővé
tegye egy szoftver verziójának leírását attól függően, hogy melyik
verziókövető rendszerrel kezelik a szoftvert. Ez olyan környezetben
hasznos, ahol az emberek különböző verziókövető rendszereket
használhatnak.

Ha egy `git describe`-ot futtatsz egy tag-néven, az egyszerűen a
tag nevét mutatja meg:

	[torvalds@g5 git]$ git describe v1.0.4
	v1.0.4

A `--all`-lal a parancs branch fejeket is használhat referenciaként,
így a kimenet a referencia útvonalát is megmutatja:

	[torvalds@g5 git]$ git describe --all --abbrev=4 v1.0.5^2
	tags/v1.0.0-21-g975b

	[torvalds@g5 git]$ git describe --all --abbrev=4 HEAD^
	heads/lt/describe-7-g975b

A `--abbrev` 0-ra állításával a parancs használható a legközelebbi
tagnév megtalálására, bármilyen toldalék nélkül:

	[torvalds@g5 git]$ git describe --abbrev=0 v1.0.5^2
	tags/v1.0.0

Vedd figyelembe, hogy a toldalék, amit ma kapsz, ha begépeled ezeket a
parancsokat, hosszabb lehet, mint amit Linus fent látott, amikor
lefuttatta ezeket a parancsokat, mivel a Git repository-ban lehetnek
olyan új commitok, amelyek objektumneve 975b-vel kezdődik, és akkor
még nem léteztek, így önmagában a "-g975b" toldalék talán nem
elegendő ezeknek a commitoknak az egyértelműsítéséhez.


[[_search_strategy]]
Keresési stratégia
------------------

Minden megadott commit-ish-hez a `git describe` először egy olyan
taget keres, amely pontosan azt a commitot tageli. Az annotált tagek
mindig előnyben részesülnek a könnyűsúlyú tagekkel szemben, és az
újabb dátumú tagek mindig előnyben részesülnek a régebbi dátumú
tagekkel szemben. Ha talál egy pontos egyezést, annak neve kerül
kiadásra, és a keresés leáll.

Ha nem talált pontos egyezést, a `git describe` visszafelé bejárja a
commit-történetet, hogy megtaláljon egy tagelt őscommitot. Az ős
tagje kerül kiadásra a bemeneti commit-ish SHA-1-ének rövidítésével
együtt. Ha meg volt adva a `--first-parent`, a bejárás csak minden
commit első szülőjét veszi figyelembe.

Ha a bejárás során több taget is talált, akkor az a tag kerül
kiválasztásra és kiadásra, amelynek a bemeneti commit-ishtől való
eltérése a legkevesebb commitban mérhető. Itt a legkevesebb eltérő
commit azt jelenti, hogy a `git log tag..input` által megjelenített
commitok száma a lehető legkisebb.

BUGS
----

A fa objektumok, valamint a nem commitra mutató tag objektumok nem
írhatók le. Blobok leírásakor a blobokra mutató könnyűsúlyú tagek
figyelmen kívül maradnak, de a blob továbbra is `<commit-ish>:<path>`
alakban lesz leírva, annak ellenére, hogy a könnyűsúlyú tag lenne
a kedvezőbb.

GIT
---
A linkgit:git[1] csomag része
