git-repo(1)
===========

NAME
----
git-repo - Információk lekérése a repository-ról

SYNOPSIS
--------
[synopsis]
git repo info [--format=(lines|nul) | -z] [--all | <key>...]
git repo info --keys [--format=(lines|nul) | -z]
git repo structure [--format=(table|lines|nul) | -z]

DESCRIPTION
-----------
Információk lekérése a repository-ról.

EZ A PARANCS KÍSÉRLETI. A VISELKEDÉSE MEGVÁLTOZHAT.

COMMANDS
--------
`info [--format=(lines|nul) | -z] [--all | <key>...]`::
	Metaadatokkal kapcsolatos információk lekérése az aktuális
	repository-ról. Csak a kért adatok kerülnek visszaadásra a kulcsaik
	alapján (l. lentebb az "INFO KEYS" szakaszt).
+
Az értékek ugyanabban a sorrendben kerülnek visszaadásra, amilyenben a
hozzájuk tartozó kulcsokat kérték. A `--all` flag az összes elérhető kulcs
értékét kéri.
+
A kimeneti formátum a `--format` flaggel választható ki. Két formátum
támogatott:
+

`lines`:::
	Kulcs-érték párok kiírása soronként egyet, a kulcs és az érték közötti
	elválasztóként a `=` karaktert használva. A "szokatlan" karaktereket
	tartalmazó értékek idézőjelbe kerülnek a `core.quotePath` konfigurációs
	változónál leírtak szerint (l. linkgit:git-config[1]). Ez az
	alapértelmezett.

`nul`:::
	Hasonló a `lines`-hoz, de a kulcs és az érték közötti elválasztóként
	újsor karaktert használ, és minden érték után egy _NUL_ karaktert.
	Ez a formátum jobban alkalmas más alkalmazások általi elemzésre, mint a
	`lines`. A `lines` formátummal ellentétben az értékek soha nem kerülnek
	idézőjelbe.
+
A `-z` a `--format=nul` álneve.

`info --keys [--format=(lines|nul) | -z]`::
	Az összes elérhető kulcs listázása, soronként egyet. A kimeneti formátum
	a `--format` flaggel választható ki. A következő formátumok támogatottak:
+
`lines`:::
	A kulcsok kiírása soronként egyet. Ez az alapértelmezett.

`nul`:::
	Hasonló a `lines`-hoz, de minden érték után egy _NUL_ karaktert használ.

`structure [--format=(table|lines|nul) | -z]`::
	Statisztikák lekérése az aktuális repository szerkezetéről. A következő
	típusú információk jelennek meg:
+
* Típus szerint kategorizált referencia-darabszámok
* Típus szerint kategorizált elérhető objektum-darabszámok
* Az elérhető objektumok teljes kifejtett mérete típus szerint
* Az elérhető objektumok teljes lemezmérete típus szerint
* A repository legnagyobb elérhető objektumai típus szerint
+
A kimeneti formátum a `--format` flaggel választható ki. Három formátum
támogatott:
+
`table`:::
	A repository statisztikáit ember számára barátságos táblázatban írja ki.
	Ez a formátum változhat, és nem gépi elemzésre szánták. Ez az
	alapértelmezett formátum.

`lines`:::
	A kimenet minden sora egy kulcs-érték párt tartalmaz egy repository-
	statisztikához. A kulcs és az érték elválasztására a '=' karakter
	szolgál. A "szokatlan" karaktereket tartalmazó értékek idézőjelbe
	kerülnek a `core.quotePath` konfigurációs változónál leírtak szerint
	(l. linkgit:git-config[1]).

`nul`:::
	Hasonló a `lines`-hoz, de a kulcs-érték párok elválasztására újsor
	helyett _NUL_ karaktert használ. A kulcs és az érték elválasztására
	pedig '=' helyett újsor karaktert. A `lines` formátummal ellentétben a
	"szokatlan" karaktereket tartalmazó értékek soha nem kerülnek
	idézőjelbe.
+
A `-z` a `--format=nul` álneve.

INFO KEYS
---------
Ahhoz, hogy értékek egy halmazát kapd meg a `git repo info`-tól, meg kell
adnod az őket azonosító kulcsokat. Íme az elérhető kulcsok és az általuk
visszaadott értékek listája:

`layout.bare`::
	`true`, ha ez egy bare repository, egyébként `false`.

`layout.shallow`::
	`true`, ha ez egy shallow repository, egyébként `false`.

`object.format`::
	A repository-ban használt objektumformátum (hash-algoritmus).

`path.commondir.absolute`::
	A Git repository közös könyvtárának kanonikus abszolút útvonala
	(a megosztott `.git` könyvtár, amely az objektumokat, a refeket és a
	globális konfigurációt tartalmazza).

`path.commondir.relative`::
	A Git repository közös könyvtárának útvonala az aktuális
	munkakönyvtárhoz képest.

`path.gitdir.absolute`::
	A Git repository könyvtárának kanonikus abszolút útvonala (a `.git` könyvtár).

`path.gitdir.relative`::
	A Git repository könyvtárának útvonala az aktuális munkakönyvtárhoz képest.

`references.format`::
	A referenciatárolási formátum. Az érvényes értékek:
+
include::ref-storage-format.adoc[]

EXAMPLES
--------

* Lekéri az aktuális repository referenciaformátumát:
+
------------
git repo info references.format
------------
+

* Lekéri, hogy az aktuális repository bare-e és hogy shallow-e, a `nul`
formátum használatával:
+
------------
git repo info --format=nul layout.bare layout.shallow
------------

SEE ALSO
--------
linkgit:git-rev-parse[1]

GIT
---
A linkgit:git[1] csomag része
