git-replace(1)
==============

NAME
----
git-replace - Objektumokat helyettesítő refek létrehozása, listázása, törlése

SYNOPSIS
--------
[verse]
'git replace' [-f] <object> <replacement>
'git replace' [-f] --edit <object>
'git replace' [-f] --graft <commit> [<parent>...]
'git replace' [-f] --convert-graft-file
'git replace' -d <object>...
'git replace' [--format=<format>] [-l [<pattern>]]

DESCRIPTION
-----------
Hozzáad egy 'replace' referenciát a `refs/replace/` névtérben.

A 'replace' referencia neve a helyettesített objektum SHA-1-e. A
'replace' referencia tartalma a helyettesítő objektum SHA-1-e.

A helyettesített objektumnak és a helyettesítő objektumnak azonos
típusúnak kell lennie. Ez a megkötés a `-f` használatával megkerülhető.

Hacsak nincs megadva a `-f`, a 'replace' referencia még nem létezhet.

A helyettesített és a helyettesítő objektumokra nincs más megkötés. A
merge-commitok helyettesíthetők nem merge-commitokkal és fordítva.

A helyettesítő referenciákat alapból minden Git parancs használja,
kivéve azokat, amelyek elérhetőségi bejárást végeznek (prune, pack
átvitel és fsck).

Bármely parancsnál letiltható a helyettesítő referenciák használata a
`--no-replace-objects` opcióval, közvetlenül a 'git' után.

Például, ha a 'foo' commitot a 'bar' commit helyettesítette:

------------------------------------------------
$ git --no-replace-objects cat-file commit foo
------------------------------------------------

a 'foo' commitról mutat információt, míg:

------------------------------------------------
$ git cat-file commit foo
------------------------------------------------

a 'bar' commitról mutat információt.

A `GIT_NO_REPLACE_OBJECTS` környezeti változó beállításával ugyanaz a
hatás érhető el, mint a `--no-replace-objects` opcióval.

OPTIONS
-------
-f::
--force::
	Ha ugyanahhoz az objektumhoz létezik replace ref, az felülíródik
	(a hibázás helyett).

-d::
--delete::
	A megadott objektumokhoz tartozó meglévő replace refek törlése.

--edit <object>::
	Egy objektum tartalmának interaktív szerkesztése. Az <object>
	meglévő tartalma szép formázással egy ideiglenes fájlba kerül, egy
	szerkesztő indul a fájlon, és az eredmény elemzésével egy új,
	<object>-tel azonos típusú objektum jön létre. Ezután egy
	helyettesítő ref jön létre, amely az <object>-et az újonnan
	létrehozott objektumra cseréli. A szerkesztő kiválasztásának
	részleteiről l. linkgit:git-var[1].

--raw::
	Szerkesztéskor a szép formázás helyett a nyers objektumtartalmat
	adja. Jelenleg ez csak a tree-ket érinti, amelyek bináris
	formájukban jelennek meg. Ezzel nehezebb dolgozni, de segíthet egy
	olyan tree javításakor, amely annyira sérült, hogy nem lehet szép
	formázással megjeleníteni. Vedd figyelembe, hogy szükség lehet a
	szerkesztőd beállítására a bináris adatok tiszta olvasásához és
	írásához.

--graft <commit> [<parent>...]::
	Egy graft commit létrehozása. Egy új commit jön létre a <commit>-tal
	azonos tartalommal, azzal a kivétellel, hogy a szülői [<parent>...]
	lesznek a <commit> szülői helyett. Ezután egy helyettesítő ref jön
	létre, amely a <commit>-ot az újonnan létrehozott commitra cseréli.
	Egy `$GIT_DIR/info/grafts` fájl konvertálásához és helyette replace
	refek használatához használd a `--convert-graft-file`-t.

--convert-graft-file::
	Graft commitokat hoz létre a `$GIT_DIR/info/grafts` összes
	bejegyzéséhez, és siker esetén törli azt a fájlt. A cél az, hogy
	segítse a felhasználókat a mostanra elavult graft fájlról való
	áttérésben.

-l <pattern>::
--list <pattern>::
	A megadott mintára illeszkedő objektumokhoz tartozó replace refek
	listázása (vagy az összesé, ha nincs minta megadva).
	A "git replace" argumentumok nélküli begépelése szintén felsorolja
	az összes replace refet.

--format=<format>::
	Listázáskor a megadott <format> használata, amely a 'short',
	'medium' és 'long' egyike lehet. Ha hiányzik, a formátum alapból
	'short'.

FORMATS
-------

A következő formátumok érhetők el:

* 'short':
	<replaced-sha1>
* 'medium':
	<replaced-sha1> -> <replacement-sha1>
* 'long':
	<replaced-sha1> (<replaced-type>) -> <replacement-sha1> (<replacement-type>)

CREATING REPLACEMENT OBJECTS
----------------------------

A linkgit:git-hash-object[1], a linkgit:git-rebase[1] és a
https://github.com/newren/git-filter-repo[git-filter-repo] – más git parancsok mellett – használható
helyettesítő objektumok létrehozására meglévő objektumokból. A `--edit`
opció a 'git replace'-szel is használható helyettesítő objektum
létrehozására egy meglévő objektum szerkesztésével.

Ha sok blobot, tree-t vagy commitot szeretnél helyettesíteni, amelyek
egy commitfüzér részei, akkor lehet, hogy elég csak egy helyettesítő
commitfüzért létrehozni, majd csak a cél-commitfüzér csúcsán lévő
commitot helyettesíteni a helyettesítő commitfüzér csúcsán lévő
committal.

BUGS
----
A helyettesített blobok vagy tree-k összehasonlítása az őket
helyettesítőkkel nem működik megfelelően. És ha a `git reset --hard`-ot
használod, hogy visszatérj egy helyettesített commithoz, az a branchet
a helyettesítő commitra mozgatja a helyettesített commit helyett.

Előfordulhatnak más problémák is a 'git rev-list' használatakor, a
függőben lévő objektumokkal kapcsolatban.

CAVEATS
-------

A replace objektumok vagy a commit graftok létezése kikapcsolja a
commit-graph olvasását és írását, ami teljesítményproblémákat okozhat.
L. linkgit:git-commit-graph[1].

SEE ALSO
--------
linkgit:git-hash-object[1]
linkgit:git-rebase[1]
linkgit:git-tag[1]
linkgit:git-branch[1]
linkgit:git-commit[1]
linkgit:git-var[1]
linkgit:git[1]
https://github.com/newren/git-filter-repo[git-filter-repo]

GIT
---
A linkgit:git[1] csomag része
