git-fmt-merge-msg(1)
====================

NAME
----
git-fmt-merge-msg - Létrehoz egy merge-commit-üzenetet


SYNOPSIS
--------
[verse]
'git fmt-merge-msg' [-m <message>] [--into-name <branch>] [--log[=<n>] | --no-log]
'git fmt-merge-msg' [-m <message>] [--log[=<n>] | --no-log] -F <file>

DESCRIPTION
-----------
A merge-elt objektumok listáját veszi a stdin-ről, és egy megfelelő
commit-üzenetet állít elő a merge-commithoz, amelyet rendszerint a
'git merge' '<merge-message>' argumentumaként adnak át.

Ez a parancs elsősorban a 'git merge'-et automatikusan meghívó
szkriptek belső használatára szolgál.

OPTIONS
-------

--log[=<n>]::
	A branchnevek mellett a napló-üzenetet feltölti a merge-elt
	commitok tényleges, egysoros leírásaival is. Merge-szülőnként
	legfeljebb <n> commit lesz felhasználva (20, ha az <n> el van
	hagyva). Ez felülbírálja a `merge.log` konfigurációs változót.

--no-log::
	Nem sorolja fel a merge-elt commitok tényleges, egysoros
	leírásait.

--summary::
--no-summary::
	A --log és a --no-log szinonimái; ezek elavultak, és a
	jövőben eltávolításra kerülnek.

-m <message>::
--message <message>::
	A branchnevek helyett a <message>-t használja a napló-üzenet
	első soraként. A `--log`-gal együtt használandó.

--into-name <branch>::
	Úgy készíti el a merge-üzenetet, mintha a `<branch>` branchbe
	merge-elnénk, ahelyett a valódi branch neve helyett, amelybe a
	merge történik.

-F <file>::
--file <file>::
	A merge-elt objektumok listáját a <file>-ból veszi, nem a
	stdin-ről.

CONFIGURATION
-------------
include::config/fmt-merge-msg.adoc[]

merge.summary::
	A `merge.log` szinonimája; ez elavult, és a jövőben
	eltávolításra kerül.

EXAMPLES
--------

---------
$ git fetch origin master
$ git fmt-merge-msg --log <$GIT_DIR/FETCH_HEAD
---------

Kiír egy napló-üzenetet, amely a "master" branch mergeét írja le az
"origin" remote-ból.


SEE ALSO
--------
linkgit:git-merge[1]

GIT
---
A linkgit:git[1] csomag része
