git-diagnose(1)
================

NAME
----
git-diagnose - Zip archívum generálása diagnosztikai információkból

SYNOPSIS
--------
[verse]
'git diagnose' [(-o | --output-directory) <path>] [(-s | --suffix) <format>]
	       [--mode=<mode>]

DESCRIPTION
-----------
Részletes információt gyűjt a felhasználó gépéről, a Git klienséről és a
repository állapotáról, majd ezt az információt egy zip archívumba csomagolja.
A létrehozott archívum ezután például megosztható a Git levelezőlistán egy
hiba felderítésének segítésére, vagy referenciaként szolgálhat a független
hibakereséshez.

Alapértelmezés szerint a következő információk kerülnek be az archívumba:

  * 'git version --build-options'
  * A repository gyökerének útvonala
  * A fájlrendszeren elérhető szabad lemezterület
  * Az egyes packfile-ok neve és mérete, beleértve az alternatív
    objektumtárolókban lévőket is
  * A laza objektumok teljes száma, valamint a `.git/objects` alkönyvtárak
    szerinti bontásban is

A `--mode` opcióval kiválasztott másik diagnosztikai mód segítségével további
információ is gyűjthető.

Ez az eszköz abban különbözik a linkgit:git-bugreport[1] parancstól, hogy
jóval részletesebb információt gyűjt, nagyobb hangsúlyt fektetve a repository
tartalmának méretére és adatformájára vonatkozó jelentésre.

OPTIONS
-------
-o <path>::
--output-directory <path>::
	A létrejövő diagnosztikai archívumot a `<path>` helyre teszi az aktuális
	könyvtár helyett.

-s <format>::
--suffix <format>::
	A diagnosztikai archívum nevéhez alternatív utótagot ad meg, hogy egy
	'git-diagnostics-<formázott-utótag>' nevű fájl jöjjön létre. Ennek egy
	strftime(3) formátumú karakterlánc alakját kell felvennie; a jelenlegi
	helyi idő kerül felhasználásra.

--mode=(stats|all)::
	Megadja a gyűjtendő diagnosztika típusát. A 'git diagnose' alapértelmezett
	viselkedése megegyezik a `--mode=stats` opcióéval.
+
A `--mode=all` opció mindent begyűjt, amit a `--mode=stats`, ezen felül a
`.git`, `.git/hooks`, `.git/info`, `.git/logs` és `.git/objects/info`
könyvtárak másolatait is. Ez a további információ érzékeny lehet, mivel
felhasználható a diagnosztizált repository teljes tartalmának
rekonstruálására. A felhasználóknak óvatosnak kell lenniük, amikor egy
`--mode=all` opcióval létrehozott archívumot megosztanak.

GIT
---
A linkgit:git[1] csomag része
