git-rebase(1)
=============

NAME
----
git-rebase - Commitok újbóli alkalmazása egy másik bázis csúcsán

SYNOPSIS
--------
[verse]
'git rebase' [-i | --interactive] [<options>] [--exec <cmd>]
	[--onto <newbase> | --keep-base] [<upstream> [<branch>]]
'git rebase' [-i | --interactive] [<options>] [--exec <cmd>] [--onto <newbase>]
	--root [<branch>]
'git rebase' (--continue|--skip|--abort|--quit|--edit-todo|--show-current-patch)

DESCRIPTION
-----------
Egy commit-sorozat áthelyezése egy másik kiindulási pontra.
A `git rebase` paranccsal a commitok átrendezhetők vagy egyesíthetők is: lásd
lentebb az INTERACTIVE MODE szakaszt, hogy ez hogyan végezhető el.

Képzeld el például, hogy a `topic` branchen dolgozol ebben a történetben, és
szeretnéd "utolérni" a `master` branchen végzett munkát.

------------
          A---B---C topic
         /
    D---E---F---G master
------------

Át szeretnéd helyezni a `topic`-on tett commitokat, amelyek azóta készültek,
hogy a branch elágazott a `master`-től (azaz A, B és C), az aktuális `master`
tetejére. Ezt úgy teheted meg, hogy futtatod a `git rebase master` parancsot,
miközben a `topic` branch van kicheckoutolva. Ha egy másik branchen állva
szeretnéd rebase-elni a `topic`-ot, a `git rebase master topic` parancs
gyorsítóút a `git checkout topic && git rebase master` helyett.

------------
                  A'--B'--C' topic
                 /
    D---E---F---G master
------------


Ha a folyamat során merge-konfliktus lép fel, a `git rebase` megáll az első
problémás commitnál, és konfliktusjelölőket hagy hátra. Ha ez történik, az
alábbiak közül teheted meg valamelyiket:

1. Oldd fel a konfliktust. A `git diff` segítségével megtalálhatod a jelölőket
   (<<<<<<), és elvégezheted a konfliktus feloldásához szükséges
   szerkesztéseket. Minden szerkesztett fájlnál jelezned kell a Gitnek, hogy a
   konfliktus fel van oldva. A konfliktust a `git add <filename>` paranccsal
   jelölheted feloldottnak. Az összes konfliktus feloldása után a rebase
   folyamatát a következővel folytathatod:

   git rebase --continue

2. Állítsd le a `git rebase`-t, és állítsd vissza a branchedet az eredeti
   állapotába a következővel:

   git rebase --abort

3. Hagyd ki a merge-konfliktust okozó commitot a következővel:

   git rebase --skip

Ha nem adsz meg `<upstream>`-et, amelyre rebase-elni szeretnél, akkor a
`branch.<name>.remote` és `branch.<name>.merge` opciókban beállított upstream
kerül felhasználásra (részletekért lásd: linkgit:git-config[1]), és a
`--fork-point` opció automatikusan feltételezve lesz. Ha jelenleg nem vagy
egyik branchen sem, vagy az aktuális branchnek nincs beállított upstreamje, a
rebase megszakad.

Íme egy egyszerűsített leírás arról, hogy a `git rebase <upstream>` mit csinál:

1. Elkészíti az aktuális brancheden lévő összes olyan commit listáját, amelyek
   azóta jöttek létre, hogy a branch elágazott az `<upstream>`-től, és
   amelyeknek nincs megfelelőjük az `<upstream>`-ben.
2. Kicheckoutolja az `<upstream>`-et, a `git checkout --detach <upstream>`
   parancsnak megfelelően.
3. Sorban, egyenként újra lejátssza a commitokat. Ez hasonló ahhoz, mintha
   minden egyes commitra lefuttatnád a `git cherry-pick <commit>` parancsot.
   Lásd a REBASING MERGES szakaszt arról, hogy a merge-ek hogyan kerülnek
   kezelésre.
4. Frissíti a branchedet, hogy a végső commitra mutasson, a
   `git checkout -B <branch>` parancsnak megfelelően.

[NOTE]
A rebase indításakor az `ORIG_HEAD` a rebase-elendő branch csúcsán lévő
commitra lesz beállítva. Az `ORIG_HEAD` azonban nem garantáltan mutat továbbra
is erre a commitra a rebase végén, ha a rebase során olyan más parancsokat is
használsz, amelyek megváltoztatják az `ORIG_HEAD`-et (mint például a
`git reset`). Az előző branch-csúcs azonban továbbra is elérhető az aktuális
branch reflogján keresztül (azaz a `@{1}` segítségével, lásd:
linkgit:gitrevisions[7]).

TRANSPLANTING A TOPIC BRANCH WITH --ONTO
----------------------------------------

Íme, hogyan helyeznél át egy topic branchet, amely az egyik branchen alapul,
egy másikra, úgy téve, mintha a topic branchet ez utóbbiból ágaztattad volna
le, a `rebase --onto` használatával.

Először tegyük fel, hogy a 'topic' a 'next' branchen alapul. Például egy, a
'topic'-ban fejlesztett funkció függ néhány, a 'next'-ben található
funkcionalitástól.

------------
    o---o---o---o---o  master
         \
          o---o---o---o---o  next
                           \
                            o---o---o  topic
------------

Azt szeretnénk, hogy a 'topic' a 'master' branchből legyen leágaztatva; például
azért, mert az a funkcionalitás, amelytől a 'topic' függ, be lett merge-elve a
stabilabb 'master' branchbe. Azt szeretnénk, hogy a fánk így nézzen ki:

------------
    o---o---o---o---o  master
        |            \
        |             o'--o'--o'  topic
         \
          o---o---o---o---o  next
------------

Ezt a következő paranccsal érhetjük el:

    git rebase --onto master next topic


A --onto opcióra egy másik példa egy branch egy részének rebase-elése. Ha a
következő helyzetben vagyunk:

------------
                            H---I---J topicB
                           /
                  E---F---G  topicA
                 /
    A---B---C---D  master
------------

akkor a következő parancs

    git rebase --onto master topicA topicB

ezt eredményezné:

------------
                 H'--I'--J'  topicB
                /
                | E---F---G  topicA
                |/
    A---B---C---D  master
------------

Ez akkor hasznos, ha a topicB nem függ a topicA-tól.

Rebase-eléssel commitok egy tartománya is eltávolítható. Ha a következő
helyzetben vagyunk:

------------
    E---F---G---H---I---J  topicA
------------

akkor a következő parancs

    git rebase --onto topicA~5 topicA~3 topicA

az F és G commitok eltávolítását eredményezné:

------------
    E---H'---I'---J'  topicA
------------

Ez akkor hasznos, ha az F és G valamilyen módon hibás volt, vagy nem kellene a
topicA részét képeznie. Vedd figyelembe, hogy a `--onto` argumentuma és az
`<upstream>` paraméter bármilyen érvényes commit-ish lehet.

MODE OPTIONS
------------

Az ebben a szakaszban lévő opciók semmilyen más opcióval nem használhatók,
egymással sem:

--continue::
	A rebase folyamatának újraindítása egy merge-konfliktus feloldása után.

--skip::
	A rebase folyamatának újraindítása az aktuális patch kihagyásával.

--abort::
	A rebase-művelet megszakítása, és a HEAD visszaállítása az eredeti
	branchre. Ha a `<branch>` meg volt adva a rebase-művelet indításakor,
	akkor a `HEAD` a `<branch>`-re lesz visszaállítva. Egyébként a `HEAD`
	arra a helyre lesz visszaállítva, ahol a rebase-művelet indításakor
	volt.

--quit::
	A rebase-művelet megszakítása, de a `HEAD` nem lesz visszaállítva az
	eredeti branchre. Emiatt az index és a munkakönyvtár is változatlanul
	marad. Ha a `--autostash` használatával egy ideiglenes stash-bejegyzés
	jött létre, az mentésre kerül a stash-listába.

--edit-todo::
	A todo lista szerkesztése egy interaktív rebase során.

--show-current-patch::
	Az aktuális patch megjelenítése egy interaktív rebase-ben, vagy amikor
	a rebase konfliktusok miatt megállt. Ez egyenértékű a
	`git show REBASE_HEAD` paranccsal.

OPTIONS
-------
--onto <newbase>::
	Az a kiindulási pont, amelynél az új commitok létrejönnek. Ha a
	`--onto` opció nincs megadva, a kiindulási pont az `<upstream>`.
	Bármilyen érvényes commit lehet, nem csak egy már létező
	branch-név.
+
Speciális esetként az "A\...B" alak használható az A és B merge-alapjának
rövidítéseként, ha pontosan egy merge-alap létezik. Az A és B közül
legfeljebb az egyik hagyható el, ez esetben az alapértelmezés a HEAD.

Példákért lásd a fenti TRANSPLANTING A TOPIC BRANCH WITH --ONTO szakaszt.

--keep-base::
	Az új commitok létrehozásának kiindulási pontját az `<upstream>` és a
	`<branch>` merge-alapjára állítja. A `git rebase --keep-base <upstream>
	<branch>` futtatása egyenértékű a következő futtatásával:
	`git rebase --reapply-cherry-picks --no-fork-point --onto <upstream>...<branch> <upstream> <branch>`.
+
Ez az opció akkor hasznos, ha valaki egy upstream branch tetején fejleszt
egy funkciót. Amíg a funkción dolgoznak, az upstream branch előrehaladhat,
és nem feltétlenül a legjobb ötlet folyamatosan az upstreamre rebase-elni,
hanem inkább változatlanul hagyni az alap commitot. Mivel az alap commit
változatlan marad, ez az opció maga után vonja a `--reapply-cherry-picks`
opciót is, hogy elkerülje a commitok elvesztését.
+
Bár mind ez az opció, mind a `--fork-point` megkeresi az `<upstream>` és a
`<branch>` merge-alapját, ez az opció a merge-alapot _kiindulási pontként_
használja, amelyen az új commitok létrejönnek, míg a `--fork-point` a
merge-alapot a rebase-elendő _commitok halmazának_ meghatározására
használja.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

<upstream>::
	Az az upstream branch, amelyhez viszonyítva összehasonlítunk. Bármilyen
	érvényes commit lehet, nem csak egy már létező branch-név.
	Alapértelmezésben az aktuális branchhez beállított upstream.

<branch>::
	A munkabranch; alapértelmezésben a `HEAD`.

--apply::
	Alkalmazó (applying) stratégiák használata a rebase-eléshez (belsőleg
	a `git-am`-et hívja meg). Ez az opció a jövőben no-oppá válhat, amint
	a merge backend mindent kezel, amit az apply backend kezel.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--empty=(drop|keep|stop)::
	Hogyan kezelje azokat a commitokat, amelyek kezdetben nem üresek, és
	nem tiszta cherry-pickjei egyetlen upstream commitnak sem, de a
	rebase után üressé válnak (mert olyan változtatásokat tartalmaznak,
	amelyek már részhalmazként megvannak az upstreamben):
+
--
`drop`;;
	A commit el lesz dobva. Ez az alapértelmezett viselkedés.
`keep`;;
	A commit megmarad. Ez az opció akkor érvényesül automatikusan, ha a
	`--exec` meg van adva, kivéve, ha az `-i`/`--interactive` is meg van
	adva.
`stop`;;
`ask`;;
	A rebase megáll, amikor a commit alkalmazásra kerül, lehetővé téve,
	hogy eldöntsd, eldobod-e, tovább szerkeszted-e a fájlokat, vagy
	egyszerűen commitolod az üres változtatásokat. Ez az opció akkor
	érvényesül automatikusan, ha az `-i`/`--interactive` meg van adva.
	Az `ask` a `stop` elavult szinonimája.
--
+
Vedd figyelembe, hogy a kezdetben üres commitok megmaradnak (kivéve, ha a
`--no-keep-empty` meg van adva), és a tiszta cherry-pickek (amelyeket a
`git log --cherry-mark ...` határoz meg) felismerésre és eldobásra kerülnek
egy előzetes lépésként (kivéve, ha a `--reapply-cherry-picks` vagy a
`--keep-base` meg van adva).
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--no-keep-empty::
--keep-empty::
	Ne tartsa meg az eredményben azokat a commitokat, amelyek a rebase
	előtt már üresek voltak (azaz semmit nem változtatnak a szülőjükhöz
	képest). Az alapértelmezés a kezdetben üres commitok megtartása,
	mivel az ilyen commitok létrehozásához a `--allow-empty` felülbíráló
	kapcsolót kell átadni a `git commit`-nak, ami azt jelzi, hogy a
	felhasználó nagyon szándékosan hozza létre az ilyen commitot, és így
	meg is akarja tartani.
+
Ennek a kapcsolónak a használata valószínűleg ritka lesz, mivel a
kezdetben üres commitoktól egy interaktív rebase elindításával és a nem
kívánt commitoknak megfelelő sorok eltávolításával is megszabadulhatsz.
Ez a kapcsoló egy kényelmes gyorsítóútként létezik, olyan esetekre, amikor
például külső eszközök sok üres commitot generálnak, és ezeket mind el
szeretnéd távolítani.
+
Azokról a commitokról, amelyek nem üresen kezdődnek, de a rebase után
üressé válnak, lásd a `--empty` kapcsolót.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--reapply-cherry-picks::
--no-reapply-cherry-picks::
	Minden, bármelyik upstream commit tiszta cherry-pickjének minősülő
	commit újbóli alkalmazása, ahelyett hogy elővigyázatosan eldobná
	őket. (Ha ezek a commitok a rebase után üressé válnak, mert olyan
	változtatások részhalmazát tartalmazzák, amelyek már megvannak az
	upstreamben, a velük szembeni viselkedést a `--empty` kapcsoló
	szabályozza.)
+
A `--keep-base` hiányában (vagy ha a `--no-reapply-cherry-picks` meg van
adva) ezek a commitok automatikusan eldobásra kerülnek. Mivel ehhez az
összes upstream commitot be kell olvasni, ez költséges lehet olyan
repository-kban, ahol nagyszámú beolvasandó upstream commit van. A
'merge' backend használatakor minden eldobott commitra figyelmeztetés
kerül kiadásra (kivéve, ha a `--quiet` meg van adva). Tanács is kiadásra
kerül, hacsak az `advice.skippedCherryPicks` nincs false-ra állítva (lásd:
linkgit:git-config[1]).
+
A `--reapply-cherry-picks` lehetővé teszi a rebase számára, hogy lemondjon
az összes upstream commit beolvasásáról, ezáltal potenciálisan javítva a
teljesítményt.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--allow-empty-message::
	No-op. Korábban az üres üzenetű commitok rebase-elése sikertelen volt,
	és ez az opció felülbírálta ezt a viselkedést, lehetővé téve az üres
	üzenetű commitok rebase-elését. Most már az üres üzenetű commitok nem
	okozzák a rebase megállását.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

-m::
--merge::
	Merge-stratégiák használata a rebase-eléshez (alapértelmezett).
+
Vedd figyelembe, hogy egy rebase-merge úgy működik, hogy a munkabranch
minden egyes commitját újra lejátssza az `<upstream>` branch tetején.
Emiatt, amikor egy merge-konfliktus történik, az 'ours'-ként jelentett
oldal az eddig rebase-elt sorozat, amely az `<upstream>`-mel kezdődik, a
'theirs' pedig a munkabranch. Más szóval, az oldalak fel vannak cserélve.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

-s <strategy>::
--strategy=<strategy>::
	A megadott merge-stratégia használata az alapértelmezett `ort` helyett.
	Ez maga után vonja a `--merge` opciót.
+
Mivel a `git rebase` a munkabranch minden egyes commitját a megadott
stratégiával játssza le újra az `<upstream>` branch tetején, az `ours`
stratégia használata egyszerűen kiüresíti a `<branch>` összes patch-ét,
aminek kevés értelme van.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

-X <strategy-option>::
--strategy-option=<strategy-option>::
	A <strategy-option> átadása a merge-stratégiának. Ez maga után vonja a
	`--merge` opciót, és ha nincs megadva stratégia, a `-s ort`-ot is.
	Vedd figyelembe az 'ours' és 'theirs' fent, a `-m` opciónál leírt
	felcserélését.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

include::rerere-options.adoc[]

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	Commitok GPG-aláírása. A `keyid` argumentum opcionális, és
	alapértelmezésben a committer személyazonossága; ha meg van adva,
	szóköz nélkül közvetlenül az opcióhoz kell illeszteni. A
	`--no-gpg-sign` a `commit.gpgSign` konfigurációs változó és egy
	korábbi `--gpg-sign` felülbírálására hasznos.

-q::
--quiet::
	Legyen csendes. Maga után vonja a `--no-stat` opciót.

-v::
--verbose::
	Legyen bőbeszédű. Maga után vonja a `--stat` opciót.

--stat::
	Egy diffstat megjelenítése arról, hogy mi változott az upstreamben az
	utolsó rebase óta. A diffstatot a rebase.stat konfigurációs opció is
	szabályozza.

-n::
--no-stat::
	Ne jelenítsen meg diffstatot a rebase folyamat részeként.

--no-verify::
	Ez az opció megkerüli a pre-rebase hookot. Lásd még: linkgit:githooks[5].

--verify::
	Engedélyezi a pre-rebase hook futtatását, ami az alapértelmezett. Ez
	az opció a `--no-verify` felülbírálására használható. Lásd még:
	linkgit:githooks[5].

-C<n>::
	Biztosítja, hogy minden változtatás előtt és után legalább `<n>` sornyi
	körülvevő kontextus egyezzen. Ha kevesebb sornyi körülvevő kontextus
	létezik, akkor mindnek egyeznie kell. Alapértelmezésben soha nincs
	figyelmen kívül hagyott kontextus. Maga után vonja a `--apply` opciót.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--no-ff::
--force-rebase::
-f::
	Az összes rebase-elt commit egyenkénti újralejátszása, ahelyett hogy
	fast-forwardolna a változatlanok felett. Ez biztosítja, hogy a
	rebase-elt branch teljes története új commitokból álljon.
+
Ez hasznos lehet egy topic branch merge-jének revertálása után, mivel ez
az opció friss commitokkal újra létrehozza a topic branchet, így az sikeresen
újra merge-elhető anélkül, hogy "revertálni kellene a revertálást" (lásd a
link:howto/revert-a-faulty-merge.html[revert-a-faulty-merge How-To]
leírást a részletekért).

--fork-point::
--no-fork-point::
	A reflog használata egy jobb közös ős megtalálásához az `<upstream>`
	és a `<branch>` között, amikor kiszámítja, hogy mely commitokat
	vezette be a `<branch>`.
+
Amikor a `--fork-point` aktív, az `<upstream>` helyett a 'fork_point' kerül
felhasználásra a rebase-elendő commitok halmazának kiszámításához, ahol a
'fork_point' a `git merge-base --fork-point <upstream> <branch>` parancs
eredménye (lásd: linkgit:git-merge-base[1]). Ha a 'fork_point' üresnek
adódik, az `<upstream>` lesz a tartalék.
+
Ha az `<upstream>` vagy a `--keep-base` meg van adva a parancssorban, akkor
az alapértelmezés a `--no-fork-point`, egyébként az alapértelmezés a
`--fork-point`. Lásd még a `rebase.forkpoint`-ot a linkgit:git-config[1]
leírásában.
+
Ha a branched az `<upstream>`-en alapult, de az `<upstream>` vissza lett
tekerve, és a branched olyan commitokat tartalmaz, amelyek el lettek dobva,
ez az opció a `--keep-base`-zel együtt használható arra, hogy eldobd
ezeket a commitokat a brancheből.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--ignore-whitespace::
	A whitespace-eltérések figyelmen kívül hagyása az eltérések
	összeegyeztetésekor. Jelenleg mindkét backend ennek a viselkedésnek
	egy közelítését valósítja meg:
+
apply backend;;
	Egy patch alkalmazásakor a whitespace-változtatások figyelmen kívül
	hagyása a kontextussorokban. Sajnos ez azt jelenti, hogy ha a
	patch által lecserélt "régi" sorok csak whitespace-ben térnek el a
	meglévő fájltól, merge-konfliktust fogsz kapni a sikeres
	patch-alkalmazás helyett.
+
merge backend;;
	A csak whitespace-változtatásokat tartalmazó sorok változatlannak
	tekintése merge-elés közben. Sajnos ez azt jelenti, hogy azok a
	patch-hunkok, amelyek célja kizárólag a whitespace módosítása volt,
	el lesznek dobva, még akkor is, ha a másik oldalon nem voltak
	konfliktusban lévő változtatások.

--whitespace=<option>::
	Ez a kapcsoló a patch-et alkalmazó `git apply` programnak kerül
	átadásra (lásd: linkgit:git-apply[1]). Maga után vonja a `--apply`
	opciót.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--committer-date-is-author-date::
	Ahelyett, hogy a jelenlegi időt használná committer-dátumként, a
	rebase-elt commit szerző-dátumát használja committer-dátumként. Ez
	az opció maga után vonja a `--force-rebase` opciót.
+
WARNING: A történet-bejárási gépezet feltételezi, hogy a commitok
nem-csökkenő commit-időbélyegekkel rendelkeznek. Fontold meg, hogy valóban
szükséged van-e erre az opcióra. Ezt az opciót csak akkor kellene
használnod a committer-dátum felülbírálására, amikor olyan alap tetejére
rebase-elsz commitokat, amelynek commitja régebbi (a commit-dátum
szempontjából), mint a legrégebbi commit, amelyet alkalmazol (a
szerző-dátum szempontjából).

--ignore-date::
--reset-author-date::
	Az eredeti commit szerző-dátuma helyett a jelenlegi időt használja a
	rebase-elt commit szerző-dátumaként. Ez az opció maga után vonja a
	`--force-rebase` opciót.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--signoff::
	Egy `Signed-off-by` trailer hozzáadása az összes rebase-elt commithoz.
	Vedd figyelembe, hogy ha az `--interactive` meg van adva, akkor csak a
	pickelésre, szerkesztésre vagy átfogalmazásra megjelölt commitokhoz
	kerül hozzáadásra a trailer.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--trailer=<trailer>::
	A megadott trailer hozzáfűzése minden rebase-elt commit-üzenethez, a
	linkgit:git-interpret-trailers[1] segítségével feldolgozva. Ez az
	opció maga után vonja a `--force-rebase` opciót.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

-i::
--interactive::
	Elkészíti a rebase-elendő commitok listáját. Lehetővé teszi a
	felhasználó számára, hogy a rebase-elés előtt szerkessze ezt a
	listát. Ez a mód commitok szétbontására is használható (lásd
	lentebb a SPLITTING COMMITS szakaszt).
+
A commit-lista formátuma a rebase.instructionFormat konfigurációs opció
beállításával módosítható. Egy testreszabott instrukció-formátum elé
automatikusan bekerül a commit hash-e.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

-r::
--rebase-merges[=(rebase-cousins|no-rebase-cousins)]::
--no-rebase-merges::
	Alapértelmezésben a rebase egyszerűen eldobja a merge-commitokat a
	todo listából, és a rebase-elt commitokat egyetlen, lineáris branchbe
	teszi. A `--rebase-merges` esetén a rebase ehelyett megpróbálja
	megőrizni a branch-struktúrát a rebase-elendő commitokon belül, a
	merge-commitok újralétrehozásával. Az ilyen merge-commitokban feloldott
	merge-konfliktusokat vagy kézi módosításokat manuálisan kell
	feloldani/újra alkalmazni. A `--no-rebase-merges` mind a
	`rebase.rebaseMerges` konfigurációs opció, mind egy korábbi
	`--rebase-merges` felülbírálására használható.
+
A merge-ek rebase-elésekor két mód létezik: a `rebase-cousins` és a
`no-rebase-cousins`. Ha a mód nincs megadva, az alapértelmezés a
`no-rebase-cousins`. A `no-rebase-cousins` módban azok a commitok,
amelyeknek nem közvetlen őse az `<upstream>`, megtartják eredeti
branch-pontjukat, azaz azok a commitok, amelyeket a linkgit:git-log[1]
`--ancestry-path` opciója kizárna, alapértelmezésben megtartják eredeti
származásukat. A `rebase-cousins` módban az ilyen commitok ehelyett az
`<upstream>`-re (vagy az `<onto>`-ra, ha meg van adva) kerülnek
rebase-elésre.
+
Jelenleg a merge-commitok újralétrehozása csak az `ort` merge-stratégiával
lehetséges; eltérő merge-stratégiák csak explicit `exec git merge -s
<strategy> [...]` parancsokon keresztül használhatók.
+
Lásd még lentebb a REBASING MERGES és az INCOMPATIBLE OPTIONS szakaszt is.

-x <cmd>::
--exec <cmd>::
	Egy "exec <cmd>" hozzáfűzése minden olyan sor után, amely a végleges
	történetben egy commitot hoz létre. A `<cmd>` egy vagy több
	shell-parancsként kerül értelmezésre. Minden olyan parancs, amely
	sikertelen, megszakítja a rebase-t, 1-es kilépési kóddal.
+
Több parancsot is végrehajthatsz, akár a `--exec` egyetlen példányát
használva több paranccsal:
+
	git rebase -i --exec "cmd1 && cmd2 && ..."
+
akár több `--exec`-et megadva:
+
	git rebase -i --exec "cmd1" --exec "cmd2" --exec ...
+
Ha a `--autosquash` van használva, az `exec` sorok nem kerülnek
hozzáfűzésre a köztes commitok után, és csak az egyes squash/fixup
sorozatok végén jelennek meg.
+
Ez belsőleg az `--interactive` gépezetét használja, de explicit
`--interactive` nélkül is futtatható.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--root::
	Az összes, a `<branch>`-ből elérhető commit rebase-elése, ahelyett
	hogy egy `<upstream>`-mel korlátozná őket. Ez lehetővé teszi egy
	branch gyökér-commitjának/commitjainak rebase-elését.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--autosquash::
--no-autosquash::
	A speciálisan formázott üzenetű commitok automatikus squashelése a
	rebase-elt korábbi commitokba. Ha egy commit-üzenet "squash! ",
	"fixup! " vagy "amend! " szöveggel kezdődik, a cím fennmaradó része
	egy commit-specifikátorként kerül értelmezésre, amely akkor illeszkedik
	egy korábbi commitra, ha megegyezik annak a commitnak a címével vagy
	hash-ével. Ha egyetlen commit sem illeszkedik teljesen, a
	specifikátornak a commit-címek elejével való egyezései vannak
	figyelembe véve.
+
A rebase todo listájában a squash, fixup és amend commitok műveletei
`pick`-ről rendre `squash`-ra, `fixup`-ra vagy `fixup -C`-re változnak, és
közvetlenül azon commit után kerülnek áthelyezésre, amelyet módosítanak.
A `--interactive` opció használható a todo lista áttekintésére és
szerkesztésére, mielőtt folytatódna a folyamat.
+
A squash-jelölőkkel rendelkező commitok létrehozásának ajánlott módja a
linkgit:git-commit[1] `--squash`, `--fixup`, `--fixup=amend:` vagy
`--fixup=reword:` opcióinak használata, amelyek a cél commitot veszik
argumentumként, és automatikusan kitöltik az új commit címét abból.
+
A `rebase.autoSquash` konfigurációs változó true-ra állítása
alapértelmezésben bekapcsolja az auto-squashelést az interaktív
rebase-hez. A `--no-autosquash` opció ennek a beállításnak a
felülbírálására használható.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

--autostash::
--no-autostash::
	Automatikusan létrehoz egy ideiglenes stash-bejegyzést a művelet
	kezdete előtt, és alkalmazza azt a művelet végén. Ez azt jelenti,
	hogy egy piszkos munkafán is futtathatsz rebase-t. Azonban legyél
	óvatos ezzel: a sikeres rebase utáni végső stash-alkalmazás nem
	triviális konfliktusokat eredményezhet.

--reschedule-failed-exec::
--no-reschedule-failed-exec::
	A sikertelen `exec` parancsok automatikus újraütemezése. Ennek csak
	interaktív módban van értelme (vagy ha meg volt adva egy `--exec`
	opció).
+
Ez az opció a rebase elindítása után lép érvénybe. A teljes rebase-re
megőrződik, ebben a sorrendben: a kezdeti `git rebase`-nek megadott
parancssori opció, a `rebase.rescheduleFailedExec` konfiguráció (lásd:
linkgit:git-config[1] vagy lentebb a „CONFIGURATION" szakaszt), vagy
alapértelmezésben false.
+
Ennek az opciónak a teljes rebase-re való rögzítése egy kényelmi funkció.
Egyébként egy explicit `--no-reschedule-failed-exec` a kezdéskor
felülíródna a `rebase.rescheduleFailedExec=true` konfiguráció jelenléte
által, amikor a `git rebase --continue` meghívásra kerül. Jelenleg nem
adhatod át a `--[no-]reschedule-failed-exec`-et a `git rebase --continue`-nak.

--update-refs::
--no-update-refs::
	Automatikusan force-frissíti azokat a brancheket, amelyek a
	rebase-elés alatt álló commitokra mutatnak. Azok a branchek, amelyek
	egy munkafában ki vannak checkoutolva, ilyen módon nem kerülnek
	frissítésre.
+
Ha a `rebase.updateRefs` konfigurációs változó be van állítva, akkor ez az
opció ennek a beállításnak a felülbírálására és letiltására használható.
+
Lásd még lentebb az INCOMPATIBLE OPTIONS szakaszt is.

INCOMPATIBLE OPTIONS
--------------------

A következő opciók:

 * --apply
 * --whitespace
 * -C

nem kompatibilisek a következő opciókkal:

 * --merge
 * --strategy
 * --strategy-option
 * --autosquash
 * --rebase-merges
 * --interactive
 * --exec
 * --no-keep-empty
 * --empty=
 * --[no-]reapply-cherry-picks, ha a --keep-base nélkül van használva
 * --update-refs
 * --root, ha a --onto nélkül van használva
 * --trailer

Ezenkívül a következő opciópárok nem kompatibilisek egymással:

 * --keep-base és --onto
 * --keep-base és --root
 * --fork-point és --root

BEHAVIORAL DIFFERENCES
----------------------

A `git rebase`-nek két elsődleges backendje van: az 'apply' és a 'merge'. (Az
'apply' backendet régebben 'am' backendként ismerték, de ez a név
zavart okozott, mivel inkább igének, mint főnévnek tűnik. Emellett a
'merge' backendet régebben interaktív backendként ismerték, de mostanra
nem-interaktív esetekben is használják. Mindkettő át lett nevezve az
alattuk húzódó alacsonyabb szintű funkcionalitás alapján.) Van néhány
finom eltérés abban, ahogyan ez a két backend viselkedik:

[[_empty_commits]]
Üres commitok
~~~~~~~~~~~~~

Az 'apply' backend sajnos eldobja a szándékosan üres commitokat, azaz
azokat a commitokat, amelyek kezdetben üresek voltak, bár ezek a
gyakorlatban ritkák. Azokat a commitokat is eldobja, amelyek üressé
válnak, és nincs opció ennek a viselkedésnek a szabályozására.

A 'merge' backend alapértelmezésben megtartja a szándékosan üres
commitokat (bár `-i` esetén ezek üresként vannak megjelölve a todo lista
szerkesztőjében, vagy automatikusan eldobhatók a `--no-keep-empty`-vel).

Az apply backendhez hasonlóan a merge backend is alapértelmezésben eldobja
azokat a commitokat, amelyek üressé válnak, hacsak nincs megadva az
`-i`/`--interactive` (ebben az esetben megáll, és megkérdezi a
felhasználót, mit tegyen). A merge backendnek van egy
`--empty=(drop|keep|stop)` opciója is az üressé váló commitok kezelési
viselkedésének módosítására.

[[_directory_rename_detection]]
Könyvtár-átnevezés-felismerés
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A pontos fa-információ hiánya miatt (amely a patchekben elérhető
korlátozott információból hamis ősök felépítéséből ered) a
könyvtár-átnevezés-felismerés le van tiltva az 'apply' backendben. A
letiltott könyvtár-átnevezés-felismerés azt jelenti, hogy ha a történet
egyik oldala átnevez egy könyvtárat, a másik pedig új fájlokat ad a régi
könyvtárhoz, akkor az új fájlok minden figyelmeztetés nélkül a régi
könyvtárban maradnak a rebase-elés idején, holott ezeket a fájlokat az új
könyvtárba érdemes lenne áthelyezni.

A könyvtár-átnevezés-felismerés a 'merge' backenddel együttműködve
figyelmeztetéseket ad az ilyen esetekben.

[[_context]]
Kontextus
~~~~~~~~~

Az 'apply' backend úgy működik, hogy létrehoz egy patch-sorozatot
(belsőleg a `format-patch`-et hívva meg), majd sorban alkalmazza a
patcheket (belsőleg az `am`-et hívva meg). A patchek több hunkból
állnak, mindegyiknek van sorszáma, egy kontextusrégiója, és a tényleges
változtatásai. A sorszámokat bizonyos eltolással kell figyelembe venni,
mivel a másik oldal valószínűleg korábban beszúrt vagy törölt sorokat a
fájlban. A kontextusrégió célja, hogy segítsen megtalálni, hogyan kell
módosítani a sorszámokat ahhoz, hogy a változtatások a megfelelő
sorokra kerüljenek alkalmazásra. Azonban ha a kód több területén is
ugyanazok a körülvevő kontextussorok szerepelnek, a rossz terület is
kiválasztható. Vannak valós esetek, amikor ez azt okozta, hogy
commitok helytelenül kerültek újra alkalmazásra, konfliktus jelzése
nélkül. A `diff.context` nagyobb értékre állítása megelőzheti az ilyen
típusú problémákat, de növeli a hamis konfliktusok esélyét (mivel több
sornyi egyező kontextust igényel az alkalmazáshoz).

A 'merge' backend minden érintett fájl teljes másolatával dolgozik,
ezáltal elszigetelve magát az ilyen típusú problémáktól.

[[_labelling_of_conflicts_markers]]
Konfliktusjelölők címkézése
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Amikor tartalmi konfliktusok vannak, a merge-gépezet megpróbálja mindkét
oldal konfliktusjelölőit megjegyzésekkel ellátni azokkal a commitokkal,
amelyekből a tartalom származik. Mivel az 'apply' backend eldobja az
eredeti információt a rebase-elt commitokról és azok szülőiről (és
ehelyett új, hamis commitokat generál a generált patchekben elérhető
korlátozott információ alapján), ezek a commitok nem azonosíthatók;
ehelyett egy commit-összefoglalóra kell hagyatkoznia. Emellett, amikor a
`merge.conflictStyle` `diff3`-ra vagy `zdiff3`-ra van állítva, az 'apply'
backend a "constructed merge base" szöveget fogja használni a merge-alap
tartalmának címkézésére, így semmilyen információt sem szolgáltat a
merge-alap commitjáról.

A 'merge' backend a történet mindkét oldalán a teljes commitokkal
dolgozik, így nincsenek ilyen korlátai.

[[_hooks]]
Hookok
~~~~~~

Az 'apply' backend hagyományosan nem hívta meg a post-commit hookot,
míg a 'merge' backend igen. Mindkettő meghívta a post-checkout hookot,
bár a 'merge' backend elnémította annak kimenetét. Továbbá mindkét
backend csak a rebase kiindulási pontjának commitjával hívja meg a
post-checkout hookot, nem a köztes commitokkal, sem a végleges
committal. Mindkét esetben ezeknek a hookoknak a meghívása inkább az
implementáció véletlen következménye volt, mintsem tudatos tervezés
(mindkét backend eredetileg shell szkriptként volt megvalósítva, és
véletlenül olyan más parancsokat hívtak meg, mint a `git checkout` vagy
a `git commit`, amelyek meghívták a hookokat). Mindkét backendnek
ugyanúgy kellene viselkednie, bár egyáltalán nem világos, hogy melyik –
ha egyáltalán bármelyik – a helyes. A jövőben valószínűleg elérjük,
hogy a rebase egyik hookot se hívja meg többé.

[[_interruptability]]
Megszakíthatóság
~~~~~~~~~~~~~~~~

Az 'apply' backendnek biztonsági problémái vannak egy rosszkor érkező
megszakítással; ha a felhasználó rossz pillanatban nyomja meg a
Ctrl-C-t, hogy megpróbálja megszakítani a rebase-t, a rebase olyan
állapotba kerülhet, amelyből nem szakítható meg egy utólagos `git
rebase --abort` paranccsal. Úgy tűnik, a 'merge' backend nem szenved
ugyanettől a hiányosságtól. (Részletekért lásd:
https://lore.kernel.org/git/20200207132152.GC2868@szeder.dev/.)

[[_commit_rewording]]
Commit-üzenet átfogalmazása
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Amikor egy konfliktus lép fel rebase-elés közben, a rebase megáll, és
megkéri a felhasználót a feloldására. Mivel a felhasználónak jelentős
változtatásokat kell tennie a konfliktusok feloldása közben, a
konfliktusok feloldása és a `git rebase --continue` futtatása után a
rebase-nek meg kellene nyitnia egy szerkesztőt, és meg kellene kérnie a
felhasználót a commit-üzenet frissítésére. A 'merge' backend ezt teszi,
míg az 'apply' backend vakon alkalmazza az eredeti commit-üzenetet.

[[_miscellaneous_differences]]
Egyéb eltérések
~~~~~~~~~~~~~~~

Van még néhány további viselkedésbeli eltérés, amelyet a legtöbben
valószínűleg lényegtelennek tartanának, de a teljesség kedvéért itt
említésre kerülnek:

* Reflog: A két backend eltérő megfogalmazást használ a reflogban
  végzett változtatások leírásakor, bár mindkettő használja a "rebase"
  szót.

* Folyamat-, informatív és hibaüzenetek: A két backend kissé eltérő
  folyamat- és informatív üzeneteket ad. Emellett az apply backend a
  hibaüzeneteket (mint például a "Your files would be overwritten...")
  a stdoutra írja, míg a merge backend a stderrre írja őket.

* Állapotkönyvtárak: A két backend eltérő könyvtárakban tartja az
  állapotát a `.git/` alatt.

include::merge-strategies.adoc[]

NOTES
-----

Meg kell értened annak a következményeit, ha egy `git rebase`-t egy olyan
repository-n használsz, amelyet megosztasz másokkal. Lásd még lentebb a
RECOVERING FROM UPSTREAM REBASE szakaszt.

Amikor a rebase fut, először végrehajt egy `pre-rebase` hookot, ha létezik
ilyen. Ezt a hookot használhatod épségellenőrzésekhez, és a rebase
elutasításához, ha az nem megfelelő. Egy példáért lásd a `pre-rebase` hook
szkript sablonját.

A befejezés után a `<branch>` lesz az aktuális branch.

INTERACTIVE MODE
----------------

Az interaktív rebase-elés azt jelenti, hogy lehetőséged van szerkeszteni a
rebase-elt commitokat. Átrendezheted a commitokat, és el is
távolíthatod őket (kigyomlálva a hibás vagy egyéb nemkívánatos
patcheket).

Az interaktív mód a következő típusú munkafolyamathoz készült:

1. legyen egy csodálatos ötleted
2. hackelj a kódon
3. készíts elő egy sorozatot beküldésre
4. küldd be

ahol a 2. pont az alábbiak több példányából áll

a) szokásos használat

 1. fejezz be valamit, ami megér egy commitot
 2. commitold

b) független javítás (fixup)

 1. vedd észre, hogy valami nem működik
 2. javítsd ki
 3. commitold

Néha a b.2.-ben javított dolgot nem lehet amendelni ahhoz a nem egészen
tökéletes commithoz, amit javít, mert az a commit egy patch-sorozat
mélyén van eltemetve. Pontosan erre való az interaktív rebase: rengeteg
"a" és "b" után használd, a commitok átrendezésével és szerkesztésével,
valamint több commit egybe squashelésével.

Indítsd el az utolsó committal, amelyet változatlanul szeretnél
megtartani:

	git rebase -i <after-this-commit>

Megnyílik egy szerkesztő az aktuális brancheden lévő összes committal
(a merge-commitokat figyelmen kívül hagyva), amelyek a megadott commit
után következnek. A listában a commitokat kedved szerint átrendezheted,
és el is távolíthatod őket. A lista körülbelül így néz ki:

-------------------------------------------
pick deadbee The oneline of this commit
pick fa1afe1 The oneline of the next commit
...
-------------------------------------------

Az oneline leírások kizárólag a te örömödre szolgálnak; a 'git rebase' nem
ezeket nézi, hanem a commit-neveket ("deadbee" és "fa1afe1" ebben a
példában), ezért ne töröld vagy szerkeszd a neveket.

A "pick" parancs "edit" parancsra cserélésével megmondhatod a `git
rebase`-nek, hogy álljon meg az adott commit alkalmazása után, hogy
szerkeszthesd a fájlokat és/vagy a commit-üzenetet, amendelhesd a
commitot, és folytathasd a rebase-t.

A rebase megszakításához (ugyanúgy, ahogy egy "edit" parancs is tenné,
de anélkül, hogy előbb bármelyik commitot cherry-pickelnéd), használd a
"break" parancsot.

Ha csupán egy commit üzenetét szeretnéd szerkeszteni, cseréld a "pick"
parancsot a "reword" parancsra.

Egy commit eldobásához cseréld a "pick" parancsot "drop"-ra, vagy
egyszerűen töröld a megfelelő sort.

Ha két vagy több commitot szeretnél eggyé összevonni, cseréld a "pick"
parancsot a második és az azt követő commitoknál "squash"-ra vagy
"fixup"-ra. Ha a commitoknak eltérő szerzőik voltak, az összevont commit
az első commit szerzőjének lesz tulajdonítva. Az összevont commithoz
javasolt commit-üzenet az első commit üzenetének és a "squash"
parancsokkal jelölt commitok üzeneteinek összefűzése, kihagyva a
"fixup" parancsokkal jelölt commitok üzeneteit, kivéve, ha "fixup -c" van
használva. Ebben az esetben a javasolt commit-üzenet kizárólag a
"fixup -c" commit üzenete, és megnyílik egy szerkesztő, amely lehetővé
teszi az üzenet szerkesztését. A "fixup -c" commit tartalma (a patch-e)
továbbra is bekerül az összevont commitba. Ha több "fixup -c" commit is
van, az utolsó üzenete kerül felhasználásra. A "fixup -C" is
használható, hogy ugyanezt a viselkedést kapd, mint a "fixup -c"
esetén, csak szerkesztő megnyitása nélkül.

A `git rebase` megáll, amikor a "pick" "edit"-re lett cserélve, vagy
amikor egy parancs merge-hibák miatt sikertelen. Amikor végeztél a
szerkesztéssel és/vagy a konfliktusok feloldásával, a `git rebase
--continue` paranccsal folytathatod.

Tegyük fel például, hogy át szeretnéd rendezni az utolsó 5 commitot úgy,
hogy ami `HEAD~4` volt, az legyen az új `HEAD`. Ennek eléréséhez a `git
rebase`-t így hívnád meg:

----------------------
$ git rebase -i HEAD~5
----------------------

Majd helyezd át az első patchet a lista végére.

Előfordulhat, hogy merge-commitokat szeretnél újra létrehozni, például ha
a következőhöz hasonló történeted van:

------------------
           X
            \
         A---M---B
        /
---o---O---P---Q
------------------

Tegyük fel, hogy az "A"-nál kezdődő mellékbranchet szeretnéd "Q"-ra
rebase-elni. Győződj meg róla, hogy az aktuális `HEAD` "B", majd hívd
meg a következőt

-----------------------------
$ git rebase -i -r --onto Q O
-----------------------------

A commitok átrendezése és szerkesztése rendszerint teszteletlen köztes
lépéseket hoz létre. Érdemes lehet ellenőrizni, hogy a történet
szerkesztése nem tört-e el semmit, egy teszt futtatásával, vagy
legalább a történet köztes pontjain való újrafordítással, az "exec"
parancs (rövidítése: "x") használatával. Ezt egy ehhez hasonló todo
lista létrehozásával teheted meg:

-------------------------------------------
pick deadbee Implement feature XXX
fixup f1a5c00 Fix to feature XXX
exec make
pick c0ffeee The oneline of the next commit
edit deadbab The oneline of the commit after
exec cd subdir; make test
...
-------------------------------------------

Az interaktív rebase megáll, amikor egy parancs sikertelen (azaz nem
0-s státusszal lép ki), hogy lehetőséged legyen a probléma
kijavítására. A `git rebase --continue` paranccsal folytathatod.

Az "exec" parancs egy shellben (az alapértelmezettben, ami általában a
/bin/sh) indítja el a parancsot, így használhatsz shell-funkciókat (mint
a "cd", ">", ";" ...). A parancs a munkafa gyökeréből fut.

----------------------------------
$ git rebase -i --exec "make test"
----------------------------------

Ez a parancs lehetővé teszi annak ellenőrzését, hogy a köztes commitok
lefordíthatók-e. A todo lista így alakul:

--------------------
pick 5928aea one
exec make test
pick 04d0fda two
exec make test
pick ba46169 three
exec make test
pick f4593f9 four
exec make test
--------------------

SPLITTING COMMITS
-----------------

Interaktív módban a commitokat megjelölheted az "edit" művelettel. Ez
azonban nem feltétlenül jelenti azt, hogy a `git rebase` ennek a
szerkesztésnek az eredményeként pontosan egy commitot vár. Sőt,
visszavonhatod a commitot, vagy hozzáadhatsz más commitokat is. Ez
felhasználható egy commit kettéosztására:

- Indíts egy interaktív rebase-t a `git rebase -i <commit>^` paranccsal,
  ahol a `<commit>` a szétosztani kívánt commit. Valójában bármilyen
  commit-tartomány megteszi, amíg tartalmazza azt a commitot.

- Jelöld meg a szétosztani kívánt commitot az "edit" művelettel.

- Amikor annak a commitnak a szerkesztésére kerül a sor, hajtsd végre a
  `git reset HEAD^` parancsot. A hatása az, hogy a `HEAD` egy committal
  visszatekerésre kerül, és az index is követi. A munkakönyvtár azonban
  változatlan marad.

- Most add hozzá az indexhez azokat a változtatásokat, amelyeket az
  első commitban szeretnél. Ehhez használhatod a `git add`-ot
  (esetleg interaktívan), a `git gui`-t (vagy mindkettőt).

- Commitold a most aktuális indexet a megfelelő commit-üzenettel.

- Ismételd meg az utolsó két lépést, amíg a munkakönyvtár tiszta nem
  lesz.

- Folytasd a rebase-t a `git rebase --continue` paranccsal.

Ha nem vagy teljesen biztos abban, hogy a köztes revíziók konzisztensek
(lefordulnak, átmennek a teszteken stb.), a `git stash`-t kellene
használnod a még nem commitolt változtatások félretételéhez minden
commit után, teszteld, és amendeld a commitot, ha javításokra van
szükség.


RECOVERING FROM UPSTREAM REBASE
-------------------------------

Egy olyan branch rebase-elése (vagy bármilyen más formában való
átírása), amelyre mások munkája épül, rossz ötlet: mindenki, aki
downstream van hozzá képest, kénytelen manuálisan kijavítani a saját
történetét. Ez a szakasz elmagyarázza, hogyan végezhető el a javítás a
downstream nézőpontjából. Az igazi megoldás azonban az volna, ha
eleve elkerülnénk az upstream rebase-elését.

Szemléltetésképpen tegyük fel, hogy olyan helyzetben vagy, ahol valaki
egy 'subsystem' branchet fejleszt, te pedig egy 'topic'-on dolgozol,
amely ettől a 'subsystem'-től függ. Egy ehhez hasonló történettel
végezhetsz:

------------
    o---o---o---o---o---o---o---o  master
	 \
	  o---o---o---o---o  subsystem
			   \
			    *---*---*  topic
------------

Ha a 'subsystem' rebase-elve lesz a 'master'-hez, a következő történik:

------------
    o---o---o---o---o---o---o---o  master
	 \			 \
	  o---o---o---o---o	  o'--o'--o'--o'--o'  subsystem
			   \
			    *---*---*  topic
------------

Ha most a szokásos módon folytatod a fejlesztést, és végül merge-eled a
'topic'-ot a 'subsystem'-be, a 'subsystem'-ből származó commitok örökre
duplikáltak maradnak:

------------
    o---o---o---o---o---o---o---o  master
	 \			 \
	  o---o---o---o---o	  o'--o'--o'--o'--o'--M	 subsystem
			   \			     /
			    *---*---*-..........-*--*  topic
------------

Az ilyen duplikátumokat általában rossz szemmel nézik, mert eltömítik a
történetet, megnehezítve annak követését. A rendrakáshoz a 'topic'-on
lévő commitokat át kell helyezned az új 'subsystem'-csúcsra, azaz
rebase-elned kell a 'topic'-ot. Ez láncreakciót indít el: mindenki, aki
downstream van a 'topic'-hoz képest, szintén kénytelen lesz
rebase-elni, és így tovább!

Kétféle javítás létezik, ezeket az alábbi alszakaszok tárgyalják:

Könnyű eset: a változtatások szó szerint ugyanazok.::

	Ez akkor történik, ha a 'subsystem' rebase-elése egy egyszerű
	rebase volt, és nem voltak konfliktusok.

Nehéz eset: a változtatások nem ugyanazok.::

	Ez akkor történik, ha a 'subsystem' rebase-elése során
	konfliktusok voltak, vagy az `--interactive` opció volt
	használva commitok kihagyására, szerkesztésére, squasholására
	vagy fixupolására; vagy ha az upstream a `commit --amend`, a
	`reset`, vagy egy teljes történetátíró parancs, mint például a
	https://github.com/newren/git-filter-repo[`filter-repo`], valamelyikét
	használta.


[[_the_easy_case]]
A könnyű eset
~~~~~~~~~~~~~

Ez csak akkor működik, ha a 'subsystem'-en végzett változtatások (a
diff-tartalom alapján képzett patch ID-k) szó szerint ugyanazok a
'subsystem' rebase-elése előtt és után.

Ebben az esetben a javítás egyszerű, mert a 'git rebase' tudja, hogy ki
kell hagynia azokat a változtatásokat, amelyek már jelen vannak az új
upstreamben (kivéve, ha a `--reapply-cherry-picks` meg van adva). Tehát
ha ezt mondod (feltéve, hogy a 'topic'-on vagy)

------------
    $ git rebase subsystem
------------
a javított történettel fogsz végezni

------------
    o---o---o---o---o---o---o---o  master
				 \
				  o'--o'--o'--o'--o'  subsystem
						   \
						    *---*---*  topic
------------


[[_the_hard_case]]
A nehéz eset
~~~~~~~~~~~~

A dolgok bonyolultabbá válnak, ha a 'subsystem' változtatásai nem
pontosan felelnek meg a rebase előttieknek.

NOTE: Bár egy "easy case" (könnyű eset szerinti) helyreállítás néha úgy
      tűnik, hogy sikeres a nehéz esetben is, nem szándékolt
      következményei lehetnek. Például egy commit, amelyet a `git
      rebase --interactive` paranccsal távolítottak el, **fel fog
      támadni**!

Az ötlet az, hogy manuálisan megmondjuk a `git rebase`-nek, "hol ért
véget a régi 'subsystem', és hol kezdődött a 'topic'-od", azaz mi volt a
közöttük lévő régi merge-alap. Meg kell találnod egy módot, hogy
megnevezd a régi 'subsystem' utolsó commitját, például:

* A 'subsystem' reflogjával: egy `git fetch` után a 'subsystem' régi
  csúcsa a `subsystem@{1}`-nél van. A további fetchek növelik ezt a
  számot. (Lásd: linkgit:git-reflog[1].)

* A 'topic' csúcsához viszonyítva: tudva, hogy a 'topic'-odnak három
  commitja van, a 'subsystem' régi csúcsának `topic~3`-nak kell lennie.

Ezután áthelyezheted a régi `subsystem..topic`-ot az új csúcsra, ha ezt
mondod (a reflog-esetre, feltéve, hogy már a 'topic'-on vagy):

------------
    $ git rebase --onto subsystem subsystem@{1}
------------

Egy "hard case" (nehéz eset szerinti) helyreállítás láncreakciója
különösen rossz: 'mindenkinek', aki downstream van a 'topic'-hoz
képest, most már szintén el kell végeznie egy "hard case"
helyreállítást!

REBASING MERGES
---------------

Az interaktív rebase parancs eredetileg egyedi patch-sorozatok
kezelésére lett megtervezve. Ennélfogva van értelme kizárni a
merge-commitokat a todo listából, mivel a fejlesztő esetleg
merge-elte a branchen való munka közben az akkor aktuális
`master`-t, csak azért, hogy végül az összes commitot a `master`-re
rebase-elje (kihagyva a merge-commitokat).

Vannak azonban jogos okok, amiért egy fejlesztő újra létre akarja
hozni a merge-commitokat: hogy megőrizze a branch-struktúrát (vagy a
"commit-topológiát") több, egymással összefüggő branchen való munka
esetén.

A következő példában a fejlesztő egy topic branchen dolgozik, amely
refaktorálja a gombok definiálásának módját, valamint egy másik topic
branchen, amely ezt a refaktorálást felhasználva valósít meg egy
"Report a bug" gombot. A `git log --graph --format=%s -5` kimenete
valahogy így nézhet ki:

------------
*   Merge branch 'report-a-bug'
|\
| * Add the feedback button
* | Merge branch 'refactor-button'
|\ \
| |/
| * Use the Button class for all buttons
| * Extract a generic Button class from the DownloadButton one
------------

A fejlesztő szeretné ezeket a commitokat egy újabb `master`-re
rebase-elni, miközben megőrzi a branch-topológiát, például akkor, ha az
első topic branch várhatóan sokkal korábban kerül integrálásra a
`master`-be, mint a második, mondjuk azért, hogy feloldja a
DownloadButton osztályon végzett, a `master`-be bekerült
változtatásokkal való merge-konfliktusokat.

Ez a rebase a `--rebase-merges` opcióval végezhető el. Egy ehhez
hasonló todo listát fog generálni:

------------
label onto

# Branch: refactor-button
reset onto
pick 123456 Extract a generic Button class from the DownloadButton one
pick 654321 Use the Button class for all buttons
label refactor-button

# Branch: report-a-bug
reset refactor-button # Use the Button class for all buttons
pick abcdef Add the feedback button
label report-a-bug

reset onto
merge -C a1b2c3 refactor-button # Merge 'refactor-button'
merge -C 6f5e4d report-a-bug # Merge 'report-a-bug'
------------

Egy szokásos interaktív rebase-hez képest itt a `pick` parancsok mellett
`label`, `reset` és `merge` parancsok is vannak.

A `label` parancs egy címkét társít az aktuális HEAD-hez, amikor az a
parancs végrehajtásra kerül. Ezek a címkék munkafa-lokális
referenciákként (`refs/rewritten/<label>`) jönnek létre, amelyek
törlésre kerülnek, amikor a rebase befejeződik. Ily módon az ugyanahhoz
a repository-hoz kapcsolódó több munkafában végzett rebase-műveletek
nem zavarják egymást. Ha a `label` parancs sikertelen, azonnal
újraütemezésre kerül, egy hasznos üzenettel arról, hogyan kell
folytatni.

A `reset` parancs visszaállítja a HEAD-et, az indexet és a munkafát a
megadott revízióra. Hasonló egy `exec git reset --hard <label>`
parancshoz, de megtagadja a nem követett fájlok felülírását. Ha a
`reset` parancs sikertelen, azonnal újraütemezésre kerül, egy hasznos
üzenettel arról, hogyan kell szerkeszteni a todo listát (ez jellemzően
akkor fordul elő, ha egy `reset` parancs manuálisan lett beillesztve a
todo listába, és elgépelést tartalmaz).

A `merge` parancs a megadott revíziót/revíziókat merge-eli abba, ami
éppen akkor a HEAD. A `-C <original-commit>` használatával a megadott
merge-commit commit-üzenete kerül felhasználásra. Ha a `-C` kisbetűs
`-c`-re változik, az üzenet egy szerkesztőben nyílik meg egy sikeres
merge után, hogy a felhasználó szerkeszthesse az üzenetet.

Ha egy `merge` parancs bármilyen más okból sikertelen, mint
merge-konfliktus (azaz amikor a merge-művelet el sem indult), azonnal
újraütemezésre kerül.

Alapértelmezésben a `merge` parancs az `ort` merge-stratégiát használja
a szokásos merge-ekhez, és az `octopus`-t az octopus merge-ekhez.
Megadható egy alapértelmezett stratégia az összes merge-hez a
`--strategy` argumentum használatával a rebase meghívásakor, vagy
felülbírálhatók konkrét merge-ek az interaktív parancslistában egy
`exec` parancs használatával, amely a `git merge`-öt hívja meg
explicit módon egy `--strategy` argumentummal. Vedd figyelembe, hogy
amikor így, explicit módon hívod meg a `git merge`-öt, kihasználhatod
azt a tényt, hogy a címkék munkafa-lokális referenciák (például a
`refs/rewritten/onto` referencia felelne meg az `onto` címkének),
hogy hivatkozz azokra a branchekre, amelyeket merge-elni szeretnél.

Megjegyzés: az első parancs (`label onto`) megcímkézi azt a revíziót,
amelyre a commitok rebase-elve lesznek; az `onto` név csupán egy
konvenció, utalva a `--onto` opcióra.

Az is lehetséges, hogy teljesen új merge-commitokat vezess be a
semmiből, egy `merge <merge-head>` alakú parancs hozzáadásával. Ez az
alak egy próba-commit-üzenetet fog generálni, és mindig megnyit egy
szerkesztőt, hogy a felhasználó szerkeszthesse azt. Ez akkor lehet
hasznos, ha például kiderül, hogy egy topic branch egynél több
problémát old meg, és két vagy akár több topic branchre szeretnénk
szétosztani. Tekintsük ezt a todo listát:

------------
pick 192837 Switch from GNU Makefiles to CMake
pick 5a6c7e Document the switch to CMake
pick 918273 Fix detection of OpenSSL in CMake
pick afbecd http: add support for TLS v1.3
pick fdbaec Fix detection of cURL in CMake on Windows
------------

Az ebben a listában szereplő egyetlen, CMake-hez nem kapcsolódó commitot
nagyon is motiválhatta a CMake-re való áttérés által bevezetett hibák
kijavításán való munka, de az egy másik problémát old meg. Ahhoz, hogy
ezt a branchet két topic branchre osszuk szét, a todo lista így
szerkeszthető:

------------
label onto

pick afbecd http: add support for TLS v1.3
label tlsv1.3

reset onto
pick 192837 Switch from GNU Makefiles to CMake
pick 918273 Fix detection of OpenSSL in CMake
pick fdbaec Fix detection of cURL in CMake on Windows
pick 5a6c7e Document the switch to CMake
label cmake

reset onto
merge tlsv1.3
merge cmake
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/rebase.adoc[]
include::config/sequencer.adoc[]

GIT
---
A linkgit:git[1] csomag része
