git-log(1)
==========

NAME
----
git-log - Commit-naplók megjelenítése


SYNOPSIS
--------
[synopsis]
git log [<options>] [<revision-range>] [[--] <path>...]

DESCRIPTION
-----------
Megjeleníti a commit-naplókat.

:git-log: 1
include::rev-list-description.adoc[]

A parancs elfogadja a linkgit:git-rev-list[1] parancsra alkalmazható
kapcsolókat annak szabályozására, hogy mi és hogyan jelenjen meg, valamint
a linkgit:git-diff[1] parancsra alkalmazható kapcsolókat annak
szabályozására, hogyan jelenjenek meg az egyes commitok által bevezetett
változtatások.


OPTIONS
-------

`--follow`::
	Egy fájl előzményeinek listázása az átnevezéseken túl is
	(csak egyetlen fájlnál működik).

`--no-decorate`::
`--decorate[=(short|full|auto|no)]`::
	Kiírja a megjelenített commitok ref-neveit. A lehetséges értékek:
+
--
`short`;; a `refs/heads/`, `refs/tags/` és `refs/remotes/` ref-név-előtagok
	nem kerülnek kiírásra.
`full`;; a teljes ref-nevet (az előtaggal együtt) írja ki.
`auto`;; ha a kimenet terminálra megy, a ref-nevek úgy jelennek meg,
	mintha a `short` lenne megadva, egyébként nem jelennek meg
	ref-nevek.
--
+
A `--decorate` kapcsoló a `--decorate=short` rövidítése. Ha be van állítva, a
`log.decorate` konfigurációs értékre áll alapból, egyébként az `auto`-ra.

`--decorate-refs=<pattern>`::
`--decorate-refs-exclude=<pattern>`::
	Minden jelölt referenciára: ne használd díszítéshez, ha illeszkedik a
	`--decorate-refs-exclude`-nak adott _<pattern>_ paraméterek
	bármelyikére, vagy ha nem illeszkedik a `--decorate-refs`-nek adott
	_<pattern>_ paraméterek egyikére sem.
	A `log.excludeDecoration` konfigurációs beállítás lehetővé teszi
	referenciák kizárását a díszítésből, de egy explicit `--decorate-refs`
	minta felülírja a `log.excludeDecoration`-beli találatot.
+
Ha ezen kapcsolók és konfigurációs beállítások egyike sincs megadva, akkor a
referenciák akkor kerülnek díszítésként felhasználásra, ha illeszkednek a
`HEAD`, `refs/heads/`, `refs/remotes/`, `refs/stash/` vagy `refs/tags/`
mintára.

`--clear-decorations`::
	Megadva ez a kapcsoló törli az összes korábbi `--decorate-refs` vagy
	`--decorate-refs-exclude` kapcsolót, és fellazítja az alapértelmezett
	díszítésszűrőt, hogy az minden referenciát tartalmazzon. Ez a kapcsoló
	érvényesül, ha a `log.initialDecorationSet` konfigurációs érték `all`-ra
	van állítva.

`--source`::
	Kiírja a parancssorban megadott azon ref-nevet, amelyen keresztül az
	egyes commitokat elérte.

`--mailmap`::
`--no-mailmap`::
`--use-mailmap`::
`--no-use-mailmap`::
	A mailmap fájl használata a szerzők és committerek neveinek és e-mail-
	címeinek kanonikus valódi nevekre és e-mail-címekre való leképezéséhez.
	Lásd linkgit:git-shortlog[1].

`--full-diff`::
	E kapcsoló nélkül a `git log -p <path>...` azokat a commitokat
	mutatja, amelyek érintik a megadott elérési utakat, és a diffeket
	ugyanezen megadott elérési utakról.  Ezzel a teljes diff jelenik meg a
	megadott elérési utakat érintő commitokra; ez azt jelenti, hogy a
	"`<path>...`" csak a commitokat korlátozza, és nem korlátozza a diffet
	ezekre a commitokra.
+
Vedd figyelembe, hogy ez minden diff-alapú kimeneti típust érint, pl. a
`--stat` stb. által előállítottakat.

`--log-size`::
	Minden commitnál beszúr egy `log size <number>` sort a kimenetbe, ahol
	a _<number>_ az adott commit üzenetének hossza bájtban. Célja azon
	eszközök felgyorsítása, amelyek a `git log` kimenetéből olvassák a
	naplóüzeneteket, azáltal, hogy előre le tudnak foglalni helyet.

include::line-range-options.adoc[]

_<revision-range>_::
	Csak a megadott revíziótartományba eső commitokat mutatja.  Ha nincs
	megadva _<revision-range>_, az alapértelmezése `HEAD` (azaz az aktuális
	commithoz vezető teljes előzmény).  Az `origin..HEAD` az összes olyan
	commitot jelöli, amely elérhető az aktuális commitból (azaz a
	`HEAD`-ből), de az `origin`-ból nem. A _<revision-range>_ leírási
	módjainak teljes listájáért lásd a linkgit:gitrevisions[7] 'Specifying
	Ranges' szakaszát.

`[--] <path>...`::
	Csak azokat a commitokat mutatja, amelyek elegendők annak
	magyarázatához, hogyan jöttek létre a megadott elérési utakra
	illeszkedő fájlok.  A részletekért és a további egyszerűsítési
	módokért lásd lentebb a 'History Simplification' szakaszt.
+
Az elérési utak elé `--`-t kell tenni, hogy elváljanak a kapcsolóktól
vagy a revíziótartománytól, ha félreértés adódhat.

include::rev-list-options.adoc[]

include::pretty-formats.adoc[]

DIFF FORMATTING
---------------

Alapértelmezés szerint a `git log` nem állít elő diff-kimenetet. Az alábbi
kapcsolókkal megjeleníthetők az egyes commitok által végzett változtatások.

Vedd figyelembe, hogy hacsak nincs explicit módon megadva a `--diff-merges`
valamely változata (beleértve a rövid `-m`, `-c`, `--cc` és `--dd`
kapcsolókat), a merge-commitok nem mutatnak diffet, még akkor sem, ha egy
diff-formátum, például a `--patch` van kiválasztva, és nem illeszkednek az
olyan keresési kapcsolókra sem, mint a `-S`. Kivétel, amikor a
`--first-parent` van használatban; ilyenkor a `first-parent` az
alapértelmezett formátum a merge-commitokhoz.

:git-log: 1
:diff-merges-default: `off`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]

EXAMPLES
--------
`git log --no-merges`::

	A teljes commit-előzmény megjelenítése, de a merge-ek kihagyásával

`git log v2.6.12.. include/scsi drivers/scsi`::

	Az összes olyan commit megjelenítése a 'v2.6.12' verzió óta, amely
	módosított bármely fájlt az `include/scsi` vagy a `drivers/scsi`
	alkönyvtárban

`git log --since="2 weeks ago" -- gitk`::

	A `gitk` fájlon az elmúlt két hétben történt változások megjelenítése.
	A `--` szükséges a `gitk` nevű *branch*-csel való összekeverés
	elkerüléséhez

`git log --name-status release..test`::

	Azon commitok megjelenítése, amelyek a "`test`" branchen vannak, de a
	"`release`" branchen még nincsenek, az egyes commitok által módosított
	elérési utak listájával együtt.

`git log --follow builtin/rev-list.c`::

	Megjeleníti azokat a commitokat, amelyek módosították a
	`builtin/rev-list.c`-t, beleértve azokat is, amelyek azelőtt
	történtek, hogy a fájl a jelenlegi nevét kapta.

`git log --branches --not --remotes=origin`::

	Megjeleníti az összes olyan commitot, amely valamelyik lokális
	branchen rajta van, de az `origin` egyik remote-tracking branchén sem
	(amid megvan, de az originnek nincs).

`git log master --not --remotes=*/master`::

	Megjeleníti az összes olyan commitot, amely a lokális masteren rajta
	van, de egyik remote repository master branchén sincs.

`git log -p -m --first-parent`::

	Megjeleníti az előzményt a változtatások diffjeivel együtt, de csak a
	``fő branch'' szemszögéből, kihagyva a merge-elt branchekből származó
	commitokat, és megjelenítve a merge-ek által bevezetett változtatások
	teljes diffjeit.
	Ennek csak akkor van értelme, ha szigorú elvet követsz: minden topic
	branchet merge-elsz, miközben egyetlen integrációs branchen maradsz.

`git log -L '/int main/',/^}/:main.c`::

	Megmutatja, hogyan fejlődött időben a `main()` függvény a `main.c`
	fájlban.

`git log -3`::

	A megjelenítendő commitok számát 3-ra korlátozza.

DISCUSSION
----------

include::i18n.adoc[]

CONFIGURATION
-------------

Az alapvető változókért lásd linkgit:git-config[1], a diff-generálással
kapcsolatos beállításokért pedig linkgit:git-diff[1].

`format.pretty`::
	A `--format` kapcsoló alapértelmezése.  (Lásd fentebb a 'Pretty
	Formats' szakaszt.)  Az alapértelmezése `medium`.

`i18n.logOutputEncoding`::
	A naplók megjelenítésekor használandó kódolás.  (Lásd fentebb a
	'Discussion' szakaszt.)  Ha be van állítva, az `i18n.commitEncoding`
	értékére áll alapból, egyébként UTF-8-ra.

include::includes/cmd-config-section-rest.adoc[]

include::config/log.adoc[]

include::config/notes.adoc[]

GIT
---
A linkgit:git[1] csomag része
