git-format-patch(1)
===================

NAME
----
git-format-patch - Patchek előkészítése e-mailes beküldéshez


SYNOPSIS
--------
[synopsis]
git format-patch [-k] [(-o|--output-directory) <dir> | --stdout]
		   [--no-thread | --thread[=<style>]]
		   [(--attach|--inline)[=<boundary>] | --no-attach]
		   [-s | --signoff]
		   [--signature=<signature> | --no-signature]
		   [--signature-file=<file>]
		   [-n | --numbered | -N | --no-numbered]
		   [--start-number <n>] [--numbered-files]
		   [--in-reply-to=<message-id>] [--suffix=.<sfx>]
		   [--ignore-if-in-upstream] [--always]
		   [--cover-from-description=<mode>]
		   [--rfc[=<rfc>]] [--subject-prefix=<subject-prefix>]
		   [(--reroll-count|-v) <n>]
		   [--to=<email>] [--cc=<email>]
		   [--[no-]cover-letter] [--quiet]
		   [--commit-list-format=<format-spec>]
		   [--[no-]encode-email-headers]
		   [--no-notes | --notes[=<ref>]]
		   [--interdiff=<previous>]
		   [--range-diff=<previous> [--creation-factor=<percent>]]
		   [--filename-max-length=<n>]
		   [--progress]
		   [<common-diff-options>]
		   [ <since> | <revision-range> ]

DESCRIPTION
-----------

Minden non-merge commithoz elkészíti a "patch"-ét
egyetlen "üzenetben" commitonként, egy UNIX postafiókhoz hasonló formátumban.
A parancs kimenete kényelmesen használható e-mailes beküldéshez vagy
a `git am`-mal együtt.

A parancs által generált "üzenet" három részből áll:

* Egy rövid metaadat-fejléc, amely `From <commit>`-tal kezdődik,
  egy rögzített `Mon Sep 17 00:00:00 2001` időbélyeggel, hogy az olyan
  programok, mint a `file`(1), felismerjék, hogy a fájl e parancs
  kimenete, valamint a szerző identitását és dátumát rögzítő mezők,
  és a változtatás címe (a commit log üzenet első bekezdéséből véve).

* A commit log üzenet második és további bekezdései.

* A "patch", vagyis a `diff -p --stat` kimenete (lásd
  linkgit:git-diff[1]) a commit és a szülője között.

A log üzenetet és a patchet egy három kötőjelből álló sor választja el.

Kétféleképpen adható meg, mely commitokon dolgozzon a parancs.

1. Egyetlen commit, _<since>_, azt jelenti, hogy azok a commitok kerülnek
   kiadásra, amelyek a jelenlegi branch csúcsához vezetnek, de nincsenek
   benne abban a történetben, amely az _<since>_-hez vezet.

2. Az általános _<revision-range>_ kifejezés (lásd a linkgit:gitrevisions[7]
   'SPECIFYING REVISIONS' szekcióját) a megadott tartományban lévő
   commitokat jelenti.

Az első szabály élvez elsőbbséget egyetlen _<commit>_ esetén. A második
szabály alkalmazásához, azaz hogy a történet elejétől egészen _<commit>_-ig
mindent formázzon, használja a `--root` opciót: `git format-patch
--root <commit>`. Ha csak magát az _<commit>_-et szeretné formázni,
ezt a `git format-patch -1 <commit>` paranccsal teheti meg.

Alapértelmezés szerint minden kimeneti fájl 1-től sorban számozott, és
a commit-üzenet első sorát (elérésiút-biztonságra tisztítva) használja
fájlnévként. A `--numbered-files` opcióval a kimeneti fájlnevek csak
számok lesznek, a commit első sora nélkül. A kimeneti fájlok neve a
standard kimenetre kerül kiírásra, hacsak a `--stdout` opció nincs megadva.

Ha a `-o` meg van adva, a kimeneti fájlok _<dir>_-ban jönnek létre.
Egyébként az aktuális munkakönyvtárban jönnek létre. Az alapértelmezett
útvonal a `format.outputDirectory` konfigurációs opcióval állítható be.
A `-o` opció elsőbbséget élvez a `format.outputDirectory`-val szemben.
Ahhoz, hogy a patcheket az aktuális munkakönyvtárban tárolja akkor is,
ha a `format.outputDirectory` máshova mutat, használja a `-o .` opciót.
Minden könyvtárkomponens létre lesz hozva.

Alapértelmezés szerint egyetlen patch tárgya "[PATCH] ", amelyet a
commit-üzenetből az első üres sorig összefűzött sorok követnek (lásd
a linkgit:git-commit[1] DISCUSSION szekcióját).

Ha több patch kerül kiadásra, a tárgy-előtag helyette "[PATCH n/m] "
lesz. Ahhoz, hogy egyetlen patch esetén is kikényszerítse az 1/1
hozzáadását, használja a `-n` opciót. A patch-számok tárgyból való
kihagyásához használja a `-N` opciót.

Ha a `--thread` meg van adva, a `git-format-patch` `In-Reply-To` és
`References` fejléceket generál, hogy a második és további patch-emailek
válasznak tűnjenek az első e-mailre; ez emellett egy `Message-ID` fejlécet
is generál, amelyre hivatkozhat.

OPTIONS
-------
:git-format-patch: 1
include::diff-options.adoc[]

`-<n>`::
	A legfelső _<n>_ commitból készít patcheket.

`-o <dir>`::
`--output-directory=<dir>`::
	_<dir>_-t használja az eredményfájlok tárolására, az aktuális
	munkakönyvtár helyett.

`-n`::
`--numbered`::
	A kimenetet '[PATCH n/m]' formátumban nevezi el, egyetlen patch
	esetén is.

`-N`::
`--no-numbered`::
	A kimenetet '[PATCH]' formátumban nevezi el.

`--start-number <n>`::
	A patchek számozását _<n>_-nél kezdi, 1 helyett.

`--numbered-files`::
	A kimeneti fájlnevek egyszerű számsorozat lesznek, a commit
	alapértelmezetten hozzáfűzött első sora nélkül.

`-k`::
`--keep-subject`::
	Nem törli/adja hozzá a '[PATCH]'-et a commit log üzenet első
	sorához.

`-s`::
`--signoff`::
	Egy `Signed-off-by` trailert ad hozzá a commit-üzenethez, saját
	committer-identitását használva.
	További információért lásd a signoff opciót a linkgit:git-commit[1]-ben.

`--stdout`::
	Az összes commitot a standard kimenetre írja ki mbox formátumban,
	ahelyett hogy fájlt hozna létre mindegyikhez.

`--attach[=<boundary>]`::
	multipart/mixed mellékletet hoz létre, amelynek első része a
	commit-üzenet, a második része pedig maga a patch,
	`Content-Disposition: attachment` fejléccel.

`--no-attach`::
	Letiltja a melléklet létrehozását, felülbírálva a konfigurációs
	beállítást.

`--inline[=<boundary>]`::
	multipart/mixed mellékletet hoz létre, amelynek első része a
	commit-üzenet, a második része pedig maga a patch,
	`Content-Disposition: inline` fejléccel.

`--thread[=<style>]`::
`--no-thread`::
	Szabályozza az `In-Reply-To` és `References` fejlécek hozzáadását,
	amelyek azt eredményezik, hogy a második és további e-mailek
	válasznak tűnjenek az elsőre. Azt is szabályozza, hogy generálódik-e
	`Message-ID` fejléc, amelyre hivatkozhatnak.
+
Az opcionális _<style>_ argumentum lehet `shallow` vagy `deep`. A
`shallow` szálazás minden e-mailt a sorozat fejére válaszol, ahol a
fej a cover letterből, a `--in-reply-to`-ból, és az első patch-e-mailből
kerül kiválasztásra, ebben a sorrendben. A `deep` szálazás minden
e-mailt az előzőre válaszol.
+
Az alapértelmezés `--no-thread`, hacsak a `format.thread` konfiguráció
be nincs állítva. A `--thread` argumentum nélkül egyenértékű a
`--thread=shallow`-val.
+
Vegye figyelembe, hogy a `git send-email` alapértelmezetten maga
szálazza az e-maileket. Ha azt szeretné, hogy a `git format-patch`
gondoskodjon a szálazásról, gondoskodnia kell arról, hogy a szálazás
le legyen tiltva a `git send-email`-nél.

`--in-reply-to=<message-id>`::
	Az első e-mailt (vagy `--no-thread` esetén az összes e-mailt)
	a megadott _<message-id>_-re adott válasznak tünteti fel, ami
	elkerüli, hogy a szálak megszakadjanak egy új patch-sorozat
	beküldésekor.

`--ignore-if-in-upstream`::
	Nem foglalja bele azt a patchet, amely megegyezik egy
	_<until>_.._<since>_-ben lévő committal. Ez megvizsgálja az
	összes, _<since>_-ből elérhető, de _<until>_-ból nem elérhető
	patchet, és összehasonlítja őket a generálandó patchekkel, és
	minden egyező patchet kihagy.

`--always`::
	Beleveszi azokat a commitokhoz tartozó patcheket is, amelyek nem
	vezetnek be semmilyen változást, és amelyeket alapértelmezetten
	kihagy.

`--cover-from-description=<mode>`::
	Szabályozza, hogy a cover letter mely részei töltődnek fel
	automatikusan a branch leírásának felhasználásával.
+
_<mode>_ a következő értékeket veheti fel:

`message`;;
`default`;; a cover letter tárgya
helyőrző szöveggel töltődik fel. A cover letter törzse a branch
leírásával töltődik fel. Ez az alapértelmezett mód, ha sem konfiguráció,
sem parancssori opció nincs megadva.
`subject`;; a branch leírásának első bekezdése tölti fel a
cover letter tárgyát. A leírás fennmaradó része tölti fel a cover
letter törzsét.
`auto`;; ha a branch leírásának első bekezdése nagyobb, mint
100 bájt, akkor a mód `message` lesz, egyébként `subject` kerül
felhasználásra.
`none`;; a cover letter tárgya és törzse is helyőrző szöveggel
töltődik fel.

`--description-file=<file>`::
	A cover letter generálásához a branch leírása helyett _<file>_
	tartalmát használja.

`--subject-prefix=<subject-prefix>`::
	A szabványos '[PATCH]' előtag helyett '[<subject-prefix>]'-et
	használ a tárgysorban. Ez felhasználható egy patch-sorozat
	elnevezésére, és kombinálható a `--numbered` opcióval.
+
A `format.subjectPrefix` konfigurációs változó is használható egy
tárgy-előtag beállítására, amelyet egy adott repository összes
patchére alkalmaz. Ez gyakran hasznos olyan levelezőlistáknál,
amelyek több repository patcheit is fogadják, és felhasználható a
patchek megkülönböztetésére (pl. "PATCH my-project" értékkel).

`--filename-max-length=<n>`::
	A szabványos 64 bájt helyett a generált kimeneti fájlneveket
	körülbelül _<n>_ bájtnál vágja le (a túl kicsi értéket némán
	egy ésszerű hosszra emeli). Alapértelmezés szerint a
	`format.filenameMaxLength` konfigurációs változó értékét
	használja, vagy 64-et, ha nincs konfigurálva.

`--rfc[=<rfc>]`::
	Az _<rfc>_ karakterláncot (alapértelmezés szerint "RFC") a
	tárgy-előtag elé illeszti. Mivel a tárgy-előtag alapértelmezetten
	"PATCH", alapesetben "RFC PATCH"-et fog kapni.
+
Az RFC a "Request For Comments" rövidítése; akkor használja, ha egy
kísérleti patchet küld megvitatásra, nem alkalmazásra. A "--rfc=WIP"
szintén hasznos módja lehet annak jelzésére, hogy egy patch még nem
kész ("WIP" a "Work In Progress" rövidítése).
+
Ha a fogadó közösség konvenciója szerint egy adott extra karakterláncot
a tárgy-előtag _után_ kell elhelyezni, az _<rfc>_ karakterlánc elé
kötőjel ("`-`") tehető, jelezve, hogy az _<rfc>_ karakterlánc
hátralévő része helyette a tárgy-előtag után kerüljön hozzáfűzésre,
pl. a `--rfc='-(WIP)'` "PATCH (WIP)"-et eredményez.

`-v <n>`::
`--reroll-count=<n>`::
	A sorozatot a téma _<n>_-edik iterációjaként jelöli meg. A
	kimeneti fájlnevek elé `v<n>` kerül, és a tárgy-előtaghoz
	(alapértelmezetten "PATCH", de a `--subject-prefix` opcióval
	konfigurálható) `v<n>` kerül hozzáfűzésre. Pl. a
	`--reroll-count=4` a `v4-0001-add-makefile.patch` fájlt
	eredményezheti, amelyben "Subject: [PATCH v4 1/20] Add makefile"
	szerepel. Az _<n>_-nek nem kell egésznek lennie (pl. a
	`--reroll-count=4.4` vagy a `--reroll-count=4rev2` is megengedett),
	de az ilyen reroll-count használatának hátránya, hogy az előző
	verzióval szembeni range-diff/interdiff nem mondja meg pontosan,
	melyik verzióval hasonlítja össze az új iterációt.

`--to=<email>`::
	Egy `To:` fejlécet ad hozzá az e-mail fejlécekhez. Ez a
	konfigurált fejlécek mellé kerül, és többször is használható.
	A tagadott `--no-to` forma eldobja az eddig hozzáadott összes
	`To:` fejlécet (konfigurációból vagy parancssorból).

`--cc=<email>`::
	Egy `Cc:` fejlécet ad hozzá az e-mail fejlécekhez. Ez a
	konfigurált fejlécek mellé kerül, és többször is használható.
	A tagadott `--no-cc` forma eldobja az eddig hozzáadott összes
	`Cc:` fejlécet (konfigurációból vagy parancssorból).

`--from`::
`--from=<ident>`::
	_<ident>_-et használja minden e-mail `From:` fejlécében. Commit
	e-mail esetén, ha a commit szerző-identitása szövegszerűen nem
	egyezik meg a megadott _<ident>_-tel, egy `From:` fejlécet
	helyez el az üzenet törzsében az eredeti szerzővel. Ha nincs
	megadva _<ident>_, vagy ha az opció egyáltalán nincs átadva, a
	jelenlegi committer identitását használja.
+
Vegye figyelembe, hogy ez az opció csak akkor hasznos, ha ténylegesen
Ön küldi el az e-maileket, és feladóként szeretné azonosítani magát,
de meg akarja tartani az eredeti szerzőt (és a `git am` helyesen fogja
felismerni a törzsön belüli fejlécet). Vegye figyelembe azt is, hogy a
`git send-email` már elvégzi Ön helyett ezt az átalakítást, így ezt az
opciót nem szabad használni, ha az eredményt a `git send-email`-nek
adja tovább.

`--force-in-body-from`::
`--no-force-in-body-from`::
	Ha az e-mail feladója a `--from` opcióval van megadva,
	alapértelmezés szerint a commit valódi szerzőjének azonosítására
	egy törzsön belüli "From:" kerül a commit log üzenet elejére,
	ha a feladó eltér a szerzőtől. Ezzel az opcióval a törzsön belüli
	"From:" akkor is hozzáadódik, ha a feladónak és a szerzőnek
	ugyanaz a neve és címe, ami segíthet, ha a levelezőlista-szoftver
	eltorzítja a feladó identitását. Alapértelmezés szerint a
	`format.forceInBodyFrom` konfigurációs változó értékét használja.

`--add-header=<header>`::
	Egy tetszőleges fejlécet ad hozzá az e-mail fejlécekhez. Ez a
	konfigurált fejlécek mellé kerül, és többször is használható.
	Például: `--add-header="Organization: git-foo"`.
	A tagadott `--no-add-header` forma eldobja *az összes* eddig
	konfigurációból vagy parancssorból hozzáadott fejlécet (`To:`,
	`Cc:` és egyéni is).

`--cover-letter`::
`--no-cover-letter`::
	A patchek mellett egy cover letter fájlt is generál, amely
	tartalmazza a branch leírását, a commitlistát és az összesített
	diffstatot. A fájlban a kiküldés előtt kitölthet egy leírást.

`--commit-list-format=<format-spec>`::
	Megadja azt a formátumot, amelyben a patch-sorozat commitlistája
	generálódik. A format-spec elfogadott értékei a `shortlog`, a
	`modern`, vagy egy `log:`-gal kezdődő formátum-string. Pl.
	`log: %s (%an)`. A `modern` ugyanaz, mint a
	`log:%w(72)[%(count)/%(total)] %s`.
	A `log:` előtag elhagyható, ha a formátum-stringben szerepel `%`
	(feltételezve, hogy az egy `%<placeholder>` része).
	Alapértelmezés szerint a `format.commitListFormat` konfigurációs
	változót használja, ha be van állítva, egyébként a `shortlog`-ot.
	Ez az opció parancssorból megadva a `--cover-letter` használatát
	vonja maga után, hacsak a `--no-cover-letter` nincs megadva.

`--encode-email-headers`::
`--no-encode-email-headers`::
	A nem-ASCII karaktereket tartalmazó e-mail fejléceket
	"Q-encoding"-gal (az RFC 2047-ben leírtak szerint) kódolja, ahelyett
	hogy a fejléceket szó szerint adná ki. Alapértelmezés szerint a
	`format.encodeEmailHeaders` konfigurációs változó értékét használja.

`--interdiff=<previous>`::
	Lektori segédeszközként beszúr egy interdiffet a cover letterbe,
	vagy egy 1 patchből álló sorozat egyetlen patchjének
	kommentárjaként, megmutatva a patch-sorozat előző verziója és a
	jelenleg formázott sorozat közötti különbségeket. _<previous>_ egy
	egyetlen revízió, amely az előző sorozat csúcsát nevezi meg, amely
	közös bázissal rendelkezik a formázott sorozattal (például
	`git format-patch --cover-letter --interdiff=feature/v1 -3
	feature/v2`).

`--range-diff=<previous>`::
	Lektori segédeszközként beszúr egy range-diffet (lásd
	linkgit:git-range-diff[1]) a cover letterbe, vagy egy 1 patchből
	álló sorozat egyetlen patchjének kommentárjaként, megmutatva a
	patch-sorozat előző verziója és a jelenleg formázott sorozat
	közötti különbségeket. _<previous>_ lehet egyetlen revízió, amely
	az előző sorozat csúcsát nevezi meg, ha közös bázissal rendelkezik
	a formázott sorozattal (például `git format-patch --cover-letter
	--range-diff=feature/v1 -3 feature/v2`), vagy egy revíziótartomány,
	ha a sorozat két verziója diszjunkt (például `git format-patch
	--cover-letter --range-diff=feature/v1~3..feature/v1 -3
	feature/v2`).
+
Vegye figyelembe, hogy a parancsnak átadott diff-opciók befolyásolják,
hogyan generálódik a `format-patch` elsődleges terméke, de nem kerülnek
átadásra a cover letter anyagának generálásához használt, alapul
szolgáló `range-diff` gépezetnek (ez a jövőben megváltozhat).

`--creation-factor=<percent>`::
	A `--range-diff`-fel együtt használva finomítja azt a heurisztikát,
	amely az előző és a jelenlegi patch-sorozat commitjait párosítja
	össze, a létrehozási/törlési költség korrekciós tényezőjének
	módosításával. Részletekért lásd a linkgit:git-range-diff[1]-et.
+
Alapértelmezetten 999 (a linkgit:git-range-diff[1] 60-at használ),
mivel a felhasználási eset ugyanazon téma egy régebbi iterációjával
való összehasonlítás megjelenítése, és az eszköznek több
megfeleltetést kell találnia a két patch-halmaz között.

`--notes[=<ref>]`::
`--no-notes`::
	Hozzáfűzi a commithoz tartozó notes-okat (lásd
	linkgit:git-notes[1]) a három kötőjelből álló sor után.
+
Ennek várt felhasználási módja az, hogy alátámasztó magyarázatot
írjunk a commithoz, amely nem tartozik szorosan a commit log üzenethez,
és mégis szerepeljen a patch beküldésénél. Bár ezeket a magyarázatokat
egyszerűen meg lehet írni azután, hogy a `format-patch` lefutott, de
mielőtt elküldenénk, ha Git notes-ként tároljuk őket, azok a
patch-sorozat verziói között is fenntarthatók (de ehhez a
munkafolyamathoz lásd a `notes.rewrite` konfigurációs opciók
tárgyalását a linkgit:git-notes[1]-ben).
+
Az alapértelmezés `--no-notes`, hacsak a `format.notes` konfiguráció
be nincs állítva.

`--signature=<signature>`::
`--no-signature`::
	Aláírást ad hozzá minden generált üzenethez. Az RFC 3676 szerint
	az aláírást egy "-- "-t tartalmazó sor választja el a törzstől.
	Ha a signature opció el van hagyva, az aláírás alapértelmezetten
	a Git verziószáma lesz.

`--signature-file=<file>`::
	Ugyanúgy működik, mint a `--signature`, azzal a különbséggel, hogy
	az aláírást egy fájlból olvassa be.

`--suffix=.<sfx>`::
	A generált fájlnevek `.patch` utótagja helyett a megadott utótagot
	használja. Egy gyakori alternatíva a `--suffix=.txt`. Ha üresen
	hagyja, eltávolítja a `.patch` utótagot.
+
Vegye figyelembe, hogy a kezdő karakternek nem kell pontnak lennie;
például a `--suffix=-patch` használatával
`0001-description-of-my-change-patch`-et kaphat.

`-q`::
`--quiet`::
	Nem írja ki a generált fájlok nevét a standard kimenetre.

`--no-binary`::
	Nem adja ki a bináris fájlokban lévő változtatások tartalmát,
	ehelyett egy értesítést jelenít meg arról, hogy azok a fájlok
	megváltoztak. Az ezzel az opcióval generált patchek nem
	alkalmazhatók megfelelően, de kódellenőrzéshez így is hasznosak.

`--zero-commit`::
  A commit hash-e helyett egy csupa-nulla hash-t ad ki minden patch
  From fejlécében.

`--no-base`::
`--base[=<commit>]`::
	Rögzíti a bázisfa-információt, amely azonosítja azt az állapotot,
	amelyre a patch-sorozat alkalmazandó. A részletekért lásd a lenti
	BASE TREE INFORMATION szekciót. Ha _<commit>_ értéke `auto`, a
	bázis commit automatikusan kiválasztásra kerül. A `--no-base`
	opció felülbírálja a `format.useAutoBase` konfigurációt.

`--root`::
	A revízió-argumentumot _<revision-range>_-ként kezeli, még akkor
	is, ha az csupán egyetlen commit (amelyet normál esetben
	_<since>_-ként kezelne). Vegye figyelembe, hogy a megadott
	tartományban szereplő root commitok mindig létrehozási patchekként
	kerülnek formázásra, ettől a jelzőtől függetlenül.

`--progress`::
	Előrehaladási jelentéseket jelenít meg a stderren, ahogy a patchek
	generálódnak.

CONFIGURATION
-------------
Konfigurációs változókkal megadhat extra e-mail fejléc-sorokat, amelyek
minden üzenethez hozzáadódnak, alapértelmezéseket a tárgy-előtaghoz és
a fájl-utótaghoz, számozhatja a patcheket, ha egynél több patch kerül
kiadásra, hozzáadhat "To:" vagy "Cc:" fejléceket, konfigurálhatja a
mellékleteket, megváltoztathatja a patchek kimeneti könyvtárát, és
sign off-olhatja a patcheket.

----
[format]
	headers = "Organization: git-foo\n"
	subjectPrefix = CHANGE
	suffix = .txt
	numbered = auto
	to = <email>
	cc = <email>
	attach [ = mime-boundary-string ]
	signOff = true
	outputDirectory = <directory>
	coverLetter = auto
	commitListFormat = shortlog
	coverFromDescription = auto
----

DISCUSSION
----------

A `git format-patch` által előállított patch UNIX postafiók
formátumban van, egy rögzített "mágikus" időbélyeggel, amely azt
jelzi, hogy a fájl a format-patch kimenete, nem pedig egy valódi
postafiók, íme egy példa:

----
From 8f72bad1baf19a53459661343e21d6491c3908d3 Mon Sep 17 00:00:00 2001
From: Tony Luck <tony.luck@intel.com>
Date: Tue, 13 Jul 2010 11:42:54 -0700
Subject: [PATCH] =?UTF-8?q?[IA64]=20Put=20ia64=20config=20files=20on=20the=20?=
 =?UTF-8?q?Uwe=20Kleine-K=C3=B6nig=20diet?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

arch/arm config files were slimmed down using a python script
(See commit c2330e286f68f1c408b4aa6515ba49d57f05beae comment)

Do the same for ia64 so we can have sleek & trim looking
...
----

Jellemzően egy MUA piszkozat mappájába kerül, ahol szerkeszthető, hogy
a három kötőjel után olyan aktuális kommentárt tartalmazzon, amelynek
nem kellene bekerülnie a changelogba, majd elküldhető olyan üzenetként,
amelynek törzse a példánkban azzal kezdődik, hogy "arch/arm config
files were...". A fogadó oldalon az olvasók elmenthetik az érdekes
patcheket egy UNIX postafiókba, és alkalmazhatják őket a
linkgit:git-am[1]-gyel.

Ha egy patch egy folyamatban lévő megbeszélés része, a `git
format-patch` által generált patch úgy módosítható, hogy kihasználja a
`git am --scissors` funkciót. A megbeszélésre adott válasza után egy
kizárólag "`-- >8 --`"-ból (olló és perforáció) álló sor következik,
amelyet a szükségtelen fejlécmezőktől megtisztított patch követ:

----
...
> So we should do such-and-such.

Makes sense to me.  How about this patch?

-- >8 --
Subject: [IA64] Put ia64 config files on the Uwe Kleine-König diet

arch/arm config files were slimmed down using a python script
...
----

Amikor így küld el egy patchet, legtöbbször a saját patchjét küldi, így
a "`From $SHA1 $magic_timestamp`" jelölő mellett el kell hagynia a
`From:` és `Date:` sorokat a patch-fájlból. A patch címe valószínűleg
eltér attól a tárgytól, amelyre a patch válaszol, ezért valószínűleg
meg akarja tartani a Subject: sort, mint a fenti példában.

[[_checking_for_patch_corruption]]
Patch-korrupció ellenőrzése
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sok levelezőprogram, ha nincs megfelelően beállítva, elrontja a
whitespace-t. Íme a korrupció két gyakori típusa:

* Üres kontextussorok, amelyeknek _egyáltalán nincs_ whitespace-ük.

* Nem üres kontextussorok, amelyeknek egy extra whitespace-ük van az
  elején.

Az egyik módja annak, hogy teszteljük, jól van-e beállítva a MUA:

* Küldje el a patchet saját magának, pontosan úgy, ahogy egyébként
  tenné, azzal a különbséggel, hogy a `To:` és `Cc:` sorok ne
  tartalmazzák a lista és a maintainer címét.

* Mentse el a patchet egy fájlba UNIX postafiók formátumban. Nevezze
  el mondjuk a.patch-nek.

* Alkalmazza:

    $ git fetch <project> master:test-apply
    $ git switch test-apply
    $ git restore --source=HEAD --staged --worktree :/
    $ git am a.patch

Ha nem alkalmazódik helyesen, ennek különböző okai lehetnek.

* Maga a patch nem alkalmazódik tisztán. Ez _rossz_, de nem sok köze
  van a MUA-jához. Ebben az esetben érdemes lehet rebase-elni a
  patchet a linkgit:git-rebase[1]-gyel, mielőtt újragenerálná.

* A MUA elrontotta a patchet; az "am" panaszkodna, hogy a patch nem
  alkalmazódik. Nézze meg a `.git/rebase-apply/` alkönyvtárban, mit
  tartalmaz a `patch` fájl, és ellenőrizze a fent említett gyakori
  korrupciós mintákat.

* Miközben ott van, ellenőrizze az `info` és a `final-commit` fájlokat
  is. Ha a `final-commit`-ban lévő tartalom nem pontosan az, amit
  látni szeretne a commit log üzenetben, nagyon valószínű, hogy a
  fogadó fél a patch alkalmazásakor kézzel fogja szerkeszteni a log
  üzenetet. Az olyan dolgoknak, mint a "Hi, this is my first
  patch.\n" a patch e-mailben, a commit-üzenet végét jelző, három
  kötőjelből álló sor után kellene következniük.

MUA-SPECIFIC HINTS
------------------
Íme néhány tipp arra, hogyan lehet sikeresen beküldeni patcheket
beágyazva, különböző levelezőprogramok használatával.

[[_gmail]]
GMail
~~~~~
A GMailnek nincs semmilyen módja a sortördelés kikapcsolására a
webes felületen, ezért el fogja rontani az összes elküldött e-mailt.
Használhatja azonban a `git send-email`-t, és elküldheti patcheit a
GMail SMTP szerverén keresztül, vagy használhat bármilyen IMAP
e-mail-klienst, hogy csatlakozzon a google IMAP szerveréhez, és azon
keresztül továbbítsa az e-maileket.

A `git send-email` GMail SMTP szerveren keresztüli patch-küldéséhez
lásd a linkgit:git-send-email[1] EXAMPLE szekcióját.

Az IMAP felületen keresztüli beküldéshez lásd a
linkgit:git-imap-send[1] EXAMPLE szekcióját.

[[_thunderbird]]
Thunderbird
~~~~~~~~~~~
Alapértelmezés szerint a Thunderbird egyszerre tördeli az e-maileket,
és `format=flowed`-ként jelöli meg őket, ami mindkettő használhatatlanná
teszi az eredményül kapott e-mailt a Git számára.

Három különböző megközelítés létezik: egy add-on használata a
sortördelés kikapcsolására, a Thunderbird konfigurálása, hogy ne
rontsa el a patcheket, vagy egy külső szerkesztő használata, hogy a
Thunderbird ne rontsa el a patcheket.

[[_approach_1_add_on]]
1. megközelítés (add-on)
^^^^^^^^^^^^^^^^^^^^^^^^

Telepítse a Toggle Line Wrap add-ont, amely elérhető innen:
https://addons.thunderbird.net/thunderbird/addon/toggle-line-wrap
Ez hozzáad egy "Line Wrap" gombot a szerkesztő eszköztárához,
amelyet ki lehet kapcsolni. Most már úgy írhatja az üzenetet, ahogy
egyébként tenné (kivágás + beillesztés, `git format-patch` |
`git imap-send` stb.), de az általa gépelt szövegekbe kézzel kell
sortöréseket beszúrnia.

Extra funkcióként az add-on képes felismerni a patch-szöveget a
szerkesztőben, és figyelmeztet, ha a sortördelés még nincs
kikapcsolva.

Az add-on igényel néhány beállítást a haladó konfigurációban
(`about:config`). Ezek a letöltési oldalon vannak felsorolva.

[[_approach_2_configuration]]
2. megközelítés (konfiguráció)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Három lépés:

1. Állítsa be a levelezőszerver-szerkesztést egyszerű szövegként:
   Edit...Account Settings...Composition & Addressing,
   kapcsolja ki a "Compose Messages in HTML" opciót.

2. Állítsa be az általános szerkesztőablakot, hogy ne tördeljen.
+
Thunderbird 2-ben:
Edit..Preferences..Composition, wrap plain text messages at 0
+
Thunderbird 3-ban:
Edit..Preferences..Advanced..Config Editor. Keresse meg a
"mail.wrap_long_lines" beállítást.
Kapcsolja át, hogy biztosan `false` legyen. Emellett keresse meg a
"mailnews.wraplength" beállítást, és állítsa az értékét 0-ra.

3. Tiltsa le a format=flowed használatát:
   Edit..Preferences..Advanced..Config Editor. Keresse meg a
   "mailnews.send_plaintext_flowed" beállítást.
   Kapcsolja át, hogy biztosan `false` legyen.

Ezután képesnek kell lennie úgy írni az e-mailt, ahogy egyébként tenné
(kivágás + beillesztés, `git format-patch` | `git imap-send` stb.), és
a patchek nem fognak elromlani.

[[_approach_3_external_editor]]
3. megközelítés (külső szerkesztő)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A következő Thunderbird kiterjesztésekre van szükség:
AboutConfig innen: https://mjg.github.io/AboutConfig/ és
External Editor innen: https://globs.org/articles.php?lng=en&pg=8

1. Készítse elő a patchet szövegfájlként, tetszőleges módszerrel.

2. Mielőtt megnyitna egy szerkesztőablakot, az Edit->Account
   Settings menüben kapcsolja ki a "Compose messages in HTML format"
   beállítást a patch küldésére használandó fiók
   "Composition & Addressing" paneljén.

3. A Thunderbird főablakában, _mielőtt_ megnyitná a patchhez tartozó
   szerkesztőablakot, a Tools->about:config menüben állítsa be a
   következőket a megadott értékekre:
+
----
	mailnews.send_plaintext_flowed  => false
	mailnews.wraplength             => 0
----

4. Nyisson meg egy szerkesztőablakot, és kattintson a külső
   szerkesztő ikonjára.

5. A külső szerkesztő ablakában olvassa be a patch-fájlt, és lépjen
   ki a szerkesztőből a szokásos módon.

Mellékes megjegyzés: lehetséges, hogy a 2. lépés elvégezhető
about:configgal és a következő beállításokkal, de ezt még senki nem
próbálta ki.

----
	mail.html_compose                       => false
	mail.identity.default.compose_html      => false
	mail.identity.id?.compose_html          => false
----

A contrib/thunderbird-patch-inline mappában van egy szkript, amely
segít könnyedén beilleszteni a patcheket a Thunderbirdben. A
használatához hajtsa végre a fenti lépéseket, majd használja a
szkriptet külső szerkesztőként.

[[_kmail]]
KMail
~~~~~
Ez segítenie kell a patchek beágyazott beküldésében a KMail
használatával.

1. Készítse elő a patchet szövegfájlként.

2. Kattintson a New Mail gombra.

3. Menjen az "Options" alá a szerkesztő ablakban, és győződjön meg
   róla, hogy a "Word wrap" nincs bekapcsolva.

4. Használja a Message -> Insert file... menüpontot, és illessze be
   a patchet.

5. Vissza a szerkesztőablakban: adjon hozzá bármilyen egyéb szöveget
   az üzenethez, töltse ki a címzés- és tárgymezőket, majd nyomja meg
   a küldés gombot.

BASE TREE INFORMATION
---------------------

A bázisfa-információs blokk arra szolgál, hogy a maintainerek vagy
külső tesztelők tudják, pontosan milyen állapotra alkalmazandó a
patch-sorozat. A "base commit"-ból áll, amely egy jól ismert commit,
amely a projekt történetének stabil részét képezi, amelyen mindenki
más is dolgozik, valamint nulla vagy több "prerequisite patch"-ből,
amelyek olyan jól ismert, folyamatban lévő patchek, amelyek még nem
részei a "base commit"-nak, és amelyeket topológiai sorrendben kell
alkalmazni a "base commit" tetejére, mielőtt a patchek
alkalmazhatók lennének.

A "base commit" "`base-commit:` " formában jelenik meg, amelyet a
commit-objektum nevének 40 hex-jegye követ. A "prerequisite patch"
"`prerequisite-patch-id:` " formában jelenik meg, amelyet a 40 hex-jegyű
"patch id" követ, amely a patchnek a `git patch-id --stable`
parancson való átvezetésével nyerhető ki.

Képzelje el, hogy a P nyilvános commit tetejére alkalmazta valaki más
jól ismert X, Y és Z patchjeit, majd felépítette a saját háromrészes
A, B, C sorozatát; a történet a következőképpen nézne ki:

................................................
---P---X---Y---Z---A---B---C
................................................

A `git format-patch --base=P -3 C` (vagy ennek változatai, pl.
`--cover-letter`-rel, vagy a tartomány megadásához `-3 C` helyett
`Z..C` használatával) paranccsal a bázisfa-információs blokk a
parancs által kiadott első üzenet végén jelenik meg (akár az első
patch, akár a cover letter), így:

----
base-commit: P
prerequisite-patch-id: X
prerequisite-patch-id: Y
prerequisite-patch-id: Z
----

Nem lineáris topológia esetén, mint például

................................................
---P---X---A---M---C
    \         /
     Y---Z---B
................................................

Használhatja a `git format-patch --base=P -3 C` parancsot is az A, B
és C patchek generálásához, és a P, X, Y, Z azonosítói az első üzenet
végéhez kerülnek hozzáfűzésre.

Ha a parancssorban be van állítva a `--base=auto`, akkor automatikusan
kiszámítja a bázis commitot a remote-tracking branch csúcs-commitjának
és a parancssorban megadott revíziótartománynak a merge-alapjaként.
Helyi branch esetén a `git branch --set-upstream-to` paranccsal be
kell állítania, hogy egy remote branchet kövessen, mielőtt ezt az
opciót használná.

EXAMPLES
--------

* Az R1 és R2 revíziók közötti commitok kinyerése, majd alkalmazásuk
  az aktuális branch tetejére a `git am`-mal, cherry-pickelve őket:
+
------------
$ git format-patch -k --stdout R1..R2 | git am -3 -k
------------

* Az összes olyan commit kinyerése, amely az aktuális branchben van,
  de az origin branchben nincs:
+
------------
$ git format-patch origin
------------
+
Minden commithoz egy külön fájl jön létre az aktuális könyvtárban.

* Az összes olyan commit kinyerése, amely az `origin`-hoz vezet, a
  projekt kezdete óta:
+
------------
$ git format-patch --root origin
------------

* Ugyanaz, mint az előző:
+
------------
$ git format-patch -M -B origin
------------
+
Ezenkívül intelligensen felismeri és kezeli az átnevezéseket és a
teljes újraírásokat, hogy átnevezési patchet állítson elő. Egy
átnevezési patch csökkenti a szöveges kimenet mennyiségét, és
általában megkönnyíti az ellenőrzést. Vegye figyelembe, hogy a
nem Git `patch` programok nem értik meg az átnevezési patcheket,
ezért csak akkor használja, ha tudja, hogy a fogadó fél Git-et
használ a patch alkalmazásához.

* A három legfelső commit kinyerése az aktuális branchből, és
  e-mailben küldhető patchekké formázása:
+
------------
$ git format-patch -3
------------

CAVEATS
-------

Vegye figyelembe, hogy a `format-patch` kihagyja a merge commitokat a
kimenetből, még akkor is, ha azok a kért tartomány részét képezik. Egy
egyszerű "patch" nem tartalmaz elég információt ahhoz, hogy a fogadó
fél újra elő tudja állítani ugyanazt a merge commitot.

=== PATCH APPLICATION

include::format-patch-caveats.adoc[]

SEE ALSO
--------
linkgit:git-am[1], linkgit:git-send-email[1]

GIT
---
A linkgit:git[1] csomag része
