git-config(1)
=============

NAME
----
git-config - Repository- vagy globális opciók lekérdezése és beállítása


SYNOPSIS
--------
[verse]
'git config list' [<file-option>] [<display-option>] [--includes]
'git config get' [<file-option>] [<display-option>] [--includes] [--all] [--regexp] [--value=<pattern>] [--fixed-value] [--default=<default>] [--url=<url>] <name>
'git config set' [<file-option>] [--type=<type>] [--all] [--value=<pattern>] [--fixed-value] <name> <value>
'git config unset' [<file-option>] [--all] [--value=<pattern>] [--fixed-value] <name>
'git config rename-section' [<file-option>] <old-name> <new-name>
'git config remove-section' [<file-option>] <name>
'git config edit' [<file-option>]
'git config' [<file-option>] --get-colorbool <name> [<stdout-is-tty>]

DESCRIPTION
-----------
Ezzel a paranccsal lekérdezhetsz/beállíthatsz/lecserélhetsz/törölhetsz
opciókat. A név valójában a szekció és a kulcs, ponttal elválasztva, az
érték pedig escape-elve lesz.

Egy opcióhoz a `--append` opcióval több sor is hozzáadható. Ha egy olyan
opciót akarsz frissíteni vagy törölni, amely több sorban is előfordulhat,
meg kell adni a `--value=<pattern>` opciót (ez egy kiterjesztett reguláris
kifejezés, hacsak nincs megadva a `--fixed-value` opció). Csak azok a
meglévő értékek frissülnek vagy törlődnek, amelyek illeszkednek a mintára.
Ha azokat a sorokat akarod kezelni, amelyek *nem* illeszkednek a mintára,
egyszerűen tegyél egy felkiáltójelet a minta elé (lásd még: <<EXAMPLES>>),
de vedd figyelembe, hogy ez csak akkor működik, ha a `--fixed-value`
opció nincs használatban.

A `--type=<type>` opció arra utasítja a 'git config'-ot, hogy biztosítsa,
hogy a bejövő és kimenő értékek kanonizálhatók legyenek a megadott
<type> alatt. Ha nincs megadva `--type=<type>`, nem történik
kanonizáció. A hívók a `--no-type` opcióval törölhetik egy már beállított
`--type` specifikátort.

Olvasáskor az értékek alapértelmezés szerint a rendszerszintű, globális
és repository-helyi konfigurációs fájlokból olvasódnak be, és a
`--system`, `--global`, `--local`, `--worktree` és `--file <filename>`
opciókkal utasítható a parancs, hogy csak abból az egy helyről olvasson
(lásd: <<FILES>>).

Íráskor az új érték alapértelmezés szerint a repository-helyi
konfigurációs fájlba íródik, és a `--system`, `--global`, `--worktree`,
`--file <filename>` opciókkal utasítható a parancs, hogy oda írjon (a
`--local`-t is megadhatod, de ez az alapértelmezés).

Ez a parancs nullától eltérő státusszal hibázik. Néhány kilépési kód:

- a szekció vagy a kulcs érvénytelen (ret=1),
- nem lett megadva szekció vagy név (ret=2),
- a konfigurációs fájl érvénytelen (ret=3),
- a konfigurációs fájl nem írható (ret=4),
- egy nem létező opciót próbálsz törölni (ret=5),
- egy olyan opciót próbálsz törölni/beállítani, amelyre több sor is
  illeszkedik (ret=5), vagy
- egy érvénytelen reguláris kifejezést próbálsz használni (ret=6).

Sikeres futás esetén a parancs a 0 kilépési kóddal tér vissza.

Az összes elérhető konfigurációs változó listája a `git help --config`
paranccsal kérhető le.

COMMANDS
--------

list::
	Kilistázza a config fájlban beállított összes változót, az
	értékükkel együtt.

get::
	Kiadja a megadott kulcs értékét. Ha a kulcs többször is szerepel a
	konfigurációban, az utolsó értéket adja ki. Ha meg van adva a
	`--all`, minden, a kulcshoz tartozó értéket kiad. 1-es hibakóddal
	tér vissza, ha a kulcs nincs jelen.

set::
	Beállítja egy vagy több konfigurációs opció értékét. Alapértelmezés
	szerint ez a parancs megtagadja a többértékű konfigurációs opciók
	írását. A `--all` megadásával az összes többértékű konfigurációs
	opció lecserélődik az új értékre, míg a `--value=` megadásával
	minden olyan konfigurációs opció lecserélődik, amelynek értéke
	illeszkedik a megadott mintára.

unset::
	Törli egy vagy több konfigurációs opció értékét. Alapértelmezés
	szerint ez a parancs megtagadja a többértékű kulcsok törlését. A
	`--all` megadásával az összes többértékű konfigurációs opció
	törlődik, míg a `--value` megadásával minden olyan konfigurációs
	opció törlődik, amelynek értéke illeszkedik a megadott mintára.

rename-section::
	Átnevezi a megadott szekciót egy új névre.

remove-section::
	Eltávolítja a megadott szekciót a konfigurációs fájlból.

edit::
	Megnyit egy szerkesztőt a megadott config fájl módosításához;
	ez a `--system`, `--global`, `--local` (alapértelmezett),
	`--worktree` vagy a `--file <config-file>` valamelyike lehet.

[[OPTIONS]]
OPTIONS
-------

--replace-all::
	Az alapértelmezett viselkedés az, hogy legfeljebb egy sort cserél
	le. Ez az összes, a kulcsra illeszkedő sort lecseréli (és
	opcionálisan a `--value=<pattern>`-re illeszkedőket).

--append::
	Új sort ad hozzá az opcióhoz, a meglévő értékek megváltoztatása
	nélkül. Ez ugyanaz, mintha '--value=^$'-t adnál meg a `set`-nél.

--comment <message>::
	Megjegyzést fűz az új vagy módosított sorok végéhez.
+
Ha az _<message>_ egy vagy több szóközzel kezdődik, amit `#` követ,
változatlanul kerül felhasználásra. Ha `#`-vel kezdődik, egy szóköz
kerül elé, mielőtt felhasználásra kerülne. Egyébként egy `" # "`
karakterlánc (szóköz, kettőskereszt, szóköz) kerül elé. A kapott
karakterlánc közvetlenül a változóhoz tartozó érték után kerül
elhelyezésre. Az _<message>_ nem tartalmazhat soremelés-karaktert
(többsoros megjegyzések nem megengedettek).

--all::
	A `get`-tel együtt egy többértékű kulcs összes értékét adja vissza.

--regexp::
	A `get`-tel együtt reguláris kifejezésként értelmezi a nevet. A
	reguláris kifejezés illesztése jelenleg kis- és nagybetűérzékeny,
	és a kulcs egy kanonizált változata ellen történik, amelyben a
	szekció- és változónevek kisbetűsek, de az alszekciónevek nem.

--url=<URL>::
	Ha egy kétrészes <name>-et adsz meg <section>.<key> formában,
	akkor a <section>.<URL>.<key> értéke jön vissza, amelynek <URL>
	része a legjobban illeszkedik a megadott URL-re (ha nincs ilyen
	kulcs, a <section>.<key> értéke szolgál tartalékként). Ha csak a
	<section>-t adod meg névként, ugyanez történik a szekció összes
	kulcsával, és kilistázza őket. 1-es hibakóddal tér vissza, ha
	nem talál értéket.

--global::
	Íráskor: a globális `~/.gitconfig` fájlba ír a repository
	`.git/config` fájlja helyett, illetve a `$XDG_CONFIG_HOME/git/config`
	fájlba ír, ha ez a fájl létezik, a `~/.gitconfig` fájl pedig nem.
+
Olvasáskor: csak a globális `~/.gitconfig`-ból és a
`$XDG_CONFIG_HOME/git/config`-ból olvas, nem az összes elérhető fájlból.
+
Lásd még: <<FILES>>.

--system::
	Íráskor: a rendszerszintű `$(prefix)/etc/gitconfig` fájlba ír a
	repository `.git/config` fájlja helyett.
+
Olvasáskor: csak a rendszerszintű `$(prefix)/etc/gitconfig`-ból olvas,
nem az összes elérhető fájlból.
+
Lásd még: <<FILES>>.

--local::
	Íráskor: a repository `.git/config` fájljába ír. Ez az
	alapértelmezett viselkedés.
+
Olvasáskor: csak a repository `.git/config` fájljából olvas, nem az
összes elérhető fájlból.
+
Lásd még: <<FILES>>.

--worktree::
	Hasonló a `--local`-hoz, azzal a különbséggel, hogy a
	`$GIT_DIR/config.worktree` fájlból olvas, illetve abba ír, ha az
	`extensions.worktreeConfig` engedélyezve van. Ha nincs, ugyanaz,
	mint a `--local`. Vedd figyelembe, hogy a `$GIT_DIR` megegyezik a
	`$GIT_COMMON_DIR`-rel a fő munkakönyvtár esetében, de más
	munkakönyvtáraknál `$GIT_DIR/worktrees/<id>/` alakú. Lásd a
	linkgit:git-worktree[1]-et, hogy megtudd, hogyan engedélyezheted
	az `extensions.worktreeConfig`-ot.

-f <config-file>::
--file <config-file>::
	Íráskor: a megadott fájlba ír a repository `.git/config` fájlja
	helyett.
+
Olvasáskor: csak a megadott fájlból olvas, nem az összes elérhető
fájlból.
+
Lásd még: <<FILES>>.

--blob <blob>::
	Hasonló a `--file`-hoz, de a megadott blobot használja fájl
	helyett. Például a 'master:.gitmodules' megadásával a '.gitmodules'
	fájlból olvashatók be értékek a master branchen. Lásd a
	linkgit:gitrevisions[7] "SPECIFYING REVISIONS" szakaszát a blob
	nevek megadási módjainak teljesebb listájáért.

`--value=<pattern>`::
`--no-value`::
	A `get`-tel, `set`-tel és `unset`-tel együtt csak az _<pattern>_-re
	illeszkedik. A minta egy kiterjesztett reguláris kifejezés, hacsak
	nincs megadva a `--fixed-value`.
+
A `--no-value`-val törölheted az _<pattern>_-et.

--fixed-value::
	A `--value=<pattern>`-nel együtt használva az _<pattern>_-et pontos
	karakterláncként kezeli reguláris kifejezés helyett. Ez azokra a
	név/érték párokra korlátozza az illesztést, amelyeknek az értéke
	pontosan megegyezik az _<pattern>_-nel.

--type <type>::
  A 'git config' biztosítja, hogy minden bemenet vagy kimenet érvényes
  legyen a megadott típus-megszorítás(ok) alatt, és a kimenő értékeket
  a `<type>` kanonikus formájában kanonizálja.
+
Az érvényes `<type>` értékek a következők:
+
--
- 'bool': a `true`, `yes`, `on` és a pozitív számok "true"-ra, a
  `false`, `no`, `off` és `0` pedig "false"-ra kanonizálódnak.
- 'int': az értékek egyszerű decimális számokká kanonizálódnak. Egy
  opcionális 'k', 'm' vagy 'g' utótag hatására az érték bemenetkor
  1024-gyel, 1048576-tal, illetve 1073741824-gyel szorzódik.
- 'bool-or-int': a fentebb leírt 'bool' vagy 'int' szerint kanonizál.
- 'path': úgy kanonizál, hogy a kezdő `~`-t a `$HOME` értékére, a
  `~user`-t pedig a megadott felhasználó saját könyvtárára cseréli.
  Ennek a specifikátornak nincs hatása az érték beállításakor (de a
  parancssorból használhatod a `git config section.variable ~/`
  alakot, hogy a shell végezze el a kifejtést).
- 'expiry-date': úgy kanonizál, hogy egy fix vagy relatív
  dátum-karakterláncból időbélyeggé alakít. Ennek a specifikátornak
  nincs hatása az érték beállításakor.
- 'color': érték lekérdezésekor egy ANSI szín-escape-szekvenciává
  alakítva kanonizál. Érték beállításakor egy ellenőrzés történik
  annak biztosítására, hogy a megadott érték kanonizálható legyen
  ANSI színként, de az érték változatlanul kerül beírásra.
--
+
Ha a parancs `list` módban van, a `--type <type>` argumentum minden
kilistázott konfigurációs értékre alkalmazásra kerül. Ha egy érték nem
elemezhető sikeresen abban a formátumban, kimarad a listából.

--bool::
--int::
--bool-or-int::
--path::
--expiry-date::
  Elavult opciók egy típus-specifikátor kiválasztására. Helyettük a
  `--type` használata javasolt (l. fent).

--no-type::
  Törli az előzőleg beállított típus-specifikátort (ha volt ilyen
  beállítva). Ez az opció azt kéri, hogy a 'git config' ne kanonizálja
  a lekérdezett változót. A `--no-type`-nak nincs hatása `--type=<type>`
  vagy `--<type>` nélkül.

-z::
--null::
	Minden olyan opciónál, amely értékeket és/vagy kulcsokat ad ki,
	mindig a null karakterrel zárja le az értékeket (soremelés
	helyett). A kulcs és az érték közötti elválasztóként soremelést
	használ helyette. Ez lehetővé teszi a kimenet biztonságos
	elemzését anélkül, hogy pl. a sortörést tartalmazó értékek
	összezavarnák.

--name-only::
	Csak a konfigurációs változók neveit adja ki a `list`-nél vagy a
	`get`-nél.

`--show-names`::
`--no-show-names`::
	A `get`-tel együtt az értékeik mellett a konfigurációs kulcsokat is
	megjeleníti. Az alapértelmezés a `--no-show-names`, hacsak nincs
	megadva a `--url`, és nincsenek alszekciók az _<name>_-ben.

--show-origin::
	Kiegészíti az összes lekérdezett konfigurációs opció kimenetét az
	eredet típusával (fájl, standard bemenet, blob, parancssor) és a
	tényleges eredettel (a config fájl útvonala, ref, vagy adott
	esetben a blob azonosítója).

--show-scope::
	Hasonló a `--show-origin`-hoz abban, hogy kiegészíti az összes
	lekérdezett konfigurációs opció kimenetét az adott érték
	hatókörével (worktree, local, global, system, command).

--get-colorbool <name> [<stdout-is-tty>]::

	Megkeresi a `<name>` szín-beállítását (pl. `color.diff`), és
	kiadja, hogy "true" vagy "false". A `<stdout-is-tty>` értéke
	"true" vagy "false" legyen, és figyelembe vétetik, amikor a
	konfiguráció "auto"-t mond. Ha a `<stdout-is-tty>` hiányzik, akkor
	magának a parancsnak a szabványos kimenetét ellenőrzi, és 0-s
	státusszal lép ki, ha színt kell használni, egyébként 1-es
	státusszal lép ki.
	Ha a `name` szín-beállítása nincs megadva, a parancs a
	`color.ui`-t használja tartalékként.

--includes::
--no-includes::
	Figyelembe veszi az `include.*` direktívákat a config fájlokban az
	értékek keresésekor. Alapértelmezés szerint `off`, ha egy konkrét
	fájl van megadva (pl. a `--file`, `--global` stb. használatával),
	és `on`, ha az összes config fájlt keresi.

--default <value>::
  Amikor a `get`-et használod, és a kért változó nem található, úgy
  viselkedik, mintha <value> lenne a változóhoz rendelt érték.

DEPRECATED MODES
----------------

Az alábbi módok elavultnak minősülnek az alparancsok javára. Az új
szintaxisra való átállás javasolt.

'git config <name>'::
	Helyette: `git config get <name>`.

'git config <name> <value> [<value-pattern>]'::
	Helyette: `git config set [--value=<pattern>] <name> <value>`.

-l::
--list::
	Helyette: `git config list`.

--get <name> [<value-pattern>]::
	Helyette: `git config get [--value=<pattern>] <name>`.

--get-all <name> [<value-pattern>]::
	Helyette: `git config get [--value=<pattern>] --all <name>`.

--get-regexp <name-regexp>::
	Helyette: `git config get --all --show-names --regexp <name-regexp>`.

--get-urlmatch <name> <URL>::
	Helyette: `git config get --url=<URL> <name>`.

--get-color <name> [<default>]::
	Helyette: `git config get --type=color [--default=<default>] <name>`.

--add <name> <value>::
	Helyette: `git config set --append <name> <value>`.

--unset <name> [<value-pattern>]::
	Helyette: `git config unset [--value=<pattern>] <name>`.

--unset-all <name> [<value-pattern>]::
	Helyette: `git config unset [--value=<pattern>] --all <name>`.

--rename-section <old-name> <new-name>::
	Helyette: `git config rename-section <old-name> <new-name>`.

--remove-section <name>::
	Helyette: `git config remove-section <name>`.

-e::
--edit::
	Helyette: `git config edit`.

CONFIGURATION
-------------
A `pager.config` csak konfiguráció listázásakor vétetik figyelembe, azaz
a `list` vagy a `get` használatakor, amelyek több eredményt is
visszaadhatnak. Az alapértelmezés egy pager használata.

[[FILES]]
FILES
-----

Alapértelmezés szerint a 'git config' több fájlból is beolvassa a
konfigurációs opciókat:

$(prefix)/etc/gitconfig::
	Rendszerszintű konfigurációs fájl.

$XDG_CONFIG_HOME/git/config::
~/.gitconfig::
	Felhasználó-specifikus konfigurációs fájlok. Ha az XDG_CONFIG_HOME
	környezeti változó nincs beállítva vagy üres, a $HOME/.config/
	kerül felhasználásra $XDG_CONFIG_HOME-ként.
+
Ezeket „globális" konfigurációs fájloknak is nevezik. Ha mindkét fájl
létezik, mindkettő beolvasásra kerül a fenti sorrendben.

$GIT_DIR/config::
	Repository-specifikus konfigurációs fájl.

$GIT_DIR/config.worktree::
	Ez opcionális, és csak akkor keresi a rendszer, ha az
	`extensions.worktreeConfig` jelen van a $GIT_DIR/config fájlban.

Bármely git parancs futtatásakor a `-c` opcióval további konfigurációs
paramétereket is megadhatsz. Részletekért lásd a linkgit:git[1]-et.

Az opciók az összes elérhető fájlból beolvasásra kerülnek. Ha a
globális vagy a rendszerszintű konfigurációs fájlok hiányoznak vagy
nem olvashatók, figyelmen kívül maradnak. Ha a repository konfigurációs
fájlja hiányzik vagy nem olvasható, a 'git config' nullától eltérő
hibakóddal lép ki. Hibaüzenet keletkezik, ha a fájl nem olvasható, de
nem keletkezik, ha hiányzik.

A fájlok a fenti sorrendben kerülnek beolvasásra, és az utolsóként
talált érték élvez elsőbbséget a korábban beolvasottakkal szemben. Ha
több érték is fel van véve, egy kulcs összes értéke felhasználásra
kerül az összes fájlból.

Alapértelmezés szerint az opciók csak a repository-specifikus
konfigurációs fájlba íródnak. Vedd figyelembe, hogy ez az olyan
opciókra is vonatkozik, mint a `set` és az `unset`. *A 'git config'
mindig csak egyetlen fájlt módosít egyszerre*.

Korlátozhatod, hogy mely konfigurációs forrásokból történjen olvasás
vagy írás, ha megadod egy fájl útvonalát a `--file` opcióval, vagy egy
konfigurációs hatókört a `--system`, `--global`, `--local` vagy
`--worktree` opcióval. Bővebben lásd a fenti <<OPTIONS>>-t.

[[SCOPES]]
SCOPES
------

Minden konfigurációs forrás egy konfigurációs hatókörön belülre esik. A
hatókörök a következők:

system::
	$(prefix)/etc/gitconfig

global::
	$XDG_CONFIG_HOME/git/config
+
~/.gitconfig

local::
	$GIT_DIR/config

worktree::
	$GIT_DIR/config.worktree

command::
	GIT_CONFIG_{COUNT,KEY,VALUE} környezeti változók (lásd lent:
	<<ENVIRONMENT>>)
+
a `-c` opció

A 'command' kivételével minden hatókör egy parancssori opciónak felel
meg: `--system`, `--global`, `--local`, `--worktree`.

Opciók olvasásakor egy hatókör megadása csak az adott hatókörön belüli
fájlokból olvassa be az opciókat. Opciók írásakor egy hatókör megadása
az adott hatókörön belüli fájlokba ír (a repository-specifikus
konfigurációs fájl helyett). A teljes leírásért lásd a fenti
<<OPTIONS>>-t.

A legtöbb konfigurációs opció attól függetlenül figyelembe vétetik,
hogy melyik hatókörben van megadva, de néhány opció csak bizonyos
hatókörökben vétetik figyelembe. A teljes részletekért lásd az adott
opció dokumentációját.

[[_protected_configuration]]
Védett konfiguráció
~~~~~~~~~~~~~~~~~~~

A védett konfiguráció (angolul: protected configuration) a 'system',
'global' és 'command' hatókörökre utal. Biztonsági okokból bizonyos
opciók csak akkor vétetnek figyelembe, ha védett konfigurációban vannak
megadva, egyébként figyelmen kívül maradnak.

A Git úgy kezeli ezeket a hatóköröket, mintha a felhasználó vagy egy
megbízható rendszergazda irányítaná őket. Ennek az az oka, hogy egy
támadó, aki irányítja ezeket a hatóköröket, jelentős kárt tud
okozni a Git használata nélkül is, így feltételezhető, hogy a
felhasználó környezete védi ezeket a hatóköröket a támadók ellen.

[[ENVIRONMENT]]
ENVIRONMENT
-----------

GIT_CONFIG_GLOBAL::
GIT_CONFIG_SYSTEM::
	A globális vagy rendszerszintű konfiguráció helyett a megadott
	fájlokból veszi a konfigurációt. Részletekért lásd a linkgit:git[1]-et.

GIT_CONFIG_NOSYSTEM::
	Hogy kihagyja-e a beállítások beolvasását a rendszerszintű
	$(prefix)/etc/gitconfig fájlból. Részletekért lásd a linkgit:git[1]-et.

Lásd még: <<FILES>>.

GIT_CONFIG_COUNT::
GIT_CONFIG_KEY_<n>::
GIT_CONFIG_VALUE_<n>::
	Ha a GIT_CONFIG_COUNT egy pozitív számra van beállítva, az összes
	GIT_CONFIG_KEY_<n> és GIT_CONFIG_VALUE_<n> környezeti pár, egészen
	eddig a számig, hozzáadódik a folyamat futásidejű konfigurációjához.
	A config-párok nulla-indexeltek. Bármely hiányzó kulcs vagy érték
	hibaként kezelendő. Egy üres GIT_CONFIG_COUNT ugyanúgy kezelendő,
	mint a GIT_CONFIG_COUNT=0, azaz egyetlen pár sem kerül feldolgozásra.
	Ezek a környezeti változók felülírják a konfigurációs fájlokban
	lévő értékeket, de a `git -c`-n keresztül átadott bármely explicit
	opció felülírja őket.
+
Ez olyan esetekben hasznos, amikor több git parancsot akarsz indítani
egy közös konfigurációval, de nem támaszkodhatsz konfigurációs fájlra,
például szkriptek írásakor.

GIT_CONFIG::
	Ha a `git config`-nak nincs megadva `--file` opció, a `GIT_CONFIG`
	által megadott fájlt használja, mintha az a `--file`-on keresztül
	lett volna megadva. Ez a változó nincs hatással más Git parancsokra,
	és leginkább történelmi kompatibilitási célt szolgál; általában
	nincs ok arra, hogy a `--file` opció helyett ezt használd.

[[EXAMPLES]]
EXAMPLES
--------

Egy ilyen .git/config esetén:

------------
#
# This is the config file, and
# a '#' or ';' character indicates
# a comment
#

; core variables
[core]
	; Don't trust file modes
	filemode = false

; Our diff algorithm
[diff]
	external = /usr/local/bin/diff-wrapper
	renames = true

; Proxy settings
[core]
	gitproxy=proxy-command for kernel.org
	gitproxy=default-proxy ; for all the rest

; HTTP
[http]
	sslVerify
[http "https://weak.example.com"]
	sslVerify = false
	cookieFile = /tmp/cookie.txt
------------

a filemode-ot true-ra állíthatod ezzel

------------
% git config set core.filemode true
------------

A hipotetikus proxy-parancs bejegyzéseknek valójában van egy utótagjuk,
amely megmondja, melyik URL-re vonatkoznak. Íme, hogyan lehet a
kernel.org-hoz tartozó bejegyzést "ssh"-ra változtatni.

------------
% git config set --value='for kernel.org$' core.gitproxy '"ssh" for kernel.org'
------------

Ez biztosítja, hogy csak a kernel.org-hoz tartozó kulcs/érték pár
cserélődjön le.

A renames bejegyzés törléséhez add ki ezt

------------
% git config unset diff.renames
------------

Ha egy multivar bejegyzését akarod törölni (mint a fenti
core.gitproxy), meg kell adnod egy reguláris kifejezést, amely
pontosan egy sor értékére illeszkedik.

Egy adott kulcs értékének lekérdezéséhez add ki ezt

------------
% git config get core.filemode
------------

vagy egy multivar lekérdezéséhez:

------------
% git config get --value="for kernel.org$" core.gitproxy
------------

Ha egy multivar összes értékét meg akarod tudni, add ki ezt:

------------
% git config get --all --show-names core.gitproxy
------------

Ha szeretsz veszélyesen élni, lecserélheted *az összes* core.gitproxy-t
egy újra ezzel

------------
% git config set --all core.gitproxy ssh
------------

Ha viszont tényleg csak az alapértelmezett proxy sorát akarod
lecserélni, azaz azt, amelyiknek nincs "for ..." utótagja, tegyél
valami ilyesmit:

------------
% git config set --value='! for ' core.gitproxy ssh
------------

Ahhoz, hogy ténylegesen csak a felkiáltójelet tartalmazó értékekre
illeszkedjen, ezt kell tenned

------------
% git config set --value='[!]' section.key value
------------

Egy új proxy hozzáadásához, a meglévők megváltoztatása nélkül, használd
ezt

------------
% git config set --append core.gitproxy '"proxy-command" for example.com'
------------

Egy példa arra, hogyan használj testreszabott színt a konfigurációból a
szkriptedben:

------------
#!/bin/sh
WS=$(git config get --type=color --default="blue reverse" color.diff.whitespace)
RESET=$(git config get --type=color --default="reset" "")
echo "${WS}your whitespace color or blue reverse${RESET}"
------------

A `https://weak.example.com` URL-eknél a `http.sslVerify` false-ra van
állítva, míg minden más URL-nél `true`-ra:

------------
% git config get --type=bool --url=https://good.example.com http.sslverify
true
% git config get --type=bool --url=https://weak.example.com http.sslverify
false
% git config get --url=https://weak.example.com http
http.cookieFile /tmp/cookie.txt
http.sslverify false
------------

include::config.adoc[]

BUGS
----
Ha az elavult `[section.subsection]` szintaxist használod, egy érték
megváltoztatása egy többsoros kulcs hozzáadását fogja eredményezni
módosítás helyett, ha az alszekció legalább egy nagybetűs karakterrel
van megadva. Például amikor a config így néz ki

--------
  [section.subsection]
    key = value1
--------

a `git config section.Subsection.key value2` futtatása ezt fogja
eredményezni

--------
  [section.subsection]
    key = value1
    key = value2
--------


GIT
---
A linkgit:git[1] csomag része
