git-stash(1)
============

NAME
----
git-stash - Egy piszkos munkakönyvtár változásainak elstashelése

SYNOPSIS
--------
[synopsis]
git stash list [<log-options>]
git stash show [-u | --include-untracked | --only-untracked] [<diff-options>] [<stash>]
git stash drop [-q | --quiet] [<stash>]
git stash pop [--index] [-q | --quiet] [<stash>]
git stash apply [--index] [-q | --quiet] [--label-ours=<label>] [--label-theirs=<label>] [--label-base=<label>] [<stash>]
git stash branch <branchname> [<stash>]
git stash [push] [-p | --patch] [-S | --staged] [-k | --[no-]keep-index] [-q | --quiet]
	     [-u | --include-untracked] [-a | --all] [(-m | --message) <message>]
	     [--pathspec-from-file=<file> [--pathspec-file-nul]]
	     [--] [<pathspec>...]
git stash save [-p | --patch] [-S | --staged] [-k | --[no-]keep-index] [-q | --quiet]
           [-u | --include-untracked] [-a | --all] [<message>]
git stash clear
git stash create [<message>]
git stash store [(-m | --message) <message>] [-q | --quiet] <commit>
git stash export (--print | --to-ref <ref>) [<stash>...]
git stash import <commit>

DESCRIPTION
-----------

Használd a `git stash`-t, amikor rögzíteni akarod a munkakönyvtár és az
index aktuális állapotát, de vissza akarsz térni egy tiszta
munkakönyvtárhoz. A parancs félreteszi a helyi módosításaidat, és a
munkakönyvtárat visszaállítja a `HEAD` commithoz.

Az e parancs által elstashelt módosítások a `git stash list`-tel
kilistázhatók, a `git stash show`-val megvizsgálhatók, és a
`git stash apply`-jal visszaállíthatók (esetleg egy másik commit
tetejére). A `git stash` argumentumok nélküli hívása egyenértékű a
`git stash push`-sal. Egy stash alapból "WIP on '<branchname>' ..."-ként
szerepel a listában, de adhatsz egy leíróbb üzenetet a parancssorban,
amikor létrehozol egyet.

A legutóbb létrehozott stashed a `refs/stash`-ben van tárolva; a
régebbi stashek ennek a referenciának a reflogjában találhatók, és a
szokásos reflog-szintaxissal nevezhetők meg (pl. a `stash@{0}` a
legutóbb létrehozott stash, a `stash@{1}` az azt megelőző, a
`stash@{2.hours.ago}` is lehetséges). A stashekre úgy is lehet
hivatkozni, hogy csak a stash-indexet adod meg (pl. az `<n>` egész szám
egyenértékű a `stash@{<n>}`-nel).

COMMANDS
--------

`push [-p | --patch] [-S | --staged] [-k | --[no-]keep-index] [-u | --include-untracked] [ -a | --all] [-q | --quiet] [(-m|--message) <message>] [--pathspec-from-file=<file> [--pathspec-file-nul]] [--] [<pathspec>...]`::

	Elmenti a helyi módosításaidat egy új 'stash-bejegyzésbe', és
	visszagörgeti őket `HEAD`-re (a working tree-ben és az indexben).
	A `_<message>_` rész opcionális, és a leírást adja meg az stashelt
	állapot mellé.
+
Gyors pillanatkép készítéséhez elhagyhatod a "push"-t. Ebben a módban a
pathspec-elemek csak egy dupla kötőjel `--` után engedélyezettek, hogy
egy elgépelt alparancs ne hozzon létre nem kívánt stash-bejegyzést.

`save [-p | --patch] [-S | --staged] [-k | --[no-]keep-index] [-u | --include-untracked] [-a | --all] [-q | --quiet] [<message>]`::

	Ez a kapcsoló elavult, helyette a 'git stash push' használandó.
	Abban különbözik a "stash push"-tól, hogy nem fogad pathspecet.
	Ehelyett az összes nem opció argumentum összefűződik, hogy a
	stash-üzenetet alkossa.

`list [<log-options>]`::

	Kilistázza a stash-bejegyzéseket, amelyek jelenleg megvannak.
	Minden 'stash-bejegyzés' a nevével (pl. a `stash@{0}` a legutóbbi
	bejegyzés, a `stash@{1}` az azt megelőző, stb.), annak a branchnek a
	nevével, amely aktuális volt a bejegyzés készültekor, és annak a
	commitnak a rövid leírásával szerepel, amelyen a bejegyzés alapult.
+
----------------------------------------------------------------
stash@{0}: WIP on submit: 6ebd0e2... Update git-stash documentation
stash@{1}: On master: 9cc0589... Add git-stash
----------------------------------------------------------------
+
A parancs a 'git log' parancsra alkalmazható opciókat fogad annak
szabályozására, hogy mi és hogyan jelenjen meg. Lásd: linkgit:git-log[1].

`show [-u | --include-untracked | --only-untracked] [<diff-options>] [<stash>]`::

	Megmutatja a stash-bejegyzésben rögzített változásokat diffként az
	stashelt tartalom és aközött a commit között, amikor a
	stash-bejegyzés eredetileg létrejött.
	Alapból a parancs a diffstatot mutatja, de elfogad minden formátumot,
	amit a 'git diff' ismer (pl. `git stash show -p stash@{1}` a
	második legutóbbi bejegyzés patch formájában való megtekintéséhez).
	Ha nincs `_<diff-option>_` megadva, az alapértelmezett viselkedést a
	`stash.showStat` és a `stash.showPatch` konfigurációs változók
	adják. A `stash.showIncludeUntracked`-et is használhatod annak
	beállítására, hogy a `--include-untracked` alapból engedélyezve
	legyen-e.

`pop [--index] [-q | --quiet] [<stash>]`::

	Eltávolít egyetlen stashelt állapotot a stash-listából, és
	alkalmazza az aktuális working tree állapot tetejére, azaz a
	`git stash push` fordított műveletét végzi. A munkakönyvtárnak
	egyeznie kell az indexszel.
+
Az állapot alkalmazása konfliktusokkal meghiúsulhat; ebben az esetben
nem távolítódik el a stash-listából. Kézzel kell feloldanod a
konfliktusokat, és utána kézzel meghívnod a `git stash drop`-ot.

`apply [--index] [-q | --quiet] [<stash>]`::

	Mint a `pop`, de nem távolítja el az állapotot a stash-listából. A
	`pop`-pal ellentétben a `<stash>` bármely commit lehet, amely úgy
	néz ki, mint egy `stash push` vagy `stash create` által létrehozott
	commit.

`branch <branchname> [<stash>]`::

	Létrehoz és checkoutol egy `_<branchname>_` nevű új branchet, abból a
	commitból kiindulva, amelynél a `_<stash>_` eredetileg létrejött,
	majd alkalmazza a `_<stash>_`-ben rögzített változásokat az új
	working tree-re és indexre. Ha ez sikerül, és a `_<stash>_` egy
	`stash@{<revision>}` alakú referencia, akkor dropolja a `_<stash>_`-t.
+
Ez akkor hasznos, ha az a branch, amelyen a `git stash push`-t
futtattad, eleget változott ahhoz, hogy a `git stash apply`
konfliktusok miatt meghiúsuljon. Mivel a stash-bejegyzés arra a
commitra alkalmazódik, amely HEAD volt a `git stash` futtatásának
idején, konfliktusok nélkül állítja vissza az eredetileg stashelt
állapotot.

`clear`::
	Eltávolítja az összes stash-bejegyzést. Vedd figyelembe, hogy azok
	a bejegyzések ezután prune-olás alá esnek, és lehet, hogy nem lehet
	őket helyreállítani (egy lehetséges stratégiához lásd az 'EXAMPLES'
	szakaszt lentebb).

`drop [-q | --quiet] [<stash>]`::
	Eltávolít egyetlen stash-bejegyzést a stash-bejegyzések listájából.

`create`::
	Létrehoz egy stash-bejegyzést (amely egy közönséges commitobjektum),
	és visszaadja az objektumnevét, anélkül, hogy bárhol tárolná a
	ref-névtérben.
	Ez szkriptek számára hasznos. Valószínűleg nem ezt a parancsot
	akarod használni; lásd a "push"-t fentebb.

`store`::

	Egy adott, 'git stash create' által létrehozott stash (amely egy
	lógó merge commit) tárolása a stash refben, a stash reflogjának
	frissítésével. Ez szkriptek számára hasznos. Valószínűleg nem ezt a
	parancsot akarod használni; lásd a "push"-t fentebb.

`export ( --print | --to-ref <ref> ) [<stash>...]`::

	Exportálja a megadott stasheket, vagy mindet, ha egy sincs megadva,
	egy commit-láncba, amely a normál fetch- és push-mechanizmusokkal
	átvihető, majd az `import` alparanccsal importálható.

`import <commit>`::
	Importálja a megadott stasheket a megadott commitból, amelyet az
	`export`-nak kellett létrehoznia, és hozzáadja őket a stashek
	listájához. A meglévő stashek lecseréléséhez előbb használd a
	`clear`-t.

OPTIONS
-------
`-a`::
`--all`::
	Ez a kapcsoló csak a `push` és `save` parancsnál érvényes.
+
Az összes ignorált és nem követett fájl is stashelődik, majd a
`git clean`-nel feltakarításra kerül.

`-u`::
`--include-untracked`::
`--no-include-untracked`::
	A `push` és `save` paranccsal együtt használva az összes nem
	követett fájl is stashelődik, majd a `git clean`-nel feltakarításra
	kerül.
+
A `show` paranccsal együtt használva a diff részeként megjeleníti a
stash-bejegyzésben lévő nem követett fájlokat.

`--only-untracked`::
	Ez a kapcsoló csak a `show` parancsnál érvényes.
+
A diff részeként csak a stash-bejegyzésben lévő nem követett fájlokat
jeleníti meg.

`--index`::
	Ez a kapcsoló csak a `pop` és `apply` parancsnál érvényes.
+
Megpróbálja visszaállítani nemcsak a working tree változásait, hanem az
indexéit is. Ez azonban meghiúsulhat, ha konfliktusaid vannak (amelyek
az indexben tárolódnak, ahol ezért már nem tudod alkalmazni a
változásokat úgy, ahogy eredetileg voltak).

`--label-ours=<label>`::
`--label-theirs=<label>`::
`--label-base=<label>`::
	Ezek a kapcsolók csak az `apply` parancsnál érvényesek.
+
A konfliktusjelölőkben a megadott címkéket használja az alapértelmezett
"Updated upstream", "Stashed changes" és "Stash base" helyett. A
`--label-base` csak a merge.conflictStyle=diff3 mellett fejt ki hatást.

`-k`::
`--keep-index`::
`--no-keep-index`::
	Ez a kapcsoló csak a `push` és `save` parancsnál érvényes.
+
Az összes, az indexhez már hozzáadott változás érintetlenül marad.

`-p`::
`--patch`::
	Ez a kapcsoló csak a `push` és `save` parancsnál érvényes.
+
Interaktívan választhatsz ki stashelendő hunkokat a HEAD és a working
tree közötti diffből. A stash-bejegyzés úgy épül fel, hogy az
indexállapota megegyezik a repository-d indexállapotával, a worktree-je
pedig csak az interaktívan kiválasztott változásokat tartalmazza. A
kiválasztott változások ezután visszagörgetődnek a worktree-dből. A
`--patch` mód működtetésének megtanulásához lásd a linkgit:git-add[1]
``Interaktív mód'' szakaszát.
+
A `--patch` kapcsoló maga után vonja a `--keep-index`-et. A
`--no-keep-index`-szel felülbírálhatod ezt.

include::diff-context-options.adoc[]

`-S`::
`--staged`::
	Ez a kapcsoló csak a `push` és `save` parancsnál érvényes.
+
Csak a jelenleg stage-elt változásokat stasheli. Ez hasonló az
alapszintű `git commit`-hoz, azzal a különbséggel, hogy az állapot a
stashbe commitolódik, nem az aktuális branchbe.
+
A `--patch` kapcsolónak elsőbbsége van ezzel szemben.

`--pathspec-from-file=<file>`::
	Ez a kapcsoló csak a `push` parancsnál érvényes.
+
A pathspec a `_<file>_`-ban adódik át, nem parancssori argumentumként.
Ha a `_<file>_` pontosan `-`, akkor a standard bemenet kerül
felhasználásra. A pathspec-elemeket LF vagy CR/LF választja el. A
pathspec-elemek idézőjelezhetők a `core.quotePath` konfigurációs
változónál elmagyarázott módon (lásd: linkgit:git-config[1]). Lásd még a
`--pathspec-file-nul`-t és a globális `--literal-pathspecs`-et.

`--pathspec-file-nul`::
	Ez a kapcsoló csak a `push` parancsnál érvényes.
+
Csak a `--pathspec-from-file`-lal van értelme. A pathspec-elemeket NUL
karakter választja el, és minden más karakter literálisan értendő (a
sortöréseket és az idézőjeleket is beleértve).

`-q`::
`--quiet`::
	Ez a kapcsoló csak az `apply`, `drop`, `pop`, `push`, `save`,
	`store` parancsnál érvényes.
+
Csendes, elnyomja a visszajelző üzeneteket.

`--print`::
	Ez a kapcsoló csak az `export` parancsnál érvényes.
+
Létrehozza az exportált stasheket képviselő commit-láncot anélkül, hogy
bárhol tárolná a ref-névtérben, és kiírja az objektumazonosítót a
standard kimenetre. Ez szkriptekhez készült.

`--to-ref`::
	Ez a kapcsoló csak az `export` parancsnál érvényes.
+
Létrehozza az exportált stasheket képviselő commit-láncot, és a megadott
refbe tárolja.

`--`::
	Ez a kapcsoló csak a `push` parancsnál érvényes.
+
Elválasztja a pathspecet az opcióktól egyértelműsítési céllal.

`<pathspec>...`::
	Ez a kapcsoló csak a `push` parancsnál érvényes.
+
Az új stash-bejegyzés csak azoknak a fájloknak a módosított állapotát
rögzíti, amelyek illeszkednek a pathspecre. Az indexbejegyzések és a
working tree fájljai ezután szintén csak ezeknél a fájloknál görgetődnek
vissza a HEAD-beli állapotra, érintetlenül hagyva azokat a fájlokat,
amelyek nem illeszkednek a pathspecre.
+
A további részletekért lásd a 'pathspec' bejegyzést a
linkgit:gitglossary[7]-ben.

_<stash>_::
	Ez a kapcsoló csak az `apply`, `branch`, `drop`, `pop`, `show` és
	`export` parancsnál érvényes.
+
Egy `stash@{<revision>}` alakú referencia. Ha nincs `_<stash>_` megadva,
a legutóbbi stash feltételezett (azaz a `stash@{0}`).

DISCUSSION
----------

Egy stash-bejegyzést egy commit képvisel, amelynek a fája a
munkakönyvtár állapotát rögzíti, az első szülője pedig az a commit,
amely `HEAD` volt a bejegyzés létrehozásakor. A második szülő fája az
index állapotát rögzíti a bejegyzés készültekor, és a `HEAD` commit
gyermekévé válik. Az ősgráf így néz ki:

            .----W
           /    /
     -----H----I

ahol `H` a `HEAD` commit, `I` egy olyan commit, amely az index
állapotát rögzíti, `W` pedig egy olyan commit, amely a working tree
állapotát rögzíti.


EXAMPLES
--------

Pull-olás egy piszkos fába::

Amikor valaminek a közepén vagy, megtudod, hogy vannak upstream
változások, amelyek esetleg relevánsak ahhoz, amit csinálsz. Amikor a
helyi változásaid nem ütköznek az upstream változásaival, egy egyszerű
`git pull` engedi, hogy előrelépj.
+
Vannak azonban esetek, amikor a helyi változásaid tényleg ütköznek az
upstream változásaival, és a `git pull` megtagadja a változásaid
felülírását. Ilyen esetben elstashelheted a változásaidat, végrehajthatsz
egy pull-t, majd unstashelhetsz, így:
+
----------------------------------------------------------------
$ git pull
 ...
file foobar not up to date, cannot merge.
$ git stash
$ git pull
$ git stash pop
----------------------------------------------------------------

Megszakított munkafolyamat::

Amikor valaminek a közepén vagy, bejön a főnököd, és követeli, hogy
azonnal javíts meg valamit. Hagyományosan egy ideiglenes branchre
commitolnál, hogy félretedd a változásaidat, majd visszatérnél az
eredeti branchedre, hogy elvégezd a sürgős javítást, így:
+
----------------------------------------------------------------
# ... hack hack hack ...
$ git switch -c my_wip
$ git commit -a -m "WIP"
$ git switch master
$ edit emergency fix
$ git commit -a -m "Fix in a hurry"
$ git switch my_wip
$ git reset --soft HEAD^
# ... continue hacking ...
----------------------------------------------------------------
+
A fentiek egyszerűsítéséhez használhatod a 'git stash'-t, így:
+
----------------------------------------------------------------
# ... hack hack hack ...
$ git stash
$ edit emergency fix
$ git commit -a -m "Fix in a hurry"
$ git stash pop
# ... continue hacking ...
----------------------------------------------------------------

Részleges commitok tesztelése::

Használhatod a `git stash push --keep-index`-et, amikor a work tree
változásaiból két vagy több commitot akarsz csinálni, és minden
változást tesztelni akarsz a commitolás előtt:
+
----------------------------------------------------------------
# ... hack hack hack ...
$ git add --patch foo            # add just first part to the index
$ git stash push --keep-index    # save all other changes to the stash
$ edit/build/test first part
$ git commit -m 'First part'     # commit fully tested change
$ git stash pop                  # prepare to work on all other changes
# ... repeat above five steps until one commit remains ...
$ edit/build/test remaining parts
$ git commit foo -m 'Remaining parts'
----------------------------------------------------------------

Nem kapcsolódó változások mentése jövőbeli felhasználásra::

Amikor hatalmas változtatások közepén vagy, és találsz valami nem
kapcsolódó problémát, amit nem akarsz elfelejteni megjavítani,
elvégezheted a változás(oka)t, stage-elheted őket, és a
`git stash push --staged`-dzsel elstashelheted őket jövőbeli
felhasználásra. Ez hasonló a stage-elt változások commitolásához, csak a
commit a stashben köt ki, nem az aktuális branchen.
+
----------------------------------------------------------------
# ... hack hack hack ...
$ git add --patch foo           # add unrelated changes to the index
$ git stash push --staged       # save these changes to the stash
# ... hack hack hack, finish current changes ...
$ git commit -m 'Massive'       # commit fully tested changes
$ git switch fixup-branch       # switch to another branch
$ git stash pop                 # to finish work on the saved changes
----------------------------------------------------------------

Tévedésből kiürített/dropolt stash-bejegyzések helyreállítása::

Ha tévedésből dropolsz vagy kiürítesz stash-bejegyzéseket, azok nem
állíthatók helyre a normál biztonsági mechanizmusokkal. Kipróbálhatod
azonban a következő varázsigét, hogy megkapd azoknak a
stash-bejegyzéseknek a listáját, amelyek még a repository-dban vannak,
de már nem elérhetők:
+
----------------------------------------------------------------
git fsck --unreachable |
grep commit | cut -d\  -f3 |
xargs git log --merges --no-walk --grep=WIP
----------------------------------------------------------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

:git-stash: 1
include::config/stash.adoc[]


SEE ALSO
--------
linkgit:git-checkout[1],
linkgit:git-commit[1],
linkgit:git-reflog[1],
linkgit:git-reset[1],
linkgit:git-switch[1]

GIT
---
A linkgit:git[1] csomag része
