git-http-push(1)
================

NAME
----
git-http-push - Objektumok pusholása HTTP/DAV felett egy másik repository-ba


SYNOPSIS
--------
[verse]
'git http-push' [--all] [--dry-run] [--force] [--verbose] <URL> <ref> [<ref>...]

DESCRIPTION
-----------
Elküldi a hiányzó objektumokat a remote repository-ba, és frissíti a
remote branchet.

*NOTE*: Ez a parancs átmenetileg le van tiltva, ha a libcurl-öd
7.16-nál régebbi, mivel a jelentések szerint ez a kombináció nem
működik, és időnként megsérti a repository-t.

OPTIONS
-------
--all::
	Ne feltételezze, hogy a remote repository a jelenlegi
	állapotában teljes, és ellenőrizze, hogy a teljes helyi
	referencia előzményének minden objektuma létezik-e a remote
	repository-ban.

--force::
	A parancs általában nem hajlandó frissíteni egy olyan remote
	referenciát, amely nem őse a felülírásra használt helyi
	referenciának. Ez a kapcsoló letiltja az ellenőrzést. Ez azt
	jelenti, hogy a remote repository commitokat veszíthet;
	óvatosan használd.

--dry-run::
	Mindent megtesz, kivéve a frissítések tényleges elküldését.

--verbose::
	Jelenti a helyben bejárt objektumok listáját és a remote
	repository-ba sikeresen elküldött objektumok listáját.

-d::
-D::
	Eltávolítja a <ref> referenciát a remote repository-ból. A
	megadott branch nem lehet a remote HEAD. Ha a -d meg van adva,
	a következő további feltételeknek is teljesülniük kell:

	- A remote HEAD-nek egy helyben létező objektumra kell
	  feloldódnia
	- A megadott branch egy helyben létező objektumra oldódik fel
	- A megadott branch a remote HEAD őse

<ref>...::
	A frissítendő remote referenciák.


SPECIFYING THE REFS
-------------------

A '<ref>' megadás lehet egyetlen minta, vagy két ilyen minta párja
kettősponttal ":" elválasztva (ez azt jelenti, hogy egy
referencianévben nem lehet kettőspont). Egyetlen '<name>' minta csak
a '<name>:<name>' rövidítése.

Minden '<src>:<dst>' mintapár a forrásoldalból (a kettőspont előtt)
és a céloldalból (a kettőspont után) áll. A pusholandó referenciát a
forrásoldalra illeszkedő találat megkeresése határozza meg, azt pedig,
hogy hova pusholódik, a céloldal használata dönti el.

 - Hiba, ha a '<src>' nem pontosan egy helyi referenciára
   illeszkedik.

 - Ha a '<dst>' egyetlen remote referenciára sem illeszkedik, akkor
   vagy

   * a "refs/"-fel kell kezdődnie; ebben az esetben a <dst> szó
     szerint lesz a cél.

   * <src> == <dst>, és a <src>-re illeszkedő referencia nem
     létezhet a remote referenciák halmazában; a <src>-re helyben
     illeszkedő referencia lesz a cél neve.

A `--force` nélkül a <src> referencia csak akkor kerül tárolásra a
remote-on, ha a <dst> nem létezik, vagy a <dst> a <src> valódi
részhalmaza (azaz őse). Ez az ellenőrzés, amelyet "fast-forward
check" néven ismernek, azért történik, hogy elkerülje a remote
referencia véletlen felülírását és mások commitjainak elvesztését
onnan.

A `--force` mellett a fast-forward ellenőrzés minden referenciára le
van tiltva.

Opcionálisan egy <ref> paraméter elé tehető egy plusz '+' jel, hogy a
fast-forward ellenőrzést csak arra a referenciára tiltsa le.

GIT
---
A linkgit:git[1] csomag része
