git-verify-pack(1)
==================

NAME
----
git-verify-pack - Érvényesíti a csomagolt Git-archívumfájlokat


SYNOPSIS
--------
[synopsis]
git verify-pack [-v | --verbose] [-s | --stat-only] [--] <pack>.idx...


DESCRIPTION
-----------
Beolvassa a parancssorban megadott csomagolt Git-archívum minden
idx-fájlját, és ellenőrzi az idx-fájlt és a hozzá tartozó packfile-t.

OPTIONS
-------
`-v`::
`--verbose`::
	A pack ellenőrzése után megjeleníti a packban lévő objektumok
	listáját, valamint a delta-lánchossz hisztogramját.

`-s`::
`--stat-only`::
	Nem ellenőrzi a pack tartalmát; csak a delta-lánchossz
	hisztogramját mutatja meg. A `--verbose`-zal az objektumlista
	is megjelenik.

`--`::
	A további argumentumokat már nem értelmezi opcióként.

OUTPUT FORMAT
-------------
A `-v` opció megadásakor a használt formátum:

	object-name type size size-in-packfile offset-in-packfile

azoknál az objektumoknál, amelyek nincsenek deltásítva a packban, és

	object-name type size size-in-packfile offset-in-packfile depth base-object-name

azoknál, amelyek deltásítva vannak.

GIT
---
A linkgit:git[1] csomag része
