git-check-attr(1)
=================

NAME
----
git-check-attr - A gitattributes-információ megjelenítése


SYNOPSIS
--------
[verse]
'git check-attr' [--source <tree-ish>] [-a | --all | <attr>...] [--] <pathname>...
'git check-attr' --stdin [-z] [--source <tree-ish>] [-a | --all | <attr>...]

DESCRIPTION
-----------
Minden egyes útvonalnévhez ez a parancs felsorolja, hogy az egyes
attribútumok 'unspecified', 'set' vagy 'unset' állapotúak-e
gitattribútumként az adott útvonalnévnél.

OPTIONS
-------
-a::
--all::
	Felsorolja az összes attribútumot, amely a megadott
	útvonalakhoz van társítva. Ha ez az opció van használva, akkor
	az 'unspecified' attribútumok nem kerülnek bele a kimenetbe.

--cached::
	Csak az indexben lévő `.gitattributes`-t veszi figyelembe, a
	munkakönyvtárat figyelmen kívül hagyva.

--stdin::
	Útvonalneveket olvas be a standard bemenetről, soronként egyet,
	a parancssor helyett.

-z::
	A kimeneti formátum géppel elemezhetővé van módosítva.
	Ha a `--stdin` is meg van adva, a bemeneti útvonalak NUL
	karakterrel vannak elválasztva a sortörés karakter helyett.

--source=<tree-ish>::
	Az attribútumokat a megadott tree-ish alapján ellenőrzi. Gyakori
	a forrás-tree-t egy hozzá tartozó commit, branch vagy tag
	megnevezésével megadni.

\--::
	Az összes megelőző argumentumot attribútumként, az összes
	következő argumentumot pedig útvonalnévként értelmezi.

Ha sem a `--stdin`, sem a `--all`, sem a `--` nincs használva, az első
argumentum attribútumként lesz kezelve, a többi argumentum pedig
útvonalnévként.

OUTPUT
------

A kimenet alakja:
<path> COLON SP <attribute> COLON SP <info> LF

hacsak a `-z` nincs érvényben, ekkor NUL kerül határolóként
használatra:
<path> NUL <attribute> NUL <info> NUL


A <path> a lekérdezett fájl útvonala, az <attribute> a lekérdezett
attribútum, az <info> pedig a következők egyike lehet:

'unspecified';; amikor az attribútum nincs meghatározva az útvonalhoz.
'unset';;	amikor az attribútum hamisként van meghatározva.
'set';;		amikor az attribútum igazként van meghatározva.
<value>;;	amikor egy érték van hozzárendelve az attribútumhoz.

A pufferelés a `GIT_FLUSH` opciónál dokumentáltak szerint történik a
linkgit:git[1]-ben. A hívó felelős azért, hogy elkerülje a
holtpontokat, amelyeket egy bemeneti puffer túltöltése vagy egy üres
kimeneti pufferből való olvasás okoz.

EXAMPLES
--------

A példákban a következő '.gitattributes' fájl van használva:

---------------
*.java diff=java -crlf myAttr
NoMyAttr.java !myAttr
README caveat=unspecified
---------------

* Egyetlen attribútum listázása:
+
---------------
$ git check-attr diff org/example/MyClass.java
org/example/MyClass.java: diff: java
---------------

* Több attribútum listázása egy fájlhoz:
+
---------------
$ git check-attr crlf diff myAttr -- org/example/MyClass.java
org/example/MyClass.java: crlf: unset
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Az összes attribútum listázása egy fájlhoz:
+
---------------
$ git check-attr --all -- org/example/MyClass.java
org/example/MyClass.java: diff: java
org/example/MyClass.java: myAttr: set
---------------

* Egy attribútum listázása több fájlhoz:
+
---------------
$ git check-attr myAttr -- org/example/MyClass.java org/example/NoMyAttr.java
org/example/MyClass.java: myAttr: set
org/example/NoMyAttr.java: myAttr: unspecified
---------------

* Nem minden érték egyformán egyértelmű:
+
---------------
$ git check-attr caveat README
README: caveat: unspecified
---------------

SEE ALSO
--------
linkgit:gitattributes[5].

GIT
---
A linkgit:git[1] csomag része
