git-shell(1)
============

NAME
----
git-shell - Korlátozott bejelentkezési shell csak Gitre korlátozott SSH-hozzáféréshez


SYNOPSIS
--------
[verse]
'chsh' -s $(command -v git-shell) <user>
'git clone' <user>`@localhost:/path/to/repo.git`
'ssh' <user>`@localhost`

DESCRIPTION
-----------

Ez egy bejelentkezési shell SSH-fiókokhoz, amely korlátozott
Git-hozzáférést biztosít. Csak a pull/push funkciót megvalósító
szerveroldali Git-parancsok, valamint a felhasználó home könyvtárában
lévő `git-shell-commands` nevű alkönyvtárban található egyéni parancsok
végrehajtását engedélyezi.

COMMANDS
--------

A 'git shell' a következő parancsokat fogadja el a `-c` opció után:

'git receive-pack <argument>'::
'git upload-pack <argument>'::
'git upload-archive <argument>'::
	Meghívja a megfelelő szerveroldali parancsot a kliens
	'git push', 'git fetch' vagy 'git archive --remote'
	kérésének kiszolgálásához.
'cvs server'::
	CVS-szervert utánoz.  Lásd linkgit:git-cvsserver[1].

Ha van `~/git-shell-commands` könyvtár, a 'git shell' egyéb, egyéni
parancsokat is kezel úgy, hogy a
"`git-shell-commands/<command> <arguments>`" parancsot futtatja a
felhasználó home könyvtárából.

INTERACTIVE USE
---------------

Alapértelmezés szerint a fenti parancsok csak a `-c` opcióval
hajthatók végre; a shell nem interaktív.

Ha van `~/git-shell-commands` könyvtár, a 'git shell' interaktívan
is futtatható (argumentumok nélkül). Ha van `help` parancs a
`git-shell-commands` könyvtárban, az lefut, hogy áttekintést adjon a
felhasználónak az engedélyezett műveletekről. Ezután megjelenik egy
"git> " prompt, amelynél beírható a `git-shell-commands` könyvtár
bármelyik parancsa, vagy az `exit` a kapcsolat lezárásához.

Ezt a módot általában adminisztratív felületként használják, amellyel
a felhasználók listázhatják az elérhető repository-kat, létrehozhatnak,
törölhetnek vagy átnevezhetnek repository-kat, illetve módosíthatják a
repository-k leírását és jogosultságait.

Ha létezik `no-interactive-login` parancs, akkor az lefut, és az
interaktív shell megszakad.

EXAMPLES
--------

Az interaktív bejelentkezések letiltásához, helyette üdvözlőüzenet
megjelenítésével:

----------------
$ chsh -s /usr/bin/git-shell
$ mkdir $HOME/git-shell-commands
$ cat >$HOME/git-shell-commands/no-interactive-login <<\EOF
#!/bin/sh
printf '%s\n' "Hi $USER! You've successfully authenticated, but I do not"
printf '%s\n' "provide interactive shell access."
exit 128
EOF
$ chmod +x $HOME/git-shell-commands/no-interactive-login
----------------

A git-cvsserver hozzáférés engedélyezéséhez (amelynek általában a
fenti `no-interactive-login` példa az előfeltétele, mivel a
git-shell-commands könyvtár létrehozása lehetővé teszi az interaktív
bejelentkezéseket):

----------------
$ cat >$HOME/git-shell-commands/cvs <<\EOF
if ! test $# = 1 && test "$1" = "server"
then
	echo >&2 "git-cvsserver only handles \"server\""
	exit 1
fi
exec git cvsserver server
EOF
$ chmod +x $HOME/git-shell-commands/cvs
----------------

SEE ALSO
--------
ssh(1),
linkgit:git-daemon[1],
contrib/git-shell-commands/README

GIT
---
A linkgit:git[1] csomag része
