git-cherry(1)
=============

NAME
----
git-cherry - Az upstream-re még nem alkalmazott commitok megkeresése

SYNOPSIS
--------
[verse]
'git cherry' [-v] [<upstream> [<head> [<limit>]]]

DESCRIPTION
-----------
Meghatározza, hogy vannak-e a `<head>..<upstream>` tartományban olyan
commitok, amelyek egyenértékűek a `<limit>..<head>` tartománybeliekkel.

Az egyenértékűség-teszt a diffen alapul, a whitespace és a sorszámok
eltávolítása után. A git-cherry ezért felismeri, ha commitokat
"másoltak" a linkgit:git-cherry-pick[1], a linkgit:git-am[1] vagy a
linkgit:git-rebase[1] segítségével.

Kiírja minden, a `<limit>..<head>` tartományban lévő commit SHA1-jét,
`-` előjellel azok esetén, amelyeknek van megfelelőjük az <upstream>-ben,
és `+` előjellel azok esetén, amelyeknek nincs.

OPTIONS
-------
-v::
	Megjeleníti a commitok tárgysorát a SHA1-ek mellett.

<upstream>::
	Az az upstream branch, amelyben egyenértékű commitokat keres.
	Alapértelmezés szerint a HEAD upstream branch-e.

<head>::
	Munka branch; alapértelmezés szerint a HEAD.

<limit>::
	Nem jelenti a limit-ig (azt is beleértve) tartó commitokat.

EXAMPLES
--------

[[_patch_workflows]]
Patch munkafolyamatok
~~~~~~~~~~~~~~~~~~~~~

A git-cherry-t gyakran használják patch-alapú munkafolyamatokban (lásd
linkgit:gitworkflows[7]) annak megállapítására, hogy egy patch-sorozatot
alkalmazott-e már az upstream maintainer. Egy ilyen munkafolyamatban
létrehozhatsz és elküldhetsz egy topic branch-et például így:

------------
$ git checkout -b topic origin/master
# work and create some commits
$ git format-patch origin/master
$ git send-email ... 00*
------------

Később megnézheted, hogy alkalmazták-e a változtatásaidat, ezt mondva
(még mindig a `topic`-on):

------------
$ git fetch  # update your notion of origin/master
$ git cherry -v
------------

[[_concrete_example]]
Konkrét példa
~~~~~~~~~~~~~

Egy olyan helyzetben, amikor a topic három commitból állt, és a
maintainer kettőt alkalmazott közülük, a helyzet így nézhet ki:

------------
$ git log --graph --oneline --decorate --boundary origin/master...topic
* 7654321 (origin/master) upstream tip commit
[... snip some other commits ...]
* cccc111 cherry-pick of C
* aaaa111 cherry-pick of A
[... snip a lot more that has happened ...]
| * cccc000 (topic) commit C
| * bbbb000 commit B
| * aaaa000 commit A
|/
o 1234567 branch point
------------

Ilyen esetekben a git-cherry tömör összefoglalót ad arról, hogy mi
vár még alkalmazásra:

------------
$ git cherry origin/master topic
- cccc000... commit C
+ bbbb000... commit B
- aaaa000... commit A
------------

Itt látjuk, hogy az A és C commitok (`-` jellel jelölve) elhagyhatók
a `topic` branch-edből, amikor rebase-eled az `origin/master` tetejére,
míg a B commitot (`+` jellel jelölve) meg kell tartani, hogy elküldésre
kerüljön az `origin/master`-re való alkalmazáshoz.


[[_using_a_limit]]
Limit használata
~~~~~~~~~~~~~~~~

Az opcionális <limit> olyan esetekben hasznos, amikor a topic másik,
upstream-ben nem lévő munkára épül. Az előző példát kibővítve ez így
nézhet ki:

------------
$ git log --graph --oneline --decorate --boundary origin/master...topic
* 7654321 (origin/master) upstream tip commit
[... snip some other commits ...]
* cccc111 cherry-pick of C
* aaaa111 cherry-pick of A
[... snip a lot more that has happened ...]
| * cccc000 (topic) commit C
| * bbbb000 commit B
| * aaaa000 commit A
| * 0000fff (base) unpublished stuff F
[... snip ...]
| * 0000aaa unpublished stuff A
|/
o 1234567 merge-base between upstream and topic
------------

Ha a `base`-t adod meg limitként, elkerülheted a `base` és `topic`
közötti commitok felsorolását:

------------
$ git cherry origin/master topic base
- cccc000... commit C
+ bbbb000... commit B
- aaaa000... commit A
------------


SEE ALSO
--------
linkgit:git-patch-id[1]

GIT
---
A linkgit:git[1] csomag része
