git-column(1)
=============

NAME
----
git-column - Adatok megjelenítése oszlopokban

SYNOPSIS
--------
[verse]
'git column' [--command=<name>] [--[raw-]mode=<mode>] [--width=<width>]
	     [--indent=<string>] [--nl=<string>] [--padding=<n>]

DESCRIPTION
-----------
Ez a parancs a standard bemenetének sorait egy több oszlopból álló
táblázattá formázza. Minden bemeneti sor a táblázat egy celláját
foglalja el. Más git parancsok belsőleg használják a kimenet
oszlopokba formázásához.

OPTIONS
-------
--command=<name>::
	Az elrendezési mód lekeresése a column.<name> és a column.ui
	konfigurációs változók használatával.

--mode=<mode>::
	Az elrendezési mód megadása. Az opciószintaxisért lásd a
	column.ui konfigurációs változót a linkgit:git-config[1]
	dokumentumban.

--raw-mode=<n>::
	Ugyanaz, mint a --mode, de a módot számként kódolva várja. Ezt
	főleg más parancsok használják, amelyek már feldolgozták az
	elrendezési módot.

--width=<width>::
	A terminál szélességének megadása. Alapértelmezetten a 'git
	column' érzékeli a terminál szélességét, vagy 80-ra esik
	vissza, ha ezt nem tudja megtenni.

--indent=<string>::
	Minden sor elején kiírandó string.

--nl=<string>::
	Minden sor végén kiírandó string, beleértve az újsor karaktert is.

--padding=<N>::
	Az oszlopok közötti szóközök száma. Alapértelmezetten egy szóköz.

EXAMPLES
--------

Adatok formázása oszlopok szerint:

------------
$ seq 1 24 | git column --mode=column --padding=5
1      4      7      10     13     16     19     22
2      5      8      11     14     17     20     23
3      6      9      12     15     18     21     24
------------

Adatok formázása sorok szerint:

------------
$ seq 1 21 | git column --mode=row --padding=5
1      2      3      4      5      6      7
8      9      10     11     12     13     14
15     16     17     18     19     20     21
------------

Néhány tag listázása egy táblázatban, nem egyenlő oszlopszélességekkel:

------------
$ git tag --list 'v2.4.*' --column=row,dense
v2.4.0  v2.4.0-rc0  v2.4.0-rc1  v2.4.0-rc2  v2.4.0-rc3
v2.4.1  v2.4.10     v2.4.11     v2.4.12     v2.4.2
v2.4.3  v2.4.4      v2.4.5      v2.4.6      v2.4.7
v2.4.8  v2.4.9
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/column.adoc[]

GIT
---
A linkgit:git[1] csomag része
