git-bugreport(1)
================

NAME
----
git-bugreport - Információk gyűjtése hibajelentés beküldéséhez

SYNOPSIS
--------
[verse]
'git bugreport' [(-o | --output-directory) <path>]
		[(-s | --suffix) <format> | --no-suffix]
		[--diagnose[=<mode>]]

DESCRIPTION
-----------
Információkat gyűjt a felhasználó gépéről, a Git kliensről és a repository
állapotáról, kiegészítve egy űrlappal, amely a felhasználó által
tapasztalt viselkedésről kér információt, és mindezt egyetlen szöveges
fájlban tárolja, amelyet a felhasználó ezután megoszthat, például a Git
levelezőlistán, egy észlelt hiba jelentése céljából.

A következő információkat kéri a felhasználótól:

 - A reprodukálás lépései
 - A várt viselkedés
 - A tényleges viselkedés

A következő információk automatikusan begyűjtésre kerülnek:

 - 'git version --build-options'
 - az uname sysname, release, version és machine stringjei
 - A fordítóprogramra jellemző infostring
 - Az engedélyezett hookok listája
 - $SHELL

További információk gyűjthetők be egy külön zip archívumba a `--diagnose`
opció használatával, és ez csatolható a bugreport dokumentum mellé, hogy
további kontextust nyújtson az olvasóknak.

Ezt az eszközt a szokásos Git-beállítási folyamaton keresztül hívja meg a
rendszer, ami azt jelenti, hogy bizonyos esetekben nem tud elindulni –
például, ha egy releváns konfigurációs fájl nem olvasható. Egy ilyen
helyzetben hasznos lehet a fent felsorolt jellegű információkat kézzel
begyűjteni, amikor kézzel kérsz segítséget.

OPTIONS
-------
-o <path>::
--output-directory <path>::
	Az elkészült hibajelentés-fájlt a `<path>`-ba helyezi az aktuális
	könyvtár helyett.

-s <format>::
--suffix <format>::
--no-suffix::
	Egy alternatív utótagot ad meg a bugreport nevéhez, hogy egy
	'git-bugreport-<formatted-suffix>' nevű fájl jöjjön létre. Ennek egy
	strftime(3) formátumstring alakját kell felvennie; az aktuális helyi
	idő kerül felhasználásra.
	A `--no-suffix` kikapcsolja az utótagot, és a fájl egyszerűen
	`git-bugreport` néven jön létre, bármiféle megkülönböztető intézkedés
	nélkül.

--no-diagnose::
--diagnose[=<mode>]::
	Egy zip archívumot hoz létre a felhasználó gépéről, a Git kliensről
	és a repository állapotáról szóló kiegészítő információkkal. Az
	archívum ugyanabba a kimeneti könyvtárba kerül, mint a hibajelentés,
	és a neve 'git-diagnostics-<formatted-suffix>'.
+
Ha nincs megadva `mode`, a diagnosztikai archívum a `git diagnose` által
jelentett statisztikák alapértelmezett halmazát fogja tartalmazni. Egy
opcionális `mode` érték megadható annak megváltoztatására, hogy mely
információk kerüljenek be az archívumba. A `mode` érvényes értékeinek
listájáért és a használatuk részleteiért lásd linkgit:git-diagnose[1].

GIT
---
A linkgit:git[1] csomag része
