git-switch(1)
=============

NAME
----
git-switch - Branchek közti váltás

SYNOPSIS
--------
[synopsis]
git switch [<options>] [--no-guess] <branch>
git switch [<options>] --detach [<start-point>]
git switch [<options>] (-c|-C) <new-branch> [<start-point>]
git switch [<options>] --orphan <new-branch>

DESCRIPTION
-----------
Átvált egy megadott branchre. A working tree és az index frissül, hogy
megfeleljen a branchnek. Minden új commit ennek a branchnek a csúcsához
adódik hozzá.

Opcionálisan a váltással együtt új branch is létrehozható a `-c` vagy `-C`
kapcsolóval, automatikusan egy azonos nevű remote branchből (lásd
`--guess`), vagy a working tree leválasztható bármely branchről a
`--detach` kapcsolóval.

A branchek közti váltás nem igényel tiszta indexet és working tree-t (azaz
`HEAD`-hez képest nincs eltérés). A művelet azonban megszakad, ha lokális
változások elvesztéséhez vezetne, hacsak a `--discard-changes` vagy a
`--merge` mást nem ír elő.

OPTIONS
-------
_<branch>_::
	A branch, amelyre váltani kell.

_<new-branch>_::
	Az új branch neve.

_<start-point>_::
	Az új branch kiindulópontja. A _<start-point>_ megadásával
	olyan pontból hozhatsz létre branchet a történetben, amely eltér
	attól, ahová a `HEAD` jelenleg mutat. (Vagy `--detach` esetén
	lehetővé teszi egy másik pont megvizsgálását és az arról való
	leválást.)
+
Az `@{-<N>}` szintaxissal a `git switch` vagy `git checkout` művelettel
utoljára _<N>_-ként érintett branchre/commitra hivatkozhatsz. Megadhatod a
`-` jelet is, amely a `@{-1}` szinonimája. Ezt gyakran használják két branch
közti gyors váltásra, vagy egy véletlen branchváltás visszavonására.
+
Speciális esetként a `<rev-a>...<rev-b>` alak rövidítésként használható a
_<rev-a>_ és _<rev-b>_ merge-alapjára, ha pontosan egy merge-alap van.
Legfeljebb az egyiket hagyhatod el a _<rev-a>_ és _<rev-b>_ közül, ekkor az
alapértelmezés a `HEAD`.

`-c <new-branch>`::
`--create <new-branch>`::
	Létrehoz egy _<new-branch>_ nevű új branchet a _<start-point>_
	pontnál, mielőtt átváltana rá. Ez a tranzakciós megfelelője a
	következőnek:
+
------------
$ git branch <new-branch>
$ git switch <new-branch>
------------
+
azaz a branch nem áll vissza / jön létre, hacsak a `git switch` nem sikeres
(pl. amikor a branch egy másik worktree-ben használatban van, nemcsak az
aktuális branch marad ugyanaz, hanem a branch sem áll vissza a
kiindulópontra).

`-C <new-branch>`::
`--force-create <new-branch>`::
	Hasonló a `--create`-hez, azzal a különbséggel, hogy ha a
	_<new-branch>_ már létezik, visszaáll a _<start-point>_ pontra. Ez
	egy kényelmes rövidítés a következőre:
+
------------
$ git branch -f _<new-branch>_
$ git switch _<new-branch>_
------------

`-d`::
`--detach`::
	Átvált egy commitra vizsgálat és eldobható kísérletek céljából. A
	részletekért lásd a "DETACHED HEAD" szakaszt a
	linkgit:git-checkout[1] oldalon.

`--guess`::
`--no-guess`::
	Ha a _<branch>_ nem található, de pontosan egy remote-on (hívjuk
	_<remote>_-nak) létezik egy egyező nevű tracking branch, akkor a
	következővel egyenértékűként kezeli:
+
------------
$ git switch -c <branch> --track <remote>/<branch>
------------
+
Ha a branch több remote-on is létezik, és az egyiket a
`checkout.defaultRemote` konfigurációs változó nevezi meg, akkor azt
használjuk az egyértelműsítéshez, még akkor is, ha a _<branch>_ nem egyedi
az összes remote között. Állítsd be például `checkout.defaultRemote=origin`
értékre, hogy a remote brancheket mindig onnan checkoutolja, ha a _<branch>_
kétértelmű, de létezik az 'origin' remote-on. Lásd még a
`checkout.defaultRemote` beállítást a linkgit:git-config[1] oldalon.
+
A `--guess` az alapértelmezett viselkedés. A letiltásához használd a
`--no-guess`-t.
+
Az alapértelmezett viselkedés a `checkout.guess` konfigurációs változóval
állítható be.

`-f`::
`--force`::
	A `--discard-changes` álneve.

`--discard-changes`::
	Folytatás akkor is, ha az index vagy a working tree eltér a
	`HEAD`-től. Az index és a working tree is visszaáll a váltás
	céljához igazodva. Ha a `--recurse-submodules` meg van adva, a
	submodule tartalma is visszaáll a váltás céljához. Ezt a lokális
	változások eldobására használják.

`-m`::
`--merge`::
	Ha egy vagy több fájlban van lokális módosításod, amely eltér az
	aktuális branch és a branch között, amelyre váltasz, a parancs
	rendes esetben megtagadja a branchváltást, hogy a módosításaidat
	kontextusban megőrizze.  Ezzel az opcióval azonban a konfliktusos
	lokális változások a váltás előtt automatikusan stashelődnek, majd
	utána újra alkalmazódnak.  Ha a lokális változások nem fednek át a
	branchek közti eltérésekkel, a váltás stashelés nélkül folytatódik.
	Ha a stash újbóli alkalmazása konfliktusokhoz vezet, a bejegyzés
	elmentődik a stash-listába.  Oldd fel a konfliktusokat, és
	végezetül futtasd a `git stash drop`-ot, vagy takarítsd ki a
	working tree-t (pl. `git reset --hard` paranccsal), mielőtt később
	lefuttatnád a `git stash pop`-ot a változásaid újbóli
	alkalmazásához.

`--conflict=<style>`::
	Ugyanaz, mint a fenti `--merge` opció, de megváltoztatja a
	konfliktusos hunkok megjelenítésének módját, felülírva a
	`merge.conflictStyle` konfigurációs változót.  Lehetséges értékek:
	`merge` (alapértelmezett), `diff3` és `zdiff3`.

`-q`::
`--quiet`::
	Csendes mód, elnyomja a visszajelző üzeneteket.

`--progress`::
`--no-progress`::
	A folyamat állapota alapértelmezés szerint a standard hibakimeneten
	jelenik meg, amikor az terminálhoz kapcsolódik, hacsak a `--quiet`
	nincs megadva. Ez a kapcsoló akkor is engedélyezi a folyamatjelzést,
	ha nincs terminálhoz kapcsolva, függetlenül a `--quiet`-tól.

`-t`::
`--track[ (direct|inherit)]`::
	Új branch létrehozásakor beállítja az "upstream" konfigurációt. A
	`-c` beleértődik. A részletekért lásd a `--track`-et a
	linkgit:git-branch[1] oldalon.
+
Ha nincs megadva `-c` opció, az új branch neve a remote-tracking branchből
származik: a megfelelő remote-hoz konfigurált refspec lokális részét
tekintve, majd a "*"-ig tartó kezdeti részt levágva.  Ez alapján a `hack`-et
kellene lokális branchként használni, amikor az `origin/hack` (vagy
`remotes/origin/hack`, vagy akár `refs/remotes/origin/hack`) alapján
branchelünk.  Ha a megadott névben nincs perjel, vagy a fenti találgatás
üres nevet eredményez, a találgatás megszakad.  Ilyenkor kifejezetten
megadhatsz egy nevet a `-c` kapcsolóval.

`--no-track`::
	Ne állítsa be az "upstream" konfigurációt, még akkor sem, ha a
	`branch.autoSetupMerge` konfigurációs változó igaz.

`--orphan <new-branch>`::
	Létrehoz egy _<new-branch>_ nevű új, meg nem született branchet.
	Minden nyomon követett fájl eltávolításra kerül.

`--ignore-other-worktrees`::
	A `git switch` megtagadja a műveletet, ha a kívánt ref már ki van
	checkoutolva egy másik worktree-ben. Ezzel az opcióval mégis
	checkoutolja a refet. Más szóval a refet több worktree is
	birtokolhatja.

`--recurse-submodules`::
`--no-recurse-submodules`::
	A `--recurse-submodules` használata az összes aktív submodule
	tartalmát a szuperprojektben rögzített commit szerint frissíti. Ha
	semmit (vagy a `--no-recurse-submodules`-t) nem használod, a
	submodule-ok working tree-jei nem frissülnek. A
	linkgit:git-submodule[1]-hez hasonlóan ez leválasztja a
	submodule-ok `HEAD`-jét.

EXAMPLES
--------

A következő parancs a "master" branchre vált:

------------
$ git switch master
------------

Miután rossz branchen dolgoztál, a helyes branchre a következővel válthatsz:

------------
$ git switch mytopic
------------

A "rossz" branched és a helyes "mytopic" branch azonban eltérhet olyan
fájlokban, amelyeket lokálisan módosítottál, ilyenkor a fenti váltás így
hiúsul meg:

------------
$ git switch mytopic
error: You have local changes to 'frotz'; not switching branches.
------------

Megadhatod a parancsnak a `-m` kapcsolót, amely átviszi a lokális
változásaidat az új branchre:

------------
$ git switch -m mytopic
Applied autostash.
Switched to branch 'mytopic'
The following paths have local changes:
M	frotz
------------

A váltás után a lokális módosítások újra alkalmazódnak, és _nem_ kerülnek be
az index fájlodba, így a `git diff` megmutatja, milyen változásokat végeztél
az új branch csúcsa óta.

Az előző branchre való visszaváltáshoz, mielőtt a mytopicra váltottunk
(azaz a "master" branchre):

------------
$ git switch -
------------

Bármely commitból növeszthetsz új branchet. Például válts a "`HEAD~3`"-ra,
és hozd létre a "`fixup`" branchet:

------------
$ git switch -c fixup HEAD~3
Switched to a new branch 'fixup'
------------

Ha egy azonos nevű remote branchből szeretnél új branchet indítani:

------------
$ git switch new-topic
Branch `new-topic` set up to track remote branch `new-topic` from `origin`
Switched to a new branch `new-topic`
------------

A `HEAD~3` commit checkoutolásához ideiglenes vizsgálat vagy kísérlet
céljából, új branch létrehozása nélkül:

------------
$ git switch --detach HEAD~3
HEAD is now at 9fc9555312 Merge branch 'cc/shared-index-permbits'
------------

Ha kiderül, hogy amit csináltál, megőrzésre érdemes, bármikor létrehozhatsz
hozzá egy új nevet (anélkül, hogy elváltanál):

------------
$ git switch -c good-surprises
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/checkout.adoc[]

SEE ALSO
--------
linkgit:git-checkout[1],
linkgit:git-branch[1]

GIT
---
A linkgit:git[1] csomag része
