git-worktree(1)
===============

NAME
----
git-worktree - Manage multiple working trees


SYNOPSIS
--------
[synopsis]
git worktree add [-f] [--detach] [--checkout] [--lock [--reason <string>]]
		 [--orphan] [(-b | -B) <new-branch>] <path> [<commit-ish>]
git worktree list [-v | --porcelain [-z]]
git worktree lock [--reason <string>] <worktree>
git worktree move <worktree> <new-path>
git worktree prune [-n] [-v] [--expire <expire>]
git worktree remove [-f] <worktree>
git worktree repair [<path>...]
git worktree unlock <worktree>

DESCRIPTION
-----------

Több, ugyanahhoz a repository-hoz csatolt working tree kezelése.

Egy git repository több working tree-t is támogathat, lehetővé téve, hogy
egyszerre több branchet is kicsekkolj.  A `git worktree add` paranccsal egy új
working tree társul a repository-hoz, további metaadatokkal együtt,
amelyek megkülönböztetik azt a working tree-t az ugyanabban a repository-ban lévő többitől.
A working tree-t, ezzel a metaadattal együtt, "worktree"-nak nevezzük.

Ezt az új worktree-t "linked worktree"-nak (láncolt worktree-nak) nevezzük, szemben a "main
worktree"-vel (fő worktree-vel), amelyet a linkgit:git-init[1] vagy linkgit:git-clone[1] készít elő.
Egy repository-nak egy fő worktree-je van (ha nem bare repository), és
nulla vagy több láncolt worktree-je. Amikor végeztél egy láncolt worktree-vel,
távolítsd el a `git worktree remove` paranccsal.

A legegyszerűbb formájában a `git worktree add <path>` automatikusan létrehoz egy
új branchet, amelynek neve a _<path>_ utolsó komponense, ami
kényelmes, ha egy új témán tervezel dolgozni. Például a `git
worktree add ../hotfix` létrehozza a `hotfix` új branchet, és kicsekkolja a
`../hotfix` útvonalon. Ha ehelyett egy meglévő branchen szeretnél dolgozni egy új worktree-ben,
használd a `git worktree add <path> <branch>` parancsot. Másrészt, ha csak
néhány kísérleti változtatást szeretnél végezni, vagy tesztelni szeretnél a meglévő fejlesztés
megzavarása nélkül, gyakran kényelmes egy 'eldobható'
worktree-t létrehozni, amely nincs semmilyen branchhez társítva. Például
a `git worktree add -d <path>` egy új worktree-t hoz létre leválasztott `HEAD`-del,
ugyanannál a commitnál, mint az aktuális branch.

Ha egy working tree-t törölnek a `git worktree remove` használata nélkül, akkor
a hozzá tartozó adminisztratív fájlok, amelyek a repository-ban találhatók
(lásd a "DETAILS" szakaszt lentebb), végül automatikusan eltávolításra kerülnek (lásd a
`gc.worktreePruneExpire`-t a linkgit:git-config[1] oldalon), vagy futtathatod a
`git worktree prune` parancsot a fő vagy bármely láncolt worktree-ben, hogy megtisztítsd az
elavult adminisztratív fájlokat.

Ha egy láncolt worktree working tree-je egy hordozható eszközön
vagy hálózati megosztáson van tárolva, amely nincs mindig csatlakoztatva, megelőzheted, hogy az
adminisztratív fájljai prune-olva legyenek a `git worktree lock`
parancs kiadásával, opcionálisan megadva a `--reason`-t, hogy elmagyarázd, miért van a worktree
zárolva.

COMMANDS
--------
`add <path> [<commit-ish>]`::

Létrehoz egy worktree-t a _<path>_-nál, és kicsekkolja bele a _<commit-ish>_-t. Az új worktree
az aktuális repository-hoz van láncolva, mindent megosztva a worktree-nkénti
fájlok, mint a `HEAD`, `index` stb. kivételével. Kényelmi okokból a _<commit-ish>_
lehet egy önmagában álló "`-`" is, amely a `@{-1}` szinonimája.
+
Ha a _<commit-ish>_ egy branchnév (nevezzük _<branch>_-nek), és nem található,
és sem a `-b`, sem a `-B`, sem a `--detach` nincs használva, de
létezik egy egyező nevű tracking branch pontosan egy remote-ban (nevezzük _<remote>_-nek),
akkor kezeld úgy, mintha ez lenne:
+
------------
$ git worktree add --track -b <branch> <path> <remote>/<branch>
------------
+
Ha a branch több remote-ban is létezik, és az egyiket a
`checkout.defaultRemote` konfigurációs változó nevezi meg, azt fogjuk használni
az egyértelműsítés céljából, még akkor is, ha a _<branch>_ nem
egyedi az összes remote között. Állítsd be pl.
`checkout.defaultRemote=origin`-re, hogy mindig onnan csekkold ki a remote
brancheket, ha a _<branch>_ kétértelmű, de létezik az
`origin` remote-on. Lásd még a `checkout.defaultRemote`-ot a
linkgit:git-config[1] oldalon.
+
Ha a _<commit-ish>_ ki van hagyva, és sem a `-b`, sem a `-B`, sem a `--detach` nincs használva,
akkor kényelmi okokból az új worktree egy `$(basename <path>)` után elnevezett
branchhez (nevezzük _<branch>_-nek) társul.  Ha a _<branch>_ nem
létezik, automatikusan létrejön egy új, a `HEAD`-en alapuló branch, mintha
`-b <branch>` lett volna megadva.  Ha a _<branch>_ létezik, ki lesz csekkolva
az új worktree-be, ha máshol nincs kicsekkolva, egyébként a
parancs megtagadja a worktree létrehozását (hacsak a `--force` nincs használva).
+
Ha a _<commit-ish>_ ki van hagyva, sem a `--detach`, sem az `--orphan`
nincs használva, és nincsenek érvényes helyi branchek (vagy remote branchek, ha a
`--guess-remote` meg van adva), akkor kényelmi okokból az új worktree
egy új, _<branch>_ nevű meg nem született branchhez társul (a
`$(basename <path>)` után elnevezve, ha sem a `-b`, sem a `-B` nincs használva), mintha `--orphan` lett volna
átadva a parancsnak. Abban az esetben, ha a repository-nak van remote-ja, és
a `--guess-remote` van használva, de nincs remote vagy helyi branch, a
parancs figyelmeztetéssel meghiúsul, amely emlékezteti a felhasználót, hogy előbb fetcheljen a remote-járól
(vagy írja felül a `-f`/`--force` használatával).

`list`::

Felsorolja minden worktree részleteit.  Először a fő worktree kerül felsorolásra,
majd mindegyik láncolt worktree.  A kimeneti részletek tartalmazzák,
hogy a worktree bare-e, az aktuálisan kicsekkolt revíziót, az aktuálisan kicsekkolt
branchet (vagy "detached HEAD", ha nincs ilyen), a "locked"-ot, ha
a worktree zárolva van, a "prunable"-t, ha a worktree prune-olható a
`prune` paranccsal.

`lock`::

Ha egy worktree egy hordozható eszközön vagy hálózati megosztáson van, amely nincs mindig
csatlakoztatva, zárold, hogy megelőzd az adminisztratív fájljainak
automatikus prune-olását. Ez azt is megakadályozza, hogy áthelyezzék vagy törölje.
Opcionálisan add meg a zárolás okát a `--reason`-nal.

`move`::

Egy worktree áthelyezése egy új helyre. Vedd figyelembe, hogy a fő worktree vagy a
submodule-okat tartalmazó láncolt worktree-k nem helyezhetők át ezzel a paranccsal. (A
`git worktree repair` parancs azonban újra tudja létesíteni a kapcsolatot
a láncolt worktree-kkel, ha kézzel helyezed át a fő worktree-t.)

`prune`::

Eltávolítja azoknak a worktree-knek a `$GIT_DIR/worktrees`-ben lévő
információit, amelyek working tree-je hiányzik.  Hasznos, miután kézzel eltávolítottál
egy már nem szükséges working tree-t (de legközelebb használd a "git worktree
remove" parancsot, ha ezt akarod tenni).  Ha egy working tree-t
máshová _helyeztél át_, ami miatt a worktree információja
fellógóvá vált, lásd a "git worktree repair" parancsot, hogy újra összekösd a worktree-t
az új working tree hellyel.

`remove`::

Eltávolít egy worktree-t. Csak tiszta worktree-k (nincs nem követett fájl, és nincs
módosítás a követett fájlokban) távolíthatók el. A nem tiszta worktree-k, vagy amelyekben
submodule-ok vannak, a `--force`-szal távolíthatók el. A fő worktree nem
távolítható el.

`repair [<path>...]`::

Megjavítja a worktree adminisztratív fájljait, ha lehetséges, ha
külső tényezők miatt sérültté vagy elavulttá váltak.
+
Például ha a fő worktree-t (vagy bare repository-t) áthelyezik, a láncolt
worktree-k nem lesznek képesek megtalálni. A `repair` futtatása a fő
worktree-ben újra létesíti a kapcsolatot a láncolt worktree-ktől vissza a
fő worktree-hez.
+
Hasonlóképpen, ha egy láncolt worktree working tree-jét áthelyezik a
`git worktree move` használata nélkül, a fő worktree (vagy bare repository) nem lesz
képes megtalálni. A `repair` futtatása a nemrég áthelyezett worktree-ben
újra létesíti a kapcsolatot. Ha több láncolt worktree-t helyeznek át,
a `repair` futtatása bármely worktree-ből, argumentumként mindegyik fa új _<path>_-jával,
újra létesíti a kapcsolatot az összes megadott útvonalhoz.
+
Ha mind a fő worktree, mind a láncolt worktree-k kézzel lettek áthelyezve vagy másolva,
akkor a `repair` futtatása a fő worktree-ben, minden láncolt worktree új _<path>_-jának
megadásával, újra létesíti az összes kapcsolatot mindkét
irányban.

`unlock`::

Feloldja egy worktree zárolását, lehetővé téve, hogy prune-olható, áthelyezhető vagy törölhető legyen.

OPTIONS
-------

`-f`::
`--force`::
	Alapból az `add` megtagadja egy új worktree létrehozását, ha
	a _<commit-ish>_ egy branchnév, és már ki van csekkolva
	egy másik worktree által, vagy ha a _<path>_ már hozzá van rendelve egy
	worktree-hez, de hiányzik (például ha a _<path>_ kézzel lett
	törölve). Ez az opció felülírja ezeket a védelmeket. Ahhoz, hogy egy hiányzó, de
	zárolt worktree útvonalat adj hozzá, add meg a `--force`-t kétszer.
+
A `move` megtagadja egy zárolt worktree áthelyezését, hacsak a `--force` kétszer
nincs megadva. Ha a célhely már hozzá van rendelve egy másik worktree-hez, de
hiányzik (például ha az _<new-path>_ kézzel lett törölve), akkor a `--force`
lehetővé teszi az áthelyezés folytatását; használd a `--force`-t kétszer, ha a célhely zárolva van.
+
A `remove` megtagadja egy nem tiszta worktree eltávolítását, hacsak a `--force` nincs használva.
Ahhoz, hogy egy zárolt worktree-t eltávolíts, add meg a `--force`-t kétszer.

`-b <new-branch>`::
`-B <new-branch>`::
	Az `add` paranccsal létrehoz egy _<new-branch>_ nevű új branchet, amely a
	_<commit-ish>_-nél kezdődik, és kicsekkolja az _<new-branch>_-et az új worktree-be.
	Ha a _<commit-ish>_ ki van hagyva, alapból `HEAD`.
	Alapból a `-b` megtagadja egy új branch létrehozását, ha az már
	létezik. A `-B` felülírja ezt a védelmet, az _<new-branch>_-et
	a _<commit-ish>_-re állítva vissza.

`-d`::
`--detach`::
	Az `add` paranccsal leválasztja a `HEAD`-et az új worktree-ben. Lásd a "DETACHED HEAD" szakaszt
	a linkgit:git-checkout[1] oldalon.

`--checkout`::
`--no-checkout`::
	Alapból az `add` kicsekkolja a _<commit-ish>_-t, azonban a `--no-checkout`
	használható a checkout elnyomására, hogy testreszabásokat végezhess,
	például a sparse-checkout konfigurálását. Lásd a "Sparse checkout" szakaszt
	a linkgit:git-read-tree[1] oldalon.

`--guess-remote`::
`--no-guess-remote`::
	A `worktree add <path>` paranccsal, _<commit-ish>_ nélkül, ahelyett
	hogy egy új branchet hoznánk létre a `HEAD`-ből, ha létezik egy, a _<path>_
	alapnevével egyező nevű tracking branch pontosan egy remote-ban,
	az új branch a remote-tracking branchre épül, és a
	remote-tracking branch "upstream"-ként lesz megjelölve az új branchtől.
+
Ez alapértelmezett viselkedésként is beállítható a
`worktree.guessRemote` config-opció használatával.

`--relative-paths`::
`--no-relative-paths`::
	A worktree-k relatív vagy abszolút (alapértelmezett) útvonalak használatával való láncolása.
	Felülírja a `worktree.useRelativePaths` config-opciót, lásd
	linkgit:git-config[1].
+
A `repair`-rel a láncoló fájlok frissülnek, ha van abszolút/relatív
eltérés, még akkor is, ha a linkek helyesek.

`--track`::
`--no-track`::
	Amikor egy új branchet hozol létre, ha a _<commit-ish>_ egy branch,
	jelöld meg "upstream"-ként az új branchtől.  Ez az
	alapértelmezés, ha a _<commit-ish>_ egy remote-tracking branch.  A
	részletekért lásd a `--track` opciót a linkgit:git-branch[1] oldalon.

`--lock`::
	A worktree zárolva tartása létrehozás után. Ez a
	`git worktree lock` egyenértéke a `git worktree add` után,
	de race condition nélkül.

`-n`::
`--dry-run`::
	A `prune`-nal semmit sem távolít el; csak jelenti, hogy mit
	távolítana el.

`--orphan`::
	Az `add` paranccsal üressé teszi az új worktree-t és az indexet, a
	worktree-t egy új, _<new-branch>_ nevű meg nem született branchhez társítva.

`--porcelain`::
	A `list`-tel a kimenet szkriptek számára könnyen elemezhető formátumban jelenik meg.
	Ez a formátum stabil marad a Git-verziók között, és a felhasználói
	konfigurációtól függetlenül.  Ajánlott ezt a `-z`-vel kombinálni.
	A részletekért lásd lentebb.

`-z`::
	Minden sor lezárása _NUL_-lal sortörés helyett, amikor
	a `--porcelain` meg van adva a `list`-tel. Ez lehetővé teszi
	a kimenet elemzését, amikor egy worktree útvonala sortörés
	karaktert tartalmaz.

`-q`::
`--quiet`::
	Az `add` paranccsal elnyomja a visszajelző üzeneteket.

`-v`::
`--verbose`::
	A `prune`-nal jelenti az összes eltávolítást.
+
A `list`-tel további információkat ad ki a worktree-kről (lásd lentebb).

`--expire <time>`::
	A `prune`-nal csak akkor prune-olja a hiányzó worktree-ket, ha régebbiek, mint _<time>_.
+
A `list`-tel prunable-ként annotálja a hiányzó worktree-ket, ha régebbiek, mint
_<time>_.

`--reason <string>`::
	A `lock`-kal vagy az `add --lock`-kal magyarázatot ad arra, hogy a worktree
	miért van zárolva.

_<worktree>_::
	A worktree-k útvonal alapján azonosíthatók, akár relatívval, akár abszolúttal.
+
Ha a worktree útvonalának utolsó útvonal-komponensei egyediek a
worktree-k között, akkor felhasználhatók egy worktree azonosítására. Például ha csak
két worktree-d van, a `/abc/def/ghi` és `/abc/def/ggg`, akkor a `ghi`
vagy a `def/ghi` elég a korábbi worktree-re mutatáshoz.

REFS
----
Amikor több worktree-t használsz, néhány ref meg van osztva az összes worktree
között, de mások egy adott worktree-re specifikusak. Az egyik példa a `HEAD`,
amely worktree-nként eltérő. Ez a szakasz a megosztási
szabályokról szól, és arról, hogyan férhetsz hozzá az egyik worktree refjeihez egy másikból.

Általában minden pszeudoref worktree-nkénti, és minden `refs/`-fel
kezdődő ref meg van osztva. A pszeudorefek olyanok, mint a `HEAD`, amelyek közvetlenül
a `$GIT_DIR` alatt vannak, nem a `$GIT_DIR/refs`-en belül. Vannak kivételek,
azonban: a `refs/bisect`, `refs/worktree` és `refs/rewritten` belüli refek
nincsenek megosztva.

A worktree-nkénti refekhez továbbra is hozzá lehet férni egy másik worktree-ből
két speciális útvonalon keresztül: `main-worktree` és `worktrees`. Az előbbi
hozzáférést biztosít a fő worktree worktree-nkénti refjeihez, míg az utóbbi az összes
láncolt worktree-hez.

Például a `main-worktree/HEAD` vagy a `main-worktree/refs/bisect/good`
ugyanarra az értékre oldódik fel, mint a fő worktree `HEAD`-je, illetve
`refs/bisect/good`-ja. Hasonlóképpen a `worktrees/foo/HEAD` vagy a
`worktrees/bar/refs/bisect/bad` ugyanaz, mint a
`$GIT_COMMON_DIR/worktrees/foo/HEAD` és a
`$GIT_COMMON_DIR/worktrees/bar/refs/bisect/bad`.

A refek eléréséhez a legjobb, ha nem nézel közvetlenül a `$GIT_DIR` belsejébe. Ehelyett
használj olyan parancsokat, mint a linkgit:git-rev-parse[1] vagy a linkgit:git-update-ref[1],
amelyek helyesen kezelik a refeket.

CONFIGURATION FILE
------------------
Alapból a repository `config` fájlja meg van osztva az összes worktree között.
Ha a `core.bare` vagy `core.worktree` config-változók jelen vannak a
közös config fájlban, és az `extensions.worktreeConfig` le van tiltva, akkor
csak a fő worktree-re lesznek alkalmazva.

Ahhoz, hogy worktree-specifikus konfigurációd legyen, bekapcsolhatod a
`worktreeConfig` kiterjesztést, pl.:

------------
$ git config extensions.worktreeConfig true
------------

Ebben a módban a specifikus konfiguráció a `git
rev-parse --git-path config.worktree` által mutatott útvonalon marad. Ebben a
fájlban konfigurációt adhatsz hozzá vagy frissíthetsz a `git config --worktree` paranccsal. A Git
régebbi verziói megtagadják az ezzel a kiterjesztéssel rendelkező repository-k elérését.

Vedd figyelembe, hogy ebben a fájlban a `core.bare` és `core.worktree`
kivétele megszűnik. Ha léteznek a `$GIT_DIR/config`-ban, át kell
mozgatnod őket a fő worktree `config.worktree`-jébe. Ezt az alkalmat kihasználhatod
arra is, hogy áttekintsd és áthelyezd más konfigurációkat is, amelyeket nem szeretnél
megosztani az összes worktree-vel:

 - a `core.worktree`-t soha nem szabad megosztani.

 - a `core.bare`-t nem szabad megosztani, ha az érték `core.bare=true`.

 - a `core.sparseCheckout`-ot nem szabad megosztani, hacsak nem vagy biztos benne, hogy
   mindig sparse checkoutot használsz az összes worktree-hez.

A részletekért lásd az `extensions.worktreeConfig` dokumentációját a
linkgit:git-config[1] oldalon.

DETAILS
-------
Minden láncolt worktree-nek van egy privát alkönyvtára a repository
`$GIT_DIR/worktrees` könyvtárában.  A privát alkönyvtár neve általában
a láncolt worktree útvonalának alapneve, esetleg egy
számmal kiegészítve, hogy egyedi legyen.  Például, amikor `$GIT_DIR=/path/main/.git`, a
`git worktree add /path/other/test-next next` parancs létrehozza a láncolt
worktree-t a `/path/other/test-next`-ben, és létrehoz egy
`$GIT_DIR/worktrees/test-next` könyvtárat is (vagy `$GIT_DIR/worktrees/test-next1`-et,
ha a `test-next` már foglalt).

Egy láncolt worktree-n belül a `$GIT_DIR` erre a privát
könyvtárra mutat (pl. a `/path/main/.git/worktrees/test-next`-re a példában), és
a `$GIT_COMMON_DIR` vissza a fő worktree `$GIT_DIR`-jára mutat
(pl. `/path/main/.git`-re). Ezek a beállítások egy `.git` fájlban vannak megadva, amely
a láncolt worktree legfelső könyvtárában található.

Az útvonal-feloldás a `git rev-parse --git-path` révén vagy a
`$GIT_DIR`-t, vagy a `$GIT_COMMON_DIR`-t használja, az útvonaltól függően. Például a
láncolt worktree-ben a `git rev-parse --git-path HEAD` a
`/path/main/.git/worktrees/test-next/HEAD`-et adja vissza (nem a
`/path/other/test-next/.git/HEAD`-et vagy a `/path/main/.git/HEAD`-et), míg a `git
rev-parse --git-path refs/heads/master` a
`$GIT_COMMON_DIR`-t használja, és a `/path/main/.git/refs/heads/master`-t adja vissza,
mivel a refek meg vannak osztva az összes worktree között, kivéve a `refs/bisect`,
`refs/worktree` és `refs/rewritten`.

További információért lásd a linkgit:gitrepository-layout[5] oldalt. Az
ökölszabály az, hogy ne tegyél semmilyen feltételezést arról, hogy egy útvonal a
`$GIT_DIR`-hez vagy a `$GIT_COMMON_DIR`-hoz tartozik-e, amikor közvetlenül hozzá kell férned valamihez
a `$GIT_DIR`-en belül. Használd a `git rev-parse --git-path`-t a végleges útvonal megszerzéséhez.

Ha kézzel helyezel át egy láncolt worktree-t, frissítened kell a `gitdir` fájlt
a bejegyzés könyvtárában. Például ha egy láncolt worktree-t áthelyeznek
a `/newpath/test-next`-be, és a `.git` fájlja a
`/path/main/.git/worktrees/test-next`-re mutat, akkor frissítsd a
`/path/main/.git/worktrees/test-next/gitdir`-t, hogy helyette a `/newpath/test-next`-re
hivatkozzon. Vagy még jobb, futtasd a `git worktree repair` parancsot, hogy automatikusan
újra létesítsd a kapcsolatot.

Ahhoz, hogy megelőzd egy `$GIT_DIR/worktrees` bejegyzés prune-olását (ami
hasznos lehet bizonyos helyzetekben, például amikor a
bejegyzés worktree-je egy hordozható eszközön van tárolva), használd a
`git worktree lock` parancsot, amely egy
`locked` nevű fájlt ad a bejegyzés könyvtárához. A fájl az okot
egyszerű szövegként tartalmazza. Például ha egy láncolt worktree `.git` fájlja
a `/path/main/.git/worktrees/test-next`-re mutat, akkor egy
`/path/main/.git/worktrees/test-next/locked` nevű fájl megelőzi a
`test-next` bejegyzés prune-olását.  A részletekért lásd a
linkgit:gitrepository-layout[5] oldalt.

Amikor az `extensions.worktreeConfig` engedélyezve van, a config fájl
`.git/worktrees/<id>/config.worktree` a `.git/config` után kerül beolvasásra.

LIST OUTPUT FORMAT
------------------
A `worktree list` parancsnak két kimeneti formátuma van. Az alapértelmezett formátum
egyetlen sorban, oszlopokban mutatja a részleteket.  Például:

------------
$ git worktree list
/path/to/bare-source            (bare)
/path/to/linked-worktree        abcd1234 [master]
/path/to/other-linked-worktree  1234abc  (detached HEAD)
------------

A parancs annotációkat is mutat minden worktree-hez, az állapotuk szerint.
Ezek az annotációk a következők:

 * `locked`, ha a worktree zárolva van.
 * `prunable`, ha a worktree prune-olható a `git worktree prune` révén.

------------
$ git worktree list
/path/to/linked-worktree    abcd1234 [master]
/path/to/locked-worktree    acbd5678 (brancha) locked
/path/to/prunable-worktree  5678abc  (detached HEAD) prunable
------------

Ezekhez az annotációkhoz egy ok is elérhető lehet, és ez a
verbose módban látható. Az annotáció ekkor a következő sorra kerül,
behúzva, majd a további információ következik.

------------
$ git worktree list --verbose
/path/to/linked-worktree              abcd1234 [master]
/path/to/locked-worktree-no-reason    abcd5678 (detached HEAD) locked
/path/to/locked-worktree-with-reason  1234abcd (brancha)
	locked: worktree path is mounted on a portable device
/path/to/prunable-worktree            5678abc1 (detached HEAD)
	prunable: gitdir file points to non-existent location
------------

Vedd figyelembe, hogy az annotáció a következő sorra kerül, ha a további
információ elérhető, egyébként ugyanazon a soron marad, mint maga a
worktree.

[[_porcelain_format]]
Porcelain formátum
~~~~~~~~~~~~~~~~~~
A porcelain formátumnak attribútumonként egy sora van.  Ha a `-z` meg van adva, a sorok
NUL-lal vannak lezárva sortörés helyett.  Az attribútumok egy
címkével és egy értékkel vannak felsorolva, egyetlen szóközzel elválasztva.  A logikai attribútumok (mint a `bare`
és a `detached`) csak címkeként vannak felsorolva, és csak akkor vannak jelen,
ha az érték true.  Néhány attribútum (mint a `locked`) csak címkeként
vagy értékkel is felsorolható, attól függően, hogy elérhető-e egy ok.  Egy worktree első
attribútuma mindig a `worktree`, egy üres sor jelzi a rekord
végét.  Például:

------------
$ git worktree list --porcelain
worktree /path/to/bare-source
bare

worktree /path/to/linked-worktree
HEAD abcd1234abcd1234abcd1234abcd1234abcd1234
branch refs/heads/master

worktree /path/to/other-linked-worktree
HEAD 1234abc1234abc1234abc1234abc1234abc1234a
detached

worktree /path/to/linked-worktree-locked-no-reason
HEAD 5678abc5678abc5678abc5678abc5678abc5678c
branch refs/heads/locked-no-reason
locked

worktree /path/to/linked-worktree-locked-with-reason
HEAD 3456def3456def3456def3456def3456def3456b
branch refs/heads/locked-with-reason
locked reason why is locked

worktree /path/to/linked-worktree-prunable
HEAD 1233def1234def1234def1234def1234def1234b
detached
prunable gitdir file points to non-existent location

------------

Hacsak a `-z` nincs használva, a zárolási okban lévő bármely "szokatlan"
karakter, mint a sortörés, escape-elve van, és a teljes ok idézőjelezve van, ahogy
az a `core.quotePath` konfigurációs változónál el van magyarázva (lásd linkgit:git-config[1]).
Például:

------------
$ git worktree list --porcelain
...
locked "reason\nwhy is locked"
...
------------

EXAMPLES
--------
Egy refactoring-munkamenet közepén vagy, és a főnököd bejön, és
azonnali javítást követel. Jellemzően a
linkgit:git-stash[1] parancsot használnád, hogy ideiglenesen elrakd a változtatásaidat, de a
working tree-d olyan rendetlen állapotban van (új, áthelyezett és eltávolított
fájlokkal, és más szanaszét heverő darabokkal), hogy nem akarod kockáztatni, hogy bármit is
megzavarj benne. Ehelyett létrehozol egy ideiglenes láncolt worktree-t, hogy
elvégezd a sürgősségi javítást, eltávolítod, amikor kész vagy, majd folytatod a korábbi
refactoring-munkamenetedet.

------------
$ git worktree add -b emergency-fix ../temp master
$ pushd ../temp
# ... hack hack hack ...
$ git commit -a -m 'emergency fix for boss'
$ popd
$ git worktree remove ../temp
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/worktree.adoc[]

BUGS
----
A multiple checkout általánosságban még kísérleti, és a submodule-ok
támogatása hiányos. NEM javasolt egy szuperprojekt
több checkoutját elkészíteni.

GIT
---
A linkgit:git[1] csomag része
