git-ls-files(1)
===============

NAME
----
git-ls-files - Információ megjelenítése az indexben és a working tree-ben lévő fájlokról


SYNOPSIS
--------
[verse]
'git ls-files' [-z] [-t] [-v] [-f]
		[-c|--cached] [-d|--deleted] [-o|--others] [-i|--ignored]
		[-s|--stage] [-u|--unmerged] [-k|--killed] [-m|--modified]
		[--resolve-undo]
		[--directory [--no-empty-directory]] [--eol]
		[--deduplicate]
		[-x <pattern>|--exclude=<pattern>]
		[-X <file>|--exclude-from=<file>]
		[--exclude-per-directory=<file>]
		[--exclude-standard]
		[--error-unmatch] [--with-tree=<tree-ish>]
		[--full-name] [--recurse-submodules]
		[--abbrev[=<n>]] [--format=<format>] [--] [<file>...]

DESCRIPTION
-----------
Ez a parancs összefésüli az indexbeli fájllistát a tényleges
munkakönyvtár-listával, és a kettő különböző kombinációit mutatja.

Több kapcsolóval megadható, mely fájlok jelenjenek meg, és minden fájl
többször is kiírásra kerülhet, ha több bejegyzés van az indexben, vagy ha a
vonatkozó fájlkiválasztási opciókra több státusz is alkalmazható.

OPTIONS
-------
-c::
--cached::
	Megjeleníti a Git indexében gyorsítótárazott összes fájlt, azaz az
	összes nyomon követett fájlt.
	(Ez az alapértelmezés, ha nincs -c/-s/-d/-o/-u/-k/-m/--resolve-undo
	opció megadva.)

-d::
--deleted::
	Megjeleníti a stage-elés nélküli törléssel rendelkező fájlokat

-m::
--modified::
	Megjeleníti a stage-elés nélküli módosítással rendelkező fájlokat (a
	stage-elés nélküli törlés is stage-elés nélküli módosításnak számít)

-o::
--others::
	Megjeleníti az egyéb (azaz nyomon nem követett) fájlokat a kimenetben

-i::
--ignored::
	Csak az ignorált fájlokat jeleníti meg a kimenetben.  Explicit '-c'-vel
	vagy '-o'-val kell használni.  Az indexben lévő fájlok
	megjelenítésekor (azaz '-c'-vel használva) csak azokat a fájlokat
	írja ki, amelyek illeszkednek egy exclude mintára.  Az „egyéb" fájlok
	megjelenítésekor (azaz '-o'-val használva) csak az exclude mintára
	illeszkedőket mutatja.  A standard ignore szabályok nem
	aktiválódnak automatikusan; ezért a `--exclude*` opciók közül
	legalább egy szükséges.

-s::
--stage::
	Megjeleníti a stage-elt tartalom módbitjeit, objektumnevét és
	stage-számát a kimenetben.

--directory::
	Ha egy egész könyvtár „egyéb"-ként van besorolva, csak a nevét
	jeleníti meg (záró perjellel), nem a teljes tartalmát.
	-o/--others nélkül nincs hatása.

--no-empty-directory::
	Ne sorolja fel az üres könyvtárakat. --directory nélkül nincs hatása.

-u::
--unmerged::
	Megjeleníti a nem merge-elt fájlokról szóló információt a kimenetben,
	de nem mutat más nyomon követett fájlt (kikényszeríti a --stage-et,
	felülírja a --cached-et).

-k::
--killed::
	Megjeleníti a fájlrendszeren azokat a nyomon nem követett fájlokat,
	amelyeket el kell távolítani a fájl-/könyvtárkonfliktusok miatt
	ahhoz, hogy a nyomon követett fájlokat a fájlrendszerre lehessen írni.

--resolve-undo::
	Megjeleníti az indexben resolve-undo információval rendelkező
	fájlokat a resolve-undo információjukkal együtt.  (a resolve-undo
	információt a "git checkout -m $PATH" megvalósítására használják,
	azaz a véletlenül feloldott merge konfliktusok újbóli létrehozására)

-z::
	\0 sorlezárás a kimeneten, és a fájlneveket nem idézőjelezi.
	További információért lásd az OUTPUT szakaszt lentebb.

--deduplicate::
	Amikor csak fájlnevek jelennek meg, elnyomja azokat a duplikátumokat,
	amelyek egy merge során meglévő több stage-ből, vagy a `--deleted` és
	a `--modified` opció egyidejű megadásából származhatnak.
	Amikor a `-t`, a `--unmerged` vagy a `--stage` opció bármelyike
	használatban van, ennek az opciónak nincs hatása.

-x <pattern>::
--exclude=<pattern>::
	Kihagyja a mintára illeszkedő, nyomon nem követett fájlokat.
	A minta egy shell helyettesítő-karakteres minta. További
	információért lásd az EXCLUDE PATTERNS szakaszt lentebb.

-X <file>::
--exclude-from=<file>::
	Exclude mintákat olvas a <file>-ból; soronként 1-et.

--exclude-per-directory=<file>::
	További exclude mintákat olvas a <file>-ból, amelyek csak a
	könyvtárra és alkönyvtáraira vonatkoznak.  Ha a Porcelain parancsok
	működését próbálod utánozni, egyszerűbb és alaposabb helyette a
	`--exclude-standard` opciót használni.

--exclude-standard::
	Hozzáadja a standard Git kizárásokat: .git/info/exclude, .gitignore
	minden könyvtárban, és a felhasználó globális kizárási fájlja.

--error-unmatch::
	Ha valamelyik <file> nem szerepel az indexben, ezt hibaként kezeli
	(1-et ad vissza).

--with-tree=<tree-ish>::
	Amikor a --error-unmatch-csel a felhasználó által megadott <file>
	(azaz útvonalminta) argumentumokat útvonalakká bővíti, úgy tesz,
	mintha a megnevezett <tree-ish> óta az indexből eltávolított
	útvonalak még jelen lennének.  Ennek az opciónak a `-s` vagy `-u`
	opcióval való használata értelmetlen.

-t::
	Megjeleníti a státuszcímkéket a fájlnevekkel együtt.  Szkriptelési
	célból a linkgit:git-status[1] `--porcelain` és a
	linkgit:git-diff-files[1] `--name-status` szinte mindig jobb
	alternatíva; felhasználóbarátabb alternatívákért a felhasználók
	nézzék meg a linkgit:git-status[1] `--short` vagy a linkgit:git-diff[1]
	`--name-status` opciót.
+
--
Ez az opció indokot ad az egyes fájlnevek megjelenítéséhez, egy
státuszcímke formájában (amelyet egy szóköz, majd a fájlnév követ).
A státuszcímkék mind egyetlen karakterek a következő listából:

	H::	nyomon követett fájl, amely nem nem-merge-elt és nem skip-worktree
	S::	nyomon követett fájl, amely skip-worktree
	M::	nyomon követett fájl, amely nem merge-elt
	R::	nyomon követett fájl stage-elés nélküli eltávolítással/törléssel
	C::	nyomon követett fájl stage-elés nélküli módosítással/változással
	K::	nyomon nem követett útvonalak, amelyek fájl-/könyvtárkonfliktusok
		részei, és megakadályozzák a nyomon követett fájlok checkoutolását
	?::	nyomon nem követett fájl
	U::     resolve-undo információval rendelkező fájl
--

-v::
	Hasonló a `-t`-hez, de kisbetűket használ azokhoz a fájlokhoz,
	amelyek 'assume unchanged'-ként vannak megjelölve (lásd
	linkgit:git-update-index[1]).

-f::
	Hasonló a `-t`-hez, de kisbetűket használ azokhoz a fájlokhoz,
	amelyek 'fsmonitor valid'-ként vannak megjelölve (lásd
	linkgit:git-update-index[1]).

--full-name::
	Alkönyvtárból futtatva a parancs általában az aktuális könyvtárhoz
	relatív útvonalakat ír ki.  Ez az opció kikényszeríti, hogy az
	útvonalak a projekt legfelső könyvtárához relatívan íródjanak ki.

--recurse-submodules::
	Rekurzívan meghívja az ls-files-t a repository minden aktív
	submodule-jén.
	Jelenleg csak a --cached és a --stage módot támogatja.

--abbrev[=<n>]::
	A teljes 40 bájtos hexadecimális objektumsorok megjelenítése helyett
	a legrövidebb, legalább '<n>' hexadecimális számjegy hosszú előtagot
	mutatja, amely egyértelműen az objektumra hivatkozik.
	Nem alapértelmezett számú számjegy a --abbrev=<n>-nel adható meg.

--debug::
	Minden fájlt leíró sor után több adatot ad hozzá a fájl
	cache-bejegyzéséről.  Ennek célja, hogy kézi vizsgálathoz a lehető
	legtöbb információt mutassa; a pontos formátum bármikor változhat.

--eol::
	Megjeleníti a fájlok <eolinfo> és <eolattr> értékét.
	Az <eolinfo> a Git által használt fájltartalom-azonosítás, amikor a
	"text" attribútum "auto" (vagy nincs beállítva, és a core.autocrlf
	nem false).
	Az <eolinfo> értéke "-text", "none", "lf", "crlf", "mixed" vagy "".
+
A "" azt jelenti, hogy a fájl nem közönséges fájl, nincs az indexben, vagy
nem elérhető a working tree-ben.
+
Az <eolattr> az az attribútum, amely checkoutoláskor vagy commitoláskor
használatos, értéke "", "-text", "text", "text=auto", "text eol=lf",
"text eol=crlf". A Git 2.10 óta a "text=auto eol=lf" és a "text=auto eol=crlf"
támogatott.
+
A közönséges fájloknál mind az indexbeli ("i/<eolinfo>"), mind a working
tree-beli ("w/<eolinfo>") <eolinfo> megjelenik, amelyet az ("attr/<eolattr>")
követ.

--sparse::
	Ha az index sparse, a sparse könyvtárakat a bennük lévő fájlokra való
	kibontás nélkül jeleníti meg. A sparse könyvtárak záró perjellel
	jelennek meg, például "x/" egy "x" nevű sparse könyvtárhoz.

--format=<format>::
	Egy sztring, amely a megjelenített eredményből `%(fieldname)`-t
	interpolál. Interpolálja a `%%`-ot `%`-ra is, a `%xXX`-et pedig, ahol
	az `XX` hexadecimális számjegy, a `XX` hexkódú karakterre; például a
	`%x00` `\0`-ra (NUL), a `%x09` `\t`-re (TAB), a %x0a pedig `\n`-re
	(LF) interpolálódik.
	A --format nem kombinálható a `-s`, `-o`, `-k`, `-t`, `--resolve-undo`
	és `--eol` opcióval.
\--::
	Ne értelmezzen több argumentumot opcióként.

<file>::
	Megjelenítendő fájlok. Ha nincs fájl megadva, minden fájl megjelenik,
	amely illeszkedik a többi megadott feltételre.

OUTPUT
------
A 'git ls-files' csak a fájlneveket írja ki, hacsak nincs megadva a
`--stage`, amely esetben ezt írja ki:

        [<tag> ]<mode> <object> <stage> <file>

A 'git ls-files --eol' ezt mutatja:
	i/<eolinfo><SPACES>w/<eolinfo><SPACES>attr/<eolattr><SPACE*><TAB><file>

A 'git ls-files --unmerged' és a 'git ls-files --stage' a nem merge-elt
útvonalak részletes információinak vizsgálatára használható.

Egy nem merge-elt útvonalnál egyetlen mód/SHA-1 pár rögzítése helyett az
index legfeljebb három ilyen párt rögzít; egyet az O fából az 1-es
stage-ben, az A-t a 2-es stage-ben, a B-t pedig a 3-as stage-ben.  Ezt az
információt a felhasználó (vagy a porcelain) használhatja annak
megtekintésére, mit kell végül az útvonalon rögzíteni. (az állapotról
bővebben lásd linkgit:git-read-tree[1])

A `-z` opció nélkül a "szokatlan" karaktereket tartalmazó útvonalneveket a
`core.quotePath` konfigurációs változónál leírtak szerint idézőjelezi (lásd
linkgit:git-config[1]).  A `-z` használatakor a fájlnév szó szerint íródik
ki, a sort pedig egy NUL bájt zárja le.

Lehetséges egyéni formátumban való kiírás a `--format` opcióval, amely
különböző mezőket képes interpolálni egy `%(fieldname)` jelöléssel. Ha
például csak az "objectname" és a "path" mező érdekel, egy konkrét
"--format"-tal futtathatod, például:

	git ls-files --format='%(objectname) %(path)'

FIELD NAMES
-----------
Az egyes útvonalak megjelenítési módja a `--format=<format>` opcióval
testreszabható, ahol a <format> sztringben lévő %(fieldname) az
indexbejegyzés különböző aspektusaira interpolálódik.  A következő
"fieldname"-ek értelmezettek:

objectmode::
	Az indexben rögzített fájl módja.
objecttype::
	Az indexben rögzített fájl objektumtípusa.
objectname::
	Az indexben rögzített fájl neve.
objectsize[:padded]::
	Az indexben rögzített fájl objektummérete ("-", ha az objektum egy
	`commit` vagy `tree`).
	Támogatja a méret kitöltött formátumát is a "%(objectsize:padded)"-del.
stage::
	Az indexben rögzített fájl stage-e.
eolinfo:index::
eolinfo:worktree::
	Az útvonal indexbeli vagy worktree-beli tartalmának <eolinfo> értéke
	(lásd a `--eol` opció leírását).
eolattr::
	Az útvonalra vonatkozó <eolattr> (lásd a `--eol` opció leírását).
path::
	Az indexben rögzített fájl útvonalneve.

EXCLUDE PATTERNS
----------------

A 'git ls-files' „exclude minták" listáját használhatja, amikor bejárja a
könyvtárfát, és megjelenítendő fájlokat keres, ha a --others vagy a
--ignored kapcsoló meg van adva.  A linkgit:gitignore[5] adja meg az exclude
minták formátumát.

Ezek az exclude minták a következő helyekről adhatók meg, ebben a sorrendben:

  1. A --exclude=<pattern> parancssori kapcsoló egyetlen mintát ad meg.
     A minták ugyanabban a sorrendben rendeződnek, ahogy a parancssorban
     megjelennek.

  2. A --exclude-from=<file> parancssori kapcsoló egy minták listáját
     tartalmazó fájlt ad meg.  A minták ugyanabban a sorrendben
     rendeződnek, ahogy a fájlban megjelennek.

  3. A --exclude-per-directory=<name> parancssori kapcsoló a 'git ls-files'
     által vizsgált minden könyvtárban lévő fájl nevét adja meg,
     rendszerint a `.gitignore`-t.  A mélyebb könyvtárakban lévő fájlok
     elsőbbséget élveznek.  A minták ugyanabban a sorrendben rendeződnek,
     ahogy a fájlokban megjelennek.

A --exclude-dal a parancssorban megadott, vagy a --exclude-from-mal megadott
fájlból beolvasott minta a könyvtárfa tetejéhez relatív.  A
--exclude-per-directory-vel megadott fájlból beolvasott minta ahhoz a
könyvtárhoz relatív, amelyben a mintafájl megjelenik.

Általában használhatod a `--exclude-standard`-ot, amikor azt szeretnéd, hogy
az exclude szabályok ugyanúgy alkalmazódjanak, mint ahogy a Porcelain
parancsok teszik.  Ahhoz, hogy utánozd, amit a `--exclude-standard` megad,
megadhatod a `--exclude-per-directory=.gitignore`-t, majd megadhatod:

  1. A `core.excludesfile` konfigurációs változó által megadott fájlt, ha
     létezik, vagy a `$XDG_CONFIG_HOME/git/ignore` fájlt.

  2. A `$GIT_COMMON_DIR/info/exclude` fájlt.

a `--exclude-from=` opción keresztül.

SEE ALSO
--------
linkgit:git-read-tree[1], linkgit:gitignore[5]

GIT
---
A linkgit:git[1] csomag része
