git-diff(1)
===========

NAME
----
git-diff - Változások megjelenítése commitok között, commit és munkakönyvtár között, stb.


SYNOPSIS
--------
[synopsis]
git diff [<options>] [<commit>] [--] [<path>...]
git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]
git diff [<options>] [--merge-base] <commit> [<commit>...] <commit> [--] [<path>...]
git diff [<options>] <commit>...<commit> [--] [<path>...]
git diff [<options>] <blob> <blob>
git diff [<options>] --no-index [--] <path> <path> [<pathspec>...]

DESCRIPTION
-----------
Megjeleníti a munkakönyvtár és az index vagy egy fa közötti változásokat, az
index és egy fa közötti változásokat, két fa közötti változásokat, egy
merge-ből eredő változásokat, két blob objektum közötti változásokat, vagy
két, lemezen lévő fájl közötti változásokat.

`git diff [<options>] [--] [<path>...]`::

	Ez a forma az index (a következő commit staging area-ja) viszonylatában
	végzett módosítások megtekintésére szolgál. Más szóval, a különbségek
	azok, amiket Gitnek _mondhatnál_, hogy adjon hozzá az indexhez, de
	még nem tetted meg. Ezeket a változásokat a linkgit:git-add[1]
	használatával stage-elheted.

`git diff [<options>] --no-index [--] <path> <path> [<pathspec>...]`::

	Ez a forma a fájlrendszeren megadott két útvonal összehasonlítására
	szolgál. A `--no-index` opciót elhagyhatod, ha a parancsot egy Git
	által vezérelt munkakönyvtárban futtatod, és legalább az egyik
	útvonal a munkakönyvtáron kívülre mutat, vagy ha a parancsot egy Git
	által vezérelt munkakönyvtáron kívül futtatod. Ez a forma
	implikálja a `--exit-code`-ot. Ha mindkét útvonal könyvtárra mutat,
	további pathspecek adhatók meg. Ezek korlátozzák a különbségbe
	bevont fájlokat. Minden ilyen pathspecnek relatívnak kell lennie,
	mivel a diff mindkét oldalára vonatkoznak.

`git diff [<options>] --cached [--merge-base] [<commit>] [--] [<path>...]`::

	Ez a forma a következő commit számára stage-elt, a megnevezett
	_<commit>_ viszonylatában vett változások megtekintésére szolgál.
	Jellemzően a legutóbbi commithoz szeretnél viszonyítani, így ha
	nem adod meg a _<commit>_-ot, az alapértelmezetten `HEAD`. Ha a
	`HEAD` nem létezik (pl. meg nem született branchek esetén), és a
	_<commit>_ sincs megadva, akkor az összes stage-elt változást
	megmutatja. A `--staged` a `--cached` szinonimája.
+
Ha a `--merge-base` meg van adva, akkor a _<commit>_ helyett a _<commit>_
és a `HEAD` közötti merge-alap kerül felhasználásra. A `git diff --cached
--merge-base A` egyenértékű a `git diff --cached $(git merge-base A
HEAD)`-del.

`git diff [<options>] [--merge-base] <commit> [--] [<path>...]`::

	Ez a forma a munkakönyvtáradban lévő, a megnevezett _<commit>_
	viszonylatában vett változások megtekintésére szolgál. A `HEAD`
	segítségével a legutóbbi commithoz, vagy egy branch nevével egy
	másik branch csúcsához hasonlíthatod.
+
Ha a `--merge-base` meg van adva, akkor a _<commit>_ helyett a _<commit>_
és a `HEAD` közötti merge-alap kerül felhasználásra. A `git diff
--merge-base A` egyenértékű a `git diff $(git merge-base A HEAD)`-del.

`git diff [<options>] [--merge-base] <commit> <commit> [--] [<path>...]`::

	Ez két tetszőleges _<commit>_ közötti változások megtekintésére
	szolgál.
+
Ha a `--merge-base` meg van adva, a két commit merge-alapja lesz az
"előtte" oldal. A `git diff --merge-base A B` egyenértékű a `git diff
$(git merge-base A B) B`-vel.

`git diff [<options>] <commit> <commit>...<commit> [--] [<path>...]`::

	Ez a forma egy merge commit eredményének megtekintésére szolgál.
	Az elsőként felsorolt _<commit>_-nak magának a merge-nek kell lennie;
	a fennmaradó két vagy több commitnak a szüleinek kell lennie. A
	kívánt revízió-halmaz előállításának kényelmes módja a `@` és a
	`^!` utótagok használata. Ha `A` egy merge commit, akkor a `git
	diff A A^@`, a `git diff A^!` és a `git show A` mind ugyanazt a
	kombinált diffet adják.

`git diff [<options>] <commit>..<commit> [--] [<path>...]`::

	Ez szinonimája a korábbi (`..` nélküli) formának, két tetszőleges
	_<commit>_ közötti változások megtekintésére. Ha a _<commit>_ az
	egyik oldalon el van hagyva, ugyanaz a hatása, mintha a `HEAD`-et
	használtad volna helyette.

`git diff [<options>] <commit>...<commit> [--] [<path>...]`::

	Ez a forma a második _<commit>_-ot tartalmazó és odáig terjedő
	branchen lévő változások megtekintésére szolgál, a két _<commit>_
	közös ősétől kezdve. A `git diff A...B` egyenértékű a `git diff
	$(git merge-base A B) B`-vel. Bármelyik _<commit>_-ot elhagyhatod,
	aminek ugyanaz a hatása, mintha a `HEAD`-et használtad volna
	helyette.

Arra az esetre, ha valami egzotikus dolgot csinálnál, meg kell jegyezni,
hogy a fenti leírásban szereplő összes _<commit>_ — a `--merge-base` esetét,
és a `..` jelöléseket használó utolsó két formát kivéve — bármilyen
_<tree>_ lehet. Egy érdekes fa az, amelyre az `AUTO_MERGE` nevű ref mutat,
amelyet az `ort` merge-stratégia ír, amikor merge-konfliktusba ütközik
(lásd linkgit:git-merge[1]). A munkakönyvtár `AUTO_MERGE`-dzsel való
összehasonlítása megmutatja azokat a változtatásokat, amelyeket eddig a
szöveges konfliktusok feloldására tettél (lásd lent a példákat).

A _<commit>_ megadásának teljesebb listájáért lásd a linkgit:gitrevisions[7]
"SPECIFYING REVISIONS" szakaszát. A `diff` azonban két _végpont_
összehasonlításáról szól, nem tartományokról, és a tartomány-jelölések
(`<commit>..<commit>` és `<commit>...<commit>`) nem jelentenek olyan
tartományt, mint amit a linkgit:gitrevisions[7] "SPECIFYING RANGES"
szakasza definiál.

`git diff [<options>] <blob> <blob>`::

	Ez a forma két blob objektum nyers tartalma közötti különbségek
	megtekintésére szolgál.

OPTIONS
-------
:git-diff: 1
include::diff-options.adoc[]

`-1`::
`--base`::
`-2`::
`--ours`::
`-3`::
`--theirs`::
	A munkakönyvtár összehasonlítása
+
--
 * a "base" verzióval (1. stage), a `-1` vagy a `--base` használatakor,
 * a "mi branchünkkel" (2. stage), a `-2` vagy a `--ours` használatakor, vagy
 * az "ő branchükkel" (3. stage), a `-3` vagy a `--theirs` használatakor.
--
+
Az index csak a nem merge-elt bejegyzések esetén, azaz a konfliktusok
feloldása közben tartalmazza ezeket a stage-eket. Részletes információért
lásd a linkgit:git-read-tree[1] "Háromutas merge" szakaszát.

`-0`::
	Elhagyja a diff kimenetét a nem merge-elt bejegyzéseknél, és csak
	azt mutatja, hogy "Unmerged". Csak akkor használható, ha a
	munkakönyvtárat az indexszel hasonlítod össze.

`<path>...`::
	A _<path>_ paraméterek, ha meg vannak adva, a diff a megnevezett
	útvonalakra korlátozására szolgálnak (könyvtárneveket is megadhatsz,
	és az alattuk lévő összes fájlra megkapod a diffet).


include::diff-format.adoc[]

EXAMPLES
--------

A munkakönyvtár ellenőrzésének különféle módjai::
+
------------
$ git diff            <1>
$ git diff --cached   <2>
$ git diff HEAD       <3>
$ git diff AUTO_MERGE <4>
------------
+
<1> A munkakönyvtár változásai, amelyek még nincsenek stage-elve a
    következő commithoz.
<2> Az index és a legutóbbi commitod közötti változások; amit akkor
    commitolnál, ha a `git commit`-ot a `-a` opció nélkül futtatnád.
<3> A munkakönyvtár változásai a legutóbbi commitod óta; amit akkor
    commitolnál, ha a `git commit -a`-t futtatnád.
<4> A munkakönyvtárban eddig tett változtatásaid a szöveges konfliktusok
    feloldásához.

Összehasonlítás tetszőleges commitokkal::
+
------------
$ git diff test            <1>
$ git diff HEAD -- ./test  <2>
$ git diff HEAD^ HEAD      <3>
------------
+
<1> Az aktuális branch csúcsa helyett a "test" branch csúcsával
    hasonlít össze.
<2> A "test" branch csúcsával való összehasonlítás helyett az aktuális
    branch csúcsával hasonlít össze, de az összehasonlítást a "test"
    fájlra korlátozza.
<3> Összehasonlítja az utolsó commit előtti verziót az utolsó committal.

Branchek összehasonlítása::
+
------------
$ git diff topic master    <1>
$ git diff topic..master   <2>
$ git diff topic...master  <3>
------------
+
<1> A topic és a master branchek csúcsai közötti változások.
<2> Ugyanaz, mint fent.
<3> A master branchen történt változások azóta, hogy a topic branch
    onnan elindult.

A diff kimenetének korlátozása::
+
------------
$ git diff --diff-filter=MRC            <1>
$ git diff --name-status                <2>
$ git diff arch/i386 include/asm-i386   <3>
------------
+
<1> Csak a módosítást, átnevezést és másolást mutatja, a hozzáadást
    vagy törlést nem.
<2> Csak a neveket és a változás jellegét mutatja, a tényleges diff
    kimenetét nem.
<3> A diff kimenetét a megnevezett alfákra korlátozza.

A diff kimenetének átalakítása::
+
------------
$ git diff --find-copies-harder -B -C  <1>
$ git diff -R                          <2>
------------
+
<1> Extra ciklusokat fordít átnevezések, másolások és teljes
    újraírások felderítésére (nagyon költséges).
<2> A diffet fordított sorrendben írja ki.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

:git-diff: 1
include::config/diff.adoc[]

SEE ALSO
--------
`diff`(1),
linkgit:git-difftool[1],
linkgit:git-log[1],
linkgit:gitdiffcore[7],
linkgit:git-format-patch[1],
linkgit:git-apply[1],
linkgit:git-show[1]

GIT
---
A linkgit:git[1] csomag része
