git-checkout-index(1)
=====================

NAME
----
git-checkout-index - Fájlok másolása az indexből a working tree-be


SYNOPSIS
--------
[verse]
'git checkout-index' [-u] [-q] [-a] [-f] [-n] [--prefix=<string>]
		   [--stage=<number>|all]
		   [--temp]
		   [--ignore-skip-worktree-bits]
		   [-z] [--stdin]
		   [--] [<file>...]

DESCRIPTION
-----------
Az összes felsorolt fájlt átmásolja az indexből a munkakönyvtárba
(a meglévő fájlok felülírása nélkül).

OPTIONS
-------
-u::
--index::
	frissíti a stat-információt a kicheckoutolt bejegyzésekhez
	az index fájlban.

-q::
--quiet::
	legyen csendes, ha fájlok léteznek vagy nincsenek benne az indexben

-f::
--force::
	kikényszeríti a meglévő fájlok felülírását

-a::
--all::
	kicheckoutolja az index összes fájlját, kivéve azokat,
	amelyeknek be van állítva a skip-worktree bitje (l.
	`--ignore-skip-worktree-bits`). Nem használható együtt explicit
	fájlnevekkel.

-n::
--no-create::
	Ne checkoutoljon ki új fájlokat, csak a már kicheckoutolt
	fájlokat frissítse.

--prefix=<string>::
	Fájlok létrehozásakor <string>-et fűz a névhez előtagként
	(rendszerint egy, záró /-t is tartalmazó könyvtár)

--stage=<number>|all::
	Az összefésületlen bejegyzések kicheckoutolása helyett a
	megnevezett stage-ből másolja ki a fájlokat. A <number>-nek 1 és
	3 között kell lennie. Megjegyzés: a --stage=all automatikusan
	maga után vonja a --temp-et.

--temp::
	A fájlok munkakönyvtárba másolása helyett a tartalmat ideiglenes
	fájlokba írja. Az ideiglenes név-hozzárendelések a stdoutra
	kerülnek kiírásra.

--ignore-skip-worktree-bits::
	Az összes fájlt kicheckoutolja, azokat is, amelyeknek be van
	állítva a skip-worktree bitje.

--stdin::
	Az útvonalak listáját a parancssor helyett a standard bemenetről
	olvassa be. Az útvonalakat alapértelmezés szerint LF választja
	el (azaz soronként egy útvonal).

-z::
	Csak a `--stdin`-nel együtt van értelme; az útvonalakat LF
	helyett NUL karakter választja el.

\--::
	A további argumentumokat ne értelmezze opcióként.

A kapcsolók sorrendje régen számított, de már nem.

Ha egyszerűen csak kiadjuk a `git checkout-index` parancsot, az nem
csinál semmit. Valószínűleg a `git checkout-index -a`-ra gondoltunk.
És ha erőltetni akarjuk, a `git checkout-index -f -a` kell.

Itt nem az intuitivitás a cél, hanem az ismételhetőség. Az „argumentum
nélkül nincs munka" viselkedés oka az, hogy szkriptekből képesnek
kell lennünk a következőt megtenni:

----------------
$ find . -name '*.h' -print0 | xargs -0 git checkout-index -f --
----------------

amely kikényszeríti, hogy az összes meglévő `*.h` fájl lecserélődjön a
gyorsítótárazott másolatára. Ha egy üres parancssor „mindent" jelentene,
akkor ez az index mindenét kényszer-frissítené, ami nem ez volt a cél.
De mivel a 'git checkout-index' elfogadja a --stdin-t, gyorsabb a
következőt használni:

----------------
$ find . -name '*.h' -print0 | git checkout-index -f -z --stdin
----------------

A `--` jó ötlet, ha tudjuk, hogy a többi argumentum fájlnév lesz; ez
megelőzi a problémákat egy, például `-a` nevű fájllal. A `--` használata
valószínűleg jó szabály szkriptekben.


A --temp vagy a --stage=all használata
---------------------------------------
Amikor a `--temp`-et használjuk (vagy azt a `--stage=all` implikálja),
a 'git checkout-index' egy ideiglenes fájlt hoz létre minden
kicheckoutolt index-bejegyzéshez. Az index nem frissül stat-
információval. Ezek az opciók akkor lehetnek hasznosak, ha a hívónak
minden összefésületlen bejegyzés összes stage-ére szüksége van ahhoz,
hogy az összefésületlen fájlokat egy külső merge-eszközzel tudja
feldolgozni.

Egy listázás kerül kiírásra a stdoutra, amely megadja az ideiglenes
fájlnevek és a követett útvonalnevek közti hozzárendelést. A listázás
formátumának két változata van:

    . tempname TAB path RS
+
Az első formátum akkor kerül használatra, ha a `--stage` el van
hagyva, vagy nem `--stage=all`. A tempname mező a fájltartalmat tartó
ideiglenes fájlnév, a path pedig a követett útvonalnév az indexben.
Csak a kért bejegyzések kerülnek kiírásra.

    . stage1temp SP stage2temp SP stage3tmp TAB path RS
+
A második formátum akkor kerül használatra, ha `--stage=all`. A három
stage ideiglenes mező (stage1temp, stage2temp, stage3temp) az
ideiglenes fájl nevét sorolja fel, ha van stage-bejegyzés az indexben,
vagy `.`-ot, ha nincs stage-bejegyzés. Az olyan útvonalak, amelyeknek
csak 0-s stage-bejegyzésük van, mindig kimaradnak a kimenetből.

Mindkét formátumban az RS (a rekordelválasztó) alapértelmezés szerint
újsor, de null-bájt lesz, ha a -z opciót adtuk meg a parancssorban.
Az ideiglenes fájlnevek mindig biztonságos sztringek; sosem
tartalmaznak könyvtárelválasztókat vagy whitespace-karaktereket. A
path mező mindig a jelenlegi könyvtárhoz relatív, az ideiglenes
fájlnevek pedig mindig a legfelső szintű könyvtárhoz relatívak.

Ha az ideiglenes fájlba kimásolt objektum egy szimbolikus link, a link
tartalma egy normál fájlba kerül kiírásra. A végfelhasználó vagy a
Porcelain feladata, hogy hasznosítsa ezt az információt.


EXAMPLES
--------
Csak a már kicheckoutolt fájlok frissítése és felújítása::
+
----------------
$ git checkout-index -n -f -a && git update-index --ignore-missing --refresh
----------------

A 'git checkout-index' használata „egy teljes fa exportálásához"::
	Az előtag-képesség alapvetően triviálissá teszi, hogy a
	'git checkout-index'-et „fa exportálása" funkcióként
	használjuk. Egyszerűen olvassuk be a kívánt fát az indexbe,
	majd:
+
----------------
$ git checkout-index --prefix=git-export-dir/ -a
----------------
+
A `git checkout-index` „exportálja" az indexet a megadott
könyvtárba.
+
A záró „/" fontos. Az exportált név szó szerint csak a megadott
sztringgel van előtagolva. Vessük ezt össze a következő példával.

Fájlok exportálása előtaggal::
+
----------------
$ git checkout-index --prefix=.merged- Makefile
----------------
+
Ez a `Makefile` jelenleg gyorsítótárazott másolatát checkoutolja ki
a `.merged-Makefile` fájlba.

GIT
---
A linkgit:git[1] csomag része
