git-clone(1)
============

NAME
----
git-clone - Repository klónozása egy új könyvtárba


SYNOPSIS
--------
[synopsis]
git clone [--template=<template-directory>]
	  [-l] [-s] [--no-hardlinks] [-q] [-n] [--bare] [--mirror]
	  [-o <name>] [-b <name>] [-u <upload-pack>] [--reference <repository>]
	  [--dissociate] [--separate-git-dir <git-dir>]
	  [--depth <depth>] [--[no-]single-branch] [--[no-]tags]
	  [--recurse-submodules[=<pathspec>]] [--[no-]shallow-submodules]
	  [--[no-]remote-submodules] [--jobs <n>] [--sparse] [--[no-]reject-shallow]
	  [--filter=<filter-spec> [--also-filter-submodules]] [--] <repository>
	  [<directory>]

DESCRIPTION
-----------

Egy repository-t klónoz egy újonnan létrehozott könyvtárba, remote-tracking
branchet hoz létre a klónozott repository minden egyes branchéhez
(a `git branch --remotes` paranccsal láthatók), majd létrehoz és
checkoutol egy kiinduló branchet, amely a klónozott repository
aktuálisan aktív branchéből ágazik le.

A klónozás után egy egyszerű, argumentum nélküli `git fetch` az
összes remote-tracking branchet frissíti, egy argumentum nélküli
`git pull` pedig ezenfelül a remote master branchet is összemerge-eli
a jelenlegi master branchbe, ha van ilyen (ez nem igaz, ha a
`--single-branch` meg van adva; lásd lentebb).

Ezt az alapértelmezett beállítást úgy éri el, hogy referenciákat hoz
létre a remote branch fejekhez a `refs/remotes/origin` alatt, és
inicializálja a `remote.origin.url` és a `remote.origin.fetch`
konfigurációs változókat.


OPTIONS
-------
`-l`::
`--local`::
	Ha a klónozandó repository egy helyi gépen van, ez a kapcsoló
	kihagyja a szokásos „Git-tudatos" transzportmechanizmust, és úgy
	klónozza a repository-t, hogy másolatot készít a `HEAD`-ről és az
	objects és refs könyvtárak alatt mindenről.
	A `.git/objects/` könyvtár alatti fájlok hardlinkeltek, hogy
	lehetőség szerint helyet takarítsanak meg.
+
Ha a repository egy helyi elérési útként van megadva (pl. `/path/to/repo`),
ez az alapértelmezett, és a `--local` lényegében no-op. Ha a repository
URL-ként van megadva, akkor ezt a kapcsolót figyelmen kívül hagyja (és
soha nem használja a helyi optimalizációkat). A `--no-local` megadása
felülírja az alapértelmezést, ha `/path/to/repo` van megadva, és helyette
a szokásos Git-transzportot használja.
+
Ha a repository `$GIT_DIR/objects` könyvtára szimbolikus linkeket
tartalmaz, vagy maga is szimbolikus link, a klónozás sikertelen lesz.
Ez egy biztonsági intézkedés, amely megakadályozza fájlok nem szándékos
másolását a szimbolikus linkek feloldásával.
+
Ez az opció biztonsági okokból nem működik más felhasználók tulajdonában
lévő repository-kkal, és a klónozás sikeréhez a `--no-local`-t kell megadni.
+
*MEGJEGYZÉS*: ez a művelet versenyhelyzetbe kerülhet a forrás-repository
egyidejű módosításával, hasonlóan ahhoz, mintha `cp -r <src> <dst>`-t
futtatnál, miközben módosítod a _<src>_-t.

`--no-hardlinks`::
	Kikényszeríti, hogy egy helyi fájlrendszeren lévő repository-ból
	történő klónozási folyamat a `.git/objects` könyvtár alatti
	fájlokat hardlinkek helyett másolja. Ez akkor lehet kívánatos, ha
	biztonsági másolatot próbálsz készíteni a repository-dról.

`-s`::
`--shared`::
	Ha a klónozandó repository a helyi gépen van, hardlinkek
	használata helyett automatikusan beállítja a
	`.git/objects/info/alternates` fájlt, hogy megossza az objektumokat
	a forrás-repository-val. Az eredményül kapott repository saját
	objektum nélkül indul.
+
MEGJEGYZÉS: ez egy potenciálisan veszélyes művelet; *ne* használd,
hacsak nem érted, mit csinál. Ha ezzel az opcióval klónozod a
repository-dat, majd brancheket törölsz (vagy bármilyen más olyan Git
parancsot használsz, amely bármely létező commitot referencia nélkülivé
tesz) a forrás-repository-ban, egyes objektumok referencia nélkülivé
(vagy „dangling"-gá) válhatnak. Ezeket az objektumokat a normál Git
műveletek (például a `git commit`) eltávolíthatják, amelyek automatikusan
meghívják a `git maintenance run --auto` parancsot. (Lásd:
linkgit:git-maintenance[1].) Ha ezeket az objektumokat eltávolítják, és
azokra a klónozott repository hivatkozott, akkor a klónozott repository
sérültté válik.
+
Vedd figyelembe, hogy a `git repack` `--local` opció nélküli futtatása
egy `--shared`-del klónozott repository-ban objektumokat másol a
forrás-repository-ból egy packbe a klónozott repository-ban, ezzel
megszüntetve a `clone --shared` lemezterület-megtakarítását. Biztonságos
azonban a `git gc` futtatása, amely alapértelmezetten a `--local` opciót
használja.
+
Ha meg akarod szüntetni egy `--shared`-del klónozott repository
függőségét a forrás-repository-jától, egyszerűen futtathatod a
`git repack -a` parancsot, hogy az összes objektumot átmásold a
forrás-repository-ból egy packbe a klónozott repository-ban.

`--reference=<repository>`::
`--reference-if-able=<repository>`::
	Ha a referencia-_<repository>_ a helyi gépen van, automatikusan
	beállítja a `.git/objects/info/alternates` fájlt, hogy objektumokat
	szerezzen be a referencia-_<repository>_-ból. Egy már létező
	repository alternate-ként való használata kevesebb objektum
	másolását igényli a klónozandó repository-ból, ami csökkenti a
	hálózati és a helyi tárolási költségeket. A `--reference-if-able`
	használatakor egy nem létező könyvtár figyelmeztetéssel átugrásra
	kerül, ahelyett hogy megszakítaná a klónozást.
+
MEGJEGYZÉS: lásd a `--shared` opcióhoz tartozó megjegyzést, valamint a
`--dissociate` opciót.

`--dissociate`::
	A `--reference` opciókkal megadott referencia-repository-któl csak
	azért kölcsönöz objektumokat, hogy csökkentse a hálózati
	adatátvitelt, majd a klónozás elkészülte után abbahagyja a tőlük
	való kölcsönzést azáltal, hogy a szükséges helyi másolatokat
	elkészíti a kölcsönzött objektumokról. Ez az opció akkor is
	használható, ha helyileg klónozol egy olyan repository-ból, amely
	már maga is objektumokat kölcsönöz egy másik repository-tól — az
	új repository ugyanattól a repository-tól fog kölcsönözni, és ez
	az opció használható a kölcsönzés leállítására.

`-q`::
`--quiet`::
	Csendes működés. A folyamat nem kerül jelentésre a szabványos
	hibafolyamon.

`-v`::
`--verbose`::
	Bőbeszédű futás. Nincs hatással a folyamatállapot szabványos
	hibafolyamra való jelentésére.

`--progress`::
	A folyamatállapotot alapértelmezetten a szabványos hibafolyamon
	jelenti, ha az egy terminálhoz van csatolva, hacsak a `--quiet`
	nincs megadva. Ez a kapcsoló kikényszeríti a folyamatállapot
	jelentését még akkor is, ha a szabványos hibafolyam nem egy
	terminálra irányul.

`--server-option=<option>`::
	A megadott karakterláncot elküldi a szervernek a 2-es protokollverzió
	használatával történő kommunikáció során. A megadott karakterlánc nem
	tartalmazhat _NUL_ vagy _LF_ karaktert. A szerveropciók kezelése, az
	ismeretleneket is beleértve, szerverfüggő.
	Ha több `--server-option=<option>` van megadva, mindegyik a
	parancssorban felsorolt sorrendben kerül elküldésre a másik oldalra.
	Ha a parancssorból nincs `--server-option=<option>` megadva, akkor
	helyette a `remote.<name>.serverOption` konfigurációs változó
	értékei kerülnek felhasználásra.

`-n`::
`--no-checkout`::
	A klónozás befejezése után nem checkoutolja a `HEAD`-et.

`--no-reject-shallow`::
`--reject-shallow`::
	Hibával leáll, ha a forrás-repository egy shallow repository.
	Az alapértelmezés a `clone.rejectShallow` konfigurációs változóval
	adható meg.

`--bare`::
	'Bare' Git repository-t hoz létre. Vagyis a _<directory>_
	létrehozása és az adminisztratív fájlok `<directory>/.git`
	alá helyezése helyett magát a _<directory>_-t teszi
	`$GIT_DIR`-ré. Ez nyilvánvalóan magával vonja a `--no-checkout`-ot,
	mivel nincs hova checkoutolni a munkakönyvtárat.
	Emellett a remote branch fejeit közvetlenül a megfelelő helyi
	branch fejekbe másolja, anélkül hogy leképezné őket a
	`refs/remotes/origin/` alá. Ha ez az opció használatban van, sem
	remote-tracking branchek, sem a hozzájuk kapcsolódó konfigurációs
	változók nem jönnek létre.

`--sparse`::
	Sparse-checkoutot alkalmaz, kezdetben csak a legfelső szintű
	könyvtárban lévő fájlok lesznek jelen. A
	linkgit:git-sparse-checkout[1] parancs használható a munkakönyvtár
	igény szerinti bővítésére.

`--filter=<filter-spec>`::
	A partial clone funkciót használja, és kéri, hogy a szerver egy
	adott objektumszűrő szerinti részhalmazát küldje el az elérhető
	objektumoknak. A `--filter` használatakor a megadott
	_<filter-spec>_ kerül felhasználásra a partial clone szűrőjeként.
+
Ha a `--filter=auto` van használva, a szűrő-specifikációt a
'promisor-remote' protokoll (lásd: linkgit:gitprotocol-v2[5]) határozza
meg automatikusan, a szerver által a kliens által elfogadott promisor
remote-okhoz meghirdetett szűrő-specifikációk kombinálásával (lásd a
`promisor.acceptFromServer` konfigurációs opciót a linkgit:git-config[1]
parancsban). Ez lehetővé teszi a szerver számára, hogy javasolja az
optimális szűrőt az elérhető promisor remote-okhoz.
+
Más szűrő-specifikációkhoz hasonlóan az „auto" érték is megőrződik a
konfigurációban. Ez biztosítja, hogy a jövőbeli fetch-ek továbbra is
alkalmazkodjanak a szerver aktuális ajánlásához.
+
Az összes többi elérhető szűrő-specifikáció részleteiért lásd a
`--filter=<filter-spec>` opciót a linkgit:git-rev-list[1] parancsban.
+
Például a `--filter=blob:none` kiszűr minden blobot (fájltartalmat)
addig, amíg a Gitnek szüksége nem lesz rájuk. Emellett a
`--filter=blob:limit=<size>` kiszűri az összes legalább _<size>_
méretű blobot.

`--also-filter-submodules`::
	A partial clone szűrőt a repository submodule-jaira is alkalmazza.
	A `--filter` és a `--recurse-submodules` szükséges hozzá. Ez
	alapértelmezetten bekapcsolható a `clone.filterSubmodules` konfigurációs
	opció beállításával.

`--mirror`::
	A forrás-repository egy tükrét (mirror) állítja be. Ez magával
	vonja a `--bare`-t. A `--bare`-hez képest a `--mirror` nemcsak a
	forrás helyi branchjeit képezi le a cél helyi branchjeire, hanem
	az összes referenciát leképezi (remote-tracking brancheket,
	note-okat stb.), és egy olyan refspec-konfigurációt állít be,
	amely szerint mindezeket a referenciákat felülírja egy
	`git remote update` a cél-repository-ban.

`-o<name>`::
`--origin=<name>`::
	Az upstream repository nyomon követéséhez az `origin` remote név
	helyett _<name>_-et használ. Felülírja a config `clone.defaultRemoteName`
	beállítását.

`-b<name>`::
`--branch=<name>`::
	Az újonnan létrehozott `HEAD`-et a _<name>_ branchre mutatja, a
	klónozott repository `HEAD`-je által mutatott branch helyett. Egy
	nem bare repository-ban ez az a branch, amely checkoutolva lesz.
	A `--branch` tageket is elfogadhat, és ilyenkor a `HEAD`-et az
	eredményül kapott repository-ban az adott commitnál leválasztja
	(detacheli).

`--revision=<rev>`::
	Új repository-t hoz létre, és lekéri a megadott _<rev>_
	revízióhoz vezető történetet (és semmi mást), anélkül hogy
	bármilyen remote-tracking branchet vagy helyi branchet létrehozna,
	és leválasztja (detacheli) a `HEAD`-et a _<rev>_-hez. Az
	argumentum lehet egy ref-név (pl. `refs/heads/main` vagy
	`refs/tags/v1.0`), amely egy commitig hámozódik le, vagy egy
	hexadecimális objektumnév.
	Ez az opció nem kompatibilis a `--branch`-csel és a `--mirror`-ral.

`-u<upload-pack>`::
`--upload-pack=<upload-pack>`::
	Nem alapértelmezett elérési utat ad meg a másik végen futtatandó
	parancshoz, amikor a klónozandó repository ssh-n keresztül érhető el.

`--template=<template-directory>`::
	Megadja azt a könyvtárat, amelyből a sablonok használatosak lesznek;
	(lásd a linkgit:git-init[1] „TEMPLATE DIRECTORY" szakaszát.)

`-c<key>=<value>`::
`--config=<key>=<value>`::
	Beállít egy konfigurációs változót az újonnan létrehozott
	repository-ban; ez azonnal érvénybe lép a repository
	inicializálása után, de még mielőtt a remote történet lekérésre
	vagy bármilyen fájl checkoutolásra kerülne. A _<key>_ ugyanolyan
	formátumú, mint amit a linkgit:git-config[1] elvár (pl.
	`core.eol=true`). Ha ugyanahhoz a kulcshoz több érték van
	megadva, mindegyik érték be lesz írva a config fájlba. Ez
	biztonságossá teszi például további fetch refspecek hozzáadását
	az origin remote-hoz.
+
A jelenlegi implementáció korlátai miatt egyes konfigurációs
változók csak a kezdeti fetch és checkout után lépnek érvénybe.
Az ismerten érvénybe nem lépő konfigurációs változók: a
`remote.<name>.mirror` és a `remote.<name>.tagOpt`. Ezek helyett
használd a megfelelő `--mirror` és `--no-tags` opciókat.

`--depth=<depth>`::
	'Shallow' klónt hoz létre, a történetet a megadott számú commitra
	csonkítva. Ez magával vonja a `--single-branch`-et, hacsak a
	`--no-single-branch` nincs megadva az összes branch csúcsai
	közelében lévő történet lekéréséhez. Ha a submodule-okat is
	shallow módon szeretnéd klónozni, add meg a
	`--shallow-submodules`-t is.

`--shallow-since=<date>`::
	Shallow klónt hoz létre, a megadott időpont utáni történettel.

`--shallow-exclude=<ref>`::
	Shallow klónt hoz létre, a történetből kizárva a megadott remote
	branchről vagy tagről elérhető commitokat. Ez az opció többször
	is megadható.

`--single-branch`::
`--no-single-branch`::
	Csak egyetlen branch csúcsáig vezető történetet klónoz, amelyet
	vagy a `--branch` opció, vagy az elsődleges branch remote-jának
	`HEAD`-je jelöl ki.
	Az eredményül kapott repository-ba történő további fetch-ek csak
	annak a branchnek a remote-tracking branchjét fogják frissíteni,
	amelyhez ezt az opciót a kezdeti klónozáshoz használták. Ha a
	remote-on lévő `HEAD` nem mutatott egyetlen branchre sem, amikor
	a `--single-branch` klónozás megtörtént, nem jön létre
	remote-tracking branch.

`--tags`::
`--no-tags`::
	Szabályozza, hogy a tagek klónozva legyenek-e. Ha a `--no-tags`
	meg van adva, ez az opció a `remote.<remote>.tagOpt=--no-tags`
	konfiguráció beállításával véglegessé válik. Ez biztosítja, hogy a
	jövőbeli `git pull` és `git fetch` ne kövessen egyetlen taget sem.
	A későbbi, explicit tag-fetch-ek továbbra is működni fognak (lásd:
	linkgit:git-fetch[1]).
+
Alapértelmezetten a tagek klónozva vannak, így a `--tags` átadása
jellemzően no-op, kivéve ha egy korábbi `--no-tags`-et von vissza.
+
Kombinálható a `--single-branch`-csel, hogy egyetlen klónozott
branchen kívül más referencia nélküli branchet lehessen klónozni és
fenntartani. Ez hasznos például egy repository alapértelmezett
branchjének minimális klónjainak fenntartásához keresőindexelés
céljából.

`--recurse-submodules[=<pathspec>]`::
	A klónozás létrehozása után inicializálja és klónozza a benne
	lévő submodule-okat a megadott _<pathspec>_ alapján. Ha nincs
	megadva `=<pathspec>`, az összes submodule inicializálva és
	klónozva lesz. Ez az opció többször is megadható több elemből
	álló pathspecekhez. Az eredményül kapott klón `submodule.active`
	beállítása a megadott pathspecre, vagy „`.`"-ra (ami az összes
	submodule-t jelenti) áll, ha nincs pathspec megadva.
+
A submodule-ok az alapértelmezett beállításaikkal kerülnek
inicializálásra és klónozásra. Ez egyenértékű azzal, mintha közvetlenül
a klónozás befejezése után futtatnád a
`git submodule update --init --recursive <pathspec>` parancsot. Ez az
opció figyelmen kívül van hagyva, ha a klónozott repository-nak nincs
worktree-je/checkoutja (azaz ha a `--no-checkout`/`-n`, `--bare` vagy
`--mirror` bármelyike meg van adva)

`--shallow-submodules`::
`--no-shallow-submodules`::
	Az összes klónozott submodule shallow lesz, 1-es mélységgel.

`--remote-submodules`::
`--no-remote-submodules`::
	Az összes klónozott submodule a submodule remote-tracking
	branchjének állapotát fogja használni a submodule frissítéséhez,
	a szuperprojekt rögzített SHA-1-je helyett. Egyenértékű a
	`--remote` átadásával a `git submodule update` parancsnak.

`--separate-git-dir=<git-dir>`::
	Ahelyett hogy a klónozott repository-t a rendeltetési helyére
	tenné, a klónozott repository-t a megadott könyvtárba helyezi,
	majd egy fájlrendszer-független Git szimbolikus linket készít
	oda. Az eredmény az, hogy a Git-repository elválasztható a
	munkakönyvtártól.

`--ref-format=<ref-format>`::

Megadja a repository-hoz használt ref-tárolási formátumot. Az érvényes
értékek:
+
include::ref-storage-format.adoc[]

`-j<n>`::
`--jobs=<n>`::
	Az egyidejűleg lekért submodule-ok száma.
	Alapértelmezetten a `submodule.fetchJobs` opció értékét veszi fel.

_<repository>_::
	A (esetleg remote) _<repository>_, amelyből klónozni kell. A
	repository-k megadásáról bővebb információért lásd a lenti
	<<URLS,GIT URL-ek>> szakaszt.

_<directory>_::
	Az új könyvtár neve, amelybe klónozni kell. A forrás-repository
	„humanish" (emberileg olvasható) része kerül felhasználásra, ha
	nincs explicit módon megadva _<directory>_ (`repo` a
	`/path/to/repo.git`-hez és `foo` a `host.xz:foo/.git`-hez). Egy
	létező könyvtárba klónozás csak akkor engedélyezett, ha a
	könyvtár üres.

`--bundle-uri=<uri>`::
	Mielőtt a remote-ról fetchelne, letölt egy bundle-t a megadott
	_<uri>_-ból, és kicsomagolja az adatokat a helyi repository-ba. A
	bundle-ben lévő referenciák a rejtett `refs/bundle/*` névtér alatt
	kerülnek tárolásra. Ez az opció nem kompatibilis a `--depth`, a
	`--shallow-since` és a `--shallow-exclude` opciókkal.

:git-clone: 1
include::urls.adoc[]

EXAMPLES
--------

* Klónozás az upstreamből:
+
------------
$ git clone git://git.kernel.org/pub/scm/.../linux.git my-linux
$ cd my-linux
$ make
------------


* Helyi klón létrehozása, amely az aktuális könyvtárból kölcsönöz, checkout nélkül:
+
------------
$ git clone -l -s -n . ../copy
$ cd ../copy
$ git show-branch
------------


* Klónozás az upstreamből, miközben egy létező helyi könyvtárból kölcsönöz:
+
------------
$ git clone --reference /git/linux.git \
	git://git.kernel.org/pub/scm/.../linux.git \
	my-linux
$ cd my-linux
------------


* Bare repository létrehozása a változtatások nyilvánosság számára való közzétételéhez:
+
------------
$ git clone --bare -l /home/proj/.git /pub/scm/proj.git
------------

* Helyi repository klónozása egy másik felhasználótól:
+
------------
$ git clone --no-local /home/otheruser/proj.git /pub/scm/proj.git
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/init.adoc[]

include::config/clone.adoc[]


GIT
---
A linkgit:git[1] csomag része
