git-p4(1)
=========

NAME
----
git-p4 - Importálás Perforce repository-kból, és submitolás azokba


SYNOPSIS
--------
[verse]
'git p4 clone' [<sync-options>] [<clone-options>] <p4-depot-path>...
'git p4 sync' [<sync-options>] [<p4-depot-path>...]
'git p4 rebase'
'git p4 submit' [<submit-options>] [<master-branch-name>]


DESCRIPTION
-----------
Ez a parancs lehetővé teszi a p4 repository-kkal való interakciót
Git használatával.

Hozz létre egy új Git repository-t egy meglévő p4 repository-ból a
'git p4 clone' paranccsal, megadva neki egy vagy több p4 depot
elérési utat.  Az új commitokat a p4 változtatásaiból a 'git p4 sync'
paranccsal építheted be.  A 'sync' parancs arra is szolgál, hogy új
brancheket vegyél fel más p4 depot elérési utakról.  A Git
változtatásokat a 'git p4 submit' paranccsal submitold vissza a
p4-be.  A 'git p4 rebase' parancs egy sync-et hajt végre, majd
rebase-eli az aktuális branchet a frissített p4 remote branchre.


EXAMPLES
--------
* Repository klónozása:
+
------------
$ git p4 clone //depot/path/project
------------

* Végezz némi munkát az újonnan létrehozott Git repository-ban:
+
------------
$ cd project
$ vi foo.h
$ git commit -a -m "edited foo.h"
------------

* Frissítsd a Git repository-t a p4 legutóbbi változtatásaival, a
  saját munkádat föléjük rebase-elve:
+
------------
$ git p4 rebase
------------

* Submitold vissza a commitjaidat a p4-be:
+
------------
$ git p4 submit
------------


COMMANDS
--------

Clone
~~~~~
A 'git p4 clone' parancsot általában arra használjuk, hogy egy új
Git könyvtárat hozzunk létre egy meglévő p4 repository-ból:

------------
$ git p4 clone //depot/path/project
------------
Ez:

1. Létrehoz egy üres Git repository-t egy 'project' nevű alkönyvtárban.
+
2. Beimportálja a megadott p4 depot elérési út head revíziójának
   teljes tartalmát egyetlen commitba a Git 'refs/remotes/p4/master'
   branchén.
+
3. Létrehoz egy helyi 'master' branchet ebből a remote-ból, és
   checkoutolja azt.

A teljes p4 előzmény Git-beli reprodukálásához használd a '@all'
módosítót a depot elérési úton:

------------
$ git p4 clone //depot/path/project@all
------------


Sync
~~~~
Ahogy a fejlesztés folytatódik a p4 repository-ban, azok a
változtatások a következővel vehetők fel a Git repository-ba:

------------
$ git p4 sync
------------

Ez a parancs megkeresi az új változtatásokat a p4-ben, és Git
commitokként importálja őket.

P4 repository-k egy meglévő Git repository-hoz is hozzáadhatók a
'git p4 sync' paranccsal:

------------
$ mkdir repo-git
$ cd repo-git
$ git init
$ git p4 sync //path/in/your/perforce/depot
------------

Ez beimportálja a megadott depot-ot a
'refs/remotes/p4/master'-be egy meglévő Git repository-ban.  A
`--branch` opcióval megadható egy másik branch, amely a p4 tartalomhoz
használandó.

Ha egy Git repository tartalmazza a 'refs/remotes/origin/p4' brancheket,
ezek lekérésre kerülnek, és egy 'git p4 sync' során elsőként ezeket
veszi figyelembe.  Mivel a p4-ből közvetlenül importálni jelentősen
lassabb, mint egy Git remote-ból pull-olni a változtatásokat, ez
hasznos lehet többfejlesztős környezetben.

Ha több branch is van, a 'git p4 sync' automatikusan a
„BRANCH DETECTION" algoritmust használja, hogy megpróbálja az új
változtatásokat a megfelelő branchbe particionálni.  Ez felülbírálható
a `--branch` opcióval, amellyel megadható egyetlen, frissítendő
branch.


Rebase
~~~~~~
Egy gyakori munkaminta, hogy lekéred a legutóbbi változtatásokat a p4
depotból, és merge-eled őket a helyi, nem commitolt változtatásokkal.
A p4 repository gyakran az összes kód végső helye, így egy
rebase-alapú munkafolyamatnak van értelme.  Ez a parancs egy
'git p4 sync'-et hajt végre, amelyet egy 'git rebase' követ, hogy a
helyi commitokat a frissített p4 változtatások fölé mozgassa.

------------
$ git p4 rebase
------------


Submit
~~~~~~
A változtatások submitolása egy Git repository-ból vissza a p4
repository-ba egy külön p4 kliens workspace-t igényel.  Ezt a
`P4CLIENT` környezeti változóval vagy a 'git-p4.client' Git
konfigurációs változóval kell megadni.  A p4 kliensnek léteznie kell,
de a kliens gyökere létrejön és feltöltésre kerül, ha még nem létezik.

Ahhoz, hogy submitold az összes olyan változtatást, amely az aktuális
Git branchben van, de a 'p4/master' branchben nincs, használd:

------------
$ git p4 submit
------------

Az aktuálistól eltérő branch megadásához használd:

------------
$ git p4 submit topicbranch
------------

Egyetlen commit vagy commitok egy tartományának megadásához használd:

------------
$ git p4 submit --commit <sha1>
$ git p4 submit --commit <sha1..sha1>
------------

Az upstream referencia általában 'refs/remotes/p4/master', de
felülbírálható a `--origin=` parancssori opcióval.

A p4 változtatások annak a felhasználónak a nevében jönnek létre, aki
a 'git p4 submit'-et meghívta. A `--preserve-user` opció hatására a
tulajdonjog a Git commit szerzőjének megfelelően módosul.  Ez az
opció admin jogosultságot igényel a p4-ben, amely a 'p4 protect'
paranccsal adható meg.

Ahhoz, hogy submitolás helyett shelve-eld a változtatásokat, használd a
`--shelve` és `--update-shelve` opciókat:

----
$ git p4 submit --shelve
$ git p4 submit --update-shelve 1234 --update-shelve 2345
----


Unshelve
~~~~~~~~
Az unshelve-elés fog egy shelve-elt P4 changelistet, és létrehozza a
neki megfelelő git commitot a refs/remotes/p4-unshelved/<changelist>
branchen.

A git commit a jelenlegi origin revízióhoz (alapértelmezetten HEAD-hez)
képest jön létre.  Az origin alapján létrejön egy szülő commit, majd
az unshelve commit ez alapján kerül létrehozásra.

Az origin revízió a „--origin" opcióval változtatható.

Ha a refs/remotes/p4-unshelved-beli célbranch már létezik, a régi
átnevezésre kerül.

----
$ git p4 sync
$ git p4 unshelve 12345
$ git show p4-unshelved/12345
<submit more changes via p4 to the same files>
$ git p4 unshelve 12345
<refuses to unshelve until git is in sync with p4 again>

----

OPTIONS
-------

Általános opciók
~~~~~~~~~~~~~~~~
A clone kivételével minden parancs elfogadja ezeket az opciókat.

--git-dir <dir>::
	Beállítja a `GIT_DIR` környezeti változót.  Lásd: linkgit:git[1].

-v::
--verbose::
	Több folyamatinformációt ad.

Sync opciók
~~~~~~~~~~~
Ezek az opciók használhatók a kezdeti 'clone'-nál, valamint a
későbbi 'sync' műveleteknél is.

--branch <ref>::
	A változtatásokat <ref>-be importálja, refs/remotes/p4/master
	helyett.  Ha a <ref> refs/-szel kezdődik, változatlanul kerül
	felhasználásra.  Egyébként, ha nem p4/-gyel kezdődik, ez az
	előtag hozzáadásra kerül.
+
Alapértelmezés szerint a refs/-szel nem kezdődő <ref>-et egy
remote-tracking branch (a refs/remotes/ alatti) neveként kezeli.
Ez a viselkedés a --import-local opcióval módosítható.
+
Az alapértelmezett <ref> a "master".
+
Ez a példa egy új "p4/proj2" remote-ot importál egy meglévő Git
repository-ba:
+
----
    $ git init
    $ git p4 sync --branch=refs/remotes/p4/proj2 //depot/proj2
----

--detect-branches::
	A branch-detektálási algoritmust használja új útvonalak
	megtalálásához a p4-ben.  Ez lentebb, a „BRANCH DETECTION"
	szakaszban van dokumentálva.

--changesfile <file>::
	Pontosan a 'file'-ban felsorolt p4 change számokat importálja,
	soronként egyet.  Normál esetben a 'git p4' megvizsgálja az
	aktuális p4 repository állapotát, és felismeri az
	importálandó változtatásokat.

--silent::
	Nem ír ki semmilyen folyamatinformációt.

--detect-labels::
	Lekérdezi a p4-től a depot elérési utakhoz tartozó labeleket, és
	tagekként adja hozzá őket a Git-hez. Korlátozottan hasznos, mivel
	csak az új changelistekhez tartozó labeleket importálja. Elavult.

--import-labels::
	Importálja a labeleket a p4-ből a Git-be.

--import-local::
	Alapértelmezés szerint a p4 branchek a 'refs/remotes/p4/'
	alatt tárolódnak, ahol a linkgit:git-branch[1] és más parancsok
	remote-tracking branchként kezelik őket.  Ez az opció ehelyett
	a 'refs/heads/p4/' alá teszi a p4 brancheket.  Vedd figyelembe,
	hogy a jövőbeli sync műveleteknek is meg kell adniuk a
	`--import-local` opciót, hogy megtalálják a p4 brancheket a
	refs/heads alatt.

--max-changes <n>::
	Legfeljebb 'n' változtatást importál, a megadott revíziómegadóban
	szereplő teljes tartomány helyett. Egy tipikus használati mód a
	'@all' revíziómegadóként való használata, majd a
	'--max-changes 1000' használata, hogy csak az utolsó 1000
	revíziót importálja a teljes revíziótörténet helyett.

--changes-block-size <n>::
	A belső blokkméret, amelyet egy olyan revíziómegadó, mint a
	'@all', konkrét change számok listájává alakításakor használ.
	Ahelyett, hogy egyetlen 'p4 changes' hívással keresné meg a
	konverzióhoz szükséges teljes változtatáslistát, egy sor
	'p4 changes -m' hívás történik, amelyek mindegyike a megadott
	méretű változtatásblokkot kéri le. Az alapértelmezett blokkméret
	500, ami általában megfelelő.

--keep-path::
	A fájlnevek p4 depot elérési útról Git-re való leképezése
	alapértelmezés szerint eltávolítja a teljes depot elérési utat.
	Ezzel az opcióval a teljes p4 depot elérési út megmarad a
	Git-ben. Például a '//depot/main/foo/bar.c' elérési út, a
	'//depot/main/'-ból importálva, 'foo/bar.c' lesz. A
	`--keep-path`-tal a Git elérési út ehelyett
	'depot/main/foo/bar.c'.

--use-client-spec::
	Egy client spec-et használ az érdekes fájlok listájának
	megkereséséhez a p4-ben. Lásd a lentebbi „CLIENT SPEC"
	szakaszt.

-/ <path>::
	Kizár bizonyos depot elérési utakat klónozáskor vagy
	sync-eléskor.

Clone opciók
~~~~~~~~~~~~
Ezek az opciók használhatók egy kezdeti 'clone'-nál, a fent leírt
'sync' opciókkal együtt.

--destination <directory>::
	Hova hozza létre a Git repository-t.  Ha nincs megadva, a p4
	depot elérési út utolsó eleme kerül felhasználásra egy új
	könyvtár létrehozásához.

--bare::
	Bare klónozást végez.  Lásd: linkgit:git-clone[1].

Submit opciók
~~~~~~~~~~~~~
Ezek az opciók a 'git p4 submit' viselkedésének módosítására
használhatók.

--origin <commit>::
	Az upstream hely, ahonnan a p4-be submitolandó commitok
	azonosításra kerülnek.  Alapértelmezés szerint ez a `HEAD`-ből
	elérhető legutóbbi p4 commit.

-M::
	Átnevezéseket detektál.  Lásd: linkgit:git-diff[1].  Az
	átnevezések a p4-ben explicit 'move' műveletekkel lesznek
	reprezentálva.  Nincs megfelelő opció a másolatok
	detektálására, de vannak változók mind a move-okhoz, mind a
	másolatokhoz.

--preserve-user::
	Újra-szerzőzi a p4 változtatásokat a p4-be történő submitolás
	előtt.  Ez az opció p4 admin jogosultságokat igényel.

--export-labels::
	Exportálja a tageket a Git-ből p4 labelekként. A Git-ben
	talált tagek a perforce munkakönyvtárra kerülnek alkalmazásra.

-n::
--dry-run::
	Csak azt mutatja meg, mely commitok kerülnének submitolásra a
	p4-be; nem változtatja meg az állapotot sem a Git-ben, sem a
	p4-ben.

--prepare-p4-only::
	Alkalmaz egy commitot a p4 workspace-re, megnyitva, hozzáadva
	és törölve a fájlokat a p4-ben, ahogy egy normál submit
	művelet esetén.  Nem adja ki a végső „p4 submit" parancsot,
	hanem ehelyett egy üzenetet ír ki arról, hogyan lehet manuálisan
	submitolni vagy visszavonni.  Ez az opció mindig az első
	(legrégebbi) commit után áll meg.  A Git tagek nem kerülnek
	exportálásra a p4-be.

--shelve::
	Submitolás helyett egy sor shelve-elt changelistet hoz létre.
	Minden egyes shelve létrehozása után az érintett fájlok
	visszaállításra/törlésre kerülnek.  Ha több commitod is várakozik,
	több shelve jön létre.

--update-shelve CHANGELIST::
	Frissít egy meglévő shelve-elt changelistet ezzel a committal.
	Magában foglalja a --shelve-et. Ismételd meg több shelve-elt
	changelisthez.

--conflict=(ask|skip|quit)::
	Konfliktusok léphetnek fel egy commit p4-re történő alkalmazásakor.
	Ha ez történik, az alapértelmezett viselkedés ("ask") megkérdezi,
	hogy ki kell-e hagyni ezt a commitot és folytatni, vagy ki kell-e
	lépni.  Ez az opció használható a kérdés megkerülésére, ezáltal a
	konfliktusos commitok automatikusan kihagyásra kerülnek, vagy a
	commitok alkalmazásának megszakítására, kérdés nélkül.

--branch <branch>::
	Submitolás után ezt a megnevezett branchet sync-eli az
	alapértelmezett p4/master helyett.  További információért lásd
	a fenti „Sync opciók" szakaszt.

--commit (<sha1>|<sha1>..<sha1>)::
    Csak a megadott commitot vagy commit-tartományt submitolja, az
    aktuális Git branchben lévő teljes változtatáslista helyett.

--disable-rebase::
    Letiltja az automatikus rebase-t azután, hogy minden commit
    sikeresen submitolásra került. A git-p4.disableRebase-zel is
    beállítható.

--disable-p4sync::
    Letiltja a p4/master automatikus sync-elését a Perforce-ból,
    miután a commitok submitolásra kerültek. Magában foglalja a
    --disable-rebase-t. A git-p4.disableP4Sync-cel is beállítható.
    Az origin/master-rel való sync továbbra is megtörténik, ha
    lehetséges.

Hookok a submithoz
------------------

p4-pre-submit
~~~~~~~~~~~~~

A `p4-pre-submit` hook lefut, ha létezik és futtatható.
A hook nem kap paramétereket, és semmit a standard bemenetről. Ha ez
a szkript nem nulla állapottal lép ki, az megakadályozza a
`git-p4 submit` elindítását.
A `--no-verify` parancssori opcióval megkerülhető.

Az egyik felhasználási forgatókönyv unit tesztek futtatása a hookban.

p4-prepare-changelist
~~~~~~~~~~~~~~~~~~~~~

A `p4-prepare-changelist` hook közvetlenül az alapértelmezett
changelist-üzenet előkészítése után, és a szerkesztő elindítása előtt
fut le.
Egy paramétert kap, annak a fájlnak a nevét, amely a changelist
szövegét tartalmazza. Ha a szkript nem nulla állapottal lép ki, az
megszakítja a folyamatot.

A hook célja, hogy a helyén szerkessze az üzenetfájlt, és ezt nem
nyomja el a `--no-verify` opció. Ez a hook akkor is meghívásra kerül,
ha a `--prepare-p4-only` be van állítva.

p4-changelist
~~~~~~~~~~~~~

A `p4-changelist` hook azután fut le, hogy a felhasználó szerkesztette
a changelist-üzenetet. A `--no-verify` opcióval megkerülhető. Egy
paramétert kap, annak a fájlnak a nevét, amely a javasolt changelist
szöveget tartalmazza. Ha nem nulla állapottal lép ki, az megszakítja a
parancsot.

A hook szerkesztheti a changelist fájlt, és felhasználható a szöveg
valamilyen projektszabvány-formátumra való normalizálására. Az
üzenetfájl megvizsgálása után a Submit elutasítására is használható.

p4-post-changelist
~~~~~~~~~~~~~~~~~~

A `p4-post-changelist` hook azután hívódik meg, hogy a submit
sikeresen megtörtént a P4-ben. Nem kap paramétereket, és elsősorban
értesítésre szolgál, a git p4 submit művelet kimenetelére nincs
hatással.



Rebase opciók
~~~~~~~~~~~~~
Ezek az opciók a 'git p4 rebase' viselkedésének módosítására
használhatók.

--import-labels::
	Importálja a p4 labeleket.

Unshelve opciók
~~~~~~~~~~~~~~~

--origin::
    Beállítja azt a git refspecet, amelyhez a shelve-elt P4
    changelistet hasonlítja.
    Alapértelmezett értéke a p4/master.

DEPOT PATH SYNTAX
-----------------
A 'git p4 sync' és a 'git p4 clone' p4 depot elérési út argumentuma
egy vagy több szóközzel elválasztott p4 depot elérési út lehet, a
végén egy opcionális p4 revíziómegadóval:

"//depot/my/project"::
    Egyetlen commitot importál az adott fa alatti '#head' változtatás
    összes fájljával.

"//depot/my/project@all"::
    Egy commitot importál az adott depot elérési út történetének
    minden egyes változtatásához.

"//depot/my/project@1,6"::
    Csak az 1-től 6-ig terjedő változtatásokat importálja.

"//depot/proj1@all //depot/proj2@all"::
    Az összes változtatást importálja mindkét megnevezett depot
    elérési útról egyetlen repository-ba.  Csak az ezen könyvtárak
    alatti fájlok kerülnek be.  A Git-ben nincs külön alkönyvtár a
    "proj1" és a "proj2" számára.  Több depot elérési út megadásakor
    a `--destination` opciót kell használnod.  A revíziómegadót
    minden depot elérési úton azonosan kell megadni.  Ha a depot
    elérési utakon azonos nevű fájlok vannak, a fájl legutóbb
    frissített verzióját tartalmazó elérési út jelenik meg a Git-ben.

Lásd a 'p4 help revisions' parancsot a p4 revíziómegadók teljes
szintaxisáért.


CLIENT SPEC
-----------
A p4 client specifikációt a 'p4 client' parancs tartja karban, és
egyéb mezők mellett tartalmaz egy View-t, amely megadja, hogyan van
leképezve a depot a kliens repository-ba.  A 'clone' és 'sync'
parancsok figyelembe vehetik a client spec-et, ha meg van adva a
`--use-client-spec` opció, vagy ha a useClientSpec változó igazra van
állítva.  A 'git p4 clone' után a useClientSpec változó automatikusan
beállításra kerül a repository konfigurációs fájljában.  Ez lehetővé
teszi, hogy a jövőbeli 'git p4 submit' parancsok megfelelően
működjenek; a submit parancs kizárólag ezt a változót nézi, és nincs
hozzá parancssori opció.

A p4 view teljes szintaxisa a 'p4 help views' parancsban van
dokumentálva.  A 'git p4' a view szintaxisnak csak egy részhalmazát
ismeri.  Érti a többsoros leképezéseket, a '+'-szal jelölt
overlay-eket, a '-'-szal jelölt kizárásokat, és a whitespace körüli
dupla idézőjeleket.  A lehetséges helyettesítő karakterek közül a
'git p4' csak a '...'-ot kezeli, és csak akkor, ha az az elérési út
végén van.  A 'git p4' panaszkodni fog, ha nem kezelt helyettesítő
karakterrel találkozik.

Hibák vannak az átfedő leképezések implementációjában.  Ha több depot
elérési út overlay-eken keresztül ugyanarra a helyre képződik le a
repository-ban, a 'git p4' rossz elérési utat is választhat.  Ezt
nehéz megoldani anélkül, hogy egy client spec-et kifejezetten a
'git p4' számára dedikálnánk.

A kliens neve többféleképpen megadható a 'git p4' számára.  A
'git-p4.client' változó elsőbbséget élvez, ha létezik.  Egyébként a
kliens meghatározásának szokásos p4-mechanizmusai kerülnek
felhasználásra: a `P4CLIENT` környezeti változó, a `P4CONFIG` által
hivatkozott fájl, vagy a helyi hostnév.


BRANCH DETECTION
----------------
A P4-nek nincs ugyanolyan branch-fogalma, mint a Gitnek.  Ehelyett a
p4 könyvtárfaként szervezi a tartalmát, ahol megállapodás szerint a
különböző logikai branchek a fa különböző helyein vannak.  A
'p4 branch' parancs a fa különböző területei közötti leképezések
karbantartására, valamint a kapcsolódó tartalom jelzésére szolgál.  A
'git p4' ezeket a leképezéseket használhatja a branch-kapcsolatok
meghatározásához.

Ha van egy olyan repository-d, ahol az érdekes branchek mind egyetlen
depot elérési út alkönyvtáraiként léteznek, klónozáskor vagy
sync-eléskor használhatod a `--detect-branches` opciót, hogy a
'git p4' automatikusan megtalálja az alkönyvtárakat a p4-ben, és
brancheket generáljon belőlük a Git-ben.

Például, ha a P4 repository felépítése a következő:

----
//depot/main/...
//depot/branch1/...
----

És a "p4 branch -o branch1" egy ehhez hasonló View sort mutat:

----
//depot/main/... //depot/branch1/...
----

Akkor ez a 'git p4 clone' parancs:

----
git p4 clone --detect-branches //depot@all
----

egy külön branchet hoz létre a 'refs/remotes/p4/'-ben a //depot/main
számára, 'master' néven, és egy másikat a //depot/branch1 számára,
'depot/branch1' néven.

Azonban nem szükséges brancheket létrehozni a p4-ben ahhoz, hogy
branchekként lehessen őket használni.  Mivel nehéz automatikusan
kikövetkeztetni a branch-kapcsolatokat, a 'git-p4.branchList' Git
konfigurációs beállítás használható a branch-kapcsolatok explicit
azonosítására.  Ez "forrás:cél" párok listája, hasonlóan egy egyszerű
p4 branch-specifikációhoz, ahol a "forrás" és a "cél" a p4 repository
elérésiút-elemei.  A fenti példa a p4 branch meglétére támaszkodott.
P4 branchek nélkül ugyanez az eredmény a következővel érhető el:

----
git init depot
cd depot
git config git-p4.branchList main:branch1
git p4 clone --detect-branches //depot@all .
----


PERFORMANCE
-----------
A 'git p4' által használt fast-import mechanizmus a 'git p4 sync'
minden egyes meghívásakor létrehoz egy pack fájlt.  Normál esetben a
Git szemétgyűjtő tömörítés (linkgit:git-gc[1]) automatikusan kevesebb
pack fájlra tömöríti ezeket, de a 'git repack -adf' explicit meghívása
javíthatja a teljesítményt.


CONFIGURATION VARIABLES
-----------------------
A következő config beállítások használhatók a 'git p4' viselkedésének
módosítására.  Mindegyikük a 'git-p4' szekcióban van.

Általános változók
~~~~~~~~~~~~~~~~~~
git-p4.user::
	Az összes p4 parancshoz opcióként megadott felhasználó, a
	'-u <user>' formában.
	Helyette a `P4USER` környezeti változó is használható.

git-p4.password::
	Az összes p4 parancshoz opcióként megadott jelszó, a
	'-P <password>' formában.
	Helyette a `P4PASS` környezeti változó is használható.

git-p4.port::
	Az összes p4 parancshoz opcióként megadott port, a
	'-p <port>' formában.
	Helyette a `P4PORT` környezeti változó is használható.

git-p4.host::
	Az összes p4 parancshoz opcióként megadott host, a
	'-h <host>' formában.
	Helyette a `P4HOST` környezeti változó is használható.

git-p4.client::
	Az összes p4 parancshoz opcióként megadott kliens, a
	'-c <client>' formában, a client spec-et is beleértve.

git-p4.retries::
	Megadja, hányszor próbálkozzon újra egy p4 paranccsal
	(nevezetesen a 'p4 sync'-kel), ha a hálózat túllépi az
	időkorlátot. Az alapértelmezett érték 3.
	Állítsd az értéket 0-ra az újrapróbálkozások letiltásához, vagy
	ha a p4 verziód nem támogatja az újrapróbálkozást (2012.2 előtti).

Clone és sync változók
~~~~~~~~~~~~~~~~~~~~~~
git-p4.syncFromOrigin::
	Mivel a commitok más Git repository-kból való importálása sokkal
	gyorsabb, mint a p4-ből, létezik egy mechanizmus a p4
	változtatások előbb Git remote-okban való megkeresésére.  Ha
	brancheket találunk a 'refs/remote/origin/p4' alatt, ezek
	lekérésre és felhasználásra kerülnek a p4-ből való sync-elés
	során.  Ez a változó 'false'-ra állítható e viselkedés
	letiltásához.

git-p4.branchUser::
	A branch-detektálás egyik fázisa a p4 branchek megvizsgálását
	jelenti, hogy megtalálja az importálandó újakat.
	Alapértelmezés szerint az összes branch megvizsgálásra kerül.
	Ez az opció a keresést a változóban megnevezett egyetlen
	felhasználó tulajdonában lévőkre korlátozza.

git-p4.branchList::
	Az importálandó branchek listája, ha a branch-detektálás
	engedélyezve van.  Minden bejegyzésnek egy kettősponttal (:)
	elválasztott branchnév-párnak kell lennie.  Ez a példa
	kijelenti, hogy mind a branchA, mind a branchB a main-ből jött
	létre:
+
-------------
git config       git-p4.branchList main:branchA
git config --add git-p4.branchList main:branchB
-------------

git-p4.ignoredP4Labels::
	A figyelmen kívül hagyandó p4 labelek listája. Ez automatikusan
	épül fel, ahogy nem importálható labelek kerülnek felismerésre.

git-p4.importLabels::
	Importálja a labeleket a p4-ből a git-be, a --import-labels
	szerint.

git-p4.labelImportRegexp::
	Csak az ennek a reguláris kifejezésnek megfelelő p4 labelek
	kerülnek importálásra. Az alapértelmezett érték
	'[a-zA-Z0-9_\-.]+$'.

git-p4.useClientSpec::
	Megadja, hogy a p4 client spec-et kell-e használni az érdekes
	p4 depot elérési utak azonosításához.  Ez egyenértékű a
	`--use-client-spec` opció megadásával.  Lásd a fenti „CLIENT
	SPEC" szakaszt.  Ez a változó egy boolean, nem egy p4 kliens
	neve.

git-p4.pathEncoding::
	A Perforce megtartja az elérési út kódolását úgy, ahogy azt a
	forrás OS megadta. A Git UTF-8-ban kódolt elérési utakat vár el.
	Ezzel a konfigurációval megmondható a git-p4-nek, milyen
	kódolást használt a Perforce az elérési utakhoz. Ez a kódolás
	kerül felhasználásra az elérési utak UTF-8-ra való átkódolásához.
	Például a Perforce Windowson gyakran a "cp1252"-t használja
	elérésiút-nevek kódolására. Ha ez az opció át van adva egy p4
	clone kérésbe, megőrződik az így létrejövő új git repóban.

git-p4.metadataDecodingStrategy::
	A Perforce a changelist-leírások és a felhasználók teljes
	nevének kódolását úgy tartja meg, ahogy azt a kliens egy adott
	OS-en tárolta. A p4v kliens az OS-helyi kódolást használja, így
	különböző felhasználók végül különböző kódolásokban tárolhatnak
	különböző changelist-leírásokat vagy felhasználói teljes neveket,
	ugyanabban a depotban.
	A Git megtűri a következetlen/hibás kódolásokat a commit-üzenetekben
	és a szerzőnevekben, de elvárja, hogy utf-8-ban legyenek megadva.
	A git-p4 három különböző dekódolási stratégiát tud használni a
	Perforce-beli kódolási bizonytalanság kezelésére: a 'passthrough'
	egyszerűen áteresztgeti az eredeti bájtokat a Perforce-ból a
	git-be, ami használható, de hibásan kódolt adatot hoz létre, ha a
	Perforce-adat utf-8-tól eltérő kódolású. A 'strict' azt várja el,
	hogy a Perforce-adat utf-8-ban legyen kódolva, és sikertelen az
	importálás, ha ez nem így van. A 'fallback' megpróbálja utf-8-ként
	értelmezni az adatot, egyébként pedig egy másodlagos kódolásra —
	alapértelmezés szerint a gyakori windowsos 'cp-1252'-re — esik
	vissza, a felső tartományba eső bájtokat escape-elve, ha a
	dekódolás a fallback kódolással is meghiúsul.
	Python2 alatt az alapértelmezett stratégia történelmi okokból a
	'passthrough', python3 alatt pedig az alapértelmezés a 'fallback'.
	Ha a 'strict' van kiválasztva és a dekódolás meghiúsul, a
	hibaüzenet felajánlja ennek a konfigurációs paraméternek a
	megváltoztatását megoldásként. Ha ez az opció át van adva egy p4
	clone kérésbe, megőrződik az így létrejövő új git repóban.

git-p4.metadataFallbackEncoding::
	Megadja a fallback kódolást, amelyet a Perforce szerzőnevek és
	changelist-leírások dekódolásához kell használni a 'fallback'
	stratégiával (lásd: git-p4.metadataDecodingStrategy). A fallback
	kódolás csak akkor kerül felhasználásra, ha az utf-8-ként való
	dekódolás meghiúsul. Ennek az opciónak az alapértelmezése
	cp1252, egy gyakori windowsos kódolás. Ha ez az opció át van adva
	egy p4 clone kérésbe, megőrződik az így létrejövő új git repóban.

git-p4.largeFileSystem::
	Megadja a nagy (bináris) fájlokhoz használt rendszert. Vedd
	figyelembe, hogy a nagyfájl-rendszerek nem támogatják a
	'git p4 submit' parancsot. Jelenleg csak a Git LFS van
	implementálva (bővebb információért lásd:
	https://git-lfs.github.com/). Töltsd le és telepítsd a Git LFS
	parancssori kiterjesztést ennek az opciónak a használatához, és
	konfiguráld így:
+
-------------
git config       git-p4.largeFileSystem GitLFS
-------------

git-p4.largeFileExtensions::
	A listában szereplő fájlkiterjesztésnek megfelelő összes fájl a
	nagyfájl-rendszerrel kerül feldolgozásra. Ne tedd a
	kiterjesztések elé '.'-ot.

git-p4.largeFileThreshold::
	Minden olyan fájl, amelynek tömörítetlen mérete meghaladja a
	küszöbértéket, a nagyfájl-rendszerrel kerül feldolgozásra.
	Alapértelmezés szerint a küszöbérték bájtban van megadva. Add
	hozzá a k, m vagy g utótagot a mértékegység módosításához.

git-p4.largeFileCompressedThreshold::
	Minden olyan fájl, amelynek tömörített mérete meghaladja a
	küszöbértéket, a nagyfájl-rendszerrel kerül feldolgozásra. Ez az
	opció lelassíthatja a klónozási/sync-elési folyamatot.
	Alapértelmezés szerint a küszöbérték bájtban van megadva. Add
	hozzá a k, m vagy g utótagot a mértékegység módosításához.

git-p4.largeFilePush::
	Boolean változó, amely meghatározza, hogy a nagy fájlok
	automatikusan pusholásra kerülnek-e egy szerverre.

git-p4.keepEmptyCommits::
	Egy olyan changelist, amely csak kizárt fájlokat tartalmaz, üres
	commitként kerül importálásra, ha ez a boolean opció true-ra
	van állítva.

git-p4.mapUser::
	Egy P4 felhasználót egy Git-beli névhez és e-mail címhez
	rendel. Használj egy, a következő formátumú sztringet egy
	leképezés létrehozásához:
+
-------------
git config --add git-p4.mapUser "p4user = First Last <mail@address.com>"
-------------
+
Egy leképezés felülbírál minden, a P4-ből származó
felhasználói információt. Több P4 felhasználóhoz is definiálhatók
leképezések.

Submit változók
~~~~~~~~~~~~~~~
git-p4.detectRenames::
	Átnevezéseket detektál.  Lásd: linkgit:git-diff[1].  Ez lehet true,
	false, vagy egy, a 'git diff -M' által elvárt pontszám.

git-p4.detectCopies::
	Másolatokat detektál.  Lásd: linkgit:git-diff[1].  Ez lehet true,
	false, vagy egy, a 'git diff -C' által elvárt pontszám.

git-p4.detectCopiesHarder::
	Erősebben detektálja a másolatokat.  Lásd: linkgit:git-diff[1].
	Egy boolean érték.

git-p4.preserveUser::
	Submitoláskor újra-szerzőzi a változtatásokat, hogy a Git
	szerzőjét tükrözzék, függetlenül attól, ki hívta meg a
	'git p4 submit'-et.

git-p4.allowMissingP4Users::
	Ha a 'preserveUser' true, a 'git p4' normál esetben leáll, ha
	nem talál szerzőt a p4 felhasználói leképezésben.  Ez a
	beállítás ettől függetlenül submitolja a változtatást.

git-p4.skipSubmitEdit::
	A submit folyamat minden egyes p4 változtatás submitolása előtt
	meghívja a szerkesztőt.  Ha ez a beállítás true, a szerkesztési
	lépés kimarad.

git-p4.skipSubmitEditCheck::
	A p4 változtatás-üzenet szerkesztése után a 'git p4'
	meggyőződik arról, hogy a leírás valóban megváltozott, a fájl
	módosítási idejét megvizsgálva.  Ez az opció kikapcsolja ezt a
	tesztet.

git-p4.allowSubmit::
	Alapértelmezés szerint bármely branch használható forrásként
	egy 'git p4 submit' művelethez.  Ez a konfigurációs változó, ha
	be van állítva, csak a megnevezett brancheket engedélyezi
	submit-forrásként.  A branch neveknek rövid neveknek kell
	lenniük (nem "refs/heads/"), és vesszővel (",") kell
	elválasztani őket, szóköz nélkül.

git-p4.skipUserNameCheck::
	Ha a 'git p4 submit'-et futtató felhasználó nem létezik a p4
	felhasználói leképezésben, a 'git p4' kilép.  Ez az opció
	használható a submitolás kikényszerítésére, ettől függetlenül.

git-p4.attemptRCSCleanup::
	Ha engedélyezve van, a 'git p4 submit' megpróbálja megtisztítani
	az RCS kulcsszavakat ($Header$ stb.). Ezek egyébként
	merge-konfliktusokat okoznának, és megakadályoznák a submitolás
	folytatását. Ezt az opciót jelenleg kísérletinek kell tekinteni.

git-p4.exportLabels::
	Git tageket exportál p4 labelekként, a --export-labels szerint.

git-p4.labelExportRegexp::
	Csak az ennek a reguláris kifejezésnek megfelelő p4 labelek
	kerülnek exportálásra. Az alapértelmezett érték
	'[a-zA-Z0-9_\-.]+$'.

git-p4.conflict::
	Megadja a submit viselkedését, ha konfliktus adódik a p4-gyel,
	a --conflict szerint.  Az alapértelmezett viselkedés 'ask'.

git-p4.disableRebase::
    Ne rebase-elje a fát a p4/master fölé egy submit után.

git-p4.disableP4Sync::
    Ne sync-elje a p4/master-t a Perforce-szal egy submit után.
    Magában foglalja a git-p4.disableRebase-t.

IMPLEMENTATION DETAILS
----------------------
* A p4-ből származó changesetek Git fast-import segítségével kerülnek
  importálásra.
* A klónozás vagy sync-elés nem igényel p4 klienst; a fájltartalmak
  a 'p4 print' segítségével kerülnek begyűjtésre.
* A submitoláshoz p4 kliens szükséges, amely nincs ugyanazon a helyen,
  mint a Git repository.  A patchek egyenként kerülnek alkalmazásra
  erre a p4 kliensre, és onnan kerülnek submitolásra.
* Minden, a 'git p4' által importált commit naplóüzenetének végén
  található egy sor, amely jelzi a p4 depot elérési útját és a
  változtatás számát.  Ezt a sort a későbbi 'git p4 sync' műveletek
  arra használják, hogy megállapítsák, mely p4 változtatások újak.

GIT
---
A linkgit:git[1] csomag része
