git-show(1)
===========

NAME
----
git-show - Objektumok különböző típusait jeleníti meg


SYNOPSIS
--------
[synopsis]
git show [<options>] [<object>...]

DESCRIPTION
-----------
Megjelenít egy vagy több objektumot (blobokat, fákat, tageket és
commitokat).

Commitok esetén megjeleníti a napló-üzenetet és a szöveges diffet.
A merge-commitot is megjeleníti egy speciális, a
`git diff-tree --cc` által előállított formátumban.

Tagek esetén megjeleníti a tag-üzenetet és a hivatkozott
objektumokat.

Fák esetén megjeleníti a neveket (egyenértékű a `--name-only`-val
hívott `git ls-tree`-vel).

Sima blobok esetén megjeleníti a sima tartalmat.

Néhány, a `git log` parancs által ismert opció felhasználható a
commit által bevezetett változtatások megjelenítésének
vezérlésére.

Ez a man page csak a leggyakrabban használt opciókat írja le.


OPTIONS
-------
`<object>...`::
	A megjelenítendő objektumok nevei (alapértelmezés: `HEAD`).
	Az objektumnevek megadásának teljesebb listájáért lásd a
	linkgit:gitrevisions[7] "SPECIFYING REVISIONS" szakaszát.

include::pretty-options.adoc[]


include::pretty-formats.adoc[]


DIFF FORMATTING
---------------
Az alábbi opciók felhasználhatók annak megváltoztatására, ahogy a
`git show` előállítja a diff-kimenetet.

:git-log: 1
:diff-merges-default: `dense-combined`
include::diff-options.adoc[]

include::diff-generate-patch.adoc[]


EXAMPLES
--------

`git show v1.0.0`::
	Megjeleníti a `v1.0.0` taget, valamint azt az objektumot,
	amelyre a tag mutat.

`git show v1.0.0^{tree}`::
	Megjeleníti a `v1.0.0` tag által mutatott fát.

`git show -s --format=%s v1.0.0^{commit}`::
	Megjeleníti a `v1.0.0` tag által mutatott commit tárgyát.

`git show next~10:Documentation/README`::
	Megjeleníti a `Documentation/README` fájl tartalmát, ahogy az
	a `next` branch 10. utolsó commitjában aktuális volt.

`git show master:Makefile master:t/Makefile`::
	Összefűzi az említett Makefile-ok tartalmát a `master` branch
	head-jében.

DISCUSSION
----------

include::i18n.adoc[]

GIT
---
A linkgit:git[1] csomag része
