git-credential-store(1)
=======================

NAME
----
git-credential-store - Helper hitelesítő adatok lemezen történő tárolásához

SYNOPSIS
--------
-------------------
git config credential.helper 'store [<options>]'
-------------------

DESCRIPTION
-----------

NOTE: Ennek a helpernek a használatával a jelszavaid titkosítatlanul
kerülnek tárolásra a lemezen, kizárólag a fájlrendszer jogosultságai
által védve. Ha ez nem elfogadható biztonsági kompromisszum, próbáld ki
a linkgit:git-credential-cache[1] parancsot, vagy keress egy olyan
helpert, amely az operációs rendszered által biztosított biztonságos
tárolóval integrálódik.

Ez a parancs korlátlan ideig tárolja a hitelesítő adatokat a lemezen a
jövőbeli Git programok számára.

Valószínűleg nem akarod ezt a parancsot közvetlenül meghívni; a git más
részei használják credential helperként. Lásd a linkgit:gitcredentials[7]
leírást, vagy a lenti `EXAMPLES` szakaszt.

OPTIONS
-------

--file=<path>::

	A `<path>` használata a hitelesítő adatok kereséséhez és tárolásához.
	A fájl jogosultságai úgy lesznek beállítva, hogy megakadályozzák a
	rendszer más felhasználóit annak olvasásában, de a fájl nem lesz
	titkosítva vagy más módon védve. Ha nincs megadva, a hitelesítő
	adatok keresése a `~/.git-credentials` és a
	`$XDG_CONFIG_HOME/git/credentials` fájlokban történik, és a
	hitelesítő adatok a `~/.git-credentials` fájlba íródnak, ha az
	létezik, vagy a `$XDG_CONFIG_HOME/git/credentials` fájlba, ha az
	létezik, de az előbbi nem. Lásd még: <<FILES>>.

[[FILES]]
FILES
-----

Ha nincs kifejezetten megadva a `--file` opcióval, két fájlban keres
hitelesítő adatokat a git-credential-store, precedencia szerinti
sorrendben:

~/.git-credentials::
	Felhasználóspecifikus hitelesítő adatokat tartalmazó fájl.

$XDG_CONFIG_HOME/git/credentials::
	Második, felhasználóspecifikus hitelesítő adatokat tartalmazó fájl.
	Ha a '$XDG_CONFIG_HOME' nincs beállítva vagy üres, a
	`$HOME/.config/git/credentials` kerül használatra. Az ebben a
	fájlban tárolt hitelesítő adatok nem kerülnek felhasználásra, ha a
	`~/.git-credentials` is tartalmaz egyező hitelesítő adatot. Célszerű
	nem létrehozni ezt a fájlt, ha időnként olyan régebbi Git-verziókat
	is használsz, amelyek nem támogatják azt.

A hitelesítő adatok kereséséhez a fájlok a fenti sorrendben kerülnek
beolvasásra, és az elsőként megtalált egyező hitelesítő adat élvez
elsőbbséget a listán lejjebb található fájlokban talált hitelesítő
adatokkal szemben.

A hitelesítő adatok tárolása alapértelmezetten az első létező fájlba
ír a listából. Ha egyik fájl sem létezik, a `~/.git-credentials` jön
létre, és abba történik az írás.

Hitelesítő adatok törlésekor az egyező hitelesítő adatok minden
fájlból törlődnek.

EXAMPLES
--------

Ennek a helpernek az a célja, hogy csökkentse azoknak az eseteknek a
számát, amikor be kell gépelned a felhasználóneved vagy jelszavad.
Például:

------------------------------------------
$ git config credential.helper store
$ git push http://example.com/repo.git
Username: <type your username>
Password: <type your password>

[several days later]
$ git push http://example.com/repo.git
[your credentials are used automatically]
------------------------------------------

TÁROLÁSI FORMÁTUM
-----------------

A `.git-credentials` fájl egyszerű szövegként (plaintext) van tárolva.
Minden hitelesítő adat a saját sorában van tárolva, URL formájában,
így:

------------------------------
https://user:pass@example.com
------------------------------

A fájlban semmilyen más típusú sor (pl. üres sorok vagy komment sorok)
nem megengedett, még ha némelyiket némán figyelmen kívül is hagyja.
Ne tekintsd meg és ne szerkeszd a fájlt szövegszerkesztőkkel.

Amikor a Git-nek egy adott URL-kontextushoz hitelesítésre van
szüksége, a credential-store mintaként kezeli ezt a kontextust, és
összeveti a hitelesítő adatok fájljának minden egyes bejegyzésével.
Ha a protokoll, a hosztnév és a felhasználónév (ha már van ilyenünk)
egyezik, akkor a jelszó visszaadásra kerül a Gitnek. További
információért lásd a konfiguráció tárgyalását a
linkgit:gitcredentials[7] leírásban.

GIT
---
A linkgit:git[1] csomag része
