git-whatchanged(1)
==================

NAME
----
git-whatchanged - Megjeleníti a naplókat az egyes commitok által bevezetett különbségekkel


SYNOPSIS
--------
[synopsis]
git whatchanged <option>...

WARNING
-------
A `git whatchanged` elavulttá vált, és eltávolításra van ütemezve a
Git egy jövőbeli verziójában, mivel csupán egy eltérő
alapértelmezésekkel rendelkező `git log`.

DESCRIPTION
-----------

Megjeleníti a commit-naplókat és az egyes commitok által bevezetett
diff-kimenetet.

Az új felhasználóknak inkább a linkgit:git-log[1] használatát
javasoljuk. A `whatchanged` parancs lényegében ugyanaz, mint a
linkgit:git-log[1], de alapértelmezés szerint a nyers formátumú
diff-kimenetet mutatja, és kihagyja a merge-eket:

----
git log --raw --no-merges
----

A parancsot elsősorban történeti okokból tartjuk meg; sok olyan
ember ujjai, akik jóval a `git log` feltalálása előtt tanulták meg a
Gitet a Linux kernel levelezőlistájának olvasásával, be vannak
gyakorolva a begépelésére.


Példák
------
`git whatchanged -p v2.6.12.. include/scsi drivers/scsi`::

	Patchekként megjeleníti azokat a commitokat a 'v2.6.12' verzió
	óta, amelyek megváltoztattak bármilyen fájlt az include/scsi
	vagy a drivers/scsi alkönyvtárakban

`git whatchanged --since="2 weeks ago" -- gitk`::

	Megjeleníti a 'gitk' fájl elmúlt két hétben történt
	változtatásait. A "--" szükséges, hogy elkerüld az összetévesztést
	a 'gitk' nevű *branch*-csel

GIT
---
A linkgit:git[1] csomag része
