git-show-branch(1)
==================

NAME
----
git-show-branch - Branchek és commitjaik megjelenítése

SYNOPSIS
--------
[verse]
'git show-branch' [-a | --all] [-r | --remotes] [--topo-order | --date-order]
		[--current] [--color[=<when>] | --no-color] [--sparse]
		[--more=<n> | --list | --independent | --merge-base]
		[--no-name | --sha1-name] [--topics]
		[(<rev> | <glob>)...]
'git show-branch' (-g | --reflog)[=<n>[,<base>]] [--list] [<ref>]

DESCRIPTION
-----------

Félig vizuálisan megjeleníti a commit-leszármazási gráfot a <rev>-ekkel
vagy <glob>-okkal megnevezett commitoktól (vagy a refs/heads és/vagy a
refs/tags alatti összes reftől) kezdve.

Egyszerre nem tud 26-nál több branchet és commitot megjeleníteni.

A `showbranch.default` többértékű konfigurációs tételeket használja, ha
nincs <rev> vagy <glob> megadva a parancssorban.


OPTIONS
-------
<rev>::
	Tetszőleges kiterjesztett SHA-1 kifejezés (lásd linkgit:gitrevisions[7]),
	amely jellemzően egy branch fejét vagy egy taget nevez meg.

<glob>::
	Egy glob minta, amely a refs/ alatti branch- vagy tagnevekre
	illeszkedik.  Például, ha sok topic branched van a
	refs/heads/topic alatt, a `topic/*` megadása
	mindet megjelenítené.

-r::
--remotes::
	A remote-tracking branchek megjelenítése.

-a::
--all::
	A remote-tracking branchek és a helyi branchek megjelenítése is.

--current::
	Ezzel az opcióval a parancs a jelenlegi branchet is felveszi a
	megjelenítendő revek listájába, amikor az nincs megadva a
	parancssorban.

--topo-order::
        Alapból a branchek és commitjaik fordított időrendben jelennek
        meg.  Ez az opció topologikus sorrendben jeleníti meg őket (azaz
        a leszármazott commitok a szüleik előtt jelennek meg).

--date-order::
	Ez az opció hasonló a `--topo-order`-hoz abban az értelemben, hogy
	egyetlen szülő sem kerül az összes gyermeke elé, de egyébként a
	commitok a commit-dátumuk szerint vannak rendezve.

--sparse::
	Alapból a kimenet kihagyja azokat a merge-eket, amelyek csak egy
	megjelenített csúcsból érhetők el.  Ez az opció láthatóvá teszi
	őket.

--more=<n>::
	A parancs általában leállítja a kimenetet, amikor megjeleníti azt a
	commitot, amely az összes branch közös őse.  Ez a kapcsoló azt
	mondja a parancsnak, hogy menjen <n> további közös committal azon
	túl.  Ha az <n> negatív, csak a megadott <ref>-eket jeleníti meg, a
	commit-leszármazási fa megjelenítése nélkül.

--list::
	A `--more=-1` szinonimája

--merge-base::
	A commitlista megjelenítése helyett meghatározza a megadott
	commitok lehetséges merge-alapjait. Minden merge-alap benne lesz az
	összes megadott commitban. Ez eltér attól, ahogy a
	linkgit:git-merge-base[1] kezeli a három vagy több commit esetét.

--independent::
	A megadott <ref>-ek közül csak azokat jeleníti meg, amelyek egyetlen
	másik <ref>-ből sem érhetők el.

--no-name::
	Ne jelenítsen meg elnevező sztringeket az egyes commitokhoz.

--sha1-name::
	A commitok elnevezése helyett azzal az útvonallal, amellyel a
	fejektől elérhetők (pl. "master~2" a "master" nagyszülőjének
	jelölésére), az objektumnevük egyedi előtagjával nevezi el őket.

--topics::
	Csak azokat a commitokat jeleníti meg, amelyek NEM az elsőként
	megadott branchen vannak.  Ez segít a topic branchek követésében
	azzal, hogy elrejt minden olyan commitot, amely már a fejlesztés fő
	vonalában van.  A "git show-branch --topics master topic1 topic2"
	megadásakor ez a "git rev-list {caret}master topic1 topic2" által
	adott revíziókat jeleníti meg

-g::
--reflog[=<n>[,<base>]] [<ref>]::
	A megadott ref <n> legutóbbi ref-log bejegyzését jeleníti meg.  Ha
	a <base> meg van adva, <n> bejegyzést visszafelé attól a
	bejegyzéstől.  A <base> megadható darabszámként vagy dátumként.
	Ha nincs explicit <ref> paraméter megadva, az alapértelmezés a
	jelenlegi branch (vagy a `HEAD`, ha leválasztott).

--color[=<when>]::
	Az egyes commitok állapotjelének (ezek egyike: `*` `!` `+` `-`)
	színezése annak megfelelően, hogy melyik branchen van.
	Az érték always (az alapértelmezés), never vagy auto lehet.

--no-color::
	A színes kimenet kikapcsolása akkor is, ha a konfigurációs fájl
	alapértelmezésként a színes kimenetet adja.
	Ugyanaz, mint a `--color=never`.

Vedd figyelembe, hogy a --more, --list, --independent és --merge-base
opciók kölcsönösen kizárják egymást.


OUTPUT
------

N darab <ref> esetén az első N sor a commit-üzenetükből vett egysoros
leírás. Azt a branch-fejet, amelyre a $GIT_DIR/HEAD mutat, egy csillag
`*` karakter előzi meg, míg a többi fejet egy `!` karakter előzi meg.

Ezt az N sort követően minden commithoz egy egysoros napló jelenik meg,
N hellyel behúzva.  Ha egy commit az I-edik branchen van, az I-edik
behúzáskarakter `+` jelet mutat; egyébként szóközt mutat.  A
merge-commitokat `-` jel jelöli.  Minden commit egy rövid nevet mutat,
amely kiterjesztett SHA-1-ként használható az adott commit
megnevezésére.

A következő példa három branchet mutat: "master", "fixes" és
"mhf":

------------------------------------------------
$ git show-branch master fixes mhf
* [master] Add 'git show-branch'.
 ! [fixes] Introduce "reset type" flag to "git reset"
  ! [mhf] Allow "+remote:local" refspec to cause --force when fetching.
---
  + [mhf] Allow "+remote:local" refspec to cause --force when fetching.
  + [mhf~1] Use git-octopus when pulling more than one head.
 +  [fixes] Introduce "reset type" flag to "git reset"
  + [mhf~2] "git fetch --force".
  + [mhf~3] Use .git/remote/origin, not .git/branches/origin.
  + [mhf~4] Make "git pull" and "git fetch" default to origin
  + [mhf~5] Infamous 'octopus merge'
  + [mhf~6] Retire git-parse-remote.
  + [mhf~7] Multi-head fetch.
  + [mhf~8] Start adding the $GIT_DIR/remotes/ support.
*++ [master] Add 'git show-branch'.
------------------------------------------------

Ez a három branch mind egy közös commitból ágazott le, [master],
amelynek commit-üzenete "Add \'git show-branch'".
A "fixes" branch egy commitot ad hozzá: "Introduce "reset type" flag to
"git reset"". Az "mhf" branch sok más commitot ad hozzá.
A jelenlegi branch a "master".


EXAMPLES
--------

Ha az elsődleges branchjeidet közvetlenül a `refs/heads` alatt tartod, a
topic brancheket pedig annak alkönyvtáraiban, a következő a konfigurációs
fájlban segíthet:

------------
[showbranch]
	default = --topo-order
	default = heads/*

------------

Ezzel a `git show-branch` extra paraméterek nélkül csak az elsődleges
brancheket jelenítené meg.  Ezenfelül, ha éppen a topic branchen vagy,
az is megjelenik.

------------
$ git show-branch --reflog="10,1 hour ago" --list master
------------

10 reflog bejegyzést jelenít meg visszafelé a csúcstól, 1 órával ezelőtti
állapot szerint.  A `--list` nélkül a kimenet azt is megmutatja, hogyan
kapcsolódnak ezek a csúcsok topologikusan egymáshoz.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/showbranch.adoc[]

GIT
---
A linkgit:git[1] csomag része
