git-pack-objects(1)
===================

NAME
----
git-pack-objects - Create a packed archive of objects


SYNOPSIS
--------
[verse]
'git pack-objects' [-q | --progress | --all-progress] [--all-progress-implied]
		   [--no-reuse-delta] [--delta-base-offset] [--non-empty]
		   [--local] [--incremental] [--window=<n>] [--depth=<n>]
		   [--revs [--unpacked | --all]] [--keep-pack=<pack-name>]
		   [--cruft] [--cruft-expiration=<time>]
		   [--stdout [--filter=<filter-spec>] | <base-name>]
		   [--shallow] [--keep-true-parents] [--[no-]sparse]
		   [--name-hash-version=<n>] [--path-walk] < <object-list>


DESCRIPTION
-----------
A standard bemenetről beolvassa az objektumok listáját, és vagy egy vagy
több csomagolt archívumot ír a lemezre a megadott base-name-mel, vagy egy csomagolt
archívumot a standard kimenetre.

A csomagolt archívum hatékony módja annak, hogy objektumok egy halmazát
két repository között átvidd, valamint egy hozzáférés-hatékony archiválási
formátum.  Egy csomagolt archívumban egy objektum vagy
tömörített egészként van tárolva, vagy valamely másik objektumtól való különbségként.
Ez utóbbit gyakran deltának nevezik.

A csomagolt archívum formátuma (.pack) úgy van megtervezve, hogy önmagában teljes legyen,
így további információ nélkül kicsomagolható. Ezért
minden objektumnak, amelytől egy delta függ, jelen kell lennie a packen belül.

A packben lévő objektumok gyors, véletlen hozzáféréséhez egy pack index fájl (.idx)
generálódik. Ha mind az indexfájlt (.idx), mind a csomagolt
archívumot (.pack) a $GIT_OBJECT_DIRECTORY (vagy a
$GIT_ALTERNATE_OBJECT_DIRECTORIES bármelyik könyvtára) pack/ alkönyvtárába
helyezed, a Git képes lesz olvasni a pack archívumból.

A 'git unpack-objects' parancs képes beolvasni a csomagolt archívumot, és
a packben lévő objektumokat "egy-fájl egy-objektum"
formátumba kibontani; ezt jellemzően a smart-pull
parancsok végzik, amikor egy packet menet közben hoznak létre a peerjeik hatékony hálózati
továbbításához.


OPTIONS
-------
base-name::
	Fájlpárokba (.pack és .idx) ír, a
	<base-name>-t használva a létrehozott fájl nevének meghatározásához.
	Amikor ez az opció használatban van, egy pár két fájlja a
	<base-name>-<SHA-1>.{pack,idx} fájlokba íródik.  A <SHA-1> egy
	a pack tartalmán alapuló hash, és a parancs standard
	kimenetére íródik.

--stdout::
	A pack tartalmának (ami a .pack fájlba íródott volna) kiírása a
	standard kimenetre.

--revs::
	A revízió-argumentumok beolvasása a standard bemenetről, az
	egyedi objektumnevek helyett.  A revízió-argumentumok ugyanúgy
	vannak feldolgozva, ahogy a 'git rev-list' a `--objects` flaggel
	a `commit` argumentumait használja azon objektumok listájának felépítéséhez, amelyeket
	kiad.  Az eredményül kapott lista objektumai lesznek csomagolva.
	A revíziókon kívül `--not` vagy `--shallow <SHA-1>` sorok is
	elfogadottak.

--unpacked::
	Ez magában foglalja a `--revs` opciót.  A standard bemenetről beolvasott
	revízió-argumentumok listájának feldolgozásakor a
	csomagolt objektumokat azokra korlátozza, amelyek még nincsenek csomagolva.

--all::
	Ez magában foglalja a `--revs` opciót.  A standard bemenetről beolvasott
	revízió-argumentumok listáján felül úgy tesz,
	mintha a `refs/` alatti összes ref meg lenne adva a
	felvételhez.

--include-tag::
	Kéretlen annotált tagek felvétele, ha az általuk
	hivatkozott objektum bekerült az eredményül kapott packfile-ba.  Ez
	hasznos lehet új tagek natív Git-kliensekhez való küldéséhez.

--stdin-packs[=<mode>]::
	A packfile-ok alapneveinek (pl. `pack-1234abcd.pack`)
	beolvasása a standard bemenetről, az objektumnevek vagy revízió-argumentumok
	helyett. Az eredményül kapott pack tartalmazza a
	felvett packekben (amelyek nem `^`-tal kezdődnek) felsorolt összes objektumot, kizárva a
	kizárt packekben (amelyek `^`-tal kezdődnek) felsorolt objektumokat.
+
Amikor a `mode` "follow", a packek ezenfelül `!` előtaggal is elláthatók,
jelezve, hogy ki vannak zárva, de nem feltétlenül zártak az
elérhetőségre nézve.  A felvett packekben lévő objektumokon felül az eredményül kapott
pack további objektumokat is tartalmazhat a következők alapján:
+
--
* Ha bármely pack `!`-tal van megjelölve, akkor az ilyen
  packekből vagy a felvettekből az elérhetőség-zárt packeken kívüli objektumokon keresztül
  elérhető objektumok bekerülnek. Ebben az esetben minden `^` pack elérhetőségre nézve zártként van
  kezelve.
* Egyébként (ha nincsenek `!` packek), a fel nem sorolt packekben lévő objektumok
  bekerülnek, ha ezek az objektumok (1) elérhetők a
  felvett packekből, és (2) nem találhatók egyetlen kizárt packben sem.
--
+
Ez a mód hasznos például a cruft packekben található, egykor nem elérhető
objektumok feltámasztására, hogy olyan packeket generáljunk, amelyek az elérhetőségre nézve
zártak a kizárt packek által meghatározott határig.
+
Nem kompatibilis a `--revs` opcióval, sem a `--revs`-t magukban foglaló opciókkal (mint a
`--all`), kivéve a `--unpacked` opciót, amely kompatibilis.

--cruft::
	A nem elérhető objektumokat egy külön "cruft" packbe csomagolja, amelyet
	egy `.mtimes` fájl megléte jelöl. Jellemzően a `git
	repack --cruft` használja. A hívók megadnak egy pack-névlistát, és
	jelzik, mely packek maradnak a repository-ban, valamint
	mely packek lesznek törölve (a `-` előtaggal jelölve). A
	cruft pack tartalma minden olyan objektum, amely nem szerepel a
	megmaradó packekben, és amely nem lépte túl a türelmi időt (lásd
	`--cruft-expiration` lentebb), vagy amely túllépte a türelmi
	időt, de elérhető egy másik objektumból, amely nem lépte túl.
+
Amikor a bemenet felsorol egy packet, amely az összes elérhető objektumot tartalmazza (és minden
más packet törlésre várónak sorol fel), a megfelelő cruft pack tartalmazza
az összes nem elérhető objektumot (amelynek mtime-ja újabb a
`--cruft-expiration`-nél), valamint minden olyan nem elérhető objektumot, amelynek mtime-ja
régebbi a `--cruft-expiration`-nél, de elérhető egy olyan
nem elérhető objektumból, amelynek mtime-ja újabb a `--cruft-expiration`-nél).
+
Nem kompatibilis a `--unpack-unreachable`, `--keep-unreachable`,
`--pack-loose-unreachable`, `--stdin-packs` opciókkal, valamint bármely más olyan
opcióval, amely magában foglalja a `--revs` opciót.

--cruft-expiration=<approxidate>::
	Ha meg van adva, az objektumok eltávolításra kerülnek a cruft packből, ha
	az mtime-juk régebbi, mint `<approxidate>`. Ha nincs megadva (és
	a `--cruft` meg van adva), akkor egyetlen objektum sem kerül eltávolításra.

--window=<n>::
--depth=<n>::
	Ez a két opció befolyásolja, hogyan tárolódnak a packben lévő
	objektumok delta-tömörítéssel.  Az
	objektumok először belsőleg típus, méret és
	opcionálisan név szerint rendeződnek, és összehasonlításra kerülnek a többi objektummal
	a --window-on belül annak megállapítására, hogy a delta-tömörítés használata megtakarít-e
	helyet.  A --depth korlátozza a maximális delta-mélységet; ha
	túl mélyre állítod, az a kicsomagoló oldalán rontja a
	teljesítményt, mert a delta-adatokat annyiszor kell alkalmazni,
	hogy eljussunk a szükséges objektumhoz.
+
A --window alapértéke 10, a --depth-é 50. A maximális
mélység 4095.

--window-memory=<n>::
	Ez az opció egy további korlátot ad a `--window` mellé;
	az ablakméret dinamikusan lekicsinyül, hogy ne foglaljon el
	több mint '<n>' bájtot a memóriában.  Ez hasznos olyan
	repository-kban, ahol nagy és kis objektumok keverednek, hogy ne fogyjon el
	a memória egy nagy ablakkal, de mégis ki lehessen használni
	a nagy ablakot a kisebb objektumokhoz.  A
	méret "k", "m" vagy "g" utótaggal látható el.
	A `--window-memory=0` korlátlanná teszi a memóriahasználatot.  Az alapértelmezés
	a `pack.windowMemory` konfigurációs változóból származik.

--max-pack-size=<n>::
	Szokatlan esetekben előfordulhat, hogy a fájlrendszereden nem tudsz
	egy bizonyos méretnél nagyobb fájlokat létrehozni, és ezzel az opcióval
	utasíthatod a parancsot, hogy a kimeneti packfile-t
	több független packfile-ra ossza, amelyek egyike sem nagyobb a
	megadott méretnél. A méret "k", "m" vagy "g" utótaggal
	látható el. A megengedett minimális méret 1 MiB-re van korlátozva.
	Az alapértelmezés korlátlan, hacsak a `pack.packSizeLimit` config-változó
	nincs beállítva. Vedd figyelembe, hogy ez az opció
	nagyobb és lassabb repository-t eredményezhet; lásd a tárgyalást a
	`pack.packSizeLimit`-nél.

--honor-pack-keep::
	Ez a flag azt eredményezi, hogy egy olyan objektum, amely már egy
	.keep fájllal rendelkező lokális packben van, figyelmen kívül marad, még akkor is, ha egyébként
	be lett volna csomagolva.

--keep-pack=<pack-name>::
	Ez a flag azt eredményezi, hogy egy olyan objektum, amely már a megadott packben van,
	figyelmen kívül marad, még akkor is, ha egyébként
	be lett volna csomagolva. A `<pack-name>` a pack fájl neve
	vezető könyvtár nélkül (pl. `pack-123.pack`). Az opció
	többször is megadható több pack megtartásához.

--incremental::
	Ez a flag azt eredményezi, hogy egy olyan objektum, amely már egy packben van,
	figyelmen kívül marad, még akkor is, ha egyébként be lett volna csomagolva.

--local::
	Ez a flag azt eredményezi, hogy egy olyan objektum, amely egy alternatív
	objektumtárolóból van kölcsönözve, figyelmen kívül marad, még akkor is, ha egyébként
	be lett volna csomagolva.

--non-empty::
        Csak akkor hozzon létre csomagolt archívumot, ha az legalább
        egy objektumot tartalmazna.

--progress::
	A folyamat állapota alapból a standard hibakimenetre kerül jelentésre,
	amikor az egy terminálhoz van csatolva, hacsak nincs megadva
	a -q. Ez a flag akkor is kikényszeríti a folyamat állapotát, ha
	a standard hibakimenet nem terminálra van irányítva.

--all-progress::
	Amikor a --stdout meg van adva, a folyamatjelentés az
	objektumszámlálási és tömörítési fázisokban jelenik meg,
	de a kiírási fázisban le van tiltva. Ennek az az oka,
	hogy egyes esetekben a kimeneti adatfolyam közvetlenül
	egy másik parancshoz kapcsolódik, amely a beérkező pack-adatok feldolgozása közben
	a saját folyamatállapotát szeretné megjeleníteni.
	Ez a flag olyan, mint a --progress, azzal a különbséggel, hogy a kiírási fázisra is
	kikényszeríti a folyamatjelentést, még akkor is, ha a --stdout van
	használatban.

--all-progress-implied::
	Ez arra szolgál, hogy a --all-progress opciót maga után vonja, valahányszor a folyamatkijelzés
	aktiválódik.  A --all-progress opcióval ellentétben ez a flag önmagában valójában nem
	kényszerít ki semmilyen folyamatkijelzést.

-q::
	Ez a flag azt eredményezi, hogy a parancs nem jelenti a folyamatát
	a standard hibakimenetre.

--no-reuse-delta::
	Amikor csomagolt archívumot hozol létre egy olyan repository-ban, amelyben
	már vannak packek, a parancs újrahasznosítja a meglévő deltákat.
	Ez néha kissé szuboptimális packet eredményez.
	Ez a flag utasítja a parancsot, hogy ne hasznosítsa újra a meglévő deltákat,
	hanem számítsa ki őket a nulláról.

--no-reuse-object::
	Ez a flag utasítja a parancsot, hogy egyáltalán ne hasznosítsa újra a meglévő objektumadatokat,
	beleértve a nem deltifikált objektumokat is, kikényszerítve mindennek az újratömörítését.
	Ez magában foglalja a --no-reuse-delta opciót. Csak abban a homályos esetben hasznos, amikor
	a csomagolt adatokon egy eltérő tömörítési szint teljes körű
	kikényszerítése a cél.

--compression=<n>::
	Megadja a tömörítési szintet az újonnan tömörített adatokhoz a
	generált packben.  Ha nincs megadva, a pack tömörítési szintjét
	először a pack.compression, majd a core.compression határozza meg,
	és -1 az alapértéke, a zlib alapértelmezése, ha egyik sincs beállítva.
	Add hozzá a --no-reuse-object opciót, ha egységes tömörítési
	szintet szeretnél kikényszeríteni minden adaton, forrástól függetlenül.

--sparse::
--no-sparse::
	A "sparse" algoritmus be- és kikapcsolása annak meghatározására, hogy mely objektumok kerüljenek
	a packbe, ha a "--revs" opcióval kombinálják. Ez az algoritmus
	csak azokat a fákat járja be, amelyek olyan útvonalakon jelennek meg, amelyek új objektumokat vezetnek be.
	Ennek jelentős teljesítménybeli előnyei lehetnek egy
	kis változtatás elküldéséhez szükséges pack kiszámításakor. Előfordulhat azonban, hogy extra
	objektumok kerülnek a pack-file-ba, ha a bevont commitok
	bizonyos típusú közvetlen átnevezéseket tartalmaznak. Ha ez az opció nincs megadva,
	alapból a `pack.useSparse` értékét veszi fel, amely true, hacsak
	másképp nincs megadva.

--thin::
	Hozzon létre "thin" packet a küldő és a fogadó közötti
	közös objektumok kihagyásával a hálózati átvitel csökkentése érdekében. Ennek az
	opciónak csak a --stdout opcióval együtt van értelme.
+
Megjegyzés: A thin pack megsérti a csomagolt archívum formátumát azzal, hogy kötelező
objektumokat hagy ki, és így a Git számára használhatatlan, amíg
önmagában teljessé nem teszik. Használd a `git index-pack --fix-thin`
parancsot (lásd linkgit:git-index-pack[1]) az önmagában teljes tulajdonság visszaállításához.

--shallow::
	Optimalizálja azt a packet, amelyet egy shallow
	repository-val rendelkező kliensnek fognak biztosítani.  Ez az opció a --thin opcióval kombinálva kisebb
	packet eredményezhet a sebesség rovására.

--delta-base-offset::
	Egy csomagolt archívum kifejezheti egy delta alap-objektumát
	vagy egy 20 bájtos objektumnévként, vagy a folyamban lévő
	eltolásként, de a Git ősi verziói nem értik az
	utóbbit.  Alapból a 'git pack-objects' csak az
	előbbi formátumot használja a jobb kompatibilitás érdekében.  Ez az opció
	lehetővé teszi a parancs számára, hogy a tömörség kedvéért
	az utóbbi formátumot használja.  Az átlagos delta-lánc
	hosszától függően ez az opció jellemzően 3-5 százalékkal csökkenti az eredményül kapott
	packfile-t.
+
Megjegyzés: A porcelain parancsok, mint a `git gc` (lásd linkgit:git-gc[1]),
`git repack` (lásd linkgit:git-repack[1]), a modern Gitben alapból átadják ezt az opciót,
amikor a repository-d objektumait pack fájlokba teszik.
Ugyanígy a `git bundle` (lásd linkgit:git-bundle[1]) is, amikor bundle-t hoz létre.

--threads=<n>::
	Megadja, hány szálat indítson a legjobb
	delta-egyezések keresésekor.  Ehhez szükséges, hogy a pack-objects
	pthreads támogatással legyen fordítva, egyébként ez az opció figyelmeztetéssel figyelmen kívül marad.
	Ez a csomagolási idő csökkentésére szolgál többprocesszoros gépeken.
	A delta-kereső ablakhoz szükséges memória mennyisége
	azonban a szálak számával szorzódik.
	A 0 megadása azt eredményezi, hogy a Git automatikusan felismeri a CPU-k számát,
	és ennek megfelelően állítja be a szálak számát.

--index-version=<version>[,<offset>]::
	Ez csak a tesztkészlet általi használatra szolgál. Lehetővé teszi
	a generált pack index verziójának kikényszerítését, és
	64 bites indexbejegyzések kikényszerítését a megadott eltolás felett elhelyezkedő objektumokon.

--keep-true-parents::
	Ezzel az opcióval a graftok által elrejtett szülők ennek ellenére
	becsomagolódnak.

--filter=<filter-spec>::
	Bizonyos objektumokat (általában blobokat) kihagy az eredményül kapott
	packfile-ból.  Az érvényes `<filter-spec>` formákért lásd
	linkgit:git-rev-list[1].

--no-filter::
	Kikapcsol minden korábbi `--filter=` argumentumot.

--missing=<missing-action>::
	Egy debug opció a jövőbeli "partial clone" fejlesztés segítésére.
	Ez az opció megadja, hogyan kezelődnek a hiányzó objektumok.
+
A '--missing=error' forma azt kéri, hogy a pack-objects hibával álljon le, ha
hiányzó objektummal találkozik.  Ha a repository egy partial clone, a
hiányzó objektumok fetchelésére kísérlet történik, mielőtt hiányzónak nyilvánítaná őket.
Ez az alapértelmezett művelet.
+
A '--missing=allow-any' forma lehetővé teszi az objektumbejárás folytatását,
ha hiányzó objektummal találkozik.  Nem történik hiányzó objektum fetchelése.
A hiányzó objektumok csendben kimaradnak az eredményekből.
+
A '--missing=allow-promisor' forma olyan, mint az 'allow-any', de csak
a VÁRT promisor hiányzó objektumok esetén engedi folytatni az objektumbejárást.
Nem történik hiányzó objektum fetchelése.  Egy nem várt hiányzó objektum
hibát vált ki.

--exclude-promisor-objects::
	Kihagyja azokat az objektumokat, amelyekről tudott, hogy a promisor remote-ban vannak.  (Ennek az
	opciónak az a célja, hogy csak a helyben létrehozott objektumokon dolgozzon,
	hogy repackeléskor továbbra is fenntartsuk a különbséget a
	helyben létrehozott objektumok [.promisor nélkül] és a
	promisor remote-ból származó objektumok [.promisorral] között.)  Ez a partial clone-nal használatos.

--keep-unreachable::
	A --unpacked= opcióval megnevezett packekben lévő refekből nem elérhető
	objektumok bekerülnek az eredményül kapott packbe,
	azon elérhető objektumokon felül, amelyek nincsenek *.keep fájlokkal megjelölt
	packekben. Ez magában foglalja a `--revs` opciót.

--pack-loose-unreachable::
	A nem elérhető laza objektumok becsomagolása (és a laza megfelelőik
	eltávolítása). Ez magában foglalja a `--revs` opciót.

--unpack-unreachable::
	A nem elérhető objektumok laza formában tartása. Ez magában foglalja a `--revs` opciót.

--delta-islands::
	Korlátozza a delta-egyezéseket "islands" (szigetek) alapján. Lásd a DELTA ISLANDS szakaszt
	lentebb.

--name-hash-version=<n>::
	A delta-tömörítés végrehajtása közben a Git csoportosítja azokat az objektumokat, amelyek
	hasonlóak lehetnek, az adott objektumhoz vezető útvonalat használó heurisztikák alapján. Bár az
	objektumok pontos útvonal-egyezés szerinti csoportosítása jó a
	sok verzióval rendelkező útvonalakhoz, előnyös delta-párokat találni
	különböző teljes útvonalak között is. A Git az objektumokat típus, majd az útvonal
	"name hash"-e, majd méret szerint gyűjti, remélve, hogy olyan objektumokat csoportosít,
	amelyek jól tömöríthetők együtt.
+
Az alapértelmezett name hash verzió az `1`, amely a hash lokalitását helyezi előtérbe azáltal, hogy
az útvonal utolsó bájtjait tekinti a hash függvény felé a maximális nagyságrendet
biztosítónak. Ez a verzió kiválóan alkalmas rövid útvonalak megkülönböztetésére
és a könyvtárak közötti átnevezések megtalálására. A hash függvény azonban elsősorban
az útvonal utolsó 16 bájtjától függ. Ha a repóban sok olyan útvonal van,
amelynek ugyanaz az utolsó 16 bájtja, és csak a szülőkönyvtárban
különböznek, akkor ez a name-hash túl sok ütközéshez vezethet, és
gyenge eredményeket okozhat. Jelenleg ez a verzió szükséges, amikor
elérhetőségi bitmap fájlokat írunk a `--write-bitmap-index` opcióval.
+
A name hash `2` verzió hasonló lokalitási jellemzőkkel bír, mint az `1` verzió,
azzal a különbséggel, hogy minden útvonal-komponenst külön kezel, és a hasheket
egy eltolással rétegzi. Ez továbbra is az útvonal utolsó bájtjait helyezi előtérbe, de
a hash alsó bitjeit is "sózza" a szülőkönyvtárak neveivel. Ez a
módszer lehetővé teszi az `1` verzió lokalitási előnyeinek egy részét, miközben
megszünteti a sok különböző könyvtárban megjelenő, hasonló nevű fájlból eredő
ütközések többségét. Jelenleg ez a verzió nem megengedett
elérhetőségi bitmap fájlok írásakor a `--write-bitmap-index` opcióval, és
automatikusan az `1` verzióra vált.

--path-walk::
	A tömörítést úgy hajtja végre, hogy először útvonal szerint rendezi az objektumokat, majd egy
	második menetben a szokásos módon tömörít az útvonalak között. Ez potenciálisan
	javíthatja a delta-tömörítést, különösen olyan fájlnevek jelenlétében,
	amelyek ütközéseket okoznak a Git alapértelmezett name-hash
	algoritmusában.
+
Amikor a `--use-bitmap-index` a `--path-walk` opcióval van megadva, egy sikeres
bitmap-bejárás van használatban az objektumok felsorolásához, a path-walk
pedig a tartalék bejárás marad, amikor a bitmap nem tudja kielégíteni a
kérést. A `--path-walk` opció támogatja a `--filter=<spec>` `blob:none`,
`blob:limit=<n>`, `tree:0`, `object:type=<type>` és
`sparse:<oid>` formákat. Ezek a támogatott szűrőtípusok kombinálhatók a
`combine:<spec>+<spec>` formával.


DELTA ISLANDS
-------------

Amikor lehetséges, a `pack-objects` megpróbálja újrahasznosítani a lemezen meglévő deltákat,
hogy ne kelljen menet közben újakat keresnie. Ez fontos
optimalizálás a fetchek kiszolgálásához, mert azt jelenti, hogy a szerver egyáltalán elkerülheti
a legtöbb objektum kitömörítését, és egyszerűen közvetlenül a lemezről küldheti
a bájtokat. Ez az optimalizálás nem működhet, amikor egy objektum egy olyan alappal szembeni deltaként
van tárolva, amellyel a fogadó nem rendelkezik (és amelyet nem is
küldünk éppen). Ebben az esetben a szerver "megtöri" a deltát, és
újat kell találnia, aminek magas a CPU-költsége. Ezért a teljesítmény szempontjából
fontos, hogy a lemezen delta-kapcsolatban lévő objektumok halmaza megegyezzen
azzal, amit egy kliens fetchelne.

Egy normál repository-ban ez általában automatikusan működik. Az objektumok
többnyire elérhetők a branchekből és tagekből, és a kliensek ezt
fetchelik. Bármely delta, amit a szerveren találunk, valószínűleg olyan objektumok között van,
amelyekkel a kliens rendelkezik vagy rendelkezni fog.

De egyes repository-elrendezésekben előfordulhat, hogy több, egymással összefüggő, de különálló
ref-csúcs-csoportod van, és a kliensek hajlamosak ezeket a csoportokat
egymástól függetlenül fetchelni. Például képzeld el, hogy egy repository több "forkját"
tárolod egyetlen megosztott objektumtárolóban, és a kliensek
különálló repository-kként látják őket a `GIT_NAMESPACE` révén, vagy különálló
repók az alternates mechanizmussal. Egy naiv repack úgy találhatja, hogy egy objektum
optimális deltája egy olyan alappal szemben van, amely csak
egy másik forkban található meg. De amikor egy kliens fetchel, nem lesz meg neki az alap-
objektum, és menet közben új deltát kell találnunk.

Hasonló helyzet állhat elő, ha sok refed van a
`refs/heads/` és `refs/tags/` körén kívül, amelyek összefüggő objektumokra mutatnak (pl.
egyes hosting-szolgáltatók által használt `refs/pull` vagy `refs/changes`). Alapból
a kliensek csak a headeket és tageket fetchelik, és a csak ezekben a
többi csoportban található objektumokkal szembeni delták nem küldhetők el változatlanul.

A delta islands megoldja ezt a problémát azzal, hogy lehetővé teszi a refeid különálló
"islands"-be (szigetekbe) csoportosítását. A Pack-objects kiszámítja, mely objektumok érhetők el
mely szigetekből, és megtagadja, hogy egy `A` objektumból deltát készítsen
egy olyan alappal szemben, amely nincs jelen `A` összes szigetén. Ez
kissé nagyobb packeket eredményez (mert néhány delta-lehetőségről
lemaradunk), de garantálja, hogy egy sziget fetchelésekor nem kell
menet közben újraszámolni a deltákat a szigethatárok átlépése miatt.

Amikor delta islands-szel repackelünk, a delta-ablak hajlamos eltömődni
olyan jelöltekkel, amelyeket a config tilt. Segít egy nagy --window-nal
repackelni (és nem tart olyan sokáig, mint egyébként tartana, mert
néhány objektumpárt a szigetek alapján elutasíthatunk, mielőtt bármilyen
számítást végeznénk a tartalmon).

A szigetek a `pack.island` opción keresztül vannak konfigurálva, amely többször is
megadható. Minden érték egy bal oldalhoz rögzített, refnevekre illeszkedő
reguláris kifejezés. Például:

-------------------------------------------
[pack]
island = refs/heads/
island = refs/tags/
-------------------------------------------

a headeket és tageket egy szigetbe teszi (amelynek neve az üres sztring; a
névadásról lásd lentebb bővebben). Bármely ref, amely nem illeszkedik ezekre a reguláris
kifejezésekre (pl. `refs/pull/123`), nincs egyetlen szigetben sem. Bármely objektum,
amely csak a `refs/pull/`-ból érhető el (de nem a headekből vagy tagekből),
ezért nem jelölt arra, hogy a `refs/heads/` alapjaként használják.

A refek a "neveik" alapján vannak szigetekbe csoportosítva, és két olyan regex,
amely ugyanazt a nevet állítja elő, ugyanabban a szigetben lévőnek
tekinthető. A neveket a regexekből számítjuk ki úgy, hogy a regex bármely
capture-csoportját összefűzzük, közéjük egy '-' kötőjelet téve. (És ha
nincsenek capture-csoportok, akkor a név az üres sztring, mint a
fenti példában.) Ez lehetővé teszi tetszőleges számú
sziget létrehozását. Legfeljebb 14 ilyen capture-csoport támogatott azonban.

Például képzeld el, hogy minden fork refeit a
`refs/virtual/ID` alatt tárolod, ahol az `ID` egy numerikus azonosító. Ekkor a
következőt konfigurálhatod:

-------------------------------------------
[pack]
island = refs/virtual/([0-9]+)/heads/
island = refs/virtual/([0-9]+)/tags/
island = refs/virtual/([0-9]+)/(pull)/
-------------------------------------------

Ez minden fork headjeit és tagjeit a saját szigetébe teszi ("1234"-nek
vagy hasonlónak nevezve), és mindegyik pull refjei a saját
"1234-pull" szigetükbe kerülnek.

Vedd figyelembe, hogy minden regexhez egyetlen szigetet választunk, ahová bekerül, "az
utolsó nyer" sorrendet használva (ami lehetővé teszi, hogy a repóspecifikus config elsőbbséget élvezzen
a felhasználószintű configgal szemben, és így tovább).


CONFIGURATION
-------------

Különböző konfigurációs változók befolyásolják a csomagolást, lásd
linkgit:git-config[1] (keress a "pack" és "delta" kifejezésekre).

Nevezetesen a delta-tömörítés nincs használatban a
`core.bigFileThreshold` konfigurációs változónál nagyobb objektumokon, és azokon a fájlokon, amelyeknél a
`delta` attribútum false-ra van állítva.

SEE ALSO
--------
linkgit:git-rev-list[1]
linkgit:git-repack[1]
linkgit:git-prune-packed[1]

GIT
---
A linkgit:git[1] csomag része
