git-prune(1)
============

NAME
----
git-prune - Minden el nem érhető objektumot eltávolít az objektumadatbázisból


SYNOPSIS
--------
[verse]
'git prune' [-n] [-v] [--progress] [--expire <time>] [--] [<head>...]

DESCRIPTION
-----------

NOTE: A legtöbb esetben a felhasználóknak a 'git gc'-t kellene
futtatniuk, amely meghívja a 'git prune'-t. Lásd lent a "NOTES"
szakaszt.

Ez lefuttatja a 'git fsck --unreachable'-t, a `refs/`-ben elérhető
összes referenciát felhasználva, opcionálisan a parancssorban
megadott objektumok egy további halmazával, és eltávolítja az
objektumadatbázisból az összes csomagolatlan objektumot, amely egyik
ilyen head-objektumból sem érhető el. Emellett a 'git prune-packed'
futtatásával eltávolítja azokat a csomagolatlan objektumokat is,
amelyek packekben is megtalálhatók. Emellett eltávolítja a
.git/shallow-ból azokat a bejegyzéseket, amelyek egyetlen
referenciából sem érhetők el.

Vedd figyelembe, hogy az el nem érhető, csomagolt objektumok
megmaradnak. Ha ez nem kívánt, lásd a linkgit:git-repack[1]-et.

OPTIONS
-------

-n::
--dry-run::
	Nem távolít el semmit; csak jelenti, mit távolítana el.

-v::
--verbose::
	Jelenti az összes eltávolított objektumot.

--progress::
	Megmutatja a folyamatot.

--expire <time>::
	Csak a <time>-nál régebbi laza objektumokat járatja le.

\--::
	A további argumentumokat már nem értelmezi opcióként.

<head>...::
	A referenciáink bármelyikéből elérhető objektumok mellett a
	felsorolt <head>ekből elérhető objektumokat is megtartja.

EXAMPLES
--------

Olyan objektumok eltávolítására, amelyeket a repository-d nem
használ, vagy egy másik, amely a `.git/objects/info/alternates`-en
keresztül kölcsönöz a repository-dból:

------------
$ git prune $(cd ../another && git rev-parse --all)
------------

NOTES
-----

A legtöbb esetben a felhasználóknak nem kell közvetlenül meghívniuk
a 'git prune'-t, hanem ehelyett a 'git gc'-t kellene meghívniuk,
amely a prune-olás mellett sok más karbantartási feladatot is kezel.

Annak leírásáért, hogy mely objektumok jönnek szóba prune-olásra,
lásd a 'git fsck' --unreachable opcióját.

SEE ALSO
--------

linkgit:git-fsck[1],
linkgit:git-gc[1],
linkgit:git-reflog[1]

GIT
---
A linkgit:git[1] csomag része
