git-reflog(1)
=============

NAME
----
git-reflog - Reflog-információk kezelése


SYNOPSIS
--------
[synopsis]
git reflog [show] [<log-options>] [<ref>]
git reflog list
git reflog exists <ref>
git reflog write <ref> <old-oid> <new-oid> <message>
git reflog delete [--rewrite] [--updateref]
	[--dry-run | -n] [--verbose] <ref>@{<specifier>}...
git reflog drop [--all [--single-worktree] | <refs>...]
git reflog expire [--expire=<time>] [--expire-unreachable=<time>]
	[--rewrite] [--updateref] [--stale-fix]
	[--dry-run | -n] [--verbose] [--all [--single-worktree] | <refs>...]

DESCRIPTION
-----------
Ez a parancs a reflogokban rögzített információkat kezeli.

A referencianaplók, avagy „reflogok", rögzítik, hogy a branchek és más
referenciák csúcsai mikor frissültek a lokális repository-ban. A reflogok
számos Git parancsban hasznosak egy referencia korábbi értékének
megadására. Például a `HEAD@{2}` azt jelenti: „ahol a HEAD két mozdulattal
ezelőtt volt", a `master@{one.week.ago}` azt jelenti: „ahová a master egy
héttel ezelőtt mutatott ebben a lokális repository-ban", és így tovább.
További részletekért l. linkgit:gitrevisions[7].

A parancs különféle alparancsokat fogad, és az alparancstól függően
eltérő opciókat:

A "show" alparancs (amely egyben az alapértelmezett is, alparancs
hiányában) a parancssorban megadott referencia (vagy alapból a `HEAD`)
naplóját mutatja. A reflog minden friss műveletet lefed, és ezenfelül a
`HEAD` reflog rögzíti a branchváltásokat is.  A `git reflog show` a
`git log -g --abbrev-commit --pretty=oneline` álneve; további
információért l. linkgit:git-log[1].

A "list" alparancs felsorolja az összes refet, amelyhez tartozik reflog.

Az "exists" alparancs ellenőrzi, hogy egy refnek van-e reflogja.  Nulla
státusszal lép ki, ha a reflog létezik, és nem nulla státusszal, ha nem.

A "write" alparancs egyetlen bejegyzést ír egy adott referencia
reflogjába. Ez az új bejegyzés a refloghoz fűződik, és így a
legfrissebb bejegyzéssé válik. A referencianévnek teljesen minősítettnek
kell lennie. Sem a régi, sem az új objektumazonosító nem lehet
rövidített, és létező objektumokra kell mutatniuk.  A reflog-üzenet
normalizálásra kerül.

A "delete" alparancs egyes bejegyzéseket töröl a reflogból, de magát a
reflogot nem. Az argumentumának egy _pontos_ bejegyzésnek kell lennie
(pl. "`git reflog delete master@{2}`"). Ezt az alparancsot szintén
jellemzően nem közvetlenül a végfelhasználók használják.

A "drop" alparancs teljesen eltávolítja a megadott referenciák
reflogját. Ez ellentétben áll az "expire"-rel és a "delete"-tel, amelyek
mindegyike reflog-bejegyzések törlésére használható, de magának a
reflognak a törlésére nem.

Az "expire" alparancs metszi a régebbi reflog-bejegyzéseket. Az
`expire` időnél régebbi bejegyzések, vagy az `expire-unreachable` időnél
régebbi és az aktuális csúcsból el nem érhető bejegyzések eltávolításra
kerülnek a reflogból.  Ezt jellemzően nem közvetlenül a végfelhasználók
használják -- helyette l. linkgit:git-gc[1].

OPTIONS
-------

[[_options_for_show]]
Opciók a `show`-hoz
~~~~~~~~~~~~~~~~~~~

A `git reflog show` elfogadja bármelyik olyan opciót, amelyet a
`git log` elfogad.


[[_options_for_delete]]
Opciók a `delete`-hez
~~~~~~~~~~~~~~~~~~~~~

A `git reflog delete` elfogadja a `--updateref`, `--rewrite`, `-n`,
`--dry-run` és `--verbose` opciókat, ugyanazzal a jelentéssel, mint
amikor az `expire`-rel használják őket.

[[_options_for_drop]]
Opciók a `drop`-hoz
~~~~~~~~~~~~~~~~~~~

`--all`::
	Az összes referencia reflogjának eldobása az összes worktree-ből.

`--single-worktree`::
	Alapból, amikor a `--all` meg van adva, az összes working tree
	reflogja eldobásra kerül. Ez az opció a feldolgozást csak az
	aktuális working tree reflogjaira korlátozza.


[[_options_for_expire]]
Opciók az `expire`-hez
~~~~~~~~~~~~~~~~~~~~~~

`--all`::
	Az összes referencia reflogjának feldolgozása.

`--single-worktree`::
	Alapból, amikor a `--all` meg van adva, az összes working tree
	reflogja feldolgozásra kerül. Ez az opció a feldolgozást csak az
	aktuális working tree reflogjaira korlátozza.

`--expire=<time>`::
	A megadott időnél régebbi bejegyzések metszése. Ha ez az opció
	nincs megadva, a lejárati idő a `gc.reflogExpire` konfigurációs
	beállításból származik, amely viszont alapból 90 nap. A
	`--expire=all` a bejegyzéseket a koruktól függetlenül metszi; a
	`--expire=never` kikapcsolja az elérhető bejegyzések metszését
	(de l. a `--expire-unreachable`-t).

`--expire-unreachable=<time>`::
	A `<time>`-nál régebbi olyan bejegyzések metszése, amelyek nem
	érhetők el a branch aktuális csúcsából. Ha ez az opció nincs
	megadva, a lejárati idő a `gc.reflogExpireUnreachable`
	konfigurációs beállításból származik, amely viszont alapból 30 nap.
	A `--expire-unreachable=all` az el nem érhető bejegyzéseket a
	koruktól függetlenül metszi; a `--expire-unreachable=never`
	kikapcsolja az el nem érhető bejegyzések korai metszését (de l. a
	`--expire`-t).

`--updateref`::
	A referencia frissítése a legfelső reflog-bejegyzés értékére (azaz
	<ref>@\{0\}), ha a korábbi legfelső bejegyzés metszésre került.  (Ez
	az opció figyelmen kívül marad a szimbolikus referenciáknál.)

`--rewrite`::
	Ha egy reflog-bejegyzés elődjét metszik, a bejegyzés "old" SHA-1-ét
	úgy állítja be, hogy egyenlő legyen az őt most megelőző bejegyzés
	"new" SHA-1 mezőjével.

`--stale-fix`::
	Minden olyan reflog-bejegyzés metszése, amely „törött commitokra"
	mutat. A törött commit olyan commit, amely egyetlen
	referencia-csúcsból sem érhető el, és amely közvetlenül vagy
	közvetve egy hiányzó commitra, tree-re vagy blob objektumra
	hivatkozik.
+
Ez a számítás az összes elérhető objektum bejárásával jár, azaz
ugyanolyan költséges, mint a 'git prune'.  Elsősorban a Git régebbi
verzióival végzett szemétgyűjtés által okozott sérülés javítására
szolgál, amelyek nem védték a reflogok által hivatkozott objektumokat.

`-n`::
`--dry-run`::
	Ne metssen ténylegesen egyetlen bejegyzést sem; csak mutassa meg,
	mit metszett volna.

`--verbose`::
	Extra információ kiírása a képernyőre.


GIT
---
A linkgit:git[1] csomag része
