git-fast-export(1)
==================

NAME
----
git-fast-export - Git adatexportáló


SYNOPSIS
--------
[verse]
'git fast-export' [<options>] [<revision-range>] [[--] <path>...]

DESCRIPTION
-----------
Ez a program a megadott revíziókat olyan formában dumpolja ki, amely
alkalmas a 'git fast-import'-ba való becsövezésre.

Használhatod emberi szemmel is olvasható bundle-helyettesítőként (lásd:
linkgit:git-bundle[1]), vagy olyan formátumként, amely szerkeszthető,
mielőtt a 'git fast-import'-nak átadnák előzmény-átírás elvégzéséhez
(ilyen képességre támaszkodnak az olyan eszközök, mint a 'git filter-repo').

OPTIONS
-------
--progress=<n>::
	'progress' utasításokat szúr be minden <n> objektumonként,
	amelyeket a 'git fast-import' jelenít meg az importálás során.

--signed-tags=(verbatim|warn-verbatim|warn-strip|strip|abort)::
	Megadja, hogyan kell kezelni az aláírt tageket. Mivel az export
	után (vagy az export közben, például revíziók kizárásakor)
	végzett bármely transzformáció megváltoztathatja az aláírt
	hasheket, az aláírások érvénytelenné válhatnak.
+
Ha az 'abort'-ot kéred (ez az alapértelmezett), a program leáll, ha
aláírt tagre bukkan. A 'strip' esetén a tagek csendben aláíratlanná
válnak, a 'warn-strip' esetén aláíratlanná válnak, de figyelmeztetés
jelenik meg, a 'verbatim' esetén csendben exportálásra kerülnek, a
'warn-verbatim' (vagy 'warn', egy elavult szinonima) esetén pedig
exportálásra kerülnek, de figyelmeztetést fogsz látni. A 'verbatim'
és a 'warn-verbatim' csak akkor használandó, ha tudod, hogy sem te,
sem a fast-export vagy a fast-import nem fog olyan transzformációt
végezni, amely a tageket vagy az előzményükben lévő bármely commitot
érinti, vagy ha nem érdekel, hogy a keletkező tag érvénytelen
aláírással fog rendelkezni.

--signed-commits=(verbatim|warn-verbatim|warn-strip|strip|abort)::
	Megadja, hogyan kell kezelni az aláírt commitokat. Pontosan úgy
	viselkedik, mint a '--signed-tags', csak commitokra. Az
	alapértelmezés a 'strip', ami ugyanaz, ahogyan e parancs korábbi,
	ezen opció nélküli verziói viselkedtek.
+
Exportáláskor az aláírás a következővel kezdődik:
+
gpgsig <git-hash-algo> <signature-format>
+
ahol a <git-hash-algo> a Git objektum-hash, tehát vagy "sha1", vagy
"sha256", a <signature-format> pedig az aláírás típusa, tehát
"openpgp", "x509", "ssh" vagy "unknown".
+
Például egy SHA-1 commit OpenPGP-aláírása `gpgsig sha1 openpgp`-vel
kezdődik, míg egy SHA-256 commit SSH-aláírása `gpgsig sha256 ssh`-val.
+
Bár egy commit összes aláírása exportálásra kerül, egy importáló
dönthet úgy, hogy csak néhányat fogad el közülük. Például a
linkgit:git-fast-import[1] jelenleg legfeljebb egy aláírást tárol
Git-hash-algoritmusonként minden commitban.
+
NOTE: Ez rendkívül kísérleti, és az adatfolyam formátuma a jövőben
kompatibilitási garancia nélkül változhat.

--tag-of-filtered-object=(abort|drop|rewrite)::
	Megadja, hogyan kell kezelni azokat a tageket, amelyek tagelt
	objektuma ki van szűrve. Mivel az exportálandó revíziók és fájlok
	útvonal szerint korlátozhatók, a tagelt objektumok teljesen
	kiszűrődhetnek.
+
Ha az 'abort'-ot kéred (ez az alapértelmezett), a program leáll, ha
ilyen tagre bukkan. A 'drop' esetén az ilyen tageket kihagyja a
kimenetből. A 'rewrite' esetén, ha a tagelt objektum egy commit,
átírja a taget úgy, hogy egy elődcommitot tageljen (szülő-átírás
révén; lásd: linkgit:git-rev-list[1]).

-M::
-C::
	Áthelyezés- és/vagy másolásészlelést végez, ahogyan azt a
	linkgit:git-diff[1] man page leírja, és felhasználja
	átnevezési és másolási parancsok generálásához a kimeneti
	dumpban.
+
Vedd figyelembe, hogy e parancs korábbi verziói nem panaszkodtak, és
helytelen eredményeket produkáltak, ha ezeket az opciókat megadtad.

--export-marks=<file>::
	Befejezéskor kiírja a belső marks-táblát a <file>-ba. A markok
	soronként egyet kerülnek kiírásra `:markid SHA-1` formában. Csak
	a revíziókhoz tartozó markok kerülnek kiírásra; a blobokhoz
	tartozó markok figyelmen kívül maradnak. A backendek ezt a fájlt
	használhatják az importok érvényesítésére a befejezésük után,
	vagy a marks-tábla mentésére inkrementális futtatások között.
	Mivel a <file> csak a befejezéskor kerül megnyitásra és
	csonkolásra, ugyanaz az útvonal biztonságosan megadható a
	--import-marks-nak is. A fájl nem kerül kiírásra, ha egyetlen új
	objektum sem lett megjelölve/exportálva.

--import-marks=<file>::
	Bármilyen bemenet feldolgozása előtt betölti a <file>-ban
	megadott markokat. A bemeneti fájlnak léteznie kell, olvashatónak
	kell lennie, és ugyanazt a formátumot kell használnia, amit a
	--export-marks állít elő.

--mark-tags::
	A blobok és commitok mark-id-kkel való megjelölése mellett a
	tageket is megjelöli. Ez hasznos a `--export-marks`-szal és a
	`--import-marks`-szal együtt, valamint hasznos (és szükséges) is
	az egymásba ágyazott tagek exportálásához. Más esetekben nem árt,
	és alapértelmezett is lehetne, de sok fast-import frontend nincs
	felkészítve arra, hogy mark-azonosítós tageket fogadjon el.
+
Az olyan commitok (vagy tagek), amelyek már meg vannak jelölve, nem
kerülnek újra exportálásra. Ha a backend hasonló --import-marks
fájlt használ, ez lehetővé teszi a repository inkrementális,
kétirányú exportálását azáltal, hogy a markok ugyanazok maradnak a
futtatások között.

--fake-missing-tagger::
	Néhány régi repository-ban vannak tagelő nélküli tagek. A
	fast-import protokoll ezzel kapcsolatban meglehetősen szigorú
	volt, és nem engedte ezt meg. Ezért egy hamis tagelőt hoz létre,
	hogy a kimenet fast-importálható legyen.

--use-done-feature::
	Egy 'feature done' szakasszal kezdi az adatfolyamot, és egy
	'done' paranccsal zárja azt le.

--no-data::
	Kihagyja a blob objektumok kiírását, és ehelyett az eredeti
	SHA-1 hash-ükön keresztül hivatkozik a blobokra. Ez akkor
	hasznos, amikor egy repository könyvtárszerkezetét vagy
	előzményét írod át anélkül, hogy az egyes fájlok tartalmához
	hozzányúlnál. Vedd figyelembe, hogy a keletkező adatfolyam csak
	olyan repository-ban használható, amely már tartalmazza a
	szükséges objektumokat.

--full-tree::
	Ez az opció azt eredményezi, hogy a fast-export minden commithoz
	kibocsát egy "deleteall" direktívát, amelyet az adott commitban
	lévő összes fájl teljes listája követ (szemben azzal, hogy csak
	a commit első szülőjétől eltérő fájlokat sorolná fel).

--anonymize::
	Anonimizálja a repository tartalmát, miközben megtartja az
	előzmény és a tárolt fa alakját. Lásd lent az `ANONYMIZING`
	szakaszt.

--anonymize-map=<from>[:<to>]::
	A `<from>` tokent `<to>`-vá alakítja az anonimizált kimenetben.
	Ha a `<to>` el van hagyva, a `<from>`-ot önmagára képezi le
	(azaz nem anonimizálja azt). Lásd lent az `ANONYMIZING` szakaszt.

--reference-excluded-parents::
	Alapértelmezés szerint az olyan parancs futtatása, mint a
	`git fast-export master~5..master`, nem tartalmazza a
	master{tilde}5 commitot, és azt eredményezi, hogy a
	master{tilde}4-nek többé nem lesz szülője a master{tilde}5 (bár
	a régi master{tilde}4-nek és az új master{tilde}4-nek is
	ugyanazok a fájljai lesznek). Használd a
	--reference-excluded-parents-t, hogy ehelyett az adatfolyam a
	kizárt előzménytartományban lévő commitokra a sha1sum-jukon
	keresztül hivatkozzon. Vedd figyelembe, hogy a keletkező
	adatfolyam csak olyan repository-ban használható, amely már
	tartalmazza a szükséges szülőcommitokat.

--show-original-ids::
	Egy extra direktívát ad hozzá a kimenethez a commitok és blobok
	esetén: `original-oid <SHA1SUM>`. Bár az ilyen direktívákat az
	olyan importálók, mint a git-fast-import, valószínűleg
	figyelmen kívül hagyják, hasznosak lehetnek köztes szűrők
	számára (pl. régebbi commitokra hivatkozó commit-üzenetek
	átírásához, vagy blobok id szerinti kiszűréséhez).

--reencode=(yes|no|abort)::
	Megadja, hogyan kell kezelni a commit objektumokban lévő
	`encoding` fejlécet. Ha az 'abort'-ot kéred (ez az
	alapértelmezett), a program leáll, ha ilyen commit objektumra
	bukkan. A 'yes' esetén a commit-üzenet UTF-8-ra lesz
	újrakódolva. A 'no' esetén az eredeti kódolás megmarad.

--refspec::
	A megadott refspecet alkalmazza minden exportált ref-re. Több is
	megadható belőlük.

[<git-rev-list-args>...]::
	A 'git rev-parse' és a 'git rev-list' számára elfogadható
	argumentumok listája, amely megadja az exportálandó konkrét
	objektumokat és referenciákat. Például a `master~10..master`
	azt eredményezi, hogy a jelenlegi master referencia exportálásra
	kerül a 10. ősétől kezdve hozzáadott összes objektummal együtt,
	valamint (hacsak nincs megadva a --reference-excluded-parents
	opció) a master{tilde}9 és a master{tilde}10 közös fájljaival
	együtt.

EXAMPLES
--------

-------------------------------------------------------------------
$ git fast-export --all | (cd /empty/repository && git fast-import)
-------------------------------------------------------------------

Ez exportálja a teljes repository-t, és importálja a meglévő üres
repository-ba. Eltekintve azoktól a commitoktól, amelyek átkódolásra
kerülnek, mert nem UTF-8-ban vannak, ez egy az egyben tükörmásolat
lenne.

-----------------------------------------------------
$ git fast-export master~5..master |
	sed "s|refs/heads/master|refs/heads/other|" |
	git fast-import
-----------------------------------------------------

Ez létrehoz egy 'other' nevű új branchet a 'master~5..master'-ből
(azaz ha a 'master'-nek lineáris előzménye van, az utolsó 5 commitot
veszi át).

Vedd figyelembe, hogy ez feltételezi, hogy az adott revíziótartomány
által hivatkozott blobok és commit-üzenetek egyike sem tartalmazza a
'refs/heads/master' stringet.


ANONYMIZING
-----------

Ha a `--anonymize` opciót megadod, a git megpróbál eltávolítani minden
azonosító információt a repository-ból, miközben megtartja az eredeti
fa és előzmény mintáinak annyit, amennyi elég néhány hiba
reprodukálásához. A cél az, hogy egy privát repository-n talált git
hiba fennmaradjon az anonimizált repository-ban is, és ez utóbbi
megosztható legyen a git fejlesztőkkel a hiba megoldásához.

Ezzel az opcióval a git a kimenetben az összes refnevet, útvonalat,
blob-tartalmat, commit- és tag-üzenetet, nevet és e-mail-címet
anonimizált adatra cseréli. Ugyanannak a stringnek két előfordulása
egyenértékűen kerül cserére (pl. két, azonos szerzőjű commit ugyanazt
az anonimizált szerzőt kapja a kimenetben, de az nem fog hasonlítani
az eredeti szerző-stringre). A commitok, branchek és tagek közötti
kapcsolat megmarad, csakúgy, mint a commit-időbélyegek (de a
commit-üzenetek és a refnevek nem hasonlítanak az eredetire). A fa
relatív felépítése megmarad (pl. ha van egy gyökérfád 10 fájllal és 3
alfával, a kimenet is ilyen lesz), de a neveik és a fájlok tartalma
lecserélődik.

Ha úgy gondolod, hogy találtál egy git hibát, kezdheted azzal, hogy
exportálod a teljes repository anonimizált adatfolyamát:

---------------------------------------------------
$ git fast-export --anonymize --all >anon-stream
---------------------------------------------------

Ezután erősítsd meg, hogy a hiba fennmarad az abból az adatfolyamból
létrehozott repository-ban is (sok hiba nem fog, mivel ténylegesen
a pontos repository-tartalomtól függenek):

---------------------------------------------------
$ git init anon-repo
$ cd anon-repo
$ git fast-import <../anon-stream
$ ... test your bug ...
---------------------------------------------------

Ha az anonimizált repository mutatja a hibát, érdemes lehet megosztani
az `anon-stream`-et egy rendes hibajelentés mellett. Vedd figyelembe,
hogy az anonimizált adatfolyam nagyon jól tömöríthető, ezért ajánlott
gzip-elni. Ha meg akarod vizsgálni az adatfolyamot, hogy megbizonyosodj
róla, nem tartalmaz privát adatot, elolvashatod közvetlenül, mielőtt
elküldenéd. Kipróbálhatod ezt is:

---------------------------------------------------
$ perl -pe 's/\d+/X/g' <anon-stream | sort -u | less
---------------------------------------------------

amely megmutatja az összes egyedi sort (a számok "X"-re alakítva, hogy
a "User 0", "User 1" stb. "User X"-be tömörüljön). Ez sokkal kisebb
kimenetet ad, és általában könnyű gyorsan megerősíteni, hogy nincs
privát adat az adatfolyamban.

Néhány hiba reprodukálásához bizonyos commitokra vagy útvonalakra kell
hivatkozni, ami kihívást jelent, miután a refnevek és útvonalak
anonimizálásra kerültek. Kérheted, hogy egy adott token változatlanul
maradjon, vagy egy új értékre képződjön le. Ha például van egy hibád,
amely a `git rev-list sensitive -- secret.c` paranccsal reprodukálható,
futtathatod ezt:

---------------------------------------------------
$ git fast-export --anonymize --all \
      --anonymize-map=sensitive:foo \
      --anonymize-map=secret.c:bar.c \
      >stream
---------------------------------------------------

Az adatfolyam importálása után futtathatod a `git rev-list foo -- bar.c`
parancsot az anonimizált repository-ban.

Vedd figyelembe, hogy az útvonalak és a refnevek per-jel határoknál
tokenekre vannak bontva. A fenti parancs a `subdir/secret.c`-t valami
ilyesmire anonimizálná: `path123/bar.c`; ezután kereshetsz a `bar.c`-re
az anonimizált repository-ban, hogy meghatározd a végleges
fájlútvonalat.

Hogy a végleges fájlútvonalra hivatkozás egyszerűbb legyen, minden
útvonal-komponenst leképezhetsz; így ha a `subdir`-t is anonimizálod
`publicdir`-ra, a végleges fájlútvonal `publicdir/bar.c` lesz.

LIMITATIONS
-----------

Mivel a 'git fast-import' nem tud fákat tagelni, nem leszel képes
teljesen exportálni a linux.git repository-t, mivel az egy fára, nem
pedig egy commitra hivatkozó taget tartalmaz.

SEE ALSO
--------
linkgit:git-fast-import[1]

GIT
---
A linkgit:git[1] csomag része
