git-svn(1)
==========

NAME
----
git-svn - Kétirányú működés egy Subversion repository és a Git között

SYNOPSIS
--------
[verse]
'git svn' <command> [<options>] [<arguments>]

DESCRIPTION
-----------
A 'git svn' egy egyszerű csatorna a changesetek számára a Subversion és a
Git között. Kétirányú változásáramlást biztosít egy Subversion és egy Git
repository között.

A 'git svn' képes egy standard Subversion repository követésére, a
megszokott „trunk/branches/tags" elrendezést követve, a --stdlayout
opcióval. Bármilyen elrendezésben lévő brancheket és tageket is képes
követni a -T/-t/-b opciókkal (lásd az 'init' lentebbi opcióit, valamint a
'clone' parancsot is).

Miután egy Subversion repository követése megkezdődött (a fenti módszerek
bármelyikével), a Git repository a Subversionből frissíthető a 'fetch'
paranccsal, a Subversion pedig a Gitből a 'dcommit' paranccsal.

COMMANDS
--------

'init'::
	Inicializál egy üres Git repository-t a 'git svn' számára szükséges
	kiegészítő metaadat-könyvtárakkal.  A Subversion URL megadható
	parancssori argumentumként, vagy teljes URL argumentumokként a
	-T/-t/-b opciókhoz.  Opcionálisan a célkönyvtár, amelyben a parancs
	dolgozik, megadható második argumentumként.  Normál esetben ez a
	parancs az aktuális könyvtárat inicializálja.

-T<trunk-subdir>;;
--trunk=<trunk-subdir>;;
-t<tags-subdir>;;
--tags=<tags-subdir>;;
-b<branches-subdir>;;
--branches=<branches-subdir>;;
-s;;
--stdlayout;;
	Ezek az init parancs opcionális parancssori opciói.  Ezen kapcsolók
	mindegyike mutathat relatív repository elérési útra
	(--tags=project/tags) vagy teljes URL-re
	(--tags=https://foo.org/project/tags).
	Több --tags és/vagy --branches opciót is megadhatsz, ha a Subversion
	repository-d több elérési út alatt is elhelyez tageket vagy
	brancheket.
	A --stdlayout opció egy rövidített módja annak, hogy a trunk,tags,
	branches relatív elérési utakként legyenek beállítva, ami a
	Subversion alapértelmezése. Ha a többi opció közül is meg van adva
	valamelyik, azok élveznek elsőbbséget.
--no-metadata;;
	Beállítja a 'noMetadata' opciót az [svn-remote] configban.
	Ez az opció nem ajánlott, kérjük, a használata előtt olvasd el
	ennek a manpage-nek a 'svn.noMetadata' szakaszát.
--use-svm-props;;
	Beállítja a 'useSvmProps' opciót az [svn-remote] configban.
--use-svnsync-props;;
	Beállítja a 'useSvnsyncProps' opciót az [svn-remote] configban.
--rewrite-root=<URL>;;
	Beállítja a 'rewriteRoot' opciót az [svn-remote] configban.
--rewrite-uuid=<UUID>;;
	Beállítja a 'rewriteUUID' opciót az [svn-remote] configban.
--username=<user>;;
	Azoknál a protokolloknál, amelyekhez az SVN kezeli a hitelesítést
	(http, https és sima svn), add meg a felhasználónevet.  Más
	protokolloknál (pl. `svn+ssh://`) a felhasználónevet az URL-be kell
	foglalnod, pl. `svn+ssh://foo@svn.bar.com/project`
--prefix=<prefix>;;
	Ez lehetővé teszi egy előtag megadását, amely a remote-ok neve elé
	kerül, ha a trunk/branches/tags meg van adva.  Az előtag nem
	tartalmaz automatikusan záró perjelet, ezért ügyelj arra, hogy az
	argumentumba illessz egyet, ha ezt szeretnéd.  Ha a --branches/-b
	meg van adva, az előtagnak tartalmaznia kell egy záró perjelet.
	Egy előtag beállítása (záró perjellel) mindenképp erősen ajánlott,
	mivel az SVN-t követő refeid ekkor a "refs/remotes/$prefix/*"
	helyen lesznek, ami kompatibilis a Git saját remote-tracking ref
	elrendezésével (refs/remotes/$remote/*). Egy előtag beállítása
	akkor is hasznos, ha több olyan projektet szeretnél követni,
	amelyek egy közös repository-n osztoznak.
	Alapértelmezés szerint az előtag 'origin/'-ra van állítva.
+
NOTE: A Git v2.0 előtt az alapértelmezett előtag "" volt (nincs előtag).
Ez azt jelentette, hogy az SVN-t követő refek a "refs/remotes/*" helyre
kerültek, ami nem kompatibilis azzal, ahogyan a Git saját remote-tracking
refjei szerveződnek. Ha még mindig a régi alapértelmezést szeretnéd, ezt
a `--prefix ""` parancssori argumentum átadásával kaphatod meg
(a `--prefix=""` esetleg nem működik, ha a Perl Getopt::Long verziója
< v2.37).

--ignore-refs=<regex>;;
	Ha az 'init' vagy a 'clone' parancsnak van átadva, ez a reguláris
	kifejezés config kulcsként meg lesz őrizve.  A `--ignore-refs`
	leírásáért lásd a 'fetch'-et.
--ignore-paths=<regex>;;
	Ha az 'init' vagy a 'clone' parancsnak van átadva, ez a reguláris
	kifejezés config kulcsként meg lesz őrizve.  A `--ignore-paths`
	leírásáért lásd a 'fetch'-et.
--include-paths=<regex>;;
	Ha az 'init' vagy a 'clone' parancsnak van átadva, ez a reguláris
	kifejezés config kulcsként meg lesz őrizve.  A `--include-paths`
	leírásáért lásd a 'fetch'-et.
--no-minimize-url;;
	Több könyvtár követésekor (a --stdlayout, --branches vagy --tags
	opciók használatával) a git svn megpróbál kapcsolódni a Subversion
	repository gyökeréhez (vagy a legmagasabb engedélyezett szinthez).
	Ez az alapértelmezés lehetővé teszi az előzmények jobb követését,
	ha egész projektek kerülnek áthelyezésre egy repository-n belül, de
	problémákat okozhat olyan repository-kon, ahol olvasási hozzáférési
	korlátozások vannak érvényben.  A `--no-minimize-url` átadása
	lehetővé teszi a git svn számára, hogy az URL-eket úgy fogadja el,
	ahogy vannak, anélkül, hogy megpróbálna egy magasabb szintű
	könyvtárhoz kapcsolódni.  Ez az opció alapértelmezés szerint ki van
	kapcsolva, ha csak egyetlen URL/branch van követve (akkor kevés
	haszna lenne).

'fetch'::
	Lekéri a le nem kért revíziókat a Subversion remote-ból, amelyet
	követünk.  A [svn-remote "..."] szekció neve a $GIT_DIR/config
	fájlban opcionális parancssori argumentumként megadható.
+
Ez automatikusan frissíti a rev_map-et, ha szükséges (lásd a lentebbi
FILES szakaszban a '$GIT_DIR/svn/\**/.rev_map.*'-ot a részletekért).

--localtime;;
	A Git commit-időpontokat a helyi időzónában tárolja UTC helyett.
	Ez azt eredményezi, hogy a 'git log' (még --date=local nélkül is)
	ugyanazokat az időpontokat mutatja a helyi időzónában, mint amit az
	`svn log` mutatna.
+
Ez nem zavarja az együttműködést azzal a Subversion repository-val,
amelyből klónoztál, de ha azt szeretnéd, hogy a helyi Git repository-d
képes legyen együttműködni valaki más helyi Git repository-jával, akkor
vagy ne használd ezt az opciót, vagy mindkettőtöknek ugyanabban a helyi
időzónában kell használnia.

--parent;;
	Csak az aktuális HEAD SVN-szülőjéből kér le.

--ignore-refs=<regex>;;
	Figyelmen kívül hagyja a Perl reguláris kifejezésnek megfelelő
	branchekhez vagy tagekhez tartozó refeket. Egy „negatív
	look-ahead assertion", mint például
	`^refs/remotes/origin/(?!tags/wanted-tag|wanted-branch).*$`
	használható arra, hogy csak bizonyos refeket engedjünk meg.
+
[verse]
config key: svn-remote.<name>.ignore-refs
+
Ha az ignore-refs konfigurációs kulcs be van állítva, és a parancssori
opció is meg van adva, mindkét reguláris kifejezés felhasználásra kerül.

--ignore-paths=<regex>;;
	Ez lehetővé teszi egy Perl reguláris kifejezés megadását, amely az
	SVN-ből történő checkoutból kihagyja az összes megfelelő elérési
	utat.  A `--ignore-paths` opciónak minden 'fetch'-nél illeszkednie
	kell (beleértve a 'clone', 'dcommit', 'rebase' stb. miatti
	automatikus fetch-eket is) egy adott repository-n.
+
[verse]
config key: svn-remote.<name>.ignore-paths
+
Ha az ignore-paths konfigurációs kulcs be van állítva, és a parancssori
opció is meg van adva, mindkét reguláris kifejezés felhasználásra kerül.
+
Példák:
+
--
A "doc*" könyvtár kihagyása minden fetch-nél;;
+
------------------------------------------------------------------------
--ignore-paths="^doc"
------------------------------------------------------------------------

Az első szintű könyvtárak "branches" és "tags" alkönyvtárainak kihagyása;;
+
------------------------------------------------------------------------
--ignore-paths="^[^/]+/(?:branches|tags)"
------------------------------------------------------------------------
--

--include-paths=<regex>;;
	Ez lehetővé teszi egy Perl reguláris kifejezés megadását, amely
	miatt az SVN-ből történő checkoutba csak a megfelelő elérési utak
	kerülnek bele.  A `--include-paths` opciónak minden 'fetch'-nél
	illeszkednie kell (beleértve a 'clone', 'dcommit', 'rebase' stb.
	miatti automatikus fetch-eket is) egy adott repository-n.
	A `--ignore-paths` elsőbbséget élvez a `--include-paths`-szal
	szemben.
+
[verse]
config key: svn-remote.<name>.include-paths

--log-window-size=<n>;;
	<n> log-bejegyzést kér le kérésenként a Subversion előzmények
	pásztázásakor. Az alapértelmezés 100. Nagyon nagy Subversion
	repository-k esetén nagyobb értékekre lehet szükség ahhoz, hogy a
	'clone'/'fetch' ésszerű időn belül befejeződjön. Ugyanakkor a túl
	nagy értékek magasabb memóriahasználathoz és kérés-időtúllépésekhez
	vezethetnek.

'clone'::
	Lefuttatja az 'init'-et és a 'fetch'-et.  Automatikusan létrehoz
	egy könyvtárat a neki átadott URL alapneve alapján; vagy ha egy
	második argumentum is át van adva, létrehoz egy könyvtárat, és
	abban dolgozik.  Elfogadja mindazokat az argumentumokat, amelyeket
	az 'init' és a 'fetch' parancsok elfogadnak, kivéve a
	`--fetch-all`-t és a `--parent`-et.  Miután egy repository
	klónozásra került, a 'fetch' parancs képes lesz frissíteni a
	revíziókat anélkül, hogy hatással lenne a munkakönyvtárra; a
	'rebase' parancs pedig képes lesz frissíteni a munkakönyvtárat a
	legutóbbi változtatásokkal.

--preserve-empty-dirs;;
	Létrehoz egy helyőrző fájlt a helyi Git repository-ban minden egyes,
	a Subversionből lekért üres könyvtárhoz.  Ez magában foglalja azokat
	a könyvtárakat is, amelyek úgy válnak üressé, hogy az összes bejegyzés
	eltávolításra kerül a Subversion repository-ban (de maga a könyvtár
	nem).  A helyőrző fájlok szintén követve vannak, és eltávolításra
	kerülnek, ha már nincs rájuk szükség.

--placeholder-filename=<filename>;;
	Beállítja a --preserve-empty-dirs által létrehozott helyőrző fájlok
	nevét.
	Alapértelmezés: ".gitignore"

'rebase'::
	Ez lekéri a revíziókat az aktuális HEAD SVN-szülőjéből, és arra
	rebase-eli az aktuális (SVN-be nem commitolt) munkát.
+
Ez hasonlóan működik, mint az `svn update` vagy a 'git pull', azzal a
különbséggel, hogy a lineáris előzményeket 'git rebase'-zel őrzi meg
'git merge' helyett, hogy könnyebb legyen dcommitolni a 'git svn'-nel.
+
Ez elfogad minden opciót, amelyet a 'git svn fetch' és a 'git rebase'
elfogad.  A `--fetch-all` azonban csak az aktuális [svn-remote]-ból kér
le, nem az összes [svn-remote] definícióból.
+
A 'git rebase'-hez hasonlóan ez megköveteli, hogy a munkakönyvtár tiszta
legyen, és ne legyenek commitolatlan változtatások.
+
Ez automatikusan frissíti a rev_map-et, ha szükséges (lásd a lentebbi
FILES szakaszban a '$GIT_DIR/svn/\**/.rev_map.*'-ot a részletekért).

-l;;
--local;;
	Ne kérjen le távolról; csak futtassa le a 'git rebase'-t a legutóbb
	lekért commitra az upstream SVN-ből.

'dcommit'::
	Commitolja az aktuális branch minden egyes diffjét közvetlenül az
	SVN repository-ba, majd rebase-el vagy reset-el (attól függően,
	hogy van-e diff az SVN és a HEAD között, vagy sincs).  Ez minden
	Git commithoz létrehoz egy revíziót az SVN-ben.
+
Ha egy opcionális Git branchnév (vagy egy Git commit-objektum neve) meg
van adva argumentumként, az alparancs a megadott branchen dolgozik, nem
az aktuális branchen.
+
A 'dcommit' használata előnyben részesítendő a (lentebbi) 'set-tree'-vel
szemben.
+
--no-rebase;;
	Commitolás után ne végezzen rebase-t vagy reset-et.
--commit-url <URL>;;
	Commitol erre az SVN URL-re (a teljes elérési útra).  Ennek célja,
	hogy lehetővé tegye a meglévő, egy adott protokollal (pl. `svn://`
	vagy `http://` névtelen olvasáshoz) létrehozott 'git svn'
	repository-k újrafelhasználását, ha egy felhasználó később hozzáférést
	kap egy alternatív protokollhoz (pl. `svn+ssh://` vagy `https://`) a
	commitoláshoz.
+
[verse]
config key: svn-remote.<name>.commiturl
config key: svn.commiturl (felülír minden svn-remote.<name>.commiturl opciót)
+
Vedd figyelembe, hogy a commiturl config kulcs SVN URL-je tartalmazza az
SVN branchet.  Ha inkább egy teljes SVN repository-hoz szeretnél commit
URL-t beállítani, használd helyette a svn-remote.<name>.pushurl-t.
+
Ennek az opciónak bármilyen más célra való használata (ne kérdezd) igen
erősen ellenjavallt.

--mergeinfo=<mergeinfo>;;
	Hozzáadja a megadott merge-információt a dcommit során
	(pl. `--mergeinfo="/branches/foo:1-10"`). Minden svn szerververzió
	képes tárolni ezt az információt (tulajdonságként), és az 1.5-ös
	verziótól kezdve az svn kliensek fel is tudják használni. Ahhoz,
	hogy több branchből is megadj merge-információt, használj egyetlen
	szóköz karaktert a branchek között
	(`--mergeinfo="/branches/foo:1-10 /branches/bar:3,5-6,8"`)
+
[verse]
config key: svn.pushmergeinfo
+
Ez az opció azt eredményezi, hogy a git-svn megpróbálja automatikusan
feltölteni az svn:mergeinfo tulajdonságot az SVN repository-ban, ahol ez
lehetséges. Jelenleg ez csak akkor tehető meg, ha olyan non-fast-forward
merge-eket dcommitolunk, amelyeknél az elsőt kivéve minden szülő már
push-olva lett az SVN-be.

--interactive;;
	Megkéri a felhasználót, hogy erősítse meg, hogy egy patch-halmazt
	valóban el kell-e küldeni az SVN-nek.
	Minden egyes patch-nél válaszolhatunk "yes"-szel (ezt a patchet
	elfogadjuk), "no"-val (ezt a patchet elvetjük), "all"-lal (minden
	patchet elfogadunk), vagy "quit"-tal.
+
A 'git svn dcommit' azonnal visszatér, ha a válasz "no" vagy "quit",
anélkül, hogy bármit is commitolna az SVN-be.

'branch'::
	Létrehoz egy branchet az SVN repository-ban.

-m;;
--message;;
	Lehetővé teszi a commit-üzenet megadását.

-t;;
--tag;;
	Létrehoz egy taget a tags_subdir használatával a git svn init során
	megadott branches_subdir helyett.

-d<path>;;
--destination=<path>;;

	Ha egynél több --branches (vagy --tags) opció volt megadva az
	'init' vagy a 'clone' parancsnak, meg kell adnod annak a branchnek
	(vagy tagnek) a helyét, amelyet az SVN repository-ban létre
	szeretnél hozni.  A <path> megadja, mely elérési utat kell
	használni a branch vagy tag létrehozásához, és illeszkednie kell a
	konfigurált branches vagy tags refspecek egyikének bal oldali
	mintájára.  Ezek a refspecek a következő parancsokkal tekinthetők
	meg
+
	git config --get-all svn-remote.<name>.branches
	git config --get-all svn-remote.<name>.tags
+
ahol a <name> az SVN repository neve, ahogy azt a -R opció adta meg az
'init' számára (vagy alapértelmezés szerint "svn").

--username;;
	Megadja azt az SVN felhasználónevet, amelynek nevében a commit
	végrehajtásra kerül.  Ez az opció felülbírálja a 'username'
	konfigurációs tulajdonságot.

--commit-url;;
	A megadott URL-t használja a célként szolgáló Subversion
	repository-hoz való kapcsolódáshoz.  Ez olyan esetekben hasznos,
	amikor a forrás SVN repository csak olvasható.  Ez az opció
	felülbírálja a 'commiturl' konfigurációs tulajdonságot.
+
	git config --get-all svn-remote.<name>.commiturl
+

--parents;;
	Létrehozza a szülőmappákat. Ez a paraméter egyenértékű az svn cp
	parancsok --parents paraméterével, és nem szabványos repository
	elrendezések esetén hasznos.

'tag'::
	Létrehoz egy taget az SVN repository-ban. Ez a 'branch -t' rövidebb
	alakja.

'log'::
	Ennek meg kell könnyítenie az svn log üzenetek felkutatását, amikor
	svn felhasználók -r/--revision számokra hivatkoznak.
+
Az `svn log' következő funkciói vannak támogatva:
+
--
-r <n>[:<n>];;
--revision=<n>[:<n>];;
	támogatott, a nem numerikus argumentumok nem:
	HEAD, NEXT, BASE, PREV, stb...
-v;;
--verbose;;
	nem teljesen kompatibilis az svn log --verbose kimenetével, de
	elég közel áll hozzá.
--limit=<n>;;
	NEM ugyanaz, mint a --max-count, nem számolja a
	merge-elt/kizárt commitokat
--incremental;;
	támogatott
--
+
Új funkciók:
+
--
--show-commit;;
	a Git commit sha1-jét is megmutatja
--oneline;;
	a --pretty=oneline mi változatunk szerinti verziója
--
+
NOTE: Maga az SVN csak UTC-ben tárolja az időpontokat, semmi mást. A
szokásos svn kliens az UTC időt helyi időre konvertálja (vagy a TZ=
környezeti változó alapján). Ez a parancs ugyanígy viselkedik.
+
Minden más argumentum közvetlenül a 'git log'-nak kerül átadásra

'blame'::
	Megmutatja, hogy melyik revízió és szerző módosította utoljára egy
	fájl minden egyes sorát. Ennek a módnak a kimenete alapértelmezés
	szerint formátum-kompatibilis az `svn blame' kimenetével. Az SVN
	blame parancshoz hasonlóan a munkakönyvtárban lévő helyi,
	commitolatlan változtatások figyelmen kívül vannak hagyva; a fájl
	HEAD revízióbeli verziója kerül annotálásra. Az ismeretlen
	argumentumok közvetlenül a 'git blame'-nek kerülnek átadásra.
+
--git-format;;
	A 'git blame'-mel megegyező formátumban állítja elő a kimenetet, de
	Git commit hash-ek helyett SVN revíziószámokkal. Ebben a módban az
	SVN-be nem commitolt változtatások (beleértve a helyi
	munkakönyvtár-beli szerkesztéseket is) 0-s revízióként jelennek meg.

'find-rev'::
	Ha egy 'rN' formájú SVN revíziószám van megadva, visszaadja a neki
	megfelelő Git commit hash-t (ezt opcionálisan követheti egy
	tree-ish, amely megadja, melyik branchen kell keresni).  Ha egy
	tree-ish van megadva, visszaadja a neki megfelelő SVN
	revíziószámot.
+
-B;;
--before;;
	Ha egy SVN revízió van megadva, nem követel meg pontos egyezést,
	ehelyett megkeresi a megadott revízióban (az aktuális branchen) az
	SVN repository állapotának megfelelő commitot.
+
-A;;
--after;;
	Ha egy SVN revízió van megadva, nem követel meg pontos egyezést; ha
	nincs pontos egyezés, az előzményekben előrehaladva keresve adja
	vissza a legközelebbi találatot.

'set-tree'::
	Ennek a parancsnak a helyett a 'dcommit' használatát érdemes
	megfontolnod.  A megadott commit- vagy tree-objektumokat commitolja
	az SVN-be.  Ez azt feltételezi, hogy a beimportált fetch-adataid
	naprakészek.  Ez az SVN-be történő commitoláskor egyáltalán nem
	próbálkozik patch-eléssel, egyszerűen felülírja a fájlokat a tree-ben
	vagy commitban megadottakkal.  Minden merge-elésnek feltételezés
	szerint a 'git svn' funkcióitól függetlenül kellett megtörténnie.

'create-ignore'::
	Rekurzívan megkeresi az svn:ignore és svn:global-ignores
	tulajdonságokat a könyvtárakon, és nekik megfelelő .gitignore
	fájlokat hoz létre. Az így keletkező fájlok stage-elve vannak
	commitolásra, de nincsenek commitolva. Használd az -r/--revision
	opciót egy adott revízióra való hivatkozáshoz.

'show-ignore'::
	Rekurzívan megkeresi és felsorolja az svn:ignore és
	svn:global-ignores tulajdonságokat a könyvtárakon. A kimenet
	alkalmas arra, hogy a $GIT_COMMON_DIR/info/exclude fájlhoz
	fűzzük.

'mkdirs'::
	Megkísérli újra létrehozni azokat az üres könyvtárakat, amelyeket a
	core Git nem tud követni, a $GIT_DIR/svn/<refname>/unhandled.log
	fájlokban lévő információk alapján.
	Az üres könyvtárak automatikusan újra létrejönnek a "git svn clone"
	és a "git svn rebase" használatakor, így az "mkdirs" olyan
	parancsok után való használatra szolgál, mint a "git checkout"
	vagy a "git reset".
	(További információért lásd a svn-remote.<name>.automkdirs config
	fájl opciót.)

'commit-diff'::
	Commitolja két, a parancssorból megadott tree-ish argumentum
	diffjét.  Ez a parancs nem igényli, hogy egy `git svn init`-elt
	repository-n belül fussunk.  Ez a parancs három argumentumot
	vár: (a) az eredeti tree-t, amelyhez képest a diffet készítjük,
	(b) az új tree eredményt, (c) a cél Subversion repository URL-jét.
	Az utolsó argumentum (URL) elhagyható, ha egy 'git svn'-tudatos
	repository-ból dolgozol (amelyet a 'git svn'-nel `init`-eltek).
	Ehhez kötelező az -r<revision> opció.
+
A commit-üzenet megadható közvetlenül a `-m` vagy `-F` opcióval, vagy
közvetetten a tagből vagy commitból, amikor a második tree-ish egy ilyen
objektumot jelöl, vagy egy szerkesztő meghívásával kerül lekérésre
(lásd a lentebbi `--edit` opciót).

-m <msg>;;
--message=<msg>;;
	A megadott `msg`-t használja commit-üzenetként. Ez az opció
	letiltja a `--edit` opciót.

-F <filename>;;
--file=<filename>;;
	A megadott fájlból veszi a commit-üzenetet. Ez az opció letiltja a
	`--edit` opciót.

'info'::
	Az `svn info' által nyújtotthoz hasonló információkat jelenít meg
	egy fájlról vagy könyvtárról.  Jelenleg nem támogatja a
	-r/--revision argumentumot.  Használd a --url opciót, hogy csak az
	'URL:' mező értékét írja ki.

'proplist'::
	Felsorolja a Subversion repository-ban egy adott fájlról vagy
	könyvtárról tárolt tulajdonságokat.  Használd az -r/--revision
	opciót egy adott Subversion revízióra való hivatkozáshoz.

'propget'::
	Lekéri az első argumentumként megadott Subversion tulajdonságot egy
	fájlhoz.  Egy adott revízió megadható az -r/--revision opcióval.

'propset'::
	Beállítja az első argumentumként megadott Subversion tulajdonságot
	a második argumentumként megadott értékre, a harmadik
	argumentumként megadott fájlnál.
+
Példa:
+
------------------------------------------------------------------------
git svn propset svn:keywords "FreeBSD=%H" devel/py-tipper/Makefile
------------------------------------------------------------------------
+
Ez beállítja az 'svn:keywords' tulajdonságot 'FreeBSD=%H' értékre a
'devel/py-tipper/Makefile' fájlnál.

'show-externals'::
	Megjeleníti a Subversion externals bejegyzéseket.  Használd az
	-r/--revision opciót egy adott revízió megadásához.

'gc'::
	Tömöríti a $GIT_DIR/svn/<refname>/unhandled.log fájlokat, és
	eltávolítja a $GIT_DIR/svn/<refname>/index fájlokat.

'reset'::
	Visszavonja a 'fetch' hatásait a megadott revízióig.  Ez lehetővé
	teszi, hogy újra 'fetch'-elj egy SVN revíziót.  Normál esetben egy
	SVN revízió tartalmának soha nem szabadna megváltoznia, és a
	'reset'-re nem lenne szükség.  Ha azonban az SVN jogosultságok
	megváltoznak, vagy módosítod a --ignore-paths opciódat, egy 'fetch'
	sikertelen lehet "not found in commit" (a fájl korábban nem volt
	látható) vagy "checksum mismatch" (kimaradt egy módosítás) hibával.
	Ha a problémás fájl nem hagyható örökre figyelmen kívül (a
	--ignore-paths használatával), a repo javításának egyetlen módja a
	'reset' használata.
+
Csak a rev_map és a refs/remotes/git-svn változik (lásd a lentebbi
FILES szakaszban a '$GIT_DIR/svn/\**/.rev_map.*'-ot a részletekért).
A 'reset' után futtass egy 'fetch'-et, majd egy 'git reset'-et vagy
'git rebase'-t, hogy a helyi brancheket az új tree-re mozgasd.

-r <n>;;
--revision=<n>;;
	Megadja a megtartandó legutóbbi revíziót.  Minden későbbi revízió
	elvetésre kerül.
-p;;
--parent;;
	A megadott revíziót is elveti, helyette a legközelebbi szülőt
	tartja meg.
Példa:;;
Tegyük fel, hogy helyi változtatásaid vannak a "master"-ben, de újra le
kell kérned az "r2"-t.
+
------------
    r1---r2---r3 remotes/git-svn
                \
                 A---B master
------------
+
Javítsd ki az ignore-paths vagy az SVN jogosultsági problémát, amely
miatt "r2" eleve hiányos lett.  Majd:
+
[verse]
git svn reset -r2 -p
git svn fetch
+
------------
    r1---r2'--r3' remotes/git-svn
      \
       r2---r3---A---B master
------------
+
Ezután javítsd ki a "master"-t 'git rebase'-zel.
NE használj 'git merge'-öt, különben az előzményeid nem lesznek
kompatibilisek egy jövőbeli 'dcommit'-tal!
+
[verse]
git rebase --onto remotes/git-svn A^ master
+
------------
    r1---r2'--r3' remotes/git-svn
                \
                 A'--B' master
------------

OPTIONS
-------

--shared[=(false|true|umask|group|all|world|everybody)]::
--template=<template-directory>::
	Csak az 'init' paranccsal használatos.
	Ezek közvetlenül a 'git init'-nek kerülnek átadásra.

-r <arg>::
--revision <arg>::
	   A 'fetch' paranccsal használatos.
+
Ez lehetővé teszi részleges/csonkolt előzmények revíziótartományainak
támogatását.  A $NUMBER, $NUMBER1:$NUMBER2 (numerikus tartományok),
$NUMBER:HEAD és BASE:$NUMBER egyaránt támogatott.
+
Ez lehetővé teszi részleges tükrök készítését fetch futtatásakor; de
általában nem ajánlott, mert az előzmények egy része kimarad és
elveszik.

-::
--stdin::
	Csak a 'set-tree' paranccsal használatos.
+
Beolvas egy commitlistát a standard bemenetről, és fordított sorrendben
commitolja őket.  Soronként csak a kezdő sha1 kerül beolvasásra, így a
'git rev-list --pretty=oneline' kimenete használható.

--rmdir::
	Csak a 'dcommit', 'set-tree' és 'commit-diff' parancsokkal
	használatos.
+
Eltávolítja a könyvtárakat az SVN tree-ből, ha nem maradt bennük fájl.
Az SVN képes verziózni az üres könyvtárakat, és azok alapértelmezés
szerint nem kerülnek eltávolításra, ha nem maradt fájl bennük. A Git
nem tudja verziózni az üres könyvtárakat.  Ennek a jelzőnek a
bekapcsolása azt eredményezi, hogy az SVN-be történő commit úgy
viselkedik, mint a Git.
+
[verse]
config key: svn.rmdir

-e::
--edit::
	Csak a 'dcommit', 'set-tree' és 'commit-diff' parancsokkal
	használatos.
+
Szerkeszti a commit-üzenetet az SVN-be történő commitolás előtt. Ez
alapértelmezés szerint ki van kapcsolva olyan objektumoknál, amelyek
commitok, és kényszerítve be van kapcsolva tree-objektumok
commitolásakor.
+
[verse]
config key: svn.edit

-l<num>::
--find-copies-harder::
	Csak a 'dcommit', 'set-tree' és 'commit-diff' parancsokkal
	használatos.
+
Mindkettő közvetlenül a 'git diff-tree'-nek kerül átadásra; további
információért lásd: linkgit:git-diff-tree[1].
+
[verse]
config key: svn.l
config key: svn.findcopiesharder

-A<filename>::
--authors-file=<filename>::
	A szintaxis kompatibilis a 'git cvsimport' által használt fájllal,
	de egy üres e-mail cím a '<>' segítségével adható meg:
+
------------------------------------------------------------------------
	loginname = Joe User <user@example.com>
------------------------------------------------------------------------
+
Ha ez az opció meg van adva, és a 'git svn' egy olyan SVN committer
nevet talál, amely nem szerepel az authors-file-ban, a 'git svn'
megszakítja a műveletet. A felhasználónak ekkor hozzá kell adnia a
megfelelő bejegyzést.  Az előző 'git svn' parancs újrafuttatásának
folytatnia kell a műveletet, miután az authors-file módosításra
került.
+
[verse]
config key: svn.authorsfile

--authors-prog=<filename>::
	Ha ez az opció meg van adva, minden olyan SVN committer névhez,
	amely nem szerepel az authors file-ban, a megadott fájl kerül
	végrehajtásra a committer névvel mint első argumentummal.  A
	programtól elvárt, hogy egyetlen sort adjon vissza "Name <email>"
	vagy "Name <>" formában, amelyet úgy kezelünk, mintha az authors
	file-ban szerepelne.
+
Történelmi okokból egy relatív 'filename' előbb az aktuális könyvtárhoz
képest relatívan kerül keresésre az 'init' és a 'clone' esetén, illetve
a munkakönyvtár gyökeréhez képest relatívan a 'fetch' esetén. Ha a
'filename' nem található, úgy kerül keresésre, mint bármely más parancs
a '$PATH'-ban.
+
[verse]
config key: svn.authorsProg

-q::
--quiet::
	Kevésbé bőbeszédűvé teszi a 'git svn'-t. Add meg másodszor is, hogy
	még kevésbé legyen bőbeszédű.

-m::
--merge::
-s<strategy>::
--strategy=<strategy>::
-p::
--rebase-merges::
	Ezek csak a 'dcommit' és a 'rebase' parancsokkal használatosak.
+
Közvetlenül a 'git rebase'-nek kerülnek átadásra, amikor a 'dcommit'
használatakor egy 'git reset' nem alkalmazható (lásd 'dcommit').

-n::
--dry-run::
	Ez a 'dcommit', 'rebase', 'branch' és 'tag' parancsokkal
	használható.
+
'dcommit' esetén kiírja azoknak a Git argumentumoknak a sorát, amelyek
megmutatnák, mely diffek kerülnének commitolásra az SVN-be.
+
'rebase' esetén megjeleníti az aktuális branchhez tartozó upstream svn
repository-hoz társított helyi branchet, valamint annak az svn
repository-nak az URL-jét, amelyből a fetch történni fog.
+
'branch' és 'tag' esetén megjeleníti azokat az URL-eket, amelyek a
másoláshoz lesznek felhasználva a branch vagy tag létrehozásakor.

--use-log-author::
	Amikor svn commitokat kérünk le a Gitbe (a 'fetch', 'rebase' vagy
	'dcommit' műveletek részeként), keresse meg a naplóüzenetben az
	első `From:` sort vagy `Signed-off-by` trailert, és azt használja
	szerzősztringként.
+
[verse]
config key: svn.useLogAuthor

--add-author-from::
	Amikor a Gitből svn-be commitolunk (a 'set-tree' vagy 'dcommit'
	műveletek részeként), ha a meglévő naplóüzenetnek még nincs
	`From:` vagy `Signed-off-by` trailere, fűzzön hozzá egy `From:`
	sort a Git commit szerzősztringje alapján.  Ha ezt használod, a
	`--use-log-author` minden commithoz érvényes szerzősztringet fog
	lekérni.
+
[verse]
config key: svn.addAuthorFrom

ADVANCED OPTIONS
----------------

-i<GIT_SVN_ID>::
--id <GIT_SVN_ID>::
	Ez beállítja a GIT_SVN_ID-t (a környezet használata helyett).  Ez
	lehetővé teszi a felhasználó számára, hogy felülbírálja az
	alapértelmezett refnevet, amelyből egyetlen URL követésekor
	fetch-elni kell.  A 'log' és 'dcommit' parancsoknak már nincs
	szükségük erre a kapcsolóra argumentumként.

-R<remote-name>::
--svn-remote <remote-name>::
	Megadja a használandó [svn-remote "<remote-name>"] szekciót, ez
	lehetővé teszi több SVN repository követését.
	Alapértelmezés: "svn"

--follow-parent::
	Ez az opció csak akkor releváns, ha brancheket követünk (a
	--trunk, --tags, --branches, --stdlayout repository-elrendezési
	opciók egyikének használatával). Minden egyes követett branchnél
	megpróbálja kideríteni, honnan lett a revíziója másolva, és
	megfelelő szülőt állít be a branch első Git commitjában.
	Ez különösen akkor hasznos, amikor egy olyan könyvtárat követünk,
	amelyet a repository-n belül áthelyezgettek.  Ha ez a funkció ki
	van kapcsolva, a 'git svn' által létrehozott branchek mind
	lineárisak lesznek, és nem osztoznak semmilyen előzményen, ami
	azt jelenti, hogy nem lesz információ arról, honnan lettek a
	branchek branch-elve vagy merge-elve.
	Ugyanakkor a hosszú/bonyolult előzmények követése sokáig
	tarthat, így ennek a funkciónak a kikapcsolása felgyorsíthatja a
	klónozási folyamatot. Ez a funkció alapértelmezés szerint be van
	kapcsolva, a kikapcsolásához használd a --no-follow-parent
	opciót.
+
[verse]
config key: svn.followparent

CONFIG FILE-ONLY OPTIONS
------------------------

svn.noMetadata::
svn-remote.<name>.noMetadata::
	Ez megszabadít a 'git-svn-id:' soroktól minden commit végén.
+
Ez az opció csak egyszeri importálásokhoz használható, mivel a
'git svn' metaadatok nélkül nem lesz képes újra fetch-elni. Ezenkívül,
ha elveszíted a '$GIT_DIR/svn/\**/.rev_map.*' fájljaidat, a 'git svn'
nem lesz képes újraépíteni azokat.
+
A 'git svn log' parancs sem fog működni az ezt használó repository-kon.
Ennek használata (remélhetőleg nyilvánvaló okokból) ütközik a
'useSvmProps' opcióval.
+
Ez az opció NEM ajánlott, mivel megnehezíti az SVN revíziószámokra való
régi hivatkozások felkutatását a meglévő dokumentációban, hibajegyekben
és archívumokban. Ha végül az SVN-ről a Gitre való migrálást tervezed,
és biztos vagy abban, hogy elhagyod az SVN előzményeket, fontold meg
inkább a https://github.com/newren/git-filter-repo[git-filter-repo]
használatát.
A filter-repo lehetővé teszi a metaadatok könnyebben olvasható formára
való átalakítását is, valamint a szerzőségi információk újraírását a
nem "svn.authorsFile"-t használók számára.

svn.useSvmProps::
svn-remote.<name>.useSvmProps::
	Ez lehetővé teszi a 'git svn' számára, hogy az SVN::Mirror (vagy az
	svk) segítségével létrehozott tükrökből származó repository URL-eket
	és UUID-kat metaadatként átleképezze.
+
Ha egy SVN revíziónak van egy "svm:headrev" tulajdonsága, valószínű,
hogy a revíziót az SVN::Mirror hozta létre (amelyet az SVK is használ).
A tulajdonság egy repository UUID-t és egy revíziót tartalmaz.  Azt
szeretnénk, ha úgy nézne ki, mintha az eredeti URL-t tükröznénk, ezért
bevezetünk egy segédfüggvényt, amely visszaadja az eredeti identitás
URL-t és UUID-t, és ezt használjuk a commit-üzenetekben lévő metaadatok
generálásakor.

svn.useSvnsyncProps::
svn-remote.<name>.useSvnsyncprops::
	Hasonló a useSvmProps opcióhoz; ez az SVN 1.4.x-től kezdve terjesztett
	svnsync(1) parancs felhasználói számára készült.

svn-remote.<name>.rewriteRoot::
	Ez lehetővé teszi a felhasználók számára, hogy alternatív URL-ekből
	hozzanak létre repository-kat.  Például egy adminisztrátor a
	szerveren helyileg futtathatja a 'git svn'-t (file://-n keresztül
	elérve), de a repository-t egy nyilvános http:// vagy svn:// URL-lel
	szeretné terjeszteni a metaadatokban, hogy a felhasználói a
	nyilvános URL-t lássák.

svn-remote.<name>.rewriteUUID::
	Hasonló a useSvmProps opcióhoz; ez azoknak a felhasználóknak
	készült, akiknek manuálisan kell átleképezniük az UUID-t. Ez
	olyan helyzetekben lehet hasznos, amikor az eredeti UUID sem a
	useSvmProps, sem a useSvnsyncProps révén nem elérhető.

svn-remote.<name>.pushurl::

	A Git `remote.<name>.pushurl`-jához hasonlóan ez a kulcs olyan
	esetekre lett tervezve, amikor az 'url' egy SVN repository-ra
	mutat egy csak olvasható protokollon keresztül, hogy egy
	alternatív olvasás/írás protokollt biztosítson. Feltételezzük,
	hogy mindkét kulcs ugyanarra a repository-ra mutat. A 'commiturl'-
	tól eltérően a 'pushurl' egy alap elérési út. Ha akár a
	'commiturl', akár a 'pushurl' használható lenne, a 'commiturl'
	élvez elsőbbséget.

svn.brokenSymlinkWorkaround::
	Ez kikapcsolja a potenciálisan költséges ellenőrzéseket, amelyek a
	hibás kliensek által az SVN-be commitolt hibás symlinkek
	megkerülésére szolgálnak.  Állítsd ezt az opciót "false"-ra, ha
	olyan SVN repository-t követsz, amelyben sok üres blob van, amelyek
	nem symlinkek.  Ez az opció megváltoztatható, amíg a 'git svn' fut,
	és a legközelebb lekért revíziónál lép hatályba.  Ha nincs
	beállítva, a 'git svn' azt feltételezi, hogy ez az opció "true".

svn.pathnameencoding::
	Ez utasítja a git svn-t, hogy az elérési útneveket egy adott
	kódolásra kódolja át. Windows-felhasználók, valamint nem utf8
	locale-okban dolgozók használhatják a nem ASCII karaktereket
	tartalmazó, sérült fájlnevek elkerülésére. Az érvényes kódolások
	azok, amelyeket a Perl Encode modulja támogat.

svn-remote.<name>.automkdirs::
	Normál esetben a "git svn clone" és a "git svn rebase" parancsok
	megpróbálják újra létrehozni a Subversion repository-ban lévő üres
	könyvtárakat.  Ha ez az opció "false"-ra van állítva, akkor az üres
	könyvtárak csak akkor jönnek létre, ha a "git svn mkdirs" parancs
	explicit módon fut le.  Ha nincs beállítva, a 'git svn' azt
	feltételezi, hogy ez az opció "true".

Mivel a noMetadata, rewriteRoot, rewriteUUID, useSvnsyncProps és
useSvmProps opciók mind hatással vannak a 'git svn' által generált és
használt metaadatokra, ezeket *kötelező* a konfigurációs fájlban
beállítani, mielőtt bármilyen előzmény importálásra kerülne, és ezeket
a beállításokat, miután be lettek állítva, soha nem szabad megváltoztatni.

Ezenkívül ezen opciók közül svn-remote szekciónként csak egy
használható, mivel hatással vannak a 'git-svn-id:' metaadat-sorra,
kivéve a rewriteRoot-ot és a rewriteUUID-t, amelyek együtt is
használhatók.


BASIC EXAMPLES
--------------

Egy Subversion által kezelt projekt trunkjának követése és az abba való
közreműködés (a tagek és branchek figyelmen kívül hagyásával):

------------------------------------------------------------------------
# Clone a repo (like git clone):
	git svn clone http://svn.example.com/project/trunk
# Enter the newly cloned directory:
	cd trunk
# You should be on master branch, double-check with 'git branch'
	git branch
# Do some work and commit locally to Git:
	git commit ...
# Something is committed to SVN, rebase your local changes against the
# latest changes in SVN:
	git svn rebase
# Now commit your changes (that were committed previously using Git) to SVN,
# as well as automatically updating your working HEAD:
	git svn dcommit
# Append svn:ignore and svn:global-ignores settings to the default Git exclude file:
	git svn show-ignore >> .git/info/exclude
------------------------------------------------------------------------

Egy teljes, Subversion által kezelt projekt követése és az abba való
közreműködés (trunkkal, tagekkel és branchekkel együtt):

------------------------------------------------------------------------
# Clone a repo with standard SVN directory layout (like git clone):
	git svn clone http://svn.example.com/project --stdlayout --prefix svn/
# Or, if the repo uses a non-standard directory layout:
	git svn clone http://svn.example.com/project -T tr -b branch -t tag --prefix svn/
# View all branches and tags you have cloned:
	git branch -r
# Create a new branch in SVN
	git svn branch waldo
# Reset your master to trunk (or any other branch, replacing 'trunk'
# with the appropriate name):
	git reset --hard svn/trunk
# You may only dcommit to one branch/tag/trunk at a time.  The usage
# of dcommit/rebase/show-ignore should be the same as above.
------------------------------------------------------------------------

A kezdeti 'git svn clone' meglehetősen időigényes lehet (különösen nagy
Subversion repository-k esetén). Ha több ember (vagy egy ember több
géppel) szeretné a 'git svn'-t ugyanazzal a Subversion repository-val
való interakcióra használni, elvégezheted a kezdeti 'git svn clone'-t
egy szerveren lévő repository-ra, majd mindenki lekérheti azt a
repository-t 'git clone'-nal:

------------------------------------------------------------------------
# Do the initial import on a server
	ssh server "cd /pub && git svn clone http://svn.example.com/project [options...]"
# Clone locally - make sure the refs/remotes/ space matches the server
	mkdir project
	cd project
	git init
	git remote add origin server:/pub/project
	git config --replace-all remote.origin.fetch '+refs/remotes/*:refs/remotes/*'
	git fetch
# Prevent fetch/pull from remote Git server in the future,
# we only want to use git svn for future updates
	git config --remove-section remote.origin
# Create a local branch from one of the branches just fetched
	git checkout -b master FETCH_HEAD
# Initialize 'git svn' locally (be sure to use the same URL and
# --stdlayout/-T/-b/-t/--prefix options as were used on server)
	git svn init http://svn.example.com/project [options...]
# Pull the latest changes from Subversion
	git svn rebase
------------------------------------------------------------------------

REBASE VS. PULL/MERGE
---------------------
Az integrálatlan commitok egy 'git svn' branchhel való szinkronizálásához
inkább a 'git svn rebase'-t vagy a 'git rebase'-t részesítsd előnyben a
'git pull'-lal vagy a 'git merge'-dzsel szemben. Ha így teszel, az
integrálatlan commitok előzményei lineárisak maradnak az upstream SVN
repository-hoz képest, és lehetővé teszik az előnyben részesített
'git svn dcommit' alparancs használatát az integrálatlan commitok
SVN-be való visszaküldéséhez.

Eredetileg a 'git svn' azt javasolta, hogy a fejlesztők pull-oljanak
vagy merge-eljenek a 'git svn' branchből.  Ez azért volt, mert a szerző
a `git svn set-tree B`-t részesítette előnyben egyetlen HEAD
commitolásához, a `git svn set-tree A..B` jelöléssel szemben, amely
több commit commitolására szolgál. A 'git pull' vagy a 'git merge'
`git svn set-tree A..B`-vel való használata azt eredményezi, hogy a
nem lineáris előzmények ellaposodnak az SVN-be történő commitoláskor,
és ez oda vezethet, hogy merge commitok váratlanul visszavonnak korábbi
commitokat az SVN-ben.

MERGE TRACKING
--------------
Bár a 'git svn' képes követni a másolási előzményeket (beleértve a
brancheket és a tageket) a standard elrendezést alkalmazó
repository-knál, még nem képes reprezentálni azt a merge-előzményt,
amely a git belsejében történt, visszafelé az SVN felhasználói felé.
Ezért ajánlott, hogy a felhasználók az előzményeket a lehető
legjobban lineárisan tartsák a Giten belül, hogy megkönnyítsék az
SVN-nel való kompatibilitást (lásd a lentebbi CAVEATS szakaszt).

HANDLING OF SVN BRANCHES
------------------------
Ha a 'git svn' branchek fetch-elésére van konfigurálva (és a
--follow-branches hatályban van), néha egyetlen SVN branchhez több
Git branchet is létrehoz, ahol a további branchek neve
'branchname@nnn' formájú (ahol az nnn egy SVN revíziószám).  Ezek a
további branchek akkor jönnek létre, ha a 'git svn' nem talál szülő
commitot egy SVN branch első commitjához, hogy a branchet a többi
branch előzményeihez kapcsolja.

Normál esetben egy SVN branch első commitja egy másolási műveletből áll.
A 'git svn' beolvassa ezt a commitot, hogy megkapja azt az SVN
revíziót, amelyből a branch létrejött. Ezután megpróbálja megtalálni
az ennek az SVN revíziónak megfelelő Git commitot, és azt használja a
branch szülőjeként. Előfordulhat azonban, hogy nincs megfelelő Git
commit, amely szülőként szolgálhatna.  Ez többek között akkor
fordul elő, ha az SVN branch egy olyan revízió másolata, amelyet a
'git svn' nem fetch-elt le (pl. mert egy régi revízió volt, amelyet a
`--revision`-nel kihagytak), vagy ha az SVN-ben egy olyan könyvtár lett
másolva, amelyet a 'git svn' nem követ (mint például egy egyáltalán
nem követett branch, vagy egy követett branch egy alkönyvtára). Ezekben
az esetekben a 'git svn' továbbra is létrehoz egy Git branchet, de
ahelyett, hogy egy meglévő Git commitot használna a branch szülőjeként,
beolvassa annak a könyvtárnak az SVN előzményeit, amelyből a branch
másolva lett, és megfelelő Git commitokat hoz létre.  Ezt jelzi az
"Initializing parent: <branchname>" üzenet.

Ezenkívül létrehoz egy speciális, '<branchname>@<SVN-Revision>' nevű
branchet, ahol az <SVN-Revision> az az SVN revíziószám, amelyből a
branch másolva lett.  Ez a branch az újonnan létrehozott
szülőcommitjára fog mutatni a branchnek.  Ha az SVN-ben a branch
törölve, majd később egy másik verzióból újra létrehozva lett, több
ilyen, '@'-ot tartalmazó branch is lesz.

Vedd figyelembe, hogy ez azt jelentheti, hogy egyetlen SVN revízióhoz
több Git commit is létrejön.

Egy példa: egy standard trunk/tags/branches elrendezésű SVN
repository-ban egy trunk/sub könyvtár jön létre az r.100-ban.
Az r.200-ban a trunk/sub branch-elésre kerül azáltal, hogy átmásolják a
branches/-be. A 'git svn clone -s' ekkor létrehoz egy 'sub' branchet.
Létrehoz továbbá új Git commitokat r.100-tól r.199-ig, és ezeket
használja a 'sub' branch előzményeként. Így minden egyes r.100-tól
r.199-ig terjedő revízióhoz két Git commit tartozik majd (az egyik a
trunk/-ot, a másik a trunk/sub/-ot tartalmazza). Végül létrehoz egy
'sub@200' branchet, amely a 'sub' branch új szülőcommitjára mutat
(azaz az r.200 és a trunk/sub/ commitjára).

CAVEATS
-------

Az egyszerűség kedvéért, és a Subversionnel való együttműködés
érdekében ajánlott, hogy minden 'git svn' felhasználó közvetlenül az
SVN szerverről klónozzon, fetch-eljen és dcommitoljon, és kerülje az
összes 'git clone'/'pull'/'merge'/'push' műveletet a Git repository-k
és branchek között.  A kódcserének a Git branchek és felhasználók
között az ajánlott módja a 'git format-patch' és a 'git am', vagy
egyszerűen az SVN repository-ba való 'dcommit'olás.

A 'git merge' vagy a 'git pull' futtatása NEM ajánlott egy olyan
branchen, amelyről 'dcommit'olni tervezel, mert a Subversion
felhasználók nem láthatják az általad végzett merge-eket.  Továbbá, ha
egy olyan Git branchből merge-elsz vagy pull-olsz, amely egy SVN branch
tükre, a 'dcommit' rossz branchbe commitolhat.

Ha mégis merge-elsz, vedd figyelembe a következő szabályt: a
'git svn dcommit' megpróbál a következőben megnevezett SVN commit
tetejére commitolni:

------------------------------------------------------------------------
git log --grep=^git-svn-id: --first-parent -1
------------------------------------------------------------------------

Ezért 'biztosítanod kell', hogy annak a branchnek a legutóbbi commitja,
amelybe dcommitolni szeretnél, a merge 'első' szülője legyen.
Ellenkező esetben káosz keletkezik, különösen, ha az első szülő egy
régebbi commit ugyanazon az SVN branchen.

A 'git clone' nem klónozza a refs/remotes/ hierarchia alatti
brancheket, sem semmilyen 'git svn' metaadatot vagy configot.  Így a
'git svn' segítségével létrehozott és kezelt repository-knak 'rsync'-et
kell használniuk a klónozáshoz, ha egyáltalán klónozásra kerül sor.

Mivel a 'dcommit' belsőleg rebase-t használ, minden olyan Git branch,
amelyre 'dcommit' előtt 'git push'-t végzel, meg fogja követelni a
remote repository-n lévő meglévő ref felülírásának kikényszerítését.
Ezt általában rossz gyakorlatnak tekintik, a részletekért lásd a
linkgit:git-push[1] dokumentációját.

Ne használd a linkgit:git-commit[1] --amend opcióját egy már
dcommitolt változtatáson.  Rossz gyakorlatnak számít --amendelni
olyan commitokat, amelyeket már pusholtál egy remote repository-ba más
felhasználók számára, és az SVN-es dcommit is analóg ezzel.

Egy SVN repository klónozásakor, ha a repository-elrendezést leíró
opciók egyike sem (--trunk, --tags, --branches, --stdlayout) van
használva, a 'git svn clone' egy teljesen lineáris előzményű Git
repository-t hoz létre, ahol a branchek és tagek külön könyvtárakként
jelennek meg a munkakönyvtárban.  Bár ez a legegyszerűbb módja annak,
hogy egy teljes repository másolatát megszerezzük, sok branchet
tartalmazó projektek esetén ez egy sokkal nagyobb munkakönyvtárt
eredményez, mint pusztán a trunk. Így a standard könyvtárstruktúrát
(trunk/branches/tags) használó projekteknél a `--stdlayout` opcióval
való klónozás ajánlott. Ha a projekt nem szabványos struktúrát használ,
és/vagy ha a branchek és tagek nem szükségesek, a legegyszerűbb csak
egyetlen könyvtárat (jellemzően a trunkot) klónozni, bármilyen
repository-elrendezési opció megadása nélkül.  Ha a branchekkel és
tagekkel együtt a teljes előzményre szükség van, a `--trunk` /
`--branches` / `--tags` opciókat kell használni.

Több --branches vagy --tags használatakor a 'git svn' nem kezeli
automatikusan a névütközéseket (például ha két különböző elérési
útról származó branchnek ugyanaz a neve, vagy ha egy branchnek és egy
tagnek ugyanaz a neve).  Ezekben az esetekben használd az 'init'-et a
Git repository-d beállításához, majd az első 'fetch' előtt szerkeszd a
$GIT_DIR/config fájlt úgy, hogy a branchek és tagek különböző
névterekhez legyenek társítva.  Például:

	branches = stable/*:refs/remotes/svn/stable/*
	branches = debug/*:refs/remotes/svn/debug/*

CONFIGURATION
-------------

A 'git svn' az [svn-remote] konfigurációs információkat a repository
$GIT_DIR/config fájljában tárolja.  Ez hasonló a core Git [remote]
szekcióihoz, azzal a különbséggel, hogy a 'fetch' kulcsok nem
fogadnak el glob argumentumokat; ehelyett a 'branches' és a 'tags'
kulcsok kezelik ezeket.  Mivel néhány SVN repository furcsa módon,
több projekttel van konfigurálva, az alább felsoroltakhoz hasonló glob
kiterjesztések megengedettek:

------------------------------------------------------------------------
[svn-remote "project-a"]
	url = http://server.org/svn
	fetch = trunk/project-a:refs/remotes/project-a/trunk
	branches = branches/*/project-a:refs/remotes/project-a/branches/*
	branches = branches/release_*:refs/remotes/project-a/branches/release_*
	branches = branches/re*se:refs/remotes/project-a/branches/*
	tags = tags/*/project-a:refs/remotes/project-a/tags/*
------------------------------------------------------------------------

Vedd figyelembe, hogy a helyi ref `*` (csillag) helyettesítő
karakterének (a `:`-tól jobbra) *kötelezően* a legjobb oldali elérési
út-komponensnek kell lennie; a remote helyettesítő karakter viszont
bárhol lehet, amíg önálló elérési út-komponens (amelyet `/` vagy sorvég
határol).   Az ilyen típusú konfigurációt az 'init' nem hozza létre
automatikusan, kézzel, szövegszerkesztővel vagy a 'git config'
használatával kell megadni.

Azt is vedd figyelembe, hogy szavanként csak egy csillag megengedett.
Például:

	branches = branches/re*se:refs/remotes/project-a/branches/*

illeszkedni fog a 'release', 'rese', 're123se' branchekre, azonban

	branches = branches/re*s*e:refs/remotes/project-a/branches/*

hibát fog eredményezni.

Az is lehetséges, hogy a branchek vagy tagek egy részhalmazát kérjük
le, kapcsos zárójelek közötti, vesszővel elválasztott névlista
használatával. Például:

------------------------------------------------------------------------
[svn-remote "huge-project"]
	url = http://server.org/svn
	fetch = trunk/src:refs/remotes/trunk
	branches = branches/{red,green}/src:refs/remotes/project-a/branches/*
	tags = tags/{1.0,2.0}/src:refs/remotes/project-a/tags/*
------------------------------------------------------------------------

Több fetch, branches és tags kulcs is támogatott:

------------------------------------------------------------------------
[svn-remote "messy-repo"]
	url = http://server.org/svn
	fetch = trunk/project-a:refs/remotes/project-a/trunk
	fetch = branches/demos/june-project-a-demo:refs/remotes/project-a/demos/june-demo
	branches = branches/server/*:refs/remotes/project-a/branches/*
	branches = branches/demos/2011/*:refs/remotes/project-a/2011-demos/*
	tags = tags/server/*:refs/remotes/project-a/tags/*
------------------------------------------------------------------------

Egy branch létrehozása egy ilyen konfigurációban megköveteli annak
egyértelműsítését, hogy melyik helyet kell használni, a -d vagy a
--destination kapcsolóval:

------------------------------------------------------------------------
$ git svn branch -d branches/server release-2-3-0
------------------------------------------------------------------------

Vedd figyelembe, hogy a git-svn nyilvántartja azt a legmagasabb
revíziót, amelyben egy branch vagy tag megjelent. Ha a branchek vagy
tagek részhalmaza a fetch után megváltozik, a $GIT_DIR/svn/.metadata
fájlt manuálisan szerkeszteni kell a branches-maxRev és/vagy a
tags-maxRev megfelelő eltávolításához (vagy visszaállításához).

FILES
-----
$GIT_DIR/svn/\**/.rev_map.*::
	Leképezés a Subversion revíziószámok és a Git commit-nevek között.
	Egy olyan repository-ban, ahol a noMetadata opció nincs beállítva,
	ez újraépíthető a minden commit végén található git-svn-id: sorokból
	(a részletekért lásd a fenti 'svn.noMetadata' szakaszt).
+
A 'git svn fetch' és a 'git svn rebase' automatikusan frissíti a
rev_map-et, ha hiányzik vagy nem naprakész.  A 'git svn reset'
automatikusan visszatekeri.

BUGS
----

Az svn:executable kivételével minden SVN tulajdonságot figyelmen kívül
hagyunk.  Minden nem kezelt tulajdonság naplózásra kerül a
$GIT_DIR/svn/<refname>/unhandled.log fájlba.

Az átnevezett és másolt könyvtárakat a Git nem érzékeli, ezért nem
kerülnek követésre az SVN-be történő commitoláskor.  Nem tervezem ennek
támogatásának hozzáadását, mivel meglehetősen nehéz és időigényes
minden lehetséges szélsőséges esetre működővé tenni (a Git sem teszi
ezt meg). Az átnevezett és másolt fájlok commitolása teljes mértékben
támogatott, ha elég hasonlóak ahhoz, hogy a Git felismerje őket.

Az SVN-ben lehetséges (bár nem ajánlott) egy taghez tartozó
változtatásokat commitolni (mivel egy tag csupán egy könyvtármásolat,
így technikailag ugyanaz, mint egy branch). Egy SVN repository
klónozásakor a 'git svn' nem tudhatja, hogy egy ilyen, taghez tartozó
commit meg fog-e történni a jövőben. Ezért óvatosan jár el, és minden
SVN taget branchként importál, a tag nevét 'tags/' előtaggal látva el.

SEE ALSO
--------
linkgit:git-rebase[1]

GIT
---
A linkgit:git[1] csomag része
