git-filter-branch(1)
====================

NAME
----
git-filter-branch - Branchek újraírása

SYNOPSIS
--------
[verse]
'git filter-branch' [--setup <command>] [--subdirectory-filter <directory>]
	[--env-filter <command>] [--tree-filter <command>]
	[--index-filter <command>] [--parent-filter <command>]
	[--msg-filter <command>] [--commit-filter <command>]
	[--tag-name-filter <command>] [--prune-empty]
	[--original <namespace>] [-d <directory>] [-f | --force]
	[--state-branch <branch>] [--] [<rev-list-options>...]

WARNING
-------
A 'git filter-branch' rengeteg buktatót rejt, amelyek nem nyilvánvaló módon
torzíthatják el a szándékolt előzmény-újraírást (és mivel a teljesítménye
kifejezetten gyenge, kevés időd marad az ilyen problémák kivizsgálására).
Ezek a biztonsági és teljesítménybeli problémák nem javíthatók visszafelé
kompatibilis módon, ezért a használata nem ajánlott. Kérjük, használj
alternatív előzmény-szűrő eszközt, például a
https://github.com/newren/git-filter-repo/[git filter-repo]-t. Ha mégis
szükséged van a 'git filter-branch' használatára, kérjük, olvasd el
figyelmesen a <<SAFETY>> (és a <<PERFORMANCE>>) szakaszt, hogy megismerd a
filter-branch buktatóit, majd éberen kerüld el az ott felsorolt veszélyeket,
amennyire ésszerűen lehetséges.

DESCRIPTION
-----------
Lehetővé teszi, hogy átírd a Git revíziós előzményeket a `<rev-list-options>`-ban
megadott branchek átírásával, egyéni szűrőket alkalmazva minden egyes revízióra.
Ezek a szűrők módosíthatják az egyes fákat (pl. egy fájl eltávolításával vagy
egy perl-átírás minden fájlon való futtatásával), vagy az egyes commitokra
vonatkozó információkat. Egyébként minden információ (beleértve az eredeti
commit-időpontokat vagy a merge-információt) megmarad.

A parancs csak a parancssorban megadott _pozitív_ referenciákat írja át
(pl. ha az `a..b`-t adod meg, csak a `b` íródik át). Ha nem adsz meg
szűrőt, a commitok mindenféle változtatás nélkül lesznek újra commitolva,
aminek normál esetben nincs hatása. Ennek ellenére ez a jövőben hasznos
lehet néhány Git-hiba vagy hasonló kompenzálására, ezért ez a használat
megengedett.

*NOTE*: Ez a parancs figyelembe veszi a `.git/info/grafts` fájlt és a
`refs/replace/` névtérben lévő referenciákat.
Ha vannak grafts-jaid vagy helyettesítő referenciáid, e parancs futtatása
végleges állapotúvá teszi őket.

*WARNING*! Az átírt előzmény minden objektumhoz más objektumnevet fog kapni,
és nem fog konvergálni az eredeti branch-csel. Nem fogod tudni egyszerűen
push-olni és terjeszteni az átírt branchet az eredeti branch tetején.
Kérjük, ne használd ezt a parancsot, ha nem ismered a teljes hatásait,
és amúgy is kerüld a használatát, ha egy egyszerű, önálló commit is elég
lenne a probléma megoldásához. (A megjelentetett előzmény átírásáról
további információért lásd a linkgit:git-rebase[1] "RECOVERING FROM
UPSTREAM REBASE" szakaszát.)

Mindig ellenőrizd, hogy az átírt verzió helyes-e: az eredeti referenciák,
ha eltérnek az átírtaktól, a 'refs/original/' névtérben lesznek tárolva.

Vedd figyelembe, hogy mivel ez a művelet nagyon I/O-igényes, jó ötlet
lehet a `-d` opcióval a lemezen kívülre irányítani az ideiglenes
könyvtárat, pl. tmpfs-re. A visszajelzések szerint a gyorsulás nagyon
szembetűnő.


Szűrők
~~~~~~

A szűrők az alább felsorolt sorrendben kerülnek alkalmazásra. A `<command>`
argumentum mindig a shell kontextusában, az 'eval' paranccsal kerül
kiértékelésre (a commit-szűrő figyelemre méltó kivételével, technikai okokból).
Ezt megelőzően a `$GIT_COMMIT` környezeti változó az átírás alatt álló commit
azonosítójára lesz állítva. Emellett a GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL,
GIT_AUTHOR_DATE, GIT_COMMITTER_NAME, GIT_COMMITTER_EMAIL és GIT_COMMITTER_DATE
az aktuális commitból kerül átvételre, és exportálásra kerül a környezetbe,
hogy befolyásolja a szerző és a committer azonosítóját a szűrők lefutása után
a linkgit:git-commit-tree[1] által létrehozott helyettesítő commit esetében.

Ha a `<command>` bármelyik kiértékelése nem nulla kilépési státuszt ad
vissza, a teljes művelet megszakad.

Elérhető egy 'map' függvény, amely egy „eredeti sha1 azonosító" argumentumot
vár, és egy „átírt sha1 azonosítót" ad vissza, ha a commit már át lett írva,
egyébként pedig az „eredeti sha1 azonosítót"; a 'map' függvény több
azonosítót is visszaadhat, külön sorokban, ha a commit-szűrőd több commitot
is kibocsátott.


OPTIONS
-------

--setup <command>::
	Ez nem egy valódi, minden commitra lefuttatott szűrő, hanem egy
	egyszeri beállítás közvetlenül a ciklus előtt. Ezért még nincsenek
	definiálva commit-specifikus változók. Az itt definiált függvények
	vagy változók a következő szűrő-lépésekben felhasználhatók vagy
	módosíthatók, kivéve a commit-szűrőt, technikai okokból.

--subdirectory-filter <directory>::
	Csak azt az előzményt vizsgálja, amely érinti a megadott
	alkönyvtárat. Az eredmény ezt a könyvtárat (és csak ezt) fogja
	tartalmazni projektgyökérként. Maga után vonja a <<Remap_to_ancestor>>-t.

--env-filter <command>::
	Ez a szűrő akkor használható, ha csak azt a környezetet kell
	módosítanod, amelyben a commit végrehajtásra kerül. Konkrétan a
	szerző/committer név/e-mail/időpont környezeti változóit
	szeretnéd átírni (a részletekért lásd a linkgit:git-commit-tree[1]-et).

--tree-filter <command>::
	Ez a fa és a tartalmának átírására szolgáló szűrő. Az argumentum
	kiértékelése a shellben történik, a munkakönyvtárral a checkoutolt
	fa gyökerére állítva. Az új fa ezután úgy kerül felhasználásra,
	ahogy van (az új fájlok automatikusan hozzáadásra, az eltűnt
	fájlok automatikusan eltávolításra kerülnek - sem a .gitignore
	fájloknak, sem semmilyen más figyelmen kívül hagyási szabálynak
	*NINCS SEMMILYEN HATÁSA*!).

--index-filter <command>::
	Ez az index átírására szolgáló szűrő. Hasonló a fa-szűrőhöz, de
	nem checkoutolja ki a fát, ami sokkal gyorsabbá teszi. Gyakran
	használják a `git rm --cached --ignore-unmatch ...` paranccsal
	együtt, lásd az EXAMPLES szakaszt lentebb. A bonyolultabb esetekhez
	lásd a linkgit:git-update-index[1]-et.

--parent-filter <command>::
	Ez a commit szülőlistájának átírására szolgáló szűrő. A szülő-
	stringet a standard bemeneten kapja meg, és az új szülő-stringet
	kell a standard kimenetre kiírnia. A szülő-string a
	linkgit:git-commit-tree[1]-ben leírt formátumban van: üres a
	kezdő commit esetén, "-p parent" egy normál commitnál, és
	"-p parent1 -p parent2 -p parent3 ..." egy merge-commitnál.

--msg-filter <command>::
	Ez a commit-üzenetek átírására szolgáló szűrő. Az argumentum
	kiértékelése a shellben történik, az eredeti commit-üzenettel a
	standard bemeneten; a standard kimenete lesz az új commit-üzenet.

--commit-filter <command>::
	Ez a commit végrehajtására szolgáló szűrő.
	Ha ez a szűrő meg van adva, akkor a 'git commit-tree' parancs
	helyett ezt hívja meg a rendszer, "<TREE_ID> [(-p
	<PARENT_COMMIT_ID>)...]" alakú argumentumokkal, a naplóüzenettel
	a standard bemeneten. A standard kimeneten a commit-azonosítót várja.
+
Speciális bővítésként a commit-szűrő több commit-azonosítót is
kibocsáthat; ebben az esetben az eredeti commit újraírt gyermekeinek
mindegyikük szülőjük lesz.
+
Ebben a szűrőben használhatod a 'map' kényelmi függvényt, és más
kényelmi függvényeket is. Például a 'skip_commit "$@"' meghívása
kihagyja az aktuális commitot (de a változtatásait nem! Ha azt
szeretnéd, használd inkább a 'git rebase'-t).
+
Használhatod a `git_commit_non_empty_tree "$@"` függvényt is a
`git commit-tree "$@"` helyett, ha nem akarod megtartani azokat az
egyetlen szülővel rendelkező commitokat, amelyek nem változtatnak a fán.

--tag-name-filter <command>::
	Ez a tagnevek átírására szolgáló szűrő. Ha meg van adva,
	minden olyan tag-referenciára meghívásra kerül, amely egy
	újraírt objektumra mutat (vagy egy olyan tag-objektumra, amely
	egy újraírt objektumra mutat). Az eredeti tagnév a standard
	bemeneten érkezik, az új tagnevet a standard kimeneten várja.
+
Az eredeti tagek nem törlődnek, de felülírhatók; használd a
"--tag-name-filter cat" beállítást, ha egyszerűen csak frissíteni
akarod a tageket. Ebben az esetben légy nagyon óvatos, és győződj
meg róla, hogy a régi tagekről van biztonsági mentésed, arra az
esetre, ha az átalakítás félresikerülne.
+
A tag-objektumok szinte megfelelő újraírása támogatott. Ha a taghez
üzenet tartozik, egy új tag-objektum jön létre ugyanazzal az
üzenettel, szerzővel és időbélyeggel. Ha a taghez aláírás tartozik,
az aláírás eltávolításra kerül. Az aláírások megőrzése definíció
szerint lehetetlen. Az ok, amiért ez csak "szinte" megfelelő, az,
hogy ideális esetben, ha a tag nem változott (ugyanarra az objektumra
mutat, ugyanaz a neve stb.), meg kellene tartania az esetleges
aláírását. Ez nincs így, az aláírások mindig eltávolításra kerülnek,
vevő vigyázz. Az sem támogatott, hogy megváltoztasd a szerzőt vagy az
időbélyeget (sem pedig a tag üzenetét, ami azt illeti). Az olyan
tagek, amelyek más tagekre mutatnak, úgy lesznek újraírva, hogy a
mögöttes commitra mutassanak.

--prune-empty::
	Egyes szűrők üres, a fát érintetlenül hagyó commitokat hoznak
	létre. Ez a kapcsoló utasítja a git-filter-branch-et, hogy
	távolítsa el az ilyen commitokat, ha pontosan egy vagy nulla
	nem-eltávolított szülőjük van; a merge-commitok tehát épen
	maradnak. Ez a kapcsoló nem használható a `--commit-filter`-rel
	együtt, bár ugyanez a hatás elérhető a `git_commit_non_empty_tree`
	függvény commit-szűrőben való használatával.

--original <namespace>::
	Ezzel a kapcsolóval állítható be az a névtér, ahol az eredeti
	commitok tárolásra kerülnek. Az alapértelmezett érték a
	'refs/original'.

-d <directory>::
	Ezzel a kapcsolóval állítható be az újraíráshoz használt
	ideiglenes könyvtár útvonala. Fa-szűrő alkalmazásakor a
	parancsnak ideiglenesen ki kell checkoutolnia a fát egy
	könyvtárba, ami nagy projektek esetén jelentős helyet
	foglalhat. Alapértelmezés szerint ezt a `.git-rewrite/`
	könyvtárban teszi, de ezzel a paraméterrel felülbírálható ez
	a választás.

-f::
--force::
	A 'git filter-branch' megtagadja az indulást, ha már létezik
	az ideiglenes könyvtár, vagy ha már vannak 'refs/original/'-lal
	kezdődő referenciák, kivéve ha kényszerítjük.

--state-branch <branch>::
	Ez a kapcsoló azt eredményezi, hogy a régi és az új objektumok
	közötti leképezés a megnevezett branchről töltődik be induláskor,
	és egy új commitként kerül mentésre erre a branchre kilépéskor,
	lehetővé téve nagy fák inkrementális feldolgozását. Ha a
	'<branch>' nem létezik, létre lesz hozva.

<rev-list options>...::
	Argumentumok a 'git rev-list' számára. Az ezekkel a kapcsolókkal
	megadott összes pozitív referencia újraírásra kerül. Megadhatsz
	olyan kapcsolókat is, mint a `--all`, de a `--`-t kell használnod,
	hogy elválaszd őket a 'git filter-branch' kapcsolóitól. Maga után
	vonja a <<Remap_to_ancestor>>-t.


[[Remap_to_ancestor]]
Áthelyezés ősre
~~~~~~~~~~~~~~~

A linkgit:git-rev-list[1] argumentumainak használatával, pl. útvonal-korlátozókkal,
korlátozható az újraírásra kerülő revíziók halmaza. A parancssorban megadott
pozitív referenciák azonban kitüntetettek: nem engedjük, hogy az ilyen
korlátozók kizárják őket. Ebből a célból helyettük a legközelebbi, ki nem
zárt ősre lesznek átírva.


EXIT STATUS
-----------

Siker esetén a kilépési státusz `0`. Ha a szűrő nem talál egyetlen
átírandó commitot sem, a kilépési státusz `2`. Bármely más hiba esetén a
kilépési státusz bármilyen más, nullától eltérő érték lehet.


EXAMPLES
--------

Tegyük fel, hogy el akarsz távolítani egy fájlt (amely bizalmas információt
vagy szerzői jogi jogsértést tartalmaz) az összes commitból:

-------------------------------------------------------
git filter-branch --tree-filter 'rm filename' HEAD
-------------------------------------------------------

Ha azonban a fájl hiányzik valamelyik commit fájából, akkor egy
egyszerű `rm filename` meg fog hiúsulni az adott fánál és commitnál.
Ezért inkább a `rm -f filename` szkriptet érdemes használni.

A `--index-filter` 'git rm'-mel való használata jelentősen gyorsabb
változatot eredményez. Ahogy a `rm filename` használatakor, a
`git rm --cached filename` is meghiúsul, ha a fájl hiányzik egy
commit fájából. Ha egy fájlt "teljesen el akarsz felejtetni", akkor
nem számít, mikor került bele az előzményekbe, ezért adjuk hozzá a
`--ignore-unmatch` kapcsolót is:

--------------------------------------------------------------------------
git filter-branch --index-filter 'git rm --cached --ignore-unmatch filename' HEAD
--------------------------------------------------------------------------

Ezután megkapod az újraírt előzményeket a HEAD-be mentve.

A repository úgy való újraírásához, mintha a `foodir/` lett volna a
projektgyökere, az összes többi előzmény eldobásával:

-------------------------------------------------------
git filter-branch --subdirectory-filter foodir -- --all
-------------------------------------------------------

Így pl. egy könyvtár-alkönyvtárból önálló repository-t csinálhatsz.
Figyeld meg a `--`-t, amely elválasztja a 'filter-branch' kapcsolóit
a revíziós kapcsolóktól, és a `--all`-t, amely az összes branch és
tag újraírását végzi.

Ahhoz, hogy egy commitot (amely jellemzően egy másik előzménysor
csúcsán van) az aktuális kezdő commit szülőjévé tegyél, azért hogy a
másik előzményt az aktuális előzmény mögé illeszd:

-------------------------------------------------------------------
git filter-branch --parent-filter 'sed "s/^\$/-p <graft-id>/"' HEAD
-------------------------------------------------------------------

(ha a szülő-string üres - ami akkor fordul elő, amikor a kezdő
commitról van szó - akkor add hozzá a graftcommitot szülőként).
Figyeld meg, hogy ez egyetlen gyökérrel rendelkező előzményt
feltételez (azaz nem történt közös ős nélküli merge). Ha ez nem
így van, használd a következőt:

--------------------------------------------------------------------------
git filter-branch --parent-filter \
	'test $GIT_COMMIT = <commit-id> && echo "-p <graft-id>" || cat' HEAD
--------------------------------------------------------------------------

vagy még egyszerűbben:

-----------------------------------------------
git replace --graft $commit-id $graft-id
git filter-branch $graft-id..HEAD
-----------------------------------------------

A "Darl McBribe" által szerzett commitok eltávolításához az
előzményekből:

------------------------------------------------------------------------------
git filter-branch --commit-filter '
	if [ "$GIT_AUTHOR_NAME" = "Darl McBribe" ];
	then
		skip_commit "$@";
	else
		git commit-tree "$@";
	fi' HEAD
------------------------------------------------------------------------------

A 'skip_commit' függvény a következőképpen van definiálva:

--------------------------
skip_commit()
{
	shift;
	while [ -n "$1" ];
	do
		shift;
		map "$1";
		shift;
	done;
}
--------------------------

A shift-varázslat először eldobja a fa-azonosítót, majd a -p
paramétereket. Figyeld meg, hogy ez helyesen kezeli a merge-eket! Ha
Darl egy P1 és P2 közötti merge-et commitolt, az helyesen lesz
propagálva, és a merge összes gyermeke a merge-commit helyett P1-et
és P2-t fogja szülőként kapni.

*MEGJEGYZÉS*: a commitok által bevezetett, és a későbbi commitok által
vissza nem vont változtatások továbbra is benne maradnak az újraírt
branchben. Ha a _változtatásokat_ is ki akarod dobni a commitokkal
együtt, akkor a 'git rebase' interaktív módját kell használnod.

A commit napló-üzeneteit a `--msg-filter` használatával írhatod át.
Például egy 'git svn' által létrehozott repository-ban a 'git svn-id'
sztringek ilyen módon távolíthatók el:

-------------------------------------------------------
git filter-branch --msg-filter '
	sed -e "/^git-svn-id:/d"
'
-------------------------------------------------------

Ha 'Acked-by' sorokat kell hozzáadnod, mondjuk, az utolsó 10 commithoz
(amelyek közül egyik sem merge), használd ezt a parancsot:

--------------------------------------------------------
git filter-branch --msg-filter '
	cat &&
	echo "Acked-by: Bugs Bunny <bunny@bugzilla.org>"
' HEAD~10..HEAD
--------------------------------------------------------

A `--env-filter` kapcsolóval módosítható a committer és/vagy a szerző
identitása. Ha például kiderül, hogy a commitjaid egy hibásan
beállított user.email miatt rossz identitással rendelkeznek, akkor a
projekt közzététele előtt így javíthatod ki:

--------------------------------------------------------
git filter-branch --env-filter '
	if test "$GIT_AUTHOR_EMAIL" = "root@localhost"
	then
		GIT_AUTHOR_EMAIL=john@example.com
	fi
	if test "$GIT_COMMITTER_EMAIL" = "root@localhost"
	then
		GIT_COMMITTER_EMAIL=john@example.com
	fi
' -- --all
--------------------------------------------------------

Ahhoz, hogy az újraírást csak az előzmények egy részére korlátozd, az új
branch neve mellett adj meg egy revíziós tartományt is. Az új branch
neve arra a legfelső revízióra fog mutatni, amelyet e tartomány
'git rev-list'-je kiír.

Vegyük ezt az előzményt:

------------------
     D--E--F--G--H
    /     /
A--B-----C
------------------

Ahhoz, hogy csak a D, E, F, G, H commitokat írd újra, de az A-t, B-t
és C-t érintetlenül hagyd, használd:

--------------------------------
git filter-branch ... C..H
--------------------------------

Ahhoz, hogy az E, F, G, H commitokat írd újra, használd ezek egyikét:

----------------------------------------
git filter-branch ... C..H --not D
git filter-branch ... D..H --not C
----------------------------------------

Ahhoz, hogy az egész fát egy alkönyvtárba helyezd, vagy onnan
eltávolítsd:

---------------------------------------------------------------
git filter-branch --index-filter \
	'git ls-files -s | sed "s-\t\"*-&newsubdir/-" |
		GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
			git update-index --index-info &&
	 mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"' HEAD
---------------------------------------------------------------



CHECKLIST FOR SHRINKING A REPOSITORY
------------------------------------

A git-filter-branch használható arra, hogy megszabadulj a fájlok egy
részhalmazától, jellemzően a `--index-filter` és a
`--subdirectory-filter` valamilyen kombinációjával. Az emberek azt
várják, hogy az eredményül kapott repository kisebb legyen az
eredetinél, de néhány további lépésre van szükség ahhoz, hogy
ténylegesen kisebb is legyen, mert a Git igyekszik nem elveszíteni
az objektumaidat, amíg nem mondod neki, hogy tegye. Először győződj
meg róla, hogy:

* Valóban eltávolítottad egy fájlnév minden változatát, ha egy blob
  áthelyezésre került az élettartama során. A
  `git log --name-only --follow --all -- filename` segíthet
  megtalálni az átnevezéseket.

* Valóban minden referenciát szűrtél: használd a
  `--tag-name-filter cat -- --all` kapcsolót a git-filter-branch
  meghívásakor.

Ezután két módon kaphatsz kisebb repository-t. A biztonságosabb mód
a klónozás, amely érintetlenül hagyja az eredetit.

* Klónozd a `git clone file:///path/to/repo` paranccsal. A klón nem
  fogja tartalmazni az eltávolított objektumokat. Lásd:
  linkgit:git-clone[1]. (Figyeld meg, hogy az egyszerű útvonallal
  történő klónozás egyszerűen csak hardlinkeli az összes fájlt!)

Ha bármilyen okból valóban nem akarod klónozni, ehelyett nézd át a
következő pontokat (ebben a sorrendben). Ez egy nagyon destruktív
megközelítés, ezért *készíts biztonsági mentést*, vagy térj vissza a
klónozáshoz. Figyelmeztetve lettél.

* Távolítsd el a git-filter-branch által biztonsági mentésként
  megőrzött eredeti referenciákat: mondjuk `git for-each-ref
  --format="%(refname)" refs/original/ | xargs -n 1 git
  update-ref -d`.

* Járasd le az összes reflogot a `git reflog expire --expire=now --all`
  paranccsal.

* Szemétgyűjtsd az összes nem hivatkozott objektumot a
  `git gc --prune=now` paranccsal (vagy ha a git-gc-d nem elég új
  ahhoz, hogy támogassa a `--prune` argumentumait, használd inkább a
  `git repack -ad; git prune` parancsot).

[[PERFORMANCE]]
PERFORMANCE
-----------

A git-filter-branch teljesítménye jéglassú; a tervezése miatt egy
visszafelé kompatibilis implementáció soha nem lehet gyors:

* A fájlok szerkesztésekor a git-filter-branch a tervezéséből adódóan
  minden egyes commitot checkoutol úgy, ahogyan az az eredeti
  repository-ban létezett. Ha a repository-dban `10^5` fájl és `10^5`
  commit van, de minden commit csak öt fájlt módosít, akkor a
  git-filter-branch `10^10` módosítást fog rád kényszeríteni, jóllehet
  (legfeljebb) csak `5*10^5` egyedi blob van.

* Ha megpróbálod becsapni a rendszert, és megpróbálod elérni, hogy a
  git-filter-branch csak a commitban módosított fájlokon dolgozzon,
  akkor két dolog történik

  ** problémákba ütközöl a törléseknél, valahányszor a felhasználó
     egyszerűen csak fájlokat próbál átnevezni (mert a nem létező
     fájlok törlésének megkísérlése no-op-nak tűnik; némi trükközésre
     van szükség ahhoz, hogy a törléseket átnevezéseken keresztül
     leképezzük, amikor az átnevezések tetszőleges, felhasználó által
     megadott shell-en keresztül történnek)

  ** még ha sikerül is a törlések-átnevezéseken-át-leképezése
     trükközés, akkor is technikailag megsérted a visszafelé
     kompatibilitást, mert a felhasználóknak megengedett, hogy a
     fájlokat a commitok topológiájától függő módon szűrjék, ahelyett
     hogy kizárólag a fájltartalom vagy a fájlnevek alapján szűrnének
     (bár ezt még sosem figyelték meg a gyakorlatban).

* Még ha nem is kell fájlokat szerkesztened, csupán például
  átnevezni vagy eltávolítani akarsz néhányat, és így elkerülheted
  minden fájl checkoutolását (azaz használhatod a --index-filtert),
  akkor is shell-kódrészleteket adsz át a szűrőidnek. Ez azt jelenti,
  hogy minden egyes commithoz elő kell készítened egy git
  repository-t, amelyben ezek a szűrők lefuttathatók. Ez jelentős
  előkészítést igényel.

* Továbbá a git-filter-branch commitonként több további fájlt hoz
  létre vagy frissít. Ezek egy része a git-filter-branch által
  biztosított kényelmi függvényeket (például a map()-et) támogatja,
  míg mások a belső állapot nyomon követésére szolgálnak (de a
  felhasználói szűrők is elérhették volna őket; a git-filter-branch
  egyik regressziós tesztje meg is teszi ezt). Ez lényegében azt
  jelenti, hogy a fájlrendszert használjuk IPC-mechanizmusként a
  git-filter-branch és a felhasználó által megadott szűrők között. A
  lemezek hajlamosak lassú IPC-mechanizmusnak lenni, és ezeknek a
  fájloknak az írása gyakorlatilag egy kényszerített szinkronizációs
  pontot is jelent a különálló folyamatok között, amelyet minden
  egyes commitnál elérünk.

* A felhasználó által megadott shell-parancsok valószínűleg parancsok
  csővezetékét (pipeline) fogják tartalmazni, ami sok folyamat
  létrehozását eredményezi commitonként. Egy újabb folyamat
  létrehozása és futtatása operációs rendszerenként igen eltérő
  ideig tart, de bármelyik platformon nagyon lassú egy függvény
  meghívásához képest.

* Maga a git-filter-branch shellben van megírva, ami eléggé lassú.
  Ez az egyetlen teljesítményprobléma, amely visszafelé kompatibilis
  módon javítható lenne, de a fenti, a git-filter-branch tervezésében
  eredendően jelen lévő problémákhoz képest maga az eszköz nyelve
  viszonylag kisebb probléma.

  ** Mellékes megjegyzés: sajnos az emberek hajlamosak a
     shellben-írtság aspektusára fixálódni, és rendszeresen
     megkérdezik, hogy a git-filter-branch átírható lenne-e egy másik
     nyelvre a teljesítményproblémák megoldásához. Ez nemcsak hogy
     figyelmen kívül hagyja a tervezésben rejlő nagyobb, eredendő
     problémákat, de kevésbé segítene, mint gondolnád: ha maga a
     git-filter-branch nem shellben lenne, akkor a kényelmi
     függvényeket (map(), skip_commit() stb.) és a `--setup`
     argumentumot már nem lehetne egyszer, a program elején
     végrehajtani, hanem minden felhasználói szűrő elé be kellene
     őket illeszteni (és így minden commitnál újra kellene futtatni
     őket).

A https://github.com/newren/git-filter-repo/[git filter-repo] eszköz a
git-filter-branch alternatívája, amely nem szenved ezektől a
teljesítményproblémáktól, sem az (alább említett) biztonsági
problémáktól. Azok számára, akiknek a meglévő eszközkészlete a
git-filter-branch-re épül, a 'git filter-repo' egy
https://github.com/newren/git-filter-repo/blob/master/contrib/filter-repo-demos/filter-lamely[filter-lamely]
nevű eszközt is biztosít, amely a git-filter-branch drop-in
helyettesítője (néhány fenntartással). Bár a filter-lamely
ugyanazoktól a biztonsági problémáktól szenved, mint a
git-filter-branch, legalább némileg enyhíti a teljesítményproblémákat.

[[SAFETY]]
SAFETY
------

A git-filter-branch tele van buktatókkal, amelyek sokféleképpen
könnyen tönkretehetik a repository-kat, vagy annál is nagyobb
katyvaszt eredményezhetnek, mint amivel kezdted:

* Valaki rendelkezhet egy "működő és tesztelt szűrők" halmazával,
  amelyet dokumentál vagy átad egy munkatársnak, aki azután egy másik
  operációs rendszeren futtatja őket, ahol ugyanazok a parancsok nem
  működnek/nincsenek tesztelve (a git-filter-branch manpage néhány
  példáját is érinti ez a probléma). A BSD és a GNU userland közötti
  különbségek igazán kellemetlenek tudnak lenni. Szerencsés esetben
  hibaüzenetek özöne jelenik meg. De ugyanolyan valószínű, hogy a
  parancsok vagy nem végzik el a kért szűrést, vagy csendben
  megsértik az állományt valamilyen nem kívánt változtatással. A nem
  kívánt változtatás csak néhány commitot érinthet, így ez sem
  feltétlenül nyilvánvaló. (Az a tény, hogy a problémák nem
  feltétlenül nyilvánvalóak, azt jelenti, hogy valószínűleg
  észrevétlenek maradnak, amíg az újraírt előzményt már jó ideje
  használják, és ekkorra már nagyon nehéz igazolni egy újabb
  "zászlós napot" egy újabb újraíráshoz.)

* A szóközöket tartalmazó fájlneveket a shell-kódrészletek gyakran
  helytelenül kezelik, mivel problémákat okoznak a shell-csővezetékek
  számára. Nem mindenki ismeri a find -print0, xargs -0,
  git-ls-files -z stb. eszközöket. Még azok is, akik ismerik ezeket,
  feltételezhetik, hogy az ilyen kapcsolók nem relevánsak, mert
  valaki más már átnevezte az ilyen fájlokat a repository-jukban,
  még mielőtt a szűrést végző személy csatlakozott a projekthez. És
  gyakran még azok is, akik ismerik a szóközös argumentumok
  kezelését, egyszerűen azért nem teszik ezt meg, mert nincsenek
  abban a gondolkodásmódban, hogy mindenre gondoljanak, ami
  elromolhat.

* A nem ASCII fájlnevek csendben eltávolíthatók, még ha a kívánt
  könyvtárban is vannak. A kívánt útvonalak megtartása gyakran olyan
  csővezetékekkel történik, mint a
  `git ls-files | grep -v ^WANTED_DIR/ | xargs git rm`. Az ls-files
  csak akkor teszi idézőjelbe a fájlneveket, ha szükséges, ezért
  előfordulhat, hogy az emberek nem veszik észre, hogy az egyik fájl
  nem illeszkedett a reguláris kifejezésre (legalábbis nem addig,
  amíg már nagyon késő nem lesz). Igen, aki tud a core.quotePath-ról,
  az elkerülheti ezt (kivéve, ha vannak más speciális karakterei,
  mint a \t, \n vagy "), és akik az ls-files -z-t grep helyett
  valami mással használják, azok is elkerülhetik ezt, de ez nem
  jelenti azt, hogy meg is fogják tenni.

* Hasonlóképpen, fájlok áthelyezésekor előfordulhat, hogy a nem
  ASCII vagy speciális karaktereket tartalmazó fájlnevek egy másik
  könyvtárban kötnek ki, olyanban, amelynek a neve idézőjel karaktert
  tartalmaz. (Ez technikailag ugyanaz a probléma, mint a fenti
  idézőjelezési probléma, de talán egy érdekes, más módja annak,
  ahogyan megnyilvánulhat és meg is nyilvánult problémaként.)

* Túlságosan könnyű véletlenül összekeverni a régi és az új
  előzményt. Ez bármelyik eszközzel lehetséges, de a
  git-filter-branch szinte hívogatja ezt. Szerencsés esetben az
  egyetlen hátrány az, hogy a felhasználók frusztráltak lesznek,
  mert nem tudják, hogyan zsugorítsák a repository-jukat és
  távolítsák el a régi cuccokat. Szerencsétlen esetben összemergelik
  a régi és az új előzményt, és minden commitnak több "másolatával"
  végzik, amelyek közül némelyik nem kívánt vagy bizalmas fájlokat
  tartalmaz, mások pedig nem. Ez többféle módon is bekövetkezhet:

  ** az alapértelmezés, hogy csak részleges előzmény-újraírás
     történik (a '--all' nem az alapértelmezés, és kevés példa
     mutatja be)

  ** az a tény, hogy nincs automatikus, futás utáni takarítás

  ** az a tény, hogy a --tag-name-filter (amikor a tagek átnevezésére
     használják) nem távolítja el a régi tageket, csak újakat ad
     hozzá az új névvel

  ** az a tény, hogy kevés oktató jellegű információ áll
     rendelkezésre, amely tájékoztatná a felhasználókat egy
     újraírás következményeiről, és arról, hogyan kerüljék el a régi
     és az új előzmény összekeverését. Ez a man page például tárgyalja,
     hogy a felhasználóknak meg kell érteniük, hogy az összes
     branchükön rebase-elniük kell a változtatásaikat az új előzmény
     tetejére (vagy törölniük és újraklónozniuk kell), de ez csak
     egy a mérlegelendő szempontok közül. További részletekért lásd a
     git filter-repo kézikönyv-oldal "DISCUSSION" szakaszát.

* Az annotált tagek véletlenül könnyűsúlyú tagekké alakulhatnak át,
  két probléma bármelyike miatt:

  ** Valaki elvégezhet egy előzmény-újraírást, ráébredhet, hogy
     elrontotta, visszaállíthatja a refs/original/-ban lévő
     biztonsági mentésekből, majd megismételheti a git-filter-branch
     parancsát. (A refs/original/-beli biztonsági mentés nem valódi
     biztonsági mentés; először dereferálja a tageket.)

  ** A git-filter-branch futtatása --tags vagy --all kapcsolóval a
     <rev-list-options>-ban. Ahhoz, hogy az annotált tagek annotáltak
     maradjanak, a --tag-name-filtert kell használnod (és nem
     szabad, hogy előzőleg visszaállítottál volna a
     refs/original/-ból egy korábban elrontott újraírásnál).

* Bármely commit-üzenet, amely kódolást ad meg, sérülni fog az
  újraírás során; a git-filter-branch figyelmen kívül hagyja a
  kódolást, veszi az eredeti bájtokat, és a megfelelő kódolás
  közlése nélkül adja át a commit-tree-nek. (Ez akkor is
  bekövetkezik, ha a --msg-filter használatban van, és akkor is, ha
  nincs.)

* A commit-üzenetek (még ha mind UTF-8 kódolásúak is) alapértelmezés
  szerint sérülnek, mivel nem frissülnek -- a commit-üzenetekben lévő,
  más commit-hashekre mutató hivatkozások mostantól már nem létező
  commitokra fognak hivatkozni.

* Nincsenek olyan eszközök, amelyek segítenék a felhasználókat abban,
  hogy megtalálják, milyen nem kívánt szemetet kellene törölniük, ami
  azt jelenti, hogy sokkal valószínűbb, hogy hiányos vagy részleges
  takarítást végeznek, ami néha zavarhoz és időpocsékoláshoz vezet,
  miközben megpróbálják megérteni a helyzetet. (Például az emberek
  hajlamosak csak nagy fájlokat keresni törlésre nagy könyvtárak vagy
  kiterjesztések helyett, és miután ezt megtették, valamikor később
  az új repository-t használó, az előzményeket átnézegető emberek
  észreveszik, hogy egy build-artifact könyvtárban vannak fájlok, de
  nem az összes, vagy egy függőség-gyorsítótár (node_modules vagy
  hasonló), amely soha nem is működhetett volna, mert hiányoznak
  belőle bizonyos fájlok.)

* Ha a --prune-empty nincs megadva, akkor a szűrési folyamat rakásnyi
  zavaró üres commitot hozhat létre

* Ha a --prune-empty meg van adva, akkor a szűrési művelet előtt
  szándékosan elhelyezett üres commitok is eltávolításra kerülnek,
  ahelyett hogy csak a szűrési szabályok miatt üressé vált commitok
  kerülnének eltávolításra.

* Ha a --prune-empty meg van adva, néha üres commitok kimaradnak, és
  mégis ott maradnak (viszonylag ritka hiba, de előfordul...)

* Egy apróbb probléma, de azok a felhasználók, akiknek az a céljuk,
  hogy egy repository-ban minden nevet és e-mail-címet frissítsenek,
  a --env-filterhez folyamodhatnak, amely csak a szerzőket és a
  committereket frissíti, a taggereket kihagyva.

* Ha a felhasználó egy olyan --tag-name-filtert ad meg, amely több
  taget ugyanarra a névre képez le, nem jelenik meg figyelmeztetés
  vagy hiba; a git-filter-branch egyszerűen felülírja az egyes
  tageket valamilyen nem dokumentált, előre meghatározott sorrendben,
  aminek eredményeként a végén csak egy tag marad. (A
  git-filter-branch egyik regressziós tesztje megköveteli ezt a
  meglepő viselkedést.)

Emellett a git-filter-branch gyenge teljesítménye gyakran biztonsági
problémákhoz vezet:

* A kívánt szűrést elvégző, helyes shell-kódrészlet megtalálása néha
  nehéz, hacsak nem csupán triviális módosítást végzel, például
  néhány fájl törlését. Sajnos az emberek gyakran csak úgy tudják
  meg, hogy a kódrészlet helyes-e vagy sem, hogy kipróbálják, de a
  helyesség vagy helytelenség speciális körülményektől (szóközök a
  fájlnevekben, nem ASCII fájlnevek, furcsa szerzőnevek vagy
  e-mail-címek, érvénytelen időzónák, graftok vagy replace-objektumok
  jelenléte stb.) függően változhat, ami azt jelenti, hogy hosszú
  ideig kell várniuk, hibába ütközniük, majd újrakezdeniük. A
  git-filter-branch teljesítménye annyira gyenge, hogy ez a ciklus
  fájdalmas, csökkentve a gondos újraellenőrzésre fordítható időt
  (arról nem is beszélve, hogy mit tesz az újraírást végző személy
  türelmével, még ha technikailag több ideje is van rá). Ezt a
  problémát tovább súlyosbítja, hogy a törött szűrőkből származó
  hibák sokáig nem jelennek meg, és/vagy elvesznek a kimenet
  tengerében. Ami még rosszabb, a törött szűrők gyakran egyszerűen
  csendes, helytelen újraírásokat eredményeznek.

* Mindezek tetejébe, még amikor a felhasználók végre megtalálják a
  működő parancsokat, természetesen meg akarják osztani őket. De
  előfordulhat, hogy nincsenek tisztában azzal, hogy a saját
  repository-jukban nem voltak jelen olyan speciális esetek, amelyek
  valaki másnak a repository-jában igen. Így amikor valaki más, egy
  eltérő repository-val futtatja ugyanazokat a parancsokat, beleütközik
  a fenti problémákba. Vagy a felhasználó éppen olyan parancsokat
  futtat, amelyeket ténylegesen ellenőriztek speciális esetekre, de
  egy másik operációs rendszeren futtatja őket, ahol - a fentebb
  leírtak szerint - nem működnek.

GIT
---
A linkgit:git[1] csomag része
