git-ls-remote(1)
================

NAME
----
git-ls-remote - Egy remote repository referenciáinak listázása


SYNOPSIS
--------
[verse]
'git ls-remote' [--branches] [--tags] [--refs] [--upload-pack=<exec>]
	      [-q | --quiet] [--exit-code] [--get-url] [--sort=<key>]
	      [--symref] [<repository> [<patterns>...]]

DESCRIPTION
-----------
Egy remote repository-ban elérhető referenciák megjelenítése a hozzájuk
tartozó commit-azonosítókkal együtt.


OPTIONS
-------
-b::
--branches::
-t::
--tags::
	Korlátozás csak a lokális branchekre, illetve a lokális tagekre.
	Ezek az opciók _nem_ zárják ki egymást; ha mindkettő meg van adva, a
	refs/heads és a refs/tags alatt tárolt referenciák jelennek meg.
	Vedd figyelembe, hogy a `--heads` és a `-h` a `--branches` és a `-b`
	elavult szinonimái, és a jövőben eltávolításra kerülhetnek.  Vedd
	figyelembe azt is, hogy a `git ls-remote -h`, ha a parancssorban
	nincs mellette semmi más, súgót ad, összhangban a többi git
	alparanccsal.

--refs::
	Ne jelenjenek meg a kimenetben a lehántott tagek vagy az olyan pszeudorefek, mint a `HEAD`.

-q::
--quiet::
	Ne írja ki a remote URL-t az stderr-re.

--upload-pack=<exec>::
	A 'git-upload-pack' teljes útvonalának megadása a remote hoszton.
	Ez lehetővé teszi a referenciák listázását az SSH-n keresztül elért
	repository-kból, ahol az SSH daemon nem a felhasználó által konfigurált
	PATH-t használja.

--exit-code::
	Kilépés "2" státusszal, ha nem található illeszkedő ref a remote
	repository-ban. A parancs általában "0" státusszal lép ki, jelezve,
	hogy sikeresen kommunikált a remote repository-val, függetlenül attól,
	hogy talált-e illeszkedő refet.

--get-url::
	A megadott remote repository URL-jének kifejtése, figyelembe véve
	bármely "url.<base>.insteadOf" config-beállítást (l. linkgit:git-config[1]),
	majd kilépés a remote-tal való kommunikáció nélkül.

--symref::
	Szimbolikus ref megjelenítésekor az általa mutatott objektumon túl
	az általa mutatott alapul fekvő ref megjelenítése is.  Jelenleg az
	upload-pack csak a HEAD symrefet mutatja, így ez lesz az egyetlen,
	amelyet az ls-remote megjelenít.

--sort=<key>::
	Rendezés a megadott kulcs alapján. Tegyél elé `-`-t az érték szerinti
	csökkenő rendezéshez. Támogatja a "version:refname"-et vagy a
	"v:refname"-et (a tagnevek verzióként kezelődnek). A "version:refname"
	rendezési sorrendet a "versionsort.suffix" konfigurációs változó is
	befolyásolhatja.  További rendezési opciókért l. a
	linkgit:git-for-each-ref[1]-et, de vedd figyelembe, hogy az olyan
	kulcsok, mint a `committerdate`, amelyek magukhoz az objektumokhoz
	való hozzáférést igénylik, nem működnek azoknál a refeknél, amelyek
	objektumai még nem lettek lefetchelve a remote-ról, és `missing object`
	hibát adnak.

-o <option>::
--server-option=<option>::
	A megadott karakterlánc továbbítása a szervernek, ha a kommunikáció
	a 2-es protokollverzióval történik.  A megadott karakterlánc nem
	tartalmazhat NUL vagy LF karaktert.
	Ha több `--server-option=<option>` van megadva, mind elküldésre kerül
	a másik oldalnak a parancssorban felsorolt sorrendben.
	Ha a parancssorból nincs `--server-option=<option>` megadva, helyette
	a `remote.<name>.serverOption` konfigurációs változó értékei
	használatosak.

<repository>::
	A lekérdezendő „remote" repository.  Ez a paraméter lehet URL vagy egy
	remote neve (l. a linkgit:git-fetch[1] GIT URLS és REMOTES szakaszait).

<patterns>...::
	Ha nincs megadva, az összes referencia megjelenik, a --heads és a
	--tags szerinti szűrés után.  Ha <patterns>... van megadva, csak a
	megadott minták egyikére vagy többjére illeszkedő referenciák
	jelennek meg. Minden minta globként értelmeződik (l. a `glob`-ot a
	linkgit:gitglossary[7]-ben), amely a ref „végére" illeszkedik, vagy a
	ref elejétől (tehát egy teljes név, mint a `refs/heads/foo`,
	illeszkedik), vagy egy perjel-elválasztótól kezdve (tehát a `bar`
	illeszkedik a `refs/heads/bar`-ra, de nem a `refs/heads/foobar`-ra).

OUTPUT
------

A kimenet formátuma:

------------
<oid> TAB <ref> LF
------------

Annotált tag megjelenítésekor – hacsak nincs megadva a `--refs` – két
ilyen sor jelenik meg: az egyikben magának a tagnek a refneve szerepel
`<ref>`-ként, a másikban a `<ref>`-et `^{}` követi. Az utóbbi soron
lévő `<oid>` annak az objektumnak a nevét mutatja, amelyre a tag mutat.

EXAMPLES
--------

* Az összes referencia listázása (a szimbolikusakat és a pszeudorefeket
  is beleértve), a tagek lehántásával:
+
----
$ git ls-remote
27d43aaaf50ef0ae014b88bba294f93658016a2e	HEAD
950264636c68591989456e3ba0a5442f93152c1a	refs/heads/main
d9ab777d41f92a8c1684c91cfb02053d7dd1046b	refs/heads/next
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

* A megadott mintákra illeszkedő összes referencia listázása:
+
----
$ git ls-remote http://www.kernel.org/pub/scm/git/git.git master seen rc
5fe978a5381f1fbad26a80e682ddd2a401966740	refs/heads/master
c781a84b5204fb294c9ccc79f8b3baceeb32c061	refs/heads/seen
----

* Csak egy megadott helyettesítő karakteres mintára illeszkedő tagek listázása:
+
----
$ git ls-remote --tags http://www.kernel.org/pub/scm/git/git.git v\*
485a869c64a68cc5795dd99689797c5900f4716d	refs/tags/v2.39.2
cbf04937d5b9fcf0a76c28f69e6294e9e3ecd7e6	refs/tags/v2.39.2^{}
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

SEE ALSO
--------
linkgit:git-check-ref-format[1].

GIT
---
A linkgit:git[1] csomag része
