git-merge-base(1)
=================

NAME
----
git-merge-base - Merge-hez a lehető legjobb közös ősök megtalálása


SYNOPSIS
--------
[verse]
'git merge-base' [-a | --all] <commit> <commit>...
'git merge-base' [-a | --all] --octopus <commit>...
'git merge-base' --is-ancestor <commit> <commit>
'git merge-base' --independent <commit>...
'git merge-base' --fork-point <ref> [<commit>]

DESCRIPTION
-----------

A 'git merge-base' megtalálja a két commit közötti legjobb közös ő(sö)ket,
amelyeket egy háromutas merge-ben lehet használni.  Egy közös ős 'jobb',
mint egy másik közös ős, ha az utóbbi az előbbinek őse.  Az a közös ős,
amelynek nincs jobb közös őse, a 'legjobb közös ős', azaz a 'merge-alap'.
Vedd figyelembe, hogy egy commitpárhoz több merge-alap is tartozhat.

OPERATION MODES
---------------

A leggyakoribb speciális esetben, ha csak két commitot adsz meg a
parancssorban, az a két megadott commit közötti merge-alap kiszámítását
jelenti.

Általánosabban: a két commit közül, amelyekből a merge-alapot ki kell
számítani, az egyiket a parancssor első commit-argumentuma adja meg; a
másik commit egy (esetleg hipotetikus) commit, amely a parancssor összes
többi commitjának merge-e.

Ennek következtében a 'merge-alap' nem feltétlenül része minden
commit-argumentumnak, ha kettőnél több commit van megadva. Ez eltér a
linkgit:git-show-branch[1]-től, amikor azt a `--merge-base` kapcsolóval
használják.

--octopus::
	Az összes megadott commit legjobb közös őseinek kiszámítása egy n-utas
	merge előkészítéseként.  Ez a 'git show-branch --merge-base'
	viselkedését utánozza.

--independent::
	A merge-alapok kiírása helyett a megadott commitok egy minimális,
	ugyanazokkal az ősökkel rendelkező részhalmazát írja ki.  Más szóval a
	megadott commitok közül azokat sorolja fel, amelyek egyik másikból sem
	érhetők el.  Ez a 'git show-branch --independent' viselkedését utánozza.

--is-ancestor::
	Ellenőrzi, hogy az első <commit> őse-e a második <commit>-nak, és 0
	státusszal lép ki, ha igen, vagy 1 státusszal, ha nem.
	A hibákat 1-től eltérő, nem nulla státusz jelzi.

--fork-point::
	Megtalálja azt a pontot, ahol egy branch (vagy bármely, a
	<commit>-hoz vezető előzmény) elágazott egy másik branchről (vagy
	bármely referenciáról), a <ref>-ről. Ez nem csak a két commit közös
	ősét keresi, hanem figyelembe veszi a <ref> reflogját is, hogy lássa,
	a <commit>-hoz vezető előzmény a <ref> branch egy korábbi
	megtestesüléséről ágazott-e el (lásd ennek a módnak a tárgyalását
	lentebb).

OPTIONS
-------
-a::
--all::
	A commitok összes merge-alapjának kiírása csak egy helyett.

DISCUSSION
----------

Adott két commit, 'A' és 'B'; a `git merge-base A B` egy olyan commitot ír
ki, amely 'A'-ból és 'B'-ből is elérhető a szülő-kapcsolaton keresztül.

Például ezzel a topológiával:

....
	 o---o---o---B
	/
---o---1---o---o---o---A
....

az 'A' és 'B' közötti merge-alap az '1'.

Adott három commit, 'A', 'B' és 'C'; a `git merge-base A B C` az 'A' és egy
hipotetikus 'M' commit közötti merge-alapot számítja ki, amely a 'B' és 'C'
merge-e.  Például ezzel a topológiával:

....
       o---o---o---o---C
      /
     /   o---o---o---B
    /   /
---2---1---o---o---o---A
....

a `git merge-base A B C` eredménye '1'.  Ez azért van, mert a 'B' és 'C'
közötti 'M' merge-commitot tartalmazó ekvivalens topológia:


....
       o---o---o---o---o
      /                 \
     /   o---o---o---o---M
    /   /
---2---1---o---o---o---A
....

és a `git merge-base A M` eredménye '1'.  A '2' commit is közös ős 'A' és
'M' között, de az '1' jobb közös ős, mert a '2' az '1' őse.  Ezért a '2'
nem merge-alap.

A `git merge-base --octopus A B C` eredménye '2', mert a '2' az összes
commit legjobb közös őse.

Amikor az előzmény kereszteződő merge-eket tartalmaz, két commithoz több
'legjobb' közös ős is tartozhat.  Például ezzel a topológiával:

....
---1---o---A
    \ /
     X
    / \
---2---o---o---B
....

az '1' és a '2' is A és B merge-alapja.  Egyik sem jobb a másiknál
(mindkettő 'legjobb' merge-alap).  Ha a `--all` kapcsoló nincs megadva,
nincs meghatározva, melyik legjobbat írja ki.

Egy gyakori idióma az A és B commit közötti "fast-forward-ság"
ellenőrzésére (vagy legalábbis régen az volt) az, hogy kiszámítjuk az A és
B közötti merge-alapot, és megnézzük, hogy megegyezik-e A-val; ebben az
esetben A a B őse.  Ezt az idiómát gyakran láthatod régebbi szkriptekben.

....
A=$(git rev-parse --verify A)
if test "$A" = "$(git merge-base A B)"
then
	... A is an ancestor of B ...
fi
....

A modern gitben ezt közvetlenebbül is megfogalmazhatod:

....
if git merge-base --is-ancestor A B
then
	... A is an ancestor of B ...
fi
....

helyette.

[[_discussion_on_fork_point_mode]]
A fork-point mód tárgyalása
---------------------------

Miután a `git switch -c topic origin/master` paranccsal létrehozott `topic`
branchen dolgoztál, az `origin/master` remote-tracking branch előzményét
esetleg visszatekerték és újraépítették, ami ilyen alakú előzményhez
vezet:

....
		 o---B2
		/
---o---o---B1--o---o---o---B (origin/master)
	\
	 B0
	  \
	   D0---D1---D (topic)
....

ahol az `origin/master` korábban a B0, B1, B2 commitokra mutatott, most
pedig a B-re mutat, és a `topic` branchedet akkor indítottad a tetején,
amikor az `origin/master` a B0-nál volt, és három commitot építettél rá:
D0, D1 és D.  Képzeld el, hogy most rebase-elni szeretnéd a topicon végzett
munkádat a frissített origin/master tetejére.

Ilyen esetben a `git merge-base origin/master topic` a fenti képen a B0
szülőjét adná vissza, de a B0^..D *nem* az a committartomány, amelyet a B
tetejére szeretnél újrajátszani (tartalmazza a B0-t, amit nem te írtál;
ez egy olyan commit, amelyet a másik oldal eldobott, amikor a csúcsát
B0-ról B1-re mozgatta).

A `git merge-base --fork-point origin/master topic` arra való, hogy ilyen
esetben segítsen.  Nemcsak a B-t, hanem a B0-t, B1-et és B2-t is (azaz a
remote-tracking branchek régi csúcsait, amelyekről a repositoryd reflogja
tud) figyelembe veszi, hogy lássa, melyik commitra épült a topic branched,
és megtalálja a B0-t, lehetővé téve, hogy csak a topicodon lévő commitokat
játszd újra, kihagyva azokat a commitokat, amelyeket a másik oldal később
eldobott.

Ezért

    $ fork_point=$(git merge-base --fork-point origin/master topic)

megtalálja a B0-t, és

    $ git rebase --onto origin/master $fork_point topic

újrajátssza a D0-t, D1-et és D-t a B tetején, hogy ilyen alakú új
előzményt hozzon létre:

....
		 o---B2
		/
---o---o---B1--o---o---o---B (origin/master)
	\                   \
	 B0                  D0'--D1'--D' (topic - updated)
	  \
	   D0---D1---D (topic - old)
....

Egy figyelmeztetés: a repositorydban lévő régebbi reflog-bejegyzéseket a
`git gc` lejárttá teheti.  Ha a B0 már nem jelenik meg az `origin/master`
remote-tracking branch reflogjában, a `--fork-point` mód nyilván nem
találja meg, és sikertelen lesz, elkerülve, hogy véletlenszerű és
haszontalan eredményt adjon (például a B0 szülőjét, ahogyan ugyanez a
parancs a `--fork-point` kapcsoló nélkül adja).

Továbbá annak a remote-tracking branchnek, amellyel a `--fork-point`
módot használod, annak kell lennie, amelynek a csúcsáról a topicod
elágazott.  Ha a csúcsnál régebbi commitról ágaztál el, ez a mód nem
találja meg az elágazási pontot (képzeld el, hogy a fenti mintaelőzményben
a B0 nem létezett, az origin/master a B1-nél kezdődött, a B2-re, majd a
B-re mozdult, és a topicodat az origin/master^-nál ágaztattad el, amikor
az origin/master a B1 volt; az előzmény alakja a fentivel megegyezne, B0
nélkül, és a B1 szülője az, amit a `git merge-base origin/master topic`
helyesen megtalál, de a `--fork-point` mód nem, mert az nem egyike azoknak
a commitoknak, amelyek korábban az origin/master csúcsán voltak).


See also
--------
linkgit:git-rev-list[1],
linkgit:git-show-branch[1],
linkgit:git-merge[1]

GIT
---
A linkgit:git[1] csomag része
