git-merge-tree(1)
=================

NAME
----
git-merge-tree - Merge végrehajtása az index és a working tree érintése nélkül


SYNOPSIS
--------
[verse]
'git merge-tree' [--write-tree] [<options>] <branch1> <branch2>
'git merge-tree' [--trivial-merge] <base-tree> <branch1> <branch2> (elavult)

[[NEWMERGE]]
DESCRIPTION
-----------

Ennek a parancsnak van egy modern `--write-tree` módja és egy elavult
`--trivial-merge` módja.  A végén lévő
<<DEPMERGE,DEPRECATED DESCRIPTION>> szakasz kivételével a dokumentáció többi
része a modern `--write-tree` módot írja le.

Végrehajt egy merge-t, de nem készít új commitot, és nem olvas a working
tree-ből vagy az indexből, illetve nem is ír azokba.

A végrehajtott merge ugyanazokat a funkciókat használja, mint a „valódi"
linkgit:git-merge[1], többek között:

  * az egyes fájlok háromutas tartalmi merge-e
  * átnevezés-észlelés
  * megfelelő könyvtár-/fájlkonfliktus-kezelés
  * rekurzív ős-konszolidáció (azaz amikor egynél több merge-alap van, egy
    virtuális merge-alap létrehozása a merge-alapok merge-elésével)
  * stb.

A merge befejezése után új legfelső szintű fa objektum jön létre.  A
részletekért lásd az `OUTPUT` szakaszt lentebb.

OPTIONS
-------

--stdin::
	A merge-elendő commitokat a parancssor helyett a standard bemenetről
	olvassa. További információért lásd az <<INPUT,INPUT FORMAT>>
	szakaszt lentebb.  Magában foglalja a `-z`-t.

-z::
	Ne idézőjelezze a fájlneveket a <Conflicted file info> szakaszban,
	és minden fájlnevet NUL karakterrel zárjon le sortörés helyett.
	Az üzenetek szakaszt is NUL karakterrel kezdje sortörés helyett.
	További információért lásd az <<OUTPUT,OUTPUT>> szakaszt lentebb.

--name-only::
	A Conflicted file info szakaszban ahelyett, hogy a konfliktusos
	fájlokhoz (mód, oid, stage, útvonal) rekordok listáját írná a
	kimenetre, csak a konfliktusos fájlnevek listáját adja meg (és nem
	sorolja fel többször a fájlneveket, ha több konfliktusos stage-ük
	van).

--messages::
--no-messages::
	A tájékoztató üzeneteket, például az "Auto-merging <path>"-t vagy a
	CONFLICT értesítéseket a stdout végére írja.  Ha nincs megadva, az
	alapértelmezés az, hogy ezeket az üzeneteket akkor tünteti fel, ha
	vannak merge konfliktusok, egyébként pedig elhagyja.

--quiet::
	Letiltja a program minden kimenetét.  Hasznos, amikor csak a kilépési
	állapot érdekel.  Lehetővé teszi, hogy a merge-tree korán kilépjen,
	amikor konfliktust talál, és hogy elkerülje a merge-ek által
	létrehozott objektumok többségének kiírását.

--allow-unrelated-histories::
	A merge-tree alapértelmezés szerint hibával kilép, ha a megadott két
	branchnek nincs közös története.  Ez a kapcsoló megadható az
	ellenőrzés felülbírálására, hogy a merge mégis végbemenjen.

--merge-base=<tree-ish>::
	Ahelyett, hogy megkeresné a merge-alapokat a <branch1> és a
	<branch2> számára, adj meg egy merge-alapot a merge-hez.  Ez az opció
	nem kompatibilis a `--stdin`-nel.
+
Több alap megadása jelenleg nem támogatott, ami azt jelenti, hogy amikor két
branchet egynél több merge-alappal merge-elsz, ennek az opciónak a
használata azt okozhatja, hogy a merge eredménye eltér attól, amit a
`git merge` számítana ki.  Ez akár azt is jelentheti, hogy az eredményül
kapott merge-ben elvész néhány, a történet egyik oldalán végzett változás.
+
Ezzel az opcióval, mivel a merge-alap közvetlenül meg van adva, a <branch1>
és a <branch2> nem kell, hogy commitokat adjon meg; fák is elegendők.

-X<option>::
--strategy-option=<option>::
	Átadja a merge-stratégia-specifikus opciót a merge-stratégiának.
	A részletekért lásd linkgit:git-merge[1].

[[OUTPUT]]
OUTPUT
------

Sikeres merge esetén a git-merge-tree kimenete egyszerűen egyetlen sor:

	<OID of toplevel tree>

Konfliktusos merge esetén viszont a kimenet alapértelmezés szerint ilyen
alakú:

	<OID of toplevel tree>
	<Conflicted file info>
	<Informational messages>

Ezeket alább egyenként tárgyaljuk.

Van azonban egy kivétel.  Ha a `--stdin` meg van adva, akkor az elején van
egy extra szakasz, a végén egy NUL karakter, majd az összes szakasz
megismétlődik a bemenet minden sorára.  Így ha az első merge konfliktusos, a
második pedig tiszta, a kimenet ilyen alakú lenne:

	<Merge status>
	<OID of toplevel tree>
	<Conflicted file info>
	<Informational messages>
	NUL
	<Merge status>
	<OID of toplevel tree>
	NUL

[[MS]]
Merge-státusz
~~~~~~~~~~~~~

Ez egy egész számú státusz, amelyet egy NUL karakter követ.  Az egész számú
státusz:

     0: a merge-nek konfliktusai voltak
     1: a merge tiszta volt

[[OIDTLT]]
A legfelső szintű fa OID-ja
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ez egy fa objektum, amely azt ábrázolja, ami a `git merge` végén a working
tree-be lenne checkoutolva.  Ha voltak konfliktusok, akkor a fában lévő
fájlokban beágyazott konfliktusjelölők lehetnek.  Ezt a szakaszt mindig egy
sortörés követi (vagy NUL, ha a `-z` meg van adva).

[[CFI]]
Konfliktusos fájlinformáció
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ez sorok sorozata a következő formátummal:

	<mode> <object> <stage> <filename>

A fájlnév a `core.quotePath` konfigurációs változónál leírtak szerint lesz
idézőjelezve (lásd linkgit:git-config[1]).  Ha azonban a `--name-only` opció
meg van adva, a mód, az objektum és a stage kimarad.  Ha a `-z` meg van adva,
a „sorokat" sortörés karakter helyett NUL karakter zárja.

[[IM]]
Tájékoztató üzenetek
~~~~~~~~~~~~~~~~~~~~

Ez a szakasz tájékoztató üzeneteket ad, jellemzően konfliktusokról.  A
szakasz formátuma jelentősen eltér attól függően, hogy a `-z` meg van-e adva.

Ha a `-z` meg van adva:

A kimeneti formátum nulla vagy több konfliktus-tájékoztató rekord,
mindegyik ilyen alakú:

	<list-of-paths><conflict-type>NUL<conflict-message>NUL

ahol a <list-of-paths> ilyen alakú:

	<number-of-paths>NUL<path1>NUL<path2>NUL...<pathN>NUL

és tartalmazza a konfliktus vagy a <conflict-message> tájékoztató üzenet
által érintett útvonalakat (vagy branchneveket).  Továbbá a <conflict-type>
egy stabil sztring, amely a konfliktus típusát magyarázza, például:

  * "Auto-merging"
  * "CONFLICT (rename/delete)"
  * "CONFLICT (submodule lacks merge base)"
  * "CONFLICT (binary)"

a <conflict-message> pedig egy részletesebb üzenet a konfliktusról, amely
gyakran (de nem mindig) beágyazza a <stable-short-type-description>-t.  Ezek
a sztringek a Git jövőbeli verzióiban változhatnak.  Néhány példa:

  * "Auto-merging <file>"
  * "CONFLICT (rename/delete): <oldfile> renamed...but deleted in..."
  * "Failed to merge submodule <submodule> (no merge base)"
  * "Warning: cannot merge binary files: <filename>"

Ha a `-z` NINCS megadva:

Ez a szakasz üres sorral kezdődik, hogy elválassza az előző szakaszoktól,
majd csak az előző szakasz <conflict-message> információját tartalmazza
(sortörésekkel elválasztva).  Ezek nem stabil sztringek, amelyeket
szkriptekkel nem szabad értelmezni, és csak emberi fogyasztásra szánták.
Vedd figyelembe azt is, hogy bár a <conflict-message> sztringek általában
nem tartalmaznak beágyazott sortörést, néha mégis.  (A szabad formátumú
üzenetekben azonban soha nem lesz beágyazott NUL karakter).  Így a teljes
információblokk emberi olvasóknak szól, az összes konfliktusüzenet
összevonásaként.

EXIT STATUS
-----------

Sikeres, konfliktusmentes merge esetén a kilépési állapot 0.  Amikor a
merge-nek konfliktusai vannak, a kilépési állapot 1.  Ha a merge valamilyen
hiba miatt nem tud befejeződni (vagy elindulni), a kilépési állapot 0-tól és
1-től eltérő valami (a kimenet pedig nincs meghatározva).  Amikor a --stdin
meg van adva, a visszatérési állapot 0 mind a sikeres, mind a konfliktusos
merge-ek esetén, és 0-tól, 1-től eltérő valami, ha nem tudja befejezni az
összes kért merge-t.

USAGE NOTES
-----------

Ez a parancs alacsonyszintű plumbingnak készült, hasonlóan a
linkgit:git-hash-object[1], linkgit:git-mktree[1],
linkgit:git-commit-tree[1], linkgit:git-write-tree[1],
linkgit:git-update-ref[1] és linkgit:git-mktag[1] parancsokhoz.  Így egy
lépéssorozat részeként használható, például:

       vi message.txt
       BRANCH1=refs/heads/test
       BRANCH2=main
       NEWTREE=$(git merge-tree --write-tree $BRANCH1 $BRANCH2) || {
           echo "There were conflicts..." 1>&2
           exit 1
       }
       NEWCOMMIT=$(git commit-tree $NEWTREE -F message.txt \
           -p $BRANCH1 -p $BRANCH2)
       git update-ref $BRANCH1 $NEWCOMMIT

Vedd figyelembe, hogy amikor a kilépési állapot nem nulla, a `NEWTREE` ebben
a sorozatban sokkal több kimenetet fog tartalmazni, mint pusztán egy fát.

Konfliktusok esetén a kimenet ugyanazt az információt tartalmazza, amit a
linkgit:git-merge[1] adna:

  * ami a working tree-be lenne írva (a
    <<OIDTLT,legfelső szintű fa OID-ja>>)
  * a magasabb rendű stage-ek, amelyek az indexbe lennének írva (a
    <<CFI,konfliktusos fájlinformáció>>)
  * bármely üzenet, amely a stdoutra lett volna kiírva (a
    <<IM,tájékoztató üzenetek>>)

[[INPUT]]
INPUT FORMAT
------------
A 'git merge-tree --stdin' bemeneti formátuma teljesen szöveges alapú. Minden
sor ilyen formátumú:

	[<base-commit> -- ]<branch1> <branch2>

Ha egy sort `--` választ el, az elválasztó előtti sztring a merge
merge-alapjának megadására szolgál, az elválasztó utáni sztring pedig a
merge-elendő brancheket írja le.

MISTAKES TO AVOID
-----------------

NE a keletkező legfelső szintű fát nézd át, hogy megpróbáld megtalálni,
mely fájlok ütköznek; helyette elemezd a <<CFI,konfliktusos fájlinformáció>>
szakaszt. Nemcsak hogy egy egész fa elemzése iszonyatosan lassú lenne nagy
repositorykban, de számos konfliktustípus nem ábrázolható
konfliktusjelölőkkel (módosítás/törlés, módkonfliktus, mindkét oldalon
megváltozott bináris fájl, fájl-/könyvtárkonfliktusok, különféle
átnevezés-konfliktus-permutációk stb.)

NE értelmezz egy üres <<CFI,konfliktusos fájlinformáció>> listát tiszta
merge-ként; ellenőrizd a kilépési állapotot.  Egy merge-nek lehetnek
konfliktusai anélkül, hogy egyes fájlok ütköznének (van néhány
könyvtárátnevezés-konfliktus-típus, amely ebbe a kategóriába esik, és a
jövőben másokat is hozzáadhatnak).

NE próbáld kitalálni, és ne is a felhasználóval találtasd ki a
konfliktustípusokat a <<CFI,konfliktusos fájlinformáció>> listából.  Az
ottani információ ehhez nem elegendő.  Például: a rename/rename(1to2)
konfliktusok (mindkét oldal másképp nevezte át ugyanazt a fájlt) azt
eredményezik, hogy három különböző fájlnak lesz magasabb rendű stage-e (de
mindegyiknek csak egy magasabb rendű stage-e), és nincs mód (a
<<IM,tájékoztató üzenetek>> szakaszon kívül) annak megállapítására, mely
három fájl kapcsolódik egymáshoz.  A fájl-/könyvtárkonfliktusok szintén
pontosan egy magasabb rendű stage-gel rendelkező fájlt eredményeznek.  A
könyvtárátnevezésben esetleg érintett konfliktusok (amikor a
"merge.directoryRenames" nincs beállítva, vagy "conflicts"-ra van állítva)
szintén pontosan egy magasabb rendű stage-gel rendelkező fájlt
eredményeznek.  Minden esetben a <<IM,tájékoztató üzenetek>> szakaszban
megvan a szükséges információ, bár nem gép általi elemzésre tervezték.

NE feltételezd, hogy a <<CFI,konfliktusos fájlinformáció>> minden útvonala
és a <<IM,tájékoztató üzenetek>> logikai konfliktusai között egy-az-egyhez
leképezés van, sem azt, hogy egy-a-többhöz leképezés, sem azt, hogy
több-az-egyhez leképezés.  Léteznek több-a-többhöz leképezések, ami azt
jelenti, hogy minden útvonalnak sok logikai konfliktustípusa lehet egyetlen
merge-ben, és minden logikai konfliktustípus sok útvonalat érinthet.

NE feltételezd, hogy a <<IM,tájékoztató üzenetek>> szakaszban felsorolt
összes fájlnévnek voltak konfliktusai.  Az üzenetek olyan fájlokhoz is
megjelenhetnek, amelyeknek nincs konfliktusuk, például "Auto-merging <file>".

KERÜLD, hogy kivedd az OID-kat a <<CFI,konfliktusos fájlinformáció>>-ból, és
újra merge-eld őket, hogy a konfliktusokat bemutasd a felhasználónak.  Ez
információt veszít.  Ehelyett keresd meg a fájl <<OIDTLT,legfelső szintű fa
OID-ja>>-n belül található verzióját, és azt mutasd meg helyette.  Ez utóbbi
konkrétan olyan konfliktusjelölőket fog tartalmazni, amelyeket a merge-elt
eredeti branch/commit annotál, és ha átnevezések történtek, az eredeti
fájlnév.  Bár az újra merge-eléskor beilleszthetnéd az eredeti branch/commit
adatot a konfliktusjelölő-annotációkba, az eredeti fájlnév nem érhető el a
<<CFI,konfliktusos fájlinformáció>>-ból, így olyan információt veszítenél,
amely segíthetné a felhasználót a konfliktus feloldásában.

[[DEPMERGE]]
DEPRECATED DESCRIPTION
----------------------

A <<NEWMERGE,DESCRIPTION>> szerint és a dokumentáció többi részétől
eltérően ez a szakasz az elavult `--trivial-merge` módot írja le.

Az opcionális `--trivial-merge`-en kívül ez a mód nem fogad el opciókat.

Ez a mód három tree-ish-t olvas be, és a triviális merge eredményeit és a
konfliktusos stage-eket egy fél-diff formátumban írja a standard kimenetre.
Mivel ezt arra tervezték, hogy magasabb szintű szkriptek dolgozzák fel, és
merge-eljék vissza az eredményeket az indexbe, kihagyja a <branch1>-re
illeszkedő bejegyzéseket.  Ennek a második alaknak az eredménye hasonló
ahhoz, amit a háromutas 'git read-tree -m' tesz, de az eredmények indexben
való tárolása helyett a parancs a bejegyzéseket a standard kimenetre írja.

Ennek az alaknak nemcsak korlátozott az alkalmazhatósága (egy triviális
merge nem tudja kezelni az egyes fájlok tartalmi merge-ét, az
átnevezés-észlelést, a megfelelő könyvtár-/fájlkonfliktus-kezelést stb.),
hanem a kimeneti formátummal is nehéz dolgozni, és általában
teljesítményben is elmarad az első alaktól még sikeres merge-ek esetén is
(különösen nagy repositorykban való munka esetén).

GIT
---
A linkgit:git[1] csomag része
