git-rm(1)
=========

NAME
----
git-rm - Fájlok eltávolítása a munkakönyvtárból és az indexből

SYNOPSIS
--------
[synopsis]
git rm [-f | --force] [-n] [-r] [--cached] [--ignore-unmatch]
       [--quiet] [--pathspec-from-file=<file> [--pathspec-file-nul]]
       [--] [<pathspec>...]

DESCRIPTION
-----------
Eltávolítja a pathspecre illeszkedő fájlokat az indexből, vagy a
munkakönyvtárból és az indexből. A `git rm` nem távolít el fájlt csak a
munkakönyvtáradból. (Nincs opció arra, hogy egy fájlt csak a
munkakönyvtárból távolíts el, de az indexben megtarts; használd a
`/bin/rm`-et, ha ezt szeretnéd.) Az eltávolítandó fájloknak azonosnak
kell lenniük a branch csúcsával, és a tartalmukhoz nem lehet frissítés
stage-elve az indexben, bár ez az alapértelmezett viselkedés
felülbírálható a `-f` opcióval. Ha a `--cached` meg van adva, a
stage-elt tartalomnak vagy a branch csúcsával, vagy a lemezen lévő
fájllal kell egyeznie, lehetővé téve a fájl eltávolítását csak az
indexből. Ha sparse-checkoutok vannak használatban (lásd
linkgit:git-sparse-checkout[1]), a `git rm` csak a sparse-checkout
mintákon belüli elérési utakat távolítja el.


OPTIONS
-------
`<pathspec>...`::
	Az eltávolítandó fájlok.  Egy kezdő könyvtárnév (pl. `dir` a
	`dir/file1` és a `dir/file2` eltávolításához) megadható a könyvtár
	összes fájljának, és rekurzívan az összes alkönyvtárnak az
	eltávolításához, de ehhez a `-r` opciót explicit módon meg kell adni.
+
A parancs csak a Git által ismert elérési utakat távolítja el.
+
A fájl-globbing könyvtárhatárokon át illeszkedik.  Így, adott két
könyvtár, `d` és `d2`, különbség van a `git rm 'd*'` és a `git rm 'd/*'`
használata között, mivel az előbbi a `d2` könyvtár egészét is
eltávolítja.
+
Bővebben lásd a _<pathspec>_ bejegyzést a linkgit:gitglossary[7] oldalon.

`-f`::
`--force`::
	A naprakészség-ellenőrzés felülbírálása.

`-n`::
`--dry-run`::
	Ne távolíts el ténylegesen egyetlen fájlt sem.  Ehelyett csak
	mutasd meg, hogy léteznek-e az indexben, és egyébként a parancs
	eltávolítaná-e őket.

`-r`::
        Rekurzív eltávolítás engedélyezése, amikor kezdő könyvtárnév
        van megadva.

`--`::
	Ezzel az opcióval elválaszthatók a parancssori opciók a fájlok
	listájától (hasznos, amikor a fájlneveket parancssori opciónak
	lehet nézni).

`--cached`::
	Ezzel az opcióval unstage-elheted és eltávolíthatod az elérési
	utakat csak az indexből.  A munkakönyvtárbeli fájlokat, akár
	módosítottak, akár nem, békén hagyja.

`--ignore-unmatch`::
	Nulla státusszal lép ki akkor is, ha egyetlen fájl sem illeszkedett.

`--sparse`::
	Engedélyezi a sparse-checkout cone-on kívüli indexbejegyzések
	frissítését.  Normál esetben a `git rm` megtagadja azon
	indexbejegyzések frissítését, amelyek elérési útja nem fér bele a
	sparse-checkout cone-ba. Bővebben lásd a linkgit:git-sparse-checkout[1] oldalt.

`-q`::
`--quiet`::
	A `git rm` normál esetben minden eltávolított fájlhoz egy sort ír ki
	(egy `rm` parancs formájában). Ez az opció elnyomja ezt a kimenetet.

`--pathspec-from-file=<file>`::
	A pathspec a _<file>_-ban van átadva argumentumok helyett. Ha a
	_<file>_ pontosan `-`, akkor a standard bemenet lesz használva. A
	pathspec-elemeket _LF_ vagy _CR_/_LF_ választja el. A pathspec-elemek
	idézőjelezhetők a `core.quotePath` konfigurációs változónál leírtak
	szerint (lásd linkgit:git-config[1]). Lásd még a `--pathspec-file-nul`
	opciót és a globális `--literal-pathspecs` opciót.

`--pathspec-file-nul`::
	Csak a `--pathspec-from-file`-lal van értelme. A pathspec-elemeket
	_NUL_ karakter választja el, és minden más karakter szó szerint
	értendő (beleértve a sortöréseket és az idézőjeleket).


REMOVING FILES THAT HAVE DISAPPEARED FROM THE FILESYSTEM
--------------------------------------------------------
A `git rm`-nek nincs opciója arra, hogy az indexből csak azokat az
elérési utakat távolítsa el, amelyek eltűntek a fájlrendszerből.
Azonban a felhasználási esettől függően több módon is megtehető
ez.

[[_using_git_commit_a]]
A ``git commit -a'' használata
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ha azt szeretnéd, hogy a következő commitod rögzítse a munkakönyvtárban
követett fájlok összes módosítását, és rögzítse azon fájlok összes
eltávolítását, amelyeket a munkakönyvtárból `rm`-mel (nem `git rm`-mel)
távolítottak el, használd a `git commit -a`-t, mivel az automatikusan
észreveszi és rögzíti az összes eltávolítást.  Hasonló hatást commitolás
nélkül is elérhetsz a `git add -u` használatával.

[[_using_git_add_a]]
A ``git add -A'' használata
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Amikor egy vendor branchhez új kódcsomagot fogadsz el, valószínűleg
rögzíteni akarod az elérési utak eltávolítását és az új elérési utak
hozzáadását is, valamint a meglévő elérési utak módosításait.

Jellemzően először eltávolítanád az összes követett fájlt a
munkakönyvtárból ezzel a paranccsal:

----------------
git ls-files -z | xargs -0 rm -f
----------------

majd kitömörítenéd az új kódot a munkakönyvtárba. Alternatívaként
'rsync'-elhetnéd a változásokat a munkakönyvtárba.

Ezután a legegyszerűbb módja annak, hogy rögzítsd a munkakönyvtárban
lévő összes eltávolítást, hozzáadást és módosítást:

----------------
git add -A
----------------

Lásd a linkgit:git-add[1] oldalt.

[[_other_ways]]
Egyéb módok
~~~~~~~~~~~
Ha csak annyit szeretnél, hogy az indexből eltávolítsd azokat a
fájlokat, amelyek már nincsenek jelen a munkakönyvtárban (talán mert a
munkakönyvtárad piszkos, így nem tudod használni a `git commit -a`-t),
használd a következő parancsot:

----------------
git diff --name-only --diff-filter=D -z | xargs -0 git rm --cached
----------------

SUBMODULES
----------
Csak a gitfile-t használó submodule-ok (ami azt jelenti, hogy 1.7.8-as
vagy újabb Git-verzióval klónozták őket) lesznek eltávolítva a
munkakönyvtárból, mivel a repository-juk a szuperprojekt `.git`
könyvtárán belül él. Ha egy submodule (vagy egy benne egymásba ágyazott
submodule) még mindig `.git` könyvtárat használ, a `git rm` áthelyezi a
submodule git-könyvtárát a szuperprojekt git-könyvtárába, hogy megvédje a
submodule előzményét. Ha létezik, a linkgit:gitmodules[5] fájlban lévő
`submodule.<name>` szekció is eltávolításra kerül, és az a fájl
stage-elve lesz (hacsak a `--cached` vagy a `-n` nincs használatban).

Egy submodule akkor számít naprakésznek, ha a `HEAD` ugyanaz, mint ami
az indexben rögzítve van, egyetlen követett fájl sincs módosítva, és
nincs a submodule munkakönyvtárában olyan nem követett fájl, amely nincs
figyelmen kívül hagyva.  A figyelmen kívül hagyott fájlok
nélkülözhetőnek tekintendők, és nem akadályozzák meg a submodule
munkakönyvtárának eltávolítását.

Ha csak egy submodule helyi checkoutját szeretnéd eltávolítani a
munkakönyvtáradból az eltávolítás commitolása nélkül, használd helyette a
linkgit:git-submodule[1] `deinit`-et. A submodule-eltávolítás
részleteiért lásd még a linkgit:gitsubmodules[7] oldalt.

EXAMPLES
--------
`git rm Documentation/\*.txt`::
	Eltávolítja az indexből az összes `*.txt` fájlt, amely a
	`Documentation` könyvtár és bármely alkönyvtára alatt van.
+
Vedd figyelembe, hogy a csillag `*` ebben a példában a shell elől
idézőjelezve van; ez lehetővé teszi, hogy a Git, és ne a shell, bontsa
ki a `Documentation/` könyvtár alatti fájlok és alkönyvtárak elérési útjait.

`git rm -f git-*.sh`::
	Mivel ez a példa hagyja, hogy a shell bontsa ki a csillagot
	(azaz explicit módon sorolod fel a fájlokat), nem távolítja el a
	`subdir/git-foo.sh`-t.

BUGS
----
Minden alkalommal, amikor egy szuperprojekt-frissítés eltávolít egy
feltöltött submodule-t (pl. az eltávolítás előtti és utáni commitok
közötti váltáskor), egy elavult submodule-checkout marad a régi helyen.
A régi könyvtár eltávolítása csak akkor biztonságos, ha az gitfile-t
használ, mivel egyébként a submodule előzménye is törlődik. Ez a lépés
elavulttá válik, amikor a rekurzív submodule-frissítés megvalósul.

SEE ALSO
--------
linkgit:git-add[1]

GIT
---
A linkgit:git[1] csomag része
