git-var(1)
==========

NAME
----
git-var - Egy Git logikai változó megjelenítése


SYNOPSIS
--------
[synopsis]
git var (-l | <variable>)

DESCRIPTION
-----------
Kiír egy Git logikai változót. 1-es kóddal lép ki, ha a változónak
nincs értéke.

OPTIONS
-------
`-l`::
	Megjeleníti a logikai változókat. Ezenkívül a .git/config Git
	konfigurációs fájl összes változóját is listázza. (A
	konfigurációs változók listázása azonban elavult, helyette a
	`git config list` használandó.)

EXAMPLES
--------
	$ git var GIT_AUTHOR_IDENT
	Eric W. Biederman <ebiederm@lnxi.com> 1121223278 -0600


VARIABLES
---------
`GIT_AUTHOR_IDENT`::
    Egy kódrészlet szerzője.

`GIT_COMMITTER_IDENT`::
    A személy, aki egy kódrészletet a Gitbe helyezett.

`GIT_EDITOR`::
    Git-parancsok által használandó szövegszerkesztő.  Az értéket a
    shell értelmezi, amikor használatba kerül.  Példák: `~/bin/vi`,
    `$SOME_ENVIRONMENT_VARIABLE`, `"C:\Program Files\Vim\gvim.exe"
    --nofork`.  A preferencia sorrendje: `$GIT_EDITOR`, majd a
    `core.editor` konfigurációs érték, majd `$VISUAL`, majd
    `$EDITOR`, végül a fordításkor kiválasztott alapértelmezés,
    ami általában a 'vi'.
ifdef::git-default-editor[]
    Az általad használt build a '{git-default-editor}'-t választotta alapértelmezésnek.
endif::git-default-editor[]

`GIT_SEQUENCE_EDITOR`::
    A 'todo' fájl szerkesztésére használt szövegszerkesztő a `git
    rebase -i` futtatása közben. A `GIT_EDITOR`-hoz hasonlóan az
    értéket a shell értelmezi, amikor használatba kerül. A
    preferencia sorrendje: `$GIT_SEQUENCE_EDITOR`, majd a
    `sequence.editor` konfigurációs érték, végül a `git var
    GIT_EDITOR` értéke.

`GIT_PAGER`::
    Git-parancsok által használandó szövegmegjelenítő (pl. 'less').  Az
    értéket a shell értelmezi.  A preferencia sorrendje: `$GIT_PAGER`,
    majd a `core.pager` konfiguráció értéke, majd `$PAGER`, végül a
    fordításkor kiválasztott alapértelmezés (általában `less`).
ifdef::git-default-pager[]
    Az általad használt build a '{git-default-pager}'-t választotta alapértelmezésnek.
endif::git-default-pager[]

`GIT_DEFAULT_BRANCH`::
    Az újonnan inicializált repository-kban létrehozott első branch neve.

`GIT_SHELL_PATH`::
    A POSIX shellt biztosító bináris útvonala a shellt használó parancsok számára.

`GIT_ATTR_SYSTEM`::
    A rendszerszintű linkgit:gitattributes[5] fájl útvonala, ha van engedélyezve.

`GIT_ATTR_GLOBAL`::
    A globális (felhasználónkénti) linkgit:gitattributes[5] fájl útvonala.

`GIT_CONFIG_SYSTEM`::
    A rendszerszintű konfigurációs fájl útvonala, ha van engedélyezve.

`GIT_CONFIG_GLOBAL`::
    A globális (felhasználónkénti) konfigurációs fájlok útvonala, ha vannak.

A legtöbb útvonalérték csak egyetlen értéket tartalmaz. Néhány azonban
több értéket is tartalmazhat, amelyeket sortörések választanak el, és a
legmagasabbtól a legalacsonyabb prioritásig vannak felsorolva. A
hívóknak fel kell készülniük arra, hogy bármelyik ilyen útvonalérték
több elemet tartalmazhat.

Vedd figyelembe, hogy az útvonalak akkor is kiíródnak, ha nem léteznek,
de nem, ha más környezeti változók letiltják őket.

SEE ALSO
--------
linkgit:git-commit-tree[1]
linkgit:git-tag[1]
linkgit:git-config[1]

GIT
---
A linkgit:git[1] csomag része
