git-multi-pack-index(1)
=======================

NAME
----
git-multi-pack-index - Multi-pack-indexek írása és ellenőrzése


SYNOPSIS
--------
[verse]
'git multi-pack-index' [<options>] write [--preferred-pack=<pack>]
		         [--[no-]bitmap] [--[no-]incremental] [--[no-]stdin-packs]
		         [--refs-snapshot=<path>] [--[no-]write-chain-file]
			 [--base=<checksum>]
'git multi-pack-index' [<options>] compact [--[no-]incremental]
		         [--[no-]bitmap] [--base=<checksum>] [--[no-]write-chain-file]
			 <from> <to>
'git multi-pack-index' [<options>] verify
'git multi-pack-index' [<options>] expire
'git multi-pack-index' [<options>] repack [--batch-size=<size>]

DESCRIPTION
-----------
Multi-pack-index (MIDX) fájl írása vagy ellenőrzése.

OPTIONS
-------

A következő parancssori opciók minden alparancsra alkalmazhatók:

--object-dir=<dir>::
	A megadott könyvtár használata a Git-objektumok helyeként. A
	`<dir>/packs/multi-pack-index`-et nézzük a jelenlegi MIDX-fájlért, és
	a `<dir>/packs`-et az indexelendő pack-fájlokért.
+
A `<dir>`-nek a jelenlegi repository egy alternate-jének kell lennie.

--progress::
--no-progress::
	A folyamatjelzés explicit be-/kikapcsolása. Ha egyik sincs megadva, a
	folyamatjelzés akkor jelenik meg, ha a standard hibakimenet terminálhoz
	van kapcsolva. A `write`, `verify`, `expire` és `repack` alparancs támogatja.

A következő alparancsok érhetők el:

write::
	Új MIDX-fájl írása. A következő opciók érhetők el a `write`
	alparancshoz:
+
--
	--preferred-pack=<pack>::
		Ha meg van adva, ennek a packnek a javára dönti el a
		holtversenyt, amikor az objektumainak további másolatai
		vannak más packekben. A preferált packben nem található
		objektumok holtversenye mindig a legmagasabb mtime-ú
		packben lévő másolat javára dől el. Ha nincs megadva,
		alapból a legalacsonyabb mtime-ú pack lesz használva. A
		preferált packnek legalább egy objektumot tartalmaznia kell.

	--[no-]bitmap::
		Szabályozza, hogy íródjon-e multi-pack bitmap.

	--stdin-packs::
		Olyan multi-pack index írása, amely csak a stdinen megadott,
		sortöréssel elválasztott pack-index-basename-ek halmazát tartalmazza.

	--refs-snapshot=<path>::
		A `--bitmap`-pel opcionálisan megadható egy fájl, amely az
		újracsomagolás előtt készített "refs snapshot"-ot tartalmaz.
+
A reference snapshot a referencia-csúcsoknak megfelelő, sortöréssel
elválasztott OID-kból áll, amelyet általában a `git repack` készít egy új
pack generálása előtt. Egy sor opcionálisan kezdődhet `+` karakterrel,
jelezve, hogy az adott OID-nak megfelelő referencia "preferált" (lásd a
linkgit:git-config[1] `pack.preferBitmapTips` beállítását).
+
A `<path>`-nál megadott fájltól elvárt, hogy olvasható legyen, és
tartalmazhat duplikátumokat. (Ha egy adott OID többször is meg van adva,
akkor preferáltként lesz megjelölve, ha legalább egy előfordulása a
speciális `+` jelölővel kezdődik.)

	--incremental::
		Olyan inkrementális MIDX-fájl írása, amely csak egy
		meglévő MIDX-rétegben nem szereplő objektumokat és
		packeket tartalmaz. Szükség esetén a nem inkrementális
		MIDX-eket inkrementálisra migrálja.

	--[no-]write-chain-file::
		A `--incremental`-lal használva új MIDX-réteget ír, de
		nem frissíti a multi-pack-index-chain fájlt. Az új réteg
		ellenőrzőösszege a standard kimenetre kerül, így a hívó
		maga állíthatja össze és írhatja a láncot. `--incremental`
		szükséges hozzá.

	--base=<checksum>::
		Egy meglévő MIDX-réteg ellenőrzőösszegének megadása,
		amelyet alapként kell használni egy új inkrementális
		réteg írásakor. A speciális `none` érték azt jelzi, hogy
		az új rétegnek ne legyen alapja (azaz gyökérréteg lesz).
		`--no-write-chain-file` szükséges hozzá.
--

compact::
	Olyan új MIDX-réteg írása, amely csak a `<from>`-tól `<to>`-ig
	terjedő tartományban lévő objektumokat és packeket tartalmazza,
	ahol mindkét argumentum a MIDX-lánc meglévő rétegeinek ellenőrzőösszege.
+
--
	--incremental::
		Az eredmény MIDX-láncba írása, önálló MIDX írása helyett.

	--[no-]bitmap::
		Szabályozza, hogy íródjon-e multi-pack bitmap.

	--[no-]write-chain-file::
		A `--incremental`-lal használva új tömörített MIDX-réteget
		ír, de nem frissíti a multi-pack-index-chain fájlt. Az új
		réteg ellenőrzőösszege a standard kimenetre kerül.
		`--incremental` szükséges hozzá.

	--base=<checksum>::
		Egy meglévő MIDX-réteg ellenőrzőösszegének megadása,
		amelyet a tömörített eredmény alapjaként kell használni, a
		`<from>` közvetlen szülője helyett. A speciális `none`
		érték azt jelzi, hogy az eredménynek ne legyen alapja.
--
+
Vedd figyelembe, hogy a compact parancs egy 2-es verziójú midx írását
igényli, amelyet a v2.54 előtti Git-verziók nem tudnak olvasni.

verify::
	A MIDX-fájl tartalmának ellenőrzése.

expire::
	Azon pack-fájlok törlése, amelyeket a MIDX-fájl követ, de
	amelyeknek nincs a MIDX által hivatkozott objektuma (a `.keep`
	packek és a cruft packek kivételével). Utána a MIDX-fájl
	újraírása, hogy eltávolítson minden hivatkozást ezekre a pack-fájlokra.
+
NOTE: ez a mód nem kompatibilis az inkrementális MIDX-fájlokkal.

repack::
	Új pack-fájl létrehozása, amely a multi-pack-index által
	hivatkozott kis pack-fájlok objektumait tartalmazza. Ha a
	`--batch-size=<size>` argumentummal megadott méret nulla, akkor
	egy olyan packet hoz létre, amely a multi-pack-index által
	hivatkozott összes objektumot tartalmazza. Nem nulla
	kötegméretnél a pack-fájlokat úgy választja ki, hogy a packeket
	a legrégebbitől a legújabbig vizsgálja, kiszámítja a "várható
	méretet" a multi-pack-index által hivatkozott packben lévő
	objektumok számának megszámolásával, majd elosztja a packben
	lévő objektumok teljes számával, és megszorozza a pack
	méretével. Azokat a packeket választjuk, amelyek várható mérete
	a kötegméret alatt van, amíg a packek halmazának teljes várható
	mérete el nem éri legalább a kötegméretet, vagy amíg az összes
	pack-fájlt figyelembe nem vettük. Ha csak egy pack-fájl van
	kiválasztva, akkor nem csinál semmit. Ha új pack-fájl jön létre,
	újraírja a multi-pack-indexet, hogy az az új pack-fájlra
	hivatkozzon. A 'git multi-pack-index expire' egy későbbi futása
	törli azokat a pack-fájlokat, amelyek ennek a kötegnek a részei voltak.
+
Ha a `repack.packKeptObjects` értéke `false`, akkor a hozzájuk tartozó
`.keep` fájllal rendelkező pack-fájlok nem lesznek kiválasztva az
újracsomagolandó kötegbe.
+
NOTE: ez a mód nem kompatibilis az inkrementális MIDX-fájlokkal.

EXAMPLES
--------

* MIDX-fájl írása a jelenlegi `.git` könyvtárban lévő packfile-okhoz.
+
-----------------------------------------------
$ git multi-pack-index write
-----------------------------------------------

* MIDX-fájl írása a jelenlegi `.git` könyvtárban lévő packfile-okhoz egy
megfelelő bitmappel.
+
-------------------------------------------------------------
$ git multi-pack-index write --preferred-pack=<pack> --bitmap
-------------------------------------------------------------

* MIDX-fájl írása egy alternate objektumtárban lévő packfile-okhoz.
+
-----------------------------------------------
$ git multi-pack-index --object-dir <alt> write
-----------------------------------------------

* A jelenlegi `.git` könyvtárban lévő packfile-ok MIDX-fájljának ellenőrzése.
+
-----------------------------------------------
$ git multi-pack-index verify
-----------------------------------------------


SEE ALSO
--------
A multi-pack-index funkcióról és fájlformátumáról bővebb információért
lásd a link:technical/multi-pack-index.html[A Multi-Pack-Index tervezési
dokumentum] leírást és a linkgit:gitformat-pack[5] oldalt.


GIT
---
A linkgit:git[1] csomag része
