git-send-pack(1)
================

NAME
----
git-send-pack - Objektumok pusholása Git protokollon keresztül egy másik repository-ba


SYNOPSIS
--------
[verse]
'git send-pack' [--mirror] [--dry-run] [--force]
		[--receive-pack=<git-receive-pack>]
		[--verbose] [--thin] [--atomic]
		[--[no-]signed | --signed=(true|false|if-asked)]
		[<host>:]<directory> (--all | <ref>...)

DESCRIPTION
-----------
Általában helyette a 'git push'-t szeretnéd használni, amely ennek a
parancsnak a magasabb szintű burkolója. L. linkgit:git-push[1].

Meghívja a 'git-receive-pack'-et egy esetleg remote repository-n, és
frissíti azt az aktuális repository-ból, megnevezett refeket küldve.


OPTIONS
-------
--receive-pack=<git-receive-pack>::
	A 'git-receive-pack' program útvonala a remote végponton.  Néha
	hasznos, amikor egy remote repository-ba pusholsz ssh-n keresztül,
	és a program nincs az alapértelmezett $PATH egyik könyvtárában sem.

--exec=<git-receive-pack>::
	Ugyanaz, mint a --receive-pack=<git-receive-pack>.

--all::
	Ahelyett, hogy explicit módon megadnád, mely refeket kell frissíteni,
	az összes lokálisan létező head frissítése.

--stdin::
	A refek listájának beolvasása az stdinről, soronként egyet. Ha ezen
	opción felül a parancssorban is meg vannak adva refek, akkor az
	stdinről érkező refek a parancssoriak után kerülnek feldolgozásra.
+
Ha a `--stateless-rpc` ezzel az opcióval együtt van megadva, akkor a
refek listájának csomag formátumban (pkt-line) kell lennie. Minden refnek
külön csomagban kell lennie, és a listának egy flush csomaggal kell
végződnie.

--dry-run::
	Minden elvégzése, kivéve a frissítések tényleges elküldését.

--force::
	A parancs általában megtagadja egy olyan remote ref frissítését,
	amely nem őse a felülíráshoz használt lokális refnek.  Ez a flag
	kikapcsolja az ellenőrzést.  Ez azt jelenti, hogy a remote repository
	commitokat veszíthet; óvatosan használd.

--verbose::
	Futtatás bőbeszédűen.

--thin::
	"thin" (vékony) pack küldése, amely az objektumokat deltásított
	formában rögzíti a packbe nem tartozó objektumok alapján, hogy
	csökkentse a hálózati forgalmat.

--atomic::
	Atomi tranzakció használata a refek frissítéséhez. Ha bármelyik ref
	frissítése meghiúsul, az egész push meghiúsul anélkül, hogy bármely
	refet megváltoztatna.

--signed::
--no-signed::
--signed=(true|false|if-asked)::
	A push-kérés GPG-aláírása a refek frissítéséhez a fogadó oldalon,
	hogy a hookok ellenőrizhessék és/vagy naplózhassák.  A `false` vagy a
	`--no-signed` esetén nem történik aláírási kísérlet.  A `true` vagy a
	`--signed` esetén a push meghiúsul, ha a szerver nem támogatja az
	aláírt pusht.  Ha `if-asked`-re van állítva, akkor és csak akkor ír
	alá, ha a szerver támogatja az aláírt pusht.  A push akkor is
	meghiúsul, ha a `gpg --sign` tényleges hívása meghiúsul.  A fogadó
	oldal részleteiért l. linkgit:git-receive-pack[1].

--push-option=<string>::
	A megadott karakterlánc átadása push-opcióként a szerveroldali
	hookok általi feldolgozásra.  Ha a szerver nem támogatja a
	push-opciókat, hibával kilép.  A részletekért l. linkgit:git-push[1]
	és linkgit:githooks[5].

<host>::
	Egy remote hoszt a repository elhelyezésére.  Ha ez a rész meg van
	adva, a 'git-receive-pack' ssh-n keresztül hívódik meg.

<directory>::
	A frissítendő repository.

<ref>...::
	A frissítendő remote refek.


SPECIFYING THE REFS
-------------------

Háromféleképpen adható meg, hogy mely refeket kell frissíteni a remote
végponton.

A `--all` flaggel az összes lokálisan létező ref átvitelre kerül a
remote oldalra.  Ha ezt a flaget használod, nem adhatsz meg egyetlen
'<ref>'-et sem.

A `--all` és bármely '<ref>' nélkül azok a headek frissülnek, amelyek
a lokális és a remote oldalon egyaránt léteznek.

Ha egy vagy több '<ref>' explicit módon van megadva (akár a
parancssorban, akár a `--stdin`-en keresztül), az lehet egyetlen minta,
vagy két ilyen minta párja kettősponttal ":" elválasztva (ez azt
jelenti, hogy egy refnévben nem lehet kettőspont).  Egyetlen '<name>'
minta csak a '<name>:<name>' rövidítése.

Minden mintapár a forrásoldalból (a kettőspont előtt) és a céloldalból
(a kettőspont után) áll.  A pusholandó ref úgy határozódik meg, hogy
a forrásoldalra illeszkedő találatot keresünk, az pedig, hogy hova
pusholódik, a céloldal használatával határozódik meg. A ref
illesztésére használt szabályok ugyanazok, mint amelyeket a
'git rev-parse' használ egy szimbolikus refnév feloldására.
L. linkgit:git-rev-parse[1].

 - Hiba, ha a <src> nem pontosan egy lokális refre illeszkedik.

 - Hiba, ha a <dst> egynél több remote refre illeszkedik.

 - Ha a <dst> nem illeszkedik egyetlen remote refre sem, akkor vagy

   * "refs/"-fel kell kezdődnie; ebben az esetben a <dst> szó szerint
     használatos célként.

   * <src> == <dst>, és a <src>-re illeszkedő ref nem létezhet a remote
     refek halmazában; a lokálisan a <src>-re illeszkedő ref használatos
     a cél neveként.

A `--force` nélkül a <src> ref csak akkor tárolódik a remote-on, ha a
<dst> nem létezik, vagy a <dst> a <src> valódi részhalmaza (azaz őse).
Ezt az ellenőrzést, amely „fast-forward ellenőrzés" néven ismert, azért
végzik, hogy elkerüljék a remote ref véletlen felülírását és mások
commitjainak elvesztését onnan.

A `--force` esetén a fast-forward ellenőrzés minden refre ki van kapcsolva.

Opcionálisan egy <ref> paraméter elé plusz '+' jel tehető, hogy a
fast-forward ellenőrzés csak azon a refen legyen kikapcsolva.

GIT
---
A linkgit:git[1] csomag része
