git-mergetool(1)
================

NAME
----
git-mergetool - Merge-konfliktus-feloldó eszközök futtatása a merge-konfliktusok feloldására

SYNOPSIS
--------
[synopsis]
git mergetool [--tool=<tool>] [-y | --[no-]prompt] [<file>...]

DESCRIPTION
-----------

A `git mergetool`-lal futtathatod a többféle merge-segédeszköz egyikét a
merge-konfliktusok feloldására.  Jellemzően a `git merge` után futtatják.

Ha egy vagy több <file> paramétert megadsz, a merge-eszköz program az
egyes fájlokban lévő eltérések feloldására fut (kihagyva a konfliktus
nélkülieket).  Egy könyvtár megadása az adott útvonalon lévő összes
feloldatlan fájlt beveszi.  Ha nincs _<file>_ név megadva, a `git mergetool`
a merge-eszköz programot minden merge-konfliktusos fájlon lefuttatja.

OPTIONS
-------
`-t <tool>`::
`--tool=<tool>`::
	A _<tool>_ által megadott merge-feloldó program használata.
	Az érvényes értékek közé tartozik az `emerge`, `gvimdiff`, `kdiff3`,
	`meld`, `vimdiff` és `tortoisemerge`. Az érvényes _<tool>_ beállítások
	listájáért futtasd a `git mergetool --tool-help`-et.
+
Ha nincs megadva merge-feloldó program, a `git mergetool` a `merge.tool`
konfigurációs változót használja.  Ha a `merge.tool` konfigurációs változó
nincs beállítva, a `git mergetool` egy megfelelő alapértelmezést választ.
+
Az eszközhöz explicit módon megadhatsz teljes útvonalat a
`mergetool.<tool>.path` konfigurációs változó beállításával. Például a
kdiff3 abszolút útvonalát a `mergetool.kdiff3.path` beállításával
konfigurálhatod. Egyébként a `git mergetool` feltételezi, hogy az eszköz
elérhető a `$PATH`-ban.
+
Az ismert merge-eszköz programok egyikének futtatása helyett a
`git mergetool` testre szabható úgy, hogy egy alternatív programot
futtasson, ha a meghívandó parancssort a `mergetool.<tool>.cmd`
konfigurációs változóban megadod.
+
Amikor a `git mergetool` ezzel az eszközzel indul (akár a `-t` vagy
`--tool` opción, akár a `merge.tool` konfigurációs változón keresztül),
a konfigurált parancssor a következőkkel hívódik meg: a `BASE` egy olyan
ideiglenes fájl nevére van állítva, amely a merge közös alapját tartalmazza,
ha elérhető; a `LOCAL` egy olyan ideiglenes fájl nevére, amely a fájl
aktuális branchen lévő tartalmát tartalmazza; a `REMOTE` egy olyan
ideiglenes fájl nevére, amely a merge-elendő fájl tartalmát tartalmazza;
a `MERGED` pedig annak a fájlnak a nevére, amelybe a merge-eszköznek a
merge-feloldás eredményét kell írnia.
+
Ha az egyéni merge-eszköz a kilépési kódjával helyesen jelzi egy
merge-feloldás sikerét, akkor a `mergetool.<tool>.trustExitCode`
konfigurációs változó `true`-ra állítható.  Egyébként a `git mergetool`
az egyéni eszköz kilépése után rákérdez a felhasználónál a feloldás
sikerére.

`--tool-help`::
	A `--tool`-lal használható merge-eszközök listájának kiírása.

`-y`::
`--no-prompt`::
	Ne kérdezzen rá a merge-feloldó program minden meghívása előtt.
	Ez az alapértelmezés, ha a merge-feloldó program explicit módon
	meg van adva a `--tool` opcióval vagy a `merge.tool` konfigurációs
	változóval.

`--prompt`::
	Rákérdezés a merge-feloldó program minden meghívása előtt, hogy a
	felhasználó kihagyhassa az adott útvonalat.

`-g`::
`--gui`::
	Amikor a `git-mergetool` a `-g` vagy `--gui` opcióval indul, az
	alapértelmezett merge-eszköz a `merge.tool` helyett a konfigurált
	`merge.guitool` változóból olvasódik be. Ha a `merge.guitool` nincs
	beállítva, a `merge.tool` alatt konfigurált eszközre esünk vissza.
	Ez automatikusan is kiválasztható a `mergetool.guiDefault`
	konfigurációs változóval.

`--no-gui`::
	Ez felülbírálja a korábbi `-g` vagy `--gui` beállítást vagy a
	`mergetool.guiDefault` konfigurációt, és az alapértelmezett
	merge-eszközt a konfigurált `merge.tool` változóból olvassa be.

`-O<orderfile>`::
	A fájlok feldolgozása az _<orderfile>_-ban megadott sorrendben,
	amely soronként egy shell glob mintát tartalmaz.
	Ez felülbírálja a `diff.orderFile` konfigurációs változót
	(l. linkgit:git-config[1]).  A `diff.orderFile` érvénytelenítéséhez
	használd a `-O/dev/null`-t.

CONFIGURATION
-------------
:git-mergetool: 1

include::includes/cmd-config-section-all.adoc[]

include::config/mergetool.adoc[]

TEMPORARY FILES
---------------
A `git mergetool` `*.orig` biztonságimentés-fájlokat hoz létre a merge-ek
feloldása közben.  Ezek biztonságosan eltávolíthatók, miután egy fájl
merge-elve lett, és a hozzá tartozó `git mergetool` munkamenet befejeződött.

Ha a `mergetool.keepBackup` konfigurációs változót `false`-ra állítod, a
`git mergetool` automatikusan eltávolítja a biztonságimentés-fájlokat,
ahogy a fájlok sikeresen merge-elődnek.

BACKEND SPECIFIC HINTS
----------------------

vimdiff
~~~~~~~
include::mergetools/vimdiff.adoc[]

GIT
---
A linkgit:git[1] csomag része
