git-sparse-checkout(1)
======================

NAME
----
git-sparse-checkout - Reduce your working tree to a subset of tracked files


SYNOPSIS
--------
[verse]
'git sparse-checkout' (init | list | set | add | reapply | disable | check-rules | clean) [<options>]


DESCRIPTION
-----------

Ez a parancs sparse checkoutok létrehozására szolgál, amelyek a
working tree-t az összes követett fájl jelenlétéből ezen fájlok csak egy
részhalmazának jelenlétévé változtatják.  Azt is átválthatja, hogy mely fájl-részhalmaz van
jelen, vagy visszavonhatja, és visszaállhat az összes követett fájl jelenlétére
a munkamásolatban.

A fájlok részhalmazát vagy könyvtárak listájának megadásával választják ki
cone módban (ez az alapértelmezés), vagy minták listájának megadásával
non-cone módban.

Amikor sparse-checkoutban vagy, más Git-parancsok kissé eltérően viselkednek.
Például a branchváltás nem frissíti a sparse-checkout könyvtárakon/mintákon
kívüli útvonalakat, és a `git commit -a` nem rögzíti töröltként a
sparse-checkout könyvtárakon/mintákon kívüli útvonalakat.

EZ A PARANCS KÍSÉRLETI. A VISELKEDÉSE, ÉS MÁS PARANCSOK VISELKEDÉSE
SPARSE-CHECKOUTOK JELENLÉTÉBEN, VALÓSZÍNŰLEG MEGVÁLTOZIK A
JÖVŐBEN.


COMMANDS
--------
'list'::
	Leírja a sparse-checkout fájlban lévő könyvtárakat vagy mintákat.

'set'::
	Engedélyezi a szükséges sparse-checkout config-beállításokat
	(`core.sparseCheckout`, `core.sparseCheckoutCone` és
	`index.sparse`), ha még nincsenek a kívánt értékekre állítva,
	feltölti a sparse-checkout fájlt a 'set' alparancsot követő argumentumok
	listájából, és ennek megfelelően frissíti a
	munkakönyvtárat.
+
Annak biztosítására, hogy a sparse-checkout beállítások egy worktree-n belüli módosítása
ne változtassa meg a sparse-checkout beállításokat más worktree-kben, a 'set'
alparancs a repository configodat worktree-specifikus config használatára fejleszti,
ha még nincs jelen. A 'set' alparancs argumentumai által definiált
ritkaság a worktree-specifikus sparse-checkout fájlban tárolódik.
További részletekért lásd a linkgit:git-worktree[1] oldalt és az
`extensions.worktreeConfig` dokumentációját a linkgit:git-config[1] oldalon.
+
Amikor a `--stdin` opció meg van adva, a könyvtárak vagy minták a
standard bemenetről kerülnek beolvasásra sortöréssel elválasztott listaként, az
argumentumok helyett.
+
Alapból a bemeneti lista könyvtárak listájának tekintendő, megegyezve
a `git ls-tree -d --name-only` kimenetével.  Ez magában foglalja, hogy a
kettős idézőjellel (") kezdődő útvonalneveket C-stílusú idézőjeles sztringekként értelmezi.
Vedd figyelembe, hogy a megadott könyvtárak alatti összes fájl (bármilyen mélységben)
bekerül a sparse checkoutba, valamint azok a fájlok is, amelyek a megadott könyvtár
vagy annak bármely őse testvérei (lásd a 'CONE PATTERN
SET' szakaszt lentebb a további részletekért).  A múltban ez nem volt az alapértelmezés,
és meg kellett adni a `--cone` opciót, vagy engedélyezni kellett a `core.sparseCheckoutCone`
opciót.
+
Amikor a `--no-cone` van megadva, a bemeneti lista minták listájának
tekintendő.  Ennek a módnak számos hátránya van, beleértve azt, hogy nem működik
bizonyos opciókkal, mint a `--sparse-index`.  Ahogy a lenti
"Non-cone Problems" szakasz elmagyarázza, nem javasoljuk a használatát.
+
Használd a `--[no-]sparse-index` opciót egy sparse index használatához (az
alapértelmezés az, hogy nem használja).  Egy sparse index csökkenti az index
méretét, hogy szorosabban igazodjon a sparse-checkout
definíciódhoz. Ennek jelentős teljesítménybeli előnyei lehetnek olyan
parancsoknál, mint a `git status` vagy `git add`.  Ez a funkció még
kísérleti. Egyes parancsok lassabbak lehetnek egy sparse indexszel, amíg
megfelelően nem integrálják őket a funkcióval.
+
**WARNING:** Egy sparse index használatához az indexet olyan módon kell módosítani,
amelyet a külső eszközök nem teljesen értenek. Ha problémáid vannak
ezzel a kompatibilitással, akkor futtasd a `git sparse-checkout init --no-sparse-index`
parancsot, hogy az indexedet nem ritkává írd át. A Git régebbi verziói nem
értik a sparse könyvtárbejegyzés-index kiterjesztést, és nem tudnak
interakcióba lépni a repository-ddal, amíg le nem tiltják.

'add'::
	Frissíti a sparse-checkout fájlt további könyvtárak
	(cone módban) vagy minták (non-cone módban) felvételéhez.  Alapból ezek a
	könyvtárak vagy minták a parancssori argumentumokból kerülnek beolvasásra,
	de a `--stdin` opcióval a stdin-ről is beolvashatók.

'reapply'::
	Újra alkalmazza a ritkasági minta szabályait a working tree útvonalaira.
	Az olyan parancsok, mint a merge vagy rebase, útvonalakat materializálhatnak a
	munkájuk elvégzéséhez (pl. hogy megmutassanak egy konfliktust), és más
	sparse-checkout parancsok esetleg nem tudnak egy adott fájlt ritkává tenni
	(pl. mert nem stage-elt változtatásai vagy konfliktusai vannak).  Ilyen
	esetekben érdemes lehet később futtatni a `git sparse-checkout reapply` parancsot,
	miután az érintett útvonalakat rendbe tetted (pl. konfliktusok feloldása, változtatások
	visszavonása vagy commitolása stb.).
+
A `reapply` parancs a `--[no-]cone` és `--[no-]sparse-index`
flageket is elfogadja, ugyanazzal a jelentéssel, mint a `set` parancs flagjei, hogy
megváltoztasd, mely ritkasági módot használod anélkül, hogy az összes ritkasági
útvonalat is újra meg kellene adnod.

'clean'::
	Opportunisztikusan eltávolítja a sparse-checkout definíción kívüli
	fájlokat. Ehhez a parancshoz cone mód szükséges, hogy rekurzív
	könyvtár-egyezéseket használjon annak meghatározására, mely fájlokat kell eltávolítani. Egy
	fájl akkor jön szóba eltávolításra, ha egy olyan követett könyvtárban van, amely
	a sparse-checkout definíción kívül esik.
+
Egyes speciális esetek, mint a merge-konfliktusok vagy a sparse-checkout definíción kívüli
módosított fájlok, olyan fájlok megtartásához vezethetnek, amelyek egyébként
eltávolításra kerülnének. Oldd fel a konfliktusokat, stage-eld a módosításokat, és használd a
`git sparse-checkout reapply` parancsot a `git sparse-checkout
clean` paranccsal együtt ezeknek az eseteknek a feloldásához.
+
Ez a parancs használható annak biztosítására, hogy a sparse index hatékonyan működjön,
bár nem igényli a sparse index funkció engedélyezését az
`index.sparse=true` konfiguráción keresztül.
+
A worktree-fájlok véletlen törlésének megelőzésére a `clean` alparancs
nem töröl fájlokat a `-f` vagy `--force` opció nélkül, hacsak
a `clean.requireForce` config-opció nincs `false`-ra állítva.
+
A `--dry-run` opció felsorolja azokat a könyvtárakat, amelyeket eltávolítana,
anélkül hogy törölné őket. Az ebben a módban való futtatás hasznos lehet a
clean parancs viselkedésének előrejelzésére, vagy annak meghatározására, milyen fajta fájlok maradnak
a sparse könyvtárakban.
+
A `--verbose` opció felsorol minden fájlt az eltávolításra szóba jövő
könyvtárakon belül. Ez az opció hasznos annak meghatározására, hogy ezek a
fájlok valóban fontosak-e, vagy talán annak megmagyarázására, miért van még jelen a könyvtár
a jelenlegi sparse-checkout ellenére.

'disable'::
	Letiltja a `core.sparseCheckout` config-beállítást, és visszaállítja a
	munkakönyvtárat, hogy az összes fájlt tartalmazza.

'init'::
	Elavult parancs, amely úgy viselkedik, mint a `set` megadott útvonalak nélkül.
	A jövőben eltávolításra kerülhet.
+
Történelmileg a `set` nem kezelte az összes szükséges config-beállítást,
ami azt jelentette, hogy mind az `init`, mind a `set` parancsot meg kellett hívni.  Mindkettő
meghívása azt jelentette, hogy az `init` lépés először eltávolította szinte az összes követett fájlt
(és cone módban a figyelmen kívül hagyott fájlokat is), majd a `set` lépés visszaadta
a követett fájlok nagy részét (de a figyelmen kívül hagyott fájlokat nem).  Az
elveszett fájlokon túl ennek a kombinációnak a teljesítménye és felhasználói felülete is
gyenge volt.
+
Szintén történelmileg az `init` valójában nem inicializálta a
sparse-checkout fájlt, ha az már létezett.  Ez azt jelentette, hogy
vissza lehetett térni egy sparse-checkouthoz anélkül, hogy emlékezni kellett volna, mely
útvonalakat kell átadni egy későbbi 'set' vagy 'add' parancsnak.  A
`--cone` és `--sparse-index` opciók azonban nem maradtak meg a
disable parancson keresztül, így az egyszerű `init` meghívásával való könnyű visszaállítás
hasznossága csökkent.

'check-rules'::
	Ellenőrzi, hogy a ritkasági szabályok illeszkednek-e egy vagy több útvonalra.
+
Alapból a `check-rules` beolvas egy útvonallistát a stdin-ről, és csak azokat
adja ki, amelyek illeszkednek a jelenlegi ritkasági szabályokra. A bemenet várhatóan soronként
egy útvonalból áll, megegyezve a `git ls-tree --name-only` kimenetével, beleértve,
hogy a kettős idézőjellel (") kezdődő útvonalneveket C-stílusú idézőjeles
sztringekként értelmezi.
+
Amikor a `--rules-file <file>` flaggel hívják meg, a bemeneti fájlok a
`<file>`-ban található sparse checkout szabályokra illesztődnek a jelenlegiek helyett.
A fájlokban lévő szabályok várhatóan ugyanabban a formában vannak, amelyet a `git
sparse-checkout set --stdin` elfogad (különösen sortöréssel elválasztottak kell legyenek).
+
Alapból a `--rules-file` opciónak átadott szabályok cone módú
könyvtárakként értelmeződnek. Non-cone módú minták `--rules-file`-lal való átadásához,
kombináld az opciót a `--no-cone` opcióval.
+
Amikor a `-z` flaggel hívják meg, a stdin-en bevitt útvonalak formátuma, valamint
a kimeneti útvonalak \0-val vannak lezárva, és nincsenek idézőjelezve. Vedd figyelembe, hogy ez nem
vonatkozik a `--rules-file` opcióval átadott szabályok formátumára.


EXAMPLES
--------
`git sparse-checkout set MY/DIR1 SUB/DIR2`::

	Váltás egy sparse checkoutra, amelyben a MY/DIR1/ és SUB/DIR2/ alatti
	összes fájl (bármilyen mélységben) jelen van a munkamásolatban (plusz a
	MY/ és SUB/ közvetlenül alatti összes fájl és a legfelső szintű
	könyvtár).  Ha már sparse checkoutban vagy, megváltoztatja, mely fájlok
	vannak jelen a munkamásolatban erre az új kiválasztásra.  Vedd figyelembe,
	hogy ez a parancs törli az összes figyelmen kívül hagyott fájlt is bármely
	olyan könyvtárban, amelyben már nincsenek jelen sem követett, sem
	nem-figyelmen-kívül-hagyott-nem-követett fájlok.

`git sparse-checkout disable`::

	Újratölti a munkakönyvtárat az összes fájllal, letiltva a sparse
	checkoutokat.

`git sparse-checkout add SOME/DIR/ECTORY`::

	Hozzáadja a SOME/DIR/ECTORY/ alatti összes fájlt (bármilyen mélységben) a
	sparse checkouthoz, valamint a SOME/DIR/ közvetlenül alatti és a
	SOME/ közvetlenül alatti összes fájlt.  A parancs használata előtt már
	sparse checkoutban kell lenned.

`git sparse-checkout reapply`::

	Előfordulhat, hogy a parancsok úgy frissítik a working tree-t, hogy az
	nem tartja tiszteletben a kiválasztott ritkasági könyvtárakat.
	Ez eredhet Giten kívüli eszközök fájlírásából, vagy
	akár Git-parancsokat is érinthet vagy speciális esetek miatt (mint
	a konfliktusokba ütközés merge/rebase közben), vagy mert egyes
	parancsok nem teljesen támogatták a sparse checkoutokat (pl. a régi
	`recursive` merge háttérrendszer csak korlátozott támogatással rendelkezett).  Ez a
	parancs újra alkalmazza a meglévő sparse könyvtár-specifikációkat,
	hogy a munkakönyvtár megegyezzen.

INTERNALS -- SPARSE CHECKOUT
----------------------------

A "Sparse checkout" lehetővé teszi a munkakönyvtár ritka feltöltését.  A
skip-worktree bitet használja (lásd linkgit:git-update-index[1]), hogy megmondja a Gitnek,
érdemes-e megnézni egy fájlt a munkakönyvtárban. Ha a
skip-worktree bit be van állítva, és a fájl nincs jelen a working tree-ben,
akkor a hiánya figyelmen kívül marad. A Git elkerüli ezeknek a fájloknak a tartalmának
feltöltését, ami hasznossá teszi a sparse checkoutot, amikor egy sok fájlt tartalmazó
repository-ban dolgozol, de csak néhány fontos a jelenlegi
felhasználó számára.

A `$GIT_DIR/info/sparse-checkout` fájl a skip-worktree referencia-bitmap
definiálására szolgál. Amikor a Git frissíti a munkakönyvtárat,
frissíti a skip-worktree biteket az indexben ez alapján
a fájl alapján. A fájlban lévő mintákra illeszkedő fájlok megjelennek
a munkakönyvtárban, a többi nem.

INTERNALS -- NON-CONE PROBLEMS
------------------------------

A `set` és `add` alparancsok által feltöltött `$GIT_DIR/info/sparse-checkout`
fájl úgy van definiálva, hogy minták halmaza (soronként egy)
a `.gitignore` fájlokkal azonos szintaxis használatával.  Cone módban ezek a
minták könyvtárakra való illeszkedésre vannak korlátozva (és a felhasználóknak csak
könyvtárneveket kell megadniuk vagy látniuk), míg non-cone módban bármely
gitignore-stílusú minta megengedett.  A teljes gitignore-stílusú
minták non-cone módban való használatának számos hiányossága van:

  * Alapvetően különböző worktree-frissítő folyamatok (pull,
    merge, rebase, switch, reset, checkout stb.) számára O(N*M) minta-egyezést
    tesz szükségessé, ahol N a minták száma, M pedig az indexben lévő
    útvonalak száma.  Ez rosszul skálázódik.

  * A skálázódási probléma elkerülését a minták számának
    korlátozásával kell elérni, vezető könyvtárnév vagy glob megadásával.

  * A globok parancssoron való átadása hibára hajlamos, mivel a felhasználók
    elfelejthetik idézőjelezni a globot, ami miatt a shell az összes
    illeszkedő fájllá bontja, és mindet egyenként átadja a
    sparse-checkout set/add parancsnak.  Bár ez probléma lehet
    pl. a "git grep -- *.c" esetén is, a grep/log/status hibái az
    azonnali kimenetben megjelennek.  A sparse-checkout esetén a hiba a
    sparse-checkout parancs futtatásának idején rögzül, és lehet, hogy
    nem okoz problémát, amíg a felhasználó később branchet vált, vagy rebase-el,
    vagy merge-el, így késleltetés kerül a felhasználó hibája és aközé, hogy
    esélye van elkapni/észrevenni azt.

  * Az előző ponthoz kapcsolódóan a sparse-checkoutnak van 'add'
    alparancsa, de nincs 'remove' alparancsa.  Még ha hozzá is adnának egy 'remove'
    alparancsot, egy véletlen, idézőjelezetlen glob visszavonása azt
    kockáztatja, hogy "túl sokat távolít el", mivel eltávolíthat olyan bejegyzéseket, amelyek
    a véletlen add előtt is be voltak vonva.

  * A non-cone mód gitignore-stílusú mintákat használ annak kiválasztására, hogy mit
    *vegyen fel* (a negált minták kivételével), míg a
    .gitignore fájlok gitignore-stílusú mintákat használnak annak kiválasztására, hogy mit
    *zárjanak ki* (a negált minták kivételével).  A
    gitignore-stílusú mintákról szóló dokumentáció általában nem
    illeszkedés vagy nem-illeszkedés fogalmaiban beszél, hanem arról, amit a felhasználó
    "ki akar zárni".  Ez zavart okozhat a felhasználók számára, akik próbálják megtanulni, hogyan
    adjanak meg sparse-checkout mintákat a kívánt viselkedés eléréséhez.

  * Minden más git alparancs, amely valamiféle "speciális útvonal-
    minta-illesztést" akar biztosítani, pathspeceket használ, de a sparse-checkout non-cone
    módja gitignore mintákat használ, ami
    inkonzisztensnek tűnik.

  * Vannak szélső esetei, ahol a "helyes" viselkedés nem világos.  Két példa:
+
Először, két felhasználó egy alkönyvtárban van, és az első futtatja
+
----
git sparse-checkout set '/toplevel-dir/*.c'
----
+
míg a második futtatja
+
----
git sparse-checkout set relative-dir
----
+
Ezeket az argumentumokat át kellene-e írni a következőre
+
----
current/subdirectory/toplevel-dir/*.c
----
+
és
+
----
current/subdirectory/relative-dir
----
+
mielőtt beszúrná a sparse-checkout fájlba?  Az a felhasználó, aki
az első parancsot beírta, valószínűleg tudatában van annak, hogy a set/add
argumentumai non-cone módban minták, és valószínűleg nem lenne
boldog egy ilyen átírással.  Sok gitignore-stílusú
minta azonban egyszerűen útvonal, ami lehet, hogy az volt, amire a
második parancsot beíró felhasználó gondolt, és feldühödne, ha az argumentumát
nem írnák át.
+
Másodszor, mire egészítsen ki a bash-completion a set/add parancsoknál
a non-cone felhasználók számára?  Ha útvonalakat javasol, súlyosbítja-e a
fenti problémát?  Továbbá, ha útvonalakat javasol, mi van, ha a felhasználónak van egy
olyan fájlja vagy könyvtára, amely '!' vagy '#' jellel kezdődik, vagy a nevében '*',
'\', '?', '[' vagy ']' van?  És ha útvonalakat javasol, a
"/pro"-t "/proc"-ra (a gyökér fájlrendszerben) egészíti ki, nem pedig az
aktuális könyvtárban lévő "/progress.txt"-re?  (Vedd figyelembe, hogy a felhasználók
valószínűleg vezető '/'-rel akarják kezdeni az útvonalakat non-cone módban,
ugyanabból az okból, amiért a .gitignore fájlokban gyakran van ilyen.)
A fájlokra vagy könyvtárakra való kiegészítés csúnya meglepetéseket okozhat
mindezekben az esetekben.

  * A túlzott rugalmasság más kiterjesztéseket lényegében
    kivitelezhetetlenné tett.  A `--sparse-index` valószínűleg lehetetlen non-cone
    módban; még ha valahogy megvalósítható is, sokkal több
    munka lett volna implementálni, és a gyakorlatban túl lassú lehetett volna.  A
    partial clone-ok és a sparse checkoutok közötti csatolás hozzáadására vonatkozó egyes
    ötletek szintén csak egy korlátozottabb útvonalhalmazzal
    praktikusak.

Mindezen okok miatt a non-cone mód elavult.  Kérjük, válts a
cone mód használatára.


INTERNALS -- CONE MODE HANDLING
-------------------------------

A "cone mód", amely az alapértelmezés, csak azt engedi megadni, mely
könyvtárakat vegye fel.  Bármely megadott könyvtár esetén az adott
könyvtár alatti összes útvonal bekerül, és a vezető könyvtárak
(beleértve a legfelső szintű könyvtárat) közvetlenül alatti útvonalak is
bekerülnek.  Így ha megadtad a könyvtárat
    Documentation/technical/
akkor a sparse checkoutod a következőket tartalmazná:

  * a legfelső szintű könyvtárban lévő összes fájl
  * a Documentation/ közvetlenül alatti összes fájl
  * a Documentation/technical/ alatti bármilyen mélységű összes fájl

Továbbá cone módban, még ha nincsenek is könyvtárak megadva, a
legfelső szintű könyvtárban lévő fájlok bekerülnek.

Amikor cone módban megváltoztatod a sparse-checkout mintákat, a Git megvizsgál minden olyan
követett könyvtárat, amely nincs a sparse-checkout cone-on belül, hogy megnézze,
tartalmaz-e nem követett fájlokat. Ha ezek a fájlok mind figyelmen kívül vannak hagyva a
`.gitignore` minták miatt, akkor a könyvtár törlésre kerül. Ha az adott könyvtárban lévő
nem követett fájlok bármelyike nincs figyelmen kívül hagyva, akkor nem történik törlés
az adott könyvtárban, és egy figyelmeztető üzenet jelenik meg. Ha ezek a fájlok
fontosak, akkor állítsd vissza a sparse-checkout definíciódat, hogy bekerüljenek,
használd a `git add` és `git commit` parancsot a tárolásukhoz, majd távolítsd el a megmaradó fájlokat
kézzel, hogy a Git optimálisan viselkedhessen.

Lásd még az "Internals -- Cone Pattern Set" szakaszt, hogy megtudd, hogyan
alakulnak át a könyvtárak a motorháztető alatt a sparse-checkout
Full Pattern Set-jének részhalmazává.


INTERNALS -- FULL PATTERN SET
-----------------------------

A full pattern set tetszőleges minta-egyezéseket és bonyolult
felvételi/kizárási szabályokat tesz lehetővé. Ezek O(N*M) minta-egyezést eredményezhetnek az
index frissítésekor, ahol N a minták száma, M pedig az indexben lévő
útvonalak száma. E teljesítménybeli probléma leküzdésére egy korlátozottabb
mintakészlet engedélyezett, amikor a `core.sparseCheckoutCone` engedélyezve van.

A sparse-checkout fájl a `.gitignore` fájlokkal azonos szintaxist használ;
a részletekért lásd linkgit:gitignore[5].  Itt azonban a minták
általában annak kiválasztására szolgálnak, mely fájlokat vegye fel, nem pedig hogy mely
fájlokat zárja ki.  (Ez azonban kissé zavaró lehet, mivel a
gitignore-stílusú mintáknak vannak negációi, amelyeket olyan minták definiálnak, amelyek
'!' jellel kezdődnek, így olyan fájlokat is kiválaszthatsz, amelyeket _ne_ vegyen fel.)

Például mindent kiválasztani, majd eltávolítani az
`unwanted` fájlt (hogy minden fájl megjelenjen a working tree-dben az
`unwanted` nevű fájl kivételével):

    git sparse-checkout set --no-cone '/*' '!unwanted'

Ezek a minták egyszerűen változatlanul kerülnek a
`$GIT_DIR/info/sparse-checkout` fájlba, így annak a fájlnak a tartalma
ezen a ponton a következő lenne

----------------
/*
!unwanted
----------------

Lásd még a linkgit:git-read-tree[1] "Sparse Checkout" szakaszát, hogy
többet megtudj a sparse checkoutokban használt gitignore-stílusú
mintákról.


INTERNALS -- CONE PATTERN SET
-----------------------------

Cone módban csak könyvtárak fogadhatók el, de ezek a full pattern set-ben
használt, azonos gitignore-stílusú mintákká alakulnak át.  Az ebben a módban
használt konkrét mintákra úgy hivatkozunk, mint amelyek két típus egyikéhez tartoznak:

1. *Recursive:* Egy könyvtáron belüli összes útvonal bekerül.

2. *Parent:* Egy könyvtáron belül közvetlenül lévő összes fájl bekerül.

Mivel a cone mód mindig felveszi a legfelső szinten lévő fájlokat, amikor a
`git sparse-checkout set` parancsot könyvtárak megadása nélkül futtatod, a legfelső szintű
könyvtár parent mintaként kerül hozzáadásra.  Ezen a ponton a
sparse-checkout fájl a következő mintákat tartalmazza:

----------------
/*
!/*/
----------------

Ez azt mondja: "vegyél fel mindent, ami közvetlenül a legfelső szintű
könyvtár alatt van, de semmit sem az alatta lévő bármely szinten."

Cone módban a `git sparse-checkout set` alparancs könyvtárak
listáját fogadja.  A `git sparse-checkout set A/B/C` parancs az
`A/B/C` könyvtárat recursive mintaként állítja be, az `A` és
`A/B` könyvtárak parent mintaként kerülnek hozzáadásra. Az eredményül kapott sparse-checkout fájl
most

----------------
/*
!/*/
/A/
!/A/*/
/A/B/
!/A/B/*/
/A/B/C/
----------------

Itt a sorrend számít, így a negatív mintákat felülírják a fájlban lejjebb
megjelenő pozitív minták.

Hacsak a `core.sparseCheckoutCone` nincs kifejezetten `false`-ra állítva, a Git úgy
elemzi a sparse-checkout fájlt, hogy ilyen típusú mintákat vár. A Git
figyelmeztet, ha a minták nem illeszkednek.  Ha a minták illeszkednek a várt
formátumra, akkor a Git gyorsabb hash-alapú algoritmusokat használ a
sparse-checkoutba való felvétel kiszámításához.  Ha nem illeszkednek, a git úgy viselkedik, mintha
a `core.sparseCheckoutCone` false lenne, a beállításától függetlenül.

A cone mód esetében, annak ellenére, hogy teljes minták íródnak
a $GIT_DIR/info/sparse-checkout fájlba, a `git sparse-checkout
list` alparancs felsorolja azokat a könyvtárakat, amelyek a recursive
mintákat definiálják. A fenti példa sparse-checkout fájl esetén a kimenet a
következő:

--------------------------
$ git sparse-checkout list
A/B/C
--------------------------

Ha `core.ignoreCase=true`, akkor a minta-illesztő algoritmus kis- és nagybetűt nem
megkülönböztető ellenőrzést használ. Ez korrigálja a kis- és nagybetűben nem egyező fájlneveket a
'git sparse-checkout set' parancsban, hogy a working directoryban a várt cone-t
tükrözze.


INTERNALS -- SUBMODULES
-----------------------

Ha a repository-d egy vagy több submodule-t tartalmaz, akkor a submodule-ok a
`git submodule` paranccsal való interakciók alapján töltődnek fel.
Konkrétan a `git submodule init -- <path>` biztosítja, hogy a
`<path>`-nél lévő submodule jelen legyen, míg a `git submodule deinit [-f] -- <path>`
eltávolítja a `<path>`-nél lévő submodule fájljait (beleértve
a nem követett fájlokat, a nem commitolt változtatásokat és a nem pusholt történetet).  Ahogy
a sparse-checkout eltávolítja a fájlokat a working tree-ből, de továbbra is
bejegyzéseket hagy az indexben, a deinitelt submodule-ok eltávolításra kerülnek
a munkakönyvtárból, de továbbra is van bejegyzésük az indexben.

Mivel a submodule-oknak lehetnek nem pusholt változtatásaik vagy nem követett fájljaik,
az eltávolításuk adatvesztést eredményezhet.  Így a sparse
felvételi/kizárási szabályok megváltoztatása nem okozza egy már kicsekkolt
submodule eltávolítását a munkamásolatból.  Másképp fogalmazva, ahogy
a `checkout` sem okozza a submodule-ok automatikus eltávolítását vagy
inicializálását még akkor sem, amikor olyan branchek között váltasz, amelyek submodule-okat
távolítanak el vagy adnak hozzá, a `sparse-checkout` használata az
"érdekes" fájlok körének szűkítésére vagy bővítésére szintén nem okozza a submodule-ok
automatikus deinitelését vagy inicializálását.

Továbbá a fenti tények azt jelentik, hogy több oka is van annak, hogy a
"követett" fájlok esetleg nincsenek jelen a munkamásolatban: a sparse-checkoutból származó
ritkasági minta alkalmazása, és a submodule inicializálási
állapota.  Így az olyan parancsok, mint a `git grep`, amelyek a munkamásolatban lévő
követett fájlokon dolgoznak, olyan eredményeket adhatnak vissza, amelyeket e korlátozások
egyike vagy mindkettő korlátoz.


SEE ALSO
--------

linkgit:git-read-tree[1]
linkgit:gitignore[5]

GIT
---
A linkgit:git[1] csomag része
