git-quiltimport(1)
==================

NAME
----
git-quiltimport - Egy quilt patchsetet alkalmaz az aktuális branchre


SYNOPSIS
--------
[verse]
'git quiltimport' [--dry-run | -n] [--author <author>] [--patches <dir>]
		[--series <file>] [--keep-non-patch]


DESCRIPTION
-----------
Egy quilt patchsetet alkalmaz az aktuális Git-branchre, megőrizve a
patchhatárokat, a patchsorrendet és a quilt patchsetben jelen lévő
patch-leírásokat.

Minden patchnél a kód megpróbálja kinyerni a szerzőt a
patch-leírásból. Ha ez sikertelen, visszaesik a --author-ral megadott
szerzőre. Ha a --author kapcsoló nem lett megadva, a patch-leírás
megjelenik, és a felhasználót interaktívan megkérdezi a patch
szerzőjéről.

Ha a patch-leírásban nem található tárgy, a patch neve marad meg
1 soros tárgyként a Git-leírásban.

OPTIONS
-------

-n::
--dry-run::
	Végigmegy a sorozat patchein, és figyelmeztet, ha nem
	találhatók meg egy patch commitolásához szükséges összes
	információk. E sorok írásakor csak a hiányzó
	szerzőinformációra figyelmeztet.

--author 'Author Name <Author Email>'::
	A használandó szerzőnév és e-mail-cím, ha nem található
	szerzőinformáció a patch-leírásban.

--patches <dir>::
	A könyvtár, ahol a quilt patcheket kell keresni.
+
A patch-könyvtár alapértelmezése a 'patches', vagy a
`$QUILT_PATCHES` környezeti változó értéke.

--series <file>::
	A quilt series fájl.
+
A series fájl alapértelmezése a <patches>/series, vagy a
`$QUILT_SERIES` környezeti változó értéke.

--keep-non-patch::
	Átadja a `-b` kapcsolót a 'git mailinfo'-nak (lásd
	linkgit:git-mailinfo[1]).

GIT
---
A linkgit:git[1] csomag része
