git-upload-pack(1)
==================

NAME
----
git-upload-pack - Objektumok csomagolt visszaküldése a git-fetch-pack számára


SYNOPSIS
--------
[verse]
'git-upload-pack' [--[no-]strict] [--timeout=<n>] [--stateless-rpc]
		  [--advertise-refs] <directory>

DESCRIPTION
-----------
A 'git fetch-pack' hívja meg; megtudja, hogy a másik oldalról mely
objektumok hiányoznak, és csomagolás után elküldi őket.

Ezt a parancsot általában nem a végfelhasználó hívja meg közvetlenül.
A protokoll felhasználói felülete a 'git fetch-pack' oldalán van, és a
programpár arra szolgál, hogy frissítéseket pulloljon egy remote
repository-ból. Push műveletekhez lásd a 'git send-pack'-et.

OPTIONS
-------

--strict::
--no-strict::
	Ne próbálja a <directory>/.git/ útvonalat, ha a <directory> nem
	Git-könyvtár.

--timeout=<n>::
	Megszakítja az átvitelt <n> másodpercnyi tétlenség után.

--stateless-rpc::
	Csak egyetlen olvasás-írás ciklust hajt végre az stdin és az
	stdout használatával. Ez illeszkedik a HTTP POST kérések
	feldolgozási modelljéhez, ahol egy program beolvashatja a
	kérést, választ írhat, majd ki kell lépnie.

--http-backend-info-refs::
	A linkgit:git-http-backend[1] használja a
	`$GIT_URL/info/refs?service=git-upload-pack` kérések
	kiszolgálására. Lásd a "Smart Clients" szakaszt a
	linkgit:gitprotocol-http[5]-ben és a "HTTP Transport" szakaszt a
	linkgit:gitprotocol-v2[5] dokumentációban. A
	linkgit:git-receive-pack[1] is értelmezi.

<directory>::
	Az a repository, amelyből szinkronizálni kell.

ENVIRONMENT
-----------

`GIT_PROTOCOL`::
	Belső változó, amely a wire protokoll kézfogásához használatos.
	A szerveradminisztrátoroknak esetleg konfigurálniuk kell néhány
	átvitelt, hogy ez a változó átadható legyen. Lásd a
	linkgit:git[1] tárgyalását.

`GIT_NO_LAZY_FETCH`::
	Amikor egy partial repository-ból (azaz olyanból, amelyet maga
	is `--filter`-rel klónoztak) klónozol vagy fetchelsz, a
	szerveroldali `upload-pack`-nek esetleg extra objektumokat kell
	fetchelnie az upstreamjéből a kérés teljesítéséhez.
	Alapértelmezés szerint az `upload-pack` nem hajt végre ilyen
	lazy fetchet, mert a `git fetch` tetszőleges, a forrás
	repository konfigurációjában és hookjaiban megadott parancsokat
	futtathat (és az `upload-pack` igyekszik biztonságosan
	futtatható lenni még nem megbízható `.git` könyvtárakban is).
+
Ez úgy van megvalósítva, hogy az `upload-pack` belsőleg `1`-re
állítja a `GIT_NO_LAZY_FETCH` változót. Ha felül szeretnéd bírálni
(mert egy partial clone-ból fetchelsz, és biztos vagy benne, hogy
megbízol benne), kifejezetten `0`-ra állíthatod a
`GIT_NO_LAZY_FETCH`-et.

SECURITY
--------

A legtöbb Git-parancsot nem szabad nem megbízható `.git` könyvtárban
futtatni (lásd a `SECURITY` szakaszt a linkgit:git[1]-ben). Az
`upload-pack` igyekszik elkerülni minden veszélyes konfigurációs
opciót vagy hookot az általa kiszolgált repository-ból, így
biztonságos egy nem megbízható könyvtárat klónozni és parancsokat
futtatni a kapott klónon.

Extra biztonsági szint érdekében az `upload-pack`-et esetleg
futtathatod egy másik felhasználóként. A részletek platformfüggők, de
sok rendszeren futtathatod a következőt:

    git clone --no-local --upload-pack='sudo -u nobody git-upload-pack' ...

SEE ALSO
--------
linkgit:gitnamespaces[7]

GIT
---
A linkgit:git[1] csomag része
