git-daemon(1)
=============

NAME
----
git-daemon - Egy nagyon egyszerű szerver Git repository-khoz

SYNOPSIS
--------
[synopsis]
git daemon [--verbose] [--syslog] [--export-all]
	   [--timeout=<n>] [--init-timeout=<n>] [--max-connections=<n>]
	   [--strict-paths] [--base-path=<path>] [--base-path-relaxed]
	   [--user-path | --user-path=<path>]
	   [--interpolated-path=<pathtemplate>]
	   [--reuseaddr] [--detach] [--pid-file=<file>]
	   [--enable=<service>] [--disable=<service>]
	   [--allow-override=<service>] [--forbid-override=<service>]
	   [--access-hook=<path>] [--[no-]informative-errors]
	   [--inetd |
	     [--listen=<host-or-ipaddr>] [--port=<n>]
	     [--user=<user> [--group=<group>]]]
	   [--log-destination=(stderr|syslog|none)]
	   [<directory>...]

DESCRIPTION
-----------
Egy nagyon egyszerű TCP Git daemon, amely normál esetben a
"DEFAULT_GIT_PORT" porton, azaz a 9418-on figyel. Egy szolgáltatást
kérő kapcsolatra vár, és kiszolgálja azt a szolgáltatást, ha az
engedélyezve van.

Ellenőrzi, hogy a könyvtár tartalmazza-e a "git-daemon-export-ok" mágikus
fájlt, és megtagadja bármely olyan Git-könyvtár exportálását, amely
nincs kifejezetten így exportálásra megjelölve (hacsak nincs megadva
az `--export-all` paraméter). Ha megadsz néhány könyvtár-útvonalat a
`git daemon` argumentumaiként, a kínálat az ezeken a könyvtárakon
belüli repository-kra korlátozódik.

Alapértelmezetten csak az `upload-pack` szolgáltatás van engedélyezve,
amely a `git fetch-pack` és `git ls-remote` klienseket szolgálja ki,
amelyeket a `git fetch`, `git pull` és `git clone` hív meg.

Ez ideálisan alkalmas csak olvasható frissítésekhez, azaz Git
repository-kból való pull-ozáshoz.

Létezik egy `upload-archive` is a `git archive` kiszolgálására.

OPTIONS
-------
`--strict-paths`::
	Az útvonalak pontos egyezését kényszeríti ki (azaz nem engedi meg a
	"/foo/repo" alakot, ha a valódi útvonal "/foo/repo.git" vagy
	"/foo/repo/.git"), és nem alkalmaz felhasználóhoz relatív útvonalakat.
	A `git daemon` megtagadja az indulást, ha ez az opció engedélyezve
	van, és nincs megadva egyetlen könyvtár-argumentum sem.

`--base-path=<path>`::
	Az összes útvonalkérést a megadott útvonalhoz képest relatívként
	képezi le. Ez egyfajta "Git-gyökér" - ha a `git daemon`-t az
	`example.com`-on `--base-path=/srv/git` kapcsolóval futtatod, majd
	utóbb megpróbálsz pull-ozni a `git://example.com/hello.git`
	címről, a `git daemon` az útvonalat `/srv/git/hello.git`-ként
	fogja értelmezni.

`--base-path-relaxed`::
	Ha a `--base-path` engedélyezve van és a repository-keresés
	sikertelen, ezzel az opcióval a `git daemon` megpróbálja a
	keresést az alap-útvonal előtagja nélkül is elvégezni. Ez hasznos
	a `--base-path` használatára való átálláshoz, miközben a régi
	útvonalak is továbbra is elérhetők maradnak.

`--interpolated-path=<pathtemplate>`::
	A virtuális hosztolás támogatásához egy interpolált útvonal-sablon
	használható alternatív útvonalak dinamikus felépítésére. A sablon
	támogatja a `%H`-t a kliens által megadott, de csupa kisbetűssé
	alakított célhosztnévhez, a `%CH`-t a kanonikus hosztnévhez, a
	`%IP`-t a szerver IP-címéhez, a `%P`-t a portszámhoz, és a `%D`-t
	a megnevezett repository abszolút útvonalához. Az interpoláció után
	az útvonal a könyvtárlistával szemben ellenőrzésre kerül.

`--export-all`::
	Engedélyezi a pull-ozást minden olyan könyvtárból, amely Git
	repository-nak látszik (van benne 'objects' és 'refs'
	alkönyvtár), még akkor is, ha nincs benne `git-daemon-export-ok`
	fájl.

`--inetd`::
	A szervert inetd szolgáltatásként futtatja. Ez maga után vonja a
	`--syslog`-ot (felülbírálható a `--log-destination=`-nel).
	Nem kompatibilis a `--detach`, `--port`, `--listen`, `--user` és
	`--group` opciókkal.

`--listen=<host-or-ipaddr>`::
	Egy konkrét IP-címen vagy hosztnéven figyel. Az IP-cím lehet IPv4-
	vagy - ha támogatott - IPv6-cím. Ha az IPv6 nem támogatott, akkor a
	`--listen=<hostname>` sem támogatott, és a `--listen`-nek IPv4-címet
	kell megadni.
	Többször is megadható.
	Nem kompatibilis a `--inetd` opcióval.

`--port=<n>`::
	Egy alternatív porton figyel. Nem kompatibilis a `--inetd` opcióval.

`--init-timeout=<n>`::
	Időkorlát (másodpercben) a kapcsolat létrejötte és a kliens
	kérésének megérkezése között (jellemzően eléggé alacsony érték,
	mivel ennek alapvetően azonnalinak kell lennie).

`--timeout=<n>`::
	Időkorlát (másodpercben) az egyes kliens-alkérésekre. Ez magában
	foglalja azt az időt, amíg a szerver feldolgozza az alkérést, és
	azt az időt is, amíg a következő kliens-kérésre vár.

`--max-connections=<n>`::
	A párhuzamos kliensek maximális száma, alapértelmezetten 32. Ha
	nem akarsz korlátot, állítsd nullára.

`--syslog`::
	Rövidítés a `--log-destination=syslog` helyett.

`--log-destination=<destination>`::
	A naplóüzeneteket a megadott célra küldi.
	Vedd figyelembe, hogy ez az opció nem vonja maga után a
	`--verbose`-t, ezért alapértelmezetten csak a hibaállapotok
	kerülnek naplózásra.
	A _<destination>_ a következők egyike lehet:
+
--
`stderr`::
	A standard hibakimenetre írja.
	Vedd figyelembe, hogy ha a `--detach` meg van adva, a folyamat
	leválik a valódi standard hibakimenetről, így ez a célpont
	gyakorlatilag egyenértékű a `none`-nal.
`syslog`::
	A syslogba írja, a `git-daemon` azonosítót használva.
`none`::
	Kikapcsolja az összes naplózást.
--
+
Az alapértelmezett célpont `syslog`, ha a `--inetd` vagy a `--detach` meg
van adva, egyébként `stderr`.

`--user-path`::
`--user-path=<path>`::
	Engedélyezi a {tilde}user jelölés használatát a kérésekben. Ha
	paraméter nélkül van megadva, a git://host/{tilde}alice/foo
	kérés az `alice` felhasználó saját könyvtárában lévő 'foo'
	repository elérésére irányuló kérésként értelmeződik.
	Ha a `--user-path=<path>` van megadva, ugyanez a kérés a
	`<path>/foo` repository elérésére irányuló kérésként
	értelmeződik az `alice` felhasználó saját könyvtárában.

`--verbose`::
	Naplózza a bejövő kapcsolatok és a kért fájlok részleteit.

`--reuseaddr`::
	A `SO_REUSEADDR`-t használja a figyelő socket bindeléséhez.
	Ez lehetővé teszi a szerver újraindítását anélkül, hogy meg
	kellene várni a régi kapcsolatok időtúllépését.

`--detach`::
	Leválik a shellről. Ez maga után vonja a `--syslog`-ot.

`--pid-file=<file>`::
	Elmenti a folyamatazonosítót a _<file>_-ba. Figyelmen kívül
	marad, ha a daemon `--inetd` alatt fut.

`--user=<user>`::
`--group=<group>`::
	Megváltoztatja a daemon uid-jét és gid-jét, mielőtt belépne a
	kiszolgálási ciklusba. Ha csak a `--user` van megadva a
	`--group` nélkül, a felhasználó elsődleges csoportazonosítója
	kerül felhasználásra. Az opció értékei a `getpwnam(3)` és a
	`getgrnam(3)` számára kerülnek átadásra, numerikus azonosítók
	nem támogatottak.
+
Ezen opciók megadása hiba, ha a `--inetd`-vel együtt van
használva; ha szükséges, az inet daemon eszközkészletét
használd ugyanennek eléréséhez a `git daemon` elindítása előtt.
+
Mint a legtöbb, felhasználói azonosítót váltó program, a daemon
sem állítja vissza az olyan környezeti változókat, mint a `HOME`,
amikor git programokat futtat, pl. az `upload-pack`-et és a
`receive-pack`-et. Ennek az opciónak a használatakor érdemes lehet
a `HOME`-ot is beállítanod és exportálnod, hogy a _<user>_ saját
könyvtárára mutasson a daemon elindítása előtt, és győződj meg
róla, hogy az abban a könyvtárban lévő Git konfigurációs fájlok
olvashatók a _<user>_ számára.

`--enable=<service>`::
`--disable=<service>`::
	Engedélyezi/letiltja a szolgáltatást site-szinten,
	alapértelmezésként. Vedd figyelembe, hogy egy site-szinten
	letiltott szolgáltatás repository-nként még mindig
	engedélyezhető, ha felülbírálhatóként van megjelölve, és a
	repository egy konfigurációs tétellel engedélyezi a
	szolgáltatást.

`--allow-override=<service>`::
`--forbid-override=<service>`::
	Engedélyezi/tiltja a site-szintű alapértelmezés felülbírálását
	repository-nkénti konfigurációval. Alapértelmezetten minden
	szolgáltatás felülbírálható.

`--informative-errors`::
`--no-informative-errors`::
	Ha az informatív hibák be vannak kapcsolva, a git-daemon
	részletesebb hibákat jelent a kliensnek, megkülönböztetve az
	olyan állapotokat, mint a "no such repository" a "repository not
	exported"-től. Ez kényelmesebb a kliensek számára, de kiszivárogtathatja
	a nem exportált repository-k létezésére vonatkozó információt. Ha az
	informatív hibák nincsenek engedélyezve, minden hiba "access denied"
	üzenetet jelent a kliensnek. Az alapértelmezés a
	`--no-informative-errors`.

`--access-hook=<path>`::
	Minden alkalommal, amikor egy kliens kapcsolódik, először lefuttat
	egy a <path> által megadott külső parancsot a szolgáltatás nevével
	(pl. "upload-pack"), a repository útvonalával, a hosztnévvel
	(`%H`), a kanonikus hosztnévvel (`%CH`), az IP-címmel (`%IP`) és a
	TCP-porttal (`%P`) mint parancssori argumentumokkal. A külső
	parancs eldöntheti, hogy elutasítja-e a szolgáltatást egy nem
	nulla állapottal való kilépéssel (vagy engedélyezheti azt nulla
	állapottal való kilépéssel). A döntés meghozatalakor a kérelmezőről
	a $REMOTE_ADDR és a `$REMOTE_PORT` környezeti változókból is
	tájékozódhat.
+
A külső parancs opcionálisan egyetlen sort írhat a standard
kimenetére, amelyet a kérelmezőnek hibaüzenetként küldünk, ha
elutasítja a szolgáltatást.

_<directory>_::
	A megmaradt argumentumok könyvtárak listáját adják meg. Ha meg van
	adva bármilyen könyvtár, a `git-daemon` folyamat csak akkor
	szolgál ki egy kért könyvtárat, ha az valamelyik ezen könyvtárak
	közül tartalmazza azt. Ha a `--strict-paths` meg van adva, a kért
	könyvtárnak pontosan meg kell egyeznie ezen könyvtárak egyikével.

SERVICES
--------

Ezek a szolgáltatások globálisan engedélyezhetők/letilthatók e parancs
parancssori opcióival. Ha finomabb szemcsézettségű vezérlés kívánatos
(pl. hogy a `git archive` csak néhány kiválasztott, a daemon által
kiszolgált repository ellenében legyen futtatható), a
repository-nkénti konfigurációs fájl használható az engedélyezésükre
vagy letiltásukra.

upload-pack::
	Ez a `git fetch-pack` és a `git ls-remote` klienseket szolgálja
	ki. Alapértelmezetten engedélyezve van, de egy repository
	letilthatja a `daemon.uploadpack` konfigurációs tétel
	`false`-ra állításával.

upload-archive::
	Ez a `git archive --remote`-ot szolgálja ki. Alapértelmezetten
	le van tiltva, de egy repository engedélyezheti a
	`daemon.uploadarch` konfigurációs tétel `true`-ra állításával.

receive-pack::
	Ez a `git send-pack` klienseket szolgálja ki, lehetővé téve az
	anonim push-t. Alapértelmezetten le van tiltva, mivel a
	protokollban _nincs_ hitelesítés (más szóval bárki bármit
	push-olhat a repository-ba, beleértve a referenciák törlését
	is). Ez kizárólag zárt LAN-környezetre szánt, ahol mindenki
	barátságos. Ez a szolgáltatás a `daemon.receivepack`
	konfigurációs tétel `true`-ra állításával engedélyezhető.

EXAMPLES
--------
Feltételezzük a következőt a /etc/services fájlban::
+
------------
$ grep 9418 /etc/services
git		9418/tcp		# Git Version Control System
------------

A 'git daemon' mint inetd szerver::
	Ahhoz, hogy a 'git daemon'-t olyan inetd szolgáltatásként
	állítsd be, amely a `/pub/foo` vagy a `/pub/bar` alatti bármely
	repository-t kezeli, helyezz el egy a következőhöz hasonló
	bejegyzést a `/etc/inetd`-be, egyetlen sorban:
+
------------------------------------------------
	git stream tcp nowait nobody  /usr/bin/git
		git daemon --inetd --verbose --export-all
		/pub/foo /pub/bar
------------------------------------------------


A 'git daemon' mint inetd szerver virtuális hosztokhoz::
	Ahhoz, hogy a 'git daemon'-t olyan inetd szolgáltatásként
	állítsd be, amely különböző virtuális hosztok, a
	`www.example.com` és a `www.example.org` repository-jait
	kezeli, helyezz el egy a következőhöz hasonló bejegyzést a
	`/etc/inetd`-be, egyetlen sorban:
+
------------------------------------------------
	git stream tcp nowait nobody /usr/bin/git
		git daemon --inetd --verbose --export-all
		--interpolated-path=/pub/%H%D
		/pub/www.example.org/software
		/pub/www.example.com/software
		/software
------------------------------------------------
+
Ebben a példában a gyökérszintű `/pub` könyvtár minden támogatott
virtuális hosztnévhez egy alkönyvtárat fog tartalmazni.
Továbbá mindkét hoszt egyszerűen
`git://www.example.com/software/repo.git`-ként hirdeti a
repository-kat. Az 1.4.0 előtti kliensek számára egy szimbolikus
link is készíthető a `/software`-ből a megfelelő alapértelmezett
repository-ba.


A `git daemon` mint reguláris daemon virtuális hosztokhoz::
	Ahhoz, hogy a `git daemon`-t olyan reguláris, nem inetd
	szolgáltatásként állítsd be, amely az IP-címeik alapján több
	virtuális hoszt repository-jait kezeli, indítsd el a daemont
	így:
+
------------------------------------------------
	git daemon --verbose --export-all
		--interpolated-path=/pub/%IP/%D
		/pub/192.168.1.200/software
		/pub/10.10.220.23/software
------------------------------------------------
+
Ebben a példában a gyökérszintű `/pub` könyvtár minden támogatott
virtuális hoszt IP-címéhez egy alkönyvtárat fog tartalmazni.
A repository-k továbbra is elérhetők hosztnév alapján is,
feltéve, hogy ezek megfelelnek ezeknek az IP-címeknek.

szolgáltatások szelektív engedélyezése/letiltása repository-nként::
	Ahhoz, hogy engedélyezd a `git archive --remote`-ot és letiltsd
	a `git fetch`-et egy repository ellenében, tedd bele a
	következőt a repository konfigurációs fájljába (ez a `HEAD`,
	'refs' és 'objects' melletti 'config' fájl).
+
----------------------------------------------------------------
	[daemon]
		uploadpack = false
		uploadarch = true
----------------------------------------------------------------


ENVIRONMENT
-----------
A `git daemon` be fogja állítani a `REMOTE_ADDR`-t a hozzá
kapcsolódó kliens IP-címére, ha az IP-cím elérhető. A `REMOTE_ADDR`
elérhető lesz a szolgáltatások teljesítésekor meghívott hookok
környezetében.

GIT
---
A linkgit:git[1] csomag része
