git-update-ref(1)
=================

NAME
----
git-update-ref - Egy refben tárolt objektumnév biztonságos frissítése

SYNOPSIS
--------
[synopsis]
git update-ref [-m <reason>] [--no-deref] -d <ref> [<old-oid>]
git update-ref [-m <reason>] [--no-deref] [--create-reflog] <ref> <new-oid> [<old-oid>]
git update-ref [-m <reason>] [--no-deref] --stdin [-z] [--batch-updates]

DESCRIPTION
-----------
Két argumentum esetén a <new-oid>-t tárolja a <ref>-ben, esetleg
feloldva a szimbolikus refeket.  Pl. a `git update-ref HEAD
<new-oid>` a jelenlegi branch fejét az új objektumra frissíti.

Három argumentum esetén a <new-oid>-t tárolja a <ref>-ben,
esetleg feloldva a szimbolikus refeket, miután ellenőrizte, hogy
a <ref> jelenlegi értéke megegyezik a <old-oid>-val.
Pl. a `git update-ref refs/heads/master <new-oid> <old-oid>`
csak akkor frissíti a master branch fejét a <new-oid>-ra, ha a
jelenlegi értéke <old-oid>.  Megadhatsz 40 "0"-t vagy üres
sztringet <old-oid>-ként annak biztosítására, hogy a létrehozandó
ref ne létezzen.

Az utolsó argumentumok objektumnevek; ez a parancs opciók nélkül nem
támogatja egy szimbolikus ref frissítését úgy, hogy az egy másik refre
mutasson (lásd linkgit:git-symbolic-ref[1]).  A `git update-ref --stdin`
viszont rendelkezik a `symref-*` parancsokkal, így a hagyományos refek és
a szimbolikus refek ugyanabban a tranzakcióban commitolhatók.

Ha a --no-deref meg van adva, maga a <ref> íródik felül, nem pedig a
szimbolikus mutatók követésének eredménye.

A `-d`-vel törli a megnevezett <ref>-et, miután ellenőrizte, hogy még
mindig a <old-oid>-t tartalmazza.

A `--stdin`-nel az update-ref a standard bemenetről olvassa az
utasításokat, és az összes módosítást együtt hajtja végre.  Add meg a
parancsokat a következő alakban:

	update SP <ref> SP <new-oid> [SP <old-oid>] LF
	create SP <ref> SP <new-oid> LF
	delete SP <ref> [SP <old-oid>] LF
	verify SP <ref> [SP <old-oid>] LF
	symref-update SP <ref> SP <new-target> [SP (ref SP <old-target> | oid SP <old-oid>)] LF
	symref-create SP <ref> SP <new-target> LF
	symref-delete SP <ref> [SP <old-target>] LF
	symref-verify SP <ref> [SP <old-target>] LF
	option SP <opt> LF
	start LF
	prepare LF
	commit LF
	abort LF

A `--create-reflog`-gal az update-ref minden refhez létrehoz egy
reflogot, akkor is, ha egyébként nem jönne létre.

A `--batch-updates`-szel az update-ref kötegben hajtja végre a
frissítéseket, de megengedi, hogy az egyes frissítések érvénytelen vagy
helytelen felhasználói bemenet miatt meghiúsuljanak, és csak a sikeres
frissítéseket alkalmazza. A rendszerrel kapcsolatos hibák azonban – mint
az I/O-hibák vagy memóriaproblémák – az összes kötegelt frissítés teljes
meghiúsulását okozzák. A meghiúsult frissítések a következő formátumban
jelennek meg:

	rejected SP (<old-oid> | <old-target>) SP (<new-oid> | <new-target>) SP <rejection-reason> LF

A whitespace-t tartalmazó mezőket úgy idézőjelezd, mintha C forráskódbeli
sztringek lennének; azaz dupla idézőjelek közé zárva, backslash
escape-ekkel.  Használj 40 "0" karaktert vagy az üres sztringet a nulla
érték megadásához.  Hiányzó érték megadásához hagyd el teljesen az
értéket és az előtte lévő SP-t.

Alternatívaként használd a `-z`-t NUL-lezárt formátumban való
megadáshoz, idézőjelezés nélkül:

	update SP <ref> NUL <new-oid> NUL [<old-oid>] NUL
	create SP <ref> NUL <new-oid> NUL
	delete SP <ref> NUL [<old-oid>] NUL
	verify SP <ref> NUL [<old-oid>] NUL
	symref-update SP <ref> NUL <new-target> [NUL (ref NUL <old-target> | oid NUL <old-oid>)] NUL
	symref-create SP <ref> NUL <new-target> NUL
	symref-delete SP <ref> [NUL <old-target>] NUL
	symref-verify SP <ref> [NUL <old-target>] NUL
	option SP <opt> NUL
	start NUL
	prepare NUL
	commit NUL
	abort NUL

Ebben a formátumban használj 40 "0"-t a nulla érték megadásához, és az
üres sztringet a hiányzó érték megadásához.

Mindkét formátumban az értékek bármilyen olyan alakban megadhatók,
amelyet a Git objektumnévként ismer fel.  A bármely más formátumú
parancsok vagy egy ismételt <ref> hibát okoznak.  A parancsok jelentése:

update::
	A <ref> beállítása <new-oid>-ra a <old-oid> ellenőrzése után, ha
	meg van adva.  Adj meg nulla <new-oid>-t annak biztosítására,
	hogy a ref ne létezzen a frissítés után, és/vagy nulla
	<old-oid>-t annak biztosítására, hogy a ref ne létezzen a
	frissítés előtt.

create::
	A <ref> létrehozása <new-oid>-val, miután ellenőrizte, hogy nem
	létezik.  A megadott <new-oid> nem lehet nulla.

delete::
	A <ref> törlése, miután ellenőrizte, hogy létezik <old-oid>-val,
	ha meg van adva.  Ha meg van adva, a <old-oid> nem lehet nulla.

symref-update::
	A <ref> beállítása <new-target>-re a <old-target> vagy <old-oid>
	ellenőrzése után, ha meg van adva. Adj meg nulla <old-oid>-t annak
	biztosítására, hogy a ref ne létezzen a frissítés előtt.

verify::
	A <ref> ellenőrzése <old-oid>-val szemben, de ne változtasd meg.
	Ha a <old-oid> nulla vagy hiányzik, a ref nem létezhet.

symref-create::
	A <ref> szimbolikus ref létrehozása <new-target>-rel, miután
	ellenőrizte, hogy nem létezik.

symref-delete::
	A <ref> törlése, miután ellenőrizte, hogy létezik <old-target>-rel, ha meg van adva.

symref-verify::
	A szimbolikus <ref> ellenőrzése <old-target>-rel szemben, de ne
	változtasd meg.  Ha a <old-target> hiányzik, a ref nem létezhet.
	Csak `no-deref` módban használható.

option::
	A következő, <ref>-et megnevező parancs viselkedésének
	módosítása.  Az egyetlen érvényes opció a `no-deref`, amely
	elkerüli egy szimbolikus ref feloldását.

start::
	Tranzakció indítása. A nem tranzakciós munkamenettel szemben egy
	tranzakció automatikusan megszakad, ha a munkamenet explicit commit
	nélkül ér véget. Ez a parancs új üres tranzakciót hozhat létre,
	amikor a jelenlegit már commitolták vagy megszakították.

prepare::
	Felkészülés a tranzakció commitolására. Ez zárolófájlokat hoz létre
	az összes sorba állított referenciafrissítéshez. Ha egy referenciát
	nem sikerült zárolni, a tranzakció megszakad.

commit::
	Az összes, a tranzakcióhoz sorba állított referenciafrissítés
	commitolása, a tranzakció lezárása.

abort::
	A tranzakció megszakítása, az összes zárolás feloldása, ha a
	tranzakció prepared állapotban van.

Ha az összes <ref> egyidejűleg zárolható az egyező <old-oid>-kkal,
minden módosítás végrehajtódik.  Egyébként semmilyen módosítás nem
hajtódik végre.  Vedd figyelembe, hogy bár minden egyes <ref>
atomi módon frissül vagy törlődik, egy egyidejű olvasó még mindig
láthatja a módosítások egy részhalmazát.

LOGGING UPDATES
---------------
Ha a "core.logAllRefUpdates" konfigurációs paraméter true, és a ref a
"refs/heads/", "refs/remotes/", "refs/notes/" alattiak egyike, vagy egy
pszeudoref, mint a HEAD vagy az ORIG_HEAD; vagy létezik a
"$GIT_DIR/logs/<ref>" fájl, akkor a `git update-ref` hozzáfűz egy sort a
"$GIT_DIR/logs/<ref>" naplófájlhoz (a naplónév létrehozása előtt feloldva
az összes szimbolikus refet), amely leírja a ref értékének változását.  A
naplósorok formátuma:

    oldsha1 SP newsha1 SP committer LF

Ahol az "oldsha1" a <ref>-ben korábban tárolt 40 karakteres
hexadecimális érték, a "newsha1" a <new-oid> 40 karakteres
hexadecimális értéke, a "committer" pedig a committer neve, e-mail-címe
és dátuma a szabványos Git committer-ident formátumban.

Opcionálisan a -m opcióval:

    oldsha1 SP newsha1 SP committer TAB message LF

Ahol minden mező a fent leírtak szerinti, a "message" pedig a -m
opciónak átadott érték.

Egy frissítés meghiúsul (a <ref> megváltoztatása nélkül), ha a jelenlegi
felhasználó nem tud új naplófájlt létrehozni, hozzáfűzni a meglévő
naplófájlhoz, vagy nincs elérhető committer-információ.

NOTES
-----

A szimbolikus refeket eredetileg szimbolikus linkekkel valósították meg.
Ez most már elavult, mivel nem minden fájlrendszer támogatja a
szimbolikus linkeket.

Ez a parancs csak akkor követi a *valódi* symlinkeket, ha "refs/"-fel
kezdődnek: egyébként csak megpróbálja olvasni és hagyományos fájlként
frissíteni őket (azaz hagyja, hogy a fájlrendszer kövesse őket, de egy
ilyen, máshová mutató symlinket egy hagyományos fájlnévvel ír felül).

SEE ALSO
--------
linkgit:git-symbolic-ref[1]

GIT
---
A linkgit:git[1] csomag része
