git-backfill(1)
===============

NAME
----
git-backfill - Hiányzó objektumok letöltése egy partial clone-ban


SYNOPSIS
--------
[synopsis]
git backfill [--min-batch-size=<n>] [--[no-]sparse] [--[no-]include-edges] [<revision-range>]

DESCRIPTION
-----------

A blobless partial clone-okat a `git clone --filter=blob:none`
paranccsal hozzuk létre, amely úgy állítja be a helyi repository-t,
hogy a Git kliens elkerülje a blob-objektumok letöltését, hacsak nem
szükségesek egy helyi művelethez. Ez kezdetben azt jelenti, hogy a
klónozás és a későbbi fetchek az elérhető commitokat és tree-ket
töltik le, blobokat nem. A későbbi, a `HEAD` mutatót megváltoztató
műveleteknek, mint a `git checkout` vagy a `git merge`, szükségük
lehet a hiányzó blobok letöltésére a művelet befejezéséhez.

A legrosszabb esetben a blob-diffeket számító parancsok, mint a
`git blame`, nagyon lelassulnak, mivel a hiányzó blobokat
egyenként, egy-egy blobra vonatkozó kérésben töltik le, ahogy a Git
parancsnak éppen szüksége van a hiányzó objektumra. Ez több letöltési
kéréshez vezet, és a Git szervernek nincs lehetősége delta-tömörítést
biztosítani ezek között az objektumok között.

A `git backfill` parancs lehetőséget ad a felhasználónak arra, hogy
kérje a Gittől a hiányzó blobok letöltését (opcionális szűrőkkel)
úgy, hogy a fájlok korábbi verzióit reprezentáló hiányzó blobok
batchekben legyenek letölthetők. A `backfill` parancs megpróbálja
optimalizálni a kérést azáltal, hogy az azonos útvonalon megjelenő
blobokat csoportosítja, remélhetőleg jó delta-tömörítést eredményezve
a szerver által küldött packfile-ban.

Ily módon a `git backfill` egy mechanizmust biztosít arra, hogy egy
nagy klónozást kisebb darabokra bontsunk. Ha egy blobless partial
clone-nal indulunk a `git clone --filter=blob:none` paranccsal, majd
lefuttatjuk a `git backfill`-t a helyi repository-ban, az lehetővé
teszi az összes elérhető objektum letöltését több, kisebb hálózati
híváson keresztül, mint amennyi a teljes repository klónozáskor
történő letöltéséhez kellene.

Alapértelmezés szerint a `git backfill` a `HEAD` commitból elérhető
összes blobot letölti. Ez a halmaz a lenti különféle opciókkal
szűkíthető vagy bővíthető.

EZ A PARANCS KÍSÉRLETI. A VISELKEDÉSE A JÖVŐBEN MEGVÁLTOZHAT.


OPTIONS
-------

`--min-batch-size=<n>`::
	Megadja a szervertől kért, hiányzó objektumokból álló batch
	minimális méretét. Ezt a méretet túllépheti az adott útvonalon
	látott utolsó bloboknak a halmaza. Az alapértelmezett minimális
	batch-méret 50 000.

`--sparse`::
`--no-sparse`::
	Csak akkor tölti le az objektumokat, ha olyan útvonalon
	jelennek meg, amely illeszkedik a jelenlegi sparse-checkoutra.
	Ha a sparse-checkout funkció engedélyezve van, akkor a
	`--sparse` a feltételezett, és a `--no-sparse`-szal
	kikapcsolható.

`--include-edges`::
`--no-include-edges`::
	A határ-commitok blobjait is belefoglalja a backfillbe. Hasznos
	az olyan parancsok előkészítésekor, mint a `git log -p A..B`
	vagy a `git replay --onto TARGET A..B`, ahol az A..B
	rendszerint kizárja A-t, de szükség van A blobjaira is. A
	`--include-edges` az alapértelmezett.

`<revision-range>`::
	Csak a megadott revíziótartományban lévő commitokból elérhető
	blobokat backfilleli. Ha nincs megadva _<revision-range>_, az
	alapértelmezés `HEAD` (azaz a jelenlegi committhoz vezető teljes
	history). A _<revision-range>_ megadási módjainak teljes
	listájáért l. a linkgit:gitrevisions[7] "Specifying Ranges"
	szakaszát.
+
A linkgit:git-rev-list[1] által ismert commit-korlátozó opciókat is
használhatjuk, mint a `--first-parent`, `--since`, vagy pathspeceket.
+
A legtöbb `--filter=<spec>` opció nem működik a `git backfill`
céljával, de a `sparse:<oid>` szűrő integrálva van, hogy egy
fókuszált útvonalhalmazt biztosítson a letöltéshez, elkülönítve a
`--sparse` opciótól.

SEE ALSO
--------
linkgit:git-clone[1],
linkgit:git-rev-list[1]

GIT
---
A linkgit:git[1] csomag része
