git-range-diff(1)
=================

NAME
----
git-range-diff - Két commit-tartomány összehasonlítása (pl. egy branch két verziója)

SYNOPSIS
--------
[synopsis]
git range-diff [--color=[<when>]] [--no-color] [<diff-options>]
	[--no-dual-color] [--creation-factor=<factor>]
	[--left-only | --right-only] [--diff-merges=<format>]
	[--remerge-diff] [--no-notes | --notes[=<ref>]]
	( <range1> <range2> | <rev1>...<rev2> | <base> <rev1> <rev2> )
	[[--] <path>...]

DESCRIPTION
-----------

Ez a parancs megmutatja a különbségeket egy patchsorozat két verziója,
vagy általánosabban két commit-tartomány között (a merge commitokat
figyelmen kívül hagyva).

Ha _<path>_ argumentumok is jelen vannak, ezek a commit-tartományok ennek
megfelelően korlátozódnak.

Ennek érdekében először olyan commitpárokat keres a két
commit-tartományból, amelyek megfelelnek egymásnak. Két commit akkor
mondható megfelelőnek, ha a patchjeik közötti diff (azaz a szerzői
információ, a commit-üzenet és a commit diffje) észszerűen kicsi a patchek
méretéhez képest. A részletekért lásd az 'Algoritmus' szakaszt lentebb.

Végül az egyező commitok listája a második commit-tartomány sorrendjében
jelenik meg, az egyezés nélküli commitok pedig közvetlenül azután
kerülnek beszúrásra, hogy az összes ősüket megjelenítette.

A commit-tartományok megadására három mód van:

- `<range1> <range2>`: Bármelyik commit-tartomány lehet
  `<base>..<rev>`, `<rev>^!` vagy `<rev>^-<n>` alakú. További
  részletekért lásd a 'SPECIFYING RANGES' szakaszt a
  linkgit:gitrevisions[7] oldalon.

- `<rev1>...<rev2>`. Ez egyenértékű a
  `<rev2>..<rev1> <rev1>..<rev2>` alakkal.

- `<base> <rev1> <rev2>`: Ez egyenértékű a `<base>..<rev1>
  <base>..<rev2>` alakkal.

OPTIONS
-------
`--no-dual-color`::
	Amikor a commit diffek eltérnek, a `git range-diff` újraalkotja az
	eredeti diffek színezését, és külső -/+ diff-jelölőket ad hozzá,
	amelyeknek a *háttere* piros/zöld, hogy könnyebb legyen látni pl.
	azt, amikor változás történt abban, hogy pontosan mely sorok
	kerültek hozzáadásra.
+
Ezenfelül azok a commit-diff sorok, amelyek csak az első commit-tartományban
vannak jelen, "halványítva" jelennek meg (ez felülírható a
`color.diff.<slot>` konfigurációs beállítással, ahol a _<slot>_ a
`contextDimmed`, `oldDimmed` és `newDimmed` egyike), azok a commit-diff
sorok pedig, amelyek csak a második commit-tartományban vannak jelen,
félkövéren jelennek meg (ez felülírható a `color.diff.<slot>` konfigurációs
beállításokkal, ahol a _<slot>_ a `contextBold`, `oldBold` vagy `newBold`
egyike).
+
Ezt a `range-diff` "kettős színezésként" ismeri. A `--no-dual-color`
használatával visszatérhetsz ahhoz, hogy minden sor a külső diff-jelölők
szerint legyen színezve (és a belső diff a színezés szempontjából teljesen
figyelmen kívül maradjon).

`--creation-factor=<percent>`::
	A létrehozási/törlési költség korrekciós tényezőjét _<percent>_-re
	állítja. Az alapértelmezés 60. Próbálj nagyobb értéket, ha a
	`git range-diff` tévesen teljes újraírásnak tekint egy nagy
	változást (egy commit törlésének és egy másik hozzáadásának), és
	kisebbet a fordított esetben.
	Hogy miért van erre szükség, arról lásd az 'Algoritmus' szakaszt
	lentebb.

`--left-only`::
	Elnyomja azokat a commitokat, amelyek hiányoznak az első megadott
	tartományból (vagy a "bal tartományból" a `<rev1>...<rev2>` alak
	használatakor).

`--right-only`::
	Elnyomja azokat a commitokat, amelyek hiányoznak a második megadott
	tartományból (vagy a "jobb tartományból" a `<rev1>...<rev2>` alak
	használatakor).

`--diff-merges=<format>`::
	Ahelyett, hogy figyelmen kívül hagyná a merge commitokat, diffeket
	generál hozzájuk a linkgit:git-log[1] megfelelő
	`--diff-merges=<format>` opciójával, és bevonja őket az
	összehasonlításba.
+
Megjegyzés: A gyakori esetben a `remerge` mód a legtermészetesebb
használni, mivel csak azt a diffet mutatja, amely a Git merge-gépezetének
kimenetére rakódik. Más szóval, ha egy merge commit egy konfliktusmentes
`git merge` eredménye, a `remerge` mód üres diffel ábrázolja.

`--remerge-diff`::
	Kényelmi opció, egyenértékű a `--diff-merges=remerge` alakkal.

`--notes[=<ref>]`::
`--no-notes`::
	Ez a kapcsoló a patcheket generáló `git log` programnak
	(lásd linkgit:git-log[1]) kerül átadásra.

`<range1> <range2>`::
	Összehasonlítja a két tartomány által megadott commitokat, ahol a
	_<range1>_ a _<range2>_ régebbi verziójának számít.

`<rev1>...<rev2>`::
	Egyenértékű a `<rev2>..<rev1>` és `<rev1>..<rev2>` átadásával.

`<base> <rev1> <rev2>`::
	Egyenértékű a `<base>..<rev1>` és `<base>..<rev2>` átadásával.
	Vedd figyelembe, hogy a _<base>_-nek nem kell a branchek pontos
	elágazási pontjának lennie. Példa: egy `my-topic` branch
	rebase-elése után a `git range-diff my-topic@{u} my-topic@{1}
	my-topic` megmutatná a rebase által bevezetett különbségeket.

A `git range-diff` elfogadja a szokásos diff-opciókat is (lásd
linkgit:git-diff[1]), legfőképpen a `--color[=<when>]` és `--no-color`
opciókat. Ezek az opciók a "patchek közötti diff" generálásakor
használatosak, azaz a megfelelő régi/új commitok szerzőjének,
commit-üzenetének és diffjének összehasonlításához. Jelenleg nincs mód arra,
hogy az e patchek generálásakor a `git log`-nak átadott diff-opciók
többségét finomhangold.

OUTPUT STABILITY
----------------

A `range-diff` parancs kimenete változhat. Ember által olvasható porcelain
kimenetnek szánták, nem olyasminek, amely a Git verziói között használható
egy szövegesen stabil `range-diff` előállítására (szemben mondjuk a
linkgit:git-patch-id[1] `--stable` opciójával). A `range-diff`-nek nincs a
linkgit:git-apply[1]-hez hasonló megfelelője sem; a kimenet nem gép által
olvashatónak készült.

Ez különösen igaz diff-opciók átadásakor. Jelenleg egyes opciók, például a
`--stat`, járulékos hatásként meglehetősen haszontalan kimenetet
produkálhatnak a `range-diff` kontextusában. A `range-diff` jövőbeli
verziói megtanulhatják az ilyen opciókat a `range-diff`-re jellemző módon
értelmezni (pl. a `--stat` esetén olyan, ember által olvasható kimenetet
előállítva, amely összefoglalja, hogyan változott a diffstat).

CONFIGURATION
-------------
Ez a parancs a `diff.color.*` és a `pager.range-diff` beállításokat
használja (utóbbi alapértelmezés szerint be van kapcsolva).
Lásd linkgit:git-config[1].


EXAMPLES
--------

Ha egy rebase során merge konfliktusokat kellett feloldani, közvetlenül
utána a következővel hasonlíthatod össze a rebase által bevezetett
változásokat:

------------
$ git range-diff @{u} @{1} @
------------


A `git range-diff` egy tipikus kimenete így nézne ki:

------------
-:  ------- > 1:  0ddba11 Prepare for the inevitable!
1:  c0debee = 2:  cab005e Add a helpful message at the start
2:  f00dbal ! 3:  decafe1 Describe a bug
    @@ -1,3 +1,3 @@
     Author: A U Thor <author@example.com>

    -TODO: Describe a bug
    +Describe a bug
    @@ -324,5 +324,6
      This is expected.

    -+What is unexpected is that it will also crash.
    ++Unexpectedly, it also crashes. This is a bug, and the jury is
    ++still out there how to fix it best. See ticket #314 for details.

      Contact
3:  bedead < -:  ------- TO-UNDO
------------

Ebben a példában 3 régi és 3 új commit van, ahol a fejlesztő eltávolította a
3.-at, hozzáadott egy újat az első kettő elé, és módosította a 2. commit
commit-üzenetét, valamint a diffjét is.

Amikor a kimenet terminálra megy, alapértelmezés szerint színkódolt, akárcsak
a szokásos `git diff` kimenete. Ezenkívül az első sor (egy commit
hozzáadása) zöld, az utolsó sor (egy commit törlése) piros, a második sor
(tökéletes egyezéssel) sárga, mint a `git show` kimenetének commit-fejléce,
a harmadik sor pedig a régi commitot pirosra, az újat zöldre színezi, a
többit pedig úgy, mint a `git show` commit-fejléce.

Egy naiv, színkódolt diffek-diffje azonban valójában kissé nehezen
olvasható, mivel a teljes sorokat pirosra vagy zöldre színezi. Az a sor
például, amely a régi commitban a "What is unexpected"-et adta hozzá,
teljesen piros, még akkor is, ha a régi commit szándéka az volt, hogy
hozzáadjon valamit.

Ennek megkönnyítésére a `range` alapértelmezés szerint a `--dual-color`
módot használja. Ebben a módban a diffek diffje megtartja az eredeti
diff-színeket, és a sorokat -/+ jelölőkkel látja el, amelyeknek a *háttere*
piros vagy zöld, hogy nyilvánvalóbb legyen: azt írják le, hogyan változott
maga a diff.


[[_algorithm]]
Algoritmus
----------

Az általános ötlet a következő: költségmátrixot generálunk a két
commit-tartomány commitjai között, majd megoldjuk a legkisebb költségű
hozzárendelést.

A költségmátrix feltöltése így történik: minden commitpárhoz mindkét diff
elkészül, majd elkészül a "diffek diffje" 3 kontextussorral, ezután annak a
diffnek a sorszáma lesz a költség.

A téves találatok elkerülésére (pl. amikor egy patchet eltávolítottak, és
egy nem kapcsolódó patchet adtak hozzá ugyanazon patchsorozat két iterációja
között) a költségmátrix kibővül ennek kezelésére, fix költségű bejegyzések
hozzáadásával a teljes törlésekhez/hozzáadásokhoz.

Példa: Legyen az `1--2` commit egy patchsorozat első iterációja, az `A--C`
pedig a második iteráció. Tegyük fel, hogy az `A` a `2,` cherry-pickje, a
`C` pedig az `1` cherry-pickje, de egy kis módosítással (mondjuk egy javított
elgépeléssel). Képzeld el a commitokat páros gráfként:

------------
    1            A

    2            B

		 C
------------

A régi sorozat alapján a "legjobb" magyarázatot keressük az új sorozatra.
Egy "magyarázat" a gráf egy éleként ábrázolható:


------------
    1            A
	       /
    2 --------'  B

		 C
------------

Ez a magyarázat "ingyen" van, mert nem történt változás. Hasonlóképpen a
`C` megmagyarázható az `1` segítségével, de ez valamekkora c>0 költséggel
jár a módosítás miatt:

------------
    1 ----.      A
	  |    /
    2 ----+---'  B
	  |
	  `----- C
	  c>0
------------

Matematikai értelemben egyfajta minimális költségű páros párosítást
keresünk; az `1` valamekkora költséggel párosul a `C`-hez stb. Az alapul
szolgáló gráf valójában teljes páros gráf; a minden élhez rendelt költség a
két commit patchje közötti diff mérete. Hogy az új commitokat is
megmagyarázzuk, mindkét oldalon fiktív csúcsokat vezetünk be:

------------
    1 ----.      A
	  |    /
    2 ----+---'  B
	  |
    o     `----- C
	  c>0
    o            o

    o            o
------------

Egy `o--C` él költsége a `C` diffjének mérete, egy 100%-nál kisebb
korrekciós tényezővel módosítva. Egy `o--o` él költsége ingyenes. A
korrekciós tényezőre azért van szükség, mert még ha az `1`-ben és a `C`-ben
nincs is semmi közös, akkor is osztozhatnak néhány üres soron és
hasonlókon, esetleg kicsit olcsóbbá téve az `1--C`, `o--o` hozzárendelést az
`1--o`, `o--C`-nél, még akkor is, ha az `1`-nek és a `C`-nek semmi közös
nincs benne. A korrekciós tényezővel jóval nagyobb közös részt követelünk
meg ahhoz, hogy a patcheket megfelelőnek tekintsük.

Az algoritmus kiszámításához szükséges teljes idő az n+m commit-diff, majd
az n*m patch-diff kiszámításához szükséges idő, plusz az n és m diff közötti
legkisebb költségű hozzárendelés kiszámításához szükséges idő. A Git a
Jonker–Volgenant algoritmus egy implementációját használja a hozzárendelési
probléma megoldására, amelynek köbös futásidejű bonyolultsága van. Az ebben
az esetben talált párosítás így néz ki:

------------
    1 ----.      A
	  |    /
    2 ----+---'  B
       .--+-----'
    o -'  `----- C
	  c>0
    o ---------- o

    o ---------- o
------------


SEE ALSO
--------
linkgit:git-log[1]

GIT
---
A linkgit:git[1] csomag része
