git-submodule(1)
================

NAME
----
git-submodule - Submodule-ok inicializálása, frissítése vagy megtekintése


SYNOPSIS
--------
[synopsis]
git submodule [--quiet] [--cached]
git submodule [--quiet] add [<options>] [--] <repository> [<path>]
git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
git submodule [--quiet] init [--] [<path>...]
git submodule [--quiet] deinit [-f|--force] (--all|[--] <path>...)
git submodule [--quiet] update [<options>] [--] [<path>...]
git submodule [--quiet] set-branch [<options>] [--] <path>
git submodule [--quiet] set-url [--] <path> <newurl>
git submodule [--quiet] summary [<options>] [--] [<path>...]
git submodule [--quiet] foreach [--recursive] <command>
git submodule [--quiet] sync [--recursive] [--] [<path>...]
git submodule [--quiet] absorbgitdirs [--] [<path>...]


DESCRIPTION
-----------
Megtekinti, frissíti és kezeli a submodule-okat.

A submodule-okról bővebb információért lásd: linkgit:gitsubmodules[7].

COMMANDS
--------
Argumentumok nélkül a meglévő submodule-ok állapotát mutatja. Több
alparancs áll rendelkezésre a submodule-okon végzett műveletekhez.

`add [-b <branch>] [-f | --force] [--name <name>] [--reference <repository>] [--ref-format <format>] [--depth <depth>] [--] <repository> [<path>]`::
	Hozzáadja a megadott repository-t submodule-ként a megadott
	útvonalon a legközelebb commitolandó changesethez az aktuális
	projekt mellett: az aktuális projektet "szuperprojektnek" nevezzük.
+
A `_<repository>_` az új submodule `origin` repository-jának az URL-je.
Ez lehet vagy egy abszolút URL, vagy (ha `./`-vel vagy `../`-vel
kezdődik) a szuperprojekt alapértelmezett remote repository-jához
relatív hely (Vedd figyelembe, hogy egy `foo.git` repository
megadásához, amely közvetlenül egy `bar.git` szuperprojekt mellett
található, a `./foo.git` helyett a `../foo.git`-et kell használnod –
ahogy azt a relatív URL-ek szabályait követve várni lehet –, mert a
relatív URL-ek kiértékelése a Gitben azonos a relatív könyvtárakéval).
+
Az alapértelmezett remote az aktuális branch remote-tracking branchjének
a remote-ja. Ha nem létezik ilyen remote-tracking branch, vagy a `HEAD`
le van választva, az `origin` a feltételezett alapértelmezett remote. Ha
a szuperprojektnek nincs alapértelmezett remote konfigurálva, a
szuperprojekt a saját mérvadó upstreamje, és helyette az aktuális
munkakönyvtár kerül felhasználásra.
+
Az opcionális `_<path>_` argumentum a klónozott submodule relatív helye,
ahol a szuperprojektben létezni fog. Ha a `_<path>_` nincs megadva, a
forrás-repository kanonikus része kerül felhasználásra (`repo` a
`/path/to/repo.git`-hez és `foo` a `host.xz:foo/.git`-hez). Ha a
`_<path>_` létezik, és már egy érvényes Git-repository, akkor klónozás
nélkül stage-elődik commitra. A `_<path>_` a submodule logikai neveként
is szolgál a konfigurációs bejegyzéseiben, hacsak a `--name <name>`
nincs használatban egy logikai név megadására.
+
A megadott URL a `.gitmodules`-ba rögzítődik a szuperprojektet klónozó
későbbi felhasználók számára. Ha az URL a szuperprojekt repository-jához
relatívan van megadva, a feltételezés az, hogy a szuperprojekt és a
submodule repository-i ugyanazon a relatív helyen maradnak együtt, és
csak a szuperprojekt URL-jét kell megadni. A git-submodule helyesen
megtalálja a submodule-t a `.gitmodules`-ban lévő relatív URL
használatával.
+
Ha a `--ref-format <format>` meg van adva, az újonnan klónozott
submodule-ok ref-tárolási formátuma ennek megfelelően lesz beállítva.

`status [--cached] [--recursive] [--] [<path>...]`::
	Megmutatja a submodule-ok állapotát. Ez minden submodule-ra kiírja
	az aktuálisan checkoutolt commit SHA-1-jét, a submodule útvonalával
	és a linkgit:git-describe[1] SHA-1-re vonatkozó kimenetével együtt.
	Minden SHA-1 esetleg `-` előtaggal jelenik meg, ha a submodule
	nincs inicializálva, `+`-szal, ha az aktuálisan checkoutolt submodule
	commit nem egyezik a tartalmazó repository indexében talált SHA-1-gyel,
	és `U`-val, ha a submodule-ban merge-konfliktusok vannak.
+
Ha a `--cached` meg van adva, ez a parancs helyette minden submodule-ra
a szuperprojektben rögzített SHA-1-et írja ki.
+
Ha a `--recursive` meg van adva, ez a parancs a beágyazott
submodule-okba is rekurzívan belemegy, és az ő állapotukat is
megmutatja.
+
Ha csak az aktuálisan inicializált submodule-ok változásai érdekelnek
az indexben vagy a `HEAD`-ben rögzített commithoz képest, a
linkgit:git-status[1] és a linkgit:git-diff[1] is megadja azt az
információt (és egy submodule work tree-jének változásait is jelenteni
tudja).

`init [--] [<path>...]`::
	Inicializálja az indexben rögzített submodule-okat (amelyeket máshol
	adtak hozzá és commitoltak) a `submodule.$name.url` beállításával a
	`.git/config`-ban, a `.gitmodules` ugyanezen beállítását sablonként
	használva. Ha az URL relatív, az alapértelmezett remote
	használatával oldódik fel. Ha nincs alapértelmezett remote, az
	aktuális repository lesz a feltételezett upstream.
+
Az opcionális `_<path>_` argumentumok korlátozzák, mely submodule-ok
inicializálódnak. Ha nincs útvonal megadva, és a submodule.active
konfigurálva van, az aktívnak konfigurált submodule-ok inicializálódnak,
egyébként az összes submodule.
+
A `submodule.$name.update` értékét is átmásolja, ha jelen van a
`.gitmodules` fájlban, a `.git/config`-ba, de (1) ez a parancs nem
módosítja a `.git/config`-ban lévő meglévő információt, és (2) az egyéni
parancsra állított `submodule.$name.update` biztonsági okokból *nem*
másolódik.
+
Ezután testreszabhatod a submodule klón-URL-eket a `.git/config`-ban a
helyi beállításodhoz, és folytathatod a `git submodule update`-tel; ha
nem szándékozol semmilyen submodule-helyet testreszabni, egyszerűen a
`git submodule update --init`-et is használhatod az explicit `init`
lépés nélkül.
+
Az alapértelmezett remote definíciójáért lásd az add alparancsot.

`deinit [-f | --force] (--all|[--] <path>...)`::
	Kiregisztrálja a megadott submodule-okat, azaz eltávolítja a teljes
	`submodule.$name` szekciót a .git/config-ból a work tree-jükkel
	együtt. A `git submodule update`, `git submodule foreach` és
	`git submodule sync` további hívásai kihagynak minden kiregisztrált
	submodule-t, amíg azokat újra nem inicializálják, így használd ezt a
	parancsot, ha már nem akarsz helyi checkoutot a submodule-ból a
	working tree-dben.
+
Amikor a parancs pathspec nélkül fut, hibázik, ahelyett, hogy mindent
deinitelne, hogy megelőzze a hibákat.
+
Ha a `--force` meg van adva, a submodule working tree-je akkor is
eltávolítódik, ha helyi módosításokat tartalmaz.
+
Ha tényleg el akarsz távolítani egy submodule-t a repository-ból, és
azt commitolni, helyette a linkgit:git-rm[1]-et használd. Az
eltávolítási opciókért lásd: linkgit:gitsubmodules[7].

`update [--init] [--remote] [-N | --no-fetch] [--[no-]recommend-shallow] [-f | --force] [--checkout | --rebase | --merge] [--reference=<repository>] [--ref-format=<format>] [--depth=<depth>] [--recursive] [--jobs <n>] [--[no-]single-branch] [--filter=<filter-spec>] [--] [<path>...]`::
+
--
Frissíti a regisztrált submodule-okat, hogy egyezzenek azzal, amit a
szuperprojekt elvár, a hiányzó submodule-ok klónozásával, a
submodule-okban lévő hiányzó commitok fetchelésével és a submodule-ok
working tree-jének frissítésével. A „frissítés" többféleképp végezhető
el, a parancssori kapcsolóktól és a `submodule.<name>.update`
konfigurációs változó értékétől függően. A parancssori kapcsolónak
elsőbbsége van a konfigurációs változóval szemben. Ha egyik sincs
megadva, `checkout` hajtódik végre. (megjegyzés: az, hogy mi van a
`.gitmodules` fájlban, ezen a ponton irreleváns; a `.gitmodules`
használatáról lásd a fenti `git submodule init`-et.) A `update`
eljárások, amelyek mind a parancssorból, mind a `submodule.<name>.update`
konfiguráción keresztül támogatottak:

`checkout`;; a szuperprojektben rögzített commit checkoutolódik a
submodule-ban egy leválasztott `HEAD`-en.
+
Ha a `--force` meg van adva, a submodule checkoutolódik (a
`git checkout --force` használatával), még akkor is, ha a tartalmazó
repository indexében megadott commit már egyezik a submodule-ban
checkoutolt committal.

`rebase`;; a submodule aktuális branchje a szuperprojektben rögzített
commitra rebase-elődik.

`merge`;; a szuperprojektben rögzített commit a submodule aktuális
branchjébe merge-elődik.

A következő frissítési eljárásoknak további korlátaik vannak:

`!<custom-command>`;; mechanizmus tetszőleges parancsok futtatására a
commit ID-jével mint argumentummal. Konkrétan, ha a
`submodule.<name>.update` konfigurációs változó `!<custom-command>`-ra
van állítva, a szuperprojektben a submodule-hoz rögzített commit
objektumneve a `_<custom-command>_` sztringhez fűződik, és végrehajtódik.
Vedd figyelembe, hogy ez a mechanizmus nem támogatott a `.gitmodules`
fájlban vagy a parancssorban.

`none`;; a submodule nem frissül. Ez a frissítési eljárás nem
megengedett a parancssorban.

Ha a submodule még nincs inicializálva, és csak a `.gitmodules`-ban
tárolt beállítást akarod használni, automatikusan inicializálhatod a
submodule-t a `--init` kapcsolóval.

Ha a `--recursive` meg van adva, ez a parancs a regisztrált
submodule-okba is rekurzívan belemegy, és frissíti az azokon belüli
beágyazott submodule-okat.

Ha a `--ref-format <format>` meg van adva, az újonnan klónozott
submodule-ok ref-tárolási formátuma ennek megfelelően lesz beállítva.

Ha a `--filter <filter-spec>` meg van adva, a megadott partial clone
szűrő alkalmazódik a submodule-ra. A szűrőspecifikációk részleteiért
lásd: linkgit:git-rev-list[1].
--
`set-branch (-b|--branch) <branch> [--] <path>`::
`set-branch (-d|--default) [--] <path>`::
	Beállítja a submodule alapértelmezett remote-tracking branchjét. A
	`--branch` kapcsoló lehetővé teszi a remote branch megadását. A
	`--default` kapcsoló eltávolítja a `submodule.<name>.branch`
	konfigurációs kulcsot, ami miatt a tracking branch alapból a remote
	`HEAD` lesz.

`set-url [--] <path> <newurl>`::
	Beállítja a megadott submodule URL-jét `_<newurl>_`-re. Ezután
	automatikusan szinkronizálja a submodule új remote URL
	konfigurációját.

`summary [--cached | --files] [(-n|--summary-limit) <n>] [commit] [--] [<path>...]`::
	Megmutatja a commit-összefoglalót a megadott commit (alapból `HEAD`)
	és a working tree/index között. A szóban forgó submodule-ra a
	submodule-ban lévő commitok egy sorozata jelenik meg a megadott
	szuperprojekt-commit és az index vagy a working tree (a `--cached`-dzsel
	váltva) között. Ha a `--files` kapcsoló meg van adva, a submodule-ban
	lévő commitok sorozatát mutatja a szuperprojekt indexe és a submodule
	working tree-je között (ez a kapcsoló nem engedi a `--cached` kapcsoló
	használatát vagy egy explicit commit megadását).
+
A `--submodule=log` kapcsoló használata a linkgit:git-diff[1]-mel
szintén megadja azt az információt.

`foreach [--recursive] <command>`::
	Kiértékel egy tetszőleges shell `_<command>_`-ot minden
	checkoutolt submodule-ban. A parancs hozzáfér a `$name`, `$sm_path`,
	`$displaypath`, `$sha1` és `$toplevel` változókhoz:
+
--
`$name`;; a vonatkozó submodule-szekció neve a `.gitmodules`-ban
`$sm_path`;; a submodule útvonala, ahogy a közvetlen szuperprojektben
	rögzítve van
`$displaypath`;; a relatív útvonal az aktuális munkakönyvtártól a
	submodule-ok gyökérkönyvtáráig
`$sha1`;; a commit, ahogy a közvetlen szuperprojektben rögzítve van
`$toplevel`;; a közvetlen szuperprojekt legfelső szintjének abszolút útvonala.
--
+
Vedd figyelembe, hogy a Windowson lévő `$PATH`-tal való ütközések
elkerülése érdekében a `$path` változó most a `$sm_path` változó elavult
szinonimája. Minden olyan submodule-t, amely a szuperprojektben van
definiálva, de nincs checkoutolva, figyelmen kívül hagy ez a parancs.
Hacsak a `--quiet` nincs megadva, a foreach minden submodule nevét
kiírja a parancs kiértékelése előtt. Ha a `--recursive` meg van adva, a
submodule-ok rekurzívan kerülnek bejárásra (azaz a megadott
shell-parancs a beágyazott submodule-okban is kiértékelődik). A
parancsból bármely submodule-ban visszakapott nem nulla érték a
feldolgozás leállását okozza. Ez felülbírálható a ++||:++ hozzáadásával
a parancs végéhez.
+
Példaként az alábbi parancs minden submodule-ra megmutatja az útvonalat
és az aktuálisan checkoutolt commitot:
+
--------------
git submodule foreach 'echo $sm_path `git rev-parse HEAD`'
--------------

`sync [--recursive] [--] [<path>...]`::
	Szinkronizálja a submodule-ok remote URL konfigurációs beállítását
	a `.gitmodules`-ban megadott értékre. Csak azokat a submodule-okat
	érinti, amelyeknek már van URL-bejegyzésük a `.git/config`-ban (ez az
	eset, amikor inicializálva vannak vagy frissen hozzáadva). Ez akkor
	hasznos, amikor a submodule URL-ek megváltoznak upstreamen, és ennek
	megfelelően frissítened kell a helyi repository-idat.
+
A `git submodule sync` az összes submodule-t szinkronizálja, míg a
`git submodule sync -- A` csak az `A` submodule-t.
+
Ha a `--recursive` meg van adva, ez a parancs a regisztrált
submodule-okba is rekurzívan belemegy, és szinkronizálja az azokon
belüli beágyazott submodule-okat.

`absorbgitdirs`::
	Ha egy submodule git-könyvtára a submodule-on belül van, áthelyezi a
	submodule git-könyvtárát a szuperprojektje `$GIT_DIR/modules`
	útvonalára, majd összeköti a git-könyvtárat és a munkakönyvtárát
	azzal, hogy beállítja a `core.worktree`-t, és hozzáad egy `.git`
	fájlt, amely a szuperprojekt git-könyvtárába ágyazott git-könyvtárra
	mutat.
+
Egy repository, amelyet függetlenül klónoztak, majd később submodule-ként
adtak hozzá, vagy a régi beállítások a submodule git-könyvtárát a
submodule-on belül tartják, ahelyett, hogy a szuperprojekt
git-könyvtárába lenne ágyazva.
+
Ez a parancs alapból rekurzív.

OPTIONS
-------
`-q`::
`--quiet`::
	Csak hibaüzeneteket ír ki.

`--progress`::
	Alapból folyamatállapotot jelent a standard hibakimeneten, amikor az
	terminálhoz van csatolva, hacsak a `-q` nincs megadva. Ez a kapcsoló
	akkor is kikényszeríti a folyamatállapotot, ha a standard hibakimenet
	nincs terminálra irányítva. Csak az `add` és `update` parancsnál
	érvényes.

`--all`::
	Kiregisztrálja a working tree összes submodule-ját. Ez a kapcsoló
	csak a `deinit` parancsnál érvényes.

`-b<branch>`::
`--branch=<branch>`::
	A repository submodule-ként hozzáadandó branchje. A branch neve
	`submodule.<name>.branch`-ként rögzítődik a `.gitmodules`-ban az
	`update --remote` számára. A `.` speciális érték annak jelzésére
	szolgál, hogy a branch neve a submodule-ban ugyanaz legyen, mint az
	aktuális branch neve az aktuális repository-ban. Ha a kapcsoló nincs
	megadva, alapból a remote `HEAD`.

`-f`::
`--force`::
	Kényszeríti a parancsot, hogy folytassa, még akkor is, ha egyébként
	meghiúsulna. Ez a kapcsoló csak az `add`, `deinit` és `update`
	parancsnál érvényes.
`add`;; engedélyezi egy egyébként ignorált submodule-útvonal
hozzáadását. Ez a kapcsoló egy olyan ellenőrzés megkerülésére is
szolgál, hogy a submodule neve nincs-e már használatban. Alapból a
`git submodule add` meghiúsul, ha a javasolt név (amely az útvonalból
származik) már regisztrálva van egy másik submodule-hoz a
repository-ban. A `--force` használata lehetővé teszi, hogy a parancs
folytassa, automatikusan egyedi nevet generálva egy szám hozzáfűzésével
az ütköző névhez (pl. ha létezik egy 'child' nevű submodule, a
'child1'-et próbálja, és így tovább).
`deinit`;; a submodule working tree-i akkor is eltávolítódnak, ha helyi
változásokat tartalmaznak.
`update`;; (csak a checkout eljárással hatásos), eldobja a helyi
változásokat a submodule-okban egy másik commitra váltáskor; és mindig
lefuttat egy checkout műveletet a submodule-ban, még akkor is, ha a
tartalmazó repository indexében felsorolt commit egyezik a submodule-ban
checkoutolt committal.

`--cached`::
	Az indexet használja a commit meghatározásához a `HEAD` helyett. Ez
	a kapcsoló csak a `status` és `summary` parancsnál érvényes.

`--files`::
	Ráveszi a `summary` parancsot, hogy az indexben lévő commitot a
	submodule `HEAD`-jében lévővel hasonlítsa össze.

`-n<n>`::
`--summary-limit=<n>`::
	Korlátozza a `summary` méretét (az összesen megjelenített commitok
	számát) `_<n>_`-re. A 0 megadása letiltja a summaryt; a negatív szám
	korlátlant jelent (az alapértelmezett). Ez a korlát csak a
	módosított submodule-okra vonatkozik. A méret mindig 1-re van
	korlátozva a hozzáadott/törölt/típusváltott submodule-okhoz.

`--remote`::
	Ahelyett, hogy a szuperprojekt rögzített SHA-1-jét használná a
	submodule frissítéséhez, a submodule remote-tracking branchjének az
	állapotát használja. Ez a kapcsoló csak az `update` parancsnál
	érvényes. A használt remote a branch remote-ja
	(`branch.<name>.remote`), alapból `origin`. A használt remote branch
	alapból a remote `HEAD`, de a branch neve felülbírálható a
	`submodule.<name>.branch` kapcsoló beállításával akár a
	`.gitmodules`-ban, akár a `.git/config`-ban (a `.git/config`
	elsőbbséget élvez).
+
Ez bármely támogatott frissítési eljárásra működik (`--checkout`,
`--rebase`, stb.). Az egyetlen változás a cél SHA-1 forrása. Például a
`submodule update --remote --merge` upstream submodule-változásokat
merge-el a submodule-okba, míg a `submodule update --merge`
szuperprojekt-gitlink-változásokat merge-el a submodule-okba.
+
Egy aktuális tracking branch állapot biztosítása érdekében az
`update --remote` fetcheli a submodule remote repository-ját az SHA-1
kiszámítása előtt. Ha nem akarsz fetchelni, a
`submodule update --remote --no-fetch`-et kell használnod.
+
Ezt a kapcsolót arra használd, hogy az upstream alprojekt változásait a
submodule-od aktuális `HEAD`-jével integráld. Alternatívaként
lefuttathatod a `git pull`-t a submodule-ból, ami egyenértékű, kivéve a
remote branch nevét: az `update --remote` az alapértelmezett upstream
repository-t és a `submodule.<name>.branch`-et használja, míg a
`git pull` a submodule `branch.<name>.merge`-jét. Részesítsd előnyben a
`submodule.<name>.branch`-et, ha a szuperprojekttel az alapértelmezett
upstream branchet akarod terjeszteni, és a `branch.<name>.merge`-et, ha
natívabb érzést akarsz, miközben magában a submodule-ban dolgozol.

`-N`::
`--no-fetch`::
	Nem fetchel új objektumokat a remote oldalról. Ez a kapcsoló csak az
	`update` parancsnál érvényes.

`--checkout`::
	Checkoutolja a szuperprojektben rögzített commitot egy leválasztott
	`HEAD`-en a submodule-ban. Ez a kapcsoló csak az `update` parancsnál
	érvényes. Ez az alapértelmezett viselkedés, e kapcsoló fő
	felhasználása a `submodule.<name>.update` felülbírálása, amikor az a
	`checkout`-tól eltérő értékre van állítva. Ha a
	`submodule.<name>.update` kulcs vagy nincs explicit módon beállítva,
	vagy `checkout`-ra van állítva, ez a kapcsoló implicit.

`--merge`::
	Merge-eli a szuperprojektben rögzített commitot a submodule aktuális
	branchjébe. Ez a kapcsoló csak az `update` parancsnál érvényes. Ha
	ez a kapcsoló meg van adva, a submodule `HEAD`-je nem lesz
	leválasztva. Ha egy merge-hiba megakadályozza ezt a folyamatot, az
	eredményül kapott konfliktusokat a submodule-on belül kell
	feloldanod a szokásos konfliktusfeloldó eszközökkel. Ha a
	`submodule.<name>.update` kulcs `merge`-re van állítva, ez a kapcsoló
	implicit.

`--rebase`::
	Rebase-eli az aktuális branchet a szuperprojektben rögzített
	commitra. Ez a kapcsoló csak az `update` parancsnál érvényes. A
	submodule `HEAD`-je nem lesz leválasztva. Ha egy merge-hiba
	megakadályozza ezt a folyamatot, ezeket a hibákat a
	linkgit:git-rebase[1]-mel kell feloldanod. Ha a
	`submodule.<name>.update` kulcs `rebase`-re van állítva, ez a
	kapcsoló implicit.

`--init`::
	Frissítés előtt inicializálja az összes submodule-t, amelyre a
	`git submodule init` eddig nem hívódott meg. Ez a kapcsoló csak az
	`update` parancsnál érvényes.


`--name=<name>`::
	Beállítja a submodule nevét a megadott sztringre, ahelyett, hogy
	alapból az útvonala lenne. A `_<name>_` érvényes kell legyen
	könyvtárnévként, és nem végződhet `/`-vel.

`--reference=<repository>`::
	Átadja a helyi `_<repository>_`-t referenciaként a submodule
	klónozásakor. Ez a kapcsoló csak az `add` és `update` parancsnál
	érvényes. Ezeknek a parancsoknak néha egy remote repository-t kell
	klónozniuk. Ebben az esetben ez a kapcsoló átadódik a
	linkgit:git-clone[1] parancsnak.
+
NOTE: *Ne* használd ezt a kapcsolót, hacsak nem olvastad el gondosan a
linkgit:git-clone[1] `--reference`, `--shared` és `--dissociate`
kapcsolóihoz tartozó megjegyzést.

`--dissociate`::
	Miután egy referencia-repository-t használtál a klónozáshoz, ne
	támaszkodj rá többé. Ez a kapcsoló csak az `add` és `update`
	parancsnál érvényes. Ezeknek a parancsoknak néha egy remote
	repository-t kell klónozniuk. Ebben az esetben ez a kapcsoló
	átadódik a linkgit:git-clone[1] parancsnak.
+
NOTE: Lásd a fenti NOTE-ot a `--reference` kapcsolóhoz.

`--recursive`::
	Rekurzívan bejárja a submodule-okat. Ez a kapcsoló csak a `foreach`,
	`update`, `status` és `sync` parancsnál érvényes. A művelet nemcsak
	az aktuális repó submodule-jaiban hajtódik végre, hanem azoknak a
	submodule-oknak a bármely beágyazott submodule-jában is (és így
	tovább).

`--depth=<depth>`::
	Létrehoz egy 'shallow' klónt, amelynek a története `_<depth>_`
	revízióra van csonkítva. Ez a kapcsoló az `add` és `update`
	parancsnál érvényes. Lásd: linkgit:git-clone[1]

`--recommend-shallow`::
`--no-recommend-shallow`::
	A submodule-ok shallow klónozásának ajánlása vagy sem. Ez a kapcsoló
	csak az `update` parancsnál érvényes. Egy submodule kezdeti klónja
	alapból a `.gitmodules` fájl által megadott ajánlott
	`submodule.<name>.shallow`-t használja. A javaslatok figyelmen kívül
	hagyásához használd a `--no-recommend-shallow`-t.

`-j<n>`::
`--jobs=<n>`::
	Új submodule-okat klónoz párhuzamosan `_<n>_` jobbal. Ez a kapcsoló
	csak az `update` parancsnál érvényes. Alapból a `submodule.fetchJobs`
	kapcsoló.

`--single-branch`::
`--no-single-branch`::
	Frissítés során csak egy branchet klónoz: `HEAD` vagy egy, amelyet a
	`--branch` ad meg. Ez a kapcsoló csak az `update` parancsnál
	érvényes.

`<path>...`::
	Útvonalak a submodule-(ok)hoz. Ha meg van adva, ez a parancsot arra
	korlátozza, hogy csak a megadott útvonalakon található
	submodule-okon működjön. (Ez az argumentum az `add`-nél kötelező.)

FILES
-----
Submodule-ok inicializálásakor a tartalmazó repository legfelső szintű
könyvtárában lévő `.gitmodules` fájl szolgál az egyes submodule-ok
URL-jének megtalálására. Ezt a fájlt ugyanúgy kell formázni, mint a
`$GIT_DIR/config`-ot. Az egyes submodule URL-ekhez tartozó kulcs a
`submodule.<name>.url`. A részletekért lásd: linkgit:gitmodules[5].

SEE ALSO
--------
linkgit:gitsubmodules[7], linkgit:gitmodules[5].

GIT
---
A linkgit:git[1] csomag része
