git-check-mailmap(1)
====================

NAME
----
git-check-mailmap - A kontaktok kanonikus nevének és e-mail-címének megjelenítése


SYNOPSIS
--------
[verse]
'git check-mailmap' [<options>] <contact>...


DESCRIPTION
-----------

A parancssorból vagy a standard bemenetről (ha a `--stdin` kapcsolót
használjuk) érkező minden egyes ``Name $$<user@host>$$'', ``$$<user@host>$$''
vagy ``$$user@host$$'' alakhoz kikeresi a személy kanonikus nevét és
e-mail-címét (l. a lenti "Szerzők leképezése" szakaszt). Ha talál ilyet,
kiírja; egyébként a bemenetet változatlanul írja ki.


OPTIONS
-------
--stdin::
	A parancssorban megadott kontaktok kimerülése után soronként egy
	kontaktot olvas be a standard bemenetről.

--mailmap-file=<file>::
	A beállított mailmap fájlokon felül a megadott mailmap fájlt is
	beolvassa. Az ebben a fájlban lévő bejegyzések elsőbbséget élveznek
	az alapértelmezett mailmap fájl vagy bármely beállított mailmap fájl
	bejegyzéseivel szemben.

--mailmap-blob=<blob>::
	A `--mailmap-file`-hoz hasonló, de az értéket a repository-n belüli
	egy blobra mutató referenciának tekinti. Ha egyszerre van megadva
	`--mailmap-file` és `--mailmap-blob` is, a `--mailmap-file`
	bejegyzései élveznek elsőbbséget.

OUTPUT
------

Minden kontakthoz egy, újsorral lezárt sor kerül kiírásra. Ha a név meg van
adva vagy ismert a 'mailmap'-ben, a ``Name $$<user@host>$$'' alak kerül
kiírásra; egyébként csak a ``$$<user@host>$$'' alak.


CONFIGURATION
-------------

Az egyéni `.mailmap` célfájl vagy -objektum megadásának módjáról l. a
`mailmap.file` és `mailmap.blob` beállításokat a linkgit:git-config[1]
parancsban.


[[_mapping_authors]]
Szerzők leképezése
------------------

L. linkgit:gitmailmap[5].


GIT
---
A linkgit:git[1] csomag része
