git-restore(1)
==============

NAME
----
git-restore - Munkakönyvtárbeli fájlok visszaállítása

SYNOPSIS
--------
[synopsis]
git restore [<options>] [--source=<tree>] [--staged] [--worktree] [--] <pathspec>...
git restore [<options>] [--source=<tree>] [--staged] [--worktree] --pathspec-from-file=<file> [--pathspec-file-nul]
git restore (-p|--patch) [<options>] [--source=<tree>] [--staged] [--worktree] [--] [<pathspec>...]

DESCRIPTION
-----------
A munkakönyvtárban megadott elérési utakat állítja vissza egy visszaállítási
forrás valamely tartalmával. Ha egy elérési út követett, de a visszaállítási
forrásban nem létezik, akkor eltávolítja, hogy megegyezzen a forrással.

A parancs az index tartalmának visszaállítására is használható a `--staged`
kapcsolóval, vagy a munkakönyvtár és az index együttes visszaállítására a
`--staged --worktree` kapcsolókkal.

Alapértelmezés szerint, ha a `--staged` meg van adva, a tartalom a `HEAD`-ből
áll vissza, egyébként az indexből. A `--source` használatával egy másik
commitból állíthatsz vissza.

A három parancs közötti különbségekért lásd a "Reset, restore and revert"
szakaszt a linkgit:git[1] man oldalon.

OPTIONS
-------
`-s <tree>`::
`--source=<tree>`::
	A munkakönyvtárbeli fájlokat a megadott fa tartalmával állítja
	vissza. Bevett szokás a forrásfát egy hozzá tartozó commit, branch
	vagy tag nevével megadni.
+
Ha nincs megadva, a tartalom a `HEAD`-ből áll vissza, ha a `--staged` meg van
adva, egyébként az indexből.
+
Speciális esetként a `"<rev-A>...<rev-B>"` alak rövidítésként használható
_<rev-A>_ és _<rev-B>_ merge-alapjára, ha pontosan egy merge-alap van. _<rev-A>_
és _<rev-B>_ közül legfeljebb az egyik elhagyható, ilyenkor az alapértelmezése `HEAD`.

`-p`::
`--patch`::
	Interaktívan válaszd ki a hunkokat a visszaállítási forrás és a
	visszaállítási hely közötti eltérésben. A `--patch` mód kezeléséről
	a linkgit:git-add[1] „Interaktív mód" szakaszában olvashatsz.

include::diff-context-options.adoc[]

`-W`::
`--worktree`::
`-S`::
`--staged`::
	A visszaállítás helyének megadása. Ha egyik kapcsoló sincs megadva,
	alapértelmezés szerint a munkakönyvtár áll vissza. A `--staged`
	megadása csak az indexet állítja vissza. Mindkettő megadása mindkettőt
	visszaállítja.

`-q`::
`--quiet`::
	Csendes mód, elnyomja a visszajelző üzeneteket. Magában foglalja a
	`--no-progress`-t.

`--progress`::
`--no-progress`::
	Az előrehaladás állapotát alapértelmezés szerint a standard hibakimenetre
	írja, ha az terminálhoz kapcsolódik, kivéve ha a `--quiet` meg van adva.
	Ez a kapcsoló akkor is bekapcsolja az előrehaladás jelzését, ha nem
	terminálhoz kapcsolódik, a `--quiet`-tól függetlenül.

`--ours`::
`--theirs`::
	Amikor a munkakönyvtárbeli fájlokat az indexből állítod vissza, a
	nem merge-elt elérési utakhoz a #2 (`ours`) vagy a #3 (`theirs`)
	stage-et használja. Ez a kapcsoló nem használható, amikor egy
	tree-ish-ből (azaz a `--source` kapcsolóval) checkoutolsz elérési utakat.
+
Vedd figyelembe, hogy `git rebase` és `git pull --rebase` közben az `ours` és
a `theirs` felcserélve tűnhet fel. Részletekért lásd ugyanezen kapcsolók
magyarázatát a linkgit:git-checkout[1] man oldalon.

`-m`::
`--merge`::
	Amikor a munkakönyvtárbeli fájlokat az indexből állítod vissza, a
	nem merge-elt elérési utakban újra létrehozza a konfliktusos merge-et.
	Ez a kapcsoló nem használható, amikor egy tree-ish-ből (azaz a
	`--source` kapcsolóval) checkoutolsz elérési utakat.

`--conflict=<style>`::
	Ugyanaz, mint a fenti `--merge` kapcsoló, de megváltoztatja a
	konfliktusos hunkok megjelenítésének módját, felülírva a
	`merge.conflictStyle` konfigurációs változót.  A lehetséges értékek:
	`merge` (alapértelmezett), `diff3` és `zdiff3`.

`--ignore-unmerged`::
	Amikor a munkakönyvtárbeli fájlokat az indexből állítod vissza, ne
	szakítsa meg a műveletet, ha vannak nem merge-elt bejegyzések, és
	sem a `--ours`, sem a `--theirs`, sem a `--merge`, sem a `--conflict`
	nincs megadva. A munkakönyvtárban lévő nem merge-elt elérési utakat
	érintetlenül hagyja.

`--ignore-skip-worktree-bits`::
	Sparse checkout módban alapértelmezés szerint csak azok a bejegyzések
	frissülnek, amelyekre a _<pathspec>_ és a `$GIT_DIR/info/sparse-checkout`
	fájlbeli sparse minták is illeszkednek. Ez a kapcsoló figyelmen kívül
	hagyja a sparse mintákat, és feltétel nélkül visszaállít minden
	_<pathspec>_ által megadott fájlt.

`--recurse-submodules`::
`--no-recurse-submodules`::
	Ha a _<pathspec>_ egy aktív submodule-t nevez meg, és a visszaállítás
	helye tartalmazza a munkakönyvtárat, a submodule csak akkor frissül,
	ha ez a kapcsoló meg van adva; ilyenkor a munkakönyvtára a
	szuperprojektben rögzített commitra áll vissza, és minden helyi
	módosítás felülíródik. Ha semmi (vagy a `--no-recurse-submodules`)
	nincs használatban, a submodule-ok munkakönyvtárai nem frissülnek.
	A linkgit:git-checkout[1]-hoz hasonlóan ez leválasztja a submodule
	`HEAD`-jét.

`--overlay`::
`--no-overlay`::
	Overlay módban a visszaállítás sosem távolít el fájlokat. No-overlay
	módban eltávolítja azokat a követett fájlokat, amelyek nem szerepelnek
	a `--source=<tree>` _<tree>_-jében, hogy pontosan megegyezzenek a
	_<tree>_-vel. Az alapértelmezés a no-overlay mód.

`--pathspec-from-file=<file>`::
	A pathspec a _<file>_-ban kerül átadásra a parancssori argumentumok
	helyett. Ha a _<file>_ pontosan `-`, akkor a standard bemenetet
	használja. A pathspec-elemeket _LF_ vagy _CR_/_LF_ választja el. A
	pathspec-elemek idézőjelezhetők, ahogyan azt a `core.quotePath`
	konfigurációs változónál leírtuk (lásd linkgit:git-config[1]). Lásd
	még a `--pathspec-file-nul` és a globális `--literal-pathspecs`
	kapcsolót.

`--pathspec-file-nul`::
	Csak a `--pathspec-from-file`-lal van értelme. A pathspec-elemeket
	_NUL_ karakter választja el, és minden más karakter szó szerint
	értendő (a soremeléseket és az idézőjeleket is beleértve).

`--`::
	Ne értelmezzen több argumentumot kapcsolóként.

`<pathspec>...`::
	Korlátozza a művelet által érintett elérési utakat.
+
További részletekért lásd a 'pathspec' bejegyzést a linkgit:gitglossary[7]-ben.

EXAMPLES
--------

A következő szekvencia átvált a `master` branchre, két revízióval korábbi
állapotra állítja vissza a `Makefile`-t, tévedésből törli a `hello.c`-t,
majd visszaszerzi az indexből.

------------
$ git switch master
$ git restore --source master~2 Makefile  <1>
$ rm -f hello.c
$ git restore hello.c                     <2>
------------

<1> egy fájl kivétele egy másik commitból
<2> a `hello.c` visszaállítása az indexből

Ha _minden_ C forrásfájlt vissza akarsz állítani úgy, hogy megegyezzen az
indexben lévő verzióval, ezt mondhatod

------------
$ git restore '*.c'
------------

Figyeld meg a `*.c` körüli idézőjeleket.  A `hello.c` fájl is
visszaáll, még akkor is, ha már nincs a munkakönyvtárban, mert a
fájlnév-globbing az indexben lévő bejegyzésekre illeszkedik (nem a
munkakönyvtárban a shell által).

Az aktuális könyvtár összes fájljának visszaállításához

------------
$ git restore .
------------

vagy a munkakönyvtár összes fájljának visszaállításához a 'top' pathspec-mágiával (lásd
linkgit:gitglossary[7])

------------
$ git restore :/
------------

Egy indexbeli fájl visszaállításához úgy, hogy megegyezzen a `HEAD`-ben
lévő verzióval (ez ugyanaz, mint a linkgit:git-reset[1] használata)

------------
$ git restore --staged hello.c
------------

vagy visszaállíthatod az indexet és a munkakönyvtárat is (ez ugyanaz, mint
a linkgit:git-checkout[1] használata)

------------
$ git restore --source=HEAD --staged --worktree hello.c
------------

vagy a rövid alak, amely praktikusabb, de kevésbé olvasható:

------------
$ git restore -s@ -SW hello.c
------------

SEE ALSO
--------
linkgit:git-checkout[1],
linkgit:git-reset[1]

GIT
---
A linkgit:git[1] csomag része
