git-clean(1)
============

NAME
----
git-clean - Nem követett fájlok eltávolítása a munkakönyvtárból

SYNOPSIS
--------
[verse]
'git clean' [-d] [-f] [-i] [-n] [-q] [-e <pattern>] [-x | -X] [--] [<pathspec>...]

DESCRIPTION
-----------

Megtisztítja a munkakönyvtárat azáltal, hogy rekurzívan eltávolítja azokat a
fájlokat, amelyek nincsenek verziókövetés alatt, az aktuális könyvtárból kiindulva.

Alapesetben csak a Git számára ismeretlen fájlok kerülnek eltávolításra, de ha
a `-x` opció meg van adva, a figyelmen kívül hagyott fájlok is törlődnek. Ez
például hasznos lehet az összes build-termék eltávolításához.

Ha bármilyen opcionális `<pathspec>...` argumentum meg van adva, csak azok az
elérési utak érintettek, amelyek illeszkednek a pathspecre.

OPTIONS
-------
-d::
	Alapesetben, ha nincs <pathspec> megadva, a git clean nem rekurzál
	be a nem követett könyvtárakba, hogy elkerülje a túl sok fájl
	eltávolítását. Add meg a -d kapcsolót, hogy ilyen könyvtárakba is
	berekurzáljon. Ha meg van adva <pathspec>, a -d irreleváns; a
	megadott elérési utakra illeszkedő összes nem követett fájl
	eltávolításra kerül (a `--force` alatt említett beágyazott git
	könyvtárak kivételével).

-f::
--force::
	Ha a clean.requireForce Git konfigurációs változó nincs false-ra
	állítva, a 'git clean' megtagadja a fájlok vagy könyvtárak törlését,
	hacsak nem kapja meg a -f kapcsolót. A Git megtagadja a nem követett
	beágyazott git repository-k (olyan könyvtárak, amelyekben van egy
	.git alkönyvtár) módosítását, hacsak nem kap egy második -f kapcsolót.

-i::
--interactive::
	Megmutatja, mi történne, és interaktívan tisztítja meg a fájlokat.
	A részletekért lásd: „Interaktív mód".
	A `clean.requireForce` konfigurációs változó figyelmen kívül marad,
	mivel ez a mód saját biztonsági védelmet nyújt azáltal, hogy
	interaktívvá válik.

-n::
--dry-run::
	Ne távolítson el ténylegesen semmit, csak mutassa meg, mi történne.
	A `clean.requireForce` konfigurációs változó figyelmen kívül marad,
	mivel úgysem törlődik semmi.

-q::
--quiet::
	Legyen csendes, csak a hibákat jelentse, de ne azokat a fájlokat,
	amelyek sikeresen eltávolításra kerültek.

-e <pattern>::
--exclude=<pattern>::
	A megadott kizárási mintát a szabványos figyelmen kívül hagyási
	szabályok mellett használja (lásd: linkgit:gitignore[5]).

-x::
	Ne használja a szabványos figyelmen kívül hagyási szabályokat (lásd:
	linkgit:gitignore[5]), de továbbra is használja a parancssorból `-e`
	opciókkal megadott figyelmen kívül hagyási szabályokat. Ez lehetővé
	teszi az összes nem követett fájl eltávolítását, beleértve a
	build-termékeket is. Ez használható (esetleg a 'git restore' vagy a
	'git reset' paranccsal együtt) egy tiszta munkakönyvtár létrehozására
	egy tiszta build teszteléséhez.

-X::
	Csak a Git által figyelmen kívül hagyott fájlokat távolítja el. Ez
	hasznos lehet, ha mindent a nulláról szeretnél újraépíteni, de meg
	akarod tartani a manuálisan létrehozott fájlokat.

Interaktív mód
--------------
Amikor a parancs belép az interaktív módba, megmutatja a
megtisztítandó fájlokat és könyvtárakat, majd belép az
interaktív parancshurokba.

A parancshurok megjeleníti az elérhető alparancsok listáját, és
egy "What now> " promptot ad. Általában, amikor a prompt egyetlen
'>' jellel végződik, csak az egyik felkínált lehetőséget
választhatod ki, és Entert nyomsz, így:

------------
    *** Commands ***
	1: clean                2: filter by pattern    3: select by numbers
	4: ask each             5: quit                 6: help
    What now> 1
------------

Azt is mondhatod, hogy `c` vagy `clean`, amíg a választás egyértelmű.

A fő parancshuroknak 6 alparancsa van.

clean::

   Elkezdi megtisztítani a fájlokat és könyvtárakat, majd kilép.

filter by pattern::

   Ez megmutatja a törlendő fájlokat és könyvtárakat, és kiad egy
   "Input ignore patterns>>" promptot. Szóközzel elválasztott mintákat
   adhatsz meg, hogy fájlokat és könyvtárakat kizárj a törlésből.
   Pl. a "*.c *.h" kizárja a ".c"-re és ".h"-ra végződő fájlokat a
   törlésből. Amikor elégedett vagy a szűrt eredménnyel, nyomj ENTER-t
   (üresen) a főmenübe való visszatéréshez.

select by numbers::

   Ez megmutatja a törlendő fájlokat és könyvtárakat, és kiad egy
   "Select items to delete>>" promptot. Amikor a prompt dupla '>>'
   jellel végződik, mint itt, több elemet is kiválaszthatsz,
   szóközzel vagy vesszővel összefűzve. Tartományokat is megadhatsz.
   Pl. a "2-5 7,9" a 2,3,4,5,7,9 elemeket választja ki a listából.
   Ha egy tartomány második száma el van hagyva, az összes hátralévő
   elem kiválasztásra kerül. Pl. a "7-" a 7,8,9 elemeket választja ki
   a listából. A '*' karakterrel mindent kiválaszthatsz. Szintén,
   amikor elégedett vagy a szűrt eredménnyel, nyomj ENTER-t (üresen)
   a főmenübe való visszatéréshez.

ask each::

  Ez elkezdi a tisztítást, és egyenként kell megerősítened az
  elemek törlését. Vedd figyelembe, hogy ez a művelet nem olyan
  hatékony, mint a fenti két művelet.

quit::

  Ez lehetővé teszi, hogy kilépj bármilyen tisztítás elvégzése nélkül.

help::

  Az interaktív git-clean rövid használati útmutatóját mutatja meg.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/clean.adoc[]

SEE ALSO
--------
linkgit:gitignore[5]

GIT
---
A linkgit:git[1] csomag része
