git-mailinfo(1)
===============

NAME
----
git-mailinfo - Patch és szerzőség kinyerése egyetlen e-mail-üzenetből


SYNOPSIS
--------
[verse]
'git mailinfo' [-k|-b] [-u | --encoding=<encoding> | -n]
	       [--[no-]scissors] [--quoted-cr=<action>]
	       <msg> <patch>


DESCRIPTION
-----------
Beolvas egyetlen e-mail-üzenetet a standard bemenetről, és a commit
napló-üzenetét a <msg> fájlba, a patcheket pedig a <patch> fájlba
írja.  A szerző neve, az e-mail és az e-mail tárgya a standard
kimenetre íródik, hogy a 'git am' felhasználja őket egy commit
létrehozásához.  Általában nem szükséges ezt a parancsot közvetlenül
használni.  Helyette lásd a linkgit:git-am[1]-et.


OPTIONS
-------
-k::
	A program általában eltávolítja az e-mail-szemetet a Subject:
	fejlécsorból, hogy kinyerje a commit napló-üzenetének címsorát.
	Ez az opció megakadályozza ezt az átalakítást, és leginkább akkor
	hasznos, ha a 'git format-patch -k' kimenetének visszaolvasására
	használják.
+
Konkrétan a következők kerülnek eltávolításra, amíg egy sem marad:
+
--
*	Kezdő és záró whitespace.

*	Kezdő `Re:`, `re:` és `:`.

*	Kezdő szögletes zárójeles karakterláncok (a `[` és `]` között,
	általában `[PATCH]`).
--
+
Végül a whitespace-sorozatok egyetlen ASCII szóköz karakterré
normalizálódnak.

-b::
	Ha a -k nincs érvényben, minden kezdő, '[' és ']' párokkal
	zárójelezett karakterlánc eltávolításra kerül.  Ez az opció az
	eltávolítást csak azokra a párokra korlátozza, amelyek zárójelezett
	karakterlánca tartalmazza a "PATCH" szót.

-u::
	A commit napló-üzenete, a szerző neve és a szerző e-mailje az
	e-mailből származik, és a MIME transfer encoding minimális
	dekódolása után az `i18n.commitEncoding` által megadott
	karakterkészletbe (alapértelmezés szerint UTF-8) kódolódnak át
	transzliterálással.  Ez korábban opcionális volt, most viszont ez
	az alapértelmezés.
+
Vedd figyelembe, hogy a patch mindig változatlanul,
karakterkészlet-konverzió nélkül kerül felhasználásra, még ezzel a
kapcsolóval is.

--encoding=<encoding>::
	Hasonló a -u-hoz.  De átkódoláskor az itt megadott
	karakterkészletet használja az `i18n.commitEncoding` vagy az UTF-8
	által megadott helyett.

-n::
	Letiltja a metaadatok minden karakterkészlet-átkódolását.

-m::
--message-id::
	A Message-ID fejléc másolása a commit-üzenet végére.  Ez hasznos
	ahhoz, hogy a commitokat levelezőlistás megbeszélésekhez lehessen
	társítani.

--scissors::
	Eltávolít mindent a törzsben egy ollóvonal (pl. "-- >8 --") előtt.
	A sor ollót és perforációs jeleket ábrázol, és arra szolgál, hogy
	arra kérje az olvasót, vágja el az üzenetet annál a sornál.  Ha ez
	a sor az üzenet törzsében a patch előtt jelenik meg, akkor ennek az
	opciónak a használatakor minden, ami előtte van (magát az
	ollóvonalat is beleértve), figyelmen kívül marad.
+
Ez akkor hasznos, ha egy megbeszélési szálban az üzenetedet azzal
szeretnéd kezdeni, hogy megjegyzéseket és javaslatokat írsz arra az
üzenetre, amelyre válaszolsz, és egy patch beküldésével szeretnéd
lezárni, elválasztva a megbeszélést és a javasolt commit
napló-üzenetének kezdetét egy ollóvonallal.
+
Ez alapértelmezés szerint bekapcsolható a mailinfo.scissors
konfigurációs opcióval.

--no-scissors::
	Figyelmen kívül hagyja az ollóvonalakat. Hasznos a
	mailinfo.scissors beállítások felülbírálásához.

--quoted-cr=<action>::
	Az a művelet, amelyet akkor hajt végre, amikor base64 vagy
	quoted-printable kódolással küldött e-mail-üzeneteket dolgoz fel, és
	a dekódolt sorok egyszerű LF helyett CRLF-fel végződnek.
+
Az érvényes műveletek:
+
--
*	`nowarn`: a Git nem tesz semmit, amikor ilyen CRLF-et talál.
*	`warn`: a Git minden üzenetnél figyelmeztetést ad, ha ilyen CRLF-et
	talál.
*	`strip`: a Git ezeket a CRLF-eket LF-re konvertálja.
--
+
Az alapértelmezett műveletet a `mailinfo.quotedCR` konfigurációs
opcióval lehet beállítani.  Ha nincs ilyen konfigurációs opció
beállítva, a `warn` lesz használatban.

<msg>::
	Az e-mailből kinyert commit napló-üzenet, általában a címsor
	kivételével, amely az e-mail tárgyából származik.

<patch>::
	Az e-mailből kinyert patch.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/mailinfo.adoc[]

GIT
---
A linkgit:git[1] csomag része
