git-name-rev(1)
===============

NAME
----
git-name-rev - Szimbolikus nevek keresése adott revíziókhoz


SYNOPSIS
--------
[verse]
'git name-rev' [--tags] [--refs=<pattern>]
	       ( --all | --annotate-stdin | <commit-ish>... )

DESCRIPTION
-----------
Ember számára emészthető szimbolikus neveket keres olyan revíziókhoz,
amelyek a 'git rev-parse' által elemezhető bármely formátumban meg
vannak adva.


OPTIONS
-------

--tags::
	Ne használjon branchneveket, csak tageket a commitok elnevezéséhez

--refs=<pattern>::
	Csak azokat a referenciákat használja, amelyek neve illeszkedik egy
	adott shell-mintára.  A minta lehet branchnév, tagnév vagy teljesen
	minősített referencianév. Ha többször van megadva, azokat a
	referenciákat használja, amelyek neve a megadott shell-minták
	bármelyikére illeszkedik. A `--no-refs` törli a korábban megadott
	referencia-mintákat.

--exclude=<pattern>::
	Ne használjon egyetlen olyan referenciát sem, amelynek neve
	illeszkedik egy adott shell-mintára. A minta lehet branchnév, tagnév
	vagy teljesen minősített referencianév. Ha többször van megadva, egy
	referencia kizárásra kerül, ha a megadott minták bármelyikére
	illeszkedik. A --refs opcióval együtt használva egy referencia csak
	akkor számít találatnak, ha legalább egy --refs mintára illeszkedik,
	és egyetlen --exclude mintára sem. A `--no-exclude` törli a kizárási
	minták listáját.

--all::
	Az összes referenciából elérhető összes commit listázása

--annotate-stdin::
	Átalakítja az stdin-t úgy, hogy az összes 40 karakteres SHA-1
	hexet (mondjuk $hex) a "$hex ($rev_name)" alakra cseréli.  A
	--name-only opcióval együtt használva a "$rev_name" alakra cseréli,
	teljesen elhagyva a $hex-et. Ezt az opciót a Git régebbi verzióiban
	`--stdin`-nek hívták.
+
Például:
+
-----------
$ cat sample.txt

An abbreviated revision 2ae0a9cb82 will not be substituted.
The full name after substitution is 2ae0a9cb8298185a94e5998086f380a355dd8907,
while its tree object is 70d105cc79e63b81cfdcb08a15297c23e60b07ad

$ git name-rev --annotate-stdin <sample.txt

An abbreviated revision 2ae0a9cb82 will not be substituted.
The full name after substitution is 2ae0a9cb8298185a94e5998086f380a355dd8907 (master),
while its tree object is 70d105cc79e63b81cfdcb08a15297c23e60b07ad

$ git name-rev --name-only --annotate-stdin <sample.txt

An abbreviated revision 2ae0a9cb82 will not be substituted.
The full name after substitution is master,
while its tree object is 70d105cc79e63b81cfdcb08a15297c23e60b07ad
-----------

--name-only::
	A SHA-1 és a név helyett csak a nevet írja ki.  A --tags opcióval
	együtt megadva a szokásos "tags/" tag-előtag is elmarad a névből,
	jobban megközelítve a `git-describe` kimenetét.

--no-undefined::
	Nem nulla hibakóddal lép ki, ha egy referencia nincs definiálva,
	az `undefined` kiírása helyett.

--always::
	Tartalék megoldásként egyedien rövidített commit-objektumot mutat.

EXAMPLES
--------

Adott egy commit, és szeretnéd megtudni, hol helyezkedik el a helyi
referenciákhoz képest. Tegyük fel, hogy valaki írt neked arról a
fantasztikus 33db5f4d9027a10e477ccf054b2c1ab94f74c85a commitról.
Természetesen belenézel a commitba, de az csak azt mondja meg, mi
történt, a kontextust nem.

Jöjjön a 'git name-rev':

------------
% git name-rev 33db5f4d9027a10e477ccf054b2c1ab94f74c85a
33db5f4d9027a10e477ccf054b2c1ab94f74c85a tags/v0.99~940
------------

Most már okosabb vagy, mert tudod, hogy ez 940 revízióval a v0.99 előtt
történt.

Egy másik hasznos dolog, amit tehetsz:

------------
% git log | git name-rev --annotate-stdin
------------

GIT
---
A linkgit:git[1] csomag része
