git-ls-tree(1)
==============

NAME
----
git-ls-tree - Egy tree objektum tartalmának listázása


SYNOPSIS
--------
[verse]
'git ls-tree' [-d] [-r] [-t] [-l] [-z]
	    [--name-only] [--name-status] [--object-only] [--full-name] [--full-tree] [--abbrev[=<n>]] [--format=<format>]
	    <tree-ish> [<path>...]

DESCRIPTION
-----------
Egy adott tree objektum tartalmának listázása, hasonlóan ahhoz, amit a
"/bin/ls -a" tesz az aktuális munkakönyvtárban.  Vedd figyelembe, hogy:

 - a viselkedés kissé eltér a "/bin/ls"-étől abban, hogy a '<path>' csak
   az illesztendő minták listáját jelöli, pl. így egy könyvtárnév megadása
   (a `-r` nélkül) másképp viselkedik, és az argumentumok sorrendje nem
   számít.

 - a viselkedés hasonló a "/bin/ls"-éhez abban, hogy a '<path>' az
   aktuális munkakönyvtárhoz képest értendő.  Pl. amikor egy 'sub'
   könyvtárban vagy, amelynek van egy 'dir' könyvtára, futtathatod a 'git
   ls-tree -r HEAD dir'-t a tree tartalmának listázásához (ez a
   `sub/dir` a `HEAD`-ben).  Ebben az esetben nem érdemes olyan tree-t
   megadni, amely nem a gyökérszinten van (pl. `git ls-tree -r HEAD:sub
   dir`), mert az a `sub/sub/dir` kérését eredményezné a `HEAD` commitban.
   Az aktuális munkakönyvtár azonban figyelmen kívül hagyható a
   --full-tree opció átadásával.

OPTIONS
-------
<tree-ish>::
	Egy tree-ish azonosítója.

-d::
	Csak magának a megnevezett tree-bejegyzésnek a megjelenítése, a gyermekeié nem.

-r::
	Rekurzió az al-tree-kbe.

-t::
	A tree-bejegyzések megjelenítése akkor is, amikor rekurzió lesz
	rajtuk. Nincs hatása, ha a `-r` nincs átadva. A `-d` maga után vonja
	a `-t`-t.

-l::
--long::
	A blob (fájl) bejegyzések objektumméretének megjelenítése.

-z::
	\0 sorlezárás a kimeneten, és a fájlnevek ne kerüljenek idézőjelbe.
	További információért l. lentebb a Kimeneti formátum szakaszt.

--name-only::
--name-status::
	Csak a fájlnevek listázása (a "long" kimenet helyett), soronként
	egyet. Nem kombinálható a `--object-only`-val.

--object-only::
	Csak az objektumok neveinek listázása, soronként egyet. Nem
	kombinálható a `--name-only`-val vagy a `--name-status`-szal.
	Ez egyenértékű a `--format='%(objectname)'` megadásával, de ehhez
	az opcióhoz és ehhez a pontos formátumhoz is a parancs egy kézzel
	optimalizált kódútvonalat használ ahelyett, hogy az általános
	formázási mechanizmuson menne keresztül.

--abbrev[=<n>]::
	A teljes, 40 bájtos hexadecimális objektum-sorok megjelenítése
	helyett a legrövidebb olyan előtag megjelenítése, amely legalább
	'<n>' hexadecimális számjegy hosszú, és egyértelműen az objektumra
	hivatkozik.
	A nem alapértelmezett számjegyszám a --abbrev=<n>-nel adható meg.

--full-name::
	Az útvonalnevek aktuális munkakönyvtárhoz képesti megjelenítése
	helyett a teljes útvonalnevek megjelenítése.

--full-tree::
	Ne korlátozza a listázást az aktuális munkakönyvtárra.
	Maga után vonja a --full-name-et.

--format=<format>::
	Egy karakterlánc, amely a megjelenített eredményből a
	`%(fieldname)`-t interpolálja. A `%%`-ot `%`-ra is interpolálja, a
	`%xNN`-t pedig – ahol az `NN` hexadecimális számjegyek – az `NN`
	hexkódú karakterre; például a `%x00` a `\0`-ra (NUL), a `%x09` a
	`\t`-re (TAB), a `%x0a` pedig a `\n`-re (LF) interpolálódik.
	Ha meg van adva, a `--format` nem kombinálható más
	formátummódosító opciókkal, beleértve a `--long`, `--name-only` és
	`--object-only` opciókat.

[<path>...]::
	Ha útvonalak vannak megadva, azok megjelenítése (vedd figyelembe,
	hogy ezek valójában nem nyers útvonalnevek, hanem inkább az
	illesztendő minták listája).  Egyébként implicit módon a tree
	gyökérszintjét használja az egyetlen útvonal-argumentumként.


[[_output_format]]
Kimeneti formátum
-----------------

Az `ls-tree` kimeneti formátumát vagy a `--format` opció, vagy más
formátummódosító opciók (mint a `--name-only` stb.) határozzák meg
(l. a `--format`-ot fentebb).

Bizonyos `--format` direktívák használata egyenértékű ezen opciók
használatával, de a teljes formázógépezet meghívása lassabb lehet, mint
egy megfelelő formázási opció használata.

Azokban az esetekben, amikor a `--format` pontosan egy meglévő opciónak
felelne meg, az `ls-tree` a megfelelő gyorsabb útvonalat használja. Így
az alapértelmezett formátum egyenértékű a következővel:

	%(objectmode) %(objecttype) %(objectname)%x09%(path)

Ez a kimeneti formátum kompatibilis azzal, amit a 'git update-index'
`--index-info --stdin`-je elvár.

Amikor a `-l` opció használatban van, a formátum a következőre változik:

	%(objectmode) %(objecttype) %(objectname) %(objectsize:padded)%x09%(path)

Az <objectname> által azonosított objektumméret bájtban van megadva, és
jobbra igazított, legalább 7 karakter szélességgel.  Az objektumméret
csak a blob (fájl) bejegyzésekhez van megadva; más bejegyzéseknél a `-`
karakter szerepel a méret helyén.

A `-z` opció nélkül a "szokatlan" karaktereket tartalmazó útvonalnevek
idézőjelbe kerülnek a `core.quotePath` konfigurációs változónál leírtak
szerint (l. linkgit:git-config[1]).  A `-z` használatával a fájlnév szó
szerint kerül a kimenetre, és a sort egy NUL bájt zárja.

Testreszabott formátum:

Egyéni formátumban is nyomtathatsz a `--format` opció használatával,
amely különböző mezőket tud interpolálni `%(fieldname)` jelöléssel.
Például, ha csak az "objectname" és a "path" mező érdekel, egy konkrét
"--format"-tal futtathatod, például:

	git ls-tree --format='%(objectname) %(path)' <tree-ish>

FIELD NAMES
-----------

Strukturált mezőkből származó különböző értékek használhatók az
eredményül kapott kimenetbe való interpolálásra. Minden kimeneti sorhoz
a következő nevek használhatók:

objectmode::
	Az objektum módja.
objecttype::
	Az objektum típusa (`commit`, `blob` vagy `tree`).
objectname::
	Az objektum neve.
objectsize[:padded]::
	Egy `blob` objektum mérete ("-", ha `commit` vagy `tree`).
	Támogatja a méret kitöltött formátumát is a "%(objectsize:padded)"-tel.
path::
	Az objektum útvonalneve.

GIT
---
A linkgit:git[1] csomag része
