git-gui(1)
==========

NAME
----
git-gui - Hordozható grafikus felület a Githez

SYNOPSIS
--------
[verse]
'git gui' [<command>] [<arguments>]

DESCRIPTION
-----------
Tcl/Tk alapú grafikus felhasználói felület a Githez.  A 'git gui' arra
összpontosít, hogy a felhasználók módosíthassák a repository-jukat új
commitok készítésével, meglévők amendelésével, branchek létrehozásával,
helyi merge-ek végrehajtásával, valamint remote repository-kba való
fetcheléssel/pusholással.

A 'gitk'-val ellentétben a 'git gui' a commitok létrehozására és
egyetlen fájl annotálására összpontosít, és nem mutatja a projekt
előzményeit. Menüműveleteket viszont biztosít ahhoz, hogy a 'git gui'-n
belülről 'gitk' munkamenetet indíthass.

A 'git gui'-ról ismert, hogy minden népszerű UNIX rendszeren, Mac OS
X-en és Windowson (Cygwin és MSYS alatt egyaránt) működik.  Amennyire
lehetséges, követi az operációs rendszerre jellemző felhasználói
felületi irányelveket, így a 'git gui' a felhasználók számára
meglehetősen natív felület.

COMMANDS
--------
blame::
	Blame-nézegetőt indít a megadott fájlon a megadott verzión (vagy a
	munkakönyvtáron, ha nincs megadva).

browser::
	Tree-böngészőt indít, amely a megadott commit összes fájlját
	megmutatja.  A böngészőn keresztül kiválasztott fájlok a
	blame-nézegetőben nyílnak meg.

citool::
	Elindítja a 'git gui'-t, és úgy állítja be, hogy pontosan egy
	commitot készítsen, mielőtt kilép és visszatér a shellbe.  A felület
	csak a commit-műveletekre korlátozódik, kissé csökkentve az alkalmazás
	indítási idejét és egyszerűsítve a menüsort.

version::
	Megjeleníti a 'git gui' jelenleg futó verzióját.


[[_examples]]
Példák
------
`git gui blame Makefile`::

	Megmutatja a 'Makefile' fájl tartalmát az aktuális munkakönyvtárban,
	és annotációt ad mind az egyes sorok eredeti szerzőjéről, mind arról,
	ki helyezte a sort a jelenlegi helyére.  A nem commitolt fájl
	annotálva van, és a nem commitolt módosítások (ha vannak) kifejezetten
	a 'Not Yet Committed' bejegyzéshez rendelődnek.

`git gui blame v0.99.8 Makefile`::

	Megmutatja a 'Makefile' tartalmát a 'v0.99.8' revízióban, és
	minden sorhoz annotációt ad.  A fenti példával ellentétben a fájl
	az objektumadatbázisból olvasódik be, nem a munkakönyvtárból.

`git gui blame --line=100 Makefile`::

	A fent leírtak szerint betölti az annotációkat, és automatikusan a
	'100'-as sorra görgeti a nézetet.

`git gui citool`::

	Készít egy commitot, és annak befejeztével visszatér a shellbe.
	Ez a parancs nem nulla kilépési kódot ad vissza, ha az ablakot
	nem commit készítésével zárták be.

`git gui citool --amend`::

	Automatikusan belép a felület 'Amend Last Commit' módjába.

`git gui citool --nocommit`::

	Úgy viselkedik, mint a normál citool, de commit készítése helyett
	egyszerűen nulla kilépési kóddal áll le. Továbbra is ellenőrzi, hogy
	az index nem tartalmaz-e nem merge-elt bejegyzéseket, így a
	linkgit:git-mergetool[1] GUI-verziójaként használható

`git citool`::

	Ugyanaz, mint a `git gui citool` (fent).

`git gui browser maint`::

	Böngészőt jelenít meg a 'maint' branch tree-jéhez.  A böngészőben
	kiválasztott fájlok a beépített blame-nézegetővel tekinthetők meg.

SEE ALSO
--------
linkgit:gitk[1]::
	A Git repository-böngésző.  Brancheket, commit-előzményeket és
	fájlkülönbségeket mutat.  A gitk az a segédprogram, amelyet a
	'git gui' Repository Visualize műveletei indítanak el.

[[_other]]
Egyéb
-----
A 'git gui'-t valójában önálló projektként karbantartják, de a stabil
verziókat a végfelhasználók kényelme érdekében a Git csomag részeként
terjesztik.

A 'git gui' projekt hivatalos repository-ja itt található:

  https://github.com/j6t/git-gui

GIT
---
A linkgit:git[1] csomag része
