git-rerere(1)
=============

NAME
----
git-rerere - Konfliktusos merge-ek rögzített feloldásának újrafelhasználása

SYNOPSIS
--------
[verse]
'git rerere' [clear | forget <pathspec>... | diff | status | remaining | gc]

DESCRIPTION
-----------

Egy viszonylag hosszú életű topic brancheket használó munkafolyamatban a
fejlesztőnek olykor újra és újra fel kell oldania ugyanazokat a
konfliktusokat, amíg a topic branchek el nem készülnek (vagy merge-elik őket
a "release" branchbe, vagy elküldik és upstream elfogadják).

Ez a parancs úgy segíti a fejlesztőt ebben a folyamatban, hogy az első kézi
merge-nél rögzíti a konfliktusos automerge-eredményeket és a hozzájuk tartozó
kézi feloldási eredményeket, majd a korábban rögzített kézi feloldásokat
alkalmazza a hozzájuk tartozó automerge-eredményekre.

[NOTE]
A parancs engedélyezéséhez be kell állítanod a `rerere.enabled` konfigurációs
változót.


COMMANDS
--------

Normál esetben a 'git rerere' argumentumok vagy felhasználói beavatkozás
nélkül fut. Van azonban több parancsa, amellyel a felhasználók
interakcióba léphetnek a munkaállapotával.

'clear'::

Visszaállítja a rerere által használt metaadatokat, ha egy merge-feloldást
meg kell szakítani.  A 'git am [--skip|--abort]' vagy a
'git rebase [--skip|--abort]' hívása automatikusan meghívja ezt a parancsot.

'forget' <pathspec>::

Visszaállítja azokat a konfliktusfeloldásokat, amelyeket a rerere a
<pathspec>-re illeszkedő elérési utakban lévő aktuális konfliktusokhoz
rögzített.

'diff'::

Megjeleníti a feloldás aktuális állapotának diffjeit.  Hasznos annak
nyomon követéséhez, mi változott, miközben a felhasználó feloldja a
konfliktusokat.  A további argumentumokat közvetlenül a PATH-ban telepített
rendszerbeli 'diff' parancsnak adja át.

'status'::

Kiírja azokat az elérési utakat, amelyekben olyan konfliktusok vannak,
amelyek merge-feloldását a rerere rögzíteni fogja.

'remaining'::

Kiírja azokat az elérési utakat, amelyekben lévő konfliktusokat a rerere
nem oldott fel automatikusan.  Ide tartoznak azok az elérési utak is,
amelyek feloldását a rerere nem tudja nyomon követni, például a konfliktusos
submodule-ok.

'gc'::

Kigyomlálja a rég történt konfliktusos merge-ek rekordjait.
Alapértelmezés szerint a 15 napnál régebbi feloldatlan konfliktusok és a 60
napnál régebbi feloldott konfliktusok kerülnek kigyomlálásra.  Ezeket az
alapértelmezéseket a `gc.rerereUnresolved`, illetve a `gc.rerereResolved`
konfigurációs változó szabályozza.


DISCUSSION
----------

Amikor a topic branched egy olyan átfedő területet módosít, amelyet a
master branched (vagy az upstream) is érintett azóta, hogy a topic branched
elágazott róla, érdemes lehet a legfrissebb masterrel tesztelned, még mielőtt
a topic branched készen állna az upstream pusholásra:

------------
              o---*---o topic
             /
    o---o---o---*---o---o master
------------

Egy ilyen teszthez valahogy merge-elned kell a mastert és a topicot.
Az egyik módja, hogy a mastert pull-olod a topic branchbe:

------------
	$ git switch topic
	$ git merge master

              o---*---o---+ topic
             /           /
    o---o---o---*---o---o master
------------

A `*`-gal jelölt commitok ugyanazt a területet érintik ugyanabban a
fájlban; a `+`-szal jelölt commit létrehozásakor fel kell oldanod a
konfliktusokat.  Ezután tesztelheted az eredményt, hogy megbizonyosodj róla,
a folyamatban lévő munkád továbbra is működik azzal, ami a legfrissebb
masterben van.

E teszt-merge után kétféleképpen folytathatod a munkádat a topicon.  A
legegyszerűbb a `+` teszt-merge commit tetejére építeni, és amikor a topic
branchbeli munkád végre készen áll, a topic branchet a masterbe pull-olod,
és/vagy megkéred az upstreamet, hogy pull-oljon tőled.  Addigra azonban a
master vagy az upstream továbbléphetett a `+` teszt-merge óta, amely esetben
a végső commit-gráf így nézne ki:

------------
	$ git switch topic
	$ git merge master
	$ ... work on both topic and master branches
	$ git switch master
	$ git merge topic

              o---*---o---+---o---o topic
             /           /         \
    o---o---o---*---o---o---o---o---+ master
------------

Ha viszont a topic branched hosszú életű, a topic branched végül sok ilyen
"Merge from master" commitot halmozna fel, ami feleslegesen zsúfolná tele a
fejlesztési előzményt.  A Linux kernel levelezőlista olvasói emlékezhetnek
rá, hogy Linus panaszkodott az ilyen túl gyakori teszt-merge-ekre, amikor
egy alrendszer-maintainer egy "useless merge"-ekkel teli branchből kért
pull-t.

Alternatívaként, hogy a topic branchet tisztán tartsd a teszt-merge-ektől,
eltüntetheted a teszt-merge-et, és tovább építkezhetsz a teszt-merge előtti
csúcs tetején:

------------
	$ git switch topic
	$ git merge master
	$ git reset --hard HEAD^ ;# rewind the test merge
	$ ... work on both topic and master branches
	$ git switch master
	$ git merge topic

              o---*---o-------o---o topic
             /                     \
    o---o---o---*---o---o---o---o---+ master
------------

Ez csak egyetlen merge-commitot hagyna hátra, amikor a topic branched végre
készen áll, és merge-elik a master branchbe.  Ez a merge megkövetelné, hogy
feloldd a `*`-gal jelölt commitok által bevezetett konfliktust.  Ez a
konfliktus azonban gyakran ugyanaz a konfliktus, amelyet az eltüntetett
teszt-merge létrehozásakor oldottál fel.  A 'git rerere' segít feloldani ezt
a végső konfliktusos merge-et a korábbi kézi feloldásból származó információ
felhasználásával.

A 'git rerere' parancs futtatása közvetlenül egy konfliktusos automerge után
rögzíti a konfliktusos munkakönyvtárbeli fájlokat, a bennük lévő szokásos
`<<<<<<<`, `=======` és `>>>>>>>` konfliktusjelölőkkel együtt.  Később,
miután befejezted a konfliktusok feloldását, a 'git rerere' ismételt
futtatása rögzíti e fájlok feloldott állapotát.  Tegyük fel, hogy ezt akkor
tetted meg, amikor létrehoztad a master topic branchbe való teszt-merge-ét.

Legközelebb, miután ugyanazt a konfliktusos automerge-et látod, a
'git rerere' futtatása háromutas merge-et hajt végre a korábbi konfliktusos
automerge, a korábbi kézi feloldás és a jelenlegi konfliktusos automerge
között.
Ha ez a háromutas merge tisztán feloldódik, az eredmény a munkakönyvtárbeli
fájlodba íródik, így nem kell kézzel feloldanod.  Vedd figyelembe, hogy a
'git rerere' az indexfájlt érintetlenül hagyja, így továbbra is neked kell
elvégezned a végső épségvizsgálatokat a `git diff`-fel (vagy a
`git diff -c`-vel) és a 'git add'-del, amikor elégedett vagy.

Kényelmi okokból a 'git merge' automatikusan meghívja a 'git rerere'-t,
amikor sikertelen automerge-dzsel lép ki, és a 'git rerere' rögzíti a kézi
feloldást, ha új konfliktusról van szó, vagy újrafelhasználja a korábbi kézi
feloldást, ha nem.  A 'git commit' szintén meghívja a 'git rerere'-t egy
merge-eredmény commitolásakor.  Ez azt jelenti, hogy neked magadnak semmi
különöset nem kell tenned (azon kívül, hogy engedélyezed a rerere.enabled
konfigurációs változót).

A példánkban, amikor elvégzed a teszt-merge-et, a kézi feloldás rögzül, és
újrafelhasználódik, amikor később elvégzed a tényleges merge-et a frissített
master és topic branchcsel, feltéve, hogy a rögzített feloldás még
alkalmazható.

A 'git rerere' által rögzített információt a 'git rebase' futtatásakor is
felhasználja.  A teszt-merge eltüntetése és a topic branchen való fejlesztés
folytatása után:

------------
              o---*---o-------o---o topic
             /
    o---o---o---*---o---o---o---o   master

	$ git rebase master topic

				  o---*---o-------o---o topic
				 /
    o---o---o---*---o---o---o---o   master
------------

futtathatnád a `git rebase master topic`-ot, hogy naprakész legyél, mielőtt a
topicod készen áll az upstreamre küldésre.  Ez háromutas merge-re való
visszaeséshez vezetne, és ugyanúgy konfliktusba kerülne, mint a korábban
feloldott teszt-merge.  A 'git rerere'-t a 'git rebase' fogja futtatni, hogy
segítsen feloldani ezt a konfliktust.

[NOTE] A 'git rerere' a fájlban lévő konfliktusjelölőkre támaszkodik a
konfliktus észleléséhez.  Ha a fájl már tartalmaz olyan sorokat, amelyek
ugyanúgy néznek ki, mint a konfliktusjelölőket tartalmazó sorok, a
'git rerere' nem biztos, hogy rögzíteni tudja a konfliktusfeloldást.  Ennek
megkerülésére a linkgit:gitattributes[5]-beli `conflict-marker-size`
beállítás használható.

GIT
---
A linkgit:git[1] csomag része
