git-show-ref(1)
===============

NAME
----
git-show-ref - Referenciák listázása egy helyi repository-ban

SYNOPSIS
--------
[verse]
'git show-ref' [--head] [-d | --dereference]
	     [-s | --hash[=<n>]] [--abbrev[=<n>]] [--branches] [--tags]
	     [--] [<pattern>...]
'git show-ref' --verify [-q | --quiet] [-d | --dereference]
	     [-s | --hash[=<n>]] [--abbrev[=<n>]]
	     [--] [<ref>...]
'git show-ref' --exclude-existing[=<pattern>]
'git show-ref' --exists <ref>

DESCRIPTION
-----------

Megjeleníti egy helyi repository-ban elérhető referenciákat a hozzájuk
tartozó commit-azonosítókkal együtt. Az eredmények mintával szűrhetők, a
tagek pedig objektumazonosítókká oldhatók fel. Ezenfelül használható
annak vizsgálatára, hogy egy adott ref létezik-e.

Alapból a tageket, a fejeket és a remote refeket jeleníti meg.

Az `--exclude-existing` alak egy szűrő, amely az ellenkezőjét teszi. A
stdinről olvas refeket, soronként egyet, és azokat jeleníti meg, amelyek
nem léteznek a helyi repository-ban.

Az `--exists` alak egyetlen referencia létezésének ellenőrzésére
használható. Ez az alak nem ellenőrzi, hogy a referencia egy tényleges
objektumra oldódik-e fel.

Ennek a segédeszköznek a használata ajánlott a `.git` könyvtár alatti
fájlok közvetlen elérésével szemben.

OPTIONS
-------

--head::

	A HEAD referencia megjelenítése, még akkor is, ha normál esetben kiszűrődne.

--branches::
--tags::

	Korlátozás a helyi branchekre, illetve a helyi tagekre.  Ezek az
	opciók nem zárják ki egymást; mindkettő megadásakor a "refs/heads"
	és a "refs/tags" alatt tárolt referenciák jelennek meg.  Vedd
	figyelembe, hogy a `--heads` a `--branches` elavult szinonimája, és
	a jövőben eltávolításra kerülhet.

-d::
--dereference::

	A tagek objektumazonosítókká való feloldása is. `^{}` végződéssel
	jelennek meg.

-s::
--hash[=<n>]::

	Csak az OID-t jeleníti meg, a referencia nevét nem. A
	`--dereference`-szel kombinálva a feloldott tag továbbra is
	megjelenik az OID után.

--verify::

	Szigorúbb referenciaellenőrzés bekapcsolása pontos ref-útvonal
	megkövetelésével.  Az 1-es hibakód visszaadásán túl hibaüzenetet is
	kiír, ha a `--quiet` nem volt megadva.

--exists::

	Ellenőrzi, hogy a megadott referencia létezik-e. 0 kilépési kódot ad
	vissza, ha igen, 2-t, ha hiányzik, és 1-et, ha a referencia
	kikeresése a referencia hiányától eltérő hibával meghiúsult.

--abbrev[=<n>]::

	Az objektumnév rövidítése.  A `--hash` használatakor nem kell
	`--hash --abbrev`-et mondanod; a `--hash=n` is megteszi.

-q::
--quiet::

	Ne írjon eredményt a stdoutra. Használható a `--verify`-jal egy
	referencia létezésének csendes ellenőrzésére.

--exclude-existing[=<pattern>]::

	A `git show-ref` szűrőként való működése, amely a stdinről
	`^(?:<anything>\s)?<refname>(?:\^{})?$` alakú refeket olvas,
	és mindegyiken a következő műveleteket végzi:
	(1) levágja a `^{}`-t a sor végéről, ha van;
	(2) figyelmen kívül hagyja, ha meg van adva minta, és az nem
	illeszkedik elölről a refname-re;
	(3) figyelmeztet, ha a refname nem jól formált refname, és kihagyja;
	(4) figyelmen kívül hagyja, ha a refname a helyi repository-ban létező ref;
	(5) egyébként kiírja a sort.


<pattern>...::

	Egy vagy több mintára illeszkedő referenciák megjelenítése. A minták
	a teljes név végétől illeszkednek, és csak teljes részek illeszkednek,
	pl. a 'master' illeszkedik a 'refs/heads/master',
	'refs/remotes/origin/master', 'refs/tags/jedi/master' nevekre, de nem
	a 'refs/heads/mymaster' vagy 'refs/remotes/master/jedi' nevekre.

OUTPUT
------

A kimenet formátuma:

------------
<oid> SP <ref> LF
------------

Például,

-----------------------------------------------------------------------------
$ git show-ref --head --dereference
832e76a9899f560a90ffd62ae2ce83bbeff58f54 HEAD
832e76a9899f560a90ffd62ae2ce83bbeff58f54 refs/heads/master
832e76a9899f560a90ffd62ae2ce83bbeff58f54 refs/heads/origin
3521017556c5de4159da4615a39fa4d5d2c279b5 refs/tags/v0.99.9c
6ddc0964034342519a87fe013781abf31c6db6ad refs/tags/v0.99.9c^{}
055e4ae3ae6eb344cbabf2a5256a49ea66040131 refs/tags/v1.0rc4
423325a2d24638ddcc82ce47be5e40be550f4507 refs/tags/v1.0rc4^{}
...
-----------------------------------------------------------------------------

A `--hash` használatakor (és nem a `--dereference`-szel) a kimenet formátuma:

------------
<oid> LF
------------

Például,

-----------------------------------------------------------------------------
$ git show-ref --branches --hash
2e3ba0114a1f52b47df29743d6915d056be13278
185008ae97960c8d551adcd9e23565194651b5d1
03adf42c988195b50e1a1935ba5fcbc39b2b029b
...
-----------------------------------------------------------------------------

EXAMPLES
--------

Az összes "master" nevű referencia megjelenítéséhez, legyenek azok tagek,
fejek vagy bármi más, és attól függetlenül, hogy milyen mélyen vannak a
referencia-elnevezési hierarchiában, használd:

-----------------------------------------------------------------------------
	git show-ref master
-----------------------------------------------------------------------------

Ez megjeleníti a "refs/heads/master"-t, de a
"refs/remote/other-repo/master"-t is, ha ilyen referenciák léteznek.

A `--verify` kapcsoló használatakor a parancs pontos útvonalat követel:

-----------------------------------------------------------------------------
	git show-ref --verify refs/heads/master
-----------------------------------------------------------------------------

csak a pontosan "master" nevű branchre fog illeszkedni.

Ha semmi sem illeszkedik, a `git show-ref` 1-es hibakódot ad vissza,
ellenőrzés esetén pedig hibaüzenetet jelenít meg.

Szkripteléshez megkérheted, hogy csendes legyen a `--quiet` kapcsolóval,
ami lehetővé teszi az ilyesmit:

-----------------------------------------------------------------------------
	git show-ref --quiet --verify -- "refs/heads/$headname" ||
		echo "$headname is not a valid branch"
-----------------------------------------------------------------------------

annak ellenőrzésére, hogy egy adott branch létezik-e vagy sem (figyeld
meg, hogy valójában nem akarunk eredményt megjeleníteni, és a teljes
refname-et akarjuk használni hozzá, hogy ne váltsuk ki a kétértelmű
részleges illeszkedések problémáját).

Csak a tagek, vagy csak a valódi branch-fejek megjelenítéséhez használd a
`--tags`, illetve a `--branches` opciót (mindkettő használata azt
jelenti, hogy tageket és brancheket jelenít meg, de a refs/
alkönyvtár alatti más, véletlenszerű referenciákat nem).

Automatikus tagobjektum-feloldáshoz használd a `-d` vagy `--dereference`
kapcsolót, így ezt teheted:

-----------------------------------------------------------------------------
	git show-ref --tags --dereference
-----------------------------------------------------------------------------

hogy megkapd az összes tag listáját azzal együtt, amire feloldódnak.

FILES
-----
`.git/refs/*`, `.git/packed-refs`

SEE ALSO
--------
linkgit:git-for-each-ref[1],
linkgit:git-ls-remote[1],
linkgit:git-update-ref[1],
linkgit:gitrepository-layout[5]

GIT
---
A linkgit:git[1] csomag része
