git-mailsplit(1)
================

NAME
----
git-mailsplit - Egyszerű UNIX mbox-felbontó program

SYNOPSIS
--------
[verse]
'git mailsplit' [-b] [-f<nn>] [-d<prec>] [--keep-cr] [--mboxrd]
		-o<directory> [--] [(<mbox>|<Maildir>)...]

DESCRIPTION
-----------
Egy mbox fájlt vagy egy Maildirt fájlok listájára bont: "0001" "0002"
.. a megadott könyvtárban, hogy onnan tovább tudd feldolgozni őket.

IMPORTANT: A Maildir-felbontás a fájlnevek rendezettségére támaszkodik,
hogy a patcheket a helyes sorrendben adja ki.

OPTIONS
-------
<mbox>::
	A felbontandó mbox fájl. Ha nincs megadva, az mbox a standard
	bemenetről kerül beolvasásra.

<Maildir>::
	A felbontandó Maildir gyökere. Ennek a könyvtárnak tartalmaznia
	kell a cur, tmp és new alkönyvtárakat.

-o<directory>::
	Az a könyvtár, amelybe az egyes üzeneteket helyezi.

-b::
	Ha egy fájl nem From sorral kezdődik, hiba jelzése helyett
	feltételezi, hogy egyetlen levélüzenetről van szó.

-d<prec>::
	Az alapértelmezett, vezető nullákkal ellátott 4 számjegy helyett
	eltérő pontosság adható meg a generált fájlnevekhez.

-f<nn>::
	Kihagyja az első <nn> számot, például ha az -f3 van megadva, a
	számozás 0004-gyel kezdődik.

--keep-cr::
	Nem távolítja el a `\r`-t a `\r\n`-nel végződő sorokból.

--mboxrd::
	A bemenet "mboxrd" formátumú, és a "^>+From " sor-escapelés
	fordítva van.

GIT
---
A linkgit:git[1] csomag része
