git-cvsimport(1)
================

NAME
----
git-cvsimport - Mentsd ki az adataidat egy másik, mindenki által gyűlölt SCM-ből


SYNOPSIS
--------
[verse]
'git cvsimport' [-o <branch-for-HEAD>] [-h] [-v] [-d <CVSROOT>]
	      [-A <author-conv-file>] [-p <options-for-cvsps>] [-P <file>]
	      [-C <git-repository>] [-z <fuzz>] [-i] [-k] [-u] [-s <subst>]
	      [-a] [-m] [-M <regex>] [-S <regex>] [-L <commit-limit>]
	      [-r <remote>] [-R] [<CVS-module>]


DESCRIPTION
-----------
*WARNING:* a `git cvsimport` a cvsps 2-es verzióját használja, amely
elavultnak számít; nem működik a cvsps 3-as és későbbi verzióival. Ha
egy CVS repository egyszeri importálását végzed, fontold meg a
http://cvs2svn.tigris.org/cvs2git.html[cvs2git] vagy a
https://gitlab.com/esr/cvs-fast-export[cvs-fast-export] használatát.

Egy CVS repository-t importál a Gitbe. Vagy egy új repository-t hoz
létre, vagy fokozatosan importál egy meglévőbe.

A CVS log patch-halmazokra bontását a 'cvsps' végzi. Legalább a 2.1-es
verzió szükséges.

*WARNING:* bizonyos helyzetekben az importálás helytelen eredményekre
vezet. További információért lásd a <<issues,ISMERT PROBLÉMÁK>> szakaszt.

*Sohase* végezz saját munkát a 'git cvsimport' által létrehozott
branch-eken. Alapértelmezés szerint a kezdeti importálás létrehoz és
feltölt egy "master" branch-et a CVS repository fő branch-éből,
amellyel szabadon dolgozhatsz; ezután a fokozatos importálásokat, vagy
bármely CVS branch-et, neked kell 'git merge'-elned. Ajánlott egy
elnevezett remote megadása a -r kapcsolóval, hogy elkülönítsd és
megvédd a bejövő branch-eket.

Ha egy megosztott, nyilvános repository-t szeretnél létrehozni,
amelyet minden fejlesztő olvashat/írhat, vagy ha a
linkgit:git-cvsserver[1] parancsot szeretnéd használni, akkor
valószínűleg egy bare klónt szeretnél készíteni az importált
repository-ból, és azt a klónt használni megosztott repository-ként.
Lásd a linkgit:gitcvs-migration[7] leírást.


OPTIONS
-------
-v::
	Bőbeszédűség: a 'cvsimport' jelentse, mit csinál éppen.

-d <CVSROOT>::
	A CVS archívum gyökere. Lehet helyi (egyszerű útvonal) vagy
	remote; jelenleg csak a :local:, :ext: és :pserver: elérési
	módok támogatottak. Ha nincs megadva, a 'git cvsimport'
	megpróbálja beolvasni a `CVS/Root` fájlból. Ha nem létezik ilyen
	fájl, a `CVSROOT` környezeti változót ellenőrzi.

<CVS-module>::
	A CVS modul, amelyet importálni szeretnél. A <CVSROOT>-hoz
	viszonyítva. Ha nincs megadva, a 'git cvsimport' megpróbálja
	beolvasni a `CVS/Repository` fájlból.

-C <target-dir>::
	A Git repository, amelybe importálni kell. Ha a könyvtár nem
        létezik, létrejön. Alapértelmezés az aktuális könyvtár.

-r <remote>::
	A Git remote, amelybe ezt a CVS repository-t importálni kell.
	Az összes CVS branch-et átmozgatja a remotes/<remote>/<branch>
	helyre, hasonlóan ahhoz, ahogy a 'git clone' alapértelmezetten
	az 'origin' nevet használja.

-o <branch-for-HEAD>::
	Ha nincs remote megadva (a -r kapcsolóval), a CVS `HEAD` branch-e
	az 'origin' branch-be kerül importálásra a Git repository-n
	belül, mivel a `HEAD`-nek már különleges jelentése van a Git
	számára. Ha meg van adva egy remote, a `HEAD` branch a
	remotes/<remote>/master nevet kapja, a 'git clone' viselkedését
	tükrözve. Használd ezt az opciót, ha egy másik branch-be
	szeretnél importálni.
+
Használd a '-o master' opciót egy olyan importálás folytatásához,
amelyet eredetileg a régi cvs2git eszközzel végeztek.

-i::
	Csak importálás: ne végezzen checkoutot az importálás után. Ez
	az opció biztosítja, hogy a munkakönyvtár és az index
	érintetlenek maradjanak, és nem hozza létre őket, ha még nem
	léteznek.

-k::
	Kulcsszavak kiölése: '-kk' kapcsolóval fogja kinyerni a fájlokat
	a CVS archívumból, hogy elkerülje a zajos changeseteket. Erősen
	ajánlott, de alapértelmezetten ki van kapcsolva, hogy megőrizze
	a kompatibilitást a korábban importált fákkal.

-u::
	Az aláhúzásjeleket pontokra alakítja a tag- és branch-nevekben.

-s <subst>::
	A "/" karakter helyettesítése <subst>-tel a branch-nevekben.

-p <options-for-cvsps>::
	További opciók a cvsps számára.
	A `-u` és '-A' opciók implicitek, és itt nem szabad használni őket.
+
Ha több opciót kell átadnod, vesszővel válaszd el őket.

-z <fuzz>::
	Átadja az időbélyeg-tűrési tényezőt a cvsps-nek, másodpercben.
	Ha nincs beállítva, a cvsps alapértelmezetten 300s-ot használ.

-P <cvsps-output-file>::
	A cvsps meghívása helyett a megadott cvsps-kimenetfájlt olvassa
	be. Hasznos hibakereséshez, vagy amikor a cvsps-t a cvsimporton
	kívül kezelik.

-m::
	Megpróbálja felismerni a merge-eket a commit-üzenet alapján. Ez
	az opció bekapcsolja az alapértelmezett reguláris kifejezéseket,
	amelyek megpróbálják kinyerni a forrás branch nevét a
	commit-üzenetből.

-M <regex>::
	Megpróbálja felismerni a merge-eket a commit-üzenet alapján,
	egy egyéni reguláris kifejezéssel. A `-m` kapcsolóval együtt is
	használható, hogy az alapértelmezett reguláris kifejezések is
	bekapcsolódjanak. A perjeleket escape-elned kell.
+
A reguláris kifejezésnek a $1-ben kell befognia a forrás branch nevét.
+
Ez az opció többször is használható, hogy több felismerő reguláris
kifejezést adj meg.

-S <regex>::
	Kihagyja a reguláris kifejezésre illeszkedő útvonalakat.

-a::
	Minden commitot importál, a legutóbbiakat is beleértve. A
	cvsimport alapértelmezetten kihagyja azokat a commitokat,
	amelyek időbélyege kevesebb, mint 10 perccel ezelőtti.

-L <limit>::
	Korlátozza az importált commitok számát. Megoldás azokra az
	esetekre, amikor a cvsimport memóriát szivárogtat.

-A <author-conv-file>::
	A CVS alapértelmezetten a Unix felhasználónevet használja a
	commit-naplói írásakor. Ennek az opciónak és egy
	author-conv-file-nak a használatával a CVS-ben rögzített nevet
	szerzői névre, e-mail-re és opcionális időzónára képezheted le:
+
---------
	exon=Andreas Ericsson <ae@op5.se>
	spawn=Simon Pawn <spawn@frog-pond.org> America/Chicago

---------
+
A 'git cvsimport' úgy fogja feltüntetni, mintha ezeknek a szerzőknek
mindvégig helyesen be lett volna állítva a GIT_AUTHOR_NAME és
GIT_AUTHOR_EMAIL értéke. Ha meg van adva időzóna, a GIT_AUTHOR_DATE
a megfelelő eltolással kerül alkalmazásra.
+
Kényelmi okokból ez az adat elmentésre kerül a `$GIT_DIR/cvs-authors`
fájlba minden alkalommal, amikor a '-A' opció meg van adva, és
ugyanabból a fájlból kerül beolvasásra minden alkalommal, amikor a
'git cvsimport' fut.
+
Nem ajánlott ezt a funkciót használni, ha később a változtatásokat
vissza szeretnéd exportálni a CVS-be a 'git cvsexportcommit'
paranccsal.

-R::
	Létrehoz egy `$GIT_DIR/cvs-revisions` fájlt, amely a CVS
	revíziószámok és az újonnan létrehozott Git commit-azonosítók
	közötti leképezést tartalmazza. A létrehozott fájl minden
	importált (fájlnév, revízió) párhoz egy sort fog tartalmazni;
	minden sor így fog kinézni:
+
---------
src/widget.c 1.1 1d862f173cdc7325b6fa6d2ae1cfd61fd1b512b7
---------
+
A revízióadat hozzáfűzésre kerül a fájlhoz, ha az már létezik,
fokozatos importáláskor való felhasználásra.
+
Ez az opció akkor lehet hasznos, ha CVS revíziószámokat tárolsz
commit-üzenetekben, hibakövető rendszerekben, e-mail archívumokban és
hasonlókban.

-h::
	Rövid használati útmutató kiírása és kilépés.

KIMENET
-------
Ha a `-v` opció meg van adva, a szkript jelenti, mit csinál.

Egyébként a sikert Unix-módra jelzi, azaz egyszerűen nulla
kilépési státusszal lép ki.

[[issues]]
ISMERT PROBLÉMÁK
----------------
Az időbélyegekkel kapcsolatos problémák:

 * Ha a CVS repository-ban lévő commitok időbélyegei nem elég
   stabilak ahhoz, hogy a változtatások sorrendjének
   meghatározására használhatók legyenek, a változtatások rossz
   sorrendben jelenhetnek meg.
 * Ha bármely fájlt valaha egynél többször "cvs import"-áltak
   (pl. egynél több beszállítói kiadás importálásakor), a HEAD
   helytelen tartalmat tartalmaz.
 * Ha a különböző fájlok időbélyeg-sorrendje keresztezi a
   revízió-sorrendet a commit-illesztési időablakon belül, a
   commitok sorrendje helytelen lehet.

A branch-ekkel kapcsolatos problémák:

 * Azok a branch-ek, amelyeken nem történt commit, nem kerülnek
   importálásra.
 * A branch-elési pontról az összes fájl hozzáadásra kerül egy
   branch-hez, még akkor is, ha az soha nem lett hozzáadva a CVS-ben.
 * Ez azokra a fájlokra vonatkozik, amelyeket egy leány branch
   létrehozása *után* adtak hozzá a forrás branch-hez: ha korábban
   nem történt commit a leány branch-en, ezek tévesen hozzá lesznek
   adva a leány branch-hez a gitben.

A tag-ekkel kapcsolatos problémák:

* Ugyanazon a revízión lévő több tag nem kerül importálásra.

Ha úgy gondolod, hogy ezen problémák bármelyike érintheti az
importálni kívánt repository-t, fontold meg a cvs2git használatát:

* cvs2git (a cvs2svn része), `https://subversion.apache.org/`

GIT
---
A linkgit:git[1] csomag része
