git-commit-graph(1)
===================

NAME
----
git-commit-graph - Git commit-graph fájlok írása és ellenőrzése


SYNOPSIS
--------
[verse]
'git commit-graph verify' [--object-dir <dir>] [--shallow] [--[no-]progress]
'git commit-graph write' [--object-dir <dir>] [--append]
			[--split[=<strategy>]] [--reachable | --stdin-packs | --stdin-commits]
			[--changed-paths] [--[no-]max-new-filters <n>] [--[no-]progress]
			<split-options>


DESCRIPTION
-----------

A szerializált commit-graph fájl kezelése.


OPTIONS
-------
--object-dir::
	A megadott könyvtár használata a packfile-ok és a commit-graph fájl
	helyeként. Ez a paraméter egy olyan alternate helyének megadására
	szolgál, amelynek csak objects könyvtára van, nem teljes `.git`
	könyvtára. A commit-graph fájlnak a `<dir>/info` könyvtárban kell
	lennie, a packfile-oknak pedig a `<dir>/pack` könyvtárban. Ha a
	könyvtárból nem képezhető abszolút útvonal, vagy nem egyezik egyetlen
	ismert objektumkönyvtárral sem, a `git commit-graph ...` nem nulla
	státusszal lép ki.

--progress::
--no-progress::
	A folyamatjelzés explicit be- vagy kikapcsolása. Ha egyik sincs
	megadva, a folyamatjelzés akkor jelenik meg, ha a standard hiba
	terminálhoz csatlakozik.

COMMANDS
--------
'write'::

Commit-graph fájl írása a packfile-okban talált commitok alapján. Ha a
`core.commitGraph` config-opció le van tiltva, ez a parancs figyelmeztetést
ír ki, majd sikeresen tér vissza a commit-graph fájl megírása nélkül.
+
A `--stdin-packs` opcióval az új commit gráf úgy jön létre, hogy csak a
megadott pack-indexekben lévő objektumokat járjuk be. (Nem kombinálható a
`--stdin-commits` vagy a `--reachable` opcióval.)
+
A `--stdin-commits` opcióval az új commit gráf úgy jön létre, hogy a bejárás
a standard bemeneten megadott commitoktól indul, OID-ok hexadecimális
listájaként, soronként egy OID-dal. Azok az OID-ok, amelyek nem commitra
oldódnak fel (akár közvetlenül, akár tagek lehántásával), csendben
figyelmen kívül maradnak. A hibásan formázott vagy nem létező OID-ok hibát
generálnak. (Nem kombinálható a `--stdin-packs` vagy a `--reachable`
opcióval.)
+
A `--reachable` opcióval az új commit gráf úgy jön létre, hogy a bejárás az
összes reftől indul. (Nem kombinálható a `--stdin-commits` vagy a
`--stdin-packs` opcióval.)
+
A `--append` opcióval a meglévő commit-graph fájlban jelen lévő összes
commit bekerül.
+
A `--changed-paths` opcióval a commit és az első szülője közötti
megváltozott elérési utakról számítunk és írunk információt. Ez a művelet
nagy repository-kban eltarthat egy ideig. Jelentős teljesítménynövekedést
biztosít egy könyvtár vagy fájl előzményeinek lekérésekor a
`git log -- <path>` használatával. Ha ez az opció meg van adva, a jövőbeli
commit-graph írások automatikusan feltételezik, hogy ez az opció szándékos
volt. Használd a `--no-changed-paths` opciót ezen adatok tárolásának
leállításához. A `--changed-paths` opciót a `commitGraph.changedPaths=true`
config beállítás implicit módon bekapcsolja.
+
A `--max-new-filters=<n>` opcióval legfeljebb `n` új Bloom filter jön
létre (ha a `--changed-paths` meg van adva). Ha `n` értéke `-1`, nincs
korlát érvényben. Csak az új rétegben jelen lévő commitok számítanak bele
ebbe a korlátba. A korábbi rétegek Bloom filtereinek utólagos
kiszámításához a `--split=replace` használata ajánlott. Felülírja a
`commitGraph.maxNewFilters` konfigurációt.
+
A `--split[=<strategy>]` opcióval a commit-graph több, a
`<dir>/info/commit-graphs` helyen tárolt commit-graph fájl láncaként
íródik. A commit-graph rétegek a stratégia és az egyéb felosztási opciók
alapján kerülnek összevonásra. A commit-graphban még nem szereplő új
commitok egy új „tip" fájlba kerülnek. Ez a fájl összevonásra kerül a
meglévő fájllal, ha a következő összevonási feltételek teljesülnek:
+
* Ha a `--split=no-merge` van megadva, összevonás soha nem történik, és a
többi opció figyelmen kívül marad. A `--split=replace` felülírja a meglévő
láncot egy újjal. Az önmagában megadott `--split` a többi opcióra
hagyatkozik. (Vedd figyelembe, hogy a commit gráfok láncának összevonása a
meglévő láncot egy 1 hosszúságú láncra cseréli, amelyben az egyetlen
inkrementális réteg tartalmazza a teljes gráfot.)
+
* Ha a `--size-multiple=<X>` nincs megadva, legyen `X` értéke 2. Ha az új
tip fájlnak `N` commitja lenne, az előző tipnek pedig `M` commitja van, és
`X`-szer `N` nagyobb, mint `M`, akkor a két fájl egyetlen fájlba lesz
összevonva.
+
* Ha a `--max-commits=<M>` van megadva `M` pozitív egész értékkel, és az új
tip fájlnak `M`-nél több commitja lenne, akkor az új tip az előző tippel
kerül összevonásra.
+
Végül, ha a `--expire-time=<datetime>` nincs megadva, legyen `datetime` a
jelenlegi idő. A felosztott commit-graph megírása után minden olyan nem
használt commit-graph törlődik, amelynek módosítási ideje régebbi, mint
`datetime`.

'verify'::

A commit-graph fájl beolvasása és tartalmának ellenőrzése az
objektumadatbázissal szemben. Sérült adatok kiszűrésére szolgál.
+
A `--shallow` opcióval a felosztott commit-graphok láncában csak a tip
commit-graph fájl kerül ellenőrzésre.


EXAMPLES
--------

* Commit-graph fájl írása a helyi `.git` könyvtárban lévő csomagolt
  commitokhoz.
+
------------------------------------------------
$ git commit-graph write
------------------------------------------------

* Commit-graph fájl írása, a jelenlegi commit-graph fájl kiterjesztésével a
  `<pack-index>`-ben lévő commitokkal.
+
------------------------------------------------
$ echo <pack-index> | git commit-graph write --stdin-packs
------------------------------------------------

* Commit-graph fájl írása, amely az összes elérhető commitot tartalmazza.
+
------------------------------------------------
$ git show-ref -s | git commit-graph write --stdin-commits
------------------------------------------------

* Commit-graph fájl írása, amely a jelenlegi commit-graph fájlban lévő
  összes commitot tartalmazza, a `HEAD`-ből elérhetőkkel együtt.
+
------------------------------------------------
$ git rev-parse HEAD | git commit-graph write --stdin-commits --append
------------------------------------------------

CAVEATS
-------

A replace objektumok vagy commit graftok megléte kikapcsolja a
commit-graphba történő olvasást vagy írást. Lásd: linkgit:git-replace[1].

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/commitgraph.adoc[]


FILE FORMAT
-----------

Lásd: linkgit:gitformat-commit-graph[5].

GIT
---
A linkgit:git[1] csomag része
