git-am(1)
=========

NAME
----
git-am - Patch-sorozat alkalmazása egy postafiókból


SYNOPSIS
--------
[synopsis]
git am [--signoff] [--keep] [--[no-]keep-cr] [--[no-]utf8] [--[no-]verify]
	 [--[no-]3way] [--interactive] [--committer-date-is-author-date]
	 [--ignore-date] [--ignore-space-change | --ignore-whitespace]
	 [--whitespace=<action>] [-C<n>] [-p<n>] [--directory=<dir>]
	 [--exclude=<path>] [--include=<path>] [--reject] [-q | --quiet]
	 [--[no-]scissors] [-S[<key-id>]] [--patch-format=<format>]
	 [--quoted-cr=<action>]
	 [--empty=(stop|drop|keep)]
	 [(<mbox> | <Maildir>)...]
git am (--continue | --skip | --abort | --quit | --retry | --show-current-patch[=(diff|raw)] | --allow-empty)

DESCRIPTION
-----------
Szétbontja a postafiókban található levélüzeneteket commit-üzenetekre,
szerzőségi információra és patch-ekre, és alkalmazza ezeket az
aktuális branchre. Úgy is felfoghatod, mint a
linkgit:git-format-patch[1] fordított műveletét, amelyet egy egyenes,
merge-ek nélküli történetű branchen futtattak.

OPTIONS
-------
`(<mbox>|<Maildir>)...`::
	A postafiók-fájlok listája, amelyekből a patch-eket olvassa. Ha
	nem adod meg ezt az argumentumot, a parancs a standard bemenetről
	olvas. Ha könyvtárakat adsz meg, azok Maildir-ként lesznek
	kezelve.

`-s`::
`--signoff`::
	Hozzáad egy `Signed-off-by` trailert a commit-üzenethez (lásd:
	linkgit:git-interpret-trailers[1]), a saját committer-identitásodat
	használva. További információért lásd a signoff opciót a
	linkgit:git-commit[1] parancsban.

`-k`::
`--keep`::
	Átadja a `-k` kapcsolót a linkgit:git-mailinfo[1] parancsnak.

`--keep-non-patch`::
	Átadja a `-b` kapcsolót a linkgit:git-mailinfo[1] parancsnak.

`--keep-cr`::
`--no-keep-cr`::
	A `--keep-cr` esetén meghívja a linkgit:git-mailsplit[1] parancsot
	ugyanezzel a kapcsolóval, hogy megakadályozza a sorvégi CR levágását.
	Az alapértelmezett viselkedés az `am.keepcr` konfigurációs változóval
	adható meg. A `--no-keep-cr` hasznos az `am.keepcr` felülbírálásához.

`-c`::
`--scissors`::
	Eltávolít mindent a törzsből egy olló-sor (scissors line) előtt
	(lásd: linkgit:git-mailinfo[1]). Alapértelmezésben aktiválható a
	`mailinfo.scissors` konfigurációs változóval.

`--no-scissors`::
	Figyelmen kívül hagyja az olló-sorokat (lásd:
	linkgit:git-mailinfo[1]).

`--quoted-cr=<action>`::
	Ez a kapcsoló továbbadásra kerül a linkgit:git-mailinfo[1]
	parancsnak.

`--empty=(drop|keep|stop)`::
	Hogyan kezelje azt az e-mail üzenetet, amelyből hiányzik a patch:
+
--
`drop`;;
	Az e-mail üzenet kimarad.
`keep`;;
	Létrejön egy üres commit, amelynek naplója az e-mail üzenet
	tartalma lesz.
`stop`;;
	A parancs meghiúsul, megszakítva az aktuális `am` munkamenetet a
	közepén. Ez az alapértelmezett viselkedés.
--

`-m`::
`--message-id`::
	Átadja a `-m` kapcsolót a linkgit:git-mailinfo[1] parancsnak, hogy
	a `Message-ID` fejléc bekerüljön a commit-üzenetbe. Az
	alapértelmezett viselkedés az `am.messageid` konfigurációs
	változóval adható meg.

`--no-message-id`::
	Nem adja hozzá a Message-ID fejlécet a commit-üzenethez. A
	`--no-message-id` hasznos az `am.messageid` felülbírálásához.

`-q`::
`--quiet`::
	Csendes működés. Csak a hibaüzeneteket írja ki.

`-u`::
`--utf8`::
	Átadja a `-u` kapcsolót a linkgit:git-mailinfo[1] parancsnak.
	Az e-mailből vett javasolt commit-naplóüzenet UTF-8 kódolásra lesz
	átkódolva (az `i18n.commitEncoding` konfigurációs változóval
	adható meg a projekt preferált kódolása, ha az nem UTF-8).
+
Ez a korábbi Git-verziókban opcionális volt, de most már ez az
alapértelmezett. A `--no-utf8` használatával felülbírálható.

`--no-utf8`::
	Átadja a `-n` kapcsolót a linkgit:git-mailinfo[1] parancsnak.

`-3`::
`--3way`::
`--no-3way`::
	Ha a patch nem alkalmazható tisztán, visszaesik háromutas
	merge-re, amennyiben a patch rögzíti azon blobok azonosítóját,
	amelyekre alkalmazni kellene, és ezek a blobok helyben elérhetők.
	A `--no-3way` használható az `am.threeWay` konfigurációs változó
	felülbírálására. További információért lásd az `am.threeWay`-t a
	linkgit:git-config[1] parancsban.

include::rerere-options.adoc[]

`--ignore-space-change`::
`--ignore-whitespace`::
`--whitespace=<action>`::
`-C<n>`::
`-p<n>`::
`--directory=<dir>`::
`--exclude=<path>`::
`--include=<path>`::
`--reject`::
	Ezek a kapcsolók a patchet alkalmazó linkgit:git-apply[1]
	programnak kerülnek átadásra.
+
A `--whitespace` opció érvényes _<action>_ értékei:
`nowarn`, `warn`, `fix`, `error` és `error-all`.

`--patch-format`::
	Alapértelmezésben a parancs megpróbálja automatikusan felismerni
	a patch formátumát. Ez az opció lehetővé teszi a felhasználónak,
	hogy megkerülje az automatikus felismerést, és megadja, milyen
	formátumúként kell értelmezni a patch(ek)et. Az érvényes
	formátumok: mbox, mboxrd, stgit, stgit-series és hg.

`-i`::
`--interactive`::
	Interaktív futtatás.

`--verify`::
`-n`::
`--no-verify`::
	Lefuttatja a `pre-applypatch` és `applypatch-msg` hookokat. Ez az
	alapértelmezés. Ezek a hookok a `-n` vagy `--no-verify` kapcsolóval
	hagyhatók ki. Lásd még: linkgit:githooks[5].
+
Vedd figyelembe, hogy a `post-applypatch` nem hagyható ki.

`--committer-date-is-author-date`::
	Alapértelmezésben a parancs az e-mail üzenet dátumát rögzíti a
	commit szerzői dátumaként, és a commit létrehozásának idejét
	használja committer-dátumként. Ez lehetővé teszi a felhasználónak,
	hogy a committer-dátumot a szerzői dátummal megegyező értékkel
	hamisítsa meg.
+
WARNING: A történet-bejárási gépezet feltételezi, hogy a commitok
monoton nem csökkenő commit-időbélyeggel rendelkeznek. Fontold meg,
hogy valóban szükséged van-e erre az opcióra. Ezt az opciót csak
akkor használd a committer-dátum felülbírálására, ha olyan alapra
alkalmazol commitokat, amelynek commitja régebbi (a commit dátuma
szerint), mint a legrégebbi alkalmazandó patch.

`--ignore-date`::
	Alapértelmezésben a parancs az e-mail üzenet dátumát rögzíti a
	commit szerzői dátumaként, és a commit létrehozásának idejét
	használja committer-dátumként. Ez lehetővé teszi a felhasználónak,
	hogy a szerzői dátumot a committer-dátummal megegyező értékkel
	hamisítsa meg.

`--skip`::
	Kihagyja az aktuális patchet. Ennek csak egy megszakított patch
	újraindításakor van értelme.

`-S[<key-id>]`::
`--gpg-sign[=<key-id>]`::
`--no-gpg-sign`::
	GPG-vel aláírja a commitokat. A _<key-id>_ opcionális, és
	alapértelmezésben a committer-identitás; ha meg van adva,
	közvetlenül, szóköz nélkül kell az opcióhoz tapasztani. A
	`--no-gpg-sign` hasznos mind a `commit.gpgSign` konfigurációs
	változó, mind egy korábbi `--gpg-sign` felülbírálásához.

`--continue`::
`-r`::
`--resolved`::
	Egy patch meghiúsulása után (pl. egy ütköző patch alkalmazási
	kísérletekor) a felhasználó kézzel alkalmazta azt, és az index
	fájl tárolja az alkalmazás eredményét. Készíts egy commitot az
	e-mail üzenetből kinyert szerzőség és commit-napló, valamint az
	aktuális index fájl felhasználásával, majd folytasd.

`--resolvemsg=<msg>`::
	Egy patch meghiúsulásakor a _<msg>_ kerül kiírásra a képernyőre
	kilépés előtt. Ez felülbírálja azt a szabványos üzenetet, amely a
	`--continue` vagy `--skip` használatára hívja fel a figyelmet a
	hiba kezeléséhez. Ez kizárólag a linkgit:git-rebase[1] és a
	linkgit:git-am[1] közötti belső használatra szolgál.

`--abort`::
	Visszaállítja az eredeti branchet, és megszakítja a
	patch-alkalmazási műveletet. Az am műveletben érintett fájlok
	tartalmát visszaállítja az am előtti állapotukra.

`--quit`::
	Megszakítja a patch-alkalmazási műveletet, de a `HEAD`-et és az
	indexet érintetlenül hagyja.

`--retry`::
	Megpróbálja újra alkalmazni az utolsó ütköző patchet. Ez
	általában csak akkor hasznos, ha extra opciókat szeretnél átadni
	az újrapróbálási kísérletnek (pl. `--3way`), mivel egyébként csak
	ugyanazt a hibát látnád újra.

`--show-current-patch[=(diff|raw)]`::
	Megjeleníti azt az üzenetet, amelynél a linkgit:git-am[1] megállt
	ütközések miatt. Ha `raw` van megadva, az e-mail üzenet nyers
	tartalmát jeleníti meg; ha `diff`, csak a diff részt.
	Alapértelmezésben `raw`.

`--allow-empty`::
	Egy olyan bemeneti e-mail üzeneten bekövetkező
	patch-meghiúsulás után, amelyből hiányzik a patch, létrehoz egy
	üres commitot, amelynek naplóüzenete az e-mail üzenet tartalma
	lesz.

[[discussion]]
DISCUSSION
----------

A commit szerzőjének neve a "From: " sorból, a commit szerzői dátuma
pedig a "Date: " sorból származik. A "Subject: " sor szolgál a commit
címeként, miután eltávolításra kerül a gyakori "[PATCH <anything>]"
előtag. A "Subject: " sornak tömören kell leírnia egy sornyi szövegben,
miről szól a commit.

A törzs elején található "From: ", "Date: " és "Subject: " sorok
felülbírálják a fejlécekből vett megfelelő commit szerzői név és cím
értékeket.

A commit-üzenet a "Subject: "-ből vett címből, egy üres sorból, és az
üzenet törzséből épül fel egészen a patch kezdetéig. Minden sor végén
a felesleges whitespace automatikusan eltávolításra kerül.

A patch elvárás szerint inline, közvetlenül az üzenet után
következik.
include::format-patch-end-of-commit-message.adoc[]

Ez azt jelenti, hogy a commit-üzenet tartalma véletlenül
megszakíthatja a feldolgozást (lásd az alábbi <<caveats,CAVEATS>>
szakaszt).

A linkgit:git-am[1] kezdeti meghívásakor megadod neki a feldolgozandó
postafiókok neveit. Amint az első nem alkalmazható patch-hez ér, a
közepén megszakad. Ebből kétféleképpen tudsz talpra állni:

. az aktuális patch kihagyásával, a parancs `--skip` opcióval való
  újrafuttatásával.

. az ütközés kézi feloldásával a munkakönyvtárban, és az index fájl
  frissítésével olyan állapotba, amilyet a patchnek elő kellett volna
  állítania. Ezután futtasd a parancsot a `--continue` opcióval.

A parancs megtagadja új postafiókok feldolgozását, amíg az aktuális
művelet be nem fejeződik, ezért ha úgy döntesz, hogy elölről kezded,
futtasd a `git am --abort` parancsot, mielőtt postafiók-nevekkel
futtatnád a parancsot.

Mielőtt bármelyik patch alkalmazásra kerülne, az `ORIG_HEAD` az
aktuális branch csúcsára lesz állítva. Ez akkor hasznos, ha
problémáid vannak több committal, például ha a linkgit:git-am[1]
parancsot rossz branchen futtattad, vagy ha a commitokban lévő hiba
egyszerűbben javítható a postafiók módosításával (pl. hibák a `From:`
sorokban).

[[caveats]]
CAVEATS
-------

:git-am: 1
include::format-patch-caveats.adoc[]

HOOKOK
------
Ez a parancs futtathatja az `applypatch-msg`, `pre-applypatch` és
`post-applypatch` hookokat. További információért lásd:
linkgit:githooks[5].

Lásd a `--verify`/`-n`/`--no-verify` opciókat.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/am.adoc[]

SEE ALSO
--------
linkgit:git-apply[1],
linkgit:git-format-patch[1].

GIT
---
A linkgit:git[1] csomag része
