git-maintenance(1)
==================

NAME
----
git-maintenance - Feladatok futtatása a Git repository-adatok optimalizálására


SYNOPSIS
--------
[verse]
'git maintenance' run [<options>]
'git maintenance' start [--scheduler=<scheduler>]
'git maintenance' (stop|register|unregister) [<options>]
'git maintenance' is-needed [<options>]


DESCRIPTION
-----------
Feladatokat futtat a Git repository-adatok optimalizálására, felgyorsítva
a többi Git parancsot, és csökkentve a repository tárolási igényét.

Azok a Git parancsok, amelyek repository-adatot adnak hozzá, mint a
`git add` vagy a `git fetch`, reszponzív felhasználói élményre vannak
optimalizálva. Ezek a parancsok nem szánnak időt a Git-adatok
optimalizálására, mivel az ilyen optimalizálások a repository teljes
méretével skálázódnak, míg ezek a felhasználói parancsok egyenként
viszonylag kis műveletet végeznek.

A `git maintenance` parancs rugalmasságot ad arra, hogyan optimalizáld a
Git repository-t.

SUBCOMMANDS
-----------

run::
	Egy vagy több karbantartási feladatot futtat. Ha egy vagy több
	`--task` kapcsoló van megadva, akkor azok a feladatok abban a
	sorrendben futnak. Egyébként a feladatokat az határozza meg, hogy
	mely `maintenance.<task>.enabled` konfigurációs kapcsolók true-ak.
	Alapból csak a `maintenance.gc.enabled` true.

start::
	Elkezdi a karbantartás futtatását az aktuális repository-n. Ez
	ugyanazokat a konfigurációfrissítéseket végzi, mint a `register`
	alparancs, majd frissíti a háttér-ütemezőt, hogy óránként lefuttassa
	a `git maintenance run --scheduled`-t.

stop::
	Leállítja a háttér-karbantartási ütemezést. Az aktuális repository
	nem távolítódik el a karbantartott repository-k listájáról, arra az
	esetre, ha a háttér-karbantartást később újraindítják.

register::
	Inicializálja a Git konfigurációs értékeit, hogy bármely ütemezett
	karbantartás elkezdjen futni ezen a repository-n. Ez hozzáadja a
	repository-t az aktuális felhasználó globális konfigjában lévő
	`maintenance.repo` konfigurációs változóhoz, vagy a --config-file
	kapcsolóval megadott konfighoz, és engedélyez néhány ajánlott
	konfigurációs értéket a `maintenance.<task>.schedule`-höz. Az
	engedélyezett feladatok biztonságosan futtathatók a háttérben az
	előtér-folyamatok megzavarása nélkül.
+
A `register` alparancs a `maintenance.strategy` konfigurációs értéket is
`incremental`-ra állítja, ha ez az érték korábban nincs beállítva. Az
`incremental` stratégia a következő ütemezést használja minden
karbantartási feladathoz:
+
--
* `gc`: letiltva.
* `commit-graph`: óránként.
* `prefetch`: óránként.
* `loose-objects`: naponta.
* `incremental-repack`: naponta.
--
+
A `git maintenance register` az előtér-karbantartást is letiltja azzal,
hogy a `maintenance.auto = false`-t beállítja az aktuális repository-ban.
Ez a konfigurációs beállítás megmarad egy `git maintenance unregister`
parancs után is.

unregister::
	Eltávolítja az aktuális repository-t a háttér-karbantartásból. Ez
	csak a konfigurált listáról távolítja el a repository-t. Nem
	állítja le a háttér-karbantartási folyamatok futását.
+
Az `unregister` alparancs hibát jelent, ha az aktuális repository nincs
már regisztrálva. A `--force` kapcsolóval sikert adhatsz vissza akkor
is, ha az aktuális repository nincs regisztrálva.

is-needed::
    Ellenőrzi, hogy szükség van-e a karbantartás futtatására, anélkül,
    hogy ténylegesen lefuttatná. 0 státuszkóddal lép ki, ha szükség van
    a karbantartás futtatására, egyébként 1-gyel. Ideális esetben a
    '--auto' kapcsolóval együtt használatos.
+
Ha egy vagy több `--task` kapcsoló van megadva, akkor azok a feladatok
abban a sorrendben kerülnek ellenőrzésre. Egyébként a feladatokat az
határozza meg, hogy mely `maintenance.<task>.enabled` konfigurációs
kapcsolók true-ak. Alapból csak a `maintenance.gc.enabled` true.

TASKS
-----

commit-graph::
	A `commit-graph` job inkrementálisan frissíti a `commit-graph`
	fájlokat, majd ellenőrzi, hogy a kiírt adat helyes-e. Az
	inkrementális írás biztonságosan futtatható egyidejű Git folyamatok
	mellett, mivel nem járatja le azokat a `.graph` fájlokat, amelyek az
	előző `commit-graph-chain` fájlban voltak. Ezeket egy későbbi futás
	törli a lejárati késleltetés alapján.

prefetch::
	A `prefetch` feladat frissíti az objektumkönyvtárat az összes
	regisztrált remote legfrissebb objektumaival. Minden remote-hoz egy
	`git fetch` parancs fut. A konfigurált refspec úgy módosul, hogy az
	összes kért refet a `refs/prefetch/`-en belülre helyezze. Emellett a
	tagek nem frissülnek.
+
Ez a remote-tracking branchek megzavarásának elkerülésére szolgál. A
végfelhasználók azt várják, hogy ezek a refek mozdulatlanul maradjanak,
hacsak nem kezdeményeznek egy fetchet. A prefetch feladattal viszont egy
későbbi valódi fetch befejezéséhez szükséges objektumok már beszerezve
lennének, gyorsabbá téve a valódi fetchet. Ideális esetben csak egy
csomó remote-tracking branch frissítésévé válik, mindenféle
objektumátvitel nélkül.
+
A `remote.<name>.skipFetchAll` konfiguráció egy adott remote prefetchből
való kizárására használható.

gc::
	Feltakarítja a szükségtelen fájlokat, és optimalizálja a helyi
	repository-t. A "GC" a "garbage collection" (szemétgyűjtés)
	rövidítése, de ez a feladat sok kisebb feladatot végez. Ez a feladat
	költséges lehet nagy repository-knál, mivel az összes Git-objektumot
	egyetlen pack-file-ba csomagolja át. Bizonyos helyzetekben zavaró is
	lehet, mivel törli az elavult adatokat. A Git szemétgyűjtéséről
	további részletekért lásd: linkgit:git-gc[1].

loose-objects::
	A `loose-objects` job feltakarítja a laza objektumokat, és
	pack-file-okba helyezi őket. Az egyidejű Git parancsokkal való
	versenyhelyzetek megelőzése érdekében kétlépéses folyamatot követ.
	Először törli azokat a laza objektumokat, amelyek már léteznek egy
	pack-file-ban; az egyidejű Git folyamatok a laza objektum helyett a
	pack-file-ban vizsgálják az objektumadatot. Másodszor létrehoz egy
	új pack-file-t (amely "loose-"-zal kezdődik), amely egy köteg laza
	objektumot tartalmaz.
+
A kötegméret alapból ötvenezer objektum, hogy megakadályozza, hogy a job
túl sokáig tartson egy sok laza objektumot tartalmazó repository-n. E
méret módosításához használd a `maintenance.loose-objects.batchSize`
konfigurációs kapcsolót, beleértve a `0` értéket a korlát
eltávolításához.
+
A `gc` feladat az elérhetetlen objektumokat laza objektumként írja ki,
hogy egy későbbi lépés takarítsa fel őket, csak akkor, ha nem kerülnek
újra hozzáadásra egy pack-file-hoz; emiatt nem ajánlott a `loose-objects`
és a `gc` feladatot egyszerre engedélyezni.

incremental-repack::
	Az `incremental-repack` job a `multi-pack-index` funkció
	használatával csomagolja át az objektumkönyvtárat. Az egyidejű Git
	parancsokkal való versenyhelyzetek megelőzése érdekében kétlépéses
	folyamatot követ. Először meghívja a `git multi-pack-index expire`-t,
	hogy törölje a `multi-pack-index` fájl által nem hivatkozott
	pack-file-okat. Másodszor meghívja a `git multi-pack-index repack`-et,
	hogy kiválasszon több kis pack-file-t, és egy nagyobba csomagolja át
	őket, majd frissítse a `multi-pack-index` azon bejegyzéseit, amelyek
	a kis pack-file-okra hivatkoznak, hogy az új pack-file-ra
	hivatkozzanak. Ez előkészíti azokat a kis pack-file-okat a törlésre a
	`git multi-pack-index expire` következő futásakor. A kis pack-file-ok
	kiválasztása olyan, hogy a nagy pack-file várható mérete legalább a
	kötegméret; lásd a `--batch-size` kapcsolót a `repack` alparancshoz a
	linkgit:git-multi-pack-index[1]-ben. Az alapértelmezett kötegméret
	nulla, ami egy speciális eset, amely megpróbálja az összes
	pack-file-t egyetlen pack-file-ba csomagolni.

pack-refs::
	A `pack-refs` feladat összegyűjti a laza referenciafájlokat, és
	egyetlen fájlba gyűjti őket. Ez felgyorsítja azokat a műveleteket,
	amelyeknek sok referencián kell végigiterálniuk. További
	információért lásd: linkgit:git-pack-refs[1].

reflog-expire::
	A `reflog-expire` feladat törli a reflogban lévő minden olyan
	bejegyzést, amely régebbi a lejárati küszöbnél. További információért
	lásd: linkgit:git-reflog[1].

rerere-gc::
	A `rerere-gc` feladat szemétgyűjtést indít a rerere cache elavult
	bejegyzéseihez. További információért lásd: linkgit:git-rerere[1].

worktree-prune::
	A `worktree-prune` feladat törli az elavult vagy sérült
	worktree-ket. További információért lásd: linkgit:git-worktree[1].

OPTIONS
-------
--auto::
	A `run` alparanccsal kombinálva csak akkor futtat karbantartási
	feladatokat, ha bizonyos küszöbök teljesülnek. Például a `gc`
	feladat akkor fut, amikor a laza objektumok száma meghaladja a
	`gc.auto` konfigurációs beállításban tárolt számot, vagy amikor a
	pack-file-ok száma meghaladja a `gc.autoPackLimit` konfigurációs
	beállítást. Nem kompatibilis a `--schedule` kapcsolóval.
	Az `is-needed` alparanccsal kombinálva ellenőrzi, hogy a szükséges
	küszöbök teljesülnek-e, anélkül, hogy ténylegesen lefuttatná a
	karbantartást.

--schedule::
	A `run` alparanccsal kombinálva csak akkor futtat karbantartási
	feladatokat, ha bizonyos időfeltételek teljesülnek, ahogy azt az
	egyes `<task>`-ekhez a `maintenance.<task>.schedule` konfigurációs
	érték megadja. Ez a konfigurációs érték egy másodpercszámot ad meg
	azóta, hogy az adott feladat utoljára futott, a
	`maintenance.<task>.lastRun` konfigurációs érték szerint. A tesztelt
	feladatok azok, amelyeket a `--task=<task>` kapcsoló(k) ad(nak) meg,
	vagy amelyeknél a `maintenance.<task>.enabled` true-ra van állítva.

--quiet::
	Nem jelent folyamatot vagy egyéb információt a `stderr`-en.

--task=<task>::
	Ha ez a kapcsoló egyszer vagy többször meg van adva, akkor csak a
	megadott feladatokat futtatja a megadott sorrendben. Ha nincs
	`--task=<task>` argumentum megadva, akkor csak azok a feladatok
	jönnek szóba, amelyeknél a `maintenance.<task>.enabled` `true`-ra
	van konfigurálva. Az elfogadott `<task>` értékek listájáért lásd a
	'TASKS' szakaszt.

--scheduler=auto|crontab|systemd-timer|launchctl|schtasks::
	A `start` alparanccsal kombinálva megadja az ütemezőt a
	`git maintenance run` óránkénti, napi és heti végrehajtásához.
	A `<scheduler>` lehetséges értékei: `auto`, `crontab` (POSIX),
	`systemd-timer` (Linux), `launchctl` (macOS) és `schtasks`
	(Windows). Amikor az `auto` van megadva, a megfelelő
	platformspecifikus ütemező kerül felhasználásra; Linuxon a
	`systemd-timer`, ha elérhető, egyébként a `crontab`. Alapból `auto`.


TROUBLESHOOTING
---------------
A `git maintenance` parancsot úgy tervezték, hogy egyszerűsítse a
repository-karbantartási mintákat, miközben minimalizálja a felhasználói
várakozási időt a Git parancsok során. Sokféle konfigurációs kapcsoló
áll rendelkezésre, hogy lehetővé tegye ennek a folyamatnak a
testreszabását. Az alapértelmezett karbantartási kapcsolók olyan
műveletekre összpontosítanak, amelyek gyorsan befejeződnek, még nagy
repository-kon is.

A felhasználók találkozhatnak olyan esetekkel, amikor az ütemezett
karbantartási feladatok nem futnak olyan gyakran, mint tervezték. Minden
`git maintenance run` parancs zárolja a repository objektumadatbázisát,
és ez megakadályozza, hogy más egyidejű `git maintenance run` parancsok
fussanak ugyanazon a repository-n. E biztosíték nélkül a versengő
folyamatok kiszámíthatatlan állapotban hagyhatnák a repository-t.

A háttér-karbantartási ütemezés óránként futtat `git maintenance run`
folyamatokat. Minden futás végrehajtja az "óránkénti" feladatokat.
Éjfélkor az a folyamat a "napi" feladatokat is végrehajtja. A hét első
napjának éjfelekor az a folyamat a "heti" feladatokat is végrehajtja.
Egyetlen folyamat végigiterál minden regisztrált repository-n, elvégezve
az adott gyakoriságú ütemezett feladatokat. A folyamatok kliensenként az
óra egy véletlenszerű percére vannak ütemezve, hogy szétterítsék a
terhelést, amelyet több kliens generálhat (pl. prefetchelésből). A
regisztrált repository-k számától és méretétől függően ez a folyamat
egy óránál tovább is tarthat. Ebben az esetben több `git maintenance run`
parancs futhat ugyanazon a repository-n egyszerre, ütközve az
objektumadatbázis-záron. Ez azt eredményezi, hogy a két feladat egyike
nem fut le.

Ha azt tapasztalod, hogy egyes karbantartási ablakok befejezése egy
óránál tovább tart, akkor fontold meg a karbantartási feladataid
összetettségének csökkentését. Például a `gc` feladat sokkal lassabb,
mint az `incremental-repack` feladat. Ez azonban egy kissé nagyobb
objektumadatbázis árán jár. Fontold meg, hogy a költségesebb feladatokat
ritkábban futtasd.

A haladó felhasználók fontolóra vehetik, hogy a saját karbantartási
feladataikat a `git maintenance start`-on és a Git konfigurációs
kapcsolóin keresztül elérhetőtől eltérő ütemezéssel ütemezzék. Ezeknek a
felhasználóknak tisztában kell lenniük az objektumadatbázis-zárral és
azzal, hogyan viselkednek az egyidejű `git maintenance run` parancsok.
Továbbá a `git gc` parancsot nem szabad `git maintenance run` parancsokkal
kombinálni. A `git gc` módosítja az objektumadatbázist, de nem ugyanúgy
zárol, mint a `git maintenance run`. Ha lehetséges, a `git gc` helyett a
`git maintenance run --task=gc`-t használd.

A következő szakaszok leírják azokat a mechanizmusokat, amelyeket a
`git maintenance start` a háttér-karbantartás futtatására bevezet, és
azt, hogyan szabhatók testre.

BACKGROUND MAINTENANCE ON POSIX SYSTEMS
---------------------------------------

A háttérfeladatok ütemezésének szabványos mechanizmusa POSIX
rendszereken a cron(8). Ez az eszköz egy adott ütemezés alapján hajt
végre parancsokat. A felhasználó által ütemezett feladatok aktuális
listája a `crontab -l` futtatásával található meg. A `git maintenance
start` által kiírt ütemezés ehhez hasonló:

-----------------------------------------------------------------------
# BEGIN GIT MAINTENANCE SCHEDULE
# The following schedule was created by Git
# Any edits made in this region might be
# replaced in the future by a Git command.

0 1-23 * * * "/<path>/git" --exec-path="/<path>" for-each-repo --config=maintenance.repo maintenance run --schedule=hourly
0 0 * * 1-6 "/<path>/git" --exec-path="/<path>" for-each-repo --config=maintenance.repo maintenance run --schedule=daily
0 0 * * 0 "/<path>/git" --exec-path="/<path>" for-each-repo --config=maintenance.repo maintenance run --schedule=weekly

# END GIT MAINTENANCE SCHEDULE
-----------------------------------------------------------------------

A kommentek egy régióként szolgálnak arra, hogy az ütemezést Git által
kiírtként jelöljék. Az e régión belüli bármely módosítást a
`git maintenance stop` teljesen törli, vagy a `git maintenance start`
felülírja.

A `crontab` bejegyzés megadja a `git` végrehajtható fájl teljes
útvonalát annak biztosítására, hogy a végrehajtott `git` parancs ugyanaz
legyen, amellyel a `git maintenance start`-ot kiadták, a `PATH`-tól
függetlenül. Ha ugyanaz a felhasználó több Git végrehajtható fájllal
futtatja a `git maintenance start`-ot, akkor csak a legutóbbi
végrehajtható fájl kerül felhasználásra.

Ezek a parancsok a `git for-each-repo --config=maintenance.repo`-t
használják arra, hogy lefuttassák a `git maintenance run
--schedule=<frequency>`-t minden repository-n, amely a többértékű
`maintenance.repo` konfigurációs kapcsolóban fel van sorolva. Ezek
jellemzően a felhasználóspecifikus globális konfigból töltődnek be. A
`git maintenance` folyamat ezután a `maintenance.<task>.schedule`
konfigurációs kapcsolókkal meghatározza, hogy mely karbantartási
feladatok vannak úgy konfigurálva, hogy minden repository-n minden
`<frequency>`-vel fussanak. Ezek az értékek a globális vagy a repository
konfigurációs értékeiből töltődnek be.

Ha a konfigurációs értékek nem elegendők a kívánt háttér-karbantartási
ütemezés eléréséhez, akkor létrehozhatod a saját ütemezésedet. Ha
lefuttatod a `crontab -e`-t, akkor betöltődik egy szerkesztő a
felhasználóspecifikus `cron` ütemezéseddel. Abban a szerkesztőben
hozzáadhatod a saját ütemezési soraidat. Kezdheted a korábban felsorolt
alapértelmezett ütemezés adaptálásával, vagy elolvashatod a crontab(5)
dokumentációt a haladó ütemezési technikákért. Kérjük, használd a teljes
útvonal és a `--exec-path` technikákat az alapértelmezett ütemezésből,
hogy biztosítsd, hogy a megfelelő binárisokat futtatod az ütemezésedben.


BACKGROUND MAINTENANCE ON LINUX SYSTEMD SYSTEMS
-----------------------------------------------

Bár a Linux támogatja a `cron`-t, a disztribúciótól függően a `cron`
lehet egy opcionális csomag, amely nincs feltétlenül telepítve. A modern
Linux-disztribúciókon a systemd időzítők leváltják.

Ha felhasználói systemd időzítők elérhetők, azok kerülnek felhasználásra
a `cron` helyett.

Ebben az esetben a `git maintenance start` felhasználói systemd
időzítő-egységeket hoz létre, és elindítja az időzítőket. A felhasználó
által ütemezett feladatok aktuális listája a `systemctl --user
list-timers` futtatásával található meg. A `git maintenance start` által
kiírt időzítők ehhez hasonlók:

-----------------------------------------------------------------------
$ systemctl --user list-timers
NEXT                         LEFT          LAST                         PASSED     UNIT                         ACTIVATES
Thu 2021-04-29 19:00:00 CEST 42min left    Thu 2021-04-29 18:00:11 CEST 17min ago  git-maintenance@hourly.timer git-maintenance@hourly.service
Fri 2021-04-30 00:00:00 CEST 5h 42min left Thu 2021-04-29 00:00:11 CEST 18h ago    git-maintenance@daily.timer  git-maintenance@daily.service
Mon 2021-05-03 00:00:00 CEST 3 days left   Mon 2021-04-26 00:00:11 CEST 3 days ago git-maintenance@weekly.timer git-maintenance@weekly.service
-----------------------------------------------------------------------

Minden `--schedule=<frequency>` kapcsolóhoz egy időzítő van
regisztrálva.

A systemd egységek definíciója a következő fájlokban vizsgálható meg:

-----------------------------------------------------------------------
~/.config/systemd/user/git-maintenance@.timer
~/.config/systemd/user/git-maintenance@.service
~/.config/systemd/user/timers.target.wants/git-maintenance@hourly.timer
~/.config/systemd/user/timers.target.wants/git-maintenance@daily.timer
~/.config/systemd/user/timers.target.wants/git-maintenance@weekly.timer
-----------------------------------------------------------------------

A `git maintenance start` felülírja ezeket a fájlokat, és újraindítja az
időzítőt a `systemctl --user`-rel, így bármilyen testreszabást egy
drop-in fájl létrehozásával kell elvégezni, azaz egy `.conf` utótagú
fájllal a `~/.config/systemd/user/git-maintenance@.service.d`
könyvtárban.

A `git maintenance stop` leállítja a felhasználói systemd időzítőket, és
törli a fent említett fájlokat.

További részletekért lásd: `systemd.timer(5)`.


BACKGROUND MAINTENANCE ON MACOS SYSTEMS
---------------------------------------

Bár a macOS technikailag támogatja a `cron`-t, a `crontab -e` használata
emelt szintű jogosultságokat igényel, és a végrehajtott folyamatnak
nincs teljes felhasználói kontextusa. Teljes felhasználói kontextus
nélkül a Git és a credential helperei nem férnek hozzá a tárolt
hitelesítő adatokhoz, így néhány karbantartási feladat nem működőképes.

Ehelyett a `git maintenance start` a `launchctl` eszközzel lép
kölcsönhatásba, amely az időzített jobok ütemezésének ajánlott módja
macOS-en. A karbantartás ütemezéséhez a `git maintenance (start|stop)`-on
keresztül néhány olyan `launchctl` funkció szükséges, amely csak a macOS
10.11-ben vagy újabbban érhető el.

A felhasználóspecifikus ütemezett feladataid XML-formátumú `.plist`
fájlokként vannak tárolva a `~/Library/LaunchAgents/`-ben. A jelenleg
regisztrált feladatokat a következő paranccsal láthatod:

-----------------------------------------------------------------------
$ ls ~/Library/LaunchAgents/org.git-scm.git*
org.git-scm.git.daily.plist
org.git-scm.git.hourly.plist
org.git-scm.git.weekly.plist
-----------------------------------------------------------------------

Minden `--schedule=<frequency>` kapcsolóhoz egy feladat van
regisztrálva. Ahhoz, hogy megvizsgáld, hogyan írja le az XML-formátum az
egyes ütemezéseket, nyisd meg az egyik ilyen `.plist` fájlt egy
szerkesztőben, és vizsgáld meg a `<key>StartCalendarInterval</key>`
elemet követő `<array>` elemet.

A `git maintenance start` felülírja ezeket a fájlokat, és újra
regisztrálja a feladatokat a `launchctl`-lel, így bármilyen testreszabást
a saját, egyedi nevű `.plist` fájljaid létrehozásával kell elvégezni.
Hasonlóképp a `git maintenance stop` parancs a `launchctl`-lel
kiregisztrálja a feladatokat, és törli a `.plist` fájlokat.

A háttérfeladataid haladóbb testreszabásaihoz további információért lásd:
launchctl.plist(5).


BACKGROUND MAINTENANCE ON WINDOWS SYSTEMS
-----------------------------------------

A Windows nem támogatja a `cron`-t, és helyette saját rendszere van a
háttérfeladatok ütemezésére. A `git maintenance start` parancs a
`schtasks` parancsot használja arra, hogy feladatokat adjon be ennek a
rendszernek. Az összes háttérfeladatot a Task Scheduler alkalmazással
vizsgálhatod meg. A Git által hozzáadott feladatok neve
`Git Maintenance (<frequency>)` alakú. A Task Scheduler GUI-jában többféle
módon is megvizsgálhatók ezek a feladatok, de a feladatokat XML-fájlokba
is exportálhatod, és ott megnézheted a részleteket.

Vedd figyelembe, hogy mivel a Git egy konzolalkalmazás, ezek a
háttérfeladatok az aktuális felhasználó számára látható konzolablakot
hoznak létre. Ez kézzel megváltoztatható a "Run whether user is logged
in or not" opció kiválasztásával a Task Schedulerben. Ez a változtatás
jelszóbevitelt igényel, ezért nem választja ki a `git maintenance start`
alapból.

Ha testre akarod szabni a háttérfeladatokat, kérjük, nevezd át a
feladatokat, hogy a `git maintenance (start|stop)` jövőbeli hívásai ne
írják felül az egyéni feladataidat.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/maintenance.adoc[]


GIT
---
A linkgit:git[1] csomag része
