git-mv(1)
=========

NAME
----
git-mv - Áthelyez vagy átnevez egy fájlt, egy könyvtárat vagy egy symlinket


SYNOPSIS
--------

[synopsis]
git mv [-v] [-f] [-n] [-k] <source> <destination>
git mv [-v] [-f] [-n] [-k] <source>... <destination-directory>

DESCRIPTION
-----------
Áthelyez vagy átnevez egy fájlt, könyvtárat vagy symlinket.

Az első alakban átnevezi a _<source>_-t (amelynek léteznie kell, és
fájlnak, symlinknek vagy könyvtárnak kell lennie) a _<destination>_-re.
A második alakban a _<destination-directory>_-nak egy meglévő
könyvtárnak kell lennie; a megadott forrásokat ebbe a könyvtárba
helyezi át.

Az index a sikeres befejezés után frissül, de a változtatást még
commitolni kell.

OPTIONS
-------
`-f`::
`--force`::
	Kikényszeríti egy fájl átnevezését vagy áthelyezését akkor is,
	ha a <destination> már létezik.
`-k`::
	Kihagyja azokat az áthelyezési vagy átnevezési műveleteket,
	amelyek hibaállapothoz vezetnének. Hiba akkor történik, ha egy
	forrás sem nem létezik, sem nincs Git által kezelve, vagy ha
	felülírna egy meglévő fájlt, hacsak a `-f` nincs megadva.
`-n`::
`--dry-run`::
	Nem csinál semmit; csak megmutatja, mi történne

`-v`::
`--verbose`::
	Jelenti a fájlok neveit, ahogy áthelyezésre kerülnek.

SUBMODULES
----------
Egy submodule gitfile-lal (ami azt jelenti, hogy Git 1.7.8-as vagy
újabb verzióval lettek klónozva) történő áthelyezése frissíti a
gitfile-t és a core.worktree beállítást, hogy a submodule működjön az
új helyen. Emellett megpróbálja frissíteni a `submodule.<name>.path`
beállítást a linkgit:gitmodules[5] fájlban, és stage-eli azt a fájlt
(hacsak a `-n` nincs használva).

BUGS
----
Minden alkalommal, amikor egy szuperprojekt-frissítés áthelyez egy
feltöltött submodule-t (pl. az áthelyezés előtti és utáni commitok
közötti váltáskor), egy elavult submodule-checkout marad a régi
helyen, és egy üres könyvtár jelenik meg az új helyen. A submodule
újbóli feltöltéséhez az új helyen a felhasználónak utána le kell
futtatnia a "git submodule update"-et. A régi könyvtár eltávolítása
csak akkor biztonságos, ha az egy gitfile-t használ, mert egyébként a
submodule előzményei is törlődnek. Mindkét lépés elavulttá válik,
amint megvalósításra kerül a rekurzív submodule-frissítés.

GIT
---
A linkgit:git[1] csomag része
