git-status(1)
=============

NAME
----
git-status - Show the working tree status


SYNOPSIS
--------

[synopsis]
git status [<options>] [--] [<pathspec>...]

DESCRIPTION
-----------
Megjeleníti azokat az útvonalakat, amelyeknél eltérés van az indexfájl és a
aktuális HEAD commit között, azokat az útvonalakat, amelyeknél eltérés van a working
tree és az indexfájl között, valamint azokat az útvonalakat a working tree-ben,
amelyeket a Git nem követ (és amelyeket a linkgit:gitignore[5] nem hagy figyelmen kívül). Az első
csoport az, amit a `git commit` futtatásával _commitolnál_; a második és
harmadik az, amit a `git add`, majd a `git commit` futtatásával
_commitolhatnál_.

OPTIONS
-------

`-s`::
`--short`::
	A kimenet megadása rövid formátumban.

`-b`::
`--branch`::
	A branch és a tracking-információ megjelenítése rövid formátumban is.

`--show-stash`::
	A jelenleg elstashelt bejegyzések számának megjelenítése.

`--porcelain[=<version>]`::
	A kimenet megadása szkriptek számára könnyen elemezhető formátumban.
	Ez hasonló a rövid kimenethez, de stabil marad a Git-verziók
	között és a felhasználói konfigurációtól függetlenül. A részletekért lásd
	lentebb.
+
A _<version>_ paraméter a formátumverzió megadására szolgál.
Ez opcionális, és alapból az eredeti `v1` verziójú formátumra áll.

`--long`::
	A kimenet megadása hosszú formátumban. Ez az alapértelmezés.

`-v`::
`--verbose`::
	A megváltozott fájlok nevein kívül a
	commitolásra stage-elt szöveges változtatásokat is megjeleníti
	(azaz mint a `git diff --cached` kimenete). Ha a `-v` kétszer van megadva,
	akkor a working tree-ben lévő, még nem stage-elt
	változtatásokat is megjeleníti (azaz mint a `git diff` kimenete).

`-u[<mode>]`::
`--untracked-files[=<mode>]`::
	A nem követett fájlok megjelenítése.
+
--
A mode paraméter a nem követett fájlok kezelésének megadására szolgál.
Opcionális: alapból `all`, és ha meg van adva, az
opcióhoz kell ragadnia (pl. `-uno`, de nem `-u no`).

A lehetséges opciók a következők:

`no`:: Egyetlen nem követett fájlt sem jelenít meg.
`normal`:: Nem követett fájlokat és könyvtárakat jelenít meg.
`all`:: A nem követett könyvtárakban lévő egyedi fájlokat is megjeleníti.

Ha a `-u` opció nincs használva, a nem követett fájlok és könyvtárak
megjelennek (azaz ugyanaz, mintha a `normal`-t adnád meg), hogy segítsen elkerülni,
hogy elfelejtsd hozzáadni az újonnan létrehozott fájlokat.  Mivel extra munkát igényel
a nem követett fájlok megtalálása a fájlrendszerben, ez a mód eltarthat egy
ideig egy nagy working tree-ben.
Fontold meg az untracked cache és a split index engedélyezését, ha támogatott (lásd
`git update-index --untracked-cache` és `git update-index
--split-index`), egyébként használhatod a `no`-t, hogy a `git status`
gyorsabban térjen vissza a nem követett fájlok megjelenítése nélkül.
A logikai `true` érték minden szokásos írásmódja `normal`-ként,
a `false` pedig `no`-ként van értelmezve.

Az alapértelmezés megváltoztatható a `status.showUntrackedFiles`
konfigurációs változóval, amely a linkgit:git-config[1] oldalon van dokumentálva.
--

`--ignore-submodules[=<when>]`::
	A submodule-ok változtatásainak figyelmen kívül hagyása a változtatások keresésekor. A _<when>_ lehet
	`none`, `untracked`, `dirty` vagy `all`, amely az alapértelmezés.
`none`;; a submodule-t módosítottnak tekinti, ha vagy nem
	követett vagy módosított fájlokat tartalmaz, vagy a HEAD-je eltér a szuperprojektben rögzített
	commit-tól, és felülírhatja az `ignore` opció beállításait a
	linkgit:git-config[1] vagy linkgit:gitmodules[5] oldalon.
`untracked`;; a submodule-ok nem tekintendők dirtynek, ha csak
	nem követett tartalmat tartalmaznak (de továbbra is átvizsgálják módosított
	tartalomért).
`dirty`;; figyelmen kívül hagyja a submodule-ok work tree-jének összes változtatását,
	csak a szuperprojektben tárolt commitok változtatásai jelennek meg (ez volt
	a viselkedés az 1.7.0 előtt).
`all`;; elrejti a submodule-ok összes változtatását
	(és elnyomja a submodule-összegzések kimenetét, amikor a
	`status.submoduleSummary` config-opció be van állítva).

`--ignored[=<mode>]`::
	A figyelmen kívül hagyott fájlok megjelenítése is.
+
--
A mode paraméter a figyelmen kívül hagyott fájlok kezelésének megadására szolgál.
Opcionális: alapból `traditional`.

A lehetséges opciók a következők:

`traditional`:: Figyelmen kívül hagyott fájlokat és könyvtárakat jelenít meg, hacsak
a `--untracked-files=all` nincs megadva, ebben az esetben
 a figyelmen kívül hagyott könyvtárakban lévő egyedi fájlok
 jelennek meg.
`no`:: Egyetlen figyelmen kívül hagyott fájlt sem jelenít meg.
`matching`:: Egy ignore-mintára illeszkedő figyelmen kívül hagyott fájlokat és
könyvtárakat jelenít meg.
+
Azok az útvonalak jelennek meg, amelyek kifejezetten illeszkednek egy
ignore-mintára. Ha egy könyvtár illeszkedik egy ignore-mintára,
akkor megjelenik, de a figyelmen kívül hagyott könyvtárban lévő útvonalak nem. Ha
egy könyvtár nem illeszkedik egy ignore-mintára, de a teljes tartalma
figyelmen kívül van hagyva, akkor a könyvtár nem jelenik meg, de a teljes tartalma megjelenik.
--

`-z`::
	A bejegyzések lezárása _NUL_-lal, _LF_ helyett.  Ez magában foglalja
	a `--porcelain=v1` kimeneti formátumot, ha nincs más formátum megadva.

`--column[=<options>]`::
`--no-column`::
	A nem követett fájlok oszlopokban való megjelenítése. Az opció-szintaxisért lásd a
	`column.status` konfigurációs változót. A `--column` és `--no-column`
	opciók nélkül az `always` és a `never` értékkel
	egyenértékű, sorrendben.

`--ahead-behind`::
`--no-ahead-behind`::
	A branch upstream branchéhez viszonyított részletes ahead/behind számok
	megjelenítése vagy nem megjelenítése.  Alapból `true`.

`--renames`::
`--no-renames`::
	Az átnevezés-felismerés be- vagy kikapcsolása a felhasználói konfigurációtól függetlenül.
	Lásd még a linkgit:git-diff[1] `--no-renames` opcióját.

`--find-renames[=<n>]`::
	Az átnevezés-felismerés bekapcsolása, opcionálisan beállítva a
	hasonlósági küszöböt.
	Lásd még a linkgit:git-diff[1] `--find-renames` opcióját.

`<pathspec>...`::
	Lásd a 'pathspec' bejegyzést a linkgit:gitglossary[7] oldalon.

OUTPUT
------
Ennek a parancsnak a kimenete arra van tervezve, hogy commit-sablon
kommentként használják.
Az alapértelmezett, hosszú formátum úgy van megtervezve, hogy ember által olvasható,
részletes és leíró jellegű legyen.  A tartalma és a formátuma bármikor
megváltozhat.

A kimenetben említett útvonalak, sok más Git-paranccsal ellentétben, az
aktuális könyvtárhoz képest relatívvá válnak, ha egy alkönyvtárban dolgozol (ez
szándékos, hogy segítse a kivágást és beillesztést). Lásd
a status.relativePaths config-opciót lentebb.

[[_short_format]]
Rövid formátum
~~~~~~~~~~~~~~

Rövid formátumban minden útvonal állapota a következő formák egyikeként
jelenik meg

	<xy> <path>
	<xy> <orig-path> -> <path>

ahol az _<orig-path>_ az, ahonnan az átnevezett/másolt tartalom
származik. Az _<orig-path>_ csak akkor jelenik meg, ha a bejegyzés át van nevezve vagy
másolva. Az _<xy>_ egy kétbetűs `XY` állapotkód.

A mezők (beleértve a `->`-t is) egyetlen szóközzel vannak elválasztva
egymástól. Ha egy fájlnév whitespace-t vagy más nem nyomtatható
karaktereket tartalmaz, az adott mező C sztring literál módjára lesz
idézőjelezve: ASCII kettős idézőjel (34) karakterekkel körülvéve, és a
belső speciális karakterek backslash-sel escape-elve.

Ezzel a formátummal háromféle állapot jelenik meg, és
mindegyik másképp használja az _<xy>_ szintaxist:

* Amikor egy merge folyamatban van, és a merge sikeres volt, vagy egy merge-helyzeten
	kívül, az `X` az index állapotát, az `Y` pedig a
	working tree állapotát mutatja.
* Amikor egy merge-konfliktus történt, és még nincs feloldva, az `X` és `Y`
	a merge egyes headjei által bevezetett állapotot mutatja, a közös
	őshöz viszonyítva. Ezekről az útvonalakról azt mondjuk, hogy _unmerged_ (nem merge-elt).
* Amikor egy útvonal nem követett, az `X` és `Y` mindig ugyanaz, mivel
	ismeretlenek az index számára. A `??` a nem követett útvonalakhoz van használva. A figyelmen kívül hagyott fájlok
	nincsenek felsorolva, hacsak nincs használva a `--ignored`; ha igen, a figyelmen kívül hagyott fájlokat
	`!!` jelzi.

Vedd figyelembe, hogy a _merge_ kifejezés itt magában foglalja az alapértelmezett
`--merge` stratégiát használó rebase-eket, cherry-pickeket, és bármi mást, ami a merge-gépezetet használja.

A következő táblázatban ez a három osztály külön szakaszokban jelenik meg, és
ezek a karakterek vannak használva az `X` és `Y` mezőkhöz az első két, követett útvonalakat
mutató szakaszban:

' ':: változatlan
`M`:: módosítva
`T`:: fájltípus megváltozott (normál fájl, szimbolikus link vagy submodule)
`A`:: hozzáadva
`D`:: törölve
`R`:: átnevezve
`C`:: másolva (ha a status.renames config-opció "copies"-ra van állítva)
`U`:: frissítve, de nem merge-elve

[cols="^1m,^1m,<2",options="header"]
|===
|X        |  Y     |Jelentés
|         |[AMD]   |nincs frissítve
|M        |[ MTD]  |frissítve az indexben
|T        |[ MTD]  |típus megváltozott az indexben
|A        |[ MTD]  |hozzáadva az indexhez
|D        |        |törölve az indexből
|R        |[ MTD]  |átnevezve az indexben
|C        |[ MTD]  |másolva az indexben
|[MTARC]  |        |index és work tree megegyezik
|[ MTARC] |M       |work tree megváltozott az index óta
|[ MTARC] |T       |típus megváltozott a work tree-ben az index óta
|[ MTARC] |D       |törölve a work tree-ben
|         |R       |átnevezve a work tree-ben
|         |C       |másolva a work tree-ben
|D        |D       |nem merge-elt, mindkettő törölve
|A        |U       |nem merge-elt, mi adtuk hozzá
|U        |D       |nem merge-elt, ők törölték
|U        |A       |nem merge-elt, ők adták hozzá
|D        |U       |nem merge-elt, mi töröltük
|A        |A       |nem merge-elt, mindkettő hozzáadva
|U        |U       |nem merge-elt, mindkettő módosítva
|?        |?       |nem követett
|!        |!       |figyelmen kívül hagyva
|===

A submodule-oknak több állapotuk van, és ehelyett a következőket jelentik

`M`:: a submodule-nak más HEAD-je van, mint ami az indexben rögzítve van
`m`:: a submodule-nak módosított tartalma van
`?`:: a submodule-nak nem követett fájljai vannak

Ez azért van, mert egy submodule módosított tartalma vagy nem követett fájljai nem
adhatók hozzá a `git add` paranccsal a szuperprojektben egy commit előkészítéséhez.

Az `m` és `?` rekurzívan van alkalmazva. Például ha egy submodule-ban lévő
beágyazott submodule tartalmaz egy nem követett fájlt, ez is `?`-ként jelenik meg.

Ha a `-b` van használva, a rövid formátumú állapotot egy sor előzi meg

[synopsis]
{empty}## <branchname> <tracking-info>


[[_porcelain_format_version_1]]
Porcelain formátum, 1. verzió
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Az 1. verziójú porcelain formátum hasonló a rövid formátumhoz, de garantáltan
nem változik visszafelé nem kompatibilis módon a Git-verziók között vagy
a felhasználói konfiguráció alapján. Ez ideálissá teszi szkriptek általi elemzésre.
A fenti rövid formátum leírása a porcelain
formátumot is leírja, néhány kivétellel:

1. A felhasználó `color.status` konfigurációja nincs figyelembe véve; a szín
   mindig ki lesz kapcsolva.

2. A felhasználó `status.relativePaths` konfigurációja nincs figyelembe véve; a
   megjelenített útvonalak mindig a repository gyökeréhez képest relatívak lesznek.

Van egy alternatív `-z` formátum is, amelyet gépi elemzéshez ajánlanak. Ebben
a formátumban az állapotmező ugyanaz, de néhány más dolog
megváltozik.  Először, a `->` kimarad az átnevezési bejegyzésekből, és a mező
sorrendje megfordul (pl. a `from -> to` `to from`-má válik). Másodszor, minden fájlnevet egy _NUL_
(ASCII 0) követ, amely szóköz helyett mezőelválasztóként
és a lezáró sortörés helyett szolgál (de egy szóköz továbbra is elválasztja az állapot-
mezőt az első fájlnévtől).  Harmadszor, a speciális
karaktereket tartalmazó fájlnevek nincsenek speciálisan formázva; nincs idézőjelezés vagy
backslash-escapelés.

Bármely submodule-változtatás módosítottként (`M`) van jelentve, nem `m`-ként vagy önálló `?`-ként.

[[_porcelain_format_version_2]]
Porcelain formátum, 2. verzió
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

A 2. verziójú formátum részletesebb információt ad a worktree
állapotáról és a megváltozott elemekről.  A 2. verzió emellett egy bővíthető,
könnyen elemezhető opcionális fejléc-készletet is definiál.

A fejlécsorok `#`-tal kezdődnek, és bizonyos parancssori argumentumokra
válaszul kerülnek hozzáadásra.  Az elemzőknek figyelmen kívül kell hagyniuk
azokat a fejléceket, amelyeket nem ismernek fel.

[[_branch_headers]]
Branch-fejlécek
^^^^^^^^^^^^^^^

Ha a `--branch` meg van adva, egy sor fejlécsor kerül kiírásra az
aktuális branchről szóló információval.

[cols="<1,<1",options="header"]
|===
|Sor                                      |Megjegyzések
|`# branch.oid <commit> \| (initial)`     |Aktuális commit.
|`# branch.head <branch> \| (detached)`   |Aktuális branch.
|`# branch.upstream <upstream-branch>`    |Ha az upstream be van állítva.
|`# branch.ab +<ahead> -<behind>`         |Ha az upstream be van állítva, és
					  a commit jelen van.
|===

[[_stash_information]]
Stash-információ
^^^^^^^^^^^^^^^^

Ha a `--show-stash` meg van adva, egy sor kerül kiírásra, amely megmutatja a
stash-bejegyzések számát, ha az nem nulla:

    # stash <N>

[[_changed_tracked_entries]]
Megváltozott követett bejegyzések
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A fejlécek után egy sor sor kerül kiírásra a követett
bejegyzésekhez.  Háromféle sorformátum egyike használható egy bejegyzés
leírására, a változtatás típusától függően.  A követett bejegyzések
meghatározatlan sorrendben kerülnek kiírásra; az elemzőknek fel kell készülniük a 3
sortípus tetszőleges sorrendű keveredésére.

A hétköznapi megváltozott bejegyzések formátuma a következő:

[synopsis]
1 <XY> <sub> <mH> <mI> <mW> <hH> <hI> <path>

Az átnevezett vagy másolt bejegyzések formátuma a következő:

[synopsis]
2 <XY> <sub> <mH> <mI> <mW> <hH> <hI> <X><score> <path><sep><origPath>

[cols="<1,<1a",options="header"]
|===
|Mező        | Jelentés

|_<XY>_
|Egy 2 karakteres mező, amely a rövid formátumban leírt
stage-elt és nem stage-elt XY értékeket tartalmazza,
a változatlant "." jelöli szóköz
helyett.
|_<sub>_
|Egy 4 karakteres mező, amely a submodule állapotát írja le.
"N..." amikor a bejegyzés nem submodule.
`S<c><m><u>` amikor a bejegyzés submodule.

* Az _<c>_ "C", ha a commit megváltozott; egyébként ".".
* Az _<m>_ "M", ha vannak követett változtatásai; egyébként ".".
* Az _<u>_ "U", ha vannak nem követett változtatások; egyébként ".".
|_<mH>_       |A HEAD-ben lévő oktális fájlmód.
|_<mI>_       |Az indexben lévő oktális fájlmód.
|_<mW>_       |A worktree-ben lévő oktális fájlmód.
|_<hH>_       |A HEAD-ben lévő objektumnév.
|_<hI>_       |Az indexben lévő objektumnév.
|_<X><score>_ |Az átnevezési vagy másolási pontszám (a mozgatás vagy másolás
forrása és célja közötti hasonlóság százalékát
jelöli). Például "R100" vagy "C75".
|_<path>_
|Az útvonalnév.  Egy átnevezett/másolt bejegyzésben ez a célútvonal.
|_<sep>_
|Amikor a `-z` opció van használva, a 2 útvonalnevet egy _NUL_
(ASCII 0x00) bájt választja el; egyébként egy _TAB_ (ASCII 0x09)
bájt választja el őket.
|_<origPath>_
|Az útvonalnév a HEAD-nél lévő commitban vagy az indexben.
Ez csak egy átnevezett/másolt bejegyzésben van jelen, és
megmondja, honnan származik az átnevezett/másolt tartalom.
|===

A nem merge-elt bejegyzések formátuma a következő; az első karakter egy
"u", hogy megkülönböztesse a hétköznapi megváltozott bejegyzésektől.

[synopsis]
u <XY> <sub> <m1> <m2> <m3> <mW> <h1> <h2> <h3> <path>

[cols="<1,<1a",options="header"]
|===
|Mező        |Jelentés
|_<XY>_      |Egy 2 karakteres mező, amely a konfliktus típusát írja le,
	    ahogy a rövid formátumban le van írva.
|_<sub>_     |Egy 4 karakteres mező, amely a submodule állapotát írja le,
	    ahogy fentebb le van írva.
|_<m1>_      |Az 1. stage-ben lévő oktális fájlmód.
|_<m2>_      |A 2. stage-ben lévő oktális fájlmód.
|_<m3>_      |A 3. stage-ben lévő oktális fájlmód.
|_<mW>_      |A worktree-ben lévő oktális fájlmód.
|_<h1>_      |Az 1. stage-ben lévő objektumnév.
|_<h2>_      |A 2. stage-ben lévő objektumnév.
|_<h3>_      |A 3. stage-ben lévő objektumnév.
|_<path>_    |Az útvonalnév.
|===

[[_other_items]]
Egyéb elemek
^^^^^^^^^^^^

A követett bejegyzések után (és ha kérték), egy sor sor kerül kiírásra a
worktree-ben talált nem követett, majd figyelmen kívül hagyott elemekhez.

A nem követett elemek formátuma a következő:

    ? <path>

A figyelmen kívül hagyott elemek formátuma a következő:

    ! <path>

[[_pathname_format_notes_and_z]]
Útvonalnév-formátum megjegyzések és a -z
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Amikor a `-z` opció meg van adva, az útvonalnevek úgy vannak kiírva, ahogy vannak,
mindenféle idézőjelezés nélkül, és a sorok egy _NUL_ (ASCII 0x00)
bájttal vannak lezárva.

A `-z` opció nélkül a "szokatlan" karaktereket tartalmazó útvonalnevek
idézőjelezve vannak, ahogy az a `core.quotePath` konfigurációs változónál
el van magyarázva (lásd linkgit:git-config[1]).


CONFIGURATION
-------------

A parancs figyelembe veszi a `color.status` (vagy `status.color` -- ugyanazt
jelentik, és az utóbbi a visszafelé kompatibilitás miatt maradt
meg) és a `color.status.<slot>` konfigurációs változókat
a kimenete színezéséhez.

Ha a `status.relativePaths` config-változó false-ra van állítva, akkor az összes
megjelenített útvonal a repository gyökeréhez képest relatív, nem az aktuális
könyvtárhoz képest.

Ha a `status.submoduleSummary` nem nulla számra vagy true-ra van állítva (ami megegyezik
a -1-gyel vagy egy korlátlan számmal), a submodule-összegzés engedélyezve lesz
a hosszú formátumhoz, és a módosított submodule-ok commitjainak összegzése
megjelenik (lásd a linkgit:git-submodule[1] `--summary-limit` opcióját). Vedd figyelembe,
hogy a status parancs összegzés-kimenete el lesz nyomva minden
submodule-ra, amikor a `diff.ignoreSubmodules` `all`-ra van állítva, vagy csak azokra a
submodule-okra, ahol `submodule.<name>.ignore=all`. Ahhoz, hogy a figyelmen kívül hagyott
submodule-ok összegzését is megnézd, használhatod a `--ignore-submodules=dirty` parancssori
opciót, vagy a 'git submodule summary' parancsot, amely hasonló
kimenetet mutat, de nem veszi figyelembe ezeket a beállításokat.

BACKGROUND REFRESH
------------------

Alapból a `git status` automatikusan frissíti az indexet, frissítve
a working tree-ből származó gyorsítótárazott stat-információt, és kiírva az
eredményt. A frissített index kiírása egy olyan optimalizálás, amely nem
feltétlenül szükséges (a `status` maga számítja ki az értékeket, de a
kiírásuk csak azért van, hogy a későbbi programoknak ne kelljen megismételniük a mi
számításunkat). Amikor a `status` a háttérben fut, az írás közben tartott zár
ütközhet más egyidejű folyamatokkal, ami azok meghiúsulását okozhatja.
A `status`-t a háttérben futtató szkripteknek érdemes megfontolniuk a
`git --no-optional-locks status` használatát (a részletekért lásd linkgit:git[1]).

UNTRACKED FILES AND PERFORMANCE
-------------------------------

A `git status` nagyon lassú lehet nagy worktree-kben, ha/amikor
nem követett fájlokat és könyvtárakat kell keresnie. Sok
konfigurációs opció áll rendelkezésre ennek felgyorsítására, akár a munka
elkerülésével, akár a korábbi Git-parancsok gyorsítótárazott eredményeinek felhasználásával. Nincs
egyetlen optimális beállításkészlet, amely mindenkinek megfelelne. Felsoroljuk
a releváns opciók összefoglalóját, hogy segítsünk, de mielőtt a listára térnénk,
érdemes lehet újra futtatni a `git status`-t, mert a konfigurációd
gyorsítótárazhatja már a `git status` eredményeit, így gyorsabb lehet a további futtatásoknál.

* A `--untracked-files=no` flag vagy a
	`status.showUntrackedFiles=no` config (mindkettőt lásd fentebb):
	azt jelzi, hogy a `git status` ne jelentsen nem követett
	fájlokat. Ez a leggyorsabb opció. A `git status` nem fogja felsorolni
	a nem követett fájlokat, így oda kell figyelned, hogy emlékezz, ha
	új fájlokat hozol létre, és kézzel `git add`-old őket.

* `advice.statusUoption=false` (lásd linkgit:git-config[1]):
	ennek a változónak `false`-ra állítása letiltja azt a figyelmeztető üzenetet,
	amely akkor jelenik meg, amikor a nem követett fájlok felsorolása 2
	másodpercnél tovább tart.  Egy nagy projektben ez tovább tarthat, és a felhasználó
	esetleg már elfogadta ezt a kompromisszumot (pl. a `-uno` használata nem biztos, hogy
	elfogadható opció a felhasználó számára), ebben az esetben nincs
	értelme kiadni a figyelmeztető üzenetet, és ilyen esetben
	a figyelmeztetés letiltása lehet a legjobb.

* `core.untrackedCache=true` (lásd linkgit:git-update-index[1]):
	engedélyezi az untracked cache funkciót, és csak azokat a könyvtárakat
	keresi, amelyek megváltoztak az előző `git status` parancs óta.
	A Git megjegyzi az egyes könyvtárakon belüli nem követett fájlok halmazát,
	és feltételezi, hogy ha egy könyvtár nem változott, akkor
	a benne lévő nem követett fájlok halmaza sem változott.  Ez sokkal
	gyorsabb, mint minden könyvtár tartalmának felsorolása, de nem
	költségmentes, mert a Gitnek még mindig meg kell keresnie a
	megváltozott könyvtárak halmazát. Az untracked cache a
	`.git/index` fájlban van tárolva. A nem követett
	fájlok keresésének csökkentett költségét kissé ellensúlyozza az index megnövekedett mérete és
	a naprakészen tartás költsége. Az a csökkentett keresési idő
	általában megéri a további méretet.

* `core.untrackedCache=true` és `core.fsmonitor=true` vagy
	`core.fsmonitor=<hook-command-pathname>` (lásd
	linkgit:git-update-index[1]): engedélyezi mind az untracked cache,
	mind az FSMonitor funkciókat, és csak azokat a könyvtárakat keresi, amelyek
	megváltoztak az előző `git status` parancs óta.  Ez
	gyorsabb, mint csak az untracked cache önmagában, mert
	a Git a megváltozott könyvtárak keresését is elkerülheti.  A Gitnek
	csak azt a pontos könyvtárhalmazt kell felsorolnia, amely nemrég
	megváltozott. Bár az FSMonitor funkció engedélyezhető az untracked cache
	nélkül is, az előnyök ebben az esetben nagymértékben csökkennek.

Vedd figyelembe, hogy miután bekapcsolod az untracked cache-t és/vagy az FSMonitor
funkciókat, eltarthat néhány `git status` parancsig, amíg a különböző
gyorsítótárak felmelegednek, mielőtt javuló parancsidőket látnál.  Ez
normális.

SEE ALSO
--------
linkgit:gitignore[5]

GIT
---
A linkgit:git[1] csomag része
