git-send-email(1)
=================

NAME
----
git-send-email - Patchek egy csoportjának e-mailben történő elküldése


SYNOPSIS
--------
[synopsis]
git send-email [<options>] (<file>|<directory>)...
git send-email [<options>] <format-patch-options>
git send-email --dump-aliases
git send-email --translate-aliases


DESCRIPTION
-----------
A parancssorban megadott patcheket fogja, és e-mailben elküldi őket.
A patchek megadhatók fájlokként, könyvtárakként (ekkor a könyvtárban lévő
összes fájl elküldésre kerül), vagy közvetlenül revíziólistaként. Az utóbbi
esetben bármilyen, a linkgit:git-format-patch[1] által elfogadott formátum
átadható a `git send-email` parancsnak, csakúgy, mint a
linkgit:git-format-patch[1] által értelmezett opciók.

Az e-mail fejléce parancssori opciókkal konfigurálható. Ha nincs megadva a
parancssorban, a felhasználót egy ReadLine-t használó felület kéri majd a
szükséges adatok megadására.

A patch-fájloknak két elfogadott formátuma van:

1. mbox formátumú fájlok
+
Ezt a linkgit:git-format-patch[1] állítja elő. A legtöbb fejlécet és a MIME
formázást figyelmen kívül hagyja.

2. Greg Kroah-Hartman `send_lots_of_email.pl` szkriptje által használt
   eredeti formátum
+
Ez a formátum azt várja, hogy a fájl első sora tartalmazza a `Cc:` értéket,
a második sor pedig az üzenet `Subject:` sorát.


OPTIONS
-------

[[_composing]]
Összeállítás
~~~~~~~~~~~~

`--annotate`::
	Tekintsd át és szerkeszd az egyes elküldeni kívánt patcheket. Az
	alapérték a `sendemail.annotate` értéke. Lásd a CONFIGURATION
	szekciót a `sendemail.multiEdit` opcióhoz.

`--bcc=<address>,...`::
	Adj meg egy `Bcc:` értéket minden e-mailhez. Az alapérték a
	`sendemail.bcc` értéke.
+
Ez az opció többször is megadható.

`--cc=<address>,...`::
	Adj meg egy kezdeti `Cc:` értéket minden e-mailhez.
	Az alapérték a `sendemail.cc` értéke.
+
Ez az opció többször is megadható.

`--compose`::
	Hívj meg egy szövegszerkesztőt (lásd a GIT_EDITOR-t a
	linkgit:git-var[1]-ben) a patch-sorozathoz tartozó bevezető üzenet
	szerkesztéséhez.
+
Ha a `--compose` van használatban, a `git send-email` az üzenetben megadott
`From`, `To`, `Cc`, `Bcc`, `Subject`, `Reply-To` és `In-Reply-To` fejléceket
fogja használni. Ha az üzenet törzse (amit a fejlécek és egy üres sor után
gépelsz be) csak üres (vagy `Git:` előtaggal kezdődő) sorokat tartalmaz, az
összefoglaló nem kerül elküldésre, de a fent említett fejlécek felhasználásra
kerülnek, hacsak nem lettek eltávolítva.
+
A hiányzó `From` vagy `In-Reply-To` fejlécekre rá fog kérdezni.
+
Lásd a CONFIGURATION szekciót a `sendemail.multiEdit` opcióhoz.

`--from=<address>`::
	Add meg az e-mailek küldőjét. Ha nincs megadva a parancssorban, a
	`sendemail.from` konfigurációs opció értéke kerül felhasználásra. Ha
	sem a parancssori opció, sem a `sendemail.from` nincs beállítva, a
	felhasználót kérdezi meg az értékről. A kérdés alapértéke a
	`GIT_AUTHOR_IDENT`, vagy ha az nincs beállítva, a `GIT_COMMITTER_IDENT`
	értéke lesz, ahogy azt a `git var -l` visszaadja.

`--reply-to=<address>`::
	Add meg azt a címet, ahová a címzettek válaszainak érkezniük kell.
	Ezt akkor használd, ha az üzenetekre érkező válaszoknak más címre
	kell mennie, mint amit a `--from` paraméter megad.

`--in-reply-to=<identifier>`::
	Az első levelet (vagy `--no-thread` esetén az összes levelet) a
	megadott Message-ID-re adott válaszként jeleníti meg, ami elkerüli a
	témaszálak megszakítását egy új patch-sorozat közlésekor.
	A második és az azt követő e-mailek a `--[no-]chain-reply-to`
	beállításnak megfelelően kerülnek elküldésre válaszként.
+
Így például amikor a `--thread` és a `--no-chain-reply-to` van megadva, a
második és az azt követő patchek az elsőre adott válaszok lesznek, ahogy azt
az alábbi ábra mutatja, ahol a `[PATCH v2 0/3]` a `[PATCH 0/2]`-re adott
válasz:
+
  [PATCH 0/2] Here is what I did...
    [PATCH 1/2] Clean up and tests
    [PATCH 2/2] Implementation
    [PATCH v2 0/3] Here is a reroll
      [PATCH v2 1/3] Clean up
      [PATCH v2 2/3] New tests
      [PATCH v2 3/3] Implementation
+
Csak akkor szükséges, ha a `--compose` is be van állítva. Ha a `--compose`
nincs beállítva, erre rá fog kérdezni.

`--outlook-id-fix`::
`--no-outlook-id-fix`::
	A Microsoft Outlook SMTP-szerverei eldobják az e-mailben elküldött
	Message-ID-t, és egy új, véletlenszerű Message-ID-t rendelnek hozzá,
	ezzel megszakítva a témaszálakat.
+
A `--outlook-id-fix` opcióval a `git send-email` egy, az Outlook
szerverekre jellemző mechanizmust használ, hogy megtudja, a szerver milyen
Message-ID-t rendelt hozzá, és ezzel javítsa a szálazást. Csak akkor
használd, ha tudod, hogy a szerver ugyanúgy adja vissza az átírt
Message-ID-t, mint az Outlook szerverek.
+
Ha ez az opció nincs megadva, a javítás alapértelmezetten megtörténik, ha a
`smtp.office365.com` vagy a `smtp-mail.outlook.com` szerverrel kommunikál.
Használd a `--no-outlook-id-fix` opciót, ha ezt ki akarod kapcsolni akkor is,
amikor ezzel a két szerverrel kommunikál.

`--subject=<string>`::
	Add meg az e-mail témaszál kezdeti tárgyát.
	Csak akkor szükséges, ha a `--compose` is be van állítva. Ha a
	`--compose` nincs beállítva, erre rá fog kérdezni.

`--to=<address>,...`::
	Add meg a generált e-mailek elsődleges címzettjét. Általában ez az
	érintett projekt upstream maintainere. Az alapérték a `sendemail.to`
	konfigurációs érték; ha az nincs megadva, és a `--to-cmd` sincs
	megadva, erre rá fog kérdezni.
+
Ez az opció többször is megadható.

`--8bit-encoding=<encoding>`::
	Ha nem ASCII üzenettel vagy tárggyal találkozik, amely nem deklarálja
	a kódolását, fejléceket/idézést ad hozzá annak jelzésére, hogy az
	_<encoding>_ kódolással van kódolva. Az alapérték a
	`sendemail.assume8bitEncoding` értéke; ha az nincs megadva, erre
	rá fog kérdezni, ha bármilyen nem ASCII fájllal találkozik.
+
Megjegyzés: semmilyen kísérlet nem történik a kódolás ellenőrzésére.

`--compose-encoding=<encoding>`::
	Add meg a compose-üzenet kódolását. Az alapérték a
	`sendemail.composeEncoding` értéke; ha az nincs megadva, UTF-8-at
	feltételez.

`--transfer-encoding=(7bit|8bit|quoted-printable|base64|auto)`::
	Add meg az SMTP-n keresztül küldött üzenethez használandó
	átviteli kódolást. A `7bit` hibázik, ha nem ASCII üzenettel
	találkozik. A `quoted-printable` akkor hasznos, ha a repository
	kocsivissza-karaktereket tartalmazó fájlokat tartalmaz, de ettől a
	nyers patch e-mail fájl (ahogy egy MUA-ból elmentve van) sokkal
	nehezebben ellenőrizhető kézzel. A `base64` még inkább hibatűrő, de
	még átláthatatlanabb is. Az `auto` a `8bit`-et használja, amikor
	lehetséges, egyébként a `quoted-printable`-t.
+
Az alapérték a `sendemail.transferEncoding` konfigurációs érték; ha az
nincs megadva, az alapértelmezés `auto`.

`--xmailer`::
`--no-xmailer`::
	Hozzáadja (vagy megakadályozza a hozzáadását) az `X-Mailer:`
	fejlécnek. Alapértelmezésben a fejléc hozzáadásra kerül, de
	kikapcsolható a `sendemail.xmailer` konfigurációs változó `false`-ra
	állításával.

[[_sending]]
Küldés
~~~~~~

`--envelope-sender=<address>`::
	Add meg az e-mailek küldéséhez használt boríték-küldőt (envelope
	sender). Ez akkor hasznos, ha az alapértelmezett címed nem az a
	cím, amely fel van iratkozva egy listára. A `From` cím
	használatához állítsd az értéket `auto`-ra. Ha a `sendmail`
	binárist használod, megfelelő jogosultságokkal kell rendelkezned az
	`-f` paraméterhez. Az alapérték a `sendemail.envelopeSender`
	konfigurációs változó értéke; ha az nincs megadva, a boríték-küldő
	kiválasztása az MTA-dra van bízva.

`--sendmail-cmd=<command>`::
	Add meg egy futtatandó parancsot az e-mail küldéséhez. A parancsnak
	sendmail-szerűnek kell lennie; konkrétan támogatnia kell a `-i`
	opciót. A parancs szükség esetén a shellben kerül végrehajtásra. Az
	alapérték a `sendemail.sendmailCmd` értéke. Ha nincs megadva, és a
	`--smtp-server` sincs megadva, a `git send-email` keresni fogja a
	`sendmail`-t a `/usr/sbin`, `/usr/lib` és a `$PATH` könyvtárakban.

`--smtp-encryption=<encryption>`::
	Add meg, milyen módon kezdődjön a titkosítás az SMTP-kapcsolathoz.
	Érvényes értékek az `ssl` és a `tls`. Bármely más érték egyszerű
	(titkosítatlan) SMTP-re esik vissza, amely alapértelmezetten a 25-ös
	portot használja.
	A nevek ellenére mindkét érték a TLS ugyanazon újabb verzióját
	használja, de történelmi okokból ezeket a neveket viselik. Az `ssl` az
	„implicit" titkosításra utal (néha SMTPS-nek is nevezik), amely
	alapértelmezetten a 465-ös portot használja. A `tls` az „explicit"
	titkosításra utal (gyakran STARTTLS néven ismert), amely
	alapértelmezetten a 25-ös portot használja. Az SMTP-szerver más
	portokat is használhat, amelyek nem az alapértelmezettek. A `tls` és
	a titkosítatlan mód esetén gyakran előforduló alternatív port az 587.
	A saját esetedhez ellenőrizned kell a szolgáltatód dokumentációját
	vagy a szervered konfigurációját. Az alapérték a
	`sendemail.smtpEncryption` értéke.

`--smtp-domain=<FQDN>`::
	Add meg a teljes tartománynevet (Fully Qualified Domain Name, FQDN),
	amelyet a HELO/EHLO parancs használ az SMTP-szerver felé. Egyes
	szerverek megkövetelik, hogy az FQDN megegyezzen az IP-címeddel. Ha
	nincs beállítva, a `git send-email` megpróbálja automatikusan
	meghatározni az FQDN-t. Az alapérték a `sendemail.smtpDomain` értéke.

`--smtp-auth=<mechanisms>`::
	A megengedett SMTP-AUTH mechanizmusok szóközzel elválasztott listája.
	Ez a beállítás rákényszeríti, hogy csak a felsorolt mechanizmusok
	legyenek használva. Példa:
+
------
$ git send-email --smtp-auth="PLAIN LOGIN GSSAPI" ...
------
+
Ha a megadott mechanizmusok közül legalább egy megegyezik az SMTP-szerver
által hirdetettek valamelyikével, és azt a használt SASL-könyvtár is
támogatja, az adott mechanizmus kerül felhasználásra a hitelesítéshez. Ha
sem a `sendemail.smtpAuth`, sem a `--smtp-auth` nincs megadva, a
SASL-könyvtár által támogatott összes mechanizmus használható. A speciális
`none` érték megadható a hitelesítés teljes letiltásához, függetlenül a
`--smtp-user`-től.

`--smtp-pass[=<password>]`::
	Jelszó az SMTP-AUTH-hoz. Az argumentum opcionális: ha nincs
	argumentum megadva, az üres sztring kerül felhasználásra
	jelszóként. Az alapérték a `sendemail.smtpPass` értéke, azonban a
	`--smtp-pass` mindig felülírja ezt az értéket.
+
Továbbá a jelszavakat nem kell megadni sem konfigurációs fájlokban, sem a
parancssorban. Ha meg lett adva egy felhasználónév (a `--smtp-user`
opcióval vagy a `sendemail.smtpUser`-rel), de nincs megadva jelszó (a
`--smtp-pass` opcióval vagy a `sendemail.smtpPass`-szal), akkor a jelszó a
linkgit:git-credential[1] segítségével kerül lekérésre.

`--no-smtp-auth`::
	Letiltja az SMTP-hitelesítést. Rövidítés a `--smtp-auth=none`-ra.

`--smtp-server=<host>`::
	Add meg a használandó kimenő SMTP-szervert (pl. `smtp.example.com`
	vagy egy nyers IP-cím). Ha nincs megadva, és a `--sendmail-cmd` sincs
	megadva, az alapértelmezés a `sendmail` keresése a `/usr/sbin`,
	`/usr/lib` és a `$PATH` könyvtárakban, ha ilyen program elérhető,
	egyébként visszaesik a `localhost`-ra.
+
Visszafelé kompatibilitás céljából ez az opció megadhatja egy
sendmail-szerű program teljes elérési útját is; a programnak támogatnia
kell a `-i` opciót. Ez a módszer nem támogatja argumentumok átadását vagy
egyszerű parancsnevek használatát. Ezekre az esetekre inkább a
`--sendmail-cmd` használatát fontold meg.

`--smtp-server-port=<port>`::
	Add meg egy, az alapértelmezett porttól eltérő portot (az
	SMTP-szerverek jellemzően a 25-ös smtp porton figyelnek, de a 587-es
	submission porton vagy a gyakori SSL smtp porton, a 465-ösön is
	figyelhetnek); szimbolikus portnevek (pl. `submission` 587 helyett)
	is elfogadottak. A port a `sendemail.smtpServerPort` konfigurációs
	változóval is beállítható.

`--smtp-server-option=<option>`::
	Add meg a használandó kimenő SMTP-szerver-opciót.
	Az alapértéket a `sendemail.smtpServerOption` konfigurációs opció
	adhatja meg.
+
A `--smtp-server-option` opciót minden, a szervernek átadni kívánt
opcióhoz meg kell ismételni. Hasonlóképpen, a konfigurációs fájlokban is
külön sort kell használni minden opcióhoz.

`--smtp-ssl`::
	Örökölt (legacy) alias a `--smtp-encryption ssl`-hez.

`--smtp-ssl-cert-path <path>`::
	Elérési út a megbízható CA-tanúsítványok tárolójához az SMTP
	SSL/TLS-tanúsítvány ellenőrzéséhez (vagy egy `c_rehash`-sel
	feldolgozott könyvtár, vagy egy fájl, amely egy vagy több, egymás
	után fűzött PEM formátumú tanúsítványt tartalmaz: lásd a
	`-CAfile <file>` és a `-CApath <dir>` opciók leírását az
	https://docs.openssl.org/master/man1/openssl-verify/
	[OpenSSL verify(1) man page-én] további információkért ezekről).
	Állítsd üres sztringre a tanúsítvány-ellenőrzés letiltásához. Az
	alapérték a `sendemail.smtpSSLCertPath` konfigurációs változó
	értéke, ha be van állítva, egyébként a mögöttes SSL-könyvtár
	fordításba beépített alapértéke (ami a legtöbb platformon a legjobb
	választás kell legyen).

`--smtp-ssl-client-cert <path>`::
	Elérési út az ügyfél-tanúsítvány fájlhoz, amelyet be kell mutatni,
	ha a szerver ezt kéri. Ez az opció szükséges, ha a szerver
	ügyfél-tanúsítványok ellenőrzésére van beállítva. Ha a megfelelő
	privát kulcs nincs a fájlban, azt a `sendemail.smtpSSLClientKey`
	konfigurációs változóval vagy a `--smtp-ssl-client-key` opcióval
	kell megadni. Az alapérték a `sendemail.smtpSSLClientCert`
	konfigurációs változó értéke, ha be van állítva.

`--smtp-ssl-client-key <path>`::
	Elérési út az ügyfél-tanúsítványhoz tartozó ügyfél-privátkulcs
	fájlhoz. A hibás konfiguráció elkerülése végett ezt az opciót a
	`sendemail.smtpSSLClientKey` konfigurációs változóval vagy a
	`--smtp-ssl-client-cert` opcióval együtt kell használni. Ha az
	ügyfélkulcs benne van az ügyfél-tanúsítványban, a privát kulcs
	kiválasztása a tanúsítvány formátumától függ. További részletekért
	látogass el a https://metacpan.org/pod/IO::Socket::SSL oldalra. Az
	alapérték a `sendemail.smtpSSLClientKey` konfigurációs változó
	értéke, ha be van állítva.

`--smtp-user=<user>`::
	Felhasználónév az SMTP-AUTH-hoz. Az alapérték a
	`sendemail.smtpUser` értéke; ha nincs megadva felhasználónév (a
	`--smtp-user` opcióval vagy a `sendemail.smtpUser`-rel), akkor nem
	történik hitelesítési kísérlet.

`--smtp-debug=(0|1)`::
	Bekapcsolja (1) vagy kikapcsolja (0) a debug kimenetet. Ha be van
	kapcsolva, az SMTP-parancsok és -válaszok kiíródnak. Hasznos a
	TLS-kapcsolat és a hitelesítési problémák debuggolásához.

`--imap-sent-folder=<folder>`::
	Néhány e-mail-szolgáltató (pl. iCloud) nem küldi el az SMTP-n
	keresztül elküldött e-mailek másolatát a postafiókod `Sent`
	mappájába vagy hasonlóba. Ezzel az opcióval a `git imap-send`
	segítségével elküldheted az e-mailek másolatát az opcióval megadott
	mappába. A `git imap-send --list` futtatásával lekérheted az
	érvényes mappanevek listáját, beleértve a postafiókod `Sent`
	mappájának pontos nevét is. Ezzel az opcióval az e-maileket egy
	tetszőleges, dedikált IMAP-mappába is küldheted.
+
Ez a funkció megköveteli a `git imap-send` beállítását. Lásd a
linkgit:git-imap-send[1] útmutatót.

`--use-imap-only`::
`--no-use-imap-only`::
	Ha ez be van állítva, minden e-mail csak a `--imap-sent-folder`
	vagy a `sendemail.imapSentFolder` által megadott IMAP-mappába
	kerül másolásra, és nem lesz elküldve a címzetteknek. Hasznos, ha
	csak piszkozatot szeretnél készíteni az e-mailekről, és egy másik
	e-mail-klienssel szeretnéd elküldeni őket.
	Ha a `--no-use-imap-only` opcióval le van tiltva, az e-mailek a
	szokásos módon kerülnek elküldésre. Alapértelmezetten le van
	tiltva, de a `sendemail.useImapOnly` konfigurációs változóval
	bekapcsolható.
+
Ez a funkció megköveteli a `git imap-send` beállítását. Lásd a
linkgit:git-imap-send[1] útmutatót.

`--batch-size=<num>`::
	Néhány e-mail-szerver (pl. `smtp.163.com`) korlátozza a munkamenetenként
	(kapcsolatonként) elküldhető e-mailek számát, ami hibához vezet sok
	üzenet küldésekor. Ezzel az opcióval a send-email _<num>_ üzenet
	elküldése után bontja a kapcsolatot, vár néhány másodpercet (lásd a
	`--relogin-delay` opciót), majd újracsatlakozik, hogy megkerülje ezt
	a korlátot. Érdemes lehet valamilyen credential helpert használnod,
	hogy ne kelljen minden alkalommal újra beírnod a jelszavadat, amikor
	ez megtörténik. Az alapérték a `sendemail.smtpBatchSize`
	konfigurációs változó.

`--relogin-delay=<int>`::
	_<int>_ másodpercig vár, mielőtt újracsatlakozna az SMTP-szerverhez.
	A `--batch-size` opcióval együtt használatos. Az alapérték a
	`sendemail.smtpReloginDelay` konfigurációs változó.

[[_automating]]
Automatizálás
~~~~~~~~~~~~~

`--no-to`::
`--no-cc`::
`--no-bcc`::
	Törli a config-on keresztül korábban beállított `To:`, `Cc:`, `Bcc:`
	címek listáját.

`--no-identity`::
	Törli a config-on keresztül beállított `sendemail.identity` korábban
	beolvasott értékét, ha van ilyen.

`--to-cmd=<command>`::
	Add meg egy parancsot, amelyet patch-fájlonként egyszer kell
	végrehajtani, és amely a patch-fájlra jellemző `To:` bejegyzéseket
	generál. Ennek a parancsnak a kimenete soronként egy e-mail cím
	kell legyen. Az alapérték a `sendemail.toCmd` konfigurációs érték.

`--cc-cmd=<command>`::
	Add meg egy parancsot, amelyet patch-fájlonként egyszer kell
	végrehajtani, és amely a patch-fájlra jellemző `Cc:` bejegyzéseket
	generál. Ennek a parancsnak a kimenete soronként egy e-mail cím
	kell legyen. Az alapérték a `sendemail.ccCmd` konfigurációs érték.

`--header-cmd=<command>`::
	Add meg egy parancsot, amely kimenő üzenetenként egyszer kerül
	végrehajtásra, és RFC 2822 stílusú fejlécsorokat ad ki, amelyeket
	be kell illeszteni az üzenetekbe. Ha a `sendemail.headerCmd`
	konfigurációs változó be van állítva, annak értéke mindig
	felhasználásra kerül. Ha a `--header-cmd` a parancssorban van
	megadva, annak értéke elsőbbséget élvez a `sendemail.headerCmd`
	konfigurációs változóval szemben.

`--no-header-cmd`::
	Letiltja a használatban lévő header-parancsot.

`--chain-reply-to`::
`--no-chain-reply-to`::
	Ha ez be van állítva, minden e-mail az előzőleg elküldött e-mailre
	adott válaszként kerül elküldésre. Ha a `--no-chain-reply-to`
	opcióval le van tiltva, az első utáni összes e-mail az első
	elküldött e-mailre adott válaszként kerül elküldésre. Ennek
	használatakor ajánlott, hogy az elsőként megadott fájl a teljes
	patch-sorozat áttekintése legyen. Alapértelmezetten le van tiltva,
	de a `sendemail.chainReplyTo` konfigurációs változóval
	bekapcsolható.

`--identity=<identity>`::
	Egy konfigurációs identitás. Ha meg van adva, a `sendemail.<identity>`
	alszekcióban lévő értékek elsőbbséget élveznek a `sendemail`
	szekcióban lévő értékekkel szemben. Az alapértelmezett identitás a
	`sendemail.identity` értéke.

`--signed-off-by-cc`::
`--no-signed-off-by-cc`::
	Ha ez be van állítva, hozzáadja a `Signed-off-by` trailerben vagy a
	`Cc:` sorokban talált e-maileket a cc listához. Az alapérték a
	`sendemail.signedOffByCc` konfigurációs érték; ha az nincs megadva,
	az alapértelmezés a `--signed-off-by-cc`.

`--cc-cover`::
`--no-cc-cover`::
	Ha ez be van állítva, a sorozat első patchjének (jellemzően a
	cover letternek) a `Cc:` fejléceiben talált e-mailek hozzáadásra
	kerülnek minden elküldött e-mail cc listájához. Az alapérték a
	`sendemail.ccCover` konfigurációs érték; ha az nincs megadva, az
	alapértelmezés a `--no-cc-cover`.

`--to-cover`::
`--no-to-cover`::
	Ha ez be van állítva, a sorozat első patchjének (jellemzően a
	cover letternek) a `To:` fejléceiben talált e-mailek hozzáadásra
	kerülnek minden elküldött e-mail to listájához. Az alapérték a
	`sendemail.toCover` konfigurációs érték; ha az nincs megadva, az
	alapértelmezés a `--no-to-cover`.

`--suppress-cc=<category>`::
	Add meg a címzettek egy további kategóriáját, amelynek automatikus
	cc-zését ki kell hagyni:
+
--
- `author` kihagyja a patch szerzőjét.
- `self` kihagyja a küldőt.
- `cc` kihagy mindenkit, aki a patch fejlécében lévő Cc sorokban szerepel,
  kivéve saját magát (erre a `self`-et használd).
- `bodycc` kihagy mindenkit, aki a patch törzsében (commit-üzenetben) lévő
  Cc sorokban szerepel, kivéve saját magát (erre a `self`-et használd).
- `sob` kihagy mindenkit, aki a Signed-off-by trailerekben szerepel,
  kivéve saját magát (erre a `self`-et használd).
- `misc-by` kihagy mindenkit, aki az Acked-by, Reviewed-by, Tested-by és
  más „-by" sorokban szerepel a patch törzsében, a Signed-off-by kivételével
  (erre a `sob`-ot használd).
- `cccmd` kihagyja a --cc-cmd futtatását.
- `body` egyenértékű a `sob` + `bodycc` + `misc-by` kombinációval.
- `all` elnyomja az összes automatikus cc-értéket.
--
+
Az alapérték a `sendemail.suppressCc` konfigurációs érték; ha az nincs
megadva, az alapértelmezés `self`, ha a `--suppress-from` meg van adva,
valamint `body`, ha a `--no-signed-off-by-cc` meg van adva.

`--suppress-from`::
`--no-suppress-from`::
	Ha ez be van állítva, ne add hozzá a `From:` címet a `Cc:` listához.
	Az alapérték a `sendemail.suppressFrom` konfigurációs érték; ha az
	nincs megadva, az alapértelmezés a `--no-suppress-from`.

`--thread`::
`--no-thread`::
	Ha ez be van állítva, az `In-Reply-To` és a `References` fejlécek
	hozzáadásra kerülnek minden elküldött e-mailhez. Hogy minden levél
	az előző e-mailre hivatkozik-e (`deep` szálazás, a `git
	format-patch` terminológiája szerint), vagy az első e-mailre
	(`shallow` szálazás), azt a `--[no-]chain-reply-to` szabályozza.
+
Ha a `--no-thread` opcióval le van tiltva, ezek a fejlécek nem kerülnek
hozzáadásra (hacsak nincsenek megadva a `--in-reply-to` opcióval). Az
alapérték a `sendemail.thread` konfigurációs érték; ha az nincs
megadva, az alapértelmezés a `--thread`.
+
A felhasználó felelőssége biztosítani, hogy még ne létezzen In-Reply-To
fejléc, amikor a `git send-email`-t megkérik annak hozzáadására (különösen
vedd figyelembe, hogy a `git format-patch` beállítható úgy, hogy maga
végezze el a szálazást). Ha ezt elmulasztod, előfordulhat, hogy a
címzett MUA-jában nem a várt eredmény jelenik meg.

`--mailmap`::
`--no-mailmap`::
	A mailmap fájl (lásd linkgit:gitmailmap[5]) használata az összes cím
	kanonikus valódi névre és e-mail címre való leképezéséhez. A `git
	send-email`-re jellemző további mailmap-adatok a
	`sendemail.mailmap.file` vagy a `sendemail.mailmap.blob`
	konfigurációs értékekkel adhatók meg. Az alapérték a
	`sendemail.mailmap`.

[[_administering]]
Adminisztráció
~~~~~~~~~~~~~~

`--confirm=<mode>`::
	Megerősítés kérése közvetlenül a küldés előtt:
+
--
- `always` mindig megerősítést kér küldés előtt.
- `never` soha nem kér megerősítést küldés előtt.
- `cc` megerősítést kér küldés előtt, ha a send-email automatikusan
  hozzáadott címeket a patchből a Cc listához.
- `compose` megerősítést kér az első üzenet küldése előtt, amikor a
  --compose van használatban.
- `auto` egyenértékű a `cc` + `compose` kombinációval.
--
+
Az alapérték a `sendemail.confirm` konfigurációs érték; ha az nincs
megadva, az alapértelmezés `auto`, hacsak nincs megadva valamelyik
suppress opció, ebben az esetben az alapértelmezés `compose`.

`--dry-run`::
	Mindent elvégez, kivéve a tényleges e-mailküldést.

`--format-patch`::
`--no-format-patch`::
	Ha egy argumentum értelmezhető akár referenciaként, akár fájlnévként,
	válaszd ki, hogy format-patch argumentumként (`--format-patch`) vagy
	fájlnévként (`--no-format-patch`) legyen értelmezve. Alapértelmezetten,
	ha ilyen ütközés fordul elő, a `git send-email` hibával leáll.

`--quiet`::
	Kevésbé bőbeszédűvé teszi a `git send-email`-t. A kimenetnek csak
	soronként egy e-mailt kell tartalmaznia.

`--validate`::
`--no-validate`::
	Épségellenőrzéseket (sanity check) végez a patcheken.
	Jelenleg az ellenőrzés a következőket jelenti:
+
--
* Meghívja a sendemail-validate hookot, ha az jelen van (lásd
  linkgit:githooks[5]).
* Figyelmeztet a 998 karakternél hosszabb sorokat tartalmazó patchekre,
  hacsak nincs megfelelő átviteli kódolás (`auto`, `base64` vagy
  `quoted-printable`) használatban; ez az SMTP-korlátok miatt szükséges,
  ahogy azt a https://www.ietf.org/rfc/rfc5322.txt leírja.
--
+
Az alapérték a `sendemail.validate`; ha ez nincs beállítva, az
alapértelmezés a `--validate`.

`--force`::
	E-mailek küldése akkor is, ha a biztonsági ellenőrzések ezt
	megakadályoznák.


[[_information]]
Információ
~~~~~~~~~~

`--dump-aliases`::
	A normál működés helyett kiírja a rövidített alias-neveket a
	konfigurált alias-fájl(ok)ból, soronként egyet, ábécésorrendben.
	Megjegyzés: ez csak az alias nevét tartalmazza, a kibontott e-mail
	címeket nem. Lásd a `sendemail.aliasesFile` opciót az aliasokról
	szóló további információkért.

`--translate-aliases`::
	A normál működés helyett a standard bemenetről olvas, és minden sort
	e-mail aliasként értelmez. Lefordítja azt a konfigurált
	alias-fájl(ok) alapján. Minden lefordított nevet és e-mail címet a
	standard kimenetre ír, soronként egyet. Lásd a `sendemail.aliasFile`
	opciót az aliasokról szóló további információkért.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/sendemail.adoc[]

EXAMPLES OF SMTP SERVERS
------------------------
[[_use_gmail_as_the_smtp_server]]
A Gmail használata SMTP-szerverként
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ahhoz, hogy a `git send-email` a Gmail SMTP-szerverén keresztül küldje el a
patcheidet, szerkeszd a `~/.gitconfig` fájlt a fiókbeállításaid megadásához:

----
[sendemail]
	smtpEncryption = ssl
	smtpServer = smtp.gmail.com
	smtpUser = yourname@gmail.com
	smtpServerPort = 465
----

A Gmail nem engedélyezi a szokásos jelszavad használatát a `git
send-email`-hez. Ha be van állítva többfaktoros hitelesítés a Gmail
fiókodon, generálhatsz egy alkalmazás-specifikus jelszót a `git
send-email`-lel való használatra. Látogass el a
https://security.google.com/settings/security/apppasswords oldalra a
létrehozásához.

Alternatívaként, alkalmazás-specifikus jelszó helyett használhatsz
OAuth2.0-hitelesítést is a Gmaillel. Az OAuth2.0 biztonságosabb, mint az
alkalmazás-specifikus jelszavak, és attól függetlenül működik, hogy be
van-e állítva többfaktoros hitelesítés. Az `OAUTHBEARER` és az `XOAUTH2`
gyakori mechanizmusok, amelyeket erre a hitelesítéstípusra használnak. A
Gmail mindkettőt támogatja. Példaként, ha az `OAUTHBEARER`-t szeretnéd
használni, szerkeszd a `~/.gitconfig` fájlodat, és add hozzá a
`smtpAuth = OAUTHBEARER` sort a fiókbeállításaidhoz:

----
[sendemail]
	smtpEncryption = ssl
	smtpServer = smtp.gmail.com
	smtpUser = yourname@gmail.com
	smtpServerPort = 465
	smtpAuth = OAUTHBEARER
----

Egy másik alternatíva a Google által fejlesztett
https://github.com/google/gmail-oauth2-tools/tree/master/go/sendgmail[sendgmail]
nevű eszköz használata e-mailek küldésére a `git send-email` segítségével.

[[_use_microsoft_outlook_as_the_smtp_server]]
A Microsoft Outlook használata SMTP-szerverként
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A Gmail-lel ellentétben a Microsoft Outlook már nem támogatja az
alkalmazás-specifikus jelszavakat. Ezért az Outlookhoz OAuth2.0-hitelesítést
kell használni. Emellett csak az `XOAUTH2` hitelesítési mechanizmust
támogatja.

Szerkeszd a `~/.gitconfig` fájlt az Outlookhoz tartozó fiókbeállításaid
megadásához, és használd az SMTP-szerverét a `git send-email`-lel:

----
[sendemail]
	smtpEncryption = tls
	smtpServer = smtp.office365.com
	smtpUser = yourname@outlook.com
	smtpServerPort = 587
	smtpAuth = XOAUTH2
----

SENDING PATCHES
---------------
Ha a commitjaid készen állnak a levelezőlistára küldésre, futtasd a
következő parancsokat:

	$ git format-patch --cover-letter -M origin/master -o outgoing/
	$ edit outgoing/0000-*
	$ git send-email outgoing/*

Az első futtatáskor a hitelesítő adataidra kérdez rá. Írd be az
alkalmazás-specifikus vagy a szokásos jelszavadat, amelyik éppen
szükséges.

Ha be van állítva credential helper (lásd linkgit:git-credential[1]), a
jelszó elmentésre kerül a credential store-ba, így legközelebb nem kell
begépelned.

Ha OAuth2.0-hitelesítést használsz, jelszó helyett egy hozzáférési tokent
kell megadnod, amikor rákérdez. Számos OAuth2.0-token-generátor elérhető
online. Közösség által karbantartott credential helperek is elérhetők:

	- https://github.com/AdityaGarg8/git-credential-email[git-credential-gmail]
	  (platformfüggetlen, dedikált helper Gmail-fiókok hitelesítéséhez)

	- https://github.com/AdityaGarg8/git-credential-email[git-credential-outlook]
	  (platformfüggetlen, dedikált helper Microsoft Outlook-fiókok hitelesítéséhez)

	- https://github.com/AdityaGarg8/git-credential-email[git-credential-yahoo]
	  (platformfüggetlen, dedikált helper Yahoo-fiókok hitelesítéséhez)

	- https://github.com/AdityaGarg8/git-credential-email[git-credential-aol]
	  (platformfüggetlen, dedikált helper AOL-fiókok hitelesítéséhez)

További OAuth-alapú hitelesítési helperekért lásd a
linkgit:gitcredentials[7] oldalt is.

A Proton Mail nem biztosít SMTP-szervert e-mailek küldésére. Ha a Proton
Mail fizető ügyfele vagy, használhatod a Proton Mail által hivatalosan
biztosított https://proton.me/mail/bridge[Proton Mail Bridge]-et, hogy
helyi SMTP-szervert hozz létre e-mailek küldésére. Mind az ingyenes, mind
a fizető felhasználók számára elérhetők közösség által karbantartott
projektek, mint a
https://github.com/AdityaGarg8/git-credential-email[git-protonmail].

Megjegyzés: a következő alap Perl modulok szükségesek, amelyek a Perl
disztribúciódhoz telepítve lehetnek:

https://metacpan.org/pod/MIME::Base64[MIME::Base64],
https://metacpan.org/pod/MIME::QuotedPrint[MIME::QuotedPrint],
https://metacpan.org/pod/Net::Domain[Net::Domain] és
https://metacpan.org/pod/Net::SMTP[Net::SMTP].

Az alábbi további Perl modulok is szükségesek:

https://metacpan.org/pod/Authen::SASL[Authen::SASL] és
https://metacpan.org/pod/Mail::Address[Mail::Address].

[[_exploiting_the_sendmailcmd_option_of_git_send_email]]
A `git send-email` `sendmailCmd` opciójának kihasználása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Az SMTP-szerveren keresztüli e-mailküldés mellett a `git send-email`
bármilyen olyan alkalmazáson keresztül is tud e-mailt küldeni, amely
támogatja a sendmail-szerű parancsokat. A további információkért lásd a
fenti `--sendmail-cmd=<command>` dokumentációját. Ez a képesség nagyon
hasznos lehet, ha egy másik alkalmazást szeretnél SMTP-kliensként
használni a `git send-email`-hez, vagy ha az e-mail-szolgáltatód SMTP
helyett saját, zárt API-kat használ e-mailek küldésére.

Példaként nézzük meg, hogyan konfigurálható a
https://marlam.de/msmtp/[msmtp], egy sok Linux-disztribúcióban megtalálható
népszerű SMTP-kliens. Szerkeszd a `~/.gitconfig` fájlt, hogy utasítsd a
`git-send-email`-t ennek használatára e-mailek küldéséhez.

----
[sendemail]
	sendmailCmd = /usr/bin/msmtp # Change this to the path where msmtp is installed
----

Néhány ilyen, közösség által karbantartott helper linkje:

	- https://marlam.de/msmtp/[msmtp]
	  (népszerű, sok funkcióval rendelkező SMTP-kliens, Linuxra és macOS-re elérhető)

	- https://github.com/AdityaGarg8/git-credential-email[git-protonmail]
	  (platformfüggetlen kliens, amely a ProtonMail API-jával tud e-maileket küldeni)

	- https://github.com/AdityaGarg8/git-credential-email[git-msgraph]
	  (platformfüggetlen kliens, amely a Microsoft Graph API-jával tud e-maileket küldeni)

CAVEATS
-------

include::format-patch-caveats.adoc[]

SEE ALSO
--------
linkgit:git-format-patch[1], linkgit:git-imap-send[1], `mbox`(5)

GIT
---
A linkgit:git[1] csomag része
