git-difftool(1)
===============

NAME
----
git-difftool - Változtatások megjelenítése általános diff-eszközökkel

SYNOPSIS
--------
[synopsis]
git difftool [<options>] [<commit> [<commit>]] [--] [<path>...]

DESCRIPTION
-----------
A `git difftool` egy Git-parancs, amellyel fájlokat lehet összehasonlítani
és szerkeszteni a revíziók között általános diff-eszközök segítségével. A
`git difftool` a `git diff`-hez készült frontend, és ugyanazokat az
opciókat és argumentumokat fogadja el. Lásd: linkgit:git-diff[1].

OPTIONS
-------
`-d`::
`--dir-diff`::
	A módosított fájlokat egy ideiglenes helyre másolja, és azokon
	végez könyvtár-diffet. Ez a mód soha nem kérdez rá a diff-eszköz
	elindítása előtt.

`-y`::
`--no-prompt`::
	Ne kérdezzen rá a diff-eszköz elindítása előtt.

`--prompt`::
	Kérdezzen rá a diff-eszköz minden egyes meghívása előtt.
	Ez az alapértelmezett viselkedés; az opció azért áll
	rendelkezésre, hogy felülbírálhassa a konfigurációs beállításokat.

`--rotate-to=<file>`::
	A diff megjelenítését _<file>_-nál kezdi, az előtte lévő
	útvonalak a végére kerülnek, és úgy jelennek meg.

`--skip-to=<file>`::
	A diff megjelenítését _<file>_-nál kezdi, kihagyva az összes
	előtte lévő útvonalat.

`-t <tool>`::
`--tool=<tool>`::
	A _<tool>_ által megadott diff-eszközt használja. Az érvényes
	értékek közé tartozik többek között az emerge, a kompare, a meld
	és a vimdiff. Futtasd a `git difftool --tool-help` parancsot az
	érvényes _<tool>_ beállítások listájáért.
+
Ha nincs megadva diff-eszköz, a `git difftool` a `diff.tool`
konfigurációs változót fogja használni. Ha a `diff.tool` konfigurációs
változó sincs beállítva, a `git difftool` egy megfelelő alapértelmezést
választ.
+
A `difftool.<tool>.path` konfigurációs változó beállításával
kifejezetten megadhatod az eszköz teljes útvonalát. Például a kdiff3
abszolút útvonalát a `difftool.kdiff3.path` beállításával
konfigurálhatod. Egyébként a `git difftool` feltételezi, hogy az
eszköz elérhető a PATH-ban.
+
Az ismert diff-eszközök egyikének futtatása helyett a `git difftool`
testre szabható úgy, hogy egy alternatív programot futtasson: ehhez
a meghívandó parancssort a `difftool.<tool>.cmd` konfigurációs
változóban kell megadni.
+
Amikor a `git difftool`-t ezzel az eszközzel hívják meg (akár a `-t`
vagy `--tool` opción, akár a `diff.tool` konfigurációs változón
keresztül), a konfigurált parancssor a következő változókkal
elérhetően kerül meghívásra: a `$LOCAL` annak az ideiglenes fájlnak a
nevére van beállítva, amely a diff kép-előzmény ("pre-image")
tartalmát tartalmazza, a `$REMOTE` pedig annak az ideiglenes fájlnak a
nevére, amely a diff kép-utókép ("post-image") tartalmát tartalmazza.
A `$MERGED` az összehasonlítás alatt álló fájl neve. A `$BASE` a
saját merge-eszköz parancsokkal való kompatibilitás miatt áll
rendelkezésre, és ugyanaz az értéke, mint a `$MERGED`-nek.

`--tool-help`::
	Kiírja a `--tool`-lal használható diff-eszközök listáját.

`--symlinks`::
`--no-symlinks`::
	A `git difftool` alapértelmezett viselkedése, hogy szimbolikus
	linkeket hoz létre a munkakönyvtárra, amikor `--dir-diff` módban
	fut, és az összehasonlítás jobb oldala ugyanazt a tartalmat adja,
	mint a munkakönyvtárban lévő fájl.
+
A `--no-symlinks` megadása arra utasítja a `git difftool`-t, hogy
ehelyett másolatokat hozzon létre. Windows alatt a `--no-symlinks`
az alapértelmezett.

`-x <command>`::
`--extcmd=<command>`::
	Egyéni parancsot ad meg a diffek megtekintéséhez.
	A `git-difftool` figyelmen kívül hagyja a konfigurált
	alapértelmezéseket, és a `<command> $LOCAL $REMOTE`-ot futtatja,
	ha ez az opció meg van adva. Emellett a `$BASE` is beállításra
	kerül a környezetben.

`-g`::
`--gui`::
`--no-gui`::
	Amikor a `git-difftool`-t a `-g` vagy `--gui` opcióval hívják meg,
	az alapértelmezett diff-eszközt a konfigurált `diff.guitool`
	változóból olvassa be a `diff.tool` helyett. Ez a `difftool.guiDefault`
	konfigurációs változó segítségével automatikusan is kiválasztható.
	A `--no-gui` opcióval felülbírálhatók ezek a beállítások. Ha a
	`diff.guitool` nincs beállítva, a `merge.guitool`, `diff.tool`,
	`merge.tool` sorrendben esünk vissza, amíg egy eszköz meg nem
	található.

`--trust-exit-code`::
`--no-trust-exit-code`::
	A diff-eszköz által jelentett hibákat alapértelmezésben figyelmen
	kívül hagyjuk. Használd a `--trust-exit-code`-ot, hogy a
	`git-difftool` kilépjen, ha a meghívott diff-eszköz nullától
	eltérő kilépési kóddal tér vissza.
+
A `git-difftool` továbbítja a meghívott eszköz kilépési kódját, ha a
`--trust-exit-code` van használatban.

A támogatott opciók teljes listájáért lásd: linkgit:git-diff[1].

CONFIGURATION
-------------
A `git difftool` visszaesik a `git mergetool` konfigurációs
változóira, ha a difftool megfelelőik nincsenek meghatározva.

include::includes/cmd-config-section-rest.adoc[]

include::config/difftool.adoc[]

SEE ALSO
--------
linkgit:git-diff[1]::
	 Változtatások megjelenítése commitok, commit és munkakönyvtár
	 között stb.

linkgit:git-mergetool[1]::
	Merge-konfliktus-feloldó eszközök futtatása merge-konfliktusok
	feloldásához

linkgit:git-config[1]::
	 Repository- vagy globális opciók lekérdezése és beállítása

GIT
---
A linkgit:git[1] csomag része
