git-fsmonitor{litdd}daemon(1)
=============================

NAME
----
git-fsmonitor--daemon - Beépített fájlrendszer-figyelő

SYNOPSIS
--------
[verse]
'git fsmonitor{litdd}daemon' start
'git fsmonitor{litdd}daemon' run
'git fsmonitor{litdd}daemon' stop
'git fsmonitor{litdd}daemon' status

DESCRIPTION
-----------

Daemon, amely a munkakönyvtárat figyeli fájl- és
könyvtárváltozásokért, platformspecifikus fájlrendszer-értesítési
eszközök használatával.

Ez a daemon közvetlenül kommunikál az olyan parancsokkal, mint a
`git status`, a link:technical/api-simple-ipc.html[egyszerű IPC]
felületet használva a lassabb linkgit:githooks[5] felület helyett.

Ez a daemon be van építve a Gitbe, így nincs szükség harmadik féltől
származó eszközökre.

OPTIONS
-------

start::
	Elindít egy daemont a háttérben.

run::
	Egy daemont futtat az előtérben.

stop::
	Leállítja az aktuális munkakönyvtárban futó daemont, ha van.

status::
	Nulla státusszal lép ki, ha egy daemon figyeli az aktuális
	munkakönyvtárat.

REMARKS
-------

Ez a daemon egy hosszan futó folyamat, amely egyetlen munkakönyvtár
figyelésére és a legutóbb megváltozott fájlok és könyvtárak listájának
karbantartására szolgál.  Az olyan parancsok, mint a `git status`,
gyorsíthatók, ha csak a munkakönyvtár változásainak összegzését kérik,
és elkerülhetik a lemez átvizsgálását.

Ha a `core.fsmonitor` `true` értékre van állítva (lásd
linkgit:git-config[1]), az olyan parancsok, mint a `git status`, a
daemontól kérik a változásokat, és automatikusan elindítják azt (ha
szükséges).

További információért lásd a "File System Monitor" szakaszt a
linkgit:git-update-index[1]-ben.

CAVEATS
-------

Az fsmonitor daemon jelenleg nem tud a submodule-okról, és nem tudja
kiszűrni a submodule-on belül történő fájlrendszer-eseményeket.  Ha az
fsmonitor daemon egy szuperrepót figyel, és egy fájlt egy submodule
munkakönyvtárán belül módosítanak, jelenteni fogja a változást (mintha
az a szuperrepóval szemben történne).  A kliens azonban helyesen
figyelmen kívül hagyja ezeket az extra eseményeket, így a teljesítmény
romolhat, de nem okoz helytelen eredményt.

Alapértelmezés szerint az fsmonitor daemon nem hajlandó hálózati
csatolású repository-kkal működni; ez felülbírálható a
`fsmonitor.allowRemote` `true` értékre állításával. Vedd azonban
figyelembe, hogy nem garantált, hogy az fsmonitor daemon helyesen
működik minden hálózati csatolású repository-val, ezért az ilyen
használat kísérletinek minősül.

Mac OS-en és Linuxon a különféle Git-parancsok és az fsmonitor daemon
közötti folyamatközi kommunikáció (IPC) Unix domain socketen (UDS)
keresztül történik -- ez egy speciális fájltípus --, amelyet a natív
Mac OS és Linux fájlrendszerek támogatnak, a hálózati csatolású
fájlrendszerek, az NTFS és a FAT32 viszont nem.  Más fájlrendszerek
esetében lehet, hogy van a szükséges támogatás, lehet, hogy nincs; nem
garantált, hogy az fsmonitor daemon működik ezekkel a fájlrendszerekkel,
és az ilyen használat kísérletinek minősül.

Alapértelmezés szerint a socket a `.git` könyvtárban jön létre.  Ha
azonban a `.git` könyvtár hálózati csatolású fájlrendszeren van, akkor
helyette a `$HOME/.git-fsmonitor-*` helyen jön létre, hacsak maga a
`$HOME` is hálózati csatolású fájlrendszeren nincs, amely esetben a
`fsmonitor.socketDir` konfigurációs változót egy natív fájlrendszeren
lévő könyvtár elérési útjára kell állítanod, amelyben a socket-fájl
létrejöhet.

Ha a fenti könyvtárak egyike sincs (`.git`, `$HOME` vagy
`fsmonitor.socketDir`) natív fájlrendszeren, az fsmonitor daemon hibát
jelez, amely a daemon és az éppen futó parancs kilépését okozza.

LINUX CAVEATS
~~~~~~~~~~~~~

Linuxon az fsmonitor daemon az inotify-t használja a
fájlrendszer-események figyelésére.  Az inotify rendszernek
felhasználónkénti korlátai vannak a létrehozható figyelők számára.  Az
alapértelmezett korlát jellemzően 8192 figyelő felhasználónként.

Sok könyvtárat tartalmazó nagy repository-knál előfordulhat, hogy meg
kell növelned ezt a korlátot.  Az aktuális korlátot így ellenőrizheted:

    cat /proc/sys/fs/inotify/max_user_watches

A korlát átmeneti megnöveléséhez:

    sudo sysctl fs.inotify.max_user_watches=65536

A változtatás véglegessé tételéhez add hozzá a `/etc/sysctl.conf`-hoz:

    fs.inotify.max_user_watches=65536

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/fsmonitor--daemon.adoc[]

GIT
---
A linkgit:git[1] csomag része
