git-symbolic-ref(1)
===================

NAME
----
git-symbolic-ref - Szimbolikus referenciákat olvas, módosít és töröl

SYNOPSIS
--------
[verse]
'git symbolic-ref' [-m <reason>] <name> <ref>
'git symbolic-ref' [-q] [--short] [--no-recurse] <name>
'git symbolic-ref' --delete [-q] <name>

DESCRIPTION
-----------
Egyetlen argumentummal megadva beolvassa, hogy a megadott szimbolikus
referencia melyik branch-headre hivatkozik, és kiírja annak útvonalát,
a `.git/` könyvtárhoz viszonyítva. Jellemzően a `HEAD`-et adnád meg
<name> argumentumként, hogy megnézd, melyik branchen van a
munkakönyvtárad.

Két argumentummal megadva létrehoz vagy frissít egy <name> szimbolikus
referenciát, hogy a megadott <ref> branchre mutasson.

A `--delete` és egy további argumentum megadásával törli a megadott
szimbolikus referenciát.

Egy szimbolikus referencia egy rendes fájl, amely egy `ref: refs/`-fel
kezdődő stringet tárol. Például a `.git/HEAD` egy rendes fájl,
amelynek tartalma `ref: refs/heads/master`.

OPTIONS
-------

-d::
--delete::
	Törli a <name> szimbolikus referenciát.

-q::
--quiet::
	Nem ad ki hibaüzenetet, ha a <name> nem szimbolikus referencia,
	hanem egy leválasztott HEAD; ehelyett csendben, nem nulla
	státusszal lép ki.

--short::
	Amikor a <name> értékét szimbolikus referenciaként jeleníti
	meg, megpróbálja lerövidíteni az értéket, pl. a
	`refs/heads/master`-ből `master`-re.

--recurse::
--no-recurse::
	Amikor a <name> értékét szimbolikus referenciaként jeleníti
	meg, ha a <name> egy másik szimbolikus referenciára hivatkozik,
	követi a szimbolikus referenciák ilyen láncát, amíg az eredmény
	már nem mutat szimbolikus referenciára (`--recurse`, ami az
	alapértelmezett). A `--no-recurse` a szimbolikus referencia
	csak egyetlen szintjének feloldása után megáll.

-m::
	Frissíti a <name> reflogját a <reason>-nel. Ez csak egy
	szimbolikus referencia létrehozásakor vagy frissítésekor
	érvényes.

NOTES
-----
Korábban a `.git/HEAD` egy szimbolikus link volt, amely a
`refs/heads/master`-re mutatott. Amikor másik branchre akartunk
váltani, a `ln -sf refs/heads/newbranch .git/HEAD`-et futtattuk, és
amikor ki akartuk deríteni, melyik branchen vagyunk, a
`readlink .git/HEAD`-et futtattuk. De a szimbolikus linkek nem
teljesen hordozhatók, ezért mostanra elavultak, és alapértelmezés
szerint (a fent leírt) szimbolikus referenciákat használunk.

A 'git symbolic-ref' 0-s státusszal lép ki, ha a szimbolikus
referencia tartalma helyesen került kiírásra, 1-es státusszal, ha a
kért név nem szimbolikus referencia, vagy 128-cal, ha másik hiba
történik.

SEE ALSO
--------
linkgit:git-update-ref[1]

GIT
---
A linkgit:git[1] csomag része
