git-archive(1)
==============

NAME
----
git-archive - Fájlarchívum létrehozása egy megnevezett fából


SYNOPSIS
--------
[verse]
'git archive' [--format=<fmt>] [--list] [--prefix=<prefix>/] [<extra>]
	      [-o <file> | --output=<file>] [--worktree-attributes]
	      [--remote=<repo> [--exec=<git-upload-archive>]] <tree-ish>
	      [<path>...]

DESCRIPTION
-----------
Létrehoz egy archívumot a megadott formátumban, amely tartalmazza a
megnevezett fa fastruktúráját, és kiírja a standard kimenetre. Ha meg
van adva <prefix>, azt az archívumban lévő fájlnevek elé illeszti.

A 'git archive' másképp viselkedik, ha egy fa ID-t kap, mint amikor egy
commit ID-t vagy tag ID-t. Ha egy fa ID van megadva, az archívumban
minden fájl módosítási idejeként az aktuális időt használja. Ezzel
szemben, ha egy commit ID vagy tag ID van megadva, akkor a hivatkozott
commit objektumban rögzített commit-időt használja helyette.
Emellett a commit ID a tar formátum használata esetén egy globális,
kiterjesztett pax fejlécben tárolódik; ez a 'git get-tar-commit-id'
paranccsal nyerhető ki. ZIP fájlokban fájlmegjegyzésként tárolódik.

OPTIONS
-------

--format=<fmt>::
	A keletkező archívum formátuma. A lehetséges értékek: `tar`,
	`zip`, `tar.gz`, `tgz`, és bármely, a `tar.<format>.command`
	konfigurációs opcióval definiált formátum. Ha a `--format` nincs
	megadva, és a kimeneti fájl meg van adva, a formátum a fájlnévből
	következik ki, ha lehetséges (pl. a `foo.zip` fájlba írás a
	kimenetet `zip` formátumúvá teszi). Egyébként a kimeneti formátum
	`tar`.

-l::
--list::
	Az összes elérhető formátum megjelenítése.

-v::
--verbose::
	Az előrehaladás jelentése az stderr-re.

--prefix=<prefix>/::
	<prefix>/ előtag illesztése az archívumban lévő útvonalak elé.
	Ismételhető; a legutolsó (legjobbra eső) értéke lesz használva
	az összes követett fájlhoz. Lásd lentebb, melyik értéket
	használja a `--add-file`.
+
A <prefix> a megadott formában kerül felhasználásra, és nem
normalizálódik. Tartalmazhat kezdő perjeleket vagy szülőkönyvtár-
komponenseket (pl. `../`). Egyes archívumfeldolgozók az ilyen
útvonalakat potenciálisan nem biztonságosnak tekinthetik, és
kicsomagoláskor módosíthatják vagy figyelmeztethetnek rájuk.

-o <file>::
--output=<file>::
	Az archívum kiírása <file>-ba a stdout helyett.

--add-file=<file>::
	Nem követett fájl hozzáadása az archívumhoz. Ismételhető több
	fájl hozzáadásához. A fájl útvonala az archívumban az utolsó,
	ez elé a `--add-file` elé eső `--prefix` opció értékének (ha van)
	és a <file> basename-jének összefűzésével épül fel.

--add-virtual-file=<path>:<content>::
	A megadott tartalom hozzáadása az archívumhoz. Ismételhető több
	fájl hozzáadásához.
+
A `<path>` argumentum kezdődhet és végződhet egy literál idézőjel
karakterrel; a benne foglalt fájlnév C-stílusú stringként értelmeződik,
azaz a backslash escape karakterként értelmeződik. Az útvonalat
idézőjelbe kell tenni, ha kettőspontot tartalmaz, hogy elkerüljük a
kettőspont téves értelmezését az útvonal és a tartalom közötti
elválasztóként, vagy ha az útvonal idézőjel karakterrel kezdődik vagy
végződik.
+
A fájlmód rendes fájlra korlátozódik, és az opcióra platformfüggő
parancssor-korlátozások vonatkozhatnak. Nem triviális esetekben inkább
írj egy nem követett fájlt, és használd helyette a `--add-file`-t.
+
Vedd figyelembe, hogy a `--add-file`-tól eltérően az archívumban
létrehozott útvonalra nincs hatással a `--prefix` opció, mivel a
teljes `<path>` megadható az opció értékeként.

--worktree-attributes::
	Az attribútumok keresése a munkakönyvtárban lévő .gitattributes
	fájlokban is (lásd <<ATTRIBUTES>>).

--mtime=<time>::
	Az archívumbejegyzések módosítási idejének beállítása. Ezen
	opció nélkül a committer-idő kerül felhasználásra, ha a
	`<tree-ish>` egy commit vagy tag, és az aktuális idő, ha egy fa.

<extra>::
	Ez bármilyen opció lehet, amelyet az archiváló backend megért.
	Lásd a következő szakaszt.

--remote=<repo>::
	Ahelyett, hogy a helyi repository-ból készítene tar archívumot,
	egy remote repository-ból kér le egy tar archívumot. Vedd
	figyelembe, hogy a remote repository korlátozásokat írhat elő
	arra vonatkozóan, hogy milyen sha1-kifejezések engedélyezettek a
	`<tree-ish>`-ben. A részletekért lásd:
	linkgit:git-upload-archive[1].

--exec=<git-upload-archive>::
	A --remote-mal együtt használva a 'git-upload-archive' remote
	oldali elérési útjának megadására szolgál.

<tree-ish>::
	Az a fa vagy commit, amelyhez az archívum készül.

<path>::
	Opcionális útvonalparaméter nélkül az aktuális munkakönyvtár
	összes fájlja és alkönyvtára bekerül az archívumba. Ha egy vagy
	több útvonal meg van adva, csak azok kerülnek bele.

BACKEND EXTRA OPTIONS
---------------------

zip
~~~
-<digit>::
	A tömörítési szint megadása. A nagyobb értékek lehetővé teszik,
	hogy a parancs több időt töltsön a kisebb méretre tömörítéssel.
	A támogatott értékek `-0`-tól (csak tárolás) `-9`-ig (legjobb
	arány) terjednek. Alapértelmezés `-6`, ha nincs megadva.

tar
~~~
-<number>::
	A tömörítési szint megadása. Az érték átadásra kerül a
	`tar.<format>.command` konfigurációban beállított tömörítő
	parancsnak. A támogatott szintek listájáért és az alapértelmezett
	szintért, ha ez az opció nincs megadva, lásd a konfigurált
	parancs man page-ét.

CONFIGURATION
-------------

tar.umask::
	Ez a változó a tar archívumbejegyzések jogosultsági bitjeinek
	korlátozására használható. Az alapértelmezés 0002, amely
	kikapcsolja a mindenki-írás bitet. A speciális "user" érték azt
	jelzi, hogy helyette az archiváló felhasználó umaskja lesz
	használva. A részletekért lásd az umask(2) man page-et. Ha a
	`--remote` van használva, akkor csak a remote repository
	konfigurációja lép érvénybe.

tar.<format>.command::
	Ez a változó egy shell parancsot ad meg, amelyen keresztül a
	`git archive` által generált tar kimenetet át kell vezetni. A
	parancsot a shell hajtja végre úgy, hogy a generált tar fájl a
	standard bemenetén van, és a végső kimenetet a standard
	kimenetén kell előállítania. Bármilyen tömörítésiszint-opció
	átadásra kerül a parancsnak (pl. `-9`).
+
A `tar.gz` és `tgz` formátumok automatikusan definiáltak, és
alapértelmezetten a `git archive gzip` mágikus parancsot használják,
amely a gzip egy belső implementációját hívja meg.

tar.<format>.remote::
	Ha igaz, engedélyezi a formátum használatát remote kliensek
	számára a linkgit:git-upload-archive[1] segítségével.
	Alapértelmezésben hamis a felhasználó által definiált
	formátumoknál, de igaz a `tar.gz` és `tgz` formátumoknál.

[[ATTRIBUTES]]
ATTRIBUTES
----------

export-ignore::
	Az export-ignore attribútummal rendelkező fájlok és könyvtárak
	nem kerülnek be az archívumfájlokba. A részletekért lásd:
	linkgit:gitattributes[5].

export-subst::
	Ha egy fájlra be van állítva az export-subst attribútum, a Git
	több helyőrzőt kifejt, amikor ezt a fájlt egy archívumhoz adja.
	A részletekért lásd: linkgit:gitattributes[5].

Vedd figyelembe, hogy az attribútumok alapértelmezetten az archiválandó
fában lévő `.gitattributes` fájlokból származnak. Ha utólag szeretnéd
finomhangolni a kimenet előállításának módját (pl. úgy commitoltál,
hogy nem adtál hozzá megfelelő export-ignore-t a `.gitattributes`
fájlhoz), szükség szerint módosítsd a checkoutolt `.gitattributes`
fájlt, és használd a `--worktree-attributes` opciót. Alternatívaként a
bármely fa archiválásakor alkalmazandó szükséges attribútumokat
megtarthatod a `$GIT_DIR/info/attributes` fájlodban.

EXAMPLES
--------
`git archive --format=tar --prefix=junk/ HEAD | (cd /var/tmp/ && tar xf -)`::

	Létrehoz egy tar archívumot, amely az aktuális branch legutóbbi
	commitjának tartalmát foglalja magába, és kicsomagolja a
	`/var/tmp/junk` könyvtárba.

`git archive --format=tar --prefix=git-1.4.0/ v1.4.0 | gzip >git-1.4.0.tar.gz`::

	Létrehoz egy tömörített tarballt a v1.4.0 kiadáshoz.

`git archive --format=tar.gz --prefix=git-1.4.0/ v1.4.0 >git-1.4.0.tar.gz`::

	Ugyanaz, mint fent, de a beépített tar.gz kezelést használva.

`git archive --prefix=git-1.4.0/ -o git-1.4.0.tar.gz v1.4.0`::

	Ugyanaz, mint fent, de a formátum a kimeneti fájlból következik ki.

`git archive --format=tar --prefix=git-1.4.0/ v1.4.0^{tree} | gzip >git-1.4.0.tar.gz`::

	Létrehoz egy tömörített tarballt a v1.4.0 kiadáshoz, de globális
	kiterjesztett pax fejléc nélkül.

`git archive --format=zip --prefix=git-docs/ HEAD:Documentation/ > git-1.4.0-docs.zip`::

	Az aktuális head Documentation/ könyvtárában lévő mindent
	beletesz a 'git-1.4.0-docs.zip'-be, 'git-docs/' előtaggal.

`git archive -o latest.zip HEAD`::

	Létrehoz egy Zip archívumot, amely az aktuális branch legutóbbi
	commitjának tartalmát foglalja magába. Vedd figyelembe, hogy a
	kimeneti formátum a kimeneti fájl kiterjesztéséből következik ki.

`git archive -o latest.tar --prefix=build/ --add-file=configure --prefix= HEAD`::

	Létrehoz egy tar archívumot, amely az aktuális branch legutóbbi
	commitjának tartalmát foglalja magába előtag nélkül, valamint a
	nem követett 'configure' fájlt 'build/' előtaggal.

`git config tar.tar.xz.command "xz -c"`::

	Beállít egy "tar.xz" formátumot LZMA-tömörített tar fájlok
	készítéséhez. A `--format=tar.xz` megadásával, vagy egy olyan
	kimeneti fájl létrehozásával használhatod, mint `-o foo.tar.xz`.


SEE ALSO
--------
linkgit:gitattributes[5]

GIT
---
A linkgit:git[1] csomag része
