git-format-rev(1)
=================

NAME
----
git-format-rev - KÍSÉRLETI: Revíziók szép formázása igény szerint


SYNOPSIS
--------
[synopsis]
(KÍSÉRLETI!) git format-rev --stdin-mode=<mode> --format=<pretty> [--[no-]notes=<ref>] [-z] [--[no-]null-output] [--[no-]null-input]

DESCRIPTION
-----------

Revíziók szép formázása a standard bemenetről.

EZ A PARANCS KÍSÉRLETI. A VISELKEDÉS MEGVÁLTOZHAT.

OPTIONS
-------

`--stdin-mode=<mode>`::
	Hogyan értelmezze a standard bemenet adatait:
+
--
`revs`;; Minden sor vagy rekord (lásd a <<io,INPUT AND OUTPUT FORMATS>>
	szakaszt) commitként értelmeződik. Bármilyen revíziókifejezés
	használható (lásd linkgit:gitrevisions[7]). Az annotált tagek le
	vannak hántva (lásd linkgit:gitglossary[7]).
+
A `rev` argumentum is elfogadott.

`text`;; A szabad szövegben található összes commit-objektumnevet
	formázza. Ezeknek teljes objektumneveknek kell lenniük, azaz a
	rövidített hexadecimális objektumneveket nem értelmezi.
+
Bármi, amit objektumnévként értelmez, de nem talál commit-objektumnévnek,
érintetlen marad (visszhangzik).
--

`--format=<pretty>`::
	Szép formázó sztring.

`--notes=<ref>`::
`--no-notes`::
	Egyéni notes-ref. A jegyzetek a `%N` atom használatakor jelennek
	meg. Lásd linkgit:git-notes[1].

`-z`::
`--null`::
	_NUL_ karakter használata a bemenet és a kimenet lezárására is,
	sortörés helyett. Ez az opció nem negálható.
+
Ez akkor hasznos, ha a bemenet és a kimenet is tartalmazhat
sortöréseket, vagy ha ennek a parancsnak a bemenete szintén _NUL_
karakteres lezárást használ; lásd lentebb a <<io,INPUT AND OUTPUT
FORMATS>> szakaszt.
+
A `--stdin-mode=text` mód akkor veheti hasznát ennek az opciónak, amikor
olyan bemenetet kell feldolgoznia, mint például a `git last-modified -z`;
lásd lentebb a <<examples,EXAMPLES>> szakaszt.

`--null-output`::
`--no-null-output`::
	_NUL_ karakter használata a kimenet lezárására sortörés helyett. Az
	alapértelmezés a `--no-null-output`.
+
Ez akkor hasznos, ha a kimenet tartalmazhat sortöréseket, például ha a
`%n` (sortörés) atomot használják.

`--null-input`::
`--no-null-input`::
	_NUL_ karakter használata a bemenet lezárására sortörés helyett. Az
	alapértelmezés a `--no-null-input`.
+
Ez akkor hasznos, ha a bemeneti revíziókifejezések tartalmazhatnak
sortöréseket.

[[io]]
INPUT AND OUTPUT FORMAT
-----------------------

A parancs alapból sortöréseket használ a bemenet és a kimenet
lezárására is. A _NUL_ karakter lezáróként való használatához lásd a
`-z`, `--null-output` és `--null-input` opciókat.

A `--stdin-mode=revs` mód egy formázott commitot ír ki, amelyet a
lezáró követ. Ezt _sornak_ vagy _rekordnak_ is nevezhetjük, arra az
esetre, ha a "sor" túlságosan sortöréssel való lezárásra utalna.

Vedd figyelembe, hogy ez azt jelenti, hogy a lezáró karakter (sortörés
vagy _NUL_) _lezáróként_, nem _elválasztóként_ működik. Más szóval az
utolsó sort vagy rekordot is lezárja a lezáró karakter.

A `--stdin-mode=text` mód minden objektumnevet a formázott committal
helyettesít, azaz a `"%s"` formátum valamely commit-objektumnevet
`"<subject>"`-re alakítana, bármilyen lezárás nélkül. Így:

[synopsis]
--
Did we not fix this in "<subject>"?
--

Biztonságos interaktívan olvasni és írni erről a parancsról, mivel
minden rekord azonnal ürítésre kerül.

[[examples]]
EXAMPLES
--------

A linkgit:git-last-modified[1] parancs azt a commitot mutatja meg,
amelyben az egyes fájlokat utoljára módosították.

----
$ git last-modified -- README.md Makefile
7798034171030be0909c56377a4e0e10e6d2df93	Makefile
c50fbb2dd225e7e82abba4380423ae105089f4d7	README.md
----

Az eredményt átvezethetjük ezen a parancson, hogy az objektumnevet a
commit szerzőjével helyettesítsük.

----
$ git last-modified -- README.md Makefile |
    git format-rev --stdin-mode=text --format=%an
Junio C Hamano	Makefile
Todd Zullinger	README.md
----

Egy másik példa a _commitok formázása a commit-üzenetekben_. Adott ez a commit-üzenet:

----
Fix off-by-one error

Fix off-by-one error introduced in
e83c5163316f89bfbde7d9ab23ca2e25604af290.

We thought we fixed this in 5569bf9bbedd63a00780fc5c110e0cfab3aa97b9 but
that only covered 1/3 of the faulty cases.
----

Formázhatjuk a commitokat, és a par(1)-gyel újratördelhetjük a szöveget,
mondjuk egy `commit-msg` hookban:

----
$ git config set hook.reference-commits.event commit-msg
$ git config set hook.reference-commits.command reference-commits
$ cat $(which reference-commits)
#/bin/sh

msg="$1"
rewritten=$(mktemp)
git format-rev --stdin-mode=text --format=reference <"$msg" |
    par >"$rewritten"
mv "$rewritten" "$msg"
----

Ami valami ilyesmit fog előállítani:

----
Fix off-by-one error

Fix off-by-one error introduced in e83c5163316 (Implement better memory
allocator, 2005-04-07).

We thought we fixed this in 5569bf9bbed (Fix memory allocator,
2005-06-22) but that only covered 1/3 of the faulty cases.
----

DISCUSSION
----------

Ez a parancs lehetővé teszi, hogy tetszőleges számú revíziót
tetszőleges sorrendben formázz egyetlen parancshívással. Vedd a fenti
<<examples,EXAMPLES>> szakaszból a linkgit:git-last-modified[1] esetét:

1. Több száz fájl is lehet
2. A commitok ismétlődhetnek, azaz két vagy több fájlt ugyanabban a
   commitban módosítottak utoljára

Két széles körben használt parancs, amely szépen formázza a commitokat,
a linkgit:git-log[1] és a linkgit:git-show[1]. Kiderül, hogy nem
illenek jól a fenti felhasználási esethez.

- A linkgit:git-last-modified[1] kimenetét szakaszokban kellene
  feldolgozni, mivel az első oszlopot külön kell átalakítani, majd a
  szerzőt a fájlnévhez kell kapcsolni. De ez leküzdhető.
- Minden commitot átadhatsz a `git show`-nak vagy a `git log --no-walk
  -1`-nek. De ez azt jelenti, hogy minden sorhoz létre kell hoznod egy
  folyamatot.
- Tegyük fel, hogy egy folyamatot akarsz használni, nem soronként
  egyet. Tehát az összes commitot át akarod adni a parancsnak. Most
  szembekerülsz azzal a problémával, hogy az összes commitot át kell
  adnod a parancsoknak, mielőtt bármilyen kimenetet kapnál (ez a
  `--stdin` módoknál is így van). Más szóval nem tudsz végigmenni minden
  soron, megszerezni a commit szerzőjét, és kiírni a szerzőt és a
  fájlnevet. Át kell adnod az összes commitot, vissza kell kapnod az
  összes kimenetet, és a kimenetet a fájlnévvel kell párosítanod.
- De a következő probléma az, hogy a parancsok deduplikálják a bemenetet,
  és minden commitot csak egyetlen egyszer írnak ki. Így nem tudod
  elérni, hogy a kimeneti sorrend egyezzen a bemeneti sorrenddel, mivel
  egy commit ismétlődhetett az eredeti bemenetben.

Röviden: egyszerű ezt a két parancsot használni, ha soronként egy
folyamatot használsz. Sokkal több munka, ha csak egy folyamatot akarsz
használni, de még mindig megvalósítható. Ezzel szemben ez a probléma
ezzel a paranccsal csak egy újabb shell-folyamatvezetékkel megoldható.

SEE ALSO
--------
linkgit:git-name-rev[1],
linkgit:git-log[1].

GIT
---
A linkgit:git[1] csomag része
