git-upload-archive(1)
=====================

NAME
----
git-upload-archive - Visszaküldi az archívumot a git-archive-nak


SYNOPSIS
--------
[verse]
'git upload-archive' <repository>

DESCRIPTION
-----------
A 'git archive --remote' hívja meg, és egy generált archívumot küld
a másik végnek a Git protokollon keresztül.

Ezt a parancsot rendszerint nem közvetlenül a végfelhasználó hívja
meg. A protokoll felhasználói felülete a 'git archive' oldalán van,
és a programpárt egy archívumnak egy távoli repository-ból való
lekérésére szánták.

SECURITY
--------

Az előzményekből eltávolított, de esetleg még nem prune-olt
objektumok privátságának védelme érdekében a `git-upload-archive`
elkerüli olyan commitok és fák archívumainak kiszolgálását, amelyek
nem érhetők el a repository referenciáiból. Azonban, mivel az
objektum-elérhetőség kiszámítása számításigényes, a
`git-upload-archive` egy szigorúbb, de könnyebben ellenőrizhető
szabálykészletet valósít meg:

  1. A kliensek kérhetnek olyan commitot vagy fát, amelyre közvetlenül
     mutat egy referencia. Pl. `git archive --remote=origin v1.0`.

  2. A kliensek kérhetnek egy alfát egy commiton vagy fán belül a
     `ref:path` szintaxissal. Pl. `git archive --remote=origin v1.0:Documentation`.

  3. A kliensek _nem_ használhatnak más sha1-kifejezéseket, még akkor
     sem, ha a végeredmény elérhető. Pl. sem egy relatív commit, mint
     a `master^`, sem egy literál sha1, mint az `abcd1234`, nem
     engedélyezett, még akkor sem, ha az eredmény elérhető a
     referenciákból.

Vedd figyelembe, hogy a 3. szabály sok olyan esetet is kizár, amelynek
nincs semmilyen privátsági vonzata. Ezek a szabályok a git jövőbeli
verzióiban változhatnak, és a `git archive --remote`-mal elért szerver
lehet, hogy követi ezeket a pontos szabályokat, lehet, hogy nem.

Ha az `uploadArchive.allowUnreachable` konfigurációs opció true-ra
van állítva, ezek a szabályok figyelmen kívül maradnak, és a
kliensek tetszőleges sha1-kifejezéseket használhatnak. Ez akkor
hasznos, ha nem érdekel az elérhetetlen objektumok privátsága, vagy
ha az objektumadatbázisod már amúgy is nyilvánosan elérhető
nem-smart-http-n keresztül.

OPTIONS
-------
<repository>::
	Az a repository, amelyből egy tar-archívumot kell beszerezni.

GIT
---
A linkgit:git[1] csomag része
