git-imap-send(1)
================

NAME
----
git-imap-send - Patchek gyűjteményének küldése a stdinről egy IMAP mappába


SYNOPSIS
--------
[synopsis]
git imap-send [-v] [-q] [--[no-]curl] [(--folder|-f) <folder>]
git imap-send --list


DESCRIPTION
-----------
Ez a parancs egy `git format-patch`-csel generált postaládát tölt fel
egy IMAP-piszkozatmappába.  Ez lehetővé teszi, hogy a patcheket ugyanúgy
küldd el, mint bármely más e-mailt, olyan levelezőprogramok használatakor,
amelyek nem tudják közvetlenül olvasni a postaláda-fájlokat. A parancs
bármilyen általános postaládával is működik, amelyben az e-mailek a `From`,
`Date` és `Subject` mezőket ebben a sorrendben tartalmazzák.

A tipikus használat valahogy így néz ki:

----
$ git format-patch --signoff --stdout --attach origin | git imap-send
----


OPTIONS
-------

`-v`::
`--verbose`::
	Legyen bőbeszédű.

`-q`::
`--quiet`::
	Legyen csendes.

`-f <folder>`::
`--folder=<folder>`::
	Add meg a mappát, amelybe az e-maileket menteni kell.
	Például: `--folder=[Gmail]/Drafts` vagy `-f INBOX/Drafts`.

`--curl`::
	A libcurl használata az IMAP-szerverrel való kommunikációhoz, kivéve
	ha tunnelezel bele.  Figyelmen kívül marad, ha a Git a
	USE_CURL_FOR_IMAP_SEND opció beállítása nélkül lett fordítva.

`--no-curl`::
	Kommunikáció az IMAP-szerverrel a git saját IMAP-rutinjaival a
	libcurl helyett.  Figyelmen kívül marad, ha a Git a NO_OPENSSL opció
	beállításával lett fordítva.

`--list`::
	Az IMAP LIST parancs futtatása az összes jelenlévő mappa listájának
	kiírásához.

CONFIGURATION
-------------

Az eszköz használatához az `imap.folder`, valamint az `imap.tunnel` vagy az
`imap.host` egyikét megfelelő értékre kell állítani.

include::includes/cmd-config-section-rest.adoc[]

include::config/imap.adoc[]

GETTING A LIST OF AVAILABLE FOLDERS
-----------------------------------

Ahhoz, hogy egy adott mappába küldj e-mailt, ismerned kell a kívánt mappa
helyes nevét a postaládádban. A különböző levelezőprogramok által megjelenített
nevek, mint a "Junk", "Trash" stb., nem feltétlenül egyeznek meg az e-mail-
szolgáltatód levelezőszerverén tárolt mappák tényleges neveivel.

Ahhoz, hogy megkapd a `git imap-send`-del használandó helyes mappanevet, futtathatod
a `git imap-send --list` parancsot. Ez megjeleníti az érvényes mappanevek listáját. Egy
példa az ilyen kimenetre, ha egy Gmail-fiókon futtatod:

.........................
* LIST (\HasNoChildren) "/" "INBOX"
* LIST (\HasChildren \Noselect) "/" "[Gmail]"
* LIST (\All \HasNoChildren) "/" "[Gmail]/All Mail"
* LIST (\Drafts \HasNoChildren) "/" "[Gmail]/Drafts"
* LIST (\HasNoChildren \Important) "/" "[Gmail]/Important"
* LIST (\HasNoChildren \Sent) "/" "[Gmail]/Sent Mail"
* LIST (\HasNoChildren \Junk) "/" "[Gmail]/Spam"
* LIST (\Flagged \HasNoChildren) "/" "[Gmail]/Starred"
* LIST (\HasNoChildren \Trash) "/" "[Gmail]/Trash"
.........................

Itt megfigyelheted, hogy a "Junk" mappa helyes neve `[Gmail]/Spam`, a "Trash"
mappáé pedig `[Gmail]/Trash`. Hasonló logikával a többi mappa is meghatározható.

EXAMPLES
--------
Tunnel mód használata:

..........................
[imap]
    folder = "INBOX.Drafts"
    tunnel = "ssh -q -C user@example.com /usr/bin/imapd ./Maildir 2> /dev/null"
..........................

Közvetlen mód használata:

.........................
[imap]
    folder = "INBOX.Drafts"
    host = imap://imap.example.com
    user = bob
    pass = p4ssw0rd
.........................

Közvetlen mód használata SSL-lel:

.........................
[imap]
    folder = "INBOX.Drafts"
    host = imaps://imap.example.com
    user = bob
    pass = p4ssw0rd
    port = 123
    ; sslVerify = false
.........................


[NOTE]
Hibakeresés közben érdemes lehet az `sslVerify=false` beállítást
használnod, ha azt gyanítod, hogy a kapcsolódási gondok oka az, hogy a
beállítani kívánt (vagy már beállított) `example.com` privát szerveren
használt tanúsítvány nem ellenőrizhető helyesen.

A Gmail IMAP-felületének használata:

----
[imap]
    folder = "[Gmail]/Drafts"
    host = imaps://imap.gmail.com
    user = user@gmail.com
    port = 993
----

A Gmail nem engedi a szokásos jelszavad használatát a `git imap-send`-hez.
Ha többfaktoros hitelesítést állítottál be a Gmail-fiókodon, generálhatsz
egy alkalmazásspecifikus jelszót a `git imap-send`-del való használatra.
A létrehozásához látogass el a
https://security.google.com/settings/security/apppasswords oldalra. Vagy
használhatod az alább leírt OAuth2.0-hitelesítést.

[NOTE]
Előfordulhat, hogy helyette a `folder = "[Google Mail]/Drafts"` beállítást kell
használnod, ha "Folder doesn't exist" hibát kapsz. Az elérhető mappák listájáért
a `git imap-send --list` parancsot is futtathatod.

[NOTE]
Ha a Gmail-fiókod az angoltól eltérő nyelvre van állítva, a "Drafts" mappa neve
lokalizálva lesz.

Ha OAuth2.0-alapú hitelesítést szeretnél használni, megadhatod az
`OAUTHBEARER` vagy az `XOAUTH2` mechanizmust a konfigurációdban. Ez
biztonságosabb, mint az alkalmazásspecifikus jelszavak használata, és nem
teszi kötelezővé a többfaktoros hitelesítést sem. Ennél a hitelesítésnél a
jelszavad helyett egy OAuth2.0-hozzáférési tokent kell használnod.

----
[imap]
    folder = "[Gmail]/Drafts"
    host = imaps://imap.gmail.com
    user = user@gmail.com
    port = 993
    authmethod = OAUTHBEARER
----

Az Outlook IMAP-felületének használata:

A Gmaillel ellentétben az Outlook csak OAuth2.0-alapú hitelesítést támogat.
Ráadásul mechanizmusként csak az `XOAUTH2`-t támogatja.

----
[imap]
    folder = "Drafts"
    host = imaps://outlook.office365.com
    user = user@outlook.com
    port = 993
    authmethod = XOAUTH2
----

Amint a commitok készen állnak az elküldésre, futtasd a következő parancsot:

----
$ git format-patch --cover-letter -M --stdout origin/master | git imap-send
----

Csak ügyelj arra, hogy kikapcsold a sortördelést a levelezőprogramban (a
Gmail webes felülete mindenképp tördeli a sorokat, ezért valódi IMAP-klienst
kell használnod).

Ha OAuth2.0-hitelesítést használsz, egyszerűbb credential helperekkel
generálni a tokeneket. A linkgit:git-send-email[1]-ben javasolt credential
helperek a `git imap-send`-hez is használhatók.

CAUTION
-------
Továbbra is a te felelősséged megbizonyosodni arról, hogy a levelezőprogramod
által küldött e-mail üzenet megfelel a projekted szabványainak.
Sok projekt nem szereti a mellékletként csatolt patcheket.  Egyes
levelezőügynökök úgy alakítják át a patcheket (pl. tördelik a sorokat,
format=flowed formában küldik), hogy azok használhatatlanná válnak.  Dühös,
gúnyolódó flame-eket fogsz kapni, ha ezt nem ellenőrzöd.

Különösen a Thunderbird ismert problémásként.  A Thunderbird-felhasználók
további információért felkereshetik ezt a weboldalt:
  https://kb.mozillazine.org/Plain_text_e-mail_-_Thunderbird#Completely_plain_email

SEE ALSO
--------
linkgit:git-format-patch[1], linkgit:git-send-email[1], `mbox`(5)

GIT
---
A linkgit:git[1] csomag része
