git-shortlog(1)
===============

NAME
----
git-shortlog - A `git log` kimenetének összegzése

SYNOPSIS
--------
[synopsis]
git shortlog [<options>] [<revision-range>] [[--] <path>...]
git log --pretty=short | git shortlog [<options>]

DESCRIPTION
-----------
A `git log` kimenetét kiadási bejelentésekbe illeszthető formátumban
összegzi. Minden commit szerző és cím szerint csoportosítva lesz.

Ezenkívül a "[PATCH]" eltávolításra kerül a commit leírásából.

Ha nincs revízió átadva a parancssoron, és vagy a standard bemenet nem
terminál, vagy nincs aktuális branch, a `git shortlog` a standard
bemenetről beolvasott napló összegzését adja ki, az aktuális
repository-ra való hivatkozás nélkül.

OPTIONS
-------

`-n`::
`--numbered`::
	A kimenetet a szerzőnkénti commitok száma szerint rendezi, nem a
	szerzők ábécésorrendje szerint.

`-s`::
`--summary`::
	Elnyomja a commit leírását, és csak commitszám-összegzést ad.

`-e`::
`--email`::
	Megjeleníti minden szerző e-mail-címét.

`--format[=<format>]`::
	A commit tárgya helyett valamilyen más információt használ az egyes
	commitok leírásához. A _<format>_ bármely olyan karakterlánc lehet,
	amelyet a `git log` `--format` opciója elfogad, például '* [%h] %s'.
	(Lásd a linkgit:git-log[1] 'PRETTY FORMATS' szakaszát.)
+
Minden pretty-printelt commit újratördelésre kerül, mielőtt megjelenik.

`--date=<format>`::
	A dátumokat a megadott dátum-karakterlánc szerint formázva jeleníti
	meg. (Lásd a `--date` opciót a linkgit:git-log[1] 'Commit
	Formatting' szakaszában). Hasznos a `--group=format:<format>`-tal.

`--group=<type>`::
	A commitokat a _<type>_ alapján csoportosítja. Ha nincs `--group`
	opció megadva, az alapértelmezés az `author`. A _<type>_ a
	következők egyike:
+
--
 - `author`, a commitok szerző szerint csoportosítva
 - `committer`, a commitok committer szerint csoportosítva (ugyanaz, mint a `-c`)
 - `trailer:<field>`, a _<field>_ kis-nagybetűtől független
   commit-üzenet trailerként értelmeződik (lásd
   linkgit:git-interpret-trailers[1]). Ha például a projekted
   `Reviewed-by` trailereket használ, a
   `git shortlog -ns --group=trailer:reviewed-by` paranccsal
   megnézheted, ki review-zott.
+
Vedd figyelembe, hogy a trailert nem tartalmazó commitok nem
számítanak bele. Hasonlóképpen a több trailerrel rendelkező commitok
(pl. több signoff) egynél többször is beszámíthatnak (de az adott
commiton belül trailerenkénti egyedi értékenként csak egyszer).
+
A shortlog megpróbálja minden trailer-értéket `name <email>`
identitásként elemezni. Ha sikerül, a mailmap alkalmazásra kerül, és az
e-mail kimarad, hacsak a `--email` opció nincs megadva. Ha az érték nem
elemezhető identitásként, szó szerint és teljesen lesz felhasználva.

 - `format:<format>`, bármely karakterlánc, amelyet a `git log`
   `--format` opciója elfogad. (Lásd a linkgit:git-log[1] 'PRETTY
   FORMATS' szakaszát.)
--
+
Ha a `--group` többször van megadva, a commitok minden érték alatt
beszámítanak (de ismét, az adott commiton belül egyedi értékenként csak
egyszer). Például a `git shortlog --group=author --group=trailer:co-authored-by`
a szerzőket és a társszerzőket is számolja.

`-c`::
`--committer`::
	Ez a `--group=committer` álneve.

`-w[<width>[,<indent1>[,<indent2>]]]`::
	Sortördeli a kimenetet úgy, hogy minden sort a `width` szélességnél
	tör.  Minden bejegyzés első sora `indent1` szóközzel van behúzva, a
	második és további sorok pedig `indent2` szóközzel. A `width`, az
	`indent1` és az `indent2` alapértelmezése rendre 76, 6 és 9.
+
Ha a szélesség `0` (nulla), akkor a kimenet sorai behúzásra kerülnek,
tördelés nélkül.

`<revision-range>`::
	Csak a megadott revíziótartományban lévő commitokat jeleníti meg.
	Ha nincs _<revision-range>_ megadva, az alapértelmezés a `HEAD`
	(azaz az aktuális commithoz vezető teljes előzmény).  Az
	`origin..HEAD` az összes olyan commitot jelöli, amely az aktuális
	commitból (azaz a `HEAD`-ből) elérhető, de az `origin`-ből nem. A
	_<revision-range>_ megadási módjainak teljes listájáért lásd a
	linkgit:gitrevisions[7] 'Specifying Ranges' szakaszát.

`[--] <path>...`::
	Csak azokat a commitokat veszi figyelembe, amelyek elegendők annak
	megmagyarázásához, hogyan jöttek létre a megadott útvonalakra
	illeszkedő fájlok.
+
Az útvonalakat esetleg `--`-tal kell prefixelni, hogy elkülönüljenek
az opcióktól vagy a revíziótartománytól, ha zavar keletkezik.

:git-shortlog: 1
include::rev-list-options.adoc[]

MAPPING AUTHORS
---------------

Lásd linkgit:gitmailmap[5].

Vedd figyelembe, hogy ha a `git shortlog` repository-n kívül fut (hogy
a napló tartalmát a standard bemenetről dolgozza fel), a `.mailmap`
fájlt az aktuális könyvtárban keresi.

GIT
---
A linkgit:git[1] csomag része
