git-fetch(1)
============

NAME
----
git-fetch - Objektumok és refek letöltése egy másik repository-ból


SYNOPSIS
--------
[synopsis]
git fetch [<options>] [<repository> [<refspec>...]]
git fetch [<options>] <group>
git fetch --multiple [<options>] [(<repository>|<group>)...]
git fetch --all [<options>]


DESCRIPTION
-----------
Branch-ek és/vagy tagek (összefoglaló néven: "refek") letöltése egy
vagy több másik repository-ból, az előzményeik teljessé tételéhez
szükséges objektumokkal együtt. A remote-tracking branchek frissülnek
(lásd a viselkedés vezérlésének lehetőségeiért a _<refspec>_ alábbi
leírását).

Alapértelmezés szerint minden olyan tag is letöltésre kerül, amely a
letöltött előzmények valamelyikébe mutat; ennek az a hatása, hogy azok
a tagek is letöltődnek, amelyek olyan branchekre mutatnak, amelyek
érdeklődésre tartanak számot. Ez az alapértelmezett viselkedés
megváltoztatható a `--tags` vagy a `--no-tags` opciók használatával,
vagy a `remote.<name>.tagOpt` beállításával. Egy tageket explicit
módon letöltő refspec használatával olyan tageket is le lehet tölteni,
amelyek nem az érdeklődésre számot tartó branchekre mutatnak.

A `git fetch` letölthet akár egyetlen, néven vagy URL-lel megadott
repository-ból, akár egyszerre több repository-ból is, ha _<group>_
van megadva, és van egy `remotes.<group>` bejegyzés a konfigurációs
fájlban. (Lásd: linkgit:git-config[1]).

Ha nincs remote megadva, alapértelmezés szerint az `origin` remote
kerül felhasználásra, kivéve, ha az aktuális branchhez van beállítva
egy upstream branch.

A letöltött refek nevei, a hozzájuk tartozó objektumnevekkel együtt,
bekerülnek a `.git/FETCH_HEAD` fájlba. Ezt az információt szkriptek
vagy más git parancsok, például a linkgit:git-pull[1], is
felhasználhatják.

OPTIONS
-------
include::fetch-options.adoc[]

include::pull-fetch-param.adoc[]

`--stdin`::
	Refspecek beolvasása a stdin-ről, soronként egy, az argumentumként
	megadottak mellett. A "tag _<name>_" formátum nem támogatott.

include::urls-remotes.adoc[]

[[CRTB]]
CONFIGURED REMOTE-TRACKING BRANCHES
-----------------------------------

Gyakran ugyanazzal a remote repository-val úgy állunk kapcsolatban, hogy
rendszeresen és ismételten fetchelünk belőle. Az ilyen remote repository
állapotának nyomon követése érdekében a `git fetch` lehetővé teszi a
`remote.<repository>.fetch` konfigurációs változók beállítását.

Egy ilyen változó jellemzően így néz ki:

------------------------------------------------
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
------------------------------------------------

Ez a konfiguráció kétféleképpen használatos:

* Ha a `git fetch` úgy fut, hogy a parancssorban nincs megadva,
  mely branchekre és/vagy tagekre vonatkozzon a fetch (pl. `git fetch origin`
  vagy `git fetch`), a `remote.<repository>.fetch` értékek refspecként
  szolgálnak — ezek határozzák meg, mely refeket kell letölteni, és mely
  helyi refeket kell frissíteni. A fenti példa letölti az összes,
  az `origin`-ban létező branchet (azaz minden olyan refet, amely illeszkedik
  az érték bal oldalára, `refs/heads/*`), és frissíti a megfelelő
  remote-tracking brancheket a `refs/remotes/origin/*` hierarchiában.

* Ha a `git fetch` explicit módon megadott branchekkel és/vagy tagekkel
  fut a parancssorban (pl. `git fetch origin master`), akkor a parancssorban
  megadott _<refspec>ek_ határozzák meg, mi kerül letöltésre (a példában
  ez a `master`, ami a `master:` rövidítése, ami viszont azt jelenti,
  hogy „töltsd le a `master` branchet, de nem mondom meg explicit módon,
  melyik remote-tracking branchet kell vele frissíteni a parancssorból"),
  és a példaparancs _csak_ a `master` branchet fogja letölteni. A
  `remote.<repository>.fetch` értékek határozzák meg, hogy melyik
  remote-tracking branch (ha van ilyen) frissül. Ilyen módon használva
  a `remote.<repository>.fetch` értékeknek nincs hatásuk arra, hogy _mi_
  kerül letöltésre (azaz nem refspecként használatosak, ha a parancssor
  refspeceket sorol fel); csak arra használatosak, hogy leképezésként
  eldöntsék, _hova_ kerülnek tárolásra a letöltött refek.

A `remote.<repository>.fetch` értékek utóbbi felhasználása felülírható
a `--refmap=<refspec>` paraméter(ek) parancssori megadásával.

PRUNING
-------

A Git alapértelmezett viselkedése az, hogy megtartja az adatokat, hacsak
explicit módon el nem dobják; ez kiterjed azokra a helyi referenciákra is,
amelyek olyan remote-okon lévő branchekre mutatnak, amelyeket a remote-ok
maguk már töröltek.

Ha hagyjuk felhalmozódni, ezek az elavult referenciák ronthatják a
teljesítményt a nagy és sokat használt repository-kon, ahol sok a
branch-mozgás, és pl. szükségtelenül bőbeszédűvé tehetik az olyan
parancsok kimenetét, mint a `git branch -a --contains <commit>`, valamint
hatással lehetnek mindenre, ami az ismert referenciák teljes halmazával
dolgozik.

Ezek a remote-tracking referenciák egyszeri alkalommal törölhetők a
következők bármelyikével:

------------------------------------------------
# While fetching
$ git fetch --prune <name>

# Only prune, don't fetch
$ git remote prune <name>
------------------------------------------------

Ahhoz, hogy a referenciák pruningja a normál munkafolyamat része legyen
anélkül, hogy ezt mindig külön futtatni kellene, állítsd be globálisan a
`fetch.prune`-t, vagy remote-onként a `remote.<name>.prune`-t a
konfigurációban. Lásd: linkgit:git-config[1].

Itt kezdenek a dolgok trükkösebbé és specifikusabbá válni. A pruning
funkciónak valójában semmi köze a branchekhez, ehelyett a helyi <-->
remote-referenciákat a remote refspecjének függvényében pruningolja
(lásd fent a `<refspec>`-et és a <<CRTB,CONFIGURED REMOTE-TRACKING BRANCHES>>
szakaszt).

Ezért ha a remote refspecje tartalmazza pl. a `refs/tags/*:refs/tags/*`
mintát, vagy manuálisan futtatod pl. a `git fetch --prune <name>
"refs/tags/*:refs/tags/*"` parancsot, nem az elavult remote-tracking
branchek törlődnek, hanem minden olyan helyi tag, amely nem létezik a
remote-on.

Ez esetleg nem az, amit vársz — azaz szeretnéd pruningolni a _<name>_
remote-ot, de emellett explicit módon tageket is fetchelni akarsz róla,
így amikor fetchelsz róla, törlődik az összes helyi tag, amelyek közül a
legtöbb eredetileg talán nem is a _<name>_ remote-ról származott.

Ezért légy óvatos, ha ilyen refspeccel dolgozol, mint a
`refs/tags/*:refs/tags/*`, vagy bármilyen más refspeccel, amely több
remote referenciáit ugyanabba a helyi névtérbe képezheti le.

Mivel a remote-on lévő branchek és tagek egyaránt naprakészen tartása
gyakori használati eset, a `--prune-tags` opció a `--prune`-nal együtt
megadva pruningolja a remote-on nem létező helyi tageket, és
force-update-eli azokat a tageket, amelyek eltérnek. A tag-pruning a
`fetch.pruneTags` vagy a `remote.<name>.pruneTags` konfigurációval is
bekapcsolható. Lásd: linkgit:git-config[1].

A `--prune-tags` opció azzal egyenértékű, mintha a `refs/tags/*:refs/tags/*`
lenne deklarálva a remote refspecjei között. Ez néhány, első ránézésre
furcsa interakcióhoz vezethet:

------------------------------------------------
# These both fetch tags
$ git fetch --no-tags origin 'refs/tags/*:refs/tags/*'
$ git fetch --no-tags --prune-tags origin
------------------------------------------------

Az, hogy nem dob hibát, ha a `--prune` vagy annak konfigurációs
megfelelője nélkül van megadva, a konfigurált verziók rugalmassága, és
annak érdekében van így, hogy 1:1 megfeleltetés maradjon a parancssori
kapcsolók és a konfigurációs verziók viselkedése között.

Ésszerű pl. a `fetch.pruneTags=true`-t beállítani a `~/.gitconfig`-ban,
hogy a tagek mindig pruningolódjanak, amikor a `git fetch --prune` fut,
anélkül, hogy a `git fetch` minden, `--prune` nélküli meghívása hibát
okozna.

A tagek `--prune-tags`-szal való pruningja akkor is működik, ha nevesített
remote helyett egy URL-ről fetchelünk. Az alábbiak mindegyike pruningolja
az origin-on nem található tageket:

------------------------------------------------
$ git fetch origin --prune --prune-tags
$ git fetch origin --prune 'refs/tags/*:refs/tags/*'
$ git fetch <url-of-origin> --prune --prune-tags
$ git fetch <url-of-origin> --prune 'refs/tags/*:refs/tags/*'
------------------------------------------------

OUTPUT
------

A „git fetch" kimenete a használt transzportmódszertől függ; ez a
szakasz a Git protokollon (akár helyben, akár ssh-n keresztül) és a
Smart HTTP protokollon keresztüli fetch kimenetét írja le.

A fetch állapota táblázatos formában jelenik meg a kimeneten, minden sor
egyetlen ref állapotát mutatja. Minden sor a következő alakú:

-------------------------------
 <flag> <summary> <from> -> <to> [<reason>]
-------------------------------

A `--porcelain` használatakor a kimeneti formátum gépileg feldolgozhatónak
van szánva. Az emberi olvasásra szánt kimeneti formátumokkal ellentétben
ezért a szabványos kimenetre ír a szabványos hibakimenet helyett. Minden
sor a következő alakú:

-------------------------------
<flag> <old-object-id> <new-object-id> <local-reference>
-------------------------------

A naprakész refek állapota csak akkor jelenik meg, ha a `--verbose`
opció használatban van.

Kompakt kimeneti módban, amelyet a fetch.output konfigurációs változó
állít be, ha a teljes _<from>_ vagy _<to>_ megtalálható a másik
stringben, azt a másik stringben `*`-gal helyettesíti. Például a
`master -> origin/master` `master -> origin/*` lesz.

flag::
	Egyetlen karakter, amely a ref állapotát jelzi:
(szóköz);; sikeresen fetchelt fast-forward esetén;
`+`;; sikeres force-update esetén;
`-`;; sikeresen pruningolt ref esetén;
`t`;; sikeres tag-frissítés esetén;
`*`;; sikeresen fetchelt új ref esetén;
`!`;; olyan ref esetén, amelyet elutasítottak, vagy amelynek a frissítése
	nem sikerült; és
`=`;; olyan ref esetén, amely naprakész volt, és nem kellett letölteni.

summary::
	Egy sikeresen fetchelt ref esetén az összefoglaló a ref régi és új
	értékét mutatja olyan formában, amely a `git log` argumentumaként
	is használható (ez a legtöbb esetben `<old>..<new>`, force-olt,
	nem fast-forward frissítéseknél pedig `<old>...<new>`).

from::
	Annak a remote refnek a neve, amelyről a fetch történik, a
	`refs/<type>/` előtag nélkül. Törlés esetén a remote ref neve
	„(none)".

to::
	Annak a helyi refnek a neve, amely frissül, a `refs/<type>/`
	előtag nélkül.

reason::
	Emberi olvasásra szánt magyarázat. Sikeresen fetchelt refek esetén
	nincs szükség magyarázatra. Sikertelen ref esetén a hiba oka van
	leírva.

EXAMPLES
--------

* A remote-tracking branchek frissítése:
+
------------------------------------------------
$ git fetch origin
------------------------------------------------
+
A fenti parancs átmásolja az összes branchet a remote `refs/heads/`
névteréből, és eltárolja őket a helyi `refs/remotes/origin/` névtérben,
hacsak a `remote.<repository>.fetch` opció nem használatos egy nem
alapértelmezett refspec megadására.

* Refspecek explicit használata:
+
------------------------------------------------
$ git fetch origin +seen:seen maint:tmp
------------------------------------------------
+
Ez frissíti (vagy szükség esetén létrehozza) a `seen` és a `tmp`
branchet a helyi repository-ban, a remote repository `seen`, illetve
`maint` branchéből fetchelve.
+
A `seen` branch akkor is frissülni fog, ha nem fast-forward, mert egy
plusz jel van előtte; a `tmp` viszont nem.

* Bepillantás egy remote branchébe, anélkül hogy a remote-ot
  beállítanánk a helyi repository-ban:
+
------------------------------------------------
$ git fetch git://git.kernel.org/pub/scm/git/git.git maint
$ git log FETCH_HEAD
------------------------------------------------
+
Az első parancs letölti a `maint` branchet a
`git://git.kernel.org/pub/scm/git/git.git` repository-ból, a második
parancs pedig a `FETCH_HEAD`-et használja a branch megvizsgálásához a
linkgit:git-log[1] segítségével. A letöltött objektumokat a git beépített
karbantartása idővel eltávolítja (lásd: linkgit:git-gc[1]).

include::transfer-data-leaks.adoc[]

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/fetch.adoc[]

BUGS
----
A `--recurse-submodules` használatával csak azokban a submodule-okban
tölthetők le új commitok, amelyek helyben, pl. a `$GIT_DIR/modules/`
alatt jelen vannak. Ha az upstream egy új submodule-t ad hozzá, az a
submodule addig nem fetchelhető, amíg klónozásra nem kerül, pl. a `git
submodule update` paranccsal. Ezt várhatóan egy jövőbeli Git-verzióban
javítják.

SEE ALSO
--------
linkgit:git-pull[1]

GIT
---
A linkgit:git[1] csomag része
