git-commit-tree(1)
==================

NAME
----
git-commit-tree - Új commit objektum létrehozása


SYNOPSIS
--------
[verse]
'git commit-tree' <tree> [(-p <parent>)...]
'git commit-tree' [(-p <parent>)...] [-S[<keyid>]] [(-m <message>)...]
		  [(-F <file>)...] <tree>


DESCRIPTION
-----------
Ezt általában nem közvetlenül futtatva szeretné használni egy
végfelhasználó. Használd inkább a linkgit:git-commit[1] parancsot.

Létrehoz egy új commit objektumot a megadott fa objektum alapján, és
kiírja az új commit objektum azonosítóját a stdout-ra. A napló-üzenet
a standard bemenetről olvasódik be, hacsak nincs megadva a `-m` vagy a
`-F` opció.

A `-m` és a `-F` opció tetszőleges számban, tetszőleges sorrendben
megadható. A commit napló-üzenete az opciók megadási sorrendjében
épül fel.

Egy commit objektumnak tetszőleges számú szülője lehet. Pontosan egy
szülővel közönséges commitról van szó. Egynél több szülő a commitot
több történelmi vonal közötti merge-gé teszi. A kezdeti (gyökér)
commitoknak nincs szülőjük.

Míg egy fa a munkakönyvtár egy adott könyvtárállapotát reprezentálja,
egy commit ezt az állapotot „időben" reprezentálja, és elmagyarázza,
hogyan lehet oda eljutni.

Egy commit rendszerint egy új „HEAD" állapotot azonosít, és bár a
Gitet nem érdekli, hova mented az erről az állapotról szóló feljegyzést,
a gyakorlatban hajlamosak vagyunk egyszerűen a `.git/HEAD` által
mutatott fájlba írni az eredményt, hogy mindig lássuk, mi volt az
utolsó commitolt állapot.

OPTIONS
-------
<tree>::
	Egy létező fa objektum.

-p <parent>::
	Minden `-p` egy szülő commit objektum azonosítóját jelzi.

-m <message>::
	Egy bekezdés a commit napló-üzenetében. Ez többször is megadható,
	és minden egyes <message> saját bekezdéssé válik.

-F <file>::
	A commit napló-üzenetének beolvasása a megadott fájlból. A `-`
	használatával a standard bemenetről olvashatsz. Ez többször is
	megadható, és minden fájl tartalma saját bekezdéssé válik.

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	A commitok GPG-aláírása. A `keyid` argumentum opcionális, és
	alapértelmezetten a committer identitása; ha meg van adva,
	szóköz nélkül kell az opcióhoz tapadnia. A `--no-gpg-sign` egy
	korábban a parancssorban megadott `--gpg-sign` opció felülbírálására
	hasznos.

[[_commit_information]]
Commit-információk
------------------

Egy commit a következőket foglalja magába:

- az összes szülő objektum azonosítója
- a szerző neve, e-mail-címe és dátuma
- a committer neve, e-mail-címe és a commit ideje.

A commit-megjegyzés a stdin-ről olvasódik be. Ha egy changelog-bejegyzés
nincs megadva "<" átirányítással, a 'git commit-tree' egyszerűen várni
fog, amíg beírják és ^D-vel lezárják.

include::date-formats.adoc[]

[[_discussion]]
Tárgyalás
---------

include::i18n.adoc[]

FILES
-----
/etc/mailname

SEE ALSO
--------
linkgit:git-write-tree[1]
linkgit:git-commit[1]

GIT
---
A linkgit:git[1] csomag része
