git-http-fetch(1)
=================

NAME
----
git-http-fetch - Letöltés egy távoli Git repository-ból HTTP-n keresztül


SYNOPSIS
--------
[verse]
'git http-fetch' [-c] [-t] [-a] [-d] [-v] [-w <filename>] [--recover] [--stdin | --packfile=<hash> | <commit>] <URL>

DESCRIPTION
-----------
Letölt egy távoli Git repository-t HTTP-n keresztül.

Ez a parancs mindig minden objektumot lekér. Korábban három opció
(`-a`, `-c` és `-t`) volt a letöltendő objektumok kiválasztására.
Ezeket most csendben figyelmen kívül hagyja.

OPTIONS
-------
commit-id::
        Vagy a hash, vagy a fájlnév a [URL]/refs/ alatt, amelyet
        le kell húzni (pull).

-a::
-c::
-t::
	Ezek az opciók történeti okokból figyelmen kívül maradnak.

-v::
	Jelenti, hogy mi kerül letöltésre.

-w <filename>::
	A commit-id-t a megadott fájlnévbe írja a $GIT_DIR/refs/<filename>
        alá a helyi oldalon, az átvitel befejezése után.

--stdin::
	Egy parancssorban megadott commit id helyett (amely ebben az
	esetben nem elvárt), a 'git http-fetch' a stdin-en vár sorokat
	a következő formátumban:

		<commit-id>['\t'<filename-as-in--w>]

--packfile=<hash>::
	Csak belső használatra. Egy parancssorban megadott commit id
	helyett (amely ebben az esetben nem elvárt), a 'git http-fetch'
	közvetlenül a megadott URL-en tölti le a packfile-t, és az
	index-pack-et használja a megfelelő .idx és .keep fájlok
	generálásához. A hash a temp fájl nevének meghatározására
	szolgál. Nem kell, hogy a pack hash-e legyen, de egyedileg
	kell azonosítania a pack tartalmát a folytatáshoz. Az
	index-pack kimenete a stdout-ra íródik ki. Egy vagy több
	--index-pack-arg opciót igényel.

--index-pack-arg=<arg>::
	Csak belső használatra. Az első előfordulás megadja a letöltött
	pack tartalmán futtatott parancsot. A további előfordulások
	az argumentumait adják meg.

--recover::
	Ellenőrzi, hogy minden, ami a céltól elérhető, le lett-e
	töltve. Egy korábbi, megszakadt fetch után használatos.

GIT
---
A linkgit:git[1] csomag része
