git-checkout(1)
===============

NAME
----
git-checkout - Branchek váltása vagy munkakönyvtár-fájlok visszaállítása

SYNOPSIS
--------
[synopsis]
git checkout [-q] [-f] [-m] [<branch>]
git checkout [-q] [-f] [-m] --detach [<branch>]
git checkout [-q] [-f] [-m] [--detach] <commit>
git checkout [-q] [-f] [-m] [[-b|-B|--orphan] <new-branch>] [<start-point>]
git checkout <tree-ish> [--] <pathspec>...
git checkout <tree-ish> --pathspec-from-file=<file> [--pathspec-file-nul]
git checkout [-f|--ours|--theirs|-m|--conflict=<style>] [--] <pathspec>...
git checkout [-f|--ours|--theirs|-m|--conflict=<style>] --pathspec-from-file=<file> [--pathspec-file-nul]
git checkout (-p|--patch) [<tree-ish>] [--] [<pathspec>...]

DESCRIPTION
-----------

A `git checkout`-nak két fő módja van:

1. **Branchváltás**, a `git checkout <branch>` paranccsal
2. **Egy fájl másik verziójának visszaállítása**, például a
   `git checkout <commit> <filename>` vagy a `git checkout <filename>` paranccsal

Lásd lentebb az ARGUMENT DISAMBIGUATION szakaszt, hogy megtudd, hogyan
dönti el a Git, melyiket teszi.

`git checkout [<branch>]`::
	Átváltás a(z) _<branch>_ branchre. Ez beállítja az aktuális branchet
	a(z) _<branch>_-re, és frissíti a munkakönyvtárad fájljait. A checkout
	meghiúsul, ha vannak nem commitolt módosítások olyan fájlokban,
	amelyeknél a(z) _<branch>_ és a jelenlegi commitod tartalma eltér.
	Egyéb esetben a nem commitolt módosítások megmaradnak.
+
Ha a(z) _<branch>_ nem található, de pontosan egy remote-on (nevezzük
_<remote>_-nak) létezik egy egyező nevű tracking branch, és a
`--no-guess` nincs megadva, ez ezzel egyenértékűnek tekintendő:
+
------------
$ git checkout -b <branch> --track <remote>/<branch>
------------
+
A `git checkout` branch megadása nélküli futtatásának nincs más hatása,
mint hogy kiírja az aktuális branch tracking-információját.

`git checkout -b <new-branch> [<start-point>]`::

	Létrehoz egy _<new-branch>_ nevű új branchet, elindítja a
	_<start-point>_-nál (alapértelmezés szerint az aktuális commitnál),
	és átvált az új branchre. A `--track` vagy a `--no-track` opciókkal
	beállíthatod a branch upstream tracking-információját.
+
Ez meghiúsul, ha hiba történik a _<new-branch>_ checkoutolásakor, például
ha a `<start-point>` commit checkoutolása felülírná a nem commitolt
módosításaidat.

`git checkout -B <branch> [<start-point>]`::

	Ugyanaz, mint a `-b`, azzal a különbséggel, hogy ha a branch már
	létezik, a _<branch>_-et a kezdőpontra állítja vissza, ahelyett
	hogy meghiúsulna.

`git checkout --detach [<branch>]`::
`git checkout [--detach] <commit>`::

	Ugyanaz, mint a `git checkout <branch>`, azzal a különbséggel, hogy
	nem a branchre mutatja a `HEAD`-et, hanem a commit ID-ra.
	Lásd lentebb a „DETACHED HEAD" szakaszt a részletekért.
+
A _<branch>_ elhagyása leválasztja a `HEAD`-et az aktuális branch
csúcsánál.

`git checkout <tree-ish> [--] <pathspec>...`::
`git checkout <tree-ish> --pathspec-from-file=<file> [--pathspec-file-nul]`::

	Lecseréli a megadott fájlokat és/vagy könyvtárakat a megadott
	commitból vagy fából származó verzióra, és hozzáadja őket az
	indexhez (más néven „staging area"-hoz).
+
Például a `git checkout main file.txt` a `file.txt`-t a `main`-ből
származó verzióra cseréli.

`git checkout [-f|--ours|--theirs|-m|--conflict=<style>] [--] <pathspec>...`::
`git checkout [-f|--ours|--theirs|-m|--conflict=<style>] --pathspec-from-file=<file> [--pathspec-file-nul]`::

	Lecseréli a megadott fájlokat és/vagy könyvtárakat az indexből
	származó verzióra.
+
Például, ha checkoutolsz egy commitot, szerkeszted a `file.txt`-t, majd
úgy döntesz, hogy ezek a módosítások tévesek voltak, a `git checkout
file.txt` eldobja a `file.txt` staging area-ba nem került módosításait.
+
Ez meghiúsul, ha a fájlnak merge-konfliktusa van, és még nem futtattad
a `git add file.txt`-t (vagy valami hasonlót), hogy megjelöld
megoldottként. A `-f` opcióval hiba helyett figyelmen kívül hagyhatod
az egyesítetlen fájlokat, a `--ours` vagy a `--theirs` opcióval a merge
egy adott oldaláról származó verzióra cserélheted őket, vagy a `-m`
opcióval az eredeti, konfliktusos merge-eredményre cserélheted őket.

`git checkout (-p|--patch) [<tree-ish>] [--] [<pathspec>...]`::
	Hasonló az előző két módhoz, de lehetővé teszi, hogy az interaktív
	felülettel megjelenítsd a „diff" kimenetet, és kiválaszd, mely
	hunkokat használod az eredményben. A `--patch` opció leírását
	lásd lentebb.

OPTIONS
-------
`-q`::
`--quiet`::
	Csendes mód, elnyomja a visszajelző üzeneteket.

`--progress`::
`--no-progress`::
	A folyamat állapota alapértelmezés szerint a standard hibakimeneti
	folyamon jelenik meg, ha az terminálhoz van csatlakoztatva, hacsak
	a `--quiet` nincs megadva. Ez a kapcsoló a folyamatjelzést akkor is
	engedélyezi, ha a kimenet nincs terminálhoz csatlakoztatva, a
	`--quiet`-től függetlenül.

`-f`::
`--force`::
	Branchváltáskor akkor is folytatja, ha az index vagy a
	munkakönyvtár eltér a `HEAD`-től, és akkor is, ha nem követett
	fájlok vannak útban. Ezzel eldobhatók a helyi módosítások és az
	útban lévő nem követett fájlok vagy könyvtárak.
+
Az index útvonalainak checkoutolásakor nem hiúsul meg egyesítetlen
bejegyzések esetén; ehelyett az egyesítetlen bejegyzések figyelmen
kívül maradnak.

`--ours`::
`--theirs`::
	Az index útvonalainak checkoutolásakor az egyesítetlen útvonalaknál
	a #2. (`ours`) vagy a #3. (`theirs`) stage-et checkoutolja.
+
Vedd figyelembe, hogy a `git rebase` és a `git pull --rebase` során az
`ours` és a `theirs` felcserélve tűnhet: a `--ours` azt a verziót adja,
amely arról a branchről származik, amelyre a módosítások rebase-elve
lettek, míg a `--theirs` azt a verziót adja, amely arról a branchről
származik, amely a rebase-elés alatt álló munkádat tartalmazza.
+
Ennek az az oka, hogy a `rebase`-t olyan munkafolyamatban használják,
amely a remote-on lévő történetet közös, kanonikus történetként
kezeli, a rebase-elt branchen végzett munkát pedig harmadik féltől
származó, integrálandó munkaként, és a rebase alatt te ideiglenesen a
kanonikus történet őrzőjének szerepét veszed fel. A kanonikus történet
őrzőjeként a remote-ról származó történetet `ours`-ként kell látnod
(azaz „a közös kanonikus történetünk"), míg a saját oldalágadon
végzett munkát `theirs`-ként (azaz „az egyik közreműködő munkája
rátéve").

`-b <new-branch>`::
	Létrehoz egy _<new-branch>_ nevű új branchet, elindítja a
	_<start-point>_-nál, és checkoutolja az eredményül kapott branchet;
	a részletekért lásd a linkgit:git-branch[1] parancsot.

`-B <new-branch>`::
	Ugyanaz, mint a `-b`, azzal a különbséggel, hogy ha a branch már
	létezik, a _<branch>_-et a kezdőpontra állítja vissza, ahelyett
	hogy meghiúsulna.

`-t`::
`--track[=(direct|inherit)]`::
	Új branch létrehozásakor beállítja az „upstream" konfigurációt. A
	részletekért lásd a `--track`-et a linkgit:git-branch[1] parancsban.
	Kényelmi megoldásként a --track -b nélkül branch létrehozását
	vonja maga után.
+
Ha nincs megadva `-b` opció, az új branch neve a remote-tracking
branchből származik: a megfelelő remote-hoz konfigurált refspec helyi
részét nézi meg, majd levágja a kezdő részt a „*"-ig.
Ez azt mondaná nekünk, hogy `hack`-et használjuk helyi branchként, ha az
`origin/hack`-ből (vagy a `remotes/origin/hack`-ből, vagy akár a
`refs/remotes/origin/hack`-ből) ágaztatunk le. Ha a megadott névben
nincs perjel, vagy a fenti tippelés üres nevet eredményez, a tippelés
megszakad. Ilyen esetben a `-b`-vel explicit módon megadhatsz egy nevet.

`--no-track`::
	Nem állítja be az „upstream" konfigurációt, még akkor sem, ha a
	`branch.autoSetupMerge` konfigurációs változó igazra van állítva.

`--guess`::
`--no-guess`::
	Ha a _<branch>_ nem található, de pontosan egy remote-on (nevezzük
	_<remote>_-nak) létezik egy egyező nevű tracking branch, ezzel
	egyenértékűnek kezeli:
+
------------
$ git checkout -b <branch> --track <remote>/<branch>
------------
+
Ha a branch több remote-on is létezik, és ezek egyikét a
`checkout.defaultRemote` konfigurációs változó nevezi meg, akkor azt
fogjuk használni az egyértelműsítéshez, még akkor is, ha a _<branch>_
nem egyedi az összes remote között. Állítsd be pl.
`checkout.defaultRemote=origin`-re, hogy mindig onnan checkoutold a
remote brancheket, ha a _<branch>_ nem egyértelmű, de létezik az
'origin' remote-on. Lásd még a `checkout.defaultRemote`-ot a
linkgit:git-config[1] parancsban.
+
A `--guess` az alapértelmezett viselkedés. Használd a `--no-guess`-t a
kikapcsolásához.
+
Az alapértelmezett viselkedés a `checkout.guess` konfigurációs
változóval állítható be.

`-l`::
	Létrehozza az új branch reflogját; a részletekért lásd a
	linkgit:git-branch[1] parancsot.

`-d`::
`--detach`::
	Ahelyett, hogy egy branchet checkoutolna a rajta végzett munkához,
	egy commitot checkoutol vizsgálatra és eldobható kísérletekhez.
	Ez a `git checkout <commit>` alapértelmezett viselkedése, ha a
	_<commit>_ nem branchnév. A részletekért lásd a „DETACHED HEAD"
	szakaszt lentebb.

`--orphan <new-branch>`::
	Létrehoz egy _<new-branch>_ nevű új, meg nem született branchet a
	_<start-point>_-ból kiindulva, és átvált rá. Az ezen az új
	branchen létrehozott első commitnak nem lesz szülője, és egy, az
	összes többi branchtől és committól teljesen elválasztott új
	történet gyökere lesz.
+
Az index és a munkakönyvtár úgy módosul, mintha korábban futtattad
volna a `git checkout <start-point>` parancsot. Ez lehetővé teszi, hogy
egy, a _<start-point>_-hoz hasonló útvonalkészletet rögzítő új
történetet indíts el a `git commit -a` egyszerű futtatásával, hogy
létrehozd a gyökércommitot.
+
Ez akkor lehet hasznos, ha egy commit fáját szeretnéd publikálni a
teljes történet felfedése nélkül. Erre szükség lehet egy olyan projekt
nyílt forráskódú branchének publikálásakor, amelynek aktuális fája
„tiszta", de a teljes története proprietary vagy más módon
korlátozott kódrészleteket tartalmaz.
+
Ha egy, a _<start-point>_-étól teljesen eltérő útvonalkészletet
rögzítő, elválasztott történetet szeretnél indítani, akkor az orphan
branch létrehozása után azonnal ki kell ürítened az indexet és a
munkakönyvtárat a `git rm -rf .` futtatásával a munkakönyvtár
legfelső szintjéről. Ezután készen állsz az új fájljaid előkészítésére,
a munkakönyvtár újbóli feltöltésére, például máshonnan másolva őket,
egy tarballt kicsomagolva stb.

`--ignore-skip-worktree-bits`::
	Sparse checkout módban a `git checkout -- <path>...` csak a
	_<paths>_ és a `$GIT_DIR/info/sparse-checkout`-beli sparse minták
	által egyezett bejegyzéseket frissítené. Ez az opció figyelmen
	kívül hagyja a sparse mintákat, és visszaadja a `<path>...`-ban
	lévő összes fájlt.

`-m`::
`--merge`::
	Branchváltáskor, ha egy vagy több olyan fájlban vannak helyi
	módosításaid, amelyek eltérnek az aktuális branch és az az között,
	amelyre váltasz, a parancs megtagadja a branchváltást, hogy a
	módosításaidat a kontextusukban megőrizze. Ezzel az opcióval a
	konfliktusos helyi módosítások automatikusan stashelve lesznek a
	váltás előtt, majd újra alkalmazva utána. Ha a helyi módosítások
	nem fedik egymást a branchek közötti eltérésekkel, a váltás
	stashelés nélkül végbemegy. Ha a stash újbóli alkalmazása
	konfliktusokat eredményez, a bejegyzés elmentődik a stash-listába.
	Oldd meg a konfliktusokat, és futtasd a `git stash drop`-ot, ha
	kész vagy, vagy ürítsd ki a munkakönyvtárat (pl. a `git reset
	--hard`-dal), mielőtt később futtatnád a `git stash pop`-ot a
	módosításaid újbóli alkalmazásához.
+
Az index útvonalainak checkoutolásakor ez az opció lehetővé teszi a
konfliktusos merge újralétrehozását a megadott útvonalakban. Ez az
opció nem használható tree-ish-ből történő útvonal-checkoutoláskor.

`--conflict=<style>`::
	Ugyanaz, mint a fenti `--merge` opció, de megváltoztatja a
	konfliktusos hunkok megjelenítésének módját, felülírva a
	`merge.conflictStyle` konfigurációs változót. A lehetséges értékek:
	`merge` (alapértelmezett), `diff3` és `zdiff3`.

`-p`::
`--patch`::
	Interaktívan kiválaszthatod a hunkokat a _<tree-ish>_ (vagy, ha
	nincs megadva, az index) és a munkakönyvtár közötti eltérésben. A
	kiválasztott hunkok ezután fordítottan kerülnek alkalmazásra a
	munkakönyvtárra (és ha egy _<tree-ish>_ meg volt adva, az indexre
	is).
+
Ez azt jelenti, hogy a `git checkout -p` paranccsal szelektíven
eldobhatod a szerkesztéseket az aktuális munkakönyvtáradból. A
`--patch` mód kezeléséhez lásd a linkgit:git-add[1] „Interaktív mód"
szakaszát.
+
Vedd figyelembe, hogy ez az opció alapértelmezés szerint a nem overlay
módot használja (lásd még a `--overlay`-t), és jelenleg nem támogatja
az overlay módot.

include::diff-context-options.adoc[]

`--ignore-other-worktrees`::
	A `git checkout` megtagadja a checkoutolást, ha a kívánt branch
	már ki van csekkolva, vagy más módon egy másik worktree használja.
	Ez az opció ennek ellenére checkoutolja a branchet. Más szóval, a
	branchet egyszerre több worktree is használhatja.

`--overwrite-ignore`::
`--no-overwrite-ignore`::
	Branchváltáskor csendben felülírja a figyelmen kívül hagyott
	fájlokat. Ez az alapértelmezett viselkedés. Használd a
	`--no-overwrite-ignore`-t a művelet megszakításához, ha az új
	branch figyelmen kívül hagyott fájlokat tartalmaz.

`--recurse-submodules`::
`--no-recurse-submodules`::
	A `--recurse-submodules` használata frissíti az összes aktív
	submodule tartalmát a szuperprojektben rögzített commit szerint.
	Ha egy submodule-ban lévő helyi módosítások felülíródnának, a
	checkout meghiúsul, hacsak nem használod a `-f`-et. Ha semmi (vagy
	a `--no-recurse-submodules`) nincs használva, a submodule-ok
	munkakönyvtárai nem frissülnek. Csakúgy, mint a
	linkgit:git-submodule[1], ez leválasztja a submodule `HEAD`-jét.

`--overlay`::
`--no-overlay`::
	Az alapértelmezett overlay módban a `git checkout` soha nem
	távolít el fájlokat az indexből vagy a munkakönyvtárból. A
	`--no-overlay` megadásakor azok a fájlok, amelyek szerepelnek az
	indexben és a munkakönyvtárban, de nem szerepelnek a
	_<tree-ish>_-ben, eltávolításra kerülnek, hogy pontosan
	megegyezzenek a _<tree-ish>_-vel.

`--pathspec-from-file=<file>`::
	A pathspec parancssori argumentumok helyett a _<file>_-ban van
	átadva. Ha a _<file>_ pontosan `-`, akkor a standard bemenet
	kerül felhasználásra. A pathspec elemeket _LF_ vagy _CR_/_LF_
	választja el. A pathspec elemek idézőjelezhetők a
	`core.quotePath` konfigurációs változónál leírtak szerint (lásd
	linkgit:git-config[1]). Lásd még a `--pathspec-file-nul`-t és a
	globális `--literal-pathspecs`-et.

`--pathspec-file-nul`::
	Csak a `--pathspec-from-file`-fal együtt van jelentése. A
	pathspec elemeket _NUL_ karakter választja el, és minden más
	karakter szó szerint kerül értelmezésre (beleértve az
	újsorokat és az idézőjeleket is).

`<branch>`::
	A checkoutolandó branch; ha branchre hivatkozik (azaz olyan névre,
	amely a „refs/heads/" előtaggal kiegészítve érvényes referencia),
	akkor az a branch kerül checkoutolásra. Egyébként, ha érvényes
	commitra hivatkozik, a `HEAD`-ed „leválasztottá" válik, és már
	nem vagy egyetlen branchen sem (a részletekért lásd lentebb).
+
Használhatod a `@{-N}` szintaxist, hogy az N-edik utoljára
checkoutolt branchre/commitra hivatkozz a „git checkout" művelettel.
Megadhatod a `-`-t is, ami a `@{-1}` szinonimája.
+
Speciális esetként a `<rev-a>...<rev-b>` alakot használhatod a
_<rev-a>_ és a _<rev-b>_ merge-alapjának rövidítéseként, ha pontosan
egy merge-alap létezik. A _<rev-a>_ és a _<rev-b>_ közül legfeljebb
az egyiket hagyhatod el, ekkor annak alapértelmezése `HEAD` lesz.

_<new-branch>_::
	Az új branch neve.

_<start-point>_::
	Annak a commitnak a neve, amelynél az új branch elindul; a
	részletekért lásd a linkgit:git-branch[1] parancsot. Az
	alapértelmezés a `HEAD`.
+
Speciális esetként a `<rev-a>...<rev-b>` alakot használhatod a
_<rev-a>_ és a _<rev-b>_ merge-alapjának rövidítéseként, ha pontosan
egy merge-alap létezik. A _<rev-a>_ és a _<rev-b>_ közül legfeljebb
az egyiket hagyhatod el, ekkor annak alapértelmezése `HEAD` lesz.

_<tree-ish>_::
	A fa, amelyből checkoutolni kell (ha útvonalak vannak megadva). Ha
	nincs megadva, az index kerül felhasználásra.
+
Speciális esetként a `<rev-a>...<rev-b>` alakot használhatod a
_<rev-a>_ és a _<rev-b>_ merge-alapjának rövidítéseként, ha pontosan
egy merge-alap létezik. A _<rev-a>_ és a _<rev-b>_ közül legfeljebb
az egyiket hagyhatod el, ekkor annak alapértelmezése `HEAD` lesz.

`--`::
	A további argumentumokat ne értelmezze opcióként.

`<pathspec>...`::
	Korlátozza a művelet által érintett útvonalakat.
+
A további részletekért lásd a 'pathspec' bejegyzést a
linkgit:gitglossary[7] parancsban.

DETACHED HEAD
-------------
A `HEAD` normál esetben egy elnevezett branchre hivatkozik (pl.
`master`). Eközben minden branch egy konkrét commitra hivatkozik.
Nézzünk meg egy repository-t három committal, amelyek közül az egyik
tag-elve van, és amelyben a `master` branch van checkoutolva:

------------
           HEAD (refers to branch 'master')
            |
            v
a---b---c  branch 'master' (refers to commit 'c')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

Amikor ebben az állapotban egy commit jön létre, a branch frissül, hogy
az új commitra hivatkozzon. Konkrétan, a `git commit` létrehoz egy új
`d` commitot, amelynek szülője a `c` commit, majd frissíti a `master`
branchet, hogy az új `d` commitra hivatkozzon. A `HEAD` továbbra is a
`master` branchre hivatkozik, így most közvetve a `d` commitra
hivatkozik:

------------
$ edit; git add; git commit

               HEAD (refers to branch 'master')
                |
                v
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

Néha hasznos checkoutolni tudni egy commitot, amely nincs egyetlen
elnevezett branch csúcsán sem, vagy akár egy olyan új commitot
létrehozni, amelyre nem hivatkozik elnevezett branch. Nézzük meg, mi
történik, amikor checkoutoljuk a `b` commitot (itt két módját mutatjuk
be annak, hogyan lehet ezt megtenni):

------------
$ git checkout v2.0  # or
$ git checkout master^^

   HEAD (refers to commit 'b')
    |
    v
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

Vedd észre, hogy attól függetlenül, melyik checkout parancsot
használjuk, a `HEAD` most közvetlenül a `b` commitra hivatkozik. Ezt
nevezzük leválasztott `HEAD` állapotnak. Egyszerűen azt jelenti, hogy a
`HEAD` egy konkrét commitra hivatkozik, szemben azzal, hogy egy
elnevezett branchre hivatkozna. Nézzük meg, mi történik, amikor
létrehozunk egy commitot:

------------
$ edit; git add; git commit

     HEAD (refers to commit 'e')
      |
      v
      e
     /
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

Most már van egy új `e` commit, de arra csak a `HEAD` hivatkozik.
Ebben az állapotban természetesen hozzáadhatunk egy újabb commitot is:

------------
$ edit; git add; git commit

	 HEAD (refers to commit 'f')
	  |
	  v
      e---f
     /
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

Valójában az összes szokásos Git-műveletet elvégezhetjük. De nézzük
meg, mi történik, amikor ezután checkoutoljuk a `master`-t:

------------
$ git checkout master

               HEAD (refers to branch 'master')
      e---f     |
     /          v
a---b---c---d  branch 'master' (refers to commit 'd')
    ^
    |
  tag 'v2.0' (refers to commit 'b')
------------

Fontos felismerni, hogy ezen a ponton semmi nem hivatkozik az `f`
commitra. Az `f` commit (és ebből következően az `e` commit is) végül
törlődni fog a rutinszerű Git szemétgyűjtési folyamat során, hacsak
nem hozunk létre rá egy referenciát, mielőtt ez megtörténne. Ha még
nem mozdultunk el az `f` commitról, bármelyik alábbi létrehoz rá egy
referenciát:

------------
$ git checkout -b foo  # or "git switch -c foo"  <1>
$ git branch foo                                 <2>
$ git tag foo                                    <3>
------------
<1> létrehoz egy `foo` nevű új branchet, amely az `f` commitra hivatkozik,
    majd frissíti a `HEAD`-et, hogy a `foo` branchre hivatkozzon. Más
    szóval, e parancs után már nem leszünk leválasztott `HEAD`
    állapotban.
<2> hasonlóképpen létrehoz egy `foo` nevű új branchet, amely az `f`
    commitra hivatkozik, de leválasztva hagyja a `HEAD`-et.
<3> létrehoz egy `foo` nevű új tag-et, amely az `f` commitra
    hivatkozik, leválasztva hagyva a `HEAD`-et.

Ha elmozdultunk az `f` commitról, akkor először vissza kell nyernünk
az objektumnevét (jellemzően a git reflog használatával), és utána
hozhatunk létre rá referenciát. Például, hogy megnézzük azt a két
utolsó commitot, amelyre a `HEAD` hivatkozott, bármelyik alábbi
parancsot használhatjuk:

------------
$ git reflog -2 HEAD # or
$ git log -g -2 HEAD
------------

ARGUMENT DISAMBIGUATION
-----------------------

Amikor a `git checkout <something>` parancsot futtatod, a Git
megpróbálja kitalálni, hogy a _<something>_ branchnek, commitnak,
vagy fájl(ok) halmazának van-e szánva, majd vagy átvált arra a
branchre vagy commitra, vagy visszaállítja a megadott fájlokat.

Ha bármilyen kétértelműség van, a Git a `<something>`-et branchként
vagy commitként fogja kezelni, de a dupla kötőjel `--`-val
kikényszerítheted, hogy a Git a paramétert fájlok és/vagy könyvtárak
listájaként kezelje, például így:

----------
git checkout -- file.txt
----------

EXAMPLES
--------

[[_1_paths]]
=== 1. Útvonalak

Az alábbi parancssorozat checkoutolja a `master` branchet,
visszaállítja a `Makefile`-t két revízióval korábbra, tévedésből
törli a `hello.c`-t, majd visszaszerzi az indexből.

------------
$ git checkout master             <1>
$ git checkout master~2 Makefile  <2>
$ rm -f hello.c
$ git checkout hello.c            <3>
------------
<1> branchváltás
<2> egy fájl kivétele egy másik commitból
<3> a `hello.c` visszaállítása az indexből

Ha az _összes_ C forrásfájlt ki akarod venni az indexből, ezt írhatod:

------------
$ git checkout -- '*.c'
------------

Vedd figyelembe a `*.c` körüli idézőjeleket. A `hello.c` fájl is
checkoutolva lesz, még ha már nincs is a munkakönyvtárban, mert a
fájl-globolást az indexbeli bejegyzések egyeztetésére használjuk
(nem a munkakönyvtárban, a shell által).

Ha van egy szerencsétlen módon `hello.c`-nek elnevezett brancheded,
ez a lépés összekeveredne az arra a branchre való átváltás
utasításával. Ehelyett ezt kellene írnod:

------------
$ git checkout -- hello.c
------------

[[_2_merge]]
=== 2. Merge

Miután a rossz branchen dolgoztál, a helyes branchre való átváltást
így végezhetnéd:

------------
$ git checkout mytopic
------------

A „rossz" brancheded és a helyes `mytopic` branch azonban eltérhet
azokban a fájlokban, amelyeket helyileg módosítottál, ebben az
esetben a fenti checkout így hiúsulna meg:

------------
$ git checkout mytopic
error: You have local changes to 'frotz'; not switching branches.
------------

Megadhatod a `-m` kapcsolót a parancsnak, ami átviszi a helyi
módosításaidat az új branchre:

------------
$ git checkout -m mytopic
Applied autostash.
Switched to branch 'mytopic'
The following paths have local changes:
M	frotz
------------

A váltás után a helyi módosítások újra alkalmazódnak, és _nincsenek_
regisztrálva az index fájlodban, így a `git diff` megmutatná, mely
módosításokat tetted az új branch csúcsa óta.

[[_3_merge_conflict]]
=== 3. Merge-konfliktus

Amikor a `--merge` (`-m`) opció meg van adva, és a helyi módosítások
átfedésben vannak azzal a branchcsel, amelyre váltunk, a módosítások
stashelve lesznek, majd a váltás után újra alkalmazva. Ha ez a
folyamat konfliktusokat eredményez, a stash-bejegyzés elmentődik, és
egy üzenet kerül kiírásra:

------------
$ git checkout -m mytopic
Your local changes are stashed, however applying them
resulted in conflicts.  You can either resolve the conflicts
and then discard the stash with "git stash drop", or, if you
do not want to resolve them now, run "git reset --hard" and
apply the local changes later by running "git stash pop".
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/checkout.adoc[]

SEE ALSO
--------
linkgit:git-switch[1],
linkgit:git-restore[1]

GIT
---
A linkgit:git[1] csomag része
