git-bisect(1)
=============

NAME
----
git-bisect - Bináris kereséssel megkeresi a hibát bevezető commitot


SYNOPSIS
--------
[synopsis]
git bisect start [--term-(bad|new)=<term-new> --term-(good|old)=<term-old>]
		 [--no-checkout] [--first-parent] [--reset-when-found[=<where>]] [<bad> [<good>...]] [--] [<pathspec>...]
git bisect (bad|new|<term-new>) [<rev>]
git bisect (good|old|<term-old>) [<rev>...]
git bisect terms [--term-(good|old) | --term-(bad|new)]
git bisect skip [(<rev>|<range>)...]
git bisect next
git bisect reset [<commit>]
git bisect (visualize|view)
git bisect replay <logfile>
git bisect log
git bisect run [--reset-when-found[=<where>]] <cmd> [<arg>...]
git bisect help

DESCRIPTION
-----------
Ez a parancs bináris kereső algoritmussal keresi meg, hogy a
projekted történetében melyik commit vezetett be egy hibát. Úgy
használod, hogy először megadsz egy "bad" (rossz) commitot, amelyről
tudott, hogy tartalmazza a hibát, és egy "good" (jó) commitot,
amelyről tudott, hogy a hiba bevezetése előttről van. Ezután a `git
bisect` kiválaszt egy commitot a két végpont között, kicheckoutolja, és
megkérdezi, hogy a kiválasztott commit "good" vagy "bad". Ezt a
tartomány szűkítését addig folytatja, amíg meg nem találja azt a
pontos commitot, amelyik a változást bevezette.

Valójában a `git bisect` felhasználható a projekted *bármely*
tulajdonságát megváltoztató commit megkeresésére; például annak a
commitnak a megkeresésére, amelyik kijavított egy hibát, vagy amelyik
javította egy benchmark teljesítményét. Ennek az általánosabb
használatnak a támogatására a "good" és "bad" helyett használhatók az
"old" (régi) és "new" (új) kifejezések is, vagy választhatsz saját
kifejezéseket. Bővebb információért lásd a lenti "Alternatív
kifejezések" szakaszt.

[[_basic_bisect_commands_start_bad_good]]
Alap bisect parancsok: start, bad, good
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Példaként tegyük fel, hogy meg akarod találni azt a commitot, amelyik
elrontott egy olyan funkciót, amely a projekted `v2.6.13-rc2` verziójában
még tudottan működött. A bisect munkamenetet a következőképpen indítod:

------------------------------------------------
$ git bisect start
$ git bisect bad                 # Current version is bad
$ git bisect good v2.6.13-rc2    # v2.6.13-rc2 is known to be good
------------------------------------------------

Miután megadtál legalább egy bad és egy good commitot, a `git
bisect` kiválaszt egy commitot a történet ezen tartományának
közepéről, kicheckoutolja, és kiír valami ehhez hasonlót:

------------------------------------------------
Bisecting: 675 revisions left to test after this (roughly 10 steps)
------------------------------------------------

Most fordítsd le a kicheckoutolt verziót, és teszteld le. Ha ez a
verzió megfelelően működik, írd be:

------------------------------------------------
$ git bisect good
------------------------------------------------

Ha ez a verzió hibás, írd be:

------------------------------------------------
$ git bisect bad
------------------------------------------------

Ekkor a `git bisect` valami ilyesmivel válaszol

------------------------------------------------
Bisecting: 337 revisions left to test after this (roughly 9 steps)
------------------------------------------------

Ismételd a folyamatot: fordítsd le a fát, teszteld le, és attól
függően, hogy jó vagy rossz, futtasd a `git bisect good` vagy a
`git bisect bad` parancsot, hogy bekérd a következő tesztelendő
commitot.

Végül nem marad több megvizsgálandó revízió, és a parancs kiírja az
első bad commit leírását. A `refs/bisect/bad` referencia ezen a
commiton marad.


[[_bisect_reset]]
Bisect reset
~~~~~~~~~~~~

Egy bisect munkamenet után, a bisect állapot letakarításához és az
eredeti `HEAD`-hez való visszatéréshez add ki a következő parancsot:

[synopsis]
git bisect reset

Alapértelmezetten ez visszaállítja a fádat arra a commitra, amely a
`git bisect start` előtt volt kicheckoutolva. (Egy új `git bisect
start` is ezt teszi, mivel letakarítja a régi bisect állapotot.)

Egy opcionális argumentummal helyette egy másik commitra is
visszatérhetsz:

[synopsis]
git bisect reset <commit>


Például a `git bisect reset bisect/bad` kicheckoutolja az első bad
revíziót, míg a `git bisect reset HEAD` az aktuális bisect commitnál
hagy, és teljesen elkerüli a commitváltást.


[[_alternate_terms]]
Alternatív kifejezések
~~~~~~~~~~~~~~~~~~~~~~

Néha nem egy hibát bevezető commitot keresel, hanem egy olyan
commitot, amelyik változást okozott valamilyen másik "old" (régi) és
"new" (új) állapot között. Például kereshetsz egy adott javítást
bevezető commitot. Vagy kereshetsz egy olyan első commitot, amelyben a
forráskód fájlnevei végre teljesen átálltak a céged elnevezési
szabványára. Vagy bármi más.

Ilyen esetekben nagyon zavaró lehet a "good" és "bad" kifejezéseket
használni "a változás előtti állapot" és "a változás utáni állapot"
jelölésére. Ehelyett tehát az "old" és "new" kifejezéseket
használhatod a "good" és "bad" helyett. (De vedd figyelembe, hogy egy
munkamenetben nem keverheted a "good"-ot és a "bad"-et az "old"-dal és
a "new"-vel.)

Ebben az általánosabb használatban egy "new" commitot adsz meg a `git
bisect`-nek, amelyiknek megvan egy adott tulajdonsága, és egy "old"
commitot, amelyiknek nincs meg. Minden alkalommal, amikor a `git
bisect` kicheckoutol egy commitot, teszteled, hogy megvan-e benne a
tulajdonság. Ha igen, jelöld meg a commitot "new"-ként; ha nem,
jelöld meg "old"-ként. Amikor a bisect befejeződött, a `git bisect`
jelenti, melyik commit vezette be a tulajdonságot.

Ahhoz, hogy "old"-ot és "new"-et használj "good" és "bad" helyett, a
`git bisect start` parancsot commitok nélkül, argumentum nélkül kell
futtatnod, majd a következő parancsokkal add hozzá a commitokat:

[synopsis]
git bisect old [<rev>]

annak jelzésére, hogy egy commit a keresett változás előtti volt, vagy

[synopsis]
git bisect new [<rev>...]

annak jelzésére, hogy utána volt.

Ahhoz, hogy emlékeztetőt kapj a jelenleg használt kifejezésekről,
használd a következőt

[synopsis]
git bisect terms

A régi kifejezést önmagában megkaphatod a `git bisect terms
--term-old` vagy a `git bisect terms --term-good` paranccsal; a `git
bisect terms --term-new` és a `git bisect terms --term-bad` pedig
arra használható, hogy megtudd, hogyan kell hívni a keresett
változásnál újabb commitokat.

Ha a "bad"/"good" vagy "new"/"old" helyett saját kifejezéseket
szeretnél használni, tetszőleges neveket választhatsz (a meglévő
bisect alparancsok, mint a `reset`, `start`, ... kivételével) a
bisect indításával, a következőt használva

[synopsis]
git bisect start --term-old <term-old> --term-new <term-new>

Például ha egy teljesítményromlást bevezető commitot keresel, ezt
használhatod

------------------------------------------------
$ git bisect start --term-old fast --term-new slow
------------------------------------------------

Vagy ha egy hibát kijavító commitot keresel, ezt használhatod

------------------------------------------------
$ git bisect start --term-new fixed --term-old broken
------------------------------------------------

Ezután a commitok megjelöléséhez a `git bisect good` és a `git bisect
bad` helyett a `git bisect <term-old>` és a `git bisect <term-new>`
parancsokat használd.

[[_bisect_visualize_view]]
Bisect visualize/view
~~~~~~~~~~~~~~~~~~~~~

Ahhoz, hogy megnézd a jelenleg fennmaradó gyanúsítottakat a `gitk`-ban,
add ki a következő parancsot a bisect folyamat közben (a `visualize`
alternatívájaként a `view` alparancs is használható):

------------
$ git bisect visualize
------------

A Git különféle környezeti változókon keresztül érzékeli a grafikus
környezetet:

`DISPLAY`:: amely Unix rendszereken X Window System környezetekben van beállítva.
`SESSIONNAME`:: amely Cygwin alatt interaktív asztali munkameneteknél van beállítva.
`MSYSTEM`:: amely Msys2 és a Git for Windows alatt van beállítva.
`SECURITYSESSIONID`:: amely macOS-en interaktív asztali munkameneteknél lehet beállítva.

Ha egyik ilyen környezeti változó sincs beállítva, helyette a `git log`
kerül használatra. Parancssori opciókat is megadhatsz, például
`-p`-t és `--stat`-ot.

------------
$ git bisect visualize --stat
------------

[[_bisect_log_and_bisect_replay]]
Bisect log és bisect replay
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Miután megjelölted a revíziókat good-ként vagy bad-ként, add ki a
következő parancsot, hogy megnézd, mi történt eddig:

------------
$ git bisect log
------------

Ha rájössz, hogy hibáztál egy revízió állapotának megadásában, elmentheted
ennek a parancsnak a kimenetét egy fájlba, szerkesztheted, hogy eltávolítsd
a hibás bejegyzéseket, majd a következő parancsokkal visszatérhetsz a
javított állapotra:

------------
$ git bisect reset
$ git bisect replay that-file
------------

[[_avoiding_testing_a_commit]]
Egy commit tesztelésének elkerülése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ha egy bisect munkamenet közepén tudod, hogy a felajánlott revízió
nem jó választás a teszteléshez (pl. nem fordul le, és tudod, hogy a
hiba semmi köze ahhoz a bughoz, amit üldözöl), kézzel is
kiválaszthatsz egy közeli commitot, és helyette azt tesztelheted.

Például:

------------
$ git bisect good/bad			# previous round was good or bad.
Bisecting: 337 revisions left to test after this (roughly 9 steps)
$ git bisect visualize			# oops, that is uninteresting.
$ git reset --hard HEAD~3		# try 3 revisions before what
					# was suggested
------------

Ezután fordítsd le és teszteld le a kiválasztott revíziót, majd a
szokásos módon jelöld meg a revíziót good-nak vagy bad-nek.

[[_bisect_skip]]
Bisect skip
~~~~~~~~~~~

Ahelyett, hogy magad választanál egy közeli commitot, megkérheted a
Gitet, hogy tegye ezt meg helyetted, a következő parancs kiadásával:

------------
$ git bisect skip                 # Current version cannot be tested
------------

Ha azonban a keresett commit szomszédját ugrod át, a Git nem fogja
tudni pontosan megmondani, hogy ezek közül a commitok közül melyik
volt az első bad.

Egyetlen commit helyett commitok tartományát is átugorhatod, a
tartomány-jelölés használatával. Például:

------------
$ git bisect skip v2.5..v2.6
------------

Ez azt mondja a bisect folyamatnak, hogy `v2.5` után egyetlen commitot
se teszteljen `v2.6`-ig bezárólag.

Vedd figyelembe, hogy ha a tartomány első commitját is át akarod
ugrani, a következő parancsot kell kiadnod:

------------
$ git bisect skip v2.5 v2.5..v2.6
------------

Ez azt mondja a bisect folyamatnak, hogy a `v2.5` és `v2.6` közötti
(bezárólag) commitokat ugorja át.

[[_bisect_next]]
Bisect next
~~~~~~~~~~~

Normál esetben, miután megjelöltél egy revíziót good-nak vagy
bad-nek, a Git automatikusan kiszámítja és kicheckoutolja a következő
tesztelendő revíziót. Ha azonban explicit módon kell kérned a
következő bisect lépést, ezt használhatod:

------------
$ git bisect next
------------

Ezt akkor használhatod, ha egy másik revízió kicheckoutolásával
megszakított bisect folyamatot szeretnél folytatni.

[[_cutting_down_bisection_by_giving_more_parameters_to_bisect_start]]
A keresés leszűkítése további paraméterek megadásával a bisect start parancsnál
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Tovább csökkentheted a próbálkozások számát, ha tudod, hogy a fa mely
része érintett a felkutatandó problémában: ehhez adj meg pathspec
paramétereket a `bisect start` parancs kiadásakor:

------------
$ git bisect start -- arch/i386 include/asm-i386
------------

Ha előre tudsz több good commitot, leszűkítheted a bisect keresési
teret az összes good commit megadásával közvetlenül a bad commit
után, a `bisect start` parancs kiadásakor:

------------
$ git bisect start v2.6.20-rc6 v2.6.20-rc4 v2.6.20-rc1 --
                   # v2.6.20-rc6 is bad
                   # v2.6.20-rc4 and v2.6.20-rc1 are good
------------

[[_bisect_run]]
Bisect run
~~~~~~~~~~

Ha van egy szkripted, amelyik meg tudja mondani, hogy az aktuális
forráskód good vagy bad, a következő parancs kiadásával bisectelhetsz:

[synopsis]
git bisect run <cmd> [<arg>...]

Vedd figyelembe, hogy az _<arg>_-gal futtatott _<cmd>_-nek 0 kóddal
kell kilépnie, ha az aktuális forráskód good/old, és 1 és 127 közötti
(bezárólag) kóddal, kivéve a 125-öt, ha az aktuális forráskód bad/new.

Bármilyen más kilépési kód megszakítja a bisect folyamatot. Meg kell
jegyezni, hogy egy `exit(-1)`-en keresztül kilépő program `$?` = 255
értéket hagy hátra (lásd az `exit`(3) man page-et), mivel az érték
`& 0377`-tel le van csonkítva.

A speciális 125-ös kilépési kódot akkor kell használni, amikor az
aktuális forráskód nem tesztelhető. Ha a szkript ezzel a kóddal lép
ki, az aktuális revízió átugrásra kerül (lásd a fenti `git bisect
skip`-et). A 125-öt azért választották, mert ez a legmagasabb ésszerű
érték, ami erre a célra használható, mivel a 126-ot és a 127-et a
POSIX shellek meghatározott hibaállapotok jelzésére használják (a 127
a "command not found", a 126 a "command found but not executable"
jelzésére szolgál -- ezek a részletek nem számítanak, mivel a
`bisect run` szempontjából ezek a szkript normál hibái).

Gyakran előfordulhat, hogy egy bisect munkamenet közben ideiglenes
módosításokat szeretnél (pl. `s/#define DEBUG 0/#define DEBUG 1/` egy
header fájlban, vagy "az a revízió, amelyben nincs meg ez a commit,
ehhez a patch-hez van szüksége, hogy megkerüljön egy másik problémát,
ami nem érdekes ennél a bisectnél") alkalmazni a tesztelt revízión.

Egy ilyen helyzet kezeléséhez, miután a belső `git bisect` megtalálta
a következő tesztelendő revíziót, a szkript a fordítás előtt
alkalmazhatja a patch-et, lefuttathatja a valódi tesztet, majd
eldöntheti, hogy a revízió (esetleg a szükséges patch-csel együtt)
átment-e a teszten, végül visszaállíthatja a fát az eredeti
állapotba. Végül a szkriptnek a valódi teszt állapotával kell
kilépnie, hogy a `git bisect run` parancs ciklusa meg tudja határozni
a bisect munkamenet végső eredményét.

OPTIONS
-------
`--no-checkout`::
	Ne checkoutolja ki az új munkakönyvtárat a bisect folyamat minden
	iterációjában. Ehelyett csak a `BISECT_HEAD` nevű referenciát
	frissíti úgy, hogy a tesztelendő commitra mutasson.
+
Ez az opció akkor lehet hasznos, ha a minden lépésben elvégzendő
teszt nem igényel kicheckoutolt fát.
+
Ha a repository bare, a `--no-checkout` automatikusan feltételezett.

`--first-parent`::
	Merge commit észlelésekor csak az első szülő commitot kövesse.
+
Egy branch mergelésén keresztül bevezetett regressziók felderítésekor
a merge commit lesz azonosítva a hiba bevezetéseként, és az ősei
figyelmen kívül maradnak.
+
Ez az opció különösen hasznos a téves pozitívok elkerülésében, amikor
egy mergelt branch hibás vagy nem lefordítható commitokat tartalmazott,
de maga a merge rendben volt.

`--reset-when-found[=<where>]`::
	Amint megtalálja az első bad commitot, jelenti azt, és letakarítja
	a bisect állapotot. A `<where>` lehet `original`, hogy visszatérjen
	a `git bisect start` előtt kicheckoutolt commitra, vagy `found`,
	hogy az első bad commit maradjon kicheckoutolva. Ha a `<where>`
	el van hagyva, az alapértelmezés `original`.
+
Ez az opció megadható a `git bisect start`-nak vagy a `git bisect
run`-nak. Nem használható `--no-checkout`-tal indított bisecthez.

EXAMPLES
--------

* Automatikusan bisectelj egy hibás buildet v1.2 és `HEAD` között:
+
------------
$ git bisect start HEAD v1.2 --      # HEAD is bad, v1.2 is good
$ git bisect run make                # "make" builds the app
$ git bisect reset                   # quit the bisect session
------------

* Automatikusan bisectelj egy tesztsikertelenséget origin és `HEAD` között:
+
------------
$ git bisect start HEAD origin --    # HEAD is bad, origin is good
$ git bisect run make test           # "make test" builds and tests
$ git bisect reset                   # quit the bisect session
------------

* Automatikusan bisectelj egy hibás tesztesetet:
+
------------
$ cat ~/test.sh
#!/bin/sh
make || exit 125                     # this skips broken builds
~/check_test_case.sh                 # does the test case pass?
$ git bisect start HEAD HEAD~10 --   # culprit is among the last 10
$ git bisect run ~/test.sh
$ git bisect reset                   # quit the bisect session
------------
+
Itt egy egyedi `test.sh` szkriptet használunk. Ebben a szkriptben, ha
a `make` sikertelen, átugorjuk az aktuális commitot.
A `check_test_case.sh`-nak `exit 0`-val kell kilépnie, ha a teszteset
sikeres, egyébként `exit 1`-gyel.
+
Biztonságosabb, ha mind a `test.sh`, mind a `check_test_case.sh` a
repository-n kívül van, hogy elkerüljük a bisect, a `make` és a
tesztfolyamatok, valamint a szkriptek közötti kölcsönhatásokat.

* Automatikusan bisectelj ideiglenes módosításokkal (hot-fix):
+
------------
$ cat ~/test.sh
#!/bin/sh

# tweak the working tree by merging the hot-fix branch
# and then attempt a build
if	git merge --no-commit --no-ff hot-fix &&
	make
then
	# run project specific test and report its status
	~/check_test_case.sh
	status=$?
else
	# tell the caller this is untestable
	status=125
fi

# undo the tweak to allow clean flipping to the next commit
git reset --hard

# return control
exit $status
------------
+
Ez minden tesztfuttatás előtt alkalmazza egy hot-fix branch
módosításait, pl. arra az esetre, ha a build- vagy tesztkörnyezeted
megváltozott, így a régebbi revízióknak szükségük lehet egy olyan
javításra, ami az újabbaknál már megvan. (Győződj meg róla, hogy a
hot-fix branch egy olyan commiton alapul, amely az összes bisectelt
revízióban benne van, hogy a merge ne húzzon be túl sok mindent, vagy
használj `git cherry-pick`-et `git merge` helyett.)

* Automatikusan bisectelj egy hibás tesztesetet:
+
------------
$ git bisect start HEAD HEAD~10 --   # culprit is among the last 10
$ git bisect run sh -c "make || exit 125; ~/check_test_case.sh"
$ git bisect reset                   # quit the bisect session
------------
+
Ez megmutatja, hogy elhagyhatod a futtató szkriptet, ha a tesztet
egyetlen sorban írod meg.

* Egy sértetlen tartomány megkeresése az objektumgráfban egy sérült
  repository-ban
+
------------
$ git bisect start HEAD <known-good-commit> [ <boundary-commit> ... ] --no-checkout
$ git bisect run sh -c '
	GOOD=$(git for-each-ref "--format=%(objectname)" refs/bisect/good-*) &&
	git rev-list --objects BISECT_HEAD --not $GOOD >tmp.$$ &&
	git pack-objects --stdout >/dev/null <tmp.$$
	rc=$?
	rm -f tmp.$$
	test $rc = 0'

$ git bisect reset                   # quit the bisect session
------------
+
Ebben az esetben, amikor a `git bisect run` befejeződik, a `bisect/bad`
egy olyan commitra fog hivatkozni, amelynek legalább egy olyan szülője
van, amelynek elérhető gráfja teljesen bejárható a `git pack-objects`
által megkövetelt értelemben.

* Javítás keresése regresszió helyett a kódban
+
------------
$ git bisect start
$ git bisect new HEAD    # current commit is marked as new
$ git bisect old HEAD~10 # the tenth commit from now is marked as old
------------
+
vagy:
+
------------
$ git bisect start --term-old broken --term-new fixed
$ git bisect fixed
$ git bisect broken HEAD~10
------------

[[_getting_help]]
Segítség kérése
~~~~~~~~~~~~~~~

A `git bisect` kiadásával rövid használati leírást kapsz, a `git
bisect help` vagy a `git bisect -h` kiadásával pedig hosszú
használati leírást.

SEE ALSO
--------
link:git-bisect-lk2009.html[Regressziók elleni küzdelem a git bisect-tel],
linkgit:git-blame[1].

GIT
---
A linkgit:git[1] csomag része
