git-for-each-repo(1)
====================

NAME
----
git-for-each-repo - Egy Git-parancsot futtat repository-k egy listáján


SYNOPSIS
--------
[verse]
'git for-each-repo' --config=<config> [--] <arguments>


DESCRIPTION
-----------
Egy Git-parancsot futtat repository-k egy listáján. Az ismert opciók
vagy a `--` jelölő utáni argumentumok a Git-alfolyamat argumentumaiként
használatosak.

EZ A PARANCS KÍSÉRLETI. A VISELKEDÉSE MEGVÁLTOZHAT.

Például futtathatunk karbantartást egy `maintenance.repo`
konfigurációs változóban tárolt repository-lista mindegyikén a
következővel:

-------------
git for-each-repo --config=maintenance.repo maintenance run
-------------

Ez a `git -C <repo> maintenance run`-t futtatja a `maintenance.repo`
többértékű konfigurációs változó minden `<repo>` értékére.


OPTIONS
-------
--config=<config>::
	A megadott konfigurációs változót abszolút útvonalneveket
	tároló, többértékű listaként használja. Végigmegy ezen az
	útvonallistán a megadott argumentumok futtatásához.
+
Ezek a konfigurációs értékek a rendszer-, a globális és a helyi
Git-konfigurációból töltődnek be, amennyiben elérhetők. Ha a
`git for-each-repo` egy olyan könyvtárban fut, amely nem Git
repository, akkor csak a rendszer- és a globális konfiguráció
használatos.

--keep-going::
	Folytatja a fennmaradó repository-kkal, ha a parancs
	sikertelen volt egy repository-n. A kilépési kód továbbra is
	azt jelzi, hogy az egész művelet nem volt sikeres.
+
Vedd figyelembe, hogy a sikertelen parancs pontos kilépési kódja
nem kerül továbbadásra a `for-each-repo` parancs kilépési kódjaként:
ha a parancs a megadott repository-k bármelyikében sikertelen volt,
az általános kilépési kód 1 lesz.

SUBPROCESS BEHAVIOR
-------------------

Ha bármelyik `git -C <repo> <arguments>` alfolyamat nem nulla
kilépési kóddal tér vissza, a `git for-each-repo` folyamat azzal a
kilépési kóddal tér vissza, további alfolyamatok futtatása nélkül.

Minden `git -C <repo> <arguments>` alfolyamat örökli a standard
`stdin`, `stdout` és `stderr` fájlleírókat.


GIT
---
A linkgit:git[1] csomag része
