git-notes(1)
============

NAME
----
git-notes - Objektumjegyzetek hozzáadása vagy megtekintése

SYNOPSIS
--------
[synopsis]
git notes [list [<object>]]
git notes add [-f] [--allow-empty] [--[no-]separator | --separator=<paragraph-break>] [--[no-]stripspace] [-F <file> | -m <msg> | (-c | -C) <object>] [-e] [<object>]
git notes copy [-f] ( --stdin | <from-object> [<to-object>] )
git notes append [--allow-empty] [--[no-]separator | --separator=<paragraph-break>] [--[no-]stripspace] [-F <file> | -m <msg> | (-c | -C) <object>] [-e] [<object>]
git notes edit [--allow-empty] [<object>] [--[no-]stripspace]
git notes show [<object>]
git notes merge [-v | -q] [-s <strategy> ] <notes-ref>
git notes merge --commit [-v | -q]
git notes merge --abort [-v | -q]
git notes remove [--ignore-missing] [--stdin] [<object>...]
git notes prune [-n] [-v]
git notes get-ref


DESCRIPTION
-----------
Objektumokhoz csatolt jegyzeteket ad hozzá, távolít el vagy olvas be,
anélkül, hogy magukhoz az objektumokhoz hozzányúlna.

Alapból a jegyzetek a `refs/notes/commits`-ba mentődnek, és onnan
olvasódnak be, de ez az alapértelmezés felülbírálható. Lásd az OPTIONS,
CONFIGURATION és ENVIRONMENT szakaszt lentebb. Ha ez a ref nem létezik,
csendben létrejön, amikor először van rá szükség egy jegyzet
tárolásához.

A jegyzetek tipikus felhasználása egy commit-üzenet kiegészítése magának
a commitnak a módosítása nélkül. A jegyzeteket a `git log` az eredeti
commit-üzenettel együtt meg tudja jeleníteni. Hogy ezek a jegyzetek
megkülönböztethetők legyenek a commitobjektumban tárolt üzenettől, a
jegyzetek az üzenethez hasonlóan vannak behúzva, egy be nem húzott sor
után, amely azt írja: „Notes (_<refname>_):" (vagy „Notes:" a
`refs/notes/commits` esetén).

A jegyzetek a `git format-patch`-csel előkészített patchekhez is
hozzáadhatók a `--notes` kapcsolóval. Az ilyen jegyzetek patch-kommentárként
kerülnek hozzáadásra egy három kötőjeles elválasztó sor után.

Hogy megváltoztasd, mely jegyzeteket jeleníti meg a `git log`, lásd a
`notes.displayRef` tárgyalását a <<CONFIGURATION,CONFIGURATION>>
szakaszban.

A commitokat átíró parancsokon átívelő jegyzetátvitel módjáról lásd a
`notes.rewrite.<command>` konfigurációt.


SUBCOMMANDS
-----------

`list`::
	Kilistázza egy adott objektum jegyzetobjektumát. Ha nincs
	objektum megadva, megjeleníti az összes jegyzetobjektum és az
	általuk annotált objektumok listáját (a "`<note-object>
	<annotated-object>`" formátumban). Ez az alapértelmezett
	alparancs, ha nincs alparancs megadva.

`add`::
	Jegyzeteket ad egy adott objektumhoz (alapból `HEAD`). Megszakad,
	ha az objektumnak már vannak jegyzetei (a `-f`-fel felülírhatók a
	meglévő jegyzetek). Ha viszont az `add`-et interaktívan használod
	(egy szerkesztővel adva meg a jegyzetek tartalmát), akkor —
	megszakadás helyett — a meglévő jegyzetek megnyílnak a
	szerkesztőben (mint az `edit` alparancsnál). Ha több `-m`-et és
	`-F`-et adsz meg, egy üres sor kerül beszúrásra az üzenetek közé. A
	`--separator` kapcsolóval más elválasztók is beszúrhatók. A `-e`-vel
	interaktívan (egy szerkesztővel) szerkesztheted és finomíthatod a
	`-m` és `-F` kapcsolóból megadott üzenete(ke)t a jegyzet
	hozzáadása előtt.

`copy`::
	Átmásolja az első objektum jegyzeteit a második objektumra (alapból
	`HEAD`). Megszakad, ha a második objektumnak már vannak jegyzetei,
	vagy ha az elsőnek nincsenek (a `-f`-fel felülírhatók a második
	objektum meglévő jegyzetei). Ez az alparancs a következővel
	egyenértékű:
	`git notes add [-f] -C $(git notes list <from-object>) <to-object>`
+
`--stdin` módban a
+
----------
<from-object> SP <to-object> [ SP <rest> ] LF
----------
+
formátumú sorokat veszi a standard bemenetről, és átmásolja a
jegyzeteket minden egyes _<from-object>_-ról a hozzá tartozó
_<to-object>_-ra. (Az opcionális _<rest>_ figyelmen kívül marad, hogy a
parancs be tudja olvasni a `post-rewrite` hooknak adott bemenetet.)
+
A `--stdin` nem kombinálható a parancssorban megadott
objektumnevekkel.

`append`::
	A `-m` vagy `-F` kapcsolóból megadott új üzenete(ke)t hozzáfűzi egy
	meglévő jegyzethez, vagy új jegyzetként adja hozzá őket, ha nincs
	ilyen, az objektumhoz (alapból `HEAD`). Meglévő jegyzethez való
	hozzáfűzéskor minden új üzenet elé egy üres sor kerül bekezdésközi
	elválasztóként. Az elválasztó a `--separator` kapcsolóval
	testreszabható. A `-e`-vel interaktívan (egy szerkesztővel)
	szerkeszd a `-m` és `-F` kapcsolóból megadott, hozzáfűzendő
	jegyzeteket a jegyzet hozzáfűzése előtt.

`edit`::
	Szerkeszti egy adott objektum jegyzeteit (alapból `HEAD`).

`show`::
	Megjeleníti egy adott objektum jegyzeteit (alapból `HEAD`).

`merge`::
	Merge-eli a megadott jegyzet-refet az aktuális jegyzet-refbe. Ez
	megpróbálja a megadott jegyzet-ref (a neve "remote") által a
	merge-alap (ha van) óta végzett módosításokat az aktuális
	jegyzet-refbe (a neve "local") merge-elni.
+
Ha konfliktusok merülnek fel, és nincs megadva stratégia a konfliktusos
jegyzetek automatikus feloldására (lásd a "NOTES MERGE STRATEGIES"
szakaszt), a `manual` feloldó kerül használatra. Ez a feloldó
checkoutolja a konfliktusos jegyzeteket egy speciális worktree-be
(`.git/NOTES_MERGE_WORKTREE`), és utasítja a felhasználót, hogy ott
kézzel oldja fel a konfliktusokat. Ha ezzel megvan, a felhasználó vagy
véglegesítheti a merge-et a `git notes merge --commit`-tal, vagy
megszakíthatja a merge-et a `git notes merge --abort`-tal.

`remove`::
	Eltávolítja a megadott objektumok jegyzeteit (alapból `HEAD`). Ha
	nulla vagy egy objektumot adsz meg a parancssorból, ez azzal
	egyenértékű, mintha üres jegyzetüzenetet adnál meg az `edit`
	alparancsnak.
+
`--stdin` módban a standard bemeneten megadott objektumneveket is
eltávolítja. Más szóval a `--stdin` kombinálható a parancssorból
származó objektumnevekkel.

`prune`::
	Eltávolítja az összes jegyzetet a nem létező/elérhetetlen
	objektumokhoz.

`get-ref`::
	Kiírja az aktuális jegyzet-refet. Ez egyszerű módot ad az aktuális
	jegyzet-ref lekérdezésére (pl. szkriptekből).

OPTIONS
-------
`-f`::
`--force`::
	Amikor olyan objektumhoz adsz jegyzeteket, amelynek már vannak
	jegyzetei, felülírja a meglévő jegyzeteket (megszakadás helyett).

`-m <msg>`::
`--message=<msg>`::
	A megadott jegyzetüzenetet használja (bekérés helyett). Ha több
	`-m` kapcsoló van megadva, az értékeik külön bekezdésekként
	fűződnek össze.

`-F <file>`::
`--file=<file>`::
	A jegyzetüzenetet a megadott fájlból veszi. A `-`-t használva a
	jegyzetüzenetet a standard bemenetről olvassa be.

`-C <object>`::
`--reuse-message=<object>`::
	A megadott blobobjektumot (például egy másik jegyzetet) veszi
	jegyzetüzenetnek. (Az objektumok közötti jegyzetmásoláshoz ehelyett
	a `git notes copy <object>`-et használd.) Maga után vonja a
	`--no-stripspace`-t, mivel az alapértelmezett viselkedés az üzenet
	szó szerinti másolása.

`-c <object>`::
`--reedit-message=<object>`::
	Mint a `-C`, de a `-c`-vel meghívódik a szerkesztő, hogy a
	felhasználó tovább tudja szerkeszteni a jegyzetüzenetet.

`--allow-empty`::
	Engedélyezi egy üres jegyzetobjektum tárolását. Az alapértelmezett
	viselkedés az üres jegyzetek automatikus eltávolítása.

`--separator=<paragraph-break>`::
`--separator`::
`--no-separator`::
	Megad egy sztringet, amely egyéni bekezdésközi elválasztóként
	szolgál (a végére szükség szerint sortörés kerül). Ha
	`--no-separator`, akkor nem kerülnek elválasztók a bekezdések közé.
	Alapból egy üres sor.

`--stripspace`::
`--no-stripspace`::
	Feltakarítja a whitespace-t. Pontosabban (lásd:
	linkgit:git-stripspace[1]):
+
--
- eltávolítja a sorvégi whitespace-t minden sorból
- több egymás utáni üres sort egyetlen üres sorrá von össze
- eltávolítja az üres sorokat a bemenet elejéről és végéről
- szükség esetén hozzáad egy hiányzó `\n`-t az utolsó sorhoz.
--
+
A `--stripspace` az alapértelmezés, kivéve a `-C`/`--reuse-message`
esetén. Ne feledd azonban, hogy ez a hasonló kapcsolók sorrendjétől
függ. Például a `-C <object> -m<message>` esetén a `--stripspace` kerül
használatra, mert a `-m` alapértelmezése felülbírálja a korábbi `-C`-t.
Ez egy ismert korlát, amit a jövőben lehet, hogy kijavítanak.

`--ref=<ref>`::
	A `_<ref>_`-ben lévő jegyzetfát manipulálja. Ez felülbírálja a
	`GIT_NOTES_REF`-et és a `core.notesRef` konfigurációt. A ref a
	teljes refnevet adja meg, ha `refs/notes/`-szal kezdődik; ha
	`notes/`-szal kezdődik, akkor `refs/` kerül elé, egyébként pedig
	`refs/notes/` kerül elé, hogy a ref teljes neve létrejöjjön.

`--ignore-missing`::
	Nem tekinti hibának, ha olyan objektumtól kérsz jegyzeteltávolítást,
	amelyhez nincsenek jegyzetek csatolva.

`--stdin`::
	Csak a `remove` és `copy` esetén érvényes. Lásd az adott
	alparancsokat.

`-n`::
`--dry-run`::
	Nem távolít el semmit; csak jelenti azoknak az objektumoknak a
	nevét, amelyeknek a jegyzetei eltávolításra kerülnének.

`-s <strategy>`::
`--strategy=<strategy>`::
	Jegyzetek merge-elésekor a jegyzetkonfliktusokat a megadott
	stratégiával oldja fel. A következő stratégiák ismertek: `manual`
	(alapértelmezett), `ours`, `theirs`, `union` és `cat_sort_uniq`.
	Ez a kapcsoló felülbírálja a `notes.mergeStrategy` konfigurációs
	beállítást. Az egyes jegyzet-merge-stratégiákról bővebb
	információért lásd a "NOTES MERGE STRATEGIES" szakaszt lentebb.

`--commit`::
	Véglegesít egy folyamatban lévő `git notes merge`-et. Akkor
	használd ezt a kapcsolót, ha feloldottad a konfliktusokat,
	amelyeket a `git notes merge` a `.git/NOTES_MERGE_WORKTREE`-ben
	tárolt. Ez amendeli a `git notes merge` által létrehozott
	részleges merge commitot (amely a `.git/NOTES_MERGE_PARTIAL`-ban
	van tárolva) a `.git/NOTES_MERGE_WORKTREE`-ben lévő jegyzetek
	hozzáadásával. A `.git/NOTES_MERGE_REF` symrefben tárolt
	jegyzet-ref az eredményül kapott commitra frissül.

`--abort`::
	Megszakít/visszaállít egy folyamatban lévő `git notes merge`-et,
	azaz egy konfliktusokkal járó jegyzet-merge-et. Ez egyszerűen
	eltávolítja a jegyzet-merge-hez kapcsolódó összes fájlt.

`-q`::
`--quiet`::
	Jegyzetek merge-elésekor csendben működik.

`-v`::
`--verbose`::
	Jegyzetek merge-elésekor bőbeszédűbb. Jegyzetek prune-olásakor
	jelenti az összes objektum nevét, amelynek a jegyzetei eltávolításra
	kerülnek.


DISCUSSION
----------

A commitjegyzetek olyan blobok, amelyek egy objektumról extra
információt tartalmaznak (általában a commit üzenetét kiegészítő
információt). Ezeket a blobokat a jegyzet-refekből veszi. Egy
jegyzet-ref általában egy branch, amely olyan „fájlokat" tartalmaz,
amelyeknek az útvonalai az általuk leírt objektumok objektumnevei,
néhány könyvtárelválasztóval a teljesítmény érdekében
footnote:[A megengedett útvonalneveknek a
'bf'`/`'fe'`/`'30'`/`'...'`/`'680d5a...' alakja van: kétjegyű
hexadecimális könyvtárnevek sorozata, amelyet egy fájlnév követ az
objektumazonosító maradékával.].

Minden jegyzetváltozás egy új commitot hoz létre a megadott
jegyzet-refnél. A jegyzetek történetét tehát megtekintheted például a
`git log -p notes/commits` meghívásával. Jelenleg a commit-üzenet csak
azt rögzíti, hogy melyik művelet váltotta ki a frissítést, és a commit
szerzősége a szokásos szabályok szerint dől el (lásd:
linkgit:git-commit[1]). Ezek a részletek a jövőben változhatnak.

Az is megengedett, hogy egy jegyzet-ref közvetlenül egy treeobjektumra
mutasson, amely esetben a jegyzetek története a
`git log -p -g <refname>`-mel olvasható.


NOTES MERGE STRATEGIES
----------------------

Az alapértelmezett jegyzet-merge-stratégia a `manual`, amely a
konfliktusos jegyzeteket egy speciális work tree-ben checkoutolja a
jegyzetkonfliktusok feloldásához (`.git/NOTES_MERGE_WORKTREE`), és
utasítja a felhasználót, hogy abban a work tree-ben oldja fel a
konfliktusokat.
Ha ezzel megvan, a felhasználó vagy véglegesítheti a merge-et a
`git notes merge --commit`-tal, vagy megszakíthatja a merge-et a
`git notes merge --abort`-tal.

A felhasználók az alábbiak közül választhatnak automatizált
merge-stratégiát, akár a `-s`/`--strategy` kapcsolóval, akár a
`notes.mergeStrategy` megfelelő beállításával:

Az `ours` automatikusan a helyi verzió (azaz az aktuális jegyzet-ref)
javára oldja fel a konfliktusos jegyzeteket.

A `theirs` automatikusan a remote verzió (azaz az aktuális jegyzet-refbe
merge-elt megadott jegyzet-ref) javára oldja fel a jegyzetkonfliktusokat.

A `union` automatikusan a helyi és a remote verzió összefűzésével oldja
fel a jegyzetkonfliktusokat.

A `cat_sort_uniq` hasonló a `union`-höz, de a helyi és a remote verzió
összefűzésén túl ez a stratégia rendezi is az eredményül kapott sorokat,
és eltávolítja a duplikált sorokat az eredményből. Ez azzal
egyenértékű, mintha a "cat | sort | uniq" shell pipeline-t alkalmaznád a
helyi és a remote verzióra. Ez a stratégia akkor hasznos, ha a jegyzetek
soralapú formátumot követnek, ahol el akarod kerülni a duplikált sorokat
a merge eredményében. Vedd figyelembe, hogy ha akár a helyi, akár a
remote verzió tartalmaz duplikált sorokat a merge előtt, ezeket is
eltávolítja ez a jegyzet-merge-stratégia.


EXAMPLES
--------

A jegyzeteket olyan annotációk hozzáadására használhatod, amelyek
olyan információt tartalmaznak, ami nem volt elérhető egy commit
megírásának idején.

------------
$ git notes add -m 'Tested-by: Johannes Sixt <j6t@kdbg.org>' 72a144e2
$ git show -s 72a144e
[...]
    Signed-off-by: Junio C Hamano <gitster@pobox.com>

Notes:
    Tested-by: Johannes Sixt <j6t@kdbg.org>
------------

Elvben egy jegyzet egy közönséges Git-blob, és bármilyen (nem-)formátum
elfogadott. Tetszőleges fájlokból bináris-biztosan hozhatsz létre
jegyzeteket a `git hash-object`-tel:

------------
$ cc *.c
$ blob=$(git hash-object -w a.out)
$ git notes --ref=built add --allow-empty -C "$blob" HEAD
------------

(Nem használhatod egyszerűen a `git notes --ref=built add -F a.out HEAD`-et,
mert az nem bináris-biztos.)
Persze nincs sok értelme nem-szöveges formátumú jegyzeteket megjeleníteni
a `git log`-gal, így ha ilyen jegyzeteket használsz, valószínűleg
speciális célú eszközöket kell írnod, hogy valami hasznosat kezdj velük.


[[CONFIGURATION]]
CONFIGURATION
-------------

`core.notesRef`::
	A `refs/notes/commits` helyett olvasandó és manipulálandó
	jegyzet-ref. Rövidítetlen refnévnek kell lennie. Ez a beállítás
	felülbírálható a környezeten és a parancssoron keresztül.

include::includes/cmd-config-section-rest.adoc[]

include::config/notes.adoc[]


ENVIRONMENT
-----------

`GIT_NOTES_REF`::
	Melyik refből manipulálja a jegyzeteket, a `refs/notes/commits`
	helyett. Ez felülbírálja a `core.notesRef` beállítást.

`GIT_NOTES_DISPLAY_REF`::
	Refek vagy globok kettősponttal elválasztott listája, amely azt
	jelzi, mely refekből — a `core.notesRef` vagy a `GIT_NOTES_REF`
	alapértelmezésén felül — olvasson be jegyzeteket a commit-üzenetek
	megjelenítésekor.
	Ez felülbírálja a `notes.displayRef` beállítást.
+
A nem létező refekhez figyelmeztetés jár, de egy olyan glob, amely
egyetlen refre sem illeszkedik, csendben figyelmen kívül marad.

`GIT_NOTES_REWRITE_MODE`::
	Jegyzetek átírás közbeni másolásakor mit tegyen, ha a cél
	commitnak már van jegyzete.
	Az `overwrite`, `concatenate`, `cat_sort_uniq` vagy `ignore` egyike
	kell legyen.
	Ez felülbírálja a `core.rewriteMode` beállítást.

`GIT_NOTES_REWRITE_REF`::
	Commitok átírásakor mely jegyzeteket másolja az eredetiről az
	átírt commitra. Refek vagy globok kettősponttal elválasztott
	listája kell legyen.
+
Ha a környezetben nincs beállítva, a másolandó jegyzetek listája a
`notes.rewrite.<command>` és a `notes.rewriteRef` beállításoktól függ.

GIT
---
A linkgit:git[1] csomag része
