git-grep(1)
===========

NAME
----
git-grep - Mintára illeszkedő sorok kiírása


SYNOPSIS
--------
[synopsis]
git grep [-a | --text] [-I] [--textconv] [-i | --ignore-case] [-w | --word-regexp]
	   [-v | --invert-match] [-h|-H] [--full-name]
	   [-E | --extended-regexp] [-G | --basic-regexp]
	   [-P | --perl-regexp]
	   [-F | --fixed-strings] [-n | --line-number] [--column]
	   [-l | --files-with-matches] [-L | --files-without-match]
	   [(-O | --open-files-in-pager) [<pager>]]
	   [-z | --null]
	   [ -o | --only-matching ] [-c | --count] [--all-match] [-q | --quiet]
	   [--max-depth <depth>] [--[no-]recursive]
	   [--color[=<when>] | --no-color]
	   [--break] [--heading] [-p | --show-function]
	   [-A <post-context>] [-B <pre-context>] [-C <context>]
	   [-W | --function-context]
	   [(-m | --max-count) <num>]
	   [--threads <num>]
	   [-f <file>] [-e] <pattern>
	   [--and|--or|--not|(|)|-e <pattern>...]
	   [--recurse-submodules] [--parent-basename <basename>]
	   [ [--[no-]exclude-standard] [--cached | --untracked | --no-index] | <tree>...]
	   [--] [<pathspec>...]

DESCRIPTION
-----------
Megadott mintákat keres a work tree nyomon követett fájljaiban, az index
fájlban regisztrált blobokban, vagy adott tree objektumokban lévő blobokban.
A minták egy vagy több, sortörés karakterekkel elválasztott keresési
kifejezés listái.  Üres sztring keresési kifejezésként minden sorra
illeszkedik.


OPTIONS
-------
`--cached`::
	A working tree nyomon követett fájljainak keresése helyett az index
	fájlban regisztrált blobokban keres.

`--untracked`::
	A working tree nyomon követett fájljaiban való keresés mellett a
	nyomon nem követett fájlokban is keres.

`--no-index`::
	A Git által nem kezelt fájlokat keres az aktuális könyvtárban, vagy
	figyelmen kívül hagyva, hogy az aktuális könyvtárat a Git kezeli.  Ez
	elég hasonló a szokásos `grep`(1) segédprogram `-r` opcióval való
	futtatásához, de néhány további előnnyel, például pathspec minták
	használatával az útvonalak korlátozására;  további információért lásd a
	`pathspec` bejegyzést a linkgit:gitglossary[7] oldalon.
+
Ez az opció nem használható a `--cached` vagy a `--untracked` opcióval
együtt. Lásd még a `grep.fallbackToNoIndex`-et a lenti 'CONFIGURATION'-ben.

`--no-exclude-standard`::
	Az ignorált fájlokban is keres, mivel nem veszi figyelembe a
	`.gitignore` mechanizmust. Csak a `--untracked`-kel hasznos.

`--exclude-standard`::
	Ne figyeljen a `.gitignore` mechanizmuson keresztül megadott ignorált
	fájlokra.  Csak akkor hasznos, amikor a `--no-index`-szel keres
	fájlokat az aktuális könyvtárban.

`--recurse-submodules`::
	Rekurzívan keres minden submodule-ban, amely aktív és ki van
	checkoutolva a repositoryban.  A _<tree>_ opcióval kombinálva
	használva minden submodule-kimenet előtagja a szülőprojekt _<tree>_
	objektumának a neve lesz.  Ez az opció nem használható a
	`--untracked`-kel együtt, és nincs hatása, ha a `--no-index` meg van
	adva.

`-a`::
`--text`::
	A bináris fájlokat úgy dolgozza fel, mintha szöveg lennének.

`--textconv`::
	Figyelembe veszi a textconv szűrő beállításait.

`--no-textconv`::
	Ne vegye figyelembe a textconv szűrő beállításait.
	Ez az alapértelmezés.

`-i`::
`--ignore-case`::
	Figyelmen kívül hagyja a kis-/nagybetűk közti eltéréseket a minták és
	a fájlok között.

`-I`::
	Ne illessze a mintát a bináris fájlokban.

`--max-depth <depth>`::
	A parancssorban megadott minden _<pathspec>_-hez legfeljebb _<depth>_
	szintnyi könyvtárba ereszkedik le. A -1 érték korlát nélkülit jelent.
	Ez az opció figyelmen kívül marad, ha a _<pathspec>_ aktív
	helyettesítő karaktereket tartalmaz.
	Más szóval, ha az "a*" egy "a*" nevű könyvtárra illeszkedik,
	a "*" literálisan illeszkedik, így a `--max-depth` továbbra is hatásos.

`-r`::
`--recursive`::
	Ugyanaz, mint a `--max-depth=-1`; ez az alapértelmezés.

`--no-recursive`::
	Ugyanaz, mint a `--max-depth=0`.

`-w`::
`--word-regexp`::
	A mintát csak szóhatáron illeszti (vagy egy sor elején kezdődik, vagy
	nem szó karakter előzi meg; egy sor végén ér véget, vagy nem szó
	karakter követi).

`-v`::
`--invert-match`::
	A nem illeszkedő sorokat választja ki.

`-h`::
`-H`::
	Alapértelmezés szerint a parancs minden találathoz megjeleníti a
	fájlnevet.  A `-h` opció ennek a kimenetnek az elnyomására szolgál.
	A `-H` a teljesség kedvéért van ott, és nem csinál semmit, azon
	kívül, hogy felülírja a parancssorban korábban megadott `-h`-t.

`--full-name`::
	Alkönyvtárból futtatva a parancs általában az aktuális könyvtárhoz
	relatív útvonalakat ír ki.  Ez az opció kikényszeríti, hogy az
	útvonalak a projekt legfelső könyvtárához relatívan íródjanak ki.

`-E`::
`--extended-regexp`::
`-G`::
`--basic-regexp`::
	POSIX kiterjesztett/alap regexpet használ a mintákhoz.  Az
	alapértelmezés az alap regexp használata.

`-P`::
`--perl-regexp`::
	Perl-kompatibilis reguláris kifejezéseket használ a mintákhoz.
+
Az ilyen típusú reguláris kifejezések támogatása egy opcionális
fordításidejű függőség. Ha a Gitet nem támogatásukkal fordították le, ennek
az opciónak a megadása miatt meg fog halni.

`-F`::
`--fixed-strings`::
	Fix sztringeket használ a mintákhoz (ne értelmezze a mintát
	regexként).

`-n`::
`--line-number`::
	Az illeszkedő sorok elé teszi a sorszámot.

`--column`::
	Az illeszkedő sor elejétől számított első találat 1-alapú
	bájt-eltolását teszi elé.

`-l`::
`--files-with-matches`::
`--name-only`::
`-L`::
`--files-without-match`::
	Minden illeszkedő sor megjelenítése helyett csak azon fájlok neveit
	jeleníti meg, amelyek találatot tartalmaznak (vagy nem tartalmaznak).
	A `git diff`-fel való jobb kompatibilitás érdekében a `--name-only` a
	`--files-with-matches` szinonimája.

`-O[<pager>]`::
`--open-files-in-pager[=<pager>]`::
	Az illeszkedő fájlokat a pagerben nyitja meg (nem a `grep` kimenetét).
	Ha a pager történetesen "less" vagy "vi", és a felhasználó csak egy
	mintát adott meg, az első fájl automatikusan az első találatra
	pozicionálódik. A `pager` argumentum opcionális; ha meg van adva,
	szóköz nélkül az opcióhoz kell ragasztani. Ha a `pager` nincs
	megadva, az alapértelmezett pager lesz használatban (lásd a
	`core.pager`-t a linkgit:git-config[1] oldalon).

`-z`::
`--null`::
	A \0-t használja az útvonalnevek elválasztójaként a kimenetben, és
	szó szerint írja ki őket. Ez az opció nélkül a "szokatlan"
	karaktereket tartalmazó útvonalneveket a `core.quotePath`
	konfigurációs változónál leírtak szerint idézőjelezi (lásd
	linkgit:git-config[1]).

`-o`::
`--only-matching`::
	Egy illeszkedő sornak csak az illeszkedő (nem üres) részeit írja ki,
	minden ilyen részt külön kimeneti sorban.

`-c`::
`--count`::
	Minden illeszkedő sor megjelenítése helyett az illeszkedő sorok
	számát jeleníti meg.

`--color[=<when>]`::
	Színes találatokat mutat.
	Az érték `always` (az alapértelmezés), `never` vagy `auto` kell hogy
	legyen.

`--no-color`::
	Kikapcsolja a találatok kiemelését, még akkor is, amikor a
	konfigurációs fájl a színes kimenetet adja alapértelmezésnek.
	Ugyanaz, mint a `--color=never`.

`--break`::
	Üres sort ír ki a különböző fájlokból származó találatok közé.

`--heading`::
	A fájlnevet az adott fájlbeli találatok fölött jeleníti meg, nem
	pedig minden megjelenített sor elején.

`-p`::
`--show-function`::
	Megjeleníti a találat előtti sort, amely a találat függvénynevét
	tartalmazza, hacsak az illeszkedő sor maga nem egy függvénynév.
	A nevet ugyanúgy határozza meg, ahogy a `git diff` állítja elő a
	patch hunk-fejléceket (lásd a 'Defining a custom hunk-header'-t a
	linkgit:gitattributes[5] oldalon).

`-<num>`::
`-C <num>`::
`--context <num>`::
	Megjelenít _<num>_ megelőző és követő sort, és egy `--`-t tartalmazó
	sort helyez a találatok összefüggő csoportjai közé.

`-A <num>`::
`--after-context <num>`::
	Megjelenít _<num>_ követő sort, és egy `--`-t tartalmazó sort helyez a
	találatok összefüggő csoportjai közé.

`-B <num>`::
`--before-context <num>`::
	Megjelenít _<num>_ megelőző sort, és egy `--`-t tartalmazó sort helyez
	a találatok összefüggő csoportjai közé.

`-W`::
`--function-context`::
	Megjeleníti a környező szöveget az előző, függvénynevet tartalmazó
	sortól a következő függvénynév előttiig, gyakorlatilag megmutatva a
	teljes függvényt, amelyben a találatot megtalálta. A függvényneveket
	ugyanúgy határozza meg, ahogy a `git diff` állítja elő a patch
	hunk-fejléceket (lásd a 'Defining a custom hunk-header'-t a
	linkgit:gitattributes[5] oldalon).

`-m <num>`::
`--max-count <num>`::
	Korlátozza a fájlonkénti találatok számát. A `-v` vagy a
	`--invert-match` opció használatakor a keresés a megadott számú
	nem-találat után leáll. A -1 érték korlátlan eredményt ad vissza (ez
	az alapértelmezés). A 0 érték azonnal kilép egy nem nulla állapottal.

`--threads <num>`::
	A használandó `grep` munkaszálak száma.  További információért lásd a
	`NOTES ON THREADS`-et és a `grep.threads`-et a 'CONFIGURATION'-ben.

`-f <file>`::
	Mintákat olvas a _<file>_-ból, soronként egyet.
+
A minta _<file>_-on keresztüli átadása lehetővé teszi \0-t tartalmazó
keresési minta megadását.
+
Nem minden mintatípus támogatja a \0-t tartalmazó mintákat. A Git hibával
kilép, ha egy adott mintatípus nem tud támogatni ilyen mintát. A
`--perl-regexp` mintatípusnak van a legszélesebb támogatása az ilyen típusú
mintákhoz, amikor a PCRE v2 backend ellen fordítják.
+
A Git 2.23.0 előtti verzióiban a \0-t tartalmazó mintákat csendben fixnek
tekintette. Ez soha nem volt dokumentálva, és voltak furcsa és
dokumentálatlan interakciók is pl. \0-t tartalmazó nem ASCII minták és a
`--ignore-case` között.
+
A jövőbeli verziókban megtanulhatjuk a \0-t tartalmazó minták támogatását
több keresési backendhez, addig meghalunk, amikor a szóban forgó mintatípus
nem támogatja őket.

`-e`::
	A következő paraméter a minta. Ezt az opciót a `-`-jellel kezdődő
	mintákhoz kell használni, és a felhasználói bemenetet a grepnek átadó
	szkriptekben kell használni.  Több mintát `or` kombinál.

`--and`::
`--or`::
`--not`::
`( ... )`::
	Megadja, hogyan kombinálódik több minta Boole-kifejezésekkel.  A
	`--or` az alapértelmezett operátor.  A `--and` magasabb precedenciájú,
	mint a `--or`.  A `-e`-t minden mintához használni kell.

`--all-match`::
	Amikor több, `--or`-ral kombinált mintakifejezést adsz meg, ez a
	kapcsoló arra szolgál, hogy a találatot azokra a fájlokra korlátozza,
	amelyekben van olyan sor, amely mindegyikre illeszkedik.

`-q`::
`--quiet`::
	Ne írja ki az illeszkedő sorokat; ehelyett 0 állapottal lépjen ki,
	amikor van találat, és nem nulla állapottal, amikor nincs.

`<tree>...`::
	A working tree nyomon követett fájljainak keresése helyett az adott
	fákban lévő blobokban keres.

`--`::
	Az opciók végét jelzi; a többi paraméter _<pathspec>_ korlátozó.

`<pathspec>...`::
	Ha meg van adva, a keresést a legalább egy mintára illeszkedő
	útvonalakra korlátozza.
	A vezető útvonalak illeszkedése és a `glob`(7) minták is támogatottak.
+
A _<pathspec>_ szintaxisáról bővebben lásd a `pathspec` bejegyzést a
linkgit:gitglossary[7] oldalon.

EXAMPLES
--------

`git grep 'time_t' -- '*.[ch]'`::
	A `time_t`-t keresi az összes nyomon követett .c és .h fájlban a
	munkakönyvtárban és annak alkönyvtáraiban.

`git grep -e '#define' --and \( -e MAX_PATH -e PATH_MAX \)`::
	Olyan sort keres, amelyben van `#define`, és `MAX_PATH` vagy
	`PATH_MAX` is.

`git grep --all-match -e NODE -e Unexpected`::
	Olyan sort keres, amelyben van `NODE` vagy `Unexpected`, olyan
	fájlokban, amelyekben van mindkettőre illeszkedő sor.

`git grep solution -- :^Documentation`::
	A `solution`-t keresi, kihagyva a `Documentation`-ben lévő fájlokat.

NOTES ON THREADS
----------------

A `--threads` opció (és a `grep.threads` konfiguráció) figyelmen kívül marad,
amikor a `--open-files-in-pager` használatban van, egyszálas végrehajtást
kényszerítve.

Az objektumadatbázisban való grepeléskor (a `--cached`-kel vagy tree
objektumok megadásával) a több szállal való futás lassabb lehet, mint az
egyszálas, ha a `--textconv` meg van adva, és túl sok a szövegkonverzió.
Ezért ha ebben az esetben alacsony teljesítményt tapasztalsz, kívánatos lehet
a `--threads=1` használata.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/grep.adoc[]

GIT
---
A linkgit:git[1] csomag része
