git-check-ref-format(1)
=======================

NAME
----
git-check-ref-format - Ellenőrzi, hogy egy referencianév helyesen van-e formázva

SYNOPSIS
--------
[verse]
'git check-ref-format' [--normalize]
       [--[no-]allow-onelevel] [--refspec-pattern]
       <refname>
'git check-ref-format' --branch <branchname-shorthand>

DESCRIPTION
-----------
Ellenőrzi, hogy egy adott 'refname' elfogadható-e, és ha nem, nullától
eltérő státusszal lép ki.

A Git egy referenciát használ a branchek és tagek megadására. A
branch-head a `refs/heads` hierarchiában, a tag pedig a ref-névtér
`refs/tags` hierarchiájában van tárolva (jellemzően a
`$GIT_DIR/refs/heads` és `$GIT_DIR/refs/tags` könyvtárakban, vagy –
ha a refeket a `git gc` becsomagolta – a `$GIT_DIR/packed-refs`
fájl bejegyzéseiként).

A Git a következő szabályokat írja elő a referenciák elnevezésére:

. Tartalmazhatnak perjelet (`/`) hierarchikus (könyvtár szerinti)
  csoportosításhoz, de egyetlen perjellel elválasztott komponens sem
  kezdődhet ponttal (`.`), és nem végződhet a `.lock` szekvenciával.

. Legalább egy `/` jelet tartalmazniuk kell. Ez kikényszeríti egy
  olyan kategória jelenlétét, mint a `heads/`, `tags/` stb., de a
  tényleges nevek nincsenek korlátozva. Ha a `--allow-onelevel`
  opciót használjuk, ez a szabály elengedésre kerül.

. Sehol sem tartalmazhatnak két egymást követő pontot (`..`).

. Sehol sem tartalmazhatnak ASCII vezérlőkaraktereket (azaz olyan
  bájtokat, amelyek értéke kisebb, mint \040, vagy \177 `DEL`),
  szóközt, tildét (`~`), kalapjelet (`^`) vagy kettőspontot (`:`).

. Sehol sem tartalmazhatnak kérdőjelet (`?`), csillagot (`*`) vagy
  nyitó szögletes zárójelet (`[`). L. a lenti `--refspec-pattern`
  opciót e szabály alóli kivételért.

. Nem kezdődhetnek és nem végződhetnek perjellel (`/`), és nem
  tartalmazhatnak több egymást követő perjelet (l. a lenti
  `--normalize` opciót e szabály alóli kivételért).

. Nem végződhetnek ponttal (`.`).

. Nem tartalmazhatják a `@{` szekvenciát.

. Nem lehetnek egyetlen `@` karakterből állók.

. Nem tartalmazhatnak `\` karaktert.

Ezek a szabályok megkönnyítik a shell szkript alapú eszközök számára a
referencianevek értelmezését, a shell által – tévedésből idézőjelek
nélkül használt referencianév esetén – végzett elérésiút-kiterjesztést,
és emellett elkerülik a kétértelműséget bizonyos referencianév-
kifejezésekben (l. linkgit:gitrevisions[7]):

. A kettőspont-pont (`..`) gyakran használatos, mint például a
  `ref1..ref2` alakban, és bizonyos kontextusokban ez a jelölés
  `^ref1 ref2`-t jelent (azaz nincs benne `ref1`-ben és benne van
  `ref2`-ben).

. A tilde (`~`) és a kalapjel (`^`) a posztfix 'n-edik szülő' és
  'hagymahámozó' művelet bevezetésére szolgál.

. A kettőspont (`:`) a `srcref:dstref` alakban azt jelenti, hogy
  "használd a srcref értékét, és tárold el dstref-ben" fetch és push
  műveletekben. Emellett egy adott objektum kiválasztására is
  használható, mint például a 'git cat-file' esetén: "git cat-file
  blob v1.3.3:refs.c".

. A kukac-nyitókapocs (`@{`) egy reflog-bejegyzés eléréséhez használt
  jelölés.

A `--branch` opcióval a parancs egy nevet vesz át, és ellenőrzi, hogy az
használható-e érvényes branch-névként (pl. új branch létrehozásakor).
Ugyanakkor legyünk óvatosak az „előző checkout" szintaxis használatakor,
amely leválasztott HEAD állapotra is hivatkozhat.
A `git check-ref-format --branch $name` által megvalósított szabály
szigorúbb lehet annál, mint amit a `git check-ref-format
refs/heads/$name` mond ki (pl. egy kötőjel megjelenhet egy
ref-komponens elején, de egy branch-név elején kifejezetten tilos).
Amikor a `--branch` opcióval egy repository-ban futtatjuk, a bemenet
először az ``előző checkout szintaxis'' (`@{-n}`) szerint kerül
kiterjesztésre. Például a `@{-1}` az utoljára "git switch" vagy
"git checkout" művelettel kicheckoutolt dologra hivatkozás egy módja.
Ezt az opciót a porcelain parancsoknak kell használniuk, hogy elfogadják
ezt a szintaxist bárhol, ahol egy branch-nevet várnak, így úgy tudnak
viselkedni, mintha a branch nevét gépeltük volna be. Kivételként
megjegyzendő, hogy az ``előző checkout művelet'' commit-objektumnevet
is eredményezhet, ha az N-edik utoljára kicheckoutolt dolog nem volt
branch.

OPTIONS
-------
--allow-onelevel::
--no-allow-onelevel::
	Vezérli, hogy az egyszintű refnevek elfogadhatók-e (azaz olyan
	refnevek, amelyek nem tartalmaznak több `/`-lel elválasztott
	komponenst). Az alapértelmezés a `--no-allow-onelevel`.

--refspec-pattern::
	A <refname>-et egy refspechez tartozó referencianév-mintaként
	értelmezi (ahogyan a remote repository-knál használatos). Ha ez
	az opció engedélyezve van, a <refname> tartalmazhat egyetlen
	`*` karaktert a refspecben (pl. `foo/bar*/baz` vagy
	`foo/bar*baz/`, de nem `foo/bar*/baz*`).

--normalize::
	Normalizálja a 'refname'-et a vezető perjel- (`/`) karakterek
	eltávolításával, és a névkomponensek közötti egymást követő
	perjeleket egyetlen perjellé vonja össze. Ha a normalizált
	refname érvényes, kiírja a standard kimenetre, és 0-s
	státusszal lép ki, egyébként nullától eltérő státusszal lép ki.
	(A `--print` a `--normalize` elavult írásmódja.)


EXAMPLES
--------

* Az utoljára kicheckoutolt dolog nevének kiírása:
+
------------
$ git check-ref-format --branch @{-1}
------------

* Egy új branchhez használandó referencianév meghatározása:
+
------------
$ ref=$(git check-ref-format --normalize "refs/heads/$newbranch")||
{ echo "we do not like '$newbranch' as a branch name." >&2 ; exit 1 ; }
------------

GIT
---
A linkgit:git[1] csomag része
