git-revert(1)
=============

NAME
----
git-revert - Néhány meglévő commit revertelése

SYNOPSIS
--------
[verse]
'git revert' [--[no-]edit] [-n] [-m <parent-number>] [-s] [-S[<keyid>]] <commit>...
'git revert' (--continue | --skip | --abort | --quit)

DESCRIPTION
-----------

Egy vagy több meglévő commit alapján visszavonja a hozzájuk tartozó
patchek által bevezetett változtatásokat, és néhány új commitot rögzít,
amelyek ezt rögzítik.  Ehhez az kell, hogy a working tree tiszta legyen
(nincs módosítás a HEAD commithoz képest).

Megjegyzés: a 'git revert' arra szolgál, hogy néhány új commitot
rögzítsen néhány korábbi commit (gyakran csak egyetlen hibás)
hatásának visszafordítására.  Ha az összes nem commitolt változtatást
el akarod dobni a munkakönyvtáradban, nézd meg a linkgit:git-reset[1]-et,
különösen a `--hard` opciót.  Ha bizonyos fájlokat úgy akarsz kinyerni,
ahogy egy másik commitban voltak, nézd meg a linkgit:git-restore[1]-et,
konkrétan a `--source` opciót. Légy óvatos ezekkel az alternatívákkal,
mert mindkettő eldobja a nem commitolt változtatásokat a
munkakönyvtáradban.

A három parancs közötti különbségekért l. a "Reset, restore and revert"
szakaszt a linkgit:git[1]-ben.

OPTIONS
-------
<commit>...::
	A revertelendő commitok.
	A commitnevek megadási módjainak teljesebb listájáért l.
	linkgit:gitrevisions[7].
	Commitok halmazai is megadhatók, de alapból nem történik bejárás;
	l. linkgit:git-rev-list[1] és a `--no-walk` opcióját.

-e::
--edit::
	Ezzel az opcióval a 'git revert' hagyja, hogy szerkeszd a
	commit-üzenetet a revert commitolása előtt. Ez az alapértelmezett,
	ha a parancsot terminálból futtatod.

-m parent-number::
--mainline parent-number::
	Általában nem tudsz merge-et revertelni, mert nem tudod, hogy a
	merge melyik oldalát kell fővonalnak tekinteni.  Ez az opció megadja
	a fővonal szülőjének számát (1-től kezdve), és lehetővé teszi a
	revertnek, hogy a megadott szülőhöz képest fordítsa vissza a
	változtatást.
+
Egy merge-commit revertelése azt jelenti ki, hogy soha nem akarod majd a
merge által behozott tree-változtatásokat.  Ennek eredményeként a
későbbi merge-ek csak olyan commitok által bevezetett
tree-változtatásokat hoznak be, amelyek nem ősei a korábban revertelt
merge-nek.  Lehet, hogy ezt akarod, de lehet, hogy nem.
+
További részletekért l. a link:howto/revert-a-faulty-merge.html[revert-a-faulty-merge How-To]-t.

--no-edit::
	Ezzel az opcióval a 'git revert' nem indítja el a commit-üzenet
	szerkesztőjét.

--cleanup=<mode>::
	Ez az opció meghatározza, hogyan lesz megtisztítva a commit-üzenet,
	mielőtt továbbadódik a commit-gépezetnek. További részletekért l.
	linkgit:git-commit[1]. Konkrétan, ha a '<mode>' a `scissors` értéket
	kapja, konfliktus esetén egy ollóvonal fűződik a `MERGE_MSG`-hez,
	mielőtt továbbadódna.

-n::
--no-commit::
	A parancs általában automatikusan létrehoz néhány commitot olyan
	commit napló-üzenetekkel, amelyek megadják, mely commitok lettek
	revertelve.  Ez a flag a megnevezett commitok reverteléséhez
	szükséges változtatásokat alkalmazza a working tree-den és az
	indexen, de nem készíti el a commitokat.  Ezenkívül, amikor ezt az
	opciót használod, az indexednek nem kell egyeznie a HEAD committal.
	A revert az indexed kiinduló állapotához képest történik.
+
Ez akkor hasznos, amikor egymás után több commit hatását revertelsz az
indexedbe.

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	Commitok GPG-aláírása. A `keyid` argumentum opcionális, és alapból
	a commitoló identitása; ha meg van adva, szóköz nélkül kell az
	opcióhoz tapadnia. A `--no-gpg-sign` hasznos mind a `commit.gpgSign`
	konfigurációs változó, mind egy korábbi `--gpg-sign`
	hatálytalanítására.

-s::
--signoff::
	Egy `Signed-off-by` trailer hozzáadása a commit-üzenet végén.
	További információért l. a signoff opciót a linkgit:git-commit[1]-ben.

--strategy=<strategy>::
	A megadott merge-stratégia használata.  Csak egyszer szabad
	használni.  A részletekért l. a MERGE STRATEGIES szakaszt a
	linkgit:git-merge[1]-ben.

-X<option>::
--strategy-option=<option>::
	A merge-stratégia-specifikus opció továbbítása a merge-stratégiának.
	A részletekért l. linkgit:git-merge[1].

include::rerere-options.adoc[]

--reference::
	Ahelyett, hogy a napló-üzenet törzsét a "This reverts
	<full-object-name-of-the-commit-being-reverted>." kezdené, a
	commitra "--pretty=reference" formátumban hivatkozz
	(vö. linkgit:git-log[1]).  A `revert.reference` konfigurációs
	változóval ez az opció alapból bekapcsolható.


SEQUENCER SUBCOMMANDS
---------------------
include::sequencer.adoc[]

EXAMPLES
--------
`git revert HEAD~3`::

	A HEAD-ben a negyedik utolsó commit által megadott változtatások
	revertelése, és egy új commit létrehozása a revertelt
	változtatásokkal.

`git revert -n master~5..master~2`::

	A masterben az ötödik utolsó committól (beleértve) a harmadik
	utolsó commitig (beleértve) terjedő commitok által végzett
	változtatások revertelése, de bármilyen commit létrehozása nélkül a
	revertelt változtatásokkal. A revert csak a working tree-t és az
	indexet módosítja.

DISCUSSION
----------

Bár a git automatikusan létrehoz egy alap commit-üzenetet,
_nyomatékosan_ ajánlott elmagyarázni, miért lesz revertelve az eredeti
commit.
Ezenkívül a revertek ismételt revertelése egyre nehézkesebb
tárgysorokat eredményez, például 'Reapply "Reapply "<original-subject>""'.
Fontold meg ezek átfogalmazását rövidebbre és egyedibbre.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/revert.adoc[]

SEE ALSO
--------
linkgit:git-cherry-pick[1]

GIT
---
A linkgit:git[1] csomag része
