gitattributes(5)
================

NAME
----
gitattributes - Útvonalankénti attribútumok megadása

SYNOPSIS
--------
$GIT_DIR/info/attributes, .gitattributes


DESCRIPTION
-----------

A `gitattributes` fájl egy egyszerű szöveges fájl, amely
`attribútumokat` rendel útvonalnevekhez.

A `gitattributes` fájl minden sora a következő alakú:

	minta attr1 attr2 ...

Vagyis egy minta, amelyet whitespace-ekkel elválasztott
attribútumlista követ. A kezdő és záró whitespace-eket
figyelmen kívül hagyja a rendszer. A '#'-tal kezdődő sorokat
figyelmen kívül hagyja. A dupla idézőjellel kezdődő mintákat
C stílusban idézettnek tekinti.
Amikor a minta illeszkedik a szóban forgó útvonalra, a soron
felsorolt attribútumokat az útvonal megkapja.

Minden attribútum az alábbi állapotok egyikében lehet egy adott
útvonalra nézve:

Beállítva::

	Az útvonal rendelkezik az attribútummal, "true" speciális
	értékkel; ezt úgy adjuk meg, hogy csak az attribútum nevét
	soroljuk fel az attribútumlistában.

Törölve::

	Az útvonal rendelkezik az attribútummal, "false" speciális
	értékkel; ezt úgy adjuk meg, hogy az attribútum nevét egy
	kötőjellel `-` megelőzve soroljuk fel az attribútumlistában.

Értékre állítva::

	Az útvonal rendelkezik az attribútummal, a megadott string
	értékkel; ezt úgy adjuk meg, hogy az attribútum nevét egy
	egyenlőségjellel `=` és az értékkel követve soroljuk fel az
	attribútumlistában.

Meghatározatlan::

	Egyetlen minta sem illeszkedik az útvonalra, és semmi nem
	mondja meg, hogy az útvonalnak van-e vagy nincs az adott
	attribútuma; ilyenkor az útvonal attribútuma Meghatározatlannak
	számít.

Ha egynél több minta illeszkedik az útvonalra, egy későbbi sor
felülbírálja a korábbit. Ez a felülbírálás attribútumonként
történik.

A minták útvonalakra illesztésének szabályai ugyanazok, mint a
`.gitignore` fájloknál (lásd: linkgit:gitignore[5]), néhány kivétellel:

  - a negatív minták tiltottak

  - a könyvtárra illeszkedő minták nem illeszkednek rekurzívan az
    adott könyvtáron belüli útvonalakra (így a záró perjeles `path/`
    szintaxis használata értelmetlen egy attribútumfájlban; helyette
    a `path/**` alakot használjuk)

Amikor eldönti, hogy mely attribútumokat rendeli egy útvonalhoz, a Git
megvizsgálja a `$GIT_DIR/info/attributes` fájlt (ennek van a legmagasabb
precedenciája), a szóban forgó útvonallal azonos könyvtárban lévő
`.gitattributes` fájlt, és annak szülőkönyvtárait egészen a munkakönyvtár
legfelső szintjéig (minél távolabb van a `.gitattributes`-t tartalmazó
könyvtár a szóban forgó útvonaltól, annál alacsonyabb a precedenciája).
Végül a globális és a rendszerszintű fájlokat veszi figyelembe (ezeknek
van a legalacsonyabb precedenciájuk).

Ha a `.gitattributes` fájl hiányzik a munkakönyvtárból, az indexben
lévő útvonal szolgál tartalékként. A checkout folyamat során az
indexben lévő `.gitattributes` fájlt használja, majd a munkakönyvtárban
lévő fájl szolgál tartalékként.

Ha csak egyetlen repository-ra szeretnél hatni (vagyis olyan
attribútumokat rendelni fájlokhoz, amelyek az adott repository-nál
egy adott felhasználó munkafolyamatára jellemzőek), akkor az
attribútumokat a `$GIT_DIR/info/attributes` fájlba kell helyezni.
Azokat az attribútumokat, amelyeket verziókövetni és más
repository-knak is terjeszteni kell (vagyis amelyek minden
felhasználó számára érdekesek), a `.gitattributes` fájlokba kell
tenni. Azokat az attribútumokat, amelyeknek egyetlen felhasználó
összes repository-jára hatniuk kell, a `core.attributesFile`
konfigurációs opció (lásd: linkgit:git-config[1]) által megadott
fájlba kell helyezni. Ennek alapértelmezett értéke
$XDG_CONFIG_HOME/git/attributes. Ha az $XDG_CONFIG_HOME nincs
beállítva vagy üres, akkor helyette a $HOME/.config/git/attributes
fájlt használja. A rendszer összes felhasználójára vonatkozó
attribútumokat a `$(prefix)/etc/gitattributes` fájlba kell tenni.

Néha szükség lehet arra, hogy egy attribútum beállítását egy
útvonalon `Meghatározatlan` állapotra írjuk felül. Ez úgy tehető meg,
hogy az attribútum nevét egy felkiáltójellel `!` megelőzve soroljuk
fel.


RESERVED BUILTIN_* ATTRIBUTES
-----------------------------

A builtin_* egy fenntartott névtér a beépített attribútumértékek
számára. Az ebben a névtérben definiált, felhasználó által megadott
attribútumokat a rendszer figyelmen kívül hagyja, és figyelmeztetést ad.

`builtin_objectmode`
~~~~~~~~~~~~~~~~~~~~
Ez az attribútum a fájlok fájl bit módjaik szerinti szűrésére szolgál
(40000, 120000, 160000, 100755, 100644), pl.
':(attr:builtin_objectmode=160000)'.
Ezeket az értékeket a `git check-attr builtin_objectmode -- <file>`
paranccsal is ellenőrizheted.
Ha az objektum nincs az indexben, a `git check-attr --cached`
meghatározatlant fog visszaadni.


EFFECTS
-------

Bizonyos Git-műveleteket befolyásolni lehet azzal, hogy adott
attribútumokat rendelünk egy útvonalhoz. Jelenleg a következő
műveletek veszik figyelembe az attribútumokat.

[[_checking_out_and_checking_in]]
Checkout és checkin
~~~~~~~~~~~~~~~~~~~

Ezek az attribútumok befolyásolják, hogy a repository-ban tárolt
tartalom hogyan másolódik át a munkakönyvtár fájljaiba, amikor
olyan parancsok futnak, mint a 'git switch', a 'git checkout' és a
'git merge'. Azt is befolyásolják, hogy a Git hogyan tárolja a
munkakönyvtárban előkészített tartalmat a repository-ban a
'git add' és a 'git commit' futtatásakor.

`text`
^^^^^^

Ez az attribútum szövegfájlként jelöli meg az útvonalat, ami engedélyezi
a sorvég-konverziót: amikor egy illeszkedő fájlt hozzáadunk az indexhez,
a fájl sorvégei LF-re normalizálódnak az indexben. Ezzel szemben, amikor
a fájl az indexből a munkakönyvtárba másolódik, a sorvégei LF-ről
CRLF-re konvertálódhatnak, az `eol` attribútumtól, a Git konfigurációtól
és a platformtól függően (lásd az `eol` alábbi magyarázatát).

Beállítva::

	A `text` attribútum beállítása egy útvonalon engedélyezi a
	fent leírt sorvég-konverziót checkinkor és checkoutkor. A
	sorvégek minden alkalommal LF-re normalizálódnak az indexben,
	amikor a fájlt checkinolják, még akkor is, ha a fájlt korábban
	CRLF sorvégekkel adták a Githez.

Törölve::

	A `text` attribútum törlése egy útvonalon azt mondja a Gitnek,
	hogy ne kíséreljen meg semmilyen sorvég-konverziót checkinkor
	vagy checkoutkor.

„auto" string értékre állítva::

	Amikor a `text` "auto"-ra van állítva, a Git saját maga dönti
	el, hogy a fájl szöveges vagy bináris. Ha szöveges, és a fájl
	még nem volt a Gitben CRLF sorvégekkel, akkor a sorvégek a
	fent leírtak szerint konvertálódnak checkinkor és checkoutkor.
	Egyébként semmilyen konverzió nem történik checkinkor vagy
	checkoutkor.

Meghatározatlan::

	Ha a `text` attribútum meghatározatlan, a Git a
	`core.autocrlf` konfigurációs változó alapján dönti el, hogy a
	fájlt konvertálni kell-e.

Bármely más érték hatására a Git úgy viselkedik, mintha a `text`
meghatározatlanul lenne hagyva.

`eol`
^^^^^

Ez az attribútum azt jelöli meg egy útvonalon, hogy a munkakönyvtárban
egy adott sorvég-stílust kell használni a checkoutkor. Csak akkor van
hatása, ha a `text` vagy a `text=auto` be van állítva (lásd fent), de
az `eol` megadása automatikusan beállítja a `text`-et is, ha az
meghatározatlanul volt hagyva.

„crlf" string értékre állítva::

	Ez a beállítás CRLF-re konvertálja a fájl sorvégeit a
	munkakönyvtárban, amikor a fájlt checkoutolják.

„lf" string értékre állítva::

	Ez a beállítás ugyanazokat a sorvégeket használja a
	munkakönyvtárban, mint amilyenek az indexben vannak, amikor a
	fájlt checkoutolják.

Meghatározatlan::

	Ha az `eol` attribútum meghatározatlan egy fájlra, a
	munkakönyvtárban lévő sorvégeit a `core.autocrlf` vagy a
	`core.eol` konfigurációs változó határozza meg (lásd ezen
	opciók definícióit a linkgit:git-config[1] oldalon). Ha a
	`text` be van állítva, de e két változó egyike sincs, az
	alapértelmezés `eol=crlf` Windows alatt, és `eol=lf` minden
	más platformon.

[[_backwards_compatibility_with_crlf_attribute]]
A `crlf` attribútummal való visszafelé kompatibilitás
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A visszafelé kompatibilitás érdekében a `crlf` attribútumot a
rendszer a következőképpen értelmezi:

------------------------
crlf		text
-crlf		-text
crlf=input	eol=lf
------------------------

[[_end_of_line_conversion]]
Sorvég-konverzió
^^^^^^^^^^^^^^^^^^

Bár a Git normál esetben békén hagyja a fájlok tartalmát, beállítható
úgy, hogy a sorvégeket LF-re normalizálja a repository-ban, és
opcionálisan CRLF-re konvertálja azokat, amikor a fájlokat checkoutolják.

Ha egyszerűen azt szeretnéd, hogy a munkakönyvtáradban CRLF sorvégek
legyenek, függetlenül attól, hogy melyik repository-val dolgozol,
beállíthatod a "core.autocrlf" konfigurációs változót, attribútumok
használata nélkül.

------------------------
[core]
	autocrlf = true
------------------------

Ez nem kényszeríti ki a szövegfájlok normalizálását, de biztosítja,
hogy azoknak a szövegfájloknak, amelyeket a repository-ba bevezetsz,
LF-re normalizálódjanak a sorvégei, amikor hozzáadod őket, és hogy a
repository-ban már normalizált fájlok normalizáltak maradjanak.

Ha azt szeretnéd biztosítani, hogy bármely közreműködő által a
repository-ba bevezetett szövegfájlok sorvégei normalizálva legyenek,
beállíthatod a `text` attribútumot "auto"-ra _minden_ fájlra.

------------------------
*	text=auto
------------------------

Az attribútumok finomhangolt szabályozást tesznek lehetővé afelett,
hogy a sorvégek hogyan konvertálódnak.
Íme egy példa, amely arra készteti a Gitet, hogy normalizálja a .txt,
.vcproj és .sh fájlokat, biztosítsa, hogy a .vcproj fájloknak CRLF, a
.sh fájloknak pedig LF sorvégeik legyenek a munkakönyvtárban, és
megakadályozza, hogy a .jpg fájlok normalizálódjanak, a tartalmuktól
függetlenül.

------------------------
*               text=auto
*.txt		text
*.vcproj	text eol=crlf
*.sh		text eol=lf
*.jpg		-text
------------------------

NOTE: Amikor a `text=auto` konverzió engedélyezve van egy platformok
közötti projektben, amely push-t és pull-t használ egy központi
repository-hoz, a CRLF-eket tartalmazó szövegfájlokat normalizálni
kell.

Egy tiszta munkakönyvtárból kiindulva:

-------------------------------------------------
$ echo "* text=auto" >.gitattributes
$ git add --renormalize .
$ git status        # Mutatja a normalizálandó fájlokat
$ git commit -m "Introduce end-of-line normalization"
-------------------------------------------------

Ha olyan fájlok jelennek meg a 'git status' kimenetében, amelyeket
nem kellene normalizálni, töröld a `text` attribútumukat, mielőtt
futtatnád a 'git add -u' parancsot.

------------------------
manual.pdf	-text
------------------------

Fordítva, azokra a szövegfájlokra, amelyeket a Git nem ismer fel,
a normalizálás manuálisan is engedélyezhető.

------------------------
weirdchars.txt	text
------------------------

Ha a `core.safecrlf` "true"-ra vagy "warn"-ra van állítva, a Git
ellenőrzi, hogy a konverzió visszafordítható-e a `core.autocrlf`
aktuális beállítására nézve. "true" esetén a Git elutasítja a nem
visszafordítható konverziókat; "warn" esetén a Git csak figyelmeztetést
ír ki, de elfogadja a nem visszafordítható konverziót. A biztonsági
mechanizmus azért lép működésbe, hogy megakadályozza az ilyen
konverziót a munkakönyvtár fájljain, de van néhány kivétel. Bár...

- a 'git add' önmagában nem nyúl a munkakönyvtár fájljaihoz, de a
  következő checkout hozzányúlna, ezért a biztonsági mechanizmus
  működésbe lép;

- a 'git apply', amikor egy szövegfájlt egy patch-csel frissít,
  hozzányúl a munkakönyvtár fájljaihoz, de a művelet szövegfájlokról
  szól, és a CRLF-konverzió a sorvég-inkonzisztenciák javításáról,
  ezért a biztonsági mechanizmus nem lép működésbe;

- a 'git diff' önmagában nem nyúl a munkakönyvtár fájljaihoz, gyakran
  azért futtatják, hogy megvizsgálják azokat a változtatásokat, amelyeket
  a felhasználó a következő 'git add'-del szándékozik hozzáadni. A
  lehetséges problémák korai felismerése érdekében a biztonsági
  mechanizmus működésbe lép.


`working-tree-encoding`
^^^^^^^^^^^^^^^^^^^^^^^

A Git az ASCII-ban vagy annak valamelyik szupersetjében (pl. UTF-8,
ISO-8859-1, ...) kódolt fájlokat szövegfájlként ismeri fel. Bizonyos
más kódolásban (pl. UTF-16) kódolt fájlokat binárisként értelmezi, és
ennek következtében a beépített Git szövegfeldolgozó eszközök (pl. a
'git diff'), valamint a legtöbb Git webes felület alapértelmezetten
nem jeleníti meg ezen fájlok tartalmát.

Ilyen esetekben a `working-tree-encoding` attribútummal közölheted a
Gittel egy fájl kódolását a munkakönyvtárban. Ha egy ezzel az
attribútummal rendelkező fájlt adsz a Githez, a Git a tartalmat a
megadott kódolásból UTF-8-ra kódolja át. Végül a Git az UTF-8
kódolású tartalmat tárolja a belső adatszerkezetében (amit "az
index"-nek hívnak). Checkoutkor a tartalom visszakódolódik a megadott
kódolásra.

Ne feledd, hogy a `working-tree-encoding` attribútum használatának
számos buktatója lehet:

- Az alternatív Git implementációk (pl. a JGit vagy a libgit2) és a
  régebbi Git verziók (2018 márciusáig bezárólag) nem támogatják a
  `working-tree-encoding` attribútumot. Ha úgy döntesz, hogy a
  repository-dban a `working-tree-encoding` attribútumot használod,
  akkor erősen ajánlott meggyőződni arról, hogy a repository-val
  dolgozó összes kliens támogatja azt.
+
Például a Microsoft Visual Studio erőforrásfájljai (`*.rc`) vagy a
PowerShell szkriptfájlok (`*.ps1`) néha UTF-16 kódolásúak. Ha a
`*.ps1` fájlokat UTF-16-osként deklarálod, és a `foo.ps1` fájlt egy
`working-tree-encoding`-ot támogató Git klienssel adod hozzá, akkor a
`foo.ps1` belsőleg UTF-8-ként lesz tárolva. Egy `working-tree-encoding`
támogatás nélküli kliens UTF-8 kódolású fájlként fogja checkoutolni
a `foo.ps1` fájlt. Ez jellemzően problémát okoz a fájl felhasználóinak.
+
Ha egy `working-tree-encoding` attribútumot nem támogató Git kliens
ad hozzá egy új `bar.ps1` fájlt, akkor a `bar.ps1` "változtatás
nélkül" lesz tárolva belsőleg (ebben a példában valószínűleg
UTF-16-ként). Egy `working-tree-encoding` támogatással rendelkező
kliens a belső tartalmat UTF-8-ként fogja értelmezni, és megpróbálja
azt UTF-16-ra konvertálni checkoutkor. Ez a művelet meg fog hiúsulni,
és hibát fog okozni.

- A tartalom nem UTF kódolásokra való átkódolása hibákat okozhat,
  mivel előfordulhat, hogy a konverzió nem UTF-8 körbeutazás-biztos
  (round trip safe). Ha gyanítod, hogy a kódolásod nem
  körbeutazás-biztos, akkor add hozzá a
  `core.checkRoundtripEncoding` változóhoz, hogy a Git ellenőrizze a
  körbeutazásos kódolást (lásd: linkgit:git-config[1]). A SHIFT-JIS
  (japán karakterkészlet) ismerten körbeutazási problémákkal
  rendelkezik az UTF-8-cal, és alapértelmezetten ellenőrzésre kerül.

- A tartalom átkódolása erőforrásokat igényel, ami lelassíthat
  bizonyos Git-műveleteket (pl. a 'git checkout'-ot vagy a 'git
  add'-et).

A `working-tree-encoding` attribútumot csak akkor használd, ha nem
tudod egy fájlt UTF-8 kódolásban tárolni, és azt szeretnéd, hogy a Git
szövegként tudja feldolgozni a tartalmát.

Példaként a következő attribútumokat használd, ha a '*.ps1' fájljaid
bájtsorrend-jellel (BOM) ellátott UTF-16 kódolásúak, és azt szeretnéd,
hogy a Git a platformod alapján automatikus sorvég-konverziót végezzen.

------------------------
*.ps1		text working-tree-encoding=UTF-16
------------------------

A következő attribútumokat használd, ha a '*.ps1' fájljaid BOM nélküli
UTF-16 little endian kódolásúak, és azt szeretnéd, hogy a Git Windows
sorvégeket használjon a munkakönyvtárban (használd a `UTF-16LE-BOM`
értéket a `UTF-16LE` helyett, ha BOM-mal ellátott UTF-16 little
endian kódolást szeretnél).
Ne feledd, erősen ajánlott a sorvégeket explicit módon megadni az
`eol` attribútummal, ha a `working-tree-encoding` attribútumot
használod, a kétértelműség elkerülése végett.

------------------------
*.ps1		text working-tree-encoding=UTF-16LE eol=crlf
------------------------

A platformodon elérhető összes kódolás listáját a következő
paranccsal kaphatod meg:

------------------------
iconv --list
------------------------

Ha nem ismered egy fájl kódolását, akkor a `file` paranccsal
megbecsülheted azt:

------------------------
file foo.ps1
------------------------


`ident`
^^^^^^^

Ha az `ident` attribútum be van állítva egy útvonalra, a Git a blob
objektumban lévő `$Id$`-t `$Id:`-re cseréli, amelyet a 40 karakteres
hexadecimális blob objektumnév követ, amelyet pedig egy dollárjel `$`
követ, checkoutkor. Bármely, a munkafa fájljában `$Id:`-vel kezdődő és
`$`-lal végződő bájtsorozatot a rendszer `$Id$`-re cserél checkinkor.


`filter`
^^^^^^^^

A `filter` attribútum egy olyan string értékre állítható, amely a
konfigurációban megadott filter drivert nevezi meg.

Egy filter driver egy `clean` parancsból és egy `smudge` parancsból
áll, amelyek közül bármelyik megadatlanul hagyható. Checkoutkor,
amikor a `smudge` parancs meg van adva, a parancs a blob objektumot
kapja meg a standard bemenetén, és a standard kimenete frissíti a
munkafa fájlját. Hasonlóképp, a `clean` parancs a munkafa fájljának
tartalmát alakítja át checkinkor. Alapértelmezetten ezek a parancsok
csak egyetlen blobot dolgoznak fel, majd befejeződnek. Ha a `clean`
és/vagy a `smudge` filterek helyett egy hosszan futó `process` filter
van használva, akkor a Git egyetlen filter-parancs meghívásával
tud feldolgozni minden blobot egy adott Git-parancs teljes
életciklusa alatt, például a `git add --all` esetén. Ha egy hosszan
futó `process` filter van konfigurálva, az mindig elsőbbséget élvez
egy konfigurált, egyetlen blobbal dolgozó filterrel szemben. A
`process` filterrel való kommunikációhoz használt protokoll leírását
lásd az alábbi szakaszban.

A tartalomszűrés egyik felhasználási módja az, hogy a tartalmat olyan
alakra hozza, amely kényelmesebb a platform, a fájlrendszer és a
felhasználó számára. Ennél a működési módnál a kulcskifejezés a
"kényelmesebb", nem pedig az, hogy "valami használhatatlant
használhatóvá alakít". Más szóval, a szándék az, hogy ha valaki
törli a filter driver definícióját, vagy nem rendelkezik a megfelelő
filter programmal, a projektnek akkor is használhatónak kell maradnia.

A tartalomszűrés egy másik felhasználási módja az, hogy olyan
tartalmat tárol, amely közvetlenül nem használható a repository-ban
(pl. egy UUID, amely a Giten kívül tárolt valódi tartalomra utal,
vagy titkosított tartalom), és checkoutkor használható formára
alakítja azt (pl. letölti a külső tartalmat, vagy visszafejti a
titkosított tartalmat).

Ez a két filter eltérően viselkedik, és alapértelmezetten egy filtert
az előbbiként kezel a rendszer, amely a tartalmat kényelmesebb
alakra hozza. A konfigurációban hiányzó filter driver definíció,
vagy egy nem nulla állapottal kilépő filter driver nem hiba, hanem
no-op passthru-vá teszi a filtert.

Kijelentheted, hogy egy filter egy önmagában használhatatlan
tartalmat használható tartalommá alakít, ha a
filter.<driver>.required konfigurációs változót `true`-ra állítod.

Megjegyzés: valahányszor a clean filter megváltozik, a repót
renormalizálni kell:
$ git add --renormalize .

Például a .gitattributes fájlban a `filter` attribútumot rendelnéd
hozzá útvonalakhoz.

------------------------
*.c	filter=indent
------------------------

Ezután a .git/config fájlban definiálnál egy "filter.indent.clean" és
egy "filter.indent.smudge" konfigurációt, hogy megadj egy pár parancsot
a C programok tartalmának módosítására, amikor a forrásfájlokat
checkinolják ("clean" fut) és checkoutolják (nem történik változás,
mert a parancs "cat").

------------------------
[filter "indent"]
	clean = indent
	smudge = cat
------------------------

A legjobb eredmény érdekében a `clean`-nek nem szabadna tovább
módosítania a kimenetét, ha kétszer futtatják ("clean->clean"-nek
egyenértékűnek kell lennie a "clean"-nel), és több `smudge`
parancsnak sem szabadna módosítania a `clean` kimenetét
("smudge->smudge->clean"-nek egyenértékűnek kell lennie a
"clean"-nel). Lásd a lentebbi, merge-elésről szóló szakaszt.

Az "indent" filter ebből a szempontból jól viselkedik: nem fogja
módosítani azt a bemenetet, amely már helyesen van behúzva. Ebben az
esetben a smudge filter hiánya azt jelenti, hogy a clean filternek
_muszáj_ elfogadnia a saját kimenetét, anélkül, hogy módosítaná azt.

Ha egy filternek _muszáj_ sikeresnek lennie ahhoz, hogy a tárolt
tartalom használható legyen, kijelentheted, hogy a filter `required`,
a konfigurációban:

------------------------
[filter "crypt"]
	clean = openssl enc ...
	smudge = openssl enc -d ...
	required
------------------------

A "%f" sorozatot a filter parancssorában annak a fájlnak a neve
váltja fel, amelyen a filter éppen dolgozik. Egy filter ezt
kulcsszó-behelyettesítésre használhatja. Például:

------------------------
[filter "p4"]
	clean = git-p4-filter --clean %f
	smudge = git-p4-filter --smudge %f
------------------------

Vedd figyelembe, hogy a "%f" annak az útvonalnak a neve, amelyen éppen
dolgoznak. A szűrt verziótól függően lehet, hogy a lemezen lévő
megfelelő fájl nem létezik, vagy más tartalma van. Ezért a smudge és a
clean parancsok ne próbáljanak hozzáférni a lemezen lévő fájlhoz,
hanem csak a standard bemeneten nekik átadott tartalmon
szűrőként működjenek.

[[_long_running_filter_process]]
Hosszan futó filterfolyamat
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Ha a filterparancs (egy string érték) a `filter.<driver>.process`
révén van megadva, akkor a Git egyetlen filter-meghívással tud
feldolgozni minden blobot egy adott Git-parancs teljes életciklusa
alatt. Ezt a hosszan futó folyamat protokoll (long-running process
protocol) használatával éri el (a
Documentation/technical/long-running-process-protocol.adoc fájlban
leírtak szerint).

Amikor a Git az első olyan fájlba ütközik, amelyet clean-elni vagy
smudge-olni kell, elindítja a filtert, és elvégzi a kézfogást
(handshake). A kézfogás során a Git által küldött üdvözlő üzenet a
"git-filter-client", csak a 2-es verzió támogatott, és a támogatott
képességek a "clean", a "smudge" és a "delay".

Ezután a Git elküld egy "kulcs=érték" párokból álló listát, amelyet
egy flush csomag zár le. A lista legalább a filterparancsot (a
támogatott képességek alapján) és a szűrendő fájl repository
gyökeréhez viszonyított útvonalnevét fogja tartalmazni. Közvetlenül a
flush csomag után a Git elküldi a tartalmat, nulla vagy több
pkt-line csomagra bontva, majd egy flush csomagot a tartalom
lezárásához. Ne feledd, hogy a filter nem küldhet semmilyen választ,
mielőtt megkapta a tartalmat és a záró flush csomagot. Azt is vedd
figyelembe, hogy egy "kulcs=érték" pár "értéke" tartalmazhatja a "="
karaktert, míg a kulcs soha nem tartalmazhatja azt a karaktert.

-----------------------
packet:          git> command=smudge
packet:          git> pathname=path/testfile.dat
packet:          git> 0000
packet:          git> CONTENT
packet:          git> 0000
-----------------------

A filternek egy "kulcs=érték" párokból álló, flush csomaggal lezárt
listával kell válaszolnia. Ha a filter nem ütközik problémákba,
akkor a listának tartalmaznia kell egy "success" állapotot.
Közvetlenül ezek után a csomagok után a filternek el kell küldenie a
tartalmat nulla vagy több pkt-line csomagban, majd a végén egy flush
csomagot. Végül egy második, flush csomaggal lezárt "kulcs=érték"
listát vár a rendszer. A filter megváltoztathatja az állapotot a
második listában, vagy megtarthatja azt egy üres listával. Ne
feledd, hogy az üres listát mindenképp flush csomaggal kell lezárni.

------------------------
packet:          git< status=success
packet:          git< 0000
packet:          git< SMUDGED_CONTENT
packet:          git< 0000
packet:          git< 0000  # empty list, keep "status=success" unchanged!
------------------------

Ha az eredménytartalom üres, akkor a filternek egy "success"
állapottal és egy flush csomaggal kell jeleznie az üres tartalmat.

------------------------
packet:          git< status=success
packet:          git< 0000
packet:          git< 0000  # empty content!
packet:          git< 0000  # empty list, keep "status=success" unchanged!
------------------------

Abban az esetben, ha a filter nem tudja vagy nem akarja feldolgozni a
tartalmat, egy "error" állapottal kell válaszolnia.

-----------------------
packet:          git< status=error
packet:          git< 0000
-----------------------

Ha a filter hibát tapasztal a feldolgozás során, akkor küldheti az
"error" állapotot azután, hogy a tartalmat (részben vagy teljesen)
elküldte.

------------------------
packet:          git< status=success
packet:          git< 0000
packet:          git< HALF_WRITTEN_ERRONEOUS_CONTENT
packet:          git< 0000
packet:          git< status=error
packet:          git< 0000
------------------------

Abban az esetben, ha a filter nem tudja vagy nem akarja feldolgozni a
tartalmat, sem semmilyen jövőbeli tartalmat a Git-folyamat teljes
élettartama alatt, akkor a protokoll bármely pontján egy "abort"
állapottal kell válaszolnia.

-----------------------
packet:          git< status=abort
packet:          git< 0000
-----------------------

A Git az "error"/"abort" állapot beállítása esetén sem nem állítja
le, sem nem indítja újra a filterfolyamatot. Azonban a Git a
`filter.<driver>.required` jelző alapján állítja be a kilépési
kódját, utánozva a `filter.<driver>.clean` / `filter.<driver>.smudge`
mechanizmus viselkedését.

Ha a filter meghal a kommunikáció során, vagy nem tartja be a
protokollt, akkor a Git leállítja a filterfolyamatot, és újraindítja
azt a következő feldolgozandó fájllal. A `filter.<driver>.required`
jelzőtől függően a Git ezt hibaként fogja értelmezni.

[[_delay]]
Késleltetés
^^^^^^^^^^^^^

Ha a filter támogatja a "delay" képességet, akkor a Git elküldheti a
"can-delay" jelzőt a filterparancs és az útvonalnév után. Ez a jelző
azt jelöli, hogy a filter késleltetheti az aktuális blob szűrését
(pl. a hálózati késleltetés kompenzálására), azzal, hogy tartalom
nélkül válaszol, de a "delayed" állapottal és egy flush csomaggal.

-----------------------
packet:          git> command=smudge
packet:          git> pathname=path/testfile.dat
packet:          git> can-delay=1
packet:          git> 0000
packet:          git> CONTENT
packet:          git> 0000
packet:          git< status=delayed
packet:          git< 0000
-----------------------

Ha a filter támogatja a "delay" képességet, akkor a
"list_available_blobs" parancsot is támogatnia kell. Ha a Git elküldi
ezt a parancsot, a filternek egy útvonalnevekből álló listát kell
visszaadnia, amelyek a korábban késleltetett, most már elérhető
blobokat jelölik.
A listát flush csomaggal kell lezárni, amelyet egy "success" állapot
követ, azt is flush csomaggal lezárva. Ha a késleltetett útvonalakhoz
tartozó blobok még nem elérhetők, akkor a filternek blokkolnia kell a
választ, amíg legalább egy blob elérhetővé nem válik. A filter egy
üres lista küldésével jelezheti a Gitnek, hogy nincs több
késleltetett blobja. Amint a filter üres listával válaszol, a Git
abbahagyja a kérdezést. Minden olyan blobot, amelyet a Git eddig a
pontig nem kapott meg, hiányzónak tekint, és ez hibát fog eredményezni.

------------------------
packet:          git> command=list_available_blobs
packet:          git> 0000
packet:          git< pathname=path/testfile.dat
packet:          git< pathname=path/otherfile.dat
packet:          git< 0000
packet:          git< status=success
packet:          git< 0000
------------------------


Miután a Git megkapta az útvonalneveket, ismét lekéri a megfelelő
blobokat. Ezek a kérések egy útvonalnevet és egy üres tartalomszakaszt
tartalmaznak. A filternek a fent leírt szokásos módon kell
válaszolnia a smudge-olt tartalommal.

------------------------
packet:          git> command=smudge
packet:          git> pathname=path/testfile.dat
packet:          git> 0000
packet:          git> 0000  # empty content!
packet:          git< status=success
packet:          git< 0000
packet:          git< SMUDGED_CONTENT
packet:          git< 0000
packet:          git< 0000  # empty list, keep "status=success" unchanged!
------------------------

[[_example]]
Példa
^^^^^^

Egy hosszan futó filter demó-implementációja megtalálható a Git
core repository-jában található
`contrib/long-running-filter/example.pl` fájlban. Ha saját hosszan
futó filterfolyamatot fejlesztesz, akkor a `GIT_TRACE_PACKET`
környezeti változó nagyon hasznos lehet a hibakereséshez (lásd:
linkgit:git[1]).

Ne feledd, hogy nem használhatsz egy meglévő `filter.<driver>.clean`
vagy `filter.<driver>.smudge` parancsot a `filter.<driver>.process`
mellett, mert az előbbi kettő más folyamatközi kommunikációs
protokollt használ, mint az utóbbi.


[[_interaction_between_checkin_checkout_attributes]]
A checkin/checkout attribútumok kölcsönhatása
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A checkin kódútban a munkafa fájlja először a `filter` driverrel
konvertálódik (ha meg van adva, és a megfelelő driver definiálva
van), majd az eredmény az `ident`-tel kerül feldolgozásra (ha meg
van adva), végül pedig a `text`-tel (megint csak, ha meg van adva és
alkalmazható).

A checkout kódútban a blob tartalma először a `text`-tel
konvertálódik, majd az `ident`-tel, és a `filter`-nek van átadva.


[[_merging_branches_with_differing_checkin_checkout_attributes]]
Eltérő checkin/checkout attribútumú branchek merge-elése
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Ha olyan attribútumokat adtál hozzá egy fájlhoz, amelyek
megváltoztatják az adott fájl kanonikus repository-formátumát, mint
például egy clean/smudge filter vagy text/eol/ident attribútumok
hozzáadása, akkor bármi merge-elése, ahol az attribútum nincs
alkalmazva, normál esetben merge-konfliktusokat okozna.

E felesleges merge-konfliktusok megelőzésére a Gitnek megmondható,
hogy futtasson egy virtuális checkoutot és checkint minden olyan fájl
mindhárom stage-jén, amelyhez háromutas tartalom-merge szükséges, a
`merge.renormalize` konfigurációs változó beállításával. Ez
megakadályozza, hogy a checkin-konverzió által okozott változtatások
hamis merge-konfliktusokat okozzanak, amikor egy konvertált fájlt egy
nem konvertált fájllal merge-elnek.

Amíg egy "smudge->clean" ugyanazt az eredményt adja, mint egy
"clean", még olyan fájlokon is, amelyek már smudge-olva vannak, ez a
stratégia automatikusan feloldja az összes filterrel kapcsolatos
konfliktust. Azok a filterek, amelyek nem így viselkednek, további
merge-konfliktusokat okozhatnak, amelyeket manuálisan kell feloldani.


[[_generating_diff_text]]
A diffszöveg előállítása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`diff`
^^^^^^

A `diff` attribútum befolyásolja, hogy a Git hogyan állítja elő az
egyes fájlok diffjeit. Megmondhatja a Gitnek, hogy szöveges patch-et
állítson-e elő az útvonalhoz, vagy bináris fájlként kezelje azt. Azt
is befolyásolhatja, hogy milyen sor jelenjen meg a hunk-fejlécen (a
`@@ -k,l +n,m @@` soron), megmondhatja a Gitnek, hogy egy külső
parancsot használjon a diff előállítására, vagy megkérheti a Gitet,
hogy szöveges formátumra konvertálja a bináris fájlokat a diff
előállítása előtt.

Beállítva::

	Az az útvonal, amelyre a `diff` attribútum be van állítva,
	szövegként van kezelve, még akkor is, ha olyan bájtértékeket
	tartalmaz, amelyek normál esetben soha nem jelennek meg
	szövegfájlokban, mint például a NUL.

Törölve::

	Az az útvonal, amelyre a `diff` attribútum törölve van,
	`Binary files differ` üzenetet fog generálni (vagy egy
	bináris patch-et, ha a bináris patch-ek engedélyezve vannak).

Meghatározatlan::

	Annak az útvonalnak, amelyre a `diff` attribútum
	meghatározatlan, először megvizsgálja a tartalmát, és ha az
	szövegnek tűnik, és kisebb, mint a core.bigFileThreshold,
	akkor szövegként kezeli. Egyébként `Binary files differ`
	üzenetet generálna.

String::

	A diff a megadott diff driverrel jelenik meg. Minden driver
	megadhat egy vagy több opciót, ahogy azt a következő szakasz
	leírja. A "foo" diff driver opcióit a Git konfigurációs
	fájl "diff.foo" szakaszában lévő konfigurációs változók
	definiálják.


[[_defining_an_external_diff_driver]]
Egy külső diff driver definiálása
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Egy diff driver definiálása a `gitconfig`-ban történik, nem a
`gitattributes` fájlban, tehát szigorúan véve ez a kézikönyvoldal
rossz hely erről beszélni. Azonban...

Egy `jcdiff` külső diff driver definiálásához adj egy szakaszt a
`$GIT_DIR/config` fájlodhoz (vagy a `$HOME/.gitconfig` fájlodhoz),
így:

----------------------------------------------------------------
[diff "jcdiff"]
	command = j-c-diff
----------------------------------------------------------------

Amikor a Gitnek meg kell mutatnia neked egy diffet egy olyan
útvonalhoz, amelynek `diff` attribútuma `jcdiff`-re van állítva, a
fenti konfigurációban megadott parancsot hívja meg, azaz a
`j-c-diff`-et, 7 paraméterrel, ugyanúgy, ahogy a `GIT_EXTERNAL_DIFF`
programot hívja. A részletekért lásd: linkgit:git[1].

Ha a program képes figyelmen kívül hagyni bizonyos változtatásokat
(hasonlóan a `git diff --ignore-space-change`-hez), akkor állítsd be
a `trustExitCode` opciót is true-ra. Ekkor azt várja el a rendszer,
hogy 1-es kilépési kóddal térjen vissza, ha jelentős változtatásokat
talál, és 0-val, ha nem.

[[_setting_the_internal_diff_algorithm]]
A belső diff algoritmus beállítása
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A diff algoritmus a `diff.algorithm` konfigurációs kulcson keresztül
állítható be, de néha hasznos lehet a diff algoritmust
útvonalanként beállítani. Például valaki szeretné a `minimal` diff
algoritmust használni a .json fájlokhoz, a `histogram`-ot pedig a .c
fájlokhoz, és így tovább, anélkül, hogy minden alkalommal a
parancssoron keresztül kellene átadnia az algoritmust.

Először a `.gitattributes` fájlban rendeld hozzá a `diff` attribútumot
útvonalakhoz.

------------------------
*.json diff=<name>
------------------------

Ezután definiálj egy "diff.<name>.algorithm" konfigurációt a diff
algoritmus megadásához, a `myers`, a `patience`, a `minimal` vagy a
`histogram` közül választva.

----------------------------------------------------------------
[diff "<name>"]
  algorithm = histogram
----------------------------------------------------------------

Ez a diff algoritmus a felhasználó felé megjelenő diff kimenetre
vonatkozik, mint a git-diff(1), a git-show(1), és a `--stat` kimenetre
is használatos. A merge-gépezet nem fogja használni az ezen a módon
beállított diff algoritmust.

NOTE: Ha a `diff.<name>.command` definiálva van a `diff=<name>`
attribútummal rendelkező útvonalhoz, akkor az külső diff driverként
kerül végrehajtásra (lásd fent), és a `diff.<name>.algorithm`
hozzáadásának nincs hatása, mivel az algoritmus nincs átadva a külső
diff drivernek.

[[_defining_a_custom_hunk_header]]
Egyéni hunk-fejléc definiálása
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A szöveges diff kimenetben minden változtatáscsoportot (amit
"hunk"-nak neveznek) egy ilyen alakú sor előz meg:

	@@ -k,l +n,m @@ TEXT

Ezt 'hunk header'-nek (hunk-fejlécnek) nevezik. A "TEXT" rész
alapértelmezetten egy olyan sor, amely betűvel, aláhúzásjellel vagy
dollárjellel kezdődik; ez megfelel annak, amit a GNU 'diff -p'
kimenete használ. Ez az alapértelmezett kiválasztás azonban nem
alkalmas bizonyos tartalmakra, és egyéni mintát is használhatsz a
kiválasztáshoz.

Először a .gitattributes fájlban rendelnéd hozzá a `diff`
attribútumot útvonalakhoz.

------------------------
*.tex	diff=tex
------------------------

Ezután definiálnál egy "diff.tex.xfuncname" konfigurációt, hogy
megadj egy reguláris kifejezést, amely illeszkedik arra a sorra,
amelyet a hunk-fejléc "TEXT" részeként szeretnél megjeleníteni. Adj
egy szakaszt a `$GIT_DIR/config` fájlodhoz (vagy a
`$HOME/.gitconfig` fájlodhoz), így:

------------------------
[diff "tex"]
	xfuncname = "^(\\\\(sub)*section\\{.*)$"
------------------------

Megjegyzés. A konfigurációs fájl feldolgozója felfal egy szint
visszaperjelet, ezért meg kell duplázni a visszaperjeleket; a fenti
minta egy olyan sort választ ki, amely visszaperjellel kezdődik,
majd nulla vagy több `sub` előfordulást tartalmaz, amelyet `section`
követ, amelyet nyitó kapcsos zárójel követ, a sor végéig.

Van néhány beépített minta, amely megkönnyíti ezt, és a `tex` az
egyik közülük, így nem kell megírnod a fentieket a konfigurációs
fájlodban (ezt még mindig engedélyezned kell az attribútum-
mechanizmussal, a `.gitattributes` fájlon keresztül). A következő
beépített minták érhetők el:

- `ada` az Ada nyelvű forráskódhoz alkalmas.

- `bash` a Bourne-Again SHell nyelvű forráskódhoz alkalmas. Lefedi a
  POSIX shell függvénydefiníciók egy szupersetjét.

- `bibtex` a BibTeX kódolású hivatkozásokat tartalmazó fájlokhoz
  alkalmas.

- `cpp` a C és C++ nyelvű forráskódhoz alkalmas.

- `csharp` a C# nyelvű forráskódhoz alkalmas.

- `css` a Cascading Style Sheets fájlokhoz alkalmas.

- `dts` a devicetree (DTS) fájlokhoz alkalmas.

- `elixir` az Elixir nyelvű forráskódhoz alkalmas.

- `fortran` a Fortran nyelvű forráskódhoz alkalmas.

- `fountain` a Fountain dokumentumokhoz alkalmas.

- `golang` a Go nyelvű forráskódhoz alkalmas.

- `html` a HTML/XHTML dokumentumokhoz alkalmas.

- `java` a Java nyelvű forráskódhoz alkalmas.

- `kotlin` a Kotlin nyelvű forráskódhoz alkalmas.

- `markdown` a Markdown dokumentumokhoz alkalmas.

- `matlab` a MATLAB és az Octave nyelvű forráskódhoz alkalmas.

- `objc` az Objective-C nyelvű forráskódhoz alkalmas.

- `pascal` a Pascal/Delphi nyelvű forráskódhoz alkalmas.

- `perl` a Perl nyelvű forráskódhoz alkalmas.

- `php` a PHP nyelvű forráskódhoz alkalmas.

- `python` a Python nyelvű forráskódhoz alkalmas.

- `ruby` a Ruby nyelvű forráskódhoz alkalmas.

- `rust` a Rust nyelvű forráskódhoz alkalmas.

- `scheme` a legtöbb Lisp dialektushoz alkalmas, beleértve a
  Scheme-et, az Emacs Lispet, a Common Lispet és a Clojure-t.

- `swift` a Swift nyelvű forráskódhoz alkalmas.

- `tex` a LaTeX dokumentumok forráskódjához alkalmas.


[[_customizing_word_diff]]
A szódiff testreszabása
^^^^^^^^^^^^^^^^^^^^^^^^^

Testreszabhatod azokat a szabályokat, amelyeket a
`git diff --word-diff` a sorban lévő szavak felosztásához használ,
egy megfelelő reguláris kifejezés megadásával a "diff.*.wordRegex"
konfigurációs változóban. Például TeX-ben egy visszaperjel, amelyet
betűk sorozata követ, egy parancsot alkot, de több ilyen parancs
futtatható együtt, közbeeső whitespace nélkül. Ezek elválasztásához
használj egy reguláris kifejezést a `$GIT_DIR/config` fájlodban
(vagy a `$HOME/.gitconfig` fájlodban), így:

------------------------
[diff "tex"]
	wordRegex = "\\\\[a-zA-Z]+|[{}]|\\\\.|[^\\{}[:space:]]+"
------------------------

Egy beépített minta van megadva az előző szakaszban felsorolt összes
nyelvhez.


[[_performing_text_diffs_of_binary_files]]
Bináris fájlok szöveges diffjeinek elkészítése
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Néha kívánatos látni néhány bináris fájl szövegre konvertált
verziójának diffjét. Például egy szövegszerkesztő dokumentum
átalakítható ASCII szöveges reprezentációvá, és a szöveg diffje
megjeleníthető. Bár ez a konverzió némi információt elveszít, a
kapott diff hasznos az emberi megtekintéshez (de közvetlenül nem
alkalmazható).

A `textconv` konfigurációs opció egy ilyen konverziót végző program
megadására szolgál. A programnak egyetlen argumentumot kell fogadnia,
a konvertálandó fájl nevét, és a kapott szöveget a stdoutra kell
kiadnia.

Például, hogy egy fájl exif-információjának diffjét mutasd a bináris
információ helyett (feltéve, hogy telepítve van az exif eszköz), add
a következő szakaszt a `$GIT_DIR/config` fájlodhoz (vagy a
`$HOME/.gitconfig` fájlodhoz):

------------------------
[diff "jpg"]
	textconv = exif
------------------------

NOTE: A szöveges konverzió általában egyirányú konverzió; ebben a
példában elveszítjük a tényleges képtartalmat, és csak a szöveges
adatra koncentrálunk. Ez azt jelenti, hogy a textconv által
generált diffek _nem_ alkalmasak alkalmazásra. Emiatt csak a
`git diff` és a `git log` parancscsalád (azaz a log, a whatchanged,
a show) fog szöveges konverziót végezni. A `git format-patch`
soha nem fogja generálni ezt a kimenetet. Ha valakinek egy bináris
fájl szövegre konvertált diffjét szeretnéd elküldeni (pl. mert az
gyorsan közvetíti az elvégzett változtatásokat), akkor azt külön kell
előállítanod, és megjegyzésként kell elküldened a szokásos bináris
diff _mellett_, amit esetleg küldenél.

Mivel a szöveges konverzió lassú lehet, különösen, ha nagy számban
végzik el őket a `git log -p` futtatásával, a Git egy mechanizmust
biztosít a kimenet gyorsítótárazására és a jövőbeli diffekben való
felhasználására. A gyorsítótárazás engedélyezéséhez állítsd be a
"cachetextconv" változót a diff driver konfigurációjában. Például:

------------------------
[diff "jpg"]
	textconv = exif
	cachetextconv = true
------------------------

Ez korlátlan ideig gyorsítótárazza az "exif" minden egyes blobon
való futtatásának eredményét. Ha megváltoztatod egy diff driver
textconv konfigurációs változóját, a Git automatikusan érvényteleníti
a gyorsítótár-bejegyzéseket, és újra lefuttatja a textconv filtert.
Ha manuálisan szeretnéd érvényteleníteni a gyorsítótárat (pl. mert
frissült az "exif" verziód, és most jobb kimenetet ad), akkor a
gyorsítótárat manuálisan is eltávolíthatod a
`git update-ref -d refs/notes/textconv/jpg` paranccsal (ahol a "jpg"
a diff driver neve, mint a fenti példában).

[[_choosing_textconv_versus_external_diff]]
Textconv vagy külső diff választása
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Ha a repository-dban lévő bináris vagy speciálisan formázott blobok
közötti különbségeket szeretnéd megjeleníteni, választhatsz egy
külső diff parancs vagy a textconv használata között, hogy diffelhető
szöveges formátumra konvertáld őket. Az, hogy melyik módszert
választod, a konkrét helyzetedtől függ.

A külső diff parancs használatának előnye a rugalmasság. Nem vagy
kötve ahhoz, hogy sor-orientált változtatásokat találj, és a
kimenetnek sem kell egyesített diffre (unified diff) hasonlítania.
Szabadon megtalálhatod és jelentheted a változtatásokat az
adatformátumod számára legmegfelelőbb módon.

Egy textconv ehhez képest sokkal korlátozóbb. Az adatok
sor-orientált szöveges formátumra való átalakítását biztosítod, és a
Git a szokásos diff eszközeivel állítja elő a kimenetet. Ennek a
módszernek több előnye is van:

1. Egyszerű használat. Gyakran sokkal egyszerűbb megírni egy
   bináris-szöveges átalakítást, mint saját diffet készíteni. Sok
   esetben meglévő programok is használhatók textconv filterként
   (pl. exif, odt2txt).

2. Git diff funkciók. Mivel csak az átalakítási lépést végzed el
   magad, továbbra is kihasználhatod a Git diff funkcióinak nagy
   részét, beleértve a színezést, a szódiffet és a merge-ekhez való
   kombinált diffeket.

3. Gyorsítótárazás. A textconv gyorsítótárazása felgyorsíthatja az
   ismétlődő diffeket, mint amilyeneket a `git log -p` futtatásával
   idézhetsz elő.


[[_marking_files_as_binary]]
Fájlok binárisként való megjelölése
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A Git általában helyesen tippeli meg, hogy egy blob szöveges vagy
bináris adatot tartalmaz-e, a tartalom elejének megvizsgálásával.
Néha azonban szükséged lehet a döntésének felülbírálására, akár
azért, mert egy blob a fájl későbbi részében bináris adatot
tartalmaz, akár azért, mert a tartalom, bár technikailag
szövegkarakterekből áll, egy ember számára átláthatatlan. Például sok
postscript fájl csak ASCII karaktereket tartalmaz, mégis zajos és
értelmetlen diffeket eredményez.

A legegyszerűbb módja annak, hogy egy fájlt binárisként jelölj meg,
a diff attribútum törlése a `.gitattributes` fájlban:

------------------------
*.ps -diff
------------------------

Ez arra készteti a Gitet, hogy `Binary files differ` üzenetet
generáljon (vagy bináris patch-et, ha a bináris patch-ek engedélyezve
vannak), egy normál diff helyett.

Azonban előfordulhat, hogy más diff driver attribútumokat is meg
szeretnél adni. Például szeretnéd a `textconv`-ot használni, hogy a
postscript fájlokat ASCII reprezentációra konvertáld emberi
megtekintéshez, de egyébként binárisként kezelnéd őket. Nem adhatod
meg egyszerre a `-diff` és a `diff=ps` attribútumokat. A megoldás a
`diff.*.binary` konfigurációs opció használata:

------------------------
[diff "ps"]
  textconv = ps2ascii
  binary = true
------------------------

[[_performing_a_three_way_merge]]
Háromutas merge végrehajtása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`merge`
^^^^^^^

A `merge` attribútum befolyásolja, hogy egy fájl három verziója
hogyan lesz merge-elve, amikor egy fájlszintű merge szükséges a
`git merge`, illetve más parancsok, mint a `git revert` és a
`git cherry-pick` során.

Beállítva::

	A beépített 3-utas merge driver kerül felhasználásra a
	tartalom merge-eléséhez, a `RCS` csomag 'merge' parancsához
	hasonló módon. Ez a hétköznapi szövegfájlokhoz alkalmas.

Törölve::

	A jelenlegi branchből származó verzió lesz az ideiglenes
	merge-eredmény, és a merge konfliktusokkal rendelkezőnek lesz
	nyilvánítva. Ez jól definiált merge-szemantikával nem
	rendelkező bináris fájlokhoz alkalmas.

Meghatározatlan::

	Alapértelmezetten ugyanaz a beépített 3-utas merge driver
	kerül felhasználásra, mint amikor a `merge` attribútum be
	van állítva. Azonban a `merge.default` konfigurációs változó
	megnevezhet egy másik merge drivert azokhoz az útvonalakhoz,
	amelyekre a `merge` attribútum meghatározatlan.

String::

	A 3-utas merge a megadott egyéni merge driverrel kerül
	végrehajtásra. A beépített 3-utas merge driver a "text"
	driver kérésével adható meg explicit módon; a beépített,
	"a jelenlegi branchet veszi" driver a "binary" kéréssel
	adható meg.


[[_built_in_merge_drivers]]
Beépített merge driverek
^^^^^^^^^^^^^^^^^^^^^^^^^^

Van néhány beépített, alacsonyszintű merge driver definiálva,
amelyek a `merge` attribútumon keresztül kérhetők.

text::

	Szokásos 3-utas fájlszintű merge szövegfájlokhoz. A
	konfliktusos részeket a `<<<<<<<`, a `=======` és a
	`>>>>>>>` konfliktusjelölők jelölik. A branchedből származó
	verzió a `=======` jelölő előtt jelenik meg, a merge-elt
	branchből származó verzió pedig a `=======` jelölő után.

binary::

	A branchedből származó verziót tartja meg a munkafában, de
	az útvonalat konfliktusos állapotban hagyja, hogy a
	felhasználó rendezze azt.

union::

	3-utas fájlszintű merge-t hajt végre szövegfájlokra, de
	mindkét verzió sorait megtartja, konfliktusjelölők hagyása
	helyett. Ez hajlamos arra, hogy a hozzáadott sorokat
	véletlenszerű sorrendben hagyja a kapott fájlban, és a
	felhasználónak ellenőriznie kell az eredményt. Ne használd
	ezt, ha nem érted a következményeit.


[[_defining_a_custom_merge_driver]]
Egyéni merge driver definiálása
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Egy merge driver definiálása a `.git/config` fájlban történik, nem a
`gitattributes` fájlban, tehát szigorúan véve ez a kézikönyvoldal
rossz hely erről beszélni. Azonban...

Egy `filfre` egyéni merge driver definiálásához adj egy szakaszt a
`$GIT_DIR/config` fájlodhoz (vagy a `$HOME/.gitconfig` fájlodhoz),
így:

----------------------------------------------------------------
[merge "filfre"]
	name = feel-free merge driver
	driver = filfre %O %A %B %L %P
	recursive = binary
----------------------------------------------------------------

A `merge.*.name` változó ad a drivernek egy emberi olvasásra szánt
nevet.

A `merge.*.driver` változó értéke a közös ős verziójára (`%O`), az
aktuális verzióra (`%A`) és a másik branchek verziójára (`%B`)
futtatandó parancs felépítésére szolgál. Ezt a három tokent a
parancssor felépítésekor azon ideiglenes fájlok neveire cseréli,
amelyek ezen verziók tartalmát tartalmazzák. Ezenkívül a `%L`-t a
konfliktusjelölő méretére cseréli (lásd alább).

A merge drivertől azt várja el a rendszer, hogy a merge eredményét a
`%A`-val megnevezett fájlba hagyja, azt felülírva, és nulla
állapottal lépjen ki, ha sikerült tisztán merge-elnie azokat, vagy
nem nullával, ha voltak konfliktusok. Ha a driver összeomlik (pl.
SEGV-vel megölve), akkor 128-nál magasabb, nem nulla állapottal
várja el a rendszer, hogy kilépjen, és ebben az esetben a merge
hibával zárul (ami különbözik a konfliktus előállításától).

A `merge.*.recursive` változó megadja, melyik másik merge drivert
kell használni, amikor a merge drivert egy belső, közös ősök közötti
merge-hez hívják meg, ha egynél több van belőlük. Ha nincs megadva,
maga a driver kerül felhasználásra mind a belső merge-hez, mind a
végső merge-hez.

A merge driver a `%P` helyőrzőn keresztül tudhatja meg azt az
útvonalnevet, amelybe a merge-elt eredmény tárolva lesz. A közös
őshöz, a helyi HEAD-hez és a másik HEAD-hez tartozó
konfliktuscímkéket a `%S`, a `%X` és az `%Y` átadásával lehet
megadni, ebben a sorrendben.

`conflict-marker-size`
^^^^^^^^^^^^^^^^^^^^^^

Ez az attribútum szabályozza a munkafa fájljában konfliktusos merge
során hagyott konfliktusjelölők hosszát. Csak egy pozitív egész
számnak van értelmes hatása.

Például a `.gitattributes` fájlban lévő ez a sor arra használható,
hogy megmondja a merge-gépezetnek, hogy sokkal hosszabb (a szokásos
7 karakter hosszú helyett) konfliktusjelölőket hagyjon, amikor a
`Documentation/git-merge.adoc` fájl merge-elése konfliktust
eredményez.

------------------------
Documentation/git-merge.adoc	conflict-marker-size=32
------------------------


[[_checking_whitespace_errors]]
Whitespace-hibák ellenőrzése
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`whitespace`
^^^^^^^^^^^^

A `core.whitespace` konfigurációs változó lehetővé teszi, hogy
meghatározd, mit tekintsen a 'diff' és az 'apply' whitespace-hibának
a projekt összes útvonalára nézve (lásd: linkgit:git-config[1]). Ez
az attribútum finomabb, útvonalankénti szabályozást biztosít.

Beállítva::

	Az összes, a Git számára ismert lehetséges whitespace-hiba
	fajtát észreveszi. A tabulátor szélessége a `core.whitespace`
	konfigurációs változó értékéből származik.

Törölve::

	Semmit sem vesz észre hibaként.

Meghatározatlan::

	A `core.whitespace` konfigurációs változó értékét használja
	annak eldöntésére, hogy mit vegyen észre hibaként.

String::

	Egy vesszővel elválasztott listát adhatsz meg a
	`core.whitespace` konfigurációs változóval megegyező
	formátumban az észreveendő gyakori whitespace-problémákról.


[[_creating_an_archive]]
Archívum létrehozása
~~~~~~~~~~~~~~~~~~~~~~~

`export-ignore`
^^^^^^^^^^^^^^^

Az `export-ignore` attribútummal rendelkező fájlok és könyvtárak nem
kerülnek hozzáadásra az archívumfájlokhoz.

`export-subst`
^^^^^^^^^^^^^^

Ha az `export-subst` attribútum be van állítva egy fájlra, akkor a
Git több helyőrzőt is ki fog egészíteni, amikor ezt a fájlt egy
archívumhoz adja. A kiegészítés a commit ID elérhetőségétől függ,
azaz ha a linkgit:git-archive[1] parancsnak egy fa lett megadva
commit vagy tag helyett, akkor semmilyen behelyettesítés nem
történik. A helyőrzők ugyanazok, mint a linkgit:git-log[1]
`--pretty=format:` opciójánál, azzal a különbséggel, hogy a fájlban
így kell őket becsomagolni: `$Format:PLACEHOLDERS$`. Pl. a `$Format:%H$`
string a commit hash-re lesz cserélve. Azonban archívumonként csak
egy `%(describe)` helyőrző kerül kiegészítésre, a
szolgáltatásmegtagadásos (denial-of-service) támadások elkerülése
végett.


[[_packing_objects]]
Objektumok csomagolása
~~~~~~~~~~~~~~~~~~~~~~~

`delta`
^^^^^^^

A delta tömörítést nem kísérli meg a rendszer azon útvonalak
blobjaira, amelyekre a `delta` attribútum false-ra van állítva.


[[_viewing_files_in_gui_tools]]
Fájlok megjelenítése GUI eszközökben
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`encoding`
^^^^^^^^^^

Ennek az attribútumnak az értéke azt a karakterkódolást adja meg,
amelyet a GUI eszközöknek (pl. a linkgit:gitk[1] és a
linkgit:git-gui[1]) kell használniuk az adott fájl tartalmának
megjelenítéséhez. Vedd figyelembe, hogy teljesítménybeli
megfontolások miatt a linkgit:gitk[1] nem használja ezt az
attribútumot, hacsak nem engedélyezed manuálisan a fájlonkénti
kódolásokat a beállításaiban.

Ha ez az attribútum nincs beállítva, vagy érvénytelen értékkel
rendelkezik, akkor helyette a `gui.encoding` konfigurációs változó
értéke kerül felhasználásra
(lásd: linkgit:git-config[1]).


USING MACRO ATTRIBUTES
----------------------

Nem szeretnéd, hogy bármilyen sorvég-konverzió alkalmazva legyen, sem
azt, hogy szöveges diff készüljön bármely általad követett bináris
fájlhoz. Ehhez például a következőt kellene megadnod:

------------
*.jpg -text -diff
------------

de ez körülményessé válhat, ha sok attribútumod van. Makróattribútumok
használatával definiálhatsz egy olyan attribútumot, amely beállításkor
egyszerre több más attribútumot is beállít vagy töröl. A rendszer
ismer egy beépített makróattribútumot, a `binary`-t:

------------
*.jpg binary
------------

A "binary" attribútum beállítása a fentiek szerint törli a "text" és
a "diff" attribútumokat is. Vedd figyelembe, hogy a makróattribútumok
csak "Beállítva" állapotba kerülhetnek, bár egy ilyen beállításnak
lehet olyan hatása, hogy más attribútumokat beállít vagy töröl, vagy
akár visszaállít más attribútumokat a "Meghatározatlan" állapotba.


DEFINING MACRO ATTRIBUTES
-------------------------

Egyéni makróattribútumok csak felső szintű gitattributes fájlokban
definiálhatók (`$GIT_DIR/info/attributes`, a munkakönyvtár legfelső
szintjén lévő `.gitattributes` fájl, vagy a globális, illetve
rendszerszintű gitattributes fájlok), nem pedig a munkakönyvtár
alkönyvtáraiban lévő `.gitattributes` fájlokban. A beépített
"binary" makróattribútum a következővel egyenértékű:

------------
[attr]binary -diff -merge -text
------------

NOTES
-----

A Git nem követi a szimbolikus linkeket, amikor a munkakönyvtárban
egy `.gitattributes` fájlhoz fér hozzá. Ez konzisztens viselkedést
biztosít, amikor a fájlhoz az indexből vagy egy fából, illetve a
fájlrendszerből férnek hozzá.

EXAMPLES
--------

Ha a következő három `gitattributes` fájlod van:

----------------------------------------------------------------
(in $GIT_DIR/info/attributes)

a*	foo !bar -baz

(in .gitattributes)
abc	foo bar baz

(in t/.gitattributes)
ab*	merge=filfre
abc	-foo -bar
*.c	frotz
----------------------------------------------------------------

a `t/abc` útvonalhoz rendelt attribútumok a következőképpen
számítódnak ki:

1. A `t/.gitattributes` fájlt megvizsgálva (amely ugyanabban a
   könyvtárban van, mint a szóban forgó útvonal), a Git megtalálja,
   hogy az első sor illeszkedik. A `merge` attribútum be van
   állítva. Azt is megtalálja, hogy a második sor illeszkedik, és a
   `foo` és a `bar` attribútumok törölve vannak.

2. Ezután megvizsgálja a `.gitattributes` fájlt (amely a
   szülőkönyvtárban van), és megtalálja, hogy az első sor
   illeszkedik, de a `t/.gitattributes` fájl már eldöntötte, hogy a
   `merge`, a `foo` és a `bar` attribútumokat hogyan kell megadni
   ehhez az útvonalhoz, így a `foo`-t és a `bar`-t törölve hagyja. A
   `baz` attribútum be van állítva.

3. Végül megvizsgálja a `$GIT_DIR/info/attributes` fájlt. Ez a fájl
   a fában lévő beállítások felülbírálására szolgál. Az első sor
   illeszkedik, és a `foo` be van állítva, a `bar` visszaáll
   meghatározatlan állapotba, a `baz` pedig törölve van.

Ennek eredményeként a `t/abc`-hez rendelt attribútumok a következők
lesznek:

----------------------------------------------------------------
foo	set to true
bar	unspecified
baz	set to false
merge	set to string value "filfre"
frotz	unspecified
----------------------------------------------------------------


SEE ALSO
--------
linkgit:git-check-attr[1].

GIT
---
A linkgit:git[1] csomag része
