gitcredentials(7)
=================

NAME
----
gitcredentials - Felhasználónevek és jelszavak megadása a Gitnek

SYNOPSIS
--------
------------------
git config credential.https://example.com.username myusername
git config credential.helper "$helper $options"
------------------

DESCRIPTION
-----------

A Gitnek műveletek végrehajtásához néha hitelesítő adatokra van szüksége a
felhasználótól; például kérhet felhasználónevet és jelszót ahhoz, hogy HTTP-n
keresztül elérjen egy remote repositoryt. Egyes remote-ok személyes
hozzáférési tokent vagy OAuth hozzáférési tokent fogadnak el jelszóként. Ez a
kézikönyv leírja azokat a mechanizmusokat, amelyekkel a Git ezeket a
hitelesítő adatokat kéri, valamint néhány funkciót, amellyel elkerülhető
ezek ismételt beírása.

REQUESTING CREDENTIALS
----------------------

Ha nincsenek credential helperek megadva, a Git a következő stratégiákkal
próbál felhasználónevet és jelszót kérni a felhasználótól:

1. Ha a `GIT_ASKPASS` környezeti változó be van állítva, a változó által
   megadott program hívódik meg. A program megfelelő promptot kap a
   parancssorban, a felhasználó bevitele pedig a program standard
   kimenetéről olvasódik be.

2. Egyébként, ha a `core.askPass` konfigurációs változó be van állítva, az
   értéke a fentiek szerint használatos.

3. Egyébként, ha a `SSH_ASKPASS` környezeti változó be van állítva, az
   értéke a fentiek szerint használatos.

4. Egyébként a felhasználó a terminálon kap promptot.

AVOIDING REPETITION
-------------------

Nehézkes lehet ugyanazokat a hitelesítő adatokat újra és újra beírni.  A Git
két módszert kínál ennek a bosszúságnak a csökkentésére:

1. Felhasználónevek statikus konfigurálása egy adott hitelesítési
   kontextushoz.

2. Credential helperek jelszavak gyorsítótárazására vagy tárolására, vagy
   egy rendszerszintű jelszótárcával vagy kulcskarikával való
   interakcióhoz.

Az első egyszerű, és megfelelő, ha nincs biztonságos tároló a jelszóhoz. Ezt
általában úgy konfigurálják, hogy ezt hozzáadják a confighoz:

---------------------------------------
[credential "https://example.com"]
	username = me
---------------------------------------

A credential helperek viszont külső programok, amelyektől a Git
felhasználónevet és jelszót is kérhet; jellemzően az operációs rendszer vagy
más programok által biztosított biztonságos tárolóval kommunikálnak.
Alternatívaként egy credential-generáló helper bizonyos szerverekhez
valamilyen API-n keresztül generálhat hitelesítő adatokat.

Egy helper használatához először ki kell választanod egyet (lentebb van egy
lista).

Lehetnek harmadik féltől származó helpereid is telepítve; keress rá a
`credential-*`-ra a `git help -a` kimenetében, és nézd meg az egyes helperek
dokumentációját.  Miután kiválasztottál egy helpert, a nevét a
credential.helper változóba írva megmondhatod a Gitnek, hogy használja.

1. Keress egy helpert.
+
-------------------------------------------
$ git help -a | grep credential-
credential-foo
-------------------------------------------

2. Olvasd el a leírását.
+
-------------------------------------------
$ git help credential-foo
-------------------------------------------

3. Mondd meg a Gitnek, hogy használja.
+
-------------------------------------------
$ git config --global credential.helper foo
-------------------------------------------

[[_available_helpers]]
=== Elérhető helperek

A Git jelenleg a következő helpereket tartalmazza:

cache::

    A hitelesítő adatok rövid ideig tárolása a memóriában. A részletekért
    lásd linkgit:git-credential-cache[1].

store::

    A hitelesítő adatok határozatlan ideig tárolása a lemezen. A
    részletekért lásd linkgit:git-credential-store[1].

A biztonságos, tartós tárolással rendelkező népszerű helperek közé tartozik:

    - git-credential-libsecret (Linux)

    - git-credential-osxkeychain (macOS)

    - git-credential-wincred (Windows)

    - https://github.com/git-ecosystem/git-credential-manager[Git Credential Manager] (többplatformos, a Git for Windows része)

A közösség átfogó listát tart karban a Git credential helperekről itt:
https://git-scm.com/doc/credential-helpers.

[[_oauth]]
=== OAuth

A jelszavak vagy személyes hozzáférési tokenek beírásának alternatívája egy
OAuth credential helper használata. A kezdeti hitelesítés böngészőablakot nyit
a hoszthoz. A további hitelesítés a háttérben történik. Számos népszerű Git
hoszt támogatja az OAuth-ot.

Az OAuth-támogatással rendelkező népszerű helperek közé tartozik:

    - https://github.com/git-ecosystem/git-credential-manager[Git Credential Manager] (többplatformos, a Git for Windows része)

    - https://github.com/hickford/git-credential-oauth[git-credential-oauth] (többplatformos, számos Linux-disztribúció része)

CREDENTIAL CONTEXTS
-------------------

A Git úgy tekinti, hogy minden hitelesítő adatnak van egy URL által
meghatározott kontextusa. Ez a kontextus a kontextusspecifikus konfiguráció
kikeresésére szolgál, és átadódik minden helpernek, amely indexként
használhatja a biztonságos tárolóba.

Képzeld el például, hogy a `https://example.com/foo.git`-et érjük el. Amikor a
Git egy config fájlba néz, hogy lássa, egy szekció illeszkedik-e erre a
kontextusra, akkor tekinti a kettőt egyezőnek, ha a kontextus a config
fájlbeli minta specifikusabb részhalmaza. Ha például ez van a config
fájlodban:

--------------------------------------
[credential "https://example.com"]
	username = foo
--------------------------------------

akkor egyezés lesz: mindkét protokoll ugyanaz, és mindkét hoszt ugyanaz.
Ez a kontextus azonban nem illeszkedne:

--------------------------------------
[credential "https://kernel.org"]
	username = foo
--------------------------------------

mert a hosztnevek eltérnek. A `foo.example.com`-ra sem illeszkedne; a Git
pontosan hasonlítja össze a hosztneveket, anélkül, hogy figyelembe venné,
hogy két hoszt ugyanazon domain része-e. Hasonlóképpen egy
`http://example.com` config-bejegyzés sem illeszkedne: a Git pontosan
hasonlítja össze a protokollokat.  Használhatsz viszont helyettesítő
karaktereket a domainnévben és más mintaillesztési technikákat, ugyanúgy,
mint a `http.<URL>.*` opcióknál.

Ha a „minta" URL tartalmaz útvonal-komponenst, akkor annak
előtag-útvonalként kell illeszkednie: a `https://example.com/bar` kontextus
illeszkedik a `https://example.com/bar/baz.git` config-bejegyzésre, de nem
illeszkedik a `https://example.com/other/repo.git` vagy a
`https://example.com/barry/repo.git` config-bejegyzésre (még akkor sem, ha az
sztring-előtag).


CONFIGURATION OPTIONS
---------------------

Egy credential-kontextus opciói vagy a `credential.*`-ban (amely az összes
hitelesítő adatra vonatkozik), vagy a `credential.<URL>.*`-ban
konfigurálhatók, ahol az <URL> a fent leírtak szerint illeszkedik a
kontextusra.

A következő opciók mindkét helyen elérhetők:

helper::

	Egy külső credential helper neve és a hozzá tartozó opciók.
	Ha a helper neve nem abszolút útvonal, akkor a `git credential-`
	sztring kerül elé. Az eredményül kapott sztringet a shell hajtja
	végre (így például ha ezt `foo --option=bar`-ra állítod, az a
	`git credential-foo --option=bar`-t hajtja végre a shellen keresztül.
	A használatukra vonatkozó példákért lásd az egyes helperek
	kézikönyvét.
+
Ha a `credential.helper` konfigurációs változóból több példány is van,
mindegyik helpert sorban kipróbálja, és mindegyik adhat felhasználónevet,
jelszót vagy semmit. Ha a Git megszerzett egy felhasználónevet és egy le nem
járt jelszót is, több helpert már nem próbál ki.
+
Ha a `credential.helper` üres sztringre van konfigurálva, ez üresre állítja
vissza a helper-listát (így felülírhatod az alacsonyabb prioritású config
fájl által beállított helpert úgy, hogy az üres sztringű helpert
konfigurálod, majd utána azt a helper-készletet, amelyet szeretnél).

username::

	Alapértelmezett felhasználónév, ha az URL nem tartalmaz egyet.

useHttpPath::

	Alapértelmezés szerint a Git nem tekinti érdemesnek egy http URL
	„path" komponensét külső helperekkel illeszteni. Ez azt jelenti, hogy
	egy `https://example.com/foo.git`-hez tárolt hitelesítő adat a
	`https://example.com/bar.git`-hez is használatban lesz. Ha meg
	szeretnéd különböztetni ezeket az eseteket, állítsd ezt az opciót
	`true`-ra.


CUSTOM HELPERS
--------------

Írhatsz saját egyéni helpereket, hogy bármely rendszerrel kommunikálj,
amelyben hitelesítő adatokat tartasz.

A credential helperek olyan programok, amelyeket a Git futtat, hogy
hitelesítő adatokat olvasson be vagy mentsen hosszú távú tárolóból, illetve
oda (ahol a „hosszú távú" egyszerűen egyetlen Git-folyamatnál hosszabbat
jelent; pl. a hitelesítő adatok tárolhatók a memóriában néhány percig, vagy
határozatlan ideig a lemezen).

Minden helpert egyetlen sztring határoz meg a `credential.helper`
konfigurációs változóban (és másokban, lásd linkgit:git-config[1]).
A sztringet a Git a következő szabályokkal alakítja végrehajtandó paranccsá:

  1. Ha a helper-sztring "!"-lel kezdődik, shell-részletnek számít, és a "!"
     utáni minden a parancs lesz.

  2. Egyébként, ha a helper-sztring abszolút útvonallal kezdődik, a
     helper-sztring szó szerint a parancs lesz.

  3. Egyébként a "git credential-" sztring kerül a helper-sztring elé, és az
     eredmény lesz a parancs.

Az eredményül kapott parancshoz ezután egy "operation" argumentum fűződik
(részletekért lásd lentebb), és az eredményt a shell hajtja végre.

Íme néhány példa-specifikáció:

----------------------------------------------------
# run "git credential-foo"
[credential]
	helper = foo

# same as above, but pass an argument to the helper
[credential]
	helper = "foo --bar=baz"

# the arguments are parsed by the shell, so use shell
# quoting if necessary
[credential]
	helper = "foo --bar='whitespace arg'"

# store helper (discouraged) with custom location for the db file;
# use `--file ~/.git-secret.txt`, rather than `--file=~/.git-secret.txt`,
# to allow the shell to expand tilde to the home directory.
[credential]
	helper = "store --file ~/.git-secret.txt"

# you can also use an absolute path, which will not use the git wrapper
[credential]
	helper = "/path/to/my/helper --with-arguments"

# or you can specify your own shell snippet
[credential "https://example.com"]
	username = your_user
	helper = "!f() { test \"$1\" = get && echo \"password=$(cat $HOME/.secret)\"; }; f"
----------------------------------------------------

Általánosságban a fenti (3) szabály a legegyszerűbb a felhasználók számára
megadni. A credential helperek szerzőinek törekedniük kell a felhasználóik
segítésére azzal, hogy a programjukat "git-credential-$NAME"-nek nevezik, és
telepítéskor a `$PATH`-ba vagy a `$GIT_EXEC_PATH`-ba helyezik, ami lehetővé
teszi a felhasználónak, hogy a `git config credential.helper $NAME`
paranccsal engedélyezze.

Amikor egy helper végrehajtódik, egy "operation" argumentum fűződik a
parancssorához, amely a következők egyike:

`get`::

	Ad egy illeszkedő hitelesítő adatot, ha létezik ilyen.

`store`::

	Tárolja a hitelesítő adatot, ha ez a helperre alkalmazható.

`erase`::

	Eltávolítja az illeszkedő hitelesítő adatokat, ha vannak, a helper
	tárolójából.

A hitelesítő adat részletei a helper stdin folyamán érkeznek. A pontos
formátum ugyanaz, mint a `git credential` plumbing parancs be-/kimeneti
formátuma (részletes specifikációért lásd az `INPUT/OUTPUT FORMAT` szakaszt a
linkgit:git-credential[1] oldalon).

Egy `get` művelethez a helpernek attribútumok listáját kell előállítania a
stdouton ugyanabban a formátumban (a gyakori attribútumokért lásd
linkgit:git-credential[1]). A helper szabadon előállíthat egy részhalmazt,
vagy akár egyáltalán semmilyen értéket, ha nincs semmi hasznos, amit adhatna.
A megadott attribútumok felülírják azokat, amelyeket a Git credential
alrendszere már ismer. A fel nem ismert attribútumok csendben eldobásra
kerülnek.

Bár lehetséges az összes attribútum felülírása, a jól viselkedő helpereknek
tartózkodniuk kell ettől a felhasználónéven és jelszón kívüli bármely
attribútum esetében.

Ha egy helper `quit` attribútumot ad ki `true` vagy `1` értékkel, több
helpert nem kérdez meg, és a felhasználó sem kap promptot (ha nem adtak meg
hitelesítő adatot, a művelet ekkor sikertelen lesz).

Hasonlóképpen, több helpert nem kérdez meg, ha a felhasználónevet és a
jelszót is megadták.

Egy `store` vagy `erase` művelethez a helper kimenete figyelmen kívül marad.

Ha egy helper nem tudja végrehajtani a kért műveletet, vagy értesítenie kell
a felhasználót egy lehetséges problémáról, írhat a stderrbe.

Ha nem támogatja a kért műveletet (pl. egy csak olvasható tároló vagy
generátor), csendben figyelmen kívül kell hagynia a kérést.

Ha egy helper bármilyen más műveletet kap, csendben figyelmen kívül kell
hagynia a kérést. Ez teret hagy a jövőbeli műveletek hozzáadására (a régebbi
helperek egyszerűen figyelmen kívül hagyják az új kéréseket).

GIT
---
A linkgit:git[1] csomag része
