gitcvs-migration(7)
===================

NAME
----
gitcvs-migration - Git CVS-felhasználóknak

SYNOPSIS
--------
[verse]
'git cvsimport' *

DESCRIPTION
-----------

A Git abban különbözik a CVS-től, hogy minden working tree tartalmaz egy
repository-t a projekt előzményének teljes másolatával, és egyik repository
sem eleve fontosabb bármelyik másiknál.  Emulálhatod azonban a CVS-modellt
egyetlen megosztott repository kijelölésével, amellyel az emberek
szinkronizálhatnak; ez a dokumentum elmagyarázza, hogyan.

Némi alapszintű Git-ismeret szükséges. A linkgit:gittutorial[7] és a
linkgit:gitglossary[7] átolvasása elegendő kell, hogy legyen.

[[_developing_against_a_shared_repository]]
Fejlesztés megosztott repository-val
------------------------------------

Tegyük fel, hogy egy megosztott repository van beállítva a
/pub/repo.git alatt a foo.com hoszton.  Ekkor egyéni committerként ssh-n
keresztül klónozhatod a megosztott repository-t ezzel:

------------------------------------------------
$ git clone foo.com:/pub/repo.git/ my-project
$ cd my-project
------------------------------------------------

és belevágsz a munkába.  A 'cvs update' megfelelője:

------------------------------------------------
$ git pull origin
------------------------------------------------

ami bemerge-eli minden olyan munkát, amit mások esetleg végeztek a
klónozási művelet óta.  Ha vannak nem commitolt változások a working
tree-dben, először commitold őket, mielőtt lefuttatnád a git pullt.

[NOTE]
================================
A 'pull' parancs bizonyos konfigurációs változók miatt tudja, honnan
szerezze a frissítéseket, amelyeket az első 'git clone' parancs
állított be; részletekért lásd a `list` alparancsot a linkgit:git-config[1] oldalon.
================================

Frissítheted a megosztott repository-t a változásaiddal úgy, hogy először
commitolod a változásaidat, majd használod a 'git push' parancsot:

------------------------------------------------
$ git push origin master
------------------------------------------------

hogy azokat a commitokat "pushold" a megosztott repository-ba.  Ha valaki
más frissebben frissítette a repository-t, a 'git push', akárcsak a 'cvs
commit', panaszkodni fog, ilyenkor pullolnod kell minden változást, mielőtt
újra megpróbálod a pusht.

A fenti 'git push' parancsban megadjuk a frissítendő remote branch nevét
(`master`).  Ha ezt elhagyjuk, a 'git push' megpróbálja frissíteni a
remote repository összes olyan branchét, amelynek neve megegyezik egy
helyi repository-beli branch nevével.  Így az utolsó 'push' a következők
bármelyikével elvégezhető:

------------
$ git push origin
$ git push foo.com:/pub/project.git/
------------

mindaddig, amíg a megosztott repository-nak nincs más branche a
`master`-en kívül.

[[_setting_up_a_shared_repository]]
Megosztott repository beállítása
--------------------------------

Feltételezzük, hogy már létrehoztál egy Git repository-t a projektedhez,
esetleg a nulláról vagy egy tarballból (lásd linkgit:gittutorial[7]),
vagy egy már létező CVS repository-ból importálva (lásd a következő
szakaszt).

Tegyük fel, hogy a meglévő repód a /home/alice/myproject alatt van.  Hozz
létre egy új "bare" repository-t (working tree nélküli repository-t), és
fetcheld bele a projektedet:

------------------------------------------------
$ mkdir /pub/my-repo.git
$ cd /pub/my-repo.git
$ git --bare init --shared
$ git --bare fetch /home/alice/myproject master:master
------------------------------------------------

Ezután adj minden csapattagnak olvasási/írási hozzáférést ehhez a
repository-hoz.  Ennek egyik egyszerű módja, hogy minden csapattagnak
ssh-hozzáférést adsz ahhoz a géphez, amelyen a repository van hosztolva.
Ha nem akarsz nekik teljes shellt adni a gépen, van egy korlátozott
shell, amely csak Git pusholásokat és pullolásokat enged a
felhasználóknak; lásd linkgit:git-shell[1].

Tedd az összes committert ugyanabba a csoportba, és tedd a repository-t
írhatóvá az adott csoport számára:

------------------------------------------------
$ chgrp -R $group /pub/my-repo.git
------------------------------------------------

Gondoskodj róla, hogy a committereknek legfeljebb 027-es umaskjuk legyen,
hogy az általuk létrehozott könyvtárak írhatók és bejárhatók legyenek a
csoport többi tagja számára.

[[_importing_a_cvs_archive]]
CVS-archívum importálása
------------------------

NOTE: Ezek az utasítások a `git-cvsimport` szkriptet használják, amely a
git része, de más importálók jobb eredményt adhatnak. Más lehetőségekért
lásd a megjegyzést a linkgit:git-cvsimport[1] oldalon.

Először telepítsd a cvsps 2.1-es vagy magasabb verzióját innen:
https://github.com/andreyvit/cvsps[https://github.com/andreyvit/cvsps], és
győződj meg róla, hogy a path-odban van.  Aztán cd-zz be az érdeklődésedre
számot tartó projekt egy checkoutolt CVS munkakönyvtárába, és futtasd a linkgit:git-cvsimport[1]-et:

-------------------------------------------
$ git cvsimport -C <destination> <module>
-------------------------------------------

Ez a megnevezett CVS-modul egy Git-archívumát a <destination> könyvtárba
teszi, amely szükség esetén létrejön.

Az import a CVS-ből minden fájl minden revízióját checkoutolja.  A hírek
szerint a cvsimport átlagosan másodpercenként úgy húsz revíziót képes
feldolgozni, így egy közepes méretű projektnél ez nem tarthat tovább pár
percnél.  Nagyobb projektek vagy remote repository-k tovább tarthatnak.

A fő trunk az `origin` nevű Git branchben van tárolva, a további
CVS-branchek pedig ugyanolyan nevű Git branchekben.  A fő trunk
legfrissebb verziója a `master` branchen is checkoutolva marad, így
azonnal elkezdheted hozzáadni a saját változásaidat.

Az import inkrementális, így ha jövő hónapban újra meghívod, lefetcheli
az időközben végzett CVS-frissítéseket.  Hogy ez működjön, nem szabad
módosítanod az importált brancheket; ehelyett hozz létre új brancheket a
saját változásaidhoz, és szükség szerint merge-eld be az importált
brancheket.

Ha megosztott repository-t szeretnél, a fent leírtak szerint bare klónt
kell készítened az importált könyvtárból. Aztán kezeld az importált
könyvtárat egy másik fejlesztői klónként az inkrementális importok
merge-elése céljából.

[[_advanced_shared_repository_management]]
Haladó megosztott repository-kezelés
------------------------------------

A Git lehetővé teszi, hogy "hookoknak" nevezett szkripteket adj meg,
amelyek bizonyos pontokon lefutnak.  Ezeket használhatod például arra,
hogy a megosztott repository-ba érkező összes commitot elküldd egy
levelezőlistára.  Lásd linkgit:githooks[5].

Finomabb szemcsézettségű jogosultságokat kényszeríthetsz ki update
hookokkal.  Lásd link:howto/update-hook-example.html[Branchekhez való
hozzáférés vezérlése update hookokkal].

[[_providing_cvs_access_to_a_git_repository]]
CVS-hozzáférés biztosítása egy Git repository-hoz
-------------------------------------------------

Lehetséges valódi CVS-hozzáférést is biztosítani egy Git repository-hoz,
hogy a fejlesztők továbbra is használhassák a CVS-t; részletekért lásd a
linkgit:git-cvsserver[1] oldalt.

[[_alternative_development_models]]
Alternatív fejlesztési modellek
-------------------------------

A CVS-felhasználók megszokták, hogy egy fejlesztői csoportnak commit-
hozzáférést adnak egy közös repository-hoz.  Ahogy láttuk, ez a Gittel is
lehetséges.  A Git elosztott természete azonban más fejlesztési
modelleket is lehetővé tesz, és érdemes lehet először átgondolnod, hogy
valamelyikük nem illik-e jobban a projektedhez.

Például választhatsz egyetlen személyt, aki a projekt elsődleges nyilvános
repository-ját karbantartja.  A többi fejlesztő ezután klónozza ezt a
repository-t, és mindegyik a saját klónjában dolgozik.  Amikor van egy
sorozatnyi változásuk, amivel elégedettek, megkérik a maintainert, hogy
pulloljon a változásokat tartalmazó branchből.  A maintainer átnézi a
változásaikat, és bepullolja őket az elsődleges repository-ba, amelyből a
többi fejlesztő szükség szerint pullol, hogy összhangban maradjon.  A
Linux kernel és más projektek ennek a modellnek a változatait használják.

Kis csoport esetén a fejlesztők egyszerűen pullolhatják a változásokat
egymás repository-jából, központi maintainer nélkül.

SEE ALSO
--------
linkgit:gittutorial[7],
linkgit:gittutorial-2[7],
linkgit:gitcore-tutorial[7],
linkgit:gitglossary[7],
linkgit:giteveryday[7],
link:user-manual.html[A Git felhasználói kézikönyve]

GIT
---
A linkgit:git[1] csomag része
