gitcli(7)
=========

NAME
----
gitcli - Git parancssori felület és konvenciók

SYNOPSIS
--------
gitcli


DESCRIPTION
-----------

Ez a kézikönyv a Git CLI-ben végig használt konvenciót írja le.

Sok parancs revíziókat (leggyakrabban "commitokat", de néha
"tree-ish"-t, a kontextustól és a parancstól függően) és elérési utakat
vesz argumentumként.  A szabályok a következők:

 * Előbb az opciók jönnek, aztán az argumentumok.
    Egy alparancs kötőjeles opciókat (amelyeknek saját argumentumaik
    lehetnek, pl. "--max-parents 2") és argumentumokat vehet.  SHOULD
    előbb a kötőjeles opciókat, majd az argumentumokat megadni.  Egyes
    parancsok elfogadhatnak kötőjeles opciókat azután is, hogy már
    megadtál nem opció argumentumokat (ami többértelművé teheti a
    parancsot), de erre nem szabad támaszkodnod (mert végül találhatunk
    módot ezeknek a többértelműségeknek a javítására az "options then
    args" szabály kikényszerítésével).

 * Előbb a revíziók jönnek, aztán az elérési utak.
   Pl. a `git diff v1.0 v2.0 arch/x86 include/asm-x86`-ban a `v1.0` és a
   `v2.0` revíziók, az `arch/x86` és az `include/asm-x86` pedig elérési
   utak.

 * Amikor egy argumentum félreérthető akár revízióként, akár elérési
   útként, egyértelműsíthetők úgy, hogy `--`-t teszel közéjük.
   Pl. a `git diff -- HEAD` azt jelenti: "Van egy HEAD nevű fájlom a
   munkakönyvtáramban.  Kérlek, mutasd az általam az indexbe stage-elt
   verzió és az e fájlból a munkakönyvtáramban lévő közötti
   változásokat", nem pedig azt, hogy "mutasd a HEAD commit és a
   munkakönyvtár egésze közötti különbséget".  Az utóbbit a
   `git diff HEAD --` kérésével kérheted.

 * Egyértelműsítő `--` nélkül a Git ésszerű tippet ad, de többértelműség
   esetén hibával kilép, és egyértelműsítést kér.  Pl. ha van egy HEAD
   nevű fájlod a munkakönyvtáradban, a `git diff HEAD` többértelmű, és az
   egyértelműsítéshez vagy a `git diff HEAD --`-t, vagy a
   `git diff -- HEAD`-t kell kiadnod.

 * Mivel a `--` egyes parancsokban a revíziókat és az elérési utakat
   egyértelműsíti, ezeknél a parancsoknál nem használható az opciók és a
   revíziók elválasztására.  Erre a `--end-of-options` használható (ez
   olyan parancsoknál is működik, amelyek nem tesznek különbséget a
   revíziók és az elérési utak között, ilyenkor egyszerűen a `--`
   aliasa).
+
Amikor olyan szkriptet írsz, amelynek várhatóan tetszőleges felhasználói
bemenetet kell kezelnie, jó gyakorlat egyértelművé tenni, melyik argumentum
micsoda úgy, hogy egyértelműsítő `--`-t helyezel a megfelelő helyekre.

 * Sok parancs megenged helyettesítő karaktereket az elérési utakban, de
   meg kell védened őket attól, hogy a shell kifejtse őket.  Ez a kettő
   különböző dolgot jelent:
+
--------------------------------
$ git restore *.c
$ git restore \*.c
--------------------------------
+
Az előbbi hagyja, hogy a shell kifejtse a fileglobot, és azt kéred, hogy a
munkakönyvtáradban lévő pont-C fájlok felülíródjanak az indexben lévő
verzióval.  Az utóbbi átadja a `*.c`-t a Gitnek, és azt kéred, hogy az
indexben lévő, a mintára illeszkedő elérési utak checkoutolódjanak a
munkakönyvtáradba.  A `git add hello.c; rm hello.c` futtatása után az
előbbivel _nem_ fogod látni a `hello.c`-t a munkakönyvtáradban, az
utóbbival viszont igen.

 * Ahogyan a fájlrendszerben a '.' (pont) az aktuális könyvtárra utal, a
   '.' repository-névként való használata a Gitben (dot-repository) relatív
   elérési út, és az aktuális repositorydat jelenti.

Az alábbi szabályokat kell követned a "flag"-ekkel kapcsolatban, amikor a
Gitet szkripteled:

 * A rövid opciók külön szavakra bontása (részesítsd előnyben a
   `git foo -a -b`-t a `git foo -ab`-vel szemben; az utóbbi lehet, hogy
   nem is működik).

 * Amikor egy parancssori opció argumentumot vesz, használd a 'stuck'
   (összeragadt) alakot.  Más szóval rövid opcióknál a `git foo -o Arg`
   helyett a `git foo -oArg`-ot írd, hosszú opcióknál pedig a
   `git foo --long-opt Arg` helyett a `git foo --long-opt=Arg`-ot.  Egy
   opcionális opció-argumentumot vevő opciót a 'stuck' alakban kell írni.

 * A fenti javaslat ellenére, amikor az Arg egy felhasználó
   home-könyvtárához képest relatív elérési út, pl. `~/directory/file`
   vagy `~u/d/f`, érdemes lehet a különálló alakot használni, pl.
   `git foo --file ~/mine`, nem `git foo --file=~/mine`.  A shell az
   előbbiben kifejti a `~/`-t a home-könyvtáradra, de a legtöbb shell az
   utóbbiban megtartja a tildét.  Egyes parancsaink tudják, hogyan
   fejtsék ki tildével az opció értékét akkor is, ha stuck alakban van
   megadva, de nem mindegyik.

 * Amikor revízió-paramétert adsz egy parancsnak, győződj meg róla, hogy a
   paraméter nem többértelmű a munkakönyvtárban lévő valamely fájl
   nevével.  Pl. ne a `git log -1 HEAD`-et írd, hanem a
   `git log -1 HEAD --`-t; az előbbi nem működik, ha netán van egy `HEAD`
   nevű fájlod a munkakönyvtárban.

 * Sok parancs megengedi, hogy egy `--option` hosszú opciót csak az
   egyedi előtagjára rövidíts (pl. ha nincs másik opció, amelynek a neve
   `opt`-tal kezdődik, talán a `--opt` beírásával is meghívhatod a
   `--option` flaget), de a szkriptjeid írásakor teljesen ki kell írnod
   őket; a Git későbbi verziói bevezethetnek egy új opciót, amelynek a
   neve ugyanazt az előtagot osztja, pl. `--optimize`, amitől egy korábban
   egyedi rövid előtag már nem lesz egyedi.


ENHANCED OPTION PARSER
----------------------
A Git 1.5.4-es sorozatától kezdve sok Git parancs (bár az írás idején nem
mindegyik) továbbfejlesztett opció-elemzővel érkezik.

Íme az ezen opció-elemző által nyújtott lehetőségek listája.


[[_magic_options]]
Mágikus opciók
~~~~~~~~~~~~~~
Azok a parancsok, amelyeknél a továbbfejlesztett opció-elemző aktiválva
van, mind értenek néhány mágikus parancssori opciót:

-h::
	a parancs szépen formázott használati útmutatóját adja.
+
---------------------------------------------
$ git describe -h
usage: git describe [<options>] <commit-ish>*
   or: git describe [<options>] --dirty

    --contains            find the tag that comes after the commit
    --debug               debug search strategy on stderr
    --all                 use any ref
    --tags                use any tag, even unannotated
    --long                always use long format
    --abbrev[=<n>]        use <n> digits to display SHA-1s
---------------------------------------------
+
Vedd figyelembe, hogy egyes alparancsok (pl. `git grep`) másképp
viselkedhetnek, ha a `-h`-n kívül más is van a parancssorban, de a `git
subcmd -h` a parancssorban minden más nélkül a használati útmutatót
hivatott következetesen megadni.

--help-all::
	Egyes Git parancsok olyan opciókat vesznek, amelyeket csak plumbing
	célra használnak, vagy amelyek elavultak, és az ilyen opciók rejtve
	vannak az alapértelmezett használati útmutatóból. Ez az opció megadja
	az opciók teljes listáját.


[[_negating_options]]
Opciók negálása
~~~~~~~~~~~~~~~
A hosszú opciónévvel rendelkező opciók a `--no-` előtaggal negálhatók.
Például a `git branch` `--track` opciója alapértelmezés szerint 'on'. A
`--no-track` használatával felülbírálhatod ezt a viselkedést. Ugyanez
vonatkozik a `--color`-ra és a `--no-color`-ra.


[[_options_trump_configuration_and_environment]]
Az opciók felülírják a konfigurációt és a környezetet
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Amikor van egy konfigurációs változó vagy egy környezeti változó, amely
egy Git parancs valamely aspektusának viselkedését hangolja, és van egy
parancssori opció is, amely ugyanazt hangolja, a parancssori opció
felülírja azt, amit a konfigurációs és/vagy a környezeti változó mond.

Például a `user.name` konfigurációs változó azt az ember által olvasható
nevet adja meg, amelyet a `git commit` parancs használ az author és a
committer nevének rögzítésére egy újonnan létrehozott commitban. A
`GIT_AUTHOR_NAME` környezeti változó, ha be van állítva, elsőbbséget élvez
annak eldöntésekor, milyen author nevet rögzítsen.  A `git commit` parancs
`--author=<author>` parancssori opciója, ha meg van adva, elsőbbséget
élvez ezzel a két információforrással szemben.


[[_aggregating_short_options]]
Rövid opciók összevonása
~~~~~~~~~~~~~~~~~~~~~~~~
Azok a parancsok, amelyek támogatják a továbbfejlesztett opció-elemzőt,
lehetővé teszik a rövid opciók összevonását. Ez azt jelenti, hogy például
használhatod a `git rm -rf`-et vagy a `git clean -fdx`-et.


[[_abbreviating_long_options]]
Hosszú opciók rövidítése
~~~~~~~~~~~~~~~~~~~~~~~~
Azok a parancsok, amelyek támogatják a továbbfejlesztett opció-elemzőt, egy
hosszú opció egyedi előtagját úgy fogadják el, mintha teljesen ki lenne
írva, de ezt óvatosan használd.  Például a `git commit --amen` úgy
viselkedik, mintha a `git commit --amend`-et gépelted volna, de ez csak
addig igaz, amíg a Git egy későbbi verziója be nem vezet egy másik opciót,
amely ugyanazt az előtagot osztja, pl. a `git commit --amenity` opciót.


[[_separating_argument_from_the_option]]
Az argumentum elválasztása az opciótól
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Egy opció kötelező opció-paraméterét külön szóként is írhatod a
parancssorban.  Ez azt jelenti, hogy az összes alábbi használat működik:

----------------------------
$ git foo --long-opt=Arg
$ git foo --long-opt Arg
$ git foo -oArg
$ git foo -o Arg
----------------------------

Ez azonban *NEM* megengedett az opcionális értékű kapcsolóknál, ahol a
'stuck' alakot kell használni:

----------------------------
$ git describe --abbrev HEAD     # correct
$ git describe --abbrev=10 HEAD  # correct
$ git describe --abbrev 10 HEAD  # NOT WHAT YOU MEANT
----------------------------


[[_magic_filename_options]]
Mágikus fájlnév-opciók
~~~~~~~~~~~~~~~~~~~~~~
A fájlnevet vevő opciók megengednek egy `:(optional)` előtagot. Például:

----------------------------
git commit -F :(optional)COMMIT_EDITMSG
# if COMMIT_EDITMSG does not exist, the above is equivalent to
git commit
----------------------------

A konfigurációs értékekhez hasonlóan, ha a megnevezett fájl hiányzik, a Git
úgy viselkedik, mintha az opció egyáltalán nem lett volna megadva. Lásd a
"Values" szakaszt a linkgit:git-config[1]-ben.

NOTES ON FREQUENTLY CONFUSED OPTIONS
------------------------------------

Sok parancs, amely a munkakönyvtárban és/vagy az indexben lévő fájlokon
tud dolgozni, elfogadja a `--cached` és/vagy a `--index` opciót.  Néha az
emberek tévesen azt gondolják, hogy mivel az indexet eredetileg cache-nek
hívták, ez a kettő szinonima.  *Nem* azok -- ez a két opció nagyon
különböző dolgokat jelent.

 * A `--cached` opció arra való, hogy egy olyan parancsot, amely
   általában a munkakönyvtárban lévő fájlokon dolgozik, *csak* az
   indexszel dolgoztass.  Például a `git grep`, ha commit nélkül
   használják annak megadására, mely commitban keressen sztringeket,
   általában a munkakönyvtárban lévő fájlokon dolgozik, de a `--cached`
   opcióval az indexben keres sztringeket.

 * A `--index` opció arra való, hogy egy olyan parancsot, amely általában
   a munkakönyvtárban lévő fájlokon dolgozik, *arra kérj*, hogy az indexet
   *is* érintse.  Például a `git stash apply` általában egy
   stash-bejegyzésben rögzített változásokat merge-eli a munkakönyvtárba,
   de a `--index` opcióval az indexbe is bemerge-eli a változásokat.

A `git apply` parancs használható a `--cached`-del és a `--index`-szel (de
nem egyszerre).  A parancs általában csak a munkakönyvtárban lévő fájlokat
érinti, de a `--index`-szel mind a fájlokat, mind az indexbejegyzéseiket
patcheli, a `--cached`-del pedig csak az indexbejegyzéseket módosítja.

További információért lásd még a
https://lore.kernel.org/git/7v64clg5u9.fsf@assigned-by-dhcp.cox.net/ és a
https://lore.kernel.org/git/7vy7ej9g38.fsf@gitster.siamese.dyndns.org/
címet.

Néhány más parancs, amely szintén a munkakönyvtárban és/vagy az indexben
lévő fájlokon dolgozik, elfogadja a `--staged` és/vagy a `--worktree`
opciót.

* A `--staged` pontosan olyan, mint a `--cached`, amely arra kéri a
  parancsot, hogy csak az indexen dolgozzon, ne a munkakönyvtáron.

* A `--worktree` az ellentéte, arra kéri a parancsot, hogy csak a
  munkakönyvtáron dolgozzon, ne az indexen.

* A két opció együtt is megadható, hogy a parancs az indexen és a
  munkakönyvtáron is dolgozzon.

GIT
---
A linkgit:git[1] csomag része
