gitdiffcore(7)
==============

NAME
----
gitdiffcore - A diff kimenet finomhangolása

SYNOPSIS
--------
[verse]
'git diff' *

DESCRIPTION
-----------

A 'git diff-index', a 'git diff-files' és a 'git diff-tree' diff-parancsoknak
megmondható, hogy az általuk talált különbségeket szokatlan módon
manipulálják, mielőtt megjelenítenék a 'diff' kimenetet.  A manipulációt
összefoglalóan „diffcore transzformációnak" nevezzük.  Ez a rövid jegyzet
leírja, mik ezek, és hogyan használhatók a szokásosnál könnyebben érthető
'diff' kimenet előállítására.


[[_the_chain_of_operation]]
A műveleti lánc
---------------

A 'git diff-{asterisk}' család először két fájlhalmazt hasonlít össze:

 - a 'git diff-index' egy "tree" objektum és a munkakönyvtár tartalmát
   hasonlítja össze (amikor a `--cached` kapcsoló nincs használatban),
   vagy egy "tree" objektum és az index fájl tartalmát (amikor a
   `--cached` kapcsoló használatban van);

 - a 'git diff-files' az index fájl és a munkakönyvtár tartalmát
   hasonlítja össze;

 - a 'git diff-tree' két "tree" objektum tartalmát hasonlítja össze;

Ezekben az esetekben maga a parancs először opcionálisan leszűkíti a két
fájlhalmazt a parancssorában megadott pathspecekkel, majd összehasonlítja a
megfelelő útvonalakat a két eredményül kapott fájlhalmazban.

A pathspecek arra szolgálnak, hogy leszűkítsék a világot, amelyben a diff
működik.  Eltávolítják a megadott útvonalnév-halmazokon kívüli filepaireket.
Pl. ha a filepairek bemeneti halmaza ezt tartalmazta:

------------------------------------------------
:100644 100644 bcd1234... 0123456... M junkfile
------------------------------------------------

de a parancshívás `git diff-files myfile` volt, akkor a junkfile bejegyzés
eltávolításra kerülne a listából, mert csak a "myfile" jön szóba.

Az összehasonlítás eredményét ezek a parancsok átadják a belsőleg
„diffcore"-nak nevezett résznek, olyan formátumban, amely hasonló ahhoz,
mint amit a -p opció mellőzésekor ír ki.  Pl.

------------------------------------------------
in-place edit  :100644 100644 bcd1234... 0123456... M file0
create         :000000 100644 0000000... 1234567... A file4
delete         :100644 000000 1234567... 0000000... D file5
unmerged       :000000 000000 0000000... 0000000... U file6
------------------------------------------------

A diffcore mechanizmus ilyen összehasonlítási eredmények listáját kapja
(mindegyiket „filepairnek" nevezzük, bár ezen a ponton mindegyik egyetlen
fájlról szól), és az ilyen listát egy másik listává alakítja.  Jelenleg 5
ilyen transzformáció van:

- diffcore-break
- diffcore-rename
- diffcore-merge-broken
- diffcore-pickaxe
- diffcore-order
- diffcore-rotate

Ezek egymás után alkalmazódnak.  A 'git diff-{asterisk}' parancsok által
talált filepair-halmaz a diffcore-break bemenete, a diffcore-break kimenete
pedig a következő transzformáció bemenete.  A végeredmény ezután a kimeneti
rutinhoz kerül, és vagy diff-raw formátumot generál (lásd a
'git diff-{asterisk}' parancsok kézikönyvének kimeneti formátum szakaszait),
vagy diff-patch formátumot.


[[_diffcore_break_for_splitting_up_complete_rewrites]]
diffcore-break: teljes újraírások szétbontásához
------------------------------------------------

A lánc második transzformációja a diffcore-break, amelyet a
'git diff-{asterisk}' parancsok -B opciója vezérel.  Ez arra szolgál, hogy
felismerjen egy „teljes újraírást" képviselő filepairt, és két filepairre
bontsa, amelyek törlést és létrehozást képviselnek.  Pl.  ha a bemenet ezt a
filepairt tartalmazta:

------------------------------------------------
:100644 100644 bcd1234... 0123456... M file0
------------------------------------------------

és ha felismeri, hogy a "file0" fájl teljesen újra van írva, akkor erre
változtatja:

------------------------------------------------
:100644 000000 bcd1234... 0000000... D file0
:000000 100644 0000000... 0123456... A file0
------------------------------------------------

Egy filepair szétbontásához a diffcore-break megvizsgálja a változások
mértékét a fájlok módosítás előtti és utáni tartalma között (azaz a fenti
példában azon tartalmak között, amelyek SHA-1 tartalom-azonosítója
"bcd1234..." és "0123456...").  Az eredeti tartalom törlésének és az új
anyag beszúrásának mennyiségét összeadja, és ha ez meghaladja a „break
score"-t, a filepair kettébontásra kerül.  A break score alapértelmezése az
eredeti és az eredmény közül a kisebbik méretének 50%-a (azaz ha a
szerkesztés zsugorítja a fájlt, az eredmény mérete számít; ha a szerkesztés
hosszabbítja a fájlt, az eredeti mérete számít), és testreszabható egy szám
megadásával a "-B" opció után (pl. "-B75", hogy 75%-ot használjon).


[[_diffcore_rename_for_detecting_renames_and_copies]]
diffcore-rename: átnevezések és másolatok észleléséhez
------------------------------------------------------

Ez a transzformáció átnevezések és másolatok észlelésére szolgál, és a
'git diff-{asterisk}' parancsok -M opciója (átnevezések észlelése) és -C
opciója (másolatok észlelése is) vezérli.  Ha a bemenet ezeket a
filepaireket tartalmazta:

------------------------------------------------
:100644 000000 0123456... 0000000... D fileX
:000000 100644 0000000... 0123456... A file0
------------------------------------------------

és a törölt fileX fájl tartalma elég hasonló a létrehozott file0 fájl
tartalmához, akkor az átnevezés-észlelés összevonja ezeket a filepaireket, és
ezt hozza létre:

------------------------------------------------
:100644 100644 0123456... 0123456... R100 fileX file0
------------------------------------------------

Amikor a "-C" opció használatban van, a módosított fájlok és a törölt fájlok
eredeti tartalma (és a módosítatlan fájloké is, ha a "--find-copies-harder"
opció használatban van) az átnevezési/másolási művelet forrásfájljainak
jelöltjeként számít.  Ha a bemenet ilyen filepairekből állna, amelyek egy
módosított fileY fájlról és egy újonnan létrehozott file0 fájlról szólnak:

------------------------------------------------
:100644 100644 0123456... 1234567... M fileY
:000000 100644 0000000... bcd3456... A file0
------------------------------------------------

a fileY eredeti tartalmát és a file0 eredményül kapott tartalmát
összehasonlítja, és ha elég hasonlóak, ezekre változtatja őket:

------------------------------------------------
:100644 100644 0123456... 1234567... M fileY
:100644 100644 0123456... bcd3456... C100 fileY file0
------------------------------------------------

Mind az átnevezés-, mind a másolatészlelésben ugyanaz a „változások
mértéke" algoritmus dönti el, hogy két fájl „elég hasonló"-e, mint amelyet a
diffcore-break használ, és testreszabható, hogy az 50%-os alapértelmezéstől
eltérő hasonlósági pontszámot használjon egy szám megadásával a "-M" vagy
"-C" opció után (pl. "-M8", hogy 8/10 = 80%-ot használjon).

Vedd figyelembe, hogy amikor az átnevezés-észlelés be van kapcsolva, de a
másolat- és a break-észlelés is ki van kapcsolva, az átnevezés-észlelés egy
előzetes lépést ad hozzá, amely először azt ellenőrzi, hogy a fájlokat
áthelyezték-e könyvtárak között úgy, hogy a fájlnevük ugyanaz maradt.  Ha egy
könyvtárhoz hozzáadtak egy fájlt, amelynek tartalma kellően hasonló egy
azonos nevű fájléhoz, amelyet egy másik könyvtárból töröltek, átnevezésként
jelöli meg őket, és kizárja őket a későbbi négyzetes lépésből (amely
páronként hasonlítja össze az összes párosítatlan fájlt a „legjobb"
egyezések megtalálásához, a legnagyobb tartalmi hasonlóság alapján).  Így
például ha egy törölt docs/ext.txt és egy hozzáadott docs/config/ext.txt elég
hasonló, átnevezésként jelöli meg őket, és megakadályozza, hogy egy
hozzáadott docs/ext.md-t, amely akár még hasonlóbb is lehet a törölt
docs/ext.txt-hez, a későbbi lépésben az átnevezés céljának tekintsen.  Emiatt
az előzetes „match same filename" lépés kissé magasabb küszöböt használ
ahhoz, hogy egy fájlpárt átnevezésként jelöljön meg, és leálljon a jobb
egyezésekre való más jelöltek vizsgálatával.  Ebben az előzetes menetben
fájlonként legfeljebb egy összehasonlítás történik; így ha a pontos
átnevezés-észlelés után több ext.txt fájl marad a könyvtárhierarchiában,
ezeknél a fájloknál ez az előzetes lépés kihagyható.

Megjegyzés.  Amikor a "-C" opciót a `--find-copies-harder` opcióval együtt
használják, a 'git diff-{asterisk}' parancsok a módosítottak mellett a
módosítatlan filepaireket is átadják a diffcore mechanizmusnak.  Ez lehetővé
teszi, hogy a másolatészlelő a módosítatlan fájlokat is másolási
forrásjelöltnek tekintse, cserébe lassabbá válik.  A `--find-copies-harder`
nélkül a 'git diff-{asterisk}' parancsok csak akkor ismerik fel a
másolatokat, ha a lemásolt fájl történetesen ugyanabban a changesetben lett
módosítva.


[[_diffcore_merge_broken_for_putting_complete_rewrites_back_together]]
diffcore-merge-broken: teljes újraírások összeillesztéséhez
-----------------------------------------------------------

Ez a transzformáció arra szolgál, hogy a diffcore-break által szétbontott, és
a diffcore-rename által átnevezéssé/másolattá nem alakított filepaireket
visszaolvassza egyetlen módosítássá.  Ez mindig lefut, amikor a
diffcore-break használatban van.

A szétbontott filepairek visszaolvasztásához a diffcore-break és a
diffcore-rename által használtaktól eltérő „változások mértéke" számítást
használ.  Csak az eredetiből való törlést számolja, a beszúrást nem.  Ha egy
100 soros dokumentumból csak 10 sort távolítottál el, még ha 910 új sort
adtál is hozzá egy új, 1000 soros dokumentum létrehozásához, nem végeztél
teljes újraírást.  A diffcore-break szétbontja az ilyen esetet, hogy segítse
a diffcore-rename-et abban, hogy az ilyen filepaireket az
átnevezés-/másolatészlelés jelöltjeként vegye figyelembe, de ha az így
szétbontott filepairek nem párosultak más filepairekkel átnevezés/másolat
létrehozásához, akkor ez a transzformáció visszaolvasztja őket az eredeti
„módosítássá".

A „változások mértéke" paraméter a 80%-os alapértelmezéstől (azaz hacsak az
eredeti anyag több mint 80%-át nem törlik, a szétbontott párok
visszaolvadnak egyetlen módosítássá) eltérően állítható egy második szám
megadásával a -B opciónak, így:

* -B50/60 (adj 50% „break score"-t a diffcore-break-nek, használj 60%-ot
  a diffcore-merge-broken-hez).

* -B/60 (ugyanaz, mint fent, mivel a diffcore-break alapértelmezése 50%).

Vedd figyelembe, hogy a korábbi implementáció a szétbontott párt külön
létrehozási és törlési patchként hagyta meg.  Ez felesleges hack volt, és a
legújabb implementáció mindig visszaolvasztja az összes szétbontott párt
módosításokká, de az eredményül kapott patch kimenete másképp van
formázva a könnyebb átnézhetőség érdekében egy ilyen teljes újraírás
esetén: a régi verzió teljes tartalmát '-' előtaggal, majd az új verzió
teljes tartalmát '+' előtaggal mutatja.


[[_diffcore_pickaxe_for_detecting_addition_deletion_of_specified_string]]
diffcore-pickaxe: megadott sztring hozzáadásának/törlésének észleléséhez
------------------------------------------------------------------------

Ez a transzformáció a filepairek halmazát azokra korlátozza, amelyek adott
sztringeket bizonyos módon megváltoztatnak a preimage és a postimage között.
A -S<block-of-text> és a -G<regular-expression> opció szolgál e sztringek
keresésének különböző módjai megadására.

A "-S<block-of-text>" azokat a filepaireket észleli, amelyek preimage-e és
postimage-e eltérő számú előfordulást tartalmaz a megadott szövegblokkból.
Definíció szerint nem észleli a fájlon belüli mozgatásokat.  Továbbá amikor
egy changeset egészében mozgat egy fájlt anélkül, hogy érintené az érdekes
sztringet, a diffcore-rename a szokásos módon lép működésbe, és a `-S`
kihagyja a filepairt (mivel az adott sztring előfordulásainak száma nem
változott abban az átnevezésként észlelt filepairben).  A `--pickaxe-regex`
kapcsolóval használva a <block-of-text> literál sztring helyett illesztendő
kiterjesztett POSIX reguláris kifejezésként kezelendő.

A "-G<regular-expression>" (emlékeztető: grep) azokat a filepaireket észleli,
amelyek szöveges diffjében van olyan hozzáadott vagy törölt sor, amely
illeszkedik a megadott reguláris kifejezésre.  Ez azt jelenti, hogy észleli a
fájlon belüli (vagy amit az átnevezés-észlelés ugyanazon fájlnak tekint)
mozgatásokat, ami zaj.  Az implementáció kétszer futtat diffet és grepel, és
ez elég költséges lehet.  A gyorsítás érdekében a textconv szűrők nélküli
bináris fájlokat figyelmen kívül hagyja.

Amikor a `-S`-t vagy a `-G`-t `--pickaxe-all` nélkül használják, csak azok a
filepairek maradnak meg a kimenetben, amelyek illeszkednek a saját
kritériumukra.  Amikor a `--pickaxe-all` használatban van, ha egy
changesetben akár csak egy filepair is illeszkedik a saját kritériumára, az
egész changeset megmarad.  Ezt a viselkedést arra tervezték, hogy
megkönnyítse a változások átnézését az egész changeset kontextusában.

[[_diffcore_order_for_sorting_the_output_based_on_filenames]]
diffcore-order: a kimenet rendezéséhez fájlnevek alapján
--------------------------------------------------------

Ez arra szolgál, hogy a filepaireket a felhasználó (vagy a projekt) ízlése
szerint átrendezze, és a 'git diff-{asterisk}' parancsok -O opciója vezérli.

Ez egy szöveges fájlt vár, amelynek minden sora egy shell glob minta.  Azok a
filepairek, amelyek a fájl egy korábbi sorában lévő glob mintára
illeszkednek, egy későbbi sorra illeszkedők előtt kerülnek a kimenetbe, a
glob mintára nem illeszkedő filepairek pedig utolsóként.

Példaként a core Git egy tipikus orderfile-ja valószínűleg így nézne ki:

------------------------------------------------
README
Makefile
Documentation
*.h
*.c
t
------------------------------------------------

[[_diffcore_rotate_for_changing_at_which_path_output_starts]]
diffcore-rotate: annak megváltoztatásához, melyik útvonalnál kezdődik a kimenet
-------------------------------------------------------------------------------

Ez a transzformáció egy útvonalnevet vesz, és úgy forgatja el a filepairek
halmazát, hogy a megadott útvonalnévhez tartozó filepair kerüljön előre,
opcionálisan eldobva az előtte lévő útvonalakat.  Ez a `--skip-to` és a
`--rotate-to` opció megvalósítására szolgál.  Hiba, ha a megadott útvonalnév
nincs a filepairek halmazában, de nem hasznos hibával kilépni a "git log"
parancscsaláddal használva, mert észszerűtlen elvárni, hogy egy adott
útvonalat a "git log" parancs által megjelenített minden egyes commit
módosítson.  Emiatt a "git log"-gal használva a kimenet ott kezdődik, ahol az
a filepair van, amely ugyanoda rendeződik, mint a megadott útvonalnév, vagy
az első olyan, amely utána.

Ha ezt a transzformációt a diffcore-order-rel kombinálva használják, az
váratlan eredményeket produkál, mivel ennek a transzformációnak a bemenete
valószínűleg nincs rendezve, amikor a diffcore-order érvényben van.


SEE ALSO
--------
linkgit:git-diff[1],
linkgit:git-diff-files[1],
linkgit:git-diff-index[1],
linkgit:git-diff-tree[1],
linkgit:git-format-patch[1],
linkgit:git-log[1],
linkgit:gitglossary[7],
link:user-manual.html[A Git felhasználói kézikönyve]

GIT
---
A linkgit:git[1] csomag része
