giteveryday(7)
==============

NAME
----
giteveryday - Hasznos minimális parancskészlet a mindennapi Githez

SYNOPSIS
--------

A mindennapi Git nagyjából 20 paranccsal

DESCRIPTION
-----------

A Git-felhasználók nagyjából négy kategóriába sorolhatók, ahhoz, hogy itt
leírjuk a mindennapi Githez hasznos parancsok egy kis készletét.

*	Az <<STANDALONE,egyéni fejlesztő (önálló)>> parancsai
	alapvetők bárkinek, aki commitol, még annak is, aki egyedül
	dolgozik.

*	Ha másokkal dolgozol, szükséged lesz az <<PARTICIPANT,egyéni
	fejlesztő (résztvevő)>> szakaszban felsorolt parancsokra is.

*	Azoknak, akik az <<INTEGRATOR,integrátor>> szerepét töltik be, a
	fentieken felül még néhány parancsot meg kell tanulniuk.

*	A <<ADMINISTRATION,repository-adminisztráció>> parancsai azoknak a
	rendszergazdáknak valók, akik a Git-repository-k gondozásáért
	felelősek.


Egyéni fejlesztő (önálló)[[STANDALONE]]
---------------------------------------

Egy önálló egyéni fejlesztő nem cserél patcheket másokkal, és egyedül
dolgozik egyetlen repository-ban, a következő parancsokat használva.

  * linkgit:git-init[1] egy új repository létrehozásához.

  * linkgit:git-log[1] annak megtekintéséhez, hogy mi történt.

  * linkgit:git-switch[1] és linkgit:git-branch[1] a branchek közötti
    váltáshoz.

  * linkgit:git-add[1] az indexfájl kezeléséhez.

  * linkgit:git-diff[1] és linkgit:git-status[1] annak megtekintéséhez,
    hogy minek a közepén vagy.

  * linkgit:git-commit[1] az aktuális branch előreléptetéséhez.

  * linkgit:git-restore[1] a változások visszavonásához.

  * linkgit:git-merge[1] a helyi branchek közötti merge-eléshez.

  * linkgit:git-rebase[1] a topic branchek karbantartásához.

  * linkgit:git-tag[1] egy ismert pont megjelöléséhez.

Példák
~~~~~~

Egy tarball használata kiindulópontként egy új repository-hoz.::
+
------------
$ tar zxf frotz.tar.gz
$ cd frotz
$ git init
$ git add . <1>
$ git commit -m "import of frotz source tree."
$ git tag v2.43 <2>
------------
+
<1> minden hozzáadása az aktuális könyvtár alatt.
<2> könnyűsúlyú, nem annotált tag készítése.

Topic branch létrehozása és fejlesztés.::
+
------------
$ git switch -c alsa-audio <1>
$ edit/compile/test
$ git restore curses/ux_audio_oss.c <2>
$ git add curses/ux_audio_alsa.c <3>
$ edit/compile/test
$ git diff HEAD <4>
$ git commit -a -s <5>
$ edit/compile/test
$ git diff HEAD^ <6>
$ git commit -a --amend <7>
$ git switch master <8>
$ git merge alsa-audio <9>
$ git log --since='3 days ago' <10>
$ git log v2.43.. curses/ <11>
------------
+
<1> új topic branch létrehozása.
<2> az elrontott változásaid visszavonása a `curses/ux_audio_oss.c`-ben.
<3> meg kell mondanod a Gitnek, ha új fájlt adtál hozzá; az
eltávolítást és a módosítást elkapja, ha később `git commit -a`-t
csinálsz.
<4> annak megtekintéséhez, hogy milyen változásokat commitolsz.
<5> minden commitolása, ahogy teszteltél, a sign-offoddal.
<6> az összes változásod megtekintése az előző committal együtt.
<7> az előző commit amendelése, minden új változásod hozzáadásával, az
eredeti üzeneteddel.
<8> váltás a master branchre.
<9> egy topic branch merge-elése a master branchedbe.
<10> commit-naplók áttekintése; a kimenet korlátozásának más alakjai
kombinálhatók, és ilyen a `-10` (legfeljebb 10 commit megjelenítéséhez),
a `--until=2005-12-10`, stb.
<11> csak azoknak a változásoknak a megtekintése, amelyek a `curses/`
könyvtárban lévő dolgokat érintik, a `v2.43` tag óta.


Egyéni fejlesztő (résztvevő)[[PARTICIPANT]]
-------------------------------------------

Egy csoportos projektben résztvevőként dolgozó fejlesztőnek meg kell
tanulnia, hogyan kommunikáljon másokkal, és ezeket a parancsokat
használja az önálló fejlesztő által igényelteken felül.

  * linkgit:git-clone[1] az upstreamből a helyi repository-d
    feltöltéséhez.

  * linkgit:git-pull[1] és linkgit:git-fetch[1] az "origin"-ból, hogy
    naprakész maradj az upstreammel.

  * linkgit:git-push[1] megosztott repository-ba, ha CVS-stílusú
    megosztott repository munkafolyamatot alkalmazol.

  * linkgit:git-format-patch[1] e-mailes beküldés előkészítéséhez, ha
    Linux kernel stílusú nyilvános fórum munkafolyamatot alkalmazol.

  * linkgit:git-send-email[1] az e-mailes beküldésed elküldéséhez, a
    MUA-d általi sérülés nélkül.

  * linkgit:git-request-pull[1] a változások összefoglalójának
    létrehozásához, hogy az upstreamed pull-olhassa.


Példák
~~~~~~

Az upstream klónozása és munka rajta. Változások betáplálása az upstreambe.::
+
------------
$ git clone git://git.kernel.org/pub/scm/.../torvalds/linux-2.6 my2.6
$ cd my2.6
$ git switch -c mine master <1>
$ edit/compile/test; git commit -a -s <2>
$ git format-patch master <3>
$ git send-email --to="person <email@example.com>" 00*.patch <4>
$ git switch master <5>
$ git pull <6>
$ git log -p ORIG_HEAD.. arch/i386 include/asm-i386 <7>
$ git ls-remote --heads http://git.kernel.org/.../jgarzik/libata-dev.git <8>
$ git pull git://git.kernel.org/pub/.../jgarzik/libata-dev.git ALL <9>
$ git reset --hard ORIG_HEAD <10>
$ git gc <11>
------------
+
<1> egy új `mine` branch checkoutolása a masterből.
<2> ismételd, ahányszor kell.
<3> patchek kinyerése a branchedből, a masterhez képest,
<4> és e-mailezd el őket.
<5> visszatérés a `master`-hez, készen arra, hogy lásd, mi az újdonság
<6> a `git pull` alapból az `origin`-ból fetchel, és az aktuális
branchbe merge-el.
<7> közvetlenül a pull-olás után nézd meg az upstreamen végzett
változásokat, mióta legutóbb megnéztük, csak azon a területen, amely
minket érdekel.
<8> ellenőrizd a branchneveket egy külső repository-ban (ha nem
ismertek).
<9> fetchelj egy konkrét `ALL` branchből egy konkrét repository-ból, és
merge-eld.
<10> a pull visszavonása.
<11> a visszavont pull-ból maradt objektumok szemétgyűjtése.


Push egy másik repository-ba.::
+
------------
satellite$ git clone mothership:frotz frotz <1>
satellite$ cd frotz
satellite$ git config --get-regexp '^(remote|branch)\.' <2>
remote.origin.url mothership:frotz
remote.origin.fetch refs/heads/*:refs/remotes/origin/*
branch.master.remote origin
branch.master.merge refs/heads/master
satellite$ git config remote.origin.push \
	   +refs/heads/*:refs/remotes/satellite/* <3>
satellite$ edit/compile/test/commit
satellite$ git push origin <4>

mothership$ cd frotz
mothership$ git switch master
mothership$ git merge satellite/master <5>
------------
+
<1> a mothership gépen van egy frotz repository a home könyvtárad alatt;
klónozz belőle, hogy repository-t indíts a satellite gépen.
<2> a clone alapból beállítja ezeket a konfigurációs változókat. Úgy
rendezi el a `git pull`-t, hogy a mothership gép branchjeit a helyi
`remotes/origin/*` remote-tracking branchekbe fetchelje és tárolja.
<3> rendezd el a `git push`-t úgy, hogy az összes helyi branchet a
mothership gép megfelelő branchjébe pusholja.
<4> a push az összes munkánkat elstasheli a mothership gépen lévő
`remotes/satellite/*` remote-tracking branchekbe. Ezt használhatod
biztonsági mentés módszerként. Hasonlóképp úgy tehetsz, mintha a
mothership „fetchelt" volna tőled (hasznos, amikor a hozzáférés
egyoldalú).
<5> a mothership gépen merge-eld a satellite gépen végzett munkát a
master branchbe.

Leágazás egy konkrét tagről.::
+
------------
$ git switch -c private2.6.14 v2.6.14 <1>
$ edit/compile/test; git commit -a
$ git checkout master
$ git cherry-pick v2.6.14..private2.6.14 <2>
------------
+
<1> egy privát branch létrehozása egy jól ismert (de kissé lemaradt)
tag alapján.
<2> a `private2.6.14` branch összes változásának előreportolása a
`master` branchbe formális „merge-elés" nélkül. Vagy hosszabban +
`git format-patch -k -m --stdout v2.6.14..private2.6.14 |
  git am -3 -k`

Egy alternatív résztvevői beküldési mechanizmus a `git request-pull`
vagy a pull request mechanizmusok használata (pl. ahogy a GitHubon
(www.github.com) használják), hogy értesítsd az upstreamedet a
hozzájárulásodról.

Integrátor[[INTEGRATOR]]
------------------------

Egy meglehetősen központi személy, aki egy csoportos projektben
integrátorként jár el, megkapja a mások által végzett változásokat,
átnézi és integrálja őket, és közzéteszi az eredményt, hogy mások
használhassák, a résztvevők által igényelteken felül ezeket a
parancsokat használva.

Ezt a szakaszt azok is használhatják, akik a `git request-pull`-ra vagy
a GitHubon (www.github.com) lévő pull requestre válaszolnak, hogy mások
munkáját a saját történetükbe integrálják. Egy repository egyik
alterületének lieutenantja résztvevőként és integrátorként is eljár.


  * linkgit:git-am[1] a hozzájárulóidtól e-mailben beküldött patchek
    alkalmazásához.

  * linkgit:git-pull[1] a megbízható lieutenantjaidtól való
    merge-eléshez.

  * linkgit:git-format-patch[1] javasolt alternatíva előkészítéséhez és
    elküldéséhez a hozzájárulóknak.

  * linkgit:git-revert[1] az elszúrt commitok visszavonásához.

  * linkgit:git-push[1] a bleeding edge közzétételéhez.


Példák
~~~~~~

Egy tipikus integrátor Git-napja.::
+
------------
$ git status <1>
$ git branch --no-merged master <2>
$ mailx <3>
& s 2 3 4 5 ./+to-apply
& s 7 8 ./+hold-linus
& q
$ git switch -c topic/one master
$ git am -3 -i -s ./+to-apply <4>
$ compile/test
$ git switch -c hold/linus && git am -3 -i -s ./+hold-linus <5>
$ git switch topic/one && git rebase master <6>
$ git switch -C seen next <7>
$ git merge topic/one topic/two && git merge hold/linus <8>
$ git switch maint
$ git cherry-pick master~4 <9>
$ compile/test
$ git tag -s -m "GIT 0.99.9x" v0.99.9x <10>
$ git fetch ko && for branch in master maint next seen <11>
    do
	git show-branch ko/$branch $branch <12>
    done
$ git push --follow-tags ko <13>
------------
+
<1> nézd meg, minek a közepén voltál, ha egyáltalán.
<2> nézd meg, mely branchek nincsenek még merge-elve a `master`-be.
Hasonlóképp bármely más integrációs branchre, pl. `maint`, `next` és
`seen`.
<3> olvasd el a leveleket, mentsd el az alkalmazhatóakat, és mentsd el
külön azokat, amelyek még nem egészen készek (más levélolvasók is
elérhetők).
<4> alkalmazd őket, interaktívan, a sign-offjaiddal.
<5> hozz létre topic branchet, ahogy kell, és alkalmazz, megint
sign-offokkal.
<6> rebase-eld a belső topic branchet, amely nincs merge-elve a
masterbe, és nincs kitéve egy stabil branch részeként.
<7> a `seen`-t minden alkalommal a nextből indítsd újra.
<8> és bundle-eld az még főzés alatt lévő topic brancheket.
<9> egy kritikus javítás backportolása.
<10> egy aláírt tag létrehozása.
<11> győződj meg róla, hogy a master nem lett véletlenül visszatekerve
azon túl, amit már kipusholtál.
<12> a `git show-branch` kimenetében a `master`-nek meg kell lennie
mindennek, ami a `ko/master`-nek van, a `next`-nek pedig mindennek, ami
a `ko/next`-nek van, stb.
<13> pushold ki a bleeding edge-et, az új tagekkel együtt, amelyek a
kipusholt történetbe mutatnak.

Ebben a példában a `ko` rövidítés a Git maintainerének kernel.org-on
lévő repository-jára mutat, és így néz ki:

------------
(in .git/config)
[remote "ko"]
	url = kernel.org:/pub/scm/git/git.git
	fetch = refs/heads/*:refs/remotes/ko/*
	push = refs/heads/master
	push = refs/heads/next
	push = +refs/heads/seen
	push = refs/heads/maint
------------


Repository-adminisztráció[[ADMINISTRATION]]
-------------------------------------------

Egy repository-adminisztrátor a következő eszközöket használja arra,
hogy a fejlesztők repository-hoz való hozzáférését beállítsa és
karbantartsa.

  * linkgit:git-daemon[1] a repository-ból való anonim letöltés
    engedélyezéséhez.

  * linkgit:git-shell[1] 'korlátozott bejelentkezési shellként'
    használható a megosztott központi repository felhasználóihoz.

  * linkgit:git-http-backend[1] a Git-over-HTTP ("Smart http")
    szerveroldali megvalósítását adja, amely fetch- és push-szolgáltatást
    is lehetővé tesz.

  * linkgit:gitweb[1] webes felületet ad a Git-repository-khoz, amely a
    linkgit:git-instaweb[1] szkripttel állítható be.

A link:howto/update-hook-example.html[update hook howto] jó példát ad
egy megosztott központi repository kezelésére.

Ezenkívül számos más, széles körben telepített hosztolási, böngészési és
átnézési megoldás létezik, mint például:

  * gitolite, gerrit code review, cgit és mások.

Példák
~~~~~~
A következőt feltételezzük a /etc/services-ben::
+
------------
$ grep 9418 /etc/services
git		9418/tcp		# Git Version Control System
------------

A git-daemon futtatása a /pub/scm kiszolgálásához inetd-ből.::
+
------------
$ grep git /etc/inetd.conf
git	stream	tcp	nowait	nobody \
  /usr/bin/git-daemon git-daemon --inetd --export-all /pub/scm
------------
+
A tényleges konfigurációs sornak egyetlen soron kell lennie.

A git-daemon futtatása a /pub/scm kiszolgálásához xinetd-ből.::
+
------------
$ cat /etc/xinetd.d/git-daemon
# default: off
# description: The Git server offers access to Git repositories
service git
{
	disable = no
	type            = UNLISTED
	port            = 9418
	socket_type     = stream
	wait            = no
	user            = nobody
	server          = /usr/bin/git-daemon
	server_args     = --inetd --export-all --base-path=/pub/scm
	log_on_failure  += USERID
}
------------
+
Ellenőrizd az xinetd(8) dokumentációdat és a beállításodat, ez egy Fedora
rendszerről származik. Másoknál eltérhet.

Csak push/pull hozzáférés adása a fejlesztőknek git-over-ssh használatával.::

pl. azoknak, akik ezt használják:
`$ git push/pull ssh://host.xz/pub/scm/project`
+
------------
$ grep git /etc/passwd <1>
alice:x:1000:1000::/home/alice:/usr/bin/git-shell
bob:x:1001:1001::/home/bob:/usr/bin/git-shell
cindy:x:1002:1002::/home/cindy:/usr/bin/git-shell
david:x:1003:1003::/home/david:/usr/bin/git-shell
$ grep git /etc/shells <2>
/usr/bin/git-shell
------------
+
<1> a bejelentkezési shell a /usr/bin/git-shell-re van állítva, amely
csak a `git push`-t és a `git pull`-t engedi. A felhasználóknak
ssh-hozzáférés kell a géphez.
<2> sok disztribúcióban az /etc/shells-nek fel kell sorolnia, mit
használnak bejelentkezési shellként.

CVS-stílusú megosztott repository.::
+
------------
$ grep git /etc/group <1>
git:x:9418:alice,bob,cindy,david
$ cd /home/devo.git
$ ls -l <2>
  lrwxrwxrwx   1 david git    17 Dec  4 22:40 HEAD -> refs/heads/master
  drwxrwsr-x   2 david git  4096 Dec  4 22:40 branches
  -rw-rw-r--   1 david git    84 Dec  4 22:40 config
  -rw-rw-r--   1 david git    58 Dec  4 22:40 description
  drwxrwsr-x   2 david git  4096 Dec  4 22:40 hooks
  -rw-rw-r--   1 david git 37504 Dec  4 22:40 index
  drwxrwsr-x   2 david git  4096 Dec  4 22:40 info
  drwxrwsr-x   4 david git  4096 Dec  4 22:40 objects
  drwxrwsr-x   4 david git  4096 Nov  7 14:58 refs
  drwxrwsr-x   2 david git  4096 Dec  4 22:40 remotes
$ ls -l hooks/update <3>
  -r-xr-xr-x   1 david git  3536 Dec  4 22:40 update
$ cat info/allowed-users <4>
refs/heads/master	alice\|cindy
refs/heads/doc-update	bob
refs/tags/v[0-9]*	david
------------
+
<1> helyezd a fejlesztőket ugyanabba a git csoportba.
<2> és tedd a megosztott repository-t a csoport által írhatóvá.
<3> használd Carl update-hook példáját a Documentation/howto/-ból a
branch-politika szabályozásához.
<4> alice és cindy pusholhat a masterbe, csak bob pusholhat a
doc-update-be. david a kiadáskezelő, és ő az egyetlen személy, aki
verziótageket hozhat létre és pusholhat.

GIT
---
A linkgit:git[1] csomag része
