gitformat-loose(5)
==================

NAME
----
gitformat-loose - Git laza objektumformátum


SYNOPSIS
--------
[verse]
$GIT_DIR/objects/[0-9a-f][0-9a-f]/*
$GIT_DIR/objects/object-map/map-*.map

DESCRIPTION
-----------

A laza objektumok révén tárolja a Git az egyes objektumokat: minden
objektum külön fájlként íródik ki.

Egy repository élettartama során az objektumok kezdetben általában laza
objektumként íródnak ki.  Ezek a laza objektumok végül a repository
karbantartása során packfile-okba tömörülnek a lemezterület-használat
javítása és az objektumok gyorsabb kikeresése érdekében.

[[_loose_objects]]
== Laza objektumok

Minden laza objektum egy előtagot tartalmaz, amelyet közvetlenül az
objektum adata követ.  Az előtag a `<type> <size>\0`-t tartalmazza.  A
`<type>` a `blob`, `tree`, `commit` vagy `tag` egyike, a `size` pedig az
adat mérete (az előtag nélkül) ASCII-ban kifejezett decimális egészként.

A teljes tartalom – az előtag és az adat összefűzve – ezután zlib-bel
tömörítésre kerül, és a tömörített adat kerül a fájlba.  Az objektum
objektumazonosítója a tömörítetlen adat SHA-1 vagy (a helyzettől függően)
SHA-256 hash-e.

A laza objektum fájlja az `objects` könyvtár alatt tárolódik, ahol az
objektumazonosító első két hexadecimális karaktere a könyvtár, a többi
karakter pedig a fájlnév.  Ez az adat szilánkokra bontását szolgálja, és
azt, hogy ne legyen túl sok fájl egy könyvtárban, mivel egyes
fájlrendszerek rosszul teljesítenek, ha sok elem van egy könyvtárban.

Példaként az üres tree (tömörítetlenül) a `tree 0\0` adatot tartalmazza,
és egy SHA-256 repository-ban a
`6ef19b41225c5369f1c104d45d8d85efa9b057b53b14b4b9b939dd74decc5321`
objektumazonosítója lenne, és a
`$GIT_DIR/objects/6e/f19b41225c5369f1c104d45d8d85efa9b057b53b14b4b9b939dd74decc5321`
alatt tárolódna.

Hasonlóképp egy `abc` tartalmú blob tömörítetlen adata a `blob 3\0abc`
lenne.

[[_loose_object_mapping]]
== Laza objektumok leképezése

Amikor a `compatObjectFormat` opció használatban van, a Gitnek tárolnia
kell egy leképezést a repository fő algoritmusa és a kompatibilitási
algoritmus között a laza objektumokra, valamint némi kiegészítő információt.

A leképezés a `$GIT_DIR/objects/object-map` alatti, `.map`-re végződő
fájlok halmazából áll.  A fájlnév kiterjesztés előtti része a fő
hash-ellenőrzőösszeg (azaz az `extensions.objectformat`-ban megadott)
hexadecimális formátumban.

A `git gc` a meglévő bejegyzéseket egy fájlba csomagolja újra, eltávolítva
minden szükségtelen objektumot, például az elavult shallow bejegyzéseket
vagy a már csomagolt laza objektumokat.

A fájlformátum a következő.  Minden érték hálózati bájtsorrendben van, és
minden 4 és 8 bájtos értéknek 4 bájtra igazítottnak kell lennie a fájlban,
így egyes esetekben NUL-kitöltésre lehet szükség.  A Git mindig a
kitöltéshez szükséges legkevesebb NUL-bájtot (akár nullát) használja, hogy
a fájlok írása determinisztikus legyen.

- A fájl elején egy fejléc áll, amely a következőkből áll:
	* 4 bájtos leképezés-szignatúra: `LMAP`
	* 4 bájtos verziószám: 1
	* A fejléc szakasz 4 bájtos hossza (a fenntartott bejegyzésekkel együtt,
		de a NUL-kitöltés nélkül).
	* Az ebben a map-fájlban deklarált objektumok 4 bájtos száma.
	* Az ebben a map-fájlban deklarált objektumformátumok 4 bájtos száma.
	* Minden objektumformátumhoz:
		** 4 bájtos formátumazonosító (pl. `sha1` a SHA-1-hez)
		** A rövidített objektumnevek (azaz a teljes objektumnevek előtagjai)
			 hossza bájtban, 4 bájton. Ez a lehető legrövidebb hossz, amely
			 egyértelművé teszi a rövidített objektumnév-tábla neveit.
		** 8 bájtos egész, amely rögzíti, hogy az ehhez a formátumhoz tartozó táblák
		hol tárolódnak ebben az indexfájlban, a fájl elejétől számított eltolásként.
	* 8 bájtos eltolás a záró blokkig, e fájl elejétől számítva.
	* A fejléc szakasz többi része jövőbeli felhasználásra van fenntartva.
		Az olvasóknak itt figyelmen kívül kell hagyniuk a fel nem ismert adatot.
- Nulla vagy több NUL-bájt.  Ezek az alábbi 4 bájtos mennyiségek
	igazításának javítására szolgálnak.
- Táblák az első objektumformátumhoz:
	* A rövidített objektumnevek rendezett táblája.  Ezek az ebben a fájlban
		lévő összes objektum nevének előtagjai, egymáshoz csomagolva, hogy
		csökkentsék egy adott objektumnév bináris keresésének gyorsítótár-igényét.
  * A teljes objektumnevek rendezett táblája.
	* 4 bájtos metaadat-értékek táblája.
- Nulla vagy több NUL-bájt.
- Táblák a további objektumformátumokhoz:
	* A rövidített objektumnevek rendezett táblája.  Ezek az ebben a fájlban
		lévő összes objektum nevének előtagjai, eltolásértékek nélkül egymáshoz
		csomagolva, hogy csökkentsék egy adott objektumnév bináris keresésének
		gyorsítótár-igényét.
	* A teljes objektumnevek táblája az első objektumformátum által megadott sorrendben.
	* 4 bájtos értékek táblája, amely az objektumnév-sorrendet az első
		objektumformátum sorrendjére képezi le. A rendezett rövidített
		objektumnevek táblájában lévő objektumhoz az ebben a táblában lévő
		megfelelő indexnél található érték az előző táblában ugyanazon objektum
		indexe.
	* Nulla vagy több NUL-bájt.
- A záró blokk a következőkből áll:
	* A fentiek mindegyikének hash-ellenőrzőösszege a fő hash használatával.

Minden metaadat-tábla alsó hat bitje egy típusmezőt tartalmaz, amely
megadja az objektum tárolásának okát:

0::
	Fenntartva.
1::
	Ez az objektum laza objektumként van tárolva a repository-ban.
2::
	Ez az objektum egy shallow bejegyzés.  A leképezés egy remote szerver
	által visszaadott shallow értékre hivatkozik.
3::
	Ez az objektum egy submodule-bejegyzés.  A leképezés a submodule-t
	reprezentáló, tárolt commitra hivatkozik.

A jövőben más adat is tárolható ebben a mezőben.  A nem használt bitek
nullák kell legyenek.

GIT
---
A linkgit:git[1] csomag része
