gitformat-pack(5)
=================

NAME
----
gitformat-pack - A Git pack formátum


SYNOPSIS
--------
[verse]
$GIT_DIR/objects/pack/pack-*.{pack,idx}
$GIT_DIR/objects/pack/pack-*.rev
$GIT_DIR/objects/pack/pack-*.mtimes
$GIT_DIR/objects/pack/multi-pack-index

DESCRIPTION
-----------

A Git pack formátum az, ahogyan a Git a legtöbb elsődleges repository
adatát tárolja. Egy repository élettartama alatt a laza objektumok (ha
vannak) és a kisebb packek nagyobb pack(ek)ké lesznek konszolidálva.
Lásd linkgit:git-gc[1] és linkgit:git-pack-objects[1].

A pack formátumot a vezetéken keresztül (over-the-wire) is használják,
lásd pl. linkgit:gitprotocol-v2[5], valamint más konténerformátumok
részeként is, a linkgit:gitformat-bundle[5] esetében.

[[_checksums_and_object_ids]]
== Ellenőrzőösszegek és objektum-ID-k

Egy hagyományos SHA-1-et használó repositoryban az alább említett pack
ellenőrzőösszegek, index ellenőrzőösszegek és objektum-ID-k (objektumnevek)
mind SHA-1-gyel vannak kiszámítva. Hasonlóképp, SHA-256 repositorykban
ezek az értékek SHA-256-tal vannak kiszámítva.

A CRC32 ellenőrzőösszegek mindig a teljes csomagolt objektum felett vannak
kiszámítva, beleértve a fejlécet (n-bájtos típus és hossz); a bázisobjektum
nevét vagy offszetjét, ha van ilyen; és a teljes tömörített objektumot.
A használt CRC32 algoritmus a zlib-é.

[[_pack_pack_files_have_the_following_format]]
== A pack-*.pack fájlok formátuma a következő:

   - Az elején egy fejléc található, amely a következőkből áll:

     4-byte signature:
         The signature is: {'P', 'A', 'C', 'K'}

     4-byte version number (network byte order):
	 Git currently accepts version number 2 or 3 but
         generates version 2 only.

     4-byte number of objects contained in the pack (network byte order)

     Observation: we cannot have more than 4G versions ;-) and
     more than 4G objects in a pack.

   - A fejlécet objektumbejegyzések sora követi, amelyek mindegyike
     így néz ki:

     (undeltified representation)
     n-byte type and length (3-bit type, (n-1)*7+4-bit length)
     compressed data

     (deltified representation)
     n-byte type and length (3-bit type, (n-1)*7+4-bit length)
     base object name if OBJ_REF_DELTA or a negative relative
	 offset from the delta object's position in the pack if this
	 is an OBJ_OFS_DELTA object
     compressed delta data

     Observation: the length of each object is encoded in a variable
     length format and is not constrained to 32-bit or anything.

  - A trailer a fentiek pack ellenőrzőösszegét rögzíti.

[[_object_types]]
=== Objektumtípusok

Az érvényes objektumtípusok:

- OBJ_COMMIT (1)
- OBJ_TREE (2)
- OBJ_BLOB (3)
- OBJ_TAG (4)
- OBJ_OFS_DELTA (6)
- OBJ_REF_DELTA (7)

Az 5-ös típus jövőbeli bővítésre van fenntartva. A 0-s típus érvénytelen.

[[_object_encoding]]
=== Objektumkódolás

A laza objektumokkal ellentétben a csomagolt objektumoknak nincs a típust,
a méretet és egy NUL bájtot tartalmazó előtagjuk. Ezekre nincs szükség, mert
meghatározhatók az adatot megelőző n-bájtos típusból és hosszból, ezért
kimaradnak a tömörített és deltásított adatból.

Az objektum-ID kiszámítása továbbra is ezt az előtagot használja, azt a
típusból és hosszból szükség szerint rekonstruálva.

[[_size_encoding]]
=== Méretkódolás

Ez a dokumentum a nemnegatív egészek alábbi „méretkódolását" használja:
minden bájtból a hét legkevésbé szignifikáns bitet használjuk fel az
eredő egész szám képzéséhez. Amíg a legszignifikánsabb bit 1, a folyamat
folytatódik; a 0 MSB-jű bájt adja az utolsó hét bitet. A hétbites darabok
egymáshoz vannak fűzve. A későbbi értékek szignifikánsabbak.

Ezt a méretkódolást nem szabad összekeverni az „offszetkódolással", amelyet
szintén használ ez a dokumentum.

Amikor egy nem deltásított objektum méretét kódoljuk egy packben, a méret a
tömörítetlen nyers objektumé. Deltásított objektumoknál ez a tömörítetlen
delta mérete. A bázisobjektum neve vagy offszetje nem része a
méretszámításnak.

[[_deltified_representation]]
=== Deltásított reprezentáció

Koncepcionálisan csak négy objektumtípus létezik: commit, tree, tag és
blob. A hely megtakarítása érdekében azonban egy objektum tárolható egy
másik „bázis" objektum „deltájaként" is. Ezek a reprezentációk új
típusokat kapnak, az ofs-delta-t és a ref-delta-t, amelyek csak pack
fájlon belül érvényesek.

Mind az ofs-delta, mind a ref-delta azt a „deltát" tárolja, amelyet egy
másik objektumra (az úgynevezett 'bázisobjektumra') kell alkalmazni az
objektum rekonstruálásához. A köztük lévő különbség az, hogy a ref-delta
közvetlenül kódolja a bázisobjektum nevét. Ha a bázisobjektum ugyanabban a
packben van, az ofs-delta helyette a bázisobjektum packen belüli offszetjét
kódolja.

A bázisobjektum szintén lehet deltásított, ha ugyanabban a packben van.
A ref-delta a packen kívüli objektumra is hivatkozhat (azaz az úgynevezett
„thin pack" esetén). Lemezen tárolva azonban a packnek önmagában
zártnak kell lennie, hogy elkerülje a ciklikus függőséget.

A delta adat a bázisobjektum méretével és a rekonstruálandó objektum
méretével kezdődik. Ezek a méretek a fenti méretkódolással vannak
kódolva. A delta adat fennmaradó része az objektumot a bázisobjektumból
rekonstruáló utasítások sorozata. Ha a bázisobjektum deltásított, azt
először kanonikus formára kell alakítani. Minden utasítás egyre több
adatot fűz a célobjektumhoz, amíg az teljes nem lesz. Eddig két támogatott
utasítás van: az egyik egy bájttartomány másolására a forrásobjektumból,
a másik pedig az utasításba ágyazott új adat beszúrására.

Minden utasítás változó hosszúságú. Az utasítás típusát az első oktett
hetedik bitje határozza meg. Az alábbi diagramok az RFC 1951 (Deflate
tömörített adatformátum) konvencióját követik.

[[_instruction_to_copy_from_base_object]]
==== Utasítás másolásra a bázisobjektumból

  +----------+---------+---------+---------+---------+-------+-------+-------+
  | 1xxxxxxx | offset1 | offset2 | offset3 | offset4 | size1 | size2 | size3 |
  +----------+---------+---------+---------+---------+-------+-------+-------+

Ez az utasításformátum egy bájttartomány másolására szolgál a
forrásobjektumból. Kódolja azt az offszetet, ahonnan másolni kell, és a
másolandó bájtok számát. Az offszet és a méret little-endian sorrendben van.

Az összes offszet- és méretbájt opcionális. Ez az utasításméret
csökkentését szolgálja kis offszetek vagy méretek kódolásakor. Az első
oktett első hét bitje határozza meg, hogy a következő hét oktett közül
melyik van jelen. Ha a nulladik bit be van állítva, offset1 jelen van. Ha
az első bit be van állítva, offset2 jelen van, és így tovább.

Vegyük észre, hogy egy kompaktabb utasítás nem változtatja meg az offszet-
és mérethelyeket. Ha például csak az offset2 marad ki, mint alább, az
offset3 továbbra is a 16-23. biteket tartalmazza. Nem lesz offset2, és nem
a 8-15. biteket tartalmazza, még akkor sem, ha közvetlenül az offset1
mellett van.

  +----------+---------+---------+
  | 10000101 | offset1 | offset3 |
  +----------+---------+---------+

A legkompaktabb formájában ez az utasítás csak egy bájtot foglal el
(0x80), az offszet és a méret is elhagyva, amelyek ekkor alapértelmezett
nulla értéket kapnak. Van még egy kivétel: a nulla méret automatikusan
0x10000-re alakul át.

[[_instruction_to_add_new_data]]
==== Utasítás új adat hozzáadására

  +----------+============+
  | 0xxxxxxx |    data    |
  +----------+============+

Ez az utasítás a célobjektum bázisobjektum nélküli felépítésére szolgál.
A következő adat a célobjektumhoz kerül hozzáfűzésre. Az első oktett első
hét bitje határozza meg az adat méretét bájtokban. A méret nem lehet nulla.

[[_reserved_instruction]]
==== Fenntartott utasítás

  +----------+============
  | 00000000 |
  +----------+============

Ez az utasítás jövőbeli bővítésre van fenntartva.

[[_original_version_1_pack_idx_files_have_the_following_format]]
== Az eredeti (1-es verziójú) pack-*.idx fájlok formátuma a következő:

  - A fejléc 256 darab 4-bájtos, hálózati bájtsorrendű egészből áll.
    A tábla N-edik bejegyzése rögzíti azon objektumok számát a
    megfelelő packben, amelyek objektumnevének első bájtja kisebb vagy
    egyenlő, mint N. Ezt nevezzük „first-level fan-out" táblának.

  - A fejlécet rendezett, 24-bájtos bejegyzések követik, egy bejegyzés
    minden objektumhoz a packben. Minden bejegyzés a következő:

    4-byte network byte order integer, recording where the
    object is stored in the packfile as the offset from the
    beginning.

    one object name of the appropriate size.

  - A fájl egy trailerrel zárul:

    A copy of the pack checksum at the end of the corresponding
    packfile.

    Index checksum of all of the above.

Pack Idx file:

	--  +--------------------------------+
fanout	    | fanout[0] = 2 (for example)    |-.
table	    +--------------------------------+ |
	    | fanout[1]                      | |
	    +--------------------------------+ |
	    | fanout[2]                      | |
	    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ |
	    | fanout[255] = total objects    |---.
	--  +--------------------------------+ | |
main	    | offset                         | | |
index	    | object name 00XXXXXXXXXXXXXXXX | | |
table	    +--------------------------------+ | |
	    | offset                         | | |
	    | object name 00XXXXXXXXXXXXXXXX | | |
	    +--------------------------------+<+ |
	  .-| offset                         |   |
	  | | object name 01XXXXXXXXXXXXXXXX |   |
	  | +--------------------------------+   |
	  | | offset                         |   |
	  | | object name 01XXXXXXXXXXXXXXXX |   |
	  | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   |
	  | | offset                         |   |
	  | | object name FFXXXXXXXXXXXXXXXX |   |
	--| +--------------------------------+<--+
trailer	  | | packfile checksum              |
	  | +--------------------------------+
	  | | idxfile checksum               |
	  | +--------------------------------+
          .-------.
                  |
Pack file entry: <+

     packed object header:
	1-byte size extension bit (MSB)
	       type (next 3 bit)
	       size0 (lower 4-bit)
        n-byte sizeN (as long as MSB is set, each 7-bit)
		size0..sizeN form 4+7+7+..+7 bit integer, size0
		is the least significant part, and sizeN is the
		most significant part.
     packed object data:
        If it is not DELTA, then deflated bytes (the size above
		is the size before compression).
	If it is REF_DELTA, then
	  base object name (the size above is the
		size of the delta data that follows).
          delta data, deflated.
	If it is OFS_DELTA, then
	  n-byte offset (see below) interpreted as a negative
		offset from the type-byte of the header of the
		ofs-delta entry (the size above is the size of
		the delta data that follows).
	  delta data, deflated.

     offset encoding:
	  n bytes with MSB set in all but the last one.
	  The offset is then the number constructed by
	  concatenating the lower 7 bit of each byte, and
	  for n >= 2 adding 2^7 + 2^14 + ... + 2^(7*(n-1))
	  to the result.



[[_version_2_pack_idx_files_support_packs_larger_than_4_gib_and]]
== A 2-es verziójú pack-*.idx fájlok 4 GiB-nál nagyobb packeket
   is támogatnak, és néhány más átszervezésen is átestek. A formátumuk:

  - Egy 4-bájtos mágikus szám ('\377tOc'), amely egy valószínűtlen
    fanout[0] értéknek felel meg.

  - Egy 4-bájtos verziószám (= 2)

  - Egy 256 bejegyzésből álló fan-out tábla, akárcsak v1-ben.

  - Egy tábla a rendezett objektumnevekkel. Ezek offszetértékek nélkül
    vannak összecsomagolva, hogy csökkentsék egy adott objektumnévre
    végzett bináris keresés cache-lábnyomát.

  - Egy tábla a csomagolt objektumadatok 4-bájtos CRC32 értékeivel.
    Ez új a v2-ben, így a tömörített adat közvetlenül másolható
    packből packbe újracsomagolás közben, észrevétlen adatsérülés
    nélkül.

  - Egy tábla a 4-bájtos offszetértékekkel (hálózati bájtsorrendben).
    Ezek általában 31-bites pack fájl offszetek, de a nagy offszetek
    a következő táblába mutató, beállított MSB-vel rendelkező
    indexként vannak kódolva.

  - Egy tábla a 8-bájtos offszetbejegyzésekkel (üres a 2 GiB-nál
    kisebb pack fájloknál). A pack fájlok úgy vannak szervezve, hogy
    a gyakran használt objektumok elöl legyenek, így a legtöbb
    objektumhivatkozásnak nem kell erre a táblára hivatkoznia.

  - Ugyanaz a trailer, mint egy v1 pack fájlnál:

    A pack ellenőrzőösszeg egy másolata a megfelelő packfile végén.

    A fentiek indexellenőrzőösszege.

[[_pack_rev_files_have_the_format]]
== A pack-*.rev fájlok formátuma a következő:

  - Egy 4-bájtos mágikus szám ('0x52494458') ('RIDX').

  - Egy 4-bájtos verzióazonosító (= 1).

  - Egy 4-bájtos hash-függvény-azonosító (= 1 SHA-1-hez, 2 SHA-256-hoz).

  - Egy tábla az indexpozíciókkal (objektumonként egy, összesen
    num_objects darab, mindegyik egy 4-bájtos, hálózati sorrendű,
    előjel nélküli egész), a packfile-beli megfelelő offszetjeik
    szerint rendezve.

  - Egy trailer, amely tartalmazza:

    a megfelelő packfile ellenőrzőösszegét, és

    a fentiek ellenőrzőösszegét.

Minden 4-bájtos szám hálózati sorrendben van.

[[_pack_mtimes_files_have_the_format]]
== A pack-*.mtimes fájlok formátuma a következő:

Minden 4-bájtos szám hálózati bájtsorrendben van.

  - Egy 4-bájtos mágikus szám ('0x4d544d45') ('MTME').

  - Egy 4-bájtos verzióazonosító (= 1).

  - Egy 4-bájtos hash-függvény-azonosító (= 1 SHA-1-hez, 2 SHA-256-hoz).

  - Egy tábla 4-bájtos előjel nélküli egészekkel. Az i-edik érték a
    megfelelő pack i-edik objektumának módosítási ideje (mtime),
    lexikografikus (index) sorrendben. Az mtime-ok szabványos
    epoch-másodperceket számolnak.

  - Egy trailer, amely tartalmazza a megfelelő packfile
    ellenőrzőösszegét, valamint a fentiek ellenőrzőösszegét (mindegyik
    a megadott hash-függvénynek megfelelő
    hosszúsággal).

[[_multi_pack_index_midx_files_have_the_following_format]]
== A multi-pack-index (MIDX) fájlok formátuma a következő:

A multi-pack-index fájlok több pack-fájlra és laza objektumra hivatkoznak.

Annak érdekében, hogy olyan bővítményeket engedjünk meg, amelyek extra
adatot adnak a MIDX-hez, a törzset „chunkokra" szervezzük, és egy
keresőtáblát biztosítunk a törzs elején. A fejléc bizonyos hosszértékeket
tartalmaz, például a packek számát, a bázis MIDX-fájlok számát, a
hash-hosszakat és -típusokat.

Minden 4-bájtos szám hálózati sorrendben van.

HEADER:

	4-byte signature:
	    The signature is: {'M', 'I', 'D', 'X'}

	1-byte version number:
	    Git writes the version specified by the "midx.version"
	    configuration option, which defaults to 2. It recognizes
	    both versions 1 and 2.

	1-byte Object Id Version
	    We infer the length of object IDs (OIDs) from this value:
		1 => SHA-1
		2 => SHA-256
	    If the hash type does not match the repository's hash algorithm,
	    the multi-pack-index file should be ignored with a warning
	    presented to the user.

	1-byte number of "chunks"

	1-byte number of base multi-pack-index files:
	    This value is currently always zero.

	4-byte number of pack files

CHUNK LOOKUP:

	(C + 1) * 12 bytes providing the chunk offsets:
	    First 4 bytes describe chunk id. Value 0 is a terminating label.
	    Other 8 bytes provide offset in current file for chunk to start.
	    (Chunks are provided in file-order, so you can infer the length
	    using the next chunk position if necessary.)

	The CHUNK LOOKUP matches the table of contents from
	the chunk-based file format, see linkgit:gitformat-chunk[5].

	The remaining data in the body is described one chunk at a time, and
	these chunks may be given in any order. Chunks are required unless
	otherwise specified.

CHUNK DATA:

	Packfile Names (ID: {'P', 'N', 'A', 'M'})
	    Store the names of packfiles as a sequence of NUL-terminated
	    strings. There is no extra padding between the filenames,
	    and they are listed in lexicographic order. The chunk itself
	    is padded at the end with between 0 and 3 NUL bytes to make the
	    chunk size a multiple of 4 bytes. Version 1 MIDXs are required to
	    list their packs in lexicographic order, but version 2 MIDXs may
	    list their packs in any arbitrary order.

	Bitmapped Packfiles (ID: {'B', 'T', 'M', 'P'})
	    Stores a table of two 4-byte unsigned integers in network order.
	    Each table entry corresponds to a single pack (in the order that
	    they appear above in the `PNAM` chunk). The values for each table
	    entry are as follows:
	    - The first bit position (in pseudo-pack order, see below) to
	      contain an object from that pack.
	    - The number of bits whose objects are selected from that pack.

	OID Fanout (ID: {'O', 'I', 'D', 'F'})
	    The ith entry, F[i], stores the number of OIDs with first
	    byte at most i. Thus F[255] stores the total
	    number of objects.

	OID Lookup (ID: {'O', 'I', 'D', 'L'})
	    The OIDs for all objects in the MIDX are stored in lexicographic
	    order in this chunk.

	Object Offsets (ID: {'O', 'O', 'F', 'F'})
	    Stores two 4-byte values for every object.
	    1: The pack-int-id for the pack storing this object.
	    2: The offset within the pack.
		If all offsets are less than 2^32, then the large offset chunk
		will not exist and offsets are stored as in IDX v1.
		If there is at least one offset value larger than 2^32-1, then
		the large offset chunk must exist, and offsets larger than
		2^31-1 must be stored in it instead. If the large offset chunk
		exists and the 31st bit is on, then removing that bit reveals
		the row in the large offsets containing the 8-byte offset of
		this object.

	[Optional] Object Large Offsets (ID: {'L', 'O', 'F', 'F'})
	    8-byte offsets into large packfiles.

	[Optional] Bitmap pack order (ID: {'R', 'I', 'D', 'X'})
	    A list of MIDX positions (one per object in the MIDX, num_objects in
	    total, each a 4-byte unsigned integer in network byte order), sorted
	    according to their relative bitmap/pseudo-pack positions.

TRAILER:

	Index checksum of the above contents.

[[_multi_pack_index_reverse_indexes]]
== A multi-pack-index reverse indexei

A pack-alapú reverse indexhez hasonlóan a multi-pack index is
használható reverse index generálására.

Ahelyett, hogy offszet, pack és indexpozíció között képezne le, ez a
reverse index egy objektum MIDX-en belüli pozíciója és annak az
objektumnak a MIDX által leírt pszeudo-packen belüli pozíciója között
képez le (azaz a multi-pack reverse index i-edik bejegyzése az i-edik
objektum MIDX-pozícióját tárolja pszeudo-pack sorrendben).

E rendezések közti különbség tisztázásához vegyünk egy multi-pack
elérhetőségi bitmapet (amely még nem létezik, de ez felé haladunk itt).
Minden bitnek egy objektumnak kell megfelelnie a MIDX-ben, ezért egy
hatékony leképezésre van szükségünk a bitpozícióból a MIDX-pozícióba.

Az egyik megoldás az, hogy a bitek ugyanazt a pozíciót foglalják el, mint
a MIDX által tárolt oid-rendezett index. Mivel azonban az oid-ok
gyakorlatilag véletlenszerűek, az ebből eredő elérhetőségi bitmapek nem
rendelkeznének lokalitással, és így rosszul tömörödnének. (Ez az oka
annak, hogy az egypackes bitmapek a pack sorrendjét használják, nem
pedig az .idx sorrendjét, ugyanerre a célra.)

Ezért szeretnénk egy rendezést definiálni a teljes MIDX-re a pack
sorrendje köré építve, amely sokkal jobb lokalitással rendelkezik (és
így hatékonyabban tömörödik). Elképzelhetünk egy pszeudo-packet, amelyet
a MIDX-ben lévő összes pack összefűzésével hozunk létre. Ha például
lenne egy MIDX-ünk három packkel (a, b, c), rendre 10, 15 és 20
objektummal, akkor az objektumok rendezését így képzelhetjük el:

    |a,0|a,1|...|a,9|b,0|b,1|...|b,14|c,0|c,1|...|c,19|

ahol a packek sorrendjét a MIDX pack-listája határozza meg, az egyes
packeken belüli objektumok sorrendje pedig megegyezik a tényleges
packfile-beli sorrenddel.

A packek listája és objektumaik száma alapján naiv módon
rekonstruálható ez a pszeudo-pack sorrend (pl. a 27. pozícióban lévő
objektumnak (c,1)-nek kell lennie, mert az „a" és „b" packek 25 helyet
foglaltak el). De van egy csapda. Az objektumok duplikálódhatnak a
packek között, amely esetben a MIDX csak egy mutatót tárol az
objektumra (és így csak egy helyet szeretnénk a bitmapben).

A hívók maguk is kezelhetnék a duplikátumokat az objektumok
bitpozíció szerinti sorrendben történő olvasásával, de ez az objektumok
számával lineáris, és túl költséges a szokásos bitmap-keresésekhez.
Egy reverse index felépítése megoldja ezt, mivel az az index logikai
inverze, és az index már eltávolította a duplikátumokat. A reverse
index menet közbeni felépítése azonban költséges lehet. Mivel már van
lemezes formátumunk a pack-alapú reverse indexekhez, használjuk fel
azt újra a MIDX pszeudo-packjéhez is.

A MIDX-ből származó objektumok az alábbiak szerint vannak rendezve a
pszeudo-pack összefűzéséhez. Legyen `pack(o)` az a pack, amelyből `o`-t
a MIDX kiválasztotta, és definiáljunk egy rendezést a packek között a
numerikus ID-juk alapján (ahogyan a MIDX tárolja). Legyen `offset(o)`
`o` objektumoffszetje `pack(o)`-n belül. Ekkor hasonlítsuk össze
`o1`-et és `o2`-t a következőképp:

  - Ha `pack(o1)` és `pack(o2)` közül az egyik preferált, a másik
    pedig nem, akkor a preferált kerül előre.
+
(Ez egy olyan részlet, amely lehetővé teszi a MIDX bitmap számára,
hogy meghatározza, melyik packet kell használnia a pack-reuse
mechanizmusnak, mivel megkérdezheti a MIDX-et a 0. bitpozícióban lévő
objektumot tartalmazó packről).

  - Ha `pack(o1) ≠ pack(o2)`, akkor a két objektumot a pack ID szerint
    csökkenő sorrendbe kell rendezni.

  - Egyébként `pack(o1) = pack(o2)`, és az objektumok pack-sorrendben
    vannak rendezve (azaz `o1` pontosan akkor előzi meg `o2`-t, ha
    `offset(o1) < offset(o2)`).

Röviden, egy MIDX pszeudo-packje a MIDX-ben tárolt packekben lévő
objektumok deduplikált összefűzése, pack-sorrendbe rendezve, a packek
pedig MIDX-sorrendben elrendezve (a preferált packkel az élen).

A MIDX reverse indexe az opcionális 'RIDX' chunkban van tárolva, magán
a MIDX-en belül.

[[_btmp_chunk]]
=== `BTMP` chunk

A Bitmapped Packfiles (`BTMP`) chunk további információt kódol a
multi-pack index elérhetőségi bitmapjében szereplő objektumokról.
Emlékeztetőül, a MIDX-ből származó objektumok „pszeudo-pack" sorrendben
vannak elrendezve (lásd fent) az elérhetőségi bitmapek esetében.

A fenti példából kiindulva, tegyük fel, hogy vannak "a", "b" és "c"
packjeink, rendre 10, 15 és 20 objektummal. Pszeudo-pack sorrendben ezek
a következőképp lennének elrendezve:

    |a,0|a,1|...|a,9|b,0|b,1|...|b,14|c,0|c,1|...|c,19|

Egypackes bitmapekkel dolgozva (vagy ezzel egyenértékűen, preferált
packkel rendelkező multi-pack elérhetőségi bitmapekkel), a
linkgit:git-pack-objects[1] ``szó szerinti'' (verbatim) újrafelhasználást
végez, megkísérelve a bitmapelt vagy preferált packfile chunkjainak
újrafelhasználását ahelyett, hogy objektumokat adna a csomagolási
listához.

Amikor egy bájtchunk egy meglévő packből kerül újrafelhasználásra, az
abban található objektumokat nem kell hozzáadni a csomagolási listához,
ami memóriát és CPU-időt takarít meg. Egy meglévő packfile chunkja
azonban csak akkor használható fel újra, ha a következő feltételek
teljesülnek:

  - A chunk csak olyan objektumokat tartalmaz, amelyeket a hívó kért
    (azaz nem tartalmaz olyan objektumot, amelyet a hívó sem explicit,
    sem implicit módon nem kért).

  - A non-thin packekben offszet- vagy referenciadeltaként tárolt
    minden objektum a bázisobjektumát is tartalmazza az eredő packben.

A `BTMP` chunk kódolja a fent leírt, packfile-ok egy halmaza feletti
multi-pack újrafelhasználás megvalósításához szükséges információt.
Pontosabban a `BTMP` chunk három információdarabot kódol (mindegyik
32-bites, hálózati bájtsorrendű, előjel nélküli egész) a MIDX-ben
tárolt minden egyes `p` packfile-hoz, az alábbiak szerint:

`bitmap_pos`:: Az első bitpozíció (pszeudo-pack sorrendben) a multi-pack
  index elérhetőségi bitmapjében, amelyet egy `p`-ből származó objektum
  foglal el.

`bitmap_nr`:: Azon bitpozíciók száma (beleértve a `bitmap_pos`-nál
  lévőt is), amelyek a `p` packből származó objektumokat kódolják.

Például a fenti példának megfelelő `BTMP` chunk (az ``a'', ``b'' és
``c'' packekkel) így nézne ki:

[cols="1,2,2"]
|===
| |`bitmap_pos` |`bitmap_nr`

|packfile ``a''
|`0`
|`10`

|packfile ``b''
|`10`
|`15`

|packfile ``c''
|`25`
|`20`
|===

Ezzel az információval a birtokunkban minden packfile-t egyedileg
újrafelhasználhatóként kezelhetünk, ugyanúgy, ahogyan a `BTMP` chunk
megvalósítása előtt a szó szerinti pack-újrafelhasználást végezték az
egyes packeken.

[[_cruft_packs]]
== cruft packek

A cruft pack funkció alternatívát kínál a Git nem elérhető objektumok
eltávolítására szolgáló hagyományos mechanizmusához képest. Ez a
dokumentum áttekintést nyújt a Git pruning mechanizmusáról, és arról,
hogyan használható helyette egy cruft pack ugyanennek elérésére.

[[_background]]
=== Háttér

A repositoryból nem elérhető objektumok eltávolításához a Git a
`git repack -Ad` parancsot kínálja (lásd linkgit:git-repack[1]). Idézve
a dokumentációból:

----
[...] unreachable objects in a previous pack become loose, unpacked objects,
instead of being left in the old pack. [...] loose unreachable objects will be
pruned according to normal expiry rules with the next 'git gc' invocation.
----

A nem elérhető objektumok nem kerülnek azonnal eltávolításra, mivel ez
versenyhelyzetbe kerülhetne egy beérkező push-sal, amely hivatkozhat egy
törlésre váró objektumra. Ehelyett ezek a nem elérhető objektumok laza
objektumként vannak tárolva, és addig maradnak azok, amíg idősebbek nem
lesznek a lejárati ablaknál, amely ponton a linkgit:git-prune[1] eltávolítja
őket.

A Gitnek lazán kell tárolnia ezeket a nem elérhető objektumokat, hogy nyomon
tudja követni az egyes objektumok mtime-jait. Ha ezeket a nem elérhető
objektumokat egy nagy packbe írnánk, akkor annak a packnek a frissítése
(mert egy benne lévő objektumot újraírtak) vagy egy új, nem elérhető
objektumokból álló pack létrehozása is frissítené a pack mtime-ját, és a
benne lévő objektumok soha nem hagynák el a lejárati ablakot. Ehelyett az
objektumok lazán vannak tárolva, hogy nyomon lehessen követni az egyes
objektumok mtime-jait, és elkerülhető legyen az a helyzet, hogy az összes
cruft objektum egyszerre frissül.

Ez nemkívánatos helyzetekhez vezethet, ha egy repository sok olyan nem
elérhető objektumot tartalmaz, amelyek még nem hagyták el a türelmi
időszakot. A `.git/objects` shardjaiban lévő nagy könyvtárak csökkenthetik
a repository teljesítményét. De elég nagy számú nem elérhető objektum
esetén ez inode-kimerüléshez vezethet, és leronthatja az egész rendszer
teljesítményét. Mivel ezeket az objektumokat soha nem tudjuk becsomagolni,
ezek a repositoryk gyakran nagy mennyiségű lemezterületet foglalnak el,
mivel csak zlib-bel tudjuk tömöríteni őket, de nem tudjuk delta láncokban
tárolni őket.

[[_cruft_packs_2]]
=== Cruft packek

Egy cruft pack megszünteti a nem elérhető objektumok laza állapotban való
tárolásának szükségességét azáltal, hogy az egyes objektumok mtime-jait egy
külön fájlban tárolja, egy összes laza objektumot tartalmazó pack mellett.

Egy cruft packet a `git repack --cruft` ír, egy új pack generálásakor.
Lásd a linkgit:git-pack-objects[1] `--cruft` opcióját. Vegyük észre, hogy
a `git repack --cruft` egy klasszikus, mindent-egybe repack, ami azt
jelenti, hogy az eredő packben minden elérhető, minden más pedig nem
elérhető. Az írás után a `--cruft` opció utasítja a `git repack`-et, hogy
generáljon egy másik packet, amely csak az előző lépésben be nem
csomagolt objektumokat tartalmazza (ami azzal egyenértékű, hogy az összes
nem elérhető objektumot egybecsomagolja). Ez a következőképp zajlik:

  1. Soroljunk fel minden objektumot, megjelölve traverzálási csúcsként
     minden olyan objektumot, amely (a) nincs benne egy megtartott
     packben, és (b) amelynek mtime-ja a türelmi időszakon belül van.

  2. Végezzünk egy elérhetőségi bejárást az előző lépésben összegyűjtött
     csúcsok alapján, útközben minden objektumot hozzáadva a packhez.

  3. Írjuk ki a packet, egy `.mtimes` fájllal együtt, amely rögzíti az
     egyes objektumok időbélyegeit.

Ezt a módot a linkgit:git-repack[1] hívja meg belsőleg, amikor cruft pack
írására kap utasítást. Lényeges, hogy a memóriában tárolt, megtartott
packek halmaza pontosan az a packhalmaz, amelyet a repack nem fog törölni;
más szóval ezek tartalmazzák a repository összes elérhető objektumát.

Ha egy repositorynak már van cruft packje, a `git repack --cruft`
jellemzően csak objektumokat ad hozzá. Ez alól kivétel, ha a
`git repack` megkapja a `--cruft-expiration` opciót, amely lehetővé
teszi, hogy a generált cruft pack kihagyja a lejárt objektumokat ahelyett,
hogy megvárná, amíg a linkgit:git-gc[1] később lejáratja azokat.

Jellemzően a linkgit:git-gc[1] felelős a lejárt, nem elérhető objektumok
eltávolításáért.

[[_alternatives]]
=== Alternatívák

Ennek a tervnek a figyelemre méltó alternatívái közé tartozik:

  - Az egyes objektumokra vonatkozó mtime-adatok helye.

Az mtime-adatok helyét illetően egy új, a packhez kötött segédfájl mellett
döntöttünk, hogy elkerüljük az `.idx` formátum bonyolítását. Ha az `.idx`
formátum valaha is támogatná az opcionális adatchunkokat, érdemes lehet
a `.mtimes` formátumot magába az `.idx`-be konszolidálni.

GIT
---
A linkgit:git[1] csomag része
