gitformat-chunk(5)
==================

NAME
----
gitformat-chunk - Chunk-alapú fájlformátumok

SYNOPSIS
--------

A linkgit:gitformat-commit-graph[5] és a "MIDX" formátum használja (l. a
pack formátum dokumentációját a linkgit:gitformat-pack[5]-ben).

DESCRIPTION
-----------

A Git egyes fájlformátumai a "chunkok" közös fogalmát használják a fájl
szakaszainak leírására. Ez egy nagy fájlhoz strukturált hozzáférést tesz
lehetővé úgy, hogy a maradék adathoz egy kis "tartalomjegyzéket" olvasunk
be. Ezt a közös formátumot a `commit-graph` és a `multi-pack-index` fájlok
használják. Arról, hogy hogyan használják a chunkokat strukturált adat
leírására, l. a `multi-pack-index` formátumot a linkgit:gitformat-pack[5]-ben
és a `commit-graph` formátumot a linkgit:gitformat-commit-graph[5]-ben.

Egy chunk-alapú fájlformátum az adott formátumra jellemző fejléc-információval
kezdődik. Ennek a fejlécnek elegendő információt kell tartalmaznia a
fájltípus, a formátumverzió és a fájlban lévő chunkok számának
azonosításához. Ebből az információból a fájl meg tudja határozni a
chunk-alapú régió kezdetét.

A chunk-alapú régió egy tartalomjegyzékkel kezdődik, amely leírja, hol
kezdődik és végződik az egyes chunkok. Ez (C+1) sorból áll, egyenként 12
bájt, ahol C a chunkok száma. Tekintsük a következő táblázatot:

  | Chunk ID (4 bytes) | Chunk Offset (8 bytes) |
  |--------------------|------------------------|
  | ID[0]              | OFFSET[0]              |
  | ...                | ...                    |
  | ID[C]              | OFFSET[C]              |
  | 0x0000             | OFFSET[C+1]            |

Minden sor egy 4 bájtos chunk-azonosítóból (ID) és egy 8 bájtos eltolásból
áll. Minden egész hálózati bájtsorrendben tárolódik.

Az `ID[i]` chunk-azonosító annak az adatnak a címkéje, amely ebben a
fájlban az `OFFSET[i]`-től (beleértve) az `OFFSET[i+1]`-ig (kizárva)
tárolódik. Így az `i`-edik chunk mérete az `OFFSET[i+1]` és az `OFFSET[i]`
különbségével egyenlő. Ehhez az kell, hogy a chunk adata folytonosan,
a tartalomjegyzékkel megegyező sorrendben jelenjen meg.

A tartalomjegyzék utolsó bejegyzésének négy nulla bájtnak kell lennie. Ez
megerősíti, hogy a tartalomjegyzék véget ér, és megadja a chunk-alapú adat
végének eltolását.

Megjegyzés: a chunk-alapú formátum azt várja el, hogy a fájl _legalább_ egy
záró hash-t tartalmazzon az `OFFSET[C+1]` után.

A chunk-alapú fájlformátumokkal való munkához szükséges függvények a
`chunk-format.h`-ban vannak deklarálva. Ezeknek a metódusoknak a
használata extra ellenőrzéseket biztosít, amelyek segítik a fejlesztőket
új fájlformátumok létrehozásakor.

[[_writing_chunk_based_file_formats]]
Chunk-alapú fájlformátumok írása
--------------------------------

Egy chunk-alapú fájlformátum írásához hozz létre egy `struct chunkfile`-t
az `init_chunkfile()` meghívásával, és adj át egy `struct hashfile`
mutatót. A hívó felelős a `hashfile` megnyitásáért és a fejléc-információ
kiírásáért, hogy a fájlformátum azonosítható legyen, mielőtt a chunk-alapú
formátum kezdődik.

Ezután hívd meg az `add_chunk()`-ot minden kiírásra szánt chunkhoz. Ez
feltölti a `chunkfile`-t az egyes kiírandó chunkok sorrendjéről és
méretéről szóló információval. Adj meg egy `chunk_write_fn` függvénymutatót,
amely kérésre elvégzi a chunk adatának kiírását.

Hívd meg a `write_chunkfile()`-t, hogy a tartalomjegyzék a `hashfile`-ba
íródjon, majd az egyes chunkok. Ez ellenőrzi, hogy minden chunk a várt
mennyiségű adatot írta-e ki, hogy a tartalomjegyzék helyes legyen.

Végül hívd meg a `free_chunkfile()`-t a `struct chunkfile` adatainak
törléséhez. A hívó felelős a `hashfile` véglegesítéséért a záró hash
kiírásával és a fájl bezárásával.

[[_reading_chunk_based_file_formats]]
Chunk-alapú fájlformátumok olvasása
-----------------------------------

Egy chunk-alapú fájlformátum olvasásához a fájlt memóriába leképezett
régióként kell megnyitni. A chunk-format API azt várja el, hogy az egész
fájl folytonos memóriarégióként legyen leképezve.

Inicializálj egy `struct chunkfile` mutatót az `init_chunkfile(NULL)`-lal.

Miután beolvastad a fejléc-információt a fájl elejéről, beleértve a chunkok
számát, hívd meg a `read_table_of_contents()`-ot, hogy feltöltsd a
`struct chunkfile`-t a chunkok listájával, eltolásaikkal és méreteikkel.

Nyerd ki az egyes chunkok adatinformációját a `pair_chunk()` vagy a
`read_chunk()` használatával:

* A `pair_chunk()` egy adott mutatóhoz hozzárendeli a memóriába leképezett
  fájlon belüli, az adott chunk eltolásának megfelelő helyet. Ha a chunk
  nem létezik, a mutató nem módosul.

* A `read_chunk()` egy `chunk_read_fn` függvénymutatót vesz át, és meghívja
  a megfelelő kezdeti mutatóval és méretinformációval. A függvény nem
  hívódik meg, ha a chunk nem létezik. Ezt a metódust akkor használd
  chunkok olvasására, ha azonnali feldolgozásra van szükséged, vagy ha a
  chunk mérete alapján kell logikát végrehajtanod.

Ezeknek a metódusoknak a meghívása után hívd meg a `free_chunkfile()`-t a
`struct chunkfile` adatainak törléséhez. Ez nem zárja be a memóriába
leképezett régiót. A hívóknak birtokolniuk kell azt az adatot addig, amíg a
régióba mutató mutatókra szükség van.

[[_examples]]
Példák
------

Ezek a fájlformátumok a chunk-format API-t használják, és példaként
szolgálhatnak jövőbeli formátumokhoz:

* *commit-graph:* l. a `write_commit_graph_file()`-t és a
  `parse_commit_graph()`-ot a `commit-graph.c`-ben arról, hogyan használják
  a chunk-format API-t a linkgit:gitformat-commit-graph[5]-ben dokumentált
  commit-graph fájlformátum írására és elemzésére.

* *multi-pack-index:* l. a `write_midx_internal()`-t és a
  `load_multi_pack_index()`-et a `midx.c`-ben arról, hogyan használják a
  chunk-format API-t a linkgit:gitformat-pack[5] multi-pack-index
  fájlformátum szakaszában dokumentált multi-pack-index fájlformátum
  írására és elemzésére.

GIT
---
A linkgit:git[1] csomag része
