gitformat-signature(5)
======================

NAME
----
gitformat-signature - Git kriptográfiai aláírásformátumok

SYNOPSIS
--------
[verse]
<[tag|commit] objektumfejléc(ek)>
<vezetéken átvitt protokoll>

DESCRIPTION
-----------

A Git különböző helyeken használ kriptográfiai aláírásokat, jelenleg
objektumokon (tagek, commitok, mergetagek) és tranzakciókon (pushok). Minden
esetben az objektumot vagy tranzakciót létrehozni készülő parancs ebből
meghatároz egy hasznos adatot, meghív egy külső programot, hogy különálló
aláírást szerezzen a hasznos adathoz (PGP-aláírások esetén `gpg -bsa`), és
beágyazza az aláírást az objektumba vagy tranzakcióba.

Az aláírások egy "ASCII Armor" fejlécsorral kezdődnek és egy záró sorral
végződnek, amelyek az aláírás típusától függően (amit a `gpg.format` választ
ki, lásd linkgit:git-config[1]) különböznek. Ezek a `gpg.format` értékeihez:

`gpg` (PGP)::
	`-----BEGIN PGP SIGNATURE-----` és `-----END PGP SIGNATURE-----`.
	Vagy, ha a gpg-t RFC1991-aláírások előállítására utasítják,
	`-----BEGIN PGP MESSAGE-----` és `-----END PGP MESSAGE-----`

`ssh` (SSH)::
	`-----BEGIN SSH SIGNATURE-----` és `-----END SSH SIGNATURE-----`

`x509` (X.509)::
	`-----BEGIN SIGNED MESSAGE-----` és `-----END SIGNED MESSAGE-----`

Az aláírások néha a normál hasznos adat részeként jelennek meg (pl. egy
aláírt tagnél az aláírásblokk az után a hasznos adat után van fűzve,
amelyre az aláírás vonatkozik), néha pedig egy objektumfejléc értékében
jelennek meg (pl. egy aláírt taget merge-elő merge-commit a teljes
tagtartalmat a "mergetag" fejlécén tárolja).  Ez utóbbi esetben az
objektumfejlécek szokásos többsoros formázási szabálya érvényes.  Azaz a
második és az azt követő sorok elé egy SP kerül annak jelzésére, hogy a sor
az előző sor folytatása.

Ez még egy eredetileg üres sorra is igaz.  A következő példákban a
whitespace-karakterrel végződő sorok végét egy `$` jel emeli ki; ha kézzel
próbálod újraalkotni ezeket a példákat, ne másold ki és illeszd be
őket--elsősorban azért vannak ott, hogy kiemeljék a néhány sor végén lévő
extra whitespace-t.

Az aláírt hasznos adat és az aláírás beágyazásának módja az objektum,
illetve a tranzakció típusától függ.

[[_tag_signatures]]
== Tag-aláírások

- létrehozza: `git tag -s`
- hasznos adat: annotált tag-objektum
- beágyazás: az aláírás hozzáfűzése az aláíratlan tag-objektumhoz
- példa: `signedtag` tag `signed tag` tárgysorral

----
object 04b871796dc0420f8e7561a895b52484b701d51a
type commit
tag signedtag
tagger C O Mitter <committer@example.com> 1465981006 +0000

signed tag

signed tag message body
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAABAgAGBQJXYRhOAAoJEGEJLoW3InGJklkIAIcnhL7RwEb/+QeX9enkXhxn
rxfdqrvWd1K80sl2TOt8Bg/NYwrUBw/RWJ+sg/hhHp4WtvE1HDGHlkEz3y11Lkuh
8tSxS3qKTxXUGozyPGuE90sJfExhZlW4knIQ1wt/yWqM+33E9pN4hzPqLwyrdods
q8FWEqPPUbSJXoMbRPw04S5jrLtZSsUWbRYjmJCHzlhSfFWW4eFd37uquIaLUBS0
rkC3Jrx7420jkIpgFcTI2s60uhSQLzgcCwdA2ukSYIRnjg/zDkj8+3h/GaROJ72x
lZyI6HWixKJkWw8lE9aAOD9TmTW9sFJwcVAzmAuFX2kUreDUKMZduGcoRYGpD7E=
=jpXa
-----END PGP SIGNATURE-----
----

- ellenőrzés: `git verify-tag [-v]` vagy `git tag -v`

----
gpg: Signature made Wed Jun 15 10:56:46 2016 CEST using RSA key ID B7227189
gpg: Good signature from "Eris Discordia <discord@example.net>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: D4BE 2231 1AD3 131E 5EDA  29A4 6109 2E85 B722 7189
object 04b871796dc0420f8e7561a895b52484b701d51a
type commit
tag signedtag
tagger C O Mitter <committer@example.com> 1465981006 +0000

signed tag

signed tag message body
----

[[_commit_signatures]]
== Commit-aláírások

- létrehozza: `git commit -S`
- hasznos adat: commit-objektum
- beágyazás: `gpgsig` fejlécbejegyzés
  (a tartalmat egy szóköz előzi meg)
- példa: commit `signed commit` tárgysorral

----
tree eebfed94e75e7760540d1485c740902590a00332
parent 04b871796dc0420f8e7561a895b52484b701d51a
author A U Thor <author@example.com> 1465981137 +0000
committer C O Mitter <committer@example.com> 1465981137 +0000
gpgsig -----BEGIN PGP SIGNATURE-----
 Version: GnuPG v1
 $
 iQEcBAABAgAGBQJXYRjRAAoJEGEJLoW3InGJ3IwIAIY4SA6GxY3BjL60YyvsJPh/
 HRCJwH+w7wt3Yc/9/bW2F+gF72kdHOOs2jfv+OZhq0q4OAN6fvVSczISY/82LpS7
 DVdMQj2/YcHDT4xrDNBnXnviDO9G7am/9OE77kEbXrp7QPxvhjkicHNwy2rEflAA
 zn075rtEERDHr8nRYiDh8eVrefSO7D+bdQ7gv+7GsYMsd2auJWi1dHOSfTr9HIF4
 HJhWXT9d2f8W+diRYXGh4X0wYiGg6na/soXc+vdtDYBzIxanRqjg8jCAeo1eOTk1
 EdTwhcTZlI0x5pvJ3H0+4hA2jtldVtmPM4OTB0cTrEWBad7XV6YgiyuII73Ve3I=
 =jKHM
 -----END PGP SIGNATURE-----

signed commit

signed commit message body
----

- ellenőrzés: `git verify-commit [-v]` (vagy `git show --show-signature`)

----
gpg: Signature made Wed Jun 15 10:58:57 2016 CEST using RSA key ID B7227189
gpg: Good signature from "Eris Discordia <discord@example.net>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: D4BE 2231 1AD3 131E 5EDA  29A4 6109 2E85 B722 7189
tree eebfed94e75e7760540d1485c740902590a00332
parent 04b871796dc0420f8e7561a895b52484b701d51a
author A U Thor <author@example.com> 1465981137 +0000
committer C O Mitter <committer@example.com> 1465981137 +0000

signed commit

signed commit message body
----

[[_mergetag_signatures]]
== Mergetag-aláírások

- létrehozza: `git merge` aláírt tagen
- hasznos adat/beágyazás: a teljes aláírt tag-objektum a (merge-)commit
  objektumba van beágyazva `mergetag` fejlécbejegyzésként
- példa: a fenti `signedtag` aláírt tag merge-elése

----
tree c7b1cff039a93f3600a1d18b82d26688668c7dea
parent c33429be94b5f2d3ee9b0adad223f877f174b05d
parent 04b871796dc0420f8e7561a895b52484b701d51a
author A U Thor <author@example.com> 1465982009 +0000
committer C O Mitter <committer@example.com> 1465982009 +0000
mergetag object 04b871796dc0420f8e7561a895b52484b701d51a
 type commit
 tag signedtag
 tagger C O Mitter <committer@example.com> 1465981006 +0000
 $
 signed tag
 $
 signed tag message body
 -----BEGIN PGP SIGNATURE-----
 Version: GnuPG v1
 $
 iQEcBAABAgAGBQJXYRhOAAoJEGEJLoW3InGJklkIAIcnhL7RwEb/+QeX9enkXhxn
 rxfdqrvWd1K80sl2TOt8Bg/NYwrUBw/RWJ+sg/hhHp4WtvE1HDGHlkEz3y11Lkuh
 8tSxS3qKTxXUGozyPGuE90sJfExhZlW4knIQ1wt/yWqM+33E9pN4hzPqLwyrdods
 q8FWEqPPUbSJXoMbRPw04S5jrLtZSsUWbRYjmJCHzlhSfFWW4eFd37uquIaLUBS0
 rkC3Jrx7420jkIpgFcTI2s60uhSQLzgcCwdA2ukSYIRnjg/zDkj8+3h/GaROJ72x
 lZyI6HWixKJkWw8lE9aAOD9TmTW9sFJwcVAzmAuFX2kUreDUKMZduGcoRYGpD7E=
 =jpXa
 -----END PGP SIGNATURE-----

Merge tag 'signedtag' into downstream

signed tag

signed tag message body

# gpg: Signature made Wed Jun 15 08:56:46 2016 UTC using RSA key ID B7227189
# gpg: Good signature from "Eris Discordia <discord@example.net>"
# gpg: WARNING: This key is not certified with a trusted signature!
# gpg:          There is no indication that the signature belongs to the owner.
# Primary key fingerprint: D4BE 2231 1AD3 131E 5EDA  29A4 6109 2E85 B722 7189
----

- ellenőrzés: az ellenőrzés alapértelmezés szerint be van ágyazva a
  merge-commit üzenetébe, alternatívaként `git show --show-signature`:

----
commit 9863f0c76ff78712b6800e199a46aa56afbcbd49
merged tag 'signedtag'
gpg: Signature made Wed Jun 15 10:56:46 2016 CEST using RSA key ID B7227189
gpg: Good signature from "Eris Discordia <discord@example.net>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: D4BE 2231 1AD3 131E 5EDA  29A4 6109 2E85 B722 7189
Merge: c33429b 04b8717
Author: A U Thor <author@example.com>
Date:   Wed Jun 15 09:13:29 2016 +0000

    Merge tag 'signedtag' into downstream

    signed tag

    signed tag message body

    # gpg: Signature made Wed Jun 15 08:56:46 2016 UTC using RSA key ID B7227189
    # gpg: Good signature from "Eris Discordia <discord@example.net>"
    # gpg: WARNING: This key is not certified with a trusted signature!
    # gpg:          There is no indication that the signature belongs to the owner.
    # Primary key fingerprint: D4BE 2231 1AD3 131E 5EDA  29A4 6109 2E85 B722 7189
----

GIT
---
A linkgit:git[1] csomag része
