gitfaq(7)
=========

NAME
----
gitfaq - Frequently asked questions about using Git

SYNOPSIS
--------
gitfaq

DESCRIPTION
-----------

Az ebben a FAQ-ban szereplő példák egy szabványos POSIX shellt feltételeznek, mint a
`bash` vagy a `dash`, és egy A U Thor nevű felhasználót, akinek az `author`
fiókja van a `git.example.org` hosting-szolgáltatónál.

[[_configuration]]
Konfiguráció
------------

[[user-name]]
Mit írjak a `user.name`-be?::
	A saját nevedet kell beírnod, általában egy keresztnevet
	és vezetéknevet használó formában.  Például a Git jelenlegi maintainere a "Junio
	C Hamano" nevet használja.  Ez lesz az a névrész, amely minden általad készített
	commitban tárolva lesz.
+
Ez a konfiguráció semmilyen hatással nincs a remote szolgáltatásokhoz való hitelesítésre;
ehhez lásd a `credential.username`-et a linkgit:git-config[1] oldalon.

[[http-postbuffer]]
Mit csinál valójában a `http.postBuffer`?::
	Ez az opció megváltoztatja annak a puffernek a méretét, amelyet a Git akkor használ,
	amikor adatokat pushol egy remote-ra HTTP-n vagy HTTPS-en keresztül.  Ha az
	adat nagyobb ennél a méretnél, a libcurl, amely a Git HTTP-támogatását kezeli,
	chunked transfer encoding-ot fog használni, mivel előre nem ismert, mekkora
	lesz a pusholt adat mérete.
+
Ezt az értéket az alapértelmezett méreten hagyni rendben van, hacsak nem tudod, hogy vagy a
remote szerver, vagy egy köztes proxy nem támogatja a HTTP/1.1-et (amely
bevezette a chunked transfer encoding-ot), vagy ismerten hibásan működik chunked
adatokkal.  Ezt gyakran (tévesen) javasolják általános push-
problémák megoldásaként, de mivel szinte minden szerver és proxy legalább a HTTP/1.1-et támogatja,
ennek az értéknek a növelése általában nem oldja meg a legtöbb push-problémát.  Egy szerver vagy proxy,
amely nem támogatná helyesen a HTTP/1.1-et és a chunked transfer encoding-ot, nem lenne
túl hasznos a mai Interneten, mivel rengeteg forgalmat törne el.
+
Vedd figyelembe, hogy ennek az értéknek a növelése növeli a memóriahasználatot minden releváns
push esetén, amelyet a Git HTTP-n vagy HTTPS-en keresztül végez, mivel a teljes puffer
lefoglalásra kerül, függetlenül attól, hogy az egészet felhasználják-e.  Ezért
a legjobb az alapértéken hagyni, hacsak nem vagy biztos benne, hogy más értékre van szükséged.

[[configure-editor]]
Hogyan állítsak be másik szerkesztőt?::
	Ha nem adtál meg kifejezetten egy szerkesztőt a Gitnek, az alapból
	a `VISUAL` vagy `EDITOR` környezeti változókkal beállított szerkesztőt fogja
	használni, vagy ha egyik sincs megadva, a rendszer alapértelmezettjét (amely általában
	a `vi`).  Mivel egyeseknek a `vi` nehezen használható, vagy más
	szerkesztőt preferálnak, kívánatos lehet megváltoztatni a használt szerkesztőt.
+
Ha egy általános szerkesztőt szeretnél beállítani a legtöbb, szerkesztőt igénylő
programhoz, szerkesztheted a shell-konfigurációdat (pl. `~/.bashrc` vagy `~/.zshenv`),
hogy tartalmazzon egy sort, amely az `EDITOR` vagy `VISUAL` környezeti változót egy megfelelő
értékre állítja.  Például ha a `nano` szerkesztőt preferálod, a
következőt írhatod:
+
----
export VISUAL=nano
----
+
Ha kifejezetten egy szerkesztőt szeretnél beállítani a Githez, beállíthatod a
`core.editor` konfigurációs értéket, vagy a `GIT_EDITOR` környezeti változót.  A
linkgit:git-var[1] oldalon megnézheted a részleteket arról, milyen sorrendben veszi figyelembe
ezeket az opciókat.
+
Vedd figyelembe, hogy minden esetben a szerkesztő értéke át lesz adva a shellnek, így
minden szóközt tartalmazó argumentumot megfelelően idézőjelbe kell tenni.  Emellett, ha
a szerkesztőd meghíváskor normál esetben leválik a terminálról, meg kell
adnod egy olyan argumentummal, amely megakadályozza ezt, különben a Git nem fog látni semmilyen
változtatást.  Egy példa a Windows-on mindkét problémát kezelő
konfigurációra a `"C:\Program Files\Vim\gvim.exe" --nofork`,
amely idézőjelbe teszi a szóközt tartalmazó fájlnevet, és megadja a `--nofork` opciót, hogy
elkerülje a folyamat háttérbe kerülését.

[[sign-off]]
Miért nincs `commit.signoff` és más hasonló konfigurációs változó?::
	A Git szándékosan nem biztosít (és nem is fog biztosítani)
	olyan konfigurációs változót, mint a `commit.signoff`, amely
	alapból automatikusan hozzáadná a `--signoff`-ot.  Ennek az az oka, hogy
	megvédje egy sign-off jogi és szándékos jelentőségét.
	Ha lennének automatizáltabb és széles körben ismert módok a
	sign-offok hozzáfűzésére, könnyebbé válna később valakinek amellett
	érvelni, hogy egy "Signed-off-by" trailer csak
	megszokásból vagy automatizálás miatt lett hozzáadva, a committer teljes
	tudatossága vagy szándéka nélkül, hogy igazolja egyetértését a
	Developer Certificate of Origin-nal (DCO) vagy egy hasonló nyilatkozattal.
	Ez alááshatja a sign-off hitelességét jogi vagy
	szerződéses helyzetekben.
+
Létezik a `format.signoff`, de ez egy történelmi hiba, és
nem indok arra, hogy még több hasonló hibát adjunk hozzá.


[[_credentials]]
Hitelesítő adatok
-----------------

[[http-credentials]]
Hogyan adjam meg a hitelesítő adataimat pusholáskor HTTP-n keresztül?::
	A legegyszerűbb módja ennek egy credential helper használata a
	`credential.helper` konfiguráción keresztül.  A legtöbb rendszer biztosít egy szabványos
	lehetőséget a rendszer credential-kezelőjével való integrációra.  Például
	a Git for Windows biztosítja a `wincred` credential-kezelőt, a macOS-nek van az
	`osxkeychain` credential-kezelője, és a szabványos
	asztali környezettel rendelkező Unix-rendszerek használhatják a `libsecret` credential-kezelőt.  Mindegyik
	titkosított tárolóban tárolja a hitelesítő adatokat, hogy biztonságban tartsa a jelszavaidat vagy
	tokenjeidet.
+
Emellett használhatod a `store` credential-kezelőt, amely egy fájlba tárol
a home könyvtáradban, vagy a `cache` credential-kezelőt, amely nem
tárolja tartósan a hitelesítő adataidat, de megakadályozza, hogy egy bizonyos ideig rákérdezzenek
rájuk.
+
Egyszerűen be is írhatod a jelszavadat, amikor rákérdeznek.  Bár lehetséges
a jelszót (amelyet százalék-kódolni kell) az URL-ben elhelyezni, ez nem
különösebben biztonságos, és a hitelesítő adatok véletlen kiszivárgásához vezethet, ezért
nem ajánlott.

[[http-credentials-environment]]
Hogyan olvassak be egy jelszót vagy tokent egy környezeti változóból?::
	A `credential.helper` konfigurációs opció egy tetszőleges
	shell-parancsot is elfogadhat, amely a credential-protokollt állítja elő a standard kimeneten.
	Ez hasznos például akkor, amikor hitelesítő adatokat adunk át egy konténerbe.
+
Egy ilyen shell-parancs megadható úgy, hogy az opció értékét felkiáltójellel
kezdjük.  Ha a jelszavad vagy tokened a `GIT_TOKEN`-ben lenne tárolva,
a következő paranccsal állíthatnád be a credential helperedet:
+
----
$ git config credential.helper \
	'!f() { echo username=author; echo "password=$GIT_TOKEN"; };f'
----

[[http-reset-credentials]]
Hogyan változtassam meg a credential-kezelőmben elmentett jelszót vagy tokent?::
	Általában, ha a jelszó vagy token érvénytelen, a Git törli, és
	újat kér.  Azonban vannak esetek, amikor ez nem mindig
	történik meg.  A jelszó vagy token megváltoztatásához törölheted a meglévő
	hitelesítő adatokat, és a Git ekkor újakat fog kérni.  A hitelesítő
	adatok törléséhez használj egy olyan szintaxist, mint a következő (behelyettesítve a felhasználóneved
	és a hosztnevet):
+
----
$ echo url=https://author@git.example.org | git credential reject
----

[[multiple-accounts-http]]
Hogyan használjak több fiókot ugyanannál a hosting-szolgáltatónál HTTP-vel?::
	Ezeknek a fiókoknak a megkülönböztetésére általában a legegyszerűbb módja
	a felhasználónév használata az URL-ben.  Például ha az `author`
	és `committer` fiókokkal rendelkezel a `git.example.org`-on, használhatod a
	https://author@git.example.org/org1/project1.git és a
	https://committer@git.example.org/org2/project2.git URL-eket.  Így amikor
	egy credential helpert használsz, az automatikusan megpróbálja majd megkeresni a
	fiókodhoz tartozó helyes hitelesítő adatokat.  Ha már be van
	állítva egy remote, megváltoztathatod az URL-t valami ilyesmivel: `git remote set-url
	origin https://author@git.example.org/org1/project1.git` (a
	részletekért lásd linkgit:git-remote[1]).

[[multiple-accounts-ssh]]
Hogyan használjak több fiókot ugyanannál a hosting-szolgáltatónál SSH-val?::
	A legtöbb SSH-t támogató hosting-szolgáltatónál egyetlen kulcspár egyedileg
	azonosít egy felhasználót.  Ezért több fiók használatához szükséges
	egy kulcspárt létrehozni minden fiókhoz.  Ha egy ésszerűen
	modern OpenSSH-verziót használsz, létrehozhatsz egy új kulcspárt valami ilyesmivel:
	`ssh-keygen -t ed25519 -f ~/.ssh/id_committer`.  Ezután
	regisztrálhatod a nyilvános kulcsot (ebben az esetben a `~/.ssh/id_committer.pub`-ot; figyelj
	a `.pub`-ra) a hosting-szolgáltatónál.
+
A legtöbb hosting-szolgáltató egyetlen SSH-fiókot használ pusholáshoz; azaz minden felhasználó
a `git` fiókba pushol (pl. `git@git.example.org`).  Ha ez a helyzet
a te szolgáltatódnál, beállíthatsz több aliast az SSH-ban, hogy egyértelmű legyen, melyik kulcs-
párt kell használni.  Például valami ilyesmit írhatsz a
`~/.ssh/config`-ba, behelyettesítve a megfelelő privát kulcsfájlt:
+
----
# This is the account for author on git.example.org.
Host example_author
	HostName git.example.org
	User git
	# This is the key pair registered for author with git.example.org.
	IdentityFile ~/.ssh/id_author
	IdentitiesOnly yes
# This is the account for committer on git.example.org.
Host example_committer
	HostName git.example.org
	User git
	# This is the key pair registered for committer with git.example.org.
	IdentityFile ~/.ssh/id_committer
	IdentitiesOnly yes
----
+
Ezután módosíthatod a push URL-edet, hogy `git@example_author`-t vagy
`git@example_committer`-t használjon `git@example.org` helyett (pl. `git remote set-url
git@example_author:org1/project1.git`).

[[_transfers]]
Átvitelek
---------

[[sync-working-tree]]
Hogyan szinkronizáljak egy working tree-t rendszerek között?::
	Először is döntsd el, hogy egyáltalán ezt akarod-e tenni.  A Git akkor
	működik legjobban, ha a tipikus `git push` és `git fetch` parancsokkal pusholod
	vagy pullolod a munkádat, és nem arra tervezték, hogy egy working tree-t rendszerek között megosszunk.  Ez
	potenciálisan kockázatos, és bizonyos esetekben repository-sérülést vagy adat-
	vesztést okozhat.
+
Ha ezt tesszük, az általában azt eredményezi, hogy a `git status`-nak újra be kell olvasnia a
working tree minden fájlját.  Emellett a Git biztonsági modellje nem engedélyezi
egy working tree megosztását nem megbízható felhasználók között, így egy working tree szinkronizálása
csak akkor biztonságos, ha azt az összes gépen csak egyetlen felhasználó fogja használni.
+
Fontos, hogy ne használj felhőalapú szinkronizáló szolgáltatást egy Git
repository bármely részének szinkronizálásához, mivel ez sérülést okozhat, mint hiányzó objektumok, megváltozott
vagy hozzáadott fájlok, törött refek, és számos más probléma.  Ezek a
szolgáltatások jellemzően fájlonként, folyamatosan szinkronizálnak, és nem értik
egy Git repository felépítését.  Ez különösen rossz, ha a
repository-t annak frissítése közben szinkronizálják, mivel ez nagy valószínűséggel
hiányos vagy részleges frissítéseket, és ezáltal adatvesztést okoz.
+
Egy példa az előforduló sérülés típusára a refek állapota
körüli konfliktus, amely miatt mindkét oldal olyan különböző commitokkal végzi egy branchen,
amelyekkel a másik nem rendelkezik.  Ez azt eredményezheti, hogy fontos objektumok
hivatkozás nélkül maradnak, és esetleg a `git gc` prune-olja őket, ami adatvesztést okoz.
+
Ezért jobb, ha a munkádat a normál push és pull mechanizmussal pusholod a másik
rendszerre vagy egy központi szerverre.  A Git 2.51-ben a Git
megtanult stash-eket importálni és exportálni, így lehetséges a working tree
állapotát szinkronizálni azzal, hogy elstasheled a `git stash`-sel, majd exportálod vagy az
összes stash-t a `git stash export --to-ref refs/heads/stashes` paranccsal (feltéve, hogy
a `stashes` branchre szeretnél exportálni), vagy a stash-eket a számuk hozzáadásával
választod ki a parancs végéhez.  A nem követett fájlokat is belefoglalhatod
a `--include-untracked` argumentum használatával az adatok elstashelésekor, de vigyázz, hogy
ezt ne tedd, ha bármelyikük érzékeny
információt tartalmaz.
+
Ezután pusholhatod a `stashes` branchet (vagy amelyik branchre exportáltál),
fetchelheted őket a helyi rendszerre (pl. `git fetch origin
+stashes:stashes` paranccsal), és importálhatod a stash-eket a másik rendszeren a `git stash
import stashes` paranccsal (ismét, szükség szerint megváltoztatva a nevet).  A változtatások alkalmazása
a working tree-re elvégezhető a `git stash pop` vagy `git stash apply` paranccsal.
Ez a legrobusztusabb és a nem szándékolt problémák elkerülésére
legvalószínűbb megközelítés.
+
Ennek ellenére vannak esetek, amikor az emberek mégis inkább
egy working tree-t osztanak meg rendszerek között.  Ha ezt teszed, az ajánlott megközelítés
az `rsync -a --delete-after` használata (ideális esetben titkosított kapcsolattal, mint
pl. az `ssh`) a repository gyökerén.  Néhány dolgot biztosítanod kell,
amikor ezt teszed:
+
* Ha vannak további worktree-id vagy egy külön Git-könyvtárad, azokat
  ugyanakkor kell szinkronizálni, mint a fő working tree-t és repository-t.
* El tudod fogadni, hogy a célkönyvtár a forráskönyvtár pontos másolata lesz,
  _törölve minden ott már meglévő adatot_.
* A repository (beleértve az összes worktree-t és a Git-könyvtárat) nyugalmi
  állapotban van az átvitel teljes időtartama alatt (azaz semmilyen művelet nem zajlik
  rajta, beleértve a háttérműveleteket, mint a `git
  gc`, és a szerkesztőd által indított műveleteket).
+
Vedd figyelembe, hogy még ezekkel az ajánlásokkal is van némi kockázata a
working tree-k ily módon való szinkronizálásának, mivel ez megkerüli a Git normál
integritás-ellenőrzését a repository-khoz, ezért javasolt biztonsági mentéseket készíteni.  Szinkronizálás
után érdemes lehet egy `git fsck`-ot is futtatni, hogy ellenőrizd az adataid integritását a célrendszeren.

[[_common_issues]]
Gyakori problémák
-----------------

[[last-commit-amend]]
Hibáztam az utolsó commitban.  Hogyan javítsam ki?::
	Elvégezheted a megfelelő módosítást a working tree-den, futtathatod a `git add
	<file>` vagy a `git rm <file>` parancsot, ahogy szükséges, hogy stage-eld, majd a `git
	commit --amend`-et.  A módosításod bekerül a commitba, és újra
	fel leszel kérve, hogy szerkeszd a commit-üzenetet; ha az eredeti
	üzenetet szó szerint szeretnéd használni, használhatod a `--no-edit` opciót a `git
	commit`-hoz, vagy egyszerűen mentsd el és lépj ki, amikor a szerkesztőd megnyílik.

[[undo-previous-change]]
Egy hibás módosítást csináltam, és az bekerült a fő branchbe.  Hogyan vonjam vissza?::
	Ezzel a szokásos módon a `git revert` használatával foglalkozunk.  Ez megőrzi
	a történetet, hogy az eredeti módosítás megtörtént, és értékes
	hozzájárulás volt, de emellett bevezet egy új commitot, amely visszavonja azokat a változtatásokat,
	mert az eredetinek problémája volt.  A revert commit-üzenete
	jelzi a visszavont commitot, és általában szerkesztik, hogy tartalmazzon
	egy magyarázatot arra, miért történt a revert.

[[ignore-tracked-files]]
Hogyan hagyjam figyelmen kívül egy követett fájl változtatásait?::
	A Git nem biztosít erre módot.  Ennek az az oka, hogy ha a Gitnek
	felül kell írnia ezt a fájlt, például egy checkout során, nem tudja,
	hogy a fájl változtatásai értékesek-e, és meg kell-e őrizni őket, vagy
	jelentéktelenek, és biztonságosan megsemmisíthetők.  Ezért a
	biztonságos utat kell választania, és mindig meg kell őriznie őket.
+
Csábító megpróbálni a `git update-index` bizonyos funkcióit használni, nevezetesen az
assume-unchanged és skip-worktree biteket, de ezek nem működnek megfelelően erre a
célra, és nem szabadna ilyen módon használni őket.
+
Ha a célod egy konfigurációs fájl módosítása, gyakran hasznos lehet, ha van
egy a repository-ba bevett fájl, amely egy sablon vagy alapértékek halmaza, amelyet
aztán a mellé lehet másolni és szükség szerint módosítani.  Ezt a második, módosított
fájlt általában figyelmen kívül hagyják, hogy megelőzzék a véletlen commitolását.

[[files-in-gitignore-are-tracked]]
Megkértem a Gitet, hogy hagyjon figyelmen kívül bizonyos fájlokat, mégis követve vannak::
	Egy `gitignore` fájl biztosítja, hogy bizonyos, a Git által nem
	követett fájl(ok) nem követettek maradjanak.  Azonban néha bizonyos
	fájl(ok) már követve voltak, mielőtt bekerültek volna a
	`.gitignore`-ba, ezért továbbra is követettek maradnak.  A fájlok/minták nem-követetté
	tételéhez és figyelmen kívül hagyásához használd a `git rm --cached <file/pattern>` parancsot
	és adj hozzá egy, a <file>-ra illeszkedő mintát a `.gitignore`-hoz.
	A részletekért lásd a linkgit:gitignore[5] oldalt.

[[fetching-and-pulling]]
Honnan tudom, hogy fetchelni vagy pullolni szeretnék-e?::
	Egy fetch eltárolja a remote
	repository legújabb változtatásainak egy másolatát, anélkül hogy módosítaná a working tree-t vagy az aktuális branchet.
	Ezután kényelmesen megvizsgálhatod, merge-elheted, rebase-elheted rá, vagy
	figyelmen kívül hagyhatod az upstream változtatásokat.  Egy pull egy fetchből áll, amelyet azonnal
	egy merge vagy rebase követ.  Lásd linkgit:git-pull[1].

[[proxy]]
Használhatok proxyt a Gittel?::
	Igen, a Git támogatja a proxyk használatát.  A Git figyelembe veszi a Unixon
	gyakran használt szabványos `http_proxy`, `https_proxy` és `no_proxy` környezeti
	változókat, és emellett a `http.proxy`-val és hasonló opciókkal is konfigurálható HTTPS-hez (lásd
	linkgit:git-config[1]).  A `http.proxy` és a kapcsolódó opciók
	URL-mintánkénti alapon testreszabhatók.  Emellett a Git elméletileg
	normálisan tud működni a hálózaton lévő átlátszó proxykkal is.
+
SSH esetén a Git támogathat egy proxyt az OpenSSH `ProxyCommand`-jának használatával. Gyakran használt
eszközök a `netcat` és a `socat`.  Azonban ezeket úgy kell konfigurálni, hogy ne
lépjenek ki, amikor EOF-ot látnak a standard bemeneten, ami általában azt jelenti, hogy a `netcat`-nek
`-q`-ra, a `socat`-nak pedig egy időtúllépésre lesz szüksége, valami ilyesmivel: `-t 10`.
Ez azért szükséges, mert a Git SSH-szervere úgy tudja meg, hogy nem érkezik több kérés,
hogy EOF-ot lát a standard bemeneten, de amikor ez megtörténik, a szerver esetleg
még nem dolgozta fel az utolsó kérést, így a kapcsolat ezen a
ponton való elejtése megszakítaná azt a kérést.
+
Egy példa konfigurációs bejegyzésre a `~/.ssh/config`-ban egy HTTP proxyval valahogy
így nézhet ki:
+
----
Host git.example.org
    User git
    ProxyCommand socat -t 10 - PROXY:proxy.example.org:%h:%p,proxyport=8080
----
+
Vedd figyelembe, hogy minden esetben, ahhoz hogy a Git megfelelően működjön, a proxynak
teljesen átlátszónak kell lennie.  A proxy semmilyen módon nem módosíthatja, nem babrálhat,
és nem pufferelheti a kapcsolatot, különben a Git szinte biztosan nem fog működni.  Vedd figyelembe, hogy sok proxy,
beleértve sok TLS middleboxot, a Windows Defendertől és a
Windows Firewalltól eltérő Windows-os vírusirtó és tűzfalprogramokat, valamint szűrő
proxykat, nem felel meg ennek a szabványnak, és ennek eredményeként elrontja a Gitet.  A
problémákról szóló számos jelentés és rossz biztonsági előéletük miatt nem
javasoljuk ezeknek a szoftver- és eszközkategóriáknak a használatát.

[[_merging_and_rebasing]]
Merge-elés és rebase-elés
-------------------------

[[long-running-squash-merge]]
Milyen problémák fordulhatnak elő, amikor hosszú életű brancheket squash merge-ekkel merge-elünk?::
	Általában különböző problémák fordulhatnak elő, amikor squash
	merge-eket használunk két branch többszöri merge-eléséhez.  Ezek közé tartozhat extra
	commitok megjelenése a `git log` kimenetében, egy GUI-ban, vagy amikor a `...` jelölést
	használjuk egy tartomány kifejezésére, valamint az a lehetőség, hogy újra és újra fel
	kell oldani a konfliktusokat.
+
Amikor a Git egy normál merge-et végez két branch között, pontosan három
pontot vesz figyelembe: a két branchet és egy harmadik commitot, amelyet _merge-alapnak_ neveznek, amely
általában a commitok közös őse.  A merge eredménye a
merge-alap és mindegyik head közötti változtatások összege.  Amikor két
branchet egy szokásos merge-committal merge-elsz, ez egy új commitot eredményez, amely a
következő merge-eléskor merge-alapként fog szolgálni, mert most már van egy új
közös ős.  A Gitnek nem kell figyelembe vennie a
merge-alap előtt bekövetkezett változtatásokat, így nem kell újra feloldanod semmilyen korábban feloldott konfliktust.
+
Amikor egy squash merge-et hajtasz végre, nem jön létre merge-commit; ehelyett a
változtatások az egyik oldalról egy szokásos commitként kerülnek alkalmazásra a másik oldalra.  Ez
azt jelenti, hogy ezeknek a brancheknek a merge-alapja nem fog megváltozni, így amikor a Git
a következő merge-elését végzi, figyelembe veszi az összes olyan változtatást, amelyet
legutóbb figyelembe vett, plusz az új változtatásokat.  Ez azt jelenti, hogy bármely konfliktust esetleg
újra fel kell oldani.  Hasonlóképpen, bármi, ami a `...` jelölést használja a `git
diff`-ben, `git log`-ban vagy egy GUI-ban, az eredeti merge-alap óta bekövetkezett
összes változtatást fogja mutatni.
+
Ennek következtében, ha két hosszú életű branchet ismételten szeretnél merge-elni,
a legjobb mindig egy szokásos merge-commitot használni.

[[merge-two-revert-one]]
Ha egy változtatást teszek két branchen, de az egyiken visszavonom, miért tartalmazza ezeknek a brancheknek a merge-elése a változtatást?::
	Alapból, amikor a Git egy merge-et végez, egy `ort`
	nevű stratégiát használ, amely egy kifinomult háromutas merge-et végez.  Ebben az
	esetben, amikor a Git elvégzi a merge-et, pontosan három pontot vesz figyelembe: a két headet és egy
	harmadik pontot, amelyet _merge-alapnak_ neveznek, amely általában ezeknek a commitoknak a
	közös őse.  A Git egyáltalán nem veszi figyelembe a történetet vagy az ezeken a brancheken
	bekövetkezett egyedi commitokat.
+
Ennek eredményeként, ha mindkét oldalon van egy változtatás, és az egyik oldal visszavonta azt a
változtatást, az eredmény a változtatás belefoglalása lesz.  Ez azért van, mert a kód megváltozott
az egyik oldalon, míg a másikon nincs nettó változás, és ebben a
forgatókönyvben a Git a változtatást fogadja el.
+
Ha ez problémát jelent számodra, ehelyett rebase-elhetsz, a visszavonást tartalmazó branchet
a másik branchre rebase-elve.  Egy rebase ebben a forgatókönyvben vissza fogja vonni
a változtatást, mert a rebase minden egyedi commitot alkalmaz, beleértve a
visszavonást is.  Vedd figyelembe, hogy a rebase-ek átírják a történetet, ezért kerülnöd kell a
publikált branchek rebase-elését, hacsak nem vagy biztos benne, hogy ezzel jól jársz.  A
további részletekért lásd a NOTES szakaszt a linkgit:git-rebase[1] oldalon.

[[_hooks]]
Hookok
------

[[restrict-with-hooks]]
Hogyan használjak hookokat, hogy megakadályozzam a felhasználókat bizonyos változtatások elvégzésében?::
	Az egyetlen biztonságos hely ezeknek a változtatásoknak az elvégzésére a remote repository
	(azaz a Git-szerver), általában a `pre-receive` hookban vagy egy
	folyamatos integrációs (CI) rendszerben.  Ezek azok a helyek, ahol a
	szabályzat hatékonyan kikényszeríthető.
+
Gyakori, hogy megpróbálják `pre-commit` hookokkal (vagy commit-üzenetekhez
`commit-msg` hookokkal) ellenőrizni ezeket a dolgokat, ami remek, ha egyedüli
fejlesztőként dolgozol, és azt szeretnéd, hogy az eszközök segítsenek neked.  Azonban a hookok
használata egy fejlesztői gépen nem hatékony szabályzat-ellenőrzésként, mert egy felhasználó megkerülheti
ezeket a hookokat a `--no-verify`-jal, anélkül hogy észrevennék (számos más mód mellett).
A Git feltételezi, hogy a felhasználó irányítja a saját helyi repository-it, és nem
próbálja megakadályozni ezt, vagy beárulni a felhasználót.
+
Emellett egyes haladó felhasználók úgy találják, hogy a `pre-commit` hookok akadályozzák azokat a
munkafolyamatokat, amelyek ideiglenes commitokat használnak a folyamatban lévő munka stage-eléséhez, vagy amelyek
fixup commitokat hoznak létre, ezért mindenképp jobb ezeket a fajta ellenőrzéseket a szerverre
tolni.

[[_cross_platform_issues]]
Platformok közötti problémák
----------------------------

[[windows-text-binary]]
Windowson vagyok, és a szövegfájljaim binárisként vannak felismerve.::
	A Git akkor működik legjobban, ha a szövegfájlokat UTF-8-ként tárolod.  Windowson
	sok program támogatja az UTF-8-at, de néhány nem, és csak a little-endian
	UTF-16 formátumot használja, amelyet a Git binárisként ismer fel.  Ha nem tudsz UTF-8-at használni
	a programjaiddal, megadhatsz egy working tree kódolást, amely jelzi,
	milyen kódolással kell kicsekkolni a fájljaidat, miközben ezeket a fájlokat továbbra is
	UTF-8-ként tárolod a repository-ban.  Ez lehetővé teszi, hogy az olyan eszközök, mint a
	linkgit:git-diff[1], a várt módon működjenek, miközben az eszközeid is működnek.
+
Ehhez megadhatsz egy linkgit:gitattributes[5] mintát a
`working-tree-encoding` attribútummal.  Például a következő minta az összes
C fájlt UTF-16LE-BOM használatára állítja, amely egy gyakori kódolás Windowson:
+
----
*.c	working-tree-encoding=UTF-16LE-BOM
----
+
Futtatnod kell a `git add --renormalize` parancsot, hogy ez érvénybe lépjen.  Vedd figyelembe,
hogy ha ezeket a változtatásokat egy platformok között használt projekten végzed,
valószínűleg egy felhasználónkénti konfigurációs fájlban, vagy a
`$GIT_DIR/info/attributes`-ban lévőben szeretnéd megtenni, mivel ha egy `.gitattributes` fájlban teszed a
repository-ban, az a repository összes felhasználójára vonatkozni fog.
+
A sorvégek normalizálásával kapcsolatos információért lásd a következő bejegyzést is,
és az attribútumfájlokkal kapcsolatos további információért lásd a linkgit:gitattributes[5] oldalt.

[[windows-diff-control-m]]
Windowson vagyok, és a git diff azt mutatja, hogy a fájljaim végén `^M` van.::
	Alapból a Git azt várja, hogy a fájlok Unix sorvégekkel legyenek tárolva.  Emiatt
	a Windows sorvég részét képező kocsivissza-karakter (`^M`) megjelenik,
	mert záró whitespace-nek számít.  A Git alapból csak
	az új sorokon mutatja a záró whitespace-t, a meglévőkön nem.
+
Tárolhatod a fájlokat a repository-ban Unix sorvégekkel, és automatikusan
átalakíthatod őket a platformod sorvégeire.  Ehhez állítsd a
`core.eol` konfigurációs opciót `native`-ra, és lásd
<<recommended-storage-settings,az ajánlott tárolási beállításokról szóló kérdést>>
arról, hogyan konfiguráld a fájlokat szövegként vagy binárisként.
+
Ezt a viselkedést a `core.whitespace` beállítással is szabályozhatod, ha
nem szeretnéd eltávolítani a kocsivissza-karaktereket a sorvégeidből.

[[always-modified-files-case]]
Miért van egy mindig módosítottnak jelzett fájlom?::
	Belsőleg a Git mindig bájtsorozatokként tárolja a fájlneveket, és nem
	végez semmilyen kódolást vagy kis-nagybetű-egyesítést.  Azonban a Windows és a macOS is alapból
	kis-nagybetű-egyesítést végez a fájlneveken.  Ennek eredményeként előfordulhat, hogy
	több olyan fájlod vagy könyvtárad lesz, amelyeknek a neve csak kis-nagybetűben tér el.  A Git ezt
	rendben tudja kezelni, de a fájlrendszer csak az egyik ilyen fájlt tudja tárolni,
	így amikor a Git a másik fájlt olvassa be a tartalmának megnézéséhez, módosítottnak tűnik.
+
A legjobb, ha eltávolítod az egyik fájlt, hogy csak egy fájlod maradjon.  Ezt
olyan parancsokkal teheted meg, mint a következők (feltéve, hogy van két fájlod, `AFile.txt` és
`afile.txt`), egy egyébként tiszta working tree-n:
+
----
$ git rm --cached AFile.txt
$ git commit -m 'Remove files conflicting in case'
$ git checkout .
----
+
Ez elkerüli a lemez érintését, de eltávolítja a plusz fájlt.  A projekted
preferálhat egy elnevezési konvenció elfogadását, mint például a csupa kisbetűs nevek, hogy
elkerülje ennek a problémának az újbóli előfordulását; egy ilyen konvenció egy
`pre-receive` hookkal, vagy egy folyamatos integrációs (CI) rendszer részeként ellenőrizhető.
+
Az is lehetséges, hogy örökké módosított fájlok forduljanak elő bármely platformon, ha egy
smudge vagy clean filter van használatban a rendszereden, de egy fájl korábban
a smudge vagy clean filter futtatása nélkül lett commitolva.  Ennek javításához futtasd a
következőt egy egyébként tiszta working tree-n:
+
----
$ git add --renormalize .
----

[[recommended-storage-settings]]
Mi az ajánlott módja a fájlok tárolásának Gitben?::
	Bár a Git bármilyen típusú fájlt tud tárolni és kezelni, vannak olyan
	beállítások, amelyek jobban működnek másoknál.  Általában azt javasoljuk, hogy a
	szövegfájlokat UTF-8-ban, bájtsorrend-jelölő (BOM) nélkül, LF
	(Unix-stílusú) sorvégekkel tárold.  Emellett a commit-üzenetekben is az UTF-8
	használatát javasoljuk (ismét BOM nélkül).  Ezek azok a beállítások, amelyek a legjobban működnek
	platformok között, és olyan eszközökkel, mint a `git diff` és a `git merge`.
+
Emellett, ha választhatsz szöveg alapú vagy nem szöveg alapú tárolási formátumok
között, azt javasoljuk, hogy szöveges formátumban tárold a fájlokat, és, ha
szükséges, alakítsd át a másik formátumba.  Például egy soronként egy rekordot tartalmazó
szöveg alapú SQL-dump sokkal jobban fog működni a diffeléshez és merge-eléshez,
mint egy valódi adatbázisfájl.  Hasonlóképpen a szöveg alapú formátumok, mint a Markdown
és az AsciiDoc, jobban fognak működni, mint a bináris formátumok, mint a Microsoft Word és a
PDF.
+
Hasonlóképpen, bináris függőségek (pl. megosztott könyvtárak vagy JAR fájlok) vagy
build-termékek tárolása a repository-ban általában nem ajánlott.  A függőségeket és
build-termékeket a legjobb egy artifact- vagy package-szerveren tárolni, csak
referenciákat, URL-eket és hasheket tárolva a repository-ban.
+
Emellett javasoljuk egy linkgit:gitattributes[5] fájl beállítását, hogy kifejezetten
megjelöld, mely fájlok szövegesek, és melyek binárisak.  Ha azt szeretnéd, hogy a Git találgasson,
beállíthatod a `text=auto` attribútumot.
+
Szövegfájlok esetén a Git általában biztosítja, hogy LF sorvégek legyenek használva a
repository-ban.  A `core.autocrlf` és `core.eol` konfigurációs változók megadják,
milyen sorvég-konvenciót követnek, amikor bármely szövegfájlt kicsekkolnak.  Az
`eol` attribútumot (pl. `eol=crlf`) is használhatod annak felülírására, mely fájlok milyen
sorvég-kezelést kapnak.
+
Például általában a shell fájloknak LF sorvégekkel kell rendelkezniük, a batch fájloknak
pedig CRLF sorvégekkel, így néhány projektben a következő lehet megfelelő:
+
----
# By default, guess.
*	text=auto
# Mark all C files as text.
*.c	text
# Ensure all shell files have LF endings and all batch files have CRLF
# endings in the working tree and both have LF in the repo.
*.sh text eol=lf
*.bat text eol=crlf
# Mark all JPEG files as binary.
*.jpg	binary
----
+
Ezek a beállítások segítenek az eszközöknek a megfelelő formátumot választani olyan
kimenetekhez, mint a patchek, és azt eredményezik, hogy a fájlok a platformnak
megfelelő sorvéggel kerülnek kicsekkolásra.

GIT
---
A linkgit:git[1] csomag része
