githooks(5)
===========

NAME
----
githooks - A Git által használt hookok

SYNOPSIS
--------
$GIT_DIR/hooks/* (vagy \`git config core.hooksPath`/*)


DESCRIPTION
-----------

A hookok olyan programok, amelyeket egy hooks könyvtárba helyezhetsz
el azért, hogy a Git végrehajtásának bizonyos pontjain műveleteket
váltsanak ki. Azok a hookok, amelyeken nincs beállítva a végrehajtható
bit, figyelmen kívül maradnak.

Alapértelmezés szerint a hooks könyvtár a `$GIT_DIR/hooks`, de ez
megváltoztatható a `core.hooksPath` konfigurációs változóval (lásd:
linkgit:git-config[1]).

Mielőtt a Git meghívna egy hookot, átváltja a munkakönyvtárát vagy a
$GIT_DIR-re bare repository esetén, vagy a munkakönyvtár gyökerére nem
bare repository esetén. Kivételt képeznek a push során kiváltott
hookok ('pre-receive', 'update', 'post-receive', 'post-update',
'push-to-checkout'), amelyek mindig a $GIT_DIR-ben futnak.

A környezeti változók, mint például a `GIT_DIR`, `GIT_WORK_TREE` stb.,
exportálásra kerülnek, hogy a hook által futtatott Git parancsok
helyesen találják meg a repository-t.  Ha a hookodnak Git parancsokat
kell hívnia egy idegen repository-ban, vagy ugyanazon repository egy
másik munkakönyvtárában, akkor törölnie kell ezeket a környezeti
változókat, hogy azok ne zavarják a Git műveleteit az idegen helyen.
Például:

------------
local_desc=$(git describe)
foreign_desc=$(unset $(git rev-parse --local-env-vars); git -C ../foreign-repo describe)
------------

A hookok az argumentumaikat a környezetből, parancssori
argumentumokból és a standard bemenetről (stdin) kaphatják meg. A
részletekért lásd az egyes hookok alábbi dokumentációját.

A `git init` a konfigurációjától függően hookokat másolhat az új
repository-ba. A részletekért lásd a "TEMPLATE DIRECTORY" szakaszt a
linkgit:git-init[1] oldalon. Amikor a dokumentum további része
"alapértelmezett hookokra" hivatkozik, az a Git-hez mellékelt
alapértelmezett sablonra utal.

A jelenleg támogatott hookok az alábbiakban vannak leírva.

HOOKS
-----

applypatch-msg
~~~~~~~~~~~~~~

Ezt a hookot a linkgit:git-am[1] hívja meg.  Egyetlen paramétert vesz
át, annak a fájlnak a nevét, amely a javasolt commit naplóüzenetet
tartalmazza.  A nem nulla állapottal való kilépés miatt a `git am`
megszakad, mielőtt alkalmazná a patchet.

A hook szerkesztheti a helyén az üzenetfájlt, és felhasználható arra,
hogy az üzenetet valamilyen projektszabvány formátumra normalizálja.
Arra is használható, hogy az üzenetfájl megvizsgálása után elutasítsa
a commitot.

Az alapértelmezett 'applypatch-msg' hook, ha engedélyezve van,
lefuttatja a 'commit-msg' hookot, ha az utóbbi is engedélyezve van.

pre-applypatch
~~~~~~~~~~~~~~

Ezt a hookot a linkgit:git-am[1] hívja meg.  Nem vesz át paramétert, és
azután hívódik meg, hogy a patch alkalmazásra került, de mielőtt a
commit megtörténne.

Ha nem nulla állapottal lép ki, akkor a munkakönyvtár nem kerül
commitolásra a patch alkalmazása után.

Felhasználható a jelenlegi munkakönyvtár megvizsgálására, és a commit
megtagadására, ha az nem felel meg bizonyos teszteknek.

Az alapértelmezett 'pre-applypatch' hook, ha engedélyezve van,
lefuttatja a 'pre-commit' hookot, ha az utóbbi is engedélyezve van.

post-applypatch
~~~~~~~~~~~~~~~

Ezt a hookot a linkgit:git-am[1] hívja meg.  Nem vesz át paramétert,
és azután hívódik meg, hogy a patch alkalmazásra került és a commit
megtörtént.

Ez a hook elsősorban értesítési célt szolgál, és nem befolyásolhatja a
`git am` kimenetelét.

pre-commit
~~~~~~~~~~

Ezt a hookot a linkgit:git-commit[1] hívja meg, és megkerülhető a
`--no-verify` opcióval.  Nem vesz át paramétert, és azelőtt hívódik
meg, hogy a javasolt commit naplóüzenet lekérésre kerülne és a commit
megtörténne.  A szkript nem nulla állapottal való kilépése miatt a
`git commit` parancs megszakad, mielőtt létrehozná a commitot.

Az összes `git commit` hook a `GIT_EDITOR=:` környezeti változóval
hívódik meg, ha a parancs nem nyit meg szerkesztőt a commit-üzenet
módosításához.

Az alapértelmezett 'pre-commit' hook, ha engedélyezve van,
megakadályozza a nem ASCII fájlnevek és a záró whitespace-t tartalmazó
sorok bevezetését. A nem ASCII ellenőrzés kikapcsolható a
`hooks.allownonascii` konfigurációs opció `true` értékre állításával.

pre-merge-commit
~~~~~~~~~~~~~~~~

Ezt a hookot a linkgit:git-merge[1] hívja meg, és megkerülhető a
`--no-verify` opcióval.  Nem vesz át paramétert, és azután hívódik meg,
hogy a merge sikeresen végrehajtásra került, de mielőtt a javasolt
commit naplóüzenet lekérésre kerülne a commit létrehozásához.  A
szkript nem nulla állapottal való kilépése miatt a `git merge` parancs
megszakad, mielőtt létrehozná a commitot.

Az alapértelmezett 'pre-merge-commit' hook, ha engedélyezve van,
lefuttatja a 'pre-commit' hookot, ha az utóbbi is engedélyezve van.

Ez a hook a `GIT_EDITOR=:` környezeti változóval hívódik meg, ha a
parancs nem nyit meg szerkesztőt a commit-üzenet módosításához.

Ha a merge nem hajtható végre automatikusan, a konfliktusokat fel kell
oldani, és az eredményt külön kell commitolni (lásd:
linkgit:git-merge[1]). Ekkor ez a hook nem hajtódik végre, de a
'pre-commit' hook igen, ha engedélyezve van.

prepare-commit-msg
~~~~~~~~~~~~~~~~~~

Ezt a hookot a linkgit:git-commit[1] hívja meg, rögtön az
alapértelmezett naplóüzenet előkészítése után, és mielőtt a szerkesztő
elindulna.

Egytől három paramétert vesz át.  Az első annak a fájlnak a neve, amely
a commit naplóüzenetet tartalmazza.  A második a commit-üzenet
forrása, és a következő lehet: `message` (ha egy `-m` vagy `-F` opció
lett megadva); `template` (ha egy `-t` opció lett megadva, vagy be van
állítva a `commit.template` konfigurációs opció); `merge` (ha a commit
egy merge, vagy létezik egy `.git/MERGE_MSG` fájl); `squash` (ha
létezik egy `.git/SQUASH_MSG` fájl); vagy `commit`, amelyet egy commit
objektumnév követ (ha egy `-c`, `-C` vagy `--amend` opció lett
megadva).

Ha a kilépési állapot nem nulla, a `git commit` megszakad.

A hook célja az üzenetfájl helyben történő szerkesztése, és nem
kapcsolható ki a `--no-verify` opcióval.  A nem nulla kilépés a hook
hibáját jelenti, és megszakítja a commitot.  Nem szabad a pre-commit
hook helyettesítőjeként használni.

A Git-hez mellékelt minta `prepare-commit-msg` hook eltávolítja a
commit sablon kikommentezett részében található súgóüzenetet.

commit-msg
~~~~~~~~~~

Ezt a hookot a linkgit:git-commit[1] és a linkgit:git-merge[1] hívja
meg, és megkerülhető a `--no-verify` opcióval.  Egyetlen paramétert
vesz át, annak a fájlnak a nevét, amely a javasolt commit
naplóüzenetet tartalmazza.  A nem nulla állapottal való kilépés miatt
a parancs megszakad.

A hook szerkesztheti a helyén az üzenetfájlt, és felhasználható arra,
hogy az üzenetet valamilyen projektszabvány formátumra normalizálja.
Arra is használható, hogy az üzenetfájl megvizsgálása után elutasítsa
a commitot.

Az alapértelmezett 'commit-msg' hook, ha engedélyezve van, észleli az
ismétlődő `Signed-off-by` trailereket, és megszakítja a commitot, ha
talál ilyet.

post-commit
~~~~~~~~~~~

Ezt a hookot a linkgit:git-commit[1] hívja meg. Nem vesz át
paramétert, és a commit létrehozása után hívódik meg.

Ez a hook elsősorban értesítési célt szolgál, és nem befolyásolhatja a
`git commit` kimenetelét.

pre-rebase
~~~~~~~~~~

Ezt a hookot a linkgit:git-rebase[1] hívja meg, és felhasználható
arra, hogy megakadályozza egy branch rebase-elését.  A hook egy vagy
két paraméterrel hívható meg.  Az első paraméter az upstream, amelyből
a sorozat le lett ágaztatva.  A második paraméter a rebase-elés alatt
álló branch, és nincs beállítva a jelenlegi branch rebase-elésekor.

post-checkout
~~~~~~~~~~~~~

Ez a hook akkor hívódik meg, amikor egy linkgit:git-checkout[1] vagy
linkgit:git-switch[1] fut le a worktree frissítése után.  A hook három
paramétert kap: az előző HEAD referenciáját, az új HEAD referenciáját
(amely lehet, hogy megváltozott, lehet, hogy nem), és egy jelzőt, amely
megmutatja, hogy a checkout branch checkout volt-e (branchváltás,
flag=1) vagy fájl checkout (fájl lekérése az indexből, flag=0).  Ez a
hook nem befolyásolhatja a `git switch` vagy a `git checkout`
kimenetelét, azon kívül, hogy a hook kilépési állapota lesz e két
parancs kilépési állapota.

Ez a hook a linkgit:git-clone[1] után is lefut, hacsak nincs
használatban a `--no-checkout` (`-n`) opció. Az első paraméter,
amelyet a hook kap, a null-referencia, a második az új HEAD
referenciája, a flag pedig mindig 1. Hasonlóképpen a `git worktree add`
esetén is, hacsak nincs használatban a `--no-checkout`.

Ez a hook felhasználható a repository érvényességének ellenőrzésére,
az előző HEAD-től való eltérések automatikus megjelenítésére, ha van
ilyen, vagy a munkakönyvtár metaadat-tulajdonságainak beállítására.

post-merge
~~~~~~~~~~

Ezt a hookot a linkgit:git-merge[1] hívja meg, ami akkor történik, ha
egy `git pull` fut le egy helyi repository-n.  A hook egyetlen
paramétert vesz át, egy állapotjelzőt, amely megadja, hogy a
végrehajtott merge squash merge volt-e vagy sem.  Ez a hook nem
befolyásolhatja a `git merge` kimenetelét, és nem hajtódik végre, ha a
merge konfliktusok miatt meghiúsult.

Ez a hook egy megfelelő pre-commit hookkal együtt használható a
munkakönyvtárhoz társított bármilyen metaadat mentésére és
visszaállítására (pl.: jogosultságok/tulajdonjog, ACL-ek stb.).  Lásd a
contrib/hooks/setgitperms.perl fájlt egy erre vonatkozó példáért.

pre-push
~~~~~~~~

Ezt a hookot a linkgit:git-push[1] hívja meg, és felhasználható egy
push megakadályozására.  A hook két paraméterrel hívódik meg, amelyek
megadják a cél remote nevét és helyét; ha nincs elnevezett remote
használatban, a két érték megegyezik.

Az arra vonatkozó információ, hogy mi kerül pusholásra, a hook
standard bemenetén érhető el, a következő formátumú sorokkal:

  <local-ref> SP <local-object-name> SP <remote-ref> SP <remote-object-name> LF

Például, ha a +git push origin master:foreign+ parancs futna le, a
hook egy ehhez hasonló sort kapna:

  refs/heads/master 67890 refs/heads/foreign 12345

bár a teljes objektumnév kerülne megadásra.  Ha az idegen referencia
még nem létezik, a `<remote-object-name>` a csupa nullából álló
objektumnév lesz.  Ha egy referenciát törölni kell, a `<local-ref>`
`(delete)` értékkel kerül megadásra, és a `<local-object-name>` a
csupa nullából álló objektumnév lesz.  Ha a helyi commit nem olyan
névvel lett megadva, amely kifejthető (mint például a `HEAD~`, vagy
egy objektumnév), akkor úgy kerül megadásra, ahogyan eredetileg meg
lett adva.

Ha ez a hook nem nulla állapottal lép ki, a `git push` megszakad
anélkül, hogy bármit is pusholna.  Az arról szóló információ, hogy
miért lett a push elutasítva, elküldhető a felhasználónak a standard
hibakimenetre írással.

[[pre-receive]]
pre-receive
~~~~~~~~~~~

Ezt a hookot a linkgit:git-receive-pack[1] hívja meg, amikor egy
`git push`-ra reagál, és referenciá(ka)t frissít a repository-jában.
Közvetlenül azelőtt, hogy elkezdené a referenciák frissítését a remote
repository-n, a pre-receive hook meghívásra kerül.  A kilépési
állapota határozza meg a frissítés sikerét vagy sikertelenségét.

Ez a hook egyszer fut le a fogadási művelethez. Nem vesz át
argumentumot, de minden frissítendő referenciához a standard bemenetén
a következő formátumú sort kapja:

  <old-oid> SP <new-oid> SP <ref-name> LF

ahol az `<old-oid>` a referenciában tárolt régi objektumnév, az
`<new-oid>` a referenciában tárolandó új objektumnév, a `<ref-name>`
pedig a referencia teljes neve.
Új referencia létrehozásakor az `<old-oid>` a csupa nullából álló
objektumnév.

Ha a hook nem nulla állapottal lép ki, egyetlen referencia sem kerül
frissítésre. Ha a hook nulla állapottal lép ki, az egyes referenciák
frissítését továbbra is megakadályozhatja az <<update,'update'>> hook.

A standard kimenet és a standard hibakimenet is továbbításra kerül a
másik végen lévő `git send-pack`-nek, így egyszerűen csak `echo`-zhatsz
üzeneteket a felhasználónak.

A `git push --push-option=...` parancssorában megadott push opciók
száma a `GIT_PUSH_OPTION_COUNT` környezeti változóból olvasható ki,
maguk az opciók pedig a `GIT_PUSH_OPTION_0`, `GIT_PUSH_OPTION_1`, ...
változókban találhatók.
Ha a felek úgy egyeztek meg, hogy nem használják a push opciók
fázisát, a környezeti változók nem lesznek beállítva. Ha a kliens úgy
dönt, hogy használja a push opciókat, de nem küld egyet sem, a
számláló változó nullára lesz állítva: `GIT_PUSH_OPTION_COUNT=0`.

Néhány óvatosságra intő megjegyzésért lásd a "Quarantine Environment"
szakaszt a linkgit:git-receive-pack[1] oldalon.

[[update]]
update
~~~~~~

Ezt a hookot a linkgit:git-receive-pack[1] hívja meg, amikor egy
`git push`-ra reagál, és referenciá(ka)t frissít a repository-jában.
Közvetlenül azelőtt, hogy frissítené a referenciát a remote
repository-n, az update hook meghívásra kerül.  A kilépési állapota
határozza meg a referenciafrissítés sikerét vagy sikertelenségét.

A hook minden frissítendő referenciára egyszer fut le, és három
paramétert vesz át:

 - a frissítendő referencia neve,
 - a referenciában tárolt régi objektumnév,
 - és a referenciában tárolandó új objektumnév.

Az update hook nulla kilépése engedélyezi a referencia frissítését.
A nem nulla állapottal való kilépés megakadályozza, hogy a
`git receive-pack` frissítse azt a referenciát.

Ez a hook felhasználható arra, hogy megakadályozza a 'forced'
frissítést bizonyos referenciákon, azáltal, hogy biztosítja, hogy az
objektumnév egy olyan commit objektum, amely leszármazottja a régi
objektumnév által megnevezett commit objektumnak.  Vagyis egy
"fast-forward only" szabály érvényesítésére.

Felhasználható lenne a régi..új állapot naplózására is.  Azonban nem
ismeri a branchek teljes halmazát, így naiv használat esetén
branchenként egy-egy e-mailt küldene ki.  Erre inkább a
<<post-receive,'post-receive'>> hook alkalmasabb.

Egy olyan környezetben, amely a felhasználók hozzáférését kizárólag a
hálózaton keresztüli git parancsokra korlátozza, ez a hook
felhasználható hozzáférés-vezérlés megvalósítására, a
fájlrendszer-tulajdonjogra és csoporttagságra való támaszkodás
nélkül. Lásd a linkgit:git-shell[1] oldalt arra vonatkozóan, hogyan
használhatod a bejelentkezési shellt a felhasználó hozzáférésének
kizárólag git parancsokra való korlátozására.

A standard kimenet és a standard hibakimenet is továbbításra kerül a
másik végen lévő `git send-pack`-nek, így egyszerűen csak `echo`-zhatsz
üzeneteket a felhasználónak.

Az alapértelmezett 'update' hook, ha engedélyezve van — és a
`hooks.allowunannotated` konfigurációs opció nincs beállítva vagy
`false`-ra van állítva —, megakadályozza az annotálatlan tagek
pusholását.

[[proc-receive]]
proc-receive
~~~~~~~~~~~~

Ezt a hookot a linkgit:git-receive-pack[1] hívja meg.  Ha a szerveren
be van állítva a `receive.procReceiveRefs` többértékű konfigurációs
változó, és a 'receive-pack'-nak küldött parancsok illeszkedő
referencianevekkel rendelkeznek, ezeket a parancsokat ez a hook fogja
végrehajtani, a belső `execute_commands()` függvény helyett.  Ez a
hook felelős a megfelelő referenciák frissítéséért, és az eredmények
visszajelentéséért a 'receive-pack' felé.

Ez a hook egyszer fut le a fogadási művelethez.  Nem vesz át
argumentumot, de egy pkt-line formátumú protokollt használ a
'receive-pack'-kal való kommunikációra, hogy beolvassa a parancsokat
és a push-opciókat, majd elküldje az eredményeket.  A protokoll alábbi
példájában az 'S' betű a 'receive-pack'-ot, a 'H' betű pedig ezt a
hookot jelöli.

    # Version and features negotiation.
    S: PKT-LINE(version=1\0push-options atomic...)
    S: flush-pkt
    H: PKT-LINE(version=1\0push-options...)
    H: flush-pkt

    # Send commands from server to the hook.
    S: PKT-LINE(<old-oid> <new-oid> <ref>)
    S: ... ...
    S: flush-pkt
    # Send push-options only if the 'push-options' feature is enabled.
    S: PKT-LINE(push-option)
    S: ... ...
    S: flush-pkt

    # Receive results from the hook.
    # OK, run this command successfully.
    H: PKT-LINE(ok <ref>)
    # NO, I reject it.
    H: PKT-LINE(ng <ref> <reason>)
    # Fall through, let 'receive-pack' execute it.
    H: PKT-LINE(ok <ref>)
    H: PKT-LINE(option fall-through)
    # OK, but has an alternate reference.  The alternate reference name
    # and other status can be given in option directives.
    H: PKT-LINE(ok <ref>)
    H: PKT-LINE(option refname <refname>)
    H: PKT-LINE(option old-oid <old-oid>)
    H: PKT-LINE(option new-oid <new-oid>)
    H: PKT-LINE(option forced-update)
    H: ... ...
    H: flush-pkt

A 'proc-receive' hook minden egyes parancsa mutathat egy
pszeudo-referenciára, és az old-oidja mindig nulla, míg a
'proc-receive' hook egy alternatív referenciát frissíthet, és ez az
alternatív referencia már létezhet nem nulla old-oiddal.  Ebben az
esetben ez a hook "option" direktívákat fog használni a vezető "ok"
direktíva által megadott referencia kiterjesztett attribútumainak
jelentésére.

Ennek a hooknak a parancsairól szóló jelentésnek ugyanabban a
sorrendben kell lennie, mint a bemenetnek.  A 'proc-receive' hook
kilépési állapota csak a neki elküldött parancscsoport sikerét vagy
sikertelenségét határozza meg, hacsak nincs használatban atomi push.

[[post-receive]]
post-receive
~~~~~~~~~~~~

Ezt a hookot a linkgit:git-receive-pack[1] hívja meg, amikor egy
`git push`-ra reagál, és referenciá(ka)t frissít a repository-jában.
A hook a remote repository-n egyszer fut le, miután az összes javasolt
referenciafrissítés feldolgozásra került, és ha ennek eredményeként
legalább egy referencia frissült.

A hook nem vesz át argumentumot.  Minden sikeresen frissített
referenciához egy sort kap a standard bemeneten, ugyanabban a
formátumban, mint a <<pre-receive,'pre-receive'>> hook.

Ez a hook nem befolyásolja a `git receive-pack` kimenetelét, mivel a
tényleges munka elvégzése után kerül meghívásra.

Ez felváltja a <<post-update,'post-update'>> hookot abban az
értelemben, hogy az összes referencia régi és új értékét is megkapja a
neveik mellett.

A standard kimenet és a standard hibakimenet is továbbításra kerül a
másik végen lévő `git send-pack`-nek, így egyszerűen csak `echo`-zhatsz
üzeneteket a felhasználónak.

Az alapértelmezett 'post-receive' hook üres, de van egy
`post-receive-email` nevű minta szkript a Git disztribúció
`contrib/hooks` könyvtárában, amely commit e-mailek küldését valósítja
meg.

A `git push --push-option=...` parancssorában megadott push opciók
száma a `GIT_PUSH_OPTION_COUNT` környezeti változóból olvasható ki,
maguk az opciók pedig a `GIT_PUSH_OPTION_0`, `GIT_PUSH_OPTION_1`, ...
változókban találhatók.
Ha a felek úgy egyeztek meg, hogy nem használják a push opciók
fázisát, a környezeti változók nem lesznek beállítva. Ha a kliens úgy
dönt, hogy használja a push opciókat, de nem küld egyet sem, a
számláló változó nullára lesz állítva: `GIT_PUSH_OPTION_COUNT=0`.

A további részletekért lásd a "post-receive" szakaszt a
linkgit:git-receive-pack[1] oldalon.

[[post-update]]
post-update
~~~~~~~~~~~

Ezt a hookot a linkgit:git-receive-pack[1] hívja meg, amikor egy
`git push`-ra reagál, és referenciá(ka)t frissít a repository-jában.
A remote repository-n egyszer fut le, miután az összes referencia
frissítésre került.

Változó számú paramétert vesz át, amelyek mindegyike egy ténylegesen
frissített referencia neve.

Ez a hook elsősorban értesítési célt szolgál, és nem befolyásolhatja a
`git receive-pack` kimenetelét.

A 'post-update' hook meg tudja mondani, hogy mely branch-csúcsok
lettek pusholva, de nem ismeri az eredeti és a frissített értéküket,
így nem alkalmas a régi..új naplózására. A
<<post-receive,'post-receive'>> hook megkapja a referenciák eredeti és
frissített értékét is. Ha szükséged van ezekre, inkább azt érdemes
megfontolnod.

Ha engedélyezve van, az alapértelmezett 'post-update' hook lefuttatja
a `git update-server-info` parancsot, hogy naprakészen tartsa a buta
(dumb) transzportok (pl. HTTP) által használt információkat.  Ha egy
HTTP-n keresztül elérhető Git repository-t teszel közzé, valószínűleg
érdemes engedélyezned ezt a hookot.

A standard kimenet és a standard hibakimenet is továbbításra kerül a
másik végen lévő `git send-pack`-nek, így egyszerűen csak `echo`-zhatsz
üzeneteket a felhasználónak.

reference-transaction
~~~~~~~~~~~~~~~~~~~~~

Ezt a hookot bármely olyan Git parancs meghívja, amely
referenciafrissítést hajt végre. Akkor fut le, amikor egy
referenciatranzakció előkészül, előkészített állapotba kerül,
véglegesítésre kerül vagy megszakad, így akár többször is meghívásra
kerülhet. A hook a szimbolikus referenciák frissítését is támogatja.

A hook pontosan egy argumentumot vesz át, amely a megadott
referenciatranzakció jelenlegi állapota:

    - "preparing": Az összes referenciafrissítés sorba lett állítva a
      tranzakcióban, de a referenciák még nincsenek lemezen zárolva.

    - "prepared": Az összes referenciafrissítés sorba lett állítva a
      tranzakcióban, és a referenciák le lettek zárolva a lemezen.

    - "committed": A referenciatranzakció véglegesítésre került, és
      minden referenciának megvan a saját új értéke.

    - "aborted": A referenciatranzakció megszakadt, semmilyen
      változtatás nem történt, és a zárolások feloldásra kerültek.

Minden a tranzakcióhoz hozzáadott referenciafrissítéshez a hook a
standard bemeneten a következő formátumú sort kapja:

  <old-value> SP <new-value> SP <ref-name> LF

ahol az `<old-value>` a referenciatranzakciónak átadott régi
objektumnév, az `<new-value>` a referenciában tárolandó új objektumnév,
a `<ref-name>` pedig a referencia teljes neve. Ha a referencia force
frissítésre kerül a jelenlegi értékétől függetlenül, vagy ha a
referencia újonnan jön létre, az `<old-value>` a csupa nullából álló
objektumnév. E két eset megkülönböztetéséhez megvizsgálhatod a
`<ref-name>` jelenlegi értékét a `git rev-parse` segítségével. A
"preparing" állapot alatt a szimbolikus referenciák nincsenek
feloldva: a `<ref-name>` magát a szimbolikus referenciát fogja
tükrözni, nem pedig azt az objektumot, amelyre mutat.

Szimbolikus referenciák frissítésekor az `<old_value>` és `<new-value>`
mezők objektumok helyett referenciákat is jelölhetnek. Egy referencia
'ref:' előtaggal lesz jelölve, például `ref:<ref-target>` formában.

A hook kilépési állapota figyelmen kívül van hagyva minden állapot
esetén, kivéve a "preparing" és "prepared" állapotokat. Ezekben az
állapotokban a nem nulla kilépési állapot a tranzakció megszakadását
okozza. A hook ebben az esetben nem lesz meghívva "aborted" állapottal.

push-to-checkout
~~~~~~~~~~~~~~~~

Ezt a hookot a linkgit:git-receive-pack[1] hívja meg, amikor egy
`git push`-ra reagál, és referenciá(ka)t frissít a repository-jában,
és amikor a push megpróbálja frissíteni azt a branchet, amely
jelenleg ki van checkoutolva, és a `receive.denyCurrentBranch`
konfigurációs változó `updateInstead` értékre van állítva.  Egy ilyen
push alapértelmezés szerint elutasításra kerül, ha a remote
repository munkakönyvtára és indexe bármilyen eltérést mutat a
jelenleg kicheckoutolt committól; ha mind a munkakönyvtár, mind az
index megegyezik a jelenlegi committal, akkor frissülnek, hogy
megegyezzenek a branch újonnan pusholt csúcsával.  Ez a hook az
alapértelmezett viselkedés felülbírálására szolgál.

A hook megkapja azt a commitot, amelyre a jelenlegi branch csúcsa
frissülni fog.  Kiléphet nem nulla állapottal a push elutasításához
(ebben az esetben nem módosíthatja sem az indexet, sem a
munkakönyvtárat).  Vagy elvégezheti a munkakönyvtáron és az indexen a
szükséges változtatásokat, hogy a kívánt állapotba hozza őket, amikor
a jelenlegi branch csúcsa frissül az új committal, és kiléphet nulla
állapottal.

Például a hook egyszerűen lefuttathatja a `git read-tree -u -m HEAD
"$1"` parancsot, hogy emulálja a `git fetch`-et, amely `git push`-sal
ellentétes irányban fut le, mivel a `git read-tree -u -m` kétfás
formája lényegében ugyanaz, mint a `git switch` vagy a `git checkout`,
amely branchet vált úgy, hogy közben megőrzi a munkakönyvtárban lévő
helyi változtatásokat, amelyek nem ütköznek a branchek közötti
eltéréssel.


pre-auto-gc
~~~~~~~~~~~

Ezt a hookot a `git gc --auto` hívja meg (lásd: linkgit:git-gc[1]).
Nem vesz át paramétert, és a szkript nem nulla állapottal való
kilépése miatt a `git gc --auto` megszakad.

post-rewrite
~~~~~~~~~~~~

Ezt a hookot azok a parancsok hívják meg, amelyek commitokat írnak
át (a linkgit:git-commit[1], ha `--amend`-del hívjuk, és a
linkgit:git-rebase[1]; azonban a teljes előzményt (újra)író eszközök,
mint a linkgit:git-fast-import[1] vagy a
https://github.com/newren/git-filter-repo[git-filter-repo], jellemzően
nem hívják meg!).  Az első argumentuma megadja, hogy melyik parancs
hívta meg: jelenleg `amend` vagy `rebase` valamelyike.  A jövőben
további, parancsfüggő argumentumok is átadásra kerülhetnek.

A hook az átírt commitok listáját kapja meg a standard bemeneten, a
következő formátumban:

  <old-object-name> SP <new-object-name> [ SP <extra-info> ] LF

Az 'extra-info' szintén parancsfüggő.  Ha üres, az azt megelőző SP is
elmarad.  Jelenleg egyetlen parancs sem ad át 'extra-info'-t.

A hook mindig az automatikus jegyzetmásolás (lásd:
"notes.rewrite.<command>" a linkgit:git-config[1] oldalon) megtörténte
után fut le, így hozzáfér ezekhez a jegyzetekhez.

A következő, parancsonként eltérő megjegyzések érvényesek:

rebase::
	A 'squash' és a 'fixup' művelet esetén az összes squasholt
	commit úgy szerepel, mintha a squasholt commitra íródott
	volna át.  Ez azt jelenti, hogy több sor is ugyanazt a
	'new-object-name' értéket fogja megosztani.
+
A commitok garantáltan abban a sorrendben szerepelnek, ahogyan a
rebase feldolgozta őket.

sendemail-validate
~~~~~~~~~~~~~~~~~~

Ezt a hookot a linkgit:git-send-email[1] hívja meg.

Ezeket a parancssori argumentumokat veszi át. Ezek a következők:
1. annak a fájlnak a neve, amely az elküldendő e-mail tartalmát tartalmazza.
2. Annak a fájlnak a neve, amely az e-mail SMTP fejléceit tartalmazza.

Az SMTP fejlécek pontosan ugyanúgy kerülnek átadásra, mint ahogyan a
felhasználó levéltovábbító ügynökének (MTA) átadásra kerülnek.
Gyakorlatilag a felhasználó MTA-jának megadott e-mail a $2 tartalmából,
majd az $1 tartalmából áll.

Néhány gyakori fejléc példáját az alábbiakban láthatod. Figyelj a
nagybetűsítésre és a többsoros tab-struktúrára.

  From: Example <from@example.com>
  To: to@example.com
  Cc: cc@example.com,
	  A <author@example.com>,
	  One <one@example.com>,
	  two@example.com
  Subject: PATCH-STRING

A nem nulla állapottal való kilépés miatt a `git send-email` megszakad,
mielőtt bármilyen e-mailt elküldene.

A következő környezeti változók vannak beállítva a hook végrehajtásakor.

`GIT_SENDEMAIL_FILE_COUNTER`::
	Egy 1-től induló számláló, amely minden egyes elküldendő e-mailt
	tartalmazó fájllal (a FIFO-k kivételével) eggyel nő. Ez a
	számláló nem követi a patch-sorozat számlálási sémáját. Mindig
	1-en indul, és a GIT_SENDEMAIL_FILE_TOTAL értékén végződik.

`GIT_SENDEMAIL_FILE_TOTAL`::
	Az elküldendő fájlok teljes száma (a FIFO-k kivételével). Ez a
	számláló nem követi a patch-sorozat számlálási sémáját. Mindig
	megegyezik az elküldött fájlok számával, függetlenül attól, hogy
	van-e kísérőlevél vagy sem.

Ezek a változók például felhasználhatók a patch-sorozat érvényesítésére.

A Git-hez mellékelt minta `sendemail-validate` hook ellenőrzi, hogy az
összes elküldött patch (a kísérőlevél kivételével) konfliktus nélkül
alkalmazható-e az upstream repository alapértelmezett branch-ének
tetejére. Néhány helyőrző szerepel a sorozat összes patch-ének
alkalmazása után elvégzendő további érvényesítési lépésekhez.

fsmonitor-watchman
~~~~~~~~~~~~~~~~~~

Ezt a hookot akkor hívja meg a rendszer, ha a `core.fsmonitor`
konfigurációs opció `.git/hooks/fsmonitor-watchman` vagy
`.git/hooks/fsmonitor-watchmanv2` értékre van állítva, a használandó
hook verziójától függően.

Az 1-es verzió két argumentumot vesz át, egy verziószámot (1) és az
1970. január 1. éjfél óta eltelt időt nanoszekundumban.

A 2-es verzió két argumentumot vesz át, egy verziószámot (2) és egy
tokent, amelyet a token óta bekövetkezett változások azonosítására
használ. Watchman esetén ez egy clock id lenne. Ennek a verziónak a
fájllista előtt ki kell írnia a standard kimenetre az új tokent, egy
NUL karakterrel elválasztva.

A hooknak ki kell írnia a standard kimenetre a munkakönyvtárban lévő
összes olyan fájl listáját, amely a kért időpont óta megváltozhatott.
A logikának inkluzívnak kell lennie, hogy ne hagyjon ki egyetlen
lehetséges változást sem. Az elérési útvonalaknak a munkakönyvtár
gyökeréhez relatívnak kell lenniük, és egyetlen NUL karakterrel
elválasztva kell szerepelniük.

Rendben van, ha olyan fájlokat is tartalmaz, amelyek valójában nem
változtak.  Minden változást, beleértve az újonnan létrehozott és a
törölt fájlokat is, tartalmaznia kell.  Fájlok átnevezésekor mind a
régi, mind az új nevet fel kell tüntetni.

A Git a megadott elérési útvonalak alapján korlátozza, hogy mely
fájlokat ellenőrzi változásokért, valamint hogy mely könyvtárakat
ellenőrzi nem követett fájlokért.

A gitnek szóló optimalizált módja annak közlésére, hogy "minden fájl
megváltozott", ha a `/` fájlnevet adja vissza.

A kilépési állapot határozza meg, hogy a git felhasználja-e a
hooktól kapott adatokat a keresés korlátozására.  Hiba esetén
visszaáll minden fájl és mappa ellenőrzésére.

p4-changelist
~~~~~~~~~~~~~

Ezt a hookot a `git-p4 submit` hívja meg.

A `p4-changelist` hook azután fut le, hogy a felhasználó
szerkesztette a changelist üzenetet. Megkerülhető a `--no-verify`
opcióval. Egyetlen paramétert vesz át, annak a fájlnak a nevét, amely
a javasolt changelist szöveget tartalmazza. A nem nulla állapottal
való kilépés miatt a parancs megszakad.

A hook szerkesztheti a changelist fájlt, és felhasználható arra,
hogy a szöveget valamilyen projektszabvány formátumra normalizálja.
Arra is használható, hogy az üzenetfájl megvizsgálása után elutasítsa
a submitot.

A részletekért futtasd a `git-p4 submit --help` parancsot.

p4-prepare-changelist
~~~~~~~~~~~~~~~~~~~~~

Ezt a hookot a `git-p4 submit` hívja meg.

A `p4-prepare-changelist` hook rögtön az alapértelmezett changelist
üzenet előkészítése után, és mielőtt a szerkesztő elindulna, fut le.
Egy paramétert vesz át, annak a fájlnak a nevét, amely a changelist
szöveget tartalmazza. A szkript nem nulla állapottal való kilépése
megszakítja a folyamatot.

A hook célja az üzenetfájl helyben történő szerkesztése, és nem
kapcsolható ki a `--no-verify` opcióval. Ez a hook akkor is
meghívásra kerül, ha a `--prepare-p4-only` be van állítva.

A részletekért futtasd a `git-p4 submit --help` parancsot.

p4-post-changelist
~~~~~~~~~~~~~~~~~~

Ezt a hookot a `git-p4 submit` hívja meg.

A `p4-post-changelist` hook azután hívódik meg, hogy a submit
sikeresen megtörtént a P4-ben. Nem vesz át paramétert, és elsősorban
értesítési célt szolgál, és nem befolyásolhatja a git p4 submit
művelet kimenetelét.

A részletekért futtasd a `git-p4 submit --help` parancsot.

p4-pre-submit
~~~~~~~~~~~~~

Ezt a hookot a `git-p4 submit` hívja meg. Nem vesz át paramétert, és
semmit sem a standard bemenetről. A szkript nem nulla állapottal való
kilépése megakadályozza a `git-p4 submit` elindulását. Megkerülhető a
`--no-verify` parancssori opcióval. A részletekért futtasd a
`git-p4 submit --help` parancsot.



post-index-change
~~~~~~~~~~~~~~~~~

Ez a hook akkor hívódik meg, amikor az index kiírásra kerül a
read-cache.c fájl do_write_locked_index függvényében.

A hooknak átadott első paraméter a munkakönyvtár frissítésének
jelzője.  "1" azt jelenti, hogy a munkakönyvtár frissült, "0" pedig
azt, hogy a munkakönyvtár nem frissült.

A hooknak átadott második paraméter azt jelzi, hogy az index
frissült-e, és hogy a skip-worktree bit megváltozhatott-e.  "1" azt
jelenti, hogy a skip-worktree bitek frissülhettek, "0" pedig azt,
hogy nem.

A hook futásakor csak az egyik paraméternek szabad "1" értékűnek
lennie.  Nem lehetséges, hogy a hook "1", "1" értékekkel fusson.

SEE ALSO
--------
linkgit:git-hook[1]

GIT
---
A linkgit:git[1] csomag része
