gitignore(5)
============

NAME
----
gitignore - Szándékosan nem követett, figyelmen kívül hagyandó fájlok megadása

SYNOPSIS
--------
$XDG_CONFIG_HOME/git/ignore, $GIT_COMMON_DIR/info/exclude, .gitignore

DESCRIPTION
-----------

A `gitignore` fájl azokat a szándékosan nem követett fájlokat adja meg,
amelyeket a Gitnek figyelmen kívül kell hagynia.
A Git által már követett fájlokat ez nem érinti; a részletekért lásd
lentebb a NOTES szakaszt.

A `gitignore` fájl minden sora egy mintát ad meg.
Amikor arról dönt, hogy figyelmen kívül hagyjon-e egy elérési utat, a Git
általában több forrásból ellenőriz `gitignore` mintákat, a következő
precedenciasorrendben, a legmagasabbtól a legalacsonyabbig (egy adott
precedenciaszinten belül az utolsó illeszkedő minta dönti el az
eredményt):

 * A parancssorból beolvasott minták azoknál a parancsoknál, amelyek
   támogatják őket.

 * Az elérési úttal azonos könyvtárban vagy bármely szülőkönyvtárában (a
   munkakönyvtár legfelső szintjéig) lévő `.gitignore` fájlból beolvasott
   minták, ahol a magasabb szintű fájlokban lévő mintákat a fájlt tartalmazó
   könyvtárig lefelé haladva az alacsonyabb szintű fájlokban lévők
   felülírják. Ezek a minták a `.gitignore` fájl helyéhez képest
   illeszkednek.  Egy projekt általában tartalmaz ilyen `.gitignore`
   fájlokat a repositoryjában, amelyek a projekt buildje során generált
   fájlokhoz tartozó mintákat tartalmaznak.

 * A `$GIT_COMMON_DIR/info/exclude`-ból beolvasott minták.

 * A `core.excludesFile` konfigurációs változó által megadott fájlból
   beolvasott minták.

Az, hogy melyik fájlba kerüljön egy minta, attól függ, hogyan szánják a
minta használatát.

 * Azok a minták, amelyeket verziókövetni kell, és klónozással más
   repositorykba kell terjeszteni (azaz olyan fájlok, amelyeket minden
   fejlesztő figyelmen kívül akar hagyni), egy `.gitignore` fájlba
   kerüljenek.

 * Azok a minták, amelyek egy adott repositoryra jellemzők, de amelyeket
   nem kell megosztani más kapcsolódó repositorykkal (pl. a repositoryn
   belül élő, de egy adott felhasználó munkafolyamatára jellemző
   segédfájlok), a `$GIT_COMMON_DIR/info/exclude` fájlba kerüljenek.

 * Azok a minták, amelyeket a felhasználó minden helyzetben figyelmen
   kívül akar hagyatni a Gittel (pl. a felhasználó választott
   szerkesztője által generált biztonsági mentés vagy ideiglenes fájlok),
   általában a felhasználó `~/.gitconfig`-jában lévő `core.excludesFile`
   által megadott fájlba kerülnek. Ennek alapértelmezett értéke
   $XDG_CONFIG_HOME/git/ignore. Ha a $XDG_CONFIG_HOME nincs beállítva vagy
   üres, helyette a $HOME/.config/git/ignore használatos.

A mögöttes Git plumbing eszközök, mint a 'git ls-files' és a
'git read-tree', a parancssori kapcsolókkal megadott `gitignore` mintákat
olvassák, vagy a parancssori kapcsolókkal megadott fájlokból.  A
magasabb szintű Git eszközök, mint a 'git status' és a 'git add', a fent
megadott forrásokból származó mintákat használják.

PATTERN FORMAT
--------------

 - Egy üres sor nem illeszkedik egyetlen fájlra sem, így az olvashatóság
   érdekében elválasztóként szolgálhat.

 - A # jellel kezdődő sor megjegyzésként szolgál.
   Tegyél egy visszaperjelet ("`\`") az első kettőskereszt elé az olyan
   mintáknál, amelyek kettőskereszttel kezdődnek.

 - A sorvégi szóközöket figyelmen kívül hagyja, hacsak nincsenek
   visszaperjellel ("`\`") escapelve.

 - Egy opcionális "`!`" előtag, amely negálja a mintát; minden olyan
   illeszkedő fájl, amelyet egy korábbi minta kizárt, ismét bekerül. Nem
   lehet újra bevenni egy fájlt, ha a fájl valamely szülőkönyvtára ki van
   zárva. A Git teljesítménybeli okokból nem listázza a kizárt
   könyvtárakat, így a bennük lévő fájlokra vonatkozó minták hatástalanok,
   bárhol is legyenek definiálva.
   Tegyél egy visszaperjelet ("`\`") az első "`!`" elé az olyan
   mintáknál, amelyek szó szerinti "`!`"-lel kezdődnek, például
   "`\!important!.txt`".

 - A perjelet ("`/`") használja könyvtárelválasztóként. Az elválasztók a
   `.gitignore` keresési minta elején, közepén vagy végén fordulhatnak elő.

 - Ha a minta elején vagy közepén (vagy mindkét helyen) van elválasztó,
   akkor a minta az adott `.gitignore` fájl könyvtárszintjéhez képest
   értendő. Egyébként a minta a `.gitignore` szintje alatti bármely
   szinten is illeszkedhet.

 - A munkakönyvtáron kívüli exclude-forrásokból, például a
   $GIT_COMMON_DIR/info/exclude-ból és a core.excludesFile-ból beolvasott
   mintákat úgy kezeli, mintha a munkakönyvtár gyökerében lennének
   megadva, azaz az ilyen mintákban a kezdő "/" a repository gyökeréhez
   rögzíti az illeszkedést.

 - Ha a minta végén van elválasztó, akkor a minta csak könyvtárakra
   illeszkedik, egyébként a minta fájlokra és könyvtárakra egyaránt
   illeszkedhet.

 - Például a `doc/frotz/` minta illeszkedik a `doc/frotz` könyvtárra, de
   az `a/doc/frotz` könyvtárra nem; a `frotz/` viszont illeszkedik a
   `frotz`-ra és az `a/frotz`-ra, ha az könyvtár (minden elérési út a
   `.gitignore` fájlhoz képest relatív).

 - Egy csillag ("`*`") mindenre illeszkedik a perjel kivételével.
   A "`?`" karakter bármely egyetlen karakterre illeszkedik a "`/`"
   kivételével.
   A tartományjelölés, pl. `[a-zA-Z]`, egy tartományba eső karakterek
   egyikére való illesztéshez használható. Részletesebb leírásért lásd az
   fnmatch(3)-at és az FNM_PATHNAME kapcsolót.

 - A visszaperjel ("`\`") bármely karakter escapelésére használható. Pl. a
   "`\*`" szó szerinti csillagra illeszkedik (és a "`\a`" az "`a`"-ra
   illeszkedik, még ha ott nincs is szükség escapelésre). Az fnmatch(3)-hoz
   hasonlóan a minta végén álló visszaperjel érvénytelen minta, amely
   sosem illeszkedik.

A teljes elérési úthoz illesztett mintákban két egymást követő csillagnak
("`**`") speciális jelentése lehet:

 - Egy kezdő "`**`", amelyet perjel követ, minden könyvtárban való
   illeszkedést jelent. Például a "`**/foo`" bárhol illeszkedik a "`foo`"
   fájlra vagy könyvtárra, ugyanúgy, mint a "`foo`" minta. A
   "`**/foo/bar`" bárhol illeszkedik a "`bar`" fájlra vagy könyvtárra,
   amely közvetlenül a "`foo`" könyvtár alatt van.

 - Egy záró "`/**`" mindenre illeszkedik, ami belül van. Például az
   "`abc/**`" az "`abc`" könyvtáron belüli összes fájlra illeszkedik, a
   `.gitignore` fájl helyéhez képest, végtelen mélységben.

 - Egy perjel, amelyet két egymást követő csillag, majd egy perjel követ,
   nulla vagy több könyvtárra illeszkedik. Például az "`a/**/b`"
   illeszkedik az "`a/b`"-re, "`a/x/b`"-re, "`a/x/y/b`"-re és így tovább.

 - Az egyéb egymást követő csillagokat normál csillagoknak tekinti, és az
   előző szabályok szerint illeszkednek.

CONFIGURATION
-------------

Az opcionális `core.excludesFile` konfigurációs változó egy olyan fájl
elérési útját jelöli, amely a kizárandó fájlnevek mintáit tartalmazza,
hasonlóan a `$GIT_COMMON_DIR/info/exclude`-hoz. Az exclude-fájlban lévő
minták a `$GIT_COMMON_DIR/info/exclude`-ban lévőkön felül használatosak.

NOTES
-----

A gitignore fájlok célja annak biztosítása, hogy bizonyos, a Git által
nem követett fájlok követetlenek maradjanak.

Egy jelenleg követett fájl követésének megszüntetéséhez használd a
'git rm --cached'-et a fájl indexből való eltávolításához. A fájlnév
ezután hozzáadható a `.gitignore` fájlhoz, hogy a fájl a későbbi
commitokban ne kerüljön újra be.

A Git nem követi a szimbolikus linkeket, amikor a munkakönyvtárban lévő
`.gitignore` fájlhoz fér hozzá. Ez konzisztensen tartja a viselkedést,
amikor a fájlhoz az indexből vagy egy fából, szemben a fájlrendszerből
férnek hozzá.

EXAMPLES
--------

 - A `hello.*` minta minden olyan fájlra vagy könyvtárra illeszkedik,
   amelynek neve `hello.`-tal kezdődik. Ha ezt csak a könyvtárra
   szeretnénk korlátozni, az alkönyvtáraira nem, a minta elé perjelet
   tehetünk, azaz `/hello.*`; a minta most már illeszkedik a
   `hello.txt`-re, `hello.c`-re, de az `a/hello.java`-ra nem.

 - A `foo/` minta illeszkedik a `foo` könyvtárra és az alatta lévő
   elérési utakra, de nem illeszkedik egy `foo` nevű normál fájlra vagy
   szimbolikus linkre (ez összhangban van azzal, ahogy a pathspec
   általában működik a Gitben)

 - A `doc/frotz` és a `/doc/frotz` minta minden `.gitignore` fájlban
   ugyanazt a hatást fejti ki. Más szóval a kezdő perjel nem lényeges, ha
   a mintában már van középső perjel.

 - A `foo/*` minta illeszkedik a `foo/test.json`-ra (normál fájl), a
   `foo/bar`-ra (könyvtár), de nem illeszkedik a `foo/bar/hello.c`-re
   (normál fájl), mivel a mintában lévő csillag nem illeszkedik a
   `bar/hello.c`-re, amelyben perjel van.

--------------------------------------------------------------
    $ git status
    [...]
    # Untracked files:
    [...]
    #       Documentation/foo.html
    #       Documentation/gitignore.html
    #       file.o
    #       lib.a
    #       src/internal.o
    [...]
    $ cat .git/info/exclude
    # ignore objects and archives, anywhere in the tree.
    *.[oa]
    $ cat Documentation/.gitignore
    # ignore generated html files,
    *.html
    # except foo.html which is maintained by hand
    !foo.html
    $ git status
    [...]
    # Untracked files:
    [...]
    #       Documentation/foo.html
    [...]
--------------------------------------------------------------

Egy másik példa:

--------------------------------------------------------------
    $ cat .gitignore
    vmlinux*
    $ ls arch/foo/kernel/vm*
    arch/foo/kernel/vmlinux.lds.S
    $ echo '!/vmlinux*' >arch/foo/kernel/.gitignore
--------------------------------------------------------------

A második .gitignore megakadályozza, hogy a Git figyelmen kívül hagyja az
`arch/foo/kernel/vmlinux.lds.S`-t.

Példa arra, hogyan zárj ki mindent egy adott `foo/bar` könyvtár
kivételével (figyeld a `/*`-ot – a perjel nélkül a helyettesítő karakter
a `foo/bar`-on belül is mindent kizárna):

--------------------------------------------------------------
    $ cat .gitignore
    # exclude everything except directory foo/bar
    /*
    !/foo
    /foo/*
    !/foo/bar
--------------------------------------------------------------

SEE ALSO
--------
linkgit:git-rm[1],
linkgit:gitrepository-layout[5],
linkgit:git-check-ignore[1]

GIT
---
A linkgit:git[1] csomag része
