gitk(1)
=======

NAME
----
gitk - A Git repository-böngésző

SYNOPSIS
--------
[verse]
'gitk' [<options>] [<revision-range>] [--] [<path>...]

DESCRIPTION
-----------
Megjeleníti egy repository vagy commitok egy kiválasztott halmazának
változásait. Ez magában foglalja a commit-gráf vizualizálását, az egyes
commitokhoz kapcsolódó információk és az egyes revíziók fáiban lévő fájlok megjelenítését.

OPTIONS
-------

Annak vezérléséhez, hogy mely revíziók jelenjenek meg, a gitk támogatja
a 'git rev-list' parancsra alkalmazható opciók legtöbbjét.  Támogat
néhány, a 'git diff-*' parancsokra alkalmazható opciót is, amelyekkel
szabályozható, hogyan jelenjenek meg az egyes commitok által bevezetett
változások.  Végül támogat néhány gitk-specifikus opciót.

A gitk általában csak a 'stuck' (tapadó) alakban megadott, argumentumos
opciókat érti (lásd linkgit:gitcli[7]) a parancssori értelmező
korlátai miatt.

[[_rev_list_options_and_arguments]]
rev-list opciók és argumentumok
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Ez a kézikönyvoldal csak a leggyakrabban használt opciókat írja le.  A
teljes listáért lásd a linkgit:git-rev-list[1] oldalt.

--all::

	Az összes ref megjelenítése (branchek, tagek stb.).

--branches[=<pattern>]::
--tags[=<pattern>]::
--remotes[=<pattern>]::

	Úgy tesz, mintha az összes branch (illetve tag, remote branch)
	fel lenne sorolva a parancssorban '<commit>'-ként. Ha meg van
	adva '<pattern>', a refeket az adott shell-globra illeszkedőkre
	korlátozza. Ha a mintából hiányzik a '?', '{asterisk}' vagy '[',
	a végére '/{asterisk}' értendő.

--since=<date>::

	Egy adott dátumnál újabb commitok megjelenítése.

--until=<date>::

	Egy adott dátumnál régebbi commitok megjelenítése.

--date-order::

	A commitok dátum szerinti rendezése, amikor lehetséges.

--merge::

	Miután egy merge-kísérlet konfliktusokkal leáll, megjeleníti a két
	branch (azaz a HEAD és a MERGE_HEAD) közötti előzményben azokat a
	commitokat, amelyek módosítják a konfliktusos fájlokat, és nem
	léteznek minden merge-elt head-en.

--left-right::

	Megjelöli, hogy egy szimmetrikus különbség melyik oldaláról
	érhető el egy commit.  A bal oldali commitok elé `<` szimbólum,
	a jobb oldaliak elé `>` szimbólum kerül.

--full-history::

	Amikor az előzményt '<path>...'-tal szűröd, nem nyes le bizonyos
	előzményrészeket.  (Részletesebb magyarázatért lásd a "History
	simplification" szakaszt a linkgit:git-log[1] oldalon.)

--simplify-merges::

	A `--full-history` kiegészítő opciója, amely eltávolít néhány
	fölösleges merge-et az eredményül kapott előzményből, mivel
	nincs olyan kiválasztott commit, amely hozzájárulna ehhez a
	merge-hez.  (Részletesebb magyarázatért lásd a "History
	simplification" szakaszt a linkgit:git-log[1] oldalon.)

--ancestry-path::

	Amikor megjelenítendő commit-tartomány van megadva
	(pl. 'commit1..commit2' vagy 'commit2 {caret}commit1'), csak
	azokat a commitokat jeleníti meg, amelyek közvetlenül a
	'commit1' és 'commit2' közötti leszármazási láncon vannak, azaz
	azokat, amelyek egyszerre leszármazottai a 'commit1'-nek és
	ősei a 'commit2'-nek.  (Részletesebb magyarázatért lásd a
	"History simplification" szakaszt a linkgit:git-log[1] oldalon.)

include::line-range-options.adoc[]

<revision range>::

	Korlátozza a megjelenítendő revíziókat. Ez lehet egyetlen revízió,
	ami az adott revíziótól visszafelé való megjelenítést jelenti, vagy
	lehet egy tartomány "'<from>'..'<to>'" alakban, ami a '<from>' és
	'<to>' közötti összes revíziót megjeleníti. Megjegyzés: fejlettebb
	revíziókiválasztás is alkalmazható. Az objektumnevek leírási
	módjainak teljesebb listájáért lásd a linkgit:gitrevisions[7] oldalt.

<path>...::

	A commitokat az adott elérési utakon lévő fájlokat érintőkre korlátozza.
	Megjegyzés: a revíziónevekkel való kétértelműség elkerülésére használj
	"--"-t az elérési utak elválasztására a megelőző opcióktól.

[[_gitk_specific_options]]
gitk-specifikus opciók
~~~~~~~~~~~~~~~~~~~~~~

--argscmd=<command>::

	Minden alkalommal lefuttatandó parancs, amikor a gitknek meg kell
	határoznia a megjelenítendő revíziótartományt.  A parancstól elvárt,
	hogy a standard kimenetére kiírja a megjelenítendő további revíziók
	listáját, soronként egyet.  Ezt használd a '<revision-range>' explicit
	megadása helyett, ha a megjelenítendő commitok halmaza frissítésről
	frissítésre változhat.

--select-commit=<ref>::

	A megadott commit kijelölése a gráf betöltése után.
	Az alapértelmezett viselkedés egyenértékű a '--select-commit=HEAD' megadásával.

[[_examples]]
Példák
------
gitk v2.6.12.. include/scsi drivers/scsi::

	A 'v2.6.12' verzió óta történt változások megjelenítése, amelyek
	az include/scsi vagy drivers/scsi alkönyvtárakban módosítottak fájlt

gitk --since="2 weeks ago" \-- gitk::

	A 'gitk' fájl elmúlt két hétben történt változásainak megjelenítése.
	A "--" szükséges a 'gitk' nevű *branch*-csel való összetévesztés
	elkerüléséhez

gitk --max-count=100 --all \-- Makefile::

	A 'Makefile' fájlon végzett legfeljebb 100 változás megjelenítése. Ahelyett,
	hogy csak a jelenlegi branchen keresne változásokat, az összes branchen keres.

[[_files]]
Fájlok
------
A felhasználói konfiguráció és beállítások tárolási helye:

* `$XDG_CONFIG_HOME/git/gitk`, ha létezik, egyébként
* `$HOME/.gitk`, ha létezik

Ha a fentiek egyike sem létezik, akkor a `$XDG_CONFIG_HOME/git/gitk` jön
létre, és az lesz alapból használva. Ha a '$XDG_CONFIG_HOME' nincs
beállítva, minden esetben a `$HOME/.config` az alapértelmezés.

[[_history]]
Történet
--------
A Gitk volt az első grafikus repository-böngésző, Paul Mackerras
írta Tcl/Tk-ban.

A 'gitk' valójában független projektként karbantartott, de a stabil
verziók a Git csomag részeként vannak terjesztve a végfelhasználók
kényelme érdekében.

A `gitk-git/` Johannes Sixt gitk projektjéből származik:

	https://github.com/j6t/gitk

SEE ALSO
--------
'qgit(1)'::
	C++-ban, Qt használatával írt repository-böngésző.

'tig(1)'::
	Minimalista repository-böngésző és Git-eszközkimenet-kiemelő, C-ben,
	Ncurses használatával írva.

GIT
---
A linkgit:git[1] csomag része
