gitmailmap(5)
=============

NAME
----
gitmailmap - Szerző/committer nevek és/vagy e-mail-címek leképezése

SYNOPSIS
--------
$GIT_WORK_TREE/.mailmap


DESCRIPTION
-----------

Ha a `.mailmap` fájl létezik a repository legfelső szintjén, vagy a
`mailmap.file` vagy `mailmap.blob` konfigurációs opciók által
megadott helyen (lásd linkgit:git-config[1]), akkor a Git ezt
használja a szerző- és committer-nevek, valamint e-mail-címek
kanonikus valódi nevekre és e-mail-címekre való leképezéséhez.


SYNTAX
------

A '#' karakter a sor végéig tartó megjegyzést kezd, az üres sorok
figyelmen kívül maradnak.

Az egyszerű formában a fájl minden sora egy szerző kanonikus valódi
nevéből, whitespace-ből és a commitban használt e-mail-címből (a '<'
és '>' közé zárva) áll, amelyet a névre kell leképezni. Például:
--
	Proper Name <commit@email.xx>
--

A bonyolultabb formák:
--
	<proper@email.xx> <commit@email.xx>
--
amely lehetővé teszi, hogy a mailmap csak egy commit e-mail-részét
cserélje le, és:
--
	Proper Name <proper@email.xx> <commit@email.xx>
--
amely lehetővé teszi, hogy a mailmap a megadott commit-e-mail-címre
illeszkedő commit nevét és e-mailjét is lecserélje, és:
--
	Proper Name <proper@email.xx> Commit Name <commit@email.xx>
--
amely lehetővé teszi, hogy a mailmap a megadott commit-névre és
e-mail-címre egyaránt illeszkedő commit nevét és e-mailjét is
lecserélje.

Az e-mailek és a nevek illesztése egyaránt kis-nagybetűtől függetlenül
történik. Például ez is illeszkedne a fenti
'Commit Name <commit&#64;email.xx>'-re:
--
	Proper Name <proper@email.xx> CoMmIt NaMe <CoMmIt@EmAiL.xX>
--

NOTES
-----

A Git nem követi a szimbolikus linkeket, amikor a working tree-ben lévő
`.mailmap` fájlhoz fér hozzá. Ez konzisztensen tartja a viselkedést
akkor is, amikor a fájlhoz az indexből vagy egy tree-ből férnek hozzá,
és akkor is, amikor a fájlrendszerből.

EXAMPLES
--------

Az előzményed két szerző, Jane és Joe commitjait tartalmazza, akiknek
a neve több alakban is megjelenik a repository-ban:

------------
Joe Developer <joe@example.com>
Joe R. Developer <joe@example.com>
Jane Doe <jane@example.com>
Jane Doe <jane@laptop.(none)>
Jane D. <jane@desktop.(none)>
------------

Most tegyük fel, hogy Joe azt szeretné, hogy a középső neve kezdőbetűjét
használják, Jane pedig a vezetéknevét teljesen kiírva szeretné. Egy
`.mailmap` fájl, amely javítja a neveket, így nézne ki:

------------
Joe R. Developer <joe@example.com>
Jane Doe <jane@example.com>
Jane Doe <jane@desktop.(none)>
------------

Vedd figyelembe, hogy nincs szükség a '<jane&#64;laptop.(none)>' nevének
leképezésére csak a nevek javításához. Azonban a nyilvánvalóan hibás
'<jane&#64;laptop.(none)>' és '<jane&#64;desktop.(none)>' e-mailek
változatlanul hagyása általában nem az, amit szeretnél. Egy `.mailmap`
fájl, amely ezeket is javítja:

------------
Joe R. Developer <joe@example.com>
Jane Doe <jane@example.com> <jane@laptop.(none)>
Jane Doe <jane@example.com> <jane@desktop.(none)>
------------

Végül tegyük fel, hogy Joe és Jane megosztott egy e-mail-címet, de a
nevet nem, például úgy, hogy egy hibabejelentő rendszer által generált
alábbi két commit szerepel az előzményben. Azaz a nevek így jelennek
meg az előzményben:

------------
Joe <bugs@example.com>
Jane <bugs@example.com>
------------

Egy teljes `.mailmap` fájl, amely ezeket az eseteket is kezeli (két sor
hozzáadása a fenti példához), így nézne ki:

------------
Joe R. Developer <joe@example.com>
Jane Doe <jane@example.com> <jane@laptop.(none)>
Jane Doe <jane@example.com> <jane@desktop.(none)>
Joe R. Developer <joe@example.com> Joe <bugs@example.com>
Jane Doe <jane@example.com> Jane <bugs@example.com>
------------



SEE ALSO
--------
linkgit:git-check-mailmap[1]


GIT
---
A linkgit:git[1] csomag része
