gitprotocol-http(5)
===================

NAME
----
gitprotocol-http - Git HTTP-alapú protokollok


SYNOPSIS
--------
[verse]
<over-the-wire-protocol>


DESCRIPTION
-----------

A Git két HTTP-alapú átviteli protokollt támogat.  Egy "dumb" protokollt,
amely csak egy szabványos HTTP-szervert igényel a kapcsolat
szerveroldalán, és egy "smart" protokollt, amely egy Git-tudatos CGI-t
(vagy szervermodult) igényel.  Ez a dokumentum mindkét protokollt leírja.

Tervezési jellemzőként a smart kliensek automatikusan frissíteni tudják a "dumb"
protokoll URL-eket smart URL-ekké.  Ez lehetővé teszi, hogy minden felhasználónak
ugyanaz a közzétett URL-je legyen, és a peerek automatikusan a számukra
elérhető leghatékonyabb átvitelt választják.


[[_url_format]]
URL-formátum
------------

A HTTP-n keresztül elért Git repository-k URL-jei a szabványos HTTP
URL-szintaxist használják, amelyet az RFC 1738 dokumentál, tehát a következő
alakúak:

  http://<host>:<port>/<path>?<searchpart>

Ebben a dokumentációban a `$GIT_URL` helyőrző a végfelhasználó által
megadott http:// repository URL-t jelöli.

A szervereknek SHOULD kezelniük minden, a `$GIT_URL`-lel egyező helyekre
irányuló kérést, mivel a Git által használt "smart" és "dumb" HTTP-protokollok
egyaránt úgy működnek, hogy további útvonal-komponenseket fűznek a
felhasználó által megadott `$GIT_URL` sztring végéhez.

Egy dumb kliens példája, amely egy laza objektumot kér:

  $GIT_URL:     http://example.com:8080/git/repo.git
  URL request:  http://example.com:8080/git/repo.git/objects/d0/49f6c27a2244e12041955e262a404c7faba355

Egy smart kérés példája egy catch-all átjáróhoz:

  $GIT_URL:     http://example.com/daemon.cgi?svc=git&q=
  URL request:  http://example.com/daemon.cgi?svc=git&q=/info/refs&service=git-receive-pack

Egy submodule-hoz intézett kérés példája:

  $GIT_URL:     http://example.com/git/repo.git/path/submodule.git
  URL request:  http://example.com/git/repo.git/path/submodule.git/info/refs

A klienseknek MUST eltávolítaniuk a záró `/`-t, ha van, a felhasználó
által megadott `$GIT_URL` sztringből, hogy megelőzzék üres útvonal-tokenek (`//`)
megjelenését bármely, a szerverhez küldött URL-ben.  A kompatibilis klienseknek
MUST kibontaniuk a `$GIT_URL/info/refs`-t `foo/info/refs`-ként, nem `foo//info/refs`-ként.


Authentication
--------------

Szabványos HTTP-hitelesítés van használva, ha hitelesítés szükséges
egy repository eléréséhez, és ezt a HTTP-szerverszoftver MAY konfigurálhatja és
kényszerítheti ki.

Mivel a Git repository-kat szabványos útvonal-komponensekkel érik el,
a szerver adminisztrátorok MAY könyvtár-alapú jogosultságokat használhatnak a
HTTP-szerverükön belül a repository-hozzáférés szabályozására.

A klienseknek SHOULD támogatniuk az RFC 2617-ben leírt Basic hitelesítést.
A szervereknek SHOULD támogatniuk a Basic hitelesítést a Git-szerverszoftver
elé helyezett HTTP-szerverre támaszkodva.

A szervereknek SHOULD NOT megkövetelniük HTTP-sütiket hitelesítési
vagy hozzáférés-szabályozási célokra.

A kliensek és szerverek MAY támogathatnak más gyakori HTTP-alapú
hitelesítési formákat is, mint például a Digest hitelesítést.


SSL
---

A klienseknek és szervereknek SHOULD támogatniuk az SSL-t, különösen a
jelszavak védelmére, amikor Basic HTTP-hitelesítésre támaszkodnak.


[[_session_state]]
Munkamenet-állapot
------------------

A Git-over-HTTP protokoll (nagyon hasonlóan magához a HTTP-hez) állapotmentes
a HTTP-szerveroldal szempontjából.  Minden állapotot MUST a kliensfolyamatnak
megőriznie és kezelnie.  Ez lehetővé teszi az egyszerű round-robin
terheléselosztást a szerveroldalon, anélkül hogy az állapotkezeléssel kellene
foglalkozni.

A klienseknek MUST NOT megkövetelniük állapotkezelést a szerveroldalon a
helyes működéshez.

A szervereknek MUST NOT megkövetelniük HTTP-sütiket a helyes működéshez.
A kliensek MAY tárolhatnak és továbbíthatnak HTTP-sütiket a kérésfeldolgozás során,
ahogy azt az RFC 2616 (HTTP/1.1) leírja.  A szervereknek SHOULD figyelmen kívül
hagyniuk minden, a kliens által küldött sütit.


[[_general_request_processing]]
Általános kérésfeldolgozás
--------------------------

Ahol nincs másképp jelezve, minden szabványos HTTP-viselkedést SHOULD
feltételezni mind a kliens, mind a szerver részéről.  Ez magában foglalja
(de nem feltétlenül korlátozódik rá):

Ha nincs repository a `$GIT_URL`-nél, vagy a `$GIT_URL`-lel egyező
helyre mutatott erőforrás nem létezik, a szervernek MUST NOT `200 OK`
válasszal válaszolnia.  A szervernek SHOULD
`404 Not Found`, `410 Gone`, vagy bármely más megfelelő HTTP-státuszkóddal válaszolnia,
amely nem sugallja, hogy az erőforrás a kért formában létezik.

Ha van repository a `$GIT_URL`-nél, de a hozzáférés jelenleg nincs
engedélyezve, a szervernek MUST a `403 Forbidden` HTTP-
státuszkóddal válaszolnia.

A szervereknek SHOULD támogatniuk mind a HTTP 1.0-t, mind a HTTP 1.1-et.
A szervereknek SHOULD támogatniuk a chunked kódolást mind a kérés-, mind a válasz-
törzsekhez.

A klienseknek SHOULD támogatniuk mind a HTTP 1.0-t, mind a HTTP 1.1-et.
A klienseknek SHOULD támogatniuk a chunked kódolást mind a kérés-, mind a válasz-
törzsekhez.

A szerverek MAY visszaadhatnak ETag és/vagy Last-Modified fejléceket.

A kliensek MAY újraérvényesíthetik a gyorsítótárazott entitásokat
If-Modified-Since és/vagy If-None-Match kérésfejlécek belefoglalásával.

A szerverek MAY visszaadhatják a `304 Not Modified`-t, ha a releváns fejlécek
megjelennek a kérésben, és az entitás nem változott.  A klienseknek MUST a
`304 Not Modified`-t a `200 OK`-val azonosan kezelniük, a gyorsítótárazott entitás újrafelhasználásával.

A kliensek MAY újrahasználhatnak egy gyorsítótárazott entitást újraérvényesítés
nélkül, ha a Cache-Control és/vagy Expires fejléc engedélyezi a gyorsítótárazást.  A
klienseknek és szervereknek MUST követniük az RFC 2616-ot a cache-vezérléshez.


[[_discovering_references]]
Referenciák felfedezése
-----------------------

Minden HTTP-kliensnek MUST egy fetch vagy push csere elkezdésekor
felfedeznie a remote repository-n elérhető referenciákat.

[[_dumb_clients]]
Dumb kliensek
~~~~~~~~~~~~~

Azoknak a HTTP-klienseknek, amelyek csak a "dumb" protokollt támogatják,
MUST felfedezniük a referenciákat a repository speciális info/refs fájljára
tett kéréssel.

A dumb HTTP-klienseknek MUST `GET` kérést tenniük a `$GIT_URL/info/refs`-re,
bármilyen search/query paraméter nélkül.

   C: GET $GIT_URL/info/refs HTTP/1.0

   S: 200 OK
   S:
   S: 95dcfa3633004da0049d3d0fa03f80589cbcaf31	refs/heads/maint
   S: d049f6c27a2244e12041955e262a404c7faba355	refs/heads/master
   S: 2cb58b79488a98d2721cea644875a8dd0026b115	refs/tags/v1.0
   S: a3c2e2402b99163d1d59756e5f207ae21cccba4c	refs/tags/v1.0^{}

A visszaadott info/refs entitás Content-Type-jának SHOULD
`text/plain; charset=utf-8`-nak lennie, de MAY bármilyen content type is lehet.
A klienseknek MUST NOT megkísérelniük a visszaadott Content-Type ellenőrzését.
A dumb szervereknek MUST NOT olyan return type-ot visszaadniuk, amely
`application/x-git-`-vel kezdődik.

Cache-Control fejlécek MAY visszaadhatók a visszaadott entitás gyorsítótárazásának
letiltásához.

A válasz vizsgálatakor a klienseknek SHOULD csak a HTTP-
státuszkódot vizsgálniuk.  Az érvényes válaszok a `200 OK`, vagy a `304 Not Modified`.

A visszaadott tartalom egy UNIX-formátumú szöveges fájl, amely leír
minden refet és annak ismert értékét.  A fájlnak SHOULD a
C locale-rendezés szerint névre rendezettnek lennie.  A fájlnak SHOULD NOT tartalmaznia
a `HEAD` nevű alapértelmezett refet.

  info_refs   =  *( ref_record )
  ref_record  =  any_ref / peeled_ref

  any_ref     =  obj-id HTAB refname LF
  peeled_ref  =  obj-id HTAB refname LF
		 obj-id HTAB refname "^{}" LF

[[_smart_clients]]
Smart kliensek
~~~~~~~~~~~~~~

Azoknak a HTTP-klienseknek, amelyek támogatják a "smart" protokollt (vagy
mind a "smart", mind a "dumb" protokollt), MUST felfedezniük a referenciákat
a repository info/refs fájljára tett paraméterezett kéréssel.

A kérésnek MUST pontosan egy query paramétert tartalmaznia, a
`service=$servicename`-et, ahol a `$servicename`-nek MUST annak a
szolgáltatásnak a neve lennie, amelyet a kliens fel kíván venni a művelet befejezéséhez.
A kérés MUST NOT további query paramétereket tartalmaznia.

   C: GET $GIT_URL/info/refs?service=git-upload-pack HTTP/1.0

dumb szerver válasza:

   S: 200 OK
   S:
   S: 95dcfa3633004da0049d3d0fa03f80589cbcaf31	refs/heads/maint
   S: d049f6c27a2244e12041955e262a404c7faba355	refs/heads/master
   S: 2cb58b79488a98d2721cea644875a8dd0026b115	refs/tags/v1.0
   S: a3c2e2402b99163d1d59756e5f207ae21cccba4c	refs/tags/v1.0^{}

smart szerver válasza:

   S: 200 OK
   S: Content-Type: application/x-git-upload-pack-advertisement
   S: Cache-Control: no-cache
   S:
   S: 001e# service=git-upload-pack\n
   S: 0000
   S: 004895dcfa3633004da0049d3d0fa03f80589cbcaf31 refs/heads/maint\0multi_ack\n
   S: 003fd049f6c27a2244e12041955e262a404c7faba355 refs/heads/master\n
   S: 003c2cb58b79488a98d2721cea644875a8dd0026b115 refs/tags/v1.0\n
   S: 003fa3c2e2402b99163d1d59756e5f207ae21cccba4c refs/tags/v1.0^{}\n
   S: 0000

A kliens elküldhet Extra Parameters-t (lásd
linkgit:gitprotocol-pack[5]) kettősponttal elválasztott sztringként
a Git-Protocol HTTP-fejlécben.

A linkgit:git-upload-pack[1] `--http-backend-info-refs` opcióját
használja.

[[_dumb_server_response]]
Dumb szerver válasza
^^^^^^^^^^^^^^^^^^^^
A dumb szervereknek MUST a dumb szerver válaszformátumával válaszolniuk.

A dumb szerver válaszának részletesebb leírásáért lásd az előző, dumb
klienseket tárgyaló szakaszt.

[[_smart_server_response]]
Smart szerver válasza
^^^^^^^^^^^^^^^^^^^^^
Ha a szerver nem ismeri fel a kért szolgáltatásnevet, vagy a kért
szolgáltatásnév le van tiltva a szerver adminisztrátora által, a
szervernek MUST a `403 Forbidden` HTTP-státuszkóddal válaszolnia.

Egyébként a smart szervereknek MUST a smart szerver válaszformátumával
válaszolniuk a kért szolgáltatásnévhez.

Cache-Control fejlécek SHOULD legyenek használva a visszaadott entitás
gyorsítótárazásának letiltásához.

A Content-Type-nak MUST `application/x-$servicename-advertisement`-nek lennie.
A klienseknek SHOULD visszaesniük a dumb protokollra, ha másik content
type kerül visszaadásra.  A dumb protokollra való visszaeséskor a klienseknek
SHOULD NOT további kérést tenniük a `$GIT_URL/info/refs`-re, hanem
SHOULD a már kéznél lévő választ használniuk.  A klienseknek MUST NOT
folytatniuk, ha nem támogatják a dumb protokollt.

A klienseknek MUST ellenőrizniük, hogy a státuszkód `200 OK` vagy
`304 Not Modified`.

A klienseknek MUST ellenőrizniük, hogy a válasz entitás első öt bájtja
illeszkedik a `^[0-9a-f]{4}#` regexre.  Ha ez a teszt sikertelen, a kliensek
MUST NOT folytatniuk.

A klienseknek MUST a teljes választ pkt-line rekordok sorozataként
elemezniük.

A klienseknek MUST ellenőrizniük, hogy az első pkt-line `# service=$servicename`.
A szervereknek MUST a $servicename-et a kérésparaméter értékére állítaniuk.
A szervereknek SHOULD LF-et tartalmazniuk e sor végén.
A klienseknek MUST figyelmen kívül hagyniuk a sor végi LF-et.

A szervereknek MUST a `0000` mágikus záró pkt-line jelölővel lezárniuk
a választ.

A visszaadott válasz egy pkt-line stream, amely leír minden refet és
annak ismert értékét.  A streamnek SHOULD a C locale-rendezés szerint névre
rendezettnek lennie.  A streamnek SHOULD tartalmaznia a `HEAD` nevű
alapértelmezett refet első refként.  A streamnek MUST tartalmaznia a
képesség-deklarációkat egy NUL mögött az első refnél.

A visszaadott válasz "version 1"-et tartalmaz, ha "version=1" lett elküldve
Extra Parameter-ként.

  smart_reply     =  PKT-LINE("# service=$servicename" LF)
		     "0000"
		     *1("version 1")
		     ref_list
		     "0000"
  ref_list        =  empty_list / non_empty_list

  empty_list      =  PKT-LINE(zero-id SP "capabilities^{}" NUL cap-list LF)

  non_empty_list  =  PKT-LINE(obj-id SP name NUL cap_list LF)
		     *ref_record

  cap-list        =  capability *(SP capability)
  capability      =  1*(LC_ALPHA / DIGIT / "-" / "_")
  LC_ALPHA        =  %x61-7A

  ref_record      =  any_ref / peeled_ref
  any_ref         =  PKT-LINE(obj-id SP name LF)
  peeled_ref      =  PKT-LINE(obj-id SP name LF)
		     PKT-LINE(obj-id SP name "^{}" LF


[[_smart_service_git_upload_pack]]
Smart szolgáltatás: git-upload-pack
-----------------------------------
Ez a szolgáltatás a `$GIT_URL` által mutatott repository-ból olvas.

A klienseknek MUST először ref-felfedezést végezniük a
`$GIT_URL/info/refs?service=git-upload-pack`-kal.

   C: POST $GIT_URL/git-upload-pack HTTP/1.0
   C: Content-Type: application/x-git-upload-pack-request
   C:
   C: 0032want 0a53e9ddeaddad63ad106860237bbf53411d11a7\n
   C: 0032have 441b40d833fdfa93eb2908e52742248faf0ee993\n
   C: 0000

   S: 200 OK
   S: Content-Type: application/x-git-upload-pack-result
   S: Cache-Control: no-cache
   S:
   S: ....ACK %s, continue
   S: ....NAK

A klienseknek MUST NOT újrahasználniuk vagy újraérvényesíteniük egy
gyorsítótárazott választ. A szervereknek MUST elegendő Cache-Control
fejlécet tartalmazniuk a válasz gyorsítótárazásának megakadályozásához.

A szervereknek SHOULD támogatniuk minden itt definiált képességet.

A klienseknek MUST legalább egy "want" parancsot küldeniük a kérés törzsében.
A klienseknek MUST NOT olyan id-re hivatkozniuk egy "want" parancsban, amely nem
jelent meg a ref-felfedezés révén kapott válaszban, hacsak a
szerver nem hirdeti az `allow-tip-sha1-in-want` vagy
`allow-reachable-sha1-in-want` képességet.

  compute_request   =  want_list
		       have_list
		       request_end
  request_end       =  "0000" / "done"

  want_list         =  PKT-LINE(want SP cap_list LF)
		       *(want_pkt)
  want_pkt          =  PKT-LINE(want LF)
  want              =  "want" SP id
  cap_list          =  capability *(SP capability)

  have_list         =  *PKT-LINE("have" SP id LF)

TODO: Ezt részletesebben dokumentálni kell.

[[_the_negotiation_algorithm]]
A tárgyalási algoritmus
~~~~~~~~~~~~~~~~~~~~~~~
A minimális pack kiválasztásának számítása a következőképpen zajlik
(C = kliens, S = szerver):

'init lépés:'

C: Használj ref-felfedezést a hirdetett refek megszerzéséhez.

C: Helyezz minden látott objektumot az `advertised` halmazba.

C: Építs egy üres `common` halmazt, hogy tárold azokat az objektumokat, amelyekről
   később megállapítást nyer, hogy mindkét végén megvannak.

C: Építs egy `want` halmazt az `advertised`-ből származó objektumokból, amelyeket a
   kliens fetchelni akar, azok alapján, amiket a ref-felfedezés során látott.

C: Indíts egy `c_pending` sort, amely commit-idő szerint van rendezve (a
   legújabbat pop-olva elsőként).  Add hozzá az összes kliens-refet.  Amikor egy commit ki lesz véve
   a sorból, a szüleit SHOULD automatikusan visszahelyezni.
   A commitok MUST csak egyszer kerülhetnek be a sorba.

'egy számítási lépés:'

C: Küldj egy `$GIT_URL/git-upload-pack` kérést:

   C: 0032want <want-#1>...............................
   C: 0032want <want-#2>...............................
   ....
   C: 0032have <common-#1>.............................
   C: 0032have <common-#2>.............................
   ....
   C: 0032have <have-#1>...............................
   C: 0032have <have-#2>...............................
   ....
   C: 0000

A stream "commandokra" van szervezve, minden command önmagában
jelenik meg egy pkt-line-ban.  Egy command soron belül
az első szóközig terjedő szöveg a command neve,
a sor további része az első LF-ig pedig az érték.
A command sorok LF-fel vannak lezárva a
pkt-line érték utolsó bájtjaként.

A commandoknak MUST a következő sorrendben megjelenniük, ha egyáltalán
megjelennek a kérés streamben:

* "want"
* "have"

A stream egy pkt-line flush-sal (`0000`) van lezárva.

Egyetlen "want" vagy "have" commandnak MUST egy hex-formátumú
objektumnevet tartalmaznia értékként.  Több objektumnevet MUST több command
küldésével kell elküldeni. Az objektumneveket MUST az `object-format`
képességen keresztül egyeztetett objektumformátumban kell megadni (alapból SHA-1).

A `have` lista a `c_pending`-ből kivett első 32 commit
alapján jön létre.  Kevesebb is megadható, ha a `c_pending` kiürül.

Ha a kliens elküldött 256 "have" commitot, és még nem
kapott vissza egyet sem ezek közül az `s_common`-ból, vagy a kliens
kiürítette a `c_pending`-et, akkor SHOULD tartalmaznia egy "done" commandot, hogy tudassa
a szerverrel, hogy nem folytatja:

   C: 0009done

S: Elemezd a git-upload-pack kérést:

Ellenőrizd, hogy a `want`-ban lévő összes objektum közvetlenül elérhető-e refekből.

A szerver MAY visszafelé bejárhatja a történetet vagy
a reflogot, hogy engedélyezzen kissé elavult kéréseket.

Ha nem érkezik "want" objektum, küldj hibát:
TODO: Definiálni kell a hibát, ha nincs kért "want" sor.

Ha bármely "want" objektum nem elérhető, küldj hibát:
Amikor egy Git-szerver érvénytelen vagy hibásan formázott `want` sort kap, egy
hibaüzenettel válaszol, amely tartalmazza a problémás objektumnevet.

Hozz létre egy üres `s_common` listát.

Ha "have" lett küldve:

Iterálj végig az objektumokon a kliens által megadott sorrendben.

Minden objektumhoz, ha a szervernek megvan az objektum egy
refből elérhetően, add hozzá az `s_common`-hoz.  Ha egy commit hozzáadásra kerül az `s_common`-hoz,
ne adj hozzá semmilyen ősét, még akkor sem, ha azok is megjelennek a `have`-ben.

S: Küldd el a git-upload-pack választ:

Ha a szerver talált egy zárt objektumhalmazt a csomagoláshoz, vagy a
kérés "done"-nal ér véget, a pack-kel válaszol.
TODO: A pack-alapú választ dokumentálni kell

   S: PACK...

A visszaadott stream a git-upload-pack szolgáltatás által támogatott
side-band-64k protokoll, és a pack az 1. streambe van beágyazva.  A
szerveroldali folyamatüzenetek MAY megjelenhetnek a 2. streamben.

Itt egy "zárt objektumhalmaz" úgy van definiálva, hogy legalább
egy útvonal vezet minden "want"-ból legalább egy "common" objektumhoz.

Ha a szervernek több információra van szüksége, egy
status continue válasszal válaszol:
TODO: A nem-pack választ dokumentálni kell

C: Elemezd az upload-pack választ:
   TODO: Az elemzési választ dokumentálni kell

'Végezz egy újabb számítási lépést.'


[[_smart_service_git_receive_pack]]
Smart szolgáltatás: git-receive-pack
------------------------------------
Ez a szolgáltatás a `$GIT_URL` által mutatott repository-ból olvas.

A klienseknek MUST először ref-felfedezést végezniük a
`$GIT_URL/info/refs?service=git-receive-pack`-kal.

   C: POST $GIT_URL/git-receive-pack HTTP/1.0
   C: Content-Type: application/x-git-receive-pack-request
   C:
   C: ....0a53e9ddeaddad63ad106860237bbf53411d11a7 441b40d833fdfa93eb2908e52742248faf0ee993 refs/heads/maint\0 report-status
   C: 0000
   C: PACK....

   S: 200 OK
   S: Content-Type: application/x-git-receive-pack-result
   S: Cache-Control: no-cache
   S:
   S: ....

A klienseknek MUST NOT újrahasználniuk vagy újraérvényesíteniük egy
gyorsítótárazott választ. A szervereknek MUST elegendő Cache-Control
fejlécet tartalmazniuk a válasz gyorsítótárazásának megakadályozásához.

A szervereknek SHOULD támogatniuk minden itt definiált képességet.

A klienseknek MUST legalább egy commandot küldeniük a kérés törzsében.
A kérés törzsének command részén belül a klienseknek SHOULD a
ref-felfedezés révén kapott id-t old_id-ként küldeniük.

  update_request  =  command_list
		     "PACK" <binary-data>

  command_list    =  PKT-LINE(command NUL cap_list LF)
		     *(command_pkt)
  command_pkt     =  PKT-LINE(command LF)
  cap_list        =  *(SP capability) SP

  command         =  create / delete / update
  create          =  zero-id SP new_id SP name
  delete          =  old_id SP zero-id SP name
  update          =  old_id SP new_id SP name

TODO: Ezt részletesebben dokumentálni kell.

REFERENCES
----------

https://www.ietf.org/rfc/rfc1738.txt[RFC 1738: Uniform Resource Locators (URL)]
https://www.ietf.org/rfc/rfc2616.txt[RFC 2616: Hypertext Transfer Protocol -- HTTP/1.1]

SEE ALSO
--------

linkgit:gitprotocol-pack[5]
linkgit:gitprotocol-capabilities[5]

GIT
---
A linkgit:git[1] csomag része
