gitprotocol-v2(5)
=================

NAME
----
gitprotocol-v2 - A Git vezetékprotokoll 2. verziója

SYNOPSIS
--------
[verse]
<over-the-wire-protocol>

DESCRIPTION
-----------

Ez a dokumentum a Git vezetékprotokolljának 2. verziójára vonatkozó
specifikációt mutatja be.  A v2 protokoll az alábbi módokon javít a v1-en:

  * Több szolgáltatásnév helyett több parancsot fog támogatni egyetlen
    szolgáltatás
  * Könnyen bővíthető, mivel a képességek a protokoll saját szekciójába
    kerülnek, és nem rejtőznek tovább egy NUL bájt mögött, sem a pkt-line
    méretkorlátja nem korlátozza őket
  * A NUL bájtok mögé rejtett egyéb információk különválasztása (pl. az
    agent sztring képességként, a symrefek pedig az 'ls-refs' paranccsal
    kérhetők le)
  * A referencia-hirdetés elmarad, hacsak explicit módon nem kérik
  * ls-refs parancs egyes refek explicit lekéréséhez
  * A tervezés a http és a stateless-rpc szem előtt tartásával készült.
    A világos flush-szemantikának köszönhetően a http remote helper
    egyszerűen proxyként tud eljárni

A v2 protokollban a kommunikáció parancs-orientált.  A szerverrel való első
kapcsolatfelvételkor a szerver hirdet egy képességlistát.  Ezen képességek
egy része olyan parancs lesz, amelynek végrehajtását a kliens kérheti.  Egy
parancs befejeződése után a kliens újra felhasználhatja a kapcsolatot, és
kérheti további parancsok végrehajtását.

[[_packet_line_framing]]
Pkt-line keretezés
------------------

Minden kommunikáció pkt-line keretezéssel történik, csakúgy, mint a
v1-ben.  További információért lásd a linkgit:gitprotocol-pack[5]-öt és a
linkgit:gitprotocol-common[5]-öt.

A v2 protokollban ezeknek a speciális csomagoknak a következő szemantikája van:

  * '0000' Flush Packet (flush-pkt) - egy üzenet végét jelzi
  * '0001' Delimiter Packet (delim-pkt) - egy üzenet szekcióit választja el
  * '0002' Response End Packet (response-end-pkt) - egy válasz végét jelzi
    stateless kapcsolatok esetén

[[_initial_client_request]]
Kezdeti klienskérés
-------------------

Egy kliens általában úgy kérheti, hogy a v2 protokollon kommunikáljanak,
hogy elküldi a `version=2` értéket a használt transporthoz tartozó
megfelelő side-channelen keresztül, ami elkerülhetetlenül beállítja a
`GIT_PROTOCOL`-t.  További információ található a linkgit:gitprotocol-pack[5]-ben
és a linkgit:gitprotocol-http[5]-ben, valamint a `GIT_PROTOCOL` definíciójában a
linkgit:git[1]-ben. Minden esetben a szervertől érkező válasz a
képesség-hirdetés.

[[_git_transport]]
Git Transport
~~~~~~~~~~~~~

A git:// transport használatakor a v2 protokoll használatát úgy lehet
kérni, hogy a "version=2" értéket extra paraméterként küldjük el:

   003egit-upload-pack /project.git\0host=myserver.com\0\0version=2\0

[[_ssh_and_file_transport]]
SSH and File Transport
~~~~~~~~~~~~~~~~~~~~~~

Az ssh:// vagy a file:// transport használatakor a GIT_PROTOCOL
környezeti változót explicit módon úgy kell beállítani, hogy tartalmazza
a "version=2"-t.  Előfordulhat, hogy a szervert be kell konfigurálni,
hogy engedélyezze ennek a környezeti változónak az átadását.

[[_http_transport]]
HTTP Transport
~~~~~~~~~~~~~~

A http:// vagy https:// transport használatakor a kliens egy "smart"
info/refs kérést hajt végre, ahogy azt a linkgit:gitprotocol-http[5] leírja, és
kéri, hogy a v2-t használják, a "version=2" megadásával a `Git-Protocol`
fejlécben.

   C: GET $GIT_URL/info/refs?service=git-upload-pack HTTP/1.0
   C: Git-Protocol: version=2

Egy v2 szerver erre így válaszolna:

   S: 200 OK
   S: <Some headers>
   S: ...
   S:
   S: 000eversion 2\n
   S: <capability-advertisement>

A további kéréseket ezután közvetlenül a
`$GIT_URL/git-upload-pack` szolgáltatáshoz intézik. (Ez ugyanígy működik
a git-receive-pack esetén is).

A `--http-backend-info-refs` opciót használja a
linkgit:git-upload-pack[1]-hez.

Előfordulhat, hogy a szervert be kell konfigurálni, hogy ennek a
fejlécnek a tartalmát a `GIT_PROTOCOL` változón keresztül adja tovább.
Lásd a témával kapcsolatos leírást a linkgit:git-http-backend[1]-ben.

[[_capability_advertisement]]
Képesség-hirdetés
-----------------

Egy szerver, amely úgy dönt (egy kliens kérése alapján), hogy a 2-es
protokollverzión kommunikál, ezt úgy jelzi a kliensnek, hogy a
kezdeti válaszában elküld egy verziósztringet, amelyet a képességeinek
hirdetése követ.  Minden képesség egy kulcs egy opcionális értékkel.
A klienseknek figyelmen kívül kell hagyniuk minden ismeretlen kulcsot.
Az ismeretlen értékek szemantikáját az adott kulcs definíciója határozza
meg.  Néhány képesség olyan parancsot ír le, amelynek végrehajtását a
kliens kérheti.

    capability-advertisement = protocol-version
			       capability-list
			       flush-pkt

    protocol-version = PKT-LINE("version 2" LF)
    capability-list = *capability
    capability = PKT-LINE(key[=value] LF)

    key = 1*(ALPHA | DIGIT | "-_")
    value = 1*(ALPHA | DIGIT | " -_.,?\/{}[]()<>!@#$%^&*+=:;")

[[_command_request]]
Parancskérés
------------

A képesség-hirdetés fogadása után a kliens kiadhat egy kérést, amellyel
kiválasztja a kívánt parancsot, tetszőleges konkrét képességekkel vagy
argumentumokkal.  Ezt egy opcionális szekció követi, amelyben a kliens
megadhatja a parancsra jellemző paramétereket vagy lekérdezéseket.
Egyszerre csak egyetlen parancs kérhető.

    request = empty-request | command-request
    empty-request = flush-pkt
    command-request = command
		      capability-list
		      delim-pkt
		      command-args
		      flush-pkt
    command = PKT-LINE("command=" key LF)
    command-args = *command-specific-arg

    command-specific-args are packet line framed arguments defined by
    each individual command.

A szerver ezután ellenőrzi, hogy a kliens kérése egy érvényes parancsból,
valamint a hirdetett érvényes képességekből áll-e.  Ha a kérés érvényes,
a szerver ezután végrehajtja a parancsot.  A szervernek MUST megvárnia,
amíg meg nem kapta a kliens teljes kérését, mielőtt választ adna.  A
válasz formátumát a végrehajtott parancs határozza meg, de minden
esetben egy flush-pkt jelzi a válasz végét.

Amikor egy parancs befejeződött, és a kliens megkapta a szervertől
érkező teljes választ, a kliens vagy egy másik parancs végrehajtását
kérheti, vagy megszakíthatja a kapcsolatot.  A kliens opcionálisan
küldhet egy csak egy flush-pktből álló üres kérést is, jelezve, hogy nem
küld több kérést.

[[_capabilities]]
Képességek
----------

Kétféle képesség létezik: normál képességek, amelyek információ
átadására vagy egy kérés viselkedésének megváltoztatására használhatók,
és parancsok, amelyek azok a fő műveletek, amelyeket a kliens el akar
végezni (fetch, push, stb).

A 2-es protokollverzió alapértelmezés szerint stateless.  Ez azt
jelenti, hogy minden parancsnak csak egyetlen körig szabad tartania, és
a szerveroldal szempontjából stateless-nek kell lennie, hacsak a kliens
nem kért olyan képességet, amely jelzi, hogy a szervernek állapotot
kell fenntartania.  A klienseknek MUST NOT megkövetelniük a
szerveroldali állapotkezelést a helyes működéshez.  Ez lehetővé teszi az
egyszerű round-robin terheléselosztást a szerveroldalon, anélkül, hogy
az állapotkezeléssel kellene foglalkozni.

[[_agent]]
agent
~~~~~

A szerver hirdetheti az `agent` képességet egy `X` értékkel (az
`agent=X` formában), hogy tájékoztassa a klienst arról, hogy a szerver
az `X` verziót futtatja.  A kliens opcionálisan elküldheti a saját agent
sztringjét úgy, hogy az `agent` képességet egy `Y` értékkel (az
`agent=Y` formában) belefoglalja a szerverhez intézett kérésébe (de
ezt MUST NOT megtennie, ha a szerver nem hirdette az agent képességet).
Az `X` és `Y` sztringek bármilyen nyomtatható ASCII karaktert
tartalmazhatnak a szóköz kivételével (azaz a 33 <= x <= 126 bájttartományt),
és jellemzően "package/version-os" alakúak (pl. "git/1.8.3.1-Linux"),
ahol az `os` az operációs rendszer neve (pl. "Linux"). Az `X` és `Y` a
GIT_USER_AGENT környezeti változóval konfigurálható, és ez élvez
elsőbbséget. Az `os`-t az `uname(2)` rendszerhívás 'sysname' mezőjéből
vagy annak megfelelőjéből kérik le. Az agent sztringek pusztán
statisztikai és hibakeresési célú, informatív jellegűek, és MUST NOT
használhatók arra, hogy programozottan feltételezzék bizonyos funkciók
jelenlétét vagy hiányát.

[[_ls_refs]]
ls-refs
~~~~~~~

Az `ls-refs` az a parancs, amelyet a v2-ben egy referencia-hirdetés
kérésére használnak.  A jelenlegi referencia-hirdetéstől eltérően az
ls-refs argumentumokat vesz fel, amelyekkel korlátozható a szerver által
küldött refek köre.

Az alapparancsban nem támogatott további funkciókat a parancs értékeként
hirdetik a képesség-hirdetésben, szóközzel elválasztott funkciólista
formájában: "<command>=<feature-1> <feature-2>"

Az ls-refs a következő argumentumokat veszi fel:

    symrefs
	Az általa mutatott objektumon kívül mutassa meg az általa mutatott
	alapul szolgáló refet is, amikor egy szimbolikus refet jelenít meg.
    peel
	Mutassa meg a peelelt tageket.
    ref-prefix <prefix>
	Ha meg van adva, csak azok a referenciák jelennek meg, amelyeknek
	az előtagja megegyezik a megadott előtagok valamelyikével. Több
	példány is megadható, ez esetben bármelyik előtaggal egyező
	referenciák megjelennek. Vegyük észre, hogy ez pusztán
	optimizációs célú; a szerver MAY olyan refeket is megmutathat,
	amelyek nem egyeznek az előtaggal, ha úgy dönt, és a
	klienseknek maguknak kell kiszűrniük az eredményt.

Ha az 'unborn' funkció hirdetve van, a következő argumentum
belefoglalható a kliens kérésébe.

    unborn
	A szerver akkor is elküldi a HEAD-re vonatkozó információt, ha az
	egy meg nem született branchre mutató symref, "unborn HEAD
	symref-target:<target>" formában.

Az ls-refs kimenete a következő:

    output = *ref
	     flush-pkt
    obj-id-or-unborn = (obj-id | "unborn")
    ref = PKT-LINE(obj-id-or-unborn SP refname *(SP ref-attribute) LF)
    ref-attribute = (symref | peeled)
    symref = "symref-target:" symref-target
    peeled = "peeled:" obj-id

[[_fetch]]
fetch
~~~~~

A `fetch` az a parancs, amelyet egy packfile v2-ben történő
lekérésére használnak.  Úgy is tekinthető, mint a v1 fetch egy
módosított változata, amelyből a ref-hirdetés ki van hagyva (mivel ezt a
szerepet az `ls-refs` parancs tölti be), és amelynek üzenetformátuma úgy
lett módosítva, hogy kiküszöbölje a redundanciákat és megkönnyítse a
jövőbeli bővítmények hozzáadását.

Az alapparancsban nem támogatott további funkciókat a parancs értékeként
hirdetik a képesség-hirdetésben, szóközzel elválasztott funkciólista
formájában: "<command>=<feature-1> <feature-2>"

Egy `fetch` kérés a következő argumentumokat veheti fel:

    want <oid>
	Jelzi a szervernek azt az objektumot, amelyet a kliens le akar
	kérni.  A want-ok bármik lehetnek, nem korlátozódnak a hirdetett
	objektumokra.

    have <oid>
	Jelzi a szervernek azt az objektumot, amellyel a kliens helyben
	rendelkezik.  Ez lehetővé teszi, hogy a szerver egy olyan
	packfile-t készítsen, amely csak a kliens számára szükséges
	objektumokat tartalmazza. Több 'have' sor is megadható.

    done
	Jelzi a szervernek, hogy az egyeztetésnek véget kell érnie (vagy
	klónozás esetén el sem kell kezdődnie), és hogy a szervernek a
	kérésben megadott információt kell felhasználnia a packfile
	felépítéséhez.

    thin-pack
	Kéri egy thin pack elküldését, amely egy olyan pack, amelynek
	deltái a packon belül nem szereplő bázisobjektumokra hivatkoznak
	(amelyekről azonban tudott, hogy léteznek a fogadó oldalon).
	Ez jelentősen csökkentheti a hálózati forgalmat, de megköveteli,
	hogy a fogadó oldal tudja, hogyan "vastagítsa meg" ezeket a
	packeket a hiányzó bázisok packhoz adásával.

    no-progress
	Kéri, hogy a normál esetben a side-band 2-es csatornán, a
	packfile átvitele közben küldött folyamatinformáció ne kerüljön
	elküldésre.  A side-band 3-as csatornát azonban továbbra is
	használják a hibaválaszokhoz.

    include-tag
	Kéri, hogy az annotált tagek is elküldésre kerüljenek, ha az
	általuk mutatott objektumok elküldésre kerülnek.

    ofs-delta
	Jelzi, hogy a kliens érti a PACKv2-t olyan deltával, amely a
	bázisára a packon belüli pozíció alapján hivatkozik, nem pedig
	egy oid alapján.  Azaz képes beolvasni az OBJ_OFS_DELTA-t (más
	néven a 6-os típust) egy packfile-ban.

Ha a 'shallow' funkció hirdetve van, a következő argumentumok
belefoglalhatók a kliens kérésébe, valamint a szerver válaszában
esetlegesen megjelenhet a 'shallow-info' szekció, ahogy azt alább
ismertetjük.

    shallow <oid>
	A kliensnek értesítenie kell a szervert minden olyan commitról,
	amelynek csak sekély (shallow) másolatával rendelkezik (azaz nem
	rendelkezik a commit szülőivel), egy 'shallow <oid>' sor
	megadásával minden ilyen objektumhoz, hogy a szerver tisztában
	legyen a kliens történetének korlátaival.  Ez azért van, hogy a
	szerver tudja, hogy a kliens esetleg nem rendelkezik az ilyen
	commitokból elérhető összes objektummal.

    deepen <depth>
	Kéri, hogy a fetch/clone legyen sekély, a remote oldalhoz
	viszonyítva <depth> commit-mélységgel.

    deepen-relative
	Kéri, hogy a "deepen" parancs szemantikája úgy változzon meg,
	hogy a kért mélység a kliens jelenlegi shallow-határához legyen
	relatív, ne pedig a kért commitokhoz.

    deepen-since <timestamp>
	Kéri, hogy a shallow clone/fetch egy adott időpontnál legyen
	elvágva, mélység helyett.  Belsőleg ez egyenértékű a
	"git rev-list --max-age=<timestamp>" végrehajtásával. Nem
	használható a "deepen"-nel együtt.

    deepen-not <rev>
	Kéri, hogy a shallow clone/fetch a '<rev>' által megadott adott
	revíziónál legyen elvágva, mélység helyett.  Belsőleg ez
	egyenértékű a "git rev-list --not <rev>" végrehajtásával. Nem
	használható a "deepen"-nel együtt, de használható a
	"deepen-since"-vel.

Ha a 'filter' funkció hirdetve van, a következő argumentum
belefoglalható a kliens kérésébe:

    filter <filter-spec>
	Kéri, hogy a packfile bizonyos objektumai kimaradjanak, több
	szűrési technika egyikének használatával. Ezek partial clone és
	partial fetch műveletekkel való használatra szolgálnak. A lehetséges
	"filter-spec" értékeket lásd a `rev-list`-nél. Más folyamatokkal
	kommunikálva a küldőknek SHOULD lefordítaniuk a skálázott
	egészeket (pl. "1k") teljesen kiírt formára (pl. "1024"), hogy
	segítsék az együttműködést az olyan régebbi fogadókkal, amelyek
	esetleg nem ismerik az újonnan bevezetett skálázási utótagokat.
	A fogadóknak azonban SHOULD elfogadniuk a következő utótagokat:
	'k', 'm' és 'g', rendre 1024, 1048576 és 1073741824 értékhez.

Ha a 'ref-in-want' funkció hirdetve van, a következő argumentum
belefoglalható a kliens kérésébe, valamint a szerver válaszában
esetlegesen megjelenhet a 'wanted-refs' szekció, ahogy azt alább
ismertetjük.

    want-ref <ref>
	Jelzi a szervernek, hogy a kliens egy adott refet szeretne
	lekérni, ahol a <ref> egy ref teljes neve a szerveren.  Protokollhiba
	want-ref-et küldeni ugyanahhoz a refhez egynél többször.

Ha a 'sideband-all' funkció hirdetve van, a következő argumentum
belefoglalható a kliens kérésébe:

    sideband-all
	Utasítja a szervert, hogy a teljes választ multiplexelve küldje,
	ne csak a packfile szekciót. A válaszban (nem csak a packfile
	szekcióban) minden nem flush és nem delim PKT-LINE ekkor egy, a
	sidebandjét jelző bájttal fog kezdődni (1, 2 vagy 3), és a
	szerver küldhet egy "0005\2"-t (egy 2-es sideband PKT-LINE-t
	payload nélkül) keepalive csomagként.

Ha a 'packfile-uris' funkció hirdetve van, a következő argumentum
belefoglalható a kliens kérésébe, valamint a szerver válaszában
esetlegesen megjelenhet a 'packfile-uris' szekció, ahogy azt alább
ismertetjük. Vegyük észre, hogy legfeljebb egy `packfile-uris` sor
küldhető el a szervernek.

    packfile-uris <comma-separated-list-of-protocols>
	Jelzi a szervernek, hogy a kliens hajlandó fogadni a megadott
	protokollok bármelyikén URI-kat objektumok helyett az elküldött
	packfile-ban. A kapcsolódási ellenőrzés végrehajtása előtt a
	kliensnek le kell töltenie az összes megadott URI-ról. Jelenleg a
	támogatott protokollok a "http" és a "https".

Ha a 'wait-for-done' funkció hirdetve van, a következő argumentum
belefoglalható a kliens kérésébe.

    wait-for-done
	Jelzi a szervernek, hogy soha ne küldjön "ready"-t, hanem várja
	meg, amíg a kliens azt mondja, hogy "done", mielőtt elküldi a
	packfile-t.

A `fetch` válasza több szekcióra van bontva, amelyeket delimiter
csomagok (0001) választanak el, minden szekció a saját
szekciófejlécével kezdődik. A legtöbb szekció csak akkor kerül
elküldésre, ha a packfile is elküldésre kerül.

    output = acknowledgements flush-pkt |
	     [acknowledgments delim-pkt] [shallow-info delim-pkt]
	     [wanted-refs delim-pkt] [packfile-uris delim-pkt]
	     packfile flush-pkt

    acknowledgments = PKT-LINE("acknowledgments" LF)
		      (nak | *ack)
		      (ready)
    ready = PKT-LINE("ready" LF)
    nak = PKT-LINE("NAK" LF)
    ack = PKT-LINE("ACK" SP obj-id LF)

    shallow-info = PKT-LINE("shallow-info" LF)
		   *PKT-LINE((shallow | unshallow) LF)
    shallow = "shallow" SP obj-id
    unshallow = "unshallow" SP obj-id

    wanted-refs = PKT-LINE("wanted-refs" LF)
		  *PKT-LINE(wanted-ref LF)
    wanted-ref = obj-id SP refname

    packfile-uris = PKT-LINE("packfile-uris" LF) *packfile-uri
    packfile-uri = PKT-LINE(40*(HEXDIGIT) SP *%x20-ff LF)

    packfile = PKT-LINE("packfile" LF)
	       *PKT-LINE(%x01-03 *%x00-ff)

    acknowledgments szekció
	* Ha a kliens egy "done" sor küldésével jelzi, hogy befejezte az
	  egyeztetést (így megkövetelve, hogy a szerver elküldjön egy
	  packfile-t), az acknowledgments szekciókat MUST kihagyni a
	  szerver válaszából.

	* Mindig az "acknowledgments" szekciófejléccel kezdődik

	* A szerver "NAK"-kal válaszol, ha a have sorokban küldött
	  objektumazonosítók közül egyik sem volt közös.

	* A szerver "ACK obj-id"-vel válaszol minden olyan
	  objektumazonosítóra, amely have sorként lett elküldve, és
	  közös.

	* Egy válasz nem tartalmazhat egyszerre "ACK" sorokat és egy
	  "NAK" sort.

	* A szerver egy "ready" sorral válaszol, jelezve, hogy elfogadható
	  közös bázist talált, és készen áll egy packfile elkészítésére
	  és elküldésére (amely ugyanazon válasz packfile szekciójában
	  lesz megtalálható)

	* Ha a szerver talált egy megfelelő vágási pontot, és úgy döntött,
	  hogy egy "ready" sort küld, akkor a szerver dönthet úgy (mint
	  optimalizáció), hogy kihagyja az egyébként a válaszában
	  elküldött "ACK" sorokat.  Ennek oka, hogy a szerver ekkor már
	  eldöntötte, mely objektumokat tervezi elküldeni a kliensnek, és
	  további egyeztetésre nincs szükség.

    shallow-info szekció
	* Ha a kliens shallow fetch/clone-t kért, egy shallow kliens
	  kér egy fetchet, vagy a szerver shallow, akkor a szerver
	  válasza tartalmazhat egy shallow-info szekciót.  A shallow-info
	  szekció akkor kerül bele, ha (a fenti feltételek valamelyike
	  miatt) a szervernek tájékoztatnia kell a klienst bármilyen
	  shallow-határról, vagy a kliens meglévő shallow-határainak
	  módosításáról.

	* Mindig a "shallow-info" szekciófejléccel kezdődik

	* Ha pozitív mélységet kérnek, a szerver kiszámítja azon
	  commitok halmazát, amelyek nem mélyebbek a kívánt mélységnél.

	* A szerver egy "shallow obj-id" sort küld minden olyan
	  commithoz, amelynek szülei nem lesznek elküldve a következő
	  packfile-ban.

	* A szerver egy "unshallow obj-id" sort küld minden olyan
	  commithoz, amelyet a kliens shallow-ként jelölt meg, de a
	  fetch eredményeként már nem shallow (mivel a szülei el lesznek
	  küldve a következő packfile-ban).

	* A szerver MUST NOT küldenie "unshallow" sort olyasmihez,
	  amit a kliens nem jelölt meg shallow-ként a kérésének
	  részeként.

    wanted-refs szekció
	* Ez a szekció csak akkor kerül bele, ha a kliens egy
	  'want-ref' sorral kért egy refet, és ha a válasz egy packfile
	  szekciót is tartalmaz.

	* Mindig a "wanted-refs" szekciófejléccel kezdődik.

	* A szerver egy reflistát küld ("<oid> <refname>") minden,
	  'want-ref' sorokkal kért referenciához.

	* A szerver MUST NOT küldenie olyan refeket, amelyeket nem
	  'want-ref' sorokkal kértek.

    packfile-uris szekció
	* Ez a szekció csak akkor kerül bele, ha a kliens küldött
	  'packfile-uris'-t, és a szervernek van legalább egy ilyen
	  elküldendő URI-ja.

	* Mindig a "packfile-uris" szekciófejléccel kezdődik.

	* Minden URI-hoz, amelyet a szerver küld, elküld egy hash-t a
	  pack tartalmáról (ahogy azt a git index-pack kiírja), majd az
	  URI-t.

	* A hash-ek 40 hexadecimális karakter hosszúak. Amikor a Git egy
	  új hash-algoritmusra vált, ezt esetleg frissíteni kell. (Ennek
	  meg kell egyeznie azzal, amit az index-pack a "pack\t" vagy a
	  "keep\t" után kiír.

    packfile szekció
	* Ez a szekció csak akkor kerül bele, ha a kliens 'want' sorokat
	  küldött a kérésében, és vagy kérte, hogy 'done' küldésével ne
	  legyen több egyeztetés, vagy a szerver úgy döntött, hogy talált
	  egy elegendő vágási pontot egy packfile előállításához.

	* Mindig a "packfile" szekciófejléccel kezdődik

	* A packfile átvitele közvetlenül a szekciófejléc után kezdődik

	* A packfile adatátvitele mindig multiplexelt, az 1-es
	  protokollverzió 'side-band-64k' képességével megegyező
	  szemantikát használva.  Ez azt jelenti, hogy a packfile
	  adatfolyam során minden csomag egy vezető 4 bájtos pkt-line
	  hosszból (ami jellemző a pkt-line formátumra) áll, amelyet egy
	  1 bájtos stream-kód követ, majd a tényleges adat.

	  A stream-kód a következők egyike lehet:
		1 - pack-adat
		2 - folyamatüzenetek
		3 - végzetes hibaüzenet közvetlenül azelőtt, hogy az
		    adatfolyam megszakad

[[_server_option]]
server-option
~~~~~~~~~~~~~

Ha hirdetve van, azt jelzi, hogy tetszőleges számú szerverspecifikus
opció belefoglalható egy kérésbe.  Ez úgy történik, hogy minden opciót
egy "server-option=<option>" képesség-sorként küldenek el a kérés
capability-list szekciójában.

A megadott opciók nem tartalmazhatnak NUL vagy LF karaktert.

[[_object_format]]
object-format
~~~~~~~~~~~~~

A szerver hirdetheti az `object-format` képességet egy `X` értékkel (az
`object-format=X` formában), hogy tájékoztassa a klienst arról, hogy a
szerver képes az X hash-algoritmust használó objektumokkal foglalkozni.
Ha nincs megadva, feltételezzük, hogy a szerver csak SHA-1-et kezel.  Ha
a kliens a SHA-1-től eltérő hash-algoritmust szeretne használni, meg
kell adnia az object-format sztringjét.

[[_session_id_session_id]]
session-id=<session-id>
~~~~~~~~~~~~~~~~~~~~~~~

A szerver hirdethet egy session ID-t, amely a folyamat több kérésen
átívelő azonosítására használható. A kliens is hirdetheti a saját
session ID-ját a szerver felé.

A session ID-knak egyedinek kell lenniük az adott folyamatra nézve.
El kell férniük egy packet-line-ban, és nem tartalmazhatnak nem
nyomtatható vagy whitespace karaktereket. A jelenlegi implementáció
trace2 session ID-ket használ (a részletekért lásd a
link:technical/api-trace2.html[api-trace2]-t), de ez a jövőben
változhat, és a session ID felhasználóinak nem szabad erre a tényre
támaszkodniuk.

[[_object_info]]
object-info
~~~~~~~~~~~

Az `object-info` az a parancs, amellyel egy vagy több objektumra
vonatkozó információt lehet lekérni.  Fő célja, hogy a kliens ezen
információ alapján hozhasson döntéseket anélkül, hogy teljesen le
kellene kérnie az objektumokat. Jelenleg csak az objektumméret és a
típus támogatott.

Egy `object-info` kérés a következő argumentumokat veszi fel:

	size
	Kéri, hogy méretinformáció kerüljön visszaadásra minden felsorolt
	objektumazonosítóhoz.

	type
	Kéri, hogy típusinformáció kerüljön visszaadásra minden felsorolt
	objektumazonosítóhoz.

	oid <oid>
	Jelzi a szervernek azt az objektumot, amelyre vonatkozóan a
	kliens információt szeretne kapni. Ezeknek teljes OID-oknak kell
	lenniük.

Az `object-info` válasza kérésenkénti attribútumonként egy pkt-line-ból
áll, amely visszaadja a szerver által jelentendő attribútumokat, majd
kérésenkénti objektumazonosítónként egy pkt-line-ból, annak
információjával, ahol az egyes mezőket egyetlen szóköz választja el.

	output = info flush-pkt

	info = *PKT-LINE(attr LF)
	       *PKT-LINE(obj-info LF)

	attr = "size" | "type"

	obj-size = 1*DIGIT

	obj-type = "blob" | "tree" | "commit" | "tag"

	obj-val = obj-size | obj-type

	obj-info = obj-id [SP [obj-val *(SP obj-val)]]

Az `obj-info`-ban szereplő értékek a megfelelő `attr` sorokkal
megegyező sorrendben jelennek meg, kérésenkénti attribútumonként pontosan
egy értékkel.

Ha a szerver nem ismeri fel az OID-ot, a válasz `<oid> SP` lesz, a kért
attribútumok számától függetlenül.

[[_bundle_uri]]
bundle-uri
~~~~~~~~~~

Ha a 'bundle-uri' képesség hirdetve van, a szerver támogatja a
`bundle-uri` parancsot.

A képesség jelenleg érték nélkül van hirdetve (azaz nem
"bundle-uri=valamiérték" formában), egy érték a jövőben hozzáadható a
parancs egészére vonatkozó bővítmények támogatásához. A klienseknek
MUST figyelmen kívül hagyniuk minden ismeretlen képességértéket, és
folytatniuk kell az általuk támogatott 'bundle-uri' dialógussal.

A 'bundle-uri' parancsot arra szánták, hogy a `fetch` előtt legyen
kiadva, hogy bundle-fájlokra (lásd linkgit:git-bundle[1]) mutató URI-kat
szerezzenek, ezzel "beoltva" és tájékoztatva a következő `fetch`
parancsot.

A kliens CAN kiadhatja a `bundle-uri`-t bármely más érvényes parancs
előtt vagy után. Ahhoz, hogy hasznos legyen a kliensek számára, az
várható, hogy egy `ls-refs` után és a `fetch` előtt lesz kiadva, de
CAN kiadható a dialógus bármely pontján.

[[_discussion_of_bundle_uri]]
A bundle-uri megvitatása
^^^^^^^^^^^^^^^^^^^^^^^^

A funkció célja, hogy optimalizálja a szerver erőforrás-fogyasztását a
gyakori esetben, azáltal, hogy a linkgit:git-clone[1] során egy nagyon
nagy PACK lekérésének gyakori esetét egy kisebb inkrementális fetchre
változtatja.

Emellett lehetővé teszi a szervereknek, hogy jobb gyorsítótárazást
érjenek el egy `uploadpack.packObjectsHook`-kal kombinálva (lásd
linkgit:git-config[1]).

Azáltal, hogy az új clone-ok vagy fetchek egy kiszámíthatóbb és
gyakoribb egyeztetést jelentenek a nemrég előállított *.bundle
fájl(ok) csúcsaival szemben. A szerverek akár elő is generálhatják az
ilyen egyeztetések eredményeit az `uploadpack.packObjectsHook`
számára, ahogy új pushok érkeznek.

Az egyik módja annak, ahogy a szerverek kihasználhatják ezeket a
bundle-öket, az, hogy a szerver azt feltételezi, hogy az új clone-ok
egy ismert bundle-t fognak letölteni, majd az abban a bundle-ben (vagy
bundle-ökben) talált ref-csúcsok segítségével felzárkóznak a
repository jelenlegi állapotára.

[[_protocol_for_bundle_uri]]
A bundle-uri protokollja
^^^^^^^^^^^^^^^^^^^^^^^^

Egy `bundle-uri` kérés nem vesz fel argumentumokat, és mint fentebb
említettük, jelenleg nem hirdet képességértéket. A jövőben mindkettő
hozzáadható.

Amikor a kliens kiad egy `command=bundle-uri` kérést, a válasz egy
kulcs-érték párokból álló lista, packet line-okként megadva, `<key>=<value>`
értékkel. Minden `<key>`-t a `bundle.*` névtérből származó
config-kulcsként kell értelmezni egy bundle-lista felépítéséhez. Ezek a
kulcsok egy `bundle.<id>.` alszekció szerint vannak csoportosítva, ahol
egy adott `<id>`-hez tartozó minden kulcs attribútumokkal járul hozzá
az adott `<id>` által meghatározott bundle-höz. Ezen kulcsok pontos
részleteiért, és hogy a Git kliens hogyan értelmezi az értéküket, lásd
a linkgit:git-config[1]-et.

A klienseknek MUST elemezniük a sort a fenti formátum szerint, azokat a
sorokat, amelyek nem felelnek meg a formátumnak, SHOULD eldobni. A
felhasználó MAY figyelmeztetve legyen ilyen esetben.

[[_bundle_uri_client_and_server_expectations]]
bundle-uri KLIENS- ÉS SZERVERELVÁRÁSOK
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

URI-TARTALOM::
A hirdetett URI-kon lévő tartalomnak MUST a két típus egyikének
lennie.
+
A hirdetett URI tartalmazhat egy bundle-fájlt, amelyet a `git bundle
verify` elfogadna. Azaz MUST tartalmazniuk egy vagy több, a kliens
által használható referencia-csúcsot, MUST jelezniük az előfeltételeket
(ha vannak) a szabványos "-" előtaggal, és MUST jelezniük az
"object-format"-jukat, ha alkalmazható.
+
A hirdetett URI alternatívaként tartalmazhat egy egyszerű szöveges
fájlt, amelyet a `git config list` elfogadna (a `--file` opcióval).
Az ebben a listában szereplő kulcs-érték párok a `bundle.*` névtérben
vannak (lásd linkgit:git-config[1]).

bundle-uri KLIENSOLDALI HIBAKEZELÉS::
A kliensnek MUST mindenekelőtt elegánsan degradálódnia hibák esetén,
akár azért, mert a bundle URI(k)ban hibás vagy hiányzó adat van, akár
azért, mert a kliens túl "buta" ahhoz, hogy pl. teljesen megértse és
feldolgozza a bundle-fejléceket és azok előfeltétel-kapcsolatait, akár
valami más okból.
+
A szerverüzemeltetőknek magabiztosnak kell érezniük magukat a
"bundle-uri" bekapcsolásakor, és nem kell aggódniuk amiatt, hogy pl. ha
a CDN-jük leáll, a clone-ok vagy fetchek súlyos hibákba fognak
ütközni. Még ha a szerver bundle-jei hiányosak, vagy valamilyen módon
hibásak is, a kliensnek akkor is egy működő repository-val kell
végeznie, csakúgy, mintha úgy döntött volna, hogy nem használja ezt a
protokollbővítményt.
+
A kliens és a szerver közötti interakcióról szóló minden további
tárgyalásnak MUST szem előtt tartania ezt.

bundle-uri SZERVERTŐL KLIENS FELÉ::
A visszaadott bundle URI-k sorrendje nem számít. A klienseknek MUST
elemezniük a fejléceiket, hogy felfedezzék a bennük foglalt OID-okat és
előfeltételeket. A kliensnek MUST a bundle(ok) tartalmát magát és azok
fejlécét tekintenie a végső igazságforrásnak.
+
A szerver MAY akár olyan bundle(oka)t is visszaadhat, amelyeknek nincs
közvetlen kapcsolatuk a klónozandó repository-val (akár véletlenül,
akár szándékos "ravasz" konfiguráció miatt), és elvárhatja a klienstől,
hogy kiválogassa, milyen adatot szeretne a bundle(ok)ból, ha
egyáltalán.

bundle-uri KLIENSTŐL SZERVER FELÉ::
A kliensnek SHOULD a bundle fejléc(ek)ben talált referencia-csúcsokat
megadnia 'have' sorokként bármely következő `fetch` kérésben. A kliens
MAY a bundle(oka)t teljesen figyelmen kívül is hagyhatja, ha ez
valamilyen okból rosszabbnak ítélhető, pl. ha a bundle-ök nem
tölthetők le, vagy nem tetszenek neki a talált csúcsok stb.

HA A HIRDETETT BUNDLE(OK) NEM IGÉNYELNEK TOVÁBBI EGYEZTETÉST::
Ha a `bundle-uri` és az `ls-refs` kiadása, valamint a bundle(ok)
fejléc(ei)nek megszerzése után a kliens azt találja, hogy a kívánt
ref-csúcsok teljes egészében a hirdetett bundle(ok)ból lekérhetők, a
kliens MAY lecsatlakozhat a Git szerverről. Egy ilyen 'clone' vagy
'fetch' eredményének megkülönböztethetetlennek kell lennie attól az
állapottól, amely a bundle-uri használata nélkül állna elő.

KORAI KLIENS-LECSATLAKOZÁSOK ÉS HIBAKEZELÉS::
A kliens MAY korai lecsatlakozást hajthat végre, miközben még
letölti a bundle(oka)t (miután azok fejléceit már streamelte és
elemezte). Ilyen esetben a kliensnek MUST elegánsan helyreállnia
minden, a bundle(ok) letöltésének és érvényesítésének befejezésével
kapcsolatos hibából.
+
Azaz a kliensnek esetleg újra kell csatlakoznia, és ki kell adnia egy
'fetch' parancsot, és esetleg vissza kell térnie ahhoz, hogy egyáltalán
ne használja a 'bundle-uri'-t.
+
Ez a "MAY" viselkedés (és nem egy "SHOULD") azért van így
meghatározva, mert feltételezhető, hogy egy bundle URI-kat hirdető
szerver valószínűbb, hogy egy viszonylag nagy repository-t szolgál ki,
és olyan URI-kra mutat, amelyeknél jó eséllyel működőképesek. A kliens
MAY pl. megnézheti a bundle-ök payload-méretét heurisztikaként annak
eldöntésére, hogy megéri-e a korai lecsatlakozás, ha egy teljes
"fetch" dialógusra való visszatérésre lenne szükség.

HA A HIRDETETT BUNDLE(OK) TOVÁBBI EGYEZTETÉST IGÉNYELNEK::
A kliensnek SHOULD megkezdenie egy PACK egyeztetését a szerverrel a
"fetch" paranccsal, a hirdetett bundle-ökben talált OID-csúcsokat
használva, még ha éppen azoknak a bundle(ok)nak a letöltése is folyik.
+
Ez lehetővé teszi az agresszív korai lecsatlakozást bármely
interaktív szerverdialógusból. A kliens vakon megbízik abban, hogy a
hirdetett OID-csúcsok relevánsak, és 'have' sorokként adja ki őket,
majd bármely csúcsot lekér, amelyet szeretne (rendszerint az
"ls-refs" hirdetéséből) 'want' sorokon keresztül. A szerver ezután
kiszámít egy (remélhetőleg kicsi) PACK-ot, a bundle(ok)ból származó
csúcsok és a kért adat közötti várt különbséggel.
+
Az egyetlen kapcsolat, amelyet a kliensnek ezután aktívan kell
tartania, a párhuzamosan letöltődő statikus bundle(ok)hoz vezet, és
amikor azokat és az inkrementális PACK-ot megkapta, ki kell csomagolni
és érvényesíteni kell őket. Az ezen a ponton fellépő hibákból
elegánsan helyre kell állni, lásd fentebb.

[[_bundle_uri_protocol_features]]
bundle-uri PROTOKOLLFUNKCIÓK
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A kliens egy bundle-listát épít fel a szerver által megadott
`<key>=<value>` párokból. Ezek a párok a `bundle.*` névtér részei, ahogy
azt a linkgit:git-config[1] dokumentálja. Ebben a szekcióban néhány
ilyen kulcsot tárgyalunk, és leírjuk azokat a műveleteket, amelyeket a
kliens ezen információ hatására végrehajt.

Konkrétan a `bundle.version` kulcs egy egész számot ad meg. Jelenleg
az egyetlen elfogadott érték `1`, de ha a kliens itt nem várt értéket
lát, akkor a kliensnek MUST figyelmen kívül hagynia a bundle-listát.

Amíg a `bundle.version` értelmezhető, minden más ismeretlen kulcsot a
kliens MAY figyelmen kívül hagyhat. A szerver garantálja a
kompatibilitást a régebbi kliensekkel, bár az újabb kliensek jobban
képesek lehetnek a letöltések minimalizálására az extra kulcsok
felhasználásával.

A pre-URI kulcs-értékek bármely visszafelé inkompatibilis hozzáadása
egy új `bundle.version` értékkel vagy értékekkel lesz védve magában a
'bundle-uri' képesség-hirdetésben, és/vagy a jövőbeli új `bundle-uri`
kéréssel kapcsolatos argumentumokkal.

Néhány példa kulcs-érték párra, amelyek jelenleg nincsenek
megvalósítva, de a jövőben megvalósíthatók lennének:

 * Egy "hash=<val>" vagy "size=<bytes>" hozzáadása a bundle-fájl várt
   hash-ének vagy méretének hirdetéséhez.

 * Annak hirdetése, hogy egy vagy több bundle-fájl azonos (pl. hogy a
   kliensek round-robin módon vagy másképp válasszanak N lehetséges
   fájl közül).

 * Egy "oid=<OID>" rövidítés és egy "prerequisite=<OID>" rövidítés.
   Annak a gyakori esetnek a kifejezésére, amikor egy bundle egy
   csúccsal és előfeltétel nélkül, vagy egy csúccsal és egy
   előfeltétellel rendelkezik.
+
Ez lehetővé tenné annak a gyakori esetnek az optimalizálását, amikor a
szerverek egyetlen "nagy bundle-t" szeretnének biztosítani, amely csak
a "main" branchüket tartalmazza, és/vagy annak inkrementális
frissítéseit.
+
Egy ilyen választ kapó kliens MAY feltételezheti, hogy kihagyhatja a
fejléc lekérését a jelzett URI-n lévő bundle-ből, és ezáltal
megspórolhatja magának és a szerver(ek)nek az adott bundle vagy
bundle-ök fejlécének megvizsgálásához szükséges kérés(eke)t.

[[_promisor_remote_pr_info]]
promisor-remote=<pr-info>
~~~~~~~~~~~~~~~~~~~~~~~~~

A szerver hirdethet néhány promisor remote-ot, amelyet használ, vagy
amelyről tud, egy olyan kliens felé, amely ezeket szeretné használni a
saját promisor remote-jaiként, e repository helyett. Ebben az esetben a
<pr-info>-nak a következő alakúnak kell lennie:

	pr-info = pr-fields | pr-info ";" pr-fields

	pr-fields = pr-field | pr-fields "," pr-field

	pr-field = field-name "=" field-value

ahol a `field-name` és a `field-value` egy adott `pr-fields`-en belül
egyetlen promisor remote-hoz kapcsolódó mezőnevek és értékek. Egy adott
`field-name` MUST NOT jelenhet meg egynél többször egy adott
`pr-fields`-ben.

A szervernek MUST hirdetnie legalább a "name" és "url" mezőneveket a
hozzájuk tartozó mezőértékekkel együtt, amelyek egy érvényes remote
neve és URL-je, minden `pr-fields`-ben. A "name" és "url" mezőknek
MUST elsőként megjelenniük minden pr-fields-ben, ebben a sorrendben.

Ezen kötelező mezők után a szerver MAY az alábbi opcionális mezőket
hirdetheti, tetszőleges sorrendben:

`partialCloneFilter`:: A remote szűrési specifikációja. Ez a
"remote.<name>.partialCloneFilter" config-beállításnak felel meg. A
kliensek ezt felhasználhatják annak megállapítására, hogy a remote
szűrési stratégiája kompatibilis-e az igényeikkel (pl. annak
ellenőrzésével, hogy mindkettő "blob:none"-t használ-e). Emellett
felhasználhatják ezt a `--filter=auto` opción keresztül a
linkgit:git-clone[1]-ben. Ezzel az opcióval a klón szűrési
specifikációja automatikusan kiszámításra kerül a kliens által
elfogadott promisor remote-ok szűrési specifikációinak kombinálásával.

`token`:: Egy hitelesítési token, amelyet a kliensek használhatnak a
remote-hoz való csatlakozáskor. Ez a "remote.<name>.token"
config-beállításnak felel meg.

A protokoll jelenleg semmilyen más mezőt nem definiál. A mezőnevek
kis- és nagybetűérzékenyek, és MUST pontosan a fent megadott módon
kell átvitelre kerülniük. A klienseknek MUST figyelmen kívül hagyniuk
az általuk fel nem ismert mezőket, hogy lehetővé tegyék a jövőbeli
protokollbővítéseket.

A kliens felhasználhatja az ezeken a mezőkön keresztül átvitt
információt annak eldöntésére, hogy elfogadja-e a hirdetett promisor
remote-ot. Emellett a kliens beállítható úgy is, hogy tárolja ezen
mezők értékeit, vagy felhasználja őket a repository automatikus
konfigurálásához (lásd a "promisor.storeFields"-et a
linkgit:git-config[1]-ben és a `--filter=auto`-t a
linkgit:git-clone[1]-ben).

A mezőértékeknek MUST urlencoded formátumúnak lenniük.

Ha a kliens úgy dönt, hogy a szerver által hirdetett egy vagy több
promisor remote-ot használja, válaszolhat egy
"promisor-remote=<pr-names>" sorral, ahol a <pr-names>-nak a következő
alakúnak kell lennie:

	pr-names = pr-name | pr-names ";" pr-name

ahol a `pr-name` egy, a szerver által hirdetett és a kliens által
elfogadott promisor remote urlencoded neve.

A kliens által elfogadott promisor remote-okat próbálja meg először a
kliens a többi konfigurált promisor remote előtt, amikor hiányzó
objektumokat próbál fetchelni.

Vegyük észre, hogy ebben a dokumentumban mindenütt a ';' és ','
karaktereket MUST kódolni, ha megjelennek a `pr-name`-ben vagy a
`field-value`-ban.

Ha a szerver nem ismer olyan promisor remote-ot, amely jó lehetne egy
kliens számára, vagy azt szeretné, hogy a kliens ne használjon
semmilyen általa használt vagy ismert promisor remote-ot, akkor
egyáltalán ne hirdesse a "promisor-remote" képességet.

Ebben az esetben, vagy ha a kliens nem akarja használni a szerver
által hirdetett egyetlen promisor remote-ot sem, a kliens egyáltalán
ne hirdesse a "promisor-remote" képességet a válaszában.

A szerveroldalon a "promisor.advertise" és a "promisor.sendFields"
konfigurációs opciók használhatók annak szabályozására, hogy mit
hirdet. A kliensoldalon a "promisor.acceptFromServer" és a
"promisor.acceptFromServerUrl" konfigurációs opciók használhatók annak
szabályozására, hogy mit fogad el, valamint a "promisor.storeFields"
opció annak szabályozására, hogy mit tárol. További információért
lásd ezen konfigurációs opciók dokumentációját a
linkgit:git-config[1]-ben.

Vegyük észre, hogy a jövőben jó lenne, ha a "promisor-remote" protokoll
képességet a szerver arra használhatná, hogy `git fetch` vagy `git
clone` esetén válaszként olyan jobban kapcsolódó remote-okat hirdessen,
amelyeket a kliens promisor remote-okként használhat e repository
helyett, hogy a kliens lustán fetchelhessen objektumokat ezekről a
jobban kapcsolódó remote-okról. Ehhez a szervernek ki kellene hagynia a
válaszából azokat az objektumokat, amelyek elérhetők a kliens által
elfogadott, jobban kapcsolódó remote-okon. Ez azonban még nincs
megvalósítva. Így egyelőre ez a "promisor-remote" képesség csak akkor
hasznos, ha a szerver olyan promisor remote-okat hirdet, amelyeket már
használ objektumok kölcsönzésére.

GIT
---
A linkgit:git[1] csomag része
