gitprotocol-pack(5)
===================

NAME
----
gitprotocol-pack - Hogyan kerülnek átvitelre a packek a vezetéken keresztül

SYNOPSIS
--------
[verse]
<over-the-wire-protocol>

DESCRIPTION
-----------

A Git támogatja az adatok packfile-okban történő átvitelét az ssh://, git://,
http:// és file:// transportokon keresztül.  Két protokollcsoport létezik: az
egyik az adatok kliensről szerverre pusholásához, a másik a szerverről
kliensre fetcheléshez.  A három transport (ssh, git, file) ugyanazt a
protokollt használja az adatátvitelhez. A http a linkgit:gitprotocol-http[5]-ben
van dokumentálva.

A kanonikus Git implementációban meghívott folyamatok a fetcheléshez a
szerveroldali 'upload-pack' és a kliensoldali 'fetch-pack'; a pusholáshoz
pedig a szerveroldali 'receive-pack' és a kliensoldali 'send-pack'. A
protokoll feladata, hogy a szerver közölje a klienssel, mi van jelenleg a
szerveren, majd hogy a kettő megegyezzen a küldendő adat legkisebb
mennyiségében annak érdekében, hogy az egyik vagy a másik teljesen
frissüljön.

[[_pkt_line_format]]
pkt-line formátum
-----------------

Az alábbi leírások a linkgit:gitprotocol-common[5]-ben ismertetett pkt-line
formátumra épülnek. Amikor a grammatika `PKT-LINE(...)`-t jelez, eltérő
megjegyzés hiányában a szokásos pkt-line LF-szabályok érvényesek: a
küldőnek SHOULD tartalmaznia egy LF-et, de a fogadó MUST NOT panaszkodjon,
ha az nincs jelen.

Egy hibacsomag egy speciális pkt-line, amely egy hibaüzenetet tartalmaz.

----
  error-line     =  PKT-LINE("ERR" SP explanation-text)
----

A protokoll egészében, ahol `PKT-LINE(...)` várt, egy hibacsomag MAY
küldhető. Amint egy kliens vagy egy szerver elküldi ezt a csomagot, az
ebben a protokollban meghatározott adatátviteli folyamat véget ér.

[[_transports]]
Transportok
-----------
Három transport létezik, amelyeken keresztül a packfile-protokoll
elindítható.

A Git transport egy egyszerű, hitelesítés nélküli szerver, amely
fogadja a parancsot (szinte mindig 'upload-pack', bár a Git-szerverek
globálisan írhatóra is konfigurálhatók, amely esetben a 'receive-pack'
elindítása is engedélyezett), amellyel a kliens kommunikálni kíván,
végrehajtja azt, és összeköti a kérő folyamattal.

Az SSH transportban a kliens egyszerűen lefuttatja az 'upload-pack'
vagy 'receive-pack' folyamatot a szerveren az SSH-protokollon keresztül,
majd az SSH-kapcsolaton keresztül kommunikál az elindított folyamattal.

A file:// transport helyben futtatja az 'upload-pack' vagy 'receive-pack'
folyamatot, és egy pipe-on keresztül kommunikál vele.

[[_extra_parameters]]
Extra Parameterek
-----------------

A protokoll biztosít egy mechanizmust, amellyel a kliensek további
információt küldhetnek az első üzenetükben a szervernek. Ezeket „Extra
Parametereknek" nevezzük, és a Git, az SSH és a HTTP protokoll is
támogatja őket.

Minden Extra Parameter a `<kulcs>=<érték>` vagy a `<kulcs>` formát veszi fel.

Az ilyen Extra Parametereket fogadó szervereknek MUST figyelmen kívül
hagyniuk minden fel nem ismert kulcsot. Jelenleg az egyetlen felismert
Extra Parameter a "version", amelynek értéke '1' vagy '2' lehet.  A 2-es
protokollverzióról bővebben lásd a linkgit:gitprotocol-v2[5]-öt.

[[_git_transport]]
Git Transport
-------------

A Git transport azzal kezdődik, hogy elküldi a parancsot és a
repository-t a vezetéken a pkt-line formátumban, amelyet egy NUL bájt
és egy hostname paraméter követ, amelyet egy NUL bájt zár le.

   0033git-upload-pack /project.git\0host=myserver.com\0

A transport küldhet Extra Parametereket egy további NUL bájt
hozzáadásával, majd egy vagy több NUL-lal lezárt sztring hozzáadásával:

   003egit-upload-pack /project.git\0host=myserver.com\0\0version=1\0

--
   git-proto-request = request-command SP pathname NUL
		       [ host-parameter NUL ] [ NUL extra-parameters ]
   request-command   = "git-upload-pack" / "git-receive-pack" /
		       "git-upload-archive"   ; case sensitive
   pathname          = *( %x01-ff ) ; exclude NUL
   host-parameter    = "host=" hostname [ ":" port ]
   extra-parameters  = 1*extra-parameter
   extra-parameter   = 1*( %x01-ff ) NUL
--

A host-parameter a git-daemon névalapú virtuális hostingjához
használatos.  Lásd a git daemon --interpolated-path opcióját, a %H/%CH
formátumkarakterekkel.

Alapvetően azt teszi a Git kliens, hogy a Git-protokollon keresztül
kapcsolódik a szerveroldali 'upload-pack' folyamathoz, valahogy így:

   $ echo -e -n \
     "003agit-upload-pack /schacon/gitbook.git\0host=example.com\0" |
     nc -v example.com 9418


[[_ssh_transport]]
SSH Transport
-------------

Az 'upload-pack' vagy 'receive-pack' folyamatok SSH-n keresztüli
elindítása a binárisnak a szerveren, SSH-n keresztüli távoli
végrehajtás útján történő futtatását jelenti.
Ez alapvetően egyenértékű a következő futtatásával:

   $ ssh git.example.com "git-upload-pack '/project.git'"

Ahhoz, hogy egy szerver támogassa a Git pusholást és pull-olást egy
adott felhasználó számára SSH-n keresztül, annak a felhasználónak
képesnek kell lennie e parancsok közül egyet vagy mindkettőt
végrehajtani a bejelentkezéskor kapott SSH-shellen keresztül.  Néhány
rendszeren ez a shell-hozzáférés csak e két parancs futtatására van
korlátozva, vagy akár csak egyre közülük.

Egy ssh:// formátumú URI-ban ez az URI-n belül abszolút, így a hostnév
(vagy portszám) utáni '/' argumentumként kerül elküldésre, amelyet a
távoli 'git-upload-pack' pontosan úgy olvas be, ahogy van, tehát ez
gyakorlatilag egy abszolút útvonal a távoli fájlrendszerben.

       git clone ssh://user@example.com/project.git
		    |
		    v
    ssh user@example.com "git-upload-pack '/project.git'"

Egy "user@host:path" formátumú URI-ban ez a felhasználó saját
könyvtárához viszonyítva relatív, mert a Git kliens a következőt
fogja futtatni:

     git clone user@example.com:project.git
		    |
		    v
  ssh user@example.com "git-upload-pack 'project.git'"

A kivétel az, ha egy '~' van használva, ebben az esetben a vezető '/'
nélkül hajtjuk végre.

      ssh://user@example.com/~alice/project.git,
		     |
		     v
   ssh user@example.com "git-upload-pack '~alice/project.git'"

A `protocol.version` konfigurációs változó értékétől függően a Git
megkísérelheti az Extra Parametereket egy kettősponttal elválasztott
sztringként elküldeni a GIT_PROTOCOL környezeti változóban. Ez csak
akkor történik meg, ha az `ssh.variant` konfigurációs változó azt
jelzi, hogy az ssh parancs támogatja a környezeti változók argumentumként
való átadását.

Néhány dolog, amit érdemes itt megjegyezni:

- A "parancsnév" kötőjellel van írva (pl. 'git-upload-pack'), de ezt a
  kliens felülbírálhatja;

- A repository útvonala mindig egyszeres idézőjelbe van téve.

[[_fetching_data_from_a_server]]
Adatok fetchelése egy szerverről
--------------------------------

Amikor az egyik Git repository meg akarja szerezni azt az adatot,
amellyel egy másik repository rendelkezik, az első 'fetch'-elhet a
másodiktól.  Ez a művelet meghatározza, hogy a szervernek milyen olyan
adata van, amellyel a kliens nem rendelkezik, majd ezt az adatot
packfile formátumban lestreameli a kliensnek.


[[_reference_discovery]]
Referenciák felfedezése
-----------------------

Amikor a kliens kezdetben kapcsolódik, a szerver azonnal válaszol egy
verziószámmal (ha a "version=1" el lett küldve Extra Parameterként),
és minden birtokában lévő referencia (az összes branch és tag)
listájával, együtt azzal az objektumnévvel, amelyre az adott
referencia jelenleg mutat.

   $ echo -e -n "0045git-upload-pack /schacon/gitbook.git\0host=example.com\0\0version=1\0" |
      nc -v example.com 9418
   000eversion 1
   00887217a7c7e582c46cec22a130adf4b9d7d950fba0 HEAD\0multi_ack thin-pack
		side-band side-band-64k ofs-delta shallow no-progress include-tag
   00441d3fcd5ced445d1abc402225c0b8a1299641f497 refs/heads/integration
   003f7217a7c7e582c46cec22a130adf4b9d7d950fba0 refs/heads/master
   003cb88d2441cac0977faf98efc80305012112238d9d refs/tags/v0.9
   003c525128480b96c89e6418b1e40909bf6c5b2d580f refs/tags/v1.0
   003fe92df48743b7bc7d26bcaabfddde0a1e20cae47c refs/tags/v1.0^{}
   0000

A visszaadott válasz egy pkt-line stream, amely leírja az egyes
refeket és azok jelenlegi értékét.  A streamnek MUST névre rendezettnek
lennie, a C locale-sorrend szerint.

Ha a HEAD egy érvényes ref, a HEAD MUST az első hirdetett refként
megjelenjen.  Ha a HEAD nem egy érvényes ref, a HEAD MUST NOT
egyáltalán megjelenjen a hirdetési listában, de más refek
megjelenhetnek.

A streamnek MUST tartalmaznia a képesség-deklarációkat egy NUL mögött
az első refen. Egy ref lefejtett értékének (azaz a "ref^{}"-nek) MUST
közvetlenül maga a ref után következnie, ha jelen van. Egy szabályos
szervernek MUST lefejtenie a refet, ha az egy annotált tag.

----
  advertised-refs  =  *1("version 1")
		      (no-refs / list-of-refs)
		      *shallow
		      flush-pkt

  no-refs          =  PKT-LINE(zero-id SP "capabilities^{}"
		      NUL capability-list)

  list-of-refs     =  first-ref *other-ref
  first-ref        =  PKT-LINE(obj-id SP refname
		      NUL capability-list)

  other-ref        =  PKT-LINE(other-tip / other-peeled)
  other-tip        =  obj-id SP refname
  other-peeled     =  obj-id SP refname "^{}"

  shallow          =  PKT-LINE("shallow" SP obj-id)

  capability-list  =  capability *(SP capability)
  capability       =  1*(LC_ALPHA / DIGIT / "-" / "_")
  LC_ALPHA         =  %x61-7A
----

A szervernek és a kliensnek MUST kisbetűt használnia az obj-id-hoz,
mindkettőnek MUST kis- és nagybetűt nem megkülönböztetőként kezelnie
az obj-id-t.

A megengedett szerverképességek listájáért és leírásáért lásd a
protocol-capabilities.txt fájlt.

[[_packfile_negotiation]]
Packfile-egyeztetés
-------------------
A referencia- és képesség-felfedezés után a kliens dönthet úgy, hogy
megszakítja a kapcsolatot egy flush-pkt küldésével, közölve a
szerverrel, hogy az most szabályosan befejezheti és bonthatja a
kapcsolatot, amikor nincs szüksége semmilyen pack-adatra. Ez
előfordulhat az ls-remote paranccsal, és akkor is, ha a kliens már
naprakész.

Ellenkező esetben belép az egyeztetési fázisba, ahol a kliens és a
szerver meghatározza, mi az átvitelhez szükséges minimális packfile,
azáltal, hogy közli a szerverrel, milyen objektumokat akar, melyek a
shallow objektumai (ha vannak), és mi a maximális commit-mélység, amit
akar (ha van).  A kliens el fogja küldeni azon képességek listáját is,
amelyeket érvényben szeretne látni, azok közül, amelyekről a szerver
azt mondta, hogy tudja őket az első 'want' sorral.

----
  upload-request    =  want-list
		       *shallow-line
		       *1depth-request
		       [filter-request]
		       flush-pkt

  want-list         =  first-want
		       *additional-want

  shallow-line      =  PKT-LINE("shallow" SP obj-id)

  depth-request     =  PKT-LINE("deepen" SP depth) /
		       PKT-LINE("deepen-since" SP timestamp) /
		       PKT-LINE("deepen-not" SP ref)

  first-want        =  PKT-LINE("want" SP obj-id SP capability-list)
  additional-want   =  PKT-LINE("want" SP obj-id)

  depth             =  1*DIGIT

  filter-request    =  PKT-LINE("filter" SP filter-spec)
----

A klienseknek MUST elküldeniük az összes obj-id-t, amelyet a
referencia-felfedezési fázisból akarnak, 'want' sorokként. A
klienseknek MUST legalább egy 'want' parancsot küldeniük a kérés
törzsében. A kliensek MUST NOT olyan obj-id-t említsenek egy 'want'
parancsban, amely nem jelent meg a ref-felfedezésen keresztül kapott
válaszban.

A kliensnek MUST leírnia minden olyan obj-id-t, amelynek csak shallow
másolata van (azaz nincs meg a commit szüleje) 'shallow' sorokként,
hogy a szerver tisztában legyen a kliens történetének
korlátaival.

A kliens ezután elküldi az e tranzakcióhoz kívánt maximális
commit-történeti mélységet, ami a történet csúcsától számítva kívánt
commitok száma, ha van ilyen, egy 'deepen' sor formájában.  A 0
mélység ugyanaz, mintha nem lenne mélységkérés. A kliens nem akar
semmilyen, ennél a mélységnél messzebbi commitot fogadni, és nem akar
olyan objektumokat sem, amelyek csak azon commitok teljessé
tételéhez szükségesek. Azok a commitok, amelyeknek a szülei emiatt
nem érkeznek meg, shallow-ként vannak definiálva, és a szerveren
ilyenként vannak megjelölve. Ez az információ a következő lépésben
kerül visszaküldésre a kliensnek.

A kliens opcionálisan kérheti, hogy a pack-objects néhány
szűrőtechnika valamelyikének használatával kihagyjon bizonyos
objektumokat a packfile-ból. Ezek a partial clone és partial fetch
műveletekkel való használatra vannak szánva. Egy olyan objektum,
amely nem felel meg egy filter-spec értéknek, ki lesz hagyva, hacsak
kifejezetten nem lett kérve egy 'want' sorban. A lehetséges
filter-spec értékekért lásd a `rev-list`-et.

Amint az összes 'want' és 'shallow' (és az opcionális 'deepen') át
lett küldve, a klienseknek MUST elküldeniük egy flush-pkt-t, hogy
közöljék a szerver oldallal, hogy befejezték a lista küldését.

Ellenkező esetben, ha a kliens pozitív mélységkérést küldött, a
szerver meghatározza, mely commitok lesznek és melyek nem lesznek
shallow-k, és elküldi ezt az információt a kliensnek. Ha a kliens nem
kért pozitív mélységet, ez a lépés kimarad.

----
  shallow-update   =  *shallow-line
		      *unshallow-line
		      flush-pkt

  shallow-line     =  PKT-LINE("shallow" SP obj-id)

  unshallow-line   =  PKT-LINE("unshallow" SP obj-id)
----

Ha a kliens pozitív mélységet kért, a szerver kiszámítja azon
commitok halmazát, amelyek nem mélyebbek a kívánt mélységnél. A
commitok halmaza a kliens want-jainál kezdődik.

A szerver 'shallow' sorokat ír minden olyan commithoz, amelynek a
szülei emiatt nem lesznek elküldve. A szerver egy 'unshallow' sort ír
minden olyan commithoz, amelyet a kliens shallow-ként jelölt meg, de
amely a jelenleg kért mélységnél már nem shallow (azaz a szülei már
el lesznek küldve). A szerver MUST NOT semmit unshallow-ként
megjelölnie, amit a kliens nem jelölt meg shallow-ként.

Most a kliens elküldi a birtokában lévő obj-id-k listáját 'have'
sorokkal, hogy a szerver olyan packfile-t tudjon készíteni, amely
csak a kliens számára szükséges objektumokat tartalmazza. multi_ack
módban a kanonikus implementáció ezekből egyszerre akár 32-t is elküld,
majd elküld egy flush-pkt-t. A kanonikus implementáció előreugrik, és
azonnal elküldi a következő 32-t, hogy mindig legyen egy 32-es blokk
"úton lévő" a vezetéken.

----
  upload-haves      =  have-list
		       compute-end

  have-list         =  *have-line
  have-line         =  PKT-LINE("have" SP obj-id)
  compute-end       =  flush-pkt / PKT-LINE("done")
----

Ha a szerver 'have' sorokat olvas be, akkor azon obj-id-k ACK-elésével
válaszol, amelyekről a kliens azt mondta, hogy megvannak neki, és
amelyek a szervernek is megvannak. A szerver eltérően ACK-eli az
obj-id-ket attól függően, hogy a kliens melyik ack módot választotta.

multi_ack módban:

  * a szerver 'ACK obj-id continue'-val válaszol minden közös
    commitra.

  * amint a szerver talált egy elfogadható közös alap-commitot, és
    kész elkészíteni a packfile-t, vakon ACK-elni fogja az összes
    'have' obj-id-t a kliens felé.

  * a szerver ezután küld egy 'NAK'-ot, majd megvárja a kliens
    következő válaszát - vagy egy 'done'-t, vagy egy újabb 'have'
    sorlistát.

multi_ack_detailed módban:

  * a szerver megkülönbözteti azokat az ACK-eket, amelyekkel jelzi,
    hogy készen áll adatot küldeni, 'ACK obj-id ready' sorokkal, és
    az azonosított közös commitokat 'ACK obj-id common' sorokkal
    jelzi.

multi_ack és multi_ack_detailed nélkül:

 * az 'upload-pack' "ACK obj-id"-t küld az első közös objektumnál,
   amit talál. Ezután semmit sem mond, amíg a kliens nem ad neki egy
   "done"-t.

 * az 'upload-pack' "NAK"-ot küld egy flush-pkt-re, ha még nem talált
   közös objektumot.  Ha talált egyet, és így már küldött egy ACK-et,
   akkor a flush-pkt-nél csendben marad.

Miután a kliens elegendő ACK-választ kapott ahhoz, hogy meg tudja
állapítani, hogy a szervernek elég információja van egy hatékony
packfile küldéséhez (a kanonikus implementációban ezt akkor
állapítja meg, amikor elég ACK-et kapott ahhoz, hogy mindent, ami a
--date-order sorban maradt, közösként jelölhessen meg a szerverrel,
vagy amikor a --date-order sor üres), vagy amikor a kliens úgy dönt,
hogy fel akarja adni (a kanonikus implementációban ezt akkor
állapítja meg, amikor a kliens 256 'have' sort küldött anélkül, hogy
azok közül bármelyiket is ACK-elte volna a szerver - ami azt jelenti,
hogy nincs semmi közös, és a szervernek egyszerűen az összes
objektumát el kell küldenie), akkor a kliens elküld egy 'done'
parancsot.  A 'done' parancs jelzi a szervernek, hogy a kliens készen
áll a packfile-adatai fogadására.

A 256-os korlát azonban a kanonikus kliens-implementációban *csak*
akkor kapcsol be, ha egy korábbi körben kaptunk legalább egy "ACK %s
continue"-t.  Ez segít biztosítani, hogy legalább egy közös ős
megtalálásra kerüljön, mielőtt teljesen feladnánk.

Amint a 'done' sor beolvasásra kerül a klienstől, a szerver vagy
elküld egy végső 'ACK obj-id'-t, vagy elküld egy 'NAK'-ot. Az
'obj-id' az utolsó, közösnek meghatározott commit objektumneve. A
szerver csak akkor küld ACK-et a 'done' után, ha van legalább egy
közös alap, és a multi_ack vagy a multi_ack_detailed engedélyezve
van. A szerver mindig NAK-ot küld a 'done' után, ha nem található
közös alap.

'ACK' vagy 'NAK' helyett a szerver hibaüzenetet is küldhet (például
ha nem ismer fel egy objektumot a klienstől kapott 'want' sorban).

Ezután a szerver elkezdi küldeni a packfile-adatait.

----
  server-response = *ack_multi ack / nak
  ack_multi       = PKT-LINE("ACK" SP obj-id ack_status)
  ack_status      = "continue" / "common" / "ready"
  ack             = PKT-LINE("ACK" SP obj-id)
  nak             = PKT-LINE("NAK")
----

Egy egyszerű klónozás így nézhet ki (nincsenek 'have' sorok):

----
   C: 0054want 74730d410fcb6603ace96f1dc55ea6196122532d multi_ack \
     side-band-64k ofs-delta\n
   C: 0032want 7d1665144a3a975c05f1f43902ddaf084e784dbe\n
   C: 0032want 5a3f6be755bbb7deae50065988cbfa1ffa9ab68a\n
   C: 0032want 7e47fe2bd8d01d481f44d7af0531bd93d3b21c01\n
   C: 0032want 74730d410fcb6603ace96f1dc55ea6196122532d\n
   C: 0000
   C: 0009done\n

   S: 0008NAK\n
   S: [PACKFILE]
----

Egy inkrementális frissítés (fetch) válasza így nézhet ki:

----
   C: 0054want 74730d410fcb6603ace96f1dc55ea6196122532d multi_ack \
     side-band-64k ofs-delta\n
   C: 0032want 7d1665144a3a975c05f1f43902ddaf084e784dbe\n
   C: 0032want 5a3f6be755bbb7deae50065988cbfa1ffa9ab68a\n
   C: 0000
   C: 0032have 7e47fe2bd8d01d481f44d7af0531bd93d3b21c01\n
   C: [30 more have lines]
   C: 0032have 74730d410fcb6603ace96f1dc55ea6196122532d\n
   C: 0000

   S: 003aACK 7e47fe2bd8d01d481f44d7af0531bd93d3b21c01 continue\n
   S: 003aACK 74730d410fcb6603ace96f1dc55ea6196122532d continue\n
   S: 0008NAK\n

   C: 0009done\n

   S: 0031ACK 74730d410fcb6603ace96f1dc55ea6196122532d\n
   S: [PACKFILE]
----


[[_packfile_data]]
Packfile-adatok
---------------

Most, hogy a kliens és a szerver befejezte az egyeztetést arról,
hogy mi a kliensnek küldendő adat minimális mennyisége, a szerver
elő fogja állítani és el fogja küldeni a szükséges adatot packfile
formátumban.

Hogy magának a packfile-nak ténylegesen mi is a formátuma, lásd a
linkgit:gitformat-pack[5]-öt.

Ha a kliens a 'side-band' vagy 'side-band-64k' képességeket
határozta meg, a szerver multiplexelve fogja küldeni a
packfile-adatokat.

Minden csomag a következő adat mennyiségét megadó packet-line
hosszal kezdődik, amelyet egy egyetlen bájt követ, amely megadja,
melyik sidebanden érkezik a következő adat.

'side-band' módban akár 999 adatbájtot plusz 1 vezérlőkódot küld, azaz
összesen legfeljebb 1000 bájtot egy pkt-line-ban.  'side-band-64k'
módban akár 65519 adatbájtot plusz 1 vezérlőkódot küld, azaz
összesen legfeljebb 65520 bájtot egy pkt-line-ban.

A sideband-bájt '1', '2' vagy '3' lesz. Az '1'-es sideband
packfile-adatot fog tartalmazni, a '2'-es sideband a haladási
információhoz lesz használva, amelyet a kliens általában a stderr-re
ír ki, a '3'-as sideband pedig hibainformációhoz használatos.

Ha nem lett 'side-band' képesség meghatározva, a szerver
multiplexelés nélkül fogja streamelni a teljes packfile-t.


[[_pushing_data_to_a_server]]
Adatok pusholása egy szerverre
------------------------------

Az adatok szerverre pusholása meghívja a 'receive-pack' folyamatot a
szerveren, amely lehetővé teszi a kliensnek, hogy közölje, mely
referenciákat kell frissítenie, majd elküldje azt az összes adatot,
amelyre a szervernek szüksége lesz ahhoz, hogy azok az új
referenciák teljesek legyenek.  Miután az összes adat megérkezett és
érvényesítésre került, a szerver frissíti a referenciáit a kliens
által meghatározottakra.

[[_authentication]]
Authentication
--------------

Maga a protokoll nem tartalmaz hitelesítési mechanizmusokat.  Ezt a
transportnak, például az SSH-nak kell kezelnie, mielőtt a
'receive-pack' folyamat meghívásra kerül.  Ha a 'receive-pack' a Git
transporton keresztül van konfigurálva, azok a repository-k bárki
számára írhatók lesznek, aki hozzáfér ahhoz a porthoz (9418), mivel
az a transport hitelesítés nélküli.

[[_reference_discovery_2]]
Referenciák felfedezése
-----------------------

A referencia-felfedezési fázis szinte ugyanúgy zajlik, mint a
fetchelési protokollban. A szerveren lévő minden egyes referencia
obj-id-je és neve packet-line formátumban kerül elküldésre a
kliensnek, amelyet egy flush-pkt követ.  Az egyetlen valódi
különbség az, hogy a képességlistázás eltérő - az egyetlen lehetséges
értékek a 'report-status', 'report-status-v2', 'delete-refs',
'ofs-delta', 'atomic' és 'push-options'.

[[_reference_update_request_and_packfile_transfer]]
Referenciafrissítési kérés és packfile-átvitel
----------------------------------------------

Amint a kliens tudja, hol áll a szerver a referenciákkal, elküldhet
egy listát a referenciafrissítési kérésekről.  A szerveren lévő,
frissíteni kívánt minden egyes referenciához elküld egy sort,
amely felsorolja a szerveren jelenleg lévő obj-id-t, azt az obj-id-t,
amelyre a kliens frissíteni szeretné, és a referencia nevét.

Ezt a listát egy flush-pkt követi.

----
  update-requests   =  *shallow ( command-list | push-cert )

  shallow           =  PKT-LINE("shallow" SP obj-id)

  command-list      =  PKT-LINE(command NUL capability-list)
		       *PKT-LINE(command)
		       flush-pkt

  command           =  create / delete / update
  create            =  zero-id SP new-id  SP name
  delete            =  old-id  SP zero-id SP name
  update            =  old-id  SP new-id  SP name

  old-id            =  obj-id
  new-id            =  obj-id

  push-cert         = PKT-LINE("push-cert" NUL capability-list LF)
		      PKT-LINE("certificate version 0.1" LF)
		      PKT-LINE("pusher" SP ident LF)
		      PKT-LINE("pushee" SP url LF)
		      PKT-LINE("nonce" SP nonce LF)
		      *PKT-LINE("push-option" SP push-option LF)
		      PKT-LINE(LF)
		      *PKT-LINE(command LF)
		      *PKT-LINE(gpg-signature-lines LF)
		      PKT-LINE("push-cert-end" LF)

  push-option       =  1*( VCHAR | SP )
----

Ha a szerver hirdette a 'push-options' képességet, és a kliens a
fenti képességlista részeként meghatározta a 'push-options'-t, a
kliens ezután elküldi a push-opcióit, amelyeket egy flush-pkt követ.

----
  push-options      =  *PKT-LINE(push-option) flush-pkt
----

A régebbi Git-szerverekkel való visszamenőleges kompatibilitás
érdekében, ha a kliens push cert-et és push-opciókat küld, MUST
elküldenie a push-opcióit mind a push cert-be ágyazva, mind a push
cert után is. (Vegyük észre, hogy a cert-en belüli push-opciók
prefixeltek, de a cert utáni push-opciók nem.) Ennek a két listának
MUST azonosnak lennie, a prefixtől eltekintve.

Ezután elküldésre kerül az a packfile, amelynek tartalmaznia kell
minden olyan objektumot, amelyre a szervernek szüksége lesz az új
referenciák teljessé tételéhez.

----
  packfile          =  "PACK" 28*(OCTET)
----

Ha a fogadó oldal nem támogatja a delete-refs-et, a küldő oldal MUST
NOT delete parancsot kérjen.

Ha a fogadó oldal nem támogatja a push-cert-et, a küldő oldal MUST
NOT push-cert parancsot küldjön.  Amikor egy push-cert parancs kerül
elküldésre, a command-list MUST NOT legyen elküldve; helyette a push
tanúsítványban rögzített parancsok kerülnek felhasználásra.

A packfile MUST NOT legyen elküldve, ha az egyetlen használt parancs
a 'delete'.

Egy packfile-t MUST elküldeni, ha a create vagy az update parancs
bármelyike használatban van, még akkor is, ha a szervernek már
megvan minden szükséges objektuma.  Ebben az esetben a kliensnek MUST
egy üres packfile-t küldenie.   Ez valószínűleg csak akkor fordul
elő, ha a kliens egy olyan új branchet vagy taget hoz létre, amely
egy már létező obj-id-re mutat.

A szerver megkapja a packfile-t, kicsomagolja, majd érvényesíti
minden frissítendő referenciánál, hogy az nem változott, amíg a
kérés feldolgozása folyamatban volt (az obj-id még mindig
megegyezik az old-id-vel), és lefuttatja az esetleges
frissítési hookokat, hogy megbizonyosodjon róla, a frissítés
elfogadható.  Ha ez mind rendben van, a szerver frissíti a
referenciákat.

[[_push_certificate]]
Push tanúsítvány
----------------

Egy push tanúsítvány egy fejlécsor-halmazzal kezdődik.  A fejléc és
egy üres sor után a protokollparancsok következnek, soronként egy.
Vegyük észre, hogy a push-cert PKT-LINE-okban a záró LF _nem_
opcionális; jelen kell lennie.

Jelenleg a következő fejlécmezők vannak meghatározva:

`pusher` ident::
	Azonosítja a GPG-kulcsot "Emberi Nyelvű Név <email@cím>"
	formátumban.

`pushee` url::
	A repository URL-je (anonimizálva, ha az URL hitelesítő
	anyagot tartalmaz), ahová az a felhasználó, aki futtatta a
	`git push`-t, pusholni szándékozott.

`nonce` nonce::
	Az a 'nonce' sztring, amelyet a fogadó repository kért a
	pusholó felhasználótól, hogy foglalja bele a tanúsítványba,
	a visszajátszásos támadások megelőzése érdekében.

A GPG-aláírás sorok egy leválasztott aláírást alkotnak a push
tanúsítványban rögzített tartalomhoz, mielőtt az aláírásblokk
elkezdődik.  A leválasztott aláírás azt hivatott igazolni, hogy a
parancsokat a pusholó adta ki, akinek egyben az aláírónak is kell
lennie.

[[_report_status]]
Állapotjelentés
---------------

Miután megkapta a pack-adatot a küldőtől, a fogadó jelentést küld,
ha a 'report-status' vagy a 'report-status-v2' képesség érvényben
van.  Ez egy rövid felsorolás arról, mi történt az adott
frissítésben.  Először felsorolja a packfile kicsomagolásának
állapotát, vagy 'unpack ok', vagy 'unpack [error]' formában.  Ezután
felsorolja az állapotot minden egyes referenciára, amelyet
megpróbált frissíteni.  Minden sor vagy 'ok [refname]', ha a
frissítés sikeres volt, vagy 'ng [refname] [error]', ha nem.

----
  report-status     = unpack-status
		      1*(command-status)
		      flush-pkt

  unpack-status     = PKT-LINE("unpack" SP unpack-result)
  unpack-result     = "ok" / error-msg

  command-status    = command-ok / command-fail
  command-ok        = PKT-LINE("ok" SP refname)
  command-fail      = PKT-LINE("ng" SP refname SP error-msg)

  error-msg         = 1*(OCTET) ; where not "ok"
----

A 'report-status-v2' képesség új opciósorok hozzáadásával bővíti a
protokollt, hogy támogassa a 'proc-receive' hook által átírt
referenciák jelentését.  A 'proc-receive' hook kezelhet egy parancsot
egy olyan pszeudo-referenciára, amely egy vagy több referenciát
hozhat létre vagy frissíthet, és minden egyes referenciának eltérő
neve, eltérő new-oid-ja és eltérő old-oid-ja lehet.

----
  report-status-v2  = unpack-status
		      1*(command-status-v2)
		      flush-pkt

  unpack-status     = PKT-LINE("unpack" SP unpack-result)
  unpack-result     = "ok" / error-msg

  command-status-v2 = command-ok-v2 / command-fail
  command-ok-v2     = command-ok
		      *option-line

  command-ok        = PKT-LINE("ok" SP refname)
  command-fail      = PKT-LINE("ng" SP refname SP error-msg)

  error-msg         = 1*(OCTET) ; where not "ok"

  option-line       = *1(option-refname)
		      *1(option-old-oid)
		      *1(option-new-oid)
		      *1(option-forced-update)

  option-refname    = PKT-LINE("option" SP "refname" SP refname)
  option-old-oid    = PKT-LINE("option" SP "old-oid" SP obj-id)
  option-new-oid    = PKT-LINE("option" SP "new-oid" SP obj-id)
  option-force      = PKT-LINE("option" SP "forced-update")

----

A frissítések számos okból lehetnek sikertelenek.  A referencia
megváltozhatott azóta, hogy a referencia-felfedezési fázis eredetileg
elküldésre került, ami azt jelenti, hogy időközben valaki pusholt.  A
pusholt referencia lehet egy non-fast-forward referencia, és a
frissítési hookok vagy a konfiguráció beállítható úgy, hogy ezt ne
engedje, stb.  Emellett néhány referencia frissíthető, míg mások
elutasíthatók.

Egy példa kliens/szerver kommunikáció így nézhet ki:

----
   S: 006274730d410fcb6603ace96f1dc55ea6196122532d refs/heads/local\0report-status delete-refs ofs-delta\n
   S: 003e7d1665144a3a975c05f1f43902ddaf084e784dbe refs/heads/debug\n
   S: 003f74730d410fcb6603ace96f1dc55ea6196122532d refs/heads/master\n
   S: 003d74730d410fcb6603ace96f1dc55ea6196122532d refs/heads/team\n
   S: 0000

   C: 00677d1665144a3a975c05f1f43902ddaf084e784dbe 74730d410fcb6603ace96f1dc55ea6196122532d refs/heads/debug\n
   C: 006874730d410fcb6603ace96f1dc55ea6196122532d 5a3f6be755bbb7deae50065988cbfa1ffa9ab68a refs/heads/master\n
   C: 0000
   C: [PACKDATA]

   S: 000eunpack ok\n
   S: 0018ok refs/heads/debug\n
   S: 002ang refs/heads/master non-fast-forward\n
----

GIT
---
A linkgit:git[1] csomag része
