gitprotocol-common(5)
=====================

NAME
----
gitprotocol-common - Különféle protokollokban közös dolgok

SYNOPSIS
--------
[verse]
<over-the-wire-protocol>

DESCRIPTION
-----------

Ez a dokumentum a Gitben használt különféle wire protokollokban és
fájlformátumokban közös dolgokat határozza meg.

[[_abnf_notation]]
ABNF-jelölés
------------

A protokoll-dokumentumokban az RFC 5234-ben leírt ABNF-jelölést
használjuk, azzal a kivétellel, hogy a következő helyettesítő
alapszabályok érvényesek:

----
  HEXDIG    =  DIGIT / "a" / "b" / "c" / "d" / "e" / "f"
----

A következő közös szabályokat is definiáljuk:

----
  NUL       =  %x00
  zero-id   =  40*"0"
  obj-id    =  40*(HEXDIGIT)

  refname  =  "HEAD"
  refname /=  "refs/" <see discussion below>
----

A refname egy hierarchikus oktett-karakterlánc, amely "refs/"-fel
kezdődik, és nem sérti meg a 'git-check-ref-format' parancs validálási
szabályait. Pontosabban:

. Tartalmazhatnak perjelet `/` a hierarchikus (könyvtár szerinti)
  csoportosításhoz, de egyetlen perjellel elválasztott komponens sem
  kezdődhet ponttal `.`.

. Legalább egy `/`-t tartalmazniuk kell. Ez kikényszeríti egy
  kategória, például `heads/`, `tags/` stb. jelenlétét, de a
  tényleges nevek nincsenek korlátozva.

. Sehol nem lehet bennük két egymást követő pont `..`.

. Sehol nem lehet bennük ASCII vezérlőkarakter (azaz olyan bájt,
  amelynek értéke kisebb, mint \040, vagy \177 `DEL`), szóköz,
  tilde `~`, kalap `^`, kettőspont `:`, kérdőjel `?`, csillag `*`,
  vagy nyitó szögletes zárójel `[`.

. Nem végződhetnek perjellel `/` vagy ponttal `.`.

. Nem végződhetnek a `.lock` sorozattal.

. Nem tartalmazhatják a `@{` sorozatot.

. Nem tartalmazhatnak `\\` karaktert.


[[_pkt_line_format]]
pkt-line formátum
-----------------

A hasznos adat nagy része (de nem az egésze) pkt-line-ok köré épül.

A pkt-line egy változó hosszúságú bináris karakterlánc.  A sor első
négy bájtja, a pkt-len, a sor teljes hosszát adja meg hexadecimálisan.
A pkt-len beleszámítja azt a 4 bájtot, amely a hossz hexadecimális
ábrázolását tartalmazza.

Egy pkt-line MAY bináris adatot tartalmazni, ezért a megvalósítóknak
MUST gondoskodniuk arról, hogy a pkt-line elemző/formázó rutinjai
8 bitesen tiszták legyenek.

Egy nem bináris sort SHOULD BE LF-fel lezárni, amelyet, ha jelen van,
MUST beleszámítani a teljes hosszba. A fogadóknak a nem bináris
adatot tartalmazó pkt-line-okat ugyanúgy MUST kezelniük attól
függetlenül, hogy tartalmazzák-e a záró LF-et (levágva az LF-et, ha
jelen van, és nem panaszkodva, ha hiányzik).

Egy pkt-line adatkomponensének maximális hossza 65516 bájt. A
megvalósítások MUST NOT olyan pkt-line-t küldeni, amelynek hossza
meghaladja a 65520-at (65516 bájt hasznos adat + 4 bájt hosszadat).

A megvalósítások SHOULD NOT üres pkt-line-t ("0004") küldeni.

A 0 hosszmezőjű pkt-line ("0000"), amelyet flush-pkt-nek nevezünk,
speciális eset, és MUST másképp kezelni, mint egy üres pkt-line-t
("0004").

----
  pkt-line     =  data-pkt / flush-pkt

  data-pkt     =  pkt-len pkt-payload
  pkt-len      =  4*(HEXDIG)
  pkt-payload  =  (pkt-len - 4)*(OCTET)

  flush-pkt    = "0000"
----

Példák (C stílusú karakterláncként):

----
  pkt-line          actual value
  ---------------------------------
  "0006a\n"         "a\n"
  "0005a"           "a"
  "000bfoobar\n"    "foobar\n"
  "0004"            ""
----

GIT
---
A linkgit:git[1] csomag része
