gitremote-helpers(7)
====================

NAME
----
gitremote-helpers - Helper programs to interact with remote repositories

SYNOPSIS
--------
[verse]
'git remote-<transport>' <repository> [<URL>]

DESCRIPTION
-----------

A remote helper programokat általában nem közvetlenül a végfelhasználók
használják, hanem a Git hívja meg őket, amikor olyan remote
repository-kkal kell interakcióba lépnie, amelyeket a Git nem támogat natívan.  Egy adott
helper az itt dokumentált képességek egy részhalmazát valósítja meg. Amikor a Gitnek
egy remote helper használatával kell interakcióba lépnie egy repository-val, elindítja
a helpert egy önálló folyamatként, parancsokat küld a helper
standard bemenetére, és eredményeket vár a helper standard
kimenetéről. Mivel egy remote helper a Gittől független folyamatként fut,
nincs szükség a Git újra-linkelésére egy új helper hozzáadásához, sem
arra, hogy a helpert összelinkeljék a Git implementációjával.

Minden helpernek támogatnia kell a "capabilities" parancsot, amelyet a Git
arra használ, hogy meghatározza, milyen más parancsokat fogad el a helper.  Ezek
a többi parancs arra használhatók, hogy felfedezzék és frissítsék a remote refeket,
objektumokat szállítsanak az objektumadatbázis és a remote repository között,
és frissítsék a helyi objektumtárolót.

A Git rendelkezik egy "curl" remote helper-családdal, amely különböző
átviteli protokollokat kezel, mint például a 'git-remote-http', 'git-remote-https',
'git-remote-ftp' és 'git-remote-ftps'. Ezek megvalósítják a
'fetch', 'option' és 'push' képességeket.

INVOCATION
----------

A remote helper programok egy vagy (opcionálisan) két
argumentummal vannak meghívva. Az első argumentum egy remote repository-t ad meg, ahogy a Gitben szokás;
ez vagy egy konfigurált remote neve, vagy egy URL. A második
argumentum egy URL-t ad meg; ez általában
'<transport>://<address>' alakú, de bármilyen tetszőleges sztring lehetséges.
A `GIT_DIR` környezeti változó be van állítva a remote helper számára,
és felhasználható annak meghatározására, hogy hová tárolja a további adatokat, vagy
melyik könyvtárból hívjon meg kiegészítő Git-parancsokat.

Amikor a Git egy '<transport>://<address>' alakú URL-lel találkozik, ahol
a '<transport>' egy olyan protokoll, amelyet nem tud natívan kezelni,
automatikusan meghívja a 'git remote-<transport>'-ot a teljes URL-lel mint
második argumentummal. Ha egy ilyen URL-lel közvetlenül a
parancssoron találkozik, az első argumentum ugyanaz, mint a második, és ha
egy konfigurált remote-ban találkozik vele, az első argumentum annak a remote-nak a neve.

Egy '<transport>::<address>' alakú URL kifejezetten arra utasítja a Gitet, hogy
hívja meg a 'git remote-<transport>'-ot '<address>'-szel mint második
argumentummal. Ha egy ilyen URL-lel közvetlenül a parancssoron találkozik,
az első argumentum '<address>', és ha egy
konfigurált remote-ban találkozik vele, az első argumentum annak a remote-nak a neve.

Emellett, amikor egy konfigurált remote-nak a `remote.<name>.vcs`-e
'<transport>'-ra van állítva, a Git kifejezetten meghívja a 'git remote-<transport>'-ot
'<name>'-mel mint első argumentummal. Ha be van állítva, a második argumentum
a `remote.<name>.url`; egyébként a második argumentum el van hagyva.

INPUT FORMAT
------------

A Git a remote helpernek egy parancslistát küld a standard bemeneten, soronként
egyet.  Az első parancs mindig a 'capabilities' parancs, amelyre
válaszul a remote helpernek ki kell írnia az általa támogatott
képességek listáját (lásd lentebb), amelyet egy üres sor követ.  A
capabilities parancsra adott válasz határozza meg, mely parancsokat használja a Git
a parancsfolyam további részében.

A parancsfolyamot egy üres sor zárja le.  Egyes esetekben
(a releváns parancsok dokumentációjában jelezve) ezt az üres
sort egy másik protokollban lévő payload követi (pl. a pack
protokoll), míg másokban ez a bemenet végét jelzi.

[[_capabilities]]
Képességek
~~~~~~~~~~

Minden remote helpertől elvárt, hogy csak a parancsok egy részhalmazát támogassa.
Azokat a műveleteket, amelyeket egy helper támogat, a `capabilities` parancsra adott
válaszban jelenti be a Gitnek (lásd a COMMANDS szakaszt lentebb).

Az alábbiakban felsoroljuk az összes definiált képességet, és
mindegyikhez felsoroljuk, mely parancsokat kell biztosítania egy ilyen
képességgel rendelkező helpernek.

[[_capabilities_for_pushing]]
Képességek pusholáshoz
^^^^^^^^^^^^^^^^^^^^^^
'connect'::
	Megkísérelhet kapcsolódni a 'git receive-pack'-hez (pusholáshoz),
	'git upload-pack'-hez stb. a git natív packfile
	protokollját használó kommunikációhoz. Ez
	egy kétirányú, full-duplex kapcsolatot igényel.
+
Támogatott parancsok: 'connect'.

'stateless-connect'::
	Kísérleti; csak belső használatra.
	Megkísérelhet kapcsolódni egy remote szerverhez a git wire-protocol
	version 2-jét használó kommunikációhoz.  További információért lásd
	a stateless-connect parancs dokumentációját.
+
Támogatott parancsok: 'stateless-connect'.

'push'::
	Felfedezheti a remote refeket, és pusholhatja a helyi commitokat és az
	azokhoz vezető történetet új vagy meglévő remote refekbe.
+
Támogatott parancsok: 'list for-push', 'push'.

'export'::
	Felfedezheti a remote refeket, és pusholhatja a megadott objektumokat egy
	fast-import streamből a remote refekbe.
+
Támogatott parancsok: 'list for-push', 'export'.

Ha egy helper hirdeti a 'connect'-et, a Git ha lehetséges, azt fogja
használni, és visszaesik egy másik képességre, ha a helper ezt kéri
kapcsolódáskor (lásd a 'connect' parancsot a COMMANDS alatt).
A 'push' és az 'export' közötti választáskor a Git a 'push'-t preferálja.
Más frontendeknek más preferencia-sorrendjük lehet.

'no-private-update'::
	Amikor a 'refspec' képesség használatban van, a git normál esetben frissíti a
	privát refet egy sikeres push után. Ez a frissítés le van tiltva, amikor
	a remote-helper hirdeti a 'no-private-update' képességet.


[[_capabilities_for_fetching]]
Képességek fetcheléshez
^^^^^^^^^^^^^^^^^^^^^^^
'connect'::
	Megkísérelhet kapcsolódni a 'git upload-pack'-hez (fetcheléshez),
	'git receive-pack'-hez stb. a Git natív
	packfile protokollját használó kommunikációhoz. Ez
	egy kétirányú, full-duplex kapcsolatot igényel.
+
Támogatott parancsok: 'connect'.

'stateless-connect'::
	Kísérleti; csak belső használatra.
	Megkísérelhet kapcsolódni egy remote szerverhez a git wire-protocol
	version 2-jét használó kommunikációhoz.  További információért lásd
	a stateless-connect parancs dokumentációját.
+
Támogatott parancsok: 'stateless-connect'.

'fetch'::
	Felfedezheti a remote refeket, és az azokból elérhető objektumokat
	átviheti a helyi objektumtárolóba.
+
Támogatott parancsok: 'list', 'fetch'.

'import'::
	Felfedezheti a remote refeket, és az azokból elérhető objektumokat
	streamként adhatja ki fast-import formátumban.
+
Támogatott parancsok: 'list', 'import'.

'check-connectivity'::
	Garantálhatja, hogy amikor egy klónozást kérnek, a fogadott
	pack önmagában teljes, és összekapcsolt.

'get'::
	Használhatja a 'get' parancsot egy fájl letöltéséhez egy megadott URI-ból.

Ha egy helper hirdeti a 'connect'-et, a Git ha lehetséges, azt fogja
használni, és visszaesik egy másik képességre, ha a helper ezt kéri
kapcsolódáskor (lásd a 'connect' parancsot a COMMANDS alatt).
A 'fetch' és az 'import' közötti választáskor a Git a 'fetch'-et preferálja.
Más frontendeknek más preferencia-sorrendjük lehet.

[[_miscellaneous_capabilities]]
Egyéb képességek
^^^^^^^^^^^^^^^^

'option'::
	Olyan beállítások megadására, mint a `verbosity` (mennyi kimenetet
	írjon a stderr-re) és a `depth` (mennyi történet szükséges egy
	shallow clone esetén), amelyek befolyásolják, hogyan hajtódnak végre a
	többi parancsok.

'refspec' <refspec>::
	Az 'import' vagy 'export' képességet megvalósító remote helperek esetén ez a képesség
	lehetővé teszi, hogy a refek egy privát névtérre legyenek korlátozva, ahelyett hogy
	közvetlenül a refs/heads-be vagy refs/remotes-ba írnának.
	Ajánlott, hogy minden importer, amely az 'import'
	képességet biztosítja, ezt használja. Az 'export' esetén kötelező.
+
Egy helper, amely hirdeti a
`refspec refs/heads/*:refs/svn/origin/branches/*` képességet,
azt mondja, hogy amikor arra kérik, hogy `import refs/heads/topic`, az
általa kiadott stream a `refs/svn/origin/branches/topic`
refet fogja frissíteni.
+
Ez a képesség többször is hirdethető.  Az első
alkalmazható refspec élvez elsőbbséget.  Az ezzel a képességgel
hirdetett refspecek bal oldalának le kell fednie a list parancs által jelentett
összes refet.  Ha nincs 'refspec' képesség hirdetve,
egy implicit `refspec *:*` érvényesül.
+
Elosztott verziókövető rendszerekhez remote-helperek
írásakor javasolt megtartani a repository egy helyi másolatát, amellyel
interakcióba lehet lépni, és hagyni, hogy a privát névtér refjei erre a
helyi repository-ra mutassanak, míg a refs/remotes névteret a
remote repository követésére használják.

'bidi-import'::
	Ez módosítja az 'import' képességet.
	A fast-import 'cat-blob' és 'ls' parancsai a remote-helperek által
	használhatók, hogy információt szerezzenek a fast-import memóriájában már
	létező blobokról és fákról. Ez egy csatornát igényel a fast-importtól a
	remote-helperhez.
	Ha az "import" mellett is hirdetve van, a Git egy pipe-ot létesít a
	fast-importtól a remote-helper stdin-jéhez.
	Ebből következik, hogy a Git és a fast-import is a
	remote-helper stdin-jéhez kapcsolódik. Mivel a Git több parancsot is küldhet
	a remote-helpernek, szükséges, hogy azok a helperek, amelyek a 'bidi-import'-ot használják,
	egy batch összes 'import' parancsát pufferelje, mielőtt adatokat küldenek a fast-importnak.
	Ez azért van, hogy megelőzze a parancsok és a fast-import válaszok keveredését a
	helper stdin-jén.

'export-marks' <file>::
	Ez módosítja az 'export' képességet, utasítva a Gitet, hogy a befejezéskor dumpolja a
	belső marks-táblát a <file>-ba. A részletekért
	olvasd el a `--export-marks=<file>`-t a linkgit:git-fast-export[1] oldalon.

'import-marks' <file>::
	Ez módosítja az 'export' képességet, utasítva a Gitet, hogy töltse be a
	<file>-ban megadott marks-okat, mielőtt bármilyen bemenetet feldolgozna. A részletekért
	olvasd el a `--import-marks=<file>`-t a linkgit:git-fast-export[1] oldalon.

'signed-tags'::
	Ez módosítja az 'export' képességet, utasítva a Gitet, hogy adja át
	a `--signed-tags=verbatim`-ot a linkgit:git-fast-export[1] parancsnak.  Ennek
	a képességnek a hiányában a Git a `--signed-tags=warn-strip`-et fogja használni.

'object-format'::
	Ez azt jelzi, hogy a helper képes egy explicit hash-algoritmus
	kiterjesztés használatával interakcióba lépni a remote oldallal.


COMMANDS
--------

A parancsokat a hívó adja meg a helper standard bemenetén, soronként egyet.

'capabilities'::
	Felsorolja a helper képességeit, soronként egyet, üres
	sorral zárva. Minden képességet megelőzhet egy '*',
	amely azt jelzi, hogy kötelező a remote helpert használó Git-
	verzióknak megérteniük. Bármely ismeretlen kötelező képesség
	végzetes hiba.
+
Ennek a parancsnak a támogatása kötelező.

'list'::
	Felsorolja a refeket, soronként egyet, "<value> <name>
	[<attr> ...]" formátumban. Az érték lehet egy hex sha1 hash, "@<dest>"
	egy symref esetén, ":<keyword> <value>" egy kulcs-érték pár esetén, vagy
	"?", ha a helper nem tudta megszerezni a ref
	értékét. A nevet egy szóközzel elválasztott attribútumlista követi;
	a fel nem ismert attribútumok figyelmen kívül maradnak. A lista üres
	sorral ér véget.
+
A jelenleg definiált attribútumok listájáért lásd a REF LIST ATTRIBUTES szakaszt.
A jelenleg definiált kulcsszavak listájáért lásd a REF LIST KEYWORDS szakaszt.
+
Támogatott, ha a helper rendelkezik a "fetch" vagy "import" képességgel.

'list for-push'::
	Hasonló a 'list'-hez, azzal a különbséggel, hogy akkor és csak akkor van
	használva, ha a hívó push-parancsok
	előkészítéséhez akarja használni az eredményül kapott ref-listát.
	Egy helper, amely mind a pushot, mind a fetchet támogatja, ezt felhasználhatja
	annak megkülönböztetésére, hogy melyik művelethez lesz felhasználva a 'list'
	kimenete, esetleg csökkentve az elvégzendő
	munka mennyiségét.
+
Támogatott, ha a helper rendelkezik a "push" vagy "export" képességgel.

'option' <name> <value>::
	Beállítja a <name> transport helper opciót <value>-ra.  Kiad egy
	egysoros választ, amely a következők egyike: 'ok' (az opció sikeresen be lett állítva),
	'unsupported' (az opció nem ismert fel) vagy 'error <msg>'
	(a <name> opció támogatott, de a <value> nem érvényes
	hozzá).  Az opciókat a többi parancs előtt kell beállítani,
	és befolyásolhatják azok viselkedését.
+
A jelenleg definiált opciók listájáért lásd az OPTIONS szakaszt.
+
Támogatott, ha a helper rendelkezik az "option" képességgel.

'fetch' <sha1> <name>::
	Fetcheli a megadott objektumot, a szükséges objektumokat
	az adatbázisba írva.  A fetch parancsok egy batch-ben vannak küldve, soronként
	egy, üres sorral lezárva.
	Egyetlen üres sort ad ki, amikor ugyanannak a batchnek az összes fetch parancsa
	befejeződött. Csak azok az objektumok fetchelhetők így, amelyek
	a 'list' kimenetében sha1-gyel voltak jelentve.
+
Opcionálisan kiadhat egy 'lock <file>' sort, amely egy fájl teljes útvonalát jelzi
a `$GIT_DIR/objects/pack` alatt, amely megtart egy packet, amíg
a refek megfelelően frissíthetők.  Az útvonalnak `.keep`-re kell végződnie. Ez
egy mechanizmus egy <pack,idx,keep> hármas megnevezésére csak a keep
komponens megadásával.  A megtartott packet egy párhuzamos repack nem fogja törölni,
még akkor sem, ha az objektumaira esetleg nem hivatkoznak, amíg a fetch be nem fejeződik.
A `.keep` fájl törlésre kerül a fetch végén.
+
Ha a 'check-connectivity' opció kérve van, a helpernek ki kell adnia
a 'connectivity-ok'-ot, ha a klón önmagában teljes és összekapcsolt.
+
Támogatott, ha a helper rendelkezik a "fetch" képességgel.

'push' +<src>:<dst>::
	Pusholja a megadott helyi <src> commitot vagy branchet a
	<dst> által leírt remote branchre.  Egy vagy több
	'push' parancsból álló batch-szekvenciát egy üres sor zár le
	(ha csak egy referenciát kell pusholni, egyetlen 'push' parancsot
	egy üres sor követ). Például a következő két 'push'
	batch lenne, az első arra kéri a remote-helpert,
	hogy pusholja a helyi 'master' refet a remote 'master' refre, és
	a helyi `HEAD`-et a remote 'branch'-re, a második pedig
	arra kéri, hogy pusholja a 'foo' refet a 'bar' refre (a '+' által kért
	kényszerített frissítéssel).
+
------------
push refs/heads/master:refs/heads/master
push HEAD:refs/heads/branch
\n
push +refs/heads/foo:refs/heads/bar
\n
------------
+
Nulla vagy több protokoll-opció adható meg az utolsó 'push'
parancs után, a batch záró üres sora előtt.
+
Amikor a push befejeződik, egy vagy több 'ok <dst>' vagy
'error <dst> <why>?' sort ad ki, hogy jelezze az egyes pusholt
refek sikerét vagy sikertelenségét.  A státuszjelentés kimenetét
egy üres sor zárja le.  A <why> opciómező C-
stílusú sztringben idézőjelezhető, ha LF-et tartalmaz.
+
Támogatott, ha a helper rendelkezik a "push" képességgel.

'import' <name>::
	Előállít egy fast-import streamet, amely importálja a megnevezett ref
	aktuális értékét. Emellett szükség szerint más refeket is importálhat, hogy
	hatékonyan felépítse a történetet. A szkript egy helper-
	specifikus privát névtérbe ír. A megnevezett
	ref értékét ennek a névtérnek egy olyan helyére kell írni, amelyet
	a "refspec" képesség refspecjeinek a ref nevére
	alkalmazásával kapunk.
+
Különösen hasznos egy idegen verziókövető rendszerrel való
interoperabilitáshoz.
+
Ugyanúgy, mint a 'push' esetén, egy vagy több 'import'-ból álló batch-szekvenciát
egy üres sor zár le. Az 'import' minden batchjéhez a remote
helpernek egy 'done' paranccsal lezárt fast-import streamet kell előállítania.
+
Vedd figyelembe, hogy ha a 'bidi-import' képesség használatban van, a teljes batch-
szekvenciát pufferelni kell, mielőtt elkezdenénk adatokat küldeni a fast-importnak,
hogy megelőzzük a parancsok és a fast-import válaszok keveredését a helper
stdin-jén.
+
Támogatott, ha a helper rendelkezik az "import" képességgel.

'export'::
	Utasítja a remote helpert, hogy minden ezt követő bemenet
	egy (a 'git fast-export' által generált) fast-import stream része,
	amely a remote-ba pusholandó objektumokat tartalmazza.
+
Különösen hasznos egy idegen verziókövető rendszerrel való
interoperabilitáshoz.
+
Az 'export-marks' és 'import-marks' képességek, ha meg vannak adva,
annyiban befolyásolják ezt a parancsot, hogy át vannak adva a 'git
fast-export'-nak, amely ekkor betölti/tárolja a helyi objektumok marks-
tábláját. Ez felhasználható inkrementális
műveletek megvalósításához.
+
Támogatott, ha a helper rendelkezik az "export" képességgel.

'connect' <service>::
	Kapcsolódik a megadott szolgáltatáshoz. A helper standard bemenete
	és standard kimenete a megadott szolgáltatáshoz (a git előtag
	a szolgáltatásnévben szerepel, így pl. a fetchelés 'git-upload-pack'-et használ
	szolgáltatásként) van kapcsolva a remote oldalon. Az erre a parancsra adott
	érvényes válaszok: üres sor (a kapcsolat létrejött), 'fallback' (nincs smart
	transport támogatás, visszaesés dumb transportokra), és egyszerűen
	kilépés hibaüzenet kiírásával (nem lehet kapcsolódni, ne
	próbálkozz visszaeséssel). A pozitív (üres) választ lezáró soremelés után
	elkezdődik a szolgáltatás kimenete. A kapcsolat végén a remote helper kilép.
+
Támogatott, ha a helper rendelkezik a "connect" képességgel.

'stateless-connect' <service>::
	Kísérleti; csak belső használatra.
	Kapcsolódik a megadott remote szolgáltatáshoz a git wire-
	protocol version 2-jét használó kommunikációhoz.  Az erre a parancsra adott
	érvényes válaszok: üres sor (a kapcsolat létrejött), 'fallback' (nincs smart
	transport támogatás, visszaesés dumb transportokra), és egyszerűen
	kilépés hibaüzenet kiírásával (nem lehet kapcsolódni, ne próbálkozz
	visszaeséssel).  A pozitív (üres) választ lezáró soremelés után
	elkezdődik a szolgáltatás kimenete.  Az üzeneteknek
	(mind a kérésnek, mind a válasznak) nulla vagy több
	PKT-LINE-ból kell állniuk, egy flush csomaggal lezárva. A válaszüzenetek
	ezután egy válasz-vég csomagot tartalmaznak a flush csomag után, hogy
	jelezzék egy válasz végét.  A kliens nem várhatja el, hogy
	a szerver bármilyen állapotot tároljon a kérés-válasz
	párok között.  A kapcsolat végén a remote helper kilép.
+
Támogatott, ha a helper rendelkezik a "stateless-connect" képességgel.

'get' <uri> <path>::
	Letölti a fájlt a megadott `<uri>`-ból a megadott `<path>`-ra. Ha
	a `<path>.temp` létezik, a Git feltételezi, hogy a `.temp` fájl egy
	korábbi kísérletből származó részleges letöltés, és onnan folytatja a
	letöltést.

Ha végzetes hiba történik, a program kiírja a hibaüzenetet a
stderr-re, és kilép. A hívónak fel kell készülnie arra, hogy egy megfelelő hiba-
üzenet ki lett írva, ha a gyermek folyamat lezárja a kapcsolatot anélkül,
hogy egy érvényes választ adott volna az aktuális parancsra.

További parancsok is támogatottak lehetnek, ahogy az a helper
által jelentett képességekből megállapítható.

REF LIST ATTRIBUTES
-------------------

A 'list' parancs egy reflistát állít elő, amelyben minden refet
követhet egy attribútumlista. A következő ref-lista
attribútumok vannak definiálva.

'unchanged'::
	Ez a ref változatlan az utolsó import vagy fetch óta, bár
	a helper nem feltétlenül tudja megállapítani, milyen érték jött ki abból.

REF LIST KEYWORDS
-----------------

A 'list' parancs előállíthat egy kulcs-érték pár listát.
A következő kulcsok vannak definiálva.

'object-format'::
	A refek a megadott hash-algoritmust használják.  Ez a kulcsszó csak akkor
	van használva, ha mind a szerver, mind a kliens támogatja az object-format
	kiterjesztést.


OPTIONS
-------

A következő opciók vannak definiálva, és (megfelelő körülmények között)
a Git állítja be őket, ha a remote helper rendelkezik az 'option' képességgel.

'option verbosity' <n>::
	Megváltoztatja a helper által megjelenített üzenetek részletességét.
	A <n> 0 értéke azt jelenti, hogy a folyamatok
	csendben működnek, és a helper csak hibakimenetet ad.
	Az 1 a részletesség alapértelmezett szintje, és a <n> magasabb
	értékei a parancssoron átadott -v flagek
	számának felelnek meg.

'option progress' {'true'|'false'}::
	Engedélyezi (vagy letiltja) a transport helper által egy
	parancs közben megjelenített folyamatüzeneteket.

'option depth' <depth>::
	Elmélyíti egy shallow repository történetét.

'option deepen-since' <timestamp>::
	Elmélyíti egy shallow repository történetét idő alapján.

'option deepen-not' <ref>::
	Elmélyíti egy shallow repository történetét, kizárva a refet.
	Több opció összeadódik.

'option deepen-relative' {'true'|'false'}::
	Elmélyíti egy shallow repository történetét az aktuális
	határhoz képest. Csak akkor érvényes, ha az "option depth"-tel együtt van használva.

'option followtags' {'true'|'false'}::
	Ha engedélyezve van, a helpernek automatikusan fetchelnie kell az annotált
	tag-objektumokat, ha az az objektum, amelyre a tag mutat, át lett vive
	a fetch parancs során.  Ha a tag-et a helper nem
	fetcheli, általában egy második fetch parancs lesz küldve, hogy
	kifejezetten a tag-et kérje.  Egyes helperek képesek lehetnek
	ezt az opciót felhasználni egy második hálózati kapcsolat elkerülésére.

'option dry-run' {'true'|'false'}::
	Ha true, úgy tesz, mintha a művelet sikeresen befejeződött volna,
	de valójában nem változtat semmilyen repository-adatot.  A legtöbb
	helper esetén ez csak a 'push'-ra vonatkozik, ha támogatott.

'option servpath <c-style-quoted-path>'::
	Beállítja a szolgáltatás útvonalát (--upload-pack, --receive-pack stb.) a
	következő connecthez. A remote helper támogathatja ezt az opciót, de
	nem támaszkodhat arra, hogy ez az opció be van állítva a
	connect kérés előtt.

'option check-connectivity' {'true'|'false'}::
	Kéri a helpert, hogy ellenőrizze egy klón összekapcsoltságát.

'option force' {'true'|'false'}::
	Kéri a helpert, hogy hajtson végre kényszerített frissítést.  Alapból
	'false'.

'option cloning' {'true'|'false'}::
	Értesíti a helpert, hogy ez egy klónozási kérés (azaz az aktuális
	repository garantáltan üres).

'option update-shallow' {'true'|'false'}::
	Lehetővé teszi a .git/shallow kiterjesztését, ha az új refek ezt megkövetelik.

'option pushcert' {'true'|'false'}::
	GPG-vel aláírja a pusholásokat.

'option push-option' <string>::
	Átadja a <string>-et push-opcióként. Mivel a push-opció
	nem tartalmazhat LF vagy NUL karaktert, a sztring nincs kódolva.

'option from-promisor' {'true'|'false'}::
	Jelzi, hogy ezek az objektumok egy promisorból vannak fetchelve.

'option no-dependents' {'true'|'false'}::
	Jelzi, hogy csak a kívánt objektumokat kell fetchelni, a
	függőségeiket nem.

'option atomic' {'true'|'false'}::
	Pusholáskor kéri a remote szervert, hogy egyetlen atomi
	tranzakcióban frissítse a refeket.  Siker esetén minden ref frissül, vagy egyik sem.  Ha a
	remote oldal nem támogatja ezt a képességet, a push meghiúsul.

'option object-format true'::
	Jelzi, hogy a hívó azt akarja, hogy a hash-algoritmus információ
	visszaadásra kerüljön a remote-tól.  Ez a mód refek fetchelésekor van
	használva.

SEE ALSO
--------
linkgit:git-remote[1]

linkgit:git-remote-ext[1]

linkgit:git-remote-fd[1]

linkgit:git-fast-import[1]

GIT
---
A linkgit:git[1] csomag része
