gitsubmodules(7)
================

NAME
----
gitsubmodules - Egy repository beágyazása egy másikba

SYNOPSIS
--------
 .gitmodules, $GIT_DIR/config

------------------
git submodule
git <command> --recurse-submodules
------------------

DESCRIPTION
-----------

A submodule egy másik repositoryba beágyazott repository.
A submodule-nak saját története van; azt a repositoryt, amelybe be van
ágyazva, szuperprojektnek nevezzük.

A fájlrendszeren egy submodule általában (de nem mindig – lásd a FORMS
szakaszt lentebb) a következőkből áll: (i) egy Git-könyvtár, amely a
szuperprojekt `$GIT_DIR/modules/` könyvtára alatt található, (ii) egy
munkakönyvtár a szuperprojekt munkakönyvtárán belül, és egy `.git` fájl a
submodule munkakönyvtárának gyökerében, amely (i)-re mutat.

Feltéve, hogy a submodule Git-könyvtára a `$GIT_DIR/modules/foo/`, a
munkakönyvtára pedig a `path/to/bar/`, a szuperprojekt egy `gitlink`
bejegyzéssel követi a submodule-t a `path/to/bar` helyen lévő fában, és egy
`submodule.foo.path = path/to/bar` alakú bejegyzéssel a `.gitmodules`
fájljában (lásd linkgit:gitmodules[5]).

A `gitlink` bejegyzés annak a commitnak az objektumnevét tartalmazza,
amelyen a szuperprojekt a submodule munkakönyvtárát várja.

A `.gitmodules` fájl `submodule.foo.*` szekciója további támpontokat ad a
Git porcelain rétegének. Például a `submodule.foo.url` beállítás megadja,
honnan szerezhető be a submodule.

A submodule-ok legalább két különböző felhasználási esetben hasznosak:

1. Egy másik projekt használata független történet megőrzése mellett.
  A submodule-ok lehetővé teszik, hogy egy másik projekt working tree-jét a
  saját working tree-den belül tartsd, miközben a két projekt története
  külön marad. Továbbá mivel a submodule-ok egy tetszőleges verzióhoz
  vannak rögzítve, a másik projekt függetlenül fejleszthető a szuperprojekt
  befolyásolása nélkül, így a szuperprojekt csak akkor rögzíti magát új
  verziókhoz, amikor szükséges.

2. Egy (logikailag egységes) projekt több repositoryra bontása, majd azok
   összekötése. Ezzel áthidalhatók a Git jelenlegi implementációjának
   korlátai, finomabb hozzáférés-szabályozás érdekében:

    * A Git repository mérete:
      Jelenlegi formájában a Git rosszul skálázódik olyan nagy
      repositorykhoz, amelyek tartalmát nem tömöríti a fák közötti
      delta-számítás. Használhatsz például submodule-okat nagy bináris
      assetek tárolására, és ezek a repositoryk sekélyen klónozhatók, így
      nem lesz nagy történet lokálisan.
    * Átviteli méret:
      Jelenlegi formájában a Git megköveteli a teljes working tree
      jelenlétét. Nem engedi részleges fák átvitelét fetch vagy clone során.
      Ha a projekt, amelyen dolgozol, több, egy szuperprojektben
      submodule-ként összekötött repositoryból áll, elkerülheted az általad
      nem használt repositoryk working tree-jének fetchelését.
    * Hozzáférés-szabályozás:
      A felhasználók submodule-okhoz való hozzáférésének korlátozásával
      írási/olvasási házirendek valósíthatók meg különböző felhasználók
      számára.

[[_the_configuration_of_submodules]]
A submodule-ok konfigurációja
-----------------------------

A submodule-műveletek a következő mechanizmusokkal konfigurálhatók
(a legmagasabbtól a legalacsonyabb prioritásig):

 * A parancssor azoknál a parancsoknál, amelyek támogatják a submodule-ok
   megadását a pathspecük részeként. A legtöbb parancsnak van egy
   `--recurse-submodules` logikai kapcsolója, amely megadja, hogy be
   kell-e lépni rekurzívan a submodule-okba. Ilyen például a `grep` és a
   `checkout`. Néhány parancs felsorolást vár, például a `fetch` és a
   `push`, ahol megadhatod, hogyan érinti a submodule-okat.

 * A submodule-on belüli konfiguráció. Ez magában foglalja a submodule
   `$GIT_DIR/config` fájlját, de a fában lévő beállításokat is, például a
   `.gitattributes` vagy `.gitignore` fájlokat, amelyek a submodule-on
   belüli parancsok viselkedését adják meg.
+
A submodule `.gitignore` fájljának hatása például akkor figyelhető meg,
amikor a szuperprojektben lefuttatod a `git status --ignore-submodules=none`
parancsot. Ez a submodule munkakönyvtárából gyűjt információt úgy, hogy a
submodule-ban lefuttatja a `status`-t, miközben figyelembe veszi a
submodule `.gitignore` fájlját.
+
A submodule `$GIT_DIR/config` fájlja akkor lép életbe, amikor a
szuperprojektben a `git push --recurse-submodules=check` fut, mivel ez
ellenőrzi, hogy a submodule-nak vannak-e olyan változásai, amelyek nincsenek
közzétéve egyetlen remote-ra sem. A remote-okat a submodule-ban a szokásos
módon, a `$GIT_DIR/config` fájlban konfigurálják.

 * A `$GIT_DIR/config` konfigurációs fájl a szuperprojektben. A Git csak az
   aktív submodule-okba lép be rekurzívan (lásd az "ACTIVE SUBMODULES"
   szakaszt lentebb).
+
Ha a submodule még nincs inicializálva, akkor a submodule-on belüli
konfiguráció még nem létezik, így például itt van konfigurálva, honnan
szerezhető be a submodule.

 * A `.gitmodules` fájl a szuperprojekten belül. Egy projekt általában
   ezzel a fájllal javasol alapértelmezéseket a repositoryk upstream
   gyűjteményéhez, a submodule neve és útvonala közti kötelező leképezéshez.
+
Ez a fájl főként a submodule-ok neve és útvonala közti leképezésként szolgál
a szuperprojektben, hogy a submodule Git-könyvtára megtalálható legyen.
+
Ha a submodule-t soha nem inicializálták, ez az egyetlen hely, ahol a
submodule konfigurációja megtalálható. Ez az utolsó tartalék annak
megadására, honnan szerezhető be a submodule.

FORMS
-----

A submodule-ok a következő alakokat vehetik fel:

 * A DESCRIPTION szakaszban leírt alapalak: egy Git-könyvtár, egy
munkakönyvtár, egy `gitlink` és egy `.gitmodules` bejegyzés.

 * „Régi alakú" submodule: egy munkakönyvtár beágyazott `.git` könyvtárral,
valamint a nyomkövető `gitlink` és `.gitmodules` bejegyzés a
szuperprojektben. Ez jellemzően a Git régebbi verzióival létrehozott
repositorykban fordul elő.
+
Ezek a régi alakú repositoryk kézzel is felépíthetők.
+
Deinicializáláskor vagy törléskor (lásd lentebb) a submodule Git-könyvtára
automatikusan a szuperprojekt `$GIT_DIR/modules/<name>/` könyvtárába kerül.

 * Deinicializált submodule: egy `gitlink` és egy `.gitmodules` bejegyzés,
de nincs submodule-munkakönyvtár. A submodule Git-könyvtára ott lehet, mert
deinicializálás után a Git-könyvtár megmarad. Az a könyvtár viszont, amely a
munkakönyvtár lenne, üres.
+
Egy submodule a `git submodule deinit` futtatásával deinicializálható. A
munkakönyvtár kiürítésén túl ez a parancs csak a szuperprojekt
`$GIT_DIR/config` fájlját módosítja, így a szuperprojekt történetét nem
érinti. Ez a `git submodule init` használatával visszavonható.

 * Törölt submodule: egy submodule a `git rm <submodule-path> && git commit`
futtatásával törölhető. Ez a `git revert` használatával visszavonható.
+
A törlés eltávolítja a szuperprojekt nyomkövetési adatait, azaz mind a
`gitlink` bejegyzést, mind a `.gitmodules` fájlbeli szekciót. A submodule
munkakönyvtára eltűnik a fájlrendszerről, de a Git-könyvtár megmarad, hogy a
korábbi commitok checkoutolása másik repositoryból való fetchelés nélkül is
lehetséges legyen.
+
Egy submodule teljes eltávolításához töröld kézzel a
`$GIT_DIR/modules/<name>/` könyvtárat.

ACTIVE SUBMODULES
-----------------

Egy submodule akkor számít aktívnak,

  1. ha a `submodule.<name>.active` értéke `true`
+
vagy

  2. ha a submodule útvonala illeszkedik a `submodule.active` pathspecére
+
vagy

  3. ha a `submodule.<name>.url` be van állítva.

és ezek ebben a sorrendben értékelődnek ki.

Például:

  [submodule "foo"]
    active = false
    url = https://example.org/foo
  [submodule "bar"]
    active = true
    url = https://example.org/bar
  [submodule "baz"]
    url = https://example.org/baz

A fenti konfigurációban csak a 'bar' és a 'baz' submodule aktív, a 'bar' az
(1) miatt, a 'baz' a (3) miatt. A 'foo' inaktív, mert az (1) elsőbbséget
élvez a (3)-mal szemben

Vedd figyelembe, hogy a (3) történelmi maradvány, és figyelmen kívül marad,
ha az (1) és a (2) azt jelzi, hogy a submodule nem aktív. Más szóval, ha a
`submodule.<name>.active` értéke `false`, vagy ha a submodule útvonala ki van
zárva a `submodule.active` pathspecében, akkor mindegy, hogy az url jelen
van-e vagy sem. Ezt szemlélteti a következő példa.

  [submodule "foo"]
    active = true
    url = https://example.org/foo
  [submodule "bar"]
    url = https://example.org/bar
  [submodule "baz"]
    url = https://example.org/baz
  [submodule "bob"]
    ignore = true
  [submodule]
    active = b*
    active = :(exclude) baz

Itt a 'baz' kivételével minden submodule (foo, bar, bob) aktív. A 'foo' a
saját active kapcsolója miatt, a többi pedig a submodule active pathspec
miatt, amely azt adja meg, hogy minden 'b'-vel kezdődő submodule a 'baz'
kivételével szintén aktív, függetlenül a .url mező jelenlététől.

[[_workflow_for_a_third_party_library]]
Munkafolyamat harmadik féltől származó könyvtárhoz
--------------------------------------------------

  # Add a submodule
  git submodule add <URL> <path>

  # Occasionally update the submodule to a new version:
  git -C <path> checkout <new-version>
  git add <path>
  git commit -m "update submodule to new version"

  # See the list of submodules in a superproject
  git submodule status

  # See FORMS on removing submodules


[[_workflow_for_an_artificially_split_repo]]
Munkafolyamat mesterségesen felbontott repositoryhoz
----------------------------------------------------

  # Enable recursion for relevant commands, such that
  # regular commands recurse into submodules by default
  git config --global submodule.recurse true

  # Unlike most other commands below, clone still needs
  # its own recurse flag:
  git clone --recurse <URL> <directory>
  cd <directory>

  # Get to know the code:
  git grep foo
  git ls-files --recurse-submodules

[NOTE]
A `git ls-files` szintén megköveteli a saját `--recurse-submodules`
kapcsolóját.

  # Get new code
  git fetch
  git pull --rebase

  # Change worktree
  git checkout
  git reset

[[_implementation_details]]
Megvalósítási részletek
-----------------------

Submodule-okat tartalmazó repository klónozásakor vagy pull-olásakor a
submodule-ok alapértelmezés szerint nem lesznek checkoutolva; utasíthatod a
`clone`-t, hogy lépjen be rekurzívan a submodule-okba. A `git submodule`
`init` és `update` alparancsa checkoutolva és a working tree-ben megfelelő
revízión tartja a submodule-okat. Alternatívaként beállíthatod a
`submodule.recurse`-t, hogy a `checkout` rekurzívan belépjen a
submodule-okba (a `submodule.recurse` más Git-parancsokat is befolyásol,
a teljes listát lásd linkgit:git-config[1]).


SEE ALSO
--------
linkgit:git-submodule[1], linkgit:gitmodules[5].

GIT
---
A linkgit:git[1] csomag része
