gittutorial-2(7)
================

NAME
----
gittutorial-2 - Bevezető ismertető a Githez: második rész

SYNOPSIS
--------
[verse]
git *

DESCRIPTION
-----------

Ezen ismertető elolvasása előtt dolgozd át a linkgit:gittutorial[7]-et.

Ennek az ismertetőnek a célja, hogy bemutassa a Git architektúrájának két
alapvető darabját – az objektumadatbázist és az indexfájlt –, és hogy
mindent az olvasó rendelkezésére bocsásson, ami a Git dokumentáció
többi részének megértéséhez szükséges.

[[_the_git_object_database]]
A Git objektumadatbázisa
------------------------

Kezdjünk egy új projektet, és hozzunk létre egy kis történetet:

------------------------------------------------
$ mkdir test-project
$ cd test-project
$ git init
Initialized empty Git repository in .git/
$ echo 'hello world' > file.txt
$ git add .
$ git commit -a -m "initial commit"
[master (root-commit) 54196cc] initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 file.txt
$ echo 'hello world!' >file.txt
$ git commit -a -m "add emphasis"
[master c4d59f3] add emphasis
 1 file changed, 1 insertion(+), 1 deletion(-)
------------------------------------------------

Mi az a 7 hexadecimális számjegy, amivel a Git a commitra válaszolt?

Az ismertető első részében láttuk, hogy a commitoknak ilyen neveik
vannak. Kiderül, hogy a Git történetében minden objektum egy 40 jegyű
hex név alatt van tárolva. Ez a név az objektum tartalmának SHA-1
hash-e; ez többek között biztosítja, hogy a Git soha nem tárolja
kétszer ugyanazt az adatot (mivel az azonos adat azonos SHA-1 nevet
kap), és hogy egy Git-objektum tartalma soha nem változik meg (mivel az
megváltoztatná az objektum nevét is). Az itteni 7 karakteres hex
sztringek egyszerűen az ilyen 40 karakter hosszú sztringek rövidítései.
A rövidítések mindenütt használhatók, ahol a 40 karakteres sztringek
használhatók, amíg egyértelműek.

Várható, hogy a fenti példa követése közben létrehozott commitobjektum
tartalma más SHA-1 hash-t generál, mint a fent látható, mert a
commitobjektum rögzíti a létrehozásának idejét és a commitot végző
személy nevét.

Erről a konkrét objektumról a `cat-file` paranccsal kérdezhetjük meg a
Gitet. Ne a 40 hex számjegyet másold ki ebből a példából, hanem a saját
verziódból származóakat használd. Vedd figyelembe, hogy csak néhány
karakterre lerövidítheted, hogy megspórold mind a 40 hex számjegy
begépelését:

------------------------------------------------
$ git cat-file -t 54196cc2
commit
$ git cat-file commit 54196cc2
tree 92b8b694ffb1675e5975148e1121810081dbdffe
author J. Bruce Fields <bfields@puzzle.fieldses.org> 1143414668 -0500
committer J. Bruce Fields <bfields@puzzle.fieldses.org> 1143414668 -0500

initial commit
------------------------------------------------

Egy fa egy vagy több „blob" objektumra hivatkozhat, amelyek mindegyike
egy-egy fájlnak felel meg. Ezenkívül egy fa más faobjektumokra is
hivatkozhat, így könyvtárhierarchiát hozva létre. Bármely fa tartalmát
megvizsgálhatod az ls-tree-vel (ne feledd, hogy a SHA-1 elég hosszú
kezdő része is működik):

------------------------------------------------
$ git ls-tree 92b8b694
100644 blob 3b18e512dba79e4c8300dd08aeb37f8e728b8dad    file.txt
------------------------------------------------

Így látjuk, hogy ebben a fában egyetlen fájl van. A SHA-1 hash egy
hivatkozás annak a fájlnak az adatára:

------------------------------------------------
$ git cat-file -t 3b18e512
blob
------------------------------------------------

Egy „blob" pusztán fájladat, amit szintén megvizsgálhatunk a
cat-file-lal:

------------------------------------------------
$ git cat-file blob 3b18e512
hello world
------------------------------------------------

Vedd figyelembe, hogy ez a régi fájladat; tehát az az objektum, amelyet
a Git a kezdeti fára adott válaszában megnevezett, egy olyan fa volt,
amely az első commit által rögzített könyvtárállapot pillanatképét
tartalmazta.

Mindezek az objektumok a SHA-1 nevük alatt vannak tárolva a
Git-könyvtáron belül:

------------------------------------------------
$ find .git/objects/
.git/objects/
.git/objects/pack
.git/objects/info
.git/objects/3b
.git/objects/3b/18e512dba79e4c8300dd08aeb37f8e728b8dad
.git/objects/92
.git/objects/92/b8b694ffb1675e5975148e1121810081dbdffe
.git/objects/54
.git/objects/54/196cc2703dc165cbd373a65a4dcf22d50ae7f7
.git/objects/a0
.git/objects/a0/423896973644771497bdc03eb99d5281615b51
.git/objects/d0
.git/objects/d0/492b368b66bdabf2ac1fd8c92b39d3db916e59
.git/objects/c4
.git/objects/c4/d59f390b9cfd4318117afde11d601c1085f241
------------------------------------------------

és ezeknek a fájloknak a tartalma pusztán a tömörített adat, plusz egy
fejléc, amely azonosítja a hosszukat és a típusukat. A típus vagy egy
blob, vagy egy tree, vagy egy commit, vagy egy tag.

A legegyszerűbben megtalálható commit a HEAD commit, amelyet a
.git/HEAD-ből találhatunk meg:

------------------------------------------------
$ cat .git/HEAD
ref: refs/heads/master
------------------------------------------------

Amint látod, ez megmondja nekünk, melyik branchen vagyunk éppen, és ezt
úgy mondja meg, hogy megnevez egy fájlt a .git könyvtár alatt, amely
maga egy commitobjektumra hivatkozó SHA-1 nevet tartalmaz, amelyet a
cat-file-lal vizsgálhatunk meg:

------------------------------------------------
$ cat .git/refs/heads/master
c4d59f390b9cfd4318117afde11d601c1085f241
$ git cat-file -t c4d59f39
commit
$ git cat-file commit c4d59f39
tree d0492b368b66bdabf2ac1fd8c92b39d3db916e59
parent 54196cc2703dc165cbd373a65a4dcf22d50ae7f7
author J. Bruce Fields <bfields@puzzle.fieldses.org> 1143418702 -0500
committer J. Bruce Fields <bfields@puzzle.fieldses.org> 1143418702 -0500

add emphasis
------------------------------------------------

Az itteni „tree" objektum a fa új állapotára hivatkozik:

------------------------------------------------
$ git ls-tree d0492b36
100644 blob a0423896973644771497bdc03eb99d5281615b51    file.txt
$ git cat-file blob a0423896
hello world!
------------------------------------------------

a „parent" objektum pedig az előző commitra hivatkozik:

------------------------------------------------
$ git cat-file commit 54196cc2
tree 92b8b694ffb1675e5975148e1121810081dbdffe
author J. Bruce Fields <bfields@puzzle.fieldses.org> 1143414668 -0500
committer J. Bruce Fields <bfields@puzzle.fieldses.org> 1143414668 -0500

initial commit
------------------------------------------------

A tree objektum az a fa, amelyet elsőként vizsgáltunk meg, és ez a
commit szokatlan abban, hogy nincs semmilyen szülője.

A legtöbb commitnak csak egy szülője van, de az is gyakori, hogy egy
commitnak több szülője van. Ebben az esetben a commit egy merge-et
képvisel, ahol a parent-hivatkozások a merge-elt branchek fejeire
mutatnak.

A blobokon, fákon és commitokon kívül az egyetlen fennmaradó
objektumtípus a „tag", amit itt nem tárgyalunk; a részletekért lásd a
linkgit:git-tag[1]-et.

Így most már tudjuk, hogyan használja a Git az objektumadatbázist egy
projekt történetének ábrázolására:

  * a „commit" objektumok „tree" objektumokra hivatkoznak, amelyek egy
    könyvtárfa pillanatképét ábrázolják a történet egy adott pontján, és
    „parent" commitokra hivatkoznak, hogy megmutassák, hogyan
    kapcsolódnak a projekt történetébe.
  * a „tree" objektumok egyetlen könyvtár állapotát ábrázolják,
    könyvtárneveket társítva fájladatot tartalmazó „blob" objektumokhoz
    és alkönyvtár-információt tartalmazó „tree" objektumokhoz.
  * a „blob" objektumok fájladatot tartalmaznak minden más struktúra
    nélkül.
  * az egyes branchek fejénél lévő commitobjektumokra mutató
    hivatkozások a .git/refs/heads/ alatti fájlokban vannak tárolva.
  * az aktuális branch neve a .git/HEAD-ben van tárolva.

Egyébként vedd figyelembe, hogy sok parancs fát vár argumentumként. De
ahogy fentebb láthatjuk, egy fára sokféleképp lehet hivatkozni – az
adott fa SHA-1 nevével, egy olyan commit nevével, amely a fára
hivatkozik, egy olyan branch nevével, amelynek a feje arra a fára
hivatkozik, stb. –, és a legtöbb ilyen parancs elfogadja bármelyiket
ezek közül a nevek közül.

A parancsok synopsisában néha a „tree-ish" szót használják egy ilyen
argumentum megjelölésére.

[[_the_index_file]]
Az indexfájl
------------

Az elsődleges eszköz, amelyet a commitok létrehozására használtunk, a
`git-commit -a`, amely olyan commitot hoz létre, amely minden
változást tartalmaz, amit a working tree-den végeztél. De mi van, ha
csak bizonyos fájlok változásait akarod commitolni? Vagy csak bizonyos
fájlok bizonyos változásait?

Ha megnézzük, hogyan jönnek létre a commitok a felszín alatt, látni
fogjuk, hogy vannak rugalmasabb módjai a commitok létrehozásának.

Folytatva a test-projectünkkel, módosítsuk újra a file.txt-t:

------------------------------------------------
$ echo "hello world, again" >>file.txt
------------------------------------------------

de ezúttal ahelyett, hogy azonnal elkészítenénk a commitot, iktassunk
be egy köztes lépést, és kérjünk diffeket útközben, hogy nyomon
kövessük, mi történik:

------------------------------------------------
$ git diff
--- a/file.txt
+++ b/file.txt
@@ -1 +1,2 @@
 hello world!
+hello world, again
$ git add file.txt
$ git diff
------------------------------------------------

Az utolsó diff üres, de nem készültek új commitok, és a fej még mindig
nem tartalmazza az új sort:

------------------------------------------------
$ git diff HEAD
diff --git a/file.txt b/file.txt
index a042389..513feba 100644
--- a/file.txt
+++ b/file.txt
@@ -1 +1,2 @@
 hello world!
+hello world, again
------------------------------------------------

Tehát a 'git diff' valami mással hasonlít össze, nem a fejjel. Az, amivel
összehasonlít, valójában az indexfájl, amely a .git/index-ben van
tárolva bináris formátumban, de amelynek a tartalmát megvizsgálhatjuk
az ls-files-szal:

------------------------------------------------
$ git ls-files --stage
100644 513feba2e53ebbd2532419ded848ba19de88ba00 0       file.txt
$ git cat-file -t 513feba2
blob
$ git cat-file blob 513feba2
hello world!
hello world, again
------------------------------------------------

Tehát amit a 'git add'-ünk tett, az annyi volt, hogy eltárolt egy új
blobot, majd elhelyezett rá egy hivatkozást az indexfájlban. Ha újra
módosítjuk a fájlt, látni fogjuk, hogy az új módosítások megjelennek a
'git diff' kimenetében:

------------------------------------------------
$ echo 'again?' >>file.txt
$ git diff
index 513feba..ba3da7b 100644
--- a/file.txt
+++ b/file.txt
@@ -1,2 +1,3 @@
 hello world!
 hello world, again
+again?
------------------------------------------------

A megfelelő argumentumokkal a 'git diff' meg tudja mutatni nekünk a
különbséget a munkakönyvtár és az utolsó commit között is, vagy az
index és az utolsó commit között:

------------------------------------------------
$ git diff HEAD
diff --git a/file.txt b/file.txt
index a042389..ba3da7b 100644
--- a/file.txt
+++ b/file.txt
@@ -1 +1,3 @@
 hello world!
+hello world, again
+again?
$ git diff --cached
diff --git a/file.txt b/file.txt
index a042389..513feba 100644
--- a/file.txt
+++ b/file.txt
@@ -1 +1,2 @@
 hello world!
+hello world, again
------------------------------------------------

Bármikor létrehozhatunk egy új commitot a 'git commit'-tal (a "-a"
kapcsoló nélkül), és ellenőrizhetjük, hogy a commitolt állapot csak az
indexfájlban tárolt változásokat tartalmazza, nem pedig azt a további
változást, amely még mindig csak a working tree-nkben van:

------------------------------------------------
$ git commit -m "repeat"
$ git diff HEAD
diff --git a/file.txt b/file.txt
index 513feba..ba3da7b 100644
--- a/file.txt
+++ b/file.txt
@@ -1,2 +1,3 @@
 hello world!
 hello world, again
+again?
------------------------------------------------

Tehát alapból a 'git commit' az indexet használja a commit
létrehozásához, nem a working tree-t; a commit "-a" kapcsolója azt
mondja neki, hogy előbb frissítse az indexet a working tree minden
változásával.

Végül érdemes megnézni a 'git add' hatását az indexfájlra:

------------------------------------------------
$ echo "goodbye, world" >closing.txt
$ git add closing.txt
------------------------------------------------

A 'git add' hatása az volt, hogy egy bejegyzést adott az indexfájlhoz:

------------------------------------------------
$ git ls-files --stage
100644 8b9743b20d4b15be3955fc8d5cd2b09cd2336138 0       closing.txt
100644 513feba2e53ebbd2532419ded848ba19de88ba00 0       file.txt
------------------------------------------------

És, ahogy a cat-file-lal láthatod, ez az új bejegyzés a fájl aktuális
tartalmára hivatkozik:

------------------------------------------------
$ git cat-file blob 8b9743b2
goodbye, world
------------------------------------------------

A „status" parancs hasznos módja annak, hogy gyors összefoglalót kapj a
helyzetről:

------------------------------------------------
$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)

	new file:   closing.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)

	modified:   file.txt

------------------------------------------------

Mivel a closing.txt aktuális állapota gyorsítótárazva van az
indexfájlban, „Changes to be committed"-ként szerepel a listában. Mivel
a file.txt-nek vannak olyan változásai a munkakönyvtárban, amelyek nem
jelennek meg az indexben, „changed but not updated"-ként van megjelölve.
Ezen a ponton a "git commit" futtatása olyan commitot hozna létre,
amely hozzáadta a closing.txt-t (az új tartalmával), de nem módosította
a file.txt-t.

Vedd figyelembe azt is, hogy egy csupasz `git diff` a file.txt
változásait mutatja, de a closing.txt hozzáadását nem, mert a
closing.txt indexfájlbeli verziója azonos a munkakönyvtárbelivel.

Amellett, hogy az új commitok staging area-ja, az indexfájl az
objektumadatbázisból is feltöltődik egy branch checkoutolásakor, és a
merge műveletben részt vevő fák tárolására is szolgál. A részletekért
lásd a linkgit:gitcore-tutorial[7]-et és a vonatkozó man page-eket.

[[_what_next]]
Mi a következő?
---------------

Ezen a ponton már mindent tudnod kell ahhoz, hogy bármelyik git parancs
man page-ét elolvasd; egy jó kiindulópont a linkgit:giteveryday[7]-ben
említett parancsok lennének. Bármilyen ismeretlen szakzsargont meg kell
találnod a linkgit:gitglossary[7]-ben.

A link:user-manual.html[Git felhasználói kézikönyve] átfogóbb bevezetést
nyújt a Githez.

A linkgit:gitcvs-migration[7] elmagyarázza, hogyan importálj egy CVS
repository-t Gitbe, és megmutatja, hogyan használd a Gitet CVS-szerű
módon.

A Git-használat néhány érdekes példájáért lásd a
link:howto-index.html[howto-kat].

Git-fejlesztőknek a linkgit:gitcore-tutorial[7] részletesen kitér az
alacsonyabb szintű Git-mechanizmusokra, amelyek például egy új commit
létrehozásában szerepet játszanak.

SEE ALSO
--------
linkgit:gittutorial[7],
linkgit:gitcvs-migration[7],
linkgit:gitcore-tutorial[7],
linkgit:gitglossary[7],
linkgit:git-help[1],
linkgit:giteveryday[7],
link:user-manual.html[A Git felhasználói kézikönyve]

GIT
---
A linkgit:git[1] csomag része
