gittutorial(7)
==============

NAME
----
gittutorial - Bevezető ismertető a Githez

SYNOPSIS
--------
[verse]
git *

DESCRIPTION
-----------

Ez az ismertető elmagyarázza, hogyan importálj egy új projektet a Gitbe,
hogyan végezz rajta módosításokat, és hogyan oszd meg a változtatásokat
más fejlesztőkkel.

Ha ehelyett elsősorban abban vagy érdekelt, hogy a Git segítségével
lehívj egy projektet, például hogy kipróbáld a legújabb verzióját,
érdemesebb lehet a link:user-manual.html[A Git felhasználói kézikönyve]
első két fejezetével kezdened.

Először is jegyezd meg, hogy egy olyan parancshoz, mint a
`git log --graph`, a dokumentációt a következővel kaphatod meg:

------------------------------------------------
$ man git-log
------------------------------------------------

vagy:

------------------------------------------------
$ git help log
------------------------------------------------

Az utóbbival a választásod szerinti kézikönyv-megjelenítőt használhatod;
további információért lásd: linkgit:git-help[1].

Jó ötlet bemutatkozni a Gitnek a neveddel és a nyilvános e-mail
címeddel, mielőtt bármilyen műveletet végrehajtanál. Erre a
legegyszerűbb módszer:

------------------------------------------------
$ git config --global user.name "Your Name Comes Here"
$ git config --global user.email you@yourdomain.example.com
------------------------------------------------


[[_importing_a_new_project]]
Egy új projekt importálása
--------------------------

Tegyük fel, hogy van egy `project.tar.gz` tarballod a kezdeti munkáddal.
Az alábbiak szerint helyezheted Git verziókövetés alá.

------------------------------------------------
$ tar xzf project.tar.gz
$ cd project
$ git init
------------------------------------------------

A Git a következőt válaszolja:

------------------------------------------------
Initialized empty Git repository in .git/
------------------------------------------------

Ezzel inicializáltad a munkakönyvtárat – észreveheted, hogy létrejött
egy új, `.git` nevű könyvtár.

Ezután a `git add` paranccsal mondd meg a Gitnek, hogy készítsen
pillanatképet az aktuális könyvtár összes fájljának tartalmáról
(figyeld meg a `.`-ot):

------------------------------------------------
$ git add .
------------------------------------------------

Ez a pillanatkép most egy ideiglenes staging area-ban van tárolva, amit
a Git „index"-nek nevez. Az index tartalmát a `git commit` paranccsal
tárolhatod tartósan a repository-ban:

------------------------------------------------
$ git commit
------------------------------------------------

Ez be fog kérni tőled egy commit-üzenetet. Ezzel eltárolódott a
projekted első verziója a Gitben.

[[_making_changes]]
Módosítások végzése
-------------------

Módosíts néhány fájlt, majd add hozzá a frissített tartalmukat az
indexhez:

------------------------------------------------
$ git add file1 file2 file3
------------------------------------------------

Most már készen állsz a commitolásra. A `git diff` paranccsal, a
`--cached` kapcsolóval megnézheted, mi fog bekerülni a commitba:

------------------------------------------------
$ git diff --cached
------------------------------------------------

(A `--cached` nélkül a `git diff` megmutatja azokat a változtatásokat,
amelyeket megtettél, de még nem adtál hozzá az indexhez.) A helyzet
rövid összefoglalóját a `git status` paranccsal is megkaphatod:

------------------------------------------------
$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)

	modified:   file1
	modified:   file2
	modified:   file3

------------------------------------------------

Ha további módosításokra van szükség, tedd meg most, majd add hozzá az
újonnan módosított tartalmat az indexhez. Végül commitold a
változtatásaidat a következővel:

------------------------------------------------
$ git commit
------------------------------------------------

Ez ismét be fog kérni tőled egy, a változtatást leíró üzenetet, majd
rögzíti a projekt egy új verzióját.

Alternatív megoldásként, ahelyett hogy előtte lefuttatnád a `git
add`-et, használhatod a következőt:

------------------------------------------------
$ git commit -a
------------------------------------------------

ez automatikusan észreveszi a módosított (de nem új) fájlokat, hozzáadja
őket az indexhez, és commitol, mindezt egyetlen lépésben.

Egy megjegyzés a commit-üzenetekről: bár nem kötelező, jó ötlet a
commit-üzenetet egyetlen rövid (legfeljebb 50 karakteres) sorral
kezdeni, amely összefoglalja a változtatást, majd egy üres sorral, végül
egy alaposabb leírással folytatni. A commit-üzenetben az első üres
sorig terjedő szöveget a Git a commit címeként kezeli, és ezt a címet
használja mindenütt. Például a linkgit:git-format-patch[1] a commitot
e-mailbe alakítja, és a címet használja a Subject sorban, a commit
többi részét pedig a törzsben.

[[_git_tracks_content_not_files]]
A Git a tartalmat követi, nem a fájlokat
----------------------------------------

Sok verziókövető rendszer biztosít egy `add` parancsot, amely megmondja
a rendszernek, hogy kezdje el követni egy új fájl változtatásait. A Git
`add` parancsa ennél egyszerűbb és erősebb dolgot csinál: a `git add`
mind az új, mind az újonnan módosított fájlokhoz használatos, és
mindkét esetben pillanatképet készít a megadott fájlokról, és stage-eli
azok tartalmát az indexben, készen a következő commitba történő
felvételre.

[[_viewing_project_history]]
A projekt előzményeinek megtekintése
------------------------------------

Bármikor megtekintheted a változtatásaid előzményeit a következővel:

------------------------------------------------
$ git log
------------------------------------------------

Ha minden lépésnél teljes diffeket is szeretnél látni, használd:

------------------------------------------------
$ git log -p
------------------------------------------------

Gyakran hasznos a változtatás áttekintése, hogy érzékeld az egyes
lépéseket

------------------------------------------------
$ git log --stat --summary
------------------------------------------------

[[_managing_branches]]
Branchek kezelése
-----------------

Egy Git repository egyszerre több fejlesztési branchet is fenntarthat.
Egy `experimental` nevű új branch létrehozásához használd:

------------------------------------------------
$ git branch experimental
------------------------------------------------

Ha most lefuttatod a következőt

------------------------------------------------
$ git branch
------------------------------------------------

megkapod az összes létező branch listáját:

------------------------------------------------
  experimental
* master
------------------------------------------------

Az `experimental` branch az, amit épp most hoztál létre, a `master`
branch pedig egy alapértelmezett branch, amelyet automatikusan
létrehozott a rendszer neked. A csillag jelöli azt a branchet,
amelyiken éppen állsz; írd be:

------------------------------------------------
$ git switch experimental
------------------------------------------------

hogy átválts az `experimental` branchre. Most szerkessz egy fájlt,
commitold a változtatást, és válts vissza a `master` branchre:

------------------------------------------------
(edit file)
$ git commit -a
$ git switch master
------------------------------------------------

Ellenőrizd, hogy az általad tett változtatás már nem látható, mivel az
az `experimental` branchen történt, te pedig most a `master` branchen
vagy.

Végezhetsz egy másik változtatást a `master` branchen:

------------------------------------------------
(edit file)
$ git commit -a
------------------------------------------------

ezen a ponton a két branch szétvált, mindegyikben más-más
változtatásokkal. Ahhoz, hogy az `experimental`-ban tett
változtatásokat merge-eld a `master`-be, futtasd:

------------------------------------------------
$ git merge experimental
------------------------------------------------

Ha a változtatások nem ütköznek, készen vagy. Ha vannak konfliktusok,
a problémás fájlokban jelölők maradnak, amelyek mutatják a konfliktust;

------------------------------------------------
$ git diff
------------------------------------------------

ez megmutatja ezt. Miután szerkesztetted a fájlokat a konfliktusok
feloldásához,

------------------------------------------------
$ git commit -a
------------------------------------------------

commitolja a merge eredményét. Végül,

------------------------------------------------
$ gitk
------------------------------------------------

megmutatja az eredményül kapott előzmények szép grafikus ábrázolását.

Ezen a ponton törölhetnéd az `experimental` branchet a következővel

------------------------------------------------
$ git branch -d experimental
------------------------------------------------

Ez a parancs biztosítja, hogy az `experimental` branchen lévő
változtatások már benne legyenek az aktuális branchben.

Ha egy `crazy-idea` nevű branchen fejlesztesz, majd meggondolod magad,
mindig törölheted a branchet a következővel

-------------------------------------
$ git branch -D crazy-idea
-------------------------------------

A branchek olcsók és egyszerűek, szóval ez egy jó módja annak, hogy
kipróbálj valamit.

[[_using_git_for_collaboration]]
A Git használata együttműködéshez
---------------------------------

Tegyük fel, hogy Alice elindított egy új projektet egy Git repository-val
a `/home/alice/project` alatt, és Bob, akinek ugyanazon a gépen van
saját home könyvtára, szeretne hozzájárulni.

Bob a következővel kezd:

------------------------------------------------
bob$ git clone /home/alice/project myrepo
------------------------------------------------

Ez létrehoz egy új, `myrepo` nevű könyvtárat, amely Alice
repository-jának egy klónját tartalmazza. A klón egyenrangú az eredeti
projekttel, és rendelkezik az eredeti projekt előzményeinek saját
másolatával.

Bob ezután végez néhány változtatást, és commitolja őket:

------------------------------------------------
(edit files)
bob$ git commit -a
(repeat as necessary)
------------------------------------------------

Amikor készen áll, szól Alice-nek, hogy pull-ozza le a változtatásokat
a `/home/bob/myrepo` alatti repository-ból. Ezt a következővel teszi
meg:

------------------------------------------------
alice$ cd /home/alice/project
alice$ git pull /home/bob/myrepo master
------------------------------------------------

Ez merge-eli a Bob `master` branchéből származó változtatásokat Alice
aktuális branchébe. Ha Alice időközben saját változtatásokat is
végzett, akkor esetleg kézzel kell megoldania az esetleges
konfliktusokat.

A `pull` parancs tehát két műveletet hajt végre: lehívja (fetcheli) a
változtatásokat egy remote branchből, majd merge-eli őket az aktuális
branchbe.

Vedd figyelembe, hogy általában Alice szeretné, ha a helyi
változtatásai commitolva lennének, mielőtt elindítja ezt a `pull`-t.
Ha Bob munkája ütközik azzal, amit Alice csinált, mióta az
előzményeik szétváltak, Alice a munkakönyvtárát és az indexet fogja
használni a konfliktusok feloldásához, és a meglévő helyi
változtatások zavarni fogják a konfliktusfeloldási folyamatot (a Git
ekkor is elvégzi a fetchet, de megtagadja a merge-et – Alice-nek
valamilyen módon meg kell szabadulnia a helyi változtatásaitól, és
újra kell pull-oznia, amikor ez történik).

Alice bepillanthat abba, hogy Bob mit csinált, anélkül hogy előtte
merge-elne, a `fetch` paranccsal; ez lehetővé teszi Alice számára,
hogy megvizsgálja, mit csinált Bob, egy speciális, `FETCH_HEAD` nevű
szimbólum segítségével, hogy eldöntse, van-e bármi, amit érdemes
lehívnia, így:

------------------------------------------------
alice$ git fetch /home/bob/myrepo master
alice$ git log -p HEAD..FETCH_HEAD
------------------------------------------------

Ez a művelet biztonságos akkor is, ha Alice-nek vannak commitolatlan
helyi változtatásai. A `HEAD..FETCH_HEAD` tartomány-jelölés azt
jelenti: „mutass meg mindent, ami elérhető a `FETCH_HEAD`-ből, de zárj
ki mindent, ami elérhető a `HEAD`-ből". Alice már mindent tud, ami az
aktuális állapotához (`HEAD`) vezet, és ezzel a paranccsal áttekinti,
hogy Bob állapotában (`FETCH_HEAD`) mi van, amit még nem látott.

Ha Alice vizualizálni szeretné, hogy Bob mit csinált, mióta az
előzményeik szétváltak, kiadhatja a következő parancsot:

------------------------------------------------
$ gitk HEAD..FETCH_HEAD
------------------------------------------------

Ez ugyanazt a kétpontos tartomány-jelölést használja, amit korábban a
`git log`-nál láttunk.

Alice esetleg szeretné megnézni, hogy mindketten mit csináltak, mióta
szétváltak. A kétpontos forma helyett használhatja a hárompontos
formát:

------------------------------------------------
$ gitk HEAD...FETCH_HEAD
------------------------------------------------

Ez azt jelenti: „mutass meg mindent, ami elérhető bármelyikükből, de
zárj ki mindent, ami mindkettőjükből elérhető".

Vedd figyelembe, hogy ezek a tartomány-jelölések használhatók mind a
`gitk`-val, mind a `git log`-gal.

Miután megvizsgálta, mit csinált Bob, ha nincs semmi sürgős, Alice
dönthet úgy, hogy tovább dolgozik anélkül, hogy pull-ozna Bobtól. Ha
Bob előzményeiben van valami, amire Alice-nek azonnal szüksége lenne,
Alice választhatja azt is, hogy előbb stash-eli a folyamatban lévő
munkáját, elvégzi a `pull`-t, majd végül unstash-eli a folyamatban
lévő munkáját az eredményül kapott előzmények tetejére.

Ha egy kicsi, szorosan összetartó csoportban dolgozol, nem szokatlan,
hogy újra és újra ugyanazzal a repository-val lépsz interakcióba. Egy
'remote' repository-rövidítés definiálásával megkönnyítheted ezt:

------------------------------------------------
alice$ git remote add bob /home/bob/myrepo
------------------------------------------------

Ezzel Alice el tudja végezni a `pull` művelet első részét
önmagában, a `git fetch` paranccsal, anélkül hogy merge-elné őket a
saját branchével, a következővel:

-------------------------------------
alice$ git fetch bob
-------------------------------------

A hosszú formától eltérően, amikor Alice a `git remote`-tal beállított
remote repository-rövidítés segítségével fetchel Bobtól, a lehívott
tartalom egy remote-tracking branchben tárolódik, ebben az esetben
`bob/master` néven. Tehát ez után:

-------------------------------------
alice$ git log -p master..bob/master
-------------------------------------

megmutatja az összes olyan változtatás listáját, amit Bob végzett,
mióta elágazott Alice `master` branchéből.

Miután megvizsgálta ezeket a változtatásokat, Alice merge-elhetné a
változtatásokat a saját `master` branchébe:

-------------------------------------
alice$ git merge bob/master
-------------------------------------

Ez a `merge` úgy is elvégezhető, hogy 'pull-oz a saját
remote-tracking branchéből', így:

-------------------------------------
alice$ git pull . remotes/bob/master
-------------------------------------

Vedd figyelembe, hogy a git pull mindig az aktuális branchbe
merge-el, függetlenül attól, hogy mi mást adsz meg a parancssorban.

Később Bob frissítheti a saját repository-ját Alice legutóbbi
változtatásaival a következővel

-------------------------------------
bob$ git pull
-------------------------------------

Vedd figyelembe, hogy nem kell megadnia Alice repository-jának
útvonalát; amikor Bob klónozta Alice repository-ját, a Git eltárolta a
repository helyét a repository konfigurációjában, és ez a hely kerül
felhasználásra a pull-oknál:

-------------------------------------
bob$ git config --get remote.origin.url
/home/alice/project
-------------------------------------

(A `git clone` által létrehozott teljes konfiguráció a `git config
list` paranccsal tekinthető meg, és a linkgit:git-config[1] man page
elmagyarázza az egyes opciók jelentését.)

A Git emellett megőriz egy érintetlen másolatot Alice `master`
branchéből `origin/master` néven:

-------------------------------------
bob$ git branch -r
  origin/master
-------------------------------------

Ha Bob később úgy dönt, hogy egy másik hosztról dolgozik, akkor is
végezhet klónozásokat és pull-okat az ssh protokoll használatával:

-------------------------------------
bob$ git clone alice.org:/home/alice/project myrepo
-------------------------------------

Alternatívaként a Gitnek van egy natív protokollja is, vagy
használhat http-t; a részletekért lásd: linkgit:git-pull[1].

A Git CVS-szerű módban is használható, egy központi repository-val,
amelybe a különböző felhasználók push-olják a változtatásaikat; lásd:
linkgit:git-push[1] és linkgit:gitcvs-migration[7].

[[_exploring_history]]
Az előzmények böngészése
------------------------

A Git előzményei egymással összefüggő commitok sorozataként jelennek
meg. Már láttuk, hogy a `git log` parancs ki tudja listázni ezeket a
commitokat. Vedd figyelembe, hogy az egyes `git log` bejegyzések első
sora egy nevet is ad a commitnak:

-------------------------------------
$ git log
commit c82a22c39cbc32576f64f5c6b3f24b99ea8149c7
Author: Junio C Hamano <junkio@cox.net>
Date:   Tue May 16 17:18:22 2006 -0700

    merge-base: Clarify the comments on post processing.
-------------------------------------

Ezt a nevet megadhatjuk a `git show`-nak, hogy megnézzük a commit
részleteit.

-------------------------------------
$ git show c82a22c39cbc32576f64f5c6b3f24b99ea8149c7
-------------------------------------

De vannak más módok is a commitokra hivatkozni. Használhatod a név
bármely kezdő részét, amely elég hosszú ahhoz, hogy egyértelműen
azonosítsa a commitot:

-------------------------------------
$ git show c82a22c39c	# the first few characters of the name are
			# usually enough
$ git show HEAD		# the tip of the current branch
$ git show experimental	# the tip of the "experimental" branch
-------------------------------------

Minden commitnak általában van egy „parent" (szülő) commitja, amely a
projekt előző állapotára mutat:

-------------------------------------
$ git show HEAD^  # to see the parent of HEAD
$ git show HEAD^^ # to see the grandparent of HEAD
$ git show HEAD~4 # to see the great-great grandparent of HEAD
-------------------------------------

Vedd figyelembe, hogy a merge commitoknak több szülőjük is lehet:

-------------------------------------
$ git show HEAD^1 # show the first parent of HEAD (same as HEAD^)
$ git show HEAD^2 # show the second parent of HEAD
-------------------------------------

Saját neveket is adhatsz a commitoknak; a következő futtatása után

-------------------------------------
$ git tag v2.5 1b2e1d63ff
-------------------------------------

hivatkozhatsz `1b2e1d63ff`-re a `v2.5` néven. Ha ezt a nevet meg
akarod osztani másokkal (például egy kiadási verzió azonosítására),
érdemes létrehoznod egy „tag" objektumot, és esetleg aláírnod; a
részletekért lásd: linkgit:git-tag[1].

Bármelyik Git parancs, amelynek tudnia kell egy commitot, elfogadja
ezen nevek bármelyikét. Például:

-------------------------------------
$ git diff v2.5 HEAD	 # compare the current HEAD to v2.5
$ git branch stable v2.5 # start a new branch named "stable" based
			 # at v2.5
$ git reset --hard HEAD^ # reset your current branch and working
			 # directory to its state at HEAD^
-------------------------------------

Legyél óvatos ezzel az utolsó paranccsal: amellett, hogy elveszíted a
munkakönyvtárban lévő változtatásokat, ez a branch összes későbbi
commitját is eltávolítja. Ha ez a branch az egyetlen, amely
tartalmazza ezeket a commitokat, akkor azok elvesznek. Emellett ne
használd a `git reset`-et egy nyilvánosan látható branchen, amelyről
más fejlesztők pull-oznak, mivel ez szükségtelen merge-eket fog
kikényszeríteni más fejlesztőknél az előzmények megtisztításához. Ha
vissza kell vonnod olyan változtatásokat, amelyeket már push-oltál,
használd inkább a `git revert`-et.

A `git grep` parancs a projekted bármely verziójában tud keresni
karakterláncokra, tehát

-------------------------------------
$ git grep "hello" v2.5
-------------------------------------

megkeresi a „hello" összes előfordulását a `v2.5`-ben.

Ha kihagyod a commit nevét, a `git grep` az aktuális könyvtárban
általa kezelt bármelyik fájlban keres. Tehát

-------------------------------------
$ git grep "hello"
-------------------------------------

ez egy gyors módja annak, hogy csak a Git által követett fájlokban
keress.

Sok Git parancs commit-halmazokat is elfogad, amelyeket többféleképpen
lehet megadni. Íme néhány példa a `git log`-gal:

-------------------------------------
$ git log v2.5..v2.6            # commits between v2.5 and v2.6
$ git log v2.5..                # commits since v2.5
$ git log --since="2 weeks ago" # commits from the last 2 weeks
$ git log v2.5.. Makefile       # commits since v2.5 which modify
				# Makefile
-------------------------------------

A `git log`-nak commitok egy „tartományát" (range) is megadhatod, ahol
az első nem feltétlenül őse a másodiknak; például, ha a `stable` és a
`master` branchek csúcsai egy közös commitból ágaztak el valamikor
korábban, akkor

-------------------------------------
$ git log stable..master
-------------------------------------

kilistázza a `master` branchen végzett, de a stable branchen nem
szereplő commitokat, míg

-------------------------------------
$ git log master..stable
-------------------------------------

megmutatja a stable branchen végzett, de a `master` branchen nem
szereplő commitok listáját.

A `git log` parancsnak van egy gyengesége: a commitokat listaként
kell megjelenítenie. Amikor az előzményekben olyan fejlesztési
vonalak vannak, amelyek szétváltak, majd újra összeolvadtak, az a
sorrend, amelyben a `git log` bemutatja ezeket a commitokat,
értelmetlen.

A legtöbb, több közreműködővel rendelkező projektben (mint például a
Linux kernel vagy maga a Git) gyakoriak a merge-ek, és a `gitk` jobb
munkát végez az előzményeik vizualizálásában. Például,

-------------------------------------
$ gitk --since="2 weeks ago" drivers/
-------------------------------------

lehetővé teszi, hogy böngéssz az elmúlt 2 hét azon commitjai között,
amelyek a `drivers` könyvtár alatti fájlokat módosították.
(Megjegyzés: a gitk betűtípusait a control billentyű lenyomva tartása
mellett a „-" vagy „+" megnyomásával állíthatod be.)

Végül, a legtöbb, fájlneveket elfogadó parancs opcionálisan lehetővé
teszi, hogy egy fájlnév elé egy commitot írj, hogy a fájl egy adott
verzióját add meg:

-------------------------------------
$ git diff v2.5:Makefile HEAD:Makefile.in
-------------------------------------

A `git show`-t is használhatod bármely ilyen fájl megtekintésére:

-------------------------------------
$ git show v2.5:Makefile
-------------------------------------

[[_next_steps]]
További lépések
---------------

Ez az ismertető elegendő kell legyen ahhoz, hogy alapszintű elosztott
verziókövetést végezz a projektjeidnél. Ahhoz azonban, hogy teljesen
megértsd a Git mélységét és erejét, meg kell értened két egyszerű
elképzelést, amelyekre épül:

  * Az objektumadatbázis az a meglehetősen elegáns rendszer, amelyet a
    projekted előzményeinek – fájloknak, könyvtáraknak és
    commitoknak – a tárolására használnak.

  * Az index fájl egy könyvtárfa állapotának cache-e, amelyet
    commitok létrehozására, munkakönyvtárak checkoutolására, és a
    merge-ben érintett különböző fák tárolására használnak.

Ennek az ismertetőnek a második része elmagyarázza az
objektumadatbázist, az index fájlt, és néhány egyéb apróságot, amelyre
szükséged lesz ahhoz, hogy a legtöbbet hozd ki a Gitből. Megtalálod
itt: linkgit:gittutorial-2[7].

Ha nem akarod rögtön azzal folytatni, néhány más kitérő, ami ezen a
ponton érdekes lehet:

  * linkgit:git-format-patch[1], linkgit:git-am[1]: Ezek git
    commit-sorozatokat alakítanak e-mailben küldött patchekké, és
    fordítva, ami olyan projekteknél hasznos, mint a Linux kernel,
    amelyek erősen támaszkodnak az e-mailben küldött patchekre.

  * linkgit:git-bisect[1]: Ha regresszió történik a projektedben, a
    hiba felderítésének egyik módja az előzmények átvizsgálása, hogy
    megtaláld a pontos, hibás commitot. A `git bisect` segíthet abban,
    hogy bináris keresést végezz erre a commitra. Elég okos ahhoz,
    hogy közel optimális keresést végezzen még összetett, nemlineáris,
    sok merge-elt branchet tartalmazó előzmények esetén is.

  * linkgit:gitworkflows[7]: Áttekintést ad az ajánlott
    munkafolyamatokról.

  * linkgit:giteveryday[7]: Mindennapi Git úgy 20 paranccsal.

  * linkgit:gitcvs-migration[7]: Git CVS-felhasználóknak.

SEE ALSO
--------
linkgit:gittutorial-2[7],
linkgit:gitcvs-migration[7],
linkgit:gitcore-tutorial[7],
linkgit:gitglossary[7],
linkgit:git-help[1],
linkgit:gitworkflows[7],
linkgit:giteveryday[7],
link:user-manual.html[A Git felhasználói kézikönyve]

GIT
---
A linkgit:git[1] csomag része
