gitweb.conf(5)
==============

NAME
----
gitweb.conf - Gitweb (Git webes felület) konfigurációs fájlja

SYNOPSIS
--------
/etc/gitweb.conf, /etc/gitweb-common.conf, $GITWEBDIR/gitweb_config.perl

DESCRIPTION
-----------

A Git repository-k webes megtekintésére szolgáló gitweb CGI szkript egy
Perl szkript-töredéket használ konfigurációs fájlként. A változókat a
"`our $variable = value`" formával állíthatod be; a "#" karaktertől a sor
végéig terjedő szöveg figyelmen kívül marad. A részletekért lásd a
*perlsyn*(1) man page-et.

Egy példa:

------------------------------------------------
# gitweb configuration file for http://git.example.org
#
our $projectroot = "/srv/git"; # FHS recommendation
our $site_name = 'Example.org >> Repos';
------------------------------------------------


A konfigurációs fájl arra szolgál, hogy felülírja azokat az alapértelmezett
beállításokat, amelyek a 'gitweb.cgi' szkript generálásakor be lettek
építve a gitwebbe.

Bár a konfigurációs beállításokat közvetlenül magában a gitweb CGI-ban is
meg lehetne változtatni, ezek a módosítások frissítéskor elvesznének. A
konfigurációs beállítások elhelyezhetők a CGI szkripttel azonos
könyvtárban lévő, alapértelmezés szerint 'gitweb_config.perl' nevű
fájlban is -- ez lehetővé teszi, hogy szimbolikus linkek segítségével
több, eltérő konfigurációjú gitweb-példányunk legyen.

Vedd figyelembe, hogy egyes beállítások a teljes gitwebre vonatkozó szint
helyett repository-nkénti szinten is szabályozhatók: lásd a
"Per-repository gitweb configuration" alszekciót a linkgit:gitweb[1]
man page-en.


DISCUSSION
----------
A gitweb az alábbi forrásokból olvassa be a konfigurációs adatokat, az
alábbi sorrendben:

 * beépített értékek (némelyik a build szakaszban van beállítva),

 * közös, rendszerszintű konfigurációs fájl (alapértelmezés szerint
   `/etc/gitweb-common.conf`),

 * vagy a példányonkénti konfigurációs fájl (alapértelmezés szerint
   'gitweb_config.perl' a telepített gitwebbel azonos könyvtárban),
   vagy ha ez nem létezik, akkor a tartalék rendszerszintű konfigurációs
   fájl (alapértelmezés szerint `/etc/gitweb.conf`).

A későbbi konfigurációs fájlokban kapott értékek felülírják a fenti
sorrendben korábban kapott értékeket.

A közös rendszerszintű konfigurációs fájl, a tartalék rendszerszintű
konfigurációs fájl és a példányonkénti konfigurációs fájl helye
fordítási időben van meghatározva, a build-időbeli Makefile
konfigurációs változók segítségével, amelyek rendre `GITWEB_CONFIG_COMMON`,
`GITWEB_CONFIG_SYSTEM` és `GITWEB_CONFIG`.

A gitweb konfigurációs fájljainak helyét futásidőben is felülírhatod, ha
a következő környezeti változókat nem üres értékre állítod:
`GITWEB_CONFIG_COMMON`, `GITWEB_CONFIG_SYSTEM` és `GITWEB_CONFIG`.


A konfigurációs fájlok szintaxisa a Perl szintaxisa, mivel ezeket a
fájlokat Perl kódtöredékként forrásoltatva dolgozza fel a rendszer (ez az
a nyelv, amelyben maga a gitweb is íródott). A változókat jellemzően az
`our` minősítővel állítjuk be (mint pl. "`our $variable = <value>;`"),
hogy elkerüljük a szintaxishibákat, ha a gitweb egy új verziója már nem
használ egy adott változót, és ezért nem is deklarálja azt.

A read_config_file() alrutinnal más konfigurációs fájlt is bevonhatsz.
Például valaki szeretné a repository-k Gitolite-on (az egyik Git
repository-kezelő eszközön) keresztüli megtekintéséhez tartozó
hozzáférés-szabályozási gitweb-beállításokat külön fájlba tenni, például
a `/etc/gitweb-gitolite.conf` fájlba. A bevonáshoz tedd a következőt

--------------------------------------------------
read_config_file("/etc/gitweb-gitolite.conf");
--------------------------------------------------

valahol a használt gitweb konfigurációs fájlban, például a
telepítésenkénti gitweb konfigurációs fájlban. Vedd figyelembe, hogy a
read_config_file() maga ellenőrzi, hogy az általa beolvasandó fájl
létezik-e, és semmit sem csinál, ha az nem található. A bevont fájlban
lévő hibákat is kezeli.


Az alapértelmezett konfiguráció, konfigurációs fájl nélkül, egyes
telepítéseknél tökéletesen megfelelő lehet. Ennek ellenére egy
konfigurációs fájl sok szempontból hasznos a gitweb viselkedésének
testreszabásához vagy finomhangolásához, és egyes opcionális funkciók
nem lesznek jelen, hacsak nincsenek kifejezetten engedélyezve a
konfigurálható `%features` változó segítségével (lásd még a lenti
"Configuring gitweb features" szekciót).


CONFIGURATION VARIABLES
-----------------------
Egyes konfigurációs változóknak van (a CGI szkriptbe beágyazott)
alapértelmezett értékük, amelyet a gitweb buildelésekor állítanak be --
ha ez a helyzet, ezt a tényt a leírásuk is tartalmazza. A buildeléshez
és telepítéshez lásd a gitweb 'INSTALL' fájlját.


[[_location_of_repositories]]
A repository-k helye
~~~~~~~~~~~~~~~~~~~~
Az alább leírt konfigurációs változók szabályozzák, hogy a gitweb hogyan
találja meg a Git repository-kat, és hogyan jelennek meg és érhetők el a
repository-k.

Lásd még a "Repositories" és az azt követő alszekciókat a
linkgit:gitweb[1] man page-en.

$projectroot::
	Abszolút fájlrendszerbeli útvonal, amely a projekt útvonala elé
	kerül; a repository útvonala `$projectroot/$project`. A telepítés
	során a `$GITWEB_PROJECTROOT` értékre van állítva. Ezt a változót
	helyesen kell beállítani ahhoz, hogy a gitweb megtalálja a
	repository-kat.
+
Ha például a `$projectroot` a "/srv/git" értékre van állítva, a
következőt téve a gitweb konfigurációs fájlba:
+
----------------------------------------------------------------------------
our $projectroot = "/srv/git";
----------------------------------------------------------------------------
+
akkor ez
+
------------------------------------------------
http://git.example.com/gitweb.cgi?p=foo/bar.git
------------------------------------------------
+
és ennek path_info-alapú megfelelője
+
------------------------------------------------
http://git.example.com/gitweb.cgi/foo/bar.git
------------------------------------------------
+
a fájlrendszeren a `/srv/git/foo/bar.git` útvonalra képződik le.

$projects_list::
	A projekteket felsoroló sima szöveges fájl neve, vagy a
	projektekért átvizsgálandó könyvtár neve.
+
A projektlista-fájloknak soronként egy projektet kell felsorolniuk, ahol
minden sor a következő formátumú
+
-----------------------------------------------------------------------------
<URI-encoded filesystem path to repository> SP <URI-encoded repository owner>
-----------------------------------------------------------------------------
+
Ennek a változónak az alapértelmezett értékét a `GITWEB_LIST` makefile
változó határozza meg a telepítés időpontjában. Ha ez a változó üres, a
gitweb visszaesik arra, hogy a `$projectroot` könyvtárat vizsgálja át
repository-kért.

$project_maxdepth::
	Ha a `$projects_list` változó nincs beállítva, a gitweb rekurzívan
	átvizsgálja a fájlrendszert Git repository-kért. A
	`$project_maxdepth` a bejárási mélység korlátozására szolgál, a
	`$projectroot`-hoz (kiindulóponthoz) viszonyítva; ez azt jelenti,
	hogy azok a könyvtárak, amelyek a `$projectroot`-tól messzebb
	vannak, mint a `$project_maxdepth`, ki lesznek hagyva.
+
Ez pusztán teljesítményoptimalizálás, eredetileg a MacOS X-hez szánva,
ahol a rekurzív könyvtárbejárás lassú. A gitweb követi a szimbolikus
linkeket, de érzékeli a köröket, figyelmen kívül hagyva minden
duplikált fájlt és könyvtárat.
+
Ennek a változónak az alapértelmezett értékét a build-időbeli
`GITWEB_PROJECT_MAXDEPTH` konfigurációs változó határozza meg, amelynek
alapértelmezése 2007.

$export_ok::
	A repository-t csak akkor mutatja, ha ez a fájl létezik (a
	repository-ban). Csak akkor hatásos, ha ez a változó igazra
	értékelődik ki. A gitweb buildelésekor a `GITWEB_EXPORT_OK`
	beállításával állítható be. Ez az útvonal a `GIT_DIR`-hez
	viszonyított. A linkgit:git-daemon[1] a 'git-daemon-export-ok'
	fájlt használja, hacsak nem `--export-all` kapcsolóval indították.
	Alapértelmezés szerint ez a változó nincs beállítva, ami azt
	jelenti, hogy ez a funkció ki van kapcsolva.

$export_auth_hook::
	Az annak eldöntésére használt függvény, hogy mely repository-kat
	kell megjeleníteni. Ennek az alrutinnak egy paramétert kell
	elfogadnia, a projekt teljes útvonalát, és ha igazat ad vissza,
	az adott projekt bekerül a projektlistába, és elérhető lesz a
	gitweben keresztül, amennyiben megfelel a $export_ok, a
	$projects_list és a $projects_maxdepth által leírt egyéb
	követelményeknek is. Példa:
+
----------------------------------------------------------------------------
our $export_auth_hook = sub { return -e "$_[0]/git-daemon-export-ok"; };
----------------------------------------------------------------------------
+
bár a fentit a `$export_ok` használatával is meg lehetne csinálni
+
----------------------------------------------------------------------------
our $export_ok = "git-daemon-export-ok";
----------------------------------------------------------------------------
+
Ha nincs beállítva (alapértelmezés), ez azt jelenti, hogy ez a funkció
le van tiltva.
+
Lásd még a bonyolultabb példát a "Controlling access to Git repositories"
alszekcióban a linkgit:gitweb[1] man page-en.

$strict_export::
	Csak azon repository-k megtekintését engedélyezi, amelyek az
	áttekintő oldalon is meg vannak jelenítve. Ez például azt
	eredményezi, hogy a `$export_ok` fájl dönti el, hogy a repository
	elérhető-e, nem csupán azt, hogy megjelenik-e. Ha a
	`$projects_list` egy projektlistát tartalmazó fájlra mutat, akkor
	csak az abban felsorolt repository-k lesznek elérhetők a gitweb
	számára. A gitweb buildelésekor a `GITWEB_STRICT_EXPORT`
	segítségével állítható be. Alapértelmezés szerint ez a változó
	nincs beállítva, ami azt jelenti, hogy közvetlenül hozzáférhetsz
	azokhoz a repository-khoz, amelyek el vannak rejtve a
	projektlista-oldalról (azaz nincsenek felsorolva a
	$projects_list fájlban).


[[_finding_files]]
Fájlok megtalálása
~~~~~~~~~~~~~~~~~~
Az alábbi konfigurációs változók mondják meg a gitwebnek, hol találja
meg a fájlokat. Ezeknek a változóknak az értékei fájlrendszerbeli
útvonalak.

$GIT::
	A használandó git alap-futtatható állomány. Alapértelmezés szerint
	`$GIT_BINDIR/git`, ami viszont alapértelmezés szerint
	`$(bindir)/git`. Ha bináris csomagból telepített Gitet használsz,
	ezt általában "/usr/bin/git" értékre kell állítanod. Ez lehet
	egyszerűen "git" is, ha a webszervered PATH-ja megfelelő; biztonsági
	szempontból jobb a git bináris abszolút útvonalát használni. Ha
	több Git verzió van telepítve, ezzel választható ki, melyiket kell
	használni. Helyesen be kell állítani ahhoz, hogy a gitweb működni
	tudjon.

$mimetypes_file::
	A (fájlnév-kiterjesztés alapú) MIME-típus becsléséhez használandó
	fájl, mielőtt a `/etc/mime.types`-t próbálná. *NOTE*, hogy ez az
	útvonal, ha relatív, az aktuális Git repository-hoz viszonyítottnak
	számít, nem a CGI szkripthez. Ha nincs beállítva, csak a
	`/etc/mime.types` kerül felhasználásra (ha létezik a
	fájlrendszeren). Ha nem található mimetypes fájl, a fájl
	kiterjesztésén alapuló mimetípus-becslés le van tiltva.
	Alapértelmezés szerint nincs beállítva.

$highlight_bin::
	A használandó highlight futtatható állomány útvonala (annak a
	http://andre-simon.de/zip/download.php[] címen található verziónak
	kell lennie, a paraméterekkel és a kimenettel kapcsolatos
	feltételezések miatt). Alapértelmezés szerint 'highlight'; állítsd
	a highlight futtatható állomány teljes útvonalára, ha az nincs
	telepítve a webszervered PATH-jában. Vedd figyelembe, hogy a
	'highlight' funkciónak be kell lennie állítva ahhoz, hogy a gitweb
	ténylegesen szintaxiskiemelést használjon.
+
*NOTE*: ahhoz, hogy egy fájl kiemelésre kerüljön, a szintaxistípusát
fel kell ismerni, és annak a szintaxisnak támogatottnak kell lennie a
"highlight" által. Az alapértelmezett szintaxisfelismerés minimális, és
sok támogatott szintaxistípushoz nincs alapértelmezett felismerés.
Három lehetőség van szintaxisfelismerés hozzáadására. Az első és a
második prioritás a `%highlight_basename` és a `%highlight_ext`,
amelyek az alapnév (a teljes fájlnév, például "Makefile") és a
kiterjesztés (például "sh") alapján ismernek fel. Ezeknek a hasheknek a
kulcsai rendre az alapnév és a kiterjesztés, egy adott kulcshoz tartozó
érték pedig a "highlight" számára `--syntax <syntax>` formában átadandó
szintaxis neve. Az utolsó prioritás a "highlight" `Shebang` reguláris
kifejezéseken alapuló konfigurációja, amely a fájl első sora alapján
ismeri fel a nyelvet (például a "#!/bin/bash" sorra illesztve). További
részletekért lásd a highlight dokumentációját és az alapértelmezett
konfigurációt a /etc/highlight/filetypes.conf fájlban.
+
Ha például az általad hosztolt repository-k "phtml" kiterjesztést
használnak a PHP fájlokhoz, és szeretnéd, hogy ezekhez a fájlokhoz
helyes szintaxiskiemelés tartozzon, a következőt adhatod a gitweb
konfigurációjához:
+
---------------------------------------------------------
our %highlight_ext;
$highlight_ext{'phtml'} = 'php';
---------------------------------------------------------


[[_links_and_their_targets]]
Linkek és céljaik
~~~~~~~~~~~~~~~~~
Az alább leírt konfigurációs változók a gitweb linkjei közül néhányat
állítanak be: a célpontjukat és a kinézetüket (szöveg vagy kép), valamint
azt, hogy hol találhatók az oldal előfeltételei (stíluslap, favicon,
képek, szkriptek). Ezek jellemzően az alapértelmezett értéken maradnak,
a `@stylesheets` változó esetleges kivételével.

@stylesheets::
	Stíluslapok URI-jainak listája (az oldal bázis-URI-jához
	viszonyítva). Megadhatsz több stíluslapot is, például hogy a
	"gitweb.css"-t használd alapként, a webhelyspecifikus
	módosításokkal egy külön stíluslapban, hogy könnyebb legyen a
	gitweb frissítése. Például hozzáadhatsz egy `site` stíluslapot a
	következővel
+
----------------------------------------------------------------------------
push @stylesheets, "gitweb-site.css";
----------------------------------------------------------------------------
+
a gitweb konfigurációs fájlban. Azok az értékek, amelyek relatív
útvonalak, a gitweb bázis-URI-jához viszonyítottak.
+
Ennek a listának tartalmaznia kell a gitweb szabványos stíluslapjának
URI-ját. A gitweb stíluslapjának alapértelmezett URI-ja build időben
állítható be a `GITWEB_CSS` makefile változóval. Az alapértelmezett
értéke `static/gitweb.css` (vagy `static/gitweb.min.css`, ha a `CSSMIN`
változó definiálva van, azaz ha CSS minifier volt használva a build
során).
+
*Note*: van egy örökölt `$stylesheet` konfigurációs változó is, amelyet
a régebbi gitweb használt. Ha a `$stylesheet` változó definiálva van,
a gitweb csak az e változó által megadott CSS stíluslapot használja.

$logo::
	Arra a helyre mutat, ahová a 'git-logo.png' fájlt tetted a
	webszervereden, vagy általánosabban a logó URI-jára (72x27-es
	méret). Ez a kép minden gitweb-oldal jobb felső sarkában jelenik
	meg, és az Atom hírcsatorna logójaként is szolgál. A gitweb
	bázis-URI-jához viszonyított (útvonalként). A gitweb buildelésekor
	a `GITWEB_LOGO` változóval állítható be. Alapértelmezés szerint
	`static/git-logo.png`.

$favicon::
	Arra a helyre mutat, ahová a 'git-favicon.png' fájlt tetted a
	webszervereden, vagy általánosabban a favicon URI-jára, amely
	"image/png" típusként lesz kiszolgálva. Azok a webböngészők,
	amelyek támogatják a favicont (webhelyikont), megjeleníthetik
	azokat a böngésző URL-sávjában és a könyvjelzőkben a webhely neve
	mellett. A gitweb bázis-URI-jához viszonyított. Build időben a
	`GITWEB_FAVICON` változóval állítható be. Alapértelmezés szerint
	`static/git-favicon.png`.

$javascript::
	Arra a helyre mutat, ahová a 'gitweb.js' fájlt tetted a
	webszervereden, vagy általánosabban a gitweb által használt
	JavaScript-kód URI-jára. A gitweb bázis-URI-jához viszonyított.
	Build időben a `GITWEB_JS` build-időbeli konfigurációs változóval
	állítható be.
+
Az alapértelmezett érték vagy `static/gitweb.js`, vagy
`static/gitweb.min.js`, ha a `JSMIN` build változó definiálva volt,
azaz ha build időben JavaScript minifier lett használva. *Note*, hogy
ez az egyetlen fájl több egyedi JavaScript "modulból" van generálva.

$home_link::
	A minden oldal tetején lévő home link célja (a nézet
	"morzsanyomának" első része). Alapértelmezés szerint az aktuális
	oldal abszolút URI-jára van beállítva (a `$my_uri` változó
	értékére, vagy "/"-re, ha a `$my_uri` nincs definiálva, vagy üres
	sztring).

$home_link_str::
	Címke a minden oldal tetején lévő "home link"-hez, amely a
	`$home_link`-re mutat (jellemzően a gitweb főoldalára, amely a
	projektlistát tartalmazza). Ez szolgál a gitweb "morzsanyomának"
	első összetevőjeként: `<home-link> / <project> / <action>`. Build
	időben a `GITWEB_HOME_LINK_STR` változóval állítható be.
	Alapértelmezés szerint "projects" értékre van állítva, mivel ez a
	link a projektek listájára vezet. Egy másik népszerű választás,
	hogy a webhely nevére állítjuk. Vedd figyelembe, hogy ez nyers
	HTML-ként van kezelve, ezért nem szabad megbízhatatlan forrásból
	beállítani.

@extra_breadcrumbs::
	További linkek, amelyek a morzsanyom elejéhez adódnak hozzá, a
	home link elé, olyan oldalakhoz, amelyek logikailag "a gitweb
	projektlista fölött" állnak, mint például a gitweb szervert hosztoló
	szervezet és részleg. A lista minden eleme egy tömbre mutató
	referencia, amelyben a 0. elem a link szövege (a `$home_link_str`
	megfelelője), az 1. elem pedig a cél URL (a `$home_link`
	megfelelője).
+
Például a következő beállítás egy olyan morzsanyomot eredményez, mint
"home / dev / projects / ...", ahol a "projects" a home link.
+
----------------------------------------------------------------------------
    our @extra_breadcrumbs = (
      [ 'home' => 'https://www.example.org/' ],
      [ 'dev'  => 'https://dev.example.org/' ],
    );
----------------------------------------------------------------------------

$logo_url::
$logo_label::
	URI és címke (title) a Git logó linkjéhez (vagy a saját webhelyed
	logójához, ha úgy döntesz, hogy más logóképet használsz).
	Alapértelmezés szerint mindkettő a Git honlapjára,
	a https://git-scm.com[] címre mutat; korábban a Git dokumentációjára
	mutattak, a https://www.kernel.org[] címre.


[[_changing_gitweb_s_look]]
A gitweb kinézetének megváltoztatása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Az alább leírt változók segítségével állíthatod be, hogyan nézzenek ki a
gitweb által generált oldalak. Megváltoztathatod a webhely nevét, közös
fejléceket és lábléceket adhatsz hozzá minden oldalhoz, és leírást
adhatsz ehhez a gitweb-telepítéshez a főoldalán (ami a projektlista
oldal), stb.

$site_name::
	A webhelyed vagy szervezeted neve, amely az oldalcímekben jelenik
	meg. Állítsd valami leíró jellegűre a tisztább könyvjelzők stb.
	érdekében. Ha ez a változó nincs beállítva, akkor a gitweb a
	`SERVER_NAME` `CGI` környezeti változó értékét használja, a
	webhely nevét "$SERVER_NAME Git" értékre állítva, vagy "Untitled
	Git" értékre, ha ez a változó sincs beállítva (pl. ha a gitweb
	önálló szkriptként fut).
+
Build időben a `GITWEB_SITENAME` segítségével állítható be.
Alapértelmezés szerint nincs beállítva.

$site_html_head_string::
	Az egyes oldalak <head> szekciójába beillesztendő HTML-töredék.
	Build időben a `GITWEB_SITE_HTML_HEAD_STRING` segítségével
	állítható be. Nincs alapértelmezett értéke.

$site_header::
	Egy HTML-t tartalmazó fájl neve, amely minden oldal tetejére
	kerül beillesztésre. A 'gitweb.cgi' szkriptet tartalmazó
	könyvtárhoz viszonyított. Build időben a `GITWEB_SITE_HEADER`
	segítségével állítható be. Nincs alapértelmezett értéke.

$site_footer::
	Egy HTML-t tartalmazó fájl neve, amely minden oldal aljára kerül
	beillesztésre. A 'gitweb.cgi' szkriptet tartalmazó könyvtárhoz
	viszonyított. Build időben a `GITWEB_SITE_FOOTER` segítségével
	állítható be. Nincs alapértelmezett értéke.

$home_text::
	Egy HTML fájl neve, amely, ha létezik, bekerül a gitweb
	projekt-áttekintő oldalára ("projects_list" nézet). A gitweb.cgi
	szkriptet tartalmazó könyvtárhoz viszonyított. Az alapértelmezett
	érték build időben a `GITWEB_HOMETEXT` változóval állítható be.
	Alapértelmezés szerint 'indextext.html'.

$projects_list_description_width::
	A projektlista "Description" oszlopának szélessége (karakterben).
	A hosszabb leírások csonkolásra kerülnek (szóhatárnál próbálva
	vágni); a teljes leírás elérhető a 'title' attribútumban
	(általában rámutatáskor jelenik meg). Az alapértelmezés 25, ami
	túl kicsi lehet, ha hosszú projektleírásokat használsz.

$default_projects_order::
	A projektek sorrendjének alapértelmezett értéke a projektlista
	oldalon, azaz az a sorrend, amely akkor van használva, ha nem
	rendezed explicit módon a projektlistát (ha nincs "o" CGI
	lekérdezési paraméter az URL-ben). Érvényes értékek: "none"
	(rendezetlen), "project" (a projektek a projektnév szerint, azaz
	a repository `$projectroot`-hoz viszonyított útvonala szerint),
	"descr" (projektleírás), "owner" és "age" (a legutóbbi commit
	dátuma szerint).
+
Az alapértelmezett érték "project". Ismeretlen érték rendezetlent
jelent.


[[_changing_gitweb_s_behavior]]
A gitweb viselkedésének megváltoztatása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ezek a konfigurációs változók a gitweb _belső_ viselkedését
szabályozzák.

$default_blob_plain_mimetype::
	Alapértelmezett mimetípus a blob_plain (nyers) nézethez, ha a
	mimetípus-ellenőrzés nem eredményez más típust; alapértelmezés
	szerint "text/plain". A gitweb a megjelenítendő fájl mimetípusát a
	fájlnév kiterjesztése alapján becsli, a `$mimetypes_file` (ha
	beállítva, és a fájl létezik) és a `/etc/mime.types` fájlok
	segítségével (lásd a *mime.types*(5) man page-et; a gitweb csak a
	fájlnév-kiterjesztés szabályokat támogatja).

$default_text_plain_charset::
	Alapértelmezett karakterkészlet szöveges fájlokhoz. Ha ez nincs
	beállítva, a webszerver konfigurációja lesz használva.
	Alapértelmezés szerint nincs beállítva.

$fallback_encoding::
	A gitweb ezt a karakterkészletet feltételezi, ha egy sor nem
	UTF-8 karaktereket tartalmaz. A tartalék dekódolás hibaellenőrzés
	nélkül történik, így akár "utf-8" is lehet. Az értéknek érvényes
	kódolásnak kell lennie; a listáért lásd az
	*Encoding::Supported*(3pm) man page-et. Az alapértelmezés
	"latin1", más néven "iso-8859-1".

@diff_opts::
	Átnevezés-felismerési opciók a git-diff és a git-diff-tree
	számára. Az alapértelmezés (\'-M'); állítsd (\'-C') vagy (\'-C',
	\'-C') értékre, hogy a másolásokat is felismerje, vagy állítsd ()
	értékre, azaz üres listára, ha nem szeretnél átnevezés-felismerést.
+
*Note*, hogy az átnevezés-, és különösen a másolás-felismerés elég
CPU-igényes lehet. Vedd figyelembe azt is, hogy a nem Git eszközöknek
problémáik lehetnek a fenti opciókkal generált patchekkel, különösen
ha azok fájlmásolásokat (\'-C') vagy keresztirányú átnevezéseket
(\'-B') érintenek.


[[_some_optional_features_and_policies]]
Néhány opcionális funkció és szabályzat
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A legtöbb funkció a `%feature` hash segítségével van beállítva; azonban
néhány extra gitweb-funkció az alább leírt változók segítségével
kapcsolható be és állítható be. Ez a lista a gitweb kinézetét vezérlő
konfigurációs változók mellett a gitweb adminisztratív oldalát is
beállító változókat tartalmaz (pl. a cross-site scripting elleni
védelmet; ez, elismerten, mellékhatásként befolyásolja azt is, hogyan
néznek ki az "summary" oldalak, vagy a terheléskorlátozást).

@git_base_url_list::
	Git alap-URL-ek listája. Ezek az URL-ek arra szolgálnak, hogy
	olyan URL-eket generáljanak, amelyek azt írják le, honnan kell
	egy projektet lehívni, és amelyek a projekt összefoglaló oldalán
	jelennek meg. A teljes lehívási URL "`$git_base_url/$project`", a
	lista minden eleméhez. Több alap-URL-t is beállíthatsz (például
	egyet a `git://` protokollhoz, és egyet a `http://` protokollhoz).
+
Vedd figyelembe, hogy a repository-nkénti konfiguráció beállítható a
`$GIT_DIR/cloneurl` fájlban, vagy a projekt konfigurációjában a
többértékű `gitweb.url` konfigurációs változó értékeiként. A
repository-nkénti konfiguráció elsőbbséget élvez a `@git_base_url_list`
elemeiből és a projektnévből összeállított értékkel szemben.
+
Beállíthatsz egyetlen értéket (egyetlen bejegyzést/elemet ebben a
listában) build időben, a `GITWEB_BASE_URL` build-időbeli konfigurációs
változó beállításával. Alapértelmezés szerint () értékre van állítva,
azaz üres listára. Ez azt jelenti, hogy a gitweb nem próbál meg
projekt-URL-t (lehíváshoz) létrehozni a projektnévből.

$projects_list_group_categories::
	Engedélyezve legyen-e a projektek kategória szerinti csoportosítása
	a projektlista oldalon. Egy projekt kategóriáját a `$GIT_DIR/category`
	fájl vagy az egyes repository-k konfigurációjában a
	`gitweb.category` változó határozza meg. Alapértelmezés szerint
	letiltva (0-ra állítva).

$project_list_default_category::
	Alapértelmezett kategória azoknak a projekteknek, amelyekhez nincs
	megadva. Ha ez üres sztringre van állítva, az ilyen projektek
	kategorizálatlanok maradnak, és a kategorizált projektek fölött,
	a lista tetején jelennek meg. Csak akkor kerül felhasználásra, ha
	a projektkategóriák engedélyezve vannak, azaz ha a
	`$projects_list_group_categories` igaz. Alapértelmezés szerint ""
	(üres sztring).

$prevent_xss::
	Ha igaz, egyes gitweb-funkciók le vannak tiltva, hogy megelőzzék,
	hogy a repository-kban lévő tartalom cross-site scripting (XSS)
	támadásokat indítson. Állítsd igazra, ha nem bízol a
	repository-jaid tartalmában. Alapértelmezés szerint hamis (0-ra
	állítva).

$maxload::
	Annak a maximális terhelésnek a beállítására szolgál, amelynél még
	válaszolunk a gitweb-lekérdezésekre. Ha a szerver terhelése
	meghaladja ezt az értéket, a gitweb "503 Service Unavailable"
	hibát ad vissza. A szerver terhelését 0-nak tekinti, ha a gitweb
	nem tudja meghatározni az értékét. Jelenleg csak Linuxon működik,
	ahol a `/proc/loadavg`-ot használja; az ott szereplő terhelés a
	rendszeren futó aktív feladatok száma -- a ténylegesen futó
	folyamatoké -- az elmúlt egy percre átlagolva.
+
Állítsd a `$maxload`-ot nem definiált értékre (`undef`), hogy kikapcsold
ezt a funkciót. Az alapértelmezett érték 300.

$omit_age_column::
	Ha igaz, a legutóbbi commit dátumát tartalmazó oszlop kimarad a
	projektlista oldalról. Ez némi I/O-t és repository-nkénti egy
	fork-ot takaríthat meg.

$omit_owner::
	Ha igaz, megakadályozza a repository tulajdonosára vonatkozó
	információk megjelenítését.

$per_request_config::
	Ha ez kódreferenciára van állítva, minden egyes kéréshez egyszer
	lefut. Így beállíthatod a konfiguráció azon részeit, amelyek
	munkamenetenként változnak. Például valaki a következő kódot
	használhatja egy gitweb konfigurációs fájlban
+
--------------------------------------------------------------------------------
our $per_request_config = sub {
	$ENV{GL_USER} = $cgi->remote_user || "gitweb";
};
--------------------------------------------------------------------------------
+
Ha a `$per_request_config` nem kódreferencia, logikai (boolean)
értékként van értelmezve. Ha igaz, a gitweb kérésenként egyszer
dolgozza fel a konfigurációs fájlokat, ha pedig hamis, a gitweb csak
egyszer dolgozza fel a konfigurációs fájlokat, minden egyes
végrehajtáskor. Alapértelmezés szerint igaz (1-re állítva).
+
*NOTE*: a `$my_url`, a `$my_uri` és a `$base_url` minden kérés előtt
felül van írva az alapértelmezett értékükkel, ezért ha meg szeretnéd
változtatni őket, mindenképp állítsd ezt a változót igazra, vagy egy, a
kívánt módosításokat elvégző kódreferenciára.
+
Ez a változó csak akkor számít, ha olyan tartós webkörnyezetet
használsz, amely egyetlen gitweb-példánnyal szolgál ki több kérést,
mint például a mod_perl, a FastCGI vagy a Plackup.


[[_other_variables]]
Egyéb változók
~~~~~~~~~~~~~~
Az alább leírt konfigurációs változók egyikét sem kellene általában
megváltoztatnod (módosítanod); ezeket a gitwebnek automatikusan a
helyes értékre kellene állítania.


$version::
	A gitweb verziója, automatikusan beállítva a gitweb.cgi
	gitweb.perl-ből történő létrehozásakor. Módosítani szeretnéd, ha
	módosított gitwebet futtatsz, például
+
---------------------------------------------------
our $version .= " with caching";
---------------------------------------------------
+
ha a gitweb gyorsítótárazást támogató módosított verzióját futtatod.
Ez a változó pusztán informatív célú, például a "generator" meta
fejlécben van használva a HTML fejlécében.

$my_url::
$my_uri::
	A gitweb-szkript teljes URL-je és abszolút URL-je; a gitweb
	korábbi verzióiban szükség lehetett ezeknek a változóknak a
	beállítására, de mostanra ennek nem kellene szükségesnek lennie.
	Lásd a `$per_request_config`-ot, ha mégis be kell állítanod őket.

$base_url::
	Bázis URL a gitweb által generált oldalakon lévő relatív URL-ekhez
	(pl. `$logo`, `$favicon`, `@stylesheets`, ha ezek relatív URL-ek),
	amely csak nem üres PATH_INFO-val rendelkező URL-ek esetén
	szükséges, és csak akkor van használva a '<base href="$base_url">'.
	A gitweb rendszerint helyesen állítja be az értékét, és nincs
	szükség e változó beállítására, pl. a $my_uri-ra vagy "/"-re. Lásd
	a `$per_request_config`-ot, ha mégis felül kell írnod.


CONFIGURING GITWEB FEATURES
---------------------------
Sok gitweb-funkció engedélyezhető (vagy letiltható) és beállítható a
`%feature` hash segítségével. A gitweb-funkciók nevei ennek a hashnek a
kulcsai.

Minden `%feature` hash-elem egy hash-referencia, és a következő
felépítésű:

----------------------------------------------------------------------
"<feature-name>" => {
	"sub" => <feature-sub-(subroutine)>,
	"override" => <allow-override-(boolean)>,
	"default" => [ <options>... ]
},
----------------------------------------------------------------------
Néhány funkció projektenként nem írható felül. Ezeknél a funkcióknál a
megfelelő `%feature` hash-elem felépítése egyszerűbb formájú:

----------------------------------------------------------------------
"<feature-name>" => {
	"override" => 0,
	"default" => [ <options>... ]
},
----------------------------------------------------------------------
Amint látható, ebből hiányzik a \'sub' elem.

A funkciókonfiguráció egyes részeinek jelentése alább található:

default::
	A funkció paramétereinek listája (tömb-referencia) (ha vannak
	ilyenek), amely az adott funkció be-/kikapcsolására (engedélyezésre
	vagy letiltásra) is szolgál.
+
Vedd figyelembe, hogy ez jelenleg *mindig* tömb-referencia, még akkor
is, ha a funkció nem fogad el semmilyen konfigurációs paramétert, és a
\'default' csak a be- vagy kikapcsolására szolgál. Ebben az esetben a
funkciót úgy kapcsolod be, hogy ezt az elemet `[1]`-re állítod, és úgy
kapcsolod ki, hogy `[0]`-ra állítod. Lásd még a "blame" funkcióról
szóló részt az "Examples" szekcióban.
+
Azoknak a funkcióknak a letiltásához, amelyek paramétereket fogadnak el
(konfigurálhatók), ezt az elemet üres listára, azaz `[]`-ra kell
állítanod.

override::
	Ha ez a mező igaz értékű, akkor az adott funkció felülírható, ami
	azt jelenti, hogy repository-nkénti alapon konfigurálható (illetve
	engedélyezhető/letiltható).
+
Az adott "<feature>" jellemzően a `gitweb.<feature>` config-változóval
konfigurálható a repository-nkénti Git konfigurációs fájlban.
+
*Note*, hogy alapértelmezés szerint egyetlen funkció sem felülírható.

sub::
	A megvalósítás belső részlete. Ami fontos, hogy ha ez a mező nincs
	jelen, akkor az adott funkcióhoz nem támogatott a repository-nkénti
	felülírás.
+
Soha nem lesz szükséged arra, hogy ezt megváltoztasd a gitweb
konfigurációs fájljában.


[[_features_in_feature]]
Funkciók a `%feature`-ben
~~~~~~~~~~~~~~~~~~~~~~~~~
Az alább felsorolt gitweb-funkciók a `%feature` hash segítségével
konfigurálhatók. Ennek a listának teljesnek kellene lennie, de a
végérvényesen hiteles és teljes lista a gitweb.cgi forráskódjában
található, a funkciók a kommentekben leírva.

blame::
	Engedélyezi a "blame" és a "blame_incremental" blob-nézeteket,
	amelyek minden egyes sorhoz megmutatják az azt utoljára módosító
	commitot; lásd linkgit:git-blame[1]. Ez nagyon CPU-igényes lehet,
	ezért alapértelmezés szerint le van tiltva.
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.blame` konfigurációs változóján keresztül (logikai).

snapshot::
	Engedélyezi és beállítja a "snapshot" akciót, amely lehetővé teszi
	a felhasználó számára, hogy bármely tree vagy commit tömörített
	archívumát letöltse, ahogy azt a linkgit:git-archive[1] állítja
	elő, esetleg további tömörítéssel. Ez potenciálisan nagy
	forgalmat generálhat, ha nagy méretű a projekted.
+
A \'default' értéke a felkínálni kívánt snapshot-formátumok neveinek
listája, amelyeket a `%known_snapshot_formats` hash definiál. A
támogatott formátumok közé tartozik a "tgz", a "tbz2", a "txz"
(gzip/bzip2/xz tömörítésű tar archívum) és a "zip"; a végleges
listáért nézd meg a gitweb forráskódját. Alapértelmezés szerint csak a
"tgz" van felkínálva.
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.snapshot` konfigurációs változóján keresztül, amely a
formátumok vesszővel elválasztott listáját tartalmazza, vagy a "none"
értéket a snapshotok letiltásához. Az ismeretlen értékek figyelmen
kívül maradnak.

grep::
	Engedélyezi a grep-keresést, amely felsorolja azokat a fájlokat a
	jelenleg kiválasztott tree-ben (könyvtárban), amelyek tartalmazzák
	a megadott sztringet; lásd linkgit:git-grep[1]. Ez természetesen
	potenciálisan CPU-igényes lehet. Alapértelmezés szerint
	engedélyezve.
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.grep` konfigurációs változóján keresztül (logikai).

pickaxe::
	Engedélyezi az úgynevezett pickaxe-keresést, amely felsorolja
	azokat a commitokat, amelyek egy adott sztringet bevezettek vagy
	eltávolítottak egy fájlból. Ez praktikus és jóval gyorsabb
	alternatívája lehet a "blame" akciónak, de továbbra is
	potenciálisan CPU-igényes. Alapértelmezés szerint engedélyezve.
+
A pickaxe-keresés a linkgit:git-log[1]-ban van leírva (a
`-S<string>` opció leírásában, amely a pickaxe bejegyzésre hivatkozik
a linkgit:gitdiffcore[7]-ban a további részletekért).
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.pickaxe` konfigurációs változójának beállításával (logikai).

show-sizes::
	Engedélyezi a blobok (közönséges fájlok) méretének megjelenítését
	egy "tree" nézetben, egy külön oszlopban, hasonlóan ahhoz, ahogy
	az `ls -l` teszi; lásd a `-l` opció leírását a
	linkgit:git-ls-tree[1] man page-en. Ez némi I/O-ba kerül.
	Alapértelmezés szerint engedélyezve.
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.showSizes` konfigurációs változóján keresztül (logikai).

patches::
	Engedélyezi és beállítja a "patches" nézetet, amely a commitok
	listáját e-mail (sima szöveges) kimeneti formátumban jeleníti meg;
	lásd még linkgit:git-format-patch[1]. Az érték a "patches"
	nézetben generált patchsetben szereplő patchek maximális száma.
	Állítsd a 'default' mezőt egyetlen elemet tartalmazó listára, vagy
	üres listára a patch-nézet letiltásához, vagy egyetlen negatív
	számot tartalmazó listára a korlát megszüntetéséhez.
	Az alapértelmezett érték 16.
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.patches` konfigurációs változóján keresztül (egész szám).

avatar::
	Avatar-támogatás. Ha ez a funkció engedélyezve van, az olyan
	nézetek, mint a "shortlog" vagy a "commit", megjelenítik az egyes
	committerek és szerzők e-mail címéhez társított avatart.
+
Jelenleg elérhető szolgáltatók a *"gravatar"* és a *"picon"*.
Egyszerre csak egy szolgáltató választható ki ('default' egyelemű
lista). Ha ismeretlen szolgáltatót adsz meg, a funkció le lesz tiltva.
*Note*, hogy egyes szolgáltatók extra Perl csomagok telepítését
igényelhetik; a további részletekért lásd a `gitweb/INSTALL` fájlt.
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.avatar` konfigurációs változóján keresztül.
+
Lásd még a `%avatar_size`-t az ikonok és avatarok pixelben megadott
méreteivel ("default" az olyan egysoros nézetekhez van használva, mint
a "log" és a "shortlog", "double" pedig az olyan kétsoros nézetekhez,
mint a "commit", a "commitdiff" vagy a "tag"). Ha az alapértelmezett
betűméretek vagy sormagasságok megváltoznak (pl. extra CSS stíluslap
hozzáadásával a `@stylesheets`-hez), érdemes lehet megváltoztatni
ezeket az értékeket is.

email-privacy::
	Kitakarja az e-mail címeket a generált HTML-ből stb. tartalomból.
	Ez elrejti a Git log szerző/committer és komment szekcióiból
	kinyert e-mail címeket.
	Célja, hogy megnehezítse a címeket learató és azokkal visszaélő
	webrobotok dolgát.
	Az ilyen robotok esetleg nem tartják tiszteletben a robots.txt-t.
	Vedd figyelembe, hogy a felhasználók és a felhasználói eszközök is
	kitakartan látják a címeket.
	Ha a Gitweb nem az utolsó lépés egy munkafolyamatban, a további
	lépések helytelenül viselkedhetnek a kapott, kitakart információk
	miatt.
	Alapértelmezés szerint letiltva.

highlight::
	Szerveroldali szintaxiskiemelés-támogatás a "blob" nézetben. Ehhez
	szükséges, hogy a `$highlight_bin` program elérhető legyen (lásd
	ennek a változónak a leírását a fenti "Configuration variables"
	szekcióban), ezért alapértelmezés szerint le van tiltva.
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.highlight` konfigurációs változóján keresztül (logikai).

remote_heads::
	Engedélyezi a remote head-ek (remote-tracking branchek)
	megjelenítését a "heads" listában. A legtöbb esetben a
	remote-tracking branchek listája szükségtelen belső, privát
	részlet, ezért ez a funkció alapértelmezés szerint le van tiltva.
	A linkgit:git-instaweb[1], amelyet jellemzően helyi repository-k
	böngészésére használnak, engedélyezi és használja ezt a funkciót.
+
Ez a funkció repository-nkénti alapon konfigurálható a repository
`gitweb.remote_heads` konfigurációs változóján keresztül (logikai).


A fennmaradó funkciók projektenként nem írhatók felül.

search::
	Engedélyezi a szöveges keresést, amely felsorolja azokat a
	commitokat, amelyeknek a szerzője, committere vagy commit-szövege
	illeszkedik a megadott sztringre; lásd a `--author`, a
	`--committer` és a `--grep` opciók leírását a linkgit:git-log[1]
	man page-en. Alapértelmezés szerint engedélyezve.
+
A projektspecifikus felülírás nem támogatott.

forks::
	Ha ez a funkció engedélyezve van, a gitweb a projektgyökér
	(alapnév) alkönyvtáraiban lévő projekteket a meglévő projektek
	forkjainak tekinti. Minden egyes +$projname.git+ projekthez a
	+$projname/+ könyvtárban és alkönyvtáraiban lévő projektek nem
	fognak megjelenni a fő projektlistában. Ehelyett egy \'+' jel
	jelenik meg a `$projname` mellett, amely egy "forks" nézetre
	mutat, amely felsorolja az összes forkot (a `$projname/`
	alkönyvtárban lévő összes projektet). Emellett egy projekt
	"forks" nézetére a projekt összefoglaló oldaláról is mutat link.
+
Ha a projektlista egy fájlból származik (a +$projects_list+ egy
fájlra mutat), a forkok csak akkor kerülnek felismerésre, ha a fő
projekt után vannak felsorolva abban a fájlban.
+
A projektspecifikus felülírás nem támogatott.

actions::
	Egyéni linkeket illeszt be minden projektoldal akciósávjába. Ez
	lehetővé teszi, hogy a gitwebbe integrálódó harmadik féltől
	származó szkriptekre mutass linkeket.
+
A "default" érték hármasok listájából áll,
`("<label>", "<link>", "<position>")` alakban, ahol "position" az a
címke, amely után a linket be kell szúrni, "link" pedig egy
formátumsztring, amelyben a `%n` a projekt nevére bővül ki, az `%f` a
projekt fájlrendszerbeli útvonalára (azaz "$projectroot/$project"), a
`%h` az aktuális hash-re (\'h' gitweb-paraméter), a `%b` pedig az
aktuális hash-alapra (\'hb' gitweb-paraméter); a `%%` pedig \'%'-ra
bővül ki.
+
Például ennek az oldalnak az írásakor a https://repo.or.cz[] Git
hosting-oldal a következőre állította ezt be, hogy engedélyezze a
grafikus logot (a *git-browser* harmadik féltől származó eszköz
használatával):
+
----------------------------------------------------------------------
$feature{'actions'}{'default'} =
	[ ('graphiclog', '/git-browser/by-commit.html?r=%n', 'summary')];
----------------------------------------------------------------------
+
Ez egy "graphiclog" című linket ad hozzá a "summary" link után, amely a
`git-browser` szkriptre vezet, `r=<project>` lekérdezési paramétert
átadva.
+
A projektspecifikus felülírás nem támogatott.

timed::
	Engedélyezi annak megjelenítését, hogy mennyi időbe és hány Git
	parancsba telt az adott oldal generálása és megjelenítése, az
	oldal láblécében (az oldal alján). Például a lábléc a következőt
	tartalmazhatja: "This page took 6.53325 seconds and 13 Git
	commands to generate." Alapértelmezés szerint letiltva.
+
A projektspecifikus felülírás nem támogatott.

javascript-timezone::
	Engedélyezi és beállítja azt a lehetőséget, hogy a gitweb
	kimenetében szereplő dátumokhoz közös időzónát lehessen váltani
	JavaScript segítségével. A gitweb kimenetében szereplő dátumok
	közé tartozik a szerzői dátum és a committer-dátum a "commit", a
	"commitdiff" és a "log" nézetekben, valamint a tagger-dátum a
	"tag" nézetben. Alapértelmezés szerint engedélyezve.
+
Az érték három érték listája: egy alapértelmezett időzóna (arra az
esetre, ha a kliens nem választott másik időzónát, és nem mentette el
azt egy cookie-ban), a kiválasztott időzóna tárolására szolgáló cookie
neve, és egy, a dátumok kezelésre való megjelölésére használt
CSS-osztály. Ha ki szeretnéd kapcsolni ezt a funkciót, állítsd a
"default"-ot üres listára: `[]`.
+
A tipikus gitweb konfigurációs fájlok csak a kiinduló (alapértelmezett)
időzónát változtatják meg, a többi elemet az alapértelmezett értéken
hagyva:
+
---------------------------------------------------------------------------
$feature{'javascript-timezone'}{'default'}[0] = "utc";
---------------------------------------------------------------------------
+
Az itt bemutatott példakonfiguráció garantáltan visszafelé és előre is
kompatibilis.
+
Az időzóna-értékek lehetnek "local" (a böngésző által használt helyi
időzónához), "utc" (amit a gitweb használ, ha a JavaScript vagy ez a
funkció le van tiltva), vagy numerikus időzónák "+/-HHMM" formában,
mint például "+0200".
+
A projektspecifikus felülírás nem támogatott.

extra-branch-refs::
	A "refs" alatti további könyvtárak listája, amelyeket branch
	refként fognak használni. Ha például van egy gerrit-beállításod,
	ahol a refs/heads/ alatti összes branch hivatalos,
	felülvizsgálat-utáni push-szal létrejövő, a refs/sandbox/, a
	refs/wip és a refs/other alatti branchek pedig felhasználói
	branchek, amelyeknél sokkal szélesebb jogosultságok vannak, akkor
	érdemes lehet a következőképp beállítanod ezt a változót:
+
--------------------------------------------------------------------------------
$feature{'extra-branch-refs'}{'default'} =
	['sandbox', 'wip', 'other'];
--------------------------------------------------------------------------------
+
Ez a funkció repository-nkénti alapon konfigurálható, miután a
$feature{'extra-branch-refs'}{'override'}-ot igazra állítottad, a
repository `gitweb.extraBranchRefs` konfigurációs változóján keresztül,
amely a refek szóközzel elválasztott listáját tartalmazza. Egy példa:
+
--------------------------------------------------------------------------------
[gitweb]
	extraBranchRefs = sandbox wip other
--------------------------------------------------------------------------------
+
A gitweb.extraBranchRefs valójában egy többértékű konfigurációs
változó, így a következő példa is helyes, és az eredmény ugyanaz, mint
a fenti kódrészleté:
+
--------------------------------------------------------------------------------
[gitweb]
	extraBranchRefs = sandbox
	extraBranchRefs = wip other
--------------------------------------------------------------------------------
+
Hiba olyan refet megadni, amely nem felel meg a "git check-ref-format"
vizsgálatnak. A duplikált értékek ki vannak szűrve.


EXAMPLES
--------

A blame, a pickaxe-keresés és a snapshot-támogatás engedélyezéséhez
(lehetővé téve a "tar.gz" és a "zip" snapshotokat), miközben az egyes
projektek kikapcsolhatják azokat, tedd a következőt a GITWEB_CONFIG
fájlodba:

--------------------------------------------------------------------------------
$feature{'blame'}{'default'} = [1];
$feature{'blame'}{'override'} = 1;

$feature{'pickaxe'}{'default'} = [1];
$feature{'pickaxe'}{'override'} = 1;

$feature{'snapshot'}{'default'} = ['zip', 'tgz'];
$feature{'snapshot'}{'override'} = 1;
--------------------------------------------------------------------------------

Ha engedélyezed a felülírást a snapshot funkcióhoz, megadhatod, mely
snapshot-formátumok legyenek globálisan letiltva. Bármilyen
parancssori opciót is hozzáadhatsz, amit csak szeretnél (például a
tömörítési szint beállítását). Például letilthatod a Zip tömörítésű
snapshotokat, és beállíthatod, hogy a *gzip*(1) 6-os szinten fusson, a
következő sorok gitweb konfigurációs fájlodhoz való hozzáadásával:

	$known_snapshot_formats{'zip'}{'disabled'} = 1;
	$known_snapshot_formats{'tgz'}{'compressor'} = ['gzip','-6'];

BUGS
----
A hibakeresés egyszerűbb lenne, ha a tartalék konfigurációs fájlnak
(`/etc/gitweb.conf`) és a helyének felülírására szolgáló környezeti
változónak ('GITWEB_CONFIG_SYSTEM') olyan nevei lennének, amelyek
tükrözik a "tartalék" szerepüket. A jelenlegi nevek meg vannak tartva,
hogy ne törjenek el a működő beállítások.

ENVIRONMENT
-----------
A példányonkénti és a rendszerszintű konfigurációs fájlok helye a
következő környezeti változókkal írható felül:

GITWEB_CONFIG::
	Beállítja a példányonkénti konfigurációs fájl helyét.
GITWEB_CONFIG_SYSTEM::
	Beállítja a tartalék rendszerszintű konfigurációs fájl helyét.
	Ez a fájl csak akkor kerül beolvasásra, ha a példányonkénti nem
	létezik.
GITWEB_CONFIG_COMMON::
	Beállítja a közös rendszerszintű konfigurációs fájl helyét.


FILES
-----
gitweb_config.perl::
	Ez a példányonkénti konfigurációs fájl alapértelmezett neve. Ennek
	a fájlnak a formátuma fentebb van leírva.
/etc/gitweb.conf::
	Ez a tartalék rendszerszintű konfigurációs fájl alapértelmezett
	neve. Ez a fájl csak akkor van használva, ha a példányonkénti
	konfigurációs változó nem található.
/etc/gitweb-common.conf::
	Ez a közös rendszerszintű konfigurációs fájl alapértelmezett neve.


SEE ALSO
--------
linkgit:gitweb[1], linkgit:git-instaweb[1]

'gitweb/README', 'gitweb/INSTALL'

GIT
---
A linkgit:git[1] csomag része
