gitweb(1)
=========

NAME
----
gitweb - Git webes felület (webes frontend Git repository-khoz)

SYNOPSIS
--------
A gitweb kipróbálásához futtasd a linkgit:git-instaweb[1] parancsot egy Git
repository-ból. Ez konfigurálja és elindítja a webszervert, majd elindít egy
webböngészőt, amely a gitwebre mutat.


DESCRIPTION
-----------
A gitweb webes felületet biztosít a Git repository-khoz. Jellemzői közé tartozik:

* Több, közös gyökerű Git repository megtekintése.
* A repository minden revíziójának böngészése.
* A repositoryban lévő fájlok tartalmának megtekintése bármely revízióban.
* A branchek revíziónaplójának, valamint a fájlok és könyvtárak
  történetének megtekintése, azaz hogy mi változott, mikor, és ki által.
* Bármely fájl blame/annotáció-részleteinek megtekintése (ha engedélyezve van).
* RSS és Atom feedek generálása a commitokról, bármely branchhez.
  A feedek modern webböngészőkben automatikusan felismerhetők.
* Egy revízióban módosított minden elem megtekintése, valamint a revíziók
  egyenkénti végiglépkedése, a repository történetének megtekintése közben.
* Olyan commitok keresése, amelyek commit-üzenete illeszkedik egy megadott
  keresési kifejezésre.

A gitweb forráskódja a https://repo.or.cz/w/git.git/tree/HEAD:/gitweb/[]
címen tekinthető meg, magával a gitwebbel böngészve.


CONFIGURATION
-------------
A gitweb viselkedésének különböző aspektusai a `gitweb_config.perl` vagy az
`/etc/gitweb.conf` konfigurációs fájlon keresztül szabályozhatók. A
részletekért lásd a linkgit:gitweb.conf[5]-öt.

[[_repositories]]
Repository-k
~~~~~~~~~~~~
A gitweb egy vagy több Git repositoryból tud információt megjeleníteni. Ezeknek
a repository-knak mindegyike a helyi fájlrendszeren kell legyen, és közös
repository-gyökérrel kell rendelkezniük, azaz mindnek egyetlen szülő-repository
alatt kell lennie (lásd még az "ADVANCED WEB SERVER SETUP" szekció
"Webszerver-konfiguráció több projekt-gyökérrel" alszekcióját).

-----------------------------------------------------------------------
our $projectroot = '/path/to/parent/directory';
-----------------------------------------------------------------------

A `$projectroot` alapértelmezett értéke `/pub/git`. Ez a gitweb buildelése
során a `GITWEB_PROJECTROOT` build-konfigurációs változóval módosítható.

Alapértelmezés szerint a `$projectroot` alatti összes Git repository látható
és elérhető a gitweb számára. A projektek listáját alapértelmezés szerint a
`$projectroot` könyvtár átvizsgálásával állítja elő, Git repository-kat keresve
benne (pontosabban objektumadatbázisokat; a gitweb nem érdeklődik a munkaterület
iránt, és leginkább "bare" repository-k megjelenítésére alkalmas).

A repository neve a gitwebben a `$GIT_DIR`-jének (az objektumadatbázisának)
a `$projectroot`-hoz viszonyított relatív útvonala. Ezért a $repo repository
a "$projectroot/$repo" helyen található meg.


[[_projects_list_file_format]]
A projektlista fájl formátuma
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ahelyett, hogy a gitweb a $projectroot-tól kezdve a fájlrendszer
átvizsgálásával keresné meg a repository-kat, megadhatsz egy előre
legenerált listát a látható projektekről a `$projects_list` beállításával,
amely egy sima szöveges fájlra mutat, amiben a projektek listája szerepel
(némi kiegészítő információval együtt).

Ez a fájl a következő formátumot használja:

* Soronként egy rekord (projekt / repository); nem támogatja a sortörés
folytatását (újsor-escapelést).

* A kezdő és záró whitespace figyelmen kívül marad.

* Whitespace-szel elválasztott mezők; bármilyen hosszú whitespace-sorozat
használható mezőelválasztóként (a Perl "`split(" ", $line)`" szabályai
szerint).

* A mezők a RFC 3986, 2.1. szakaszában (Percent-Encoding) meghatározott
módosított URI-kódolást használják, pontosabban a "Query string encoding"-ot
(lásd https://en.wikipedia.org/wiki/Query_string#URL_encoding[]), azzal a
különbséggel, hogy a SP (" ") "{plus}"-ként is kódolható (és ezért a
"{plus}"-t is percent-encode-olni kell).
+
A fenntartott karakterek: "%" (a kódoláshoz használva), "{plus}" (a SPACE
kódolására használható), valamint a Perl által whitespace-ként definiált
összes karakter, beleértve a SP-t, TAB-ot és LF-et (a rekordon belüli mezők
elválasztására használva).

* A jelenleg felismert mezők a következők:
<repository path>::
	a repository GIT_DIR-jének útvonala, a `$projectroot`-hoz viszonyítva
<repository owner>::
	repository-tulajdonosként jelenik meg, lehetőleg teljes név, e-mail
	cím, vagy mindkettő

A projektlista index fájlt közvetlenül a gitwebből is legenerálhatod a
project_index akcióval (a projektlista oldalon lévő 'TXT' linkkel); lásd
még a lenti "A projektlista generálása gitweb segítségével" szekciót.

Példa tartalom:

-----------------------------------------------------------------------
foo.git       Joe+R+Hacker+<joe@example.com>
foo/bar.git   O+W+Ner+<owner@example.org>
-----------------------------------------------------------------------


Alapértelmezés szerint ez a fájl csak azt szabályozza, mely projektek
*láthatók* a projektlista oldalon (megjegyzendő, hogy azok a bejegyzések,
amelyek nem mutatnak megfelelően felismert Git repository-ra, nem jelennek
meg a gitwebben). Még ha egy projekt nem is látható a projektlista oldalon,
akkor is megtekintheted egy kézzel összeállított gitweb URL segítségével. A
`$strict_export` konfigurációs változó (lásd linkgit:gitweb.conf[5])
igazra állításával engedélyezheted, hogy csak azok a repository-k legyenek
megtekinthetők, amelyek az áttekintő oldalon is szerepelnek (azaz csak a
projektlista fájlban explicit módon felsorolt projektek lesznek elérhetők).


[[_generating_projects_list_using_gitweb]]
A projektlista generálása gitweb segítségével
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Feltesszük, hogy a GITWEB_CONFIG a Makefile alapértelmezett értékét veszi
fel, nevezetesen a 'gitweb_config.perl'-t. Tedd a következőt a
'gitweb_make_index.perl' fájlba:

----------------------------------------------------------------------------
read_config_file("gitweb_config.perl");
$projects_list = $projectroot;
----------------------------------------------------------------------------

Ezután hozd létre a következő szkriptet, hogy megkapd a projektlistát a
GITWEB_LIST build-konfigurációs változóhoz (vagy a gitweb konfigurációban
lévő `$projects_list` változóhoz) megfelelő formátumban:

----------------------------------------------------------------------------
#!/bin/sh

export GITWEB_CONFIG="gitweb_make_index.perl"
export GATEWAY_INTERFACE="CGI/1.1"
export HTTP_ACCEPT="*/*"
export REQUEST_METHOD="GET"
export QUERY_STRING="a=project_index"

perl -- /var/www/cgi-bin/gitweb.cgi
----------------------------------------------------------------------------

Futtasd ezt a szkriptet, és mentsd a kimenetét egy fájlba. Ez a fájl aztán
projektlista fájlként használható, azaz beállíthatod a `$projects_list`-et
a fájlnevére.


[[_controlling_access_to_git_repositories]]
Hozzáférés szabályozása a Git repository-khoz
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Alapértelmezés szerint a `$projectroot` alatti összes Git repository látható
és elérhető a gitweb számára. Ugyanakkor beállíthatod, hogyan szabályozza a
gitweb a repository-khoz való hozzáférést.

* Ahogy a "A projektlista fájl formátuma" szekcióban leírtuk, azt
szabályozhatod, mely projektek *láthatók*, ha szelektíven felveszed a
repository-kat a projektlista fájlba, és a `$projects_list` gitweb
konfigurációs változót erre állítod. A `$strict_export` beállításával a
projektlista fájl arra is használható, hogy szabályozza, mely repository-k
*elérhetők*.

* Beállíthatod a gitwebet úgy, hogy csak az explicit módon exportált
repository-kat listázza és engedje megtekinteni, a gitweb konfigurációs
fájlban lévő `$export_ok` változó segítségével; lásd a
linkgit:gitweb.conf[5] man page-et. Ha ez igazra értékelődik ki, a gitweb
csak akkor mutatja a repository-kat, ha az `$export_ok` által megnevezett
fájl létezik az objektumadatbázisában (azaz a könyvtárban megvan az
`$export_ok` nevű mágikus fájl).
+
Például a linkgit:git-daemon[1] alapértelmezés szerint (hacsak nincs
használva a `--export-all` opció) csak azoknak a repository-knak engedi a
pull-olást, amelyeknek megvan a 'git-daemon-export-ok' fájljuk. A következő
hozzáadása
+
--------------------------------------------------------------------------
our $export_ok = "git-daemon-export-ok";
--------------------------------------------------------------------------
+
azt eredményezi, hogy a gitweb csak azokat a repository-kat mutatja és
teszi elérhetővé, amelyek a `git://` protokollon keresztül fetchelhetők.

* Végül lehetőség van egy tetszőleges perl-alrutin megadására is, amelyet a
rendszer minden repository-ra meghív, hogy eldöntse, exportálható-e. Az
alrutin egyetlen paraméterként a projekt (repository) abszolút útvonalát
kapja meg (azaz "$projectroot/$project").
+
Például, ha mod_perl-t használsz a szkript futtatásához, és néma
HTTP-protokoll-hitelesítés van beállítva a repository-jaidhoz, a
következő hookkal engedélyezheted a hozzáférést csak akkor, ha a
felhasználó jogosult a fájlok olvasására:
+
--------------------------------------------------------------------------
$export_auth_hook = sub {
	use Apache2::SubRequest ();
	use Apache2::Const -compile => qw(HTTP_OK);
	my $path = "$_[0]/HEAD";
	my $r    = Apache2::RequestUtil->request;
	my $sub  = $r->lookup_file($path);
	return $sub->filename eq $path
	    && $sub->status == Apache2::Const::HTTP_OK;
};
--------------------------------------------------------------------------


[[_per_repository_gitweb_configuration]]
Repository-nkénti gitweb-konfiguráció
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A gitwebben megjelenő egyes repository-kat úgy konfigurálhatod, hogy fájlt
hozol létre a Git repository `GIT_DIR`-jében, vagy beállítasz valamilyen
repo-konfigurációs változót (a `GIT_DIR/config`-ban, lásd
linkgit:git-config[1]).

A repository-ban a következő fájlokat használhatod:

README.html::
	Egy html fájl (HTML-fragmens), amely bekerül a gitweb projekt
	"summary" oldalára, egy `<div>` blokk-elemen belül. Ezt használhatod
	egy projekt hosszabb leírására, linkek megadására (például a projekt
	honlapjához), stb. Ez csak akkor lesz felismerve, ha az XSS-védelem ki
	van kapcsolva (`$prevent_xss` hamis, lásd linkgit:gitweb.conf[5]); a
	jövőben talán kidolgozásra kerül egy mód, hogy egy README-t
	biztonságosan be lehessen illeszteni akkor is, ha az XSS-védelem be
	van kapcsolva.

description (or `gitweb.description`)::
	Egy projekt (egy repository) rövid (a projektlista oldalon
	`$projects_list_description_width`-re rövidítve, ami alapértelmezés
	szerint 25 karakter; lásd linkgit:gitweb.conf[5]), egysoros leírása.
	Sima szöveges fájl; a HTML escapelve lesz. Alapértelmezés szerint a
+
-------------------------------------------------------------------------------
Unnamed repository; edit this file to name it for gitweb.
-------------------------------------------------------------------------------
+
értékre van állítva, a repository létrehozásakor a sablonból, amely
általában a `/usr/share/git-core/templates/` alatt van telepítve.
Használhatod a `gitweb.description` repo-konfigurációs változót is, de a
fájl elsőbbséget élvez.

category (or `gitweb.category`)::
	Egy projekt egysoros kategóriája, amely a projektek csoportosítására
	szolgál, ha a `$projects_list_group_categories` engedélyezve van.
	Alapértelmezés szerint (ha sem a fájl, sem a konfigurációs változó
	nincs jelen) a kategorizálatlan projektek a
	`$project_list_default_category` kategóriába kerülnek. Használhatod a
	`gitweb.category` repo-konfigurációs változót is, de a fájl
	elsőbbséget élvez.
+
A `$projects_list_group_categories` és `$project_list_default_category`
konfigurációs változók leírása a linkgit:gitweb.conf[5]-ben található

cloneurl (or multiple-valued `gitweb.url`)::
	Fájl a repository URL-jével (klónozáshoz és fetcheléshez használva),
	soronként egy. A projekt summary oldalán jelenik meg. Erre a célra
	használhatod a többértékű `gitweb.url` repository-konfigurációs
	változót is, de a fájl elsőbbséget élvez.
+
Ez a globális, prefix-alapú `@git_base_url_list` gitweb konfigurációs
változó (lásd linkgit:gitweb.conf[5]) repository-nkénti kiegészítése /
változata.

gitweb.owner::
	A `gitweb.owner` repository-konfigurációs változóval beállíthatod a
	repository tulajdonosát. Ez megjelenik a projektlistán és a summary
	oldalon.
+
Ha nincs beállítva, a fájlrendszerbeli könyvtár tulajdonosa kerül
felhasználásra (a GECOS mezőn keresztül, azaz a *getpwuid*(3) valós
név mezőjéből), ha a `$projects_list` nincs beállítva (a gitweb ekkor a
`$projectroot`-ot vizsgálja át repository-kért); ha a `$projects_list`
egy repository-lista fájlra mutat, akkor a projekt tulajdonosa
alapértelmezés szerint az adott repository-hoz tartozó, ebből a fájlból
származó érték lesz.

various `gitweb.*` config variables (in config)::
	A részletes listáért és leírásokért olvasd el a `%feature` hash
	leírását. Lásd még a "Configuring gitweb features" szekciót a
	linkgit:gitweb.conf[5]-ben


ACTIONS, AND URLS
-----------------
A gitweb path_info (komponens) alapú URL-eket is tud használni, vagy az összes
szükséges információt átadhatja query paramétereken keresztül. A jellemző
gitweb URL-ek öt komponensre bonthatók le:

-----------------------------------------------------------------------
.../gitweb.cgi/<repo>/<action>/<revision>:/<path>?<arguments>
-----------------------------------------------------------------------

repo::
	A repository, amelyen az akció végrehajtásra kerül.
+
Minden akció, azok kivételével, amelyek valamilyen formában az összes
elérhető projektet listázzák, megköveteli ezt a paramétert.

action::
	Az akció, amely lefut. Alapértelmezés szerint 'projects_list', ha a
	repo nincs beállítva, egyébként pedig 'summary'.

revision::
	A megjelenített revízió. Alapértelmezés szerint HEAD.

path::
	A <repository>-n belüli útvonal, amelyen az akció végrehajtásra
	kerül, azon akciók esetében, amelyeknek ez szükséges.

arguments::
	Bármely argumentum, amely az akció viselkedését szabályozza.

Néhány akció megköveteli vagy lehetővé teszi két revízió megadását, sőt
néha akár két útvonalnevet is. A legáltalánosabb formában egy ilyen
path_info (komponens) alapú gitweb URL a következőképpen néz ki:

-----------------------------------------------------------------------
.../gitweb.cgi/<repo>/<action>/<revision-from>:/<path-from>..<revision-to>:/<path-to>?<arguments>
-----------------------------------------------------------------------


Minden akció egy-egy alrutinként van megvalósítva, és jelen kell lennie a
%actions hashben. Néhány akció alapértelmezés szerint le van tiltva, és a
feature-mechanizmuson keresztül kell bekapcsolni. Például a 'blame' nézet
engedélyezéséhez add hozzá a következőt a gitweb konfigurációs fájlhoz:

-----------------------------------------------------------------------
$feature{'blame'}{'default'} = [1];
-----------------------------------------------------------------------


[[_actions]]
Akciók:
~~~~~~~
A standard akciók a következők:

project_list::
	Kilistázza az elérhető Git repository-kat. Ez az alapértelmezett
	parancs, ha az URL-ben nincs repository megadva.

summary::
	Megjeleníti a megadott repository összefoglalóját. Ez az
	alapértelmezett parancs, ha az URL-ben nincs akció megadva, csak
	repository.

heads::
remotes::
	Kilistázza a megadott repository összes lokális, illetve összes
	remote-tracking branchét.
+
Az utóbbi alapértelmezés szerint nem elérhető, hacsak nincs
konfigurálva.

tags::
	Kilistázza a megadott repository összes tagjét (könnyűsúlyú és
	annotált egyaránt).

blob::
tree::
	Megjeleníti a megadott repository-útvonalon lévő fájlokat és
	könyvtárakat, a megadott revíziónál. Ez az alapértelmezett parancs,
	ha az URL-ben nincs akció megadva, és meg van adva útvonal.

blob_plain::
	Visszaadja a megadott repository-ban, a megadott útvonalon és
	revíziónál lévő fájl nyers adatait. Az erre az akcióra mutató linkek
	'raw'-ként vannak megjelölve.

blobdiff::
	Megjeleníti ugyanazon fájl két revíziója közötti különbséget.

blame::
blame_incremental::
	Megjeleníti egy fájl blame (más néven annotáció) információját.
	Soronkénti bontásban megmutatja, melyik revízióban változott utoljára
	az adott sor, és melyik felhasználó commitolta a változtatást. Az
	inkrementális verzió (amelyet, ha konfigurálva van, automatikusan
	használ a rendszer, ha a JavaScript engedélyezve van) Ajaxot használ
	a blame-információ fokozatos hozzáadásához a megadott fájl
	tartalmához.
+
Ez az akció teljesítményi okokból alapértelmezés szerint le van tiltva.

commit::
commitdiff::
	Információt jelenít meg egy repository-ban lévő adott commitról. A
	'commit' nézet részletesebb információt mutat a commitról, a
	'commitdiff' akció pedig a megadott commithoz tartozó changesetet
	jeleníti meg.

patch::
	Visszaadja a commitot sima szöveges mail-formátumban, amely
	alkalmas a linkgit:git-am[1]-mel való alkalmazásra.

tag::
	Megjeleníti a megadott annotált taget (tag-objektumot).

log::
shortlog::
	Naplóinformációt (commit-üzenetet vagy csak a commit tárgyát)
	jelenít meg egy adott branchhez (a megadott revíziótól kezdve).
+
A 'shortlog' nézet tömörebb; soronként egy commitot mutat.

history::
	Megjeleníti a megadott repository-útvonalon lévő fájl vagy
	könyvtár történetét, a megadott revíziótól kezdve (alapértelmezés
	szerint HEAD-től, azaz az alapértelmezett branchtől).
+
Ez a nézet hasonló a 'shortlog' nézethez.

rss::
atom::
	RSS- (vagy Atom-) feedet generál a repository változásairól.


WEBSERVER CONFIGURATION
-----------------------
Ez a szekció elmagyarázza, hogyan lehet néhány elterjedt webszervert
konfigurálni a gitweb futtatásához. Minden esetben a `/path/to/gitweb` a
példákban az a könyvtár, amelybe a gitwebet telepítetted, és amely
tartalmazza a `gitweb_config.perl`-t.

Ha olyan webszervert konfiguráltál a gitwebhez, amely itt nincs felsorolva,
kérjük, küldd el az utasításokat, hogy bekerülhessenek egy jövőbeli
kiadásba.

[[_apache_as_cgi]]
Apache CGI-ként
~~~~~~~~~~~~~~~
Az Apache-ot úgy kell konfigurálni, hogy támogassa a CGI szkripteket abban
a könyvtárban, amelybe a gitweb telepítve van. Tegyük fel, hogy ez a
`/var/www/cgi-bin` könyvtár.

-----------------------------------------------------------------------
ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"

<Directory "/var/www/cgi-bin">
    Options Indexes FollowSymlinks ExecCGI
    AllowOverride None
    Order allow,deny
    Allow from all
</Directory>
-----------------------------------------------------------------------

Ezzel a konfigurációval a repository-k böngészéséhez vezető teljes útvonal
a következő lenne:

  http://server/cgi-bin/gitweb.cgi

[[_apache_with_mod_perl_via_modperl_registry]]
Apache mod_perl-lel, a ModPerl::Registry-n keresztül
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A gitwebet mod_perl-lel is használhatod. Telepítened kell az
Apache::Registry-t (mod_perl 1.x esetén) vagy a ModPerl::Registry-t
(mod_perl 2.x esetén) ehhez a támogatáshoz.

Feltéve, hogy a gitweb a `/var/www/perl`-be van telepítve, a következő
Apache-konfiguráció (mod_perl 2.x esetén) megfelelő.

-----------------------------------------------------------------------
Alias /perl "/var/www/perl"

<Directory "/var/www/perl">
    SetHandler perl-script
    PerlResponseHandler ModPerl::Registry
    PerlOptions +ParseHeaders
    Options Indexes FollowSymlinks +ExecCGI
    AllowOverride None
    Order allow,deny
    Allow from all
</Directory>
-----------------------------------------------------------------------

Ezzel a konfigurációval a repository-k böngészéséhez vezető teljes útvonal
a következő lenne:

  http://server/perl/gitweb.cgi

[[_apache_with_fastcgi]]
Apache FastCGI-vel
~~~~~~~~~~~~~~~~~~
A gitweb működik Apache-csal és FastCGI-vel. Először át kell nevezned, le
kell másolnod, vagy symlinkelned kell a gitweb.cgi-t gitweb.fcgi-re.
Tegyük fel, hogy a gitweb a `/usr/share/gitweb` könyvtárba van telepítve.
A következő Apache-konfiguráció megfelelő (NEM TESZTELT!)

-----------------------------------------------------------------------
FastCgiServer /usr/share/gitweb/gitweb.cgi
ScriptAlias /gitweb /usr/share/gitweb/gitweb.cgi

Alias /gitweb/static /usr/share/gitweb/static
<Directory /usr/share/gitweb/static>
    SetHandler default-handler
</Directory>
-----------------------------------------------------------------------

Ezzel a konfigurációval a repository-k böngészéséhez vezető teljes útvonal
a következő lenne:

  http://server/gitweb


ADVANCED WEB SERVER SETUP
-------------------------
Mindegyik példa request rewritingot használ, és `mod_rewrite`-ot (vagy
azzal egyenértékűt) igényel; az alábbi példák Apache-hoz vannak írva.

[[_single_url_for_gitweb_and_for_fetching]]
Egyetlen URL a gitwebhez és a fetcheléshez
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ha egyetlen URL-t szeretnél mind a gitweb, mind a `http://`
repository-jaid számára, a következőképpen konfigurálhatod az Apache-ot:

-----------------------------------------------------------------------
<VirtualHost *:80>
    ServerName    git.example.org
    DocumentRoot  /pub/git
    SetEnv        GITWEB_CONFIG   /etc/gitweb.conf

    # turning on mod rewrite
    RewriteEngine on

    # make the front page an internal rewrite to the gitweb script
    RewriteRule ^/$  /cgi-bin/gitweb.cgi

    # make access for "dumb clients" work
    RewriteRule ^/(.*\.git/(?!/?(HEAD|info|objects|refs)).*)?$ \
		/cgi-bin/gitweb.cgi%{REQUEST_URI}  [L,PT]
</VirtualHost>
-----------------------------------------------------------------------

A fenti konfiguráció azt várja, hogy a nyilvános repository-jaid a
`/pub/git` alatt éljenek, és `http://git.domain.org/dir-under-pub-git`
formájában szolgálja ki őket, mind klónozható Git URL-ként, mind
böngészhető gitweb-felületként. Ha ezután elindítod a
linkgit:git-daemon[1]-et a `--base-path=/pub/git --export-all` opciókkal,
akkor akár a `git://` URL-t is használhatod pontosan ugyanezzel az
útvonallal.

A `GITWEB_CONFIG` környezeti változó beállítása közli a gitweb-bel, hogy a
megnevezett fájlt (azaz ebben a példában az `/etc/gitweb.conf`-ot)
használja konfigurációként. A fenti példában erre valójában nincs
szükséged; csak akkor kötelező, ha a konfigurációs fájlod máshol van, mint
a (gitweb fordítása során) beépített 'gitweb_config.perl' vagy
`/etc/gitweb.conf`. A részletekért, különösen az elsőbbségi szabályokkal
kapcsolatos információkért lásd a linkgit:gitweb.conf[5]-öt.

Ha a példabeli rewrite-szabályokat használod, *lehet*, hogy szükséged lesz
valami hasonlóra is a gitweb konfigurációs fájlodban (a fenti példát
követő `/etc/gitweb.conf`):

----------------------------------------------------------------------------
@stylesheets = ("/some/absolute/path/gitweb.css");
$my_uri    = "/";
$home_link = "/";
$per_request_config = 1;
----------------------------------------------------------------------------

Manapság azonban a gitwebnek szükség esetén létre kell hoznia egy HTML
base taget (a relatív linkek bázis-URI-jának beállításához), így ennek
automatikusan kell működnie.


[[_webserver_configuration_with_multiple_projects_root]]
Webszerver-konfiguráció több projekt-gyökérrel
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ha a gitwebet több projekt-gyökérrel szeretnéd használni, a következő
módon szerkesztheted az Apache virtuális host és a gitweb konfigurációs
fájljait.

A virtuális host konfigurációjának (az Apache konfigurációs fájljában) a
következőképpen kell kinéznie:

--------------------------------------------------------------------------
<VirtualHost *:80>
    ServerName    git.example.org
    DocumentRoot  /pub/git
    SetEnv        GITWEB_CONFIG  /etc/gitweb.conf

    # turning on mod rewrite
    RewriteEngine on

    # make the front page an internal rewrite to the gitweb script
    RewriteRule ^/$  /cgi-bin/gitweb.cgi  [QSA,L,PT]

    # look for a public_git directory in unix users' home
    # http://git.example.org/~<user>/
    RewriteRule ^/\~([^\/]+)(/|/gitweb.cgi)?$	/cgi-bin/gitweb.cgi \
		[QSA,E=GITWEB_PROJECTROOT:/home/$1/public_git/,L,PT]

    # http://git.example.org/+<user>/
    #RewriteRule ^/\+([^\/]+)(/|/gitweb.cgi)?$	/cgi-bin/gitweb.cgi \
		 [QSA,E=GITWEB_PROJECTROOT:/home/$1/public_git/,L,PT]

    # http://git.example.org/user/<user>/
    #RewriteRule ^/user/([^\/]+)/(gitweb.cgi)?$	/cgi-bin/gitweb.cgi \
		 [QSA,E=GITWEB_PROJECTROOT:/home/$1/public_git/,L,PT]

    # defined list of project roots
    RewriteRule ^/scm(/|/gitweb.cgi)?$ /cgi-bin/gitweb.cgi \
		[QSA,E=GITWEB_PROJECTROOT:/pub/scm/,L,PT]
    RewriteRule ^/var(/|/gitweb.cgi)?$ /cgi-bin/gitweb.cgi \
		[QSA,E=GITWEB_PROJECTROOT:/var/git/,L,PT]

    # make access for "dumb clients" work
    RewriteRule ^/(.*\.git/(?!/?(HEAD|info|objects|refs)).*)?$ \
		/cgi-bin/gitweb.cgi%{REQUEST_URI}  [L,PT]
</VirtualHost>
--------------------------------------------------------------------------

Itt a tényleges projekt-gyökeret a webszerver adja át a gitwebnek a
`GITWEB_PROJECT_ROOT` környezeti változón keresztül, ezért a következő
sort kell elhelyezned a gitweb konfigurációs fájljában (a fenti példában
az `/etc/gitweb.conf`-ban):

--------------------------------------------------------------------------
$projectroot = $ENV{'GITWEB_PROJECTROOT'} || "/pub/git";
--------------------------------------------------------------------------

*Megjegyzés*: ezt minden kéréshez be kell állítani, ezért vagy a
`$per_request_config`-nak hamisnak kell lennie, vagy a fentit be kell
tenni a `$per_request_config` által hivatkozott kódba;

Ezek a konfigurációk két dolgot tesznek lehetővé. Először is, a szerver
minden unix felhasználója (`<user>`) böngészheti a `~/public_git/`
alatt található gitweb Git repository-kat a következő url-lel:

  http://git.example.org/~<user>/

Ha ezt a funkciót nem szeretnéd a szervereden, egyszerűen távolítsd el a
második rewrite-szabályt.

Ha már használod a `mod_userdir`-t a virtuális hostodban, vagy nem
szeretnéd a \'~' karaktert első karakterként használni, egyszerűen
kommenteld ki vagy távolítsd el a második rewrite-szabályt, és
kommenteld ki a következők közül azt, amelyiket szeretnéd használni.

Másodszor, a `/pub/scm/` és a `/var/git/` alatt található repository-k
elérhetők lesznek a `http://git.example.org/scm/` és a
`http://git.example.org/var/` címeken keresztül. Tetszőleges számú
projekt-gyökeret hozzáadhatsz a harmadikhoz és negyedikhez hasonló
rewrite-szabályok felvételével.


[[_path_info_usage]]
PATH_INFO használata
~~~~~~~~~~~~~~~~~~~~
Ha a következő beállítással engedélyezed a PATH_INFO használatát a
gitwebben

----------------------------------------------------------------------------
$feature{'pathinfo'}{'default'} = [1];
----------------------------------------------------------------------------

a gitweb konfigurációs fájlodban, lehetőség van úgy beállítani a
szervered, hogy a következő formájú URL-eket fogyassza és állítsa elő:

  http://git.example.com/project.git/shortlog/sometag

azaz a 'gitweb.cgi' rész nélkül, az alábbihoz hasonló konfiguráció
használatával. Ez a konfiguráció azt feltételezi, hogy a
`/var/www/gitweb` a webszervered DocumentRootja, amely tartalmazza a
gitweb.cgi szkriptet és a kiegészítő statikus fájlokat (stíluslap,
favicon, JavaScript):

----------------------------------------------------------------------------
<VirtualHost *:80>
	ServerAlias git.example.com

	DocumentRoot /var/www/gitweb

	<Directory /var/www/gitweb>
		Options ExecCGI
		AddHandler cgi-script cgi

		DirectoryIndex gitweb.cgi

		RewriteEngine On
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteRule ^.* /gitweb.cgi/$0 [L,PT]
	</Directory>
</VirtualHost>
----------------------------------------------------------------------------

A rewrite-szabály garantálja, hogy a meglévő statikus fájlok megfelelően
kiszolgálásra kerülnek, míg minden más URL PATH_INFO paraméterként kerül
átadásra a gitwebnek.

*Vedd figyelembe*, hogy ebben az esetben nincs szükséged speciális
beállításokra a `@stylesheets`, `$my_uri` és `$home_link` számára, viszont
elveszíted a "dumb client" hozzáférést a projekted .git könyvtáraihoz (l.
az "Egyetlen URL a gitwebhez és a fetcheléshez" szekciót). Egy lehetséges
megoldás az utóbbira a következő: a projekt-gyökérkönyvtáradban (pl.
`/pub/git`) legyenek a projektek .git kiterjesztés *nélkül* elnevezve
(pl. `/pub/git/project` a `/pub/git/project.git` helyett), és az
Apache-ot a következőképpen konfiguráld:

----------------------------------------------------------------------------
<VirtualHost *:80>
	ServerAlias git.example.com

	DocumentRoot /var/www/gitweb

	AliasMatch ^(/.*?)(\.git)(/.*)?$ /pub/git$1$3
	<Directory /var/www/gitweb>
		Options ExecCGI
		AddHandler cgi-script cgi

		DirectoryIndex gitweb.cgi

		RewriteEngine On
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteRule ^.* /gitweb.cgi/$0 [L,PT]
	</Directory>
</VirtualHost>
----------------------------------------------------------------------------

A kiegészítő AliasMatch azt eredményezi, hogy

  http://git.example.com/project.git

nyers hozzáférést biztosít a projekt Git könyvtárához (hogy a projekt
klónozható legyen), míg

  http://git.example.com/project

felhasználóbarát gitweb-hozzáférést biztosít.

Ez a megoldás nem 100%-osan hibabiztos, abban az értelemben, hogy ha
valamelyik projektnek van egy `git/`-vel kezdődő nevű refje (branch, tag),
akkor az olyan útvonalak, mint

  http://git.example.com/project/command/abranch..git/abranch

404-es hibával fognak elbukni.


BUGS
----
Kérjük, a hibákat vagy funkciókéréseket a git@vger.kernel.org címre
jelentsd, az e-mail tárgyába a "gitweb" szót írva.

SEE ALSO
--------
linkgit:gitweb.conf[5], linkgit:git-instaweb[1]

`gitweb/README`, `gitweb/INSTALL`

GIT
---
A linkgit:git[1] csomag része
