gitworkflows(7)
===============

NAME
----
gitworkflows - Áttekintés az ajánlott munkafolyamatokról Gittel

SYNOPSIS
--------
[verse]
git *


DESCRIPTION
-----------

Ez a dokumentum megpróbálja leírni és megindokolni néhányat azokból a
munkafolyamat-elemekből, amelyeket magához a `git.git`-hez használnak.
Sok ötlet általánosan is alkalmazható, bár a teljes munkafolyamatra
ritkán van szükség kisebb, kevesebb embert érintő projekteknél.

Gyors hivatkozáshoz megfogalmazunk egy 'szabály'-halmazt, míg a próza
megpróbálja mindegyiket megindokolni. Ne vedd őket mindig szó szerint;
a tetteid jó indokait többre kell értékelned, mint az olyan
manpage-eket, mint ez.


SEPARATE CHANGES
----------------

Általános szabályként próbáld meg a változásaidat kis, logikus
lépésekre bontani, és mindegyiket commitolni. Konzisztensnek kell
lenniük, bármely későbbi committól függetlenül működniük kell, át kell
menniük a tesztkészleten, stb. Ez sokkal könnyebbé teszi az átnézési
folyamatot, a történetet pedig sokkal hasznosabbá a későbbi vizsgálathoz
és elemzéshez, például a linkgit:git-blame[1]-mel és a
linkgit:git-bisect[1]-tel.

Ennek elérése érdekében próbáld meg a munkádat a legelejétől fogva kis
lépésekre bontani. Mindig könnyebb néhány commitot összesquashelni, mint
egy nagy commitot többre bontani. Ne félj attól, hogy túl kicsi vagy
tökéletlen lépéseket teszel útközben. Később mindig visszamehetsz, és
szerkesztheted a commitokat a `git rebase --interactive`-val, mielőtt
publikálnád őket. A `git stash push --keep-index`-et használhatod arra,
hogy a tesztkészletet a többi nem commitolt változástól függetlenül
futtasd; lásd a linkgit:git-stash[1] EXAMPLES szakaszát.


MANAGING BRANCHES
-----------------

Két fő eszköz van, amely arra használható, hogy egy branch változásait
egy másikba is belefoglald: linkgit:git-merge[1] és
linkgit:git-cherry-pick[1].

A merge-eknek sok előnye van, így igyekszünk minél több problémát
pusztán merge-ekkel megoldani. A cherry-pickelés alkalmanként még mindig
hasznos; példáért lásd a "Merge-elés felfelé" részt lentebb.

A legfontosabb, hogy a merge-elés a branchek szintjén működik, míg a
cherry-pickelés a commitok szintjén. Ez azt jelenti, hogy egy merge
egyenlő könnyedséggel viheti át 1, 10 vagy 1000 commit változásait, ami
viszont azt jelenti, hogy a munkafolyamat sokkal jobban skálázódik nagy
számú hozzájáróra (és hozzájárulásra). A merge-eket könnyebb is
megérteni, mert egy merge commit egy „ígéret", hogy az összes szülőjéből
származó összes változás mostantól bele van foglalva.

Van persze egy kompromisszum: a merge-ek gondosabb branchkezelést
igényelnek. A következő alszakaszok tárgyalják a fontos pontokat.


[[_graduation]]
Előlépés
~~~~~~~~

Ahogy egy adott feature a kísérletitől a stabilig jut, a szoftver
megfelelő branchjei között is „előlép". A `git.git` a következő
'integrációs branch'-eket használja:

* a 'maint' azokat a commitokat követi, amelyeknek a következő
  „karbantartási kiadásba" kell kerülniük, azaz az utoljára kiadott
  stabil verzió frissítésébe;

* a 'master' azokat a commitokat követi, amelyeknek a következő kiadásba
  kell kerülniük;

* a 'next' a masterre való stabilitás szempontjából tesztelt topicok
  tesztbranchjének szánt.

Van egy negyedik hivatalos branch, amelyet kicsit másképp használnak:

* a 'seen' (a maintainer által látott patchek) egy integrációs branch
  olyan dolgokhoz, amelyek még nem egészen készek a bevonásra (lásd az
  "Integration Branches" részt lentebb).

A négy branch mindegyike általában a felette lévő közvetlen leszármazottja.

Fogalmilag a feature egy instabil branchen (általában 'next' vagy 'seen')
lép be, és „előlép" a 'master'-re a következő kiadáshoz, amint elég
stabilnak ítélik.


[[_merging_upwards]]
Merge-elés felfelé
~~~~~~~~~~~~~~~~~~

A fent tárgyalt „lefelé előlépés" azonban nem végezhető el tényleges
lefelé merge-eléssel, mivel az az instabil branch 'összes' változását a
stabilba merge-elné. Innen a következő:

.Merge-elés felfelé
[caption="Rule: "]
=====================================
Mindig a legrégebbi támogatott branchbe commitold a javításaidat,
amely igényli őket. Aztán (periodikusan) merge-eld az integrációs
brancheket felfelé egymásba.
=====================================

Ez a javítások nagyon kontrollált áramlását adja. Ha észreveszed, hogy
egy javítást pl. a 'master'-re alkalmaztál, amelyre a 'maint'-ben is
szükség van, cherry-pickelned kell azt (a linkgit:git-cherry-pick[1]
használatával) lefelé. Ez néhányszor előfordul, és nincs miért aggódni
miatta, hacsak nem csinálod nagyon gyakran.


[[_topic_branches]]
Topic branchek
~~~~~~~~~~~~~~

Bármely nem triviális feature megvalósításához több patchre lesz
szükség, és extra bugfixeket vagy fejlesztéseket kaphat az élettartama
során.

Ha mindent közvetlenül az integrációs branchekre commitolsz, az sok
problémához vezet: a rossz commitok nem vonhatók vissza, így egyenként
kell őket revertelni, ami zavaros történeteket és további
hibalehetőséget teremt, amikor elfelejted egy változáscsoport egy
részét visszavonni. A párhuzamos munka összekeveri a változásokat,
további zavart teremtve.

A "topic branchek" használata megoldja ezeket a problémákat. A név
elég magától értetődő, egy figyelmeztetéssel, amely a fenti "merge
felfelé" szabályból ered:

.Topic branchek
[caption="Rule: "]
=====================================
Csinálj egy oldalbranchet minden topichoz (feature, bugfix, ...).
Ágaztasd le a legrégebbi integrációs branchnél, amelybe végül merge-elni
akarod majd.
=====================================

Sok minden ekkor nagyon természetesen elvégezhető:

* Ahhoz, hogy a feature/bugfix bekerüljön egy integrációs branchbe,
  egyszerűen merge-eld. Ha a topic időközben tovább fejlődött, merge-eld
  újra. (Vedd figyelembe, hogy nem feltétlenül kell először a
  legrégebbi integrációs branchbe merge-elned. Például először
  merge-elhetsz egy bugfixet a 'next'-be, adhatsz neki egy kis
  teszidőt, és merge-elheted a 'maint'-be, amikor tudod, hogy stabil.)

* Ha úgy találod, hogy új feature-ökre van szükséged az 'other' branchből
  ahhoz, hogy folytasd a munkát a topicodon, merge-eld az 'other'-t a
  'topic'-ba. (Ezt azonban ne csináld "csak megszokásból", lásd
  lentebb.)

* Ha úgy találod, hogy rossz branchről ágaztál le, és "vissza akarod
  mozgatni az időben", használd a linkgit:git-rebase[1]-et.

Vedd figyelembe, hogy az utolsó pont ütközik a másik kettővel: egy
topicot, amelyet máshová már merge-eltek, nem szabad rebase-elni. Lásd a
RECOVERING FROM UPSTREAM REBASE szakaszt a linkgit:git-rebase[1]-ben.

Rá kell mutatnunk, hogy "megszokásból" (rendszeresen, valódi ok nélkül)
egy integrációs branchet a topicjaidba merge-elni -- és kiterjesztve,
bármi upstreamet bármi downstreambe rendszeresen merge-elni -- rossz
szemmel néznek:

.Downstreambe csak jól definiált pontokon merge-elj
[caption="Rule: "]
=====================================
Ne merge-elj downstreambe, kivéve jó okkal: az upstream API-változásai
érintik a branchedet; a branched már nem merge-elődik tisztán az
upstreambe; stb.
=====================================

Egyébként az a topic, amelybe merge-eltek, hirtelen egynél több
(jól elkülönített) változást tartalmaz. A sok ebből eredő kis merge
nagyban összezavarja a történetet. Bárkinek, aki később egy fájl
történetét vizsgálja, ki kell derítenie, hogy az a merge érintette-e a
fejlesztés alatt álló topicot. Egy upstream akár véletlenül is
merge-elődhet egy "stabilabb" branchbe. És így tovább.


[[_throw_away_integration]]
Eldobható integráció
~~~~~~~~~~~~~~~~~~~~

Ha követted az utolsó bekezdést, most sok kis topic branched lesz, és
alkalmanként eltűnődsz, hogyan hatnak egymásra. Talán a merge-elésük
eredménye nem is működik? De másrészről el akarjuk kerülni, hogy bárhová
"stabilba" merge-eljük őket, mert az ilyen merge-ek nem vonhatók vissza
könnyen.

A megoldás persze az, hogy olyan merge-et csinálunk, amelyet vissza
tudunk vonni: merge-elés egy eldobható branchbe.

.Eldobható integrációs branchek
[caption="Rule: "]
=====================================
Több topic kölcsönhatásának teszteléséhez merge-eld őket egy eldobható
branchbe. Soha nem szabad semmilyen munkát ilyen branchre alapoznod!
=====================================

Ha (nagyon) egyértelművé teszed, hogy ezt a branchet a tesztelés után
rögtön törölni fogják, akár publikálhatod is ezt a branchet, például
hogy a tesztelőknek esélyt adj a vele való munkára, vagy más
fejlesztőknek esélyt, hogy lássák, a folyamatban lévő munkájuk
kompatibilis lesz-e. A `git.git`-nek van egy ilyen hivatalos eldobható
integrációs branchje, amelynek a neve 'seen'.


[[_branch_management_for_a_release]]
Branchkezelés egy kiadáshoz
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Feltételezve, hogy a fent tárgyalt merge-megközelítést használod,
amikor kiadod a projekted, néhány további branchkezelési munkát kell
végezned.

Egy feature kiadás a 'master' branchből jön létre, mivel a 'master'
azokat a commitokat követi, amelyeknek a következő feature kiadásba kell
kerülniük.

A 'master' branch elvileg a 'maint' szuperhalmaza. Ha ez a feltétel nem
áll fenn, akkor a 'maint' tartalmaz néhány olyan commitot, amely nincs
benne a 'master'-en. Az ezekkel a commitokkal képviselt javítások tehát
nem lesznek benne a feature kiadásodban.

Annak ellenőrzéséhez, hogy a 'master' valóban a 'maint' szuperhalmaza,
használd a git logot:

.Ellenőrizd, hogy a 'master' a 'maint' szuperhalmaza
[caption="Recipe: "]
=====================================
`git log master..maint`
=====================================

Ennek a parancsnak nem szabad egyetlen commitot sem listáznia.
Egyébként checkoutold a 'master'-t, és merge-eld bele a 'maint'-et.

Most folytathatod a feature kiadás létrehozásával. Alkalmazz egy taget a
'master' csúcsára, amely jelzi a kiadás verzióját:

.Kiadás-tagelés
[caption="Recipe: "]
=====================================
`git tag -s -m "Git X.Y.Z" vX.Y.Z master`
=====================================

Az új taget egy nyilvános Git-szerverre kell pusholnod (lásd a
"DISTRIBUTED WORKFLOWS" részt lentebb). Ez elérhetővé teszi a taget
másoknak, akik a projektedet követik. A push egy post-update hookot is
kiválthat, hogy kiadással kapcsolatos dolgokat végezzen, mint a kiadási
tarballok és az előformázott dokumentációoldalak építése.

Hasonlóképp egy karbantartási kiadáshoz a 'maint' követi a kiadandó
commitokat. Ezért a fenti lépésekben egyszerűen a 'maint'-et tageld és
pushold a 'master' helyett.


[[_maintenance_branch_management_after_a_feature_release]]
Karbantartási branchkezelés egy feature kiadás után
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Egy feature kiadás után kezelned kell a karbantartási brancheidet.

Először, ha továbbra is szeretnél karbantartási javításokat kiadni a
legutóbbi előtt készült feature kiadáshoz, akkor létre kell hoznod egy
másik branchet, hogy kövesse az adott korábbi kiadás commitjait.

Ehhez az aktuális karbantartási branch átmásolódik egy másik branchbe,
amely a korábbi kiadás verziószámával van elnevezve (pl.
maint-X.Y.(Z-1), ahol X.Y.Z az aktuális kiadás).

.A maint másolása
[caption="Recipe: "]
=====================================
`git branch maint-X.Y.(Z-1) maint`
=====================================

A 'maint' branchet most fast-forwardolni kell az újonnan kiadott kódra,
hogy a karbantartási javítások követhetők legyenek az aktuális
kiadáshoz:

.A maint frissítése az új kiadásra
[caption="Recipe: "]
=====================================
* `git checkout maint`
* `git merge --ff-only master`
=====================================

Ha a merge meghiúsul, mert nem fast-forward, akkor lehetséges, hogy
néhány javítás a 'maint'-en kimaradt a feature kiadásból. Ez nem
történik meg, ha a branchek tartalmát az előző szakaszban leírtak
szerint ellenőrizték.


[[_branch_management_for_next_and_seen_after_a_feature_release]]
A next és a seen branchkezelése egy feature kiadás után
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Egy feature kiadás után az integrációs branch 'next' opcionálisan
visszatekerhető és újraépíthető a 'master' csúcsáról a 'next'-en
túlélő topicok használatával:

.A next visszatekerése és újraépítése
[caption="Recipe: "]
=====================================
* `git switch -C next master`
* `git merge ai/topic_in_next1`
* `git merge ai/topic_in_next2`
* ...
=====================================

Ennek az az előnye, hogy a 'next' története tiszta lesz. Például
néhány, a 'next'-be merge-elt topic kezdetben ígéretesnek tűnhetett, de
később nemkívánatosnak vagy korainak bizonyult. Ilyen esetben a topicot
kirevertelik a 'next'-ből, de a történetben megmarad a tény, hogy egykor
merge-elték és revertelték. A 'next' újraalkotásával az ilyen topicok
egy másik megtestesülésének tiszta lapot adsz az újrapróbálkozáshoz, és
egy feature kiadás jó pont a történetben ehhez.

Ha ezt megteszed, akkor nyilvános bejelentést kell tenned, amely jelzi,
hogy a 'next'-et visszatekerték és újraépítették.

Ugyanez a visszatekerési és újraépítési folyamat követhető a 'seen'
esetén is. Nyilvános bejelentésre nincs szükség, mivel a 'seen' egy
eldobható branch, ahogy fentebb leírtuk.


DISTRIBUTED WORKFLOWS
---------------------

Az utolsó szakasz után tudnod kell, hogyan kezeld a topicokat.
Általában nem te leszel az egyetlen személy, aki a projekten dolgozik,
így meg kell osztanod a munkádat.

Nagyjából két fontos munkafolyamat van: a merge és a patch. A fontos
különbség, hogy a merge-munkafolyamat teljes történetet tud
propagálni, a merge-eket is beleértve, míg a patchek nem. Mindkét
munkafolyamat használható párhuzamosan: a `git.git`-ben csak az
alrendszer-maintainerek használják a merge-munkafolyamatot, míg mindenki
más patcheket küld.

Vedd figyelembe, hogy a maintainer(ek) korlátozásokat írhatnak elő, mint
a "Signed-off-by" követelmények, amelyekhez minden bevonásra beküldött
commitnak/patchnek igazodnia kell. További információért nézd meg a
projekted dokumentációját.


[[_merge_workflow]]
Merge-munkafolyamat
~~~~~~~~~~~~~~~~~~~

A merge-munkafolyamat úgy működik, hogy brancheket másol az upstream és
a downstream között. Az upstream a hivatalos történetbe merge-elheti a
hozzájárulásokat; a downstream a hivatalos történetre alapozza a
munkáját.

Három fő eszköz van, amely erre használható:

* linkgit:git-push[1] a brancheidet egy remote repository-ba másolja,
  általában egy olyanba, amelyet minden érintett fél olvashat;

* linkgit:git-fetch[1], amely a remote brancheket a repository-dba
  másolja; és

* linkgit:git-pull[1], amely a fetchet és a merge-et egy menetben
  végzi.

Figyelj az utolsó pontra. 'Ne' használd a 'git pull'-t, hacsak nem
tényleg merge-elni akarod a remote branchet.

A változások kijuttatása egyszerű:

.Push/pull: Branchek/topicok publikálása
[caption="Recipe: "]
=====================================
`git push <remote> <branch>`, és mondd meg mindenkinek, honnan
fetchelhetnek.
=====================================

Az embereket még mindig más módon kell értesítened, például
e-mailben. (A Git biztosítja a linkgit:git-request-pull[1]-t
előformázott pull requestek küldésére az upstream maintainereknek, hogy
egyszerűsítse ezt a feladatot.)

Ha csak az integrációs branchek legfrissebb másolatait akarod megkapni,
a naprakészen maradás is egyszerű:

.Push/pull: Naprakészen maradás
[caption="Recipe: "]
=====================================
Használd a `git fetch <remote>`-ot vagy a `git remote update`-et a
naprakészen maradáshoz.
=====================================

Aztán egyszerűen ágaztasd le a topic brancheidet a stabil remote-okról,
ahogy korábban elmagyaráztuk.

Ha maintainer vagy, és mások topic branchjeit szeretnéd az integrációs
branchekbe merge-elni, jellemzően e-mailben küldenek erre kérést. Egy
ilyen kérés így néz ki

-------------------------------------
Please pull from
    <URL> <branch>
-------------------------------------

Ebben az esetben a 'git pull' egy menetben végezheti a fetchet és a
merge-et, a következőképp.

.Push/pull: Remote topicok merge-elése
[caption="Recipe: "]
=====================================
`git pull <URL> <branch>`
=====================================

Alkalmanként a maintainer merge-konfliktusokat kaphat, amikor
megpróbálja pull-olni a downstream változásait. Ebben az esetben
megkérheti a downstreamet, hogy ő maga végezze el a merge-et, és oldja
fel a konfliktusokat (talán jobban tudja, hogyan kell feloldani őket).
Ez azon ritka esetek egyike, amikor a downstreamnek 'kellene'
upstreamből merge-elnie.


[[_patch_workflow]]
Patch-munkafolyamat
~~~~~~~~~~~~~~~~~~~

Ha olyan hozzájáruló vagy, aki e-mailek formájában küld változásokat
upstreamnek, a szokásos módon kell topic brancheket használnod (lásd
fent). Aztán használd a linkgit:git-format-patch[1]-et a megfelelő
e-mailek generálásához (erősen ajánlott a kézi formázással szemben, mert
megkönnyíti a maintainer életét).

.format-patch/am: Branchek/topicok publikálása
[caption="Recipe: "]
=====================================
* `git format-patch -M upstream..topic`, hogy előformázott
  patch-fájlokká alakítsd őket
* `git send-email --to=<recipient> <patches>`
=====================================

További használati megjegyzésekért lásd a linkgit:git-format-patch[1] és
a linkgit:git-send-email[1] manpage-eket.

Ha a maintainer közli veled, hogy a patched már nem alkalmazható az
aktuális upstreamre, rebase-elned kell a topicodat (nem használhatsz
merge-et, mert a merge-eket nem lehet format-patchelni):

.format-patch/am: Topicok naprakészen tartása
[caption="Recipe: "]
=====================================
`git pull --rebase <URL> <branch>`
=====================================

Ekkor a rebase során javíthatod a konfliktusokat. Feltehetően nem
publikáltad a topicodat e-mailen kívül máshogy, így a rebase-elése nem
probléma.

Ha ilyen patch-sorozatot kapsz (maintainerként, vagy talán a
levelezőlista olvasójaként, amelyre küldték), mentsd a leveleket
fájlokba, hozz létre egy új topic branchet, és használd a 'git am'-et a
commitok importálásához:

.format-patch/am: Patchek importálása
[caption="Recipe: "]
=====================================
`git am < patch`
=====================================

Egy említésre méltó feature a háromutas merge, amely segíthet, ha
konfliktusokat kapsz: a `git am -3` a patchekben lévő indexinformációt
használja a merge-alap kiderítésére. Más kapcsolókért lásd:
linkgit:git-am[1].


SEE ALSO
--------
linkgit:gittutorial[7],
linkgit:git-push[1],
linkgit:git-pull[1],
linkgit:git-merge[1],
linkgit:git-rebase[1],
linkgit:git-format-patch[1],
linkgit:git-send-email[1],
linkgit:git-am[1]

GIT
---
A linkgit:git[1] csomag része
