A Git bizonyos mértékig karakterkódolás-független.

 - A blob objektumok tartalma értelmezetlen bájtsorozat. A core
   szinten nincs kódolás-átalakítás.

 - Az útvonalnevek UTF-8 C normalizálási formában vannak kódolva.
   Ez vonatkozik a tree objektumokra, az indexfájlra, a
   referencianevekre, valamint a parancssori argumentumokban,
   környezeti változókban és konfigurációs fájlokban
   (`.git/config` (lásd linkgit:git-config[1]),
   linkgit:gitignore[5], linkgit:gitattributes[5] és
   linkgit:gitmodules[5]) szereplő útvonalnevekre.
+
Vedd figyelembe, hogy a Git a core szinten az útvonalneveket
egyszerűen nem-NUL bájtok sorozataként kezeli, nincs
útvonalnév-kódolás átalakítás (a Mac és a Windows kivételével).
Ezért a nem ASCII útvonalnevek használata többnyire működik még
olyan platformokon és fájlrendszereken is, amelyek régi,
kiterjesztett ASCII kódolást használnak. Az ilyen rendszereken
létrehozott repository-k azonban nem működnek megfelelően UTF-8
alapú rendszereken (pl. Linux, Mac, Windows), és fordítva.
Ezenkívül sok Git-alapú eszköz egyszerűen UTF-8-nak feltételezi
az útvonalneveket, és nem képes helyesen megjeleníteni más
kódolásokat.

 - A commit napló-üzenetek jellemzően UTF-8 kódolásúak, de más
   kiterjesztett ASCII kódolások is támogatottak. Ide tartozik az
   ISO-8859-x, a CP125x és sok más, de _nem_ az UTF-16/32, az
   EBCDIC és a CJK több bájtos kódolások (GBK, Shift-JIS, Big5,
   EUC-x, CP9xx stb.).

Bár azt javasoljuk, hogy a commit napló-üzenetek UTF-8 kódolásúak
legyenek, mind a core, mind a Git Porcelain úgy készült, hogy ne
kényszerítse az UTF-8-at a projektekre. Ha egy adott projekt
összes résztvevője kényelmesebbnek találja a régi kódolások
használatát, a Git nem tiltja azt. Néhány dolgot azonban érdemes
szem előtt tartani.

. A `git commit` és a `git commit-tree` figyelmeztetést ad, ha a
  neki átadott commit napló-üzenet nem tűnik érvényes UTF-8
  karakterláncnak, hacsak nem mondod meg kifejezetten, hogy a
  projekted régi kódolást használ. Ezt úgy közölheted, hogy az
  `i18n.commitEncoding` szerepel a `.git/config` fájlban, így:
+
------------
[i18n]
	commitEncoding = ISO-8859-1
------------
+
A fenti beállítással létrehozott commit-objektumok az
`i18n.commitEncoding` értékét az `encoding` fejlécükben rögzítik.
Ez azért van, hogy segítsen másoknak, akik később megnézik őket.
A fejléc hiánya azt jelenti, hogy a commit napló-üzenet UTF-8
kódolású.

. A `git log`, a `git show`, a `git blame` és társaik egy
  commit-objektum `encoding` fejlécét nézik, és megpróbálják a
  napló-üzenetet UTF-8-ra átkódolni, hacsak nincs másképp megadva.
  A kívánt kimeneti kódolást az `i18n.logOutputEncoding`
  segítségével adhatod meg a `.git/config` fájlban, így:
+
------------
[i18n]
	logOutputEncoding = ISO-8859-1
------------
+
Ha ez a konfigurációs változó nincs beállítva, helyette az
`i18n.commitEncoding` értéke lesz felhasználva.

Vedd figyelembe, hogy szándékosan úgy döntöttünk, hogy nem
kódoljuk át a commit napló-üzenetet a commit létrehozásakor
azért, hogy UTF-8-at kényszerítsünk a commit-objektum szintjén,
mert az UTF-8-ra való átkódolás nem feltétlenül visszafordítható
művelet.
