MERGE STRATEGIES
----------------

A merge-mechanizmus (`git merge` és `git pull` parancsok) lehetővé teszi a
háttérben lévő 'merge-stratégiák' kiválasztását a `-s` opcióval.  Egyes
stratégiák saját opciókat is elfogadnak, amelyek `-X<option>`
argumentumokként adhatók át a `git merge`-nek és/vagy a `git pull`-nak.

`ort`::
	Ez az alapértelmezett merge-stratégia egyetlen branch pull-olásakor
	vagy merge-elésekor.  Ez a stratégia csak két headet tud feloldani
	háromutas merge-algoritmussal.  Ha egynél több közös ős van, amely
	használható háromutas merge-hez, létrehozza a közös ősök merge-elt
	tree-jét, és azt használja referencia-tree-ként a háromutas merge-hez.
	A Linux 2.6 kernelfejlesztési előzményeiből vett valódi
	merge-commitokon végzett tesztek szerint ez kevesebb
	merge-konfliktust eredményez anélkül, hogy hibás merge-eket okozna.
	Ezenkívül ez a stratégia képes az átnevezéseket érintő merge-ek
	észlelésére és kezelésére.  Nem használja fel az észlelt másolatokat.
	Az algoritmus neve egy betűszó ("Ostensibly Recursive's Twin"), és
	abból ered, hogy a korábbi alapértelmezett algoritmus, a `recursive`
	helyettesítésére íródott.
+
Abban az esetben, ha az útvonal egy submodule, és a merge egyik oldalán
használt submodule-commit a merge másik oldalán használt submodule-commit
leszármazottja, a Git megpróbál fast-forwardolni a leszármazottra.
Egyébként a Git ezt az esetet konfliktusként kezeli, feloldásként egy
olyan submodule-commitot javasolva, amely a konfliktusban lévők
leszármazottja, ha van ilyen.
+
Az `ort` stratégia a következő opciókat fogadja el:

`ours`;;
	Ez az opció kikényszeríti a konfliktusos hunkok tiszta automatikus
	feloldását a 'mi' verziónk előnyben részesítésével.  A másik tree azon
	változtatásai, amelyek nem konfliktálnak a mi oldalunkkal, megjelennek
	a merge eredményében.  Bináris fájl esetén a teljes tartalom a mi
	oldalunkról származik.
+
Ezt nem szabad összekeverni az `ours` merge-stratégiával, amely egyáltalán
meg sem nézi, hogy a másik tree mit tartalmaz.  Eldob mindent, amit a másik
tree tett, kijelentve, hogy a 'mi' előzményünk mindent tartalmaz, ami benne
történt.

`theirs`;;
	Ez az `ours` ellentéte; vedd figyelembe, hogy az `ours`-szal
	ellentétben nincs `theirs` merge-stratégia, amellyel össze lehetne
	keverni ezt a merge-opciót.

`ignore-space-change`;;
`ignore-all-space`;;
`ignore-space-at-eol`;;
`ignore-cr-at-eol`;;
	A jelzett típusú whitespace-változtatást tartalmazó sorokat
	változatlannak tekinti a háromutas merge szempontjából.  A sorok más
	változtatásaival keveredő whitespace-változtatások nem maradnak
	figyelmen kívül.  Lásd még a linkgit:git-diff[1] `-b`, `-w`,
	`--ignore-space-at-eol` és `--ignore-cr-at-eol` opcióit.
+
* Ha az 'ő' verziójuk csak whitespace-változtatásokat vezet be egy
  sorba, a 'mi' verziónk használatos;
* Ha a 'mi' verziónk whitespace-változtatásokat vezet be, de az 'ő'
  verziójuk lényegi változtatást tartalmaz, az 'ő' verziójuk használatos;
* Egyébként a merge a szokásos módon folytatódik.

`renormalize`;;
	Ez virtuális check-outot és check-int futtat minden olyan fájl
	mindhárom fázisára, amely háromutas merge-t igényel.  Ezt az opciót
	akkor érdemes használni, amikor eltérő clean filterekkel vagy
	sorvég-normalizálási szabályokkal rendelkező brancheket merge-elsz.
	A részletekért l. a "Merging branches with differing checkin/checkout
	attributes" szakaszt a linkgit:gitattributes[5]-ben.

`no-renormalize`;;
	Kikapcsolja a `renormalize` opciót.  Ez felülbírálja a
	`merge.renormalize` konfigurációs változót.

`find-renames[=<n>]`;;
	Bekapcsolja az átnevezés-észlelést, opcionálisan beállítva a
	hasonlósági küszöböt.  Ez az alapértelmezett. Ez felülbírálja a
	`merge.renames` konfigurációs változót.
	Lásd még a linkgit:git-diff[1] `--find-renames` opcióját.

`rename-threshold=<n>`;;
	Elavult szinonimája a `find-renames=<n>`-nek.

`no-renames`;;
	Kikapcsolja az átnevezés-észlelést. Ez felülbírálja a `merge.renames`
	konfigurációs változót.
	Lásd még a linkgit:git-diff[1] `--no-renames` opcióját.

`histogram`;;
	Elavult szinonimája a `diff-algorithm=histogram`-nak.

`patience`;;
	Elavult szinonimája a `diff-algorithm=patience`-nek.

`diff-algorithm=(histogram|minimal|myers|patience)`;;
	Eltérő diff-algoritmus használata a merge során, ami segíthet
	elkerülni azokat a hibás merge-eket, amelyek lényegtelen illeszkedő
	sorok (például különböző függvények kapcsos zárójelei) miatt
	fordulnak elő.  Lásd még a linkgit:git-diff[1] `--diff-algorithm`
	opcióját.  Vedd figyelembe, hogy az `ort` alapból
	`diff-algorithm=histogram`-ot használ, míg a szokásos diffek jelenleg
	alapból a `diff.algorithm` config-beállítást.

`subtree[=<path>]`;;
	Ez az opció a 'subtree' stratégia fejlettebb formája, ahol a stratégia
	tippet ad arra, hogy merge-eléskor hogyan kell a két tree-t
	eltolni, hogy illeszkedjenek egymáshoz.  Ehelyett a megadott útvonal
	kerül elő (vagy le az elejéről), hogy a két tree alakja illeszkedjen.

`recursive`::
	Ez most az `ort` szinonimája.  A v2.49.0-ig alternatív
	implementáció volt, de a v2.50.0-ban átirányításra került, hogy az
	`ort`-ot jelentse.  A korábbi recursive stratégia volt az
	alapértelmezett stratégia két head feloldásához a Git v0.99.9k-tól a
	v2.33.0-ig.

`resolve`::
	Ez csak két headet tud feloldani (azaz az aktuális branchet és egy
	másik branchet, amelyből pull-oltál) háromutas merge-algoritmussal.
	Gondosan megpróbálja észlelni a keresztirányú merge-kétértelműségeket.
	Az átnevezéseket nem kezeli.

`octopus`::
	Ez a kettőnél több headet tartalmazó eseteket oldja fel, de
	megtagadja az olyan összetett merge-et, amely kézi feloldást igényel.
	Elsősorban topic branchek headjeinek összekötegelésére szolgál.  Ez az
	alapértelmezett merge-stratégia egynél több branch pull-olásakor vagy
	merge-elésekor.

`ours`::
	Ez tetszőleges számú headet feloldja, de a merge eredményül kapott
	tree-je mindig az aktuális branch headjéé, gyakorlatilag figyelmen
	kívül hagyva minden más branch minden változtatását.  Az oldalági
	branchek régi fejlesztési előzményeinek felváltására szolgál.  Vedd
	figyelembe, hogy ez különbözik az `ort` merge-stratégia `-Xours`
	opciójától.

`subtree`::
	Ez egy módosított `ort` stratégia. Amikor az A és a B tree-t
	merge-eled, ha B az A egy subtree-jének felel meg, B-t először
	hozzáigazítja az A tree-szerkezetéhez, ahelyett, hogy a tree-ket
	azonos szinten olvasná.  Ez az igazítás a közös ős tree-jén is
	megtörténik.

A háromutas merge-t használó stratégiáknál (beleértve az alapértelmezett
`ort`-ot is), ha mindkét branchen elvégeznek egy változtatást, de később az
egyik branchen visszavonják, az a változtatás jelen lesz a merge-elt
eredményben; egyesek zavarónak találják ezt a viselkedést.  Azért fordul
elő, mert a merge végrehajtásakor csak a headeket és a merge-alapot veszik
figyelembe, nem az egyes commitokat.  A merge-algoritmus ezért a visszavont
változtatást egyáltalán nem tekinti változtatásnak, és helyette a
megváltoztatott verziót teszi be.
