= Az első objektumbejárásom

[[_what_s_an_object_walk]]
== Mi az az objektumbejárás?

Az objektumbejárás (object walk) a Git egyik kulcsfogalma - ez az a folyamat,
amely olyan műveletek alapját képezi, mint az objektumátvitel és az fsck. Egy
adott commitból kiindulva az objektumok listáját a commitok közötti szülő-kapcsolatok
bejárásával (X commit a W commitra épül) és az objektumok közötti tartalmazási
kapcsolatok bejárásával (Y tree benne foglaltatik X commitban, Z blob pedig
Y tree-n belül található, ami az X commithoz tartozó munkakönyvtárban valami
ilyesmit ad, mint `y/z.txt`) találjuk meg.

Ehhez kapcsolódó fogalom a revízióbejárás (revision walk), amely a commit
objektumokra és azok szülő-kapcsolataira fókuszál, más objektumtípusokba nem
megy bele. A revízióbejárást olyan műveletek használják, mint a `git log`.

[[_related_reading]]
=== Kapcsolódó olvasmányok

- A `Documentation/user-manual.adoc` "Hacking Git" című része a revízióbejáró
  (revision walker) különböző megvalósításait is részben tárgyalja.
- `revision.h`
- A https://eagain.net/articles/git-for-computer-scientists/[Git for Computer Scientists]
  jó áttekintést ad a Git objektumtípusairól, és arról, hogy mit is ír le
  valójában az objektumbejárásod.

[[_setting_up]]
== Beállítás

Hozz létre egy új branchet a `master`-ből.

----
git checkout -b revwalk origin/master
----

A kísérletezésünket egy új parancsba tesszük. A viccesség kedvéért nevezzük el
`git walken`-nek. Nyiss meg egy új `builtin/walken.c` fájlt, és állítsd be a
parancskezelőt:

----
/*
 * "git walken"
 *
 * Part of the "My First Object Walk" tutorial.
 */

#include "builtin.h"
#include "trace.h"

int cmd_walken(int argc, const char **argv, const char *prefix, struct repository *repo)
{
	trace_printf(_("cmd_walken incoming...\n"));
	return 0;
}
----

NOTE: A `trace.h`-ban definiált `trace_printf()` abban különbözik a `printf()`-től,
hogy futásidőben be- és kikapcsolható. Ennek az oktatóanyagnak a keretében úgy
írjuk meg a `walken`-t, mintha "plumbing" (alacsonyszintű) parancsként szánnánk
használatra: vagyis olyan parancsként, amelyet elsősorban szkriptek használnak,
nem pedig emberek interaktívan ("porcelain" (magasszintű) parancs). Ezért a
debug kimenetünket a `trace_printf()`-nek küldjük. Futtatáskor a `GIT_TRACE`
környezeti változó beállításával kapcsolhatod be a trace-kimenetet.

Adj hozzá használati szöveget és `-h` kezelést, ahogy minden alparancsnak
következetesen tennie kell (a tesztkészletünk észreveszi és panaszkodik, ha ezt
elmulasztod). Be kell includeolnunk a `parse-options.h` headert.

----
#include "parse-options.h"

...

int cmd_walken(int argc, const char **argv, const char *prefix)
{
	const char * const walken_usage[] = {
		N_("git walken"),
		NULL,
	};
	struct option options[] = {
		OPT_END()
	};

	argc = parse_options(argc, argv, prefix, options, walken_usage, 0);

	...
}
----

Vedd fel a megfelelő sort a `builtin.h`-ban is, a `cmd_version()` közelében:

----
int cmd_walken(int argc, const char **argv, const char *prefix, struct repository *repo);
----

Vedd fel a parancsot a `git.c`-ben a `commands[]`-ban, a `version` bejegyzése
mellé, megtartva az ábécésorrendet:

----
{ "walken", cmd_walken, RUN_SETUP },
----

Vegyél fel egy bejegyzést az új parancshoz mind a Make, mind a Meson build
rendszerben, a `worktree` bejegyzése előtt:

- A `Makefile`-ban:
----
...
BUILTIN_OBJS += builtin/walken.o
...
----

- A `meson.build` fájlban:
----
builtin_sources = [
   ...
  'builtin/walken.c',
   ...
]
----

Buildeld és teszteld le a parancsodat, arról sem megfeledkezve, hogy a
`DEVELOPER` flag be legyen állítva, és a `GIT_TRACE` engedélyezve legyen, hogy
lásd a debug kimenetet:

----
$ echo DEVELOPER=1 >>config.mak
$ make
$ GIT_TRACE=1 ./bin-wrappers/git walken
----

NOTE: Az új parancs felvételének folyamatáról bővebb áttekintést a
`Documentation/MyFirstContribution.adoc`-ban találsz.

NOTE: Egy referenciaimplementáció megtalálható itt:
https://github.com/nasamuffin/git/tree/revwalk.

[[_struct_rev_cmdline_info]]
=== `struct rev_cmdline_info`

A `struct rev_cmdline_info` definíciója a `revision.h`-ban található.

Ez a struct a `rev_info` structon belül helyezkedik el, és a felhasználó által
a parancssoron megadott paramétereket tükrözi.

Az `nr` a tömbben jelen lévő `rev_cmdline_entry` elemek számát jelöli.

Az `alloc`-ot az `ALLOC_GROW` makró használja. Nézd meg az `alloc.h`-t - ez a
változó a lista allokált méretét követi.

Bejegyzésenként a következőket találjuk:

Az `item` az az objektum, amelyre az objektumbejárás alapul. A Git-ben az
elemek lehetnek blobok, tree-k, commitok vagy tagek. (Lásd:
`Documentation/gittutorial-2.adoc`.)

A `name` az objektum objektumazonosítója (OID) - egy hex string, amelyet talán
már ismersz onnan, hogy a Git-et korábban a forrásod rendszerezésére
használtad. A fent, az elején említett oktatóanyagban találsz egy áttekintést
arról, hogy honnan származhat az OID.

A `whence` némi információt jelez arról, hogy mit kell tenni a megadott
objektum szüleivel. Ezt a flaget később bővebben is megvizsgáljuk; nézd meg a
`Documentation/revisions.adoc`-ot, hogy képet kapj arról, mi állíthatja be a
`whence` értékét.

A `flags` a revízióbejárás kezdetének jelzésére szolgál, és ez az első blokk a
`revision.h`-ban lévő `#include`-ok alatt. A `rev_cmdline_info`-ban
legvalószínűbben beállított flagek az `UNINTERESTING` és a `BOTTOM`, de
ugyanezek a flagek a bejárás során is használhatók.

[[_struct_rev_info]]
=== `struct rev_info`

Ez jóval hosszabb, és sok mezőt csak a bejárás közben használ a `revision.c`
- nem konfigurációs opciók ezek. A `struct rev_info`-ban lévő konfigurálható
flagek többségének van megfelelője a `Documentation/rev-list-options.adoc`-ban.
Érdemes rászánni egy kis időt, hogy végigolvasd azt a dokumentumot.

[[_basic_commit_walk]]
== Alap commit-bejárás

Először nézzük meg, hogy le tudjuk-e reprodukálni a `git log --oneline`
kimenetét. Gyakran vissza fogunk hivatkozni erre az implementációra, hogy
felfedezzük a normákat egy saját objektumbejárás elvégzésekor.

Ehhez először sorrendben megkeressük az összes commitot, amely a jelenlegi
commit előtt volt. Mindegyikből kinyerjük a commit nevét és tárgyát.

Ideális esetben azt is ki tudjuk majd deríteni, melyek vannak jelenleg a
különböző branchek csúcsán.

[[_setting_up_2]]
=== Beállítás

Az objektumbejárás előkészítésének néhány jól elkülönülő szakasza van.

1. Végezd el az alapértelmezett beállítást ehhez a módhoz, és bármely másikhoz,
   amelyet meghívhatunk.
2. Nézd meg a konfigurációs fájlokban a releváns beállításokat.
3. Állítsd be a `rev_info` structot.
4. Igazítsd az inicializált `rev_info`-t az aktuális bejáráshoz.
5. Készítsd elő a `rev_info`-t a bejáráshoz.
6. Iterálj végig az objektumokon, mindegyiket feldolgozva.

[[_default_setups]]
==== Alapértelmezett beállítások

Mielőtt megvizsgálnánk a parancs viselkedését módosító konfigurációs fájlokat,
állítsd be az alapértelmezett állapotot a parancsod kapcsolóihoz vagy
opcióihoz. Ha a parancsod más Git-komponenseket is használ, kérd meg őket, hogy
ők is állítsák be a saját alapértelmezett állapotukat. Például a `git log`
kihasználja a `grep` és a `diff` funkcionalitást, ezért az `init_log_defaults()`
beállítja a saját állapotát (`decoration_style`), és megkéri a `grep`-et és a
`diff`-et, hogy inicializálják magukat a saját inicializáló függvényeik
meghívásával.

[[_configuring_from_gitconfig]]
==== Konfigurálás a `.gitconfig`-ból

Ezután meg kell néznünk a releváns konfigurációs beállításokat (vagyis azokat,
amelyek a `git config`-ból olvashatók és állíthatók). Ezt egy `repo_config()`-nak
átadott callbackkel tesszük meg; ezen a callbacken belül meghívhatod más
komponensek metódusait is, amelyeknek szükségük lehet arra, hogy elfogják
ezeket az opciókat. A callbacked minden olyan konfigurációs értékre egyszer
meghívódik, amelyről a Git tud (global, local, worktree stb.).

Az alapértelmezett értékekhez hasonlóan itt sincs még saját teendőnk; azonban
meg kell hívnunk a `git_default_config()`-ot, ha nem hívunk más, már létező
config-callbacket.

Adj egy új függvényt a `builtin/walken.c`-hez.
Be kell includeolnunk a `config.h` headert is:

----
#include "config.h"

...

static int git_walken_config(const char *var, const char *value,
			     const struct config_context *ctx, void *cb)
{
	/*
	 * For now, we don't have any custom configuration, so fall back to
	 * the default config.
	 */
	return git_default_config(var, value, ctx, cb);
}
----

Ügyelj rá, hogy meghívd vele a `repo_config()`-ot a `cmd_walken()`-edben:

----
int cmd_walken(int argc, const char **argv, const char *prefix, struct repository *repo)
{
	...

	repo_config(repo, git_walken_config, NULL);

	...
}
----

[[_setting_up_rev_info]]
==== A `rev_info` beállítása

Most, hogy összegyűjtöttük a külső konfigurációt és opciókat, itt az ideje
inicializálni a `rev_info` objektumot, amelyet a bejárás elvégzéséhez fogunk
használni. Ezt jellemzően a `repo_init_revisions()` meghívásával tesszük meg,
átadva neki a célzott repository-t, valamint a `cmd_walken` `prefix`
argumentumát és a `rev_info` structodat.

Vedd fel a `struct rev_info`-t és a `repo_init_revisions()` hívást.
Be kell includeolnunk a `revision.h` headert is:

----
#include "revision.h"

...

int cmd_walken(int argc, const char **argv, const char *prefix, struct repository *repo)
{
	/* This can go wherever you like in your declarations.*/
	struct rev_info rev;
	...

	/* This should go after the repo_config() call. */
	repo_init_revisions(repo, &rev, prefix);

	...
}
----

[[_tweaking_rev_info_for_the_walk]]
==== A `rev_info` finomhangolása a bejáráshoz

Már közel vagyunk, de még nem vagyunk egészen készen az indulásra. Most, hogy a
`rev` inicializálva van, módosíthatjuk, hogy megfeleljen az igényeinknek. Ezt
az áttekinthetőség kedvéért általában egy segédfüggvényen belül tesszük meg,
úgyhogy vegyünk fel egyet:

----
static void final_rev_info_setup(struct rev_info *rev)
{
	/*
	 * We want to mimic the appearance of `git log --oneline`, so let's
	 * force oneline format.
	 */
	get_commit_format("oneline", rev);

	/* Start our object walk at HEAD. */
	add_head_to_pending(rev);
}
----

[NOTE]
====
Ahelyett, hogy a rövidített `add_head_to_pending()`-et használnád, tehetnél
valami ilyesmit is:

----
	struct setup_revision_opt opt;

	memset(&opt, 0, sizeof(opt));
	opt.def = "HEAD";
	opt.revarg_opt = REVARG_COMMITTISH;
	setup_revisions(argc, argv, rev, &opt);
----

A `setup_revision_opt` használata finomabb kontrollt ad a bejárásod
kezdőpontja felett.
====

Ezután hívjuk meg a `final_rev_info_setup()`-ot a `repo_init_revisions()`
hívása után:

----
int cmd_walken(int argc, const char **argv, const char *prefix, struct repository *repo)
{
	...

	final_rev_info_setup(&rev);

	...
}
----

Később még további argumentumokat is hozzá szeretnénk majd adni a
`final_rev_info_setup()`-hoz. De egyelőre ennyi elég nekünk.

[[_preparing_rev_info_for_the_walk]]
==== A `rev_info` előkészítése a bejáráshoz

Most, hogy a `rev` teljesen inicializálva és konfigurálva van, van még egy
beállítási lépésünk, mielőtt nekilátnánk. Ezt megtehetjük egy segédfüggvényben,
amely előkészíti a `rev_info`-t a bejáráshoz, és el is végzi magát a bejárást.
Kezdjük a segédfüggvényt a `prepare_revision_walk()` hívásával, amely hibát
tud visszaadni anélkül, hogy önmaga elhalna (die):

----
static void walken_commit_walk(struct rev_info *rev)
{
	if (prepare_revision_walk(rev))
		die(_("revision walk setup failed"));
}
----

NOTE: A `die()` a `stderr`-re ír, és kilépteti a programot. Mivel a `stderr`-re
fog írni, valószínűleg egy ember fogja látni, ezért lokalizálni fogjuk.

[[_performing_the_walk]]
==== A bejárás elvégzése!

Végre! Készen állunk, hogy elkezdjük magát a bejárást. Most már láthatjuk,
hogy a `rev_info` iterátorként is használható; a bejárás következő elemére a
`get_revision()` ismételt hívásával lépünk tovább. Vedd fel a felsorolt
változódeklarációkat a tetejére, és a bejáró ciklust a
`prepare_revision_walk()` hívás alá, a `walken_commit_walk()`-ödön belül:

----
#include "pretty.h"

...

static void walken_commit_walk(struct rev_info *rev)
{
	struct commit *commit;
	struct strbuf prettybuf = STRBUF_INIT;

	...

	while ((commit = get_revision(rev))) {
		strbuf_reset(&prettybuf);
		pp_commit_easy(CMIT_FMT_ONELINE, commit, &prettybuf);
		puts(prettybuf.buf);
	}
	strbuf_release(&prettybuf);
}
----

NOTE: A `puts()` egy `char*`-ot ír a `stdout`-ra. Mivel a parancsnak ezt a
részét gépi feldolgozásra szánjuk, közvetlenül a stdout-ra küldjük.

Próbáld ki.

----
$ make
$ ./bin-wrappers/git walken
----

Látnod kell a tree-d történetében szereplő összes commit tárgysorát,
sorrendben, egészen a kezdeti commitig, "Initial revision of "git", the
information manager from hell" tárggyal bezárólag. Gratulálunk! Megírtad az
első revízióbejárásodat. Ha kíváncsi vagy, kedvedre kipróbálhatod, hogy
kinyomtass néhány további mezőt is az egyes commitokból; nézd meg a
`commit.h`-ban elérhető függvényeket.

[[_adding_a_filter]]
=== Filter hozzáadása

Ezután próbáljuk meg szűrni a látott commitokat a szerzőjük alapján. Ez
egyenértékű a `git log --author=<pattern>` futtatásával. Egy filtert a
`rev_info.grep_filter` módosításával adhatunk hozzá, amely egy `struct
grep_opt`.

Először egy kis előkészület. Add hozzá a `grep_config()`-ot a
`git_walken_config()`-hoz:

----
static int git_walken_config(const char *var, const char *value,
			     const struct config_context *ctx, void *cb)
{
	grep_config(var, value, ctx, cb);
	return git_default_config(var, value, ctx, cb);
}
----

Ezután módosíthatjuk a `grep_filter`-t. Ezt a `grep.h`-ban található kényelmi
függvényekkel tesszük meg. A poén kedvéért csak azokra a commitokra szűrünk,
amelyek szerzője `gmail.com` email-címet használ - ez egy nem túl pontos
tippünk arra, hogy ki dolgozhat a Git-en hobbiként. Mivel a szerzőt ellenőrizzük,
ami a header egy meghatározott sora, az `append_header_grep_pattern()`
segédfüggvényt fogjuk használni. Az `enum grep_header_field`-et használhatjuk
annak jelzésére, hogy a commit-header melyik részét szeretnénk keresni.

A `final_rev_info_setup()`-ban add hozzá a filtersorodat:

----
static void final_rev_info_setup(int argc, const char **argv,
		const char *prefix, struct rev_info *rev)
{
	...

	append_header_grep_pattern(&rev->grep_filter, GREP_HEADER_AUTHOR,
		"gmail");
	compile_grep_patterns(&rev->grep_filter);

	...
}
----

Az `append_header_grep_pattern()` hozzáadja az új "gmail" mintánkat a
`rev_info`-hoz, de ez nem fog működni, amíg le nem fordítjuk a
`compile_grep_patterns()`-szel.

NOTE: Ha a `setup_revisions()`-t használod (például ha egy `setup_revision_opt`-ot
adsz át az `add_head_to_pending()` használata helyett), nem kell meghívnod a
`compile_grep_patterns()`-t, mert a `setup_revisions()` ezt megteszi helyetted.

NOTE: Ugyanezt a filtert az `append_grep_pattern()` segédfüggvénnyel is
hozzáadhatnánk, ha akarnánk, de az `append_header_grep_pattern()` helyettünk
adja hozzá az `enum grep_context`-et és az `enum grep_pat_token`-t.

[[_changing_the_order]]
=== A sorrend megváltoztatása

Néhány módon megváltoztathatjuk a commitok sorrendjét a revízióbejárás során.
Először is használhatjuk az `enum rev_sort_order`-t, hogy néhány tipikus
rendezés közül válasszunk.

A `topo_order` ugyanaz, mint a `git log --topo-order`: elkerüljük, hogy egy
szülőt megjelenítsünk azelőtt, hogy az összes gyermeke megjelent volna, és
elkerüljük, hogy különböző történeti ágakhoz tartozó commitokat keverjünk. (A
`git help log` `--topo-order`-ról szóló szakaszában egy nagyon szemléletes
diagram illusztrálja ezt.)

Nézzük meg, mi történik, ha a `REV_SORT_BY_AUTHOR_DATE` helyett a
`REV_SORT_BY_COMMIT_DATE`-tel futtatunk. Add hozzá a következőt:

----
static void final_rev_info_setup(int argc, const char **argv,
		const char *prefix, struct rev_info *rev)
{
	...

	rev->topo_order = 1;
	rev->sort_order = REV_SORT_BY_COMMIT_DATE;

	...
}
----

Írassuk ki ezt egy fájlba, hogy könnyen diffelhessük a szerzői dátum szerint
rendezett bejárással.

----
$ make
$ ./bin-wrappers/git walken > commit-date.txt
----

Ezután rendezzünk szerzői dátum szerint, és futtassuk le újra.

----
static void final_rev_info_setup(int argc, const char **argv,
		const char *prefix, struct rev_info *rev)
{
	...

	rev->topo_order = 1;
	rev->sort_order = REV_SORT_BY_AUTHOR_DATE;

	...
}
----

----
$ make
$ ./bin-wrappers/git walken > author-date.txt
----

Végül hasonlítsuk össze a kettőt. Objektumnevek vagy dátumok nélkül ez kicsit
kevésbé hasznos, de reméljük, így is átjön a lényeg.

----
$ diff -u commit-date.txt author-date.txt
----

Ez a megjelenítés azt mutatja, hogy a commitok megírásuk után átrendezhetők,
például a `git rebase`-szel.

Próbáljunk ki még egy átrendezést a commitokon. A `rev_info` egy `reverse`
flaget tesz elérhetővé. Állítsd be ezt a flaget valahol a
`final_rev_info_setup()`-on belül:

----
static void final_rev_info_setup(int argc, const char **argv, const char *prefix,
		struct rev_info *rev)
{
	...

	rev->reverse = 1;

	...
}
----

Futtasd le újra a bejárásodat, és figyeld meg a sorrend különbségét. (Ha
eltávolítod a grep mintát, az utolsó commitnak, amit ez a hívás ad, a
jelenlegi HEAD-nek kell lennie.)

[[_basic_object_walk]]
== Alap objektumbejárás

Eddig csak commitokat jártunk be. De a Git-nek ennél sokkal több
objektumtípusa van! Nézzük meg, be tudjuk-e járni _az összes_ objektumot, és
ki tudunk-e deríteni némi információt mindegyikről.

A munkánkat egy példára alapozhatjuk. A `git pack-objects` mindenféle
objektumot előkészít arra, hogy bitmapbe vagy packfile-ba csomagolja őket. Az
minket érdeklő munka a `builtin/pack-objects.c:get_object_list()`-ben
található; ennek a függvénynek a vizsgálata megmutatja, hogy a
teljes-objektumbejárást a `traverse_commit_list()` vagy a
`traverse_commit_list_filtered()` végzi. Ez a két függvény a
`list-objects.c`-ben található; a forrás vizsgálata megmutatja, hogy a nevük
ellenére ezek a függvények mindenféle objektumot bejárnak. Nézzük meg a
`traverse_commit_list()` argumentumait.

- `struct rev_info *revs`: Ez a bejáráshoz használt `rev_info`. Ha a `filter`
  mezője nem `NULL`, akkor a `filter` információt tartalmaz arról, hogyan
  kell szűrni az objektumlistát.
- `show_commit_fn show_commit`: Egy callback, amelyet az egyes commit
  objektumok kezelésére fogunk használni.
- `show_object_fn show_object`: Egy callback, amelyet az egyes nem-commit
  objektumok (vagyis minden blob, tree vagy tag) kezelésére fogunk használni.
- `void *show_data`: Egy kontextuspuffer, amelyet sorban átadunk a
  `show_commit`-nak és a `show_object`-nek.

Emellett a `traverse_commit_list_filtered()`-nek van egy további paramétere:

- `struct oidset *omitted`: Azon objektumazonosítók láncolt listája, amelyeket
  a megadott filter kihagyott.

Úgy tűnik, ezek a metódusok az általunk megadott callbackeket használják,
ahelyett hogy nekünk kellene ismételten meghívnunk őket. Menő! Adjuk hozzá
először a callbackeket.

Ennek az oktatóanyagnak a kedvéért egyszerűen csak nyilvántartjuk, hogy az
egyes objektumtípusokból hányat találunk. Vedd fel a következő
nyilvántartó változókat fájl-hatókörben a `builtin/walken.c`-ben:

----
static int commit_count;
static int tag_count;
static int blob_count;
static int tree_count;
----

A commitokat egy másik callback kezeli, mint a többi objektumot; kezdjük
azzal:

----
static void walken_show_commit(struct commit *cmt, void *buf)
{
	commit_count++;
}
----

A `cmt` argumentum meglehetősen magától értetődő. De érdemes megemlíteni, hogy
a `buf` argumentum valójában az a kontextuspuffer, amelyet átadhatunk a
bejáró hívásoknak - ez a `show_data`, amelyet az imént említettünk.

Mivel megvan a `struct commit` objektumunk, megnézhetjük ugyanazokat a
részeket, amelyeket a korábbi, csak commitokat bejáró walkunkban is
megnéztünk. Ennek az oktatóanyagnak a kedvéért azonban most csak megnöveljük
a commit-számlálót, és megyünk tovább.

A nem-commitokhoz tartozó callback kicsit más, mivel meg kell vizsgálnunk,
milyen típusú objektummal van dolgunk:

----
static void walken_show_object(struct object *obj, const char *str, void *buf)
{
	switch (obj->type) {
	case OBJ_TREE:
		tree_count++;
		break;
	case OBJ_BLOB:
		blob_count++;
		break;
	case OBJ_TAG:
		tag_count++;
		break;
	case OBJ_COMMIT:
		BUG("unexpected commit object in walken_show_object\n");
	default:
		BUG("unexpected object type %s in walken_show_object\n",
			type_name(obj->type));
	}
}
----

Ismét: az `obj` meglehetősen magától értetődő, és kitalálhatjuk, hogy a `buf`
ugyanaz a kontextusmutató, amelyet a `walken_show_commit()` is kap: a
`traverse_commit_list()` és a `traverse_commit_list_filtered()` `show_data`
argumentuma. Végül a `str` az objektum nevét tartalmazza, ami valami olyasmi
lesz, mint `foo.txt` (blob), `bar/baz` (tree), vagy `v1.2.3` (tag).

Hogy biztosak lehessünk benne, hogy nem számoljuk kétszer a commitokat,
beleveszünk egy kis panaszkodást arra az esetre, ha egy commit objektum a
nem-commit callbackünkön keresztül jutna el hozzánk; panaszkodunk akkor is, ha
érvénytelen objektumtípust látunk. Mivel ennek a két esetnek elérhetetlennek
kellene lennie, és csak a Git kódbázisának egy szemantikai változása esetén
változna, a `BUG()`-gal panaszkodunk - ez egy jelzés a fejlesztő felé, hogy az
általa végzett módosítás nem szándékolt következményeket okozott, és a kódbázis
többi részét frissíteni kell, hogy megértse ezt a változást. A `BUG()`-ot nem a
nyilvánosságnak szánjuk látni, ezért nincs lokalizálva.

A fő objektumbejárás-implementációnk lényegesen eltér a commit-bejárás
implementációnktól, ezért készítsünk egy új függvényt az objektumbejárás
elvégzésére. Itt is elvégezhetjük az összes objektumra vonatkozó beállítást,
külön tartva azt a csak commitokat bejáró walkokra vonatkozó beállítástól.

Azzal kezdjük, hogy a `struct rev_info`-ban engedélyezzük az összes
objektumtípust. Bekapcsoljuk a `tree_blobs_in_commit_order`-t is, ami azt
jelenti, hogy közvetlenül az egyes commitok megtalálása után bejárjuk a commit
tree-jét és mindent, amire az mutat, ahelyett hogy megvárnánk a végét, és a
teljes commit-történet feltárása után járnánk be az összes tree-t. A megfelelő
beállítások konfigurálása után készen állunk a `prepare_revision_walk()`
meghívására.

----
static void walken_object_walk(struct rev_info *rev)
{
	rev->tree_objects = 1;
	rev->blob_objects = 1;
	rev->tag_objects = 1;
	rev->tree_blobs_in_commit_order = 1;

	if (prepare_revision_walk(rev))
		die(_("revision walk setup failed"));

	commit_count = 0;
	tag_count = 0;
	blob_count = 0;
	tree_count = 0;
----

Kezdjük azzal, hogy csak a szűretlen bejárást hívjuk meg, és jelentjük a
számlálóinkat. Fejezd be a `walken_object_walk()` implementációját.
Be kell includeolnunk a `list-objects.h` headert is.

----
#include "list-objects.h"

...

	traverse_commit_list(rev, walken_show_commit, walken_show_object, NULL);

	printf("commits %d\nblobs %d\ntags %d\ntrees %d\n", commit_count,
		blob_count, tag_count, tree_count);
}
----

NOTE: Ezt a kimenetet gépi feldolgozásra szánjuk. Ezért nem küldjük a
`trace_printf()`-nek, és nem lokalizáljuk - a szkripteknek biztosra kell
venniük, hogy a formázás pontosan olyan lesz, amilyen itt látható. Ha ezt a
kimenetet emberek olvasására szánnánk, akkor a `_()`-vel kellene
lokalizálnunk.

Végül megkérjük a `cmd_walken()`-t, hogy inkább az objektumbejárást használja.
A parancssori opciók megbeszélése kívül esik ennek az oktatóanyagnak a
hatókörén, ezért csak hardkódolunk egy ágat, amelyet fordítási időben
tudunk módosítani. Ott, ahol a `final_rev_info_setup()`-ot és a
`walken_commit_walk()`-öt hívod, ágazz el helyette így:

----
	if (1) {
		add_head_to_pending(&rev);
		walken_object_walk(&rev);
	} else {
		final_rev_info_setup(argc, argv, prefix, &rev);
		walken_commit_walk(&rev);
	}
----

NOTE: Az egyszerűség kedvéért elkerültük az összes, a `final_rev_info_setup()`-ban
alkalmazott filtert és rendezést, és egyszerűen csak a `HEAD`-et adtuk hozzá a
pending queue-nkhoz. Ha szeretnéd, természetesen használhatod a korábban
hozzáadott filtereket is, ha a `final_rev_info_setup()`-ot kiveszed a
feltételből, és eltávolítod az `add_head_to_pending()` hívást.

Most kipróbálhatjuk a parancsunk futtatását! Ennek érezhetően tovább kell
tartania, mint a commit-bejárásnak, de a kimenet vizsgálata megmutatja, miért.
A kimenetednek hasonlónak kell lennie ehhez a példához, de eltérő
számlálóértékekkel:

----
Object walk completed. Found 55733 commits, 100274 blobs, 0 tags, and 104210 trees.
----

Ennek van értelme. Több tree-nk van, mint commitunk, mert a Git projektnek
sok, esetenként változó alkönyvtára van, plusz commitonként legalább egy
tree. Nincs tagünk, mert egy commiton (`HEAD`) kezdtük, és bár a tagek
mutathatnak commitokra, a commitok nem mutathatnak tagekre.

NOTE: Neked eltérő számlálóértékeid lesznek, amikor te magad futtatod ezt! Az
objektumok száma a Git projekttel együtt növekszik.

[[_adding_a_filter_2]]
=== Filter hozzáadása

Van néhány filter, amelyet alkalmazhatunk az objektumbejárásra, ezek fel
vannak sorolva a `Documentation/rev-list-options.adoc`-ban. Ezek a filterek
jellemzően olyan műveleteknél hasznosak, mint a packfile-ok létrehozása vagy a
partial clone végrehajtása. A `list-objects-filter-options.h`-ban vannak
definiálva. Ennek az oktatóanyagnak a céljaira a "tree:1" filtert fogjuk
használni, amely miatt a bejárás kihagy minden olyan tree-t és blobot, amelyre
nem hivatkozik közvetlenül olyan commit, amely elérhető a `pending`-ben lévő
commitból a bejárás kezdetekor. (A `pending` azoknak az objektumoknak a
listája, amelyeket a bejárás során be kell járni; segít megérteni, ha egy
szélességi fabejárásra gondolsz. A mi esetünkben ez azt jelenti, hogy
kihagyjuk azokat a tree-ket és blobokat, amelyekre nem hivatkozik közvetlenül
a `HEAD` vagy a `HEAD` története, mert a bejárást csak a `HEAD`-del kezdjük a
`pending` listában.)

Egyelőre nem fogjuk nyomon követni a kihagyott objektumokat, ezért ezeket a
paramétereket `NULL`-lal helyettesítjük. Az egyszerűség kedvéért felveszünk
egy egyszerű, fordítási időben eldöntött ágat arra, hogy használjuk-e a
filterünket vagy sem. Illeszd a `traverse_commit_list()`-et hívó sor elé a
következőt, amely emlékeztet minket arra, milyen fajta bejárást végeztünk el
az imént:

----
	if (0) {
		/* Unfiltered: */
		trace_printf(_("Unfiltered object walk.\n"));
	} else {
		trace_printf(
			_("Filtered object walk with filterspec 'tree:1'.\n"));

		parse_list_objects_filter(&rev->filter, "tree:1");
	}
	traverse_commit_list(rev, walken_show_commit,
			     walken_show_object, NULL);
----

A `rev->filter` mezőt általában közvetlenül egy parancssori argumentumból
építjük fel, ezért a modul egy egyszerű módot biztosít arra, hogy egyet egy
stringből építsünk fel. Bár most nem fogadunk el felhasználói bemenetet, még
mindig felépíthetünk egyet egy hardkódolt stringgel a
`parse_list_objects_filter()` használatával.

A "tree:1" filterspeccel azt várjuk, hogy _csak_ az egyes commitok
gyökér-tree-jét lássuk; ezért a tree objektumok számának kisebbnek vagy
egyenlőnek kell lennie a commitok számánál. (Példaként arra, hogy ez miért
igaz: a `git commit --revert` ugyanarra a tree objektumra mutat, mint a
nagyszülője.)

[[_counting_omitted_objects]]
=== A kihagyott objektumok megszámolása

Arra is képesek vagyunk, hogy felsoroljuk az összes olyan objektumot, amelyet
egy filter kihagyott, ahogy a `git log --filter=<spec> --filter-print-omitted`
esetében. Ehhez cseréld le a `traverse_commit_list()`-et
`traverse_commit_list_filtered()`-re, amely képes feltölteni egy `omitted`
listát. Ennek a szűrt objektumlistának a lekérése azonban teljesítményromlást
okozhat, mert ebben az esetben az objektumok szűrése ellenére az összes
elérhető objektum esetleg jóval nagyobb halmazát kell feldolgozni ahhoz, hogy
feltöltsük azt a listát.

Először add hozzá a `struct oidset`-et és a hozzá kapcsolódó elemeket, amelyeket
az iterálásához fogunk használni:

----
#include "oidset.h"

...

static void walken_object_walk(
	...

	struct oidset omitted;
	struct oidset_iter oit;
	struct object_id *oid = NULL;
	int omitted_count = 0;
	oidset_init(&omitted, 0);

	...
----

Cseréld le a `traverse_commit_list()` hívást
`traverse_commit_list_filtered()`-re, és add át a fent definiált és
inicializált `omitted` oidsetre mutató pointert:

----
	...

		traverse_commit_list_filtered(rev,
			walken_show_commit, walken_show_object, NULL, &omitted);

	...
----

Ezután, a bejárásod után, az `oidset` bejárása meglehetősen egyszerű. Számold
meg az összes benne lévő objektumot, és módosítsd a kiíró utasítást:

----
	/* Count the omitted objects. */
	oidset_iter_init(&omitted, &oit);

	while ((oid = oidset_iter_next(&oit)))
		omitted_count++;

	printf("commits %d\nblobs %d\ntags %d\ntrees %d\nomitted %d\n",
		commit_count, blob_count, tag_count, tree_count, omitted_count);
----

Ha lefuttatod a bejárásodat a filterrel és anélkül is, azt kell tapasztalnod,
hogy a teljes objektumszám mindkét esetben megegyezik. A `walken` alparancs
egyes meghívásait is időzítheted, `omitted` átadásával és anélkül is, hogy
magad is meggyőződj az összes kihagyott objektum nyomon követésének
futásidőre gyakorolt hatásáról.

[[_changing_the_order_2]]
=== A sorrend megváltoztatása

Végül mutassuk meg, hogy nemcsak a commitok bejárását, hanem az összes
objektum bejárását is átrendezhetjük. Először tegyük bőbeszédűbbé a
kezelőinket - módosítsd a `walken_show_commit()`-ot és a
`walken_show_object()`-et úgy, hogy menet közben kiírják az objektumot:

----
#include "hex.h"

...

static void walken_show_commit(struct commit *cmt, void *buf)
{
	trace_printf("commit: %s\n", oid_to_hex(&cmt->object.oid));
	commit_count++;
}

static void walken_show_object(struct object *obj, const char *str, void *buf)
{
	trace_printf("%s: %s\n", type_name(obj->type), oid_to_hex(&obj->oid));

	...
}
----

NOTE: Mivel ezt a kimenetet közvetlenül emberként fogjuk megvizsgálni, itt a
`trace_printf()`-et fogjuk használni. Ráadásul, mivel ez a változtatás jelentős
számú kiírt sort eredményez, a `trace_printf()` használatával könnyen
elnémíthatjuk ezeket a sorokat újrafordítás nélkül is.

(Hagyd meg a számlálónövelő logikát.)

Csak ezzel a változtatással futtasd le újra (de spórolj magadnak egy kis
scrollbackot):

----
$ GIT_TRACE=1 ./bin-wrappers/git walken 2>&1 | head -n 10
----

Nézd meg a legfelső commitot a `git show`-val és a kiírt objektumazonosítót;
ennek meg kell egyeznie a `git show HEAD` kimenetével.

Most változtassunk meg egy beállítást a `struct rev_info`-nkon a
`walken_object_walk()`-ön belül. Keresd meg, hol változtatod a `rev` egyéb
beállításait, mint a `rev->tree_objects` és a `rev->tree_blobs_in_commit_order`,
és add hozzá a `reverse` beállítást a végéhez:

----
	...

	rev->tree_objects = 1;
	rev->blob_objects = 1;
	rev->tag_objects = 1;
	rev->tree_blobs_in_commit_order = 1;
	rev->reverse = 1;

	...
----

Most futtasd le újra, de ezúttal ragadjuk meg az objektumok utolsó néhányát az
első néhány helyett:

----
$ make
$ GIT_TRACE=1 ./bin-wrappers/git walken 2>&1 | tail -n 10
----

Az utolsóként adott commit objektumnak ugyanazzal az OID-dal kell rendelkeznie,
mint amelyiket korábban a tetején láttunk, és a `git show <oid>` futtatásának
ezzel az OID-dal ismét ugyanazokat az eredményeket kell adnia, mint a `git show
HEAD`. Továbbá, ha újra lefuttatod és megvizsgálod az első tíz sort (a `tail`
helyett `head`-del, ahogy a `reverse` beállítás alkalmazása előtt tettük),
azt kell látnod, hogy most az elsőként kiírt commit a kezdeti commit,
`e83c5163`.

[[_wrapping_up]]
== Összefoglalás

Nézzük át. Ebben az oktatóanyagban:

- Felépítettünk egy commit-bejárást a semmiből
- Engedélyeztünk egy grep filtert ehhez a commit-bejáráshoz
- Megváltoztattuk ennek a szűrt commit-bejárásnak a rendezési sorrendjét
- Felépítettünk egy objektumbejárást (tagek, commitok, tree-k és blobok) a
  semmiből
- Megtanultuk, hogyan adjunk filterspecet egy objektumbejáráshoz
- Megváltoztattuk a szűrt objektumbejárás megjelenítési sorrendjét
