Felsorolja azokat a commitokat, amelyek a megadott commit(ok)ból a
`parent` linkek követésével elérhetők, de kizárja azokat a
commitokat, amelyek a '{caret}'-tel eléjük írt commit(ok)ból
érhetők el. A kimenet alapértelmezés szerint fordított időrendi
sorrendben jelenik meg.

Ezt egy halmazműveletként képzelheted el. A parancssorban megadott
commitok bármelyikéből elérhető commitok egy halmazt alkotnak, majd
a '{caret}'-tel eléjük írtak bármelyikéből elérhető commitok
kivonásra kerülnek ebből a halmazból. A megmaradó commitok jelennek
meg a parancs kimenetében. Az eredmény további korlátozására
különböző egyéb opciók és útvonal-paraméterek használhatók.

Így a következő parancs:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list foo bar ^baz
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log foo bar ^baz
-----------------------------------------------------------------------
endif::git-log[]

azt jelenti, hogy "sorolj fel minden olyan commitot, amely elérhető a
'foo'-ból vagy a 'bar'-ból, de nem a 'baz'-ból".

Egy speciális jelölés, a "`<commit1>..<commit2>`" rövidítésként
használható a "`^<commit1> <commit2>`" helyett. Például a következők
bármelyike felcserélhetően használható:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list origin..HEAD
$ git rev-list HEAD ^origin
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log origin..HEAD
$ git log HEAD ^origin
-----------------------------------------------------------------------
endif::git-log[]

Egy másik speciális jelölés a "`<commit1>...<commit2>`", amely
merge-eknél hasznos. Az eredményül kapott commit-halmaz a két operandus
szimmetrikus differenciája. A következő két parancs egyenértékű:

ifdef::git-rev-list[]
-----------------------------------------------------------------------
$ git rev-list A B --not $(git merge-base --all A B)
$ git rev-list A...B
-----------------------------------------------------------------------
endif::git-rev-list[]
ifdef::git-log[]
-----------------------------------------------------------------------
$ git log A B --not $(git merge-base --all A B)
$ git log A...B
-----------------------------------------------------------------------
endif::git-log[]
