Patchek átnézése a Git projektben
=================================

[[_introduction]]
Bevezetés
---------
A Git fejlesztői közössége egyének széles körben elosztott, sokszínű,
folyamatosan változó csoportja. A Git levelezőlistán keresztüli aszinkron
kommunikáció egyedi kihívásokat jelent a patchek átnézésekor vagy
megvitatásakor. Ez a dokumentum néhány vezérelvet és hasznos eszközt
tartalmaz, amelyekkel az átnézéseidet egyszerre teheted hatékonyabbá saját
magad számára és eredményesebbé más contributorok számára.

Vedd figyelembe, hogy az itteni ajánlások egyike sem kötelező, és
semmilyen módon nem feltétele a Git közösségben való részvételnek.
Erőforrásként szolgálnak a contributori készségeid kiegészítésére.

[[_principles]]
Alapelvek
---------

[[_selecting_patch_es_to_review]]
Átnézendő patch(ek) kiválasztása
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ha átnézésre váró patchsorozatot keresel, kezdd a legutóbbi "What's
cooking in git.git" e-mail megnézésével
(https://lore.kernel.org/git/xmqqilm1yp3m.fsf@gitster.g/[példa]). A "What's
cooking" e-mailek és válaszok az `s:"What's cooking"` lekérdezéssel
találhatók meg a https://lore.kernel.org/git/[`lore.kernel.org` levelezőlista-archívumban];
másik lehetőségként a "What's cooking" e-mail tartalmát a Git `todo`
branchén, a `whats-cooking.txt` fájlban követve is megtalálhatod. A "Needs
review" címkével ellátott témák és a "[New Topics]" szakaszban lévők
jellemzően azok, amelyek a legtöbbet profitálnának a további átnézésből.

A patchek kézzel is kereshetők a levelezőlista-archívumban egy olyan
lekérdezéssel, mint az `s:"PATCH" -s:"Re:"`. Ezekben az eredményekben a
szakértelmedhez vagy érdeklődésedhez kapcsolódó témák után böngészhetsz.

Ha már hozzájárultál a Githez, előfordulhat, hogy CC-be kerülsz egy másik
contributor patchsorozatában. Ezek olyan témák, ahol a szerző úgy érzi,
hogy indokolt a figyelmed. Ennek oka lehet, hogy a patchük olyasmit
változtat meg, amit korábban te írtál (így jól meg tudod ítélni, hogy az
új megközelítés működik-e vagy sem), vagy hogy megvan a szakértelmed egy
kivételesen hasznos átnézés nyújtásához. Nincs előírás ezeknek a
patcheknek az átnézésére, de a nyílt forráskódú együttműködés szellemében
erősen fontold meg, hogy megteszed.

[[_reviewing_patches]]
Patchek átnézése
~~~~~~~~~~~~~~~~
Bár minden contributor a maga módján áll hozzá a patchek átnézéséhez, íme
néhány általános tanács, hogy az átnézéseidet a lehető legvilágosabbá és
leghasznosabbá tedd. A tanácsok két durva kategóriába vannak sorolva:
magas szintű átnézési útmutatás, és konkrét tippek a patchekkel való
munkához a levelezőlistán.

[[_high_level_guidance]]
==== Magas szintű útmutatás
- Ne feledd, hogy a patch diffjében lévő kódváltoztatás mellett a
  commit-üzenetek tartalmát is nézd át helyesség és érthetőség
  szempontjából. Egy patch commit-üzenetének pontosan és teljesen el kell
  magyaráznia a diffben végzett kódváltoztatást.

- A tesztlefedettség átnézése az átnézések egy fontos – de könnyen
  figyelmen kívül hagyható – összetevője. Egy patch változtatásait
  fedhetik meglévő tesztek, vagy új tesztek kerülhetnek be az új
  viselkedés gyakorlására. Egy patch vagy sorozat lokális checkoutolása
  lehetővé teszi, hogy kézzel módosítsd az új és a meglévő tesztek sorait
  a várt sikeres/sikertelen viselkedés ellenőrzésére. Ezt az információt
  felhasználhatod a megfelelő lefedettség ellenőrzésére, vagy hogy további
  teszteket javasolj, amelyeket a szerző hozzáadhatna.

- Amikor ajánlást fogalmazol meg, a lehető legvilágosabban jelezd, hogy
  "blokkolónak" tekinted-e (a kód hibás lenne, vagy más módon rosszabbá
  válna, ha egy problémát nem javítanak) vagy "nem blokkolónak" (a patch
  jobbá tehető az ajánlás megfogadásával, de a sorozat elfogadása nem
  igényli). A nem blokkoló ajánlások különösen kétértelműek lehetnek,
  amikor egy sorozathoz kapcsolódnak – de annak hatókörén kívül esnek
  ("nice-to-have"-ek), vagy amikor csak stilisztikai különbségeket
  jelentenek a szerző és az átnéző között.

- Amikor egy problémához fűzöl megjegyzést, próbálj javaslatokat is
  mellékelni arra, hogyan javíthatná ki a szerző. Ez nemcsak abban segíti
  a szerzőt, hogy megértse és kijavítsa a problémát, hanem elmélyíti és
  javítja a téma megértését is nálad.

- Az átnézéseknek nem kell kizárólag problémákra rámutatniuk.  A pozitív
  átnézések azt jelzik, hogy nem csak a patchek eredeti szerzőjének
  fontos az a probléma, amelyet a patchek megcéloznak, és erősen
  bátorítottak.

- Ne habozz pozitív átnézést adni egy munkatársad sorozatára.  Ha a
  pozitív átnézésed jól van megírva, nem fog úgy tűnni, mintha ti ketten
  vállalati érdeket képviselnétek egy olyan sorozaton, amely egyébként
  nem érdekli a közösség többi tagját, és rájuk erőltetnétek azt.

- Úgy írj pozitív átnézést, hogy mások megérthessék, miért támogatod a
  célt, a megközelítést és a patchek által választott implementációt.
  Mindenképp mutasd meg, hogy alaposan elolvastad a sorozatot, és eléggé
  megértetted a problémakört ahhoz, hogy meg tudd mondani, a patchek jól
  vannak megírva.  Nyugodtan "gondolkodj hangosan" az átnézésedben: írd
  le, hogyan olvastad és értetted meg egy patch egy összetett szakaszát,
  tegyél fel kérdést valamiről, ami összezavart, mutass rá valamire,
  amit kivételesen jól megírtnak találtál, stb.

- Különösen a felemelő visszajelzés sokat tesz azért, hogy a
  contributorokat aktívabb részvételre bátorítsa a Git közösségben.

[[_performing_your_review]]
==== Az átnézésed elvégzése
- Az átnézési megjegyzéseidet patchenként add meg egy egyszerű szöveges
  "Reply-All" e-mailben az érintett patchre. A megjegyzéseket a szövegbe
  ágyazva, közvetlenül az érintett szakasz(ok) alatt kell megtenni.

- Előfordulhat, hogy a patch diffjében biztosított korlátozott
  kontextus néha nem elegendő egy alapos átnézéshez. Ilyen esetekben a
  patcheket a lokális tree-dben nézheted át úgy, hogy vagy alkalmazod a
  patcheket a linkgit:git-am[1]-mel, vagy checkoutolod a hozzá tartozó
  branchet a https://github.com/gitster/git-ről, ha a sorozat már ott
  van követve.

- A nagy, bonyolult patch-diffek néha elkerülhetetlenek, például amikor
  meglévő kódot refaktorálnak. Ha egy ilyen patchet nehéznek találsz
  értelmezni, próbáld meg a `--color-moved` és/vagy a
  `--ignore-space-change` opcióval előállított diffet átnézni.

- Ha egy patch hosszú, bátorítunk, hogy töröld belőle az e-mail-válaszban
  azokat a részeket, amelyek nem kapcsolódnak az átnézésedhez. Ügyelj rá,
  hogy elég kontextust hagyj ahhoz, hogy az olvasók megértsék a
  megjegyzéseidet!

- Ha nem tudsz egy sorozat teljes átnézését egyszerre elvégezni, fontold
  meg, hogy tudatod a szerzővel (a listán vagy azon kívül), hogy
  tervezed-e, és ha igen, mikor átnézni a sorozat többi részét.

[[_completing_a_review]]
Egy átnézés befejezése
~~~~~~~~~~~~~~~~~~~~~~
Miután egy sorozat minden patchét átnézték, a szerző (és/vagy más
contributorok) megvitathatják az átnézés(eke)t. Ez eredményezheti azt,
hogy nem alkalmaznak változtatásokat, vagy a szerző elküldi a patch(ek)
egy új verzióját.

Miután egy sorozatot a te vagy mások átnézésére válaszul újragöngyölnek,
mindenképp nézd át újra a frissítéseket. Ha elégedett vagy a
patchsorozat állapotával, explicit módon jelezd a jóváhagyásodat
(jellemzően a legfrissebb verzió kísérőlevelére adott válasszal).
Opcionálisan tudathatod a szerzővel, hogy hozzáadhatnak egy
"Reviewed-by: <te>" trailert, ha a sorozat egy későbbi iterációjában szó
szerint újra beküldik az átnézett patchet.

Végül a későbbi "What's cooking" e-mailek explicit módon rákérdezhetnek,
hogy egy átnézett téma készen áll-e a `next` branchbe való merge-elésre
(jellemzően "Will merge to \'next\'?" megfogalmazással). Segíthetsz a
maintainernek és a szerzőnek azzal, hogy röviden leírod a saját (és ha
van, mások) átnézésének állapotát, beleértve az érintett szál(ak)ra
mutató linkeket.

[[_terminology]]
Terminológia
------------
nit: ::
	Egy kis problémát jelöl, amelyet ki kellene javítani, például egy
	elgépelést vagy a feltételek elrendezésének eltérését egy `if()`
	utasításban.

aside: ::
optional: ::
non-blocking: ::
	Az olvasó számára jelzi, hogy a következő megjegyzés nem
	blokkolhatja a patch vagy a sorozat elfogadását. Ezek jellemzően a
	kódszervezéshez és -stílushoz kapcsolódó ajánlások, vagy a szóban
	forgó patchhez kapcsolódó, de annak hatókörén kívül eső témákon való
	tűnődések.

s/<before>/<after>/::
	Rövidítés arra, hogy "azt írtad, hogy <before>, de szerintem
	<after>-t akartál", általában elírásokra vagy más elgépelésekre.
	A szintaxis a Unix-eszközökben (mint az `ed`, `sed`, `vim` és `perl`)
	gyakran megtalálható "substitute" parancsra utal.

cover letter::
	Egy több patchből álló sorozat "Patch 0"-ja. Ez az e-mail leírja a
	patchsorozat magas szintű szándékát és szerkezetét a Git levelezőlista
	olvasói számára. Itt adja meg a szerző a következő verziók changelog-
	jegyzeteit és range-diffjét is.
+
Egy patchből álló beküldéseknél a cover letter tartalmát jellemzően nem
külön e-mailként küldik el. Ehelyett a patch commit-üzenetének vége (a
`---` után) és a diff eleje közé kerül beszúrásra.

#leftoverbits::
  Szerző vagy átnéző használja olyan funkciók vagy javasolt
  változtatások leírására, amelyek egy adott patch vagy sorozat hatókörén
  kívül esnek, de a vita kedvéért relevánsak a témához.

[[_see_also]]
Lásd még
--------
link:MyFirstContribution.html[MyFirstContribution]
