SPECIFYING REVISIONS
--------------------

Egy '<rev>' revíziós paraméter jellemzően, de nem feltétlenül, egy
commitobjektumot nevez meg. Az úgynevezett 'kiterjesztett SHA-1'
szintaxist használja. Íme az objektumnevek leírásának különféle
módjai. A lista vége felé felsoroltak egy commitban lévő fákat és
blobokat neveznek meg.

NOTE: Ez a dokumentum a git által látott „nyers" szintaxist mutatja. A
shell és más felhasználói felületek további idézőjelezést igényelhetnek
a speciális karakterek védelméhez és a szódarabolás elkerüléséhez.

'<sha1>', e.g. 'dae86e1950b1277e545cee180551750029cfe735', 'dae86e'::
  A teljes SHA-1 objektumnév (40 bájtos hexadecimális sztring), vagy egy
  kezdő részsztring, amely egyedi a repository-n belül.
  Pl. a dae86e1950b1277e545cee180551750029cfe735 és a dae86e egyaránt
  ugyanazt a commitobjektumot nevezi meg, ha nincs más objektum a
  repository-dban, amelynek az objektumneve dae86e-vel kezdődik.

'<describeOutput>', e.g. 'v1.7.4.2-679-g3bee7fb'::
  A `git describe` kimenete; azaz egy legközelebbi tag, opcionálisan egy
  kötőjellel és egy commitszámmal, majd egy kötőjellel, egy 'g'-vel és
  egy rövidített objektumnévvel követve.

'<refname>', e.g. 'master', 'heads/master', 'refs/heads/master'::
  Egy szimbolikus refnév. Pl. a 'master' jellemzően a
  'refs/heads/master' által hivatkozott commitobjektumot jelenti. Ha
  történetesen mind 'heads/master'-ed, mind 'tags/master'-ed van,
  explicit módon megmondhatod, hogy 'heads/master', hogy közöld a
  Gittel, melyikre gondolsz. Ha nem egyértelmű, egy '<refname>' úgy
  válik egyértelművé, hogy a következő szabályok közül az első
  illeszkedést veszi:
+
  . Ha a '$GIT_DIR/<refname>' létezik, arra gondolsz (ez általában csak a
    `HEAD`, `FETCH_HEAD`, `ORIG_HEAD`, `MERGE_HEAD`, `REBASE_HEAD`,
    `REVERT_HEAD`, `CHERRY_PICK_HEAD`, `BISECT_HEAD` és `AUTO_MERGE`
    esetén hasznos);

  . egyébként 'refs/<refname>', ha létezik;

  . egyébként 'refs/tags/<refname>', ha létezik;

  . egyébként 'refs/heads/<refname>', ha létezik;

  . egyébként 'refs/remotes/<refname>', ha létezik;

  . egyébként 'refs/remotes/<refname>/HEAD', ha létezik.

+
  `HEAD`:::
    azt a commitot nevezi meg, amelyre a working tree-beli
    változásaidat alapoztad.
  `FETCH_HEAD`:::
    azt a branchet rögzíti, amelyet egy remote repository-ból
    fetcheltél a legutóbbi `git fetch` híváskor.
  `ORIG_HEAD`:::
    azok a parancsok hozzák létre, amelyek drasztikus módon mozgatják a
    `HEAD`-edet (`git am`, `git merge`, `git rebase`, `git reset`), hogy
    rögzítsék a `HEAD` pozícióját a műveletük előtt, hogy könnyen
    visszaállíthasd a branch csúcsát a futtatásuk előtti állapotra.
  `MERGE_HEAD`:::
    azo(ka)t a commit(oka)t rögzíti, amelye(ke)t a branchedbe
    merge-elsz, amikor lefuttatod a `git merge`-et.
  `REBASE_HEAD`:::
    rebase közben azt a commitot rögzíti, amelynél a művelet éppen
    megállt, akár konfliktusok, akár egy interaktív rebase-beli `edit`
    parancs miatt.
  `REVERT_HEAD`:::
    azt a commitot rögzíti, amelyet revertelsz, amikor lefuttatod a
    `git revert`-et.
  `CHERRY_PICK_HEAD`:::
    azt a commitot rögzíti, amelyet cherry-pickelsz, amikor lefuttatod a
    `git cherry-pick`-et.
  `BISECT_HEAD`:::
    az aktuálisan tesztelendő commitot rögzíti, amikor lefuttatod a
    `git bisect --no-checkout`-ot.
  `AUTO_MERGE`:::
    egy olyan treeobjektumot rögzít, amely annak az állapotnak felel
    meg, amelyet az 'ort' merge-stratégia a working tree-be írt, amikor
    egy merge művelet konfliktusokat eredményezett.

+
Vedd figyelembe, hogy a fenti 'refs/*' esetek bármelyike jöhet akár a
`$GIT_DIR/refs` könyvtárból, akár a `$GIT_DIR/packed-refs` fájlból. Bár a
refnév kódolása nincs meghatározva, az UTF-8 az előnyben részesített,
mivel egyes kimenetfeldolgozások UTF-8-as refneveket feltételezhetnek.

'@'::
  Az '@' önmagában a `HEAD` rövidítése.

'[<refname>]@{<date>}', e.g. 'master@\{yesterday\}', 'HEAD@{5 minutes ago}'::
  Egy ref, amelyet a '@' utótag követ egy kapcsos zárójelpárba zárt
  dátum-megadással (pl. '\{yesterday\}', '{1 month 2 weeks 3 days 1 hour 1
  second ago}' vagy '{1979-02-26 18:30:00}'), a ref egy korábbi
  időpontbeli értékét adja meg. Ez az utótag csak közvetlenül egy refnév
  után használható, és a refnek léteznie kell egy naplójának
  ('$GIT_DIR/logs/<ref>'). Vedd figyelembe, hogy ez a *helyi* refed
  állapotát keresi ki egy adott időpontban; pl. mi volt a helyi
  'master' branchedben a múlt héten. Ha bizonyos időszakokban készült
  commitokat szeretnél megnézni, lásd a `--since` és `--until`
  kapcsolót.

'<refname>@{<n>}', e.g. 'master@\{1\}'::
  Egy ref, amelyet a '@' utótag követ egy kapcsos zárójelpárba zárt
  sorszám-megadással (pl. '\{1\}', '\{15\}'), az adott ref n-edik
  korábbi értékét adja meg. Például a 'master@\{1\}' a 'master'
  közvetlenül megelőző értéke, míg a 'master@\{5\}' a 'master' 5.
  korábbi értéke. Ez az utótag csak közvetlenül egy refnév után
  használható, és a refnek léteznie kell egy naplójának
  ('$GIT_DIR/logs/<refname>').

'@{<n>}', e.g. '@\{1\}'::
  Az '@' konstrukciót üres ref-résszel is használhatod, hogy az
  aktuális branch egy reflog-bejegyzéséhez juss. Például ha a 'blabla'
  branchen vagy, akkor a '@\{1\}' ugyanazt jelenti, mint a
  'blabla@\{1\}'.

'@{-<n>}', e.g. '@{-1}'::
  A '@{-<n>}' konstrukció az aktuális előtt <n>-edikként checkoutolt
  branchet/commitot jelenti.

'[<branchname>]@\{upstream\}', e.g. 'master@\{upstream\}', '@\{u\}'::
  Egy B branch beállítható úgy, hogy egy X branchre (a
  `branch.<name>.merge`-dzsel konfigurálva) épüljön egy R remote-on (a
  `branch.<name>.remote`-tal konfigurálva). A B@{u} az R remote-ról vett
  X branchhez tartozó remote-tracking branchre hivatkozik, amely
  jellemzően a `refs/remotes/R/X`-nél található.

'[<branchname>]@\{push\}', e.g. 'master@\{push\}', '@\{push\}'::
  A '@\{push}' utótag azt a branchet jelenti, "ahová pusholnánk", ha a
  `git push` akkor futna, amikor a `branchname` van checkoutolva (vagy
  az aktuális `HEAD`, ha nincs branchname megadva). A '@\{upstream\}'-hoz
  hasonlóan azt a remote-tracking branchet jelentjük, amely az adott
  branchnek felel meg a remote-on. Ha a push célja egy URL, és pontosan
  egy konfigurált remote használja ezt az URL-t pusholásra, a '@\{push}'
  annak a remote-nak a remote-tracking branchét jelenti.
+
Íme egy példa, hogy világosabb legyen:
+
------------------------------
$ git config push.default current
$ git config remote.pushdefault myfork
$ git switch -c mybranch origin/master

$ git rev-parse --symbolic-full-name @{upstream}
refs/remotes/origin/master

$ git rev-parse --symbolic-full-name @{push}
refs/remotes/myfork/mybranch
------------------------------
+
Figyeld meg a példában, hogy egy háromszög alakú munkafolyamatot
állítottunk be, ahol az egyik helyről pull-olunk, és egy másikra
pusholunk. Egy nem háromszög alakú munkafolyamatban a '@\{push}'
ugyanaz, mint a '@\{upstream}', és nincs rá szükség.
+
Ezt az utótagot nagybetűvel írva is elfogadja, és ugyanazt jelenti, a
kis-/nagybetűtől függetlenül.

'<rev>{caret}[<n>]', e.g. 'HEAD{caret}, v1.5.1{caret}0'::
  Egy revíziós paraméter '{caret}' utótagja az adott commitobjektum első
  szülőjét jelenti. A '{caret}<n>' az <n>-edik szülőt jelenti (azaz a
  '<rev>{caret}'
  egyenértékű a '<rev>{caret}1'-gyel). Speciális szabályként a
  '<rev>{caret}0' magát a commitot jelenti, és akkor használatos, amikor
  a '<rev>' egy commitobjektumra hivatkozó tagobjektum objektumneve.

'<rev>{tilde}[<n>]', e.g. 'HEAD{tilde}, master{tilde}3'::
  Egy revíziós paraméter '{tilde}' utótagja az adott commitobjektum első
  szülőjét jelenti.
  Egy revíziós paraméter '{tilde}<n>' utótagja azt a commitobjektumot
  jelenti, amely a megnevezett commitobjektum <n>-edik generációs őse,
  csak az első szülőket követve. Azaz a '<rev>{tilde}3' egyenértékű a
  '<rev>{caret}{caret}{caret}'-tal, amely egyenértékű a
  '<rev>{caret}1{caret}1{caret}1'-gyel. Lentebb lásd ennek az alaknak a
  használatát szemléltető ábrát.

'<rev>{caret}{<type>}', e.g. 'v0.99.8{caret}\{commit\}'::
  Egy '{caret}' utótag, amelyet egy kapcsos zárójelpárba zárt
  objektumtípusnév követ, azt jelenti, hogy a '<rev>'-nél lévő
  objektumot rekurzívan dereferálni kell, amíg egy '<type>' típusú
  objektum elő nem kerül, vagy az objektum már nem dereferálható tovább
  (ez esetben hiba).
  Például ha a '<rev>' egy commit-ish, a '<rev>{caret}\{commit\}' a
  megfelelő commitobjektumot írja le.
  Hasonlóan, ha a '<rev>' egy tree-ish, a '<rev>{caret}\{tree\}' a
  megfelelő treeobjektumot írja le.
  A '<rev>{caret}0'
  a '<rev>{caret}\{commit\}' rövidítése.
+
A '<rev>{caret}\{object\}' arra használható, hogy megbizonyosodj arról,
hogy a '<rev>' egy létező objektumot nevez meg, anélkül, hogy a
'<rev>'-nek tagnek kellene lennie, és a '<rev>' dereferálása nélkül;
mivel egy tag már eleve egy objektum, egyszer sem kell dereferálni
ahhoz, hogy egy objektumhoz juss.
+
A '<rev>{caret}\{tag\}' arra használható, hogy biztosítsd, hogy a
'<rev>' egy létező tagobjektumot azonosít.

'<rev>{caret}{}', e.g. 'v0.99.8{caret}{}'::
  Egy '{caret}' utótag, amelyet egy üres kapcsos zárójelpár követ, azt
  jelenti, hogy az objektum lehet egy tag, és a taget rekurzívan
  dereferálni kell, amíg egy nem-tag objektum elő nem kerül.

'<rev>{caret}{/<text>}', e.g. 'HEAD^{/fix nasty bug}'::
  Egy revíziós paraméter '{caret}' utótagja, amelyet egy kapcsos
  zárójelpár követ, amely egy perjellel bevezetett szöveget tartalmaz,
  ugyanaz, mint a lenti ':/fix nasty bug' szintaxis, azzal a
  különbséggel, hogy a legfiatalabb illeszkedő commitot adja vissza,
  amely a '{caret}' előtti '<rev>'-ből elérhető.

':/<text>', e.g. ':/fix nasty bug'::
  Egy kettőspont, majd egy perjel, majd egy szöveg egy olyan commitot
  nevez meg, amelynek a commit-üzenete illeszkedik a megadott reguláris
  kifejezésre.
  Ez a név a legfiatalabb illeszkedő commitot adja vissza, amely bármely
  refből — beleértve a HEAD-et is — elérhető.
  A reguláris kifejezés a commit-üzenet bármely részére illeszkedhet. Egy
  sztringgel kezdődő üzenetekre illesztéshez használható pl. a ':/^foo'.
  A ':/!' speciális szekvencia az illesztett dolog módosítói számára van
  fenntartva. A ':/!-foo' negatív illesztést végez, míg a ':/!!foo' egy
  literál '!' karakterre illeszkedik, amelyet 'foo' követ. A ':/!'-jellel
  kezdődő bármely más szekvencia egyelőre fenntartott.
  A megadott szövegtől függően a shell szódarabolási szabályai további
  idézőjelezést igényelhetnek.

'<rev>:<path>', e.g. 'HEAD:README', 'master:./README'::
  Egy ':' utótag, amelyet egy útvonal követ, a kettőspont előtti rész
  által megnevezett tree-ish objektumban lévő, az adott útvonalon
  található blobot vagy fát nevezi meg.
  A './'-vel vagy '../'-vel kezdődő útvonal az aktuális munkakönyvtárhoz
  relatív.
  A megadott útvonal a working tree gyökérkönyvtárához relatívvá lesz
  konvertálva.
  Ez leginkább egy blob vagy fa címzésére hasznos egy olyan commitból
  vagy fából, amelynek ugyanolyan a fastruktúrája, mint a working
  tree-nek.

':[<n>:]<path>', e.g. ':0:README', ':README'::
  Egy kettőspont, amelyet opcionálisan egy stage-szám (0-tól 3-ig) és
  egy kettőspont követ, majd egy útvonal, egy blobobjektumot nevez meg
  az indexben az adott útvonalon. A hiányzó stage-szám (és az azt követő
  kettőspont) egy 0-s stage bejegyzést nevez meg. Merge közben az 1-es
  stage a közös ős, a 2-es stage a cél branch verziója (jellemzően az
  aktuális branch), a 3-as stage pedig a merge-elt branch verziója.

Íme egy szemléltető ábra, Jon Loeliger-től. A B és C commitcsomópont
egyaránt az A commitcsomópont szülője. A szülőcommitok balról jobbra
vannak sorrendezve.

........................................
G   H   I   J
 \ /     \ /
  D   E   F
   \  |  / \
    \ | /   |
     \|/    |
      B     C
       \   /
        \ /
         A
........................................

    A =      = A^0
    B = A^   = A^1     = A~1
    C =      = A^2
    D = A^^  = A^1^1   = A~2
    E = B^2  = A^^2
    F = B^3  = A^^3
    G = A^^^ = A^1^1^1 = A~3
    H = D^2  = B^^2    = A^^^2  = A~2^2
    I = F^   = B^3^    = A^^3^
    J = F^2  = B^3^2   = A^^3^2


SPECIFYING RANGES
-----------------

A történetet bejáró parancsok, mint a `git log`, egy commithalmazon
működnek, nem csupán egyetlen commiton.

Ezeknél a parancsoknál egyetlen revízió megadása az előző szakaszban
leírt jelöléssel az adott commitból `elérhető` commitok halmazát
jelenti.

Több revízió megadása a megadott commitok bármelyikéből elérhető
commitok halmazát jelenti.

Egy commit elérhető halmaza maga a commit és az ősei láncolatában lévő
commitok.

Több jelölés is van egy összefüggő commithalmaz (amit
„revíziótartománynak" neveznek) megadására, ezeket lentebb
szemléltetjük.


[[_commit_exclusions]]
Commit-kizárások
~~~~~~~~~~~~~~~~

'{caret}<rev>' (caret) Notation::
 Egy commitból elérhető commitok kizárásához egy '{caret}' előtag-jelölés
 használatos. Pl. a '{caret}r1 r2' azokat a commitokat jelenti, amelyek
 az 'r2'-ből elérhetők, de kizárja azokat, amelyek az 'r1'-ből elérhetők
 (azaz az 'r1'-et és az őseit).

[[_dotted_range_notations]]
Pontos tartományjelölések
~~~~~~~~~~~~~~~~~~~~~~~~~

The '..' (two-dot) Range Notation::
 A '{caret}r1 r2' halmazművelet olyan gyakran előfordul, hogy van rá
 rövidítés. Ha van két commitod, 'r1' és 'r2' (a fenti SPECIFYING
 REVISIONS-ben leírt szintaxis szerint megnevezve), a '{caret}r1 r2'-vel
 kérheted azokat a commitokat, amelyek az r2-ből elérhetők, kizárva
 azokat, amelyek az r1-ből elérhetők, és ez 'r1..r2'-ként írható.

The '\...' (three-dot) Symmetric Difference Notation::
 Egy hasonló jelölést, az 'r1\...r2'-t az 'r1' és 'r2' szimmetrikus
 különbségének nevezik, és így definiálják:
 'r1 r2 --not $(git merge-base --all r1 r2)'.
 Ez azoknak a commitoknak a halmaza, amelyek az 'r1' (bal oldal) vagy az
 'r2' (jobb oldal) valamelyikéből elérhetők, de nem mindkettőből.

Ebben a két rövidítés-jelölésben az egyik véget elhagyhatod, és hagyhatod,
hogy alapból HEAD legyen. Például az 'origin..' az 'origin..HEAD'
rövidítése, és azt kérdezi: "Mit csináltam azóta, hogy leágaztam az
origin branchről?" Hasonlóan a '..origin' a 'HEAD..origin' rövidítése, és
azt kérdezi: "Mit csinált az origin azóta, hogy leágaztam róla?" Vedd
figyelembe, hogy a '..' azt jelentené, hogy 'HEAD..HEAD', ami egy üres
tartomány, amely a HEAD-ből egyszerre elérhető és elérhetetlen.

Léteznek olyan parancsok, amelyeket kifejezetten két különálló
tartomány fogadására terveztek (pl. a "git range-diff R1 R2" két
tartomány összehasonlítására), de ezek kivételek. Ha másképp nincs
jelezve, minden "git" parancs, amely egy commithalmazon működik,
egyetlen revíziótartományon dolgozik. Más szóval két "kétpontos
tartományjelölés" egymás mellé írása, pl.

    $ git log A..B C..D

a legtöbb parancsnál *nem* ad meg két revíziótartományt. Ehelyett egyetlen
összefüggő commithalmazt nevez meg, azaz azokat, amelyek a B-ből vagy a
D-ből elérhetők, de sem az A-ból, sem a C-ből nem érhetők el. Egy ilyen
lineáris történetben:

    ---A---B---o---o---C---D

mivel az A és a B elérhető a C-ből, az e két pontos tartomány által
megadott revíziótartomány egyetlen commit, a D.


[[_other_rev_parent_shorthand_notations]]
Egyéb <rev>{caret} szülő-rövidítésjelölések
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Létezik három másik rövidítés, amelyek különösen merge commitoknál
hasznosak, egy olyan halmaz megnevezésére, amelyet egy commit és a
szülőcommitjai alkotnak.

Az 'r1{caret}@' jelölés az 'r1' összes szülőjét jelenti.

Az 'r1{caret}!' jelölés magában foglalja az 'r1' commitot, de kizárja az
összes szülőjét. Önmagában ez a jelölés az egyetlen 'r1' commitot
jelöli.

A '<rev>{caret}-[<n>]' jelölés magában foglalja a '<rev>'-et, de kizárja
az <n>-edik szülőt (azaz a '<rev>{caret}<n>..<rev>' rövidítése), '<n>' =
1-gyel, ha nincs megadva. Ez jellemzően merge commitoknál hasznos, ahol
egyszerűen átadhatod a '<commit>{caret}-'-t, hogy megkapd az összes
commitot abban a branchben, amelyet a '<commit>' merge commitban
merge-eltek (magát a '<commit>'-ot is beleértve).

Míg a '<rev>{caret}<n>' egyetlen commitszülő megadásáról szólt, ez a
három jelölés a szülőit is figyelembe veszi. Például mondhatod, hogy
'HEAD{caret}2{caret}@', viszont nem mondhatod, hogy 'HEAD{caret}@{caret}2'.

[[_revision_range_summary]]
Revíziótartomány-összefoglaló
-----------------------------

'<rev>'::
	Beleveszi azokat a commitokat, amelyek a <rev>-ből elérhetők (azaz
	a <rev>-et és az őseit).

'{caret}<rev>'::
	Kizárja azokat a commitokat, amelyek a <rev>-ből elérhetők (azaz a
	<rev>-et és az őseit).

'<rev1>..<rev2>'::
	Beleveszi azokat a commitokat, amelyek a <rev2>-ből elérhetők, de
	kizárja azokat, amelyek a <rev1>-ből elérhetők. Ha akár a <rev1>,
	akár a <rev2> el van hagyva, alapból `HEAD`.

'<rev1>\...<rev2>'::
	Beleveszi azokat a commitokat, amelyek a <rev1> vagy a <rev2>
	valamelyikéből elérhetők, de kizárja azokat, amelyek mindkettőből
	elérhetők. Ha akár a <rev1>, akár a <rev2> el van hagyva, alapból
	`HEAD`.

'<rev>{caret}@', e.g. 'HEAD{caret}@'::
  Egy '{caret}' utótag, amelyet egy kukac követ, ugyanaz, mint a '<rev>'
  összes szülőjének felsorolása (azaz belevesz mindent, ami a szülőiből
  elérhető, de magát a commitot nem).

'<rev>{caret}!', e.g. 'HEAD{caret}!'::
  Egy '{caret}' utótag, amelyet egy felkiáltójel követ, ugyanaz, mint a
  '<rev>' commit és az összes szülője megadása '{caret}' előtaggal, hogy
  kizárja őket (és az őseiket).

'<rev>{caret}-<n>', e.g. 'HEAD{caret}-, HEAD{caret}-2'::
	Egyenértékű a '<rev>{caret}<n>..<rev>'-vel, '<n>' = 1-gyel, ha nincs
	megadva.

Íme néhány példa a fenti Loeliger-ábra használatával, ahol a jelölés
kifejtésének és kiválasztásának minden lépése gondosan ki van írva:

....
   Args   Expanded arguments    Selected commits
   D                            G H D
   D F                          G H I J D F
   ^G D                         H D
   ^D B                         E I J F B
   ^D B C                       E I J F B C
   C                            I J F C
   B..C   = ^B C                C
   B...C  = B ^F C              G H D E B C
   B^-    = B^..B
	  = ^B^1 B              E I J F B
   C^@    = C^1
	  = F                   I J F
   B^@    = B^1 B^2 B^3
	  = D E F               D G H E F I J
   C^!    = C ^C^@
	  = C ^C^1
	  = C ^F                C
   B^!    = B ^B^@
	  = B ^B^1 ^B^2 ^B^3
	  = B ^D ^E ^F          B
   F^! D  = F ^I ^J D           G H D F
....
