scalar(1)
=========

NAME
----
scalar - Eszköz nagy Git repositoryk kezelésére

SYNOPSIS
--------
[verse]
scalar clone [--single-branch] [--branch <main-branch>] [--full-clone]
	[--[no-]src] [--[no-]tags] [--[no-]maintenance] <url> [<enlistment>]
scalar list
scalar register [--[no-]maintenance] [<enlistment>]
scalar unregister [<enlistment>]
scalar run ( all | config | commit-graph | fetch | loose-objects | pack-files ) [<enlistment>]
scalar reconfigure [--maintenance=(enable|disable|keep)] [ --all | <enlistment> ]
scalar diagnose [<enlistment>]
scalar delete <enlistment>

DESCRIPTION
-----------

A Scalar egy repository-kezelő eszköz, amely a Gitet nagy repositorykban való
használatra optimalizálja. A Scalar úgy javítja a teljesítményt, hogy fejlett
Git beállításokat konfigurál, a repositorykat a háttérben karbantartja, és
segít csökkenteni a hálózaton átküldött adatok mennyiségét.

A Scalar egyik fontos fogalma az enlistment: ez a projekt legfelső szintű
könyvtára. Általában tartalmazza a `src/` alkönyvtárt, amely egy Git
worktree. Ez ösztönzi a nyomon követett fájlok (a `src/`-en belül) és a
nyomon nem követett fájlok, például a build artifactok (a `src/`-en kívül)
elkülönítését. Amikor egy meglévő, `src`-től eltérő nevű Git worktree-t
regisztrálsz a Scalarral, az enlistment azonos lesz a worktree-vel.

A `scalar` parancs különféle alparancsokat valósít meg, és az alparancstól
függően eltérő opciókat. A `clone`, a `list` és a `reconfigure --all`
kivételével minden alparancs elvárja, hogy egy enlistmentben fusson.

A következő opciók az alparancs _előtt_ adhatók meg:

-C <directory>::
	Az alparancs futtatása előtt megváltoztatja a munkakönyvtárat. Ez az
	opció a linkgit:git[1] azonos opcióját utánozza.

-c <key>=<value>::
	A megadott alparancs futtatásának idejére beállítja ezt a beállítást.
	Ez az opció a linkgit:git[1] azonos opcióját utánozza.

COMMANDS
--------

[[_clone]]
Klónozás
~~~~~~~~

clone [<options>] <url> [<enlistment>]::
	Klónozza a megadott repositoryt, hasonlóan a linkgit:git-clone[1]-hoz.
	Alapértelmezés szerint csak commit és tree objektumok klónozódnak. A
	befejezés után a worktree a `<enlistment>/src` helyen található.
+
A sparse-checkout funkció engedélyezve van (kivéve, ha a `--full-clone`-nal
fut), és az egyetlen jelen lévő fájlok a legfelső szintű könyvtárban lévők.
A `git sparse-checkout set` paranccsal bővítheted a látni kívánt könyvtárak
halmazát, vagy a `git sparse-checkout disable`-lel az összes fájlra bővítheted
(további részletekért lásd linkgit:git-sparse-checkout[1]). A
sparse-checkouton kívüli alkönyvtárakat a `git ls-tree HEAD[:<directory>]`
használatával fedezheted fel.

-b <name>::
--branch <name>::
	Ahelyett, hogy a klónozott repository HEAD-je által mutatott branchet
	checkoutolná, a `<name>` branchet checkoutolja.

--single-branch::
--no-single-branch::
	Csak az egyetlen branch csúcsához vezető történetet klónozza, amelyet
	vagy a `--branch` opció ad meg, vagy amelyre a remote elsődleges
	branchének `HEAD`-je mutat.
+
Az eredményül kapott repositoryba való további fetchek csak annak a
branchnek a remote-tracking branchét frissítik, amelyhez ezt az opciót a
kezdeti klónozáshoz használták. Ha a remote-on lévő HEAD nem mutatott
egyetlen branchre sem, amikor a `--single-branch` klónozás történt, nem jön
létre remote-tracking branch.

--src::
--no-src::
	Alapértelmezés szerint a `scalar clone` a klónozott repositoryt egy
	`<entlistment>/src` könyvtárba helyezi. A `--no-src` használatával a
	klónozott repositoryt közvetlenül a `<enlistment>` könyvtárba helyezi.

--tags::
--no-tags::
	Alapértelmezés szerint a `scalar clone` letölti a remote által
	hirdetett tag objektumokat, és a jövőbeli `git fetch` parancsok is ezt
	teszik. A `--no-tags` használatával elkerülheted a tagek letöltését a
	`scalar clone`-ban, és úgy konfigurálhatod a repositoryt, hogy a
	jövőben elkerülje a tagek letöltését. A `--no-tags`-szal való klónozás
	utáni tagletöltéshez futtasd a `git fetch --tags`-et.

--full-clone::
--no-full-clone::
	Alapértelmezés szerint sparse-checkout inicializálódik. Ez a
	viselkedés a `--full-clone`-nal kikapcsolható.

--maintenance::
--no-maintenance::
	Alapértelmezés szerint a `scalar clone` úgy konfigurálja az
	enlistmentet, hogy a Git háttérkarbantartási funkcióját használja. A
	`--no-maintenance` használatával kihagyhatod ezt a konfigurációt.

[[_list]]
Listázás
~~~~~~~~

list::
	Felsorolja a Scalar által jelenleg regisztrált enlistmenteket. Ezt az
	alparancsot nem kell enlistmenten belül futtatni.

[[_register]]
Regisztrálás
~~~~~~~~~~~~

register [<enlistment>]::
	Hozzáadja az enlistment repositoryját a regisztrált repositoryk
	listájához, és elindítja a háttérkarbantartást. Ha a `<enlistment>`
	nincs megadva, akkor az aktuális munkakönyvtárhoz tartozó enlistment
	kerül regisztrálásra.
+
Megjegyzés: amikor ezt az alparancsot egy `src/` nevű worktree-ben hívják
meg, a szülőkönyvtára számít a Scalar enlistmentnek. Ha a worktree _nem_
`src/` nevű, akkor maga számít a Scalar enlistmentnek.

--maintenance::
--no-maintenance::
	Alapértelmezés szerint a `scalar register` úgy konfigurálja az
	enlistmentet, hogy a Git háttérkarbantartási funkcióját használja. A
	`--no-maintenance` használatával kihagyhatod ezt a konfigurációt. Ez
	nem tiltja le azt a karbantartást, amely már más módon engedélyezve
	lehet.

[[_unregister]]
Kiregisztrálás
~~~~~~~~~~~~~~

unregister [<enlistment>]::
	Eltávolítja a megadott repositoryt a Scalarral regisztrált
	repositoryk listájából, és leállítja az ütemezett
	háttérkarbantartást.

[[_run]]
Futtatás
~~~~~~~~

scalar run ( all | config | commit-graph | fetch | loose-objects | pack-files ) [<enlistment>]::
	Lefuttatja a megadott karbantartási feladatot (vagy az összeset, ha az
	`all` volt megadva). Az `all` és a `config` kivételével ez az
	alparancs egyszerűen átadja a vezérlést a linkgit:git-maintenance[1]-nek
	(a `fetch`-et `prefetch`-re, a `pack-files`-t `incremental-repack`-re
	képezve).
+
Ezek a feladatok automatikusan lefutnak az ütemezett karbantartás
részeként, amint a repositoryt regisztrálják a Scalarral. Ezért nem kellene
szükségesnek lennie ennek az alparancsnak a kézi futtatására.
+
A `config` feladat Scalar-specifikus, és beállítja mindazokat a határozott
alapértelmezéseket, amelyektől a Git hatékonyabban működik nagy
repositorykkal. Mivel ez a feladat a `scalar clone` részeként automatikusan
lefut, ennek a feladatnak a kifejezett meghívására ritkán van szükség.

[[_reconfigure]]
Újrakonfigurálás
~~~~~~~~~~~~~~~~

Egy Scalar-frissítés után, vagy amikor egy Scalar enlistment konfigurációja
valahogy megsérült vagy tévedésből megváltozott, ez az alparancs lehetővé
teszi az enlistment újrakonfigurálását.

--all::
	Amikor a `--all` meg van adva, újrakonfigurálja az összes, a Scalarral
	jelenleg a `scalar.repo` config kulccsal regisztrált enlistmentet.
	Használd ezt az opciót minden frissítés után a legújabb funkciók
	eléréséhez.

--maintenance=(enable|disable|keep)::
	Alapértelmezés szerint a Scalar úgy konfigurálja az enlistmentet, hogy
	a Git háttérkarbantartási funkcióját használja; ez ugyanaz, mint az
	`enable` érték használata ehhez az opcióhoz. A `disable` értéket
	használva minden vizsgált enlistmentet eltávolít a
	háttérkarbantartásból.
	A `keep' használatával érintetlenül hagyja e repositoryk
	háttérkarbantartási konfigurációját.

[[_diagnose]]
Diagnosztizálás
~~~~~~~~~~~~~~~

diagnose [<enlistment>]::
    A Scalarral kapcsolatos problémák jelentésekor gyakran hasznos megadni
    az ezzel a paranccsal összegyűjtött információt, beleértve a naplókat és
    bizonyos statisztikákat, amelyek az aktuális enlistment adatalakját
    írják le.
+
Ennek a parancsnak a kimenete egy `.zip` fájl, amely a `src` könyvtárban lévő
worktree melletti könyvtárba íródik.

[[_delete]]
Törlés
~~~~~~

delete <enlistment>::
	Ez az alparancs lehetővé teszi egy meglévő Scalar enlistment törlését a
	lokális fájlrendszeredből, kiregisztrálva a repositoryt.

RECOMMENDED CONFIG VALUES
-------------------------

Mind a `scalar clone`, mind a `scalar register` részeként bizonyos Git config
értékek beállításra kerülnek a nagy repositorykra vagy a többplatformos
támogatásra való optimalizálás érdekében. Ezek az opciók az új Git
verziókban a nagy repositorykra vonatkozó legjobb ismert tanács szerint
frissülnek, és a felhasználók a `scalar reconfigure [--all]` futtatásával
megkaphatják a legújabb ajánlásokat.

Ez a szakasz a legújabb verzióban beállított config értékek indoklásait
sorolja fel.

am.keepCR=true::
	Ez a beállítás fontos a Windows és nem Windows platformok közötti
	többplatformos fejlesztéshez, és a kocsivissza (`\r`) karakterek
	megtartásához bizonyos munkafolyamatokban.

commitGraph.changedPaths=true::
	Ez a beállítás segít a szerializált commit-graphot kiszámító
	háttérkarbantartási lépéseknek abban, hogy megváltozott-útvonalú Bloom
	szűrőket is tároljanak. Ez felgyorsítja a fájltörténet-parancsokat, és
	lehetővé teszi, hogy a felhasználók automatikusan hasznot húzzanak
	belőle előtér-parancs futtatása nélkül.

commitGraph.generationVersion=1::
	Bár teljesítménybeli okokból a 2-es a preferált verzió, azoknak a
	meglévő felhasználóknak, akiknek alapértelmezés szerint az 1-es verzió
	volt, különös figyelemre lesz szükségük a 2-es verzióra való
	frissítéskor. Ez a jövőben valószínűleg változni fog, ahogy a
	frissítési folyamat megszilárdul.

core.autoCRLF=false::
	Ez eltávolítja a worktree-fájlok azon átalakítását, amely CRLF
	sorvégeket ad hozzá, amikor csak LF sorvégek léteznek. Ezt
	teljesítménybeli okokból távolítottuk el. Azoknak a repositoryknak,
	amelyek CRLF sorvégekkel törődő eszközöket használnak, helyette a
	szükséges fájlokat azokkal a sorvégekkel kell commitolniuk.

core.logAllRefUpdates=true::
	Ez engedélyezi a reflogot minden branchen. Bár ez teljesítménybeli
	költség a nagy repositoryknak, gyakran fontos adatforrás a
	felhasználóknak ahhoz, hogy kikerüljenek rossz helyzetekből, vagy
	szakértőktől kérjenek segítséget.

core.safeCRLF=false::
	A `core.autoCRLF=false`-hoz hasonlóan ez letiltja azokat az
	ellenőrzéseket, amelyek arra vonatkoznak, hogy a CRLF konverzió
	visszafordítható-e. Ez teljesítménybeli javulás, de veszélyes lehet, ha
	a felhasználó újra engedélyezi a `core.autoCRLF`-et.

credential.https://dev.azure.com.useHttpPath=true::
	Ez a beállítás csak az Azure DevOps webes URL-jeihez engedélyezi a
	`credential.useHttpPath` funkciót. Ez fontos azoknak a
	felhasználóknak, akik több szervezettel, így több credential tokennel
	kommunikálnak azzal a szolgáltatással.

feature.experimental=false::
	Ez letiltja az e feature config alá csoportosított „kísérleti"
	optimalizációkat. Az elvárás az, hogy minden értékes optimalizációt a
	Scalar config is kifejezetten beállít, és minden eltérés szándékos. A
	jelentős eltérések közé tartozik több bitmappel kapcsolatos config
	opció, amelyek a kliensközpontú Scalar repókhoz le vannak tiltva.

feature.manyFiles=false::
	Ez letiltja az e feature config alá csoportosított „sok fájl"
	optimalizációkat. Az elvárás az, hogy minden értékes optimalizációt a
	Scalar config is kifejezetten beállít, és minden eltérés szándékos.

fetch.showForcedUpdates=false::
	Ez letiltja a `git fetch` végén lévő ellenőrzést, amely értesíti a
	felhasználót, ha a ref frissítése force-update volt (olyan, ahol a
	korábbi pozíció nem érhető el a legutóbbi pozícióból). Ez az ellenőrzés
	nagy repositorykban nagyon költséges lehet, ezért le van tiltva, és egy
	tanácsüzenettel van helyettesítve. Állítsd be az
	`advice.fetchShowForcedUpdates=false`-t ennek a tanácsüzenetnek a
	letiltásához.

fetch.unpackLimit=1::
	Ez a beállítás megakadályozza, hogy a Git a packfile-okat laza
	objektumokká csomagolja ki, ahogy azok letöltődnek a szerverről. A 100-as
	alapértelmezett korlát arra szolgált, hogy megelőzze a túl sok
	packfile-ból eredő teljesítményproblémákat, de a Scalar
	háttérkarbantartással csoportosítja a packfile-okat, és
	multi-pack-indexszel fedi le őket, megszüntetve ezt a problémát.

fetch.writeCommitGraph=false::
	Ezt a config beállítást azért hozták létre, hogy segítsen a
	felhasználóknak automatikusan frissíteni a commit-graph fájljaikat,
	miközben fetcheket végeznek. Ez azonban időt vesz el az előtérben
	végzett fetchektől és pulloktól, és a Scalar helyette
	háttérkarbantartást használ erre a funkcióra.

gc.auto=0::
	Ez letiltja az automatikus szemétgyűjtést, mivel a Scalar
	háttérkarbantartással tartja jó formában a repository adatait.

gui.GCWarning=false::
	Mivel a Scalar a `gc.auto=0` beállításával letiltja a szemétgyűjtést, a
	`git-gui` eszköz elkezdhet figyelmeztetni erre a beállításra. Tiltsd le
	ezt a figyelmeztetést, mivel a Scalar háttérkarbantartási
	konfigurációja irrelevánssá teszi a figyelmeztetést.

index.skipHash=true::
	Letiltja az index tartalmának hashelését írás közben. Ez segíti a
	teljesítményt, különösen nagy index fájloknál.

index.threads=true::
	Ez azt mondja a Gitnek, hogy automatikusan észlelje, hány szálat kell
	használnia az index olvasásakor a `core.preloadIndex` alapértelmezett
	értéke miatt, amely engedélyezi a párhuzamos indexolvasást. Ez a
	kifejezett beállítás engedélyezi az `index.recordOffsetTable=true`-t
	is a párhuzamos indexolvasás felgyorsítására.

index.version=4::
	Ez az indexverzió tömörítést ad az útvonalnevekhez, jelentősen
	csökkentve az index méretét a nagy repóknál. Ez fontos
	teljesítménynövelés.

log.excludeDecoration=refs/prefetch/*::
	Mivel a Scalar az `incremental` stratégiával engedélyezi a
	háttérkarbantartást, ez a beállítás elkerüli, hogy a `git log` kimenetét
	a háttérbeli prefetch műveletek által tárolt refek szennyezzék.

merge.renames=true::
	Nagy repókban a merge-ek kiszámításakor különösen fontos az átnevezések
	észlelése, hogy maximalizáljuk egy helyesen validáló eredmény
	esélyét. Azok a felhasználók, akik lokálisan végeznek merge-eket,
	valószínűbb, hogy azért teszik, mert egy szerveroldali merge (pull
	requesten vagy hasonlón keresztül) konfliktusokat eredményezett. Bár ez
	az alapértelmezett beállítás, kifejezetten azért van beállítva, hogy
	felülírja a `diff.renames` esetleges változását, amelyet a felhasználó
	teljesítménybeli okokból állíthat be.

merge.stat=false::
	Ez letiltja a diff kimenetet egy merge kiszámítása után. Ez javítja a
	`git merge` teljesítményét a nagy repóknál, miközben csökkenti a zajos
	kimenetet.

pack.useBitmaps=false::
	Ez letiltja a packfile-okhoz csatolt `.bitmap` fájlok használatát. A
	bitmap fájlok szerveroldali használatra vannak optimalizálva, nem
	kliensoldalira. A Scalar ezt letiltja, hogy elkerüljön néhány
	teljesítményproblémát, amely akkor fordulhat elő, ha egy felhasználó
	véletlenül `.bitmap` fájlokat hoz létre.

pack.usePathWalk=true::
	Ez alapértelmezés szerint engedélyezi a `--path-walk` opciót a
	`git pack-objects`-hez. Ez felgyorsíthatja a `git push` és más
	repack-műveletek által létrehozott packfile-ok kiszámítását és
	tömörítését.

receive.autoGC=false::
	A `gc.auto`-hoz hasonlóan ez a beállítás le van tiltva a
	háttérkarbantartás javára.

status.aheadBehind=false::
	Ez letiltja az ahead/behind számítást, amely normál esetben egy
	`git status` parancs során történne. Ezt az információt a felhasználók
	gyakran figyelmen kívül hagyják, de költséges lehet kiszámítani a nagy
	repókban, amelyek naponta több ezer commitot kapnak. A számítást egy
	tanácsüzenet helyettesíti, amely az `advice.statusAheadBehind` config
	letiltásával tiltható le.

A következő beállítások a használatban lévő platformtól függően eltérnek:

core.untrackedCache=(true|false)::
	Az untracked cache funkció fontos a nagy repositoryk
	teljesítménybeli előnyeihez, de néhány bugot mutatott a Windows
	fájlrendszereken. Ezért ez más platformokra be van állítva, Windowson
	viszont le van tiltva.

http.sslBackend=schannel::
	Windowson az `openssl` backendnek van néhány problémája bizonyos típusú
	remote szolgáltatókkal és tanúsítványtípusokkal. Írd felül az
	alapértelmezett beállítást ezeknek a gyakori problémáknak az
	elkerüléséhez.


SEE ALSO
--------
linkgit:git-clone[1], linkgit:git-maintenance[1].

GIT
---
A linkgit:git[1] csomag része
