Eszközök a Git fejlesztéséhez
=============================
:sectanchors:

[[summary]]
== Összefoglaló

Ez a dokumentum tippeket, szkripteket és konfigurációs fájlokat gyűjt
össze, hogy segítse a Git kódbázisán dolgozókat a kedvenc eszközeik
használatában a Git kódolási stílusának követése mellett.

[[author]]
=== Szerző

A Git közösség.

[[table_of_contents]]
== Tartalomjegyzék

- <<vscode>>
- <<emacs>>

[[vscode]]
=== Visual Studio Code (VS Code)

A contrib/vscode/init.sh szkript olyan konfigurációs fájlokat hoz
létre, amelyek számos hasznos VS Code funkciót engedélyeznek. A
szkript használatával kapcsolatos további információkért lásd a
contrib/vscode/README.md fájlt.

[[emacs]]
=== Emacs

Ez a Linux CodingStyle dokumentumában található javaslat alapján
készült:

- A CodingGuidelines szabályainak követéséhez hasznos a következőt
elhelyezni a GIT_CHECKOUT/.dir-locals.el fájlban, feltéve, hogy
cperl-mode-ot használsz:

----
;; note the first part is useful for C editing, too
((nil . ((indent-tabs-mode . t)
	 (tab-width . 8)
	 (fill-column . 80)))
	 (cperl-mode . ((cperl-indent-level . 8)
			(cperl-extra-newline-before-brace . nil)
			(cperl-merge-trailing-else . t))))
----

Egy teljesebb beállításhoz, mivel a Git kódbázisa a Linux kernel
stílusához hasonló kódolási stílust használ, a Linux CodingStyle
dokumentumában adott tippek itt is alkalmazhatók.

==== https://www.kernel.org/doc/html/v4.10/process/coding-style.html#you-ve-made-a-mess-of-it
