SECURITY
--------
A fetch és a push protokollok nincsenek úgy tervezve, hogy megakadályozzák,
hogy az egyik fél olyan adatokat lopjon a másik repository-ból, amelyeket
nem szántak megosztásra. Ha van olyan privát adatod, amelyet egy
rosszindulatú partnertől kell megvédened, a legjobb megoldás, ha egy másik
repository-ban tárolod. Ez mind a kliensekre, mind a szerverekre vonatkozik.
Különösen a szerveren lévő névterek nem hatékonyak olvasási hozzáférés-
szabályozásra; csak olyan klienseknek szabad olvasási hozzáférést adnod
egy névtérhez, akikben megbíznál a teljes repository-hoz való olvasási
hozzáféréssel is.

Az ismert támadási vektorok a következők:

. Az áldozat "have" sorokat küld, amelyek olyan objektumok ID-jait
  hirdetik, amelyeket nem szándékozik kifejezetten megosztani, de
  felhasználhatók az átvitel optimalizálására, ha a partnernek is
  megvannak. A támadó kiválaszt egy ellopandó X objektum ID-t, és
  küld egy referenciát X-re, de nem kell elküldenie X tartalmát, mert
  az áldozatnak már megvan. Az áldozat most azt hiszi, hogy a
  támadónak megvan X-e, és később visszaküldi neki X tartalmát. (Ezt
  a támadást a legegyszerűbb egy kliensnek végrehajtania egy
  szerveren, úgy, hogy létrehoz egy referenciát X-re abban a
  névtérben, amelyhez a kliensnek hozzáférése van, majd letölti azt.
  A legvalószínűbb mód, ahogy egy szerver végrehajthatja ezt egy
  kliensen, az, hogy "merge-eli" X-et egy nyilvános branchbe, és
  reméli, hogy a felhasználó további munkát végez ezen a branchen,
  és visszaküldi a szervernek anélkül, hogy észrevenné a merge-et.)

. Az 1. ponthoz hasonlóan a támadó kiválaszt egy ellopandó X objektum
  ID-t. Az áldozat elküld egy Y objektumot, amely a támadónak már
  megvan, és a támadó hamisan azt állítja, hogy X-e megvan, Y-a
  viszont nincs, így az áldozat Y-t X-hez képesti deltaként küldi el.
  A delta felfedi a támadó számára X-nek az Y-hoz hasonló részeit.
