include::urls.adoc[]

REMOTES[[REMOTES]]
------------------

A következők egyikének a neve használható URL helyett _<repository>_
argumentumként:

* egy remote a Git konfigurációs fájlban: `$GIT_DIR/config`,
* egy fájl a `$GIT_DIR/remotes` könyvtárban, vagy
* egy fájl a `$GIT_DIR/branches` könyvtárban.

Ezek mindegyike lehetővé teszi a refspec elhagyását a parancssorból,
mert mindegyik tartalmaz egy refspecet, amelyet a git alapértelmezés
szerint használ.

[[_named_remote_in_configuration_file]]
Megnevezett remote a konfigurációs fájlban
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Megadhatod egy olyan remote nevét, amelyet korábban a
linkgit:git-remote[1], a linkgit:git-config[1] segítségével, vagy akár a
`$GIT_DIR/config` fájl kézi szerkesztésével konfiguráltál.  Ennek a
remote-nak az URL-je lesz használva a repository eléréséhez.  Ennek a
remote-nak a refspecje lesz használva alapértelmezés szerint, amikor
nem adsz meg refspecet a parancssoron.  A config fájlban a bejegyzés
így nézne ki:

------------
	[remote "<name>"]
		url = <URL>
		pushurl = <pushurl>
		push = <refspec>
		fetch = <refspec>
------------

A _<pushurl>_ csak a pushokhoz használatos. Opcionális, és
alapértelmezése a _<URL>_. Egy remote-ba való pusholás az összes
megadott pushurlt érinti, vagy az összes megadott urlt, ha nincsenek
pushurlok megadva. A fetch viszont csak az első megadott urlről
fetchel, ha több url van megadva.

[[_named_file_in_git_dir_remotes]]
Megnevezett fájl a `$GIT_DIR/remotes`-ban
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Megadhatod egy `$GIT_DIR/remotes`-ban lévő fájl nevét.  Az ebben a
fájlban lévő URL lesz használva a repository eléréséhez.  Az ebben a
fájlban lévő refspec lesz használva alapértelmezésként, amikor nem
adsz meg refspecet a parancssoron.  Ennek a fájlnak a következő
formátumúnak kell lennie:

------------
	URL: one of the above URL formats
	Push: <refspec>
	Pull: <refspec>

------------

A `Push:` sorokat a `git push`, a `Pull:` sorokat pedig a `git pull` és
a `git fetch` használja.  Több `Push:` és `Pull:` sor is megadható
további branch-leképezésekhez.

[[_named_file_in_git_dir_branches]]
Megnevezett fájl a `$GIT_DIR/branches`-ban
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Megadhatod egy `$GIT_DIR/branches`-ban lévő fájl nevét.
Az ebben a fájlban lévő URL lesz használva a repository eléréséhez.
Ennek a fájlnak a következő formátumúnak kell lennie:


------------
	<URL>#<head>
------------

A _<URL>_ kötelező; a `#<head>` opcionális.

A művelettől függően a git a következő refspecek egyikét használja, ha
nem adsz meg egyet a parancssoron.  A _<branch>_ ennek a fájlnak a neve
a `$GIT_DIR/branches`-ban, a _<head>_ alapértelmezése pedig a `master`.

A git fetch ezt használja:

------------
	refs/heads/<head>:refs/heads/<branch>
------------

A git push ezt használja:

------------
	HEAD:refs/heads/<head>
------------


[[UPSTREAM-BRANCHES]]
UPSTREAM BRANCHES
-----------------

A Git branchei opcionálisan társíthatók egy upstream remote branchhez.
A Git alapértelmezés szerint az upstream branchet használja a remote
műveletekhez, például:

* Ez az alapértelmezés az argumentum nélküli `git pull` vagy
  `git fetch` esetén.
* Ez az alapértelmezés az argumentum nélküli `git push` esetén, néhány
  kivétellel. Használhatod például a `branch.<name>.pushRemote` opciót,
  hogy más remote-ba pushold, mint amelyikből pullolsz, és
  alapértelmezés szerint a `push.default=simple` mellett az általad
  konfigurált upstream branchnek ugyanolyan nevűnek kell lennie.
* Különféle parancsok, köztük a `git checkout` és a `git status`,
  megmutatják, hány commit került az aktuális branchedre és az
  upstreamre, amióta leágaztál róla, például "Your branch and
  'origin/main' have diverged, and have 2 and 3 different commits each
  respectively".

Az upstream a `.git/config`-ban van tárolva, a "`remote`" és "`merge`"
mezőkben. Például, ha a `main` upstreamje az `origin/main`:

------------
[branch "main"]
   remote = origin
   merge = refs/heads/main
------------

Explicit módon beállíthatsz egy upstream branchet a
`git push --set-upstream <remote> <branch>` paranccsal, de a Git gyakran
automatikusan beállítja helyetted az upstreamet, például:

* Amikor klónozol egy repository-t, a Git automatikusan beállítja az
  upstreamet az alapértelmezett branchhez.
* Ha be van állítva a `push.autoSetupRemote` konfigurációs opció, a
  `git push` automatikusan beállítja az upstreamet, amikor először
  pusholsz egy branchet.
* Egy remote-tracking branch checkoutolása a `git checkout <branch>`
  paranccsal automatikusan létrehoz egy helyi branchet ezzel a névvel,
  és az upstreamet a remote branchre állítja.

[NOTE]
Az upstream brancheket néha "tracking information"-ként emlegetik,
mint a "set the branch's tracking information" kifejezésben.
